Getting Started - Learn how Free Code Camp Works translated into Braz…
freeCodeCamp/freeCodeCamp pull request #10390
Opened 2016-08-30 03:38 UTC by samanthakem

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

I did the translation of the session - Getting Started **[Learn How Free Code Camp Works]** - into Brazilian Portuguese.

2016-08-30 15:07 UTC, atjonathan commented
please get someone in the brazilian portuguese chat rooms to peer review this, thanks :+1:

2016-08-30 16:33 UTC, samanthakem commented
@atjonathan I already sent the PR link to the pt-br channel ... waiting anyone get back to me :/

2016-09-04 04:19 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Um screenshot de alguns dos nossos campistas programando Toronto.",
Uma pequena correção:
`"Um screenshot de alguns dos nossos campistas programando **em** Toronto.",`

2016-09-04 04:42 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Uma imagem de um campista codando e bebendo café no Free Code Camp.",
>  "An image of a camper at a cafe building projects on Free Code Camp."
Não seria melhor algo como: Imagem de um campista numa cafeteria construindo projetos no Free Code Camp.

2016-09-04 04:49 UTC, samanthakem commented on seed/challenges/00-getting-started/getting-started.json
> +              "Uma imagem de um campista codando e bebendo café no Free Code Camp.",
Definitivamente sim! Obrigada.

2016-09-04 04:50 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Nosso programa de estudos está dividido em 4 certificações. Estas certificações são padronizadas e instataneamente verificadas por seus clientes freelance e futuros empregadores. Assim
> ...são padronizadas e instataneamente verificadas...

typo fix: instantaneamente

2016-09-04 04:57 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Se você completar todas as 2.080 horas válidas de desafios e projetos, você ganhará nosso certificado de desenvolvimento Full Stack. Nós o(a) oferecemos prática gratuita para entrevist
typo fix 
"espeficamente"

2016-09-26 06:22 UTC, Bouncey commented
@samanthakem is there any progress with this PR?

2016-09-26 20:03 UTC, ghost requested changes
Make necessary changes commented and fix merge conflicts ❗

2016-09-28 18:31 UTC, atjonathan commented
Closing as stale. Please reopen when you've made the changes @samanthakem 😄

2016-09-28 18:31 UTC, closed without merging

2016-09-30 02:13 UTC, samanthakem commented
I don't having permissions to re-open this issue but you will find the new PR here:

https://github.com/FreeCodeCamp/FreeCodeCamp/pull/10991