[WIP] Feat(challenges): Adds the ability to test with async methods
freeCodeCamp/freeCodeCamp pull request #10711
Opened 2016-09-12 20:32 UTC by BerkeleyTrue

2016-09-14 22:49 UTC, Em-Ant commented on client/frame-runner.js
> +            __result = Rx.Obserable.of(null);
there's a typo here `Obserable`

2016-09-15 13:05 UTC, Em-Ant commented on client/frame-runner.js
> +              __result = Rx.Observable.fromNodeCallback(test);
I'm a rx newbie, but here I think you need this : 
` __result = Rx.Observable.fromNodeCallback(test)();`
I wasn't able to make the callback approach work, then I used the debugger and I noticed that `fromNodeCallback` returns a function, and this function returns the `Observable`.
Adding the `()` function call the callback approach works correctly

2016-09-15 13:06 UTC, Em-Ant requested changes
Async testing example https://hyperdev.com/#!/project/marsh-glazer

2016-09-23 14:25 UTC, BerkeleyTrue commented on client/frame-runner.js
> +              __result = Rx.Observable.fromNodeCallback(test);
Good catch!

2016-09-23 14:26 UTC, BerkeleyTrue commented
@Em-Ant I've made those fixes. If the async stuff looks good please test to make sure this does not break normal challenges. Then it is safe to merge.

2016-09-23 21:11 UTC, Em-Ant commented
@BerkeleyTrue @QuincyLarson  is importing the package.json tests right now. Then I think we will be able to run some experiments...

2016-09-28 04:24 UTC, BerkeleyTrue commented
@Em-Ant Can you release this so that it can be merged in

2016-09-28 09:45 UTC, Em-Ant commented
It should be ready this evening (tomorrow morning california time).

2016-09-28 09:48 UTC, Em-Ant approved these changes

2016-09-28 20:54 UTC, merged