Add more explanation for what escaping is
freeCodeCamp/freeCodeCamp pull request #10751
Opened 2016-09-15 21:54 UTC by daphneppl

- [✓] Your pull request targets the `staging` branch of FreeCodeCamp.
- [✓] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [✓] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [✓] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

- [✓] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

- [✓ ] Tested changes locally.
- [✓] Closes currently open issue: Closes #10337 

#### Description
A further explanation about escaping.

2016-09-16 07:15 UTC, atjonathan commented on seed/challenges/01-front-end-development-certification/basic-javascript.json
> +        "Quotes are not the only characters that can be <dfn>escaped</dfn> inside a string. There are two reasons to escaping characters. First is to allow you to use characters you might not otherwi
~~There are two reasons to escaping characters.~~ There are two reasons to use escaping characters.

2016-09-16 07:15 UTC, ghost requested changes
#### LGTM 👍

Just fix that grammar adjustment and we should be good to go!

2016-09-19 15:37 UTC, ghost approved these changes

2016-09-23 14:19 UTC, dhcodes commented
@daphneppl can you squash your commits? http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231

2016-10-01 04:11 UTC, merged