Update basic-bonfires.json
freeCodeCamp/freeCodeCamp pull request #10853
Opened 2016-09-22 12:34 UTC by ChuanfengZhang

correct a little mistake
Old say:Repeat a given string (first argument) num times (second argument). Return an empty string if num is not a positive number.
The first "num" should be "str".

2016-09-22 12:44 UTC, MarcLBryson approved these changes

2016-09-22 12:56 UTC, Bouncey commented
I don't remember seeing this as an issue.

Your edit confuses the instructions.

Could we use better/different grammar for non-native English speakers? 

Will this potentially be resolved in beta with language selection?

/cc @FreeCodeCamp/issue-moderators

2016-09-22 13:09 UTC, ChuanfengZhang commented
Sorry,I mistaken it.
@Bouncey

2016-09-22 13:13 UTC, abhisekp commented
@ChuanfengZhang @Bouncey How about the following?

> Repeat a given string *`str`* (first argument) for *`num`* times (second argument).

2016-09-22 13:18 UTC, Bouncey commented
@abhisekp 
### LGTM :+1:

2016-09-22 13:20 UTC, Bouncey commented
@ChuanfengZhang please ammend your PR

Don't forget to use `git commit --amend` so as not to add an additional commit

2016-09-22 13:23 UTC, abhisekp commented on seed/challenges/01-front-end-development-certification/basic-bonfires.json
> +        "Repeat a given string (first argument) <code>str</code> times (second argument). Return an empty string if <code>num</code> is not a positive number.",
> Repeat a given string *`str`* (first argument) for *`num`* times (second argument).

2016-09-22 13:24 UTC, abhisekp requested changes
Modify instruction.

2016-10-05 12:26 UTC, Bouncey commented
@ChuanfengZhang Do you have any progress on this?

2016-10-05 14:33 UTC, hallaathrad commented
Do we have a policy on completing the changes? I'm up for it.

2016-10-07 09:11 UTC, ChuanfengZhang commented
@Bouncey Sorry,I a starter.Is it OK now?

2016-10-07 09:39 UTC, merged

2016-10-07 09:40 UTC, Bouncey commented
## LGTM :+1: 

Don't worry about it being your first time, you did great!

Thanks for contributing :tada: