WIP: Changes to enable development environment to use containers
freeCodeCamp/freeCodeCamp pull request #10866
Opened 2016-09-23 00:31 UTC by mpaluru

This is still a WIP, hence not squashing the commits yet. Once the changes are accepted, I will recreate the PR will all the following requirements satisfied.

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

2016-09-23 06:16 UTC, BerkeleyTrue commented
Is it possible to run this without docker?

2016-09-23 06:23 UTC, BerkeleyTrue commented on gulpfile.js
> +    proxy: 'http://0.0.0.0:3000',
Why does docker require 0.0.0.0 as the IP instead of 127.0.01?

2016-09-23 06:23 UTC, BerkeleyTrue commented on Dockerfile.dev
> +FROM node:6.6.0
Can we add this files to a /docker folder?

2016-09-23 06:37 UTC, leodotcloud commented
Is it possible to run this without docker?
- Nope, we need to install docker to be able to run the containers. For linux users it's literally one short command to install docker `curl -sSL https://get.docker.com | sh -`. For OS X users, it's a .dmg install and for Windows I assume it's a single exe file installation.

Why does docker require 0.0.0.0 as the IP instead of 127.0.01?
- In the host mode, 127.0.0.1 refers to the same host, but when running inside a container it's the localhost of the container but not the host. So to be able to open the communication from the host to the container I had to change it to 0.0.0.0

Can we add these files to a /docker folder?
- `Dockerfile` can copy files into the image only from the current folder, so if we move to docker folder, we would have to refer to the files using `../` and it's not supported. The other option could be moving all the current source files inside `FreeCodeCamp/src` and leave `FreeCodeCamp/Dockerfile` at level to keep the structure clean. If you look at other projects, `Dockerfile` is usually at the top level. Another common practice if we want to keep the `Dockerfile` inside the docker folder would be to generate one bundle file for client and server, using the build script copy them to `docker/build` folder and then in the `Dockerfile` reference them as `./build/client_bundle.js` or `./build/server_bundle.js`.

2016-09-23 06:38 UTC, mpaluru commented
Is it possible to run this without docker?
- Nope, we need to install docker to be able to run the containers. For linux users it's literally one short command to install docker `curl -sSL https://get.docker.com | sh -`. For OS X users, it's a .dmg install and for Windows I assume it's a single exe file installation.

Why does docker require 0.0.0.0 as the IP instead of 127.0.01?
- In the host mode, 127.0.0.1 refers to the same host, but when running inside a container it's the localhost of the container but not the host. So to be able to open the communication from the host to the container I had to change it to 0.0.0.0

Can we add these files to a /docker folder?
- `Dockerfile` can copy files into the image only from the current folder, so if we move to docker folder, we would have to refer to the files using `../` and it's not supported. The other option could be moving all the current source files inside `FreeCodeCamp/src` and leave `FreeCodeCamp/Dockerfile` at level to keep the structure clean. If you look at other projects, `Dockerfile` is usually at the top level. Another common practice if we want to keep the `Dockerfile` inside the docker folder would be to generate one bundle file for client and server, using the build script copy them to `docker/build` folder and then in the `Dockerfile` reference them as `./build/client_bundle.js` or `./build/server_bundle.js`.

2016-09-23 06:47 UTC, BerkeleyTrue commented
> Nope, we need to install docker to be able to run the containers.

So the only way to run FCC would be in a container? 

> can copy files into the image only from the current folder, 

Then can this be a separate repo instead of in this main repo?

2016-09-23 17:18 UTC, leodotcloud commented
> So the only way to run FCC would be in a container?
The usual way of running locally will still be available. This is an extra option for people who do not want to install all the dependencies locally and for those who want to use containers.

> Then can this be a separate repo instead of in this main repo?
Yes it can be but separating it out into a separate repo is adding an extra step/complexity.
- Imagine if someone wants to rebuild the container, they would have to now clone two different repos and that starting the container with the path of the previous one, it's a little too complicated and not scriptable in a generic way.
- The general practice across the industry is to keep the Dockerfile together with the source code.

2016-09-23 17:20 UTC, mpaluru commented
> So the only way to run FCC would be in a container?

The usual way of running locally will still be available. This is an extra option for people who do not want to install all the dependencies locally and for those who want to use containers.

> Then can this be a separate repo instead of in this main repo?

Yes it can be but separating it out adds an extra step/complexity.
- Imagine if someone wants to rebuild the container, they would have to now clone two different repos and then starting the container with the volume path of the fcc repo, it's a little too complicated and not scriptable in a generic way.
- The general practice across the industry is to keep the Dockerfile together with the source code in the same repo.

2016-09-23 20:17 UTC, BerkeleyTrue commented
> everything was loading except the code editor. 

This makes it sound like the issue is not with the ip but the build dev tools. Do the rest of the static files load?

2016-09-29 17:42 UTC, mpaluru commented
| This makes it sound like the issue is not with the ip but the build dev tools. Do the rest of the static files load?

Initially I thought the same but just changing the IP makes it work without any need for rebuilding.

2016-09-29 17:49 UTC, BerkeleyTrue commented
> Initially I thought the same but just changing the IP makes it work without any need for rebuilding.

This is a possible solution, but not the cause. You must first identify the cause before you can form the proper response.

> Do the rest of the static files load?

Also, I've made significant changes to the dev server. Please rebase off the current staging

2016-10-13 16:23 UTC, ghost requested changes

2016-10-13 16:23 UTC, atjonathan commented on CONTRIBUTING.md
> +-   [Development Environment using Containers] (#development-environment-using-containers)
~~~`[Development Environment using Containers] (#development-environment-using-containers)`~~
`[Development Environment using Containers](#development-environment-using-containers)`

2016-10-13 19:36 UTC, BerkeleyTrue commented
@mpaluru ping

2016-10-14 06:48 UTC, mpaluru commented
@BerkeleyTrue Have been busy, will try to work on this over the weekend.

2016-11-03 14:22 UTC, atjonathan commented
@mpaluru, any update on this?

2016-11-03 14:32 UTC, raisedadead commented on gulpfile.js
> +    proxy: 'http://0.0.0.0:3000',
I haven't used docker, but yeah on C9, you do have to setup 0.0.0.0 as your IP. Might I suggest we make this an ENV var and add a `require('dotenv').load();` to the top.

Of course with fallbacks to localhost ?

2016-11-04 15:11 UTC, BerkeleyTrue commented
Closing as stale. Please re-open when ready.

Happy Coding

2016-11-04 15:11 UTC, closed without merging