email setting, blur button on click
freeCodeCamp/freeCodeCamp pull request #11001
Opened 2016-09-30 17:36 UTC by ivantedja

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10458

#### Description

- convert react component: "function of props" into "ES6 class descending from React.Component"
- need to use `ref` to access the DOM to call `blur()`
- need to use `ReactDOM.findDOMNode` to access DOM behind `<Button>` component

2016-09-30 19:42 UTC, BerkeleyTrue requested changes
Can this be solved with CSS? For instance, adding a class 'btn-no-focus'?

2016-09-30 19:59 UTC, QuincyLarson commented
@ivantedja I agree - a pure CSS solution with a 'btn-no-focus' class would be much simpler, and could be used throughout the app.

2016-10-01 05:52 UTC, ivantedja commented
If we are going to pure CSS way, then it means if we navigate using keyboard (tab), the button will not become green when on focus. I tried to do pure CSS way and things look good to me (see attachment). My idea was:
- when focus -> color into darkgreen, background transparent
- when active & focus -> color light gray, background darkgreen

BUT when I tested on Firefox, it is not working properly because it appears that [clicking a button => make the button into focus] only happened in Chrome (Firefox doesn't change it into focus) so my pure CSS solution was broken.

I think I'm gonna back off from this one as I've spent a lot of time on this. I learnt a lot of things though :smile:

![css](https://cloud.githubusercontent.com/assets/1907854/19012112/b86a899a-87d5-11e6-8038-4f482f4cb673.gif)

2016-10-01 05:52 UTC, closed without merging

2016-10-01 15:19 UTC, QuincyLarson commented
@ivantedja I think this would be a good question for Stack Overflow. You're right - we want for keyboard navigation to still work like normal. Still, there must be a way to accomplish both goals using CSS in a general way (without a bunch of custom JavaScript).

At the very least, we should try to create a generic piece of JavaScript that looks for a class rather than having functions specific to individual buttons. I think the Stack Overflow crowd may have some experience with this. It seems like it would be a fairly common UI use case.