Translating Getting Started - Learn What to Do If You Get Stuck secti…
freeCodeCamp/freeCodeCamp pull request #11028
Opened 2016-10-02 23:20 UTC by samanthakem

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

I translated the session - Getting Started **[Learn What to Do If You Get Stuck]** - into Brazilian Portuguese.

2016-10-03 21:51 UTC, ghost reviewed
#### LGTM :tada:

Could you get someone to approve this translation :question:

2016-10-04 17:35 UTC, lu-zen requested changes
This is my review. Nice job!

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "A palavra \"Programar é difícil.\"",
`"A **frase** \"Programar é difícil.\"",`

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Programar é difícil. Você não vai conseguir sair do lugar. Até mesmo codificadores experientes ficam presos. A chave é saber como conseguir sair do lugar.",
Substituir codificadores por **desenvolvedores** ou **programadores**.

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "A palavra \"Leva tempo para saber como ficar bom em programação\"",
`"A frase \"Leva-se tempo para ficar bom em programação\"",`

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Leva tempo para ficar bom em programação. Você não esperaria vencer um mestre de xadrez depois de jogar por apenas 3 meses. Não espere conseguir construir o próximo Facebook após progr
`"Leva**-se** tempo para ficar bom em programação. Você não esperaria vencer um mestre de xadrez depois de jogar por apenas 3 meses. Não espere conseguir construir o próximo Facebook após programar por apenas 3 meses.",`

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Continue a praticar programação todos os dias, socialize com outras pessoas que programam e você se tornará um desenvolvedor pronto para trabalhar.",
`"Continue a praticar programação todos os dias, socialize com outras pessoas que programam e você se tornará um desenvolvedor pronto para **o mercado de trabalho.**",`

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Uma imagem com o texto \"1. Leia o erro 2. Pesquisa no Google 3. Peça ajuda.\"",
`"Uma imagem com o texto \"1. Leia o erro 2. Pesquise no Google 3. Peça ajuda.\"",`

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Um gif mostrando em seguida ao link abaixo para ir a sala de bate-papo de ajuda e perguntas \"jquery não executa quando a minha página carrega\".",
`"Um gif mostrando-nos usando o link abaixo para ir a sala de bate-papo de ajuda e perguntando: \"jquery não executa quando a minha página carrega\".",`

2016-10-04 17:35 UTC, sirluis commented on seed/challenges/00-getting-started/getting-started.json
> +              "Agora você está pronto para começar a codificar. O botão \"Mapa\" no canto superior direito irá mostrar-lhe o nosso mapa de desafios. Recomendamos que você complete estes desafios de c
`"Agora você está pronto para começar a programar. O botão \"Mapa\" no canto superior direito irá mostrar-lhe o nosso mapa de desafios. Recomendamos que você complete estes desafios de cima para baixo, em um ritmo adequado. Nossa comunidade open source está constantemente melhorando os nossos desafios por isso não se surpreenda se os desafios mudarem. Não se preocupe em voltar - apenas continue seguindo em frente.",`

2016-10-04 17:47 UTC, samanthakem commented
Done @sirluis Thanks a lot / Muito obrigada!

2016-10-04 18:26 UTC, lu-zen approved these changes
Okidoki

2016-10-04 18:34 UTC, samanthakem commented
"All checks have failed"

I did `npm test` here and everything worked out :/ what's going on?

@atjonathan do you have any thoughts?

2016-10-04 20:00 UTC, atjonathan commented
@samanthakem, Don't worry, it's [an issue with our CI](https://travis-ci.org/FreeCodeCamp/FreeCodeCamp/jobs/165018923#L1271)!

#### LGTM :+1:
Thanks for contributing and happy hacktoberfest!

2016-10-04 20:02 UTC, merged