Fix Contributing Guide To Remove Need For Wiki Article
freeCodeCamp/freeCodeCamp pull request #11100
Opened 2016-10-07 19:51 UTC by adamisntdead

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #11006

#### Description
Following on from issue #11006 - this removes the need for the [http://forum.freecodecamp.com/t/how-to-fork-and-maintain-a-local-instance-of-free-code-camp/19116](http://forum.freecodecamp.com/t/how-to-fork-and-maintain-a-local-instance-of-free-code-camp/19116) Wiki page, creating just a CONTRIBUTING document.

If someone wouldn't mind looking over the new CONTRIBUTING.md file, it would be great to get a second opinion to make sure I haven't missed anything 👍

2016-10-11 08:21 UTC, salman-bhai commented
Is this issue open now?

2016-10-11 19:25 UTC, dhcodes requested changes
Found a few typos and made a couple suggestions. All in all, though it's great. Just amend the changes and I'll merge it in.

2016-10-11 19:25 UTC, dhcodes commented on CONTRIBUTING.md
> +1. Install [Git](https://git-scm.com/) or your favourite Git client.
'favourite' should be 'favorite' (US v. GB, I know)

2016-10-11 19:25 UTC, dhcodes commented on CONTRIBUTING.md
> +2. (Optional) [Setup an SSH Key](https://help.github.com/articles/generating-ssh-keys/) for GitHub.
To prevent redirect, URL should be `https://help.github.com/articles/generating-an-ssh-key/`

2016-10-11 19:25 UTC, dhcodes commented on CONTRIBUTING.md
> +1. Open a Terminal / Command Line / Bash Shell in your projects directory (_IE: `/mean/`_)
I think `IE` should be `i.e.` and our sample directory should be `/yourprojectdirectory/` instead of `/mean/` but this is opinion.

2016-10-11 19:25 UTC, dhcodes commented on CONTRIBUTING.md
>  congratulations – you're all set. Otherwise, let us know by opening a GitHub
I think `let us know by opening a Github issue...` should be changed to `let us know by asking in the [Contributors Room](https://gitter.im/FreeCodeCamp/Contributors) on Gitter. There also might be an error in the console of your browser or in Bash / Terminal / Command Line that will help identify the problem.`

2016-10-11 19:25 UTC, dhcodes commented on CONTRIBUTING.md
> +To do this, see [Rebasing](http://forum.freecodecamp.com/t/how-to-use-git-rebase/13226).
I believe this should be `To do this, see [Squashing Your Commits](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231).`

2016-10-11 19:25 UTC, dhcodes commented on CONTRIBUTING.md
> +##### (make sure to replace `yourUsername` with yout GitHub Username)
`yout` should be `your`

2016-10-11 19:25 UTC, dhcodes commented on CONTRIBUTING.md
> +Before you start working, you will need to create a seperate branch specific to the issue / feature you're working on. You will push your work to this branch.
`seperate` should be `separate`

2016-10-12 17:18 UTC, adamisntdead commented
I think I fixed them all @dhcodes

2016-10-12 17:48 UTC, dhcodes approved these changes

2016-10-12 17:49 UTC, dhcodes commented
LGTM! Thanks for making the fixes and thanks for contributing to freeCodeCamp 🎉

2016-10-12 17:49 UTC, merged