Add how we QA and how we close stale issues sections
freeCodeCamp/freeCodeCamp pull request #11190
Opened 2016-10-13 19:05 UTC by QuincyLarson

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

2016-10-13 19:11 UTC, ghost requested changes

2016-10-13 19:11 UTC, atjonathan commented on CONTRIBUTING.md
> +If you would like to apply to join our Issue Moderator team - which is a Core Team position - message @berkeleytrue with links to a 5 of your pull requests that have been accepted and 5 issues where
~~a 5 of your pull requests~~ 5 of your pull requests

2016-10-13 19:11 UTC, atjonathan commented on CONTRIBUTING.md
> +If you would like to apply to join our Issue Moderator team - which is a Core Team position - message @berkeleytrue with links to a 5 of your pull requests that have been accepted and 5 issues where
~~else through commneting~~ else through **commenting**

2016-10-13 19:11 UTC, atjonathan commented on CONTRIBUTING.md
> +- pull requests that are waiting on other pull requests
~~pull requests that are waiting on other pull requests~~ pull requests that are waiting on other pull requests **to be merged**

2016-10-13 22:21 UTC, QuincyLarson commented on CONTRIBUTING.md
> +If you would like to apply to join our Issue Moderator team - which is a Core Team position - message @berkeleytrue with links to a 5 of your pull requests that have been accepted and 5 issues where
Fixed.

2016-10-13 22:22 UTC, QuincyLarson reviewed
I've made these changes.

2016-10-14 04:36 UTC, raisedadead commented
LGTM except for the typo that @atjonathan

2016-10-14 15:56 UTC, QuincyLarson commented on CONTRIBUTING.md
> +- pull requests that are waiting on other pull requests
Fixed.

2016-10-14 15:57 UTC, QuincyLarson commented
@atjonathan I've made all your proposed changes. Please take a look and if it looks good, could you release the review and merge the PR?

2016-10-14 16:02 UTC, ghost requested changes

2016-10-14 16:02 UTC, atjonathan commented on CONTRIBUTING.md
> +If you would like to apply to join our Issue Moderator team - which is a Core Team position - message [@berkeleytrue](https://gitter.im/berkeleytrue) with links to 5 of your pull requests that have b
As @raisedadead mentioned 😉 
```diff
- else through commneting or QA'ing.
+ else through commenting or QA'ing.
```

2016-10-14 17:22 UTC, QuincyLarson commented
@atjonathan @raisedadead thanks for your patience. I fixed that final typo.

2016-10-14 17:57 UTC, ghost approved these changes

2016-10-14 17:57 UTC, atjonathan commented
@QuincyLarson, thanks 😃

2016-10-14 17:57 UTC, merged