Documentation Improvement: Checking versions of prerequsites
freeCodeCamp/freeCodeCamp pull request #11327
Opened 2016-10-22 23:09 UTC by utsab

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description
This PR improves documentation. For people who already have pre-existing versions of node and mongo, provide instructions for making sure they have the right versions. This can help prevent contributors from experiencing incompatibility errors.  

…ready have these installed on their machine.  This helps prevent contributors from using older versions that may be incompatible.

2016-10-22 23:15 UTC, systimotic reviewed
👍 I like this change. A lot of people seem to miss this and still try to run FCC with Node v4. Maybe this will help. It seems like you indented the commands a bit. Everywhere else in this document they're right up against the left edge. I think it would be a good idea to remove the indentation here. Maybe the sentence inside the brackets should be expanded to a full sentence below the code block, saying that if they're lower than the required versions, they should update.

2016-10-22 23:39 UTC, systimotic approved these changes
LGTM! 🎉

2016-10-22 23:40 UTC, utsab commented
@systimotic Thanks for the feedback.  We factored it in and added a 2nd commit to this PR.  Question: I know the best practice is to have only a single commit per PR.   Should we squash the commits somehow?  This is our first PR, so not sure how to do this.

2016-10-22 23:43 UTC, systimotic commented
Yesss please! You can [find instructions on how to squash your commits here](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231)

2016-10-23 00:24 UTC, utsab commented
Thanks @systimotic, I squashed the commits .

2016-10-23 12:15 UTC, ghost requested changes

2016-10-23 12:15 UTC, atjonathan commented on CONTRIBUTING.md
> +
Remove this line

2016-10-24 12:01 UTC, Bouncey commented on CONTRIBUTING.md
> +
I think @atjonathan meant 'Remove this extra line (53)' :+1:

2016-10-26 00:02 UTC, utsab commented
@atjonathan, I removed the extra newline as you requested.

2016-10-26 07:11 UTC, ghost approved these changes

2016-10-26 07:12 UTC, ghost approved these changes
#### LGTM 👍

Thanks for the contribution!

2016-10-26 07:13 UTC, merged