Next step unlocked persistence
freeCodeCamp/freeCodeCamp pull request #11322
Opened 2016-10-22 19:14 UTC by Bouncey

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #9952

#### Description

Utilises localStorage to persist next step unlocked.

2016-10-25 23:12 UTC, BerkeleyTrue requested changes

2016-10-25 23:12 UTC, BerkeleyTrue commented on common/app/routes/challenges/redux/actions.js
> +export const completeAction = createAction(
Action creators should not have side effects.

2016-10-25 23:12 UTC, BerkeleyTrue commented on common/app/routes/challenges/utils.js
> +  if (typeof Storage !== 'undefined') {
These utils should not have side effects. 

Side effects should happen in an epic.

2016-10-25 23:12 UTC, BerkeleyTrue commented on common/app/routes/challenges/components/step/Step.jsx
> +    function onClickHandler() {
Functions should not be created per render. Use an instance method

2016-10-26 22:32 UTC, Bouncey commented
I will update the tests to cover for the new payload from `step-challenge-epic`

2016-10-26 22:38 UTC, BerkeleyTrue commented
We shouldn't put these in localStorage. There is no reason too.

The original issue is with going back while in a step challenge. We can just put this information in the redux store.

Something like an array of booleans indicating if the step action has been taken.

2016-10-27 11:18 UTC, Bouncey commented on common/app/routes/challenges/redux/step-challenge-epic.test.js
> +              payload: { step: 0, isUnlocked: false }
I don't know how to set this test up to return true.

Guidance would be greatly appreciated :+1:

2016-10-27 17:15 UTC, Bouncey commented on common/app/routes/challenges/components/step/Step.jsx
> +  handleActionClick() {
This needs removed, left over from a previous iteration

2016-11-02 11:21 UTC, Bouncey commented
I have updated the tests to check that the previous unlocked step remains unlocked on `stepBackward`

This is ready for another QA @BerkeleyTrue

2016-12-22 00:48 UTC, BerkeleyTrue commented on common/app/routes/challenges/redux/step-challenge-epic.js
> +function unlockStep(challengeId, index, unlockedSteps) {
We don't want to save all the challenge steps completed just the current one.

2016-12-22 00:51 UTC, BerkeleyTrue commented on common/app/routes/challenges/redux/step-challenge-epic.js
> +    }
indenting

2016-12-22 00:51 UTC, BerkeleyTrue commented on common/app/routes/challenges/redux/step-challenge-epic.js
> +    return (current.some( i => i === index));
padding in the arguments
unnecessary parenthesis around expression.

2016-12-22 00:55 UTC, BerkeleyTrue commented on common/app/routes/challenges/redux/step-challenge-epic.js
> +    updated = unlockedSteps[challengeId] = current.concat([index]);
You are mutating the state directly. You should never mutate state. State should be updated through the reducer

2016-12-30 02:23 UTC, BerkeleyTrue commented
While the code quality looks good I'm concerned about the way locked steps are stored. They are currently stored in a hash `unlockedSteps: { [challengeId]: [...Number] }`. 

This poses a couple of problems. 

We are storing information in state of challenges between subsequent challenges. This works fine until the user refreshes the page. They will start out with an empty state, causing confusion when a previously completed action from another challenge is no longer completed. 

The second issue is the storage mechanism itself is inefficient. Steps numbers are stored in an array which is stored in a hashmap keyed to each challenge id. The properties of the array data structure itself could be used instead of storing the information of which step is completed by pushing the step number onto an array. 

`unlockedSteps: [...Boolean|Void]`

To check if a step has been completed we simply do `!!unlockedSteps[stepIndex]`;

This should solve both of the issues above and doing an index check is more efficient then iterating through all those elements.

2017-01-03 21:34 UTC, Bouncey commented
The reason I put it in a hash was to cut down possible confusion if the camper jumps around the challenges and sees steps unlocked when they haven't completed the required action.

If you need `stepsUnlocked` to persist over a refresh, I can place them into local storage with a method to remove them when the challenge is submitted. 

Your idea of an array of steps would require more iteration than my hash. It would need to hold a bool for each step in the challenge, compared to my hash that only stores a step if required.

2017-01-05 00:01 UTC, BerkeleyTrue commented
> if the camper jumps around the challenges and sees steps unlocked when they haven't completed the required action.

These steps should always be reset on challenge load. 

> If you need stepsUnlocked to persist over a refresh

No they shouldn't.

> Your idea of an array of steps would require more iteration than my hash

Pushing numbers onto an array requires iteration. Using the index of the array would require no iteration.

You don't need to hold a bool for each step, just the completed steps. You can assume `undefined` is uncompleted or no action required.

2017-01-07 21:16 UTC, BerkeleyTrue approved these changes

2017-01-07 21:42 UTC, merged

2017-01-08 02:07 UTC, QuincyLarson commented
@Bouncey thanks for fixing this!