Improve wording in instructions in Make Dead Links challenge
freeCodeCamp/freeCodeCamp pull request #11359
Opened 2016-10-24 23:18 UTC by Manish-Giri

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11297 

#### Description

Changed instructions in the challenge to clarify that the **value** of the `href` attribute needs to be replaced with a `#`, not the `href` itself.

closes #11297

2016-10-25 22:20 UTC, Bouncey requested changes

2016-10-25 22:20 UTC, Bouncey commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "The current value of the <code>href</code> attribute is a link that points to \"http://www.freecatphotoapp.com\". Replace this link with a <code>#</code>, also known as a hash symbol, to cre
~~Replace this link with a <code>#</code>~~

Replace the <code>href</code> attribute value with a <code>#</code>

2016-10-25 22:44 UTC, Bouncey commented on seed/challenges/01-front-end-development-certification/html5-and-css.json
> +        "The current value of the <code>href</code> attribute is a link that points to \"http://www.freecatphotoapp.com\". Replace this link with a <code>#</code>, also known as a hash symbol, to cre
You have shown the camper where the `href` attr is by pointing out what the value is. You then call it a link, which not only is a change in terminology, it is also incorrect. 

The anchor element is the `link`, the `href` attr is the `target` of the `link`.

2016-10-25 23:48 UTC, Manish-Giri commented
@Bouncey Thanks for the review! I made the changes you'd asked for.

2016-10-27 12:36 UTC, Bouncey approved these changes

2016-10-27 12:36 UTC, Bouncey commented
## LGMT :+1: 

Thanks for contributing :tada:

2016-10-27 12:36 UTC, merged