Code with hyperdev.com url should not run
freeCodeCamp/freeCodeCamp pull request #11377
Opened 2016-10-26 04:23 UTC by yasserhussain1110

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #11265 

#### Description

A new thrower has been added to `throwers.js`
which checks for the regex \hyperdev\.com\gi and
emits an error if matched.

2016-10-26 05:37 UTC, BerkeleyTrue requested changes

2016-10-26 05:37 UTC, BerkeleyTrue commented on client/rechallenge/throwers.js
> +                   'should not be allowed to run',
Use two space indentation.

2016-10-26 06:30 UTC, yasserhussain1110 commented on client/rechallenge/throwers.js
> +                   'should not be allowed to run',
Done.

2016-10-27 13:11 UTC, Bouncey commented
## LGTM :+1: 

Thanks for contributing :tada:

2016-10-27 13:11 UTC, merged