show core team status in user profile
freeCodeCamp/freeCodeCamp pull request #11425
Opened 2016-10-28 08:23 UTC by ivantedja

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm run test-challenges`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11418

#### Description

2016-10-28 13:04 UTC, raisedadead commented
Would this look cleaner:

![image](https://cloud.githubusercontent.com/assets/1884376/19807275/01e2de16-9d3d-11e6-8fd7-5a8ae05b4a45.png)

than current:

![image](https://cloud.githubusercontent.com/assets/1884376/19807307/1ea3b4b2-9d3d-11e6-8fe1-da803c44e3a5.png)

2016-10-28 13:09 UTC, raisedadead commented
It would be cleaner with badges. And a setting to manage the visibility of them as well.

2016-10-28 13:57 UTC, ivantedja commented
That looks better, I'll update it. Badge looks more beautiful, I think it will be better if we have different kind of badge each year (more eye catching) but I'm not sure who will create the asset for that

2016-10-28 22:12 UTC, QuincyLarson commented
@ivantedja rather than have a static badge image, perhaps you could one using built using CSS, so we could dynamically change the year?

2016-10-28 22:16 UTC, BerkeleyTrue requested changes

2016-10-28 22:16 UTC, BerkeleyTrue commented on common/models/user.json
> +    "coreTeam": {
Let's change the structure to be more extensible.

```json
  badges: {
    coreTeam: [
      "2016"
    ]
  } 
```

This way we can add more badges in the future

2016-10-29 07:12 UTC, atjonathan commented on common/models/user.json
> +    "coreTeam": {
:+1:

2016-10-29 07:17 UTC, Mongues commented
t

On Oct 29, 2016 2:13 AM, "Jonathan" <notifications@github.com> wrote:
>
> @atjonathan commented on this pull request.
>
> ________________________________
>
> In common/models/user.json:
>
> > @@ -206,6 +206,10 @@ "type": "string", "description": "An IETF language
tag", "default": "en" + }, + "coreTeam": {
>
> Hi👍
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
Am I on the new w/ John and Dave etc??

t

2016-10-29 07:44 UTC, raisedadead commented
Hello!

Looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) or click on the image below and select **"Not watching"**.

[![image](https://cloud.githubusercontent.com/assets/1884376/15005313/9ba8a14a-11e0-11e6-81cb-d7cfe6b66a30.png)](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription)


We are sorry for your inconvenience!

2016-10-29 07:58 UTC, Mongues commented
Yeah but my team in here somewhere and by the way much respect as I've been
trying to learn from your thread following a long time please I have a few
quick questions please..

t

On Oct 29, 2016 2:45 AM, "Mrugesh Mohapatra" <notifications@github.com>
wrote:

> Hello!
>
> Looks like you may have accidentally subscribed to all notifications for
> the FreeCodeCamp <https://github.com/FreeCodeCamp/FreeCodeCamp>
> repository. To stop receiving notifications please visit the subscriptions
> page <https://github.com/FreeCodeCamp/FreeCodeCamp/subscription> or click
> on the image below and select *"Not watching"*.
>
> [image: image] <https://github.com/FreeCodeCamp/FreeCodeCamp/subscription>
>
> We are sorry for your inconvenience!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11425#issuecomment-257077308>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJwcfSgLICjT0x6icIv5RfxEmKG9XKt9ks5q4vmcgaJpZM4KjMcz>
> .
>

2016-10-29 09:08 UTC, ivantedja commented
@QuincyLarson probably styling the shape can be done in separate task? It is possible to use CSS but my sense of art is not that great 😈 

@BerkeleyTrue I don't know why the travis is failed

2016-10-29 09:31 UTC, raisedadead commented
@ivantedja build has been fixed, restarted it.

2016-10-29 14:54 UTC, BerkeleyTrue approved these changes

2016-10-31 15:50 UTC, Bouncey submitted a review, later dismissed

2016-10-31 15:50 UTC, Bouncey commented on server/views/account/show.jade
> +        if (badges.coreTeam && badges.coreTeam.length)
Would this not be `badges.type.coreTeam`?

2016-11-01 02:33 UTC, ivantedja commented on server/views/account/show.jade
> +        if (badges.coreTeam && badges.coreTeam.length)
from my understanding, `type` is a keyword provided by `loopback` to specify the "schema" of the property

2016-11-01 13:09 UTC, raisedadead commented
Tested.

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks.

2016-11-01 17:21 UTC, BerkeleyTrue commented
To be clear, `user.badges.coreTeam = ['2015', '2016']`. Is that correct?

2016-11-01 19:04 UTC, raisedadead commented
Yup, in reverse order, though:

user.badges.coreTeam = ['2016', '2015']

2016-11-01 19:07 UTC, BerkeleyTrue commented
Then this line `h4 Core Team #{badges.coreTeam.reverse().join(', ')}` will print in chronological order?

`Core Team 2015, 2016`

2016-11-01 19:12 UTC, raisedadead commented
Yup.

2016-11-01 19:14 UTC, BerkeleyTrue commented
Then why are we putting them in reverse order if we are just showing them in chronological?

2016-11-01 19:58 UTC, raisedadead commented
Oh, sorry my bad. Yes you are correct, Quincy is supposed to enter the Years in the backend manually in the chronological order which you correctly said:

`user.badges.coreTeam = ['2015', '2016']`

and the output should now turn out like this:

![image](https://cloud.githubusercontent.com/assets/1884376/19905115/5f4d7bf4-a09b-11e6-8303-9ad99b88cbb1.png)

2016-11-01 20:00 UTC, merged

2016-11-01 20:00 UTC, BerkeleyTrue commented
Thanks @ivantedja!

2016-11-01 23:56 UTC, QuincyLarson commented
@ivantedja great work!