Improve Exact Change readability
freeCodeCamp/freeCodeCamp pull request #11478
Opened 2016-10-31 13:23 UTC by damon-myers

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10491 

#### Description

2016-11-01 05:13 UTC, abhisekp requested changes
@damon-myers Please remove all trailing zeros that comes after decimal

_There some more place that what i've marked._

Please fix the remaining issues and this is ready to merge :loop:

2016-11-01 05:13 UTC, abhisekp commented on seed/challenges/01-front-end-development-certification/advanced-bonfires.json
> +        "checkCashRegister(19.50, 20, [[\"PENNY\", 1.01], [\"NICKEL\", 2.05], [\"DIME\", 3.10], [\"QUARTER\", 4.25], [\"ONE\", 90], [\"FIVE\", 55], [\"TEN\", 20], [\"TWENTY\", 60], [\"ONE HUNDRED\",
Remove all trailing zeros that comes after decimal

- `checkCashRegister(19.50,`
- `[\"DIME\", 3.10]`

2016-11-01 05:13 UTC, abhisekp commented on seed/challenges/01-front-end-development-certification/advanced-bonfires.json
> +        "var denom = [\n\t{ name: 'ONE HUNDRED', val: 100},\n\t{ name: 'TWENTY', val: 20},\n\t{ name: 'TEN', val: 10},\n\t{ name: 'FIVE', val: 5},\n\t{ name: 'ONE', val: 1},\n\t{ name: 'QUARTER', val
Remove all trailing zeros that comes after decimal

- `{ name: 'DIME', val: 0.10}`

2016-11-01 05:13 UTC, abhisekp commented on seed/challenges/01-front-end-development-certification/advanced-bonfires.json
> +        "assert.isArray(checkCashRegister(19.50, 20, [[\"PENNY\", 1.01], [\"NICKEL\", 2.05], [\"DIME\", 3.10], [\"QUARTER\", 4.25], [\"ONE\", 90], [\"FIVE\", 55], [\"TEN\", 20], [\"TWENTY\", 60], [\"
Remove all trailing zeros that comes after decimal

- `[\"DIME\", 3.10]` <--- assertion
- `[\"DIME\", 3.10]` <-- message

2016-11-01 05:13 UTC, abhisekp commented on seed/challenges/01-front-end-development-certification/advanced-bonfires.json
> +        "assert.isString(checkCashRegister(19.50, 20, [[\"PENNY\", 0.01], [\"NICKEL\", 0], [\"DIME\", 0], [\"QUARTER\", 0], [\"ONE\", 0], [\"FIVE\", 0], [\"TEN\", 0], [\"TWENTY\", 0], [\"ONE HUNDRED\
Remove all trailing zeros that comes after decimal

- `checkCashRegister(19.50` <-- assertion
- `<code>checkCashRegister(19.50` <-- message

2016-11-01 23:22 UTC, damon-myers commented
@abhisekp I was initially thinking we only wanted the change to apply to whole dollar amounts, but this makes more sense. On it now.

2016-11-05 11:11 UTC, raisedadead commented
@damon-myers this has a a few unwanted commits. Mind doing a rebase against staging?

`git checkout <pr branch>`
`git pull --rebase upstream staging`
`git push origin --force`

Thanks.

2016-11-06 10:18 UTC, damon-myers commented
@raisedadead, done and squashed to one commit.

2016-11-06 12:35 UTC, abhisekp approved these changes
<h1 align="center"> :sparkles:  :smile_cat:  :+1: LGTM :smiley: :+1:   :sparkles:  </h1>

2016-11-07 07:24 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @abhisekp for the review and @damon-myers for the changes!

2016-11-07 07:24 UTC, merged

2016-11-07 07:30 UTC, damon-myers commented
@raisedadead, @abhisekp Thanks for all of your help!