Fix/Replace nbsp in campers code
freeCodeCamp/freeCodeCamp pull request #11472
Opened 2016-10-30 23:43 UTC by Bouncey

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): 
Closes #11400
Closes #7753
Closes #11086  

#### Description

Replaces `nbsp` in campers code before tests are run

2016-10-31 10:42 UTC, Bouncey commented
The code from [this link](https://www.freecodecamp.com/challenges/use-a-css-class-to-style-an-element#?solution=%3Cstyle%3E%0A%20%C2%A0.red-text%20%7B%0A%20%C2%A0%20%20color%3A%20red%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A%0A%3Ch2%20class%3D%22red-text%22%3ECatPhotoApp%3C%2Fh2%3E%0A%0A%3Cp%3EKitty%20ipsum%20dolor%20sit%20amet%2C%20shed%20everywhere%20shed%20everywhere%20stretching%20attack%20your%20ankles%20chase%20the%20red%20dot%2C%20hairball%20run%20catnip%20eat%20the%20grass%20sniff.%3C%2Fp%3E%0A) contains a `&nbsp;`

2016-11-01 20:23 UTC, BerkeleyTrue requested changes

2016-11-01 20:23 UTC, BerkeleyTrue commented on client/sagas/execute-challenge-saga.js
>        const { files } = state.challengesApp;
This might be better placed as a transformer. Is there a reason you did it directly in the build?

2016-11-01 20:23 UTC, BerkeleyTrue commented on client/sagas/execute-challenge-saga.js
> +            contents: file.contents.replace(nbspRegExp, ' ')
You don't need a regex when replacing an exact match.

2016-11-01 20:30 UTC, Bouncey commented on client/sagas/execute-challenge-saga.js
>        const { files } = state.challengesApp;
If I'm honest its the first place I tried. The transformers didn't even come into my thought process. I will refactor.

2016-11-01 20:30 UTC, Bouncey commented on client/sagas/execute-challenge-saga.js
> +            contents: file.contents.replace(nbspRegExp, ' ')
Every day is a school day :+1:

2016-11-02 11:41 UTC, Bouncey commented on client/rechallenge/transformers.js
> +        const nbspRegExp = new RegExp(String.fromCharCode(160), 'g');
Needs to be a RegExp to ensure all `&nbsp;`'s are removed

From [w3schools](http://www.w3schools.com/jsref/jsref_replace.asp)

> If you are replacing a value (and not a regular expression), only the first instance of the value will be replaced.

2016-11-02 20:09 UTC, BerkeleyTrue requested changes

2016-11-02 20:09 UTC, BerkeleyTrue commented on client/rechallenge/transformers.js
> +        const nbspRegExp = new RegExp(String.fromCharCode(160), 'g');
Nice catch.

Can you add this as a property of the object instead of creating per function call.

2016-11-02 23:30 UTC, BerkeleyTrue approved these changes

2016-11-04 13:11 UTC, ghost approved these changes
### LGTM :+1:

Sorry for the wait @Bouncey :smile:

2016-11-04 13:11 UTC, merged