Fix: Entities reducer refactor to enable update of redux-actions
freeCodeCamp/freeCodeCamp pull request #11784
Opened 2016-11-23 23:47 UTC by Bouncey

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

This PR supersedes #11754 and #11781 

`entities-reducer.js` required a refactor to accept new versions of `redux-actions`, see #11754 for more details.

I have two commits
- `entities-reducer` refactor
- `redux-actions` update

2016-12-22 03:40 UTC, BerkeleyTrue commented on common/app/redux/entities-reducer.js
> +  if (newState.user !== user && Object.keys(user).length > 0) {
Why are you doing the additional check for user keys? If the user ref values are not the same, that alone should signify that the user object has been updated and the overall state object should receive a  new ref value.

2016-12-26 15:21 UTC, Bouncey commented on common/app/redux/entities-reducer.js
> +  if (newState.user !== user && Object.keys(user).length > 0) {
I was running into a problem `user` was just an empty Object. Without the `Object.keys` check, `state.user` was being totally overridden with an empty Object.

2016-12-30 03:03 UTC, BerkeleyTrue commented on common/app/redux/actions.js
> +  (username, lang) => ({ username, languageTag: lang })
Great catch!

2016-12-30 03:22 UTC, BerkeleyTrue requested changes

2016-12-30 03:22 UTC, BerkeleyTrue commented on common/app/redux/entities-reducer.js
> +  if (newState.user !== user && Object.keys(user).length > 0) {
I see. After some debugging, I think I have found the reason.

Normally when combining reducers subsequent reducers should see the latest state, but if `metaReducer` makes a change to `state.user` when `userReducer` ends up seeing stale data. You should always feed `newState.user` to `userReducer`. Then you will not need the check for keys.

2016-12-30 03:22 UTC, BerkeleyTrue commented on common/app/redux/entities-reducer.js
> +  const user = userReducer(state && state.user || {}, action);
initialState is already given to the `handleActions`. No need add the extra `|| {}` check.

2016-12-30 03:23 UTC, BerkeleyTrue commented
Looking good @Bouncey! Almost there

2017-01-01 09:25 UTC, Bouncey commented
Passing `newState.user` helped greatly with the blank object. I also found a few typo and assignment bugs which caused a blank object to be returned along with the user object.

2017-01-01 09:35 UTC, Bouncey commented
The build fails on the challenge solution for `Friendly Dates Ranges` because 2017. 

I will raise an issue to rectify

2017-01-01 09:51 UTC, Bouncey commented
Please see #12305

2017-01-02 23:19 UTC, BerkeleyTrue commented
Please rebase off of latest staging. That should fix the test issues

2017-01-04 23:57 UTC, BerkeleyTrue requested changes

2017-01-04 23:57 UTC, BerkeleyTrue commented on common/app/redux/entities-reducer.js
> +    console.log('meta', action.meta.entities.user);
remove console.log

2017-01-04 23:57 UTC, BerkeleyTrue commented on common/app/redux/entities-reducer.js
> +  console.log(newState.user);
remove console.log

2017-01-05 00:16 UTC, BerkeleyTrue approved these changes

2017-01-05 00:16 UTC, merged