Change instructions in Counting Cards Challenge
freeCodeCamp/freeCodeCamp pull request #11835
Opened 2016-11-27 16:26 UTC by rashmimalpande

#### Pre-Submission Checklist

- [* ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ *] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [* ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ *] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [* ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Added a sentence in Counting Cards challenge instructions that the input can be a number or a String.
Closes issue #11819

2016-11-27 20:20 UTC, dhcodes requested changes
I know that @Bouncey used emphasis and strong in the issue thread, but I think he only did so to show what text needed to be added. I don't think the additional text needs `<em>` or `<strong>`. Please remove them, amend the commit, and re-push the branch with `-f` to update it.

2016-11-28 06:15 UTC, rashmimalpande commented
I made the changes. I hope I did everything correct. Thanks.

2016-11-28 13:29 UTC, dhcodes approved these changes

2016-11-28 13:29 UTC, dhcodes commented
Tested and LGTM 👍 . Thanks for contributing to FreeCodeCamp

2016-11-28 13:29 UTC, merged