revised description for Concatenate Arrays with .concat
freeCodeCamp/freeCodeCamp pull request #11844
Opened 2016-11-28 07:27 UTC by johnnyqbui

#### Pre-Submission Checklist

- [x ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x ] Tested changes locally.
- [x ] Closes currently open issue (replace XXXX with an issue no): Closes #10511

#### Description

Revised description for Concatenate Arrays with .concat challenge for a more accurate description of .concat.

2016-11-28 20:33 UTC, Bouncey requested changes

2016-11-28 20:33 UTC, Bouncey commented on seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json
> +        "Ex. 1:\n<code>otherArray</code> onto the end of <code>oldArray</code>:\n<code>newArray = oldArray.concat(otherArray);</code>",
Do not abbreviate `Example`. Many people using freeCodeCamp currently are not native English speakers

2016-11-28 20:33 UTC, Bouncey commented on seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json
> +        "Ex. 1:\n<code>otherArray</code> onto the end of <code>oldArray</code>:\n<code>newArray = oldArray.concat(otherArray);</code>",
`\n` shouldn't be used. Instead, add another element to the `description` array for new lines.

This helps keep the seed JSON's readable

2016-11-28 20:33 UTC, Bouncey commented on seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json
> +        "Ex. 1:\n<code>otherArray</code> onto the end of <code>oldArray</code>:\n<code>newArray = oldArray.concat(otherArray);</code>",
The code example would be better off inside a `<blockquote>` without `<code>` tags

2016-11-28 20:33 UTC, Bouncey commented on seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json
> +        "Ex. 2:\n<code>newArray</code> with all values of <code>arr1, arr2,</code> and <code>arr3</code>:\n<code>newArray = arr1.concat(arr2, arr3);</code>",
Same as Example 1

2016-11-28 23:59 UTC, closed without merging

2016-11-29 00:03 UTC, johnnyqbui commented on seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json
> +        "Ex. 2:\n<code>newArray</code> with all values of <code>arr1, arr2,</code> and <code>arr3</code>:\n<code>newArray = arr1.concat(arr2, arr3);</code>",
@Bouncey I've made the requested changes, but was having issues with the branch name so I had to delete my branch name and create a new one. Can I resubmit another PR?