fix(issue-reports): Remove encoded solution
freeCodeCamp/freeCodeCamp pull request #11863
Opened 2016-11-29 19:03 UTC by raisedadead

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

This commit removes the encoded solution from the URI to make issue submission cleaner.

2016-11-29 22:09 UTC, systimotic reviewed
Should this be tied to #11261?

2016-11-29 22:21 UTC, raisedadead commented
@systimotic nope, that's a different topic. It relates to how challenge solutions are encoded and evaluated in browsers. 

My PR addresses the GitHub Issue requests that are created from the Report Bug button, often campers reporting from the interface end up with issues that have huge URL in the description making it messy for everyone to understand. 

This is not required because the code from the editor is taken into the body anyway. 

My PR removes the same from the URL to the challenge. Hopefuly making it cleaner.

2016-11-29 22:36 UTC, systimotic commented
Fair enough. My reasoning was that if the code is removed from the URL in general, we can send the full URL again.

I do quite like the way it is right now, but I could see why you would want to remove it, as it breaks often, which is really annoying.



On Tue, Nov 29, 2016 at 11:23 PM +0100, "Mrugesh Mohapatra" <notifications@github.com<mailto:notifications@github.com>> wrote:


@systimotic<https://github.com/systimotic> nope, that's a different topic. It relates to how challenge solutions are encoded and evaluated in browsers.

My PR addresses the GitHub Issue requests that are created from the Report Bug button, often campers reporting from the interface end up with issues that have huge URL in the description making it messy for everyone to understand.

This is not required because the code from the editor is taken into the body anyway.

My PR removes the same from the URL to the challenge. Hopefuly making it cleaner.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11863#issuecomment-263718906>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AG7PV0-zc0qutMAY30-Pxj8frIWdApr7ks5rDKW2gaJpZM4K_WZJ>.

2016-11-29 23:28 UTC, Bouncey commented
There is no encoded solution in the URI now with react.

This is the output for the issue template from `staging`
> `Challenge [say-hello-to-html-elements](http://localhost:3000/en/challenges/html5-and-css/say-hello-to-html-elements) has an issue.`

2016-11-30 11:21 UTC, raisedadead commented
> There is no encoded solution in the URI now with react.

Agreed, but this does not count already constructed URLs in the Camper's profiles. Although really rare if someone would report after visiting a solution, yet this is a safety and the former logic of using `href` is not needed any longer.

my two cents.

2016-12-01 21:32 UTC, Bouncey requested changes

2016-12-01 21:32 UTC, Bouncey commented on client/commonFramework/report-issue.js
> -        window.location.href,
This file is no longer in use. 

Please edit the [new version of this file](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/549cfc305f75d8c6036a3cde65c47b518607b18c/common/app/routes/challenges/redux/bug-saga.js). Line 53 is where the location is being sent with the issue :+1:

2016-12-08 07:25 UTC, raisedadead commented
Closing this request in favor of pushing this against `backup/master`. We are getting very frequent issues with URLs that aren't parsed by GitHub correctly.

2016-12-08 07:25 UTC, closed without merging