Add note about arguments object to seek and destroy challenge
freeCodeCamp/freeCodeCamp pull request #11867
Opened 2016-11-29 22:07 UTC by systimotic

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #11271

#### Description

This PR adds a note about having to use the arguments object to this challenge, as per the issue.
The link to the MDN page about the arguments object was already in place, which is why I didn't add it to the message.

2016-11-29 22:16 UTC, erictleung requested changes
Almost good. But I think to be consistent with preexisting code, there should be a line break and no colon.

2016-11-29 22:16 UTC, erictleung commented on seed/challenges/01-front-end-development-certification/basic-bonfires.json
> +        "<strong>Note:</strong> You have to use the <code>arguments</code> object.",
I think we usually have a `<br>` after the Note and no colon like in [this line](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/1f105f38610bd442fcad7ebabbc82406843ee5f6/seed/challenges/01-front-end-development-certification/basic-javascript.json#L505).

2016-11-29 22:41 UTC, systimotic commented
Ah, thank you for bringing this up. I was thinking about it, but then forgot about it.
I'm happy to chanhe this tomorrow when I get back to my laptop.
The reason I went with this format is https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11805 It might be a good idea to agree on a common format for this.



On Tue, Nov 29, 2016 at 11:17 PM +0100, "Eric Leung" <notifications@github.com<mailto:notifications@github.com>> wrote:


@erictleung requested changes on this pull request.

Almost good. But I think to be consistent with preexisting code, there should be a line break and no colon.

________________________________

In seed/challenges/01-front-end-development-certification/basic-bonfires.json<https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11867#pullrequestreview-10651543>:

> @@ -671,6 +671,7 @@
       "title": "Seek and Destroy",
       "description": [
         "You will be provided with an initial array (the first argument in the destroyer function), followed by one or more arguments. Remove all elements from the initial array that are of the same value as these arguments.",
+        "<strong>Note:</strong> You have to use the <code>arguments</code> object.",


I think we usually have a <br> after the Note and no colon like in this line<https://github.com/FreeCodeCamp/FreeCodeCamp/blob/1f105f38610bd442fcad7ebabbc82406843ee5f6/seed/challenges/01-front-end-development-certification/basic-javascript.json#L505>.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11867#pullrequestreview-10651543>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AG7PV0Q-8omqA1-PvPylUPRx7-Kic2a0ks5rDKSQgaJpZM4K_i9a>.

2016-11-30 00:26 UTC, erictleung commented
@systimotic ah I see. When I made one of these "Notes" a while back, I was told to go with the styling I mentioned. I agree that we should have some consistent way of formatting the notes.

2016-11-30 01:41 UTC, HKuz commented
For what it's worth, I've been using the &lt;strong&gt;Note&lt;/strong&gt;&lt;br&gt; formatting in the curriculum expansion challenges. (I think the first example in the existing code I found did it that way). I have that and a few other minor formatting nits in a list of things that we'll need to make consistent across all challenges - making the change in existing challenges will probably be one of the last things I do for the QA process 😄.

2016-12-01 21:38 UTC, Bouncey commented
## LGTM :+1: 

Thanks for contributing :tada:

2016-12-01 21:38 UTC, merged