Remove reset/delete account progress animations and change color/increase size of buttons
freeCodeCamp/freeCodeCamp pull request #11881
Opened 2016-12-01 01:43 UTC by johnnyqbui

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

…delete account buttons

2016-12-01 08:11 UTC, ghost requested changes

2016-12-01 08:11 UTC, atjonathan commented on client/less/main.less
> +  .modal-footer {
Add a space between each class's styles declared inside of `.modal-footer`.

2016-12-01 18:10 UTC, johnnyqbui commented on client/less/main.less
> +  .modal-footer {
@atjonathan I've made the changes.

2016-12-01 19:36 UTC, johnnyqbui commented on client/less/main.less
> +  .modal-footer {
@atjonathan I was trying to squash the commits, but I think I messed up.

2016-12-03 15:39 UTC, dhcodes commented
LGTM. 

@atjonathan Is the following behavior intended?
When canceling the modal for deleting the account, it goes to the about page.
When canceling the modal for resetting progress, it goes back to the settings page.

That may be outside the scope of this PR.

2016-12-04 23:54 UTC, ghost approved these changes

2016-12-04 23:54 UTC, atjonathan commented
@dhcodes 
> When canceling the modal for deleting the account, it goes to the about page.

That behavior should be changed. The other seems fine. I opened a new issue (#11922), as this PR is irrelevant. 

@johnnyqbui, **LGTM 👍**
Thanks for contributing, loving the UI improvements 💪

2016-12-04 23:54 UTC, merged