Add P2P Video Chat Application to Extra Projects
freeCodeCamp/freeCodeCamp pull request #11927
Opened 2016-12-05 07:26 UTC by karuppiah7890

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes FreeCodeCamp/CurriculumExpansion#88

#### Description

Added a new application - P2P Video Chat application to the set of Extra Projects

2016-12-05 07:28 UTC, karuppiah7890 commented
The local test `npm test` failed. It was some problem with already written code and commits, because all the errors were not related to my changed.

2016-12-05 18:52 UTC, Greenheart commented
@karuppiah7890 I really like this idea! :smile:

 @Em-Ant and @systimotic What do you think about this as a new project as one of the fullstack projects?

2016-12-06 13:12 UTC, raisedadead requested changes

2016-12-06 13:12 UTC, raisedadead commented on seed/challenges/10-extra-practice-projects/extra-practice-projects.json
> +
Remove Extra Line

2016-12-06 13:14 UTC, raisedadead requested changes

2016-12-06 13:14 UTC, raisedadead commented on seed/challenges/10-extra-practice-projects/extra-practice-projects.json
> +      "challengeSeed": [],
Can this be left blank?

2016-12-06 13:56 UTC, karuppiah7890 commented
@Greenheart Thanks! :smile:

2016-12-06 17:51 UTC, Em-Ant commented
@karuppiah7890 great project. I think it's very interesting. :+1:

2016-12-06 19:51 UTC, karuppiah7890 commented
@Em-Ant Thanks! I learned this in Google Code Labs actually. https://codelabs.developers.google.com/codelabs/webrtc-web and implemented using some npm modules instead of directly writing WebRTC code, which seemed a little bit of heavy lifting, with all the error handling and data channels stuff.

2016-12-06 21:30 UTC, raisedadead commented on seed/challenges/10-extra-practice-projects/extra-practice-projects.json
> +      "challengeSeed": [],
Cool. thanks for the clarification

2016-12-06 21:31 UTC, raisedadead approved these changes

2016-12-12 16:13 UTC, raisedadead commented
LGTM. thanks @karuppiah7890, sorry about the delay.

2016-12-12 16:13 UTC, merged

2016-12-13 08:31 UTC, karuppiah7890 commented
@raisedadead :+1: