[WIP] feat(user): Report profiles
freeCodeCamp/freeCodeCamp pull request #12048
Opened 2016-12-14 21:30 UTC by raisedadead

This adds a simple mechanism to report profiles for abuse.
Closes #11891 

P.S: Targeting to complete probably in a day or two.

2016-12-22 03:33 UTC, BerkeleyTrue commented on server/boot/user.js
> +    if (!user.email || !user.emailVerified) {
This should be a middleware and both the get request and the api should block those that have not been authenticated.

2016-12-22 03:34 UTC, BerkeleyTrue requested changes

2016-12-22 03:34 UTC, BerkeleyTrue commented on server/boot/user.js
> +        user.email +
Why are you sending the users email to the reporter?

2016-12-22 03:35 UTC, BerkeleyTrue commented
This seems something that can easily be abused and does not really solve the problem. 

I'm not sure just sending an email to quincy is the right thing to do. This could potentially make our inbox unmanageable.

@QuincyLarson What are you thoughts?

2016-12-22 04:09 UTC, raisedadead commented on server/boot/user.js
> +        user.email +
We are showing a notif to the reporter. This is the reporter's email.

We are keeping them in the copy to continue the follow-up, plus having them in copy means they won't be spamming with multiple reports.

2016-12-22 04:16 UTC, raisedadead commented
@BerkeleyTrue thanks for the QA.

Yeah, it's a very simple, light-weight, mechanism, as per @QuincyLarson's [comment](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/10807#issuecomment-264329567), we aren't looking to hit the database.

Regarding safeguards against abuse, we are aiming to have this towards logged in users with verified emails only. Each report is sent as a copy to the reporter. This aims to reduce the chances of spam mailing.

But of course, we should consider this least on the list of our priorities.

I will fix the routing issues in your review and update the PR.

2016-12-22 04:17 UTC, raisedadead commented
On that note, maybe I'll add some recorded GIF's to showcase the flow, if that would help.

2016-12-22 19:41 UTC, BerkeleyTrue commented
Alright, let's give it a try and see how it works out.

2016-12-24 17:43 UTC, BerkeleyTrue approved these changes

2016-12-25 18:41 UTC, raisedadead commented
Please wait for fixes to Berkeley's earlier review comments before merging, will update when ready.

2016-12-27 04:55 UTC, raisedadead commented
Ready for QA. Have addressed the earlier comments and added the unAuth and the non-verified email middlewares.

2016-12-30 02:49 UTC, BerkeleyTrue requested changes

2016-12-30 02:49 UTC, BerkeleyTrue commented on server/boot/user.js
> +    ifNoUser401,
sending status code should be done when the endpoint is an api. 

When the endpoint is sending back to a page the redirect should also send them to a page.

So here we want to redirect unauthenticated(not logged in) users to either the `map` or `login`

2016-12-30 02:49 UTC, BerkeleyTrue commented on server/utils/middleware.js
> +export function ifNoEmailVerifiedRedirectToSettings(req, res, next) {
We can shorten this to just `ifNotVerifiedRedirectToSettings` as we will be using the verified field more often now we don't need the extra `email` qualifier.

2016-12-30 02:49 UTC, BerkeleyTrue commented on server/boot/user.js
> +  function postReportUserProfile(req, res) {
API endpoints should always include the `next` argument.

2016-12-30 02:49 UTC, BerkeleyTrue commented on server/boot/user.js
> +      if (err) {
errors should be sent to the default express handler using `return next(err)`. This prevents having to write duplicate code.

You can still define the redirect by adding the `redirectTo` property to the error instance.

https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/middlewares/error-handlers.js#L32

2016-12-30 02:49 UTC, BerkeleyTrue commented on server/boot/user.js
> +    const username = req.params.username.toLowerCase();
req.params.username could be `undefined` causing this line to crash. 

Also, this line and the two below can be done declaratively using object destructuring.

2016-12-30 02:49 UTC, BerkeleyTrue commented on server/boot/user.js
> +    const report = req.body.reportDescription;
Both the `reportDescription` and username should be sanitized just in case. We don't want malicious scripts to be sent to out email

2016-12-30 02:49 UTC, BerkeleyTrue commented on server/boot/user.js
> +        return res.redirect('/' + user.username);
This is redirect the reporting user to their own user profile. Is this intentional? shouldn't this send them back to the page they were on using req.params.username?

2017-01-10 18:22 UTC, raisedadead commented on server/boot/user.js
> +      if (err) {
Fixed.

2017-01-10 18:23 UTC, raisedadead commented
This is ready for QA. I have added a custom sanitizer (source is quoted in the comments).

2017-01-11 19:24 UTC, BerkeleyTrue commented
Why are you adding a custom sanitizer? Why not use the one built into express-validator?

2017-01-12 04:49 UTC, raisedadead commented
Going by the docs, they have just basic escaping as default.
see: [express-validator#sanitizer](https://github.com/ctavan/express-validator#sanitizer)

More sanitizers are available from, their dependency in [chriso/validator.js](https://github.com/chriso/validator.js), but they apparently removed support for scripts, more details in their readme.

I went by a SO answer http://stackoverflow.com/a/430240/1932901, it was aimed for client side cleanup, by solves our purposes, for API side validation.

I tested, it recursively removes all sorts of tags and dirty elements from the text. 
Again, very basic but does a much cleaner job.

I am open to suggestions though.

2017-01-12 17:55 UTC, BerkeleyTrue commented
ok sounds good.

2017-01-12 17:57 UTC, BerkeleyTrue requested changes

2017-01-12 17:57 UTC, BerkeleyTrue commented on server/middlewares/validator.js
> +         var rawValue;
use `let` instead of `var`

2017-01-24 18:48 UTC, raisedadead commented
Ready for a QA.

2017-01-24 19:21 UTC, BerkeleyTrue approved these changes

2017-01-24 19:21 UTC, BerkeleyTrue commented
code lgtm

2017-01-26 20:16 UTC, QuincyLarson commented
@raisedadead This works amazingly. Thank you for implementing this. :shipit:

2017-01-26 20:16 UTC, merged

2017-01-27 05:23 UTC, raisedadead commented
Happy to help!