Add class btn-toggle and remove bg-color from inactive buttons in nig…
freeCodeCamp/freeCodeCamp pull request #12144
Opened 2016-12-21 08:19 UTC by MarkusToe

…ht mode

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description
I added a new class `.btn-toggle` and set the background-color to transparent in night mode. Buttons with the classes `.btn-toggle` and `.active` will get the darkgreen background.

2016-12-29 15:02 UTC, raisedadead commented
@MarkusToe could you squash your commits? Thanks.

2016-12-30 04:00 UTC, BerkeleyTrue requested changes
Indenting should always be two spaces.

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Locked-Settings.jsx
> +import React, {PropTypes} from 'react';
Re-add padding

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Locked-Settings.jsx
> +import {Button, Row, Col} from 'react-bootstrap';
Re-add padding

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Locked-Settings.jsx
> +    isLocked: PropTypes.bool,
Remove added space

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Email-Setting.jsx
> +              )
Should be two space indent

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Email-Setting.jsx
> +                  'btn-toggle'
Should be two space indent

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Email-Setting.jsx
> +                  'btn-toggle'
Should be two space indent

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Locked-Settings.jsx
> +        'btn-toggle': true
Should be two space indent

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Locked-Settings.jsx
> +    const className = classnames({
Should be two space indent

2016-12-30 04:00 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Locked-Settings.jsx
> +        </Row>
Should be two space indent

2017-01-06 06:36 UTC, raisedadead commented
The OP seems to be away. I have addressed the comments, please check and review.

2017-01-07 21:03 UTC, BerkeleyTrue commented on common/app/routes/settings/components/Locked-Settings.jsx
> +export default function LockSettings({isLocked, toggle}) {
Re-add padding

2017-01-08 12:36 UTC, raisedadead commented
@BerkeleyTrue addressed.

2017-01-12 18:00 UTC, BerkeleyTrue approved these changes

2017-01-12 18:00 UTC, BerkeleyTrue commented
Code LGTM

2017-01-24 13:39 UTC, dhcodes commented
@raisedadead is this good to go?

2017-01-24 13:44 UTC, raisedadead commented
Yes, I have fixed all changes, this has been sitting here for a merge, can you please check and merge?

2017-01-24 16:11 UTC, dhcodes commented
Looks good @raisedadead but while this is open, what do you think about changing the `btn-primary` border-color to `#777`. The black border blends in almost completely with the dark gray background. 
Here's the line:  https://github.com/freeCodeCamp/freeCodeCamp/blob/0a6024769bb7d7c0625309ab23f9d6a25c7a8064/client/less/main.less#L1132

Here's a screenshot: ![nightbutton](http://i.imgur.com/OXMTrdT.png)

2017-01-24 16:58 UTC, raisedadead commented
@dhcodes this is ready for a review once more 😉 !

2017-01-24 17:37 UTC, dhcodes commented
magnifique! 👍  Thanks for putting up with me @raisedadead. 🌮  💯

2017-01-24 17:37 UTC, merged