Grammatical Fix (Fixes #12300)
freeCodeCamp/freeCodeCamp pull request #12304
Opened 2017-01-01 05:59 UTC by ryzokuken

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of FreeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

2017-01-01 07:05 UTC, ryzokuken commented
There was an issue with `MakeFriendlyDate()`, I suppose, but the simple commit does not even modify such a method.

2017-01-01 09:46 UTC, Bouncey commented
@ryzokuken please see #12305 

It is not an issue with your PR

Thanks for contributing :+1:

2017-01-01 16:14 UTC, Bouncey requested changes

2017-01-01 16:14 UTC, Bouncey commented on seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json
> +        "Give your <code>motorBike</code> object <code>wheels</code>, <code>engines</code>, and <code>seats</code> attributes and set each to a number"
Comma after `<code>engines</code>` is not required

2017-01-02 21:10 UTC, systimotic requested changes
This looks great! If you could add back the period at the end of the sentence and remove the ever-so-controversial Oxford comma as requested by Bouncey, this should be good to merge! Nice work 👍

2017-01-03 05:18 UTC, raisedadead commented
@ryzokuken thanks a lot for your change, but looks like you have made a change on GitHub interface, can you close this and make a fresh request from a local copy? This will let you address the review comments.

Have a look at our [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

Reach us out on the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), if you need any assistance.

2017-01-03 06:16 UTC, ryzokuken commented
@raisedadead Yes, I would love to. I am setting up the project locally. This might take a little time though, and I'm sorry for that.

2017-01-03 07:29 UTC, raisedadead commented
@ryzokuken sure no problem.

2017-01-03 07:29 UTC, closed without merging

2017-01-03 07:30 UTC, Bouncey commented
Time is not an issue here @ryzokuken :+1: 

Thank you for taking the time to fix this