Improve console.log output
freeCodeCamp/freeCodeCamp pull request #12322
Opened 2017-01-02 17:02 UTC by systimotic

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12271

#### Description

Here's my test code:
```js
var hi = 'potato';

function right() {
  return 'wrong';
}

console.log('normal thing');
console.log('// this should not really do what it does, but oh well');
console.log(NaN);
console.log([8, null, 0, NaN, undefined, "", 'text', hi, right]);
console.log(['array', ['nested array', ['nested nested array', undefined]]]);
console.log(right());
console.log({
  property: '1',
  otherProperty: 1,
  'anotherProperty': NaN
});
```
This is what that looks like on the current staging branch
![chrome_2017-01-02_15-23-24](https://cloud.githubusercontent.com/assets/7262039/21590857/802bd14c-d0ff-11e6-96b8-8a85ecbc1d2a.png)
This is what it looks like after my changes
![chrome_2017-01-02_14-06-49](https://cloud.githubusercontent.com/assets/7262039/21590858/802bf1e0-d0ff-11e6-86a3-38e638b90093.png)

### Things that work great now
- Strings actually show up as strings
- Previously, `undefined` and `NaN` were converted to `null`. They now stay as is.
- Objects are prettified.
- Arrays get an extra space, like they have in the browser console.

### Things that aren't perfect yet
- Nested arrays and property values are still handled by `JSON.stringify`, so they still have the `NaN` -> `null` issue.
- All strings that start with // are displayed as comments.
- The indentation of indented arrays doesn't necessarily have to be this way. I guess it comes down to our preference.

Tests are still broken as per #12305. I ran them with the fix from #12317, and they passed.

2017-01-02 23:31 UTC, BerkeleyTrue requested changes

2017-01-02 23:31 UTC, BerkeleyTrue commented on common/app/routes/challenges/utils.js
> +      if (Array.isArray(arg)) {
I would move this check into the logReplacer itself.

2017-01-02 23:31 UTC, BerkeleyTrue commented on common/app/routes/challenges/utils.js
> +  } else if (typeof value === 'number' && isNaN(value)) {
If you uses a `return` in the body of each `if` then you just omit the `else if` and just use a serious of `if`s

```js
if (...) {
  return ...
}
if (...) {
  return ...
}
return ...
```

this reduces the number of chars and gives a cleaner look.

2017-01-02 23:31 UTC, BerkeleyTrue commented on common/app/routes/challenges/utils.js
>      .map(arg => typeof arg === 'undefined' ? 'undefined' : arg)
This case should also be in the logReplacer

2017-01-04 15:09 UTC, systimotic commented on common/app/routes/challenges/utils.js
> +  } else if (typeof value === 'number' && isNaN(value)) {
I usually do that. This was originally inside of one of the `map`s setting a variable instead. For some stupid reason I forgot to change it when I refactored it into a function. Will make the change now.

2017-01-04 17:26 UTC, systimotic commented on common/app/routes/challenges/utils.js
> +      if (Array.isArray(arg)) {
That's actually a really good idea, as it immediately makes it recursive

2017-01-04 17:34 UTC, systimotic commented
@BerkeleyTrue I made the changes.

2017-01-04 23:35 UTC, BerkeleyTrue approved these changes

2017-01-04 23:39 UTC, merged

2017-01-04 23:39 UTC, BerkeleyTrue commented
@systimotic Nice work!!