unsubscribe all user with the same email address
freeCodeCamp/freeCodeCamp pull request #12377
Opened 2017-01-05 06:51 UTC by suhussai

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12352 

#### Description

Changed the function call from `findOne()` to `update()` with the `multi` parameter set to `true`. This approach no longer requires the extra step of updating the attributes of the user that was found using the `findOne()` function call. Rather, in one function call, we can update the appropriate attributes of all users that have the same email address. Also, because the update function returns a counter that indicates the number of users that were found, the "Email address not found." error can still be displayed when the counter is equal to zero.

2017-01-07 21:11 UTC, BerkeleyTrue requested changes

2017-01-07 21:11 UTC, BerkeleyTrue commented on server/boot/randomAPIs.js
> +    return User.update(query, params, options, (err, updates) => {
Did you mean `updateAll`?

http://apidocs.strongloop.com/loopback/v/2.36.2/#persistedmodel-updateall

Also, please change `updates` to `info` so it falls in line with LB docs

2017-01-07 21:11 UTC, BerkeleyTrue commented on server/boot/randomAPIs.js
> +      if (updates['count'] === 0) {
use dot notation instead of reflection.

`if (updates.count === 0) {`

2017-01-07 21:26 UTC, suhussai commented on server/boot/randomAPIs.js
> +    return User.update(query, params, options, (err, updates) => {
For the `update()` function, I found the documentation in this link: https://mongodb.github.io/node-mongodb-native/api-generated/collection.html. I've never worked with loopback, but it seems to be a middleware between the actual backend and the frontend. Is that correct?

2017-01-07 21:26 UTC, suhussai commented on server/boot/randomAPIs.js
> +      if (updates['count'] === 0) {
sure, I can change that.

2017-01-07 21:28 UTC, BerkeleyTrue commented on server/boot/randomAPIs.js
> +    return User.update(query, params, options, (err, updates) => {
Yes.

Use the LoopBack api, not the MongoDB api.

2017-01-07 22:46 UTC, suhussai commented on server/boot/randomAPIs.js
> +    return User.update(query, params, options, (err, updates) => {
I've updated the function call to use updateAll():
```
  function unsubscribeAll(req, res, next) {
    req.checkParams('email', 'Must send a valid email').isEmail();
    var query = { email: req.params.email };
    var params = {
      sendQuincyEmail: false,
      sendMonthlyEmail: false,
      sendNotificationEmail: false
    };
    return User.updateAll(query, params, function(err, info) {
      console.log(err);
      if (err) { return next(err); }
      console.log(info);
      if (info.count === 0) {
        req.flash('info', {
          msg: 'Email address not found. ' +
          'Please update your Email preferences from your profile.'
        });
        return res.redirect('/map');
      } else {
        req.flash('info', {
          msg: 'We\'ve successfully updated your Email preferences.'
        });
        return res.redirect('/unsubscribed');
      }
    });

```

The issue is that `info.count` returns a number larger than 0, but the function call does not update the mongo database. The attributes:

```
"sendMonthlyEmail" : true, 
"sendNotificationEmail" : true,
"sendQuincyEmail" : true
```
remain `true` even after the function call has been made. The weird thing is that the error value is `null` and `info.count` is greater than 0 so the application assumes the change has been made, but when I query the users using the mongo client I can see that it hasn't changed. There are no obvious errors in the console, so I am not sure what's wrong. Any ideas?

2017-01-08 20:50 UTC, suhussai commented on server/boot/randomAPIs.js
> +    return User.update(query, params, options, (err, updates) => {
I got it now. I wasn't using the `freecodecamp` db in mongodb when I was checking for whether or not the user was being updated. It works now.

2017-01-08 20:54 UTC, suhussai commented
@BerkeleyTrue updated the PR.

2017-01-09 09:36 UTC, tmpvnunes commented
@suhussai Hi, have you fix this issue?

2017-01-09 17:55 UTC, suhussai commented
@tmpvnunes I've tested the new unsubscribe feature and found that it successfully unsubscribes multiple users with the same email.

2017-01-09 17:58 UTC, BerkeleyTrue approved these changes

2017-01-12 17:38 UTC, merged

2017-01-12 17:38 UTC, BerkeleyTrue commented
Thanks!