Corrected Grammatical Errors.
freeCodeCamp/freeCodeCamp pull request #12442
Opened 2017-01-09 13:19 UTC by 91aman

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12300

#### Description
Corrected the grammar changes as pointed out in the issue no #12300

2017-01-10 07:17 UTC, erictleung requested changes

2017-01-10 07:17 UTC, erictleung commented on seed/challenges/01-front-end-development-certification/object-oriented-and-functional-programming.json
> +        "Give your <code>motorBike</code> object <code>wheels</code>, <code>engines</code> and <code>seats</code> attribute and set them to numbers."
This line still needs a change.

```diff
- <code>seats</code> attribute and set them to numbers.
+ <code>seats</code> attributes and set each to a number.
```

2017-01-10 07:18 UTC, erictleung commented
@91aman thanks for the PR! Almost there, just need to change the line I've pointed out just a little bit. Let us know in the [contributor's chat room](https://gitter.im/FreeCodeCamp/Contributors) if you need any help.

2017-01-10 10:40 UTC, 91aman commented
@erictleung I have done the changes as requested by you. Do let me know if any others changes need to be done.

2017-01-11 04:13 UTC, erictleung approved these changes
LGTM! 👍

2017-01-11 08:38 UTC, 91aman commented
@erictleung Thanks. what are next steps I need to do to get this PR merged?

2017-01-11 08:54 UTC, erictleung commented
@91aman ah I was waiting for possibly others to take a look at this PR as well. But this kind of change should be safe to merge. I'll go ahead and merge it. Thanks for contributing! 🎉

2017-01-11 08:55 UTC, merged

2017-01-11 10:19 UTC, 91aman commented
@erictleung Awesome thanks :)