Enable react/sort-prop-types rule
freeCodeCamp/freeCodeCamp pull request #12497
Opened 2017-01-12 21:42 UTC by Bouncey

Adds eslint rule `react/sort-prop-types` to enforce alphabetical sorting of propTypes

2017-01-16 21:13 UTC, BerkeleyTrue requested changes

2017-01-16 21:13 UTC, BerkeleyTrue commented on package.json
> +    "eslint-plugin-react": "^6.9.0",
This is already in the devDependencies

2017-01-30 19:03 UTC, BerkeleyTrue commented
@Bouncey Can you rebase this PR?

2017-02-18 18:06 UTC, Bouncey commented
@berkeleytrue just incase you didn't see the rebase

2017-02-27 22:00 UTC, merged