translated Getting Started in italian
freeCodeCamp/freeCodeCamp pull request #12500
Opened 2017-01-13 02:01 UTC by jlouiss

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of FreeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #12498 

#### Description
Completed translation for getting-started.json

2017-01-13 17:15 UTC, raisedadead commented
Thanks for pull request @jlouiss ! Can you get this peer reviewed with anyone? You can start by looking the chat rooms for people who would be interested.

2017-01-13 19:20 UTC, jlouiss commented
@raisedadead I already asked on gitter, I hope people will check the PR as soon as possible

2017-01-14 05:29 UTC, raisedadead commented
@jlouiss sure thing, we will wait for a week and post that we will merge after a sanity check if no one comes ahead for a review.

But, thanks a lot for your effort in bringing freeCodeCamp to more people. Cheers!

2017-01-17 19:38 UTC, Em-Ant requested changes
I think there are some small issues in your translation. Anyway, thanks for your help :+1:  :smile:

2017-01-17 19:38 UTC, Em-Ant commented on seed/challenges/00-getting-started/getting-started.json
> +              "Una gif mostrando come puoi cliccare sul tasto \"follow\" per seguire le pubblicazioni di Free Code Camp.",
"...una gif ~~mostrando~~ **che mostra** ..." it's better. What do you think ?

2017-01-17 19:38 UTC, Em-Ant commented on seed/challenges/00-getting-started/getting-started.json
> +          "title": "Configura il tuo portfolio da programmatore",
i didn't like the "portfolio codice" wording too !

2017-01-17 19:38 UTC, Em-Ant commented on seed/challenges/00-getting-started/getting-started.json
> +              "La nostra comunità ha uno spazio su Medium dove pubblica numerosi articoli pratici parlando di programmazione e di tecnologia. Una volta aperto il link, clicca sul tasto \"follow\" in
"...~~parlando~~ **che parlano**..." same as before. In Italian the "gerundio" verbal form is not used this way.

2017-01-19 00:31 UTC, jlouiss commented
I just committed the requested changes

2017-01-19 21:17 UTC, Em-Ant commented
@jlouiss @raisedadead  LGTM :+1:

2017-01-20 04:12 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @jlouiss @Em-Ant !

2017-01-20 04:12 UTC, merged