(beta) update links and formatting, project landing pages
freeCodeCamp/freeCodeCamp pull request #12821
Opened 2017-01-25 05:48 UTC by no-stack-dub-sack

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] curriculum update
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #12661

#### Description

@QuincyLarson  this PR addresses #12661:
- updates all project landing pages with correct test suite CDN link
- updates all project landing pages with correct test suite code pen links
- added Tree Map D3 project 
- added dataset links for all D3 projects

There's still a bit to be done with the landing pages, so we will need to open a separate issue for that and/or condense already existing issues

2017-01-25 21:35 UTC, raisedadead requested changes

2017-01-25 21:35 UTC, raisedadead commented on seed/challenges/03-front-end-libraries/front-end-libraries-projects.json
> +        "<strong>Note On Calculator Logic:</strong> It should be noted that there are two main schools of thought on calculator input logic: <dfn>immediate execution logic</dfn> and <dfn>formula logi
Break this into multiple lines:

![image](https://cloud.githubusercontent.com/assets/1884376/22309986/9995faaa-e373-11e6-94bb-ba2d376d3db4.png)

2017-01-25 21:35 UTC, raisedadead commented on seed/challenges/04-data-visualization/data-visualization-projects.json
> +        "Here is the dataset you will need to complete this project:<br><ul><li><code>https://raw.githubusercontent.com/FreeCodeCamp/ProjectReferenceData/master/GDP-data.json1</code></li></ul>",
Inconsistent bullet points

![image](https://cloud.githubusercontent.com/assets/1884376/22310105/076fbc5a-e374-11e6-8577-d2c11d05fe05.png)

2017-01-25 21:37 UTC, raisedadead commented
Do we really need bullet points, I am not a huge fan but this could just simply follow the same format as that of the previous JS and HTML challenges?

We already have less real estate, with the large font size. What do you think?

2017-01-25 23:55 UTC, no-stack-dub-sack commented
@raisedadead I'm ok with going no bullet points, I only did it there for consistency with the D3 projects that have multiple datasets which I felt needed them: 
![image](https://cloud.githubusercontent.com/assets/18563015/22314461/88353620-e32f-11e6-98d0-e08aeb5db0e9.png)

But I guess I could just leave them there where they make sense, and get rid of them everywhere else. Sound good? Or do you think I should just ditch them there too? I thought, for that one and the other with multiple, that it was important to let the user know what the particular dataset was for

2017-01-26 07:14 UTC, raisedadead commented
Yeah, I think the label on top of the resources is important. And I also agree that you should leave the bullet points where they make sense as in the example above.

2017-01-26 17:50 UTC, no-stack-dub-sack commented
@raisedadead ok, so I'll change it to be in only those challenges that have multiple datasets, and leave the rest without bullet points. I still think it looks a little funny, be was have bigger things to worry about for the time being so this will do for now.

2017-01-26 17:59 UTC, raisedadead commented
I think this needs a styling overhaul. but yeah if you could address the first comment about breaking the instructions to at least multiline, we can ignore the other aesthetics for now.

2017-01-27 04:40 UTC, no-stack-dub-sack commented
@raisedadead about to make a PR and I think this does it for now - added the multiline for the example like you said, and removed the bullets where they were not needed (from every challenge except D3 tree map and D3 choropleth where multiple datasets are needed)

Also, I definitely agree with you that these sections need an overall style overhaul 😄

2017-01-27 04:45 UTC, no-stack-dub-sack commented
@raisedadead WAIT! Don't merge this yet - looks like #12720 affects this entire section, so once that PR is merged, I will rebase off of that before this gets merged. Does that make sense or should the merge still go ok if this is merged first?

2017-01-27 06:21 UTC, raisedadead commented
Blocked for merge.

2017-01-28 07:50 UTC, raisedadead commented
@no-stack-dub-sack I have resolved a merge conflict with a PR that came in with another PR https://github.com/freeCodeCamp/freeCodeCamp/pull/12909

Can you please do a sanity check and let me know, for a merge?

Also we need not wait for #12720, it already has conflicts and should be resolved separately.

2017-01-28 07:50 UTC, raisedadead approved these changes

2017-01-28 16:41 UTC, no-stack-dub-sack commented
@raisedadead Yup, if all you changed is adding the closing `</a>` tags to resolve that conflict than LGTM!

2017-01-29 08:43 UTC, merged