Add arrow keys to navigate in step challenges
freeCodeCamp/freeCodeCamp pull request #12832
Opened 2017-01-25 14:05 UTC by systimotic

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #10056, I think

#### Description
Found this kind-of-old-but-fun issue. I was doing keyboard shortcut stuff today anyway, so I thought I'd go ahead and implement this.
Pressing the left arrow key goes to the previous slide, right arrow key goes to the next. If the next slide is blocked, you'll have to open the link first.
This is on `keyup` instead of `keydown`, so that you don't accidentally skip over a bunch of stuff by holding down the key.

I'm very, very new to React, so feedback would be awesome!

2017-01-30 19:05 UTC, BerkeleyTrue requested changes

2017-01-30 19:05 UTC, BerkeleyTrue commented on common/app/routes/challenges/components/step/Step.jsx
> +import MouseTrap from 'mousetrap';
Mousetrap capture is done in https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/client/sagas/mouse-trap-saga.js

You'll need to capture them there and then dispatch appropriate actions

2017-02-12 20:39 UTC, QuincyLarson commented
@systimotic what's the status of this PR? Have you had a chance to make the changes @BerkeleyTrue recommended?

2017-02-12 22:06 UTC, systimotic commented
@QuincyLarson I've had a hard time getting to work over the past two weeks. You might be able to tell from the activity on my profile that I didn't get a whole lot of things done 😞
I'm completely new to Redux, so I started reading up on it a bit. I'm still not quite sure how I should do this with Redux. I'm having a hard time finding time to learn more, but I definitely do want to learn more. Any links, tips and other advice would be amazing!

As it stands, it may take a little while before I have enough Redux knowledge to solve this issue the proper way.

2017-02-18 02:44 UTC, QuincyLarson commented
@systimotic I'm inexperienced with Redux myself. I would recommend asking @BerkeleyTrue or @Bouncey for help with this. It's not a super high priority, so take your time :)

2017-03-17 20:56 UTC, BerkeleyTrue commented
Looking at this code it is apparent that we should have some defined way to add mouse events to components themselves and leave the mousetrap epic as a place to put global key events.

Let me stew on this...

2017-09-02 01:15 UTC, BerkeleyTrue commented
Hey @systimotic 

We are going to need to rethink how we implement mousetrap in the codebase. I think I haven't expressed how mousetrap bindings should be added at the component level. This is unfortunately a low priority as we try to get beta launched. 

We are closing as many issues and PR's as possible to clear up the debt we have incurred so I'm closing this.

2017-09-02 01:15 UTC, closed without merging

2017-09-02 01:16 UTC, manzilo commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (104/100 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60187 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2w-0003QV-RI
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:26 -0400
Received: from o4.sgmail.github.com ([192.254.112.99]:48383)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx2r-0001rs-6V
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:21 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=g828FwueKsFdSlqUxk2KYj2+kd8=; b=toFqlSW9thsh6+EJ
	mYZERA8QfxotTwcMBlw2zY+j2dcpQsBY7IeAlnRNTL6UWxu81AZeZlMQA++mMraR
	5Hc0VXv8d8ZvR8EcmJ5GMzuyHLyMBqFhXhKByKhQNXR6PvABLO21LQLYcYd+G35E
	29/CD+ZGD278MT3JTqoI6MAPDg8=
Received: by filter1177p1mdw1.sendgrid.net with SMTP id filter1177p1mdw1-8682-59AA0663-7
        2017-09-02 01:16:19.239855325 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0040p1mdw1.sendgrid.net (SG) with ESMTP id AbPCdBblTkWjYcX_VJ2xyg
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:19.157 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:19 +0000 (UTC)
From: Berkeley Martinez <notifications@github.com>
Reply-To: freeCodeCamp/freeCodeCamp <reply@reply.github.com>
To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <freeCodeCamp/freeCodeCamp/pull/12832/c326712583@github.com>
In-Reply-To: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
References: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
Subject: Re: [freeCodeCamp/freeCodeCamp] [WIP] Add arrow keys to navigate in
 step challenges (#12832)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_59aa065c80a59_27303fa003af5c3421056f";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: BerkeleyTrue
X-GitHub-Recipient: manzilo
X-GitHub-Reason: subscribed
List-ID: freeCodeCamp/freeCodeCamp <freeCodeCamp.freeCodeCamp.github.com>
List-Archive: https://github.com/freeCodeCamp/freeCodeCamp
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+00bd4a0a9125a0528ebe475b9ce6715afd5512d67c21094d92cf0000000115c1c85c92a169ce0c1b3c0a@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AL1KCtJQm3k8sHvKS94K8cOm3H7VYjwuks5seKxcgaJpZM4LthUs>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: manzil@funtasticlabs.com
X-SG-EID: 83UmH9Yz2HjU1qKK7JE10vR6ZA73mzRCr3l9ny8S/eHoAauBYeFxDQhg5N2CNuwLVQ63BfjDgoLFlM
 bLNUVzVJxWi2FB9J3nlOTcF4pyceumhasRpioXcmXSL6zCLj/UwG21Or8/EzmHojB1dV8hxFKBpA1t
 zt359gif4dRz8F0gpthOl0tNtZjg43toL8dkUGOJuqRcJhmrne9UboWqDzOiZ66N4zDtLLa/LadFAf
 w=
X-MAILIN-01-MailScanner-Information: Please contact the ISP for more information
X-MAILIN-01-MailScanner-ID: 1dnx2r-0001rs-6V
X-MAILIN-01-MailScanner: Found to be clean
X-MAILIN-01-MailScanner-SpamCheck: not spam, SpamAssassin (not cached,
	score=-1.773, required 10, AWL 0.23, BAYES_00 -1.90,
	HTML_IMAGE_ONLY_28 1.40, HTML_MESSAGE 0.00, KHOP_THREADED -1.50,
	SPF_PASS -0.00, T_RP_MATCHES_RCVD -0.01, URIBL_BLOCKED 0.00)
X-MailScanner-From: bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com
X-Spam-Status: No


----==_mimepart_59aa065c80a59_27303fa003af5c3421056f
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hey @systimotic 

We are going to need to rethink how we implement mousetrap in the codebase. I think I haven't expressed how mousetrap bindings should be added at the component level. This is unfortunately a low priority as we try to get beta launched. 

We are closing as many issues and PR's as possible to clear up the debt we have incurred so I'm closing this.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/freeCodeCamp/freeCodeCamp/pull/12832#issuecomment-326712583
----==_mimepart_59aa065c80a59_27303fa003af5c3421056f
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<p>Hey <a href=3D"https://github.com/systimotic" class=3D"user-mention">@sy=
stimotic</a></p>
<p>We are going to need to rethink how we implement mousetrap in the codeba=
se. I think I haven't expressed how mousetrap bindings should be added at t=
he component level. This is unfortunately a low priority as we try to get b=
eta launched.</p>
<p>We are closing as many issues and PR's as possible to clear up the debt =
we have incurred so I'm closing this.</p>

<p style=3D"font-size:small;-webkit-text-size-adjust:none;color:#666;">&mda=
sh;<br />You are receiving this because you are subscribed to this thread.<=
br />Reply to this email directly, <a href=3D"https://github.com/freeCodeCa=
mp/freeCodeCamp/pull/12832#issuecomment-326712583">view it on GitHub</a>, o=
r <a href=3D"https://github.com/notifications/unsubscribe-auth/AL1KCsmI37xb=
dhWZilU-UPM6FhT3p6Fiks5seKxcgaJpZM4LthUs">mute the thread</a>.<img src=3D"h=
ttp://www.mailscanner.tv/1x1spacer.gif" width=3D"1" height=3D"1" alt=3D"Web=
 Bug from https://github.com/notifications/beacon/AL1KCk4E5q6ZqS2QnFGDzMAb7=
eu3Nwwoks5seKxcgaJpZM4LthUs.gif" /></p>
<div itemscope itemtype=3D"http://schema.org/EmailMessage">
<div itemprop=3D"action" itemscope itemtype=3D"http://schema.org/ViewAction=
">
  <link itemprop=3D"url" href=3D"https://github.com/freeCodeCamp/freeCodeCa=
mp/pull/12832#issuecomment-326712583"></link>
  <meta itemprop=3D"name" content=3D"View Pull Request"></meta>
</div>
<meta itemprop=3D"description" content=3D"View this Pull Request on GitHub"=
></meta>
</div>

<MailScannerScript7215 script type=3D"application/json" data-scope=3D"inbox=
markup">{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767=
c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeCodeCamp/=
freeCodeCamp","title":"freeCodeCamp/freeCodeCamp","subtitle":"GitHub reposi=
tory","main_image_url":"https://cloud.githubusercontent.com/assets/143418/1=
7495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https=
://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9a=
ed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://githu=
b.com/freeCodeCamp/freeCodeCamp"}},"updates":{"snippets":[{"icon":"PERSON",=
"message":"@BerkeleyTrue in #12832: Hey @systimotic \r\n\r\nWe are going to=
 need to rethink how we implement mousetrap in the codebase. I think I have=
n't expressed how mousetrap bindings should be added at the component level=
. This is unfortunately a low priority as we try to get beta launched. \r\n=
\r\nWe are closing as many issues and PR's as possible to clear up the debt=
 we have incurred so I'm closing this."}],"action":{"name":"View Pull Reque=
st","url":"https://github.com/freeCodeCamp/freeCodeCamp/pull/12832#issuecom=
ment-326712583"}}}</MailScannerScript7215>=

----==_mimepart_59aa065c80a59_27303fa003af5c3421056f--

2017-09-02 01:16 UTC, manzilo commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60215 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx3G-0003TI-KK
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:46 -0400
Received: from o7.sgmail.github.com ([167.89.101.198]:47088)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx37-0001sy-AS
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:16:37 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=xbFktHKZjoJr0cgJ6f09vKP5oXI=; b=Pfom3e42nm4PJ5cR
	ImWcafXXalXiQFZ/ybez72KBtVJTSYleYh907YepMLxc/f8i493aRioHQimOgz9K
	CbIutiFx5NfBAQEDIfzAhI5JcW8QqzID3ca2dkVme3Rjc88//zcLySrRNmFpjsGS
	yDdTE6ABSgMLhvs36nL0TlnBoHw=
Received: by filter0086p1las1.sendgrid.net with SMTP id filter0086p1las1-31759-59AA0674-33
        2017-09-02 01:16:36.289857014 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id GI2iXs1wRIKCdCP-Udl2DQ
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:16:36.211 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:36 +0000 (UTC)
From: Berkeley Martinez <notifications@github.com>
Reply-To: freeCodeCamp/freeCodeCamp <reply@reply.github.com>
To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <freeCodeCamp/freeCodeCamp/pull/12832/issue_event/1232190212@github.com>
In-Reply-To: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
References: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
Subject: Re: [freeCodeCamp/freeCodeCamp] [WIP] Add arrow keys to navigate in
 step challenges (#12832)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_59aa06731a983_5ef23f999d113c3c229387";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: BerkeleyTrue
X-GitHub-Recipient: manzilo
X-GitHub-Reason: subscribed
List-ID: freeCodeCamp/freeCodeCamp <freeCodeCamp.freeCodeCamp.github.com>
List-Archive: https://github.com/freeCodeCamp/freeCodeCamp
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+00bd4a0ac29db399e1f1c35ffcab1dc26e3965362499a4ab92cf0000000115c1c87392a169ce0c1b3c0a@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AL1KCg5EeYhAlf4INiqWeQwrpeJ806Kdks5seKxzgaJpZM4LthUs>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: manzil@funtasticlabs.com
X-SG-EID: 83UmH9Yz2HjU1qKK7JE10vR6ZA73mzRCr3l9ny8S/eG/ewx5+4L5I7T8ei4Q2FOmuJHYujvOjzs9nv
 zqLSLzjy4HwIYJbI0pNFWyWVqCd7w/j75z7VIAEc+j/uEx1RCQrzOj55R4NcLq6/im7loypl0JdbFJ
 OFUe1qlLd4DNn12yqtGxJCLJdSIh4BTjK/Ig5gyc+ujR7mDkmojJPznvS5hbLmhrH1fbsL88/wrJY5
 o=
X-MAILIN-01-MailScanner-Information: Please contact the ISP for more information
X-MAILIN-01-MailScanner-ID: 1dnx37-0001sy-AS
X-MAILIN-01-MailScanner: Found to be clean
X-MAILIN-01-MailScanner-SpamCheck: not spam, SpamAssassin (not cached,
	score=-1.665, required 10, AWL 0.13, BAYES_00 -1.90,
	HTML_IMAGE_ONLY_24 1.62, HTML_MESSAGE 0.00, KHOP_THREADED -1.50,
	SPF_PASS -0.00, T_RP_MATCHES_RCVD -0.01, URIBL_BLOCKED 0.00)
X-MailScanner-From: bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com
X-Spam-Status: No


----==_mimepart_59aa06731a983_5ef23f999d113c3c229387
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Closed #12832.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/freeCodeCamp/freeCodeCamp/pull/12832#event-1232190212
----==_mimepart_59aa06731a983_5ef23f999d113c3c229387
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Closed <a href="https://github.com/freeCodeCamp/freeCodeCamp/pull/12832" class="issue-link js-issue-link" data-url="https://github.com/freeCodeCamp/freeCodeCamp/issues/12832" data-id="203111434" data-error-text="Failed to load issue title" data-permission-text="Issue title is private">#12832</a>.</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br />You are receiving this because you are subscribed to this thread.<br />Reply to this email directly, <a href="https://github.com/freeCodeCamp/freeCodeCamp/pull/12832#event-1232190212">view it on GitHub</a>, or <a href="https://github.com/notifications/unsubscribe-auth/AL1KCu51jhc2ng3plizrSMllabhjLYEiks5seKxzgaJpZM4LthUs">mute the thread</a>.<img src="http://www.mailscanner.tv/1x1spacer.gif" width="1" height="1" alt="Web Bug from https://github.com/notifications/beacon/AL1KCl8OiLuFJoXj0vz69QrJH1dfsqQvks5seKxzgaJpZM4LthUs.gif" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/freeCodeCamp/freeCodeCamp/pull/12832#event-1232190212"></link>
  <meta itemprop="name" content="View Pull Request"></meta>
</div>
<meta itemprop="description" content="View this Pull Request on GitHub"></meta>
</div>

<MailScannerScript7275 script type="application/json" data-scope="inboxmarkup">{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/freeCodeCamp/freeCodeCamp","title":"freeCodeCamp/freeCodeCamp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/freeCodeCamp/freeCodeCamp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #12832."}],"action":{"name":"View Pull Request","url":"https://github.com/freeCodeCamp/freeCodeCamp/pull/12832#event-1232190212"}}}</MailScannerScript7275>
----==_mimepart_59aa06731a983_5ef23f999d113c3c229387--

2017-09-02 01:17 UTC, pawan-mehta commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (104/100 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f44.google.com ([209.85.218.44]:32804)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx3f-003kmR-CH
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:47:25 +0530
Received: by mail-oi0-f44.google.com with SMTP id r203so13969317oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:16:51 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=NYNPrLx3burzmY2ZnXrwLm3N5kS7E2TqEETU3fcnNvQ=;
        b=SB0NlOVSzSBNfXuztv7jsqwHqGlWTNYm4XPw07RL919wSksSZqYZHzRGqKL7xY6aQ0
         vXsFqgdot1qiyDlGCUfIhU32y3qkG+ObSXBN5178FcC8D5+IJvg1kN+jvyZf28CGeTeP
         TOL5Ne6ckCnS0s526/Ibv61t2w7gl9pcOY6QSfhFLZaqT1ZOt36eYi9dWAwJcbZlLuuj
         N7ON+OZqe3OwCwx9jjjrgAyWJLTqows33knBlN/Rvj4tm3P3yC8KvHx1lxkV/Dc2BNhX
         /MjKE07ghH/fhY7Gsiuk9+I2/Jqt006Ep+Ku7ULh0Wk9/u5L/v0+MU9/aSiGdK4ymv6t
         p3EQ==
X-Gm-Message-State: AHPjjUgiy0C1oQ4RlPM38vCRQgXOO6tZl0SUB+VKYy3vDdECyG/r4knq
	3QthO8fKzoECQH7sFAl0lvbub0uwTArYh5HsNIpjdg==
X-Received: by 10.202.72.17 with SMTP id v17mr3297136oia.129.1504314989165;
        Fri, 01 Sep 2017 18:16:29 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352724ofe;
        Fri, 1 Sep 2017 18:16:28 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb4MQ8+Y4sJG4baOrg8fEbno3Ohxr1vFsCSRx+NFlTObvhL+bFY1LdDevUlCRTrJ0DwvylBp
X-Received: by 10.84.141.1 with SMTP id 1mr4694920plu.189.1504314988026;
        Fri, 01 Sep 2017 18:16:28 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504314988; cv=none;
        d=google.com; s=arc-20160816;
        b=txJUyTUVdVlL/bM+1bQg6pCrxuxO4NTMUm7X7O9T5HkA98Sad/nX7ULg3tRi7Gm4KE
         yh59lo6fMY5M7DRbJfhMg7nMjmIER2CzY8LMwCt761m+YsT11t7YAcmwekTfetZiiqFS
         sD6B2gAor94OmcuNQ2377N06vAUJ8bNjBLCI/b1awGiIeZKhKL7+Qu1e13QyKUwS9h8V
         AqAMzX7fXxP/vYhddvCoD0laQv+aTG2DCMQqEswnSyxyg0vuhwgYnLvQE3pLl2dH1jqK
         SW6qQWjq/dCyl0Jz+5rOot2qTL0z9zhac0bz+tNqLYbciExDzoKNh5Nc1Z3AaUaEh80S
         xW8Q==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=NYNPrLx3burzmY2ZnXrwLm3N5kS7E2TqEETU3fcnNvQ=;
        b=CaJmZSsdIPq3xxzcobTLXkY5BB9fY3wLW60kYiDIexHb3xBnot4ROK+soazachbG4T
         RjTrts0zMwnnlvRdfkl/DHx6WGRPQ86cgqRI+rNehOa4oA6SXH2lhcBkVUIiuQzaw5M2
         koP5UOhea3oO5y9boJvf++eFgtJAveCVPmU6lbfrysMdh9tToJxY98aRW5s8P3f6mjVX
         49WogeT/H+plFRObbqsYjf9Y8cGj+I/dshth8GBJ8wDlqxBwceQ02dmstXlqxXhLtYaT
         r4sfMSICHoxALozU+6v+6DAr1VasGoo9Ki1HoNjLqwFzA1NEGY64VBW150RdtNtaksQ8
         lKyA==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=SLEZiOj3;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=fWlR8e0j;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o8.sgmail.github.com (o8.sgmail.github.com. [167.89.101.199])
        by mx.google.com with ESMTPS id t206si1073450pgb.315.2017.09.01.18.16.27
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:28 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) client-ip=167.89.101.199;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=SLEZiOj3;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=fWlR8e0j;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.199 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=aaRuhp0sgk8anR6/f+KlIs6tPOs=; b=SLEZiOj36lKLlga4
	P2hreYw+Ax6KdiYn5nNoGZLRhNW/+YKd4pHQc6C5k9iRtywUan1OzQG13B+c1r1K
	GP+Qn68jLplRJBrisHeONZJS5VUgGMFDP+6mB9uiI+zufSFbTDMb9XV1NmFwvlM3
	ABPl1a+eU4W5c69P8phEXXJF7do=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=aaRuhp0sgk8anR6/f+KlIs6tPOs=; b=fWlR8e0jfq9kxgdi3w
	onoQnji1SC9JR/f3D/+v+7rjPRDsiIEWzQcppQ/aNxplLMOCJpPDJauvwee2WWlO
	quqSCR817zhQuDedwLRXEX3yVB0YYJXgjvaKf5br4FFizV8Y1sAe5rhhkyUdC5iK
	skfFgK8voX8fY72tV4+3MiW/c=
Received: by filter0155p1las1.sendgrid.net with SMTP id filter0155p1las1-9627-59AA066B-24
        2017-09-02 01:16:27.573488663 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id zM6MXdMTQAyBTk2_tGrLZQ
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:27.477 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:27 +0000 (UTC)
From: Berkeley Martinez <notifications@github.com>
Reply-To: freeCodeCamp/freeCodeCamp <reply@reply.github.com>
To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <freeCodeCamp/freeCodeCamp/pull/12832/c326712583@github.com>
In-Reply-To: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
References: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
Subject: Re: [freeCodeCamp/freeCodeCamp] [WIP] Add arrow keys to navigate in
 step challenges (#12832)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_59aa066741d5e_27303fa003af5c342324e3";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: BerkeleyTrue
X-GitHub-Recipient: pawan-mehta
X-GitHub-Reason: subscribed
List-ID: freeCodeCamp/freeCodeCamp <freeCodeCamp.freeCodeCamp.github.com>
List-Archive: https://github.com/freeCodeCamp/freeCodeCamp
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+00cf52080a0cb72ed0f235d42340f9d837aa613a70a7020792cf0000000115c1c86792a169ce0c1b3c0a@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AM9SCFlSm_q6epTTk6M4gpW1JxaH1WK0ks5seKxngaJpZM4LthUs>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: pawan.ossindia@gmail.com
X-SG-EID: OpfRgdkK9YQWPKIAgM5UQUoN56mCdWNmGtfFv0Mnvk3/L8NG+gg0yi4qnYVlT6dAoLUZa9tITW6YDH
 DRXv+ylDGfTZul+Gn4zwpTijnfM0cvqdXZz2ZTY1ZrUuRgbyJ4W49S8 [...]

2017-09-02 01:18 UTC, pawan-mehta commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f41.google.com ([209.85.218.41]:32895)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx42-003n05-HN
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:48:09 +0530
Received: by mail-oi0-f41.google.com with SMTP id r203so13972473oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:17:14 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=AIdTKePLR51n2O3ogEg7cVSlkfuFjvLGYj/E2HjVSLA=;
        b=pygRWyv6yTwzIvUeuPJuyDPo6AWbh9dUZVRRlvnHDMbEVxkpcPeODH8PsW5JTZDlHb
         YqGFaQ7zuDoe2sIo6LnMc0N5XhFD74Z80Er2fi1HlqWLpPURc3jF76VsQxhAElzp5G0b
         +J0fZMVtKMtBeVcHT5EueDoA+loUsgIzlfmzQrhw0Dz7PlTwTWQrVekbIpUgA7wPnOxk
         k+UDfDHfiU7rHIZoVtn14yDUnSGjNgrudzdqBeWdTIsBzVZTKIJxr8IPtpZmNYAxwXRt
         3HmeRg48OPCPGaBaKiVLHkprAQoRee25Pmcqkd14IQYnalwFgPdwS+h8gfqQ3pW9/tvg
         OyGw==
X-Gm-Message-State: AHPjjUjfMmb1ax7dSbTJQvTj7jBCCrn6u9+Cvm47a1dNY4gLnS6oCxQt
	FH9WyssOgHrbE3yAVz8gyAmBbuy56ttGqyDqHADq3A==
X-Received: by 10.202.4.130 with SMTP id 124mr4144424oie.246.1504315012093;
        Fri, 01 Sep 2017 18:16:52 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352951ofe;
        Fri, 1 Sep 2017 18:16:51 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb5KFWcsdwixabzSK18YKjx3etz+zLVP44LKdvubRllXwhCxO8dhir/nzYt2G1iHSgLNP9ev
X-Received: by 10.84.194.195 with SMTP id h61mr4548056pld.371.1504315011382;
        Fri, 01 Sep 2017 18:16:51 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315011; cv=none;
        d=google.com; s=arc-20160816;
        b=lDoFzApNVUV9v/A+6//L68ggJs3vt2F6IVA91mfSI5Si8KAc1ycRV1WF5jkK1pQu7I
         HE3ZhnU8T0Kk0egHWB2OrS3t4g//F5qvJgd1C97nZlpgxGVQ98+QkfWVIhyRpPUUk9BX
         oQ1MoCYeD3w4rQeIsq0kVsyHyMYM8mjuQs5829M58jey2yBRLBBCITFUbQJRVkVOCQLi
         0mXBL+jbzB5f3OMLqMb/DYqjRhSEFo7G8gXHyRNRz9Cvn9/jgMfj1qoEAPE0sZDF9ASG
         paVGlqEmQSQ5UqfY+M/Q76ZpEe0QjOV2Hf2R+GLMt9A6MLhfO0UFw2TSLpvjpKYRRjp7
         mk4w==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=AIdTKePLR51n2O3ogEg7cVSlkfuFjvLGYj/E2HjVSLA=;
        b=sfgi9uB4x/eEI96AMpO+Sd/VPx1sSWn+fpOfX+AnDVGaC1Ly/gTF3S95SkQI1WypID
         MMF6M03C40TBIWFn59HTk6bbsYzPxYyH6mqIbol7sDKawbLOxuOUX/vJirdoQM6ODxUj
         p4yHeDa6zchu9ltZYdc9ZrF2Fv/iOhZkm9jXvGpcWKzCHAzt6t7J6ZwXwzII5h/8iPdW
         TkbxkOpXix7pAaPrKBEm6xju0FN3Z2zXKBTX+ck2jV3HCAwzqamWi6EA//kFGKpcWFQO
         Dq6upAnrEAyzsc+0lfOmh9DMYaiCXBQQqL1177+uKsKlvqWZwXiBnzBnwSulOEjpjVju
         n5pg==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=Qc7GmsVm;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=vV2igLN8;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from o11.sgmail.github.com (o11.sgmail.github.com. [167.89.101.202])
        by mx.google.com with ESMTPS id t191si1062252pgc.726.2017.09.01.18.16.50
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:16:51 -0700 (PDT)
Received-SPF: pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) client-ip=167.89.101.202;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@github.com header.s=s20150108 header.b=Qc7GmsVm;
       dkim=pass header.i=@sendgrid.info header.s=smtpapi header.b=vV2igLN8;
       spf=pass (google.com: domain of bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com designates 167.89.101.202 as permitted sender) smtp.mailfrom=bounces+848413-3702-pawan.ossindia=gmail.com@sgmail.github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=9QRq3GL/H/EyzvtcW97/vb367+4=; b=Qc7GmsVm6LWedXor
	1oIwzVyyoaRRwkFDjHRvZCN6lknxLW8jr5v5jxZQ8co57Fo5jnMit5Che31yDHhS
	5S5elOdgO8FkgRSGpXoufpQWvVNEfSYX4qFgrbunCMlOSku1/CbV2DZhIwvDe7Ct
	Me84+vIRMFpv06DC679vK2oWKOw=
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=sendgrid.info; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe:x-feedback-id; 
	s=smtpapi; bh=9QRq3GL/H/EyzvtcW97/vb367+4=; b=vV2igLN8VFgSLTLlOD
	MNI9gaVPCmyW+ChMY8vGLQlHbNdu8Q6tGV+dHa/bnmCjckBnuuvOAkjGc/GTse5F
	mTSZt+e5riiIOSCt9193xjqHnhEi+M23WMBaX4C2umnel13fjSL2KS9ENZfW+E8C
	QGtIRfuN/ZopuuC8RXdRxaWLQ=
Received: by filter0244p1las1.sendgrid.net with SMTP id filter0244p1las1-23473-59AA0682-A
        2017-09-02 01:16:50.203608188 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id DdoWqf0TSJKPtKGY1u9JRA
	for <pawan.ossindia@gmail.com>; Sat, 02 Sep 2017 01:16:50.091 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:16:50 +0000 (UTC)
From: Berkeley Martinez <notifications@github.com>
Reply-To: freeCodeCamp/freeCodeCamp <reply@reply.github.com>
To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <freeCodeCamp/freeCodeCamp/pull/12832/issue_event/1232190212@github.com>
In-Reply-To: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
References: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
Subject: Re: [freeCodeCamp/freeCodeCamp] [WIP] Add arrow keys to navigate in
 step challenges (#12832)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_59aa0680ea066_5ef23f999d113c3c25146b";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: BerkeleyTrue
X-GitHub-Recipient: pawan-mehta
X-GitHub-Reason: subscribed
List-ID: freeCodeCamp/freeCodeCamp <freeCodeCamp.freeCodeCamp.github.com>
List-Archive: https://github.com/freeCodeCamp/freeCodeCamp
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+00cf5208910b95578d51d6f9bc0981956adb765f14ae29a092cf0000000115c1c88092a169ce0c1b3c0a@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AM9SCLm-hz0NeVBkuZloAMHabDh9k-I2ks5seKyAgaJpZM4LthUs>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: pawan.ossindia@gmail.com
X-SG-EID: OpfRgdkK9YQWPKIAgM5UQUoN56mCdWNmGtfFv0Mnvk1NEbhU+MBL4zB4yTrcDqhaSi4aGIcXGjV4MY
 dM5RReJsrgPH2D5pVg6sKKMvnkTmDnp5x5Xt8 [...]

2017-09-02 01:20 UTC, pawan-mehta commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (121/100 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 28300 characters long; only the first
------ 5000 or so are included here.
Received: from mail-oi0-f51.google.com ([209.85.218.51]:33937)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx6U-003urj-9m
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:50:21 +0530
Received: by mail-oi0-f51.google.com with SMTP id w10so13917235oie.1
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:19:45 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:date:dkim-signature:from:reply-to
         :to:cc:message-id:in-reply-to:references:subject:mime-version
         :content-transfer-encoding:precedence:list-id:list-archive:list-post
         :list-unsubscribe;
        bh=KjPF6ZPA2mTxqBBENl/PYOxCgK7leRzj1nflVnSW+rU=;
        b=sJR2kMHXguM3SDYsRAu85KAC3QD+y8HUocxPSz26r/gm8/USNFkxJdJ5Q2vfI/XIsq
         Wn9sBKNXkIn7md0WqmOU9HRmtChnH03rl+fH2zyGSjRw96srrIERLa0h2KsfhzU/ZkK1
         FBx60H9AEomFYr7wvdVuVB7J63PQaOgQv7O0zfibjDTqtlRc/IjEzZkGVUt01pP64C2w
         /dB8Wukz5/hoioLfhN7Oo+29K1UefWkqvM2+h++QchUD0lOJd3z7c9jNekdvs3v132Qn
         IUVVEhHkAv+bIGA0/H9cbQesD+K8k68MsfHGNtejUp0mKTfYNN/0rav5bYjjtVdDiukl
         rrBw==
X-Gm-Message-State: AHPjjUjCZNqjhH6aAX6SyZr0HIvKdbalJGSPndLhv+bfS5OjnOy/fSsq
	vIc7fHNjq2P1KnU/J3r27N/4ycs+X3UCZDs83anAFw==
X-Received: by 10.202.84.6 with SMTP id i6mr3779983oib.221.1504315163430;
        Fri, 01 Sep 2017 18:19:23 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1354386ofe;
        Fri, 1 Sep 2017 18:19:22 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb50xBlbV/fNUoA3pqut1OmK+O7Zeev8jvFqrktgFjJiS2po7yZFgftrlr5sXNso0CDLE+XD
X-Received: by 10.55.212.4 with SMTP id l4mr5385782qki.147.1504315162182;
        Fri, 01 Sep 2017 18:19:22 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315162; cv=none;
        d=google.com; s=arc-20160816;
        b=HT6ZuRF4iF9FQApSYz/Hbwsej87i2uwFudRo4F1DJzJwGHwI6vGk2q3dj7R5lGcztZ
         4O+6la9+WlXO4JeFYeKL7LxRXL5FS97G21XCpYe3iL+yLgciq4RWY1T8wfy4sfoIFfli
         HaH4Jpf3qhQTGLm+kneblYZMC3YghZxZBaWhhrCm8ZMu9gbA+QkbQ9P4QGhrUTUBJHtK
         0DoRgp5lm2N7vBusThr/3HlDlae4NEYINqGbarRZnFmqb75J03dL8hGUWdJ/JyEYSR7s
         rEQBhMhIDa/S3BYNELzu9L7AnIqefmg1ax5HU7NojqtsKvB6WTli8lUNaolSzaicp8Jw
         p7Lw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:dkim-signature:date
         :arc-authentication-results;
        bh=KjPF6ZPA2mTxqBBENl/PYOxCgK7leRzj1nflVnSW+rU=;
        b=ioWEtxNj/mkaduO40RL2TfVcG2e4mcpCRQd7ddaZSQ0DgUROwFV+UNhL1ow+7BRai2
         eSGm/cD/pCvexW/DKHWFCgr9kI4sFVKh2k1KsXA9IXvgZgWzFcpcLF0JyEMGiwB87X6U
         ytZlUkbOao39fqHial74psCIFKXr5bOv7aVBNHRuvaEP95aXdMkceNFAAcQOn1dNR8aY
         a4PVuvt1Ff9pmPYHQ8iesXMjZsdJB56SqzLo0jZgTKsy8wEYNEU9zvwYH6LNgjC6CJ41
         /U3F5CZ4f9NjSibpv0gd3SF6sHPLPga3C0L7CJ76YvM2xtYHQF/v0uEP/k0o0biVEwRv
         U7BQ==
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=qC9EXopY;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.196 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2-ext5.iad.github.net. [192.30.252.196])
        by mx.google.com with ESMTPS id 11si131465qko.194.2017.09.01.18.19.22
        for <pawan.ossindia@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Fri, 01 Sep 2017 18:19:22 -0700 (PDT)
Received-SPF: pass (google.com: domain of noreply@github.com designates 192.30.252.196 as permitted sender) client-ip=192.30.252.196;
Authentication-Results: mx.google.com;
       dkim=pass (test mode) header.i=@github.com header.s=pf2014 header.b=qC9EXopY;
       spf=pass (google.com: domain of noreply@github.com designates 192.30.252.196 as permitted sender) smtp.mailfrom=noreply@github.com;
       dmarc=pass (p=NONE sp=NONE dis=NONE) header.from=github.com
Date: Fri, 01 Sep 2017 18:19:14 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1504315161;
	bh=KjPF6ZPA2mTxqBBENl/PYOxCgK7leRzj1nflVnSW+rU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qC9EXopY1MqqdGdEnJAibF7i9F5bqHczKxyQSH8U3fj8dcVoAE261+V1fvJ+LJTu1
	 viDDio80puXMU2E5NbnmQBNUlmgfqYULIfDGmg5Xv9BmIwO2a/n82UyY0IengSwh8p
	 y6NkjzNj9K3SXgs7kp3QRFb7uwBovBd23pIRusvg=
From: Manzil <notifications@github.com>
Reply-To: freeCodeCamp/freeCodeCamp <reply@reply.github.com>
To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Message-ID: <freeCodeCamp/freeCodeCamp/pull/12832/c326712658@github.com>
In-Reply-To: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
References: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
Subject: Re: [freeCodeCamp/freeCodeCamp] [WIP] Add arrow keys to navigate in
 step challenges (#12832)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_59aa0712918d4_3a2f3fda6c3d7c3820038f";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: manzilo
X-GitHub-Recipient: pawan-mehta
X-GitHub-Reason: subscribed
List-ID: freeCodeCamp/freeCodeCamp <freeCodeCamp.freeCodeCamp.github.com>
List-Archive: https://github.com/freeCodeCamp/freeCodeCamp
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+00cf5208dbbd7615c275173321339aeeadc473d6de9e80c992cf0000000115c1c91292a169ce0c1b3c0a@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AM9SCFSSI3DiVINJloJRIp1ohDjUyYyoks5seK0SgaJpZM4LthUs>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: pawan.ossindia@gmail.com
X-Spam-Status: No, score=0.2
X-Spam-Score: 2
X-Spam-Bar: /
X-Ham-Report: Spam detection software, running on the system "server14.hostingraja.in",
 has NOT identified this incoming email as spam.  The original
 message has been attached to this so you can view it or label
 similar future email.  If you have any questions, see
 root\@localhost for details.
 
 Content preview:  This message was created automatically by mail delivery software.
    A message that you sent could not be delivered to one or more of its recipients.
    This is a temporary error. The following address(es) deferred: [...] 
 
 Content analysis details:   (0.2 points, 5.0 required)
 
  pts rule name              description
 ---- ---------------------- --------------------------------------------------
  0.0 URIBL_BLOCKED          ADMINISTRATOR NOTICE: The query to URIBL was blocked.
                             See
                             http://wiki.apache.org/spamassassin/DnsBlocklists#dnsbl-block
                              for more information.
                             [URIs: mailscanner.tv]
  0.0 HEADER_FROM_DIFFERENT_DOMAINS From and EnvelopeFrom 2nd level mail
                             domains are different
  0.0 T_SPF_TEMPERROR        SPF: test of record failed (temperror)
  0.0 HTML_MES [...]

2017-09-02 01:21 UTC, manzilo commented
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  manzil@gmail.com
    Domain funtasticlabs.com has exceeded the max emails per hour (123/100 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 45381 characters long; only the first
------ 5000 or so are included here.
Received: from mailin-01.elitehosts.com ([108.60.141.228]:60380 helo=offsite.elitehosts.com)
	by neo.internetwebserver.net with esmtp (Exim 4.87)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx7a-0004iK-8a
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:21:14 -0400
Received: from o11.sgmail.github.com ([167.89.101.202]:55483)
	by offsite.elitehosts.com with esmtp (Exim 4.69)
	(envelope-from <bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com>)
	id 1dnx6x-00024Z-9O
	for manzil@funtasticlabs.com; Fri, 01 Sep 2017 21:20:41 -0400
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=85xkaQXcCzue/Lq9XHqJ14D/91E=; b=JrawQ3oWNrzmd6uF
	nZLHNxihiJ6ImJIXE02xIsJRMIS30pFwUrElQEV5rqyF70rLmNgn+6o0JVcH4ePb
	PoxVQaHUolHdc3oh8N7aYHkR0XJ9QduQZYLXr2CnCUUDrdSVUB5dPoKRJK+M0FtI
	6oVxfvTPkk6s2QiHUHWLNObCvX0=
Received: by filter0550p1las1.sendgrid.net with SMTP id filter0550p1las1-11909-59AA0760-E
        2017-09-02 01:20:32.855500862 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id OUFoCZClRSOYSEY76aQgnw
	for <manzil@funtasticlabs.com>; Sat, 02 Sep 2017 01:20:32.754 +0000 (UTC)
Date: Sat, 02 Sep 2017 01:20:32 +0000 (UTC)
From: Pawan Mehta <notifications@github.com>
Reply-To: freeCodeCamp/freeCodeCamp <reply@reply.github.com>
To: freeCodeCamp/freeCodeCamp <freeCodeCamp@noreply.github.com>
Cc: Manzil <manzil@funtasticlabs.com>, 
 Comment <comment@noreply.github.com>
Message-ID: <freeCodeCamp/freeCodeCamp/pull/12832/c326712803@github.com>
In-Reply-To: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
References: <freeCodeCamp/freeCodeCamp/pull/12832@github.com>
Subject: Re: [freeCodeCamp/freeCodeCamp] [WIP] Add arrow keys to navigate in
 step challenges (#12832)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_59aa07594ea94_25d673ff80b451c38154945";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: pawan-mehta
X-GitHub-Recipient: manzilo
X-GitHub-Reason: comment
List-ID: freeCodeCamp/freeCodeCamp <freeCodeCamp.freeCodeCamp.github.com>
List-Archive: https://github.com/freeCodeCamp/freeCodeCamp
List-Post: <mailto:reply@reply.github.com>
List-Unsubscribe: <mailto:unsub+00bd4a0a7aaa93992f3781628766ff8b3f4167bbbe00426192cf0000000115c1c95992a169ce0c1b3c0a@reply.github.com>,
 <https://github.com/notifications/unsubscribe/AL1KCvOEu_-W76VnSRhOgm1hMDv-Cbf_ks5seK1ZgaJpZM4LthUs>
X-Auto-Response-Suppress: All
X-GitHub-Recipient-Address: manzil@funtasticlabs.com
X-SG-EID: 83UmH9Yz2HjU1qKK7JE10vR6ZA73mzRCr3l9ny8S/eFfrdmhorME26rdzHG5udYNfjclqeaQjEEuLr
 eS+/qYynhrlo8IfLD1ZtIfGo3YvUgwLtGZThUQOZxcxUf0MZH85qZZ0BZhIK7s2OeDftja2YbRMWG2
 87pwHkW1qKliI0Mqq/MYbzMX09yVn8V45Rjc3FQ3jMlrkEa2lq3CEyV9RJnUsv+Ow9y3s81tj23A+V
 U=
X-MAILIN-01-MailScanner-Information: Please contact the ISP for more information
X-MAILIN-01-MailScanner-ID: 1dnx6x-00024Z-9O
X-MAILIN-01-MailScanner: Found to be clean
X-MAILIN-01-MailScanner-SpamCheck: not spam, SpamAssassin (not cached,
	score=-2.473, required 10, autolearn=not spam, AWL 0.94,
	BAYES_00 -1.90, HTML_MESSAGE 0.00, KHOP_THREADED -1.50,
	SPF_PASS -0.00, T_RP_MATCHES_RCVD -0.01, URIBL_BLOCKED 0.00)
X-MailScanner-From: bounces+848413-8c2f-manzil=funtasticlabs.com@sgmail.github.com
X-Spam-Status: No


----==_mimepart_59aa07594ea94_25d673ff80b451c38154945
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  ossbackup2@gmail.com
    Domain oss-india.net has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from mail-oi0-f41.google.com ([209.85.218.41]:32895)
	by server14.hostingraja.in with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <pawan.ossindia+caf_=pawan=oss-india.net@gmail.com>)
	id 1dnx42-003n05-HN
	for pawan@oss-india.net; Sat, 02 Sep 2017 06:48:09 +0530
Received: by mail-oi0-f41.google.com with SMTP id r203so13972473oih.0
        for <pawan@oss-india.net>; Fri, 01 Sep 2017 18:17:14 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:delivered-to:dkim-signature:dkim-signature:date
         :from:reply-to:to:cc:message-id:in-reply-to:references:subject
         :mime-version:content-transfer-encoding:precedence:list-id
         :list-archive:list-post:list-unsubscribe;
        bh=AIdTKePLR51n2O3ogEg7cVSlkfuFjvLGYj/E2HjVSLA=;
        b=pygRWyv6yTwzIvUeuPJuyDPo6AWbh9dUZVRRlvnHDMbEVxkpcPeODH8PsW5JTZDlHb
         YqGFaQ7zuDoe2sIo6LnMc0N5XhFD74Z80Er2fi1HlqWLpPURc3jF76VsQxhAElzp5G0b
         +J0fZMVtKMtBeVcHT5EueDoA+loUsgIzlfmzQrhw0Dz7PlTwTWQrVekbIpUgA7wPnOxk
         k+UDfDHfiU7rHIZoVtn14yDUnSGjNgrudzdqBeWdTIsBzVZTKIJxr8IPtpZmNYAxwXRt
         3HmeRg48OPCPGaBaKiVLHkprAQoRee25Pmcqkd14IQYnalwFgPdwS+h8gfqQ3pW9/tvg
         OyGw==
X-Gm-Message-State: AHPjjUjfMmb1ax7dSbTJQvTj7jBCCrn6u9+Cvm47a1dNY4gLnS6oCxQt
	FH9WyssOgHrbE3yAVz8gyAmBbuy56ttGqyDqHADq3A==
X-Received: by 10.202.4.130 with SMTP id 124mr4144424oie.246.1504315012093;
        Fri, 01 Sep 2017 18:16:52 -0700 (PDT)
X-Forwarded-To: pawan@oss-india.net
X-Forwarded-For: pawan.ossindia@gmail.com pawan@oss-india.net
Delivered-To: pawan.ossindia@gmail.com
Received: by 10.168.167.13 with SMTP id q13csp1352951ofe;
        Fri, 1 Sep 2017 18:16:51 -0700 (PDT)
X-Google-Smtp-Source: ADKCNb5KFWcsdwixabzSK18YKjx3etz+zLVP44LKdvubRllXwhCxO8dhir/nzYt2G1iHSgLNP9ev
X-Received: by 10.84.194.195 with SMTP id h61mr4548056pld.371.1504315011382;
        Fri, 01 Sep 2017 18:16:51 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1504315011; cv=none;
        d=google.com; s=arc-20160816;
        b=lDoFzApNVUV9v/A+6//L68ggJs3vt2F6IVA91mfSI5Si8KAc1ycRV1WF5jkK1pQu7I
         HE3ZhnU8T0Kk0egHWB2OrS3t4g//F5qvJgd1C97nZlpgxGVQ98+QkfWVIhyRpPUUk9BX
         oQ1MoCYeD3w4rQeIsq0kVsyHyMYM8mjuQs5829M58jey2yBRLBBCITFUbQJRVkVOCQLi
         0mXBL+jbzB5f3OMLqMb/DYqjRhSEFo7G8gXHyRNRz9Cvn9/jgMfj1qoEAPE0sZDF9ASG
         paVGlqEmQSQ5UqfY+M/Q76ZpEe0QjOV2Hf2R+GLMt9A6MLhfO0UFw2TSLpvjpKYRRjp7
         mk4w==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=list-unsubscribe:list-post:list-archive:list-id:precedence
         :content-transfer-encoding:mime-version:subject:references
         :in-reply-to:message-id:cc:to:reply-to:from:date:dkim-signature
         :dkim-signature:arc-authentication-results;
        bh=AIdTKePLR51n2O3ogEg7cVSlkfuFjvLGYj/E2HjVSLA=;
        b=sfgi9uB4x/eEI96AMpO+Sd/VPx1sSWn+fpOfX+AnDVGaC1Ly/gTF3S95SkQI1WypID
         MMF6M03C40TBIWFn59HTk6bbsYzPxYyH6mqIbol7sDKawbLOxuOUX/vJirdoQM6ODxUj
         p4yHeDa6zchu9ltZYdc9ZrF2Fv/iOhZkm9jXvGpcWKzCHAzt6t7J6ZwXwzII5h/8iPdW
         TkbxkOpXix7pAaPrKBEm6xju0FN3Z2zXKBTX+ck2jV3HCAwzqamWi6EA//kFGKpcWFQO
         Dq6upAnrEAyzsc+0lfOmh9DMYaiCXBQQqL1177+uKsKlvqWZwXiBnzBnwSulOEjpjVju
         n5pg==
ARC-Authentication-Results: i=1;  [...]

2017-09-03 14:35 UTC, systimotic commented
@BerkeleyTrue 👍 I understand. Getting the beta launched is way more important than this.