Fix closing backticks indentation on bug report
freeCodeCamp/freeCodeCamp pull request #12856
Opened 2017-01-25 20:49 UTC by systimotic

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12838

#### Description
As described in the issue, the closing backticks for a codeblock are indented, which makes them display as code.
It appears that there's an issue with dedent. I tried adding newlines before it both as lines that were empty in the editor and as `\n`, but it did not help.
I switched the code from dedent to good old string concatenation, which works fine.

2017-01-25 20:56 UTC, raisedadead commented
@systimotic you just beat me into this... damn you are fast!

2017-01-25 20:57 UTC, Greenheart commented
@systimotic Nice work! :blush:

Template strings and `dedent` are a clean solution, but since this works - why not stick to this method? :ok_hand:

2017-01-25 21:03 UTC, systimotic commented
@raisedadead I kind of already knew the solution when I reported it five hours ago, and had planned to do it now 😛 It was very fast, yeah, but that's not always the case for me 🙂

@Greenheart Thanks! Yeah, that was my thinking as well 👍

2017-01-25 21:07 UTC, raisedadead approved these changes
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @systimotic

2017-01-26 17:37 UTC, BerkeleyTrue requested changes

2017-01-26 17:37 UTC, BerkeleyTrue commented on common/app/routes/challenges/redux/bug-saga.js
> +      '\`\`\`' + fileType + '\n' +
Operators should end the line and the next addition should come on a new line

```js
return foo +
  'bar' +
  baz;
```

2017-01-27 09:19 UTC, systimotic commented on common/app/routes/challenges/redux/bug-saga.js
> +      '\`\`\`' + fileType + '\n' +
@BerkeleyTrue 👍 I was trying to make it look like it did with dedent, but I'm OK with that as well. I updated the PR.

2017-01-27 21:46 UTC, raisedadead commented
:shipit:

2017-01-29 21:20 UTC, Greenheart approved these changes
Let's launch it! :rocket:

2017-01-29 21:20 UTC, merged