Test, formatting fixes for new JS challenges
freeCodeCamp/freeCodeCamp pull request #12855
Opened 2017-01-25 20:49 UTC by HKuz

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12727 and Closes #12728 

#### Description

- General formatting fixes for last 4 challenges that were recently added to the Basic JavaScript section (`code`, `dfn`, and `blockquote` tags applied where needed, titles capitalized)
- Fixes the order of the challenges so the two `parseInt` ones are together, followed by the two `conditional operator` ones (probably why the diff looks odd)
- Fixes the isNaN test in `Use the parseInt Function` challenge, adds tests to check that `parseInt()` was used

2017-01-29 21:55 UTC, Greenheart requested changes
@HKuz Nice work! 

Tested this locally and the challenges works just as expected. Only some ideas about further formatting improvements :blush:

2017-01-29 21:55 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
>          "}",
Possibly add an empty line between the function and the test-call.

2017-01-29 21:55 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
>          "}",
Possibly add an empty line between the function and the test-call.

2017-01-29 21:55 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
> +        "The <dfn>conditional operator</dfn>, also called the <dfn>ternary operator</dfn>, is a one line if-else statement.",
Actually, this is an expression. This is what allows it to be used in so many more places than a regular if-else statement.

Either we add "(...), is **like** a one line if-else statement", or even clearer, "(...), **can be used as** a one line if-else expression".

2017-01-29 21:55 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
>          "}",
Possibly add an empty line between the function and the test-call.

2017-01-29 21:55 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
> +        "assert(checkEqual(1, -1) === false, 'message: <code>checkEqual(1, -1)</code> should return false');"
Possibly add a test to check that the ternary operator was actually used? :smile:

2017-01-29 21:55 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
>          "}",
Possibly add an empty line between the function and the test-call.

2017-01-29 21:55 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
> +        "Note that the <code>conditional operator</code> is right associative.",
What does this mean? Maybe add a link defining right associative? Maybe just for me? :smile:

2017-01-29 23:11 UTC, HKuz commented
Thanks @Greenheart - I'll make these changes 👍

2017-01-29 23:13 UTC, HKuz commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
> +        "Note that the <code>conditional operator</code> is right associative.",
I had to look this up when I read through these 😳  - if I can find a good link, I'll add it in, otherwise I can take this line out.

2017-01-30 00:27 UTC, HKuz commented
Alright, my branch is updated. I deleted the right associative line because the links I saw (Wiki article and MDN on the ternary operator) were either dense/unclear or didn't explain it. Also, the new regex tests are pretty flexible, just in case someone decides to be a contrarian and write something like `return a !== b ? false : true;`...

2017-01-30 18:29 UTC, Greenheart approved these changes
@HKuz Nice work!

This is ready to be merged :smile:

2017-01-30 18:30 UTC, merged