Add hint to Falsy Bouncer challenge description
freeCodeCamp/freeCodeCamp pull request #12861
Opened 2017-01-26 02:57 UTC by codeman869

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12433

#### Description

Updates the Falsy Bouncer challenge description to include a hint
to help campers understand how they should approach the challenge
without revealing too much information or locking the camper into
a particular solution.

2017-01-26 08:21 UTC, systimotic requested changes
Thanks for the PR @codeman869!

2017-01-26 08:21 UTC, systimotic commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json
> +        "Hint: Try converting each value to Boolean.",
To **a** Boolean

2017-01-26 16:12 UTC, codeman869 commented
@systimotic - I've amended my commit!

2017-01-26 19:16 UTC, Greenheart approved these changes
@codeman869 Nice work! :smile:

2017-01-27 10:27 UTC, systimotic approved these changes
# LGTM 👍 🎉 
Thank you for contributing again @codeman869! Also a thank you for helping figure out what to put here!

2017-01-27 10:27 UTC, merged