Fix isBeta challenges displaying without title when they should be hidden
freeCodeCamp/freeCodeCamp pull request #12989
Opened 2017-01-30 20:58 UTC by systimotic

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): 
   Closes #12941
   Closes #12842
   Original: #11547

#### Description
Woo! So this is probably the biggest change I have made to date. A lot of hours went into understanding what's going on here.

Challenges with `isBeta: true` would display in production, but without title.
This was because the challenges weren't being filtered from the blocks. The titles were taken from the `searchNames`, which were filtered, so no title showed up.

@BerkeleyTrue This is my first time making a change this "major", and my first time changing the tests. Your review would be much appreciated.

2017-02-05 23:23 UTC, Bouncey commented on common/app/routes/challenges/utils.js
> +        block.challenges = challenges;
You are mutating state here. A better (FP) way would be something like this:

```js
return {
  ...block,
  challenges: [ ...filteredChallenges ]
};
```

2017-02-05 23:37 UTC, Bouncey requested changes
Some great work here, just a few pointers for keeping it functional :smiley:

2017-02-05 23:37 UTC, Bouncey commented on common/app/routes/challenges/utils.js
> +        let challenges = block.challenges;
A better way here would be 
```js
const filteredChallenges = block.challenges
  .map(...)
  .filter(...)
  .map(...);
```

2017-02-05 23:37 UTC, Bouncey commented on common/app/routes/challenges/utils.js
> +        block.challenges = challenges;
You are mutating state here. A better (FP) way would be something like this:

```js
return {
  ...block,
  challenges: [ ...filteredChallenges ]
};
```
This is the ~same as `Object.assign({}, block, { challenges: filteredChallenges })` where an empty object has the properties of `block` copied in to it, and then we overwrite the prop `challenges` with our new filtered challenges.

2017-02-05 23:37 UTC, Bouncey commented on common/app/routes/challenges/utils.js
> +        if (Array.isArray(challenges)) {
This function is used only when we have received `entities` from the db. This check is not required.

2017-02-05 23:37 UTC, Bouncey commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json
> -      "isBeta": true,
Why was this removed?

2017-02-18 23:57 UTC, systimotic commented on common/app/routes/challenges/utils.js
> +        if (Array.isArray(challenges)) {
Yep, you're right! I originally added this because it seemed to be necessary for something, but it works fine without it now.

2017-02-18 23:59 UTC, systimotic commented on common/app/routes/challenges/utils.js
> +        let challenges = block.challenges;
Good to know, thanks!

2017-02-18 23:59 UTC, systimotic commented on common/app/routes/challenges/utils.js
> +        block.challenges = challenges;
That's pretty cool! I totally didn't think about mutating state, that's really good to learn. Thanks for the tip!

2017-02-19 00:00 UTC, systimotic commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json
> -      "isBeta": true,
I believe this challenge wasn't meant to be in beta. I'm not sure how I should confirm this.

2017-02-19 00:01 UTC, systimotic commented
@Bouncey Thank you so much for reviewing! I'm sorry for taking so long, I've been a bit absent in the past two weeks and I completely forgot about this. I just pushed the requested updates. How are things now?

2017-02-26 00:27 UTC, systimotic commented
@Bouncey @BerkeleyTrue Can you review?

2017-03-05 12:39 UTC, systimotic commented
@Bouncey @BerkeleyTrue A review would be great!

2017-03-07 21:41 UTC, BerkeleyTrue requested changes

2017-03-07 21:42 UTC, BerkeleyTrue commented
@systimotic Sorry about that. I had requested changes a while back but I had failed to submit them.

2017-03-11 22:01 UTC, systimotic commented
@BerkeleyTrue No worries!
That does make a whole lot of sense. I'll open an issue about the `isBeta` for the splicing challenge. 
I updated the PR. How is it now?

2017-03-17 20:53 UTC, BerkeleyTrue requested changes

2017-03-17 20:53 UTC, BerkeleyTrue commented on common/app/routes/challenges/utils.test.js
> +        });
Use `reduce` instead of `forEach` since the results is an array from an object.

2017-03-17 20:53 UTC, BerkeleyTrue commented on common/app/routes/challenges/utils.test.js
> +        });
Same as above.

2017-03-17 20:53 UTC, BerkeleyTrue commented on common/app/routes/challenges/utils.test.js
> +      console.log(challengesFromBlocksCount, actual.block);
stray console.log here.

2017-08-02 13:10 UTC, dhcodes commented
@systimotic This PR would also fix the new issue #15705. Do you plan to update this or do you want to start from scratch now that there have been a few updates to the base? I can take a stab at it as well, but looks like you're already a bit farther down the road to solving it.

2017-08-22 02:16 UTC, BerkeleyTrue requested changes

2017-08-22 02:16 UTC, BerkeleyTrue commented on common/app/redux/utils.js
> +  { challenge: challengeMap, block: blocks, ...rest },
nit: this should stick to the convention of calling these id => object objects `maps`. We use the plural of the noun to represent iterables or streams. So `blocks` should be `blockMap`.

2017-08-22 02:20 UTC, BerkeleyTrue commented
@systimotic Thanks for the PR. I think this will do for now (other than my nit pick above). The issue with this approach is now all the challenges are iterated through twice in addition to the blocks. We now have over 400 challenges and 60+ blocks, so this function went from iterating 400+ times to more like 900+ times. This is a very costly function now. Not your fault, but we will need to come up with a more integrated solution that does not involving iterating through all the challenges and instead filters out during nextChallenge and map rendering.

Other than the nitpick above code LGTM. If someone could run it and verify it's ready to merge.

2017-08-24 18:28 UTC, systimotic commented on common/app/redux/utils.js
> +  { challenge: challengeMap, block: blocks, ...rest },
Picking nits is important. Bad things happen if you leave nits be.

2017-08-24 18:30 UTC, systimotic commented
@BerkeleyTrue Yeah, it's not ideal. Should we stick with the workaround from #15741 instead?

2017-09-02 02:34 UTC, BerkeleyTrue approved these changes

2017-09-02 03:03 UTC, BerkeleyTrue commented
Merged!!! https://github.com/freeCodeCamp/freeCodeCamp/commit/01291162ef3cb747763202119ecfb6340e2eaba5


Happy Coding!

2017-09-02 03:03 UTC, closed without merging