fix(challenge): Improve example for "Applied Visual Design: Use the u Tag to Underline Text"
freeCodeCamp/freeCodeCamp pull request #13012
Opened 2017-01-31 21:54 UTC by Greenheart

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12986 

#### Description
This improves the example of the challenge according to the referenced issue.
* Update instruction.
* Update `challengeSeed` for affected challenges.
* Update tests.
* Use strict equality for tests.

2017-02-06 07:17 UTC, erictleung requested changes
Just did a static code review and found that one *small* inconsistency. I haven't seeded this locally yet to just double check. I'll try to get around it tomorrow, unless someone else gets to it before I do. But it looks all right so far.

2017-02-06 07:17 UTC, erictleung commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "assert($('u').text().indexOf('Ph.D. students') > -1, 'message: The <code>u</code> tag should wrap around the text \"Ph.D students\".');",
```diff
- ...around the text \"Ph.D students\"
+ ...around the text \"Ph.D. students\"
```

2017-02-06 10:25 UTC, Greenheart commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "assert($('u').text().indexOf('Ph.D. students') > -1, 'message: The <code>u</code> tag should wrap around the text \"Ph.D students\".');",
@erictleung Thanks for sharing that formatted diff! I didn't know that :smile:

2017-02-06 18:38 UTC, erictleung commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "assert($('u').text().indexOf('Ph.D. students') > -1, 'message: The <code>u</code> tag should wrap around the text \"Ph.D students\".');",
@Greenheart no prob! Yeah, it blew my mind when I found out you can do that. The "language" for the code block is "diff" and you just have to add the `+` and `-` signs accordingly.

2017-02-06 20:59 UTC, raisedadead requested changes

2017-02-06 20:59 UTC, raisedadead commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "Wrap the <code>u</code> tag around the text \"Ph.D. students\". It should not include the parent <code>div</code> that has the class of <code>cardLinks</code>.",
```diff
-cardLinks
+cardText
```

Caught a pre-existing typo, @Greenheart would you mind fixing this?

2017-02-07 11:53 UTC, Greenheart commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "Wrap the <code>u</code> tag around the text \"Ph.D. students\". It should not include the parent <code>div</code> that has the class of <code>cardLinks</code>.",
@raisedadead Done! :smile:

2017-02-07 13:46 UTC, raisedadead approved these changes

2017-02-07 17:10 UTC, erictleung approved these changes

2017-02-07 17:10 UTC, merged