fix(challenges): add class to backend challenge wrapper, fix basic no…
freeCodeCamp/freeCodeCamp pull request #13164
Opened 2017-02-05 19:48 UTC by no-stack-dub-sack

…de formatting

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13163

#### Description

- added the class `.challenge-instructions` to the `<Row>` component surrounding the function that renders challenge instructions in the new backend challenge component
- changed all the code examples in Basic Node and Express section to `<blockquote>`s to exemplify the changes
- this will also allow us to use `<dfn>` tags in this section which previously would not have formatted correctly

### NOTE: 
I think this may cause some merge conflicts in other PRs if merged before them. #13155 and #13162 should be merged first to avoid this I believe.

2017-02-06 04:56 UTC, JosephLivengood commented on seed/challenges/05-apis-and-microservices/basic-node-and-express.json
> +        "<blockquote>function(req, res) {<br> res.send('Response String');<br>}</blockquote>",
I recommend using <pre> with \n. This way you can preserve indentation and it's formatted as code. See attached for what it looks like:

![screen shot 2017-02-05 at 11 55 03 pm](https://cloud.githubusercontent.com/assets/13642392/22635129/9a112188-ebfe-11e6-85ce-3ae3c4b7c37b.png)

2017-02-06 20:42 UTC, no-stack-dub-sack commented on seed/challenges/05-apis-and-microservices/basic-node-and-express.json
> +        "<blockquote>function(req, res) {<br> res.send('Response String');<br>}</blockquote>",
@JosephLivengood Hey Joseph, actually, wrapping it in a blockquote and adding the class that I've added to the challenge description wrapper is what will give it the appearance of how code examples look in other challenges. Even though they appear to be wrapped in pre at first glance, stylized blockquotes are the FCC standard. See the code [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/client/less/challenge.less#L75) to check how the effect is achieved.

2017-02-08 21:11 UTC, raisedadead commented
@no-stack-dub-sack blocking for a merge post the others?

2017-02-08 23:24 UTC, no-stack-dub-sack commented
@raisedadead Yeah, sorry, meant to add the label. Once the 2 referenced above are merged, we can remove this label and review.

2017-02-13 13:38 UTC, raisedadead commented
@no-stack-dub-sack I guess we are good to go after addressing the review comments now?

2017-02-16 01:10 UTC, no-stack-dub-sack commented
@raisedadead Yeah, if anyone would like to review at this point, the two holding it up have been merged

2017-02-17 18:59 UTC, raisedadead requested changes

2017-02-17 18:59 UTC, raisedadead commented on seed/challenges/05-apis-and-microservices/basic-node-and-express.json
>          "Let’s serve our first string ! In Express, routes takes the following structure: app.METHOD(PATH, HANDLER). METHOD is an http method in lowercase. PATH is a relative path on the server (it c
`app.METHOD(PATH, HANDLER)`

Can we wrap these and similar things in `<code></code>` for better UX and consistency.

2017-02-17 19:00 UTC, raisedadead commented
@no-stack-dub-sack these changes LGTM, except for some formatting overhaul. Would you be interested in doing so via this PR.

Or we could take up later, I'll leave the choice to you.

2017-02-18 00:56 UTC, no-stack-dub-sack commented
@raisedadead Where, in the entire backend section? Or just in the section that I've already modified.  Because as you know, I've only done basic node and express here, and the entire backend curriculum has code examples that also need to be wrapped in blockquotes. So I can do it for this section, but I think maybe the other sections should have everything done at once

2017-02-18 02:01 UTC, no-stack-dub-sack commented
@raisedadead Ok, I've made some updates, I think I caught most of everything, but not sure if some things like POST and GET should be wrapped in code tags to have them stand apart even when they're not explicitly in the context of code. They are also mentioned in this section several times before they're actually introduced, so maybe this could use some re-working and DFN tags in the right places. 

This also will now close #13168 which I opened a while ago.

2017-02-26 20:16 UTC, no-stack-dub-sack commented
@raisedadead Did you get a chance to check out the changes I made since we last checked in?

2017-02-27 07:01 UTC, raisedadead approved these changes

2017-02-27 07:03 UTC, raisedadead commented
@no-stack-dub-sack sorry have been travelling a bit last weekend. LGTM. Lets add more formatting in further PR's.

I am yet to pull down locally and merge it in. I am okay if anyone beats me to it.

2017-02-28 21:43 UTC, merged