Remove code tags from challenge seed
freeCodeCamp/freeCodeCamp pull request #13198
Opened 2017-02-06 20:19 UTC by Manish-Giri

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13181 

#### Description

Removed code tags from the challenge seed, which were causing some tests to fail. Also added code tags around the ES6 function syntax in `description`, to be consistent with the example above it.

Closes #13181

2017-02-06 21:12 UTC, erictleung requested changes

2017-02-06 21:12 UTC, erictleung commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "<code> const Container extends Component { </code>",
This multi-line example in the description of the challenge should be in `<blockquote>` tags. [Here's](https://github.com/freeCodeCamp/freeCodeCamp/blob/15474e8065d633657842a3208b1e6ca34814abf6/seed/challenges/02-javascript-algorithms-and-data-structures/object-oriented-programming.json#L45) an example of it being used. You can use `<br>` for line breaks. Make sure those spaces are there to retain the formatting.

2017-02-07 00:02 UTC, Manish-Giri commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "<code> const Container extends Component { </code>",
@erictleung So, I tried out the `<blockquote>` on the first code example. Please review this, I can move on to the next example if this one looks all right - 

![screenshot 2017-02-06 18 58 43](https://cloud.githubusercontent.com/assets/11348778/22671883/a66c2b4e-ec9e-11e6-9ee7-72980c86c53c.png)

2017-02-07 02:13 UTC, erictleung commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "<code> const Container extends Component { </code>",
@Manish-Giri yep, the top part is what it should look like!

2017-02-08 21:10 UTC, raisedadead commented
@erictleung this LGTM, unless you want to add anything more to the change.

2017-02-08 23:29 UTC, erictleung commented
@raisedadead if you're able to locally test this, go ahead and merge. I haven't made the time yet to get to this and pull it down locally.

2017-02-12 10:00 UTC, erictleung approved these changes

2017-02-12 10:00 UTC, merged