Chore(package): Remove gltter-sidecar due to vulnerability
freeCodeCamp/freeCodeCamp pull request #13200
Opened 2017-02-06 20:54 UTC by Bouncey

sync.io is flagging the module `gitter-sidecar` as the source of a vulnerability due to one of it's dependants.

We do not use this module any more

2017-02-08 15:10 UTC, raisedadead commented
@Bouncey Does this need updates to the `.snyk` file? I am not aware how this works.

2017-02-08 22:44 UTC, atjonathan commented
@Bouncey, try running `npm run snyk-protect`? If it updates the `.snyk` file, then push the changes to this PRs branch 💪

2017-02-09 20:56 UTC, Bouncey commented
The `.snyk` file I think is auto generated and tracks patched applied to modules. 

`npm run snyk-protect` does not change the `.synk` file.

2017-02-11 13:51 UTC, systimotic requested changes
@Bouncey I did a check on the Snyk thing. I found out that it should be updated. Running:
```
snyk wizard
N
n
```
will yell you no vulnerabilities were found, but it will remove the `gitter-sidecar` rule from the .snyk file.

2017-02-11 15:34 UTC, Bouncey commented
Thanks @systimotic, I like learning things!

2017-02-11 16:22 UTC, systimotic approved these changes
# LGTM! 🎉 
Thanks for fixing this @Bouncey!

2017-02-11 16:22 UTC, merged

2017-02-11 16:33 UTC, teeleek commented
Okay

Puttasak insee

เมื่อ 11 ก.พ. 2017 23:24 "Timo" <notifications@github.com> เขียนว่า

> Merged #13200 <https://github.com/freeCodeCamp/freeCodeCamp/pull/13200>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/13200#event-958385929>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWEMJvpJiSjo9lVC10EoBsrmHUDjKcUtks5rbeC7gaJpZM4L4tJC>
> .
>

2017-02-11 16:33 UTC, teeleek commented
Okay

Puttasak insee

เมื่อ 11 ก.พ. 2017 23:33 "Puttasak Insee" <teelek201460@gmail.com> เขียนว่า

> Okay
>
> Puttasak insee
>
> เมื่อ 11 ก.พ. 2017 23:24 "Timo" <notifications@github.com> เขียนว่า
>
>> Merged #13200 <https://github.com/freeCodeCamp/freeCodeCamp/pull/13200>.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/freeCodeCamp/freeCodeCamp/pull/13200#event-958385929>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AWEMJvpJiSjo9lVC10EoBsrmHUDjKcUtks5rbeC7gaJpZM4L4tJC>
>> .
>>
>

2017-02-12 00:52 UTC, texas2010 commented
@teeleek 
looks like you may have accidentally subscribed to all notifications for the [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) repository. To stop receiving notifications please visit the [subscriptions page](https://github.com/FreeCodeCamp/FreeCodeCamp/subscription) and select "Not watching". Additionally, you can visit the [GitHub Help page on managing notification delivery methods](https://help.github.com/articles/managing-notification-delivery-methods/) for more help.

We are sorry for your inconvenience!

2017-02-12 00:54 UTC, teeleek commented
Okay

Puttasak insee

เมื่อ 12 ก.พ. 2017 07:53 "Lance" <notifications@github.com> เขียนว่า

> @teeleek <https://github.com/teeleek>
> looks like you may have accidentally subscribed to all notifications for
> the FreeCodeCamp <https://github.com/FreeCodeCamp/FreeCodeCamp>
> repository. To stop receiving notifications please visit the subscriptions
> page <https://github.com/FreeCodeCamp/FreeCodeCamp/subscription> and
> select "Not watching". Additionally, you can visit the GitHub Help page
> on managing notification delivery methods
> <https://help.github.com/articles/managing-notification-delivery-methods/>
> for more help.
>
> We are sorry for your inconvenience!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/13200#issuecomment-279187693>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWEMJsAYIli-3OVcqzhRmRDyqvXfu-5lks5rblgkgaJpZM4L4tJC>
> .
>