Feature singly linked list descriptions enhancements
freeCodeCamp/freeCodeCamp pull request #13219
Opened 2017-02-07 15:26 UTC by TheeMattOliver

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

These changes target the Singly Linked List Data Structure challenge.

Specifically, they deal with enhancing the descriptions to improve readability and aid in comprehension, as the instructions and descriptions were unclear. Grammar errors were corrected, and word choice improved.

The "helper" methods for 'size()' and 'head()' were removed as these were redundant and unnecessary, and the tests for each section were updated to reflect this change. Wherever a test called for the size or head of a list, the length and head properties were used respectively.

2017-02-08 21:09 UTC, raisedadead commented
@TheeMattOliver this needs a rebase and squash, to resolve the conflicts. Can you update the pull request?

Reach us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), if you need any assistance.

2017-02-13 13:44 UTC, raisedadead requested changes
Please remove the additional translation blocks that are empty.

2017-02-13 13:44 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +      "translations": {
Please revert this line of change. We do not need to add empty translation blocks.

2017-02-13 13:44 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +      "translations": {
Please revert this line of change. We do not need to add empty translation blocks.

2017-02-13 13:44 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +      "translations": {
Please revert this line of change. We do not need to add empty translation blocks.

2017-02-13 13:44 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +      "translations": {
Please revert this line of change. We do not need to add empty translation blocks.

2017-02-13 13:44 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +      "translations": {
Please revert this line of change. We do not need to add empty translation blocks.

2017-02-13 14:53 UTC, TheeMattOliver commented
Done. Thanks.

2017-02-15 02:22 UTC, TheeMattOliver commented
@raisedadead Anything else I need to do?

2017-02-15 12:34 UTC, raisedadead requested changes
@TheeMattOliver 

Thanks a lot for taking the time to contribute, we really appreciate the efforts.
I have left some comments, basically related to the formatting.
When you have done addressing the changes, please [squash your commits](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231).
Will take a look and merge, thanks once again

2017-02-15 12:34 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +      "translations": {}
Remove white space, refer out contributing guide to configure the linter for your text editor.

2017-02-15 12:34 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "In our code editor, we've created two nodes, Kitten and Puppy, and we've manually connected the Kitten node to the Puppy node.",
Wrap the words like Kitten, Puppy, Cat, Dog in `<code>...</code>` tags for legibility.

2017-02-15 12:34 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "In our code editor, we've created two nodes, Kitten and Puppy, and we've manually connected the Kitten node to the Puppy node.",
You would want to do this at all places in this pull request, where you are referring variable, keywords, etc. in the challenge seed.

2017-02-15 12:34 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
>          "Instructions",
Does not concern your pull request, but would you mind changing this to `<hr>`

```diff
- "Instructions",
+ "<hr>",
```

2017-02-15 12:34 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "In our code editor, we've created two nodes, Kitten and Puppy, and we've manually connected the Kitten node to the Puppy node.",
A good place to refer the formatting is :
https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json

2017-02-15 12:34 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "In our code editor, we've created two nodes, Kitten and Puppy, and we've manually connected the Kitten node to the Puppy node.",
You many need to add `<dfn></dfn>` to definations as well, just refer the file above

2017-02-15 17:52 UTC, TheeMattOliver commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +      "translations": {}
Awesome thanks so much Mrugesh @raisedadead! I committed my changes and if there's anything else I need to do just let me know!

2017-02-16 20:40 UTC, TheeMattOliver commented
@raisedadead I had a syntax error. Fixed and squashed.

2017-02-17 19:03 UTC, raisedadead requested changes

2017-02-17 19:03 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
>          "Instructions",
Delete this line.

```diff
- "Instructions",
```

2017-02-17 19:03 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
>          "Instructions",
Delete this line.

```diff
- "Instructions",
```

2017-02-17 19:03 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
>          "Instructions",
Delete this line.

```diff
- "Instructions",
```

2017-02-17 19:03 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
>          "Instructions",
Delete this line.

```diff
- "Instructions",
```

2017-02-17 19:03 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
>          "Instructions",
Delete this line.

```diff
- "Instructions",
```

2017-02-17 19:06 UTC, raisedadead commented
@TheeMattOliver Great work so far, almost there. Some final touches and we are good to go. Sorry for being picky.. 😅 !

when you have made the changes please amend the commit like this:

```sh
git commit --amend --no-edit
git push origin --force
```

This will let you edit the commit, without creating more.
Good luck, and thanks a lot for helping us out.

If you need any assistance hit us in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors).

2017-02-17 19:28 UTC, TheeMattOliver commented
Done! Thanks @raisedadead. Let me know if you'd like me to make further changes.

2017-02-17 20:06 UTC, raisedadead commented
@TheeMattOliver looks like you forgot to do a `git add --all`, the changes are not reflecting.

```sh
git add --all
git commit --amend --no-edit
git push origin --force
```

2017-02-17 20:38 UTC, TheeMattOliver commented
Thanks @raisedadead I was wondering about that. I followed your last instructions literally. 

Just pushed again.

👍

2017-02-17 20:43 UTC, raisedadead commented
@TheeMattOliver thanks for making the changes. Will merge after a QA check first thing in the morning.

2017-02-24 03:12 UTC, TheeMattOliver commented
Hey guys did this get hung up on a check I didn't pass again? @raisedadead

2017-02-24 04:41 UTC, raisedadead commented
@TheeMattOliver looks like this got into a merge conflict. Do not worry we will resolve and merge upstream.

2017-02-24 15:18 UTC, raisedadead commented
@TheeMattOliver I have resolved the conflicts, but this will break the tests. Mind having a look?

2017-02-24 15:20 UTC, raisedadead commented
On you local setup, you need to delete this branch (local machine only, NOT on GitHub) and pull down again.

```
git checkout staging
git branch -D feature-singly-linked-list-descriptions-enhancements
git fetch origin --all
git checkout feature-singly-linked-list-descriptions-enhancements
Make Necessary changes to the tests.
git add --all
git commit --amend --no-edit
git push origin feature-singly-linked-list-descriptions-enhancements --force
```

2017-02-24 15:21 UTC, TheeMattOliver commented
@raisedadead Will do now, pls hold.

2017-02-27 18:32 UTC, raisedadead commented
Hey @TheeMattOliver ! I guess you would have to make a fresh PR. I couldn't get this working. Sincerest apologies for the inconvenience.

Let me know if you need assistance. 

Thanks a lot once again for your contribution.

2017-02-27 18:32 UTC, closed without merging