added step by step instruction on adding an image to a website
freeCodeCamp/freeCodeCamp pull request #13272
Opened 2017-02-10 07:19 UTC by Marmiz

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

As per #13261 I have added some step by step instruction to ease the understanding of the image tag:

>Let's try to add an image to our website:
        Before the <code>h2</code> element insert an <code>img</code> tag.
        Now set the <code>src</code> attribute so that it point to this url:
        <code>https://bit.ly/fcc-relaxing-cat</code>
        Finally don't forget to give your image an <code>alt</code> text.

2017-02-10 07:32 UTC, Marmiz commented
Just noticed a small typo:

I have written:

> Now set the src attribute so that it point to this url:

Should probably be:

> Now set the src attribute so that it **points** to this url:

Can I change and commit without re-submitting a PR?

2017-02-10 10:20 UTC, raisedadead commented
> Can I change and commit without re-submitting a PR?

Yes, just to the below:
1. `git checkout  fix/Add-images-challenge `
2. Edit the file to make the necessary changes 
3. `git add --all`
4. `git commit --amend --no-edit`
5. `git push origin --force`

This will update the PR automatically.

2017-02-10 10:21 UTC, raisedadead commented
Also please edit the PR description in the Opening Post above to modify the closes tag refering the issue, this will automatically close the open issue.

2017-02-10 10:40 UTC, Marmiz commented
@raisedadead followed the instruction 😄 
I've edited the PR template (hopefully correctly); I didn't know that will close the issue automatically.

I've learned another new thing today!
Thanks for your help 💙

2017-02-11 06:10 UTC, raisedadead requested changes
Just a minor change and we are good to go.

2017-02-11 06:10 UTC, raisedadead commented on seed/challenges/01-responsive-web-design/basic-html-and-html5.json
> +        "Before the <code>h2</code> element insert an <code>img</code> tag.",
Update the statement:
```diff
- "Before the <code>h2</code> element insert an <code>img</code> tag.",
+ "Insert an <code>img</code> tag, before the <code>h2</code> element.",
```

2017-02-13 02:45 UTC, Marmiz commented
@raisedadead pushed the change as requested:
> "Insert an <code>img</code> tag, before the <code>h2</code> element.",

Apparently now there's a vulnerable path, the "details" show is linked to the `marked` packages that I haven't touched.
Suggestion on a fix?

I haven't done a `git pull` before re-committing the change, perhaps was that?

2017-02-13 06:24 UTC, teeleek commented
Okay

Puttasak insee

เมื่อ 13 ก.พ. 2017 09:46 "Claudio Restifo" <notifications@github.com>
เขียนว่า

> @raisedadead <https://github.com/raisedadead> pushed the change as
> requested:
>
> "Insert an img tag, before the h2 element.",
>
> Apparently now there's a vulnerable path, the "details" show is linked to
> the marked packages that I haven't touched.
> Suggestion on a fix?
>
> I haven't done a git pull before re-committing the change, perhaps was
> that?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/13272#issuecomment-279281920>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWEMJgQ4G5u09bdQYISwif59H0kET0d-ks5rb8QQgaJpZM4L9E8o>
> .
>

2017-02-13 12:59 UTC, raisedadead commented
> Apparently now there's a vulnerable path, the "details" show is linked to the marked packages that I haven't touched.

Yes, this doesn't relate to your PR, a re-base against the `staging` branch will fix this for your branch.

This happened, when we patched a pre-existinf vulnerability, and your PR had been open before that, a simple re-base would take care of this.

```
git checkout <branch name>
git pull --rebase upstream staging
git push origin --force
```

2017-02-13 13:00 UTC, raisedadead approved these changes

2017-02-13 13:00 UTC, raisedadead commented
Changes LGTM. Ready for a merge pending re-base.

2017-02-17 20:12 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @Marmiz for your contribution!

2017-02-17 20:12 UTC, merged