Fix/typos advanced express tools
freeCodeCamp/freeCodeCamp pull request #13342
Opened 2017-02-14 05:03 UTC by RamiroPinol

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Fixed several typos in advanced-express-tools.json

2017-02-14 05:19 UTC, erictleung requested changes
Thanks for the PR! There are some changes with having "a" in front of words start with "u". Also, there's a missing apostrophe. Let us know if you have any questions about amending your commit.

2017-02-14 05:19 UTC, erictleung commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "Many strategies are set up using different settings, general it is easy to set it up based on the README in that strategies repository though. A good example of this is the Github strategy w
`don't need to worry about an username`

This doesn't need to be changed. It should be left alone as

`don't need to worry about a username`

Source: http://english.stackexchange.com/a/105117

2017-02-14 05:19 UTC, erictleung commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "Now at this point if you enter an username and password in the form, it should redirect to the home page <em>/</em> and in the console of your server should be 'User {USERNAME} attempted to
Same here, it should be `a username`, not `an username`

2017-02-14 05:19 UTC, erictleung commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "Also in the profile, add a link to <em>/logout</em>. That route will host the logic to unauthenticate an user. <code>a(href='/logout') Logout</code>",
Same here, should be `unauthenticate a user` not `unauthenticate an user`

2017-02-14 05:19 UTC, erictleung commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "With a findAndModify, it allows you to search for an object and update it, as well as upsert the object if it doesn't exist and receive the new object back each time in our callback function
While you're making changes, can you also add an apostrophe here?

```diff
- returned wont have all 
+ returned won't have all 
```

2017-02-14 05:21 UTC, erictleung commented
@RamiroPinol also, it appears you've merged in some really old commits. You might want to head over to the [Contributors](https://gitter.im/FreeCodeCamp/Contributors) help room if you need assistance.

2017-02-14 08:01 UTC, systimotic requested changes
Thank you for these fixes!

2017-02-14 08:01 UTC, systimotic commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "To do this, add MongoDB as a dependancy and require it in your server. (<code>const mongo = require('mongodb').MongoClient;</code>)",
Can you change "dependancy" to "dependency"?

2017-02-14 17:19 UTC, RamiroPinol commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "To do this, add MongoDB as a dependancy and require it in your server. (<code>const mongo = require('mongodb').MongoClient;</code>)",
There are several "dependancy" in the json, I looked in the web and it seems to be a valid word, that's why I didn't changed it. But can fix them, no problem.

2017-02-14 18:02 UTC, RamiroPinol commented
It seems ok now

2017-02-18 19:41 UTC, raisedadead commented
@Greenheart @erictleung I have rebased the merge conflicts, please have a look and merge.

2017-02-18 20:28 UTC, Greenheart requested changes
@RamiroPinol Nice work!

I caught one minor detail, but apart from that, this is solid :blush:

2017-02-18 20:28 UTC, Greenheart commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "Serialization and deserialization are important concept in regards to authentication. To serialize an object means to convert its contents into a small <em>key</em> essentially that can then
```diff
-concept
+concepts
```

2017-02-19 23:57 UTC, RamiroPinol commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "Serialization and deserialization are important concept in regards to authentication. To serialize an object means to convert its contents into a small <em>key</em> essentially that can then
Nice catch, fixed. ;)

2017-02-20 07:15 UTC, Greenheart requested changes
@RamiroPinol Great work!

Normally, you would have to squash your commits into one [using this method](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md#squash-your-commits), but as I assume you haven't updated your local branch yet (`git pull origin <your-branch>`), you probably just could ignore the above and do the following instead:
1. Re-apply the changes you made through the GitHub interface to your local branch.
2. `git commit --amend --no-edit` (to add your changes to the latest commit, without changing the commit message)
3. git push origin <your-branch> -f

Then we should only see one commit here and this PR should be good to go :blush:

2017-02-20 20:51 UTC, RamiroPinol commented
Sorry, forgot about the "only 1 commit" rule. Fixed now

2017-02-20 20:55 UTC, Greenheart approved these changes
@RamiroPinol No problem, you've done a great job! :smile: :+1:

2017-02-20 20:55 UTC, merged

2017-02-26 00:45 UTC, systimotic commented on seed/challenges/06-information-security-and-quality-assurance/advanced-express-tools.json
> +        "To do this, add MongoDB as a dependancy and require it in your server. (<code>const mongo = require('mongodb').MongoClient;</code>)",
Thanks! "dependancy" is incorrect, it's the archaic form of "dependency" https://en.wiktionary.org/wiki/dependancy
Do you want to look at replacing the other instances of this?