Format Learn how a stack works challenge
freeCodeCamp/freeCodeCamp pull request #13343
Opened 2017-02-14 05:27 UTC by erictleung

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

- Improve readability of challenge
- Spell out JavaScript abbreviations
- Apply appropriate dfn and code tags
- Change from single quotes to double quotes
- Add periods to end of challenge tests

2017-02-14 21:26 UTC, dhcodes commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "You are probably familiar with stack of books on your table. You might have used the undo feature in your computer. You are also probably used to hitting the back button on your phone to go
I recommend changing "You might have used the undo feature in your computer." to "You have likely used the Undo feature of a text editor".

"In your computer" seems generic.

2017-02-14 21:33 UTC, dhcodes requested changes
Please see comments.

2017-02-14 21:33 UTC, dhcodes commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "Oh, and did I mention such a data storage scheme is called a <dfn>Stack</dfn>! In particular, we would have to implement the <code>push()</code> method that pushes JavaScript objects at the
Recommend changing:
>"Oh, and did I mention such a"

to:
 
>"This". 

and removing the `!`

2017-02-14 21:33 UTC, dhcodes commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "Create a stack data storage scheme with JavaScript arrays and functions that we always get back first what we put there last.",
I recommend changing:
>"Create a stack data storage scheme with JavaScript arrays and functions..."

to:

>Write a function that accepts an array and a new item and removes the last item of the array and replaces it with the new item. Then call your function using `homeworkStack` as the array and `"CS50"` as the new item that will replace `"PSY44"`.

2017-02-14 21:33 UTC, dhcodes commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "You are probably familiar with stack of books on your table. You might have used the undo feature in your computer. You are also probably used to hitting the back button on your phone to go
I recommend changing:
>"You might have used the undo feature in your computer." 

to

>"You have likely used the Undo feature of a text editor".

"In your computer" seems generic.

2017-02-16 16:20 UTC, erictleung commented
@dhcodes thanks for the feedback! I've been bogged down with other stuff the past few days. I'll get to this by sometime this weekend.

2017-02-17 16:42 UTC, erictleung commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "Create a stack data storage scheme with JavaScript arrays and functions that we always get back first what we put there last.",
This challenge only requires you to use `pop` and `push`. You don't need a function to pass the challenge. The tests only look at `homeworkStack`. I can change it something like

> Modify the given array and treat it like a `stack` using JavaScript methods. Remove the top element `"BIO12"` from the stack. Then add `"CS50"` to be the new top element of the stack. 

But now that I look at it, the unit tests need a bit of work. You can pass the challenge if you just set `homeworkStack` to the correct array elements.

2017-02-24 21:52 UTC, Greenheart requested changes
@erictleung Nice work! :blush:

2017-02-24 21:52 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "var homeworkStack = [\"BIO12\",\"HIS80\",\"MAT122\",\"PSY44\"];",
This is rather unserious, but why the double quotes?

By using single quotes, you can save campers from downloading the extra bytes for the escaping backslashes - just saying... :wink:

2017-02-24 21:52 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "assert(homeworkStack.indexOf('PSY44') === -1, 'message: <code>homeworkStack</code> should not contain <code>\"PSY44\"</code>.');"
This still allows the challenge to be passed

```js
var homeworkStack = ["BIO12","HIS80","MAT122","PSY44"];
// Only change code below this line

homeworkStack = ['BIO12', 'HIS80', 'MAT122', 'CS50'];
```

I see two approaches to making the tests more robust:
1. Use a regex to verify that the first line of the challengeSeed is intact, and that the `code` only contains one instance of the `=` character. **This is probably the best method**.
2. Alternatively we can verify that the array methods have actually been used.

What do you think?

2017-02-24 23:21 UTC, erictleung commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "var homeworkStack = [\"BIO12\",\"HIS80\",\"MAT122\",\"PSY44\"];",
Haha I've just seen only double quotes in seed codes, so I'm just trying to be consistent :smile:

2017-02-24 23:23 UTC, erictleung commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "assert(homeworkStack.indexOf('PSY44') === -1, 'message: <code>homeworkStack</code> should not contain <code>\"PSY44\"</code>.');"
@Greenheart I've added this issue to address the insufficiencies in the challenge tests https://github.com/freeCodeCamp/freeCodeCamp/issues/13459. I can go ahead and add better tests here but this PR was just on formatting.

2017-02-24 23:24 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "assert(homeworkStack.indexOf('PSY44') === -1, 'message: <code>homeworkStack</code> should not contain <code>\"PSY44\"</code>.');"
@erictleung Right, then I'll merge this :blush:

2017-02-24 23:27 UTC, merged