Add parameter to example code
freeCodeCamp/freeCodeCamp pull request #13380
Opened 2017-02-16 12:50 UTC by jamos-tay

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #13379

#### Description

Added `element` as parameter in example code.

Also converted block code to `blockquote` form, as it looks nicer

2017-02-16 20:55 UTC, dhcodes requested changes

2017-02-16 20:55 UTC, dhcodes commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
>          "In this exercise you will add a function to add a value to our set collection:",
While you're at it, can you change this line from:
>In this exercise you will add a function to add a value to our set collection:

to:

>For this exercise, create a function that will add a value to our set collection as long as the value does not already exist in the set. For example:

2017-02-16 21:00 UTC, dhcodes commented
@jamos-tay I think we could improve it further. Can you change the line in the review on your local branch and then run `git commit --amend` and save the same commit message, and then push your branch again with `-f` to update this PR.

Thanks.

2017-02-17 03:46 UTC, jamos-tay commented
@dhcodes Okay, I've made the necessary changes 👍

2017-02-17 05:19 UTC, dhcodes approved these changes

2017-02-17 05:19 UTC, dhcodes commented
Tested locally and **LGTM!**. Thanks for contributing to freeCodeCamp! 👍 🌮 🎉

2017-02-17 05:19 UTC, merged