changed url
freeCodeCamp/freeCodeCamp pull request #13410
Opened 2017-02-17 21:49 UTC by nellarro

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Changed urls on lines 1140 and 1169 from *<a href=\"https://atjonathan.github.io/catphotoapp\* to *<a href=\"http://freecatphotoapp.com/*

2017-02-17 23:59 UTC, JosephLivengood commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "<a href=\"http://freecatphotoapp.com/" target=\"_blank\">CatPhotoApp</a>"
The endquote needs escaped like
` "<a href=\"http://freecatphotoapp.com/\" target=\"_blank\">CatPhotoApp</a>" `

2017-02-18 00:01 UTC, JosephLivengood requested changes
Also, please enter the issue number this is fixing please!

2017-02-18 00:01 UTC, JosephLivengood commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "<a href=\"http://freecatphotoapp.com/" target=\"_blank\">CatPhotoApp</a>"
The endquote needs escaped :+1:

2017-02-18 03:18 UTC, nellarro commented on seed/challenges/01-responsive-web-design/applied-visual-design.json
> +        "<a href=\"http://freecatphotoapp.com/" target=\"_blank\">CatPhotoApp</a>"
Oh, duh! Lol. Let me change that! Thanks for the heads up!

2017-02-18 06:42 UTC, closed without merging