Reformat ES6 Challenge Descriptions
freeCodeCamp/freeCodeCamp pull request #13414
Opened 2017-02-18 03:12 UTC by robbawebba

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX
Progress towards issue #12698 

#### Description

Reformat descriptions, titles and challenge seed when necessary for 4 Challenges in ES6 section: Nested Object Destructuring, Array Destructuring, Array Destructuring with Rest Operator, and Destructuring Function Parameters

2017-02-18 19:11 UTC, Greenheart requested changes
@robbawebba This is a big improvement, great job! :smile:

Just a few minor thoughts below.

2017-02-18 19:11 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
>          "const arr = source ; // change this",
We might want to remove this space for consistency.

2017-02-18 19:11 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
>          "}",
Missing semicolon here.

2017-02-20 19:42 UTC, robbawebba commented
Thanks for the suggestions @Greenheart!

2017-02-20 20:15 UTC, Greenheart approved these changes
@robbawebba Thanks for fixing this! :smile:

2017-02-20 20:15 UTC, merged