moved comment to new line to remove overflow-x scrollbar
freeCodeCamp/freeCodeCamp pull request #13418
Opened 2017-02-18 04:23 UTC by cdrainxv

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13352

#### Description

Moved comment to next line to negate the need for a scrollbar in the x direction as the text was overflowing on the desktop view.

2017-02-18 18:22 UTC, Greenheart requested changes
@cdrainxv Thanks for the fix! :blush:

2017-02-18 18:22 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "<blockquote>let jennyStr = \"Jenny8675309\";<br>let myRegex = /[a-z0-9]/ig;<br>jennyStr.match(myRegex);<br>// matches all letters and numbers in jennyStr</blockquote>",
@cdrainxv What do you think about moving the comment to the line before the regex?

2017-02-19 03:07 UTC, cdrainxv commented on seed/challenges/02-javascript-algorithms-and-data-structures/regular-expressions.json
> +        "<blockquote>let jennyStr = \"Jenny8675309\";<br>let myRegex = /[a-z0-9]/ig;<br>jennyStr.match(myRegex);<br>// matches all letters and numbers in jennyStr</blockquote>",
I agree.

2017-02-19 09:13 UTC, Greenheart approved these changes
@cdrainxv Thanks!

This is ready to merge

2017-02-19 09:13 UTC, merged