revised circular queue challenge and added working tests
freeCodeCamp/freeCodeCamp pull request #13453
Opened 2017-02-19 21:12 UTC by bonham000

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes #13428

#### Description
This PR revises the Circular Queue challenge in the Advanced Data Structures section with a improved description, instructions, seed code, and working tests.

2017-02-19 22:53 UTC, Greenheart requested changes
@bonham000 Thanks for working on this! :smile:

2017-02-19 22:53 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "In this challenge you will be creating a Circular Queue. A circular queue is basically a queue that writes to the end of a collection then begins over writing itself at the beginning of the
I'd say "a circular queue is commonly used for streaming media" might be a better wording. That way, we're clearer about the use case, and avoid introducing a related word (but not the precise one we refer to in this challenge). What do you think? :blush:

2017-02-19 22:53 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> -        "class CircularQueue {\n  constructor () {\n    this._cq = ['', '', '', '', ''];\n    this._reader = 0;\n    this._writer = 0;\n  }\n  \n  printCollection () {\n    return this._cq;\n  }\n  \
Why did you delete the solution? It's used to improve the coverage of `npm test`, which allows us to see when challenges get breaking tests etc

2017-02-19 22:53 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> -        "class CircularQueue {\n  constructor () {\n    this._cq = ['', '', '', '', ''];\n    this._reader = 0;\n    this._writer = 0;\n  }\n  \n  printCollection () {\n    return this._cq;\n  }\n  \
Ah, I created this solution for the old version of the challenge, so it's no longer valuable.

I think we should add an updated solution.

2017-02-19 22:53 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "In this challenge we will implement a circular queue. The circular queue should provide <code>enqueue</code> and <code>dequeue</code> methods which allow you to read and write to the queue.
What do you think?
```diff
-read and write to the queue
+read from and write to the queue
```

2017-02-20 00:03 UTC, bonham000 commented
@Greenheart hey I made the two revisions and I didn't realize `npm test` was verifying solution code if it's present in the seed files which is the real reason I removed that from the original PR. Anyway, I added in my solution now and verified it with `npm test` so this should be good to go now.

2017-02-20 07:25 UTC, Greenheart requested changes
@bonham000 Nice solution! Just one more thing :smile:

2017-02-20 07:25 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "In this challenge you will be creating a Circular Queue. A circular queue is basically a queue that writes to the end of a collection then begins over writing itself at the beginning of the
If I'm not confusing this for something else, the circular queue technically isn't responsible for the *streaming of media* as the current sentence indicates - it's useful when storing the streaming media.

I'd suggest the following change
```diff
-to stream media
+for streaming media
```

2017-02-20 19:26 UTC, bonham000 commented
@Greenheart sounds good, I've added that change!

2017-02-20 19:29 UTC, Greenheart approved these changes
@bonham000 Thanks! This looks good :blush:

2017-02-20 19:29 UTC, merged