Fixed iPhone frame doesn't disappear on narrow widths
freeCodeCamp/freeCodeCamp pull request #13476
Opened 2017-02-20 21:01 UTC by nawazishali

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #12763

#### Description

I have made changes in challenge.less and have set optimal breakpoint to make the iPhone frame disappear (display:none). The breakpoint I found suitable was 1030px and everything now works as intended. I have also checked for any additional bugs that I might have created but wasn't able to find any.

There is one noticeable thing that I found, Whenever the screen width is less then 1200px the iPhone frame disappears where as it should not disappear if I compare it with the production site. This is happening due to hidden-xs class on a parent div element of iPhone frame. I left this other bug as it is because I think it could be the way you guys would have liked it.

2017-02-21 06:25 UTC, BerkeleyTrue requested changes

2017-02-21 06:25 UTC, BerkeleyTrue commented on client/less/challenge.less
> +    clear: both;
Remove reformatting changes. PR's should be scoped the issue it tries to solve. This adds a ton of noise and makes the PR hard to review.

2017-02-21 13:21 UTC, nawazishali commented on client/less/challenge.less
> +    clear: both;
I have made the changes as requested. Sorry for inconvenience. I didn't pay attention to the formatting and my text editor messed it all up.

2017-02-21 20:27 UTC, Greenheart commented
@nawazishali I'll review the functionality in just a moment.

Meanwhile, could you please squash your commits into one? (See the guide linked in the PR description)

2017-02-21 20:43 UTC, Greenheart approved these changes
@nawazishali Nice work! :+1:

Except from squashing the commits, this is ready to be merged.

As you said in the description, there's an breakpoint at 1200px that might seem strange but I agree that it could be intentional. It actually feels pretty clean to get the output without the iPhone frame.

Keep it up! :smile:

2017-02-22 18:53 UTC, nawazishali commented
I have squashed my last commit into first. Know all should be fine I guess.

2017-02-22 20:32 UTC, Greenheart approved these changes

2017-02-22 20:33 UTC, Greenheart commented
@nawazishali Thanks for contributing! :smile: :tada:

2017-02-22 20:33 UTC, merged

2017-02-23 03:56 UTC, nawazishali commented
@Greenheart No need to thank I am so happy to have my First Pull request merged to such a big Repository. That's what I can call giving back to the community. Thanks to FCC for all this progress I have made.

2017-02-23 10:41 UTC, Greenheart commented
@nawazishali Congratulations! :smile: I totally agree, freeCodeCamp has been a huge opportunity for me as well!

2017-02-24 05:19 UTC, QuincyLarson commented
@nawazishali awesome work. Thank you for helping fix this!

2017-02-24 14:56 UTC, nawazishali commented
@QuincyLarson Thanks to you as well for creating FCC. Your Idea is what made people like me capable of doing all this.