Reformatted instructions for the class ES6 challenges
freeCodeCamp/freeCodeCamp pull request #13559
Opened 2017-02-24 01:37 UTC by IanTeo

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no):

Progress towards issue #12698, which is a compiled list of QA tasks for the new ES6 section introduced in beta

#### Description
* Added \<blockquote\> tag for multi-line code examples
* Added \<dfn\> and \<code\> tags for important terms
* Replaced "Instructions" with \<hr\> tag
* Capitalised first letters of the SpaceShuttle class
* Did not make any changes to the tests

2017-02-25 11:59 UTC, Greenheart requested changes
@IanTeo Great work! :blush: :+1:

2017-02-25 11:59 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "Use <code>class</code> keyword and write a proper constructor to create the Vegetable class.",
```diff
-Vegetable
+<code>Vegetable</code>
```

2017-02-25 11:59 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
>          "The Vegetable lets you create a vegetable object, with a property name, to be passed to constructor."
1. 
```diff
-Vegetable
+<code>Vegetable</code>
```

2. 
```diff
-name
+<code>name</code>
```

2017-02-25 11:59 UTC, Greenheart commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "These are classically called <dfn>getters and setters</dfn>.",
```diff
-<dfn>getters and setters</dfn>
+<dfn>getters</dfn> and <dfn>setters</dfn>
```

2017-02-25 20:20 UTC, IanTeo commented
I have made the requested changes

2017-02-26 23:17 UTC, erictleung requested changes

2017-02-26 23:17 UTC, erictleung commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "Now create <dfn>getter and setter</dfn> in the class, to obtain the temperature in Celsius scale.",
[Same change suggestion](https://github.com/freeCodeCamp/freeCodeCamp/pull/13559/files#r103077540) should be made here as well.

```diff
- <dfn>getter and setter</dfn>
+ <dfn>getter</dfn> and <dfn>setter</dfn>
```

2017-02-27 01:01 UTC, IanTeo commented
Sorry, I missed that. I have made the changes requested

2017-02-27 13:45 UTC, Greenheart approved these changes
@IanTeo Thanks for fixing this! I've tested this locally and it looks good! :smile: :+1:

2017-02-27 13:45 UTC, merged