fix(challenge): More robust test for "Learn how a Stack Works".
freeCodeCamp/freeCodeCamp pull request #13576
Opened 2017-02-24 23:56 UTC by Greenheart

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13459 

#### Description

Improve robustness of the tests by ensuring that the `homeworkStack` wasn't overwritten.

2017-02-26 23:28 UTC, erictleung requested changes
Close, just a small change so it renders correctly.

2017-02-26 23:28 UTC, erictleung commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "assert(code.match(/=/g).length === 1 && /homeworkStack\\s*=\\s*\\[\"BIO12\"\\s*,\\s*\"HIS80\"\\s*,\\s*\"MAT122\"\\s*,\\s*\"PSY44\"\\]/.test(code)), 'message: The initial declaration of the <
You're missing a closing parens and semicolon :smile: 

```diff
- <code>homeworkStack</code> should not be changed.'"
+ <code>homeworkStack</code> should not be changed.');"
```

So it's creating a stray single quote in the tests

![image](https://cloud.githubusercontent.com/assets/2754821/23344829/0f2f9e7e-fc38-11e6-8445-7327a5316754.png)

2017-02-27 14:22 UTC, Greenheart commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/coding-interview-data-structure-questions.json
> +        "assert(code.match(/=/g).length === 1 && /homeworkStack\\s*=\\s*\\[\"BIO12\"\\s*,\\s*\"HIS80\"\\s*,\\s*\"MAT122\"\\s*,\\s*\"PSY44\"\\]/.test(code)), 'message: The initial declaration of the <
@erictleung Haha nice catch! :smile:

2017-02-27 14:28 UTC, Greenheart commented
@erictleung Should be fixed now :wink:

2017-03-09 09:02 UTC, erictleung approved these changes
Sorry for the late QA! Been busy lately. Nonetheless, LGTM! 👍  Thanks for working on this!

2017-03-09 09:02 UTC, merged

2017-03-17 19:46 UTC, Greenheart commented
@erictleung Haha no worries! I've been away for the last few weeks myself :smile:

2017-03-22 05:56 UTC, QuincyLarson commented
@Greenheart awesome work on these. Thanks for all these contributions.