Fix missing backtick in the description, move sample code in a blockq…
freeCodeCamp/freeCodeCamp pull request #13712
Opened 2017-03-03 12:42 UTC by szib

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Closing backtick was missing in the sample code. Moved the code and result into blockquotes.

2017-03-03 12:48 UTC, raisedadead commented
Thanks @szib, Just a query any open issues about this to be tagged?, its alright if there are none.

Pro tip: Keep commit messages shorter ( <=50 Chars )
https://chris.beams.io/posts/git-commit/

2017-03-03 12:50 UTC, szib commented
#13704 relates to it, but it does not fix that issue. OK. I'll keep them shorter. Thanks.

2017-03-03 16:13 UTC, systimotic requested changes
Nice work @szib, thank you for contributing! Could you bring back the `div` tags? You will have to escape the `<` and `>` characters as `&lt;` and `&gt;`

2017-03-03 16:16 UTC, systimotic commented
I just noticed, escaping `<li>` in line 554 as `&lt;li&gt;` should fix the issue. While you're at it, could you also wrap `${variable}` in the description in `<code>` tags? Those don't need to be escaped.

2017-03-03 18:51 UTC, szib commented
@systimotic I missed your last comment and updated the PR without wrapping ${variable}. I'll update it again soon. Sorry for making mistakes, I'm new to contributing. I did not think that errors in the description were the cause of #13704, but I believe it is fixed now. I wanted to fix only the missing backtick in the sample code, that's why I did not refer to that issue.

2017-03-03 19:10 UTC, szib commented
"If you have trouble finding backticks, it's the ` key, to the left of your 1; and has ¬ on it."
I changed ~ to ¬ as the backtick key on my UK keyboard has ¬ on it, not ~. I thought it was a mistake, but I've just realised UK and US keyboards are different. Probably this sentence need to be rephrased, but no idea how.

2017-03-04 15:31 UTC, systimotic commented
@szib Yeah, it's different on all keyboard layouts. Perhaps we should link [this superuser answer](http://superuser.com/a/254077) instead?

2017-03-04 15:33 UTC, systimotic requested changes
This is really good work! Thank you so much for updating the PR

2017-03-04 15:33 UTC, systimotic commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "The expected output is each entry of result object's failure array, wrapped inside an element, with class attribute text-warning.",
You removed the `<li>` here. Instead, please escape it like the divs above: `&lt;/div&gt;`

2017-03-04 19:20 UTC, szib commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "The expected output is each entry of result object's failure array, wrapped inside an element, with class attribute text-warning.",
Thanks for your help @systimotic You're absolutely right, I'll fix it soon and insert your superuser link as well.

2017-03-04 22:16 UTC, systimotic requested changes
This challenge will be much improved by your changes, thank you so much @szib!
I'm sorry, but I'm going to keep annoying you for a little bit longer 😅 
Thank you for staying on top of things. It's really helpful when people stay around and make the needed changes.

2017-03-04 22:16 UTC, systimotic commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "Backtick key is usually located just above [TAB], to the left of your 1. If you have trouble finding it, read <a href=\"http://superuser.com/a/254077\" target=\"_blank\">this article</a>. "
```diff
- Backtick key is usually located just above [TAB], to the left of your 1.
+ The backtick key is usually located right above \"tab\", to the left of the \"1\" key.
```

2017-03-04 22:16 UTC, systimotic commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "Backtick key is usually located just above [TAB], to the left of your 1. If you have trouble finding it, read <a href=\"http://superuser.com/a/254077\" target=\"_blank\">this article</a>. "
There's a trailing space behind the last period. Sorry, I'm really nitpicking here 😅

2017-03-04 22:16 UTC, systimotic commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "Backtick key is usually located just above [TAB], to the left of your 1. If you have trouble finding it, read <a href=\"http://superuser.com/a/254077\" target=\"_blank\">this article</a>. "
Looks like superuser also serves over HTTPS, so let's link to that instead 👍 https://superuser.com/a/254077

2017-03-05 20:19 UTC, szib commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "Backtick key is usually located just above [TAB], to the left of your 1. If you have trouble finding it, read <a href=\"http://superuser.com/a/254077\" target=\"_blank\">this article</a>. "
Thanks. 👍  I have fixed them now.

2017-03-30 16:16 UTC, raisedadead commented
@systimotic I believe this is ready, except for the merge conflicts, which we can resolve. Should I do that and merge, after a sanity check?

2017-04-10 16:57 UTC, dhcodes commented
@raisedadead yes, sanity check and merge after resolving conflicts if good to go.

2017-04-23 19:48 UTC, raisedadead commented
@robbawebba @szib Can you guys confirm if the changes in this PR are valid. I was checking the merge conflict, and am unsure if the last change made to this file by @robbawebba has already taken care of what this PR was aiming.

Sorry about the delay in the QA.

2017-04-24 10:18 UTC, szib commented
@raisedadead It seems to me @robbawebba rewrote this challenge since my PR. I suppose there's no need to merge this PR.

2017-04-24 10:45 UTC, raisedadead commented
@szib thanks for the update and we value your contribution, please keep them coming. :smile:

2017-04-24 10:45 UTC, closed without merging

2017-05-26 16:43 UTC, systimotic commented
I apologize for disappearing @szib! I was busy with exams and haven't been around, but I'm back now. I look forward to seeing your contributions again!