Changed icon color to improve general UX
freeCodeCamp/freeCodeCamp pull request #13720
Opened 2017-03-03 17:26 UTC by Ethan-Arrowood

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #12844

#### Description

Changed icon color to be better appealing and less distracting to the user. Was previously too light, then changed to green which was mis-informative, now it is dark grey similar to color of the text (see image below). 
<img width="356" alt="screen shot 2017-03-03 at 11 07 50 am" src="https://cloud.githubusercontent.com/assets/16144158/23561513/8e441e06-000c-11e7-9886-0c7fd00f7447.png">

2017-03-03 18:26 UTC, Bouncey commented
@Ethan-Arrowood can you show me what is looks like in night mode? I do like the grey

2017-03-03 18:32 UTC, raisedadead requested changes

2017-03-03 18:32 UTC, raisedadead commented on client/less/challenge.less
> +  color: #575757;
please declare this as a variable and use here.

2017-03-03 18:35 UTC, Ethan-Arrowood commented on client/less/challenge.less
> +  color: #575757;
Okay

2017-03-03 18:36 UTC, Ethan-Arrowood commented on client/less/challenge.less
> +  color: #575757;
Once I make the change whats the correct way to fix my PR?

2017-03-03 19:01 UTC, raisedadead commented on client/less/challenge.less
> +  color: #575757;
Follow the below:

```sh
git add <filename>
git commit --amend --no-edit
git push --force
```

2017-03-03 19:02 UTC, raisedadead commented on client/less/challenge.less
> +  color: #575757;
This will automatically update the PR.

2017-03-03 19:05 UTC, renjit00 commented
Hi guys....i want to join with you ...

2017-03-03 19:46 UTC, Ethan-Arrowood commented on client/less/challenge.less
> +  color: #575757;
Okay great thank you.

2017-03-03 22:55 UTC, systimotic commented
@Bouncey Very good point. This will probably need to be changed in the night mode.  

![firefox_2017-03-03_23-49-55](https://cloud.githubusercontent.com/assets/7262039/23572022/af326766-006c-11e7-8334-ee3376bdf63a.png)

2017-03-04 02:41 UTC, Ethan-Arrowood commented on client/less/challenge.less
> +  color: #575757;
@raisedadead 

> please declare this as a variable and use here.

Is there a preferred file I should declare the variable or can I do it in the challenge.less file?

2017-03-04 19:12 UTC, BerkeleyTrue commented on client/less/challenge.less
> +  color: #575757;
client/less/bootstrap/variables

2017-03-04 22:03 UTC, Ethan-Arrowood commented on client/less/challenge.less
> +  color: #575757;
thank you @BerkeleyTrue didn't know if I was allowed to make edits there or not.

2017-03-04 22:12 UTC, Ethan-Arrowood commented
@systimotic How does this look for night mode?
<img width="396" alt="screen shot 2017-03-04 at 5 11 24 pm" src="https://cloud.githubusercontent.com/assets/16144158/23582681/ac0ef4c8-00fd-11e7-8403-5bba35033566.png">
I made it match the font color

2017-03-04 22:20 UTC, Bouncey commented
## LGTM :+1: 

Thanks for contributing :tada:

2017-03-04 22:21 UTC, merged

2017-03-04 22:23 UTC, Ethan-Arrowood commented
@Bouncey Thank you! I love working on FCC 😄

2017-03-04 22:27 UTC, systimotic commented
@Ethan-Arrowood Thanks a lot for contributing! Isn't it so much fun?

2017-03-04 22:35 UTC, Ethan-Arrowood commented
@systimotic It is! I'm already working on another issue regarding the npm tests 😋