Review/editing pass on the pt-br text of the getting-started section
freeCodeCamp/freeCodeCamp pull request #13756
Opened 2017-03-05 13:42 UTC by ellenkorbes

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [x] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description
This is a review/editing pass on the pt-br text of the getting-started section. I focused on making the text sound more natural, how Portuguese actually does, instead of making sure every word was perfectly translated from the original.

I'm getting a mountain of errors when trying to run the tests. Since I didn't change the structure of the file in any way though, only words and sentences, I don't think the errors have anything to do with my changes. Lemme know if I'm wrong.

2017-03-06 12:05 UTC, frontendwizard approved these changes
LGTM. Definitely improves the translation. Good work @ellenkorbes

2017-03-09 21:13 UTC, systimotic requested changes
Thanks a lot for these improvements @ellenkorbes! Big thanks to @julianorafael as well for QA'ing!
We try to get PR's reviewed and merged as soon as we can, but we've been [really busy](https://github.com/freeCodeCamp/freeCodeCamp/pulse) since the beta release. Things can take a little longer sometimes 😅

2017-03-09 21:13 UTC, systimotic commented on seed/challenges/00-getting-started/getting-started.json
> +          "An illustration showing that you will learn HTML5, CSS3, JavaScript, Databases, Git, Node.js, React, and D3.",
The next sentence does not have an Oxford comma either. Can you remove the added Oxford comma here for consistency?

2017-03-09 22:11 UTC, systimotic approved these changes
# LGTM 🎉 
Thanks for the improvements @ellenkorbes!
Again, a big thanks to @julianorafael as well for QA'ing, having another speaker QA is crucial to great translations.

2017-03-09 22:11 UTC, merged