Fix typo in basic-css-hex-code-colors. Add article -the- to description.
freeCodeCamp/freeCodeCamp pull request #13795
Opened 2017-03-07 19:35 UTC by homerrowsky

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13581 

#### Description

- This change is a **first-timers-only** contribution. 
- **Adds article _'the'_ to a sentence** in the challenge's description.
- This is an additional change suggested by @erictleung after one made by @eti8.

closes #13581

2017-03-07 19:51 UTC, ooade approved these changes

2017-03-08 05:39 UTC, erictleung requested changes
Looks good. Just one more small change. Let us know if you need any help making this change.

2017-03-08 05:39 UTC, erictleung commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "We usually use <code>decimals</code>, or base 10 numbers, which use the symbols 0 to 9 for each digit. <code>Hexadecimals</code> (or <code>hex</code>) are base 16 numbers. This means it uses
I think [we agreed](https://github.com/freeCodeCamp/freeCodeCamp/issues/13581#issuecomment-282499672) to add in "the" in this sentence as well.

```diff
- Like decimals, the symbols 0-9 represent values zero to nine. 
+ Like decimals, the symbols 0-9 represent the values zero to nine.
```

2017-03-08 06:12 UTC, homerrowsky commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "We usually use <code>decimals</code>, or base 10 numbers, which use the symbols 0 to 9 for each digit. <code>Hexadecimals</code> (or <code>hex</code>) are base 16 numbers. This means it uses
@erictleung 
**Ouch..**, I passed by the comment of @Greenheart. Sorry :(.
**I suppose I have to make a new pull request, is it right?** (Don't know if there is a _'un-pull request'_)

2017-03-08 16:43 UTC, homerrowsky commented
@erictleung :

I did this: 
1. **Modified the file to add Greeenheart's suggestion**
1. **Commited the change** _--(I realized that my question of 'un-pull request' was wrong. I needed to squash commits according to FCC Contributing Guide)_ :open_mouth: 
1. **git pull --rebase upstream staging** _--(Update my local fork of FCC)_ 
1. **git push origin staging** _--(Push the update just done to my remote github fork. OPTIONAL )_
1. **git checkout fix/typo-in-html-and-css** _--(Change to my local branch where edits are made)_
1. **git rebase -i staging** _--(Squash the last two commits of my testing branch, with a rebase against the updated version of my local staging. This was a little painful, never done before)_ :cold_sweat: 
1. **git push -f origin fix/typo-in-html-and-css** _--(Push the squashed commits to my remote branch)_

So that's it. I hope it was well done.
Thanks for your support to all FCC comrades! I've been learning very A LOT from this project.
:+1: :+1: :+1:

2017-03-08 17:38 UTC, erictleung approved these changes
LGTM! 👍  Thanks for your contribution and congrats! 🎉  A small change goes a long way 😄

2017-03-08 17:38 UTC, merged

2017-03-17 19:50 UTC, Greenheart commented
@homerrowsky Thanks for contributing! :smile: 🙌

2017-03-22 05:56 UTC, QuincyLarson commented
@homerrowsky thanks for your contribution!