Combine Google Font challenges into one
freeCodeCamp/freeCodeCamp pull request #13960
Opened 2017-03-16 23:03 UTC by HKuz

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13471 

#### Description

The curriculum expansion added a challenge (in the Applied Visual Design section) about importing a Google Font. It covered the same concept as the existing "Use a Google Font" challenge in the Basic CSS section. This PR layers some additional information from the new challenge into the original Google Font challenge (and slightly tweaks the "How Fonts Degrade" challenge), and removes the new one.

2017-03-17 13:34 UTC, dhcodes requested changes
@HKuz Thanks for doing this. Please see my comments; I think there are some ways the instructions could be shortened and improved. Let me know what you think.

2017-03-17 13:34 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "<a href='https://fonts.google.com/' target='_blank'>Google Fonts</a> is a great way to find free fonts to use in a project.",
I recommend changing this line to:
>Google Fonts is a free library of web-safe fonts that you can use in your CSS by referencing the font's URL.

2017-03-17 13:34 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "Once you have selected the preferred font, copy the link tag that is provided and insert it into the <code>head</code> of your page.",
IMHO, this is misleading as this suggests they can choose any font for this challenge. I recommend removing this line.

2017-03-17 13:34 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "Then, you can make a <code>call</code> to Google to grab the <code>Lobster</code> font and load it into your HTML.",
I recommend changing this to:
>To import a Google Font, you can copy the font(s) URL from the Google Fonts library and then paste it in your HTML. For this challenge, we'll import the <code>Lobster</code> font. To do this, copy the following code snippet and paste it into the top of your code editor:
`<code>&#60;link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\" type=\"text/css\"&#62;</code>`

2017-03-17 13:34 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "The font is available to include in your CSS by using the pattern:<br><code>font-family: FAMILY_NAME, GENERIC_NAME;</code>.",
I recommend changing this to:
>Now you can use the `Lobster` font in your CSS by using `Lobster` as the FAMILY_NAME as in the following example:
`<br><code>font-family: FAMILY_NAME, GENERIC_NAME;</code>`

2017-03-17 13:34 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
>          "Remember, before you can apply styles, like a new font, to an element, you'll need to create a CSS rule.",
Consider removing; seems unnecessary?

2017-03-17 13:34 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
>          "Copy the following code snippet and paste it into the top of your code editor:",
Remove this line in favor of above.

2017-03-17 13:34 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
>          "<code>&#60;link href=\"https://fonts.googleapis.com/css?family=Lobster\" rel=\"stylesheet\" type=\"text/css\"&#62;</code>",
Remove this line in favor of above.

2017-03-17 13:36 UTC, dhcodes commented
@HKuz should've named your branch `oneGoogleFontToRuleThemAll` #missedopportunity 😆

2017-03-17 18:09 UTC, HKuz commented
@dhcodes - I was *thisclose* to naming my branch that, then reconsidered because it seemed long. Haha - a missed opportunity indeed. 😞 

These comments are all good - I'm turning them now, and will update 👍

2017-03-17 20:46 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "<a href='https://fonts.google.com/' target='_blank'>Google Fonts</a> is a free library of web-safe fonts that you can use in your CSS by referencing the font's URL.",
@HKuz Great work! I made a mistake though. The fonts on Google Fonts aren't web-safe (my poor understanding of the terminology) so can you change "web-safe" to "web"

2017-03-17 20:47 UTC, dhcodes commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "<a href='https://fonts.google.com/' target='_blank'>Google Fonts</a> is a free library of web-safe fonts that you can use in your CSS by referencing the font's URL.",
Otherwise it's good to go.

2017-03-17 22:14 UTC, HKuz commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "<a href='https://fonts.google.com/' target='_blank'>Google Fonts</a> is a free library of web-safe fonts that you can use in your CSS by referencing the font's URL.",
Sounds good! Updating this now 👍

2017-03-18 03:07 UTC, dhcodes commented
Tested and **LGTM**! Thanks for putting up with my suggestions :) 🌮 💎 :octocat:

2017-03-18 03:07 UTC, dhcodes approved these changes

2017-03-18 03:07 UTC, merged

2017-03-18 18:38 UTC, HKuz commented
Thanks @dhcodes 🍻 🍀 :1st_place_medal: !!

2017-03-22 05:33 UTC, QuincyLarson commented
@HKuz @dhcodes thanks for making this improvement. I agree - this is more streamline 😄