Tweaked title and description of JSON APIs and AJAX challenge
freeCodeCamp/freeCodeCamp pull request #13988
Opened 2017-03-18 12:06 UTC by hay-dee

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #13586 

#### Description

Tweaked title of [JSON APIs and Ajax: Trigger click Events with JavaScript challenge](http://beta.freecodecamp.com/en/challenges/json-apis-and-ajax/trigger-click-events-with-javascript), to suit the topic of the challenge, which is the <code>onclick</code> property. Also tweaked the description to move certain portions to a more appropriate challenge. Finally, added a hint that the <code>onclick</code> event handler is but one of many event handlers.

2017-03-22 05:55 UTC, QuincyLarson reviewed
This is almost there.

2017-03-22 05:55 UTC, QuincyLarson commented on seed/challenges/04-data-visualization/json-apis-and-ajax.json
> +        "Remember that APIs - or Application Programming Interfaces - are tools that computers use to communicate with one another. You'll learn how to update HTML with the data we get from APIs usin
You left off a period at the end of this sentence.

2017-03-22 05:55 UTC, QuincyLarson commented on seed/challenges/04-data-visualization/json-apis-and-ajax.json
> +        "You can implement event handlers that goes inside of the <code>DOMContentLoaded</code> function. You can implement an <code>onclick</code> event handler which triggers when the user clicks o
"goes" should be "go". "which" should be "that".

2017-03-25 10:46 UTC, raisedadead requested changes
@hay-dee thanks for the pull request, can you please address the review comments?

2017-03-25 12:53 UTC, hay-dee commented on seed/challenges/04-data-visualization/json-apis-and-ajax.json
> +        "You can implement event handlers that goes inside of the <code>DOMContentLoaded</code> function. You can implement an <code>onclick</code> event handler which triggers when the user clicks o
Hi @QuincyLarson , thanks for reviewing this PR! Should it be "You can implement event handlers **that** go .." or "You can implement event handlers **which** go .."?

2017-03-25 13:15 UTC, hay-dee commented
Hi @raisedadead @QuincyLarson , apologies for the delay. I could not find time to work on this during the weekdays. I have updated the PR, hopefully in a correct manner, to address the changes mentioned. Kindly excuse the multiple amendments as its my first time updating a PR 😅 .

2017-03-25 15:50 UTC, raisedadead approved these changes

2017-03-25 15:51 UTC, raisedadead commented
@QuincyLarson this LGTM, unless you have any more points to add?

2017-03-25 15:53 UTC, raisedadead commented on seed/challenges/04-data-visualization/json-apis-and-ajax.json
> +      "title": "Handle Click Events with Javascript using the onclick property",
```diff 
- Javascript
+ JavaScript
```

2017-03-25 18:26 UTC, raisedadead requested changes
Minor change.

2017-03-26 02:42 UTC, hay-dee commented
@raisedadead PR has been updated to include the change 😄

2017-03-26 06:13 UTC, QuincyLarson commented
@hay-dee Awesome. Since @raisedadead has an open review, I'll leave merging this to him :)

2017-03-26 08:39 UTC, raisedadead approved these changes

2017-03-26 08:40 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @hay-dee !

2017-03-26 08:40 UTC, merged

2017-03-26 19:00 UTC, QuincyLarson commented
@hay-dee thanks for your contribution!