Improve Node challenges wording and formatting
freeCodeCamp/freeCodeCamp pull request #14061
Opened 2017-03-23 07:53 UTC by Atomk

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Changed the descriptions of the Node challenges to achieve a bit higher level of quality. There were many inconstitencies in the way some technical terms are used, some confusing formatting errors due to words being put between angle brackets and ignored by the browser... A lot of stuff. I didn't fix everything, but now it is better for sure.

2017-03-24 19:24 UTC, raisedadead commented
Hi @Atomk thanks for the PR, can you please rebase this against staging? There are conflicts that have crept in with https://github.com/freeCodeCamp/freeCodeCamp/pull/14054

2017-03-24 19:26 UTC, raisedadead requested changes

2017-03-24 19:26 UTC, raisedadead commented on seed/challenges/05-apis-and-microservices/basic-node-and-express.json
> +        "During the development process, it is important to be able to check what’s going on in your code. Node is just a Javascript environment. Like client side Javascript, you can use the console
```diff
- Javascript
+ JavaScript
```

As per convention.

2017-03-24 19:26 UTC, raisedadead commented on seed/challenges/05-apis-and-microservices/basic-node-and-express.json
> +        "During the development process, it is important to be able to check what’s going on in your code. Node is just a Javascript environment. Like client side Javascript, you can use the console
Here and all other places.

2017-03-26 22:29 UTC, Atomk commented
@raisedadead I did a bit of a mess with Git but I think I solved the problem.

2017-03-30 18:30 UTC, raisedadead approved these changes

2017-03-30 19:09 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @Atomk

2017-03-30 19:10 UTC, merged