allow spaces between style attribute and its value
freeCodeCamp/freeCodeCamp pull request #14117
Opened 2017-03-27 11:47 UTC by JoolsMcFly

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #14116

#### Description

http://beta.freecodecamp.com/challenges/basic-css/change-the-color-of-text challenge does not allow for spaces around `style` and its value:
`<h2 style = "color:red">CatPhotoApp</h2>` should be a valid answer according to https://www.w3.org/TR/html51/syntax.html#elements-attributes under (see **Double-quoted attribute value syntax**).

This PR simply adds `\s*` around the `=` sign in the assertion regexp.

Thanks!

2017-03-29 22:57 UTC, no-stack-dub-sack commented
@JoolsMcFly Thanks for the PR, but I was hoping to get some input on the other issues I mentioned with this challenge on the issue page first - what are your thoughts? I was thinking that since we allow `red` and the rgb value for red, perhaps we should also allow the other values that will equal red, namely hex since this is such a common notation in CSS.  

Would you like to make an update to the PR for at least hex, and we can worry about other possible notations later?

2017-03-29 22:57 UTC, no-stack-dub-sack requested changes

2017-03-29 22:57 UTC, no-stack-dub-sack commented on seed/challenges/01-responsive-web-design/basic-css.json
> +        "assert(code.match(/<h2\\s+style\\s*=\\s*\"color:\\s*rgb\\(255,\\s*0,\\s*0\\)\\;?\">\\s*CatPhotoApp\\s*<\\/h2>/) || code.match(/<h2\\s+style\\s*=\\s*\"color:\\s*red\\;?\">\\s*CatPhotoApp\\s*<
Can we add hex value to this test?

2017-03-30 05:08 UTC, JoolsMcFly commented
Np, I'll update this PR soon.

2017-04-03 22:30 UTC, no-stack-dub-sack commented
@JoolsMcFly Any progress on this?

2017-04-04 04:51 UTC, JoolsMcFly commented
Hey, sorry, I've been busy these past days. I'll get on it this week.

2017-04-04 08:25 UTC, JoolsMcFly commented
Updated regexp should allow for these variants:
`color:red`
`color: rgb(255, 0, 0)`
`color: rgb(100%, 0%, 0%)` //alternative use of rgb
`color: #ff0000`
`color: #f00` //short form
`color: hsl(0, 100%, 50%)` // we never know!

Extra spaces in values and trailing `;` are also handled.

And, of course, extra spaces around `style` are allowed.

2017-04-04 21:38 UTC, no-stack-dub-sack commented
@JoolsMcFly awesome! Very thorough, I like it. Let me run this locally and check it out!

2017-04-04 21:50 UTC, no-stack-dub-sack commented
Pulled down changes and tested locally with all values stated above. I think this covers everything! Nicely work @JoolsMcFly! 

### LGTM! ✨  🌟  ✨  🌟  ✨  🌟  ✨  🌟

2017-04-04 21:51 UTC, no-stack-dub-sack approved these changes

2017-04-04 21:51 UTC, merged

2017-04-04 21:56 UTC, JoolsMcFly commented
Excellent, thank you!