Protect the global name space from the code editor
freeCodeCamp/freeCodeCamp pull request #14214
Opened 2017-04-02 16:56 UTC by Bouncey

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #7270

#### Description

Adds `window` prop names to a `predef` list used for codemirror linting.

Linter warns that you are redefining ${variableName}

2017-04-18 18:16 UTC, BerkeleyTrue requested changes

2017-04-18 18:16 UTC, BerkeleyTrue commented on common/app/routes/challenges/views/classic/Editor.jsx
> +    predef: [ ...envProps ]
You can just you the `envProps` direction.

2017-05-15 17:36 UTC, BerkeleyTrue approved these changes

2017-05-15 17:37 UTC, BerkeleyTrue commented
Code LGTM.

2017-05-26 16:01 UTC, Bouncey commented
cc @freeCodeCamp/moderators

2017-07-19 13:00 UTC, Greenheart approved these changes

2017-08-19 12:17 UTC, systimotic commented
@Bouncey Can you update this to resolve the merge conflict?

2017-09-02 03:27 UTC, BerkeleyTrue commented
merged!!!!!
https://github.com/freeCodeCamp/freeCodeCamp/commit/1126bf7004ec6cabfeb0641eefc823175d33c4ba

🍺 🍻 

Happy Coding!

2017-09-02 03:27 UTC, closed without merging