fix(challenges): Fix classic modal styling not rendering
freeCodeCamp/freeCodeCamp pull request #14609
Opened 2017-04-26 23:47 UTC by BerkeleyTrue

Move classic modal less files co-locating them in the app file structure

closes #14215

2017-05-02 19:31 UTC, Bouncey requested changes

2017-05-02 19:31 UTC, Bouncey commented on client/less/classic-modal.less
> -  .modal-header {
Somewhere along the way I think we lost the background colour to the `.modal-header`, it must have been inherited. 

So here will need to be 
```css
.modal-header {
  background-color: @brand-primary;
  color: #fff;
  margin-bottom: 0;
}
```

2017-05-02 21:57 UTC, BerkeleyTrue commented on client/less/classic-modal.less
> -  .modal-header {
Wasn't that removed on purpose? I seem to remember a discussion about this

2017-05-02 23:32 UTC, Bouncey commented on client/less/classic-modal.less
> -  .modal-header {
Blame on the file says it hasn't been edited since it was merged. I had it mimic the production version

2017-05-02 23:34 UTC, BerkeleyTrue commented on client/less/classic-modal.less
> -  .modal-header {
Cool, I'll add the background color in

2017-05-15 17:35 UTC, BerkeleyTrue commented
@Bouncey updated

2017-05-19 04:46 UTC, Bouncey commented
## LGTM

:+1: 

Thanks for contributing @BerkeleyTrue :wink:

2017-05-19 04:46 UTC, merged