Change the text of a jQuery challenge description
freeCodeCamp/freeCodeCamp pull request #14799
Opened 2017-05-10 00:21 UTC by Ntropish

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #14608 

#### Description
Rewrites the description of the challenge "jQuery: Target the Children of an Element Using jQuery".
It doesn't change the challenge itself other than a slight rewording of the instructions.

The reason for the change is that the description was incorrect. It described descendants as if they were children. It also previously talked about property inheritance which is outside the scope of the challenge. Going outside the scope violates the instruction "Each challenge should teach exactly one concept" from the challenge style guide.

2017-05-11 00:57 UTC, frutsy007 commented
Let my

2017-05-11 05:22 UTC, raisedadead requested changes
Some minor changes, and I think this is good.

2017-05-11 05:22 UTC, raisedadead commented on seed/challenges/03-front-end-libraries/jquery.json
> +
Remove this extra newline

2017-05-11 05:22 UTC, raisedadead commented on seed/challenges/03-front-end-libraries/jquery.json
> +        "Here's an example of how you would use the <code>children()</code> function to give the children of your <code>left-well</code> element the color blue:",
Consider wrapping `blue` in a `<code></code>`

2017-05-11 13:25 UTC, Ntropish commented on seed/challenges/03-front-end-libraries/jquery.json
> +
Should it be in the format `[..."lineOne<hr>", "lineTwo"...]`? I'm unfamiliar with the system, thanks for the help.

2017-05-14 17:45 UTC, raisedadead commented on seed/challenges/03-front-end-libraries/jquery.json
> +
@Ntropish Yes, that is correct. The diff shows that this JSON has an extra line. If you are stuck, you can let us know in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), we will try and help.

2017-05-14 17:48 UTC, raisedadead commented on seed/challenges/03-front-end-libraries/jquery.json
> +
Here is how the diff looks to me:
```diff
-        "Give all the children of your <code>#right-well</code> element a color of orange."
+        "<hr>",
+        "Give all the children of your <code>right-well</code> element the color orange."
+
+        ],
+       "challengeSeed": [
```

And here is how it should be:
```diff
-        "Give all the children of your <code>#right-well</code> element a color of orange."
+        "<hr>",
+        "Give all the children of your <code>right-well</code> element the color orange."
+        ],
+       "challengeSeed": [
```

2017-05-14 17:50 UTC, raisedadead commented
You can push changes to this same PR by amending your commit, the instructions are there in the [Guidelines for Contributing](https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md).

> git add <file name>
> git commit --amend

2017-05-30 18:28 UTC, raisedadead approved these changes

2017-05-30 18:29 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @Ntropish ! Congrats on your first contribution to freeCodeCamp! Sorry about the delay in getting back to you!

Happy coding!

2017-05-30 18:29 UTC, merged