fix(code-uri): Chrome iframe error with XSS Auditor
freeCodeCamp/freeCodeCamp pull request #15064
Opened 2017-05-26 18:59 UTC by raisedadead

- [x] remove solution from URI

Closes #13727

2017-05-26 22:48 UTC, systimotic requested changes
This works upon load, which is an improvement and tells us this fix will work, which is great. However, as soon as I start typing, the URL is updated and things break. If we stop updating the URL, I believe this fix will work. Disabling auto run does not seem necessary to me, we only need to stop changing the URL.
As an aside, we should take a look at what this does to solutions in your profile once we fix this.

Great work!

2017-05-26 22:52 UTC, BerkeleyTrue commented
@systimotic I've updated the user stories for this PR

I don't believe this will have an effect on loading user solutions, since this still loads the code initially

2017-05-27 06:11 UTC, raisedadead commented
Just to note:

1. I have ensured that existing URL code is parsed in, and added to the editor before being removed.
2. Code submission and save in DB is NOT affected.

Please let me know if I might have missed any corner cases.

2017-05-27 10:42 UTC, systimotic approved these changes

2017-05-27 10:44 UTC, systimotic commented
Looks like this works great! I can confirm that this resolves the original issue.

What I was worried about was loading and especially saving the user solutions, but that still works wonderfully. I originally thought it may have been doing that based on the URL, but luckily that was not the case.

@BerkeleyTrue Can you confirm, and if everything is OK, merge and deploy?

2017-05-27 12:23 UTC, raisedadead commented
> I originally thought it may have been doing that based on the URL, but luckily that was not the case.

Yes, actually that's what took analyzing and testing so long, turns out that I wasn't aware of a ton of inner working of the code runner. Lol.

2017-06-10 05:54 UTC, BerkeleyTrue approved these changes

2017-06-10 05:54 UTC, BerkeleyTrue commented
Code LGTM.
Since both of you have tested it out I'm going to go ahead and launch this

2017-06-10 05:55 UTC, merged