Add available for hire button
freeCodeCamp/freeCodeCamp pull request #15420
Opened 2017-06-17 22:12 UTC by padulam

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15357

#### Description

This update adds an available for hire button to the user settings page. The default setting for this button is 'unavailable'. The user can toggle the button from available/unavailable, similar to the other buttons on the settings page.

2017-06-18 05:29 UTC, raisedadead requested changes
This key should be better named to `isAvailableForHire` for sake of understanding

2017-06-18 05:29 UTC, raisedadead commented on server/services/user.js
> +  'isAvailable',
This key should be better named to `isAvailableForHire`

2017-06-18 05:29 UTC, raisedadead commented on server/boot/user.js
> +          isAvailable: true,
This key should be better named to `isAvailableForHire`

2017-06-18 05:29 UTC, raisedadead commented on server/boot/settings.js
> +    toggleUserFlag('isAvailable')
This key should be better named to `isAvailableForHire`

2017-06-18 05:29 UTC, raisedadead commented on common/models/user.json
> +    "isAvailable": {
This key should be better named to `isAvailableForHire`

2017-06-18 05:29 UTC, raisedadead commented on common/app/routes/settings/redux/update-user-saga.js
> +  isAvailable: 'available-for-hire',
This key should be better named to `isAvailableForHire`

2017-06-18 05:29 UTC, raisedadead commented on common/app/routes/settings/components/Settings.jsx
> +              isAvailable={ isAvailable }
This key should be better named to `isAvailableForHire`

2017-06-18 05:29 UTC, raisedadead commented on common/app/routes/settings/components/Job-Settings.jsx
> +          { isAvailable ? 'Available' : 'Unavailable' }
This key should be better named to `isAvailableForHire`

2017-06-18 05:29 UTC, raisedadead commented on common/app/routes/settings/components/Job-Settings.jsx
> +  isAvailable: PropTypes.bool,
This key should be better named to `isAvailableForHire`

2017-06-18 13:17 UTC, padulam commented
@raisedadead I updated all instances of the isAvailable key to isAvailableForHire. I also updated the toggleIsAvailable function to toggleIsAvailableForHire. Thanks!

2017-06-18 16:56 UTC, BerkeleyTrue approved these changes

2017-06-21 08:48 UTC, raisedadead approved these changes

2017-06-21 08:50 UTC, raisedadead commented
Awesome! Changes LGTM, I'll let @BerkeleyTrue merge this.

Thanks a lot for this pull request and great work @padulam!!

2017-06-21 22:30 UTC, merged