Improve description of work with dynamic data in D3 challenge
freeCodeCamp/freeCodeCamp pull request #15539
Opened 2017-06-26 18:27 UTC by dakshshah96

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #14668 

#### Description

Implemented the suggested changes to description of the "Work with Dynamic Data in D3" challenge.

2017-06-27 22:06 UTC, QuincyLarson commented
@HKuz do you have any feedback on this copy change?

2017-06-28 16:24 UTC, HKuz commented
I had left my comments over on the original issue. I'm on mobile, so hard to compare, but looks like this PR makes the recommended changes. 👍

> On Jun 27, 2017, at 6:07 PM, Quincy Larson <notifications@github.com> wrote:
> 
> @HKuz do you have any feedback on this copy change?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-08-21 03:19 UTC, dhcodes requested changes

2017-08-21 03:19 UTC, dhcodes commented on seed/challenges/04-data-visualization/data-visualization-with-d3.json
> +        "The last two challenges cover the basics of displaying data dynamically with D3 using the <code>data()</code> and <code>enter()</code> methods. These methods take a data set and, together wi
The word "the" is used twice in this line. One of them needs to be removed.

2017-08-21 03:19 UTC, dhcodes commented on seed/challenges/04-data-visualization/data-visualization-with-d3.json
> +        "Using the current example as context, the first <code>h2</code> element is bound to 12, the second <code>h2</code> element is bound to 31, the third <code>h2</code> element is bound to 22, a
The end of this line seems to be repetitive of the beginning.

2017-08-23 03:28 UTC, QuincyLarson commented
@dakshshah96 It looks like this is almost ready to merge. Can you take a look at the changes requested by @dhcodes?

2017-08-23 11:02 UTC, dakshshah96 commented
@QuincyLarson Done!

2017-09-06 01:32 UTC, merged

2017-09-06 01:33 UTC, BerkeleyTrue commented
@dakshshah96 Merged! Happy Coding!

2017-09-11 21:02 UTC, QuincyLarson commented
@dakshshah96 Thanks again for your contribution!