Add test case to 'Wherefore art thou'
freeCodeCamp/freeCodeCamp pull request #15549
Opened 2017-06-27 15:31 UTC by CodingPower472

Closes #14057

I have tested this change on a local copy of the site.

2017-06-27 22:10 UTC, erictleung commented on seed/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "assert.deepEqual(whatIsInAName([{ \"a\": 1, \"b\": 2, \"c\": 3 }], { \"a\": 1, \"b\": 9999, \"c\": 3 }), [])"
Can you add an appropriate message here for users to know what this test does? See the other tests in this challenge for examples.

2017-06-28 04:25 UTC, CodingPower472 commented on seed/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "assert.deepEqual(whatIsInAName([{ \"a\": 1, \"b\": 2, \"c\": 3 }], { \"a\": 1, \"b\": 9999, \"c\": 3 }), [])"
I will do that.

2017-06-28 04:40 UTC, CodingPower472 commented
Alright, I added the message.

2017-06-28 05:01 UTC, CodingPower472 commented
Sorry, there was an issue with the first commit.  I fixed the issue.

2017-07-01 01:57 UTC, CodingPower472 commented
What is the state of this pull request?

2017-07-01 01:58 UTC, CodingPower472 commented
@erictleung Done.

2017-07-01 16:47 UTC, erictleung requested changes
Looks mostly good. Just make the change I've noted in the code and it should be good to go :+1:

2017-07-01 16:47 UTC, erictleung commented on seed/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "assert.deepEqual(whatIsInAName([{ \"a\": 1, \"b\": 2, \"c\": 3 }], { \"a\": 1, \"b\": 9999, \"c\": 3 }), [], 'message: <code>whatIsInAName([{\"a\": 1, \"b\": 2, \"c\": 3}], {\"a\": 1, \"b\":
Your ending is missing a semi-colon, which is being parsed wrong. The ending should be

```diff
- ...</code>')"
+ ...</code>.');"
```

2017-07-02 13:04 UTC, CodingPower472 commented on seed/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "assert.deepEqual(whatIsInAName([{ \"a\": 1, \"b\": 2, \"c\": 3 }], { \"a\": 1, \"b\": 9999, \"c\": 3 }), [], 'message: <code>whatIsInAName([{\"a\": 1, \"b\": 2, \"c\": 3}], {\"a\": 1, \"b\":
When I look in my code, it seems this is already the case.

2017-07-02 13:18 UTC, CodingPower472 commented on seed/challenges/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
> +        "assert.deepEqual(whatIsInAName([{ \"a\": 1, \"b\": 2, \"c\": 3 }], { \"a\": 1, \"b\": 9999, \"c\": 3 }), [], 'message: <code>whatIsInAName([{\"a\": 1, \"b\": 2, \"c\": 3}], {\"a\": 1, \"b\":
Oops, never mind.

2017-07-02 13:23 UTC, CodingPower472 commented
Done.

2017-07-02 17:18 UTC, erictleung approved these changes
LGTM! :+1: Thanks for taking the time to contribute! :sparkles:

2017-07-02 17:19 UTC, merged