Replaced 'startsWith' with checking individual characters
freeCodeCamp/freeCodeCamp pull request #15561
Opened 2017-06-28 19:43 UTC by CodingPower472

Closes #15558

I tested this on a local copy of FreeCodeCamp.

2017-06-29 08:31 UTC, ahstro approved these changes

2017-06-29 13:51 UTC, CodingPower472 commented
When will this be merged?

2017-06-29 13:56 UTC, ahstro commented
I don't have the ability to merge, so I don't know, sorry. 🙂

2017-06-30 09:02 UTC, Bouncey requested changes

2017-06-30 09:02 UTC, Bouncey commented on common/app/routes/challenges/utils.js
> +      !(value.charAt(0) === '/' && value.charAt(1) === '/')) {
I think a Regular Expression checking for `//` at the beginning will be a more elegant solution. It also keeps the number of checks required to a minimum

2017-06-30 09:02 UTC, Bouncey commented
Thank you for providing a patch for this, please see my comment :+1:

2017-06-30 12:02 UTC, CodingPower472 commented
I'll change that. Thanks for the suggestion

2017-06-30 14:58 UTC, CodingPower472 commented
I switched to regex.

2017-07-01 16:04 UTC, Bouncey requested changes

2017-07-01 16:04 UTC, Bouncey commented on common/app/routes/challenges/utils.js
> +  if (typeof value === 'string' && !RegExp('^//').test(value)) {
So, to use the constructor method of creating a `RegExp` we need the `new` keyword. This ensures it is has direct inheritance from `RegExp.prototype` and we are not leaving ourselves open to bugs or attacks. Also, it is better to escape the `/`'s for the same reasons.

You can just create a literal RegExp and test with 
```js
/^\/\//.test(value)

// -------or-------

const inlineCommentRE = /^\/\//;
inlineCommentRE.test(value)
```
which will sort of the inheritance for us. Note that the `/`'s are still escaped. 

Thanks for all your effort in this PR, I think one last change and it should be ready to merge ✨

2017-07-02 13:45 UTC, CodingPower472 commented
@Bouncey Done.

2017-07-02 14:13 UTC, Bouncey approved these changes

2017-07-02 14:14 UTC, Bouncey commented
Great work @CodingPower472 thank you

## LGTM 👍

2017-07-02 14:15 UTC, merged