Adds glitch weather API to take home interview weather project.
freeCodeCamp/freeCodeCamp pull request #15608
Opened 2017-07-08 13:46 UTC by MiloATH

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #15598

#### Description

This will add the glitch weather API to the weather project challenge in the take home interview section. This means that users can get the weather without using an API key and using a HTTP Secure connection.

2017-07-08 17:52 UTC, raisedadead requested changes

2017-07-08 17:52 UTC, raisedadead commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/take-home-interview-projects.json
> +        "<strong>Note:</strong> Many internet browsers now require an HTTP Secure (<code>https://</code>) connection to obtain a user's locale via HTML5 Geolocation. For this reason, we recommend usi
```diff
- ...FreeCodeCamp
+ ...freeCodeCamp
```

Please update the styling.

2017-07-08 18:34 UTC, MiloATH commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/take-home-interview-projects.json
> +        "<strong>Note:</strong> Many internet browsers now require an HTTP Secure (<code>https://</code>) connection to obtain a user's locale via HTML5 Geolocation. For this reason, we recommend usi
Thanks. I just updated the styling.

2017-07-09 05:36 UTC, raisedadead approved these changes

2017-07-09 05:36 UTC, merged

2017-07-09 05:36 UTC, raisedadead commented
Thanks @MiloATH

2017-07-09 21:25 UTC, QuincyLarson commented
@MiloATH Wow - excellent work! Thank you for fixing this! Could you also make this change off backup/master and create a pull request there? We should get this into production ASAP. Once it's merged there, @BerkeleyTrue can deploy it.