fix test on es6 export default
freeCodeCamp/freeCodeCamp pull request #15627
Opened 2017-07-11 20:49 UTC by dhcodes

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #15507

#### Description

Updated the challenge seed, description, and test as the current challenge text is not possible per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#Using_the_default_export

2017-08-30 16:50 UTC, markusenglund requested changes

2017-08-30 16:50 UTC, yogaboll commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "assert(code.match(/export\\s+default\\s+\\s+function\\s+subtract\\(x,y\\)\\s+{return\\s+x\\s-\\s+y;}/ig))"
Looks like you mistakenly added an extra \\s+ between default and function.

2017-09-03 22:25 UTC, dhcodes commented
Updated. Thanks @yogaboll @systimotic

2017-09-04 08:16 UTC, systimotic approved these changes
Can't really test this, as the tests in this section don't work yet, but this is an improvement, so
## LGTM 👍 
Thanks @dhcodes

2017-09-04 08:16 UTC, merged