Move Fahrenheit Variable Below Comment Line
freeCodeCamp/freeCodeCamp pull request #15670
Opened 2017-07-20 15:45 UTC by prateekgoel

Challenge URL: https://www.freecodecamp.org/challenges/convert-celsius-to-fahrenheit

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [x] Closes currently open issue : Closes #15664 

#### Description

Changed the desciption as mentioned in the linked issue.

2017-07-28 14:18 UTC, dhcodes commented
@prateekgoel could you also add Eric's note from the issue thread? You can go back to your branch, add the note, save the file, and then run `git add .`, `git commit --amend`, save the file as-is, and then run `git push origin fix/move-fahrenheit-variable -f` to update this PR.

2017-07-28 14:20 UTC, dhcodes requested changes

2017-07-28 14:20 UTC, dhcodes commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json
> +        "You are given a variable <code>celsius</code> representing a temperature in Celsius. Use the variable <code>fahrenheit</code> already defined and assign it the Fahrenheit temperature equival
Add @erictleung's note after these lines.

2017-07-31 12:09 UTC, prateekgoel commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json
> +        "You are given a variable <code>celsius</code> representing a temperature in Celsius. Use the variable <code>fahrenheit</code> already defined and assign it the Fahrenheit temperature equival
Ok. I will do that.

2017-07-31 12:10 UTC, prateekgoel commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting.json
> +        "You are given a variable <code>celsius</code> representing a temperature in Celsius. Use the variable <code>fahrenheit</code> already defined and assign it the Fahrenheit temperature equival
Ok. I'll add that.

2017-08-01 13:58 UTC, prateekgoel commented
@dhcodes Add the note.

2017-08-01 16:21 UTC, dhcodes approved these changes

2017-08-01 16:22 UTC, merged

2017-08-01 18:30 UTC, dhcodes commented
@prateekgoel I forgot to mention this, but in the future, please squash your commits. Read about it here: https://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231

Alternatively, you could amend your past changes and then force push as I explained in the comment above. This would've kept these changes as one commit.

2017-08-01 19:40 UTC, prateekgoel commented
@dhcodes Sure. I'll take care in future.