fix(styles): Change modal title color
freeCodeCamp/freeCodeCamp pull request #15671
Opened 2017-07-20 19:14 UTC by dhcodes

Closes #15588

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #15588 

#### Description

added `color: #f9f9f9` to the `modal-title` class.

2017-07-20 19:16 UTC, dhcodes commented
Resulting effect:
![modal title](http://i.imgur.com/6Sa2CW7.jpg)

2017-07-24 22:46 UTC, BerkeleyTrue requested changes

2017-07-24 22:46 UTC, BerkeleyTrue commented on client/less/lib/bootstrap/modals.less
> +  color: #f9f9f9;
Use the bootstrap variables instead of hardcoding hex values. I'm sure we have a variable already for this color.

2017-07-25 14:08 UTC, dhcodes commented
@BerkeleyTrue corrected!

2017-07-31 20:49 UTC, BerkeleyTrue approved these changes

2017-07-31 20:50 UTC, merged