docs(contributing): Add correct commands for installing and running mongoDB
freeCodeCamp/freeCodeCamp pull request #15686
Opened 2017-07-25 06:36 UTC by yogaboll

Closes #15648

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

CONTRUBUTING.md in its current state might confuse windows-users since it contains commands for MongoDB that simply do not work. This change aims to fix this by adding specific instructions for windows-users.

2017-07-26 18:04 UTC, raisedadead requested changes

2017-07-26 18:04 UTC, raisedadead commented on CONTRIBUTING.md
> +
remove additional newline.

2017-07-27 06:43 UTC, yogaboll commented
Done!

2017-07-28 13:43 UTC, merged

2017-07-28 13:43 UTC, raisedadead commented
Thanks @yogaboll !