Correct misalignment between challenge names and hour estimates
freeCodeCamp/freeCodeCamp pull request #15734
Opened 2017-08-04 07:49 UTC by anawebdev

#### Pre-Submission Checklist

- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #15706

#### Description

The misalignment happens when the left panel in challenges view gets too small and the text wraps around the hour estimates, which are floated right. I added two media queries to fix this.

2017-08-04 20:28 UTC, dhcodes requested changes

2017-08-04 20:28 UTC, dhcodes commented on common/app/Map/map.less
> +  @media (min-width: 721px) {
Could these `@media` lines be added to the selector at line 72?

2017-08-04 20:36 UTC, anawebdev commented on common/app/Map/map.less
> +  @media (min-width: 721px) {
Sure :)

2017-08-05 08:45 UTC, anawebdev commented
I  made the requested changes.

2017-08-05 17:40 UTC, QuincyLarson commented
@anawebdev Awesome. Thanks for this elegant fix!

@dhcodes this looks good to me. Thanks for reviewing this. Please merge once you're ready.

2017-08-06 02:16 UTC, dhcodes approved these changes

2017-08-06 02:17 UTC, dhcodes commented
Agree with Quincy. **LGTM**. Thanks @anawebdev for making this change. 👍 💯 🏎 🌮

2017-08-06 02:17 UTC, merged