Ask for help button feature
freeCodeCamp/freeCodeCamp pull request #15737
Opened 2017-08-05 18:58 UTC by prateekgoel

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #15669

#### Description

Implemented the 'Ask for help' button feature for production.

2017-08-05 19:39 UTC, piotrek1543 commented on server/views/partials/challenge-modals.jade
> +                a.btn.btn-lg.btn-primary.btn-block#ask-for-help-button(name='_csrf', value=_csrf) Create a help post on the forum
I think that `Create a help post` is enough for link text and `on the forum` might be omitted as it is already explained in description. For me it seems like doubled content.

2017-08-06 14:03 UTC, prateekgoel commented on server/views/partials/challenge-modals.jade
> +                a.btn.btn-lg.btn-primary.btn-block#ask-for-help-button(name='_csrf', value=_csrf) Create a help post on the forum
@piotrek1543 I kept it as descibed in the issue by @QuincyLarson .
However, if you want I will make it short.

2017-08-06 15:49 UTC, QuincyLarson commented on server/views/partials/challenge-modals.jade
> +                a.btn.btn-lg.btn-primary.btn-block#ask-for-help-button(name='_csrf', value=_csrf) Create a help post on the forum
@piotrek1543 I think "ask for help on the forum" will be more clear to newcomers.

2017-08-06 15:51 UTC, QuincyLarson commented
@prateekgoel This works great! Could you also add a **link to the challenge** to the end of post body? This will save people who are trying to help campers a lot of time.

2017-08-06 17:19 UTC, prateekgoel commented
@QuincyLarson Sure. I will add the link too.

2017-08-06 18:31 UTC, prateekgoel commented
@QuincyLarson Added the link :)

2017-08-07 20:38 UTC, ghost approved these changes

2017-08-08 19:45 UTC, QuincyLarson commented
@prateekgoel I'm in the process of QA'ing this. Thanks for your patience.

2017-08-08 20:22 UTC, prateekgoel commented
@QuincyLarson Ok thanks. 😃

2017-08-09 15:45 UTC, QuincyLarson commented
@prateekgoel Awesome! This looks good to me. Waiting for @BerkeleyTrue to approve it as well, since this will go straight into production.

2017-08-09 16:50 UTC, prateekgoel commented
@QuincyLarson Thanks. I am happy I could help.

2017-08-09 16:53 UTC, BerkeleyTrue requested changes

2017-08-09 16:53 UTC, BerkeleyTrue commented on client/commonFramework/ask-for-help.js
> +        'http://forum.freecodecamp.org/new-topic?title='
This should either be https or omitted

2017-08-09 19:50 UTC, prateekgoel commented on client/commonFramework/ask-for-help.js
> +        'http://forum.freecodecamp.org/new-topic?title='
@BerkeleyTrue Yes I missed that! I will change it to https.

2017-08-11 04:31 UTC, QuincyLarson commented
@BerkeleyTrue It looks like @prateekgoel made the changes. Can you take look, then merge and deploy?

2017-08-11 19:50 UTC, BerkeleyTrue approved these changes

2017-08-11 19:51 UTC, merged

2017-08-12 18:18 UTC, prateekgoel commented
@QuincyLarson @BerkeleyTrue I am not able to see 'Ask for help' button on freeCodeCamp site. What might be the reason?

2017-08-12 19:34 UTC, QuincyLarson commented
@prateekgoel We're waiting for @BerkeleyTrue to deploy it.

2017-08-13 05:02 UTC, prateekgoel commented
Ok Thanks @QuincyLarson . I hope it gets deployed soon.

2017-08-13 19:03 UTC, BerkeleyTrue commented
This is now live. Thanks for your patience. Happy Coding.

2018-02-12 16:22 UTC, Zou1738 commented
I need theses messages to STOP

On Sun, Aug 13, 2017 at 2:05 PM Berkeley Martinez <notifications@github.com>
wrote:

> This is now live. Thanks for your patience. Happy Coding.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/15737#issuecomment-322060632>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AZfyQTqBnGzkn96Xgq1kZlhNvsAwcz-gks5sX0kDgaJpZM4OuiYN>
> .
>