fix(challenges): Provide accessible test description and status
freeCodeCamp/freeCodeCamp pull request #15758
Opened 2017-08-12 21:36 UTC by xnt

Closes #13013

fix(challenges): Provide accessible test description and status

#### Pre-Submission Checklist
- [X] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [ ] Closes currently open issue: Closes #13013

#### Description
* Use aria-hide on elements that aren't independently relevant for visually impaired or challenged users
* Merge test status and text on a single string
* Add the string as the aria text / label of the row element
* Force the row element to be a tab stop

Changes have been tested with Mac's VoiceOver on Chrome and Safari. Changes _should_ work on NVDA and JAWS (don't have a test environment at the moment). npm test / lint runs fine.
<img width="600" alt="screen shot 2017-08-12 at 2 32 46 pm" src="https://user-images.githubusercontent.com/309783/29244364-4a26f7b4-7f6b-11e7-899b-ba80801076c5.png">
<img width="535" alt="screen shot 2017-08-12 at 2 33 24 pm" src="https://user-images.githubusercontent.com/309783/29244365-4a27c2b6-7f6b-11e7-8b47-abb6b34bf7b2.png">

2017-08-13 21:10 UTC, QuincyLarson commented
@HKuz since you're our resident accessibility expert, would you be interested in QA'ing this?

2017-08-14 23:27 UTC, HKuz commented
I'm sorry, @QuincyLarson - I don't know anything about aria elements, I wouldn't know how to QA this.

2017-08-16 18:21 UTC, BerkeleyTrue requested changes

2017-08-16 18:21 UTC, BerkeleyTrue commented on common/app/routes/challenges/Test-Suite.jsx
> +  getAccessibleText(err, pass, text) {
Why does this function need to be a method attached to the class? It should just be a top level function in this file

2017-08-16 21:21 UTC, xnt commented on common/app/routes/challenges/Test-Suite.jsx
> +  getAccessibleText(err, pass, text) {
@BerkeleyTrue I'm sorry. I'm not really that experienced with JSX, so I didn't think there'd be any problem with it. I've updated the pull request per your comments -making the function top-level within the file, popping it out of the class, and verifying that npm test runs nicely and the results are still the same.

Thank you!

2017-08-19 18:00 UTC, BerkeleyTrue requested changes

2017-08-19 18:00 UTC, BerkeleyTrue commented on common/app/routes/challenges/Test-Suite.jsx
> +    accessibleText += 'Waiting';
This logic can be simplified. If Waiting is the default then this last conditional can be removed and the `accessibleText` can start out as `Waiting`.

Then the two conditionals above just overwrite the string.

2017-08-19 18:00 UTC, BerkeleyTrue commented on common/app/routes/challenges/Test-Suite.jsx
> +  return accessibleText;
These three lines can be condensed into one simple string concatenation.
`return accessibleText + '-' + text;`

2017-08-19 19:49 UTC, xnt commented
@BerkeleyTrue - I've addressed your latest comments. Please take a look when you have a chance. Thank you!

2017-08-23 02:30 UTC, BerkeleyTrue commented
@xnt It's general good practice to always test that your code changes have the desired affect. Have you done so? 

![fix_challenges___provide_accessible_test_description_and_status_by_xnt_ _pull_request__15758_ _freecodecamp_freecodecamp_](https://user-images.githubusercontent.com/6775919/29595878-fc1e6302-876e-11e7-86a1-5c15c23b8ec1.png)

This shows that the accessibility text will always have `Waiting` appended to the text. Is this the desired outcome?

Also `Error ` has a space after the word while waiting and pass do not. Is this inconsistency intended?

There is a saying in coding that goes `red light - green light`. Meaning, first validate that the issue exists (red light!), make your changes, and then validate that your code changes actually solve the issue (green light!) either by writing tests or actually running the code. I don't expect most campers to write test for new code but it should be the minimum to always run the code in the browser and verify that the outcome of your changes is what you expect.

It is also best to ask for clarification if requested changes do not make sense. Communication through the internet is always subpar and often leads to misunderstandings.

2017-08-23 02:57 UTC, xnt commented
I find that comment rather condescending and makes me feel a bit uncomfortable, @berkeleyTrue . I'll assume that's what you mean by supbar, prone to misunderstandings. 

That's definitely a bug in my code and I'll fix it later today. That is not the intended effect.

2017-08-23 05:19 UTC, xnt commented
Fixed, @BerkeleyTrue . Apologies for the careless mistake and not performing appropriate testing.

<img width="647" alt="screen shot 2017-08-22 at 10 07 55 pm" src="https://user-images.githubusercontent.com/309783/29599965-db05b8c8-8787-11e7-945f-99532362f038.png">

2017-08-31 15:20 UTC, QuincyLarson commented
@BerkeleyTrue it seems @xnt has made the requested changes (I'm not sure if he needs to do anything to the review to send you a notification through GitHub). This is ready to QA again when you get time.

2017-09-04 21:21 UTC, BerkeleyTrue approved these changes

2017-09-04 21:22 UTC, merged

2017-09-11 22:20 UTC, QuincyLarson commented
@xnt Thanks again for your contribution!

2017-09-12 00:54 UTC, xnt commented
@QuincyLarson my pleasure, I'll keep an eye to more a11y issues when I have a bit of downtime.