feat(challenges): Added more assertion for euler problem twenty two
freeCodeCamp/freeCodeCamp pull request #15788
Opened 2017-08-22 13:12 UTC by alvinkl

more assertion and updated question

#### Pre-Submission Checklist

- [ x] Your pull request targets the `staging` branch of freeCodeCamp.
- [ x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ]x Tested changes locally.
- [ ] Closes currently open issue (replace XXXX with an issue no): Closes #XXXX

#### Description

Updated Project Euler seeds for problem 22 
Here's the solution, I can't add it to the json file, due to it's always failing on the test.
```javascripts
function sumNames(n) {
    const names = require('./p022_names');
    names.sort();

    var sum = 0;

    for (let i = 0; i < n; i++) {
        let atoi = names[i]
            .split('')
            .map((_, j) => names[i].charCodeAt(j) - 64)
            .reduce((c, n) => c + n, 0);

        sum += (i + 1) * atoi;
    }

    return sum;
}
```

2017-08-23 02:16 UTC, BerkeleyTrue requested changes

2017-08-23 02:16 UTC, BerkeleyTrue commented on seed/challenges/08-coding-interview-questions-and-take-home-assignments/project-euler-problems.json
> +        "assert.strictEqual(sumNames(1000), 31279822, 'message: <code>sumNames(1000)</code> should return 31279822.');",
use plain asserts

2017-08-24 16:58 UTC, BerkeleyTrue approved these changes

2017-08-24 16:58 UTC, BerkeleyTrue commented
CODE LGTM

2017-09-02 03:27 UTC, beaucarnes commented
This problem does not work with the freeCodeCamp platform since the description says to use an external file. This is impossible with the platform. We are going to remove this problem completely in another pull request.

2017-09-02 03:27 UTC, closed without merging