fix(challenges): Improve local scope challenge tests
freeCodeCamp/freeCodeCamp pull request #15800
Opened 2017-08-24 23:19 UTC by systimotic

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.com/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #13409

#### Description
This PR updates the challenge as discussed in the issue. See regexr.com/3gk6t for the regex with some test cases.

2017-08-24 23:24 UTC, systimotic commented
Regarding that first camperbot message: we should probably get that updated, it conflicts with the commitzen guidelines

2017-09-12 03:54 UTC, QuincyLarson commented
@systimotic Thanks for your patience. I just QA'd this. 

This does indeed work, though I was a bit confused as to which console.log line to update. I also am not a fan of the "follow the directions in the code" part. I feel like we need to figure out a more elegant way of conveying this.

2017-09-12 03:55 UTC, QuincyLarson requested changes

2017-09-12 03:55 UTC, QuincyLarson commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
> +        "assert(/^[^\\/\\n]*var[^\\S\\n]+myVar[^\\S\\n]*=[^\\S\\n]*100[^\\S\\n]*;?.*$/m.test(code), 'message: Add a local <code>myVar</code> variable with a value of <code>100</code>');"
This does indeed work, though I was a bit confused as to which console.log line to update. I also am not a fan of the "follow the directions in the code" part. I feel like we need to figure out a more elegant way of conveying this.

2017-10-20 15:00 UTC, raisedadead commented
@systimotic ping!

2017-12-13 06:31 UTC, raisedadead commented
Closing decayed, please re-open if you see this and have additional clarification as requested.

2017-12-13 06:31 UTC, closed without merging