Add confirm password validation to reset view
freeCodeCamp/freeCodeCamp pull request #15916
Opened 2017-09-25 17:52 UTC by shovanch

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [X] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [X] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [X] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Closes currently open issue (replace XXXX with an issue no): Closes #15909 

#### Description

Added confirm password validation to reset view. Shows error message if passwords don't match. Blocks form submission until passwords are validated

2017-09-26 06:09 UTC, raisedadead requested changes

2017-09-26 06:09 UTC, raisedadead commented on server/views/account/reset.jade
> +        script.
Move this line and everything below it (the whole script block), to its correct indentation. Your script block is going to be within the form elements without that. Most browsers will not execute such code.

You should have it rather at the same level as line 4 in this snippet.

This is how the jade(pug) templating engine renders elements, and hence indentation is very crucial.

2017-09-26 06:12 UTC, raisedadead commented
Are you able to test this locally?

2017-09-26 06:21 UTC, shovanch commented
Yes, I have tested them locally, Seems to work fine.

2017-09-26 06:45 UTC, shovanch commented
I have amended the requested changes

2017-09-26 07:26 UTC, raisedadead commented
> Yes, I have tested them locally.

Do you mind providing some screenshots, I would be able to QA it soon, but a quick look at how it looks would help in doing it faster.

2017-09-26 07:29 UTC, shovanch commented
Sure. Should I rather make a GIF showing the process?

2017-09-26 08:26 UTC, shovanch commented
I have made a GIF showing the whole process - [GIF link](https://i.imgur.com/LWY8DFB.gif)

2017-09-27 06:05 UTC, raisedadead approved these changes

2017-09-27 06:06 UTC, merged

2017-09-27 06:06 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @shovanch , and congratulations on your first contribution to freeCodeCamp.

/cc @BerkeleyTrue