fix(setup): Include MailHog setup instructions
freeCodeCamp/freeCodeCamp pull request #15930
Opened 2017-10-02 19:43 UTC by Spidy88

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:
- [x] Tested changes locally.
- [x] Closes currently open issue: Closes #15838

#### Description
With the changes to passwordless account creation, contributors are
unable to create an account locally. MailHog spins up a local SMPT
server that can catch all outgoing emails, allowing contributors to
successfully create accounts and see any other emails generated locally.

2017-10-03 15:41 UTC, raisedadead commented
Hi @Spidy88 thanks a lot for the PR. 

Can you possibly update the `docker-compose` file? I believe this is a would be a good addition.

2017-10-03 16:36 UTC, raisedadead requested changes

2017-10-03 16:36 UTC, raisedadead commented on CONTRIBUTING.md
> +
Please add additional info about opening up the localhost web view of the service available at 8025 port, or something on similar lines.

2017-10-04 04:40 UTC, Spidy88 commented
@raisedadead Ya I can add the mailhog container to the docker-compose. I was avoiding it because the Docker setup seemed broken when I tried it and I just wanted a quick fix for contributors. Let me see if I can fix the Docker setup.

2017-10-04 04:59 UTC, raisedadead commented
Ah.. I see in that case lets make a fresh PR for the docker setup when we are ready, for now, could you just add the instruction about web view and we should be good to merge.

Thanks a lot.

2017-10-04 05:52 UTC, raisedadead approved these changes

2017-10-04 05:56 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @Spidy88 for this awesome contribution!

2017-10-04 05:56 UTC, merged