feat(enhancement): added comminity dropdown to primary navigation. ad…
freeCodeCamp/freeCodeCamp pull request #15937
Opened 2017-10-04 16:24 UTC by adityaparab

…ded link to fcc guide

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Closes currently open issue (replace XXXX with an issue no): Closes #15792

#### Description
- Minor CSS customization to override bootstrap breakpoints.
- Restructured navigation to show different kinds of menus on different screen sizes.

2017-10-06 04:20 UTC, QuincyLarson requested changes
This is almost ready. Please make these quick changes. Then we can merge.

2017-10-06 04:20 UTC, QuincyLarson commented on server/views/partials/navbar.jade
> +                a(href="https://medium.freecodecamp.com" target="_blank") Medium
This should be https://medium.freecodecamp.org (a .org domain)

2017-10-06 04:20 UTC, QuincyLarson commented on server/views/partials/navbar.jade
> +                a(href="https://forum.freecodecamp.com" target="_blank") Forum
This should be https://forum.freecodecamp.org (a .org domain)

2017-10-06 04:20 UTC, QuincyLarson commented on server/views/partials/navbar.jade
> +                a(href="https://forum.freecodecamp.com/t/free-code-camp-city-based-local-groups/19574" target="_blank") In your city
Instead of this URL we should send them to: https://study-group-directory.freecodecamp.org/

2017-10-08 03:08 UTC, QuincyLarson requested changes

2017-10-08 03:08 UTC, QuincyLarson commented on server/views/partials/navbar.jade
> +                a(href="https://forum.freecodecamp.com/t/free-code-camp-city-based-local-groups/19574" target="_blank") In your city
This is still not fixed. Please use this URL instead of that link to the forum: https://study-group-directory.freecodecamp.org/

2017-10-08 03:21 UTC, QuincyLarson commented
@adityaparab One more change and this will be ready to merge. Please take a closer look at my review.

2017-10-08 06:18 UTC, adityaparab commented
@QuincyLarson : Does this look good now?

2017-10-08 13:48 UTC, QuincyLarson approved these changes

2017-10-08 13:48 UTC, merged

2017-10-08 13:49 UTC, QuincyLarson commented
@adityaparab Awesome! thanks! I've merged this and @BerkeleyTrue will deploy it next chance he gets.

2017-10-09 03:54 UTC, BerkeleyTrue commented
I've had to revert this PR as it broke the map button.

2017-10-10 07:12 UTC, adityaparab commented
@BerkeleyTrue Can you let me know what exactly was broken? I don't have access to codebase right now. Will check that in morning.

2017-10-10 07:40 UTC, BerkeleyTrue commented
@adityaparab The Map button in the nav bar would not open the map drawer

2017-10-12 05:17 UTC, adityaparab commented
@BerkeleyTrue Sure will push another commit.

2017-10-12 21:16 UTC, QuincyLarson commented
@adityaparab OK - thanks! As soon as you've fixed this, we can fast-track this to production.