fix(challenges): Clarified instructions on es6 let challenge
freeCodeCamp/freeCodeCamp pull request #15983
Opened 2017-10-18 21:01 UTC by dhcodes

Closes #12818

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [X] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #12818 

#### Description

Updated examples and instructions.

2017-10-19 18:58 UTC, dhcodes commented
Hold off for a bit, one of the tests isn't working. Will update.

2017-12-16 17:56 UTC, Bouncey requested changes

2017-12-16 17:56 UTC, Bouncey commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "<strong>Note</strong><br>Remember that since let prevent variables from being overridden, you will need to remove one of the declarations entirely."
Prevents

2017-12-16 17:56 UTC, Bouncey commented on seed/challenges/02-javascript-algorithms-and-data-structures/es6.json
> +        "A new keyword called <code>let</code> was introduced in ES6 to solve this potential issue with the <code>var</code> keyword.",
Switch line 35 & 36?

2017-12-21 16:58 UTC, raisedadead commented
Ping @dhcodes !

2018-01-01 17:58 UTC, dhcodes commented
I'm unfamiliar with the merge commit additions but made the updates @raisedadead 👋

2018-01-03 15:42 UTC, raisedadead commented
@Bouncey if you are happy with the changes, lets merge.

2018-01-04 10:58 UTC, Bouncey approved these changes

2018-01-04 10:58 UTC, merged