Update CONTRIBUTING.md
freeCodeCamp/freeCodeCamp pull request #16013
Opened 2017-10-23 15:37 UTC by magicansk

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

2017-10-23 18:27 UTC, raisedadead requested changes
Please check comments inline. Also since this was made of GitHub interface, you would have to make a fresh pull request squashing your commits into a named branch as mentioned in the Contributing guide.

2017-10-23 18:27 UTC, raisedadead commented on CONTRIBUTING.md
> +  If your aren't on `staging`, resolve outstanding files / commits and checkout the `staging` branch
Can you make the indentation to work with the step that this belongs?

2017-10-23 18:27 UTC, raisedadead commented on CONTRIBUTING.md
> +   This will pull down all of the changes to the official staging branch, without making an additional commit in your local repo.
Can you make the indentation to work with the step that this belongs?

2017-10-23 18:27 UTC, raisedadead commented on CONTRIBUTING.md
>    > This will overwrite the staging branch of your fork.
Looks like this was missed, and also can you make the indentation to work with the step that this belongs?

2017-10-23 18:28 UTC, raisedadead commented
@magicansk thanks a lot for contributing to freeCodeCamp, please make a fresh request from a local copy of your fork addressing the comments above.

Happy fixing!

2017-10-23 18:28 UTC, closed without merging

2017-10-25 05:53 UTC, magicansk commented
Already PR and fixed it.