feat(seed): Added more assertions for project euler
freeCodeCamp/freeCodeCamp pull request #16079
Opened 2017-11-06 01:31 UTC by alvinkl

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

```javascript
function codedTriangleNumbers(n) {
	const words = [
		'A',
		'ABILITY',
		'ABLE',
		'ABOUT',
		'ABOVE',
		'ABSENCE',
		'ABSOLUTELY',
		'ACADEMIC',
		'ACCEPT',
		'ACCESS',
		'ACCIDENT',
		'ACCOMPANY',
		'ACCORDING',
		'ACCOUNT',
		'ACHIEVE',
		'ACHIEVEMENT',
		'ACID',
		'ACQUIRE',
		'ACROSS',
		'ACT',
		'ACTION',
		'ACTIVE',
		'ACTIVITY',
		'ACTUAL',
		'ACTUALLY',
		'ADD',
		'ADDITION',
		'ADDITIONAL',
		'ADDRESS',
		'ADMINISTRATION',
		'ADMIT',
		'ADOPT',
		'ADULT',
		'ADVANCE',
		'ADVANTAGE',
		'ADVICE',
		'ADVISE',
		'AFFAIR',
		'AFFECT',
		'AFFORD',
		'AFRAID',
		'AFTER',
		'AFTERNOON',
		'AFTERWARDS',
		'AGAIN',
		'AGAINST',
		'AGE',
		'AGENCY',
		'AGENT',
		'AGO',
		'AGREE',
		'AGREEMENT',
		'AHEAD',
		'AID',
		'AIM',
		'AIR',
		'AIRCRAFT',
		'ALL',
		'ALLOW',
		'ALMOST',
		'ALONE',
		'ALONG',
		'ALREADY',
		'ALRIGHT',
		'ALSO',
		'ALTERNATIVE',
		'ALTHOUGH',
		'ALWAYS',
		'AMONG',
		'AMONGST',
		'AMOUNT',
		'AN',
		'ANALYSIS',
		'ANCIENT',
		'AND',
		'ANIMAL',
		'ANNOUNCE',
		'ANNUAL',
		'ANOTHER',
		'ANSWER',
		'ANY',
		'ANYBODY',
		'ANYONE',
		'ANYTHING',
		'ANYWAY',
		'APART',
		'APPARENT',
		'APPARENTLY',
		'APPEAL',
		'APPEAR',
		'APPEARANCE',
		'APPLICATION',
		'APPLY',
		'APPOINT',
		'APPOINTMENT',
		'APPROACH',
		'APPROPRIATE',
		'APPROVE',
		'AREA',
		'ARGUE',
		'ARGUMENT',
		'ARISE',
		'ARM',
		'ARMY',
		'AROUND',
		'ARRANGE',
		'ARRANGEMENT',
		'ARRIVE',
		'ART',
		'ARTICLE',
		'ARTIST',
		'AS',
		'ASK',
		'ASPECT',
		'ASSEMBLY',
		'ASSESS',
		'ASSESSMENT',
		'ASSET',
		'ASSOCIATE',
		'ASSOCIATION',
		'ASSUME',
		'ASSUMPTION',
		'AT',
		'ATMOSPHERE',
		'ATTACH',
		'ATTACK',
		'ATTEMPT',
		'ATTEND',
		'ATTENTION',
		'ATTITUDE',
		'ATTRACT',
		'ATTRACTIVE',
		'AUDIENCE',
		'AUTHOR',
		'AUTHORITY',
		'AVAILABLE',
		'AVERAGE',
		'AVOID',
		'AWARD',
		'AWARE',
		'AWAY',
		'AYE',
		'BABY',
		'BACK',
		'BACKGROUND',
		'BAD',
		'BAG',
		'BALANCE',
		'BALL',
		'BAND',
		'BANK',
		'BAR',
		'BASE',
		'BASIC',
		'BASIS',
		'BATTLE',
		'BE',
		'BEAR',
		'BEAT',
		'BEAUTIFUL',
		'BECAUSE',
		'BECOME',
		'BED',
		'BEDROOM',
		'BEFORE',
		'BEGIN',
		'BEGINNING',
		'BEHAVIOUR',
		'BEHIND',
		'BELIEF',
		'BELIEVE',
		'BELONG',
		'BELOW',
		'BENEATH',
		'BENEFIT',
		'BESIDE',
		'BEST',
		'BETTER',
		'BETWEEN',
		'BEYOND',
		'BIG',
		'BILL',
		'BIND',
		'BIRD',
		'BIRTH',
		'BIT',
		'BLACK',
		'BLOCK',
		'BLOOD',
		'BLOODY',
		'BLOW',
		'BLUE',
		'BOARD',
		'BOAT',
		'BODY',
		'BONE',
		'BOOK',
		'BORDER',
		'BOTH',
		'BOTTLE',
		'BOTTOM',
		'BOX',
		'BOY',
		'BRAIN',
		'BRANCH',
		'BREAK',
		'BREATH',
		'BRIDGE',
		'BRIEF',
		'BRIGHT',
		'BRING',
		'BROAD',
		'BROTHER',
		'BUDGET',
		'BUILD',
		'BUILDING',
		'BURN',
		'BUS',
		'BUSINESS',
		'BUSY',
		'BUT',
		'BUY',
		'BY',
		'CABINET',
		'CALL',
		'CAMPAIGN',
		'CAN',
		'CANDIDATE',
		'CAPABLE',
		'CAPACITY',
		'CAPITAL',
		'CAR',
		'CARD',
		'CARE',
		'CAREER',
		'CAREFUL',
		'CAREFULLY',
		'CARRY',
		'CASE',
		'CASH',
		'CAT',
		'CATCH',
		'CATEGORY',
		'CAUSE',
		'CELL',
		'CENTRAL',
		'CENTRE',
		'CENTURY',
		'CERTAIN',
		'CERTAINLY',
		'CHAIN',
		'CHAIR',
		'CHAIRMAN',
		'CHALLENGE',
		'CHANCE',
		'CHANGE',
		'CHANNEL',
		'CHAPTER',
		'CHARACTER',
		'CHARACTERISTIC',
		'CHARGE',
		'CHEAP',
		'CHECK',
		'CHEMICAL',
		'CHIEF',
		'CHILD',
		'CHOICE',
		'CHOOSE',
		'CHURCH',
		'CIRCLE',
		'CIRCUMSTANCE',
		'CITIZEN',
		'CITY',
		'CIVIL',
		'CLAIM',
		'CLASS',
		'CLEAN',
		'CLEAR',
		'CLEARLY',
		'CLIENT',
		'CLIMB',
		'CLOSE',
		'CLOSELY',
		'CLOTHES',
		'CLUB',
		'COAL',
		'CODE',
		'COFFEE',
		'COLD',
		'COLLEAGUE',
		'COLLECT',
		'COLLECTION',
		'COLLEGE',
		'COLOUR',
		'COMBINATION',
		'COMBINE',
		'COME',
		'COMMENT',
		'COMMERCIAL',
		'COMMISSION',
		'COMMIT',
		'COMMITMENT',
		'COMMITTEE',
		'COMMON',
		'COMMUNICATION',
		'COMMUNITY',
		'COMPANY',
		'COMPARE',
		'COMPARISON',
		'COMPETITION',
		'COMPLETE',
		'COMPLETELY',
		'COMPLEX',
		'COMPONENT',
		'COMPUTER',
		'CONCENTRATE',
		'CONCENTRATION',
		'CONCEPT',
		'CONCERN',
		'CONCERNED',
		'CONCLUDE',
		'CONCLUSION',
		'CONDITION',
		'CONDUCT',
		'CONFERENCE',
		'CONFIDENCE',
		'CONFIRM',
		'CONFLICT',
		'CONGRESS',
		'CONNECT',
		'CONNECTION',
		'CONSEQUENCE',
		'CONSERVATIVE',
		'CONSIDER',
		'CONSIDERABLE',
		'CONSIDERATION',
		'CONSIST',
		'CONSTANT',
		'CONSTRUCTION',
		'CONSUMER',
		'CONTACT',
		'CONTAIN',
		'CONTENT',
		'CONTEXT',
		'CONTINUE',
		'CONTRACT',
		'CONTRAST',
		'CONTRIBUTE',
		'CONTRIBUTION',
		'CONTROL',
		'CONVENTION',
		'CONVERSATION',
		'COPY',
		'CORNER',
		'CORPORATE',
		'CORRECT',
		'COS',
		'COST',
		'COULD',
		'COUNCIL',
		'COUNT',
		'COUNTRY',
		'COUNTY',
		'COUPLE',
		'COURSE',
		'COURT',
		'COVER',
		'CREATE',
		'CREATION',
		'CREDIT',
		'CRIME',
		'CRIMINAL',
		'CRISIS',
		'CRITERION',
		'CRITICAL',
		'CRITICISM',
		'CROSS',
		'CROWD',
		'CRY',
		'CULTURAL',
		'CULTURE',
		'CUP',
		'CURRENT',
		'CURRENTLY',
		'CURRICULUM',
		'CUSTOMER',
		'CUT',
		'DAMAGE',
		'DANGER',
		'DANGEROUS',
		'DARK',
		'DATA',
		'DATE',
		'DAUGHTER',
		'DAY',
		'DEAD',
		'DEAL',
		'DEATH',
		'DEBATE',
		'DEBT',
		'DECADE',
		'DECIDE',
		'DECISION',
		'DECLARE',
		'DEEP',
		'DEFENCE',
		'DEFENDANT',
		'DEFINE',
		'DEFINITION',
		'DEGREE',
		'DELIVER',
		'DEMAND',
		'DEMOCRATIC',
		'DEMONSTRATE',
		'DENY',
		'DEPARTMENT',
		'DEPEND',
		'DEPUTY',
		'DERIVE',
		'DESCRIBE',
		'DESCRIPTION',
		'DESIGN',
		'DESIRE',
		'DESK',
		'DESPITE',
		'DESTROY',
		'DETAIL',
		'DETAILED',
		'DETERMINE',
		'DEVELOP',
		'DEVELOPMENT',
		'DEVICE',
		'DIE',
		'DIFFERENCE',
		'DIFFERENT',
		'DIFFICULT',
		'DIFFICULTY',
		'DINNER',
		'DIRECT',
		'DIRECTION',
		'DIRECTLY',
		'DIRECTOR',
		'DISAPPEAR',
		'DISCIPLINE',
		'DISCOVER',
		'DISCUSS',
		'DISCUSSION',
		'DISEASE',
		'DISPLAY',
		'DISTANCE',
		'DISTINCTION',
		'DISTRIBUTION',
		'DISTRICT',
		'DIVIDE',
		'DIVISION',
		'DO',
		'DOCTOR',
		'DOCUMENT',
		'DOG',
		'DOMESTIC',
		'DOOR',
		'DOUBLE',
		'DOUBT',
		'DOWN',
		'DRAW',
		'DRAWING',
		'DREAM',
		'DRESS',
		'DRINK',
		'DRIVE',
		'DRIVER',
		'DROP',
		'DRUG',
		'DRY',
		'DUE',
		'DURING',
		'DUTY',
		'EACH',
		'EAR',
		'EARLY',
		'EARN',
		'EARTH',
		'EASILY',
		'EAST',
		'EASY',
		'EAT',
		'ECONOMIC',
		'ECONOMY',
		'EDGE',
		'EDITOR',
		'EDUCATION',
		'EDUCATIONAL',
		'EFFECT',
		'EFFECTIVE',
		'EFFECTIVELY',
		'EFFORT',
		'EGG',
		'EITHER',
		'ELDERLY',
		'ELECTION',
		'ELEMENT',
		'ELSE',
		'ELSEWHERE',
		'EMERGE',
		'EMPHASIS',
		'EMPLOY',
		'EMPLOYEE',
		'EMPLOYER',
		'EMPLOYMENT',
		'EMPTY',
		'ENABLE',
		'ENCOURAGE',
		'END',
		'ENEMY',
		'ENERGY',
		'ENGINE',
		'ENGINEERING',
		'ENJOY',
		'ENOUGH',
		'ENSURE',
		'ENTER',
		'ENTERPRISE',
		'ENTIRE',
		'ENTIRELY',
		'ENTITLE',
		'ENTRY',
		'ENVIRONMENT',
		'ENVIRONMENTAL',
		'EQUAL',
		'EQUALLY',
		'EQUIPMENT',
		'ERROR',
		'ESCAPE',
		'ESPECIALLY',
		'ESSENTIAL',
		'ESTABLISH',
		'ESTABLISHMENT',
		'ESTATE',
		'ESTIMATE',
		'EVEN',
		'EVENING',
		'EVENT',
		'EVENTUALLY',
		'EVER',
		'EVERY',
		'EVERYBODY',
		'EVERYONE',
		'EVERYTHING',
		'EVIDENCE',
		'EXACTLY',
		'EXAMINATION',
		'EXAMINE',
		'EXAMPLE',
		'EXCELLENT',
		'EXCEPT',
		'EXCHANGE',
		'EXECUTIVE',
		'EXERCISE',
	 [...]

2017-11-13 17:24 UTC, thmsdnnr commented
Hi @alvinkl — I'm doing some QA on this PR now. Here are a few questions I had:

0. When I try to do the trivial solution — just returning the expected value for any of the four test cases with no code (e.g., if (n===1400) { return 129; }, none of the results pass.

<img width="470" alt="screen shot 2017-11-13 at 11 16 34 am" src="https://user-images.githubusercontent.com/18345212/32738970-256fef56-c864-11e7-8ba5-2d11b6d1c76b.png">

I believe the issue is that we're using `assert.strictEqual` but we give no expected result, so we're comparing `true` or `false` with the `message:` string, which is never equal — [nodeJS docs](https://nodejs.org/api/assert.html#assert_assert_strictequal_actual_expected_message)

```
assert.strictEqual(codedTriangleNumbers(1500) == 137, 'message: <code>codedTriangleNumbers(1500)</code> should return 137.');
```
should instead be
```
assert.strictEqual(codedTriangleNumbers(1500), 137, 'message: <code>codedTriangleNumbers(1500)</code> should return 137.');
```

We could change all these assertions from `assert.strictEqual` to `assert.ok` and they'd work as-is, but none of the other solutions use `assert.ok`, so we should probably stay consistent stylistically.

1. Can we make the `words` array either hidden, or possibly display at the bottom of the function? As it is now, I have to scroll through the whole array to get to the `//good luck` comment where I start coding. 
* My thought on making the array hidden is if an end user accidentally adds or deletes any words from that array, our tests could break, since we're hardcoding the # of triangle-number words into that array.
* I don't know if there's such a thing as an immutable challenge object where `words` could be stored

## how i set up the branch locally: is this right?

I can test more when I get the actual assertions passing on my machine. The other earlier challenges work and I have things running locally fine. I'm sorry if I just messed up the checkout process on your branch. Here's what I did:

```
git checkout -b 16079
git pull https://github.com/alvinkl/freeCodeCamp.git feature/problem_euler42
```
at this point it asked me to merge your branch into mine, which I did.

Then I ran `node seed` and `gulp`.

When I run git branch -v it tells me I'm on this:
`* 16079                   f80c1710 branch 'feature/problem_euler42' of https://github.com/alvinkl/freeCodeCamp into 16079`, and this is where I'm gulping from.

2017-11-26 00:10 UTC, alvinkl commented
Hey @thmsdnnr, thank you so much for QA-ing my PR :D
Oh yeah sorry for the assertions mistake, I missed that, thanks for correcting me, it was really bad mistake haha.
I don't really know how to make the word array hidden, I used to play around in the arcade mode repo and I couldn't find a way to make it hidden, but I'm pretty sure there is a way, maybe when running the test we can inject the data there, but I haven't do much research about it.

### Setting branch locally
You don't need to git pull every branch in order to test them,  you can easily fetch the targeted branch from their remotes
for example (if you have added the remote into your git):
```bash
$ git fetch alvink feature/problem42
```
and you can just checkout to the branch
```bash
$ git checkout alvink/feature/problem42
```
and there you can do npm run test and everything without merging anything :D

If it's still unclear you can text me via gitter, because I don't know why I didn't receive any notification here, although I've watched and tick the notification for this repo.
Thank you 👍

2017-11-26 13:33 UTC, thmsdnnr commented
Hi @alvinkl, no problem. Thanks for the git tips. LGTM now. Awesome work! 👍

2017-12-26 09:42 UTC, raisedadead commented
@scissorsneedfoodtoo can you take a look at this one too?

2017-12-26 11:28 UTC, scissorsneedfoodtoo commented
Hi again @alvinkl!

Like @thmsdnnr suggested, how about removing the words array from within the function and moving it below the function itself? Then, then all you have to do is move the function call (codedTriangleNumbers(1786)) to the very bottom of the editor, below the words array, or just remove it entirely.

Like you both discussed, there may be a way to hide the array, however it might not be necessary if you add some spacing and a warning like `// Only change code above this line`.  Not ideal in the sense that it's still possible for the user to accidentally change a word, but it would also give them a chance to bugfix a bit more easily.

So maybe something like this for the challengeSeed:

"function codedTriangleNumbers(n) {",
        "  // Good luck!",
        "  return 1;",
        "}",
        "",
        "// Only change code above this line",
        "const words = [ ...]",
        "];",
        "",
        "codedTriangleNumbers(1786);"


Other than that, everything LGTM!

2017-12-26 11:51 UTC, raisedadead requested changes
Need changes as @scissorsneedfoodtoo suggests

2018-01-04 01:06 UTC, alvinkl commented
hi @raisedadead @scissorsneedfoodtoo,

thanks for reviewng my PR, I've updated the seed as @scissorsneedfoodtoo suggested :)

2018-01-04 06:13 UTC, raisedadead approved these changes

2018-01-05 13:20 UTC, merged