WIP: Migrate React-Redux Curriculum into FCC Codebase
freeCodeCamp/freeCodeCamp pull request #16138
Opened 2017-12-02 06:37 UTC by bonham000

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [x] New feature (non-breaking change which adds new functionality)

#### Checklist:
- [ ] Tested changes locally.

#### Description
Migrate the challenges from the [prototype module](https://github.com/bonham000/fcc-react-tests-module).

2017-12-08 06:02 UTC, Ethan-Arrowood commented
@bonham000 I'm interested in helping you move over the react and redux challenges. Let me know how I can help!

2017-12-08 18:07 UTC, bonham000 commented
Sounds good @Ethan-Arrowood I sent you a message on Gitter.

2017-12-10 03:00 UTC, anhtran1906 commented
@bonham000 Hi I'm also interested in helping you migrate the react/redux challenges over also. Please let me know how I could help

2017-12-10 17:37 UTC, no-stack-dub-sack commented
Hi @anhtran1906, thanks for reaching out! What time zone are you in and what is your schedule like? If you are on Gitter (which will make communication much faster), send one or both of us a message soon, and we can add you to a room where we can discuss how you can help. Thanks again!

2017-12-10 20:25 UTC, anhtran1906 commented
@no-stack-dub-sack Hi I'm in EST timezone and my schedule for the week from December 16th is pretty empty. I am on Gitter as @anhtran1906 also. Please add me in a room so we could discuss more! Thank you!

2017-12-10 20:45 UTC, Ethan-Arrowood commented
@anhtran1906 welcome to the crew I just added you to the gitter chat

2017-12-14 07:05 UTC, Ethan-Arrowood commented
Going to use this comment to track my textual QA of the migrated challenges. 

Completed Challenges: [ ]

2017-12-14 08:14 UTC, bonham000 commented
@Ethan-Arrowood sounds great! Thanks for QA'ing them. Keep updating here and we'll add medals :1st_place_medal: to the passing challenges in the comment above.

We've finished migrated all the challenges so this final review is that last checklist item. Thanks again for your help.

2017-12-14 18:46 UTC, Ethan-Arrowood commented
@bonham000 I'll get through all of them today (in batches). 🎉

2017-12-14 23:48 UTC, Ethan-Arrowood commented
All React challenges are QA'd Redux and React-Redux coming this evening.

2017-12-15 02:58 UTC, Ethan-Arrowood commented
Redux done. React-Redux up next 💯

2017-12-15 20:39 UTC, BerkeleyTrue requested changes

2017-12-15 20:39 UTC, BerkeleyTrue commented on client/frame-runner.js
> +    };
The tests that require access to user code should use `getUserInput` see: https://github.com/freecodecamp/freecodecamp/blob/staging/seed/challenges/03-front-end-libraries/react.json#L65

2017-12-15 20:39 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/execute-challenge-epic.js
> +              return frameTests(build);
see above comment in frame.js

2017-12-15 20:39 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/index.js
> +  updateFileMetaCreator
This change has already landed in staging

2017-12-15 20:39 UTC, BerkeleyTrue commented on common/app/routes/Challenges/utils/frame.js
> +  tests.__originalCode = sources['originalCode'] || '';
see above comment in framejs

2017-12-15 22:15 UTC, BerkeleyTrue commented
This is continued in PR #16200

2017-12-15 22:15 UTC, closed without merging