add tip for alt attribute for the add-images-to-your-website challenge
freeCodeCamp/freeCodeCamp pull request #16197
Opened 2017-12-15 13:55 UTC by angelfeliz

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16050

#### Description
Add description tip for use of the alt attribute use inside the challenge

2017-12-20 19:59 UTC, raisedadead requested changes
LGTM, except for a minor change.

2017-12-20 19:59 UTC, raisedadead commented on seed/challenges/01-responsive-web-design/basic-html-and-html5.json
> +        "Ideally the alt attribute should not contain special chars unless needed.",
Please wrap the `alt` around `code` tags

```diff
- "Ideally the alt attribute should not contain special chars unless needed.",
+ "Ideally the <code>alt</code>attribute should not contain special chars unless needed.",
```

2017-12-21 14:47 UTC, angelfeliz commented
add your suggestion to the request

2017-12-21 16:34 UTC, raisedadead approved these changes

2017-12-21 16:34 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Thanks @angelfeliz , for this pull request and contributing to this code-base for the first time.

Happy contributing!

2017-12-21 16:35 UTC, merged