fix(seed): Space between function name and parameters was not
freeCodeCamp/freeCodeCamp pull request #16324
Opened 2017-12-25 18:41 UTC by sagarjhaa

the regular expression has been changed in test to check for zero or
more space.

Closes #16304

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16304 

#### Description

Edited the regular expression on second test to check for zero to many space between function name and the parameters with "\s*". I have tested with zero space, 1 space and many space between function name and parameters and it works for all the cases.

2017-12-29 18:06 UTC, Bouncey requested changes

2017-12-29 18:06 UTC, Bouncey commented on seed/challenges/02-javascript-algorithms-and-data-structures/functional-programming.json
> +          "assert(code.match(/function\\s+?incrementer\\s*\\(.+?\\)/g), 'message: Your <code>incrementer</code> function should take a parameter.');",
Can you make this a lazy match please with the `*?` quantifier

i.e. `incrementer\\s*?\\(`

2017-12-31 17:50 UTC, sagarjhaa commented
Sure I will make the change.
On Fri, Dec 29, 2017 at 1:09 PM Stuart Taylor <notifications@github.com>
wrote:

> *@Bouncey* requested changes on this pull request.
> ------------------------------
>
> In
> seed/challenges/02-javascript-algorithms-and-data-structures/functional-programming.json
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/16324#discussion_r159088451>
> :
>
> > @@ -289,7 +289,7 @@
>        ],
>        "tests": [
>            "assert(fixedValue === 4, 'message: Your function <code>incrementer</code> should not change the value of <code>fixedValue</code>.');",
> -          "assert(code.match(/function\\s+?incrementer\\(.+?\\)/g), 'message: Your <code>incrementer</code> function should take a parameter.');",
> +          "assert(code.match(/function\\s+?incrementer\\s*\\(.+?\\)/g), 'message: Your <code>incrementer</code> function should take a parameter.');",
>
> Can you make this a lazy match please with the *? quantifier
>
> i.e. incrementer\\s*?\\(
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/16324#pullrequestreview-85992309>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIZ1g1Dqvu1tSNDnZELquVlMdBxZuiTnks5tFSr0gaJpZM4RMXv4>
> .
>

2018-01-03 03:51 UTC, sagarjhaa commented
@camperbot I have made changes.

2018-01-11 23:56 UTC, sagarjhaa commented
@raisedadead do I need to do anything in order to get this pull request merged?

2018-01-12 04:36 UTC, raisedadead commented
Nope, we will pull down and review.. thanks for contributing.

2018-01-15 16:38 UTC, raisedadead approved these changes
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @sagarjhaa , for this pull request and contributing to the code-base for the first time.

We will be looking forward for more contributions like this.

Cheers and happy contributing!

2018-01-15 16:38 UTC, merged

2018-01-15 16:42 UTC, raisedadead commented
P.S: @camperbot is just a dumb robot, doesn't do much other than ranting, I should add some humour settings to it.