style(editor): Change cursor color in editor in dark mode
freeCodeCamp/freeCodeCamp pull request #16320
Opened 2017-12-24 21:56 UTC by huyenltnguyen

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16284

#### Description

The default cursor color is black, which makes it invisible in dark mode. I changed its color (actually `border-color`) to text color to fix it.

2017-12-29 18:03 UTC, Bouncey requested changes

2017-12-29 18:03 UTC, Bouncey commented on common/app/routes/Challenges/views/classic/classic.less
> +    .CodeMirror-cursor {
We need to be more selective here, else `codemirror` styles will win the cascade. 

Use this instead :+1: 
```css
.CodeMirror-cursor {
      border-left-color: @night-text-color;
    }
```

2017-12-30 00:08 UTC, huyenltnguyen commented
Changed as requested. I also nested the code inside `.@{ns}-editor .CodeMirror {}` to match the selectors structure.
@Bouncey Thanks for QA'ing my PR.

2018-01-03 03:54 UTC, DavidCurtis321 approved these changes

2018-01-03 12:10 UTC, tomasvn commented on common/app/routes/Challenges/views/classic/classic.less
>        background-color:#242424;
Add a space after semicolon

Prefer lower case hex values for colors

2018-01-03 12:13 UTC, tomasvn requested changes
~~Fix stylistic inconsistencies across LESS file~~ 

**_Mod update:_** See comment below

2018-01-03 12:13 UTC, tomasvn commented on common/app/routes/Challenges/views/classic/classic.less
>        color:#ABABAB;
Add space after semicolon

Prefer lower case hex values for colors

2018-01-03 12:13 UTC, tomasvn commented on common/app/routes/Challenges/views/classic/classic.less
>        background-color:#242424;
Add a space after semicolon

Prefer lower case hex values for colors

2018-01-03 12:13 UTC, tomasvn commented on common/app/routes/Challenges/views/classic/classic.less
>        color:#5CAFD6;
Add a space after semicolon

Prefer lower case hex values for colors

2018-01-07 17:12 UTC, vkWeb commented
@huyenltnguyen Please make the requested changes. This needs to be merged before shipping. Thanks.

2018-01-08 14:01 UTC, raisedadead commented
Hi @tomasvn 

Thanks for the QA,  I agree, you are 100% correct about the best practices. 

But IMHO, OP has not made those (see diff), hence asking them for a change, isn't fair and not even polite.

I am guessing we could take this up as a separate activity, and maybe a good first timers only task?
Would you be interested in creating the issue? or PR?

@vkWeb thanks for the nudge :man_shrugging: , but, see explanation above, same applies.

@huyenltnguyen 
First of all thanks a lot for taking the time to put this together. 

> Edit: I realized that this PR is just papering over the cracks, more details in #16319. I'll leave this PR open as I don't know which solution you guys'd choose, but feel free to close it. Thanks.

Yes, you are absolutely correct.

We have added some additional clarifications in #16319 if you are interested in taking a stab at it.

Meanwhile, I think this is okay to merge.

2018-01-08 14:03 UTC, raisedadead commented
Will do a QA, tonight. @Bouncey do you approve of your earlier request for changes?

2018-01-08 14:26 UTC, tomasvn commented
@raisedadead I have seen it across different less files, everyone is writing it in a different way, woudn't it be better to have some styleguide? regarding writing consistent CSS? This would help with maintainability of the CSS

2018-01-08 15:29 UTC, raisedadead commented
@tomasvn 

> I have seen it across different less files, everyone is writing it in a different way, woudn't it be better to have some styleguide? regarding writing consistent CSS? This would help with maintainability of the CSS

That's an excellent idea.

Here are our current brand guide https://design-style-guide.freecodecamp.org/ but I can understand that we need an dedicated coding style guide.

We can incorporate per your feedback. Would you mind creating an issue on this tracker and add your thoughts / ideas about the CSS style guide?

We are currently updating out docs in general (see tracker for doc issues). Some outline would get us started in adding those as well.

2018-01-08 15:36 UTC, huyenltnguyen commented
Thanks @tomasvn and @vkWeb. I noticed the inconsistent code style as well but decided not to touch them as I wasn't sure if this PR was a fix or just a hack (turns out it is the latter).

@raisedadead, thanks for cleaning things up here and also for your explanation in #16319. I think this PR is not necessary as I'm pretty sure we can achieve white cursor when the change discussed in #16319 implemented, and you know what? I made the change on `classic.less`. I haven't tested it yet, but I don't think it works on the `modern` editor (I didn't know we have 2 editors when I submitted this PR). So this PR is ineffective anyway and should be closed. I'm working on the issue right now, have some questions already but I need to do some documenting first. I'll see you in the issue thread and hope you don't mind another wall of text lol.

Thanks again @Bouncey.

2018-01-08 15:36 UTC, closed without merging

2018-01-08 16:36 UTC, tomasvn commented
@raisedadead where should I open the issue? here in the fcc repository? or in the appropriate fcc design style guide repo?

2018-01-08 16:41 UTC, raisedadead commented
@tomasvn here in this repository, we plan to keep the docs here itself.