[WIP]Fix: email signup logic
freeCodeCamp/freeCodeCamp pull request #16330
Opened 2017-12-27 00:09 UTC by BerkeleyTrue

2017-12-27 11:15 UTC, raisedadead requested changes

2017-12-27 11:15 UTC, raisedadead commented on common/models/user.json
> +      "type": "bolean",
```diff
-      "type": "bolean",
+      "type": "boolean",
```

2017-12-27 16:42 UTC, raisedadead commented
Hi @BerkeleyTrue this is an excellent direction IMHO, especially moving the logic to the dedicated boot script.

I know this is super busy time for you, but could you share any of the error logs that you saw in production (or analysis of it?).

I suspect and fear that the accessToken Objects and the User Objects were not correctly linked? Just curious and concerned to find the root cause.

2017-12-27 18:13 UTC, BerkeleyTrue commented on common/models/user.json
> +      "type": "bolean",
fixed

2017-12-27 18:21 UTC, BerkeleyTrue commented
@raisedadead I suspect the issue lies with some code running currently. There where also a great many db calls being made. The errors I where seeing where `cannot set headers after they are set`, which is express' way of telling us that the request has been fulfilled but some async process is attempting to the send more data. 

I didn't grab screen caps of these errors but I'd seen them enough to know that there was at the minimum an async issue.

2017-12-27 18:30 UTC, raisedadead approved these changes

2017-12-27 18:54 UTC, raisedadead commented
> I suspect the issue lies with some code running currently. There where also a great many db calls being made.

Yup, the initial implementation relied on nested calls to db. I admit that it was way too procedural.

I don't remember now, but I guess the flexibility was for accounts which may not have had the `emailVerified` property set (for example, old accounts, GitHub created accounts, etc).

But, now we are enforcing only one path to create/login via email (which is good). Hence this approach suits better.

I'll definitely want to keep in mind though of the behaviour, if User Objects missing this `emailVerified` property.

Will test when this is ready, thanks for the refactor.

2017-12-29 04:40 UTC, BerkeleyTrue commented
This is almost ready. I'd like to make one more change, adding a new model based of the accessToken called authToken. This ensures that there is a complete separation between the two types of tokens

2017-12-29 06:05 UTC, raisedadead commented
Nice work @BerkeleyTrue !

>  I'd like to make one more change, adding a new model based of the accessToken called authToken. This ensures that there is a complete separation between the two types of tokens

Sounds reasonable to me, but with that we need to define the lifecycle methods on that too.

What I mean is we would have to implement the:
```
this.createAccessToken$({ ttl: 15 * 60 * 1000 });
```

and its associated lifecycle methods?
If not a priority we should defer it to later?

2017-12-30 07:41 UTC, raisedadead commented
WIP - QA

Testing locally
QA:
- [x] Create new account
  - [x] get new account message
  - [x] get new account email
  - [x] follow new account email link to signin
- [ ] Sign in with old account
  - [ ] get sign in message
  - [ ] get sign in email
  - [ ] follow sign in email to signin

Observations:

- The TTL for the AccessToken Object (long term) is `NaN`
```
{
    "_id" : "PwtRSaZPbcvver5t9E0gks7xASZLq4o2znvYAqB903lSiRbbdR4wo8oUU6DUyIhu",
    "ttl" : NaN,
    "created" : ISODate("2017-12-30T07:36:48.123Z"),
    "userId" : ObjectId("5a47420bf3f3e8298faaa18f")
}
```

2017-12-30 08:08 UTC, raisedadead commented
Additional Notes (to be taken in new PR, since they are not bugs per say because of changes):

-  The update email path breaks with a `Error: Authorization Required`
  -  Email is sent and received correctly.
  -  Clicking on the email is hitting LoopBack's native implementation (`/confirm` endpoint) and needs to be rather implemented now.

2017-12-30 08:47 UTC, raisedadead commented
@BerkeleyTrue 

Everything looks good to me.

One thing to handle though is the destruction of the old token as I am able to do repeated logins after sign out for second time on using the same previous Login Requested email.

Steps:
1. Create new account / Logout
2. Sign in with old account (from step 1) / Logout
3. Click the same (from step 2) / Logout
4. Repeat steps 2-3.

2017-12-31 03:50 UTC, BerkeleyTrue commented
@raisedadead Sorry, I left three commits on my local. It should fix those problems.

2018-01-02 08:26 UTC, raisedadead commented
Thanks @BerkeleyTrue, Happy new year. I'll QA tonight and merge.

2018-01-02 18:07 UTC, raisedadead commented
#### :sparkles: :sparkles: **WOOT!** :sparkles: :sparkles: 

Thanks @BerkeleyTrue, Nice work! Everything works like a charm. 
Lets get this on beta, and test the response times in the wild.

2018-01-02 18:08 UTC, merged