fix(seed): Best practice for radio button
freeCodeCamp/freeCodeCamp pull request #16349
Opened 2017-12-28 00:52 UTC by darthm3gatron

Closes #15946

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

2017-12-28 06:26 UTC, raisedadead requested changes

2017-12-28 06:26 UTC, raisedadead commented on seed/challenges/01-responsive-web-design/basic-html-and-html5.json
> +        "It is considered best practice to set the for attribute for assistive technologies to be able to link the relationship between the label and the child elements such as an input in this case.
Please wrap the `for` and `input` around `<code>` tags.

2017-12-28 06:27 UTC, raisedadead commented
Also please fill the checklist in the PR description above

2017-12-29 05:59 UTC, raisedadead requested changes
@darthm3gatron nice work, some finishing touches and we are good to go!

2017-12-29 05:59 UTC, raisedadead commented on seed/challenges/01-responsive-web-design/basic-html-and-html5.json
> +        "<code>&#60;label&#62;&#60;input type=\"radio\" name=\"indoor-outdoor\" for=\"indoor\" &#62; Indoor&#60;/label&#62;</code>",
Some more changes:

1. The code sample needs the `for` attribute inside the `<label>`, NOT the `<input>`
2. Lets, split it into a block to make it cleaner. (refer: [Challenge Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/seed/challenge-style-guide.md))
3. The clarification text is to be placed after the code sample.

```diff
-        "<code>&#60;label&#62;&#60;input type=\"radio\" name=\"indoor-outdoor\" for=\"indoor\" &#62; Indoor&#60;/label&#62;</code>",
+        "<blockquote>&#60;label for=\"indoor\"&#62; <br> &#60;input type=\"radio\" name=\"indoor-outdoor\"&#62;Indoor <br>&#60;/label&#62;</blockquote>",
+        "It is considered best practice to set the <code>for</code> attribute for assistive technologies to be able to link the relationship between the label and the child elements such as an <code>input</code> in this case.",
```

2017-12-29 05:59 UTC, raisedadead commented on seed/challenges/01-responsive-web-design/basic-html-and-html5.json
> +        "It is considered best practice to set the <code>for</code> attribute for assistive technologies to be able to link the relationship between the label and the child elements such as an <code>
Remove this line

```diff
-        "It is considered best practice to set the <code>for</code> attribute for assistive technologies to be able to link the relationship between the label and the child elements such as an <code>input</code> in this case."
```

2017-12-29 18:11 UTC, darthm3gatron commented
It's telling me the Travis CI build failed. I'm not sure what went wrong there.

2017-12-29 18:16 UTC, raisedadead commented
There is an invalid `+` character in the new changes. This is also easily caught when you run tests and locally check by running the local server.

```
npm run test
```

```
npm run develop
```

2017-12-29 18:33 UTC, darthm3gatron commented
Sorry about that. I'm new to all this.

2017-12-29 18:54 UTC, raisedadead approved these changes

2017-12-29 18:57 UTC, raisedadead commented
#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles: 

Real nice work! Sorry about so many change requests, its just a part of reviewing. 

Thanks @darthm3gatron,  for this pull request and contributing to the code-base for the first time. 

Happy contributing!

2017-12-29 18:57 UTC, merged