fix(babel): Pause babel pipeline when not submitting challenge
freeCodeCamp/freeCodeCamp pull request #16370
Opened 2017-12-29 17:37 UTC by Bouncey

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16361 

#### Description

This PR will:
- Pause babel pipeline whilst code is most probably incomplete. 
- Provide friendly toast messages explaining any trans-pile errors from babel

2018-01-02 00:09 UTC, BerkeleyTrue requested changes

2018-01-02 00:09 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/execute-challenge-epic.js
> +            isJSEnabledSelector(state) &&
This disables the live preview when editing html

2018-01-02 00:09 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/execute-challenge-epic.js
> -        types.modernEditorUpdated,
This disables the live preview window for modern challenges

2018-01-02 00:09 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/execute-challenge-epic.js
> +            isJSEnabledSelector(state)
This only runs on execute which sets isJSEnabled to true, so this conditional would never be false

2018-01-02 00:14 UTC, BerkeleyTrue commented
The best approach for this issue is going to be changing the build pipeline not changes to redux

The entry would be here https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Challenges/utils/build.js#L48

This is where we can use state to selectively enabled/disable parts of the pipeline.

Here https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/common/app/routes/Challenges/rechallenge/transformers.js#L100

Is where we can also inject logic to selectively disable transformers.

2018-01-05 00:51 UTC, BerkeleyTrue commented
I'm liking where the changes are going. There is a lot of complexity that may not be necessary. 
This still does not actually remove the js transforms from the pipeline when js is disabled.

2018-01-16 18:02 UTC, BerkeleyTrue commented on client/epics/err-epic.js
> +      message: error.message || 'Something went wrong, please try again later'
We shouldn't be displaying err messages to users.

2018-01-16 18:13 UTC, BerkeleyTrue commented on common/utils/polyvinyl.js
> +//   files: List[ PolyVinyl ]
You don't need to include `List` here. To express an array in rtype its just `[]`. To express a typed array it's `[...Polyvinyl]`.

2018-01-17 22:50 UTC, BerkeleyTrue commented
@Bouncey I apologies for being latent on this PR but I'm mulling over an idea in my head that hasn't yet reified.

The abstract of it came from your use of the error to signal to the user that the transform has failed.

In the build pipelines current shape this is necessary for this feature to work, but it got me thinking about how we get messages from the frame-runner out to the app state.

I'm leaning toward a solution that would mimic this behavior. Possibly adding a proxy to tap into the build pipeline that would be used to get messages out. This way we wouldn't need to highjack the error handling thread of the observable and we would add the the api of the pipeline itself making it more flexible and powerful.

Does this make sense? What are your thoughts?

2018-01-24 23:24 UTC, Bouncey commented
@BerkeleyTrue Sorry I am only seeing this now, I have seeing 'blond, brunette, red-head' for the past week.

I think that having a way to provide helpful messages to the user would be great. At the minute the `friendly message` is just being dumped to the browser console, which is no good if the user relys on the proxy console.

Would you want it done along with this PR or a separate one?

2018-01-25 16:16 UTC, Bouncey commented
I've just had a quick play with this idea, and the only way I can see of doing it is setting another property on the poly as they come through to hold the `friendlyError`. Then if that prop is defined, dispatch an action somehow.

At the minute it would require us to inject dispatch from the execute challenge epic

2018-02-26 12:21 UTC, Bouncey commented
@BerkeleyTrue Should we merge this is get Beta out the door and put friendly error messages on the road map?

2018-02-26 20:05 UTC, BerkeleyTrue approved these changes

2018-02-26 20:05 UTC, BerkeleyTrue commented
Alright, if you think this is ready we'll merge it in.

2018-02-26 20:10 UTC, merged