Feature/link to guide
freeCodeCamp/freeCodeCamp pull request #16442
Opened 2018-01-08 06:20 UTC by iabrenne

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Partial update for #16388. 

#### Description
Added "See Guide" button to ToolPanel component that will only display if "guideUrl" prop is present for the given challenge. Once button is clicked, an article from FCC Guide for the corresponding challenge opens up in a new  browser tab. I am now in process of updating .json files in the seed/challenges folder by adding guideUrl property with appropriate links. 20 challenges have been seeded so far. Many more left to go . 

![image](https://user-images.githubusercontent.com/24214306/34660656-9a958de2-f409-11e7-89eb-6615ac9c2775.png)

2018-01-08 07:23 UTC, raisedadead commented
Nice work. just a quick query, is this ready for us to QA, or you are adding more changes? It's alright if you need time updating challenges, we can take them in small separate PRs. Let us know, and thanks for contributing.

2018-01-08 12:23 UTC, iabrenne commented
@raisedadead Yes, I was thinking we can do this in small separate PRs. It will take a while to update all the challenges. If we do it in small PRs, at least campers can benefit from having guide article available for some of the challenges.

2018-01-08 12:41 UTC, raisedadead commented
Awesome. Thanks for the update.

2018-01-08 15:50 UTC, BerkeleyTrue requested changes

2018-01-08 15:50 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/index.js
> +      guideUrl,
If this is already on the challenge object, do we need to add it to the meta information? meta is reserved for derived data.

2018-01-09 04:09 UTC, iabrenne commented
@BerkeleyTrue - thank you for the feedback. I missed the fact that guideUrl field did not need to be returned from challengeMetaSelector, as it was already available on the Challenge object. I removed my updates from the Challenges/redux/index.js.

2018-01-09 14:20 UTC, BerkeleyTrue commented on common/app/routes/Challenges/Show.jsx
> +    { viewType, title, guideUrl },
You're still pulling the guideUrl from metadata here.

2018-01-10 10:51 UTC, iabrenne commented
@BerkeleyTrue - thank you so much, missed that also. I *think* this is fixed now. I made an update to pull guideUrl field from the Challenge object instead of the MetaSelector in the Show.jsx as well. Would you please take a look? Thank you!

2018-01-10 23:12 UTC, BerkeleyTrue commented on common/app/routes/Challenges/Show.jsx
> +    guideUrl,
This is added to mapStateToProps but the value is not used anywhere in the component. This may be an unnecessary change.

2018-01-10 23:13 UTC, BerkeleyTrue commented on common/models/challenge.json
> +      "type": "string"
Please add a short description of the purpose of this property.

2018-01-11 00:37 UTC, iabrenne commented
Thank you, @BerkeleyTrue. Changes have been made. Please let me know if you see anything else.

2018-01-13 16:48 UTC, BerkeleyTrue approved these changes

2018-01-16 20:52 UTC, merged

2018-01-16 20:52 UTC, BerkeleyTrue commented
@iabrenne Works great, thanks for putting this together!

Happy Coding