fix(map): Removed NA text for challenge without time estimat
freeCodeCamp/freeCodeCamp pull request #16479
Opened 2018-01-12 11:13 UTC by lgrzybowski

Closes #16454

#### Pre-Submission Checklist
- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change
- [X] Small bug fix (non-breaking change which fixes an issue)

#### Checklist:

- [X] Tested changes locally.
- [X] Addressed currently open issue https://github.com/freeCodeCamp/freeCodeCamp/issues/16454

Closes #16454

#### Description
I had run already implemented tests, but I think for react project it would be really nice to use jest with [snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html).

2018-01-12 15:47 UTC, vkWeb commented
@lgrzybowski Next time please comment on the issue you're working on so that the other participants know that you're on it.

2018-01-12 19:53 UTC, 0x0936 commented
The if/else block added in Block.jsx produces a lot of duplicate code. Perhaps there's a more elegant way to inject the time span.

```js
{
  time
    ? <span className={ `${ns}-block-time` }>({ time })</span>
    : ''
}
```

2018-01-12 23:52 UTC, r1chard5mith commented
Or you could just leave the time as N/A and test for it in the JSX and then it's a one line change to one file only.

`<span className={ `${ns}-block-time` }>{ time === "N/A" ? "" : "(" + time + ")" }</span>
`

2018-01-14 20:01 UTC, lgrzybowski commented
@0x0936 This should looks better now.

2018-01-18 06:53 UTC, BerkeleyTrue requested changes

2018-01-18 06:53 UTC, BerkeleyTrue commented on common/app/Map/Block.jsx
> +          : ''
This can be reduced to a short circuit
```js
foo && <foo />
``

2018-01-23 18:36 UTC, lgrzybowski commented
@BerkeleyTrue Thx for your review this should be looking better now.

2018-01-24 02:59 UTC, BerkeleyTrue approved these changes

2018-01-24 02:59 UTC, merged

2018-01-24 02:59 UTC, BerkeleyTrue commented
@lgrzybowski nice work!


Happy Coding

2018-01-24 04:20 UTC, QuincyLarson commented
@lgrzybowski Awesome! Thank you for your contribution to the codebase!