fix(challenges): Add logic to toggle editor theme
freeCodeCamp/freeCodeCamp pull request #16496
Opened 2018-01-15 06:51 UTC by huyenltnguyen

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16284
Refers #16319

#### Description

What I did:
- Add logic to both of the `Editor.jsx` files to toggle theme based on user's selected mode.
- Import theme's style into our style sheet.
- Add night mode style to the console output. (I use the exact same colors as the dracula's).
- Delete duplicate code in `Editor.less` as the code already exists in `challenges.less`.

Note:
This PR was **not** fully tested as syntax highlighting doesn't work on local version. The issue was addressed here: https://github.com/JedWatson/react-codemirror/issues/34.

2018-01-16 17:02 UTC, BerkeleyTrue requested changes

2018-01-16 17:02 UTC, BerkeleyTrue commented on common/app/routes/Challenges/challenges.less
> +@import (inline) '../../../../node_modules/codemirror/theme/dracula.css';
We grab codemirror css from a cdn here: https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/server/views/partials/react-stylesheets.jade

2018-01-16 22:50 UTC, BerkeleyTrue approved these changes

2018-01-17 19:24 UTC, merged

2018-01-17 19:24 UTC, BerkeleyTrue commented
@huyenltnguyen Nice work!

Happy Coding

2018-01-18 08:22 UTC, huyenltnguyen commented
@BerkeleyTrue Thanks for all the help!