fix(ui): Add logic to toggle console theme
freeCodeCamp/freeCodeCamp pull request #16551
Opened 2018-01-21 13:31 UTC by huyenltnguyen

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16319

#### Description

I made a mistake in my previous PR [(#16496)](https://github.com/freeCodeCamp/freeCodeCamp/pull/16496) by manually changing the console style in the stylesheet instead of implementing the logic to the Output component, which results a terrible render on the live beta (see screenshot).
Same as the previous PR, this one was **not** fully tested due to the syntax highlighting issue.

![untitled](https://user-images.githubusercontent.com/25715018/35194690-cc297a40-fee9-11e7-984e-05722bbad5e5.png)

2018-01-21 14:44 UTC, raisedadead commented
Just to confirm the current issue only affects night mode? And this PR fixes this? Also, syntax highlight seems to work for me locally.

2018-01-21 15:04 UTC, raisedadead approved these changes
LGTM. I'll wait for @BerkeleyTrue for a look. Also we might need a a border around the console in the day mode.

But, I guess I am a fan of the night mode right now.

2018-01-21 16:15 UTC, huyenltnguyen commented
@raisedadead Thanks for the QA. Yes, the issue only affects night mode. It's because I didn't give the console the theme, let it use `default` as a fallback and get all the `default` style (dark text on white background). The syntax highlighting issue made me think the console only displays text, therefore, I decided not to implement any logic to the component as it'd be a bit of an overkill, and I just went tweak the background and text color for night mode instead.
I'm happy to update the PR for the border if you guys need it.
The syntax highlighting issue is weird. A number of people reported that they have this issue as well, but just a few days ago I did see someone's screenshot of the local version, in which the syntax highlighting works fine. It's a bit annoying but not important, though.

2018-01-21 16:47 UTC, raisedadead commented
Sure, if you have a moment and the change is not too much work, then please add it while your at this already.

2018-01-22 07:28 UTC, huyenltnguyen commented
Added a border for the console in day mode.

2018-01-22 18:45 UTC, BerkeleyTrue requested changes

2018-01-22 18:45 UTC, BerkeleyTrue commented on common/app/routes/Challenges/Output.jsx
> +const mapStateToProps = createSelector(
There is no need to add a layer of memoization if there is only one value being selected for. In these situations it is fine just to use the selector (in this case the theme selector) with a plain function.

2018-01-23 12:33 UTC, huyenltnguyen commented
Changed as requested.
I also noticed the 'link to github' button doesn't have a green background as others in night mode, so I made a change to fix it too.

![untitled](https://user-images.githubusercontent.com/25715018/35275945-0383a890-0074-11e8-95fd-d67c09cb495f.png)

2018-01-24 02:07 UTC, BerkeleyTrue commented on common/app/routes/Settings/Social-Settings.jsx
> +      className='btn-link-social btn-github btn-primary'
This change should be a prop

`bsStyle='primary'`

2018-01-24 19:01 UTC, BerkeleyTrue commented on common/app/routes/Settings/Social-Settings.jsx
> +      bsStyle='primary'
Looking at this now, I don't understand your reasoning for adding this. None of the other social buttons have a primary style. What is missing is the active state. Maybe you where referring to that? In that case the change would be to add `active={ isGithubCool }`

2018-01-24 19:08 UTC, BerkeleyTrue commented
I've tested the PR. The output is noticeably improved. I have one more note that requires fixing for this to be merged in.

2018-01-24 20:53 UTC, huyenltnguyen commented
@BerkeleyTrue Sorry for all the mess I've made, including the output.
I'm a bit confused, what does `active` mean? Does it mean user has connected to their github account? I didn't really look into its logic, though. The button is just right below the 'toggle theme' button, so while I was working on the theme issue, I noticed that it didn't have a green background like the others (not the other social buttons, but the other buttons on the same page). I didn't see any other social buttons on the page, so there wasn't any style reference for this. That's why I compared it with the 'toggle theme' button and thought it was missing the `primary` class.
If the intent is to light up the button only when github account is connected, then my change is unnecessary and I'll revert it.
Sorry again.

2018-01-25 09:05 UTC, systimotic commented
The other social buttons don't have the `primary` style either, but I agree that this is a bit weird. Every single other button on the page does have the `primary` style, even toggles that are off. That said, it's also nice to have a visual difference between an active and an inactive button.
We should probably remove this change from this PR and open a new issue to discuss this.

2018-01-25 13:19 UTC, raisedadead commented
> We should probably remove this change from this PR and open a new issue to discuss this.

Up I too agree on this.

2018-01-25 13:32 UTC, huyenltnguyen commented
I should have asked first before wasting our time.
Sorry and thanks for all the help!

2018-01-25 20:13 UTC, BerkeleyTrue approved these changes

2018-01-25 20:13 UTC, merged

2018-01-25 20:15 UTC, BerkeleyTrue commented
@huyenltnguyen thanks for the PR!

@raisedadead @systimotic The social buttons are styled differently because they have their own styling, which `primary` would override. What is needed is slightly different styling when dark mode is active. Maybe making the background of the button a different shade of gray?

2018-01-25 20:27 UTC, raisedadead commented
@huyenltnguyen nice work, trust me I would just default to the night mode..! lol.

2018-01-25 20:28 UTC, raisedadead commented
Lets, take Berkeley's advice though, if you are still up for making a PR for the social buttons. But that said Stuart has some things in pipeline and we should probably defer a little on those changes.

2018-01-25 22:42 UTC, systimotic commented
Thanks for fixing this @huyenltnguyen, nice work!

To elaborate on what Stuart has in the pipeline, it's this PR: https://github.com/freeCodeCamp/freeCodeCamp/pull/16412
It's massive and touches the area around these buttons, so I agree that it would be a good idea to wait for that.