Fix/backend completion
freeCodeCamp/freeCodeCamp pull request #16699
Opened 2018-02-12 12:45 UTC by Bouncey

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16596

#### Description

2018-02-12 22:35 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/completion-epic.js
> +    console.log(solution)
console log

2018-02-12 22:36 UTC, BerkeleyTrue requested changes

2018-02-12 22:36 UTC, BerkeleyTrue commented on common/app/routes/Challenges/redux/completion-epic.js
> +    const { solution } = getValues(state.form.BackEndChallenge);
This should be a selector. Reaching into state is couples this epic with the shape of the state

2018-02-15 20:09 UTC, QuincyLarson commented
@Bouncey once @BerkeleyTrue is happy with this and has dismissed his review I'll QA the functionality and merge :)

2018-02-16 00:26 UTC, BerkeleyTrue approved these changes

2018-02-16 15:24 UTC, QuincyLarson commented
LGTM! Thanks, @Bouncey!

2018-02-16 15:24 UTC, merged