fix(navigation): Give new users a currentChallengeId if one is not pr…
freeCodeCamp/freeCodeCamp pull request #16838
Opened 2018-03-06 11:53 UTC by Bouncey

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #16792

#### Description

New users do not have a current challenge id until they either click a challenge in the map or submit a challenge. This leads to some navigation features not working correctly. 

This PR updates the local user state with the current challenge id if none if found in the user state.

2018-03-07 05:33 UTC, raisedadead approved these changes

2018-03-08 22:12 UTC, BerkeleyTrue requested changes
hangouts notes: debug Nav/redux loadCurrentEpic

2018-03-12 21:31 UTC, BerkeleyTrue approved these changes

2018-03-12 21:31 UTC, BerkeleyTrue commented
Wow, nice find!

2018-03-12 21:32 UTC, merged