refactor: Remove deprecated endpoints, methods and properties.
freeCodeCamp/freeCodeCamp pull request #16898
Opened 2018-03-15 03:46 UTC by ojongerius

Removes bits that were marked as deprecated a while ago, as far as I can tell they were no longer in use. Tests still pass.

```
  total:     1343
  passing:   1343
  duration:  12.1s
```

/cc @BerkeleyTrue

2018-03-19 18:19 UTC, BerkeleyTrue commented
Are these in production?

2018-03-21 20:27 UTC, ojongerius commented
`/modern-challenge-completed` definitely was. I was hoping you would have more confidence in what is out there at the moment -I have no insight in how you deploy FCC.

2018-03-23 17:33 UTC, raisedadead requested changes

2018-03-23 17:33 UTC, raisedadead commented on common/models/user.json
> -    "currentChallenge": {
We still need this, because of our legacy database. This will mutate the User Object (old) in a way that we do not want.

2018-05-15 05:31 UTC, raisedadead commented
Hi @ojongerius I am closing this for now, and lets revisit the cleanup once again.

2018-05-15 05:31 UTC, closed without merging