docs(seed): Japanese translation
freeCodeCamp/freeCodeCamp pull request #17055
Opened 2018-04-12 21:45 UTC by t-cool

#### Pre-Submission Checklist

- [* ] Your pull request targets the `staging` branch of freeCodeCamp.
- [* ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [* ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [* ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [* ] Add new translation (feature adding new translations)

#### Checklist:

- [* ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

Japanese translation: 01-responsive-web-design/basic-html-and-html5.json

2018-04-12 21:46 UTC, t-cool commented
I sent a new PR!

2018-04-13 04:25 UTC, raisedadead requested changes
Hi @t-cool 

1. Remove the lock file from your commit.
2. Amend your commit message to `feat(seed): Japanese translation of basic html challenges`

2018-04-13 08:09 UTC, t-cool commented
@raisedadead 
I fixed it!

2018-04-13 11:14 UTC, t-cool commented
@raisedadead 
What does "status: blocked" mean?

2018-04-13 12:13 UTC, raisedadead requested changes
Please revisit my https://github.com/freeCodeCamp/freeCodeCamp/pull/17055#pullrequestreview-111878283

You need to remove (DO NOT delete) the package-lock.json from this pull request.

If you need assistance. Please visit the [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors)

2018-04-13 12:13 UTC, raisedadead commented on .gitignore
> +package-lock.json
Why are you adding the lock file to `.gitignore`? This has to be reverted

2018-04-13 13:57 UTC, t-cool commented
I'll close this PR and make another PR tomorrow!

2018-04-13 13:57 UTC, closed without merging