contribution guideline link takes to table of contents
freeCodeCamp/freeCodeCamp pull request #17070
Opened 2018-04-18 17:00 UTC by Dipeshwagle

#### Pre-Submission Checklist

- [x] Your pull request targets the `staging` branch of freeCodeCamp.
- [x] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [x] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [x] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [x] Tested changes locally.
- [x] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17062

#### Description

Links associated with 'contribution guidelines' were broken, due to change from 'Contribution Guidelines header' to 'Table of Contents' in [this](https://github.com/freeCodeCamp/freeCodeCamp/commit/6bc521815aa68e3296935dec3f292d64dba65e6c) commit. Fixed links so it goes to to 'Table of Contents'.

2018-04-19 04:30 UTC, rohanBagchi commented
I think renaming the `Table of Contents` to `Contribution Guidelines` would make more sense. 
The list on top does say :
Follow the **Contribution Guidelines** to start working on the issue.
Personally I would expect a list with a similar title.

2018-04-23 12:33 UTC, raisedadead requested changes

2018-04-23 12:33 UTC, raisedadead commented on CONTRIBUTING.md
> +3. Follow the [Contribution Guidelines](#table-of-contents) to start working on the issue.
Lets just get rid of this link. I think its not required.

```diff
- 3. Follow the [Contribution Guidelines](#table-of-contents) to start working on the issue.
+ 3. Follow the instructions in this guide to start working on the issue.
```

2018-04-23 12:33 UTC, raisedadead commented on CONTRIBUTING.md
> +     the [Contribution Guidelines](#table-of-contents) for more detail.
```diff
- .... Review the [Contribution Guidelines](#table-of-contents) for more detail.
```

2018-04-23 12:33 UTC, raisedadead commented on CONTRIBUTING.md
> +     the [Contribution Guidelines](#table-of-contents) for more detail.
Remove the above sentence.

2018-04-26 22:03 UTC, merged