Fixed tag nesting order in Applied Visual Design challenge
freeCodeCamp/freeCodeCamp pull request #17093
Opened 2018-04-29 02:41 UTC by VoxHumana

#### Pre-Submission Checklist

- [ x ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ x ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [x ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ x ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ x ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ x ] Tested changes locally.
- [ x ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17077

#### Description

This PR fixes the nesting order of the `<p>` and `<em>` tags in this [Applied Visual Design challenge](https://beta.freecodecamp.org/en/challenges/applied-visual-design/use-the-em-tag-to-italicize-text)

Previously the users were instructed to wrap the `<em>` tags around the `<p>` tags like this 
`<em><p> Some text here...</p></em>` which was incorrect.

The users should now warp the `<em>` tag around the paragraph contents like this 
`<p><em> Some text here...</em></p>`.

2018-04-29 02:56 UTC, VoxHumana commented
Incidentally I've noticed that for this challenge, it is possible for the user to pass the new tests with incorrect solutions such as 
```html
<p>
  <em>Google was founded by Larry Page and Sergey Brin while they were 
    <u>Ph.D. students</u> 
    at 
    <strong>Stanford University </em></strong>.
</p>
```
Notice that the `</em>` closed within a `<strong>` tag. This appears to be due to the fact that the actual HTML generated from this input would be something like this

```html
<p>
  <em>Google was founded by Larry Page and Sergey Brin while they were 
    <u>Ph.D. students</u> 
    at 
    <strong>Stanford University </strong>
  </em>.
</p>
```
If we consider only this particular challenge, it's possible to enforce that the user place the `<em></em>` tags immediately after the `<p>` and immediately before the `</p>` by verifying the innerHtml in the tests. However I've no idea what a solution to the larger problem of the HTML generation might be.

2018-05-03 14:10 UTC, mstellaluna commented
Currently working on this PR

2018-05-03 14:35 UTC, mstellaluna requested changes
Minor Changes needed

2018-05-03 14:40 UTC, mstellaluna commented
@VoxHumana hello, I have tested your PR and have some additional suggestion(s).

the following code still passes the tests even though it is incorrect. The opening em tag is inside the p tag where as the closing em tag is outside the p tag 

` <p><em>Google was founded by Larry Page and Sergey Brin while they were <u>Ph.D. students</u> at <strong>Stanford University</strong>.</p></em>`

2018-05-04 05:26 UTC, VoxHumana commented
@mstellaluna Hi, I've taken a look at your suggestion. Currently the incorrect markup that you posted generates exactly the same DOM in Chrome and Firefox as the correct version. In other words, putting the closing em tag outside, or just inside the p tag doesn't appear to make a difference to the browser.

So browsers are now apparently rendering invalid markup as if they're valid. Short of creating some sort of validation layer for all user submitted markup, I'm not sure how to fix an issue like this.  The tests won't be of any help here since invalid/valid markup both generate the same DOM.

2018-05-09 00:08 UTC, mstellaluna commented
@VoxHumana Sorry for the delay in responding. Thanks for the clarification.

2018-05-09 00:08 UTC, mstellaluna approved these changes

2018-05-09 00:09 UTC, mstellaluna commented
@VoxHumana I will go ahead and approve this PR. Thank you for your contribution. Happy Coding.

2018-05-09 00:09 UTC, merged