feat(interview-prep): Porting Rosetta problems
freeCodeCamp/freeCodeCamp pull request #17388
Opened 2018-06-02 08:50 UTC by NitronR

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

#### Description

Moved Gamma function problem to correct the alphabetic order. Ported 3 rosetta problems.

2018-06-02 09:22 UTC, raisedadead commented
Thanks for the PR @NitronR

2018-06-04 09:19 UTC, scissorsneedfoodtoo commented
@NitronR, sorry again for the delay. Thank you for your patience and for finding the MathJax library that we'll need over on Learn.

Just a couple of things. I know in your last PR I didn't mention anything about the formatting of the description, but I believe it could cause errors in the future. Could you go through and clean up the some of the HTML tags? They might have been needed on Arcade Mode, but they shouldn't be necessary here.

Here's the Gamma Function description as an example:

```
"description": [
        "Implement one algorithm (or more) to compute the <a class=\"rosetta__link--wiki\" href=\"https://en.wikipedia.org/wiki/Gamma function\" title=\"wp: Gamma function\">Gamma</a> ($\\Gamma$) function (in the real field only).",
        "The Gamma function can be defined as:,",
        "<div style='padding-left: 4em;'><big><big>$\\Gamma(x) = \\displaystyle\\int_0^\\infty t^{x-1}e^{-t} dt$</big></big></div>"
      ],
```

I just went through and took out the `<p>` and `<div class="rosetta-____">` tags. The tricky part was the math formula, where I removed the semi-colon indents and spans, then added a div with padding-left to mimic a tab. The <big> tags can be left in, as they're part of the MathJax library.

Would you mind going through and making those changes to the descriptions? Also, I left some code reviews with a couple other minor changes.

2018-06-04 09:30 UTC, NitronR commented
Sure I will do that.

2018-06-05 10:38 UTC, NitronR commented
@scissorsneedfoodtoo Fixed the descriptions as you said. Thanks for the example!!

2018-06-06 10:45 UTC, scissorsneedfoodtoo commented
@NitronR, thank you! I'll take a look now.

2018-06-06 12:08 UTC, scissorsneedfoodtoo requested changes
@NitronR, thank you for your patience with this whole process. Just a few small changes and I think we're good to go.

2018-06-06 12:08 UTC, scissorsneedfoodtoo commented on seed/challenges/08-coding-interview-prep/rosetta-code.json
> +      "challengeType": 3,
Could you please change this to `"challengeType": 5,`? Otherwise it shows a project type of submission form rather than the code editor.

2018-06-06 12:08 UTC, scissorsneedfoodtoo commented on seed/challenges/08-coding-interview-prep/rosetta-code.json
> +      "description": [
Could you change the description to the following? Tried to simplify it a bit and took out a couple of lingering `<p>` tags:

```
"description": [
        "Write a generalized version of <a href=\"http://rosettacode.org/wiki/FizzBuzz\">FizzBuzz</a> that works for any list of factors, along with their words.",
        "This is basically a \"fizzbuzz\" implementation where the rules of the game are supplied to the user. Create a function to implement this. The function should take two parameters.",
        "The first will be an array with the FizzBuzz rules. For example: <code>[ [3,\"Fizz\"] , [5,\"Buzz\"] ]</code>.",
        "This indcates that <code>Fizz</code> should be printed if the number is a multiple of 3 and <code>Buzz</code> if it is a multiple of 5. If it is a multiple of both then the strings should be concatenated in the order specified in the array. In this case, <code>FizzBuzz</code> if the number is a multiple of 3 and 5.",
        "The second parameter is the number for which the function should return a string as stated above."
      ],
```

2018-06-06 12:08 UTC, scissorsneedfoodtoo commented on seed/challenges/08-coding-interview-prep/rosetta-code.json
> +      "challengeType": 2,
This one too, please. `"challengeType": 5,`.

2018-06-06 12:08 UTC, scissorsneedfoodtoo commented on seed/challenges/08-coding-interview-prep/rosetta-code.json
> +      "challengeType": 2,
And last one, `"challengeType": 5,`.

2018-06-06 12:37 UTC, NitronR commented
@scissorsneedfoodtoo Thanks for the review. I have made the changes.

2018-06-06 13:38 UTC, scissorsneedfoodtoo approved these changes

2018-06-06 13:39 UTC, merged

2018-06-06 13:39 UTC, scissorsneedfoodtoo commented
@NitronR, wow! That was really fast. Thank you so much for bearing with me and making all of those changes. Everything LGTM!