Updated json file with right url values
freeCodeCamp/freeCodeCamp pull request #17445
Opened 2018-06-05 17:21 UTC by bogadodiegoh

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17416

#### Description

2018-06-06 13:04 UTC, scissorsneedfoodtoo commented
@bogadodiegoh, thank you very much for submitting a PR for this. However, it seems like there's a slight issue with the URL you updated. Please take a look at my review.

2018-06-06 13:08 UTC, scissorsneedfoodtoo requested changes

2018-06-06 13:08 UTC, scissorsneedfoodtoo commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
> +            "<strong>Nota</strong><br>No olvides usar <code>notación corchete</code> cuando <a href=\"javascript-algorithms-and-data-structures/basic-javascript/accessing-objects-properties-with-vari
This line, too:
`javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-variables`

2018-06-06 13:08 UTC, scissorsneedfoodtoo commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
> +        "<strong>Hints</strong><br>Use <code>bracket notation</code> when <a href=\"javascript-algorithms-and-data-structures/basic-javascript/accessing-objects-properties-with-variables\" target=\"_
Could you change this to the following:

`javascript-algorithms-and-data-structures/basic-javascript/accessing-object-properties-with-variables`

2018-06-06 15:08 UTC, scissorsneedfoodtoo commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
>          "You may refer back to <a href=\"manipulating-complex-objects\" target=\"_blank\">Manipulating Complex Objects</a> Introducing JavaScript Object Notation (JSON) for a refresher."
While you're at it, could you also change this link?:
`javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects`

2018-06-06 15:10 UTC, scissorsneedfoodtoo commented on seed/challenges/02-javascript-algorithms-and-data-structures/basic-javascript.json
>          "You may refer back to <a href=\"manipulating-complex-objects\" target=\"_blank\">Manipulating Complex Objects</a> Introducing JavaScript Object Notation (JSON) for a refresher."
While you're at it, could you also update this link?:
`javascript-algorithms-and-data-structures/basic-javascript/manipulating-complex-objects`

2018-06-08 23:17 UTC, raisedadead commented
@scissorsneedfoodtoo see https://github.com/freeCodeCamp/freeCodeCamp/pull/17471#issuecomment-395914805

2018-06-09 22:44 UTC, bogadodiegoh commented
Updated broken links with review suggestions.

2018-06-10 11:34 UTC, scissorsneedfoodtoo commented
@bogadodiegoh, thank you for making those changes! Everything looks great.

@raisedadead, this PR is ready to merge.

2018-06-10 23:46 UTC, merged

2018-06-10 23:46 UTC, scissorsneedfoodtoo commented
@bogadodiegoh, thank you for your contribution! :+1: :+1: :+1: We all look forward to your next PR!

@raisedadead, this one has been merged.