fix: removed unnecessary stripe call from boot sequence
freeCodeCamp/freeCodeCamp pull request #17526
Opened 2018-06-10 20:14 UTC by cmoss3

#### Pre-Submission Checklist

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

#### Type of Change

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

#### Checklist:

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #17510

#### Description

2018-06-12 08:56 UTC, Bouncey requested changes
Thanks @cmoss3 for your work on this. I think instead of leaving the setup of stripe to the first request to each server instance (we run more than one in production), we should still do the setup in the boot phase of the app. 

We can still use your `connectToStripe` function, but we should have it return a promise. Let me explain what I have in my head

```js

export default function donateBoot(app, done) {
  if (!stripeAPIKey) {
    if (NODE_ENV === 'production') {
      throw new Error('Stripe API keys required!');
      // if we are in production and have no keys, throw
    }
    console.info('No Stripe API keys found, this can be safely ignored in development';);
    return done();
    // if we don't have an API Key, we don't setup the donate routes, this is OK for development
  }
  // ... setup route handlers and routers, then...
  connectToStripe().then(done);
}
```

I hope this makes sense.

2018-06-13 21:50 UTC, cmoss3 commented
Hey @Bouncey, I updated the PR with the changes you mentioned.  I did make the connectToStripe function return a promise but it's setup so that the "done" function will be called before there is a response from the Stripe API, but after the requests were made. I hope that's what you expected, if not just let me know.

Also, still haven't been able to test the /external/donate/charge-stripe API. I did try testing it with Postman but I was a bit confused on what parameters should be passed and also I think I need to be logged in to get a valid JWT.

2018-06-15 11:57 UTC, Bouncey requested changes
Thanks for working on this @cmoss3, you have introduced some extra whitespace in this file.

VS Code does this to me sometimes also. please convert them back to spaces (2).

2018-06-15 11:57 UTC, Bouncey commented on server/boot/donate.js
> +export default function(app, done) {
`export default function donateBoot(app, done) {`

2018-06-15 11:57 UTC, Bouncey commented on server/boot/donate.js
> +    const secretInvalid = keys.stripe.secret === 'sk_from_stipe_dashboard';
We should check to see if we have keys as well. 

```js
const secretInvalid = !keys.stripe.secret || keys.stripe.secret === 'sk_from_stipe_dashboard';
const publicInvalid = !keys.stripe.public || keys.stripe.public === 'pk_from_stipe_dashboard';
```

2018-06-15 22:29 UTC, cmoss3 commented
Hrm, seems like the build is running into some linting error. 
Locally I ran `npm run test`, `npm run lint` and `npm run lint-js` none of which produced any errors.
Any suggestions?

2018-06-18 12:04 UTC, cmoss3 commented
Yikes, had to update one more time because I forgot to name the export function. O_O'

@Bouncey These changes are done though. Looks like there's still some issues with the build but all tests are passing locally.

2018-06-18 12:16 UTC, Nirajn2311 commented
@cmoss3 the linking error will be fixed once #17609 is merged. It is caused due to wrong location of eslint when the command gets executed.

2018-06-18 14:46 UTC, Bouncey approved these changes
Awesome! Thanks @cmoss3

2018-06-18 14:47 UTC, merged