<!-- freeCodeCamp Pull Request Template -->
freeCodeCamp/freeCodeCamp pull request #17630
Opened 2018-06-19 06:33 UTC by raisedadead

- [ ] Your pull request targets the `staging` branch of freeCodeCamp.
- [ ] Branch starts with either `fix/`, `feature/`, or `translate/` (e.g. `fix/signin-issue`)
- [ ] You have only one commit (if not, [squash](http://forum.freecodecamp.org/t/how-to-squash-multiple-commits-into-one-with-git/13231) them into one commit).
- [ ] All new and existing tests pass the command `npm test`. Use `git commit --amend` to amend any fixes.

- [ ] Small bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would change existing functionality)
- [ ] Add new translation (feature adding new translations)

- [ ] Tested changes locally.
- [ ] Addressed currently open issue (replace XXXXX with an issue no in next line)

Closes #XXXXX

2018-06-21 12:11 UTC, Bouncey requested changes
There is an issue where, if I change my email then visit `/` without verifying, I get redirected to `/update-email` asking me to verify my old email

The UI of the email form doesn't make any sense now that I am looking at it. I will add a picture with some improvements.

2018-06-21 12:12 UTC, Bouncey commented
Current Email should be in a `<p>` or `<span>`, or something just as uneditable. 

![email](https://user-images.githubusercontent.com/18572518/41718379-ac7ddb00-7554-11e8-8208-6a6c2571dce9.png)

2018-06-21 13:35 UTC, raisedadead commented
The other issue will be resolved with https://github.com/freeCodeCamp/freeCodeCamp/pull/17669

2018-06-21 13:36 UTC, raisedadead commented
Regarding the UI. I think I am not an expert at the moment. But will give it a quick try. I just added back the original views that we commented previously.

2018-06-26 14:48 UTC, Bouncey requested changes
Updating my email changes my current email on the page. 

I have provided setups to fix this :+1:

2018-06-26 14:48 UTC, Bouncey commented on common/app/routes/Settings/components/Email-Settings.jsx
> +          <EmailForm
```jsx
<EmailForm
  email={ email }
  initialValues={{ email, confirmEmail: '' }}
/>
```

2018-06-26 14:48 UTC, Bouncey commented on common/app/routes/Settings/components/EmailForm.jsx
> +              { email.value }
`{ this.props.email }`

Unless you want to de-structure it at Line 72

2018-06-28 09:27 UTC, Bouncey approved these changes

2018-06-28 09:28 UTC, merged