chore: housekeeping on things that we dont want
freeCodeCamp/freeCodeCamp pull request #17747
Opened 2018-06-28 15:34 UTC by raisedadead

2018-06-28 17:44 UTC, Bouncey requested changes
Will this also get rid of the optimizely cookies?

2018-06-28 17:44 UTC, Bouncey commented on webpack.config.js
>      'loop-protect': 'loopProtect'
We are no using `loop-protect` any more

2018-06-28 18:45 UTC, raisedadead commented on webpack.config.js
>      'loop-protect': 'loopProtect'
I know. The PR is WIP

2018-06-28 18:46 UTC, raisedadead commented
> Will this also get rid of the optimizely cookies?

Not the ones already set in the browser. New will not be added.

2018-06-30 14:08 UTC, raisedadead commented
#### Please rebase and merge in case we want to revert a specific commit

2018-07-02 08:25 UTC, Bouncey requested changes
We could also remove the build step for `frame-runner` in the gulp file and the `webpack.frame-runner.js`

2018-08-02 15:28 UTC, QuincyLarson commented
@raisedadead This all looks good. It needs to be tested. @Bouncey when you get a moment could you deploy this to freecodecamp.rocks and we can verify over time that it doesn't seem to have broken anything?

2018-08-04 12:26 UTC, sittirac1234 approved these changes

2018-08-04 21:48 UTC, Bouncey approved these changes

2018-08-04 21:48 UTC, merged