Make russian translate little better
freeCodeCamp/freeCodeCamp pull request #18530
Opened 2018-10-12 17:42 UTC by Shtihl

Make russian translate for add-a-text-alternative-to-images-for-visually-impaired-accessibility.russian.md little better and more russian

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request addresses a currently open issue, replace the XXXXX below with that issue number.

Closes #XXXXX

2018-10-27 11:27 UTC, greggubarev requested changes
Need to improve translate: localeTitle and at 11 line

2018-10-29 10:38 UTC, greggubarev approved these changes

2018-11-03 16:56 UTC, greggubarev submitted a review, later dismissed
Please imrpove translate at line 14

2018-11-04 23:55 UTC, merged

2018-11-04 23:56 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉