Added brief explanation of the keywords mentioned.
freeCodeCamp/freeCodeCamp pull request #18598
Opened 2018-10-12 20:48 UTC by mathur619

an example of "initial" is also added .

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-12 20:59 UTC, ArielLeslie commented
I'm not sure that the example html code adds value. At the very least it should be formatted nicer. The note that percentage and pixel values can also be used is now pushed down below that html code rather than being with the actual css.

2018-10-15 17:57 UTC, tchaffee requested changes

2018-10-15 17:57 UTC, tchaffee commented on client/src/pages/guide/english/css/background-size/index.md
> +.auto {background-size: auto;} <!-- The background image is displayed in its original size -->
```<!--``` is not a valid comment in CSS. You must use ```/*``` and ```*/``` to begin and end comments in CSS.

2018-10-17 11:06 UTC, Bouncey commented
@mathur619 Thanks for taking the time to create this pull request. As stated above, I don't believe the extra `html` adds anything to the document.

A note for future contributions, you added `html` to a `css` code block. It would be better to either open a second code block for the `html`, or convert the existing code block to `html` and wrap the `css` in a `<style>` block.

Happy coding! 👍

2018-10-17 11:06 UTC, closed without merging