fix: update tests for difference on two sets
freeCodeCamp/freeCodeCamp pull request #18698
Opened 2018-10-13 06:45 UTC by cazyw

Fix the test strings to run the functions as the challenge currently passes without any code changes

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

Is related to #17815

2018-10-13 16:18 UTC, cazyw commented
Is also related to #17856

2018-10-13 16:53 UTC, cazyw commented
Updated the non-English challenge tests (for the difference of two sets challenge and the intersection of two sets challenge)

2018-10-25 07:39 UTC, raisedadead commented
Hey @Bouncey @ValeraS this is one of the examples where the tests are timing out. I pulled down the PR and could reproduce this locally.

2018-10-25 07:57 UTC, ValeraS commented
@raisedadead  I've made new PR #28296, it should work without these errors.

2018-10-25 08:28 UTC, ValeraS commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/perform-a-difference-on-two-sets-of-data.english.md
> +    testString: 'assert((function(){var setA = new Set(); var setB = new Set(); setA.add("a"); setA.add("b"); setA.add("c"); setB.add("c"); setB.add("d"); var differenceSetAB = setA.difference(setB);
This string transforms into incorrect js string. Because of this, the test fails. You need to set quotes as in the source file.

2018-10-25 08:56 UTC, ValeraS requested changes

2018-10-25 08:56 UTC, ValeraS commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/perform-an-intersection-on-two-sets-of-data.english.md
> +    testString: 'assert((function(){  var setA = new Set();  var setB = new Set();  setA.add("a");  setA.add("b");  setA.add("c");  setB.add("c");  setB.add("d");  var intersectionSetAB = setA.inters
the same as above

2018-11-29 11:36 UTC, Bouncey commented
@cazyw Is there any update on this?

2018-12-03 12:40 UTC, cazyw commented
Hi, sorry I've made some edits to the file (fixed the test check so the solution passes)

2018-12-11 13:48 UTC, QuincyLarson commented
@cazyw Thanks for making all these improvements. As I mentioned on #18700 a moment ago:

We are planning tools to help the maintainers of other languages sync their tests and seed code with the other language versions, so that changes to one language (such as your improvements to the English language version) can propagate to other languages, too.

In this case, it sounds like these changes you've made are ready to be merged. Instead of merging this PR, could you open a new PR with just the changes to the English language files? Then we can merge that. I will go ahead and close this current PR.

Then once we've finished our tool, we'll be able to highlight these differences and the maintainers of the other languages will be able to look at them and decide whether to merge them into those languages as well.

2018-12-11 13:48 UTC, closed without merging

2018-12-12 14:11 UTC, cazyw commented
ok thanks, will do