Added solution to Use the Lifecycle Method componentWillMount
freeCodeCamp/freeCodeCamp pull request #18745
Opened 2018-10-13 10:51 UTC by thecodingaviator

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-15 18:12 UTC, tchaffee requested changes

2018-10-15 18:12 UTC, tchaffee commented on client/src/pages/guide/english/certifications/front-end-libraries/react/use-the-lifecycle-method-componentwillmount/index.md
> +The challenge is a basic introduction to React's LifeCycle components. Thhis challenge is set with the motive of introducing the ``` componentWillMount ``` Life Cycle method of React's.
The English grammar needs to be improved.

2018-10-15 18:12 UTC, tchaffee commented on client/src/pages/guide/english/certifications/front-end-libraries/react/use-the-lifecycle-method-componentwillmount/index.md
> +Since you can log anything, use the ```javascript console.log(); ``` and pass in a string. The ``` componentWillMount ``` methos should look like:
Please change ```javascript console.log();``` to:

JavaScript ```console.log```

2018-10-15 18:12 UTC, tchaffee commented on client/src/pages/guide/english/certifications/front-end-libraries/react/use-the-lifecycle-method-componentwillmount/index.md
> +Since you can log anything, use the ```javascript console.log(); ``` and pass in a string. The ``` componentWillMount ``` methos should look like:
Please fix spelling errors.

2018-10-15 18:12 UTC, tchaffee commented on client/src/pages/guide/english/certifications/front-end-libraries/react/use-the-lifecycle-method-componentwillmount/index.md
> +  console.log("Component being mounted");
Please use single quotes for JavaScript strings.

2018-10-16 08:34 UTC, thecodingaviator commented
@tchaffee I have created a new PR at #19452 to fix this PR as the original branch for this PR was deleted so no changes can be made.

2018-10-16 08:34 UTC, closed without merging