Created guide for Docker pull command.
freeCodeCamp/freeCodeCamp pull request #18779
Opened 2018-10-13 12:48 UTC by beawolf

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-13 23:42 UTC, jonathan-grah requested changes

2018-10-13 23:42 UTC, jonathan-grah commented on client/src/pages/guide/english/docker/docker-pull/index.md
> +#### For More Information:
Would you mind changing this to `#### More Information:`? Sorry, just to keep the subheadings consistent.

2018-10-14 08:10 UTC, mustafacagataytulun reviewed
Sure thing. I made the required change.

2018-10-15 15:56 UTC, jonathan-grah approved these changes

2018-10-15 16:00 UTC, jonathan-grah commented
Thanks for the contribution @beawolf 😃 Happy Hacktoberfest!

2018-10-15 16:00 UTC, merged