Add hints to three front-end-libraries certification projects
freeCodeCamp/freeCodeCamp pull request #18938
Opened 2018-10-14 01:12 UTC by MikeBudimon

- Add hints to the front-end-libraries - build a markdown-previewer project
- Add hints to the front-end-libraries - build a drum machine
- Add hints to the front-end-libraries - build a pomodoro clock

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

2018-10-14 02:00 UTC, RandellDawson requested changes
Under the Build a Drum Machine hints, the example code part should be avoided, because depending on whether the user uses vanilla JS, jQuery, or React, the code could be different.

2018-10-14 13:36 UTC, MikeBudimon commented
Should I remove the example code or it would be fine to say that the following code could look like this using vanilla JS?

2018-10-15 01:47 UTC, RandellDawson commented
I think example code should be avoided.  They can always look at the example project for code ideas.

2018-10-15 01:51 UTC, RandellDawson approved these changes

2018-10-15 01:56 UTC, merged