fix(coding):  update instructions to CSS Flexbox challenge in Portuguese
freeCodeCamp/freeCodeCamp pull request #19077
Opened 2018-10-14 14:06 UTC by brenoxav

Change the positions of some words to be in accordance with the syntax rules of the Portuguese language.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-24 13:54 UTC, frontendwizard requested changes

2018-10-24 13:54 UTC, thefrontendwizard commented on curriculum/challenges/portuguese/01-responsive-web-design/css-flexbox/use-the-flex-shorthand-property.portuguese.md
> +Por exemplo, <code>flex: 1 0 10px;</code> irá definir o item para <code>flex-grow: 1;</code> <code>flex-shrink: 0;</code> e <code>flex-basis: 10px;</code> .
Remove line break.

2018-10-24 13:54 UTC, thefrontendwizard commented on curriculum/challenges/portuguese/01-responsive-web-design/css-flexbox/use-the-flex-shorthand-property.portuguese.md
> +As configurações padrão da propriedade são <code>flex: 0 1 auto;</code> . </section>
Remove line break.

2018-10-24 13:54 UTC, thefrontendwizard commented on curriculum/challenges/portuguese/01-responsive-web-design/css-flexbox/use-the-flex-shorthand-property.portuguese.md
> +Esses valores farão com que <code>#box-1</code> cresça para preencher o espaço extra com o dobro da taxa de <code>#box-2</code> quando o container for maior que 300px e encolherá com o dobro da taxa
Remove line break.

2018-11-14 21:43 UTC, lynxlynxlynx commented
@thefrontendwizard markdown doesn't care about those newlines, but they do improve readability of the source.

See for example the rendered output comparison — the newlines got eaten up: https://github.com/freeCodeCamp/freeCodeCamp/pull/19077/files?short_path=722e456#diff-722e456cb1a96bf49df457120e39683e

2019-02-10 16:30 UTC, RandellDawson commented
@lynxlynxlynx Would you merge this PR?

2019-02-10 16:52 UTC, lynxlynxlynx commented
Yes, it looks fine to me.

2019-02-10 16:52 UTC, lynxlynxlynx approved these changes

2019-02-20 14:14 UTC, merged

2024-04-02 11:39 UTC, Briseno00 reviewed
Nueva configuracion de roles

2025-04-20 10:52 UTC, lynxlynxlynx commented
If you want to suggest changes to the current Portuguese text, please submit a new pull request with them — this here is not the right place.

2025-04-20 11:29 UTC, ilenia-magoni commented
@lynxlynxlynx @Prisca1260 please do not translate through GitHub, translations are done through Crowdin