fix(coding):  update instructions to CSS Flexbox challenge in Portuguese
freeCodeCamp/freeCodeCamp pull request #19073
Opened 2018-10-14 13:54 UTC by brenoxav

Change the positions of some words to be in accordance with the syntax rules of the Portuguese language.
Change some translated words back to English for clarity of the instructions.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-24 13:38 UTC, frontendwizard requested changes

2018-10-24 13:38 UTC, thefrontendwizard commented on curriculum/challenges/portuguese/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-row.portuguese.md
> +Outras opções para <code>flex-direction</code> são  <code>row-reverse</code> (linha reversa) e <code>column-reverse</code> (coluna reversa).
Please try to follow the same formatting of the previous translation. Don't break the line when there's no line break previously.

2018-10-24 13:50 UTC, frontendwizard requested changes

2018-10-24 13:50 UTC, thefrontendwizard commented on curriculum/challenges/portuguese/01-responsive-web-design/css-flexbox/use-the-flex-direction-property-to-make-a-row.portuguese.md
> +<strong>Nota</strong> <br> O valor padrão da propriedade <code>flex-direction</code> é <code>row</code>. </section>
Remove line break.

2019-02-10 16:29 UTC, RandellDawson commented
@thefrontendwizard At this point, I think we should either close this PR due to it being stale or just remove the added line breaks if that is the only thing wrong with this challenge.

2019-02-20 14:09 UTC, thefrontendwizard commented
I'll remove the line breaks and merge it in.

2019-02-20 14:12 UTC, thefrontendwizard commented
I don't have push access to the branch. I'll close this one.

2019-02-20 14:12 UTC, closed without merging