fix: Add a build test to check all file names are in lower case
freeCodeCamp/freeCodeCamp pull request #19104
Opened 2018-10-14 16:34 UTC by Sathish-kumar-Subramani

fixes issue #18325

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #18325

2018-10-14 17:50 UTC, lynxlynxlynx commented on client/package.json
> +    "test": "sh check-file-name.sh && jest"
this should be bash explicitly, since you rely on its syntax.

2018-10-14 18:00 UTC, lynxlynxlynx requested changes

2018-10-14 18:00 UTC, lynxlynxlynx commented on client/check-file-name.sh
> +    echo "${no} file(s) are in upper case. Please rename files to lower case."
For this to be more useful, rather save the find output, so you can present it here too.

2018-10-16 14:38 UTC, raisedadead requested changes
Hi @Sathish-kumar-Subramani 

We would like to test this in JavaScript instead of a shell script. Are you able to do so? If not, please close this PR.

Thanks.

2018-10-17 15:51 UTC, Sathish-kumar-Subramani commented
Hi @raisedadead 

Sure. I'll do with JS and update the pull request.
Can this wait until Saturday?

2018-10-20 14:02 UTC, raisedadead commented
Hi @Sathish-kumar-Subramani 

Someone already added the tests. Thanks for taking the time to contribute. We look forward to futire contributions.

Thanks.

2018-10-20 14:02 UTC, closed without merging