Fixed some typos and grammatical errors
freeCodeCamp/freeCodeCamp pull request #19573
Opened 2018-10-17 04:13 UTC by Catherinesjkim

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #18307

2018-10-22 22:56 UTC, tbushman requested changes

2018-10-22 22:56 UTC, tbushman commented on docs/spanish/how-to-work-on-guide-articles.md
> +    feat: Añadir articulo sobre JavaScript hosting
Whoever reviews this for translation -- this should remain as `hoisting`

2019-02-07 17:19 UTC, RandellDawson commented
@tbushman What is the status with this PR?

2019-02-07 17:25 UTC, tbushman commented
@RandellDawson Needs Spanish proofreading.

2019-04-28 01:37 UTC, yvette-chica requested changes
Good job correcting many errors! I noticed you changed a few second person informal (tú) imperative conjugations to second person formal (usted). I left comments where this happened.

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +3. 🔧 Propónga cambios asombrosos!
Most of this article is written using the second person informal (tú) grammatical person. I would continue using this to be consistent.

So, we should keep ***Propón***

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +4. 📖 Lea la [guía de buenas prácticas de estilo](/docs/style-guide-for-guide-articles).
Keep ***Lee***

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +Mira este video de demostración o sigue los siguientes pasos:
Mira este ***vídeo***

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +1. Vea las carpetas **"páginas"** (situado en [`guide`](/guide)) donde encontrarás el artículo raiz que quieras editar.
***Ve***

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +    > Si el icono aparece gris y te muestra la alerta "Debes estar en una rama para hacer o proponer cambios a este archivo", significa que probablemente estas en la rama de otra persona. En la parte
probablemente ***estás*** en la rama

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +    Sea breve, no más de 50 caracteres. Puedes añadir información extra en la descripción del mensaje.
***Sé***

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +Felicitaciones 🎉! Acabas de crear una pull request.
***un*** pull request

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +##### Lea sobre estas recomendaciones en [Cómo configurar freeCodeCamp localmente](/docs/how-to-setup-freecodecamp-locally.md)
***Lee*** sobre estas recomendaciones

2019-04-28 01:37 UTC, yvette-chica commented on docs/spanish/how-to-work-on-guide-articles.md
> +Si la Pull Request no es perfecta el revisor podría:
Si ***el*** Pull Request

2019-05-11 07:47 UTC, tomaspozo commented
This is a very old PR and there are several typos which are fixed on the latest version of the file.

2019-05-11 07:47 UTC, closed without merging