[Russian] Responsive Web Design: Improve translate
freeCodeCamp/freeCodeCamp pull request #19650
Opened 2018-10-17 18:47 UTC by greggubarev

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-17 22:49 UTC, RandellDawson requested changes
Can you also translate the testString parts between the " ".  For example:
```
"Your code should have one <code>main</code> tag."
```
and 
```
"The <code>main</code> tags should be between the closing <code>header</code> tag and the opening <code>footer</code> tag."
```

2018-10-18 08:47 UTC, greggubarev commented
@RandellDawson done

2018-10-18 17:10 UTC, RandellDawson requested changes

2018-10-18 17:10 UTC, RandellDawson commented on curriculum/challenges/russian/01-responsive-web-design/applied-accessibility/jump-straight-to-the-content-using-the-main-element.russian.md
> +    testString: 'assert(code.match(/<\/header>\s*?<main>\s*?<\/main>/gi), "The <code>main</code> теги должны быть между закрывающем тегом <code>header</code> и открывающим тегом <code>footer</code>."
On line 23, I still see the word "The".

2018-10-29 10:20 UTC, merged