Redaction and translation updated.
freeCodeCamp/freeCodeCamp pull request #19761
Opened 2018-10-18 13:48 UTC by Josev47

Enhanced redaction and translation, made a better explanation to enhance the understanding about the description, the instructions, the tests and the challenge seed.

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x ] None of my changes are plagiarized from another source without proper attribution.
- [ x ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-25 19:15 UTC, lynxlynxlynx requested changes

2018-11-25 19:15 UTC, lynxlynxlynx commented on curriculum/challenges/spanish/01-responsive-web-design/basic-css/use-a-css-class-to-style-an-element.spanish.md
> +<h2 class="red-text">CatPhotoApp</h2>
this change is wrong, it's up to the user to solve the challenge, not us.

2019-02-14 17:27 UTC, RandellDawson commented
@raisedadead It appears this PR is attempting to add more content to this challenge, instead of just a direct translation of the challenge.  

I believe we need to have new additions only come from the English version first and then we create translations (automatically using the bot) and also auto-create PRs for each language which would go through the normal PR review process.

If I am mistaken, please let me know.

2019-02-14 21:41 UTC, lynxlynxlynx commented
There's no new content here, just the common mistake of adding the solution to the seed.

2019-02-14 21:45 UTC, RandellDawson commented
@lynxlynxlynx Sorry about that.  It appeared there was additions to the description section, but it appears those were just translations.  I think I may have mixed this one up with another PR.

2019-03-13 18:02 UTC, merged

2019-03-13 18:03 UTC, lynxlynxlynx commented
Thanks, I've fixed the remaining issues.