Correções do código apresentado
freeCodeCamp/freeCodeCamp pull request #19937
Opened 2018-10-18 18:20 UTC by EduardoAirton

Identação do código apresentado em JavaScript para melhor entendimento além de algumas correções e tradução do termo First In First Out para quem não fala inglês ter uma melhor noção do conceito.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-28 11:06 UTC, jeffersonataide requested changes
Bacana a iniciativa, mas de uma conferida na identação da versao em ingles como referencia (declarar uma variavel por linha).

Algumas variaveis foram ainda declaradas em ingles, e usadas em portugues, e vice versa. Tente corrigir para manter uniforme, caso contrario o codigo gera erros.

2018-10-29 17:29 UTC, EduardoAirton commented
Código Corrigido!

2018-10-30 09:14 UTC, jeffersonataide approved these changes

2018-11-08 09:57 UTC, RandellDawson commented
This PR was closed and then re-opened in an attempt to clear a specific Travis build failure.

2018-11-08 10:10 UTC, merged

2018-11-08 10:10 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉