Added examples and definition - CSS
freeCodeCamp/freeCodeCamp pull request #20066
Opened 2018-10-18 19:05 UTC by chef-danny-d

- added two examples with the most used values
- added definition

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-26 14:20 UTC, b3u commented
LGTM
BTW, use one backtick instead of three for inline code. "(```initial``` vs. `initial`)

2018-10-26 15:33 UTC, chef-danny-d commented
@b3u appreceat it!!! changed it to single ticks.

2018-10-28 03:07 UTC, huyenltnguyen requested changes

2018-10-28 03:07 UTC, huyenltnguyen commented on guide/english/css/graceful-degradation/index.md
> +[Online CSS linter](http://csslint.net/)
This website is not supporting `https`, which is not conform with the [freeCodeCamp's Style Guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#links). Please remove it from your changes.

2018-10-31 00:07 UTC, huyenltnguyen approved these changes

2018-11-01 05:51 UTC, huyenltnguyen commented
Hi @chef-danny-d, thank you for the PR!

I really appreciate your effort to improve the article. I'm merging your PR now.

Congratulations on your first contribution to this repo ✨ 🎉 We look forward to your next.

Happy coding!

2018-11-01 05:51 UTC, merged