Added some info
freeCodeCamp/freeCodeCamp pull request #20123
Opened 2018-10-18 19:23 UTC by allenpbiju

Some information has been added on how to define a function after the main program.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-28 08:59 UTC, Manish-Giri requested changes
This topic is already covered earlier in the guide in the "An example" section.

To maintain the flow, please add your code sample in that section, before this line -

> With that in mind, let's go over the first line in a function in our next section, titled:

2018-10-30 16:20 UTC, allenpbiju reviewed
Reviewed and good to go.

2018-11-02 15:06 UTC, Nirajn2311 commented
Hey @username

You haven't actually added any content so I will be invalid pull requests this PR and marking it as `invalid`. 😓️

Feel free to open another PR though! 👍

2018-11-04 01:14 UTC, Manish-Giri approved these changes

2018-11-04 01:14 UTC, merged