Edited text under "### Remove multple images"
freeCodeCamp/freeCodeCamp pull request #20191
Opened 2018-10-18 19:41 UTC by Ellyshachavez

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-28 09:10 UTC, Manish-Giri requested changes
Suggested improvements to be addressed.

2018-10-28 09:10 UTC, Manish-Giri commented on guide/english/docker/docker-rmi/index.md
> +You may remove multiple images at the same time. First thing you will want to do is, get the Image IDs simply by listing the images then execute a simple followed command.
```suggestion
You may remove multiple images at the same time. The first thing you will want to do is, get the Image IDs simply by listing the images, then execute the following command: 
```

2018-11-04 01:24 UTC, Nirajn2311 approved these changes

2018-11-04 01:43 UTC, Manish-Giri approved these changes
Hi @Ellyshachavez,

Thank you for your contribution to the page! 👍

We're happy to accept these changes and look forward to future contributions. 🎉

2018-11-04 01:43 UTC, merged