cleanup html input docs
freeCodeCamp/freeCodeCamp pull request #20241
Opened 2018-10-18 19:56 UTC by andrew-anguiano

- General cleanup and editing
- Add types section
- Tweak example code
- Remove old YouTube link

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

2018-10-28 08:12 UTC, huyenltnguyen requested changes

2018-10-28 08:12 UTC, huyenltnguyen commented on guide/english/html/attributes/input/index.md
> +# Input
Please change the heading back to `##`. 
You can use this page for reference: https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/css/borders/index.md. Click on the <kbd>Raw</kbd> button if you want to see its markdown.

2018-10-28 08:12 UTC, huyenltnguyen commented on guide/english/html/attributes/input/index.md
>  ## Example
I know this is not your change, but while you are at it, I hope you don't mind changing this to `###`.

2018-10-28 08:12 UTC, huyenltnguyen commented on guide/english/html/attributes/input/index.md
> +## Types
Please change this to `###` as well.

2018-10-28 08:12 UTC, huyenltnguyen commented on guide/english/html/attributes/input/index.md
> +- **Radio**
Please add an explanation for the `Checkbox` and `Radio`.

2018-10-28 18:19 UTC, andrew-anguiano commented
@huyenltnguyen made the changes you requested. Let me know if you need anything else!

2018-10-29 02:56 UTC, huyenltnguyen approved these changes
LGTM 👍

@andrew-anguiano Thank you for the additional changes and for your PR! 

I will merge this as soon as the Travis build completes.

Congratulations on your first contribution to this repo ✨ 🎉 We look forward to your next!

Happy coding!

2018-10-29 06:42 UTC, merged