Added reference video on conference speaking
freeCodeCamp/freeCodeCamp pull request #20322
Opened 2018-10-18 20:17 UTC by smorgie

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-29 05:05 UTC, Manish-Giri requested changes
H @smorgie,

Please review the [style guide for guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md) for the right way to create and style links in guide articles. 

Also, please use `#### More Information` instead of `## References`. Thanks!

2018-10-29 14:08 UTC, smorgie commented
Thanks! I updated my reference per your corrections.

2018-11-01 02:12 UTC, Manish-Giri approved these changes

2018-11-02 21:13 UTC, merged

2018-11-02 21:14 UTC, Manish-Giri reviewed
Hi @smorgie ,

Thank you for your contribution to the page! 👍

We're happy to accept these changes, and look forward to future contributions. 🎉