Improve russian translation in challenge
freeCodeCamp/freeCodeCamp pull request #20506
Opened 2018-10-18 21:17 UTC by plxel

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

This PR only contains language translation enhancements.

2018-10-28 10:11 UTC, greggubarev requested changes
@plxel please add translated text in tests. Thank you for helping!

2018-10-28 11:06 UTC, plxel commented
@greggubarev fixed

2018-10-28 11:43 UTC, greggubarev approved these changes

2018-10-29 10:30 UTC, greggubarev commented
LGTM

2018-10-29 10:30 UTC, merged