add the text "15.sudo"
freeCodeCamp/freeCodeCamp pull request #20745
Opened 2018-10-18 22:28 UTC by dr0017

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-02 19:18 UTC, nikrb requested changes

2018-11-02 19:18 UTC, nikrb commented on guide/english/linux/basic-linux-commands/index.md
> +15. sudo — A widely used command in the Linux command line, sudo stands for "SuperUser Do". So, if you want any command to be done with administrative or root privileges, you can use the sudo command
@dr0017 thanx for the pr.
Could you amend your update to match the existing format of the doc. e.g.:
```
15. **sudo** - execute a command as super user
- A widely used command ...
```

2018-11-03 12:33 UTC, Nirajn2311 approved these changes

2018-11-03 12:48 UTC, merged

2018-11-03 12:48 UTC, Nirajn2311 commented
Hi @dr0017 . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝