Updated code comments to portuguese
freeCodeCamp/freeCodeCamp pull request #20785
Opened 2018-10-18 22:45 UTC by CubeSkyy

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-02 13:17 UTC, jeffersonataide requested changes
Muito boas as modificações, apenas de uma olhada nos detalhes que eu comentei antes.

2018-11-02 13:17 UTC, jefferson2z commented on guide/portuguese/algorithms/graph-algorithms/dijkstra/index.md
> +        // Se o novo caminho u oferece menor custo, actualiza o vector de distancias e adiciona a pq
traduzir palavra vector

2018-11-02 13:17 UTC, jefferson2z commented on guide/portuguese/algorithms/graph-algorithms/dijkstra/index.md
> +    // Calcula o caminho mais curto para cada vertice apartir da fonte e retorna a distancia
acentos na palavra distância

2018-11-02 13:17 UTC, jefferson2z commented on guide/portuguese/algorithms/graph-algorithms/dijkstra/index.md
> +    int distance[] = new int[gn]; // Menor distancia de cada vertice da fonte
acento na palavra distância

2018-11-02 13:17 UTC, jefferson2z commented on guide/portuguese/algorithms/graph-algorithms/dijkstra/index.md
> +        Pair<Integer> x = pq.remove(); // Retira o vertice com menor distancia á fonte
acento na palavra vértice

2018-11-02 13:17 UTC, jefferson2z commented on guide/portuguese/algorithms/graph-algorithms/dijkstra/index.md
> +        Pair<Integer> x = pq.remove(); // Retira o vertice com menor distancia á fonte
"á" deveria ser a craseado ,i.e., "à"

2018-11-02 13:17 UTC, jefferson2z commented on guide/portuguese/algorithms/graph-algorithms/dijkstra/index.md
> +        // Itera sobre os visinhos de u e atualiza as suas distancias
acento na palavra distâncias

2018-11-02 13:17 UTC, jefferson2z commented on guide/portuguese/algorithms/graph-algorithms/dijkstra/index.md
> +        // Verifica se vertice v não foi visitado
acento na palavra vértice

2018-11-03 13:45 UTC, jefferson2z commented
Thanks for your contribution and congratulations for your first PR merge to this repo! :smiley_cat:

2018-11-03 13:46 UTC, jeffersonataide approved these changes

2018-11-03 13:46 UTC, merged