Example of how to use Number in Typescript
freeCodeCamp/freeCodeCamp pull request #20802
Opened 2018-10-18 22:52 UTC by Coldplayer1995

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-13 18:41 UTC, amandeepmittal approved these changes

2018-11-13 20:51 UTC, itaisteinherz commented on guide/english/typescript/number-type/index.md
> +Example of usage Number type in typescript:
```suggestion
Example usage of the type `Number` in TypeScript:
```

2018-11-13 20:52 UTC, itaisteinherz requested changes
This looks good. My only suggestion other than my comment is to properly format and indent the code, in order for it to be more readable.

2018-11-14 16:38 UTC, itaisteinherz commented on guide/english/typescript/number-type/index.md
> +class Employee extends Person{
```suggestion
class Employee extends Person {
```

2018-11-14 16:39 UTC, itaisteinherz commented on guide/english/typescript/number-type/index.md
> +  age:Number;
```suggestion
  age: Number;
```

2018-11-14 16:40 UTC, itaisteinherz commented on guide/english/typescript/number-type/index.md
> +  constructor(age : Number){
```suggestion
  constructor(age: Number) {
```

2018-11-14 16:40 UTC, itaisteinherz commented on guide/english/typescript/number-type/index.md
> +    //calling constructor of Person
```suggestion
    // Run when an object of type `Person` is created
```

2018-11-14 16:41 UTC, itaisteinherz commented on guide/english/typescript/number-type/index.md
> +  getAge(): Number{
```suggestion
  getAge(): Number {
```

2018-11-14 16:42 UTC, itaisteinherz requested changes
@cmccormack I've added a few more suggestions to further improve the code quality.

2018-11-15 01:39 UTC, cmccormack commented
This looks good to me.  Thank you for your contribution!

2018-11-15 01:39 UTC, merged