Fixed grammar issues to help readability
freeCodeCamp/freeCodeCamp pull request #21144
Opened 2018-10-19 01:14 UTC by jhoard08

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-07 20:35 UTC, jonathan-grah requested changes
Would you mind also changing the folder name to `loops`?

Thanks

2018-11-07 20:35 UTC, jonathan-grah commented on guide/english/php/loop/index.md
> +When you need to repeat task for multiple times, you can use a loop instead of adding the same code over and over again.
```suggestion
When you need to repeat a task multiple times, you can use a loop instead of adding the same code over and over again.
```

2018-12-28 19:10 UTC, RandellDawson commented
@jonathan-grah I made the changes you requested on behalf of the user with the exception of changing the folder from `loop` to `loops` and resolved all the merge conflicts.  Since the majority of the content for Loops is already in the loop directory, maybe we should merge this one in the loop directory and then I will create a separate PR which replaces the existing `index.md` in the loops folder with this `index.md`.  The loops `index.md` does not have much info in it, so this should not be a problem.  If you agree, please merge this one and let me know and I will create the other PR.

Once you merge this one, there are two other existing PRs (# and #31136) for this same file which I have already reviewed/approved which I will merge before I create the new PR.

Thanks.

2018-12-29 21:24 UTC, jonathan-grah approved these changes

2018-12-29 21:24 UTC, merged