Fix some bugs on the translation
freeCodeCamp/freeCodeCamp pull request #21196
Opened 2018-10-19 01:37 UTC by rogervieiraa

Corrigidas algumas linhas que não são otimizadas.

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

2019-05-17 05:49 UTC, thecodingaviator commented
@freeCodeCamp/portuguese-language-editors please have a look and review

2019-08-08 18:06 UTC, CleoAguiar requested changes
@rogervieiraa agradecemos o PR. Por favor, verifique a tradução dos subtítulos e texto. Também seria bom corrigir os algoritmos, você pode usar o [guia](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/guide/english/cplusplus/vector/index.md) em inglês como referência caso tenha alguma dúvida nos códigos.

2019-08-09 20:26 UTC, rogervieiraa commented
Eu acidentalmenet deletei minha branch, consegue me ajudar em como eu consigo reabrir essa PR branch? @CleoAguiar

2019-08-09 20:32 UTC, RandellDawson commented
@rogervieiraa If you have already deleted the branch locally and on GitHub, the only thing you can do is create a new PR.  However, we are really not accepting new PRs for translations now.

2019-08-22 11:56 UTC, closed without merging