Fixed typos, changed wording index.md
freeCodeCamp/freeCodeCamp pull request #21461
Opened 2018-10-19 03:47 UTC by evanjfarmer

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-04 12:29 UTC, Manish-Giri requested changes
Hi @evanjfarmer,

Please address the suggested change.

2018-11-04 12:29 UTC, Manish-Giri commented on guide/english/working-in-tech/imposter-syndrome/index.md
> +If you suffer from imposter syndrome you may have a sense of inadequacy or insecurity about your ability to contribute.
```suggestion
If you suffer from imposter syndrome you may have a sense of inadequacy or insecurity about your ability to contribute. In reality, you may be perfectly capable and do contribute to your tasks.
```

Your changes are good, but let's not delete this line.

2018-11-04 13:01 UTC, chefsaroar approved these changes

2018-11-17 04:06 UTC, Manish-Giri approved these changes

2018-11-17 04:06 UTC, Manish-Giri approved these changes
Hi @evanjfarmer ,

Thank you for your contribution to the page! 👍

We're happy to accept these changes and look forward to future contributions. 🎉

2018-11-17 04:06 UTC, merged