Update index.md
freeCodeCamp/freeCodeCamp pull request #21719
Opened 2018-10-19 05:54 UTC by bibin-johny

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-19 08:36 UTC, Nirajn2311 requested changes

2018-10-19 08:36 UTC, Nirajn2311 commented on guide/english/computer-science/data-structures/linked-lists/index.md
> +If you want to understand Linked Lists, is necessary to understand **Arrays**.
```suggestion
If you want to understand Linked Lists, it is necessary to understand **Arrays**.
```

2018-11-12 15:01 UTC, Nirajn2311 approved these changes

2018-11-15 14:03 UTC, moT01 commented
Thank you for opening this pull request.
This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.
Thank you and happy coding.

2018-11-15 14:03 UTC, closed without merging