added article for this stub
freeCodeCamp/freeCodeCamp pull request #21818
Opened 2018-10-19 06:25 UTC by takachou

added 3 ways for full page background image

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-16 17:29 UTC, thecodingaviator requested changes
Try to never use personal links, do not keep the html and css blocks apart, put the css in a `<style>` tag, and use the language i.e. html in this case after the three back tick characters. like ```html

2018-11-17 16:50 UTC, cmccormack approved these changes
These changes look good; conflict resolution will need to be performed and then we can merge.

2018-11-17 16:50 UTC, cmccormack commented on guide/english/css/tutorials/perfect-full-page-background-image/index.md
> +see <a href="https://codepen.io/takachou/pen/gBzRwK">codepen for solution 2</a>
Please use github markdown style [links](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#links)

2018-11-17 16:50 UTC, cmccormack commented on guide/english/css/tutorials/perfect-full-page-background-image/index.md
> +see <a href="https://codepen.io/takachou/pen/bmMRgz">codepen for solution 3</a>
Please use github markdown style [links](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#links)

2018-11-17 16:50 UTC, cmccormack commented on guide/english/css/tutorials/perfect-full-page-background-image/index.md
>  <!-- Please add any articles you think might be helpful to read before writing the article -->
Can remove comments when filling out a stub

2018-11-17 17:23 UTC, merged