Fix markdown format
freeCodeCamp/freeCodeCamp pull request #21943
Opened 2018-10-19 07:11 UTC by Aingeru72

Markdown format was broken for instal examples.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

2019-05-14 08:11 UTC, thecodingaviator requested changes

2019-05-14 08:11 UTC, thecodingaviator commented on guide/spanish/angular/index.md
> +npm instalar angular
```suggestion
npm install angular
```

2019-06-03 23:07 UTC, RandellDawson commented
@thecodingaviator This PR has gone stale.

2019-06-06 07:41 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-06-06 07:41 UTC, closed without merging