Adicionar o texto "dicas para lot" no artigo
freeCodeCamp/freeCodeCamp pull request #22524
Opened 2018-10-19 11:38 UTC by xandechaves

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-08-13 11:45 UTC, CleoAguiar requested changes

2019-08-13 11:45 UTC, CleoAguiar commented on guide/portuguese/android-development/core-components/index.md
> +Colocar dicas para LOT
I suggest to remove this line.
```suggestion
Colocar dicas para LOT
```

2019-08-13 13:23 UTC, RandellDawson commented
@xandechaves Please make the suggested change which @CleoAguiar has suggested above.

Thank you.

2019-08-14 14:41 UTC, RandellDawson commented
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

2019-08-14 14:41 UTC, closed without merging