rename to variables_php.md
freeCodeCamp/freeCodeCamp pull request #22966
Opened 2018-10-19 15:04 UTC by serg-t

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

2018-10-23 11:09 UTC, Asjas submitted a review, later dismissed

2018-10-23 11:09 UTC, Asjas commented on guide/russian/php/PHP Variables/variables_php.md
> +---
Hi @serg-t 

Please change the folder name to be lowercase and to be separated with hyphens. Also change the filename back to `index.md`.

Then also use `code blocks` for any code examples you use in the article.

2018-11-25 18:46 UTC, RandellDawson commented
@greggubarev Can you review this one?

2018-11-26 14:11 UTC, greggubarev requested changes
@serg-t please add example from 8 line, and add markdown for highlighting code

2018-11-26 16:44 UTC, greggubarev approved these changes

2018-11-26 16:45 UTC, greggubarev approved these changes
LGTM 👍 :dart:

Thank you for the PR ✨ 🎉
 We're happy to accept these changes and look forward to your future contributions :clap:

Happy coding! :octocat:

2018-11-26 17:36 UTC, merged