fixed machine translation
freeCodeCamp/freeCodeCamp pull request #23779
Opened 2018-10-20 01:09 UTC by andrhua

not ideal though

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-23 18:55 UTC, greggubarev commented on guide/russian/typescript/getters-setters/index.md
> +TypeScript поддерживает свойства `get` и `set` . На самом деле они называются свойствами доступа (accessors). Аксессоры атрибута есть функции, связанные с получением (чтением, геттеры) или установкой
```suggestion
TypeScript поддерживает свойства `get` и `set` . На самом деле они называются свойствами доступа (accessors). Аксессоры атрибута есть функции, связанные с получением (чтением, геттеры) или установкой (записью, сеттеры) атрибута. Объявления класса могут содержать геттер и сеттер как вместе, так и поразнь.
```

2018-11-23 18:55 UTC, greggubarev requested changes
поразнь =>порознь plz

2018-11-23 18:55 UTC, greggubarev commented on guide/russian/typescript/getters-setters/index.md
> +TypeScript поддерживает свойства `get` и `set` . На самом деле они называются свойствами доступа (accessors). Аксессоры атрибута есть функции, связанные с получением (чтением, геттеры) или установкой
```suggestion
TypeScript поддерживает свойства `get` и `set` . На самом деле они называются свойствами доступа (accessors). Аксессоры атрибута есть функции, связанные с получением (чтением, геттеры) или установкой (записью, сеттеры) атрибута. Объявления класса могут содержать геттер и сеттер как вместе, так и поразнь.
```

2018-11-23 19:58 UTC, andrhua commented on guide/russian/typescript/getters-setters/index.md
> +TypeScript поддерживает свойства `get` и `set` . На самом деле они называются свойствами доступа (accessors). Аксессоры атрибута есть функции, связанные с получением (чтением, геттеры) или установкой
```suggestion
Объявления класса могут содержать геттер и сеттер как вместе, так и порознь.
```

2018-11-26 16:50 UTC, greggubarev approved these changes

2018-11-26 16:50 UTC, greggubarev approved these changes
LGTM 👍 :dart:

Thank you for the PR ✨ 🎉
 We're happy to accept these changes and look forward to your future contributions :clap:

Happy coding! :octocat:

2018-11-26 16:50 UTC, merged