Create flexbox-aligning-flex-items.md
freeCodeCamp/freeCodeCamp pull request #24102
Opened 2018-10-20 08:50 UTC by leebut

This file describes and illustrates how flex-direction, justify-content, align-items and align-content work together.
I will take some screenshots for the align-content section. All other screenshots are done.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-21 04:13 UTC, leebut commented
I don't understand why this failed.

2019-02-17 15:52 UTC, thecodingaviator requested changes
Please either replace all the alt text with correct ones or leave them empty

2019-02-18 02:21 UTC, leebut commented
I don't understand. What alt text? I didn't include any images.

2019-03-01 14:21 UTC, thecodingaviator commented on guide/english/css/flexbox-how-to-align-flex-items/index.md
> +![alt text](https://raw.githubusercontent.com/leebut/Flexbox-Images/master/cross%20axis%20col.png "Cross axis of a column.")
These^

2019-03-24 14:48 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-03-24 16:04 UTC, thecodingaviator commented
Hi @leebut 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-03-24 16:04 UTC, closed without merging