Graph Algorithms: Added ford fulkerson algorithm for maximum flow
freeCodeCamp/freeCodeCamp pull request #24481
Opened 2018-10-20 17:14 UTC by Trion129

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Added guide for Ford Fulkerson algorithm with python implementation.

2019-03-15 20:16 UTC, theNaut1lus requested changes
@Trion129 Just some small change suggestions regarding some tab spacing issues, please go through the same.

/cc: @RandellDawson

2019-03-15 20:16 UTC, co16353sidak commented on guide/english/algorithms/graph-algorithms/ford-fulkerson/index.md
> +Ford Fulkerson's algorithm solves the maximum flow graph problem. It finds the best organisation of flow through the edges of graphs such that you get maximum flow out on the other end. The source ha
Please remove tab spacing after the sentences here.

2019-05-11 02:53 UTC, RandellDawson approved these changes

2019-05-11 02:54 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-05-11 03:46 UTC, merged