added information to abs function
freeCodeCamp/freeCodeCamp pull request #24936
Opened 2018-10-21 04:07 UTC by shilpi03

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-04-26 13:09 UTC, thecodingaviator requested changes
Please clear merge conflicts and check comments below

2019-04-26 13:09 UTC, thecodingaviator commented on guide/english/python/abs-function/index.md
> +`abs()` is a built-in function in Python 3, to compute the absolute value of any number. The absolute value of a number "means only how far a number is from 0" <sup>1</sup> It takes one argument `x`.
Change the link here to markdown format

2019-04-26 13:09 UTC, thecodingaviator commented on guide/english/python/abs-function/index.md
> +abs(x)
Change this to code format

2019-04-26 13:09 UTC, thecodingaviator commented on guide/english/python/abs-function/index.md
> +The return value is an integer or a float. Even if complex number is passed, it would return its magnitude, computed as per complex number algebra.
Make this what it was originally, it is more clear

2019-05-03 18:38 UTC, thecodingaviator requested changes
Check comments above, same thing

2019-05-17 01:42 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-05-17 05:36 UTC, thecodingaviator commented
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-05-17 05:36 UTC, closed without merging