added pros & cons
freeCodeCamp/freeCodeCamp pull request #24978
Opened 2018-10-21 06:07 UTC by Praneeth16

Added advantages and disadvantages for Random Forests.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-04-30 22:54 UTC, jonathan-grah commented on guide/english/machine-learning/random-forest/index.md
> +- It generally does not overfit too badly, and it is very easy to stop it from overfitting.
```
- They generally don't overfit too badly, and it's very easy to stop.
```

2019-04-30 22:54 UTC, jonathan-grah commented on guide/english/machine-learning/random-forest/index.md
> +- It doesnot work well on image data.
```
- Random forests don't work well on image data.
```

2019-04-30 22:55 UTC, jonathan-grah commented on guide/english/machine-learning/random-forest/index.md
> +- It is a predictive modeling tool and not a descriptive tool. That means, if you are looking for a description of the relationships in your data, other approaches would be preferred.
```
- Predictive modelling tool, not a descriptive tool, meaning if you are looking for a description of the relationships in your data; other approaches would be preferred.
```

2019-04-30 22:55 UTC, jonathan-grah commented on guide/english/machine-learning/random-forest/index.md
> +
Remove this line.

2019-04-30 22:56 UTC, jonathan-grah commented on guide/english/machine-learning/random-forest/index.md
> +- It requires very few pieces of feature engineering.
```
- Requires very few pieces of feature engineering.
```

2019-04-30 22:56 UTC, jonathan-grah requested changes
### LGTM 👍 
Just a few minor SPG changes 😃

2019-05-26 04:15 UTC, RandellDawson commented
@jonathan-grah This PR has gone stale.  Do you want to make your suggested changes on behalf of the user and merge or just close it?

2019-06-20 14:33 UTC, RandellDawson commented
HI @Praneeth16 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-06-20 14:33 UTC, closed without merging