added the usage of std::find
freeCodeCamp/freeCodeCamp pull request #25262
Opened 2018-10-21 13:28 UTC by glanderson42

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

2019-02-25 07:57 UTC, scissorsneedfoodtoo requested changes
I got some errors while checking your code. Could you fix those and update this PR?

2019-02-25 07:57 UTC, scissorsneedfoodtoo commented on guide/english/cplusplus/vector/index.md
> +#include <iostream>
Running this code produces the following error: `error: no matching function for call to 'find'`

2019-02-25 07:57 UTC, scissorsneedfoodtoo commented on guide/english/cplusplus/vector/index.md
> +#include <iostream>
This code produces the same error mentioned above.

2019-04-16 23:29 UTC, RandellDawson commented
@scissorsneedfoodtoo This PR has gone stale.

2019-04-17 03:16 UTC, scissorsneedfoodtoo commented
@RandellDawson, I agree. Best to close this.

2019-04-17 03:16 UTC, closed without merging