Add the text article Infinite Loop to my article
freeCodeCamp/freeCodeCamp pull request #25516
Opened 2018-10-21 18:56 UTC by SakshamGupta1995

The article  "##Infinite Loop by opposite iteration##" gives an example to new java programmer as to how a program can go into infinite loop if we increment the value of i instead of decrementing it and vice-versa. It is a basic but an important example for new coders.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-21 23:03 UTC, Manish-Giri requested changes
1.  To add more code samples demonstrating infinite loops, use a statement to introduce the same with the `h4` tag (follow the recommended guide formatting), like:
 
     > #### Some more examples of infinite loops are shown below.

2. Remove the `/*My Changes` line

3. Use subheadings like `h4` to introduce points like `##Infinite Loop by opposite iteration##` and remove the hashes at the end.

4. Please don't add unnecessary new lines and remove the ones you've added.

2018-11-01 08:10 UTC, Manish-Giri approved these changes

2018-11-03 19:29 UTC, cmccormack commented
Closing and reopening to reset CI

2018-11-03 19:51 UTC, cmccormack commented
Looks good to me, and congratulations on your first Pull Request!  🎉🎉🎉
We look forward to future contributions!

2018-11-03 19:51 UTC, merged