Add more details for constants
freeCodeCamp/freeCodeCamp pull request #25524
Opened 2018-10-21 19:05 UTC by tokesk

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-02-19 18:13 UTC, theNaut1lus requested changes
I have left 2 suggestive comments, please review on them both and make the required changes.

2019-02-19 18:13 UTC, co16353sidak commented on guide/english/php/constants/index.md
> +### Example - Valid and invalid constant names
In adding this example, you have in the process created a duplicate Example heading which shouldn't be there,
make it such that headings should be in the format `Example # - Description` with # being the number of the example and description being a small description describing the example.

2019-02-19 18:13 UTC, co16353sidak commented on guide/english/php/constants/index.md
> +
As a practice it is a suggestion to add output alongside the code to allow for the reader to understand how constants will work, follow the format in the below example.

2019-03-28 21:31 UTC, RandellDawson commented
Hi @tokesk ,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-03-28 21:31 UTC, closed without merging