Remove unwanted comma
freeCodeCamp/freeCodeCamp pull request #26050
Opened 2018-10-22 16:47 UTC by NaveenDA

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-25 09:13 UTC, RandellDawson commented
Closed and Reopened this PR in an attempt to attempt to break out of the Travis build pending status.

2019-01-03 07:02 UTC, amandeepmittal approved these changes
LGTM!

2019-01-03 07:02 UTC, amandeepmittal commented
@RandellDawson is it okay to merge this PR?

2019-01-09 02:31 UTC, RandellDawson requested changes
@amandeepmittal, @NaveenDA  While a few of the commas needed to be removed, in some cases, an extra comma is needed.  See my requested changes.

2019-01-09 02:31 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +Good <code>alt</code> text is short but descriptive and meant to briefly convey the meaning of the image. You should always include an <code>alt</code> attribute on your image. Per HTML5 specificatio
This should actually be written as:
```
Good <code>alt</code> text is short but descriptive and meant to briefly convey the meaning of the image. You should always include an <code>alt</code> attribute on your image. Per HTML5 specification, this is now considered mandatory.
```

2019-01-09 02:31 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +Camper Cat happens to be both a coding ninja and an actual ninja and is building a website to share his knowledge. The profile picture he wants to use shows his skills and should be appreciated by al
Actually, to really make this sentence more grammatically correct, it should read something like:

```
Camper Cat happens to be both a coding ninja and an actual ninja, who is building a website to share his knowledge. The profile picture he wants to use shows his skills and should be appreciated by all site visitors. 
```

2019-01-09 02:31 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +    testString: assert($('img').attr('alt'), 'Your <code>img</code> tag should have an <code>alt</code> attribute and it should not be empty.');
These changes look good.

2019-01-28 17:22 UTC, RandellDawson approved these changes

2019-01-29 02:03 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +Good <code>alt</code> text is short but descriptive and meant to briefly convey the meaning of the image. You should always include an <code>alt</code> attribute on your image. Per HTML5 specificatio
On second thought, I think two conjunctions in the same sentence makes it more complicated than needed.  Why not rephrase to:
`Good <code>alt</code> text provides the reader a brief description of the image.  You should always include an <code>alt</code> attribute on your image. Per HTML5 specification, this is now considered mandatory.`

2019-01-29 17:41 UTC, amandeepmittal approved these changes

2019-01-29 17:42 UTC, amandeepmittal commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +    testString: assert($('img').attr('alt'), 'Your <code>img</code> tag should have an <code>alt</code> attribute and it should not be empty.');
Yes, I agree.

2019-01-29 18:11 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +Good <code>alt</code> text is short but descriptive and meant to briefly convey the meaning of the image. You should always include an <code>alt</code> attribute on your image. Per HTML5 specificatio
@amandeepmittal What do you think about what I posted above?

2019-02-07 17:15 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +Camper Cat happens to be both a coding ninja and an actual ninja and is building a website to share his knowledge. The profile picture he wants to use shows his skills and should be appreciated by al
@amandeepmittal What about my suggestion above?

2019-02-10 15:29 UTC, RandellDawson commented
@amandeepmittal Can you take a look at the one last suggestion I had above?

2019-02-10 15:32 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/add-a-text-alternative-to-images-for-visually-impaired-accessibility.english.md
> +Camper Cat happens to be both a coding ninja and an actual ninja and is building a website to share his knowledge. The profile picture he wants to use shows his skills and should be appreciated by al
On second thought, let's go ahead an approve the PR as is and I will create a new PR for the changes I have suggested, but the user has yet to add.

2019-02-10 15:33 UTC, merged

2019-02-10 15:40 UTC, RandellDawson commented
Congrats @NaveenDA  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝