Add The text "My Changes " To the Artical
freeCodeCamp/freeCodeCamp pull request #26071
Opened 2018-10-22 17:06 UTC by tofiqueahmedkhan

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-23 07:51 UTC, Manish-Giri commented on guide/english/bootstrap/index.md
> +My Changes.
Delete "My Changes."

2018-10-23 07:52 UTC, Manish-Giri commented on guide/english/bootstrap/index.md
> +Bootstrap is designed to be mobile first, meaning that the classes are designed such that we can begin by targeting mobile device screens first and then work upwards to larger screen sizes.
Add your changes to the "Boostrap Features" section as a list item.

2018-10-23 07:52 UTC, Manish-Giri requested changes
Suggested changes to be addressed.

2018-10-23 19:38 UTC, ArielLeslie commented
Stop putting the words 'My Changes' in random places.

2018-11-04 02:05 UTC, Manish-Giri reviewed
Hi @tofiqueahmedkhan,

As there has been no response from your end for a while, I am closing this PR.

Feel free to re-open it if you've addressed the suggested changes.

2018-11-04 02:05 UTC, closed without merging