Add "code for transparent background image" to article
freeCodeCamp/freeCodeCamp pull request #26070
Opened 2018-10-22 17:04 UTC by PanSem

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-02-22 19:07 UTC, theNaut1lus requested changes
@PanSem 
Added some simple typographical changes, please consider the suggestions so that we could merge these

/cc: @RandellDawson

2019-02-22 19:07 UTC, co16353sidak commented on guide/english/css/tutorials/transparent-background-images/index.md
> +You must have same width and height for div and div:before
`have same` -> `have the same`

2019-02-22 19:07 UTC, co16353sidak commented on guide/english/css/tutorials/transparent-background-images/index.md
> +You have to add :before to the element which you want to add the transparent background image
`to the element which` -> `to the element to which`

2019-02-22 19:07 UTC, co16353sidak commented on guide/english/css/tutorials/transparent-background-images/index.md
> +You have to add :before to the element which you want to add the transparent background image
`add :before` -> `add the :before pseudo-selector` (or equivalent)

2019-05-13 07:41 UTC, RandellDawson commented
Hi @PanSem 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-05-13 07:41 UTC, closed without merging