Add typescript classes guide.
freeCodeCamp/freeCodeCamp pull request #26244
Opened 2018-10-22 18:35 UTC by jasmeetsohal

2018-10-23 05:55 UTC, jasmeetsohal reviewed
text formatting changes

2019-01-15 21:43 UTC, Manish-Giri requested changes
Hi @jasmeetsohal 

Please re-open this PR if you wish to apply the suggested changes.

2019-01-15 21:43 UTC, Manish-Giri commented on guide/english/typescript/classes/index.md
> +      this.name = name
Add the ending `;` to be consistent. 
```suggestion
      this.name = name; 
```

2019-01-15 21:43 UTC, Manish-Giri commented on guide/english/typescript/classes/index.md
> +      console.log("Pet name is  :   "+this.name)
Add ending `;`.
```suggestion
      console.log("Pet name is  :   "+this.name); 
```

2019-01-15 21:43 UTC, Manish-Giri commented on guide/english/typescript/classes/index.md
> +pet.show();
Add the expected output in a comment beside this line -
```suggestion
pet.show(); // output goes here
```

2019-01-15 21:43 UTC, Manish-Giri commented on guide/english/typescript/classes/index.md
> +      //Fields
Add a space after the comment and the comment text -
```suggestion
      // Fields
      // Constructors
      // Functions
```

2019-01-15 21:43 UTC, Manish-Giri commented on guide/english/typescript/classes/index.md
> +`Object Oriented Programming` is worthwhile where tons of code are written, by structuring the code it makes vivid to understand.
Please re-phrase these lines so they are easier to understand.
> `Object Oriented Programming` is worthwhile where tons of code are written, by structuring the code it makes vivid to understand.
Class is one of the paradigm of `OOP`.
TypeScript class reserved `class` keyword to create a class. The syntax is given below - 

Maybe something like this -

```suggestion
Object Oriented Programming is an important programming principle, especially where a lot of code is written. By structuring the code in classes and objects, it makes the code easier to understand.
```

Same with this line -
> TypeScript class reserved `class` keyword to create a class. The syntax is given below -

2019-01-24 05:08 UTC, jasmeetsohal commented
@Manish-Giri Where do I re-open this PR? I couldn't find the way to re-open this.

2019-01-24 05:31 UTC, scissorsneedfoodtoo commented
@jasmeetsohal, it should be the button on the left right below this comment box. I can go ahead an reopen it for you.

2019-01-25 07:04 UTC, jasmeetsohal commented
Hi @Manish-Giri 
Please review the changes that I've made.

2019-01-25 16:11 UTC, jasmeetsohal commented
> @jasmeetsohal, it should be the button on the left right below this comment box. I can go ahead an reopen it for you.

Thanks @scissorsneedfoodtoo

2019-01-26 03:55 UTC, Manish-Giri approved these changes
Hi @jasmeetsohal 

Thanks for making the changes.

While most of your changes are good, I was meaning for you to add the expected output when this line would be executed - 

> `pet.show();`

But I've fixed it and added the output - 

> `pet.show(); // Pet name is: Bruno`

Thanks for creating the PR, and Happy Coding!

2019-01-26 03:55 UTC, merged

2019-01-27 13:45 UTC, jasmeetsohal commented
Thanks @Manish-Giri 
I hope, that I'll continue the contribution on FCC projects :smile: