add the text "The first publicly available description of HTML was a …
freeCodeCamp/freeCodeCamp pull request #26370
Opened 2018-10-22 20:26 UTC by karlwil1

…document called "HTML Tags", first mentioned on the Internet by Tim Berners-Lee in late 1991. Who is widely credited with the invention of html." to article

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-22 20:32 UTC, karlwil1 commented
> "The first publicly available description of HTML was a document called "HTML Tags", first mentioned on the Internet by Tim Berners-Lee in late 1991" - from https://en.wikipedia.org/wiki/HTML

2018-10-22 22:33 UTC, Manish-Giri requested changes
Suggested changes to be addressed.

2018-10-22 22:33 UTC, Manish-Giri commented on guide/english/html/index.md
> +The first publicly available description of HTML was a document called "HTML Tags", first mentioned on the Internet by Tim Berners-Lee in late 1991. Who is widely credited with the invention of html.
```suggestion
The first publicly available description of HTML was a document called "HTML Tags", first mentioned on the Internet in late 1991 by Tim Berners-Lee, who is widely credited with the invention of html. 
```

2018-11-04 02:45 UTC, Manish-Giri approved these changes
Hi @karlwil1 ,

 Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions. 📝

2018-11-04 02:46 UTC, merged