Expand article to include an example
freeCodeCamp/freeCodeCamp pull request #26384
Opened 2018-10-22 20:46 UTC by wheat779

Expand article to discuss downward flow of data when using props, and to include an example.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-03-16 16:49 UTC, thecodingaviator commented
Under our policy on plagiarism, we cannot include this, I'm hence closing the PR

2019-03-16 22:10 UTC, wheat779 commented
Wow, five months later. I forgot about this.

The cited example is from the React official documentation which is available to be used in this fashion under its license if you care to read it. 

https://github.com/facebook/react/blob/master/LICENSE

Not plagiarism.

2019-03-17 10:37 UTC, thecodingaviator commented
I'm sorry, yes, you're right, I'm reopening the PR and requesting some changes, please go ahead and make those

2019-03-17 10:39 UTC, thecodingaviator requested changes
Please go ahead and make the requested changes, also fix the Merge Conflict to reflect what you'd like to add for the updated file

2019-03-17 10:39 UTC, thecodingaviator commented on guide/english/react/props/index.md
> +---
```suggestion

```
Please remove these lines

2019-03-17 10:39 UTC, thecodingaviator commented on guide/english/react/props/index.md
> +---
```suggestion

```
This too

2019-03-17 10:39 UTC, thecodingaviator commented on guide/english/react/props/index.md
> +```
Change it to 
```
```jsx
```
 so that it indicates the language

2019-03-17 10:39 UTC, thecodingaviator commented on guide/english/react/props/index.md
> +Here "element" calls the welcome function with the prop 'name = "Sara"', which creates a header element is then rendered to the screen by ReactDOM.render().
```suggestion
Here `element` calls the welcome function with the prop `name = "Sara"`, which creates a header element is then rendered to the screen by ReactDOM.render().
```

2019-04-10 16:53 UTC, RandellDawson commented
@thecodingaviator PR has gone stale.

2019-04-11 08:26 UTC, thecodingaviator commented
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-04-11 08:26 UTC, closed without merging