Changed machine translation nonsense
freeCodeCamp/freeCodeCamp pull request #26463
Opened 2018-10-22 22:17 UTC by alexgnatrow

Changed most of nonsense produced by machine translation

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-08 01:49 UTC, PurpleCatfish requested changes
Added fix recommendations to Russian article

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
>  freeCodeCamp.org возможен благодаря тысячам добровольцев, таких как вы. Мы благодарим за Ваш вклад, и мы рады приветствовать Вас на борту.
"Мы благодарим за Ваш вклад, и мы рады приветствовать Вас на борту." => 
"Мы благодарим Вас за вклад, и рады приветствовать Вас на борту."

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +У нас есть огромная база с открытым исходным кодом из тысяч [задач на программирование](https://www.freecodecamp.org/learn) и [Обучающие статьи](https://www.freecodecamp.org/guide). Эти задачи и стат
"задач на программирование" => "задач по программированию"

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +- [💻 В создании, обновлении и исправлении ошибок в наших задачах на программирование.](#create-update-and-fix-bugs-in-our-curriculum-challenges)
"на программирование" => "по программированию"

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +- [🌐 В переводе обучающих статей и задач на программирование.](#translate-guide-articles-and-curriculum-challenges)
"на программирование" => "по программированию"

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +Чтобы помочь, найдите «шаблон» на нашем [Сайте Руководства](https://www.freecodecamp.org/guide), напишите статью, затем создайте 'pull request', чтобы заменить шаблон своей статьей. [Pull request](ht
"это то как Вы " => "это то, как Вы "

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +Все наши задачи на программирование пишутся сообществом, принося экспертные знания таких добровольцев, как Вы.
"на программирование" => "по программированию"

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
>  Тем не менее, их необходимо постоянно совершенствовать по качеству. Например, вы можете обновить инструкции, чтобы исправить их [пустословие](https://en.oxforddictionaries.com/definition/verbiage) Вы
"их необходимо постоянно совершенствовать по качеству" => 
"их качество необходимо постоянно совершенствовать"

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +Вы можете помочь нам с переводом наших статей и задач на программирование для вашего родного языка. В настоящее время мы переводим версии в:
"на программирование" => "по программированию"

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +Вы можете помочь нам с переводом наших статей и задач на программирование для вашего родного языка. В настоящее время мы переводим версии в:
"переводим версии в:" => "переводим версии на:"

2018-11-08 01:49 UTC, sergeyradov commented on docs/russian/CONTRIBUTING.md
> +Мы ожидаем некоторых базовых знаний с некоторыми из вышеупомянутых технологий, инструментов и библиотек. Тем не менее, вы не обязаны быть в этом экспертом.
"Мы ожидаем некоторых базовых знаний с некоторыми" => "Мы надеемся на наличие базовых знаний в вышеупомянутых "

2019-01-17 17:04 UTC, greggubarev commented
**Thank you for opening this pull request.**

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. **We would welcome future pull requests from you.**

Thank you and happy coding.

2019-01-17 17:04 UTC, closed without merging