Changed the word "Mecanismo" to Engine
freeCodeCamp/freeCodeCamp pull request #26474
Opened 2018-10-22 22:34 UTC by TarikPonciano

The literal translations doesn't work, as people knows tools like Unity as Game Engines, and the word is used even when speaking portuguese.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-13 09:42 UTC, frontendwizard requested changes

2018-11-13 09:42 UTC, thefrontendwizard commented on guide/portuguese/game-development/unity/index.md
> +O Unity é uma engine de jogos para todos os propósitos que suporta gráficos 2D e 3D, rrecursos de arrastar e solta e codificação por meio da linguagem [C #](https://guide.freecodecamp.org/csharp) .
Fix `rrecursos` to `recursos`.

2019-06-20 16:29 UTC, RandellDawson commented
@thefrontendwizard This PR has gone stale.  Can you either close this PR or make the changes on behalf of the user?

Thank you

2019-06-24 14:57 UTC, RandellDawson commented
Hi @TarikPonciano ,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-06-24 14:57 UTC, closed without merging