Translated all  overall descriptions
freeCodeCamp/freeCodeCamp pull request #26476
Opened 2018-10-22 22:35 UTC by alexgnatrow

Translated all  overall descriptions and command descriptions for commands to work locally

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-08 02:04 UTC, PurpleCatfish requested changes

2018-11-08 02:04 UTC, sergeyradov commented on docs/russian/README.md
> +Эта папка содержит все описания по внесению вклада в freeCodeCamp.org
" папка содержит" => "раздел содержит" ?

2018-11-08 02:04 UTC, sergeyradov commented on docs/russian/README.md
> +| `npm run bootstrap` | Оборачивает разные сервисы |
"Оборачивает" => "Подготавливает" Or "Запускает"

2018-11-08 02:05 UTC, sergeyradov commented
@alexgnatrow Resolve conflict is needed. 
overall LGTM

2018-12-22 19:28 UTC, greggubarev approved these changes
**Thank you for opening this pull request.**

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. **We would welcome future pull requests from you.**

Thank you and happy coding.

2018-12-22 19:28 UTC, closed without merging