Added new section
freeCodeCamp/freeCodeCamp pull request #26554
Opened 2018-10-23 00:41 UTC by marcusparsons

Added a new section for defining what can be returned in custom methods and how to correct a mistake with returns

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-04-26 13:06 UTC, thecodingaviator requested changes
Please clear merge conflict and see comments below

2019-04-26 13:06 UTC, thecodingaviator commented on guide/english/csharp/return/index.md
> +[Run the following program on Repl.it](https://repl.it/@heyitsmarcus/Using-Return-for-Custom-Classes)
```suggestion
```
Remove this line, we're no longer accepting user based links to code

2019-04-26 13:06 UTC, thecodingaviator commented on guide/english/csharp/return/index.md
> +```csharp
```suggestion
```text
```
I believe to write output as text rather than C# code is better

2019-04-26 13:06 UTC, thecodingaviator commented on guide/english/csharp/return/index.md
> +It's important to realize what can be `return`ed in a method.  The type you return must match the type you initialize with the method you're calling.
```suggestion
It's important to realize what can be returned in a method.  The type you return must match the type you initialize with the method you're calling.  
```

2019-04-26 13:06 UTC, thecodingaviator commented on guide/english/csharp/return/index.md
> +Let's take a look at a **wrong** example:
```suggestion
Let's take a look at an example which **does not work**:
```

2019-04-28 08:57 UTC, thecodingaviator submitted a review, later dismissed
You still have outstanding merge conflicts, please fix them

2019-04-28 15:23 UTC, RandellDawson commented
@thecodingaviator I fixed the merge conflict on behalf of user.

2019-05-17 15:01 UTC, cmccormack approved these changes
This looks good to me 👍.  Thank you for your contribution!

2019-05-17 15:02 UTC, merged