add resource type
freeCodeCamp/freeCodeCamp pull request #26605
Opened 2018-10-23 02:25 UTC by bangnokia

add resource type

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-02-19 19:02 UTC, theNaut1lus requested changes
@bangnokia 
Please check comments for suggestions.

2019-02-19 19:02 UTC, co16353sidak commented on guide/english/php/php-data-types/index.md
> +A resource is a special variable, holding a reference to an external resource. Resources are created and used by special functions. See the [appendix](http://php.net/manual/en/resource.php) for a lis
here in the links, there is no appendix in the file being edited over here, so simply writing the word `appendix` will make it unclear to the reader about where the link will go.
Instead write `See the [official PHP documentation] for a ...` to make it more readable.

2019-02-28 09:35 UTC, theNaut1lus approved these changes
Changes made, simple merge.

@RandellDawson

2019-03-11 14:49 UTC, merged

2019-03-11 14:49 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉