Protecting Singleton From Reflection And Serialization
freeCodeCamp/freeCodeCamp pull request #26623
Opened 2018-10-23 02:57 UTC by Piyush-Blackbuck-121

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-04-10 16:38 UTC, thecodingaviator commented on guide/english/software-engineering/design-patterns/singleton/index.md
> +Also, Basic implementation of singleton is breakable by reflection, serialization and multithreading. So it needs extra care while implementing this pattern depending on the usecase. Here is [goodrea
```suggestion
Also, Basic implementation of singleton is breakable by reflection, serialization and multi-threading. So it needs extra care while implementing this pattern depending on the use-case. Here is a [goodread](https://medium.com/exploring-code/how-to-make-the-perfect-singleton-de6b951dfdb0) about Singleton.
```

2019-04-10 16:40 UTC, thecodingaviator requested changes
Check comments

2019-05-10 22:03 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-05-11 06:48 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-05-11 06:48 UTC, closed without merging