Fixed some translation to Portuguese (arvore Binaria) - Binary Search
freeCodeCamp/freeCodeCamp pull request #26659
Opened 2018-10-23 03:59 UTC by myluco

I read through the translation for arvore binaria in the Portuguese section of the guides.

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-02 15:35 UTC, frontendwizard requested changes

2018-11-02 15:35 UTC, thefrontendwizard commented on guide/portuguese/algorithms/binary-search-trees/index.md
> +1.  Cada árvore tem um nó raiz (no topo) quem possui algum valor.
Acho que o correto aqui é `que` ao inves de `quem`.

2019-06-20 16:30 UTC, RandellDawson commented
@thefrontendwizard This PR has gone stale. Can you either close this PR or make the changes on behalf of the user?

Thank you

2019-06-20 17:03 UTC, RandellDawson commented
@myluco Why did you close this PR?  Why not just make the suggested changes?

2019-06-20 18:10 UTC, myluco commented
Sorry. I am not familiar how these pull request work... Not even sure what is going on....
I thought you were asking me to close. so I did.
Looking at the request, the portuguese changes do not seem correct: I would not change the "tendo" with "quem possui"
Let me know what you want me to do (unfortunately, I do not have much time this week :( )

2019-06-20 18:53 UTC, RandellDawson commented
@myluco Is it that the Portuguese translation you are suggesting vs @thefrontendwizard's suggestion a matter of European vs. Brazilian Portuguese?

2019-06-21 01:03 UTC, myluco commented
I know brazilian portuguese. The suggestion from the frontendwizard does not look good from brazilian portuguese perspective. It seems that I did not suggest changes for that part that frontendwizard is suggesting. So, let me know how to proceed. I believe that someone needs to approve the changes I proposed.

2019-07-04 05:22 UTC, myluco reviewed
I am not sure how to get this going. I made several comments regarding the "quem possui" does not make sense in brazilian portuguese. 
Not sure what to do next to get the rest of the commit approved

2019-07-19 09:10 UTC, closed without merging