Clarification about the If-Else block.
freeCodeCamp/freeCodeCamp pull request #26926
Opened 2018-10-23 12:20 UTC by BlueJayBird

Just some added clarification about how when the condition for the 'If' section is not met it performs the 'else' block by default

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-25 04:43 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-03-03 14:52 UTC, thecodingaviator requested changes

2019-03-03 14:52 UTC, thecodingaviator commented on guide/english/csharp/if-else-statement/index.md
>  The If-Else statement executes a block of code depending on whether your precondition is fullfilled or not.
```suggestion
The `if else` statement executes a block of code depending on whether your precondition is fulfilled or not.
```

2019-03-03 14:52 UTC, thecodingaviator commented on guide/english/csharp/if-else-statement/index.md
> +If the 'If' condition is not met then it performs the 'Else' block by default.
```suggestion
If the `if` condition is not met then it performs the `else` block. 
```

2019-03-24 14:51 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-03-24 16:04 UTC, thecodingaviator commented
Hi @BlueJayBird 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-03-24 16:04 UTC, closed without merging