Update GUI options for GIT
freeCodeCamp/freeCodeCamp pull request #26962
Opened 2018-10-23 13:04 UTC by luciantanase14

I have added 2 links for GUI options for git for which I used.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-25 04:45 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-03-18 09:59 UTC, thecodingaviator requested changes

2019-03-18 09:59 UTC, thecodingaviator commented on guide/english/git/gui-options/index.md
> +* [GITX-dev](https://github-windows.s3.amazonaws.com/GitHubSetup.exe) is a fork of GitX, a GUI for git revision-control system. GitX-dev has been especially developed for software developers for use
```suggestion
* [GITX-dev](https://github-windows.s3.amazonaws.com/GitHubSetup.exe) is a fork of GitX, a GUI for git revision-control system. GitX-dev has been especially developed for software developers for use in production environments.Is intended for MAC environment.
```
This is a direct download link, change the link to an introduction page or something

2019-04-10 08:52 UTC, thecodingaviator commented
Hi

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-04-10 08:52 UTC, closed without merging