CSS Variables
freeCodeCamp/freeCodeCamp pull request #27717
Opened 2018-10-24 07:13 UTC by JanLawrence

Added guide for css -> css-variables

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-26 07:30 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-02-21 06:10 UTC, theNaut1lus requested changes
Added a small change, as such new guide file being created, not able to find any duplicate files, seems viable to merge post rectification.

/cc: @RandellDawson

2019-02-21 06:10 UTC, co16353sidak commented on guide/english/css/css-variables/index.md
> +Variables in CSS should be declared within a CSS selector that defines its scope. For a global scope you can use either the :root or the body selector.
add code emphasis on :root and on body as `:root` and `body`

2019-02-21 06:16 UTC, RandellDawson commented
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:**  The changes being added here were taken directly from https://www.w3schools.com/css/css3_variables.asp.  We do not allow plagiarized content in the Guide.

2019-02-21 06:16 UTC, closed without merging