fixed typo
freeCodeCamp/freeCodeCamp pull request #27768
Opened 2018-10-24 08:49 UTC by samujjal1618

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-26 10:04 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-03-08 02:53 UTC, RandellDawson requested changes
Please revert the changes on the lines specified.  The typo correction is fine.

2019-03-08 02:53 UTC, RandellDawson commented on guide/english/cplusplus/map/index.md
> +myMap.insert(pair<char, int> ("earth", 1));
This change is not necessary.   The original use of `make_pair` is valid syntax.

2019-03-08 02:53 UTC, RandellDawson commented on guide/english/cplusplus/map/index.md
> +myMap.insert(pair<char, int> ("moon", 2));
This change is not necessary.   The original use of `make_pair` is valid syntax.

2019-03-31 18:33 UTC, thecodingaviator commented
@RandellDawson This has gone stale

2019-04-03 15:06 UTC, RandellDawson commented
Hi @samujjal1618 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-04-03 15:06 UTC, closed without merging