Finding an Inverse Matrix (2x2)
freeCodeCamp/freeCodeCamp pull request #28132
Opened 2018-10-24 18:52 UTC by Domin-Sweet

Information on how to solve for and verify an inverse matrix for any 2 by 2 matrix.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-03-03 14:31 UTC, thecodingaviator requested changes

2019-03-03 14:31 UTC, thecodingaviator commented on guide/english/mathematics/2-by-2-inverse-matrix/index.md
> +<table>
Please use markdown tables over here

2019-03-24 14:52 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-03-24 16:05 UTC, thecodingaviator commented
Hi @Domin-Sweet 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-03-24 16:05 UTC, closed without merging