Extend information about Promises.
freeCodeCamp/freeCodeCamp pull request #28193
Opened 2018-10-24 20:27 UTC by githesp

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-26 21:40 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-04-03 08:48 UTC, thecodingaviator requested changes
Rename the folder to reflect title changes

2019-04-03 08:49 UTC, thecodingaviator requested changes

2019-04-03 08:49 UTC, thecodingaviator commented on guide/english/miscellaneous/the-es6-promises/index.md
> +## syntax
```suggestion
### Syntax
```

2019-04-03 08:49 UTC, thecodingaviator commented on guide/english/miscellaneous/the-es6-promises/index.md
> +Promises are a feature of ES6 to help with async programming, such as calls to a database or API.
```suggestion
## ES6 Promises
Promises are a feature of ES6 to help with async programming, such as calls to a database or API.
```

2019-04-25 08:17 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-04-25 13:44 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-04-25 13:44 UTC, closed without merging