translate: fix translation and grammar on vim's guide index.md
freeCodeCamp/freeCodeCamp pull request #28551
Opened 2018-10-25 13:35 UTC by jefferson2z

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-08-16 14:02 UTC, CleoAguiar requested changes

2019-08-16 15:39 UTC, RandellDawson commented on guide/portuguese/vim/index.md
> +O Vim é extremamente estável e entre os seus muitos recursos estao inclusos:
@CleoAguiar Your suggested change is not different than what the user already has.  Make sure to corrected verbiage/code you expect to see in the `suggestion`.

Thank you.

2019-08-17 11:27 UTC, CleoAguiar commented on guide/portuguese/vim/index.md
> +O Vim é extremamente estável e entre os seus muitos recursos estao inclusos:
Sorry, I've updated the suggestion

2019-08-17 13:45 UTC, RandellDawson commented on guide/portuguese/vim/index.md
> +O Vim é extremamente estável e entre os seus muitos recursos estao inclusos:
I made the change on behalf of the user.

2019-08-17 13:46 UTC, RandellDawson approved these changes

2019-08-17 13:46 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-08-18 04:52 UTC, merged