Default timezone
freeCodeCamp/freeCodeCamp pull request #28613
Opened 2018-10-25 15:11 UTC by hassanrafi39

A important feature for customized websites for any region.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-02-19 18:57 UTC, theNaut1lus requested changes
@hassanrafi39 I have requested a few changes.

2019-02-19 18:57 UTC, co16353sidak commented on guide/english/php/functions/time/index.md
> +You can set or get the settings using `date_default_timezone_set()` and `date_default_timezone_get()`.
As a suggestion make it more clear to the reader, what settings you are peering here.
you can make changes as follows:-

`date_default_timezone_set()` :- Used to set the default time zone

Similarly for `date_default_timezone_get()`

2019-02-19 18:57 UTC, co16353sidak commented on guide/english/php/functions/time/index.md
> +```
Here you haven't echoed the `$variable` so technically there won't be any output, so it is suggested to add an echo keyword such as
`echo $variable`

2019-03-19 21:58 UTC, RandellDawson commented
Hi @hassanrafi39 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-03-19 21:58 UTC, closed without merging