Revise Grammar and update index.md
freeCodeCamp/freeCodeCamp pull request #28684
Opened 2018-10-25 16:49 UTC by ComputerLee

I have revised the first two sections of this article. The previous grammar was poor and needed much improvement to be useful as a educational tool.

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-03-03 14:17 UTC, theNaut1lus requested changes
@ComputerLee small grammatical suggestions I have mentioned down in the comments, please consider these to improve the readability of your changes.

/cc: @RandellDawson merge conflict present, can be merged post resolution and changes.

2019-03-03 14:17 UTC, co16353sidak commented on guide/english/computer-science/garbage-collection/index.md
> +As said above, every programming language has their own way of implementing GC. In C programming, developers need to take care of memory allocation and deallocation using malloc() and dealloc() funct
on this line, it should be either `need to address GC` or it should be reverted back to the previous like `need to take care of GC`.
`need to take address GC` just seems odd and I feel it is grammatically wrong.

2019-03-03 14:17 UTC, co16353sidak commented on guide/english/computer-science/garbage-collection/index.md
> + In C#, memory allocation of objects are addressed in managed heap. which takes care by CLR (common language runtime). Memory allocation for the heap is done through win32 dll in the Operating System
removing the word `works` will be better here: `memory mapping is works based` -> `memory mapping is based`
small grammatical change: `Is happening in a consecutive manner` -> `for heap occurs in a consecutive manner`.

2019-03-03 14:18 UTC, co16353sidak commented
@ComputerLee consider removing merge conflicts of your PR with the `master` branch

2019-03-03 16:07 UTC, RandellDawson requested changes
@ComputerLee See the changes requested by @co16353sidak.  If you need help resolving the merge conflict, just ask.

Thank you.

2019-03-24 14:54 UTC, RandellDawson commented
Hi @ComputerLee 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-03-24 14:54 UTC, closed without merging