Update index.md
freeCodeCamp/freeCodeCamp pull request #28696
Opened 2018-10-25 17:08 UTC by dipashreepatil

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-26 20:37 UTC, RandellDawson commented
Closed and reopened this PR in an attempt to resolve the following Travis build failure:

> AssertionError: The <code>CurrentDate</code> component should render the value from the <code>date</code> prop in the <code>p</code> tag

2018-11-26 20:48 UTC, RandellDawson commented
Closed and reopened in an attempt to resolve specific Travis build failure.

2019-03-07 14:54 UTC, theNaut1lus requested changes
@dipashreepatil I have requested some small grammatical changes into this PR, please go through them.

/cc: @RandellDawson

2019-03-07 14:54 UTC, co16353sidak commented on guide/english/agile/actual-time-estimation/index.md
> +Actual time estimation is a time-based method of estimating development work. It is used to find out the best approximate time period required to perform the complete work in measures like e.g.certai
Small Change here:
`31 october` -> `31st October` : better grammar and readability.
`like e.g.certain task` -> `like for e.g certain task`

2019-05-22 23:10 UTC, moT01 approved these changes
Looks good enough for now @dipashreepatil - congratulations on your first contribution to freeCodeCamp!

2019-05-22 23:10 UTC, merged