Updated index.md with Grammar and Syntax Fixes
freeCodeCamp/freeCodeCamp pull request #28806
Opened 2018-10-25 19:28 UTC by XGiurob94

Updated index.md fixing grammar mistakes and Editing Errors (adding ``` to close the coding block and fixing the variable's name and general syntax errors).

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-03-06 15:58 UTC, RandellDawson requested changes
Please see requests for change.

2019-03-06 15:58 UTC, RandellDawson commented on guide/english/cplusplus/for-loop/index.md
> +### Init
Do not change spelling here.

2019-03-06 15:58 UTC, RandellDawson commented on guide/english/cplusplus/for-loop/index.md
> +### Condition
Do not change spelling here.

2019-03-06 15:58 UTC, RandellDawson commented on guide/english/cplusplus/for-loop/index.md
> +### Update
Do not change spelling here.

2019-03-06 15:58 UTC, RandellDawson commented on guide/english/cplusplus/for-loop/index.md
> +Here's the initialization condition which is first set to a=10. The loop first checks for this condition. It then checks for the condition expression i.e a<20 which holds true as 10<20(for the first
The current version on the master branch has changed, do you will need to resync your fork and resolve merge conflicts as some of your changes are not needed any longer.

2019-03-17 16:58 UTC, cmccormack reviewed
Thank you for your contribution.  At this time we have decided not to merge your pull request.  We welcome future pull requests from you.

**Explanation**
The changes in this PR conflict with the master branch.  The file edited in this commit has since been edited, moved, or deleted.  Please feel free to update your fork of the freeCodeCamp master branch and submit your edits in a new Pull Request.

Happy Coding!

2019-03-17 16:58 UTC, closed without merging