Linux find cmd examples
freeCodeCamp/freeCodeCamp pull request #29360
Opened 2018-10-26 08:01 UTC by godchaser

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-05-18 12:35 UTC, thecodingaviator requested changes

2019-05-18 12:35 UTC, thecodingaviator commented on guide/english/linux/using-the-find-command/index.md
> +# Useful find commands
```suggestion
## Useful find commands
```

2019-05-18 12:35 UTC, thecodingaviator commented on guide/english/linux/using-the-find-command/index.md
> +## Find all javascript files
```suggestion
### Find all javascript files
```

2019-05-18 12:35 UTC, thecodingaviator commented on guide/english/linux/using-the-find-command/index.md
> +## Find and remove multiple files
```suggestion
### Find and remove multiple files
```

2019-05-18 12:35 UTC, thecodingaviator commented on guide/english/linux/using-the-find-command/index.md
> +## Find last 30 days modified files
```suggestion
### Find last 30 days modified files
```

2019-05-18 12:35 UTC, thecodingaviator commented on guide/english/linux/using-the-find-command/index.md
> +## Find files with size between 100MB – 200MB
```suggestion
### Find files with size between 100MB – 200MB
```

2019-05-26 04:43 UTC, RandellDawson commented
@thecodingaviator I made your suggested changes on behalf of the user.

2019-05-26 12:28 UTC, thecodingaviator approved these changes
LGTM

2019-05-26 16:08 UTC, merged

2019-05-26 16:08 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉