Add TypeScript 'abstract classes' guide.
freeCodeCamp/freeCodeCamp pull request #29514
Opened 2018-10-26 12:55 UTC by jasmeetsohal

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-06 10:36 UTC, jasmeetsohal commented
I have added content on  Abstract Classes for TypeScript guide could you please review @raisedadead Thanks

2019-06-23 23:41 UTC, moT01 requested changes
Looks real good @jasmeetsohal - I made a few grammar change suggestions. If you can change these, we can get this merged. Thanks.

2019-06-23 23:41 UTC, moT01 commented on guide/english/typescript/abstract-classes/index.md
> +Abstract classes are super classes which can be derived by other classes.The class marked with `abstract` keyword
```suggestion
Abstract classes are super classes which can be derived by other classes. The class marked with the `abstract` keyword
```

2019-06-23 23:41 UTC, moT01 commented on guide/english/typescript/abstract-classes/index.md
> +Methods enclosed to abstract class which are marked `abstract` they do not contain method body and must be implemented in derived
```suggestion
Methods enclosed to abstract class which are marked `abstract` do not contain a method body and must be implemented in the derived
```

2019-07-03 15:29 UTC, moT01 approved these changes
Looks good @jasmeetsohal - thanks for contributing to freeCodeCamp! 🎉

2019-07-03 19:46 UTC, merged