[Layout] Update navigation bar to responsive
freeCodeCamp/freeCodeCamp pull request #29905
Opened 2018-10-26 22:38 UTC by sureemo

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Result (for screen width more than 630px):
![navbar_improve](https://user-images.githubusercontent.com/1849256/47595382-5b0c4a80-d9aa-11e8-8e70-64d1300cafd7.png)

2018-12-06 12:19 UTC, Bouncey approved these changes
Sorry for the delay @sureemo. The screen shot looks good, but things have changed since this PR has been raised

2018-12-06 12:19 UTC, Bouncey commented on client/src/components/Header/header.css
> +  .app-wrapper {
I don't think this class is available any more. You would perhaps need to apply these styles in the `Default` layout as all layouts use this as a base.

2018-12-06 12:19 UTC, Bouncey requested changes
I hit the wrong button before, sorry

2018-12-07 11:32 UTC, RandellDawson commented
There is an outstanding issue #29824 regarding what is being attempted to resolve here.  

@Bouncey FYI - There is a newer PR #34586 which attempts a fix for this issue.

2019-03-09 03:05 UTC, RandellDawson commented
@Bouncey Are these changes still relevant or should this PR be closed?

2019-03-11 15:12 UTC, raisedadead commented
We have taken a different approach to this and the search also needs some more work.

@sureemo 

Thanks a lot for taking the time to prepare this PR. Unfortunately we haven't been able to land this in time. Please do not be disappointed. We are really grateful for your contribution and would love to see some more in future.

Happy contributing.

2019-03-11 15:12 UTC, closed without merging