adding articles and youtube video
freeCodeCamp/freeCodeCamp pull request #29910
Opened 2018-10-26 22:53 UTC by lejlasp

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-01-19 16:54 UTC, rupali317 requested changes

2019-01-19 16:54 UTC, rupali317 commented on guide/english/documentation/index.md
> +Code documentation is a way in which developers write their code to create the best versions of their functions possible. Code Documentation lets the newbie to get comfortable with the customs of the
Please change "Code Documentation lets the newbie to get comfortable with..." to "Code Documentation lets the newbie get comfortable with....". Basically just omit the "to".

2019-01-19 16:54 UTC, rupali317 commented on guide/english/documentation/index.md
> +alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>
For **alt="IMAGE ALT TEXT HERE"**, the value of alt seems very generic. We should describe what the image is about. When the image fails to load then "IMAGE ALT TEXT HERE" won't be helpful in describing what the image is about.

One possible value  of alt attribute could be "Documentation for Better Code"

2019-03-05 08:47 UTC, thecodingaviator requested changes
Check my comments

2019-03-05 08:47 UTC, thecodingaviator commented on guide/english/documentation/index.md
> +Code documentation is a way in which developers write their code to create the best versions of their functions possible. Code Documentation lets the newbie get comfortable with the customs of the pa
```suggestion
Code documentation is a way in which developers write their code to create the best versions of their functions possible. Code Documentation lets a newbie get comfortable with the customs of the particular module, functions etc for a particular programming language. It is always recommended to go with the documentation before debugging your code, this helps you to debug effectively.
```

2019-03-05 08:47 UTC, thecodingaviator commented on guide/english/documentation/index.md
> +<br/><a href="http://www.youtube.com/watch?feature=player_embedded&v=pubm3spwkog
You don't need the line break here, please also change the link to markdown format

2019-03-26 03:39 UTC, RandellDawson commented
@thecodingaviator This one has gone stale

2019-03-26 07:34 UTC, thecodingaviator commented
Hi @lejlasp 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-03-26 07:34 UTC, closed without merging