Added guide to setup Firebase Crashlytics.
freeCodeCamp/freeCodeCamp pull request #30073
Opened 2018-10-27 05:05 UTC by HRankit

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-12-21 16:13 UTC, RandellDawson commented
Fixed frontmatter on user's behalf.  Still needs to be reviewed.

2019-05-11 16:09 UTC, thecodingaviator requested changes

2019-05-11 16:09 UTC, thecodingaviator commented on guide/english/android-development/firebase/firebase-crashlytics/setup/index.md
> +```java
Change spacing to 2-spaces per indent level

2019-05-11 16:09 UTC, thecodingaviator commented on guide/english/android-development/firebase/firebase-crashlytics/setup/index.md
> +```java
Here too

2019-06-03 23:12 UTC, RandellDawson commented
@thecodingaviator This PR has gone stale.

2019-06-04 19:22 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-06-04 19:22 UTC, closed without merging