Added Vagrant description
freeCodeCamp/freeCodeCamp pull request #30136
Opened 2018-10-27 07:09 UTC by alexkorsun

- added description for Vagrant
- updated gitignore to not commit idea files when use Webstorm IDE

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-01-01 17:34 UTC, RandellDawson commented
@raisedadead Check out the change to .gitignore

2019-01-01 17:58 UTC, raisedadead commented on .gitignore
> +/.idea
```suggestion
.idea
```

2019-01-01 17:59 UTC, raisedadead requested changes
A minor change.

2019-01-01 17:59 UTC, raisedadead commented
@RandellDawson We should consolidate all the .gitignore files together from the different sub projects.

2019-03-06 09:19 UTC, raisedadead commented
Closing as stale/decayed.

Hi,

Thanks a lot for your pull request. We have not seen an update from you on this PR in a while. We are going to have to close this as stale. If you are still interested, please open a fresh PR.

In case you believe this is closed incorrectly please hit us up in the [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors) to get this re-opened.

Thanks and happy contributing.

2019-03-06 09:19 UTC, closed without merging