How Fonts Should Degrade
freeCodeCamp/freeCodeCamp pull request #30159
Opened 2018-10-27 07:49 UTC by andrea1015

CSS basic

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-27 05:05 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-03-05 09:04 UTC, thecodingaviator requested changes

2019-03-05 09:04 UTC, thecodingaviator commented on guide/english/css/fonts/index.md
> +In this was we import the `lobster`
```suggestion
Here, the `Lobster` font has been imported
```

2019-03-05 09:04 UTC, thecodingaviator commented on guide/english/css/fonts/index.md
> +the in the css we can use such font:
```suggestion
In the page style, it can be used in the following form:
```

2019-03-05 09:04 UTC, thecodingaviator commented on guide/english/css/fonts/index.md
> +In this way the font `Lobster` will be the first choice, but if it is not avaiable the `monospace` will replace it.
```suggestion
In this way the font `Lobster` will be the first choice, but if it is not available the `monospace` font will replace it.
```

2019-03-05 09:04 UTC, thecodingaviator commented on guide/english/css/fonts/index.md
> +It is also possbible to import a new font:
```suggestion
It is also possible to import a new font:
```

2019-03-06 07:50 UTC, closed without merging