Add basic PHP file writing functions
freeCodeCamp/freeCodeCamp pull request #30396
Opened 2018-10-27 14:44 UTC by RichardLim00

2 different fopen mode, each with different properties and 1 file writing function.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-02-19 18:52 UTC, theNaut1lus requested changes
I have suggested a few changes to some grammatical errors, please make the above changes into the article @RichardLim00

2019-02-19 18:52 UTC, co16353sidak commented on guide/english/php/functions/files/file-writing/index.md
> +PHP had prepared a few functions to help user save information outside of PHP to be used later.
the line here should be `has prepared`

2019-02-19 18:52 UTC, co16353sidak commented on guide/english/php/functions/files/file-writing/index.md
> +Like most of the file handling functions, before conduct any file operation we must prepare the file for the operation first.
line should read `before conducting any`

2019-02-19 18:52 UTC, co16353sidak commented on guide/english/php/functions/files/file-writing/index.md
> +This is the function to add content to your file. This function should contain two variable, the first one should be the file handling variable and the second should be the content you wish to add to
`two variable` -> `two variables`

2019-02-20 10:43 UTC, RichardLim00 commented on guide/english/php/functions/files/file-writing/index.md
> +PHP had prepared a few functions to help user save information outside of PHP to be used later.
Thanks for the suggestion!

2019-02-20 11:08 UTC, fadaile commented
language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - '$HOME/.npm'

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

before_install:
  - npm config set loglevel warn

install: npm ci

before_script:
  - git config --global user.email team+camperbot@freeCodeCamp.org
  - git config --global user.name "CamperBot"

jobs:
  include:
    - stage: Lint javaScript
      script:
        - npm run ensure-env
        - npm run lint

    - stage: Unit and Integration tests
      script: npm test

    - stage: Artifacts builds
      if: branch = master && type != pull_request
      script: bash tools/ci-scripts/trigger-build.sh
      install: skip
      before_script: skip

2019-03-28 21:50 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-03-28 22:22 UTC, merged