Translated this README file to Russian
freeCodeCamp/freeCodeCamp pull request #30411
Opened 2018-10-27 15:02 UTC by Boto1

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-27 15:10 UTC, Boto1 commented
#18308

2018-11-08 01:36 UTC, PurpleCatfish approved these changes

2018-11-09 22:05 UTC, sergeyradov commented on docs/russian/README.md
> +| `npm run bootstrap` | Загружает различные сервисы. |
Something happened to table formatting. The table in the place looks broken in comparison to English Verison.

2018-11-09 22:06 UTC, PurpleCatfish requested changes
LGTM

2018-11-09 22:09 UTC, sergeyradov commented
@Boto1 Could you please rebase on the master branch to resolve the conflict?

2018-12-22 19:36 UTC, greggubarev approved these changes
**Thank you for opening this pull request.**

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. **We would welcome future pull requests from you.**

Thank you and happy coding.

2018-12-22 19:37 UTC, closed without merging