Grammatical Changes and Some minor additions.
freeCodeCamp/freeCodeCamp pull request #30451
Opened 2018-10-27 16:09 UTC by ComputerLee

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-03-03 14:23 UTC, theNaut1lus requested changes
@ComputerLee 
Small typographical changes in the comments. please consider them

2019-03-03 14:23 UTC, co16353sidak commented on guide/english/computer-science/notation/asymptotic-notation/index.md
> +In Compputer Science, time is one of our most valuable resources. In computing, we can measure performance with the amount of time a process takes to complete. Anthough the difference between the pro
1. `Compputer Science` -> `Computer Science`
2. `Anthough` -> `Although`
3. `algporithms` -> `algorithms`

2019-04-15 10:25 UTC, thecodingaviator commented
@ComputerLee please make the changes @co16353sidak suggested

2019-04-15 10:25 UTC, thecodingaviator requested changes
.

2019-05-11 06:56 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-05-11 06:56 UTC, closed without merging