feat(interview-prep): Porting Rosetta Problem: Sort stability
freeCodeCamp/freeCodeCamp pull request #31119
Opened 2018-10-28 14:44 UTC by NitronR

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-04 20:46 UTC, nikrb commented
@RandellDawson successfully tested locally

2018-11-15 19:18 UTC, nikrb commented
@NitronR a large part of the description seems to be copied from [here](https://rosettacode.org/wiki/Sort_stability). We do not condone plagiarism so please update or attribute to the source.

2018-12-05 13:35 UTC, scissorsneedfoodtoo requested changes
We should be good to go once those two things are fixed!

2018-12-05 13:35 UTC, scissorsneedfoodtoo commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/sort-stability.md
> +tests:
Could you indent the tests like so?:

```js
tests:
  - text: <code>stableSort</code> should be a function.
    testString: assert(typeof stableSort=='function','<code>stableSort</code> should be a function.');
```

2018-12-05 13:35 UTC, scissorsneedfoodtoo commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/sort-stability.md
> +function stableSort (arr) {,
Seems to be a couple of unnecessary commas here:

```js
function stableSort (arr) {
  // Good luck!
}
```

2018-12-05 14:37 UTC, NitronR commented
@scissorsneedfoodtoo Removed the commas and fixed indentation in all 6 PRs where needed.

2018-12-10 07:02 UTC, scissorsneedfoodtoo approved these changes

2018-12-10 07:02 UTC, merged

2018-12-10 07:02 UTC, scissorsneedfoodtoo commented
Everything LGTM! Thanks for all of your hard work, @NitronR.