Update for consistancy and clarity
freeCodeCamp/freeCodeCamp pull request #31250
Opened 2018-10-28 17:46 UTC by kmgern

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2019-05-17 06:05 UTC, thecodingaviator requested changes

2019-05-17 06:05 UTC, thecodingaviator commented on guide/english/html/elements/index.md
> +# html elements
```suggestion
# Elements
```

2019-06-20 14:57 UTC, RandellDawson approved these changes
@thecodingaviator LGTM

2019-06-22 08:20 UTC, thecodingaviator approved these changes
LGTM

2019-06-22 08:20 UTC, merged