Added selecting element with n
freeCodeCamp/freeCodeCamp pull request #31543
Opened 2018-10-29 03:07 UTC by andrewmamus

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-29 03:18 UTC, andrewmamus commented
Many people taught that they can only have access to the elements with class or id

2018-11-27 23:07 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-02-21 07:10 UTC, theNaut1lus requested changes
@andrewmamus 
Simple typographical changes, consider making them.

/cc: @RandellDawson

2019-02-21 07:10 UTC, co16353sidak commented on guide/english/css/css3-nth-child-selector/index.md
> +  	<ul class="parent">
Slight formatting issue here:
Align the opening tag `<ul>` with closing `</ul>`

2019-02-21 07:10 UTC, co16353sidak commented on guide/english/css/css3-nth-child-selector/index.md
> +     <li>Third</li>
This `<li>` tag seems out of place with the rest, consider adding a space to make it even

2019-02-21 07:10 UTC, co16353sidak commented on guide/english/css/css3-nth-child-selector/index.md
> +  }
consider adding spaces between property and value, such as:
`color:brown` -> `color: brown` for improved readability

2019-02-21 07:14 UTC, RandellDawson requested changes
@andrewmamus Please make the suggestions from @co16353sidak for this PR.

Thank you.

2019-03-19 22:01 UTC, RandellDawson commented
Hi @andrewmamus 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-03-19 22:01 UTC, closed without merging