I have updated the solution for this file.
freeCodeCamp/freeCodeCamp pull request #31749
Opened 2018-10-29 13:31 UTC by SGokul1

I have added the expected output of the  challenge seed code.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-29 13:33 UTC, SGokul1 commented
Expected solution for the solution seed code

2019-01-25 19:41 UTC, paulywill approved these changes

2019-02-06 01:59 UTC, RandellDawson requested changes
Looks good, but the `Challenge Seed` has `<h2>CatPhotoApp</h2>` above the `main` element, so your solution should look the same.

2019-02-14 19:28 UTC, RandellDawson approved these changes

2019-02-14 19:28 UTC, merged

2019-02-14 19:29 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉