Correct spelling and add spanish links
freeCodeCamp/freeCodeCamp pull request #31778
Opened 2018-10-29 14:23 UTC by francom94

- Replaced marco for framework since it's the correct terminology.
- Replaced english wiki links to spanish links for the same article.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-28 02:01 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-02-14 21:06 UTC, lynxlynxlynx requested changes

2019-02-14 21:06 UTC, lynxlynxlynx commented on guide/spanish/ruby/ruby-on-rails/index.md
> +[Ruby on Rails](http://rubyonrails.org/) es un framework del lado del servidor (gema) construido en el lenguaje Ruby para hacer sitios web. Rails hace que el desarrollo web sea más rápido, más fácil
Specifying an exact version is bad, as it will be obsolete soon and we don't want to keep updating the article. Please revert his part of the change.

2019-05-06 22:24 UTC, RandellDawson commented
@lynxlynxlynx Are you OK with closing this one as stale?

2019-05-07 21:15 UTC, lynxlynxlynx commented
I'm ok with closing all and any guide PRs. ;)

2019-05-07 21:33 UTC, RandellDawson commented
@francom94 As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-05-07 21:33 UTC, closed without merging