Updated index.md to change the grammatical mistakes
freeCodeCamp/freeCodeCamp pull request #32494
Opened 2018-10-30 11:05 UTC by AkhilBabu94

In the line no. 6, added an "an" before the word "element". Similar corrections in line no. 8, 9, and 10. In line no. 8, "then" is added in the line to make a proper meaning in completing the sentence. The word "to the" is added before the words such as "top", "left" and "bottom" in line nos. 9 and 10 to make a proper sentence.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-28 03:52 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-02-22 18:22 UTC, theNaut1lus reviewed
@AkhilBabu94 , I have added some suggestions for grammatical changes, please consider reviewing so that we could merge this.

/cc: @RandellDawson

2019-02-22 18:26 UTC, RandellDawson requested changes
@AkhilBabu94 I agree with @co16353sidak's assessment, so please make his recommended changes.

Thank you.

2019-02-23 03:18 UTC, AkhilBabu94 commented on guide/english/css/properties/padding-property/index.md
> +* Four values are provided, then values will apply in the following order: top, right, bottom, left.
@co16353sidak i have added the required the required changes. Thanks

2019-03-01 22:10 UTC, RandellDawson commented
@co16353sidak What do you think about @AkhilBabu94's new changes?

2019-03-01 22:19 UTC, theNaut1lus approved these changes
LGTM 🎉  - @RandellDawson 
Congratulations @AkhilBabu94 on your first contribution

2019-03-01 22:28 UTC, RandellDawson approved these changes

2019-03-01 22:29 UTC, merged

2019-03-02 03:04 UTC, AkhilBabu94 commented
Thanks all...😊