adding more information about Interfaces in Java
freeCodeCamp/freeCodeCamp pull request #32539
Opened 2018-10-30 12:36 UTC by renetanikolova

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-28 03:58 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-05-21 01:15 UTC, Manish-Giri commented on guide/english/java/data-abstraction/index.md
> +All methods in interface are public, we may not write it every time, like all of them are abstract, but we never write the key word abstract.
```suggestion
All methods in an Interface are implicitly `public` so we need not write the `public` keyword each time. 
```

Java 8 introduced default methods, which can contain full implementation, so "all of them are abstract" doesn't really hold true anymore.

2019-05-21 01:19 UTC, Manish-Giri requested changes
Hi @renetanikolova 

Thanks for creating this PR. Please address the suggested changes.

2019-05-21 01:19 UTC, Manish-Giri commented on guide/english/java/data-abstraction/index.md
> +The interface should have at least one method but not too many.
Is there a reference that you can link to which supports this statement?

2019-05-21 01:19 UTC, Manish-Giri commented on guide/english/java/data-abstraction/index.md
> +It decouples your code.
Please use list formatting to list out the advantages. Please review the [style guide for guide articles](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md) if you need help with formatting.

2019-06-10 22:58 UTC, Manish-Giri reviewed
Hi,

As there has been no response from your end for a while, I am closing this PR.

Feel free to re-open it if you wish to apply the suggested changes.

Happy Coding!

2019-06-10 22:58 UTC, closed without merging