Added articles: Material Design and User interface design for the English and Spanish language
freeCodeCamp/freeCodeCamp pull request #32779
Opened 2018-10-30 17:47 UTC by FahedHermoza

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

2019-05-01 15:11 UTC, RandellDawson commented
@lynxlynxlynx What do you think about this article and the Spanish translation of it?  Is it good to be merged?

2019-05-01 21:34 UTC, lynxlynxlynx commented
Too Spanish for me to review, but it's for the guide anyway.

2019-06-23 14:10 UTC, moT01 requested changes
Thanks for the PR @FahedHermoza - for the most part, these looks real good. I made a number of suggestions - A lot of them are pretty minor, formatting issues. But a couple should get fixed up for sure. There's a typo in the title and the same typo in the folder name - as well as a few other typos in the english files where spanish was used. Also, we are trying to move away from using images in these articles, so it would be great if you could make these work without them. 

It looks like you spent some time on these and they look good, so it would be great if you could make these changes and we can probably get this merged. Thanks!

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Material Design para Android](https://developer.android.com/design/material/?hl=es-419).
```suggestion
- [Material Design para Android](https://developer.android.com/design/material/?hl=es-419)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Material Components for Android](https://github.com/material-components/material-components-android).
```suggestion
- [Material Components for Android](https://github.com/material-components/material-components-android)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Material design specifications](https://material.io/design/introduction/#).
```suggestion
- [Material design specifications](https://material.io/design/introduction/#)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Material Design](https://www.youtube.com/watch?v=Q8TXgCzxEnw).
```suggestion
- [Material Design](https://www.youtube.com/watch?v=Q8TXgCzxEnw)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Material Design in the Google I/O App](https://www.youtube.com/watch?v=XOcCOBe8PTc&hl=es-419).
```suggestion
- [Material Design in the Google I/O App](https://www.youtube.com/watch?v=XOcCOBe8PTc&hl=es-419)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Google I/O 2014 - Material design: Structure and components](https://www.youtube.com/watch?v=dZqzz5lZFvo).
```suggestion
- [Google I/O 2014 - Material design: Structure and components](https://www.youtube.com/watch?v=dZqzz5lZFvo)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [User interfaces using Material Design by Uplabs](https://www.uplabs.com/android).
```suggestion
- [User interfaces using Material Design by Uplabs](https://www.uplabs.com/android)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862).
```suggestion
- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/material-design/index.md
> +- [Codelab](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0).
```suggestion
- [Codelab](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/user-interface-desing/index.md
> +- [Layouts](https://developer.android.com/guide/topics/ui/declaring-layout?hl=en-419).
```suggestion
- [Layouts](https://developer.android.com/guide/topics/ui/declaring-layout?hl=en-419)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/user-interface-desing/index.md
> +- [Layout resource](https://developer.android.com/guide/topics/resources/layout-resource?hl=es-419).
```suggestion
- [Layout resource](https://developer.android.com/guide/topics/resources/layout-resource?hl=es-419)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/user-interface-desing/index.md
> +- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862).
```suggestion
- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862)
```

2019-06-23 14:10 UTC, moT01 commented on guide/english/android-development/user-interface-desing/index.md
> +- [CodeLabs](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0).
```suggestion
- [CodeLabs](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [Material Design para Android](https://developer.android.com/design/material/?hl=es-419).
```suggestion
- [Material Design para Android](https://developer.android.com/design/material/?hl=es-419)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [Material Components for Android](https://github.com/material-components/material-components-android).
```suggestion
- [Material Components for Android](https://github.com/material-components/material-components-android)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [Material design specifications](https://material.io/design/introduction/#).
```suggestion
- [Material design specifications](https://material.io/design/introduction/#)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [Material Design](https://www.youtube.com/watch?v=Q8TXgCzxEnw).
```suggestion
- [Material Design](https://www.youtube.com/watch?v=Q8TXgCzxEnw)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [Google I/O 2014 - Material design: Structure and components](https://www.youtube.com/watch?v=dZqzz5lZFvo).
```suggestion
- [Google I/O 2014 - Material design: Structure and components](https://www.youtube.com/watch?v=dZqzz5lZFvo)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [User interfaces using Material Design by Uplabs](https://www.uplabs.com/android).
```suggestion
- [User interfaces using Material Design by Uplabs](https://www.uplabs.com/android)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862).
```suggestion
- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/material-design/index.md
> +- [Codelab](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0).
```suggestion
- [Codelab](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/user-interface-desing/index.md
> +title: User interface desing
```suggestion
title: User Interface Design
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/user-interface-desing/index.md
> +- [Layouts](https://developer.android.com/guide/topics/ui/declaring-layout?hl=en-419).
```suggestion
- [Layouts](https://developer.android.com/guide/topics/ui/declaring-layout?hl=en-419)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/user-interface-desing/index.md
> +- [Layout resource](https://developer.android.com/guide/topics/resources/layout-resource?hl=es-419).
```suggestion
- [Layout resource](https://developer.android.com/guide/topics/resources/layout-resource?hl=es-419)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/user-interface-desing/index.md
> +- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862).
```suggestion
- [Material Design for Android Developers](https://www.udacity.com/course/material-design-for-android-developers--ud862)
```

2019-06-23 14:10 UTC, moT01 commented on guide/spanish/android-development/user-interface-desing/index.md
> +- [CodeLabs](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0).
```suggestion
- [CodeLabs](https://codelabs.developers.google.com/codelabs/material-design-style-sp/index.html#0)
```

2019-07-01 23:57 UTC, moT01 approved these changes
Looks good @FahedHermoza - congratulations on your first contribution to freeCodeCamp! 🎉

2019-07-01 23:57 UTC, merged