Added PHP Try Catch to Guide.
freeCodeCamp/freeCodeCamp pull request #33840
Opened 2018-10-31 20:27 UTC by Gabehoverman

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-29 09:39 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-02-20 05:15 UTC, theNaut1lus requested changes
Just a small typographic error, otherwise good to merge.

@Gabehoverman Please make the required changes 

/cc: @RandellDawson

2019-02-20 05:15 UTC, co16353sidak commented on guide/english/php/try-catch/index.md
> +Below is an example of how you could use a tru catch block in a real world situation:
`tru` -> `try`

2019-02-21 04:29 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-02-21 04:52 UTC, merged