First third of article translated
freeCodeCamp/freeCodeCamp pull request #33937
Opened 2018-10-31 22:43 UTC by totalamd

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-08 01:31 UTC, PurpleCatfish requested changes
Reviewed Russian text and proposed fixes of grammar or typos.
Could you please take a look and review?

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +4. 📖 Прочитайте это [руководство по лучшим практикам](/docs/style-guide-for-guide-articles.md).
"руководство по лучшим практикам" => "руководство из лучших практик"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +5. 👉 [Пошлите пул-реквест](https://github.com/freeCodeCamp/freeCodeCamp/compare)
"Пошлите пул-реквест" => "Создайте пул-реквест"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +6. 🎉 Получите одобрение пул-реквеста - успех!
"Получите одобрение пул-реквеста - успех!" => "Дождитесь одобрение пул-реквеста и вот он успех!"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +Или просто [создайте ишью](https://github.com/freeCodeCamp/freeCodeCamp/issues) - любая самая маленькая помощь считается! 😊
"создайте ишью" => "создайте дефект"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +Или просто [создайте ишью](https://github.com/freeCodeCamp/freeCodeCamp/issues) - любая самая маленькая помощь считается! 😊
"маленькая помощь считается! 😊" => "любая помощь ценна! 😊"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +### [Следуйте этим рекомендациям из Руководства по созданию превосходных статей](/docs/style-guide-for-guide-articles.md)
"Следуйте этим рекомендациям из Руководства по созданию превосходных статей" 
=> 
"Следуйте рекомендациям из \"Руководства по созданию превосходных статей\""

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +Есть два варианта отсылать изменения в репозитории (после создания или редактирования статьи):
Нужно полностью перефразировать, потерян смысл фразы. (исправить позже)

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +Шаги, показанные на видео, описаны за ним:
"описаны за ним" => "описаны за ниже"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +1. Проследуйте в папку [**"guide"**](/guide) (расположенную в репозитории freeCodeCamp), выберите языковой раздел, в который вы ходите сделать вклад, и найдите заготовку статьи, которую вы хотите нап
"Проследуйте в папку [**"guide"**](/guide) (расположенную в репозитории freeCodeCamp), " => "Откройте папку [**"guide"**](/guide), расположенную в репозитории freeCodeCamp,"

"вы ходите сделать вклад" => "вы готовы сделать вклад" OR "вы хотите сделать вклад"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +1. Проследуйте в папку [**"guide"**](/guide) (расположенную в репозитории freeCodeCamp), выберите языковой раздел, в который вы ходите сделать вклад, и найдите заготовку статьи, которую вы хотите нап
"и найдите заготовку статьи, которую вы хотите написать или отредактировать." = > 
"и найдите заготовку для статьи, которую вы можете написать или отредактировать."

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +2. Кликните на <kbd>Edit this file</kbd> иконку с карандашом и сделайте изменения в вашем файле с помощь GitHub-варианта языка разметки Markdown.
"в вашем файле" => "в созданном файле"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +3. Прокрутите страницу до низа и добавьте сообщение в коммит, описывающее ваши изменения.
"до низа" => "до конца"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +    (Опционально): Мы очень рекомендуем использовать общепринятые сообщения в коммиты. Это хорошая практика, которую вы увидете на некоторых популярных Open Source-репозиториях. Это поощряет вас, как
"Это поощряет вас, как разработчика, " => "Это поможет вам, как разработчику, "

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +    Вот некоторые примеры общепринятых сообщений в коммиты:
"Вот некоторые примеры общепринятых сообщений в коммиты:"  =>
"Ниже приведены некоторые примеры общепринятых сообщений для коммитов:"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +    Стерайтесь делать эти сообщения короче, не более 50 символов. Вы всегда можете добавить дополнительную информацию в описание к сообщению.
"Стерайтесь делать эти сообщения короче, не более 50 символов." => "Будь кратки, используйте не больше 50 символов" **or** "Будьте локаничны, используйте не больше 50 символов"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +    Это не занимает дополнительное время по сравнению с нетипичными сообщениями навроде "update file" или "add index.md".
"Это не занимает дополнительное время по сравнению с нетипичными сообщениями навроде"
"Это не займет много времени по сравнению с обобщенными сообщениями вида"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +    Вы можете научиться о том, [как и что использовать, тут](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#why-use-conventional-commits).
"Вы можете научиться о том," => 
"Вы прочесь о том, почему мы используем локаничные коммиты,"

2018-11-08 01:31 UTC, sergeyradov commented on docs/russian/how-to-work-on-guide-articles.md
> +Вам не требуется работать на вашей локальной машине, если вы не хотите предварительно смотреть свои изменения или не занимаетесь исправлением пользовательского интерфейса (UI) или другими улучшениями
можно ссылку на оригинал - здесь я бы тоже перефразировал, совсем уж машинный перевод

2018-11-08 01:33 UTC, sergeyradov commented
I can do to a PR to @totalamd 's fork to make this fixes. 
@totalamd please advise if you expect my PR or can fix them by yourself?

2019-04-02 05:43 UTC, thecodingaviator requested changes
@totalamd Please fix merge conflicts

2019-04-03 19:56 UTC, totalamd commented
> advise if you expect my PR or can fix them

@sergeyradov You are very welcome to send PR on my PR or use mine as a base for your PR.

2019-05-11 07:04 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-05-11 07:04 UTC, closed without merging