Cleaned up Spanish translation of Java While loop guide
freeCodeCamp/freeCodeCamp pull request #33949
Opened 2018-10-31 23:03 UTC by murrutiar

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x ] None of my changes are plagiarized from another source without proper attribution.
- [ x ] My article does not contain shortened URLs or affiliate links.

2018-11-29 12:06 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-02-17 00:40 UTC, hestellez requested changes

2019-02-17 00:40 UTC, hestellez commented on guide/spanish/java/loops/while-loop/index.md
> +El `while` bucle repetidamente ejecuta el bloque de instrucciónes hasta que la condición especificada dentro de los paréntesis se evalúa como `false` . Por ejemplo:
- Debería ser **El bucle `while`** 
- No se necesita el espacio después de `false`

2019-02-17 00:40 UTC, hestellez commented on guide/spanish/java/loops/while-loop/index.md
> +Cada 'iteración' (de ejecutar el bloque de instrucciónes) está precedida por la evaluación de la condición especificada dentro del paréntesis: las instrucciónes se ejecutan solo si la condición se ev
- instrucciones no lleva tilde
- es mejor **dentro**, o en otro caso, **dentro de los paréntesis**...

2019-02-17 00:40 UTC, hestellez commented on guide/spanish/java/loops/while-loop/index.md
> +**Nota:** Para que el `while` bucle empieze la ejecución, requiere que la condición sea `true` inicialmente. Sin embargo, para salir del bucle, debe hacer algo dentro del bloque de instrucciónes para
- **empiece**
- instrucciones no lleva tilde

2019-08-13 20:28 UTC, RandellDawson commented
@murrutiar Can you please make the suggested changes @hestellez has suggested.

Thank you.

2019-08-27 20:32 UTC, closed without merging