Translate specific terms in readme.md
freeCodeCamp/freeCodeCamp pull request #33965
Opened 2018-10-31 23:31 UTC by soyvikman

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-10-31 23:32 UTC, soyvikman commented
I translate some specific terms of the english version of aritmetic operators!

2019-01-27 02:39 UTC, hestellez requested changes

2019-01-27 02:39 UTC, hestellez commented on guide/spanish/javascript/arithmetic-operation/index.md
> + false + 5      // interpreta false como y retorna 5
Should be:
//interpreta false como 0 y retorna 5

2019-01-27 02:39 UTC, hestellez commented on guide/spanish/javascript/arithmetic-operation/index.md
> + 5 + "foo"      // concatena la cadena y el numero y retorna "5foo"
should be "número" with an accent mark

2019-08-13 20:29 UTC, RandellDawson approved these changes

2019-08-13 20:32 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-08-13 22:11 UTC, merged