Fix: minor time tense mistakes
freeCodeCamp/freeCodeCamp pull request #34023
Opened 2018-11-01 01:52 UTC by 1634640

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-01 01:57 UTC, 1634640 commented
Fixed minor mistakes in where words should be written in in future tense.

2018-11-29 13:53 UTC, RandellDawson commented
Closed and Reopened this PR to attempt to resolve a specific Travis build failure.

2019-01-27 02:35 UTC, hestellez requested changes

2019-01-27 02:35 UTC, hestellez commented on guide/spanish/agile/safe/index.md
> +1.  **Adoptar una visión económica** : evalúar los costos económicos de decisiones, desarrollos y riesgos
"evaluar" no lleva tilde

2019-01-27 02:35 UTC, hestellez commented on guide/spanish/agile/safe/index.md
> +7.  **Apliqar cadencia, sincronice con la planificación de dominios cruzados** : la cadencia es el establecimiento de fechas en las que ocurren ciertos eventos (por ejemplo, el lanzamiento semanal) y
Es "aplicar"

2019-08-10 00:14 UTC, RandellDawson commented
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

2019-08-10 00:14 UTC, closed without merging