Created article page for Inkscape tool
freeCodeCamp/freeCodeCamp pull request #34205
Opened 2018-11-04 10:35 UTC by moinshaikh

Created a page for Inkscape tool under Designers-tools directory.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

2018-11-06 18:29 UTC, jonathan-grah requested changes

2018-11-06 18:29 UTC, jonathan-grah commented on guide/english/designer-tools/inkscape/index.md
> +You can freely download Inkscape [here](https://inkscape.org/release/0.92.3/)
This line can be removed

2018-11-06 18:29 UTC, jonathan-grah commented on guide/english/designer-tools/inkscape/index.md
> +Inkscape can be used to create or edit vector based graphics including illustrations, shapes, line arts, charts,logos, diagrams,
```suggestion
Inkscape can be used to create or edit vector-based graphics including illustrations, shapes, line arts, charts,logos, diagrams, 
```

2018-11-06 18:29 UTC, jonathan-grah commented on guide/english/designer-tools/inkscape/index.md
> +Download link for particular Operating Systems can be found here:
```suggestion
Download links for particular Operating Systems can be found here:
```

2018-11-06 18:29 UTC, jonathan-grah commented on guide/english/designer-tools/inkscape/index.md
> +It is available for all major Operating Systems including Windows, Linux, and Mac OS X.
Tag this on to the previous line

2018-11-11 17:53 UTC, moinshaikh commented
Recommended changes done. If you or someone can take a look and advise if anything else needs to be done.

Thanks!

2019-04-10 08:57 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +Download links for particular Operating Systems can be found here:
If you could link to download page, that's be great, versions keep changing

2019-04-10 08:57 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +You can also get access to the raw source code of Inskcape [here](https://inkscape.org/release/0.92.3/source/)
Same goes for this

2019-04-10 08:58 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +Further Information and Tutorials Resources:
```suggestion
### More Information:
```

2019-04-10 08:59 UTC, thecodingaviator requested changes
Check comments

2019-04-10 08:59 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +Inkscape is an open-source vector-based graphic editing tool used by graphic designers, artists andillustrationist to create high quality,
```suggestion
Inkscape is an open-source vector-based graphic editing tool used by graphic designers, artists andillustrationist to create high quality, vector-based illustration and designs. Inkscape is widely termed as 'free and open-source' alternative to popular illustration design tool Adobe Illustrator.
```

2019-04-10 08:59 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +vector-based illustration and designs. Inkscape is widely termed as 'free and open-source' alternative
```suggestion
```

2019-04-10 08:59 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +to popular illustration design tool Adobe Illustrator.
```suggestion
```

2019-04-10 08:59 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +as well as raster images.
```suggestion
```

2019-04-10 08:59 UTC, thecodingaviator commented on guide/english/designer-tools/inkscape/index.md
> +Inkscape can be used to create or edit vector-based graphics including illustrations, shapes, line arts, charts,logos, diagrams,
```suggestion
Inkscape can be used to create or edit vector-based graphics including illustrations, shapes, line arts, charts,logos, diagrams, as well as raster images.
```

2019-04-10 09:00 UTC, thecodingaviator commented
@jonathan-grah If your issue have been cleared, please go ahead and approve the PR. If you no longer want to take it up, please remove your assignment too. Thanks :)

2019-04-10 16:45 UTC, jonathan-grah approved these changes

2019-04-10 16:46 UTC, jonathan-grah commented
@thecodingaviator, thanks yeah, much better idea to not refer to version numbers in links, I agree 👍

2019-04-30 23:29 UTC, RandellDawson commented
@jonathan-grah Are you approving the PR as is or are you expecting the OP to make the changes requested by @thecodingaviator?

2019-05-01 08:20 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-05-01 08:20 UTC, closed without merging