Adding Full Stack Development Heading + book
freeCodeCamp/freeCodeCamp pull request #34218
Opened 2018-11-05 07:09 UTC by Recelis

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-05 12:51 UTC, amandeepmittal requested changes

2018-11-05 12:51 UTC, amandeepmittal commented on guide/english/book-recommendations/index.md
> +* Pro Mern Stack: Full Stack Web App Development with Mongo, Express, React, and Node*
Please remove the asterisk.

2018-11-05 12:51 UTC, amandeepmittal commented on guide/english/book-recommendations/index.md
> +- https://www.amazon.com/Pro-MERN-Stack-Development-Express/dp/1484226526
Add the link in correct format. Hint: see how other links are added in this document.

2018-11-05 20:27 UTC, paulywill reviewed
@amandeepmittal Is correct! Please fix these up.

2018-11-10 05:05 UTC, amandeepmittal approved these changes
LGTM now!

2018-11-10 05:06 UTC, merged