[Tests] ES6: Use Destructuring Assignment with the Rest Operator
freeCodeCamp/freeCodeCamp pull request #34303
Opened 2018-11-12 06:39 UTC by ezioda004

Added additional tests and solution. Have tested locally.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #18190

2018-11-12 10:04 UTC, nikrb approved these changes
LGTM

2018-11-12 10:08 UTC, nikrb commented
@ezioda004 successfully tested locally.
Just in passing ... Is requiring a specific variable name `arr` a bit, restrictive?

2018-11-12 10:30 UTC, ezioda004 commented
@nikrb It kinda is but we're providing `arr` variable in the seed anyway. Besides that, there are other challenges too which makes a particular identifier returned. Also, we already have other test that are relying on this variable. 
```
text: <code>arr</code> should be <code>[3,4,5,6,7,8,9,10]</code>
    testString: assert(arr.every((v, i) => v === i + 3) && arr.length === 8,'<code>arr</code> should be <code>[3,4,5,6,7,8,9,10]</code>');
```
So IMO its fine but if you have any suggestions we can add that.

2018-11-12 10:50 UTC, nikrb commented
@ezioda004 yes I noticed that other test, was going to suggest it should be rewritten, but given the time constraints I figured it could wait :smile:

2018-11-13 12:54 UTC, nikrb commented
@ezioda004 I don't see the error with #18069 on local master.
However, I think the seed should be updated because we're using the global variable in the function. I would suggest changing the seed to something like:
```
...
function removeFirstTwo(list) {
  "use strict";
  // change code below this line
  const updatedList = list; // change this
  // change code above this line
  return updatedList;
}
...
```

2018-11-13 13:07 UTC, ezioda004 commented
@nikrb Awesome, fixed.
BTW if the PR looks good to you, you can merge it.

2018-11-18 08:37 UTC, Nirajn2311 requested changes
@ezioda004 Everything LGTM, just do the below change

2018-11-18 08:37 UTC, Nirajn2311 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements.english.md
> +  const [, , ...arr] = list;
Remove extra space:
```suggestion
  const [, , ...arr] = list;
```

2018-11-18 08:46 UTC, ezioda004 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-with-the-rest-operator-to-reassign-array-elements.english.md
> +  const [, , ...arr] = list;
Fixed.

2018-11-18 08:48 UTC, Nirajn2311 approved these changes

2018-11-22 11:53 UTC, scissorsneedfoodtoo commented
@ezioda004, just checked this out and everything seems to be working fine locally. The only thing I might suggest is that we consider removing the first destructuring test, the one that reads "Destructuring should be used." Seems unnecessary since we have the other test to use destructuring on list now, but having both tests wouldn't hurt. Totally up to you! Either way I think we're good to merge.

2018-11-22 12:38 UTC, ezioda004 commented
@scissorsneedfoodtoo I agree, removed the old test as it was redundant.

2018-11-22 13:27 UTC, merged