fix: Fixes white space comparision issues on run test.
freeCodeCamp/freeCodeCamp pull request #34436
Opened 2018-11-23 21:33 UTC by wmollenkopf

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #34344

2019-02-17 05:55 UTC, RandellDawson requested changes

2019-02-17 05:55 UTC, RandellDawson commented on curriculum/challenges/arabic/03-front-end-libraries/react-and-redux/moving-forward-from-here.arabic.md
> +    testString: assert(new RegExp(/console.log\((\s)*\"Now I know React and Redux!\"(\s)*\)\;/g).test(editor.getValue()) || new RegExp(/console.log\((\s)*\'Now I know React and Redux!\'(\s)*\)\;/g).t
```suggestion
    testString: assert(/console\.log\(\s*("|')Now I know React and Redux!\1\s*\);?/.test(code));
```

2019-02-17 05:55 UTC, RandellDawson commented on curriculum/challenges/chinese/03-front-end-libraries/react-and-redux/moving-forward-from-here.chinese.md
> +    testString: assert(new RegExp(/console.log\((\s)*\"Now I know React and Redux!\"(\s)*\)\;/g).test(editor.getValue()) || new RegExp(/console.log\((\s)*\'Now I know React and Redux!\'(\s)*\)\;/g).t
```suggestion
    testString: assert(/console\.log\(\s*("|')Now I know React and Redux!\1\s*\);?/.test(code));
```

2019-02-17 05:55 UTC, RandellDawson commented on curriculum/challenges/english/03-front-end-libraries/react-and-redux/moving-forward-from-here.english.md
> +    testString: assert(new RegExp(/console.log\((\s)*\"Now I know React and Redux!\"(\s)*\)\;/g).test(editor.getValue()) || new RegExp(/console.log\((\s)*\'Now I know React and Redux!\'(\s)*\)\;/g).t
```suggestion
    testString: assert(/console\.log\(\s*("|')Now I know React and Redux!\1\s*\);?/.test(code));
```

2019-02-17 05:55 UTC, RandellDawson commented on curriculum/challenges/portuguese/03-front-end-libraries/react-and-redux/moving-forward-from-here.portuguese.md
> +    testString: assert(new RegExp(/console.log\((\s)*\"Now I know React and Redux!\"(\s)*\)\;/g).test(editor.getValue()) || new RegExp(/console.log\((\s)*\'Now I know React and Redux!\'(\s)*\)\;/g).t
```suggestion
    testString: assert(/console\.log\(\s*("|')Now I know React and Redux!\1\s*\);?/.test(code));
```

2019-02-17 05:55 UTC, RandellDawson commented on curriculum/challenges/russian/03-front-end-libraries/react-and-redux/moving-forward-from-here.russian.md
> +    testString: assert(new RegExp(/console.log\((\s)*\"Now I know React and Redux!\"(\s)*\)\;/g).test(editor.getValue()) || new RegExp(/console.log\((\s)*\'Now I know React and Redux!\'(\s)*\)\;/g).t
```suggestion
    testString: assert(/console\.log\(\s*("|')Now I know React and Redux!\1\s*\);?/.test(code));
```

2019-02-17 05:55 UTC, RandellDawson commented on curriculum/challenges/spanish/03-front-end-libraries/react-and-redux/moving-forward-from-here.spanish.md
> +    testString: assert(new RegExp(/console.log\((\s)*\"Now I know React and Redux!\"(\s)*\)\;/g).test(editor.getValue()) || new RegExp(/console.log\((\s)*\'Now I know React and Redux!\'(\s)*\)\;/g).t
```suggestion
    testString: assert(/console\.log\(\s*("|')Now I know React and Redux!\1\s*\);?/.test(code));
```

2019-02-17 05:55 UTC, RandellDawson commented
@wmollenkopf I pulled your PR locally and once I rebased it, had to resolve a merge conflict.  After doing so, your changes do not work.  They fail for even the most basic solutions of:
```
console.log('Now I know React and Redux!');
```
See my suggested assert which should work.  You will have to update this same assert across all the language files.

2019-03-16 17:12 UTC, lynxlynxlynx commented
If you plan to fix this PR, please reopen it with the working changes — I'm closing it due to lack of activity.

2019-03-16 17:12 UTC, closed without merging