Fix broken image in overflow
freeCodeCamp/freeCodeCamp pull request #34475
Opened 2018-11-28 11:23 UTC by thecodingaviator

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

This PR is w.r.t. #34441 and #20681

2019-06-23 15:16 UTC, moT01 reviewed
This added link is not working for me.

2019-06-23 15:50 UTC, thecodingaviator commented
@ahmadabdolsaheb can you please upload the posting image to the CDN and drop a link here?

2019-07-07 20:07 UTC, moT01 requested changes
I'm not sure what I was looking at before, but this does display an image. But it's not on it's own line and it's centered. Removing the line I suggested should put it on its own line I think. Or maybe adding two spaces at the end of the line. If you can make that quick change, we can merge this for now to make the article look better.

2019-07-07 20:07 UTC, moT01 commented on guide/english/css/overflow/index.md
>  And the `.box-element` will look like this:
```suggestion
```

2019-07-09 08:48 UTC, thecodingaviator commented
@moT01 how does it look now?

2019-07-09 11:10 UTC, moT01 approved these changes
Looks good @thecodingaviator 🎉

2019-07-09 11:10 UTC, merged