fix(challenges): D3 and Bootstrap font awesome challenges
freeCodeCamp/freeCodeCamp pull request #34477
Opened 2018-11-28 13:01 UTC by scissorsneedfoodtoo

Added an updated version of D3 as a CDN link to the data-visualization-with-d3 meta file and did the same for the latest version of Font Awesome in the Bootstrap challenges meta file. Doing this fixes the D3 challenges along with a couple of challenges in the Bootstrap section that require FA.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

If your pull request closes a GitHub issue, replace the XXXXX below with the issue number.

Closes #XXXXX

2018-11-28 14:14 UTC, ValeraS commented
All D3 challenges contain a required link. If we add a link into the `meta` file we should remove links from challenge files.

2018-11-28 15:40 UTC, scissorsneedfoodtoo commented
@ValeraS, yes, I agree. I started doing that for all the D3 files in all languages, but found that it broke the test suite. Started playing with the test-challenges.js file to try and point to the required link in the meta but figured it was a bit outside the scope of this PR. I'd be happy to go back and make those changes, though

2018-11-28 15:49 UTC, ValeraS commented
Rebase to latest master and try remove links again. It should work now.

2018-11-28 23:44 UTC, scissorsneedfoodtoo commented
Sure! I'll do that and update this PR as soon as I can.

2018-12-01 12:15 UTC, scissorsneedfoodtoo commented
@ValeraS, would you mind taking another look at this when you get a chance? And please let me know if there's anything else I can change.

2018-12-01 16:38 UTC, ValeraS requested changes

2018-12-01 16:38 UTC, ValeraS commented on curriculum/challenges/_meta/bootstrap/meta.json
> +      "link": "https://use.fontawesome.com/releases/v5.5.0/css/all.css"
IMO, it's not needed here. Only a few challenges require FA and they contain a link to it. Now both links from a `meta` file and from a challenge file are used in the client and for test challenges. Let's remove it from this PR and if you want you'll open new PR with updated links in challenge files.

2018-12-02 03:51 UTC, scissorsneedfoodtoo commented
@ValeraS, yes, I agree. Glad to see that the required field is being loaded to the iframe now! I learned a lot seeing how you did that.

I went ahead and made the requested change and this should be ready for further review.

2019-02-07 23:37 UTC, RandellDawson commented
@ValeraS What do you think about these changes?

2019-02-08 06:31 UTC, ValeraS approved these changes

2019-02-08 06:37 UTC, merged