feat: execute js challenges saga
freeCodeCamp/freeCodeCamp pull request #34524
Opened 2018-12-03 13:17 UTC by ValeraS

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [ ] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

Before run JS challenges we transform them by babel with a loop protect plugin. For some challenges it prevents pass the tests. For https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-10-summation-of-primes, a correct solution does not pass the tests.

This PR proposes run JS challenges without loop protect in a worker with a timeout.

2018-12-03 13:39 UTC, ezioda004 commented
@ValeraS So currently its only for the challenge you've mentioned? [Problem 35](https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-35-circular-primes) and [Problem 47](https://learn.freecodecamp.org/coding-interview-prep/project-euler/problem-42-coded-triangle-numbers) would also benefit from this.

2018-12-03 13:42 UTC, ValeraS commented
@ezioda004 All these challenges will benefit from this.

2018-12-04 13:01 UTC, Bouncey commented
The speed of this is amazing, could we possibly extend our use of workers to the moving all the transformers in to WebWorkers?

I was never happy using babel on the client, but this seems like a good alternative.

2018-12-04 13:23 UTC, Bouncey requested changes

2018-12-06 13:04 UTC, Bouncey approved these changes

2018-12-06 13:05 UTC, merged