Add Gravit Designer to designer tool.
freeCodeCamp/freeCodeCamp pull request #34566
Opened 2018-12-06 01:04 UTC by demangejeremy

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] My article does not contain shortened URLs or affiliate links.

Closes #XXXXX

2019-01-18 10:48 UTC, thecodingaviator requested changes

2019-01-18 10:48 UTC, thecodingaviator commented on guide/english/designer-tools/index.md
> +[Gravit Designer](https://www.designer.io/)
Add the video guide for Gravit as has been done for the restof the designers, link to playlist: https://www.youtube.com/playlist?list=PLqsk_4aqUvEYbEdXeg7_sxtF4MNfleFQJ&disable_polymer=true

2019-03-20 01:24 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-03-20 06:08 UTC, thecodingaviator commented
Hi @demangejeremy 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-03-20 06:08 UTC, closed without merging