fix: use JSON.stringify to cast console output rather than String
freeCodeCamp/freeCodeCamp pull request #34660
Opened 2018-12-12 20:55 UTC by justinsabourin

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #34417 

I have tested on a local copy.

2019-01-14 19:57 UTC, justinsabourin commented
Hi @raisedadead, I ran the current master branch locally and the bug still occurs. I've pushed some changes to resolve the conflicts in the PR.

2019-01-14 20:08 UTC, ValeraS requested changes
@justinsabourin You should add it into `buildProxyConsole` too https://github.com/freeCodeCamp/freeCodeCamp/blob/23cb7b80430d8d11b8c12214b59b883ee99fd05d/client/src/templates/Challenges/utils/frame.js#L76

2019-01-14 20:08 UTC, ValeraS commented on client/src/client/workers/test-evaluator.js
> +  } = e.data;
@justinsabourin Is it your formatting or prettier?

2019-02-14 09:37 UTC, Bouncey commented
@justinsabourin are you able to implement @ValeraS's suggested change?

2019-02-26 21:31 UTC, ValeraS approved these changes

2019-03-01 14:42 UTC, Bouncey commented
Great work @justinsabourin 

Thank you 👍 and congratulations on your first accepted pull request to freeCodeCamp/freeCodeCamp. We hope you will find time to contribute again in the future.

:sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles: :sparkles:

2019-03-01 14:42 UTC, Bouncey approved these changes

2019-03-01 14:43 UTC, merged