Changed grid-column-gap to column-gap
freeCodeCamp/freeCodeCamp pull request #34749
Opened 2018-12-27 17:27 UTC by kevindelsh

grid-column-gap is obsolete and should be replaced with column-gap. column-gap is already implemented in all the major browsers except for IE and Edge Mobile.

The file name should also be renamed to "create-a-column-gap-using-column-gap.english.md", IMHO, but I wasn't sure about that out of inexperience.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2018-12-27 17:35 UTC, kevindelsh commented
BTW, if you're OK with this PR, I can happily do the same for grid-row-gap => row-gap and grid-gap => gap.

2019-03-31 06:31 UTC, thecodingaviator requested changes
You'll need to change the challenge name in the `meta.json` file too

2019-03-31 06:32 UTC, thecodingaviator commented
@kevindelsh Please add the changes you wanted to `grid-row-gap` challenge to this very PR

2019-04-25 08:27 UTC, RandellDawson commented
@thecodingaviator This one has gone stale.

2019-04-25 13:45 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-04-25 13:45 UTC, closed without merging