SASS. @each. Replace stub
freeCodeCamp/freeCodeCamp pull request #34844
Opened 2019-01-10 00:17 UTC by TylerGlenski

Added 1x guide/example, 1x problem, and 1x solution.

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-01-16 06:54 UTC, thecodingaviator requested changes
Remove the whole problem section please, the user can go back to the curriculum if they want to see the problem again

2019-01-16 06:54 UTC, thecodingaviator commented on guide/english/certifications/front-end-libraries/sass/use-each-to-map-over-items-in-a-list/index.md
> +## Problem:
```suggestion

```
You do not need to restate the problem here, just put the hints and solution

2019-03-08 15:42 UTC, thecodingaviator commented
I see that there are improvements made by this PR, however, #34792 made changes to the same file adding the solution. Since it was a previous PR, it was merged first.

If you could please fix the merge conflict and update your file to what you want to add, please do. If you want to close the PR, that's fine too.

Thank you for contributing! Happy coding! ✈️

2019-03-08 20:57 UTC, RandellDawson commented
@thecodingaviator I fixed the merge conflict on behalf of the user, so the text and example added by the OP is included in this article.

If you are fine with the changes, go ahead and merge it.

2019-03-09 06:45 UTC, thecodingaviator approved these changes
LGTM! 👍

2019-03-09 07:03 UTC, merged

2019-03-09 07:03 UTC, thecodingaviator commented
@TylerGlenski Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝