fix: Use npm-run-all to run the develop command
freeCodeCamp/freeCodeCamp pull request #34840
Opened 2019-01-09 14:13 UTC by Bouncey

## Requires Windows machine to QA correctly

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.

Closes #34627

2019-01-09 17:38 UTC, cmccormack reviewed
It appears to be working well - the only problem I have now is I cannot seem to kill the process(es) after the development environment is fully loaded.  I'd be interested to see if I'm the only one.

2019-01-09 17:57 UTC, Nirajn2311 commented
@cmccormack you ain’t the only. Even I couldn’t kill the processes using git bash or wsl.

2019-01-09 19:17 UTC, RandellDawson commented
I can kill it with Ctrl+Break when using Git-Bash.

2019-01-09 19:18 UTC, RandellDawson reviewed
Works fine for me.  I can use Ctrl+Break to kill the processes when using Git-Bash

2019-01-10 07:02 UTC, raisedadead approved these changes

2019-02-06 13:03 UTC, Bouncey commented
@cmccormack @Nirajn2311 I cannot work on this any longer, as I do not have a windows machine to debug on.

Could either of you take this up, or pair on it?

2019-02-06 16:31 UTC, RandellDawson commented
@Bouncey FYI- I thought you already made changes to fix this issue a long time ago, because I no longer experience this issue on Windows 10.  I just have to make sure that I run Git-bash or Powershell as administrator and everything works fine.

2019-02-06 16:44 UTC, raisedadead commented
> I just have to make sure that I run Git-bash or Powershell as administrator and everything works fine.

Can someone add this to the instructions in this PR? Let's get this in.

2019-02-07 05:52 UTC, ValeraS requested changes

2019-02-07 05:52 UTC, ValeraS commented on package.json
> +    "develop": "npm-run-all -s ensure-env && npm-run-all -p start-develop-server start-develop-client",
```suggestion
    "develop": "npm run ensure-env && npm-run-all -p develop:*",
```

2019-02-07 05:52 UTC, ValeraS commented on package.json
> +    "start-develop-client": "cd ./client && node ./node_modules/gatsby-cli develop",
```suggestion
    "develop:client": "cd ./client && npm run develop",
```

2019-02-07 05:52 UTC, ValeraS commented on package.json
> +    "start-develop-server": "cd ./api-server && node development-entry.js",
```suggestion
    "develop:server": "cd ./api-server && node development-entry.js",
```

2019-02-07 09:16 UTC, raisedadead commented on package.json
> +    "develop": "npm-run-all -s ensure-env && npm-run-all -p start-develop-server start-develop-client",
Yep. Cleaner.

2019-02-12 17:53 UTC, RandellDawson commented
@ValeraS Are you ok with @Bouncey's latest changes?

2019-02-12 18:26 UTC, ValeraS approved these changes

2019-02-12 18:31 UTC, RandellDawson commented
> Can someone add this to the instructions in this PR? Let's get this in.

@raisedadead Can you explain what needs to be done and I will attempt to add it to this PR?

2019-02-12 18:42 UTC, raisedadead commented
> Can you explain what needs to be done and I will attempt to add it to this PR?

Sure.

We probably need some instructions in the local setup guide. I'll leave the location in the guide itself to your discretion that adds something on the lines of:

> Note: 
> If you are on Windows, make sure the command line tool (Cmd, PowerShell or Git Bash for Windows, etc.) that you use have correct user privileges. If possible, you should launch the tool with Administrator's privilege. 
> On windows, you should be able to launch a tool by right click -> Launch as an Administrator

Feel free to make the verbiage simpler as you seem fit.

2019-02-16 23:43 UTC, RandellDawson commented
@raisedadead OK, I added the Windows note where I think it fits the best.

2019-02-17 08:40 UTC, raisedadead approved these changes

2019-02-17 08:40 UTC, merged