Intermediate explanation number two
freeCodeCamp/freeCodeCamp pull request #34854
Opened 2019-01-11 12:17 UTC by MoonCWang

Please note I could not find a way to anonymize or shorten my repl.it url.

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-03-04 11:39 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/arguments-optional/index.md
> +*   <a href='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments' target='_blank' rel='nofollow'>arguments object</a>
Please change all these links to markdown format

2019-03-04 11:39 UTC, thecodingaviator requested changes
Check my comment

2019-03-04 17:09 UTC, RandellDawson requested changes
See change request.

2019-03-04 17:09 UTC, RandellDawson commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/arguments-optional/index.md
> +![:rocket:](https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:") <a href='https://repl.it/@MoonCWang/addtogether' target='_blank' rel='nofollow'>Run Code</a>
@MoonCWang Also, please remove this line as we no longer want these in the challenge guide articles.

2019-03-22 22:15 UTC, Manish-Giri reviewed
Hi @MoonCWang 

Welcome to FreeCodeCamp, and Thank You for creating a Pull Request. 

However, the solution in your PR is inherently similar to the existing Advanced solution in the guide. It's best not to have two solutions with similar logic for the same challenge.

I will be closing this PR but feel free to create another one 👍

2019-03-22 22:16 UTC, closed without merging