Fixed bad redireccion of the link with "Storing Values with the Equal Operator"
freeCodeCamp/freeCodeCamp pull request #34897
Opened 2019-01-18 11:07 UTC by frodriguez20H

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-01-18 11:11 UTC, thecodingaviator requested changes

2019-01-18 11:11 UTC, thecodingaviator commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/generate-random-fractions-with-javascript.english.md
> +<strong>Note</strong><br>Like <a href='javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator' target='_blank'>Storing Values with the Equal Operator</
```suggestion
<strong>Note</strong><br>Like <a href='javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator' target='_blank'>Storing Values with the Assignment Operator</a>, all function calls will be resolved before the <code>return</code> executes, so we can <code>return</code> the value of the <code>Math.random()</code> function.
```

2019-01-18 22:44 UTC, RandellDawson commented
When I test the link you changed locally, I get a 404, because it attempts to link to:

> http://localhost:8000/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator instead

instead of:
> http://localhost:8000/learn/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator

@Bouncey When I click the `Preview custom 404 page`, it still does not go to where it should.  Is that because the link needs to be prefixed with `learn` or is this a known Gatsby bug that will not be present in production?

![image](https://user-images.githubusercontent.com/5313213/51416708-82992c00-1b2f-11e9-869e-caf48ef87a62.png)

2019-01-19 06:13 UTC, thecodingaviator commented
@RandellDawson I think that's because on local, the learn.freecodecamp.org page is served from localhost:8000/learn but on the web the correct link most definitely is https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator/

2019-01-22 11:49 UTC, Bouncey requested changes

2019-01-22 11:49 UTC, Bouncey commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/generate-random-fractions-with-javascript.english.md
> +<strong>Note</strong><br>Like <a href='javascript-algorithms-and-data-structures/basic-javascript/storing-values-with-the-assignment-operator' target='_blank'>Storing Values with the Assignment Opera
the current `master` branch differs from what we have in production. We are trying to move things that are on subdomains in to subdirectories. Therefore, this `href` needs to be prefixed with `/learn`.

2019-02-10 14:32 UTC, RandellDawson commented
This will be fixed in another PR #35125 which fixes all such challenges.

2019-02-12 07:55 UTC, closed without merging