Added a solution/fixed stub
freeCodeCamp/freeCodeCamp pull request #34902
Opened 2019-01-18 22:36 UTC by jan-miksik

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-02-01 12:06 UTC, lipis commented on guide/english/certifications/coding-interview-prep/rosetta-code/100-doors/index.md
> +*   Please add your username only if you have added any **relevant main contents**. (![:warning:](https://forum.freecodecamp.com/images/emoji/emoji_one/warning.png?v=3 ":warning:") **_DO NOT_** _remo
```suggestion
- Please add your username only if you have added any **relevant main contents**. (![:warning:](https://forum.freecodecamp.com/images/emoji/emoji_one/warning.png?v=3 ":warning:") **_DO NOT_** _remove any existing usernames_)
```

2019-02-01 12:06 UTC, lipis commented on guide/english/certifications/coding-interview-prep/rosetta-code/100-doors/index.md
> +*   Categorize the solution in one of the following categories — **Basic**, **Intermediate** and **Advanced**. ![:traffic_light:](https://forum.freecodecamp.com/images/emoji/emoji_one/traffic_light.p
```suggestion
- Categorize the solution in one of the following categories — **Basic**, **Intermediate** and **Advanced**. ![:traffic_light:](https://forum.freecodecamp.com/images/emoji/emoji_one/traffic_light.png?v=3 ":traffic_light:")
```

2019-02-01 12:07 UTC, lipis commented on guide/english/certifications/coding-interview-prep/rosetta-code/100-doors/index.md
> +*   Add an explanation of your solution.
```suggestion
- Add an explanation of your solution.
```

2019-02-01 12:07 UTC, lipis commented on guide/english/certifications/coding-interview-prep/rosetta-code/100-doors/index.md
> +*   ![:warning:](https://forum.freecodecamp.com/images/emoji/emoji_one/warning.png?v=3 ":warning:") **DO NOT** add solutions that are similar to any existing solutions. If you think it is **_similar
```suggestion
- ![:warning:](https://forum.freecodecamp.com/images/emoji/emoji_one/warning.png?v=3 ":warning:") **DO NOT** add solutions that are similar to any existing solutions. If you think it is **_similar but better_**, then try to merge (or replace) the existing similar solution.
```

2019-05-16 07:21 UTC, thecodingaviator requested changes

2019-05-16 07:21 UTC, thecodingaviator commented on guide/english/certifications/coding-interview-prep/rosetta-code/100-doors/index.md
> +    function getFinalOpenedDoors (numDoors) {
Put this in code block with \`\`\`js

2019-06-20 14:59 UTC, RandellDawson commented
@lipis @thecodingaviator This PR has gone stale.  I suggest either making the changes on behalf of the contributor or close this PR.

2019-06-22 08:18 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-06-22 08:19 UTC, closed without merging