feat: proof of concept to inject react components in md files
freeCodeCamp/freeCodeCamp pull request #34953
Opened 2019-01-25 03:49 UTC by ronaldcs

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34494

2019-01-26 14:27 UTC, ValeraS requested changes
It's a working solution, but I think it does not meet our needs. It's good for cases where you have the same few components on many pages. But we have unique components on pages.

I propose next:
- in `index.md` add into frontmatter line:
```yml
component: calculators/CodingBootcampCodeCalculator
```
- place component files to `src/templates/Guide/components/calculators/CodingBootcampCodeCalculator`
- set `index.js` name for main file with default export and add a guide article layout to it.
- in `gatsby-node.js` add `component` to graphQL query
- in `utils/gattsby/guidePageCreator.js` 
```diff
@@ -32,7 +33,14 @@ exports.createGuideArticlePages = createPage => ({

   return createPage({
     path: `/guide${slug}`,
-    component: guideArticle,
+    component: !component
+      ? guideArticle
+      : path.resolve(
+          __dirname,
+          '../../src/templates/Guide/components/',
+          component,
+          'index.js'
+        ),
     context: {
       id,
       meta
```

if @Bouncey agree then I'll make proposed changes and @ronaldcs change CodingBootcampCodeCalculator and `index.md` files.

2019-01-26 17:55 UTC, ronaldcs commented on client/src/components/Calculators/CodingBootcampCostCalculator.js
> +      d3: node,
Seems like the only way I could get this to work was to use `document.createElement('div')` to get it to play nice with react-d3-library. I've tried `createRef` but that didn't work. Suggestions welcome.

2019-01-26 22:56 UTC, ronaldcs commented on client/src/components/Calculators/CodingBootcampCostCalculator.js
> +import rd3 from 'react-d3-library';
Excellent, thanks for the lesson :-).

2019-01-27 02:15 UTC, ronaldcs commented on client/src/components/Calculators/CodingBootcampCostCalculator.js
> +      d3: <div />,
Not needed anymore, will remove.

2019-02-14 09:47 UTC, ValeraS commented
@ronaldcs Could you redo this component like it done in this example https://github.com/freeCodeCamp/freeCodeCamp/commit/5a8f9bff4134519b477eb7db85940597c3f8a78b

2019-02-14 13:18 UTC, ronaldcs commented
@ValeraS sure, I can work on that.

2019-02-18 23:31 UTC, ronaldcs commented
https://github.com/freeCodeCamp/freeCodeCamp/pull/35278 replaces this PR relative to moving bootcamp cost calculator to guide.

2019-02-18 23:31 UTC, closed without merging