feat: Add article on Automated Accessibility Tools
freeCodeCamp/freeCodeCamp pull request #34998
Opened 2019-01-29 21:00 UTC by rkrupnick

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-02-14 02:55 UTC, theNaut1lus reviewed
Also add a short tutorial describing how to set up testing tools onto your repository or project.

the most common you can pick up is Lighthouse or something similar.

2019-06-23 12:49 UTC, moT01 requested changes
Thanks for the PR @rkrupnick, it looks good - [here's a preview of your changes](https://github.com/freeCodeCamp/freeCodeCamp/blob/12941d7ed1db63309c55cdc5bfb4bd20822b17de/guide/english/accessibility/automated-testing/index.md) - the `More Information` area needs some line breaks. I believe adding two spaces at the end of each line will make that line break. It would be great if you could add those. Thanks.

2019-06-23 12:49 UTC, moT01 commented on guide/english/accessibility/automated-testing/index.md
> +[W3C List of Web Accessibility Tools](https://www.w3.org/WAI/ER/tools/)
```suggestion
[W3C List of Web Accessibility Tools](https://www.w3.org/WAI/ER/tools/)  
```

2019-06-23 12:49 UTC, moT01 commented on guide/english/accessibility/automated-testing/index.md
> +[W3C Guide to Selecting Accessibility Tools](https://www.w3.org/WAI/test-evaluate/tools/selecting/)
```suggestion
[W3C Guide to Selecting Accessibility Tools](https://www.w3.org/WAI/test-evaluate/tools/selecting/)  
```

2019-06-23 12:49 UTC, moT01 commented on guide/english/accessibility/automated-testing/index.md
> +[Comparing 3 Top Automated Accessibility Tools](https://medium.com/myplanet-musings/comparing-3-top-automated-accessibility-testing-tools-wave-tenon-io-and-google-lighthouse-d3897d7bb311)
```suggestion
[Comparing 3 Top Automated Accessibility Tools](https://medium.com/myplanet-musings/comparing-3-top-automated-accessibility-testing-tools-wave-tenon-io-and-google-lighthouse-d3897d7bb311)  
```

2019-07-07 18:59 UTC, moT01 approved these changes
Looks good @rkrupnick - thanks for contributing to freeCodeCamp! 🎉

2019-07-07 18:59 UTC, merged