simplifying the mathematical solution for Sum All Numbers in a Range
freeCodeCamp/freeCodeCamp pull request #35007
Opened 2019-01-31 01:11 UTC by zhengfu23

We don't need to sort the two number array, using Math.abs() we can get the count of the numbers in range and calculate the sum.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-01-31 01:36 UTC, RandellDawson commented
Two more suggestions.  

1. Unless a variable's value needs to change later in the code, use `const` vs `let`.

2. If you are going to use `const`, go ahead and use arrow function syntax for the example instead of the traditional `function () { ... }`.

2019-01-31 01:41 UTC, zhengfu23 commented
@RandellDawson Thanks for the suggestion. Could you clarify what you mean by the `function () { ... }` part?

2019-01-31 01:44 UTC, RandellDawson commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-numbers-in-a-range/index.md
>      function sumAll(arr) {
Instead of:
```
function sumAll(arr) {
```
use:
```
const sumAll = (arr) => {
```

2019-01-31 01:45 UTC, RandellDawson requested changes
See my comment above regarding the `function` declaration.

2019-01-31 01:47 UTC, zhengfu23 commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-numbers-in-a-range/index.md
>      function sumAll(arr) {
I see! Fixed.

2019-01-31 01:54 UTC, RandellDawson commented
Don't forget to put a semi-colon after the final `}`.  Technically, it is not needed in this particular case, but it is a best practice to use it.

2019-03-20 08:41 UTC, thecodingaviator approved these changes
LGTM! 👍 Challenge tested on latest build of rocks. @RandellDawson merge if you feel it's fine

2019-03-20 13:51 UTC, RandellDawson approved these changes

2019-03-20 13:52 UTC, RandellDawson commented
@thecodingaviator Waiting for #34946 to be merged, but there are several PRs ahead of it that we are waiting either waiting for changes to be made or other things.

2019-03-27 16:56 UTC, thecodingaviator commented
@zhengfu23 Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

2019-03-27 16:56 UTC, thecodingaviator commented
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

2019-03-27 16:57 UTC, merged