fix: make border radius challenge Firefox compatible
freeCodeCamp/freeCodeCamp pull request #35009
Opened 2019-01-31 10:24 UTC by ojeytonwilliams

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34867 by changing the tests to check the radii of all four corners separately.

2019-02-06 09:35 UTC, Bouncey requested changes

2019-02-06 09:35 UTC, Bouncey commented on curriculum/challenges/english/01-responsive-web-design/basic-css/add-rounded-corners-with-border-radius.english.md
> +<script>
@ojeytonwilliams I think we should remove this

2019-02-06 09:44 UTC, ojeytonwilliams commented
Yeah, sorry about that!

On Wed, 6 Feb 2019, 10:39 Stuart Taylor <notifications@github.com wrote:

> *@Bouncey* requested changes on this pull request.
> ------------------------------
>
> In
> curriculum/challenges/english/01-responsive-web-design/basic-css/add-rounded-corners-with-border-radius.english.md
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/35009#discussion_r254194500>
> :
>
> > @@ -94,6 +94,10 @@ tests:
>      <button type="submit">Submit</button>
>    </form>
>  </main>
> +<script>
>
> @ojeytonwilliams <https://github.com/ojeytonwilliams> I think we should
> remove this
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/35009#pullrequestreview-200480509>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/APEdzqLEaQCVvdf3fp8WkhCDfPzDq-kdks5vKqLegaJpZM4acASj>
> .
>

2019-02-16 17:16 UTC, Bouncey approved these changes

2019-02-16 17:17 UTC, Bouncey commented
Thanks @ojeytonwilliams

2019-02-16 17:17 UTC, merged

2019-02-16 18:29 UTC, RandellDawson commented
@Bouncey I assume the same change needs to be made across all the other languages?  If so, @ojeytonwilliams would you be interested in updating those as well?

2019-02-18 13:25 UTC, ojeytonwilliams commented
Sure, I'd be happy to take a look.

2019-02-18 13:53 UTC, ojeytonwilliams commented
@Bouncey One thing I'm unsure about is the following: the translated tests typically fail at the validation stage (missing descriptions, syntax errors and so on).  Would it be better if I tried to make it pass the validation or just change the tests.

I'm a little unsure, because some of the fixes would require me to add placeholder data just to validate correctly.