Feat/add guide for writing solutions
freeCodeCamp/freeCodeCamp pull request #35041
Opened 2019-02-02 15:26 UTC by Dana94

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #34957

2019-02-03 16:55 UTC, raisedadead approved these changes

2019-02-03 22:01 UTC, ValeraS requested changes

2019-02-03 22:40 UTC, ValeraS approved these changes

2019-02-05 12:04 UTC, merged

2019-02-05 12:04 UTC, ahmadabdolsaheb commented
Thank you @Dana94