[Fix] Modified regex to allow spaces in one of the tests for challenge Apply a Style Until a Condition is Met with @while
freeCodeCamp/freeCodeCamp pull request #35100
Opened 2019-02-08 06:56 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Fixes 2nd problem reported in issue #34755 related to the incrementing of the index.  I modified the regular expression to allow spaces.

2019-03-05 10:57 UTC, thecodingaviator requested changes

2019-03-05 10:57 UTC, thecodingaviator commented on curriculum/challenges/english/03-front-end-libraries/sass/apply-a-style-until-a-condition-is-met-with-while.english.md
> +    testString: assert(code.match(/\$(.*)\s*?:\s*\$\1\s*\+\s*1;/gi), 'Your code should increment the counter variable.');
```suggestion
    testString: assert(code.match(/\$(.*)\s*?:\s*\$\1\s*\+\s*1\s*;/gi), 'Your code should increment the counter variable.');
```
This is a test case I came across while testing this locally, rest everything LGTM

2019-03-05 17:23 UTC, thecodingaviator approved these changes
Tested locally, LGTM 👍

2019-03-06 08:05 UTC, Manish-Giri approved these changes
LGTM. Thank You for your contribution.

2019-03-06 08:05 UTC, merged