Fix/search ui
freeCodeCamp/freeCodeCamp pull request #35146
Opened 2019-02-11 13:06 UTC by ahmadabdolsaheb

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-02-11 19:49 UTC, ahmadabdolsaheb commented
Thanks for the review @thecodingaviator.

2019-02-11 21:13 UTC, ValeraS commented on client/src/components/Header/header.css
> +.ais-Highlight-highlighted {
Try something more specific to remove `!important`
```suggestion
.fcc_searchBar .ais-Highlight-highlighted {
```

2019-02-14 14:37 UTC, ahmadabdolsaheb commented
Thanks @ValeraS for the help. I resolved it in the way you suggested. Also added media queries to the suggestions wrapper.

2019-02-15 10:43 UTC, ahmadabdolsaheb commented
@raisedadead @ValeraS this one is ready for Review/merge. screenshots are included in the issue.

2019-02-15 11:09 UTC, ValeraS submitted a review, later dismissed

2019-02-16 12:36 UTC, ahmadabdolsaheb commented
@raisedadead @ValeraS, 🙏

2019-02-16 21:13 UTC, ValeraS requested changes

2019-02-16 21:13 UTC, ValeraS commented on client/src/components/Header/header.css
> +.ais-Hits-item .ais-Highlight-highlighted {
```suggestion
.fcc_searchBar .ais-Highlight-highlighted {
```

2019-02-16 21:13 UTC, ValeraS commented on client/src/components/Header/header.css
> +.ais-Hits-item .fcc_suggestion_item {
```suggestion
.fcc_searchBar .fcc_suggestion_item {
```

2019-02-16 21:36 UTC, ValeraS approved these changes

2019-02-16 21:38 UTC, merged