Adding gulp as a prerequisite
freeCodeCamp/freeCodeCamp pull request #35152
Opened 2019-02-11 18:44 UTC by hestellez

Gulp executable is called during the npm installation, it throws an error if youn don't have it installed.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-02-11 20:34 UTC, RandellDawson commented
You already have similar changes in PR #35045 for this article you're editing, so we are closing this duplicate.😓

If you feel you have more to add, please feel free to open up a new PR.

Thanks again! 😊

---

> If you have any questions, feel free to reach out through [Gitter](https://gitter.im/FreeCodeCamp/Contributors) or by commenting below. 💬

2019-02-11 20:51 UTC, RandellDawson commented on docs/how-to-setup-freecodecamp-locally.md
> +| gulp                                        | `4.0`   | It's called in the [curriculum scripts](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/package.json) |
@raisedadead Is this necessary?

2019-02-12 06:47 UTC, raisedadead requested changes
Hi @hestellez 

Thanks for the PR. We have moved away from Gulp in most build tooling. The issue that you have faced looks like the leftovers from our previous setup.

We should rather move towards removing it completely.

If you are up for it, I would recommend updating this PR for removing it and the refactoring the dependent scripts around it.

Thanks.

2019-02-13 09:35 UTC, Bouncey commented
It was used when preparing the curriculum package for publishing to npm, which we do not do any more. It is also a `devDependency` of the curriculum project.
https://github.com/freeCodeCamp/freeCodeCamp/blob/3b9ae3d786bc26838a88210de361f7c543b287ea/curriculum/package.json#L58

If we do not plan on publishing the curriculum package any more, this can be removed

2019-02-13 17:34 UTC, hestellez commented
@raisedadead I'd love to try

2019-03-05 16:10 UTC, raisedadead commented
Closing as stale. Please open a fresh PR if you are interested.

2019-03-05 16:10 UTC, closed without merging