Typescript -> TypeScript (spanish)
freeCodeCamp/freeCodeCamp pull request #35204
Opened 2019-02-14 10:43 UTC by lipis

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-04-10 04:58 UTC, hestellez requested changes

2019-04-10 04:58 UTC, hestellez commented on guide/spanish/typescript/getters-setters/index.md
> +# Hechiceros y Setters
You could change the Hechiceros to Getters

2019-07-29 17:57 UTC, brianRey-glb commented on guide/spanish/angular/index.md
> +Angular (versiones 2.x y posteriores) es un marco de código abierto basado en TypeScript para desarrollar aplicaciones web front-end. Angular tiene las siguientes funciones como genéricos, escritura
You can replace it with 

> Angular (versiones 2.x y posteriores) es un framework de código abierto basado en TypeScript utilizado el desarrollo de aplicaciones web front end. Angular posee funcionalidades tales como genéricos, tipado estático y muchas de las características de ES6.

2019-08-10 00:18 UTC, RandellDawson commented
@lipis Can you please make the changes suggested by the users and fix the merge conflict?

Thank you.

2019-08-20 15:21 UTC, RandellDawson commented
After reviewing the PR again, since the scope of the PR was just to fix the "TypeScript" instances, just ignore the other change requests.  This PR LGTM.

2019-08-20 15:21 UTC, RandellDawson approved these changes

2019-08-20 15:21 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-08-20 15:41 UTC, merged