Fix/update challenges for basic html and html5
freeCodeCamp/freeCodeCamp pull request #35234
Opened 2019-02-15 20:25 UTC by aditijoshi14

Currently, for this following challenge:
https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list/
An empty string was being accepted. With this fix, it will not allow an empty string or whitespaces as an input. 

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (only English)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #18007

2019-02-15 20:44 UTC, RandellDawson commented
@aditijoshi14 You are probably wondering why you have a merge conflict.  You probably need to run:
`git pull --rebase upstream master` on your local branch with the changes and then resolve the conflict if it still exists.

2019-02-15 21:20 UTC, aditijoshi14 commented
@RandellDawson Thank you so much I was able to resolve the conflict.

2019-02-15 21:26 UTC, RandellDawson commented
I don't think you meant to have that other file on the PR did you?

2019-02-15 21:28 UTC, aditijoshi14 commented
Nope. I didn't mean to have the other file on this PR but I had to commit that to resolve the conflict. I apologize for the confusion.

2019-02-15 21:30 UTC, RandellDawson requested changes
Please see my requested changes.

2019-02-15 21:30 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list.english.md
> +    testString: assert($("ul li").filter(function(index){return $(this).text().trim().length === 0;}).length === 0, 'Make sure your <code>li</code> elements doesn\’t contain empty string or only whit
While your added test works fine, yo could use the same logic but simplify a bit.
```suggestion
    testString: assert($("ul li").filter((_, item) => !$(item).text().trim()).length === 0, 'Make sure your <code>li</code> elements don\’t contain an empty string or only white-space.');
```

2019-02-15 21:30 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-bulleted-unordered-list.english.md
> +  - text: Make sure your <code>li</code> elements doesn’t contain empty string or only whitespace.
Please make the following changes to the text.
```suggestion
  - text: Make sure your <code>li</code> elements don’t contain an empty string or only white-space.
```

2019-02-15 21:32 UTC, RandellDawson commented
Please see my suggestions above and remove the changes to that extra file from this PR.

Thank you.

2019-02-15 21:51 UTC, RandellDawson commented
You still have the other file on this PR.  In the future, before you start making changes, do a rebase on your master branch `git pull --rebase upstream master` and then checkout a new branch (`git checkout -b branchname`) before making changes for your next PR.  It appears this PR has some changes left over from another branch you made for another PR.

2019-02-15 21:52 UTC, RandellDawson commented
That is why your commit history for this PR goes all the way back to December 6, 2018.

2019-02-15 22:02 UTC, aditijoshi14 commented
I apologize for that. I will surely do that from next time. Do you happen to know if there is anyway I can delete that extra file from this PR?

2019-02-15 22:15 UTC, aditijoshi14 commented
If you want I can create a new branch, add changes into it and make a new pull request.

2019-02-15 22:20 UTC, RandellDawson commented
No, just keep this PR open and I will try to help you out.  It is a little more complicated, because you have made several other commits trying to resolve this and I get merge conflicts when I try to rebase your PR locally.  In the end it will be a good learning experience for both of us.  I don't have time to debug this now, but will reply later when I have some more time to work on this.

2019-02-15 22:21 UTC, RandellDawson commented
What happens if you `git pull --rebase upstream master on your local `ix/update-challenges-for-basic-html-and-html5` branch?  Do you get a merge conflict?

2019-02-16 19:51 UTC, aditijoshi14 commented
Yes, I get a marge conflict.

2019-02-16 20:45 UTC, aditijoshi14 commented
@RandellDawson  I was able to resolve the merge conflict and remove the extra file. Thank you so much for all your help!

2019-02-16 20:47 UTC, RandellDawson commented
Just out of curiosity, how did you finally remove it?  I figured out two ways to do it, but you beat me to it.

2019-02-16 21:19 UTC, RandellDawson commented
Can you visit the Contributer's channel?  I need to discuss something with you.

2019-02-16 21:47 UTC, aditijoshi14 commented
@RandellDawson  I actually synced my forked repo with FreeCodeCamp's repo, which I believe was giving me merge conflict in my third commit. My third commit was when I deleted the extra file from my PR directly. After syncing my forked repo, I reverted to the third commit and made the changes you suggested. 

I am currently in Contributor's channel in Gitter.

2019-02-16 22:39 UTC, RandellDawson approved these changes

2019-02-16 22:40 UTC, RandellDawson approved these changes

2019-02-16 22:41 UTC, RandellDawson commented
I have tested the changes locally and validate the new test added works as intended without any "side-effects" that I can see.

2019-02-17 20:19 UTC, ezioda004 approved these changes

2019-02-17 20:19 UTC, merged

2019-02-17 20:19 UTC, ezioda004 commented
Thank you @aditijoshi14 for your contribution and congratulations on your first PR merge to this repo! 🎉
Hope to see more contributions from you in the future.