fix(client): return an empty string for empty sections
freeCodeCamp/freeCodeCamp pull request #35274
Opened 2019-02-18 13:43 UTC by ValeraS

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

2019-03-01 14:45 UTC, Bouncey requested changes

2019-03-01 14:45 UTC, Bouncey commented on tools/challenge-md-parser/text-to-data.js
> +          const textArray = hasData
Can you add a test to cover this?

2019-03-01 16:10 UTC, ValeraS commented on tools/challenge-md-parser/text-to-data.js
> +          const textArray = hasData
done, is it ok?

2019-03-02 13:15 UTC, Bouncey commented
@ValeraS I have added some commits to the PR.

- Undo changes to the mock ast and the snapshot
- Add a second ast with no instructions for use in the new test

This ensures that we are still testing the output for a challenge with instructions and without.

Let me know if these changes are ok with you, then I can merge.

2019-03-02 13:15 UTC, Bouncey approved these changes

2019-03-02 15:08 UTC, ValeraS commented
It's ok, but I don't see the need. For these tests, it does no matter which section names we use. So we have tests for:
- contentful section
- empty section
- and the missing section
and they might not depend on challenge sections.

2019-03-04 08:30 UTC, Bouncey commented
You are right, yes. I failed to read the rest of the tests.

2019-03-04 08:56 UTC, merged