Adding a second solution with a "for" loop
freeCodeCamp/freeCodeCamp pull request #35299
Opened 2019-02-19 11:26 UTC by codingk8

+ adapted some texts to make the whole thing coherent
+ added some Useful links at the end of the article

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-02-19 11:38 UTC, codingk8 commented
Please let me know if I could have improved something in this PR.

2019-02-19 12:23 UTC, thecodingaviator requested changes
Please check and make the required changes

2019-02-19 12:23 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype/index.md
> +The THIS keyword gives us access to the object we are calling myMap on.
```suggestion
The `this` keyword gives us access to the object we are calling myMap on.
```

2019-02-19 12:23 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype/index.md
> +### Solution 1 - Solve this challenge using the keyword THIS and the forEach method
```suggestion
### Solution 1 - Solve this challenge using `this` and the forEach method
```

2019-02-19 12:23 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype/index.md
> +### Solution 2 - Solve this challenge using a "for" loop and the THIS keyword
```suggestion
### Solution 2 - Solve this challenge using a "for" loop and `this`
```

2019-02-19 12:23 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype/index.md
> +[This in MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)<br/>
```suggestion
[this. JavaScript MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)<br/>
```

2019-02-19 12:23 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype/index.md
> +[This in Javascript W3Schools](https://www.w3schools.com/js/js_this.asp)
```suggestion
[this. JavaScript W3Schools](https://www.w3schools.com/js/js_this.asp)   
```

2019-02-19 12:23 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype/index.md
> +[For loop in MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for)
```suggestion
[for loop MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for)   
```

2019-02-19 12:23 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype/index.md
> +[Array Prototype in MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype)
```suggestion
[Array.prototype MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype)   
```

2019-02-19 13:02 UTC, codingk8 commented
All done I guess. Thanks!

2019-02-19 14:53 UTC, thecodingaviator commented
I had used backticks for marking code, which you've changed to ", please set it back to `

2019-02-19 15:10 UTC, codingk8 commented
Right, sorry about that. Should be OK now. Thank!

2019-03-01 14:24 UTC, codingk8 commented
Sorry to bother you. It's been 10 days and it's still open. Is there a pb? Is it normal ? Thanks for letting me know 😃

2019-03-01 15:01 UTC, thecodingaviator commented
Yup, such waiting times are normal since we are still dealing with a lot of Pull Requests from October last  year. We're hierarchically going through the PRs from oldest to latest

2019-03-01 15:46 UTC, codingk8 commented
OK fine. It's good to know. So I just wait until it's merged.

2019-03-01 17:24 UTC, RandellDawson commented
@codingk8 There is only one PR ahead of yours in terms of the file you changed, but it affects many other files.  This means, we are having to review many other earlier PRs (about 20) which affect files on the other PR first.  Probably 1-2 weeks out is my guess.

2019-03-03 12:22 UTC, thecodingaviator commented
@RandellDawson Do we want the solutions to be named solution 1 and solution 2 or just solutions or intermediate and advanced, like how we have it in the other JS challenges

2019-03-03 16:21 UTC, RandellDawson commented
@thecodingaviator Personally, it does not matter since we have no true policy in the docs about this.  As you know, issue #35453 hopes to standardize and create a formal policy around these types of articles.

2019-03-28 10:42 UTC, thecodingaviator approved these changes
LGTM! :+1:

2019-03-28 12:31 UTC, thecodingaviator commented
Thanks for contributing to the freeCodeCamp repository. Congratulations on your first PR! 🎊 

Look forward to more contributions from you! ✈️

2019-03-28 12:31 UTC, merged