fix(docs) Corrected challenge template example
freeCodeCamp/freeCodeCamp pull request #35307
Opened 2019-02-20 02:25 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

I fixed the issue below and also attempt to resolve the suggestions requested by @ValeraS on an earlier PR which which became stale.

Closes #34208

2019-02-20 06:26 UTC, thecodingaviator approved these changes
Looks good

2019-02-20 07:09 UTC, ValeraS requested changes

2019-02-20 07:09 UTC, ValeraS commented on docs/how-to-work-on-coding-challenges.md
> +  testString: 'A stringified function possibly using Chai asserts'
We should mention somehow: `text` and `testString` strings should be valid YAML strings

2019-02-20 07:09 UTC, ValeraS commented on docs/how-to-work-on-coding-challenges.md
> +  testString: 'A stringified function possibly using Chai asserts'
A stringified function or expression possibly using Chai asserts

2019-02-20 07:14 UTC, ValeraS requested changes
And check open/close tags

2019-02-24 09:39 UTC, RandellDawson commented
@ValeraS OK, I think I covered everything you requested.  I put some more notes near the top regarding the `Tests` section.

2019-02-24 14:56 UTC, ValeraS commented on docs/how-to-work-on-coding-challenges.md
> +  testString: 'A stringified function possibly using Chai asserts'
@RandellDawson I did not mean to replace text to `bla bla`. I have shown missing line `tests:` and indentations.

2019-02-24 15:00 UTC, ValeraS commented
> And check open/close tags

Remove `</section>` before `### After tests

2019-02-24 16:58 UTC, RandellDawson commented
@ValeraS So sorry about that.  I must have a looked at that 10 times and did not see it.

2019-02-26 18:38 UTC, raisedadead approved these changes

2019-02-26 18:59 UTC, ValeraS approved these changes

2019-02-26 19:21 UTC, merged