fix(curriculum) Prevent 5th test from allowing invalid solution in Escape Sequences in Strings challenge
freeCodeCamp/freeCodeCamp pull request #35367
Opened 2019-02-22 22:48 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #17712

This PR fixes the issue referenced above and also corrects the `text` to correct display a single `\` instead of `\\` which was displaying before the fix.  Also, I took the opportunity to remove `message` from the assert which is no longer needed in all assert tests.

2019-03-04 06:57 UTC, thecodingaviator approved these changes
All the regexes have been tested on a regex tool to check that they do what the text says. LGTM! 👍

2019-03-04 14:58 UTC, moT01 requested changes
This passes when you add things between the first and second line. It seems as long as the 3 escaped characters are in there and in order, you can add anything in between them (sort of). These all pass...
`var myStr = "FirstLine\n\t\f\f\f\\SecondLine\nThirdLine"; // Change this line`
`var myStr = "FirstLine\n\t\n\f\\\\SecondLine\nThirdLine"; // Change this line`
`var myStr = "FirstLine\n\t\nasdfasdfasdf\f\\\\SecondLine\nThirdLine"; // Change this line`
`var myStr = "FirstLine\nasdfasdf\n\t\nasdfasdfasdf\f\\\\SecondLine\nThirdLine"; // Change this line
`
This doesn't seem to happen for between the second and third lines.

You could possibly add a final test to just make sure the string is exactly what's expected since there's only one way this should pass...
`var myStr = "FirstLine\n\t\\SecondLine\nThirdLine"; // Change this line`
Although if you do this test, you might not want to put the text as to give away the answer. Meaning it should not say "myStr should equal 'FirstLine\n\t\\SecondLine\nThirdLine'" - since it would give away the answer.

2019-03-04 15:24 UTC, RandellDawson commented
@moT01 It appears the existing `master` code let's the same code cases you mention about pass all the tests too.  I will think about it a bit more.

2019-03-04 21:09 UTC, RandellDawson commented
@moT01 , @thecodingaviator  Can you look at the new test I added to disallow code like the examples @moT01 showed above?  The extra test validates `myStr` is the only way to pass the challenge without telling them the answer.

2019-03-05 02:50 UTC, moT01 commented
The testing looks good now @RandellDawson - I can't pass anything that should fail - I think something like "myStr should match the expected output" might be a more accurate response for that last test.

2019-03-05 02:51 UTC, moT01 approved these changes

2019-03-05 12:58 UTC, Manish-Giri commented
Looks like I've posted on the issue, instead of the PR. Reposting from https://github.com/freeCodeCamp/freeCodeCamp/issues/17712#issuecomment-469488593 - 

---

I tested this locally, and the last test pretty much ensures there's only one (correct) way to pass the challenge.
 
I did notice that with this string - `'FirstLine\n\t\\SecondLine\n\n\ThirdLine';`, this test doesn't pass -
 
> There should be a newline character between SecondLine and ThirdLine
 
Based on the test requirement, there _is_, technically, a newline between `SecondLine` and `ThirdLine`. So, one could ask why the test won't pass. Maybe the text assert could be changed to -
 
> There should be **one** newline character between SecondLine and ThirdLine
 
But that's probably beyond the scope of this PR, and a good candidate for another PR.
 
Either way, LGTM.

2019-03-05 13:57 UTC, merged