Added pointer on putting whole solution in guide articles
freeCodeCamp/freeCodeCamp pull request #35390
Opened 2019-02-24 14:53 UTC by thecodingaviator

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-02-24 17:39 UTC, RandellDawson requested changes
@thecodingaviator What do you think about the following suggestions?

2019-02-24 17:39 UTC, RandellDawson commented on docs/style-guide-for-guide-articles.md
> +In the solution which you propose for the guide, the full code should be given i.e. the seed code with the changes which have been made to achieve the desired result.
```suggestion
When proposing a solution for curriculum challenge related article, the full code should be given.  This includes all the original seed code plus any changes needed to pass the all the challenge's tests.
```

2019-02-24 17:39 UTC, RandellDawson commented on docs/style-guide-for-guide-articles.md
> +## Solutions
```suggestion
## Curriculum Challenge Solutions
```

2019-02-25 09:29 UTC, thecodingaviator commented
@RandellDawson Those were definitely better than what I had proposed, I made some minor corrections to it and it should look better now

2019-02-28 03:11 UTC, Manish-Giri requested changes
Suggested some grammatical changes.

2019-02-28 03:11 UTC, Manish-Giri commented on docs/style-guide-for-guide-articles.md
> +When proposing a solution for a curriculum challenge related article, the full code should be given. This includes all the original seed code plus any changes needed to pass the all the challenge's t
```suggestion
When proposing a solution for a curriculum challenge related article, the full code should be given. This includes all the original seed code plus any changes needed to pass all the challenge tests.
```

2019-02-28 03:36 UTC, RandellDawson commented on docs/style-guide-for-guide-articles.md
> +When proposing a solution for a curriculum challenge related article, the full code should be given. This includes all the original seed code plus any changes needed to pass the all the challenge's t
I like @Manish-Giri's suggestion.

2019-03-01 16:45 UTC, RandellDawson approved these changes

2019-03-01 16:46 UTC, RandellDawson commented
@thecodingaviator Still awaiting some requested change on on a couple ealier PRs before merging this one.

2019-03-24 17:03 UTC, Nirajn2311 approved these changes
LGTM 👍

2019-03-24 17:04 UTC, merged

2019-03-24 17:05 UTC, Nirajn2311 commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

PS - @RandellDawson Since all other previous PRs were merged, I merged this one.