Port search page and search bar form search-assets
freeCodeCamp/freeCodeCamp pull request #35458
Opened 2019-02-28 16:46 UTC by Bouncey

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.

2019-02-28 17:01 UTC, RandellDawson commented
@Bouncey If I want to test this PR, is there a way to update the indexes, so I can see how the search functionality would work with all the changes and additions to the repo's guide and challenge files?

2019-02-28 17:31 UTC, Bouncey commented
It should work with the current indexes.

Re-indexing is a task unto itself, and something I wish to tackle separlately.

2019-02-28 18:10 UTC, RandellDawson commented
Oh OK.  There are about 5-10 open issues related to the indexes not being updated in a while, so I guess those will be resolved once you perform that separate task.  I was just anxious to maybe be able to close those too.

2019-02-28 18:17 UTC, raisedadead requested changes

2019-02-28 18:17 UTC, raisedadead commented on client/src/components/search/searchPage/SearchPageHits.js
> +              target='_blank'
```suggestion
              rel='noopener noreferrer'
              target='_blank'
```

Resolve the warning.

2019-02-28 18:18 UTC, raisedadead requested changes
There are few styling suggestions as well that I wanted to make based on https://github.com/freeCodeCamp/freeCodeCamp/issues/35103

Do you want to tackle them here, or wait for a future PR.

2019-02-28 18:20 UTC, raisedadead commented on client/package-lock.json
> +      "resolved": "http://registry.npmjs.org/bl/-/bl-1.2.2.tgz",
Something weird is happening with the lockfile. You may want to run `npm install --prefer-online` on root.

2019-02-28 18:21 UTC, raisedadead commented on client/src/components/Header/index.js
> +import FCCSearch from '../search/searchBar/SearchBar';
Is there a reason we want to call it `FCCSearch` vs `Search`

2019-03-12 14:32 UTC, ahmadabdolsaheb commented
@raisedadead I can sort the styles out as soon as this is merged.

2019-06-07 21:46 UTC, raisedadead approved these changes

2019-06-07 21:46 UTC, merged

2019-06-07 21:47 UTC, raisedadead commented
Thanks @Bouncey for the intial work and @ValeraS for taking this up. I have merged this to keep going forth.