feat/add-prev-next-btns-to-lessons
freeCodeCamp/freeCodeCamp pull request #35485
Opened 2019-03-02 00:06 UTC by moT01

I'm not sure if this is even wanted, as there wasn't much discussion on the issue about it. I think they're pretty slick, so I hope this feature/PR is taken into consideration.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/17509

2019-03-02 06:13 UTC, ahmadabdolsaheb commented
@moT01 so forward work as expected.
back takes me to undefined.
load the page with a new browser, go to map while signed in. go to the first challenge. then go forward and go backward. you will get undefined.

2019-03-02 06:57 UTC, raisedadead commented
Hi @moT01 

Thanks for the PR. 

We are currently under a feature freeze. I have left some explanation here: https://gitter.im/FreeCodeCamp/Contributors?at=5c7a23172ca5ec547462f85d

Will add more comprehensive communication in the an related issue thread soon.

2019-05-19 19:39 UTC, thecodingaviator approved these changes
Just tested it locally, awesome work! 🎊

2019-06-06 15:54 UTC, ojeytonwilliams approved these changes
I also gave it a whirl, LGTM!  I couldn't recreate the bug when going to previous challenges - it works just fine for me.

2019-06-06 15:58 UTC, RandellDawson commented
The bug I mentioned in the issue is no longer present.

2019-06-06 18:36 UTC, raisedadead commented
The community needs a feature --> we love the community --> let's do it right. 

Opening up for QA. Thanks @moT01 for the PR and everyone for playing with this.

2019-06-06 19:06 UTC, RandellDawson approved these changes

2019-06-06 19:16 UTC, thecodingaviator commented
We have three approvals. @QuincyLarson do you wanna take a look?

2019-06-06 19:41 UTC, raisedadead commented
> We have three approvals...

Just to be clear the dev-team QA is pending.

2019-06-07 16:17 UTC, ojeytonwilliams commented
Just to confirm what @moT01 said, the previous button linking to undefined only happens if you try to use the cache of a build without the buttons.

To reproduce:
* Rebase to master
* checkout master
* delete `client/.cache`
* `npm run develop`
* checkout the rebased branch
* `npm run develop`

In short: definitely not a bug.

2019-06-07 16:33 UTC, ojeytonwilliams reviewed
While playing around with it, I found the buttons resizing to be a bit odd:
![ResizingButtons](https://user-images.githubusercontent.com/15801806/59119270-a16b5400-8952-11e9-8593-801d291a07a0.gif)

Perhaps it's better if they don't change.

2019-06-07 16:33 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/challenge-title.css
> +.challenge-title-wrap > Button {
```suggestion
```
It looks a bit weird when the buttons resize, so I'd recommend leaving them fixed.

2019-06-07 16:33 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/challenge-title.css
> +  flex-grow: 2;
```suggestion
```
Seems redundant with the button `flex-grow` change below.

2019-06-07 16:33 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/challenge-title.css
> +  flex-grow: 1;
```suggestion
```

2019-06-07 16:33 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/challenge-title.css
> +}
```suggestion
```

2019-06-07 17:56 UTC, moT01 commented
Thanks for opening this up @raisedadead - and all the reviews everyone! I added @ojeytonwilliams suggestion to make the buttons a static size - as well as add a few properties to stop the buttons from jumping around so much like @RandellDawson mentioned in the issue

2019-06-11 22:20 UTC, raisedadead requested changes
Lets, make the button inverted. Please note that we want primary to be a call to action. And that should usually be one action item. It's already associated with run tests.

Next is the ability to be a11y complaint. Those `>` && `<` would hurt a11y. I have added some labels in the suggestion to make it complaint.

I am inclined that we should use text links instead of buttons, but that can come later.

2019-06-11 22:20 UTC, raisedadead commented on client/src/templates/Challenges/components/Challenge-Title.js
> +        <Button bsStyle='primary' onClick={() => navigate(prevChallengePath)}>
```suggestion
        <Button
          aria-label='Previous lesson'
          bsStyle='primary'
          className='btn-invert'
          onClick={() => navigate(prevChallengePath)}
        >
```

2019-06-11 22:20 UTC, raisedadead commented on client/src/templates/Challenges/components/Challenge-Title.js
> +        <Button
```suggestion
        <Button
          aria-label='Next lesson'
          bsStyle='primary'
          className='btn-invert'
          onClick={() => navigate(introPath ? introPath : nextChallengePath)}
        >
```

2019-06-11 22:22 UTC, raisedadead reviewed
Also some tests would be awesome, this is a great feature. Let's make it resilient.

2019-06-18 18:45 UTC, moT01 commented
I think I need some help coming up with tests for this - I took a look and couldn't come up with anything. Anyone want to work with me on it? or take a look or something?

2019-06-18 18:56 UTC, ojeytonwilliams commented
I'd be happy to work on this with you.  I'll be around on Gitter tomorrow.

2019-06-28 08:49 UTC, ahmadabdolsaheb commented
@raisedadead

2019-07-18 09:44 UTC, raisedadead approved these changes

2019-07-18 09:45 UTC, raisedadead commented
Nice work @moT01 on working on this. And thanks to everyone who tested this.

2019-07-18 09:46 UTC, merged

2019-07-21 23:03 UTC, moT01 commented
yay! 🎉 - thanks for merging this and all the reviews everyone!