Make a comparison in the test more accurately
freeCodeCamp/freeCodeCamp pull request #35500
Opened 2019-03-03 21:17 UTC by iliyaZelenko

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

2019-03-20 15:08 UTC, ojeytonwilliams commented
I agree that the example above should not pass.  However, if the dates are compared at the millisecond level, there's a small risk that the tests will randomly fail.  The two dates will not necessarily be created at the same millisecond (or the same month, for that matter, but that's incredibly rare).

I think it would be better to check that `magic` contains `new Date()` with a regex.

2019-03-27 04:28 UTC, RandellDawson commented
@iliyaZelenko Can you respond to @ojeytonwilliams's suggestion?

2019-03-27 06:59 UTC, iliyaZelenko commented
@ojeytonwilliams You are right that this method may sometimes not work correctly.



I reset the hours, minutes, seconds, milliseconds for better accuracy using `setHours`, I was inspired by [this answer](https://stackoverflow.com/questions/492994/compare-two-dates-with-javascript#comment10495421_493018).

Now not accuracy is minimized and the date will be checked by year, month and day.
  
Maybe I missed something? Is it better to do it through regexp?

2019-03-27 08:39 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2019-03-27 13:50 UTC, RandellDawson requested changes
Since we are working on this challenge anyway, let's fix the assert messages to make them more like all the rest in the curriculum (i.e. using `should`).

2019-03-27 13:50 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions.english.md
>    - text: User did replace <code>var</code> keyword.
```suggestion
   - text: User should replace <code>var</code> keyword.
```

2019-03-27 13:50 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions.english.md
>    - text: <code>magic</code> is a <code>function</code>.
```suggestion
   - text: <code>magic</code> should be a <code>function</code>.
```

2019-03-27 13:50 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions.english.md
>    - text: <code>magic()</code> returns correct date.
```suggestion
   - text: <code>magic()</code> should return correct date.
```

2019-03-27 13:50 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-arrow-functions-to-write-concise-anonymous-functions.english.md
>    - text: <code>function</code> keyword was not used.
```suggestion
   - text: <code>function</code> keyword should not be used.
```

2019-03-27 15:05 UTC, RandellDawson approved these changes

2019-03-27 15:06 UTC, RandellDawson commented
@ojeytonwilliams Are you OK with the changes made based on my suggestions?  If so, feel free to merge this PR.

2019-04-01 08:55 UTC, merged

2019-04-01 08:56 UTC, ojeytonwilliams commented
@iliyaZelenko Thanks for the contribution! Apologies for the delay in getting it merged.