Fixed Typographical Error in guide/english/accessibility/index.md
freeCodeCamp/freeCodeCamp pull request #35507
Opened 2019-03-04 07:37 UTC by iamrajiv

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-03-06 14:25 UTC, thecodingaviator requested changes

2019-03-06 14:25 UTC, thecodingaviator commented on guide/english/accessibility/index.md
> +Web accessibility also **benefits** people *without* disabilities. For example, a key principle of Web accessibility is designing Web sites and software that are flexible to meet different user needs
We use the American version of English for this project so `aging` is correct, please revert the change

2019-03-06 19:29 UTC, thecodingaviator approved these changes
LGTM! 👍

2019-03-07 17:20 UTC, iamrajiv commented
@RandellDawson is this PR good to be merged?

2019-03-07 17:24 UTC, RandellDawson commented
@iamrajiv This has been reviewed by @thecodingaviator, so he can make that decision.

2019-03-08 08:42 UTC, merged

2019-03-08 08:42 UTC, thecodingaviator commented
@iamrajiv Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝