added html solution for testing
freeCodeCamp/freeCodeCamp pull request #35516
Opened 2019-03-05 17:28 UTC by paulywill

The solution for testing; 
Tested against: https://github.com/freeCodeCamp/freeCodeCamp/pull/34711 

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

2019-03-20 20:44 UTC, lynxlynxlynx commented
Is this supposed to be failing? I see the other PR has already been merged.

2019-03-26 20:08 UTC, RandellDawson requested changes
@paulywill Please see my suggestions for what the correct solution should be.

2019-03-26 20:08 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +    opacity: 0.7;
```suggestion
```

2019-03-26 20:08 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +  }
```suggestion
```

2019-03-26 20:08 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +
```suggestion
    opacity: 0.7;
```

2019-04-12 15:47 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +  a {
I have pushed my suggested changes on behalf of user to avoid stale PR.

2019-04-12 15:48 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +    opacity: 0.7;
I have pushed my suggested changes on behalf of user to avoid stale PR.

2019-04-12 15:48 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +  }
I have pushed my suggested changes on behalf of user to avoid stale PR.

2019-04-12 15:48 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +
I have pushed my suggested changes on behalf of user to avoid stale PR.

2019-04-12 15:54 UTC, RandellDawson approved these changes

2019-04-12 16:17 UTC, merged

2019-04-12 16:17 UTC, ojeytonwilliams commented
@paulywill  Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo: