Added Advance Alternate Solution
freeCodeCamp/freeCodeCamp pull request #35524
Opened 2019-03-06 11:10 UTC by akmanon

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-03-06 12:24 UTC, thecodingaviator requested changes

2019-03-06 12:24 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sorted-union/index.md
> +![:rocket:](https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:") <a href='https://repl.it/@AshishKumar24/AdorableNeatCheckpoint' target='_blank' rel='nofollow'>Run Code</a
We're removing all external links like these from our repo. Please remove this

2019-03-06 12:24 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sorted-union/index.md
> +*   <a href='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat' target='_blank' rel='nofollow'>Flat</a>
Please change these links to markdown format

2019-03-06 14:33 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sorted-union/index.md
> +![:rocket:](https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:") <a href='https://repl.it/@AshishKumar24/AdorableNeatCheckpoint' target='_blank' rel='nofollow'>Run Code</a
I'm talking about this repl link when I refer to external links

2019-03-06 15:02 UTC, RandellDawson commented
I propose adding your reference links in the Relevant Links section back in.

@thecodingaviator Instead of adding another solution, let's use this Alternative Advanced solution to replace the existing Alternative Advanced solution.  They are almost identical in logic.

2019-03-06 15:17 UTC, thecodingaviator commented
@RandellDawson Sounds good. On a look, yes, this solution seems better

@akmanon Please go ahead and change the solution as @RandellDawson has requested above

2019-03-09 06:13 UTC, closed without merging

2019-03-09 13:46 UTC, RandellDawson commented
@akmanon Why did you close this PR?