Fix some UI issues
freeCodeCamp/freeCodeCamp pull request #35522
Opened 2019-03-06 09:46 UTC by ValeraS

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.

2019-03-07 14:03 UTC, raisedadead requested changes
Your PR:

![image](https://user-images.githubusercontent.com/1884376/53961885-bfd17180-410f-11e9-9456-8906c691f500.png)


On Master (Beta Site):

![image](https://user-images.githubusercontent.com/1884376/53961943-dd064000-410f-11e9-9787-8830397022e2.png)

2019-03-09 19:26 UTC, ValeraS commented
@raisedadead fixed

2019-03-11 11:23 UTC, ahmadabdolsaheb commented
Great work @ValeraS, LGTM @raisedadead.

2019-03-14 13:35 UTC, raisedadead approved these changes

2019-03-14 13:36 UTC, merged