Fixed Typographical Error in guide/english/blockchain/index.md
freeCodeCamp/freeCodeCamp pull request #35542
Opened 2019-03-07 18:29 UTC by iamrajiv

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-03-08 23:01 UTC, Manish-Giri commented on guide/english/blockchain/index.md
> +The first work on a cryptographically secured chain of blocks as described in 1991 by Stuart Haber and W. Scott Stornetta. They wanted to implement a system where documents' timestamps could not be t
> The first work on a cryptographically secured chain of blocks **was** described in 1991 by Stuart Haber and W. Scott Stornetta.

In this sentence, "was" acts as the verb. "as" can't work as a verb here. Please revert to "was".

You can add a hyphen here if you wish - "cryptographically secured" .

2019-03-08 23:02 UTC, Manish-Giri commented on guide/english/blockchain/index.md
> +1. Permissionless, public blockchains - these are not controlled by any single company or person. The blockchain is accessible to anyone to participate in. Bitcoin and Ethereum are examples of permis
"The" isn't required before consensus. Please revert.

2019-03-08 23:06 UTC, Manish-Giri commented on guide/english/blockchain/index.md
> +The words block and chain were used separately in Satoshi Nakamoto's original paper but were eventually popularized as a single word, the blockchain, by 2016. The term blockchain 2.0 refers to new ap
> as a single word, **the** blockchain, by 2016.

Again, "the" isn't required here. You can capitalize blockchain if you wish.

2019-03-08 23:11 UTC, Manish-Giri requested changes

2019-03-08 23:11 UTC, Manish-Giri commented on guide/english/blockchain/index.md
> +Another issue is its lack of regulation, or a central authority backing its currencies, which in the past has lead to huge increases in speculation, and ultimately crashes. An example of this is the
> poster child of **the** blockchain

Remove "the".

2019-03-18 20:38 UTC, iamrajiv commented
@Manish-Giri is this PR good to be merged

2019-03-19 03:35 UTC, Manish-Giri approved these changes
LGTM. Thank You for your contribution.

2019-03-19 03:35 UTC, merged