fix: Added assets, including missing favicons
freeCodeCamp/freeCodeCamp pull request #35568
Opened 2019-03-11 15:11 UTC by ojeytonwilliams

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This is a stab at fixing #35219.

The static/assets directory existed in the old version of the client and contained the missing favicons.  This PR simply restores that.  Some of these assets are pulled in by https://github.com/freeCodeCamp/freeCodeCamp/blob/43a0705a913819406000c5c1d63dbd359b18cc8c/client/src/head/favicons.js, but not all of them.  I assumed that all of them should be, but I wasn't sure.  If anyone knows better, let me know and I'll change things appropriately.

Sorry if this is a little less than perfect, but I figured I shouldn't delay given that this is on the critical path.

2019-03-14 13:05 UTC, raisedadead requested changes
A few minor changes. Could we use the existing plugin, or a better plugin and have it handled in gatsby to generate the manifest?

2019-03-14 13:05 UTC, raisedadead commented on client/static/assets/site.webmanifest
> +    "name": "Learn | freeCodeCamp",
```suggestion
    "name": "freeCodeCamp.org",
```

2019-03-14 13:05 UTC, raisedadead commented on client/static/assets/site.webmanifest
> +    "short_name": "Learn | freeCodeCamp",
```suggestion
    "short_name": "fCC",
```

2019-03-14 15:08 UTC, ojeytonwilliams commented
@raisedadead So, it turns out the Gatsby plugin is already generating a manifest and some icons.  I had thought the problem was due to a lack of assets, but it was just that trying and failing to find these assets confuses Firefox.  If they're never looked for, it is fine.

If you're happy with what that plugin produces, we can simply remove the redundant icons and manifest.  I'll update this PR so you can see that in action.

2019-03-15 19:24 UTC, raisedadead approved these changes

2019-03-15 19:28 UTC, raisedadead commented
Going to re-review the approach here.

2019-03-29 09:19 UTC, merged