Fixed Typographical Error in guide/english/css/index.md
freeCodeCamp/freeCodeCamp pull request #35626
Opened 2019-03-17 20:27 UTC by iamrajiv

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-03-18 15:13 UTC, thecodingaviator requested changes

2019-03-18 15:13 UTC, thecodingaviator commented on guide/english/css/index.md
> +      <style>
Change all the indentation to be 2 spaces per level please

2019-03-22 09:28 UTC, iamrajiv commented
@thecodingaviator is this PR good to be merged

2019-03-22 10:01 UTC, thecodingaviator commented
Yup @iamrajiv

2019-03-22 10:01 UTC, thecodingaviator approved these changes
LGTM! 👍

2019-03-22 10:02 UTC, merged

2019-03-22 10:02 UTC, thecodingaviator commented
@iamrajiv Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝