Fixed Typographical Error in guide/english/kotlin/index.md
freeCodeCamp/freeCodeCamp pull request #35625
Opened 2019-03-17 20:24 UTC by iamrajiv

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-03-22 17:33 UTC, iamrajiv commented
@thecodingaviator can you  review this

2019-03-22 19:02 UTC, thecodingaviator requested changes

2019-03-22 19:02 UTC, thecodingaviator commented on guide/english/kotlin/index.md
> +If you are someone who prefers doing things in a more manual way and does not want to tie yourself down to an editor/IDE you might wanna use the Kotlin compiler.
It was fine before

2019-03-23 06:49 UTC, thecodingaviator commented
@iamrajiv I've made a minor change on your behalf

2019-03-23 06:49 UTC, thecodingaviator approved these changes
LGTM! 👍

2019-03-23 10:14 UTC, merged

2019-03-23 10:14 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝