Fixed Typographical Error in guide/english/java/index.md
freeCodeCamp/freeCodeCamp pull request #35649
Opened 2019-03-21 19:08 UTC by iamrajiv

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-03-22 09:27 UTC, iamrajiv commented
@RandellDawson can you review this

2019-03-23 18:56 UTC, iamrajiv commented
@thecodingaviator can you review this

2019-03-23 19:31 UTC, Manish-Giri commented on guide/english/java/index.md
> +JAVA is one of the OBJECT-ORIENTED PROGRAMMING LANGUAGES, unlike C and FORTRAN which are procedural languages. The OBJECT ORIENTED concept of programming makes it much more efficient than procedural
```suggestion
JAVA is one of the object-oriented programming languages, unlike C and FORTRAN which are procedural languages. The object-oriented concept of programming makes it much more efficient than procedural languages. Basically, object orientation breaks the program into parts, which is decided by the programmer. Then the complete program is stored in the permanent memory, and when it is executed, only that part is brought to dynamic memory which is called by the programmer. Each such part is called a `class` and when it is called in the dynamic memory, it is called an `object`.
```

2019-03-23 19:34 UTC, Manish-Giri commented on guide/english/java/index.md
> +After finishing the installation, we can begin to understand the nitty gritty of the Java ecosystem. Java is an <a href='http://stackoverflow.com/questions/1326071/is-java-a-compiled-or-an-interprete
```suggestion
After finishing the installation, we can begin to understand the nitty gritty of the Java ecosystem. Java is an <a href='http://stackoverflow.com/questions/1326071/is-java-a-compiled-or-an-interpreted-programming-language' target='_blank' rel='nofollow'>interpreted and compiled</a> language, that is, the code we write gets compiled to bytecode and interpreted to run. We write the code in `.java` files, Java compiles them into <a href='https://en.wikipedia.org/wiki/Java_bytecode' target='_blank' rel='nofollow'>bytecode</a> which is run on a Java Virtual Machine or JVM for execution. The bytecode typically has a `.class` extension.
```

2019-03-23 19:35 UTC, Manish-Giri commented on guide/english/java/index.md
> +Java is a pretty secure language as it doesn't let your program run directly on the machine. Instead, your program runs on a Virtual Machine called JVM. This Virtual Machine exposes several APIs for
```suggestion
Java is a pretty secure language as it doesn't let your program run directly on the machine. Instead, your program runs on a virtual machine called the JVM (Java Virtual Machine). This virtual machine exposes several APIs for low-level machine interactions you can make, but other than that, you cannot play with machine instructions explicitly. This adds a huge bonus of security.
```

2019-03-23 19:36 UTC, Manish-Giri requested changes
@iamrajiv Please address the requested changes.

2019-03-23 19:46 UTC, iamrajiv commented
@Manish-Giri can you take a look, please

2019-03-23 20:01 UTC, Manish-Giri approved these changes
LGTM. Thank You for your contribution.

2019-03-23 20:01 UTC, merged