Add a solution for Finders Keepers challenge
freeCodeCamp/freeCodeCamp pull request #35655
Opened 2019-03-22 06:56 UTC by nikkiselev

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-03-22 13:47 UTC, RandellDawson requested changes
In addition to the change I requested in the code, please remove lines 77-79 and 85-87 as we no longer use this.  There is an outstanding PR which will remove all of these from existing challenges, but not from new challenges.

Also, we may use your solution to replace the Basic solution as it is short and simple.  We will let you know what we decide.

Thank you.

2019-03-22 13:47 UTC, RandellDawson commented on guide/english/certifications/javascript-algorithms-and-data-structures/basic-algorithm-scripting/finders-keepers/index.md
> +*   <a href='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find' target='_blank' rel='nofollow'>Array.prototype.find</a>
We prefer you to use markdown styling for the links.  See the [styling guide](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#links)

2019-03-23 14:38 UTC, nikkiselev commented
Hi @RandellDawson , I've updated the PR. 
Thanks

2019-03-23 14:54 UTC, RandellDawson approved these changes

2019-03-23 14:55 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-03-23 15:35 UTC, merged