feat(reCAPTCHA): add middleware to verify response
freeCodeCamp/freeCodeCamp pull request #35677
Opened 2019-03-25 16:35 UTC by raisedadead

2019-03-25 16:37 UTC, raisedadead commented
@bouncey your initial thoughts on this? Do I really need to promisify the call to the Google API?

2019-03-26 07:48 UTC, ValeraS requested changes
~~You need to rebase your branch for a correct CI build~~

2019-03-26 07:48 UTC, ValeraS commented on server/boot/donate.js
> +      return res.status(200).send({ error: 'Captcha validation failed' });
```suggestion
      return res.status(400).send({ error: 'Captcha validation failed' });
```

2019-03-26 07:48 UTC, ValeraS commented on server/boot/donate.js
> +    return request(verificationURL, function(error, response, body) {
Should it be a post request?

2019-03-26 08:49 UTC, raisedadead commented
Thanks @ValeraS ! The CI was erroring out for a random fail in one of the challenges, a restart fixed it. I have also applied your suggestions.

2019-03-26 09:08 UTC, ValeraS commented on server/boot/donate.js
> +    return request.post(verificationURL, function(error, response, body) {
And params need to place in a request body:
```suggestion
    return request.post({
      url:verificationURL,
      form: {
        secret: keys.recaptcha,
        response: captchaResponse,
        remoteip: remoteAddress
      }
    }, function(error, response, body) {
```

2019-03-29 14:40 UTC, Bouncey approved these changes

2019-03-29 14:40 UTC, merged