Typo Fix In guide / english / computer-hardware / rom / index.md
freeCodeCamp/freeCodeCamp pull request #35740
Opened 2019-04-02 18:29 UTC by iamrajiv

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-04-03 14:24 UTC, iamrajiv commented
@thecodingaviator please review this

2019-04-03 17:16 UTC, Manish-Giri requested changes
> to read the data off the disc

The usage of `off` is fine here. Please revert.

2019-04-03 17:16 UTC, Manish-Giri commented on guide/english/computer-hardware/rom/index.md
> +The CD-ROM is a type of compact disc storage object that requires the use of an optical laser to read the data of the disc. The devices used to read the data house the lasers and are called CD-ROM Dr
```suggestion
The CD-ROM is a type of compact disc storage object that requires the use of an optical laser to read the data off the disc. The devices used to read the data house the lasers and are called CD-ROM Drives. The disc itself is generally created in a factory and once made, is read-only. This is in contrast to the CD-R (compact disc recordable) medium which has the additional ability to hold new data.
```

2019-04-03 18:10 UTC, iamrajiv commented
@Manish-Giri thanks for correction

2019-04-05 22:19 UTC, Manish-Giri approved these changes
LGTM. Thank You for your contribution.

2019-04-05 22:19 UTC, merged