fix(curriculum): Improve Array Sort Challenge
freeCodeCamp/freeCodeCamp pull request #35756
Opened 2019-04-03 23:40 UTC by Manish-Giri

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

While reviewing #35746, I noticed that the Array Sort challenge doesn't mention anything about the details of how a regular compare function callback works, when one is provided to `.sort()`. I feel like this information is critical to implementing any sort function, especially if you don't want the default Unicode value based ordering during the sort.

This PR moves the details about the compare function that @RandellDawson added to the Hints section for the challenge, to the challenge itself.

2019-04-04 15:03 UTC, RandellDawson requested changes
@Manish-Giri Looks good, but see my one suggestion.

2019-04-04 15:03 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method.english.md
> +<strong>Note:</strong> JavaScript's default sorting method is by string Unicode point value, which may return unexpected results. Therefore, it is encouraged to provide a callback function to specify
I don't think we need this to be a note.  To me, it should just be part of the challenge description.
```suggestion
JavaScript's default sorting method is by string Unicode point value, which may return unexpected results. Therefore, it is encouraged to provide a callback function to specify how to sort the array items. When such a callback function, normally called <code>compareFunction</code>, is supplied, the array elements are sorted according to the return value of the <code>compareFunction</code>:
```

2019-04-05 14:44 UTC, RandellDawson approved these changes

2019-04-05 14:45 UTC, RandellDawson commented
@Manish-Giri Maybe need a rebase?

2019-04-05 22:09 UTC, Manish-Giri commented
@RandellDawson Done.

2019-04-07 08:11 UTC, thecodingaviator approved these changes
LGTM! 👍

2019-04-07 08:12 UTC, merged

2019-04-07 08:12 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝