fix(curriculum): Add solutions to Bootstrap challenges
freeCodeCamp/freeCodeCamp pull request #35789
Opened 2019-04-08 02:17 UTC by Manish-Giri

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to #35753

2019-04-10 19:42 UTC, RandellDawson approved these changes
LGTM

2019-04-23 18:26 UTC, ojeytonwilliams requested changes
I only found a couple of typos.  Looks great otherwise.

2019-04-23 18:26 UTC, ojeytonwilliams commented on curriculum/challenges/english/03-front-end-libraries/bootstrap/use-a-span-to-target-inline-elements.english.md
> +  <p>Things cats <span class="text-danger">love</span></p>
```suggestion
  <p>Things cats <span class="text-danger">love</span>:</p>
```

2019-04-23 18:26 UTC, ojeytonwilliams commented on curriculum/challenges/english/03-front-end-libraries/bootstrap/use-responsive-design-with-bootstrap-fluid-containers.english.md
> +
```suggestion
```

2019-04-25 02:01 UTC, moT01 approved these changes
This looks good to me. The two changes the @ojeytonwilliams mentioned could be added, then this can be merged. I do not have permission or I would commit them myself, I think it's your repo @Manish-Giri that is blocking me so you will have to do that quick.

2019-05-01 01:06 UTC, Manish-Giri commented
@RandellDawson @ojeytonwilliams @moT01 Thanks for the reviews, guys! Sorry, I've been away for a bit due to uni stuff, but I'm back now, so I'll take care of this one tonight.

2019-05-02 09:24 UTC, merged

2019-05-02 09:25 UTC, ojeytonwilliams commented
@Manish-Giri Thanks for sorting this out!