Modify test to allow grid-column: 2 / -1 as valid answer
freeCodeCamp/freeCodeCamp pull request #35786
Opened 2019-04-07 20:38 UTC by kylesureline

This lesson currently only allows `grid-column: 2 / 4;`, when `grid-column: 2 / -1;` would also do the trick. I think the lesson could introduce the concept here and I've modified both the lesson and test accordingly.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-04-10 09:49 UTC, ojeytonwilliams requested changes
Aside from the extra message, looks good to me.  Thanks for the PR!

2019-04-10 09:49 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/css-grid/use-grid-column-to-control-spacing.english.md
> +    testString: assert(code.match(/.item5\s*?{[\s\S]*grid-column\s*?:\s*?2\s*?\/\s*?(4|-1)\s*?;[\s\S]*}/gi), '<code>item5</code> class should have a <code>grid-column</code> property that has the val
```suggestion
    testString: assert(code.match(/.item5\s*?{[\s\S]*grid-column\s*?:\s*?2\s*?\/\s*?(4|-1)\s*?;[\s\S]*}/gi));
```
The extra message is no longer needed here, so we might as well get rid of it.

2019-04-12 04:16 UTC, kylesureline commented
Whoops, Good catch @ojeytonwilliams! And you're welcome. Glad to be able to give back!

2019-04-12 10:37 UTC, ojeytonwilliams approved these changes

2019-04-20 16:59 UTC, RandellDawson commented
To me, this is trying to introduce another way to solve the same problem.  There may be other ways to solve this challenge.  I recommend we figure out a way to test any solution which provides the desired effect without trying to use regex.  Then, we leave the existing challenge description alone (to simplify what the challenge is trying to teach) and put @kylesureline's solution in the guide as an alternate solution.  

The trick here is to figure out a way to test this without resorting to a complex regex.

2019-04-22 05:58 UTC, thecodingaviator commented
Does jQuery allow checking for CSS Grid properties, yet? We could try that

2019-04-22 18:36 UTC, RandellDawson commented
@thecodingaviator There may be some plugin for jQuery.  I came up with an idea which allows the user to use both solutions without having to add what @kylesureline wants to add to the challenge (which I believe belongs in the Guide as an alternate solution).  I have created PR # 35893 that validates the space taken up by the div with class="item5" is what we expect it to be.  I created a new test for this and modified the original text `text` and regex just to validate the `grid-column` property appears in the `item5` class definition.

2019-04-23 13:03 UTC, thecodingaviator commented
@RandellDawson Can you create a draft PR for what you have, I can put it down and have a look

2019-05-01 02:23 UTC, moT01 commented
I think I agree with @RandellDawson here, the description of this challenge is already on the long side.
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column) shows yet a third way this could be solved... `grid-column: 2/ span 2;` So should we add another paragraph to describe that?
If anything, I think these could be turned into new challenges to teach specifically that.
Thanks a bunch for the PR @kylesureline, but I vote to close this. I will leave it open for now until one more person weighs in.

2019-05-01 08:38 UTC, closed without merging