Fix/update challenges for responsive-web-design-principles
freeCodeCamp/freeCodeCamp pull request #35804
Opened 2019-04-09 21:26 UTC by aditijoshi14

Fixing test for  https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/create-a-media-query/ challenge. 

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (only English)
- [X] My changes do not use shortened URLs or affiliate links.

Closes issue #35785

2019-04-09 22:48 UTC, RandellDawson requested changes
@aditijoshi14 See my suggested changes.

2019-04-09 22:48 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md
> +    testString: assert($("style").text().replace(/\s/g ,'').match(/@media\(max-height:800px\)/g));
It is not necessary to escape `{` or `}`.

2019-04-09 22:48 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md
> +    testString: assert($("style").text().replace(/\s/g ,'').match(/@media\(max-height:800px\)\{p\{font-size:10px;\}\}/g));
It is not necessary to escape { or }.  Also, you should make the semi-colon optional if there are no other properties after a property/value pair.

2019-04-09 22:48 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md
> +    testString: assert($("style").text().replace(/\s/g ,'').replace(/@media.*\}/g, '').match(/p\{font-size:20px;\}/g));
It is not necessary to escape { or }.

2019-04-09 22:48 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md
> +
Remove this extra line:
```suggestion
```

2019-04-10 00:42 UTC, aditijoshi14 commented
@RandellDawson  Thank you so much for your suggestions. I made the changes requested.

2019-04-10 01:05 UTC, RandellDawson approved these changes

2019-04-10 06:15 UTC, Manish-Giri commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md
> +  - text: Your <code>p</code> element should have the <code>font-size</code> of 10px when the device <code>height</code> is less than or equal to 800px.
```suggestion
  - text: Your <code>p</code> element should have a <code>font-size</code> of 10px when the device <code>height</code> is less than or equal to 800px.
```

2019-04-10 06:17 UTC, Manish-Giri requested changes
Just some minor changes.

2019-04-10 06:17 UTC, Manish-Giri commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/create-a-media-query.english.md
> +  - text: Your <code>p</code> element should have initial <code>font-size</code> of 20px when device <code>height</code> is more than 800px.
```suggestion
  - text: Your <code>p</code> element should have an initial <code>font-size</code> of 20px when the device <code>height</code> is more than 800px.
```

2019-04-10 19:32 UTC, aditijoshi14 commented
@Manish-Giri  Thank you so much for your suggestion. I have committed your requested changed.

2019-04-10 21:26 UTC, Manish-Giri approved these changes
@aditijoshi14 LGTM. Thank You for your contribution. 💯

2019-04-10 21:26 UTC, merged