fix: add solution to binay agent guide article
freeCodeCamp/freeCodeCamp pull request #35885
Opened 2019-04-20 19:05 UTC by sanghyundev

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-04-23 13:12 UTC, thecodingaviator approved these changes
LGTM!

2019-05-02 12:31 UTC, thecodingaviator requested changes

2019-05-02 12:31 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/binary-agents/index.md
> +![:rocket:](https://forum.freecodecamp.com/images/emoji/emoji_one/rocket.png?v=3 ":rocket:") <a href='https://repl.it/repls/PointlessUltimateAddition' target='_blank' rel='nofollow'>Run Code</a>
```suggestion
```
Hi, thank you for your PR but now we are no longer accepting links or other resources (images, etc.) which are not under our control, i.e. which a user or service might remove and is not under our control.

Please remove this line

2019-06-25 18:23 UTC, RandellDawson commented
@thecodingaviator This PR has gone stale.

2019-06-25 19:58 UTC, RandellDawson commented
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

**Reason:** Since your PR was created, the master branch content has updated making some of your changes unnecessary or need to be reorganized to fit the current version.  Please re-sync your fork so you are looking at the latest version of master and then create a new PR if you find any changes warranted.  

Thank you and happy coding.

2019-06-25 19:58 UTC, closed without merging