Fix HSTS test in Infosec curriculum (#17593)
freeCodeCamp/freeCodeCamp pull request #35880
Opened 2019-04-18 18:36 UTC by Wocanilo

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #17593

The max-age attribute must be seconds, not miliseconds [1]

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

2019-04-18 19:29 UTC, RandellDawson commented
@Wocanilo It would also seem that https://glitch.com/#!/import/github/freeCodeCamp/boilerplate-infosec/ would need to be updated?

2019-04-19 04:37 UTC, Dharmin2108 commented
.

2019-04-19 04:39 UTC, Dharmin2108 commented
.

2019-04-19 04:40 UTC, Dharmin2108 commented
.

2019-04-19 04:45 UTC, Dharmin2108 commented
.

2019-04-19 04:50 UTC, Dharmin2108 commented
/

2019-04-19 04:57 UTC, Dharmin2108 commented
/

2019-04-19 05:00 UTC, Dharmin2108 commented
.

2019-04-19 05:02 UTC, Dharmin2108 commented
'

2019-04-19 06:50 UTC, Dharmin2108 commented
5

2019-04-19 12:31 UTC, madurachanna commented
This has to updated

2019-04-19 12:40 UTC, madurachanna commented
It has to updated

2019-04-19 12:42 UTC, madurachanna commented
It has to be updated

2019-04-19 12:44 UTC, madurachanna commented
It has to updated

2019-04-19 12:45 UTC, madurachanna commented
It has to updated

2019-04-19 16:47 UTC, Wocanilo commented
@RandellDawson True, I just made a pull request with the changes.

2019-07-07 20:43 UTC, moT01 commented
The glitch project would need to be updated as well? Not sure if the projects are pulled from the boilerplates or what. But yes, this change seem fine to me, but we probably want to change all the locations of this problem at the same time. Additionally - projects that have been completed in the past might not pass anymore - not sure if there's anything we can do about that.

2019-07-10 13:47 UTC, ojeytonwilliams commented
@moT01 Yeah, that's right, the glitch projects are built from the source on github, so as soon as the boilerplate is updated all new projects will use the updated code.  So, as you say, this will need to be synchronised.  Once we know that master is going live we can merge this and then merge the changes to the boilerplate as soon as this PR actually makes it to production.

@RandellDawson Do you know what we're doing with translations?  Still merging them?

2019-07-10 13:59 UTC, ojeytonwilliams requested changes
I'm not sure what, if anything, should be done about the other languages.  Anyways, I noticed one more conversion that was missed for the English.

2019-07-10 13:59 UTC, ojeytonwilliams commented on curriculum/challenges/english/06-information-security-and-quality-assurance/information-security-with-helmetjs/ask-browsers-to-access-your-site-via-https-only-with-helmet.hsts.english.md
>    - text: maxAge should be equal to 7776000 ms (90 days)
```suggestion
  - text: maxAge should be equal to 7776000 s (90 days)
```

2019-07-10 16:03 UTC, RandellDawson commented
@ojeytonwilliams We don't have to do anything for the other languages, because they will never be implemented into production.

2019-07-10 18:56 UTC, ojeytonwilliams commented
Thanks @RandellDawson.  Just that one remaining milli, then.

2019-07-18 17:37 UTC, RandellDawson commented
@Wocanilo Can you please make the last change @ojeytonwilliams suggested, so we can get this PR merged.  Unfortunately, you did not allow maintainers to make changes on your behalf, so we can not make the change for you.

Thank you.

2019-07-18 19:29 UTC, ojeytonwilliams commented
If @Wocanilo isn't available to address the review suggestions, we can just merge as is and then fix with another PR.

2019-07-18 19:43 UTC, Wocanilo commented
I just accepted the last change.

2019-07-18 20:04 UTC, RandellDawson approved these changes

2019-07-18 20:50 UTC, RandellDawson commented
@ojeytonwilliams Just need your approval.

2019-08-13 15:37 UTC, ojeytonwilliams approved these changes

2019-08-13 15:39 UTC, ojeytonwilliams commented
Sorry about the delay., this PR looks good now! My only concern is that the boilerplate will need changing as soon as master goes live.  Any ideas how best to do that?

2019-08-13 15:44 UTC, RandellDawson commented
@raisedadead What is the best way to implement what @ojeytonwilliams is asking?

2019-08-13 16:21 UTC, raisedadead commented
> Sorry about the delay., this PR looks good now! My only concern is that the boilerplate will need changing as soon as master goes live. Any ideas how best to do that?

We need to create a PR on the boilerplate-repo. Then on we wait for master to ship out and land this PR and the boilerplate PR all at the same time. It has to be orchestrated. 

The other option is to land the changes on the boilerplate, but not deploy it (someone actually goes into the Glitch account to pull the changes) untill master is shipped.

I am OK with either.

2019-08-13 16:49 UTC, ojeytonwilliams commented
@Wocanilo made https://github.com/freeCodeCamp/boilerplate-infosec/pull/5, so I think all we need is to do is set up a reminder for when master goes live.

2019-10-17 16:51 UTC, RandellDawson commented
@Wocanilo, @ojeytonwilliams, @raisedadead Now that `master` has been released to production, it is time to get the merge conflicts resolved and get this PR merged along with making sure the boilerplate PR is merged too.

2019-10-22 23:21 UTC, raisedadead commented
Because the OP deleted their fork, this will now land via https://github.com/freeCodeCamp/freeCodeCamp/pull/37469

2019-10-22 23:21 UTC, closed without merging