Initialize brancgh. Add problem and solution to reverse-a-queue-chall…
freeCodeCamp/freeCodeCamp pull request #35896
Opened 2019-04-22 21:33 UTC by anthonykyi

…enge.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-04-22 22:11 UTC, RandellDawson commented
Please review the instructions for [how to create a new challenge](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-curriculum-challenges.md).  Was this discussed in an issue prior to you creating this PR?

2019-04-28 19:45 UTC, anthonykyi commented
@RandellDawson This challenge was not discussed prior to creating this PR.
I was testing it to see if it would pass the test.  I found out the problems I had with it and I believe I resolved it.  If it needs anymore changing, please let me know.

2019-04-28 20:00 UTC, RandellDawson requested changes
In addition to the suggestion I made, I suggest adding other tests where the items are strings and are not in numeric or alphabetic order, or someone could just simply use `sort` method on the array.

2019-05-17 18:28 UTC, anthonykyi commented
@RandellDawson I added 1 additional test case as you suggested!
Tell me how it looks!

2019-05-19 00:22 UTC, anthonykyi commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/reverse-a-queue.english.md
> +1,2,3,4,5, the output will then be 5,4,3,2,1.s
@RandellDawson I just changed the code according to your suggested change!

2019-05-19 00:41 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/reverse-a-queue.english.md
> +1,2,3,4,5, the output will then be 5,4,3,2,1.s
You did not add additional tests like I specified above.

2019-05-19 00:53 UTC, anthonykyi commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/reverse-a-queue.english.md
> +1,2,3,4,5, the output will then be 5,4,3,2,1.s
I added the following test to include strings..
And I will get to enqueue and dequeue right away.

- text: Your stringed <code>data</code> should be a reverse of itself.
    testString: assert((function(){var testQueueString = new Queue(['hello', 'world']); testQueueString.reverse(); return JSON.stringify(testQueueString.data) === JSON.stringify(['world', 'hello'])}()), 'Your stringed <code>data</code> should be a reverse of itself' );

2019-05-19 00:59 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/reverse-a-queue.english.md
> +1,2,3,4,5, the output will then be 5,4,3,2,1.s
Your tests would use the enqueue method to add the multiple items to the queue.  I recommend having at least 4 items for the tests which adds the string items.

2019-07-03 16:02 UTC, thecodingaviator requested changes
The challenge would need to be added to `meta.json` before we can proceed with this

2019-08-13 15:36 UTC, RandellDawson commented
Hi @anthonykyi 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-08-13 15:36 UTC, closed without merging