Added Binary Search Tree Challenge
freeCodeCamp/freeCodeCamp pull request #35907
Opened 2019-04-24 23:21 UTC by anthonykyi

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-04-25 03:23 UTC, RandellDawson requested changes
See my one suggestion.  Also, you will need to update [meta.json](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/_meta/data-structures/meta.json) which defines the order in which the challenge will appear.

2019-04-25 03:23 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/check-if-binary-search-tree.md
> +The main distinction of a binary search tree is that the nodes are ordered in an organized fashion. Nodes have at most 2 child nodes that are placed to the right and the left based on if the node's v
```suggestion
The main distinction of a binary search tree is that the nodes are ordered in an organized fashion. Nodes have at most 2 child nodes (placed to the right and/or left) based on if the child node's value is greater than or equal to (right) or less than (left) the parent node.
```

2019-04-25 17:49 UTC, RandellDawson commented
@anthonykyi Also, you need to make sure the file is named properly.  It should actually be named:
`curriculum/challenges/english/08-coding-interview-prep/data-structures/check-if-binary-search-tree.english.md` since this is the English version of the challenge.

2019-06-11 01:01 UTC, RandellDawson approved these changes
LGTM

2019-06-11 01:01 UTC, RandellDawson commented
@raisedadead Need a core team review.

2019-06-11 01:31 UTC, raisedadead approved these changes

2019-06-11 03:35 UTC, Manish-Giri approved these changes
@anthonykyi LGTM. Thank You for your contribution.

2019-06-11 03:35 UTC, merged