fix: Moved instruction to proper place and removed assert text in Font Awesome challenges
freeCodeCamp/freeCodeCamp pull request #35928
Opened 2019-04-28 09:36 UTC by thecodingaviator

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-04-28 15:07 UTC, RandellDawson requested changes
See my suggestion and also need to fix merge conflicts.

2019-04-28 15:07 UTC, RandellDawson commented on curriculum/challenges/english/03-front-end-libraries/bootstrap/add-font-awesome-icons-to-all-of-our-buttons.english.md
> +Note: The <code>span</code> element is an acceptable alternative to the <code>i</code> element for the directions below.
```suggestion

<strong>Note:</strong> The <code>span</code> element is an acceptable alternative to the <code>i</code> element for the directions below.
```

2019-04-28 16:39 UTC, thecodingaviator commented
@RandellDawson Changes made

2019-04-28 17:05 UTC, RandellDawson approved these changes

2019-04-28 17:06 UTC, RandellDawson commented
@thecodingaviator OK, LGTM.

2019-04-29 13:51 UTC, merged

2019-04-29 13:51 UTC, ojeytonwilliams commented
@thecodingaviator Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo: