fix(learn): Added solution for invert binary tree data structures challenge
freeCodeCamp/freeCodeCamp pull request #35922
Opened 2019-04-25 21:28 UTC by StanimalTheMan

[ x ] I have read freeCodeCamp's contribution guidelines.
[ x ] My pull request has a descriptive title (not a vague title like Update index.md)
[ x ] My pull request targets the master branch of freeCodeCamp.
[ x ] None of my changes are plagiarized from another source without proper attribution.
[ x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
[ x ] My changes do not use shortened URLs or affiliate links.
Closes #35914

Maybe it's just me but I do not see a certifications subdirectory in the mock-guide directory anymore so I could not test on the local copy of fcc as I was told to here:

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-open-a-pull-request.md
#35511

2019-04-26 14:50 UTC, sil3nthill commented
hello , i think its better to test  run tests locally before ! 
with `npm run test `or `npm run test:curriculum` in your case .

2019-04-27 07:29 UTC, RandellDawson requested changes
@StanimalTheMan In addition to what @camperbot pointed out, you need to make sure all solutions include all original challenge seed and any changes to solve the challenge.  Both of the solutions you provide in the files you changed are only partial solutions.

2019-04-27 12:21 UTC, Dharmin2108 commented
j

2019-04-29 03:58 UTC, StanimalTheMan commented
Alright.  Thank you.

2019-04-30 00:21 UTC, StanimalTheMan commented
@RandellDawson When/if you can, please let me know if there is still something wrong.  Thank you.

2019-04-30 22:34 UTC, RandellDawson commented
@StanimalTheMan Would you mind using 2 space indentation per our style guides?  Other than that, I believe it looks good.

2019-05-01 01:29 UTC, StanimalTheMan commented
@RandellDawson Alright, I think I followed what you told me to do.  Thank you.

2019-05-14 07:49 UTC, ojeytonwilliams requested changes
We're moving away from using emojis in the guide (see [here](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/style-guide-for-guide-articles.md#images)), but other than that everything looks good.

2019-05-17 18:13 UTC, StanimalTheMan commented
@ojeytonwilliams thank you for the heads up. @RandellDawson Sorry for the late reply.  I see that you self-assigned the task; please let me know if you want me to still work on this.  Thank you.

2019-05-17 18:34 UTC, RandellDawson commented
You still need to make the change @ojeytonwilliams recommended.

2019-05-17 18:40 UTC, ojeytonwilliams commented
@StanimalTheMan yeah, I could have put it a bit better, but I did actually want you take the emojis out.

2019-05-23 20:59 UTC, RandellDawson requested changes
@StanimalTheMan My assignment just means I was going to be reviewing it. 

See my suggested changes as we have been removing the Problem Descriptions from these articles as it is just duplicated from the challenge itself.

2019-05-23 20:59 UTC, RandellDawson commented on guide/english/certifications/coding-interview-prep/data-structures/invert-a-binary-tree/index.md
> +Remember to use <a>**`Read-Search-Ask`**</a> if you get stuck. Try to pair program
```suggestion
```

2019-05-23 20:59 UTC, RandellDawson commented on guide/english/certifications/coding-interview-prep/data-structures/invert-a-binary-tree/index.md
> +### Problem Explanation:
``suggestion
```

2019-05-23 20:59 UTC, RandellDawson commented on guide/english/certifications/coding-interview-prep/data-structures/invert-a-binary-tree/index.md
> +To solve this problem, you should use a function to invert a binary tree.  A temp variable can possibly be used and a stack can work as well but doing so may require more memory.
```suggestion
```

2019-05-23 20:59 UTC, RandellDawson commented on guide/english/certifications/coding-interview-prep/data-structures/invert-a-binary-tree/index.md
> +
```suggestion
```

2019-06-03 08:47 UTC, ojeytonwilliams approved these changes

2019-06-11 19:40 UTC, RandellDawson approved these changes

2019-06-20 17:28 UTC, Manish-Giri approved these changes
@StanimalTheMan LGTM. Thank You for your contribution.

I'll make a PR in a bit to fix some formatting issues in the guide.

2019-06-20 17:28 UTC, merged