fix(curriculum): Improved the tests for Find the length of a String challenge
freeCodeCamp/freeCodeCamp pull request #35940
Opened 2019-04-29 19:50 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

I have noticed a few campers get confused regarding the test messages for this challenge.  The reason for the confusion is if the user changes the original setup code, but the code would still technically result in the correct solution, the test message would fail but the reason given would not match the reason stated because the test combines the following checks but displays "You should be getting the length of lastName by using .length like this: lastName.length." if either fail.
1. Check that the original setup code is not changed
2. Check the the user gets the length of lastName by using .length like this: lastName.length

See https://www.freecodecamp.org/forum/t/help-w-js-challenge-suspected-bug/274365 for the full discussion.

This PR creates an additional test to make sure the user does not change the original setup code which the tests use.

2019-04-29 20:22 UTC, ValeraS requested changes
we can delete an after test section.

2019-04-29 20:22 UTC, ValeraS commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/find-the-length-of-a-string.english.md
> +    testString: assert(typeof lastNameLength !== 'undefined' && typeof lastNameLength === 'number' && lastNameLength === 8);
```suggestion
    testString: assert(typeof lastNameLength !== 'undefined' && lastNameLength === 8); 
```

2019-04-29 20:30 UTC, RandellDawson commented
@ValeraS So we do not need the following for this challenge? That was already there.
````

### After Test
<div id='js-teardown'>
```js
if(typeof lastNameLength !== "undefined"){(function(){return lastNameLength;})();}
```
</div>

````

2019-04-29 20:36 UTC, ValeraS commented
I don't see why it needed.

2019-04-29 20:56 UTC, ValeraS approved these changes

2019-05-01 00:12 UTC, moT01 approved these changes
LGTM! Thanks @RandellDawson! There was no issue for this I take it?

2019-05-01 00:12 UTC, merged