Js every function
freeCodeCamp/freeCodeCamp pull request #35945
Opened 2019-05-01 09:21 UTC by fgkolf

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-05-01 09:46 UTC, fgkolf commented
pr reopened, separated some and every functions. For every function i kept my version which complies with the some function guide. Let me know if this is okay.

2019-05-03 15:57 UTC, thecodingaviator requested changes

2019-06-03 23:23 UTC, RandellDawson commented
@thecodingaviator This PR has gone stale.

2019-06-04 19:20 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2019-06-04 19:20 UTC, closed without merging