fix(guide) Replace invalid prism code block names
freeCodeCamp/freeCodeCamp pull request #35961
Opened 2019-05-03 20:11 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Related to #35960

This PR aims to resolve 95% of the issues related to issue #35960.  I will create a separate PR for the other 5% based on feedback given to my comment on the issue.

Since my changes only effect code blocks, I put everything on a single PR (note I did not check the box above regarding multiple languages on the same PR).  If these need to be broken down by language, I can do that if absolutely necessary.

I have keep all the commits (one for each type of replacement made) in case I need to revert any.  At the very end, I can squash them if necessary.

2019-05-04 00:02 UTC, RandellDawson commented
OK, I no longer see the prism warnings after my latest commits.

2019-05-08 15:01 UTC, ojeytonwilliams requested changes
Nice work!  There were a few \```sh and ```C++ that slipped through, but for the most part it looks great.  I didn't check the formatting of every file, but I did look at a semi-random sample and they all seemed fine.  After our discussion, I checked the XAML -> xml change and that looks fine to me.

One thing I wasn't sure how to do was build the guide in any language other than English.  Any ideas?

Just restate, because the comment order isn't what I thought it would be: there were some `jsx`s used in the redux section, but that's just pure JS.

2019-05-08 15:13 UTC, RandellDawson commented on guide/spanish/rust/installing-rust/index.md
>  ```sh
@ojeytonwilliams According to prism's supported languages, `sh` is not one of them.  We can use `bash` or `shell` for Bash.

2019-05-08 15:14 UTC, RandellDawson commented on guide/chinese/certifications/front-end-libraries/redux/dispatch-an-action-event/index.md
> +```jsx
@ojeytonwilliams `jsx` is supported by prism, so why not use it?

2019-05-08 15:15 UTC, RandellDawson commented on guide/chinese/certifications/front-end-libraries/redux/get-state-from-the-redux-store/index.md
> +```jsx
@ojeytonwilliams `jsx` is supported by prism, so why not use it?

2019-05-08 15:16 UTC, RandellDawson commented on guide/russian/cplusplus/terms-to-know-for-beginners/index.md
>  ```C++
Prism documentation shows `C++` needs to be `cpp`

2019-05-08 15:17 UTC, RandellDawson commented on guide/spanish/cplusplus/terms-to-know-for-beginners/index.md
>  ```C++
Prism documentation shows C++ needs to be cpp

2019-05-08 15:17 UTC, RandellDawson commented on guide/spanish/csharp/hello-world/index.md
>  ```sh
see my other related comment

2019-05-08 15:17 UTC, RandellDawson commented on guide/spanish/rust/installing-rust/index.md
>  ```sh
see my other related comment

2019-05-08 15:17 UTC, RandellDawson commented on guide/spanish/redux/tutorial/index.md
>  ```sh
see my other related comment

2019-05-08 15:18 UTC, RandellDawson commented on guide/chinese/rust/installing-rust/index.md
>  ```sh
see my other related comment

2019-05-08 15:18 UTC, RandellDawson commented on guide/chinese/cplusplus/terms-to-know-for-beginners/index.md
>  ```C++
see my other related comment

2019-05-08 15:24 UTC, ojeytonwilliams commented on guide/chinese/certifications/front-end-libraries/redux/get-state-from-the-redux-store/index.md
> +```jsx
See above

2019-05-08 15:26 UTC, RandellDawson commented on guide/chinese/certifications/front-end-libraries/redux/dispatch-an-action-event/index.md
> +```jsx
Fair enough.

2019-05-08 15:32 UTC, RandellDawson commented
@ojeytonwilliams  Thanks for the review.  Not sure how those extra lines got in there, but I must have messed up my regex replace in VS Code somehow.  I have committed all of your suggestions.

> One thing I wasn't sure how to do was build the guide in any language other than English. Any ideas?

I don't think the logic has been completely implemented yet but @raisedadead could answer better.

2019-05-08 15:43 UTC, raisedadead commented
You can locally build the guide or learn for available languages by changing the `LOCALE=english` in your `.env` files.

2019-05-08 15:46 UTC, RandellDawson commented
@raisedadead followup question:  When we use `npm run develop`, then guide is really just the `mock-guide` files.  Is there a way use `npm run develop` so that the complete guide is built out for a particular language using the actual guide folder?

2019-05-08 15:58 UTC, ojeytonwilliams commented
@RandellDawson You could edit `gatsby-config.js` as a quick hack.  There's a line 
```js
const selectedGuideDir = `../${
  env === 'production' ? 'guide' : 'mock-guide'
}/${locale}`;
```
That you'd want to change.

@raisedadead Yeah, I tried that, but there are errors in the challenge files, so `gatsby develop` never finishes.  I guess the solution is to just not build the challenges.  I'll see if I can do that without breaking things!

2019-05-08 15:58 UTC, ojeytonwilliams approved these changes

2019-05-08 16:54 UTC, raisedadead commented
With languages other than English you have to build the production bundle. Spoiler you need a really good machine that will survive the build. 

Then you can spawn the api app and the client app separately.

You want `gatsby serve` in client and dig into the server package json for the script to spin up the api.

2019-05-09 18:21 UTC, moT01 commented
You can copy all the stuff from the guide folder and paste in the mock-guide folder - that's how I usually test guide changes.

2019-05-10 19:53 UTC, RandellDawson commented
**Moderators:**  It appears we are going to have to wait a while to merge this one, because there are several PRs (across multiple languages before it which would result in merge conflicts) if merged first. I will start reviewing the English guide articles, but we will need members of the non-English language teams to help review the other non-English PRs.

2019-05-10 20:19 UTC, raisedadead commented
/cc @freeCodeCamp/translation-team @freeCodeCamp/moderators

2019-05-10 20:27 UTC, moT01 commented
looking at the contributors tool @RandellDawson - it looks like maybe 50 files have other PR's touching these files - you could remove those files from this PR and there would be no potential for conflicts - and we could maybe merge this faster

2019-05-10 20:46 UTC, RandellDawson commented
@moT01 I suppose I can revert the changes to the files on those specific earlier PRs and then go into each and add the prism support language to the triple backticks if needed.  That way, they will get the update, but not end up with a merge conflict.  What do you think?

2019-05-10 21:43 UTC, RandellDawson commented
I have successfully reverted the changes to the 42 files on earlier PRs which would have caused merge conflicts if this PR would have been merged.  Now, I will review the 68 PRs which had these 42 files and add an extra commit to fix the invalid prism code block names if needed.

2019-05-10 23:42 UTC, RandellDawson commented
OK.  I just went through the 68 PRs which contained the files 42 files I reverted earlier.  I made commits on those PRs so if they are merged, they will already have the correct code block names.

2019-05-12 01:38 UTC, moT01 requested changes
I took a look through these - nice job @RandellDawson! I found these few things that I think got missed. Other than those I think the rest looks good.

I did not test this locally - I simply looked through the diff

2019-05-12 02:43 UTC, RandellDawson commented
@moT01 OK, I committed the changes which I had missed.  I am thinking we should probably have one more moderator take a look at this PR before it gets merged.

2019-05-12 02:46 UTC, moT01 approved these changes

2019-05-15 16:39 UTC, Manish-Giri approved these changes
LGTM 💯

2019-05-15 17:02 UTC, ojeytonwilliams commented
@RandellDawson you mentioned taking another look - are you happy with the PR?

2019-05-15 17:05 UTC, RandellDawson commented
@ojeytonwilliams Yes I am happy with it now.  Feel free to merge it. Once this one is merged, I will be creating another PR for a related issue which deals with a ton of files which have a space between the triple backticks and the language specifier (like below).
````
``` js
// code goes here
```
````

2019-05-15 17:08 UTC, merged

2019-05-15 17:08 UTC, ojeytonwilliams commented
Thanks @RandellDawson for the hard work and @moT01 and @Manish-Giri for reviewing this monster!