docs: moved local docker setup into local setup file
freeCodeCamp/freeCodeCamp pull request #35975
Opened 2019-05-05 20:01 UTC by cmccormack

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

This PR was requested by @raisedadead and other FCC devs to remove redundant setup files to prevent having to make the same changes in multiple places.  @freeCodeCamp/dev-team  please review and provide suggestions to help improve the document if needed.

2019-05-05 20:23 UTC, raisedadead requested changes
![image](https://user-images.githubusercontent.com/1884376/57199854-afb80000-6fa1-11e9-8d27-f3a41b15e9b1.png)


You can use the preview button to check if the table will look good on commit.

2019-05-05 20:23 UTC, raisedadead commented on docs/how-to-setup-freecodecamp-locally.md
> +| Prerequisite | Version | Notes |
```suggestion

| Prerequisite | Version | Notes |
```

2019-05-05 20:23 UTC, raisedadead commented on docs/how-to-setup-freecodecamp-locally.md
> +| [Docker CE](https://docs.docker.com/install/) | `Stable` |       |
```suggestion
| [Docker CE](https://docs.docker.com/install/) | `Stable` | - |
```

2019-05-05 20:23 UTC, raisedadead commented on docs/how-to-setup-freecodecamp-locally.md
> +| Prerequisite | Version | Notes |
```suggestion

| Prerequisite | Version | Notes |
```

2019-05-06 08:30 UTC, raisedadead requested changes
I moved around some things to explain the context better. Let me know what you think. Thanks this is good to go.

2019-05-06 08:30 UTC, raisedadead commented on docs/how-to-setup-freecodecamp-locally.md
> +Only **one** of these methods is necessary. If you are having issues using one method, try using the other. If you do run into issues with either method, first perform a web search for your issue and
```suggestion
You are required to follow any **one** of the above methods. 

The Docker setup will ideally result in fewer errors during the installation process and aims to have the best developer experience. We use Docker to install and run the additional software dependencies behind the scenes. This should make it hassle free and consistent experience across most device/OS types.

If you are having issues using one method, try using the other. If you do run into issues with either method, first perform a web search for your issue and see if it has already been answered. If you cannot find a solution, please search our GitHub [issues](https://github.com/freeCodeCamp/freeCodeCamp/issues) page for a solution and report the issue if it has not yet been reported.

And as always, feel free to hop on to our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), for quick queries.
```

2019-05-06 08:31 UTC, raisedadead commented on docs/how-to-setup-freecodecamp-locally.md
> +The new Docker setup procedure *should* result in fewer, if not zero, errors during the setup process and make it easier for you. We use Docker to install and run many of the software dependencies wh
Remove here, move until the users reach the actual setup.

2019-05-07 15:43 UTC, cmccormack commented on docs/how-to-setup-freecodecamp-locally.md
> +
Thank you - glad you added it to this PR rather than to a new PR against the Docker setup doc!

2019-05-07 15:51 UTC, raisedadead approved these changes

2019-05-07 15:53 UTC, merged

2019-05-07 16:27 UTC, ojeytonwilliams commented on docs/how-to-setup-freecodecamp-locally.md
> +
No problem!  I'm glad I checked first...