fix(curriculum) Convert blockquote elements to triple backtick syntax for Responsive Web Design
freeCodeCamp/freeCodeCamp pull request #35993
Opened 2019-05-08 04:35 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

**PR Purpose:** Converts `blockquote` elements to triple backtick syntax in the `Description` and `Instructions` sections of the `Responsive Web Design` challenges.

Related to issue #35991

2019-05-08 15:41 UTC, thecodingaviator submitted a review, later dismissed
Check comments.

cc: @moT01 what do you think?

2019-05-08 15:41 UTC, thecodingaviator commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/adjust-the-background-color-property-of-text.english.md
> +```shell
```suggestion
```text
```
I think this should be text rather than shell

2019-05-08 15:41 UTC, thecodingaviator commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +```shell
```suggestion
```text
```
Same for this

2019-05-08 15:41 UTC, thecodingaviator commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/learn-about-complementary-colors.english.md
> +```shell
```suggestion
```text
```

2019-05-08 15:49 UTC, RandellDawson commented
@thecodingaviator `text` is not a valid prism language, so it would be the same as leaving off the `text`.

2019-05-08 16:42 UTC, ojeytonwilliams commented
It's slightly worse than that, we'd throw up an extra warning telling us off for using `text`.  Why not leave these as blockquotes?  They aren't code, after all.

2019-05-08 16:51 UTC, RandellDawson commented
@ojeytonwilliams I think the your idea of using blockquote could work, but why not just use triple backticks without the language.  The original goal was to make the backticks version look like the current blockquote.

2019-05-08 17:18 UTC, ojeytonwilliams commented
@RandellDawson Basically because those particular examples aren't actually code, so it's best not to embed them in code tags. 

My interpretation of the original goal was that we should be able to use backticks when we wanted to write code and have it look right.

2019-05-08 18:44 UTC, thecodingaviator commented
I’m with @ojeytonwilliams on this one. I think those should be changed to blockquotes

2019-05-08 19:21 UTC, RandellDawson commented
I will revert these back to their original blockquote syntax.

2019-05-08 19:25 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/adjust-the-background-color-property-of-text.english.md
> +```shell
Done

2019-05-08 19:26 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/decrease-the-opacity-of-an-element.english.md
> +```shell
Done

2019-05-08 19:28 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/learn-about-complementary-colors.english.md
> +```shell
Doine

2019-05-08 21:12 UTC, moT01 requested changes
For the most part, this looks good to me - I made a few suggestions, mostly some formatting that was probably already "wrong" before the PR - They could probably be fixed quick, but this could also be merged without fixing them.

2019-05-08 21:12 UTC, moT01 commented on curriculum/challenges/english/01-responsive-web-design/basic-css/use-css-selectors-to-style-elements.english.md
> +  h2 {color: red;}
```suggestion
  h2 {
    color: red;
  }
```

2019-05-08 21:12 UTC, moT01 commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.english.md
> + Here's a <a target="_blank" href="http://freecodecamp.org"> link to freecodecamp.org</a> for you to follow.
```suggestion
  Here's a <a target="_blank" href="http://freecodecamp.org"> link to freecodecamp.org</a> for you to follow.
```

2019-05-08 21:12 UTC, moT01 commented on curriculum/challenges/english/01-responsive-web-design/css-grid/place-items-in-grid-areas-using-the-grid-area-property.english.md
> +.item1 { grid-area: header; }
```suggestion
.item1 {
  grid-area: header;
}
```

2019-05-08 21:12 UTC, moT01 commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-principles/use-a-retina-image-for-higher-resolution-displays.english.md
> +```css
```suggestion
```html
```

2019-05-09 01:44 UTC, RandellDawson commented
@moT01 I committed the changes you requested.

2019-05-09 08:38 UTC, ojeytonwilliams requested changes
There're a few things I noticed, but the it bulk of it looks great.

2019-05-09 08:38 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/improve-chart-accessibility-with-the-figure-element.english.md
> +
```suggestion
  <br>
```
This `<br>` was intended to be part of the output, not just a line break.

2019-05-09 08:38 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility.english.md
> +
```suggestion
```

2019-05-09 08:38 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility.english.md
> +    <label for="one">Choice One</label>
```suggestion
    <label for="one">Choice One</label><br>
```
As before, the text `</br>` should appear.

2019-05-09 08:38 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility.english.md
> +
```suggestion
```

2019-05-09 08:38 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/wrap-radio-buttons-in-a-fieldset-element-for-better-accessibility.english.md
> +    <label for="two">Choice Two</label>
```suggestion
    <label for="two">Choice Two</label><br>
```
As before, the text `</br>` should appear.

2019-05-09 13:27 UTC, thecodingaviator reviewed
The general frame of the PR looks good to me. @ojeytonwilliams ' changes look fine to me

2019-05-09 14:22 UTC, RandellDawson commented
@ojeytonwilliams Thanks for catching those intended `<br>` elements I accidentally replaced.  I had a feeling I would probably mess up a few of these `<br>` elements in these HTML challenges.  I have committed your requested changes.

2019-05-09 15:21 UTC, moT01 approved these changes
Tested this again locally - LGTM 🎉

2019-05-10 11:13 UTC, ojeytonwilliams approved these changes

2019-05-10 11:16 UTC, ojeytonwilliams commented
Same here, everything LGTM!  @RandellDawson There's no need to wait for the rest of the PRs to be reviewed, we can merge once the reviewing is done, right?

2019-05-10 15:27 UTC, RandellDawson commented
@raisedadead Are you OK with us merging all the PRs related to #35991 once they have been reviewed?

2019-05-10 18:28 UTC, raisedadead commented
Yes, please go ahead if its mutually okay for fellow contributors.

2019-05-14 04:10 UTC, RandellDawson commented
@ojeytonwilliams, @thecodingaviator , @moT01 If we have a consensus that this is good to go, @raisedadead says it can be merged.  There are no earlier PRs ahead of this.  There is newer PR (#36041) and I will fix the merge conflict which will result of this being merged.

2019-05-14 07:43 UTC, thecodingaviator approved these changes
LGTM to be merged

2019-05-14 08:11 UTC, merged

2019-05-14 08:12 UTC, ojeytonwilliams commented
@RandellDawson Nice work!  Thanks everyone for checking this over.