fix(curriculum): Convert blockquote elements to triple backtick syntax for Coding Interview Prep
freeCodeCamp/freeCodeCamp pull request #35998
Opened 2019-05-08 04:41 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

**PR Purpose:** Converts `blockquote` elements to triple backtick syntax in the `Description` and `Instructions` sections of the `Coding Interview Prep` challenges.

Related to issue #35991

2019-05-13 15:06 UTC, ojeytonwilliams requested changes
Everything is rendering nicely!  Comments below.

2019-05-14 04:32 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-list.english.md
> +```js
OK, I reverted this one back in latest commit.

2019-05-14 04:32 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-list.english.md
> +  [1, 2], # Node1
OK, I reverted this one back in latest commit.

2019-05-14 04:32 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-list.english.md
> +  [0],    # Node2
OK, I reverted this one back in latest commit.

2019-05-14 04:32 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-list.english.md
> +  [0]     # Node3
OK, I reverted this one back in latest commit.

2019-05-14 04:32 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-matrix.english.md
> +```js
OK, I reverted this one back in latest commit.

2019-05-14 04:32 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/incidence-matrix.english.md
> +```js
OK, I reverted this one back in latest commit.

2019-05-14 04:32 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/incidence-matrix.english.md
> +```js
OK, I reverted this one back in latest commit.

2019-05-14 04:41 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-list.english.md
> +  [1, 2], # Node1
Fixed this in latest commit

2019-05-14 04:42 UTC, RandellDawson commented
@ojeytonwilliams I believe I have resolved this issues you pointed out.

2019-05-15 06:14 UTC, thecodingaviator approved these changes
LGTM

2019-05-15 07:39 UTC, ojeytonwilliams approved these changes

2019-05-15 07:39 UTC, ojeytonwilliams commented
@RandellDawson Yep, LGTM now, thanks.

2019-05-15 07:49 UTC, RandellDawson commented
Looks like we are just waiting on #35912 to be fixed/merged which is waiting on #35825 to be reviewed/merged.  I will try to offer a review on #35825 tomorrow.  I am going to sleep now.

2019-06-04 07:07 UTC, merged

2019-06-04 07:08 UTC, ojeytonwilliams commented
With #35912 being closed the potential conflicts went away.  Nice work, again!