Feat/imgur2 s3
freeCodeCamp/freeCodeCamp pull request #36007
Opened 2019-05-09 15:21 UTC by ahmadabdolsaheb

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

closes #35956

2019-05-09 16:54 UTC, raisedadead requested changes
Incorrect format for the CDN URL.

2019-05-09 16:54 UTC, raisedadead commented on guide/arabic/miscellaneous/storing-mongo-username--password-persistently-using-dotenv/index.md
> +[! \[Drake Main](https://s3.amazonaws.com/cdn-media-1.freecodecamp.org/imgr/jRaTj.jpg) \] (http://stackoverflow.com/users/4956243/drake-main) #### [أفضل الممارسات عند استخدام مفتاح API في Node.js](ht
This is an incorrect format for the URL. 
```suggestion
[! \[Drake Main](https://cdn-media-1.freecodecamp.org/imgr/jRaTj.jpg) \] (http://stackoverflow.com/users/4956243/drake-main) #### [أفضل الممارسات عند استخدام مفتاح API في Node.js](http://stackoverflow.com/questions/35356692/best-practice-when-using-an-api-key-in-node-js)
```

2019-05-09 16:56 UTC, raisedadead requested changes
Also make sure, you make no additional changes (including formatting) than swapping the image URLs.

2019-05-10 10:38 UTC, raisedadead commented
Just one more thought, you probably want to make lots of smaller PRs changing just a few files. This way your PR will not be held up due to merge conflicts.

/cc @freeCodeCamp/moderators

2019-05-10 10:55 UTC, ahmadabdolsaheb commented
@raisedadead I think I will be able to complete the whole thing today. Would I still need to make small prs?

2019-05-10 11:06 UTC, moT01 commented
If you search for your PR# [here](https://contribute.freecodecamp.org/dashboard/) - you can see what files would potentially create conflicts. You could maybe just remove those files from this PR and put them on a different one.

2019-05-10 15:06 UTC, thecodingaviator commented
> @raisedadead I think I will be able to complete the whole thing today. Would I still need to make small prs?

@ahmadabdolsaheb Yes please, that'll make it a lot easier

2019-05-15 14:41 UTC, ahmadabdolsaheb commented
@moT01, @thecodingaviator, the pr is divided in 8 prs. one pr is for files with potential conflicts. :)

2019-05-15 15:28 UTC, closed without merging

2019-05-16 21:15 UTC, RandellDawson commented
@ahmadabdolsaheb @raisedadead I have reviewed all 8 of the PRs referenced above and made suggested comments where applicable.  

The one question I have (even though it is probably bike-shedding) is if these are `imgur` images, shouldn't the base url be:
`"https://cdn-media-1.freecodecamp.org/imgur`
instead of the currently used url:
`"https://cdn-media-1.freecodecamp.org/imgr`

2019-05-16 23:41 UTC, ahmadabdolsaheb commented
@RandellDawson Thanks you for your review.  
That is a relevant question and shows your attention to details.

That was an attempt to make the url one letter shorter and still make the source recognizable. 

However, it would not matter a lot since all of them will be replaced with an environmental variable in the near future.

2019-05-16 23:49 UTC, RandellDawson commented
@ahmadabdolsaheb Did you mean to close this PR?