feat: add article for JavaScript String.valueOf()
freeCodeCamp/freeCodeCamp pull request #36017
Opened 2019-05-10 05:26 UTC by HasanAbdullah31

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-05-10 15:05 UTC, thecodingaviator requested changes

2019-05-10 15:05 UTC, thecodingaviator commented on guide/english/javascript/standard-objects/string/string-prototype-valueof/index.md
> +console.log(x);        // String {"hi"}
```suggestion
console.log(x); // String {"hi"}
```

2019-05-10 15:05 UTC, thecodingaviator commented on guide/english/javascript/standard-objects/string/string-prototype-valueof/index.md
> +console.log(x.valueOf());        // hi
```suggestion
console.log(x.valueOf()); // hi
```

2019-05-10 15:05 UTC, thecodingaviator commented on guide/english/javascript/standard-objects/string/string-prototype-valueof/index.md
> +*Note*: for String objects, `valueOf()` and `toString()` return the same thing.
```suggestion
*Note*: For String objects, `valueOf()` and `toString()` return the same thing.
```

2019-05-10 15:05 UTC, thecodingaviator commented on guide/english/javascript/standard-objects/string/string-prototype-valueof/index.md
> +**Example**
```suggestion
**Usage**
```

2019-05-10 15:05 UTC, thecodingaviator commented on guide/english/javascript/standard-objects/string/string-prototype-valueof/index.md
> +The `valueOf()` method returns the primitive string value of the given String object.
```suggestion
The `valueOf()` method returns the primitive string value of the given `String` object.
```

2019-05-16 19:30 UTC, HasanAbdullah31 commented
@thecodingaviator I added the changes you requested, check the file again.

2019-05-17 10:50 UTC, thecodingaviator approved these changes
LGTM

2019-05-17 10:51 UTC, merged

2019-05-17 10:51 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝