fix: update article for JavaScript String.indexOf()
freeCodeCamp/freeCodeCamp pull request #36012
Opened 2019-05-10 05:11 UTC by HasanAbdullah31

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-06-25 20:57 UTC, moT01 requested changes

2019-06-25 20:57 UTC, moT01 commented on guide/english/javascript/standard-objects/string/string-prototype-indexof/index.md
>  - MDN documentation: <a href='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf' target='_blank' rel='nofollow'>MDN</a>
[String.prototype.indexOf() on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf)

2019-07-05 19:27 UTC, RandellDawson commented
@moT01 Is this PR merge-ready?

2019-07-06 11:02 UTC, thecodingaviator approved these changes
LGTM. @moT01 merge at discretion

2019-07-06 16:08 UTC, moT01 approved these changes
Looks good @HasanAbdullah31 - thanks for contributing to freeCodeCamp! 🎉

2019-07-06 16:08 UTC, merged