Add "sapply function" guide to R guides
freeCodeCamp/freeCodeCamp pull request #36010
Opened 2019-05-10 04:51 UTC by nCarol595

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-05-10 05:14 UTC, RandellDawson commented
@nCarol595 I have not used `r` before, so I am not familiar with the syntax, but I tried to run the code examples on replt.it, but not sure how to do that to validate your examples work as intended.  I thought I should be able to copy/paste the example and run it to see a result, but it does not seem to work that way.  Is everything you are writing in the code block actual code or is some of it pseudo-code?

2019-05-11 13:02 UTC, erictleung requested changes
Thanks for taking the time to write this up! Good to see that R is being represented, but just a few concerns and suggestions to make this article better. Hope the feedback is helpful.

2019-05-11 13:02 UTC, erictleung commented on guide/english/r/functions/sapply-function/index.md
> +```r
```suggestion
```r
df <- data.frame(a = c(49, 12, 32, 21, 16), b = c(22, 39, 8, 54, 26))
```

2019-05-17 19:55 UTC, nCarol595 commented
@RandellDawson Thanks for the feedback, I will make the suggested changes to the article. Also thanks to @erictleung for the suggestions as well.

2019-06-28 07:23 UTC, RandellDawson commented
@nCarol595 Are you able to make these changes?

2019-07-04 05:25 UTC, RandellDawson commented
@erictleung Since the OP has not made the changes and it has been well over 21 days since we have last heard from the OP, I suggest you either make the suggested changes on behalf of the user or close this PR as stale.

2019-07-04 07:25 UTC, erictleung commented
@RandellDawson I can take a look at this in the next couple days. Thanks!

2019-07-06 00:06 UTC, erictleung approved these changes
Changes made and code is minimally reproducible.

2019-07-06 00:07 UTC, erictleung commented
@RandellDawson I've made the changes I've suggested. I think this should be a good start for this article. Let me know if you have any other suggestions on this starting article. Thanks!

2019-07-06 00:27 UTC, RandellDawson approved these changes

2019-07-06 00:27 UTC, merged

2019-07-06 00:27 UTC, RandellDawson commented
Thank you @nCarol595 and @erictleung for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉