fixed issue where tests should fail when code has error
freeCodeCamp/freeCodeCamp pull request #36029
Opened 2019-05-12 11:52 UTC by Stevo99

Signed-off-by: Stevo99 <Sfailla1983@gmail.com>

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-05-12 11:56 UTC, raisedadead commented
Thanks for the PR. Can you update the template above as well?

2019-05-12 13:37 UTC, RandellDawson commented
@Stevo99 Is this related to a current issue?  If so, make sure to state "Closes #issueNumber" in the PR instead of just leaving it "Closes #####".

Thanks.

Also, it is not necessary to put "Signed-off-by: Stevo99 Sfailla1983@gmail.com"

2019-05-12 13:45 UTC, Stevo99 commented
ok thanks!

2019-05-12 13:59 UTC, RandellDawson commented
@Stevo99 You have referenced this PR's number instead of an issue number.

2019-05-12 14:10 UTC, Stevo99 commented
hopefully I got it right now.  I got the number from the initial issue I first responded to.

2019-05-12 17:01 UTC, thecodingaviator commented
@Stevo99 it looks good now. Thanks

2019-05-13 16:08 UTC, ojeytonwilliams submitted a review, later dismissed
So, first off, the code does fix the problems in the issue.  However, I think it should be done a little differently, since it is a bit indirect.  Rather than updating the tests as failing, it tries to execute the tests (which we know will all fail) using the build error as a test runner.  This fails and so the tests are set as failing.  However, at first glance it's hard to understand *why* the code attempts to execute the tests in the catch block, since you should only reach it if something has gone wrong.

Instead, @ValeraS suggested, a better approach would be to start by setting the tests as failing. 
Then they can be passed to `executeTests` if the build passes or straight to `updateTests` if the build fails.  I think the logic is easier to follow this way.

2019-05-14 14:09 UTC, Stevo99 commented
I'm having trouble starting the tests as failing.  Should I be making the changes in `executeChallengeSaga()` function or somewhere else?

2019-05-18 16:08 UTC, ojeytonwilliams commented
Sorry @Stevo99, I completely missed your comment.  I didn't mean to leave you hanging.

> Should I be making the changes in executeChallengeSaga() function or somewhere else?

Mostly `executeChallengeSaga()`, yes. If you get the tests there instead of in `executeTests()`, you can set them as failing (each test needs the property `pass: false`) and pass them to `executeTests()` along with the test runner.  That way if the build fails, the tests still count as failing, even though they're never executed.  Let me know if that works or not.

2019-05-18 16:22 UTC, Stevo99 commented
No prob I know you guys are busy and I feel bad bothering you lol. Ok I was close let me go back and see if I can get it now thanks!

2019-05-22 20:43 UTC, Stevo99 commented
I made those changes and it didn't work.  I believe it would work but the logic has to change a little bit in `executeTests()`.  I've been trying to figure it out for the last few days but unfortunately have not been able to.  Let me know if you have any ideas. thanks!

2019-05-22 21:29 UTC, ojeytonwilliams commented
How about I have a go at solving it and add a commit to this PR? That way you'll still be credited for the work you've put into this. If you could review the code, since you've been looking at this, that would help with the QA. How does that sound?

2019-05-22 22:17 UTC, Stevo99 commented
Yea that sounds good to me.  Thanks!

2019-05-23 08:23 UTC, ojeytonwilliams commented
@ValeraS could you take a look?

2019-05-23 11:46 UTC, ValeraS requested changes

2019-05-23 11:46 UTC, ValeraS commented on client/src/templates/Challenges/redux/execute-challenge-saga.js
> +      test.err = 'build failed';
IMO, it's better to mark tests as not executed:
```js
	const tests = (yield select(challengeTestsSelector)).map(
      ({ text, testString }) => ({ text, testString })
    );
    yield put(updateTests(tests));
```

2019-05-23 11:46 UTC, ValeraS commented on client/src/templates/Challenges/redux/execute-challenge-saga.js
> +function* executeTests(testRunner, tests) {
```suggestion
function* executeTests(testRunner, tests, testTimeout = 5000) {
```

2019-05-23 11:46 UTC, ValeraS commented on client/src/templates/Challenges/redux/execute-challenge-saga.js
> +    testResults = yield executeTests(testRunner, tests);
```suggestion
    const testResults = yield executeTests(testRunner, tests);
```

2019-05-23 11:46 UTC, ValeraS commented on client/src/templates/Challenges/redux/execute-challenge-saga.js
> +    yield put(updateTests(testResults));
```suggestion
```

2019-05-26 10:49 UTC, ojeytonwilliams commented
@ValeraS I made the requested changes.  There was a webpack error when I used the syntax you suggested (not sure why, it's fine).  That's why I ended up using a longer expression.

2019-05-26 20:57 UTC, ValeraS approved these changes

2019-05-26 21:00 UTC, merged

2019-05-26 21:07 UTC, ojeytonwilliams commented
Huh.  That definitely didn't work on my machine, but it does now.  Not sure what changed.