fix(client): Vague Error messages
freeCodeCamp/freeCodeCamp pull request #36047
Opened 2019-05-15 08:58 UTC by thecodingaviator

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
~- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)~
- [x] My changes do not use shortened URLs or affiliate links.

Closes #17413

2019-06-09 00:29 UTC, raisedadead requested changes

2019-06-09 00:29 UTC, raisedadead commented on api-server/common/models/User-Identity.js
> +          ${provider} did not return a valid email address.
Fix the indentation like it was originally.

2019-06-09 00:29 UTC, raisedadead commented on api-server/common/models/User-Identity.js
> +          Please try again with a different account that has an
Fix the indentation like it was originally.

2019-06-09 00:29 UTC, raisedadead commented on api-server/common/models/User-Identity.js
> +    email associated with it or modify permissions to allow us to view your email.
```suggestion
    email associated with it or update the settings on ${provider}, for us to be able to retrieve your email.
```

2019-06-09 00:29 UTC, raisedadead commented on api-server/server/boot/authentication.js
> +          message: 'We could not log you out, please try logging out again.',
```suggestion
          message: 'We could not log you out, please try again in a moment.',
```

2019-06-09 00:29 UTC, raisedadead commented on api-server/server/boot/authentication.js
> +          message: 'We could not log you out, please try logging out again.',
Give them the impression, that something is delayed on our side.

2019-06-09 00:29 UTC, raisedadead commented on api-server/server/boot/user.js
> +        message: 'Your report cannot be empty. Please add information.'
```suggestion
        message: 'Your report cannot be empty. Please add details for us to be able to address your concern.'
```

2019-06-09 00:29 UTC, raisedadead commented on api-server/server/boot/user.js
> +    } else if (!report || report === '') {
This conditional is not valid. What happens when `username`, `report` both are null/undefined?

2019-06-09 00:29 UTC, raisedadead commented on api-server/server/middlewares/error-handlers.js
> +      handled.message || 'Oops! Something went wrong. Please try again';
```suggestion
      handled.message || 'Oops! Something went wrong. Please try again in a moment.';
```

2019-06-09 11:11 UTC, thecodingaviator commented on api-server/common/models/User-Identity.js
> +    email associated with it or modify permissions to allow us to view your email.
How about `update your settings on ${provider}`?

2019-06-09 11:41 UTC, raisedadead requested changes
This entire block is anti-pattern. Why? Repetitive, Complex and difficult to read.

```js
    if (!username && (!report || report === '')) {
      return res.json({
      return res.json({
        type: 'danger',
        type: 'danger',
        message: 'Oops, something is not right please re-check your submission.'
        message: 'Please enter a valid username and add details for us to be able to address your concern.'
      });
    } else if ((!report || report === '') && username) {
      return res.json({
        type: 'danger',
        message: 'Your report cannot be empty. Please add details for us to be able to address your concern.'
      });
    } else if (!username) {
      return res.json({
        type: 'danger',
        message: 'Please enter a valid username.'
      });
      });
    }
    }
```
You should re-factor this to be a simple return early pattern.

2019-06-09 11:44 UTC, raisedadead commented
Finally I have noticed that you depend on the CI for while fixing up PRs, IMHO you should test things locally before pushing to ease the notifications barrage it triggers for everyone subscribed to the thread.

2019-06-19 14:29 UTC, raisedadead approved these changes

2019-06-19 14:30 UTC, raisedadead commented
You should probably have different returns for each of those last validations on username and report, returning early. Anyways I'll merge this.

2019-06-19 14:31 UTC, merged