fix: replace imgur to s3 for arabic guide files with no conflict
freeCodeCamp/freeCodeCamp pull request #36051
Opened 2019-05-15 13:42 UTC by ahmadabdolsaheb

(cherry picked from commit 96a14a1f278c12e0123216813ab27076b1bcdb66)

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Reference #36007

2019-05-16 20:58 UTC, RandellDawson requested changes
@ahmadabdolsaheb See my two suggested changes.

2019-05-16 20:58 UTC, RandellDawson commented on guide/arabic/cplusplus/tokens-variables/index.md
> +    https://cdn-media-1.freecodecamp.org/imgr/
Is this line a mistake?
```suggestion
```

2019-05-16 20:58 UTC, RandellDawson commented on guide/arabic/cplusplus/tokens-variables/index.md
> +https://cdn-media-1.freecodecamp.org/imgr/
Is this line a mistake?
```suggestion
```

2019-05-16 23:18 UTC, ahmadabdolsaheb commented
@RandellDawson thanks for the suggestions. It should be alright now.

2019-05-17 00:04 UTC, RandellDawson approved these changes

2019-05-17 00:04 UTC, RandellDawson commented
@ahmadabdolsaheb OK, this PR looks good now.

2019-05-19 13:53 UTC, ahmadabdolsaheb commented
I edited some spaces out, this should be good to go

2019-05-20 19:46 UTC, thecodingaviator commented on guide/arabic/css/properties/background-position-property/index.md
> +  background-image: url('https://cdn-media-1.freecodecamp.org/imgr/6Z2VStD.png');
Referring just so we don't forget this in the other PR we've discussed

2019-05-20 19:51 UTC, thecodingaviator approved these changes
LGTM

2019-05-20 19:52 UTC, merged

2019-05-20 19:52 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝