fix: repalce imgur with s3 for russian guide without conflict
freeCodeCamp/freeCodeCamp pull request #36055
Opened 2019-05-15 14:20 UTC by ahmadabdolsaheb

(cherry picked from commit ac90750e36b0dd1fe508c69a2277b75be48e4b95)

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Reference #36007

2019-05-16 21:08 UTC, RandellDawson requested changes
@ahmadabdolsaheb See my requested changes.

2019-05-16 21:08 UTC, RandellDawson commented on guide/russian/cplusplus/tokens-variables/index.md
> +    https://cdn-media-1.freecodecamp.org/imgr/
This seems like it does not belong here.
```suggestion
```

2019-05-16 21:08 UTC, RandellDawson commented on guide/russian/cplusplus/tokens-variables/index.md
> +https://cdn-media-1.freecodecamp.org/imgr/
This seems like it does not belong here.
```suggestion
```

2019-05-16 23:24 UTC, ahmadabdolsaheb commented
thanks @RandellDawson, your suggestions have been implemented.

2019-05-17 00:01 UTC, RandellDawson approved these changes

2019-05-17 00:02 UTC, RandellDawson commented
@ahmadabdolsaheb OK, this PR looks good now.

2019-05-19 14:34 UTC, ahmadabdolsaheb commented
I double checked this. it should be good to go.

2019-05-23 11:58 UTC, ahmadabdolsaheb commented
@thecodingaviator, how does this look?

2019-05-24 20:50 UTC, thecodingaviator commented on guide/russian/css/properties/background-position-property/index.md
> +  background-image: url('https://cdn-media-1.freecodecamp.org/imgr/6Z2VStD.png');
Just putting it out here that we need to get on this when we get to the curriculum PR

2019-05-24 20:52 UTC, thecodingaviator approved these changes
Rest LGTM

2019-05-24 20:53 UTC, merged

2019-05-24 20:54 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝