fix: replace imgur to s3 for Chinese guide without conflict
freeCodeCamp/freeCodeCamp pull request #36052
Opened 2019-05-15 13:46 UTC by ahmadabdolsaheb

(cherry picked from commit 21e3afaee0f23d700f76ea662bc193b392fc54ac)

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Reference #36007

2019-05-16 21:01 UTC, RandellDawson requested changes
@ahmadabdolsaheb See my requested changes.

2019-05-16 21:01 UTC, RandellDawson commented on guide/chinese/cplusplus/index.md
> +https://cdn-media-1.freecodecamp.org/imgr/
Is this line needed?
```suggestion
```

2019-05-16 21:01 UTC, RandellDawson commented on guide/chinese/cplusplus/tokens-variables/index.md
> +https://cdn-media-1.freecodecamp.org/imgr/
Is this line needed?
```suggestion
```

2019-05-16 23:19 UTC, ahmadabdolsaheb commented
@RandellDawson, they should be resolved now.

2019-05-17 00:03 UTC, RandellDawson commented
@ahmadabdolsaheb OK, this PR looks good now.

2019-05-17 00:03 UTC, RandellDawson approved these changes

2019-05-19 14:35 UTC, ahmadabdolsaheb commented
I double checked this. it should be good to go.

2019-05-23 11:59 UTC, ahmadabdolsaheb commented
@thecodingaviator, I would appreciate it If you could take a look into this.

2019-05-24 21:09 UTC, thecodingaviator approved these changes
LGTM

2019-05-24 21:09 UTC, merged

2019-05-24 21:09 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝