fix: replace imgur with s3 for Portuguese guide without conflict
freeCodeCamp/freeCodeCamp pull request #36054
Opened 2019-05-15 14:01 UTC by ahmadabdolsaheb

(cherry picked from commit 55e786f8dbcf917e16088be97e18c951d937cd71)

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Reference #36007

2019-05-16 21:04 UTC, RandellDawson requested changes
@ahmadabdolsaheb See my suggested changes.

2019-05-16 21:04 UTC, RandellDawson commented on guide/portuguese/cplusplus/index.md
> +https://cdn-media-1.freecodecamp.org/imgr/
Is this line needed?
```suggestion
```

2019-05-16 21:04 UTC, RandellDawson commented on guide/portuguese/cplusplus/tokens-variables/index.md
> +    https://cdn-media-1.freecodecamp.org/imgr/
Is this line needed?
```suggestion
```

2019-05-16 21:04 UTC, RandellDawson commented on guide/portuguese/cplusplus/tokens-variables/index.md
> +https://cdn-media-1.freecodecamp.org/imgr/
Is this line needed?
```suggestion
```

2019-05-16 23:21 UTC, ahmadabdolsaheb commented
@RandellDawson, this should be ready now.

2019-05-17 00:02 UTC, RandellDawson approved these changes

2019-05-17 00:03 UTC, RandellDawson commented
@ahmadabdolsaheb OK, this PR looks good now.

2019-05-19 13:22 UTC, ahmadabdolsaheb commented
i made a few changes, so This should be ready to go.

2019-05-23 11:59 UTC, ahmadabdolsaheb commented
@thecodingaviator, I would appreciate it If you could take a look into this.

2019-05-24 21:00 UTC, thecodingaviator approved these changes
LGTM

2019-05-24 21:00 UTC, merged

2019-05-24 21:00 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝