Add comments and update callback arguments' names
freeCodeCamp/freeCodeCamp pull request #36082
Opened 2019-05-18 12:21 UTC by GK-Hynes

I've added a few comments to the solution and given the callback arguments more descriptive names to clarify what the solution is doing, since this challenge seemed a little more complex than the previous challenges.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-05-18 15:01 UTC, RandellDawson requested changes
@GK-Hynes Your changes are good, but I have one recommendation.

2019-05-18 15:01 UTC, RandellDawson commented on guide/english/certifications/javascript-algorithms-and-data-structures/functional-programming/use-the-reduce-method-to-analyze-data/index.md
> +      .reduce((rating1, rating2) => rating1 + rating2)
While we are making parameter names more readable, the first parameter represents the accumulator so:
```suggestion
      .reduce((sumOfRatings, rating) => sumOfRatings + rating) 
```

2019-05-19 14:04 UTC, RandellDawson commented
After reviewing this again, I realize it is not using two-space indentation.  Also, I think find it better if the watchList variable is on the same line of the `=`.
```js
var averageRating = watchList
  // Use filter to find films directed by Christopher Nolan
  .filter(film => film.Director === "Christopher Nolan")
  // Use map to convert their ratings from strings to numbers
  .map(film => Number(film.imdbRating))
  // Use reduce to add together their ratings
  .reduce((sumOfRatings, rating) => sumOfRatings + rating) 
  // Divide by the number of Nolan films to get the average rating 
  / watchList.filter(film => film.Director === "Christopher Nolan").length;
```

2019-05-19 16:34 UTC, GK-Hynes commented
Sorry about the indentation discrepancy. Having watchlist on the same line as the `=` also seems sensible.

2019-05-19 17:45 UTC, RandellDawson approved these changes
LGTM

2019-05-19 17:45 UTC, merged

2019-05-19 18:06 UTC, GK-Hynes commented
Thanks for helping me to make it a better contribution.