added-basic-information-about-javascript-and-links
freeCodeCamp/freeCodeCamp pull request #36092
Opened 2019-05-20 08:32 UTC by rajat2502

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-05-20 20:02 UTC, thecodingaviator commented on guide/english/certifications/javascript-algorithms-and-data-structures/basic-javascript/index.md
> +Javascript (often abbreviated as "JS") , invented by "Brendan Eich" , is a high level,dynamic programming language which when combined with HTML can convert static websites into Dynamic Websites(havi
```suggestion
JavaScript (often abbreviated as "JS"), invented by "Brendan Eich", is a high level, dynamic programming language which when combined with HTML can convert Static Websites into Dynamic Websites (having some functionality). It is one of the most versatile languages of all time, finding applications in almost all domains from Machine Learning to Data Scraping and Web Development.
```

2019-05-20 20:58 UTC, RandellDawson requested changes
I don't think we want to push campers away from the site for an overview in a Guide article for a challenge intro section?

2019-05-21 10:16 UTC, rajat2502 commented
I have made the required changes please do the review again.

2019-05-24 10:10 UTC, jamiehaywood approved these changes

2019-05-24 20:37 UTC, thecodingaviator commented
The PR adds info about JS but nothing about what the curriculum would teach to the campers in general. How do you think about adding something @ojeytonwilliams @moT01 @RandellDawson ?

2019-06-03 09:12 UTC, ojeytonwilliams commented
I agree with @thecodingaviator.  This is the guide article for the challenges, not JavaScript in general.  This article should probably be something like

> This section contains guides to help you better understand individual lessons from the [curriculum](https://learn.freecodecamp.org/).  To learn more about JavaScript in general, take a look at its section in the [guide](https://guide.freecodecamp.org/javascript)

The more general description in this PR could be incorporated into the main JavaScript article, but I don't think it belongs here.

2019-06-26 17:24 UTC, RandellDawson commented
Hi @rajat2502 ,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-06-26 17:24 UTC, closed without merging