Fix/revise es6 import lessons
freeCodeCamp/freeCodeCamp pull request #36144
Opened 2019-05-30 14:08 UTC by moT01

Draft for a slight revision of es6 import lessons

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to #36063

2019-06-02 08:40 UTC, thecodingaviator reviewed
~@moT01 If you're done, please squash commits. Makes it easier as you already know~

2019-06-06 12:52 UTC, ojeytonwilliams requested changes
Nice PR!  Everything looks good, except for the meta duplication.  Literally the only thing I thought could have been done differently was to allow `export { subtract as default };` as a solution.  However, I appreciate we can't cover everything, so perhaps it's better as is.

Regardless, if you sort out meta.json, I'm happy to approve this.

2019-06-06 12:52 UTC, ojeytonwilliams commented on curriculum/challenges/_meta/es6/meta.json
> +    [
```suggestion
```

2019-06-06 12:52 UTC, ojeytonwilliams commented on curriculum/challenges/_meta/es6/meta.json
> +      "587d7b8c367417b2b2512b55",
```suggestion
```

2019-06-06 12:52 UTC, ojeytonwilliams commented on curriculum/challenges/_meta/es6/meta.json
> +      "Reuse Javascript Code Using import"
```suggestion
```

2019-06-06 12:52 UTC, ojeytonwilliams commented on curriculum/challenges/_meta/es6/meta.json
> +    ],
```suggestion
```

2019-06-07 08:38 UTC, ojeytonwilliams approved these changes

2019-06-07 08:38 UTC, ojeytonwilliams commented
LGTM :+1:

2019-06-25 22:58 UTC, RandellDawson commented
@moT01 Overall I think you have made significant improvements to the existing challenges and added some valid new challenges.

Regarding the use of exporting functions using `default` and importing them, I think one thing missing is that a function does not even need a name in the `export default`.  It can be an anonymous function.  Also, the import can be any name when importing a default function.  The way the challenges are currently written, it implies there must be a function name specified in the `export default` and that when importing a default function, that it must be referenced by the same name.  

I am not exactly sure how best to add this verbiage to make it clear, but I believe the `export default` challenge should allow the user to not specify a named function and the challenge dealing with importing a default function should make it clear the function could be named something different if the export had a named function.

2019-06-26 03:42 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/create-an-export-fallback-with-export-default.english.md
> +Here is a couple examples using <code>export default</code>:
```suggestion
Here are examples using <code>export default</code>:
```

2019-06-26 03:44 UTC, RandellDawson requested changes
New changes look good.  The `Here is a couple examples` seemed like incorrect grammar.  We can avoid that with my suggestion.

2019-06-26 15:29 UTC, RandellDawson approved these changes

2019-06-27 14:39 UTC, RandellDawson commented
@scissorsneedfoodtoo Just waiting on @ojeytonwilliams final review of this PR, but we also need a core team member to approve before we merge.

2019-06-27 15:08 UTC, ojeytonwilliams approved these changes
Sorry for the delay, LGTM!

2019-06-28 08:04 UTC, scissorsneedfoodtoo approved these changes
Everything LGTM - thank you @moT01 :+1: :+1:

2019-06-28 08:05 UTC, merged