fix(client): for a11y, add role "application" to input monaco editor
freeCodeCamp/freeCodeCamp pull request #36154
Opened 2019-05-31 22:05 UTC by xnt

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

<img width="729" alt="Screen Shot 2019-05-31 at 6 03 20 PM" src="https://user-images.githubusercontent.com/309783/58737204-ae29fe00-83ce-11e9-892c-ae19a410a885.png">

Closes #36153

2019-06-04 08:02 UTC, ojeytonwilliams requested changes
Thanks for the PR!  
Regrettably the role prop is ignored by `MonacoEditor`, so the best bet is probably just to wrap the editor in a div with that role.

2019-06-04 15:12 UTC, xnt commented on client/src/templates/Challenges/classic/Editor.js
> +          role={'application'}
Awwww, bummer! Didn't look into it. I'll find a workaround when I have a downtime, thanks!

2019-06-04 15:27 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/Editor.js
> +          role={'application'}
Thanks.  Good luck!

2019-08-17 21:46 UTC, closed without merging

2019-08-17 21:46 UTC, raisedadead commented
Please feel free to open a fresh pull-request when ready.