fix/es6-destructuring-reword+new-lesson
freeCodeCamp/freeCodeCamp pull request #36201
Opened 2019-06-07 15:24 UTC by moT01

- Added new lesson "Use Destructuring Assignment to Extract Values from Objects" to teach destructure without renaming variables.
- Rewrote "Use Destructuring Assignment to Assign Variables from Objects" to focus on destructure+renaming
- Rewrote "Use Destructuring Assignment to Assign Variables from Nested Objects" to align with the other lessons - and since the example there was abstract, I thought it could use it.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #35574

2019-06-20 14:18 UTC, ojeytonwilliams requested changes
This is a massive improvement on how it was done before, nice job!

Comments follow.

2019-06-20 14:18 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects.english.md
> +Using a similar object from previous examples:
```suggestion
Using an object similar to previous examples:
```

2019-06-20 14:18 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects.english.md
> +And here's how you can assign new variable names when destructuring a nested object like this:
```suggestion
And here's how you can assign new variable names when destructuring a nested object:
```
I think this is a little better.

2019-06-20 14:18 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects.english.md
> +Replace the two assignments with an equivalent destructuring assignment. It should still assign the variables <code>lowToday</code> and <code>highToday</code> the values of <code>today.low</code> and
```suggestion
Replace the two assignments with an equivalent destructuring assignment. It should still assign the variables <code>lowToday</code> and <code>highToday</code> the values of <code>today.low</code> and <code>today.high</code> from the <code>LOCAL_FORECAST</code> object.
```

2019-06-20 15:06 UTC, ojeytonwilliams approved these changes

2019-06-20 15:07 UTC, ojeytonwilliams commented
Thanks, @moT01, LGTM :+1:

2019-06-26 16:50 UTC, lasjorg commented
Was asked to chime in. I think this looks great, so much better. :+1: 

I do have one question, do we want to use the word "field" when talking about an object property/key?

> You may read it as "get the field name and copy the value into userName" and so on.

This doesn't seem to match the terminology used in the curriculum, or am I wrong?


Other than that it LGTM, great work. @moT01

2019-06-26 19:10 UTC, moT01 commented
Thanks for the review @lasjorg - I changed it slightly

2019-06-26 19:15 UTC, RandellDawson requested changes
@moT01 See my slight change in the verbiage.

2019-06-26 19:15 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects.english.md
> +You may read it as "get the value of <code>user.name</code> and copy it into <code>userName</code>" and so on.
```suggestion
You may read it as "get the value of <code>user.name</code> and assign it to a new variable named <code>userName</code>" and so on.
```

2019-06-26 22:05 UTC, RandellDawson approved these changes

2019-06-26 22:17 UTC, lasjorg commented
This might be splitting hairs, but I would prefer the use of `property` or `key` over `variable` when talking about objects.

2019-06-26 22:34 UTC, RandellDawson commented
> This might be splitting hairs, but I would prefer the use of property or key over variable when talking about objects.

To which sentence are you referring?

2019-06-26 22:41 UTC, lasjorg commented
All of them. Any mention of a property as a variable.

2019-06-26 22:53 UTC, RandellDawson commented
@lasjorg I see what you mean now.  Feel free to request how you would word them differently.  I would support it.

2019-06-26 23:14 UTC, lasjorg commented
Not really sure how to format this.

https://github.com/freeCodeCamp/freeCodeCamp/blob/12527818dd4e63c6cb4bfbb3c3ed910416224311/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-nested-objects.english.md

> - Here's how to extract the values into variables with the same name as they have in the object:
> - Here's how to extract the values into properties with the same name as they have in the object:


> - And here's how you can assign new variable names when destructuring a nested object:
> - And here's how you can assign new property names when destructuring a nested object:


> - Replace the two assignments with an equivalent destructuring assignment. It should still assign the variables lowToday and highToday the values of today.low and today.high from the LOCAL_FORECAST object.
> - Replace the two assignments with an equivalent destructuring assignment. It should still assign the properties lowToday and highToday the values of today.low and today.high from the LOCAL_FORECAST object.



https://github.com/freeCodeCamp/freeCodeCamp/blob/f743d5c0738668ba6c5372d741979235601fc94f/curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-destructuring-assignment-to-assign-variables-from-objects.english.md

> - Destructuring allows you to assign a new variable name when extracting values. You can do this by putting the new name after a colon when assigning the value.
> - Destructuring allows you to assign to a new property when extracting values. You can do this by putting the new property name after a colon when assigning the value.


> - Here's how you can give new variable names in the assignment:
> - Here's how you can give new property names in the assignment:


> - You may read it as "get the value of <code>user.name</code> and assign it to a new variable named <code>userName</code>" and so on.
> - You may read it as, get the value from the property `name` and assign it to a new property named `userName`.


> - Replace the two assignments with an equivalent destructuring assignment. It should still assign the variables highToday and highTomorrow the values of today and tomorrow from the HIGH_TEMPERATURES object.
> - Replace the two assignments with an equivalent destructuring assignment. It should still assign the properties highToday and highTomorrow the values of today and tomorrow from the HIGH_TEMPERATURES object.

2019-06-26 23:30 UTC, RandellDawson commented
@lasjorg I was thinking you were going in a different direction.

The first one (seen below):
>`Here's how to extract the values into properties with the same name as they have in the object:

You are not extracting values into properties.  You are assigning the property values to variables. 
I was thinking something more like:
>Here's how to extract the values of object properties and assign them to variables with the same name as the properties of the object:

The same kind of verbiage would apply to the other sentences (see an example below):

> And here's how you can assign an object properties' values to variables with different names than the  proprerty names of the nested object:

2019-06-27 00:43 UTC, lasjorg commented
@RandellDawson  Your right I don't know what the hell I was thinking. That was a massive brain fart. I just started to replace all the variables with properties, I completely forgot what the challenges were even doing. My only excuse is it's late and I clearly shouldn't be anywhere near code right now. Sorry, that was embarrassing. :disappointed:

2019-06-27 02:17 UTC, moT01 commented
What's the problem here? I'm not sure I see it.

2019-06-27 02:42 UTC, scissorsneedfoodtoo commented
Thank you @moT01 for taking the time to add this lesson and improve the existing ones. These are a huge improvement.

I'm in favor of changing the wording in `/use-destructuring-assignment-to-assign-variables-from-nested-objects.english.md` slightly as @RandellDawson suggested. Perhaps something just slightly shorter like "Here's how to extract the values of object properties and assign them to variables with the same name:", and the following sentence to "And here's how you can assign an object properties' values to variables with different names:"

2019-06-27 07:47 UTC, scissorsneedfoodtoo approved these changes

2019-06-27 07:48 UTC, scissorsneedfoodtoo commented
Thank you @moT01 -- everything LTGM :1st_place_medal:

2019-06-27 07:48 UTC, merged