fix(docs): Set up freeCodeCamp locally with Docker Toolbox for Windows 10 Home
freeCodeCamp/freeCodeCamp pull request #36267
Opened 2019-06-11 21:53 UTC by georgejean

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #36100

2019-06-11 22:13 UTC, RandellDawson commented
@georgejean Why did you add the extra spaces and dashes in the table?  It does not appear to change how it displays.

2019-06-11 22:28 UTC, georgejean commented
@RandellDawson
Sorry. I have the "Markdown All in One" extension for Visual Studio Code which automatically formats the markdown tables on save. I have fixed this.

2019-06-11 22:51 UTC, RandellDawson commented
@raisedadead I may have interpreted your comments on the issue, but I was thinking there was going to actually be a new document containing the supplement information and then link from the how-to-set-up-freecodcamp-locally to this new document.  Instead, we have a link to a forum post?

2019-06-11 23:04 UTC, raisedadead commented
Hi @RandellDawson lets give @georgejean some leeway here. I think they are new to contributing on Github.

@georgejean 

- You have closed the pull-request, I am guessing that was just an accident.
- I also noticed that you have two commits, the first one seems to do what is expected, that is add the guide as a new file.
- The second completely removes the file instead of updating the formatting issues.

No worries, you can still re-open the PR and continue working on it. You should totally hit us up on our [Contributors Chat room](https://gitter.im/FreeCodeCamp/Contributors), where we hang out, and should be able to walk you thru this.

2019-06-13 13:57 UTC, georgejean commented
@raisedadead 
Indeed, I have closed the pull request by accident.
As RandellDawson pointed out, I put first a simple link to the post where the little guide was (I have not dared to create a new file for that).
But my first commit also has changed the format of some markdown tables so I've had to correct that (hence my second commit).
I try now to reopen the Pull Request with one single commit.

2019-06-13 14:03 UTC, raisedadead commented
Ok. That makes sense now. 

We indeed want a new file instead of the issue. You can follow along the current guide for inspiration on the verbiage of the content and add your analysis to it. Then on you can link that new file in the main one as you have already.

Do not worry about multiple commits for now, some one will either squash it or ask for a rebase if needed.

Thanks for the PR.

2019-06-13 14:35 UTC, georgejean commented
> Do not worry about multiple commits for now, some one will either squash it or ask for a rebase if needed.

Sorry, I've pushed my change before reading your post.

2019-06-13 15:57 UTC, raisedadead commented
> > Do not worry about multiple commits for now, some one will either squash it or ask for a rebase if needed.
> 
> Sorry, I've pushed my change before reading your post.

Do not worry about it. It's fine. Some one will review and give you feedback. You can push additional commits if needed.

2019-06-17 15:37 UTC, cmccormack commented
I'm not sure we need a new document for these changes.  There is very little that is unique to the Docker Toolbox setup in the new document, but any time we update information on the original doc it would need to be updated on this doc as well.  I would prefer to see the specific Docker Toolbox instructions be called out inline within the original doc, where appropriate.

2019-06-20 12:58 UTC, georgejean commented
So I've put the instructions directly in the guide.
I'm not native English and am not sure of my English, feel free to correct me if you find any spelling errors.

2019-07-02 09:24 UTC, Nirajn2311 requested changes

2019-07-02 09:24 UTC, Nirajn2311 commented on docs/how-to-setup-freecodecamp-locally.md
> +Your forked freeCodeCamp folder must then be located in the folder `C:\Users\user_name\`.
I think the "then" is not required here.
```suggestion
Your forked freeCodeCamp folder must be located in the folder `C:\Users\user_name\`. 
```

2019-07-02 09:24 UTC, Nirajn2311 commented on docs/how-to-setup-freecodecamp-locally.md
> +To view the app in your browser, go to the adress indicated:
Wrong spelling of address
```suggestion
To view the app in your browser, go to the address indicated:
```

2019-07-02 11:16 UTC, georgejean commented on docs/how-to-setup-freecodecamp-locally.md
> +To view the app in your browser, go to the adress indicated:
Thanks!

2019-08-21 01:39 UTC, cmccormack commented
@georgejean do you have links to the documentation stating why the cloned freecodecamp repository must be in the user's home directory?  I don't know if this document is the best place to introduce a new concept like symbolic links when they aren't required to work on the repository.  It would be better to link out to an official document from Docker instead.

2019-09-04 14:09 UTC, closed without merging