fix regexp to match require statement without .js extension #2
freeCodeCamp/freeCodeCamp pull request #36293
Opened 2019-06-14 17:12 UTC by kozlovvski

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36283
---

I fixed regexp to match files without `.js` extension.

Also, previous regexp matched strings like `require("./routes.js')` (with mixed quotation marks) or even stuff like `requirefoo"./routes.js'`

Now it should work properly

2019-06-14 17:13 UTC, kozlovvski commented
@RandellDawson sorry, I force-pushed and [previous pull request](https://github.com/freeCodeCamp/freeCodeCamp/pull/36290) has closed itself.

I took your regexp and includes it in English version of the challenge only. Is everything right now?

2019-06-14 17:59 UTC, Hardik500 reviewed
Apparently your regex has a bit of problem. Since it also approves require statements which contains new lines. Try limiting the whitespace or new line.

![Screenshot_2](https://user-images.githubusercontent.com/28431356/59528505-1662fe80-8efc-11e9-944f-2ee80267293a.png)

2019-06-14 19:16 UTC, RandellDawson commented
@Hardik500 The example you wrote above would still be perfectly valid code and would not error out.  You can add as much white space as you want in JavaScript and it would not change anything.  I could write the following also:
```
var express = require

(
  
  'express'


);
```

2019-06-14 19:26 UTC, kozlovvski commented
What should I do then?

2019-06-14 19:32 UTC, RandellDawson commented
> What should I do then?

@kozlovvski Nothing else for now.  Another mod will review before it can be merged.

2019-06-28 23:48 UTC, RandellDawson approved these changes

2019-07-01 18:46 UTC, thecodingaviator submitted a review, later dismissed
LGTM

2019-07-01 18:55 UTC, thecodingaviator requested changes

2019-07-01 18:55 UTC, thecodingaviator commented on curriculum/challenges/english/06-information-security-and-quality-assurance/advanced-node-and-express/clean-up-your-project-with-modules.english.md
> +    testString: getUserInput => $.get(getUserInput('url')+ '/_api/server.js') .then(data => { assert.match(data, /require\s*\(('|")\.\/routes(\.js)?\1\)/gi, 'You should have required your new files')
```suggestion
    testString: getUserInput => $.get(getUserInput('url')+ '/_api/server.js') .then(data => { assert.match(data, /require[^\S\r\n]{1,}*\(('|")\.\/routes(\.js)?\1\)/gi, 'You should have required your new files'); assert.match(data, /mongo.connect[^]*routes/gi, 'Your new modules should be called after your connection to the database'); }, xhr => { throw new Error(xhr.statusText); })
```
@RandellDawson How does this look?

2019-07-01 20:20 UTC, thecodingaviator approved these changes
LGTM

2019-07-01 20:21 UTC, merged