fix(challenge): rename challenge, change fields to properties, fix test
freeCodeCamp/freeCodeCamp pull request #36338
Opened 2019-06-27 14:59 UTC by lasjorg

1. The current challenge (on master) lets you pass using an empty object.

2. Rename the challenge to:

> Write Concise Object Literal Declarations Using Object Property Shorthand

3. Switch out the term fields for properties.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/36325

2019-07-01 19:00 UTC, thecodingaviator reviewed
I think you'll need to change the name in `meta.json` too

2019-07-01 22:59 UTC, lasjorg commented
@thecodingaviator whoops, thanks for that.

2019-07-02 01:06 UTC, raisedadead approved these changes
Platform code LGTM. Approved for QA and merge.

2019-07-03 14:32 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

For future reference, if you want you can use `DeepEqual` instead of comparing stringified objects.  It just does that for you.

2019-07-03 16:14 UTC, RandellDawson requested changes
See my requested changes.

2019-07-03 16:14 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/write-concise-object-literal-declarations-using-object-property-shorthand.md
>    - text: 'The output is <code>{name: "Zodiac Hasbro", age: 56, gender: "male"}</code>.'
If we are going to fix this challenge, let's fix the `text` of the tests.
```suggestion
  - text: '<codecreatePerson("Zodiac Hasbro", 56, "male")</code> should return <code>{name: "Zodiac Hasbro", age: 56, gender: "male"}</code>.'
```

2019-07-03 16:14 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/write-concise-object-literal-declarations-using-object-property-shorthand.md
>    - text: No <code>key:value</code> were used.
```suggestion
  - text: Your code should not use <code>key:value</code>.
```

2019-07-04 16:20 UTC, lasjorg commented
Sorry, I forgot to update the second assert message.

---

I do have a question. The challenge text says...

> return a `Person` object

...but it's not really a `Person` object, right? It's just an object.

Putting `Person` with capitalized P and having it inside a `<code>` tag makes it look (to me anyway) like it would be an object returned from a Person constructor invoked with the `new` keyword. But this is just a normal function returning an object. Shouldn't we remove `<code>Person</code>` from the text?

> Use object property shorthand with object literals to create and return an object with `name`, `age` and `gender` properties.

2019-07-04 16:23 UTC, RandellDawson commented
@lasjorg I think your latest suggestion is a good idea.  Go ahead and commit it.

2019-07-07 20:18 UTC, RandellDawson approved these changes

2019-07-10 08:31 UTC, merged

2019-07-10 08:31 UTC, ojeytonwilliams commented
@lasjorg Thank you for your contribution to the page! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo: