fix(curriculum): Remove unnecessary assert message argument from English Front End Libraries challenges - 01
freeCodeCamp/freeCodeCamp pull request #36408
Opened 2019-07-09 03:09 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to issue #36400

This PR removes assert message arguments from `testString` for the following sub sections of the `Front End Libraries` curriculum section:
* Bootstrap
* jQuery
* React and Redux
* Sass

2019-07-24 11:05 UTC, ojeytonwilliams requested changes
Just one slipped through.

2019-07-24 11:05 UTC, ojeytonwilliams commented on curriculum/challenges/english/03-front-end-libraries/react-and-redux/use-provider-to-connect-redux-to-react.english.md
>      testString: getUserInput => assert((function() { const mockedComponent = Enzyme.mount(React.createElement(AppWrapper)); return getUserInput('index').replace(/\s/g,'').includes('<Providerstore={st
```suggestion
    testString: getUserInput => assert((function() { const mockedComponent = Enzyme.mount(React.createElement(AppWrapper)); return getUserInput('index').replace(/\s/g,'').includes('<Providerstore={store}>'); })());
```

2019-07-24 12:16 UTC, thecodingaviator reviewed
Things LGTM except what Oliver suggested above

2019-07-24 15:40 UTC, ojeytonwilliams commented
Sorry about the extra space, should be okay now.

2019-07-24 16:53 UTC, RandellDawson commented
I saw the extra space in one view, but in the view which shows all the changes, it did not show up, which is why I went ahead and made commit you requested.

2019-07-25 06:52 UTC, ojeytonwilliams approved these changes

2019-07-25 06:53 UTC, ojeytonwilliams commented
@RandellDawson I just wish I knew what I did wrong in the first place.

Anyway, it all LGTM now.

2019-07-25 06:53 UTC, merged