fix(curriculum): Remove additional unnecessary assert message argument from English challenges JavaScript Algorithms and Data Structures
freeCodeCamp/freeCodeCamp pull request #36439
Opened 2019-07-10 21:46 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x]  My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to issue #36400

This PR removes assert message arguments from `testString` for the following sub sections of the `JavaScript Algorithms and Data Structures` curriculum section.  This PR was created to remove assert message arguments which were wrapped in two single quotes instead of single quotes.  [See this discussion for more information](https://github.com/freeCodeCamp/freeCodeCamp/pull/36409#issuecomment-510219004)

* Basic Algorithm Scripting
* Debugging
* ES6
* Functional Programming
* Basic Data Structures
* Intermediate Algorithm Scripting
* Object Oriented Programming
* Regular Expressions
* JavaScript Algorithms and Data Structures Projects

2019-07-24 20:16 UTC, vkWeb requested changes
@RandellDawson Except for a few files, all the files have message arguments that need to be removed. Please go through all the files once more.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting/boo-who.english.md
>      testString: assert.strictEqual(booWho([].slice), false, '<code>booWho([].slice)</code> should return false.');
Fix this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/access-property-names-with-bracket-notation.english.md
>      testString: assert.strictEqual(checkInventory('apples'), 25, '<code>checkInventory("apples")</code> should return <code>25</code>');
3 arguments in this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/modify-an-array-stored-in-an-object.english.md
>      testString: assert('name' in user && 'age' in user && 'data' in user, 'The <code>user</code> object has <code>name</code>, <code>age</code>, and <code>data</code> keys');
2 arguments in this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/modify-an-object-nested-within-an-object.english.md
>      testString: assert(userActivity.data.online === 45, 'The <code>online</code> property nested in the <code>data</code> key of <code>userActivity</code> should be set to <code>45</code>');
3 arguments in this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/use-the-delete-keyword-to-remove-object-properties.english.md
>      testString: assert(code.search(/oranges:/) !== -1 && code.search(/plums:/) !== -1 && code.search(/strawberries:/) !== -1, 'The <code>oranges</code>, <code>plums</code>, and <code>strawberries</co
This one here.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/delete-properties-from-a-javascript-object.english.md
>      testString: assert(typeof myDog === "object" && myDog.tails === undefined, 'Delete the property <code>"tails"</code> from <code>myDog</code>.');
This one.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/escaping-literal-quotes-in-strings.english.md
>      testString: assert(code.match(/\\"/g).length === 4 && code.match(/[^\\]"/g).length === 2, 'You should use two double quotes (<code>&quot;</code>) and four escaped double quotes (<code>&#92;&quot;
This one.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/replacing-if-else-chains-with-switch.english.md
>      testString: assert(chainToSwitch(42) === "The Answer", '<code>chainToSwitch(42)</code> should be "The Answer"');
Remove all the arguments in this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/updating-object-properties.english.md
>      testString: assert(/happy coder/gi.test(myDog.name), 'Update <code>myDog</code>&apos;s <code>"name"</code> property to equal "Happy Coder".');
This one.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/catch-misspelled-variable-and-function-names.english.md
>      testString: assert(!code.match(/recievables/g), 'There should be no instances of mis-spelled variables in the code.');
4 arguments here needs to be removed.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/debugging/catch-unclosed-parentheses-brackets-braces-and-quotes.english.md
>      testString: assert(code.match(/myArray\s*?=\s*?\[\s*?1\s*?,\s*?2\s*?,\s*?3\s*?\];/g), 'Your code should fix the missing piece of the array.');
This one.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-filter-method-to-extract-data-from-an-array.english.md
>      testString: assert(!code.match(/for\s*?\(.+?\)/g), 'Your code should not use a <code>for</code> loop.');
3 arguments need to be removed.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person.english.md
>      testString: assert.deepEqual(bob.lastName, undefined, '<code>bob.lastName</code> should return undefined.');
4 arguments in this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/missing-letters.english.md
>      testString: assert.isUndefined(fearNotLetter('abcdefghijklmnopqrstuvwxyz'), '<code>fearNotLetter("abcdefghijklmnopqrstuvwxyz")</code> should return undefined.');
This one.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/sum-all-primes.english.md
>      testString: assert.deepEqual(sumPrimes(10), 17, '<code>sumPrimes(10)</code> should return 17.');
2 arguments in this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/cash-register.english.md
>      testString: assert.deepEqual(Object.prototype.toString.call(checkCashRegister(19.5, 20, [["PENNY", 1.01], ["NICKEL", 2.05], ["DIME", 3.1], ["QUARTER", 4.25], ["ONE", 90], ["FIVE", 55], ["TEN", 20
This one.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/palindrome-checker.english.md
>      testString: assert(palindrome("1 eye for of 1 eye.") === false, '<code>palindrome("1 eye for of 1 eye.")</code> should return false.');
A lot of arguments are there in this file.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/object-oriented-programming/extend-constructors-to-receive-arguments.english.md
>      testString: assert((new Dog('Clifford')).name === 'Clifford', '<code>Dog</code> should receive an argument for <code>name</code>.');
3 arguments.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/match-all-non-numbers.english.md
>      testString: assert("21 Jump Street".match(noNumRegex).length == 12, 'Your regex should find 12 non-digits in <code>"21 Jump Street"</code>.');
A lot of arguments found.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/match-all-numbers.english.md
>      testString: assert("21 Jump Street".match(numRegex).length == 2, 'Your regex should find 2 digits in <code>"21 Jump Street"</code>.');
A lot of arguments here too.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/match-non-whitespace-characters.english.md
>      testString: assert("MindYourPersonalSpace".match(countNonWhiteSpace).length == 21, 'Your regex should find 21 non-spaces in <code>"MindYourPersonalSpace"</code>');
4 arguments.

2019-07-24 20:16 UTC, vkWeb commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/match-whitespace.english.md
>      testString: assert("MindYourPersonalSpace".match(countWhiteSpace) == null, 'Your regex should find no spaces in <code>"MindYourPersonalSpace"</code>');
4 arguments.

2019-07-25 00:00 UTC, RandellDawson commented
@vkWeb This PR actually is an extra PR which removed arguments which were missed in the series of other PRs for the JavaScript Algorithm and Data Structures section.  This PR only will contain fixes which were missed in the earlier PRs.

2019-07-25 12:42 UTC, vkWeb commented
@RandellDawson Ohh. Okay, I'll give this one a quick look after rebase.

2019-07-27 15:56 UTC, thecodingaviator commented
This is the only such PR left now @RandellDawson

2019-07-28 04:15 UTC, thecodingaviator approved these changes
LGTM

2019-07-28 04:16 UTC, merged

2019-07-28 04:17 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝