Prepare for deploy
freeCodeCamp/freeCodeCamp pull request #36469
Opened 2019-07-19 12:27 UTC by raisedadead

2019-07-19 15:46 UTC, ojeytonwilliams commented
I think `npm run develop` is failing because of Gatsby.  I'm trying to find a recent version that works.

2019-07-22 10:02 UTC, ojeytonwilliams requested changes
The floating point weirdness turned out to because `Math.pow()` has changed slightly quite recently and the newer puppeteer uses a version of Chromium that includes the change.

As far as I can see, the only remaining problems are type errors.  Looks good otherwise.

2019-07-22 10:16 UTC, raisedadead commented
Awesome, thanks for the QA and fixing those errors. I am going to do one last force push, re-arranging a few commits. I will also pick yours in the process.

2019-07-22 10:29 UTC, ojeytonwilliams approved these changes

2019-07-22 11:40 UTC, merged