Add hints for "install and set up mongoose"
freeCodeCamp/freeCodeCamp pull request #36474
Opened 2019-07-21 01:04 UTC by ailyntang

* Add hint for how to solve the timeout error

* Add hint for what to put in the `.env` file

* Add code snippets for `.env`, `package.json` and `myApp.js`

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

2019-07-21 03:01 UTC, RandellDawson requested changes
@ailyntang 

Keep the hints separate from the solution code.  The following is part of the solution which is already at the bottom.  Just remove the following changes:

>Once you remove the comma, the tests will run correctly. The correct code:
```
"dependencies": {
  "express": "^4.12 .4",
  "body-parser": "^1.15.2"
},
```
Other than making sure actual solution code is not outside the Solutions section, I think the overall content changes are good. 

We are restructuring all of these hint/solutions.  Only use headers where shown below.  For other sections in your article, just use bolding (surround text with `**`) Please use following structure.  If a section is not needed, do not include the header for it.

````
# Challenge Title

## Problem Explanation
This section gives a summary of what is needed to be done without just copying/pasting the instructions.  Ideally, this header would be placed above lines 6-14.

## Hints

### Hint #1

### Hint#2

#### Relevant Links
These would be relevant Links for the entire Hints section above

## Solutions

<details><summary>Solution #1 (Click to Show/Hide)</summary>

```javascript
// code goes here
```

#### Code Explanation
* Use bullets for the various steps explanation if you want to have anything for Code Explanation

#### Relevant Links
* Use bullets for each link you want to use for this particular solution
</details>

<details><summary>Solution #2 (Click to Show/Hide)</summary>

```javascript
// code goes here
```

#### Code Explanation
* Use bullets for the various steps explanation if you want to have anything for Code Explanation

#### Relevant Links
* Use bullets for each link you want to use for this particular solution
</details>

````

2019-07-22 02:20 UTC, ailyntang commented
Thanks @RandellDawson , I've made the changes. 

By the way, the content on this hints page is not showing up on the website. Instead the website is showing outdate content: https://guide.freecodecamp.org/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/

Let me know if you'd like me to raise an issue for this. I assume this is already a known issue.

2019-07-23 06:35 UTC, RandellDawson requested changes
In addition to the changes requested here, please use 2 space indentation for all JavaScript and JSON code.

Thank you.

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +### Hint #1: Timeout error
```suggestion
### Hint #1
**Timeout error**
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +### Hint #2: add MONGO_URI to .env
```suggestion
### Hint #2
**add MONGO_URI to .env**
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +<details>
```suggestion
<details><summary>Solution #1 (Click to Show/Hide)</summary>
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +  <summary>.env</summary>
```suggestion
**.env**
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +```GLITCH_DEBUGGER=true
````suggestion
```
GLITCH_DEBUGGER=true
````

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +</details>
```suggestion
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +<details>
```suggestion
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +  <summary>package.json</summary>
```suggestion
**package.json**
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> + </details>
```suggestion
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +<details>
```suggestion
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +  <summary>myApp.js</summary>
```suggestion
**myApp.js**
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +  ```/**********************************************
````suggestion
```javascript
/**********************************************
````

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
>  <!-- The article goes here, in GitHub-flavored Markdown. Feel free to add YouTube videos, images, and CodePen/JSBin embeds  -->
```suggestion
```

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +  ```{
````suggestion
```json
{
````

2019-07-23 06:35 UTC, RandellDawson commented on guide/english/certifications/apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose/index.md
> +See below for the correct code to make the tests pass.
```suggestion
```

2019-07-23 17:00 UTC, RandellDawson approved these changes

2019-07-23 17:00 UTC, merged