Add one-liner about using a VPN when working with restricted ISPs
freeCodeCamp/freeCodeCamp pull request #36485
Opened 2019-07-22 19:57 UTC by Jo-IE

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [ x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #36472

2019-07-24 12:28 UTC, thecodingaviator commented
I don't see a reason why someone's ISP would block `docker` or `npm` in general except in case of uncleared dues or a government directive, as such, I believe that I speak for all of freeCodeCamp when I say that we would not like to promote anything that might be illegal.

cc: @raisedadead

2019-07-24 14:50 UTC, raisedadead requested changes

2019-07-24 14:50 UTC, raisedadead commented on docs/how-to-setup-freecodecamp-locally.md
> +**NB:** If your ISP has certain network restrictions, the above step (2) may fail without warning. In such a case, you will need to install a VPN or proxy to get this step to pass.
```suggestion
If you get errors while installing the dependencies, please make sure that you are not in a restricted network or your firewall settings do not prevent you from accessing resources. Some solutions would be use to VPN services if possible and allowed in your environment.
```

Hi @Jo-IE 

Thanks for the PR. I think we should move this change to the troubleshooting area. Second we should update the language to be more neutral.

2019-07-24 21:58 UTC, Jo-IE commented
Thanks for the suggestion @raisedadead, I just committed it.

2019-07-25 01:44 UTC, jonathan-grah requested changes
Hi @Jo-IE, I also agree with @raisedadead that we should move this to the troubleshooting section (at the bottom of the page).

2019-07-25 01:44 UTC, jonathan-grah commented on docs/how-to-setup-freecodecamp-locally.md
> +If you get errors while installing the dependencies, please make sure that you are not in a restricted network or your firewall settings do not prevent you from accessing resources. Some solutions wo
```suggestion
If you get errors while installing the dependencies, please make sure that you are not in a restricted network or your firewall settings do not prevent you from accessing resources. One solution would be to use a VPN service if possible and allowed in your environment.
```

2019-07-25 09:44 UTC, Jo-IE commented
Thanks for the clarifications, the latest commit should have addressed all the issues above.

2019-07-25 09:51 UTC, raisedadead commented
Great the latest commit moved it to the correct location, can you update the verbiage as per https://github.com/freeCodeCamp/freeCodeCamp/pull/36485#discussion_r307085515

2019-07-25 10:40 UTC, Jo-IE commented
Oh sorry I didn't catch that. They've been added now.

2019-07-25 11:13 UTC, raisedadead approved these changes

2019-07-25 11:14 UTC, merged

2019-07-25 11:15 UTC, raisedadead commented
Thanks for the working on this @Jo-IE !