Update get-geolocation-data-to-find-a-users-gps-coordinates.english.md
freeCodeCamp/freeCodeCamp pull request #36525
Opened 2019-07-28 16:17 UTC by Vrajsingh

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-07-28 20:40 UTC, RandellDawson requested changes
@Vrajsingh Please commit the following changes:

In the future, make sure you setup the repo locally and run the following before creating a PR.  If all the test pass, then you can create a PR.
```bash
npm run test:curriculum
```

2019-07-28 20:40 UTC, RandellDawson commented on curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/get-geolocation-data-to-find-a-users-gps-coordinates.english.md
> -<section id='solution'>
Please add the following back in:
```suggestion
<section id='solution'>
```

2019-07-28 20:40 UTC, RandellDawson commented on curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/get-geolocation-data-to-find-a-users-gps-coordinates.english.md
>  ```js
Please change the following to html:
````suggestion
```html
````

2019-07-28 20:40 UTC, RandellDawson commented on curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/get-geolocation-data-to-find-a-users-gps-coordinates.english.md
> -</section>
Please add the following back in:
```suggestion
</section>
```

2019-09-18 14:38 UTC, closed without merging

2019-09-18 14:38 UTC, raisedadead commented
Thanks for the PR @Vrajsingh, closing this as stale. Please open a fresh PR if you are still interested.