feat(tools) add script to audit all packages
freeCodeCamp/freeCodeCamp pull request #36537
Opened 2019-07-30 15:29 UTC by ojeytonwilliams

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Lerna does not (yet) have a command to run `npm audit` or `npm audit fix` on all packages in a repo.  This script does that, ensuring that all the packages in `lerna.json` get audited.  I decided on `npm audit fix`, but if we want `npm audit` as well, I can add that in.

This should make #36535 a bit easier to solve.

2019-07-30 15:52 UTC, raisedadead commented
I think you are able to do `lerna exec npm audit` and  `lerna exec npm audit fix`

2019-07-30 19:40 UTC, ojeytonwilliams commented
Huh.  I assumed that, since Lerna has an open issue about auditing, it couldn't be that easy.  Shows what I know.

Do you think it's still worth creating a couple of npm scripts for that, in case I'm not the only one that makes this mistake?  Even though my script isn't needed.

2019-07-31 07:41 UTC, raisedadead commented
Hmm, I think we should be keeping the `fix` part from the script as a separate command or something.

More often than not, I have seen even in range updates break the setup. 🤷‍♂

2019-07-31 09:03 UTC, ojeytonwilliams commented
How about these?  It's a bit slow with concurrency 1, but I guess we aren't going to be running it all the time.

2019-07-31 16:25 UTC, raisedadead requested changes
Lerna will not cover the root of the repo.

2019-07-31 16:25 UTC, raisedadead commented on package.json
> +    "audit": "lerna exec --concurrency 1 'echo $LERNA_PACKAGE_NAME && npm audit'",
```suggestion
    "audit": "npm audit && lerna exec --concurrency 1 'echo $LERNA_PACKAGE_NAME && npm audit'",
```

2019-07-31 16:25 UTC, raisedadead commented on package.json
> +    "audit:fix": "lerna exec --concurrency 1 'echo $LERNA_PACKAGE_NAME && npm audit fix'",
```suggestion
    "audit:fix": "npm audit fix && lerna exec --concurrency 1 'echo $LERNA_PACKAGE_NAME && npm audit fix'",
```

2019-07-31 17:30 UTC, ojeytonwilliams commented
Good point.  Thanks!

2019-07-31 17:40 UTC, raisedadead approved these changes

2019-07-31 17:40 UTC, merged