Issue #36564 update regex for spread operator
freeCodeCamp/freeCodeCamp pull request #36565
Opened 2019-08-05 20:30 UTC by enrider

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36564

2019-08-05 20:54 UTC, RandellDawson requested changes
@enrider Thank you for you PR.  See my comments and requested change.

2019-08-05 20:54 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-the-spread-operator-to-evaluate-arrays-in-place.english.md
> +    testString: assert(code.match(/\s*...arr1\s*/g));
@enrider The problem with your regex is that it should not just be checking if the spread operator is used on `arr1`.  It is supposed to validate the spread operator correctly creates a copy of `arr1`.

If you read the documentation for challenge related PRs, you will find you must test the changes locally (`npm run test:curriculum`) to confirm you do not make any breaking changes.  Your change allows the user to not change any of the challenge seed code and still pass all of the tests.

Also, the original regex should not have used `...`.  Instead, it should have been `\.\.\.`.  I have made a suggestion which does pass all of the tests and correctly fails when no code is changed.  You can click `Commit suggestion` and it apply the suggested change on your behalf.

```suggestion
    testString: assert(code.match(/Array\(\s*\.\.\.arr1\s*\)|\[\s*\.\.\.arr1\s*\]/));
```

2019-08-06 21:48 UTC, moT01 approved these changes
LGTM! 🎉 

Want to approve and merge this @RandellDawson ?

2019-08-06 21:56 UTC, RandellDawson approved these changes

2019-08-06 21:56 UTC, merged

2019-08-06 21:57 UTC, RandellDawson commented
Congrats @enrider  on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝