fix(client): add warning on exceeding forum post length limit
freeCodeCamp/freeCodeCamp pull request #36625
Opened 2019-08-17 21:39 UTC by raisedadead

Closes #36323
Closes #18005

2019-08-18 10:20 UTC, raisedadead commented
Next things:

- [ ] Add tests please.
- [ ] Consolidate the helper functions and reduce repetition.
- [ ] Get the forum base URL `https://www.freecodecamp.org/forum` from env and construct further URL bits as needed.

2019-08-18 18:29 UTC, RandellDawson commented
@raisedadead I believe I have taken care of the following:
* Consolidate the helper functions and reduce repetition.
*  Get the forum base URL https://www.freecodecamp.org/forum from env and construct further URL bits as needed.

Now, I will work on some tests.

2019-08-18 19:20 UTC, raisedadead commented
While you are at this, can you clean up this file:

`client/src/templates/Challenges/redux/create-question-epic.js`

```
      const studentCode = window.encodeURIComponent(textMessage);
      const altStudentCode = window.encodeURIComponent(altTextMessage);

      const defaultURI = `https://www.freecodecamp.org/forum/new-topic?category=${category}
                          &title=&body=${studentCode}`;
      const altURI = `https://www.freecodecamp.org/forum/new-topic?category=${category}
      &title=&body=${altStudentCode}`;

      if (defaultURI.length < 8000) {
        window.open(defaultURI, '_blank');
      } else {
        window.open(altURI, '_blank');
```

This can be simplified. Also the text block can be wrapped in backtick instead of the ugly single quotes.

2019-08-18 19:45 UTC, RandellDawson commented
OK.

2019-08-23 09:43 UTC, ojeytonwilliams requested changes
Thanks to @RandellDawson adding the tests for `getGuideUrl`, I noticed that the title isn't URI encoded.  I included suggestions to fix that.

2019-08-23 09:43 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/index.test.js
> +        title: 'a sample title'
```suggestion
        title: '& a sample title?'
```
I think we should add a couple of special characters so we're sure they're encoded properly

2019-08-23 09:43 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/index.test.js
> +        `${forumLocation}/search?q=a sample title%20in%3Atitle%20order%3Aviews`
```suggestion
        `${forumLocation}/search?q=%26%20a%20sample%20title%3F%20in%3Atitle%20order%3Aviews`
```
We should use the encoded version.

2019-08-23 09:43 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/index.js
> +  return forumTopicId
```suggestion
  title = encodeURIComponent(title);
  return forumTopicId
```
In case the title includes &, ? etc.

2019-08-23 16:54 UTC, ojeytonwilliams approved these changes

2019-08-26 09:50 UTC, raisedadead commented
Is this ready for review? If yes, can you update the label.

2019-08-26 10:01 UTC, ojeytonwilliams commented
I think Randell was planning to add a few tests for the React components.

2019-08-28 16:25 UTC, raisedadead reviewed
Merge. Merge. Merge.

2019-08-28 16:25 UTC, merged