fix/heatmap-colors
freeCodeCamp/freeCodeCamp pull request #36660
Opened 2019-08-21 16:05 UTC by moT01

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36650

2019-08-21 16:42 UTC, thecodingaviator reviewed
This looks amazing 🔥

2019-08-21 20:24 UTC, jonathan-grah commented
@moT01 😍

2019-08-22 14:27 UTC, ojeytonwilliams requested changes
Nice one, @moT01, this looks cool!

I found one typo, see below.

Also, one thought I had was, the chain of `if`s might look a bit cleaner if you got rid of the `{}` since they're each one liners

```js
if(cond) return 'result'
```
That sort of thing.  Not a huge deal, I'd be happy merging if the typo's fixed, but I figured I'd mention it.

2019-08-22 14:27 UTC, ojeytonwilliams commented on client/src/components/profile/components/HeatMap.js
> +            return 'color-scale-empty';
```suggestion
            return 'color-empty';
```

2019-08-22 14:48 UTC, moT01 commented on client/src/components/profile/components/HeatMap.js
> +            return 'color-scale-empty';
nice catch

2019-08-22 14:59 UTC, ojeytonwilliams approved these changes

2019-08-22 15:00 UTC, ojeytonwilliams commented
Thanks, @moT01, it looks nice and tidy now.

2019-08-25 14:56 UTC, moT01 commented
Is there something specific you want updated here @raisedadead?

2019-08-25 20:16 UTC, ahmadabdolsaheb commented
@moT01, this pr is in the queue. I will test it locally in a day or two and let you know.

2019-08-26 13:21 UTC, raisedadead approved these changes

2019-08-26 13:22 UTC, merged