fix: make challenge links on profile page work
freeCodeCamp/freeCodeCamp pull request #36701
Opened 2019-08-27 18:40 UTC by moT01

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36085

2019-08-27 19:03 UTC, ojeytonwilliams commented
I'll take a proper look at this soon, but my first impressions are that this is a nice solution.  The extra work the server has to do is pretty small.

I am still wondering if we can get away with not using the server at all.  Nonetheless, if we are using it, this looks like the way to go.

2019-08-28 16:32 UTC, raisedadead commented
We can update the styles. It was sort of a mess. Feel free to take a dig at it.

2019-08-28 16:59 UTC, ojeytonwilliams commented
@raisedadead The issue is that the TimeLine's cert links are currently 404s, so we were wondering if they should be filtered out or made to point at the certifications.

Also, @RandellDawson noticed that the certifications appear in the TimeLine even if they aren't public.  Presumably that's a bug!

2019-08-28 17:35 UTC, raisedadead commented
🤦‍♂ I need more coffee. Yes, this looks like a bug.

2019-08-28 18:30 UTC, ahmadabdolsaheb commented
it seems like we are moving in the direction of completely removing these links and making the the profile more resume like. I wonder if we should sunset this list now if fixing it is too time consuming. @raisedadead thoughts?

2019-08-28 18:49 UTC, raisedadead commented
> it seems like we are moving in the direction of completely removing these links and making the the profile more resume like. I wonder if we should sunset this list now if fixing it is too time consuming. 

I think this should be fixed now. 

We have not planned or designed anything about the "resume" like settings page. It could presumably take weeks. From my point of view this is a blocker issue right now from releasing master.

I would defer to @QuincyLarson though.

2019-08-29 08:09 UTC, ojeytonwilliams requested changes
I have a couple of nitpicks, but otherwise this looks good.

2019-08-29 08:09 UTC, ojeytonwilliams commented on client/src/components/profile/components/TimeLine.js
> +  idToNameMap: PropTypes.object,
```suggestion
  idToNameMap: PropTypes.objectOf(
    PropTypes.shape({
      challengePath: PropTypes.string,
      challengeTitle: PropTypes.string
    })
  ),
```
Might as well specify the type of object.

2019-08-29 08:09 UTC, ojeytonwilliams commented on client/src/components/profile/components/TimeLine.js
> +    const challengeTitle = idToNameMap[id].challengeTitle;
```suggestion
    const { challengeTitle, challengePath } = idToNameMap[id];
```
Just to save a line.

2019-08-29 08:09 UTC, ojeytonwilliams commented on client/src/components/profile/components/TimeLine.js
> +    const challengePath = idToNameMap[id].challengePath;
```suggestion
```

2019-08-29 13:04 UTC, ojeytonwilliams approved these changes

2019-08-29 17:54 UTC, raisedadead approved these changes

2019-08-29 17:55 UTC, merged

2019-08-29 18:16 UTC, moT01 commented
Thanks for all the reviews lately everyone! 🎉 @raisedadead @ahmadabdolsaheb @RandellDawson @ojeytonwilliams @thecodingaviator @Manish-Giri @jonathan-grah 🎉