fix: clean up
freeCodeCamp/freeCodeCamp pull request #36778
Opened 2019-09-10 21:06 UTC by ahmadabdolsaheb

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #36764

2019-09-11 08:13 UTC, raisedadead reviewed
See https://github.com/freeCodeCamp/freeCodeCamp/issues/36764#issuecomment-530272561

2019-09-11 13:38 UTC, raisedadead commented on tools/scripts/build/create-redirects.js
> +/software-resources-for-nonprofits            #{{NEWS}}/software-resources-for-nonprofits
Add a http status code for the redirect. Also update the test snapshot for the redirects file.

2019-09-11 13:38 UTC, raisedadead requested changes
Add a http status code for the redirect. Also update the test snapshot for the redirects file.

2019-09-13 14:46 UTC, ahmadabdolsaheb commented
thanks for noticing that.

2019-09-15 07:35 UTC, raisedadead approved these changes

2019-09-15 07:36 UTC, merged