fix:Typo in uncomment-html page
freeCodeCamp/freeCodeCamp pull request #36800
Opened 2019-09-15 22:07 UTC by ezgikaysikesler

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36794

2019-09-15 22:36 UTC, RandellDawson commented
@ezgikaysikesler Since we are changing that line now, do we really even need that comma before the word `and`?

2019-09-16 11:43 UTC, thecodingaviator requested changes

2019-09-16 11:43 UTC, thecodingaviator commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/uncomment-html.english.md
> +Comments in HTML start with <code>&#60;!--</code>, and end with a <code>--&#62;</code>
```suggestion
Comments in HTML start with <code>&#60;!--</code> and end with a <code>--&#62;</code>
```

2019-09-16 12:14 UTC, thecodingaviator approved these changes

2019-09-18 17:51 UTC, RandellDawson approved these changes

2019-09-18 17:51 UTC, merged

2019-09-18 17:52 UTC, RandellDawson commented
Congrats @ezgikaysikesler on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes and look forward to future contributions. 📝