fix: add report user button back to profile pages
freeCodeCamp/freeCodeCamp pull request #36926
Opened 2019-10-01 20:24 UTC by moT01

As far as I can tell, this seems to work. It will put a `Report This User` button in place of the settings button anytime it's not the users own profile.

From there it will bring up the report form for an authenticated user, and redirect a non authenticated user to /signin after 5 seconds

I was unable to actually send a report email to myself, but I'm guessing that will work in production?

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #36837

2019-10-02 06:42 UTC, raisedadead commented
> From there it will bring up the report form for an authenticated user, and redirect a non authenticated user to `/signin` after 5 seconds

Is this an intended wait time somewhere? Or you are proposing this?

> Also, the automatic redirect to `/signin` doesn't work locally - I'm pretty sure that will be fine on production.

This should work on local as well. There is no reason for it to break. We have mocked the OAuth 2.0 strategy. You will not see a prompt but the api logs on your terminal should show up hitting the paths.

Anyways, to be in the clear, you should be able to setup Auth0 and get your own keys. This is particularly useful if you will be working with authenticated routes very often.

I can hook you up with the keys if you need to be very close to production. But the type of auth (passwordless/social, etc.) really does not matter. The defaults you get from Auth0 (password based) should be fine as it is. The API will see it as a OAuth 2.0 provider.

Setting this on the Auth0 Application setting should be fine (everything else can be ignored):

```
Allowed Callback URLs: http://localhost:3000/auth/auth0/callback
```

Set these:

```
AUTH0_CLIENT_ID=stuff
AUTH0_CLIENT_SECRET=stuff
AUTH0_DOMAIN=stuff
```

Disable local mocking

```
LOCAL_MOCK_AUTH=false
```

2019-10-02 15:02 UTC, moT01 commented
> From there it will bring up the report form for an authenticated user, and redirect a non authenticated user to /signin after 5 seconds

This was the functionality that was already in place on the [showUser.js file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/client-only-routes/ShowUser.js) - I assume that was the page that users were taken to for reporting in the past. I just added the button to get there.

2019-10-02 16:53 UTC, raisedadead commented
> This was the functionality that was already in place [...]

Thanks for pointing me to this :) Let's leave that as is.

2019-10-02 17:13 UTC, moT01 commented
I think I figured out the local sign in issues when comparing that file to other redirects to /signin. I added a commit which fixes it for local redirects.

2019-10-02 17:34 UTC, moT01 commented
The last commit there is for when you submit a report, it redirects to learn instead of the homepage because the homepage automatically redirects to learn, so there was like a double redirect that was annoying.

2019-10-02 17:47 UTC, raisedadead commented
Nice work @moT01. 
Can we add some tests to go with this, because we are fixing a regression?

2019-10-03 08:52 UTC, ojeytonwilliams requested changes
Looks great, @moT01.

The only thing was that `navigate` was essentially an alias for `hardGoTo`, so I made some suggestions to make that explicit.

Regardless, everything is working nicely.

2019-10-03 08:52 UTC, ojeytonwilliams commented on client/src/client-only-routes/ShowUser.js
> +  hardGoTo,
```suggestion
  hardGoTo as navigate,
```
If we alias like this, we can clean up a little.  See below.

2019-10-03 08:52 UTC, ojeytonwilliams commented on client/src/client-only-routes/ShowUser.js
> +  hardGoTo: PropTypes.func.isRequired,
```suggestion
```

2019-10-03 08:52 UTC, ojeytonwilliams commented on client/src/client-only-routes/ShowUser.js
> +      hardGoTo,
```suggestion
```

2019-10-03 08:52 UTC, ojeytonwilliams commented on client/src/client-only-routes/ShowUser.js
> +      navigate: location => dispatch(hardGoTo(location)),
```suggestion
      navigate,
```

2019-10-03 08:54 UTC, ojeytonwilliams commented
@raisedadead unless I'm missing something, `hardGoTo` achieves the same thing as reach-router's `navigate`.  Is there a reason to keep it or can we just cut it out?  In general, that is, rather than just this PR.

2019-10-03 09:04 UTC, raisedadead commented
> Is there a reason to keep it or can we just cut it out? 

I think it was a legacy thing that we had before we had `navigate`. It can be removed and cleaned up.

2019-10-03 09:08 UTC, ojeytonwilliams commented on client/src/client-only-routes/ShowUser.js
>  import { bindActionCreators } from 'redux';
```suggestion
import { bindActionCreators } from 'redux';
import { navigate } from '@reach/router';
```
https://github.com/freeCodeCamp/freeCodeCamp/pull/36926#issuecomment-537857201

2019-10-03 14:36 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2019-10-05 07:28 UTC, raisedadead approved these changes

2019-10-05 07:28 UTC, merged