grammatical mistakes fix docs/how-to-setup-freecodecamp-locally.md
freeCodeCamp/freeCodeCamp pull request #36930
Opened 2019-10-01 21:15 UTC by iamrajiv

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-10-01 21:23 UTC, RandellDawson requested changes
@iamrajiv See my suggested changes.

2019-10-01 21:23 UTC, RandellDawson commented on docs/how-to-setup-freecodecamp-locally.md
> +The keys in the `.env` file is *not* required to be changed to run the app locally. You can leave the default values copied over from `sample.env` as-is.
Please revert this line as the verb "are" is for the word "keys" and not "file".

2019-10-01 21:23 UTC, RandellDawson commented on docs/how-to-setup-freecodecamp-locally.md
> -Keep in mind if you want to use additional services, you'll have to acquire your own API keys for those services and edit the entries accordingly in the `.env` file.
No reason to change this.

2019-10-01 21:23 UTC, RandellDawson commented on docs/how-to-setup-freecodecamp-locally.md
> +> Make sure the command-line tool you use (e.g., cmd, PowerShell, Git Bash for Windows, WSL) has the correct user privileges. If possible, you should launch the tool with the Administrator's privileg
No reason to add the word "the" here.

2019-10-01 21:23 UTC, RandellDawson commented on docs/how-to-setup-freecodecamp-locally.md
> -This is essential as it allows you to work on your own copy of freeCodeCamp on GitHub, or to download (clone) your repository to work on locally. Later, you will be able to request changes to be pull
Please add the word "own" back in.

2019-10-01 21:23 UTC, RandellDawson commented on docs/how-to-setup-freecodecamp-locally.md
> +    This step **will sync the latest changes** from the main repository of freeCodeCamp. You must rebase your branch on top of the latest `upstream/master` as often as possible to avoid conflicts lat
This is not a case of "must do" here.  This should be reverted.

2019-10-09 06:59 UTC, raisedadead approved these changes

2019-10-09 07:10 UTC, merged