definition espanola enhancement
freeCodeCamp/freeCodeCamp pull request #36985
Opened 2019-10-03 13:10 UTC by rayhanhanaputra

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-03 23:02 UTC, Ast2435 requested changes
This is way better and professional than before, and it's a better description overall. I would still change "Nuestra comunidad ya ha ayudado" to just "Nuestra comunidad ha ayudado".

2019-11-01 15:58 UTC, Narshe1412 requested changes

2019-11-01 15:58 UTC, Narshe1412 commented on docs/i18n-languages/spanish/README.md
> +[freeCodeCamp.org](https://www.freecodecamp.org) es una organización sin fines de lucro que consta de una plataforma web de aprendizaje interactiva, un foro comunitario en línea, salas de chat, publi
- "sin ánimo de lucro" should be the term as defined in RAE: https://dej.rae.es/lema/sin-%C3%A1nimo-de-lucro
- "hacer que el aprendizaje de desarrollo web" order reversed in aprendizaje and desarrollo web

2019-11-29 01:02 UTC, RandellDawson commented
As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2019-11-29 01:02 UTC, closed without merging