Fix typo on translation of "obtain" in line 12
freeCodeCamp/freeCodeCamp pull request #36988
Opened 2019-10-03 15:05 UTC by aquelemiguel

The translation of "obtain" had a typo.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-30 01:05 UTC, TheSirion requested changes
"necessita" in the first line isn't conjugated correctly according to the subject. "Alguns dos fluxos de email [...] necessitam".

2019-11-24 17:17 UTC, junagao approved these changes

2019-11-24 18:20 UTC, RandellDawson commented
@aquelemiguel Can you please also make the change @TheSirion has suggested here.

Thank you.

2020-02-10 14:57 UTC, raisedadead commented
Hi @aquelemiguel we haven't heard back from you in a while. We are closing this PR, please open a fresh one updating the changes as requested.

Thanks.

2020-02-10 14:57 UTC, closed without merging