MODIFIED convert-json-data-to-html to warn about XSS attacks (spanish)
freeCodeCamp/freeCodeCamp pull request #37037
Opened 2019-10-04 21:24 UTC by Wocanilo

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] None of my changes are plagiarized from another source without proper attribution.
- [X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [X] My changes do not use shortened URLs or affiliate links.

Closes #36162

2019-10-04 21:43 UTC, RandellDawson commented
@Wocanilo The same verbiage as the English changes you suggested in #37036 will apply here as well.

2019-10-04 21:56 UTC, RandellDawson requested changes
One more thing to fix.

2019-10-04 21:56 UTC, RandellDawson commented on curriculum/challenges/spanish/04-data-visualization/json-apis-and-ajax/convert-json-data-to-html.spanish.md
> +<b>Nota:</b> Para completar este reto es necesario añadir nuevos elementos html, por lo que no podrá depender de textContent. Deberá utilizar el método innerHTML que podría hacer que su página web se
Something I did not catch in the first review, but according to our guidelines, notes are surrounded by `strong` tags.
```suggestion
<strong>Nota:</strong> Para completar este reto es necesario añadir nuevos elementos html, por lo que no podrá depender de textContent. Deberá utilizar el método innerHTML que podría hacer que su página web sea vulnerable a ataques de cross site scripting.
```

2019-10-24 01:39 UTC, batistaDev1113 requested changes
I think the following term should be changed from **Cuando el bucle termina** to **Cuando la repetición de instrucciones termina**

2019-10-25 21:59 UTC, RandellDawson commented
@batistaDev1113 Since your suggested change is not part of the document which the user is changing, can you please create a separate PR to make your suggested change?

Thank you.

2019-11-20 21:57 UTC, moT01 commented
I made the suggested changes to this, that were suggested on the linked PR. It should be good to go.

2020-02-10 14:54 UTC, merged