Added meaning of ones in the matrix
freeCodeCamp/freeCodeCamp pull request #37048
Opened 2019-10-05 14:33 UTC by harshsaver

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-11-07 17:32 UTC, ojeytonwilliams requested changes
Thanks for the PR! I made a few suggestions below.

2019-11-07 17:32 UTC, ojeytonwilliams commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-matrix.english.md
> +<strong>Note</strong>: The numbers to the top and left of the matrix are just labels for the nodes and the Ones means there exists an edge between the vertices (nodes) representing the row and column
```suggestion

<strong>Note</strong>: The numbers to the top and left of the matrix are just labels for the nodes. Inside the matrix ones mean there exists an edge between the vertices (nodes) representing the row and column.  Finally, zeros mean there is no edge or relationship.
```
One and zero are not a proper nouns - no need to capitalise them.  I also split the sentences to aide comprehension.

2019-11-07 17:32 UTC, ojeytonwilliams commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/adjacency-matrix.english.md
>  <blockquote>    1 2 3<br>   ------<br>1 | 0 1 1<br>2 | 1 0 0<br>3 | 1 0 0</blockquote>
```suggestion
<pre>
    1 2 3
  -------
1 | 0 1 1
2 | 1 0 0
3 | 1 0 0
</pre>
```
Blockquotes don't preserve whitespace, so I changed it to a pre element instead.

2019-11-25 15:08 UTC, moT01 commented
I looks unlikely that the PR creator will make these changes @ojeytonwilliams, do you want to commit them?

2020-02-27 10:23 UTC, ojeytonwilliams commented
@raisedadead oops, forgot about this one.  I'll fix the linting.

2020-02-27 11:07 UTC, ojeytonwilliams commented
I've fixed the lint problem with a mild hack.  It was interpreting the ----- as a heading, so the slash stops that (and still looks good, imo).

2020-02-27 11:07 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2020-02-27 12:54 UTC, moT01 approved these changes
LGTM 🎉 Thanks for contributing to freeCodeCamp 🎉

2020-02-27 12:54 UTC, merged