Update russian chain-middleware
freeCodeCamp/freeCodeCamp pull request #37099
Opened 2019-10-07 19:27 UTC by 3t3rn1ty

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-07 19:41 UTC, RandellDawson commented
@3t3rn1ty Please validate you have complied with all of the items in the list above and translate everything in the instructions.

2019-10-07 19:52 UTC, term1nal approved these changes
Ok.

2019-10-07 19:55 UTC, 3t3rn1ty commented
> @3t3rn1ty Please validate you have complied with all of the items in the list above and translate everything in the instructions.

Its ok!

2019-10-07 20:12 UTC, RandellDawson commented
@3t3rn1ty You have not translated everything in the instructions.

2019-10-09 11:24 UTC, greggubarev requested changes

2019-10-09 11:24 UTC, greggubarev commented on curriculum/challenges/russian/05-apis-and-microservices/basic-node-and-express/chain-middleware-to-create-a-time-server.russian.md
> +В цепочке маршрута  <code>app.get('/now', ...)</code> есть функция промежуточного программного обеспечения и конечный обработчик. В функции промежуточного программного обеспечения необходимо добавить
"принимая структуру" - можно использовать более лаконичный перевод, передающий смысл? В данном виде он немного искажен

2019-12-20 15:26 UTC, raisedadead commented
Hi @3t3rn1ty can you address @greggubarev's suggestions?

2020-02-27 13:33 UTC, closed without merging