Create how-to-open-a-pull-request.md
freeCodeCamp/freeCodeCamp pull request #37130
Opened 2019-10-08 17:42 UTC by Plingooo

Translate to german

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-10 06:01 UTC, raisedadead commented
Hi @Plingooo same as your previous pull-request can you get this PR reviewed

2019-10-15 07:35 UTC, martin-gnodtke requested changes
Some minor consistency changes to @Plingooo's translation. Well done!

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +Wenn du eine Pull Request(PR) erstellst, verwende die folgende Thementabelle, um zu entscheiden, wie du deinen PR im folgenden Format benennen möchtest:
```suggestion
Wenn du eine Pull Request(PR) erstellst, verwende die folgende Tabelle, um zu entscheiden, wie du deine PR im folgenden Format benennen möchtest:
```

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +## Vorschlag für einen Pull-Request (PR)
```suggestion
## Vorschlag für eine Pull-Request (PR)
```

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +2. Standardmäßig sollten alle Pull-Requests gegen den Hauptrepo von freeCodeCamp, Zweig `master`, gerichtet sein.
```suggestion
2. Standardmäßig sollten alle Pull-Requests gegen den `master` Zweig des Hauptrepositories von freeCodeCamp, gerichtet sein.
```

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +    Stelle sicher, dass dein Standard Fork auf freeCodeCamp/freeCodeCamp eingestellt ist, wenn du einen Pull-Request auslöst.
```suggestion
    Stelle sicher, dass dein `base fork:` auf freeCodeCamp/freeCodeCamp eingestellt ist, wenn du eine Pull-Request auslöst.
```

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +3. Sende die Pull-Anfrage aus deinem Zweig an den `master`- Zweig von freeCodeCamp.
```suggestion
3. Sende die Pull-Request aus deinem Zweig an den `master` Zweig von freeCodeCamp.
```

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +    - Es wird dir eine Pull Request Vorlage angezeigt. Dies ist eine Checkliste, die du vor dem Öffnen des Pull-Auftrags hättest befolgen sollen.
```suggestion
    - Es wird dir eine Pull Request Vorlage angezeigt. Dies ist eine Checkliste, die du vor dem Öffnen der Pull-Request hättest befolgen sollen.
```

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +    - Fülle die Details aus, wie es dir passt. Diese Informationen werden überprüft und entschieden, ob deine Pull-Anfrage akzeptiert wird oder nicht.
```suggestion
    - Fülle die Details aus, wie es dir passt. Diese Informationen werden überprüft und entschieden, ob deine Pull-Request akzeptiert wird oder nicht.
```

2019-10-15 07:35 UTC, Squizzi3 commented on docs/i18n-languages/german/how-to-open-a-pull-request.md
> +      der Beschreibung deines Pull Requests, das Schlüsselwort `closes` und #xxxx an (wobei xxxx
```suggestion
      der Beschreibung deiner Pull Request, das Schlüsselwort `closes` und #xxxx an (wobei xxxx
```

2019-10-15 07:53 UTC, Plingooo commented
oh, I must have been a little tired. Thanks for the improvements @Squizzi3

2019-10-15 11:53 UTC, raisedadead approved these changes

2019-10-15 11:53 UTC, merged