Translated how-to-catch-outgoing-emails-locally.md into ukrainian
freeCodeCamp/freeCodeCamp pull request #37229
Opened 2019-10-12 12:30 UTC by Pavlik1400

translated "how-to-catch-outgoing-emails-locally.md" into ukrainian

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

2019-10-12 12:36 UTC, last-genius requested changes
Change "сріншот" to "скріншот"

2019-10-12 12:36 UTC, last-genius approved these changes

2019-10-12 13:09 UTC, JanusDG commented
This is the startpoint of my https://github.com/freeCodeCamp/freeCodeCamp/pull/37233

2019-10-15 11:37 UTC, yevhenorlov requested changes
well done! please take a look at the comments

2019-10-15 11:37 UTC, yevhenorlov commented on docs/i18n-languages/ukrainian/how-to-catch-outgoing-emails-locally.md
> +Деякі робочі процеси електронної пошти (наприклад оновлення електронної пошти користувача) вимагають щоб внутрішній сервер через api відправляв електронні листи. Під час розробки ви можете використов
change "екземляром" to "екземпляром"

2019-10-15 11:37 UTC, yevhenorlov commented on docs/i18n-languages/ukrainian/how-to-catch-outgoing-emails-locally.md
> +- [Установка MailHog on Linux](#installing-mailhog-on-linux)
maybe change "on" to "на"?

2019-10-15 11:37 UTC, yevhenorlov commented on docs/i18n-languages/ukrainian/how-to-catch-outgoing-emails-locally.md
> +Після цього ви можете перейти безпосередньо до  [використання MailHog](#using-mailhog).
double space after "до"

2019-10-15 11:37 UTC, yevhenorlov commented on docs/i18n-languages/ukrainian/how-to-catch-outgoing-emails-locally.md
> +Завантажте останню версію MailHog з  [офіційного репозиторію](https://github.com/mailhog/MailHog/releases). Виберіть посилання для вашої версії Windows (32 або 64 біт) і .exe файл буде завантажений н
double space after "з"

2019-10-15 11:37 UTC, yevhenorlov commented on docs/i18n-languages/ukrainian/how-to-catch-outgoing-emails-locally.md
> +Для систем на базі Debian, таких як Ubuntu і Linux Mint, виконайте команду
let's add colon here for consistency with line 55

2019-10-15 11:37 UTC, yevhenorlov commented on docs/i18n-languages/ukrainian/how-to-catch-outgoing-emails-locally.md
> +- З будь-якими іншими питаннями, пов'язаних з MailHog або інструкціями по призначених для користувача налаштувань, ви можете ознайомитися в [MailHog](https://github.com/mailhog/MailHog)
"пов'язаних" -> "пов'язаними", 
"налаштувань" -> "налаштуваннях"

2020-02-27 13:40 UTC, raisedadead commented
Closing stale, there are review comments on this thread that have not been addressed? Please feel free to make a fresh PR if still interested.

2020-02-27 13:40 UTC, closed without merging