Corrected some of the grammatical mistakes in readme.md
freeCodeCamp/freeCodeCamp pull request #37237
Opened 2019-10-12 14:36 UTC by adad20

2019-10-15 19:17 UTC, RandellDawson commented
@raisedadead I think most of the changes are good.  The only change I question is changing "Platform" to "The platform".

2019-10-17 07:20 UTC, adad20 commented
> @raisedadead I think most of the changes are good. The only change I question is changing "Platform" to "The platform".

Thank you for your suggestion, I have updated the readme.md file again.

2019-10-17 08:01 UTC, raisedadead requested changes

2019-10-17 08:01 UTC, raisedadead commented on README.md
> +=======
You don't need these lines

2019-10-17 08:01 UTC, raisedadead commented on README.md
> +
You don't need this empty new line

2019-10-18 11:57 UTC, adad20 commented
All the issues has been resolved.

2019-10-18 12:47 UTC, raisedadead requested changes
> All the issues has been resolved.

You just simple clicked the resolve button?

![image](https://user-images.githubusercontent.com/1884376/67095354-53553f80-f1d3-11e9-8dc0-73a1e5079f5a.png)


That will not make the code change for you! Please make changes, as requested before.

2019-10-18 12:59 UTC, adad20 commented
I am sorry I have updated it on my local repository. Now I have resolved all the issues.

2019-10-18 13:18 UTC, RandellDawson requested changes
Please fix the one change @raisedadead requested earlier.

2019-10-18 13:18 UTC, RandellDawson commented on README.md
> +
Please remove this extra line:
```suggestion
```

2019-10-18 13:35 UTC, RandellDawson approved these changes
@raisedadead Feel free to merge if you are fine with the "The platform" change.

2019-10-18 15:14 UTC, raisedadead commented on README.md
> +* [The platform, Build and Deployment Status](#platform-build-and-deployment-status)
```suggestion
* [Platform, Build and Deployment Status](#platform-build-and-deployment-status)
```

This should be understood as platform status, build status and deployment status as three things.

2019-10-18 17:15 UTC, raisedadead approved these changes

2019-10-18 17:16 UTC, merged