Update how-to-catch-outgoing-emails-locally.md
freeCodeCamp/freeCodeCamp pull request #37265
Opened 2019-10-13 16:32 UTC by moi238

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-13 23:10 UTC, RandellDawson requested changes
I have requested several changes.

Thank you.

2019-10-13 23:10 UTC, RandellDawson commented on docs/how-to-catch-outgoing-emails-locally.md
> +When the download completes, click to open the file. A Windows firewall notification may appear, requesting access permission for MailHog. A standard Windows command line prompt will open, where Mail
Please revert the changes on this line.

2019-10-13 23:10 UTC, RandellDawson commented on docs/how-to-catch-outgoing-emails-locally.md
> +Run the following commands to install GO on RPM-based systems, like CentOS, Fedora, Red Hat Linux, etc.
Remove the comma:
```suggestion
Run the following commands to install GO on RPM-based systems like CentOS, Fedora, Red Hat Linux, etc.
```

2019-10-13 23:10 UTC, RandellDawson commented on docs/how-to-catch-outgoing-emails-locally.md
> +Now set the path for Go, with the following commands.
Revert the changes to this line.

2019-10-13 23:10 UTC, RandellDawson commented on docs/how-to-catch-outgoing-emails-locally.md
> +Open a new browser tab, or window, and navigate to [http://localhost:8025](http://localhost:8025) to open your MailHog inbox when the MailHog installation has completed, and MailHog is running. The i
Revert the changes to this line.

2019-10-13 23:10 UTC, RandellDawson commented on docs/how-to-catch-outgoing-emails-locally.md
> +Two tabs that allow you to view either plain text, or source content, will be available when you open a given email. Ensure that the plain text tab is selected as below.
Revert changes to this line.

2019-10-13 23:10 UTC, RandellDawson commented on docs/how-to-catch-outgoing-emails-locally.md
> +Run the following commands to install GO on Debian-based systems, like Ubuntu and Linux Mint.
Please revert the changes to this line.

2019-10-14 13:38 UTC, moi238 reviewed
All changes made as requested.

2019-10-15 19:13 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2019-10-15 22:38 UTC, RandellDawson approved these changes

2019-10-15 22:48 UTC, RandellDawson approved these changes

2019-10-16 13:13 UTC, merged