Update how-to-work-on-coding-challenges
freeCodeCamp/freeCodeCamp pull request #37266
Opened 2019-10-13 16:41 UTC by moi238

Made some minor grammatical changes to improve the flow of the sentences.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-15 15:01 UTC, RandellDawson requested changes
@moi238 Please see several suggested changes to your PR.  You were adding several unnecessary commas.

2019-10-15 15:01 UTC, RandellDawson commented on docs/how-to-work-on-coding-challenges.md
> +We have JavaScript events that track how long it takes for campers to solve challenges, and we can use them to identify challenges that need to be simplified or split.
Suggested change:
```suggestion
We track how long it takes for campers to solve changes and use this information to identify challenges that need to be simplified or split.
```

2019-10-15 20:52 UTC, moi238 reviewed
All changes made as requested.

2019-10-16 13:14 UTC, RandellDawson commented
Waiting to merge until PR #37103 and #37238 have been reviewed/merged/closed first.

2019-11-20 22:18 UTC, moT01 commented
Fixed conflicts on behalf of user.

2020-03-06 07:15 UTC, raisedadead approved these changes

2020-03-06 07:16 UTC, merged