make Contributing.md in polish
freeCodeCamp/freeCodeCamp pull request #37350
Opened 2019-10-16 21:08 UTC by mathias3

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-20 12:15 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Szczęsliwego rozwijania kodu open source!
"Szczęśliwego"

2019-10-20 12:17 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Możesz przyczynić się do jednego z tych:
"[...] do jednego z tych rzeczy:"

2019-10-20 12:18 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Jesteśmy podekscytowani, że pomożemy Ci wziąć udział we wszystkich tematach, nad którymi chciałbyś pracować. Zachęcamy do zadawania nam pytań na tematy pokrewne, a my chętnie udzielimy wyjaśnień. Upe
"Jesteśmy podekscytowani, by pomóc Ci ze wzięciu udziału"

2019-10-20 12:21 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +1. [Przyczyniaj się do tej otwartej źródłowej bazy danych](#przyczyniaj się do tej otwartej źródłowej bazy danych). Pomóż nam edytować wyzwania związane z kodowaniem lub naprawiaj błędy na platformie
```suggestion
1. [Przyczyniaj się do tej otwartej źródłowej bazy danych](#https://github.com/freeCodeCamp/freeCodeCamp/). Pomóż nam edytować wyzwania związane z kodowaniem lub naprawiaj błędy na platformie edukacyjnej.
```

2019-10-20 12:24 UTC, Qondor requested changes
Corrected few typos and grammar mistakes, but there may be more of them.

2019-10-24 17:38 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +funkcjonowanie freeCodeCamp.org jest możliwe dzięki tysiącom życzliwych wolontariuszy takich jak Ty. Jesteśmy wdzięczni za Twój wkład i cieszymy się, że możemy Cię powitać na pokładzie.
```suggestion
Funkcjonowanie freeCodeCamp.org jest możliwe dzięki tysiącom życzliwych wolontariuszy takich jak Ty. Jesteśmy wdzięczni za Twój wkład i cieszymy się, że możemy powitać Cię na pokładzie.
```

2019-10-24 17:39 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +## Oto kilka zabawnych sposobów, w które możesz pomóc
```suggestion
## Oto kilka fajnych sposobów, w które możesz pomóc
```

2019-10-24 17:41 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +1. [Przyczyniaj się do tej otwartej źródłowej bazy danych](#https://github.com/freeCodeCamp/freeCodeCamp/). Pomóż nam edytować wyzwania związane z kodowaniem lub naprawiaj błędy na platformie edukacy
```suggestion
1. [Rozwijaj tę otwartoźródłowej bazy danych](#https://github.com/freeCodeCamp/freeCodeCamp/). Pomóż nam edytować wyzwania związane z kodowaniem lub naprawiaj błędy na platformie edukacyjnej.
```
This is the proper translation of "open-source" https://sjp.pwn.pl/poradnia/haslo/otwartozrodlowy;10114.html

2019-10-24 17:42 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +2. Pomoc dla kamperów na naszym [forum publicznym](https://www.freecodecamp.org/forum/). [Odpowiedz na pytania dotyczące kodowania](https://www.freecodecamp.org/forum/?max_posts=1) lub [podaj im info
```suggestion
2. Pomoc dla kamperów na naszym [publicznym forum](https://www.freecodecamp.org/forum/). [Odpowiedz na pytania dotyczące kodowania](https://www.freecodecamp.org/forum/?max_posts=1) lub [podaj im informacje zwrotne na temat ich projektów kodowania](https://www.freecodecamp.org/forum/c/project-feedback?max_posts=1).
```

2019-10-24 17:43 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +3. Pomóż nam dodawać napisy (podpisy zamknięte) do naszych [Filmów na kanale YouTube](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ/videos).
```suggestion
3. Pomóż nam dodawać napisy do naszych [filmów na kanale YouTube](https://www.youtube.com/channel/UC8butISFwT-Wl7EV0hUK0BQ/videos).
```

2019-10-24 17:43 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +## Przyczyniaj się do tej otwartej źródłowej bazy danych.
```suggestion
## Przyczyniaj się do tej otwartoźródłowej bazy danych.
```

2019-10-24 17:43 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Wszystkie nasze wyzwania związane z kodowaniem są obsługiwane przez społeczność, dostarczającą specjalistyczną wiedzę od wolontariuszy takich jak Ty.
```suggestion
Wszystkie nasze wyzwania związane z kodowaniem są obsługiwane przez społeczność dostarczającą specjalistyczną wiedzę od wolontariuszy takich jak Ty.
```

2019-10-24 17:45 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +rozwijanie naszego stacku wymaga trochę zrozumienia API, ES6 Syntax, i chęci nauki.
```suggestion

Rozwijanie naszego stacku wymaga trochę zrozumienia API, ES6 Syntax, i chęci nauki.
```

2019-10-24 17:46 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +**Jeśli chcesz pomóc nam udoskonalić naszą bazę danych, możesz albo [skonfigurować freeCodeCamp lokalnie](/docs/how-to-setup-freecamp-locally.md) albo użyć Gitpod, darmowego środowiska online dev.**
```suggestion
**Jeśli chcesz pomóc nam udoskonalić naszą bazę danych, możesz albo [skonfigurować freeCodeCamp lokalnie](/docs/how-to-setup-freecamp-locally.md) albo użyć Gitpod, darmowego internetowego środowiska deweloperskiego.**
```

2019-10-24 17:46 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +(Uruchamia gotowe do kodowania środowisko dev dla freecodecamp w przeglądarce.)
```suggestion
(Uruchamia gotowe do kodowania środowisko deweloperskie dla freecodecamp w przeglądarce.)
```

2019-10-24 17:47 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Jeśli uważasz, że znalazłeś błąd, przeczytaj najpierw artykuł ["Help I've Found a Bug"](https://forum.freecodecamp.org/t/how-to-report-a-bug/19543) i postępuj zgodnie z jego instrukcjami.
```suggestion
Jeśli uważasz, że znalazłeś błąd, przeczytaj najpierw artykuł ["Pomocy znalazłem błąd"](https://forum.freecodecamp.org/t/how-to-report-a-bug/19543) i postępuj zgodnie z jego instrukcjami.
```

Other links have polish names too, so I suppose this one should have as well?

2019-10-24 17:49 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Proszę zwrócić uwagę, że wszelkie problemy, które szukają pomocy przy kodowaniu w przypadku wyzwania, zostaną zamknięte. Śledzenie spraw jest ściśle związane z zagadnieniami związanymi z bazą danych
```suggestion
Zwróć uwagę, że wszelkie problemy, które szukają pomocy przy kodowaniu w przypadku wyzwania, zostaną zamknięte. Śledzenie spraw jest ściśle związane z zagadnieniami związanymi z bazą danych i dyskusjami. W razie wątpliwości, przed sporządzeniem raportu należy [szukać pomocy na forum](https://www.freecodecamp.org/forum).
```

2019-10-24 17:49 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Proszę nie tworzyć problemów z GitHub w sprawach bezpieczeństwa. Zamiast tego, wyślij e-mail na adres `security@freecodecamp.org` i natychmiast się temu przyjrzymy.
```suggestion
Proszę nie tworzyć problemów z GitHub w sprawach bezpieczeństwa. Zamiast tego wyślij e-mail na adres `security@freecodecamp.org` i natychmiast się temu przyjrzymy.
```

2019-10-24 17:51 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Powinieneś przejść przez [**`help wanted`**](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) lub [**`first timers welcome`**](https://github.com/
```suggestion
Powinieneś przejść przez [**`potrzebna pomoc`**](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) lub [**`nowicjusze mile widziani`**](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22first+timers+welcome%22) w celu szybkiego przeglądu tego, nad czym możesz pracować. 
```

2019-10-24 17:52 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Są one do pobrania i nie musisz ubiegać się o pozwolenie przed rozpoczęciem pracy nad nimi. Jeśli te kwestie nie są jasne, co należy zrobić, nie krępuj się zadawać pytań w komentarzach.
```suggestion
Są one do pobrania i nie musisz ubiegać się o pozwolenie przed rozpoczęciem nad nimi pracy. Jeśli w kwestiach tych nie jest jasne, co należy zrobić, nie krępuj się zadawać pytań w komentarzach.
```

2019-10-24 17:53 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +W przypadku literówek i innych zmian w słownictwie, możesz bezpośrednio otwierać żądania ciągnięcia bez wcześniejszego tworzenia problemu. Kwestie są bardziej przydatne do omówienia większych problem
```suggestion
W przypadku literówek i innych zmian w słownictwie, możesz bezpośrednio otwierać żądania ciągnięcia bez wcześniejszego tworzenia problemu. Problemy są bardziej przydatne do omówienia większych problemów związanych z kodem lub aspektami strukturalnymi programu nauczania.
```

2019-10-24 18:06 UTC, Qondor requested changes
I have corrected grammar and syntax errors. Seem okay now.

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Proszę nie tworzyć problemów z GitHub w sprawach bezpieczeństwa. Zamiast tego, wyślij e-mail na adres `security@freecodecamp.org` i natychmiast się temu przyjrzymy.
```suggestion
Proszę nie tworzyć problemów z GitHub w sprawach bezpieczeństwa. Zamiast tego wyślij e-mail na adres `security@freecodecamp.org` a natychmiast się temu przyjrzymy.
```

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Powinieneś przejść przez [**`help wanted`**](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) lub [**`first timers welcome`**](https://github.com/
```suggestion
Powinieneś przejść przez [**`potrzebna pomoc`**](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) lub [**`nowicjusze mile widziani`**](https://github.com/freeCodeCamp/freeCodeCamp/issues?q=is%3Aopen+is%3Aissue+label%3A%22first+timers+welcome%22) w celu szybkiego przeglądu tego, nad czym możesz pracować. 
```

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Są one do pobrania i nie musisz ubiegać się o pozwolenie przed rozpoczęciem pracy nad nimi. Jeśli te kwestie nie są jasne, co należy zrobić, nie krępuj się zadawać pytań w komentarzach.
```suggestion
Są one do pobrania i nie musisz ubiegać się o pozwolenie przed rozpoczęciem nad nimi pracy. Jeśli w kwestiach tych nie jest jasne, co należy zrobić, nie krępuj się zadawać pytań w komentarzach.
```

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +W przypadku literówek i innych zmian w słownictwie, możesz bezpośrednio otwierać żądania ciągnięcia bez wcześniejszego tworzenia problemu. Kwestie są bardziej przydatne do omówienia większych problem
```suggestion
W przypadku literówek i innych zmian w słownictwie, możesz bezpośrednio otwierać żądania ciągnięcia bez wcześniejszego tworzenia problemu. Problemy są bardziej przydatne do omówienia większych problemów związanych z kodem lub aspektami strukturalnymi programu nauczania.
```

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Zazwyczaj nie przydziela się problemów nikomu innemu niż długoletni współpracownicy, aby uniknąć ambitnego nie pojawienia się na zajęciach. Zamiast tego postępujemy zgodnie z poniższą polityką, aby b
```suggestion
Zazwyczaj nie przydziela się problemów nikomu innemu niż długoletnim współpracownikom, aby uniknąć ambitnego nie dostarczenia wyników. Zamiast tego postępujemy zgodnie z poniższą polityką, aby być sprawiedliwym dla wszystkich:
```

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Przeczytaj nasz [How to Contribute to Open Source Guide](https://github.com/freeCodeCamp/how-to-contribute-to-open-source).
```suggestion
Przeczytaj nasz [Poradnik jak wnieść wkład do Open Source](https://github.com/freeCodeCamp/how-to-contribute-to-open-source).
```

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +##### Utknęłam na czymś, co nie jest zawarte w tej dokumentacji. Jak mogę uzyskać pomoc?
```suggestion
##### Utknąłem na czymś, co nie jest zawarte w tej dokumentacji. Jak mogę uzyskać pomoc?
```

2019-10-24 18:06 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +- [Nasz publiczny współpracownik - chat room na Gitterze](https://gitter.im/FreeCodeCamp/Contributors)
```suggestion
- [Nasz publiczny chat room dla współpracowników na Gitterze](https://gitter.im/FreeCodeCamp/Contributors)
```

2019-10-25 04:35 UTC, mathias3 commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +1. [Przyczyniaj się do tej otwartej źródłowej bazy danych](#https://github.com/freeCodeCamp/freeCodeCamp/). Pomóż nam edytować wyzwania związane z kodowaniem lub naprawiaj błędy na platformie edukacy
wymagana poprawka do tej poprawki- masz tu literówkę

2019-10-25 04:36 UTC, mathias3 commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Nie potrzebujesz żadnego zezwolenia dla spraw, które są oznaczone jako "pomoc poszukiwana" lub "pierwsze powitanie czasowe", jak wyjaśniono wcześniej. Postępuj zgodnie z wytycznymi i otwórz prośbę o
literówka "potrzeban pomoc"

2019-10-25 04:46 UTC, mathias3 commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Jeśli masz wątpliwości, możesz skontaktować się z naszym zespołem programistów platformy, aby Ci w tym pomóc:
done

2019-10-26 14:23 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +Nie potrzebujesz żadnego zezwolenia dla spraw, które są oznaczone jako "pomoc poszukiwana" lub "pierwsze powitanie czasowe", jak wyjaśniono wcześniej. Postępuj zgodnie z wytycznymi i otwórz prośbę o
Great catch, thanks.

2019-10-26 14:24 UTC, Qondor commented on docs/i18n-languages/polish/CONTRIBUTING.md
> +1. [Przyczyniaj się do tej otwartej źródłowej bazy danych](#https://github.com/freeCodeCamp/freeCodeCamp/). Pomóż nam edytować wyzwania związane z kodowaniem lub naprawiaj błędy na platformie edukacy
Corrected too.

2019-10-27 12:36 UTC, RandellDawson commented
@mathias3 You have an earlier PR (#37401) which creates a CONTRIBUTING.md file.  Please either close this PR and make the same changes to #37401 or close #37401 and add its changes to this PR.  You also have another PR (#37384) which creates a CONTRIBUTING.md file.  You should only have a single PR which makes changes to the CONTRIBUTING.md file.  There can be other files on the same PR, but no multiple PRs for the same file.  Merging these would cause a substantial merge conflict.

Thank you.

2019-10-27 17:07 UTC, Qondor approved these changes

2019-10-27 22:06 UTC, mathias3 commented
> @mathias3 You have an earlier PR (#37401) which creates a CONTRIBUTING.md file. Please either close this PR and make the same changes to #37401 or close #37401 and add its changes to this PR. You also have another PR (#37384) which creates a CONTRIBUTING.md file. You should only have a single PR which makes changes to the CONTRIBUTING.md file. There can be other files on the same PR, but no multiple PRs for the same file. Merging these would cause a substantial merge conflict.
> 
> Thank you.
Done. I deleted contributing.md from both (#37401) and(#37384)

2019-10-27 22:11 UTC, RandellDawson commented
@mathias3 I should have chosen my words more carefully.  You can't just delete the file from the PR, because that would delete the file from the repo.  Instead you need to revert the changes to the file on the PR, so it is as if you never made any changes to it.

2019-11-10 21:10 UTC, mathias3 commented
> @mathias3 You have an earlier PR (#37401) which creates a CONTRIBUTING.md file. Please either close this PR and make the same changes to #37401 or close #37401 and add its changes to this PR. You also have another PR (#37384) which creates a CONTRIBUTING.md file. You should only have a single PR which makes changes to the CONTRIBUTING.md file. There can be other files on the same PR, but no multiple PRs for the same file. Merging these would cause a substantial merge conflict.
> 
> Thank you.

ok, i closed all others pull request to avoid merge conflict. All files are in this pr and they were checked by Qondor and few others for  spell check

2020-03-11 13:00 UTC, RandellDawson commented
@raisedadead Do we have any reviewers for this one?

2020-03-12 16:53 UTC, raisedadead commented
I do not believe we have anyone, but I am going ahead and merging this for the hard work that has been put in by @mathias3 :)

2020-03-12 16:54 UTC, merged