fix: conditionally load MathJax
freeCodeCamp/freeCodeCamp pull request #37360
Opened 2019-10-17 07:55 UTC by scissorsneedfoodtoo

Removed MathJax CDN from header and set it up to download whenever a user goes to a Rosetta Code challenge

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-10-17 10:58 UTC, scissorsneedfoodtoo commented
Sorry, should have put this into draft mode. It's ready for review now.

2019-10-17 11:30 UTC, raisedadead commented
> Sorry, should have put this into draft mode. It's ready for review now.

Resolve conflicts.

2019-10-17 14:40 UTC, ojeytonwilliams requested changes
Hey @scissorsneedfoodtoo once you've visited a challenge everything looks good - it's just that typically MathJax isn't going to be ready when the component mounts.

2019-10-17 14:40 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/Side-Panel.js
> +  async componentDidMount() {
```suggestion
  componentDidMount() {
```
I don't think this is necessary, see below.

2019-10-17 14:40 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/Side-Panel.js
> +    const MathJax = await global.MathJax;
```suggestion
    const MathJax = global.MathJax;
```
`MathJax` is just an ordinary object, no `await`ing required.

2019-10-17 14:40 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/Side-Panel.js
>      if (MathJax) {
The case where MathJax isn't loaded needs to be handled, too.  This https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/components/Donation/components/DonateModal.js#L55-L61 is how it was handled for Stripe.

2019-10-18 11:40 UTC, scissorsneedfoodtoo commented
Will wait for https://github.com/freeCodeCamp/freeCodeCamp/pull/37388 to land before updating further.

2019-10-20 11:12 UTC, raisedadead commented
@scissorsneedfoodtoo bump for further work.

2019-10-28 06:04 UTC, scissorsneedfoodtoo commented
@ojeytonwilliams, thank you for your earlier review. I went through and made the changes you suggested.

I updated the MathJax fallback script loader to work like the one in `donate.js`, but it always seems to run for some reason. Took a look at `gatsby-ssr.js` and can't figure out while the Stripe script loads when on a challenge or `/donate` but not on any of the Rosetta Code problems, leading to the fallback running when users first visit a Rosetta Code challenge.

2019-10-28 12:29 UTC, ojeytonwilliams commented
@scissorsneedfoodtoo I think the issue is that https://github.com/freeCodeCamp/freeCodeCamp/blob/4ff2870ced8b67ad98a81efdf6a5fa5d9c88171d/client/gatsby-ssr.js#L66
should not have a trailing slash, since the `pathname`s Gatsby returns don't have them.

2019-10-28 12:33 UTC, ojeytonwilliams commented
So, yeah, sorry about that!  I think that was my mistake.

2019-10-29 09:03 UTC, scissorsneedfoodtoo commented
@ojeytonwilliams, no need to apologize! I should have thought of trying that. Thank you for pointing that out -- learned something new about Gatsby.

I'll go in and remove that slash.

2019-10-29 12:03 UTC, ojeytonwilliams commented
Thanks for sorting that out!

So, I've been having a look at it in development mode and I noticed something odd.  This is what you get when you reload the first challenge (100 doors)

![image](https://user-images.githubusercontent.com/15801806/67763212-71c70080-fa47-11e9-85c9-e69de026fe21.png)
while on .dev it looks like this
![image](https://user-images.githubusercontent.com/15801806/67763275-97540a00-fa47-11e9-8d7e-ea6f2e78fe96.png)

But, if you navigate to 100 doors from another challenge, it's fine.

I think the configuration is getting messed up somehow (it's treating `(` as delimiters, but only some of the time).  I'll see if I can figure out why after I grab some lunch.

2019-10-29 13:42 UTC, scissorsneedfoodtoo commented
@ojeytonwilliams, great catch. I've been looking at the very math heavy pages and didn't notice that at all.

I believe you're right, MathJax is treating `(` as delimiters. Probably has to do with the way I'm trying to set the configuration in the fallback script in `scriptLoaders.js`. The parentheses probably need to be escaped there, but we may be able to take that extra configuration out entirely.

I'll do some quick testing.

2019-10-29 15:14 UTC, ojeytonwilliams commented
@scissorsneedfoodtoo I'm glad you realised they needed escaping twice, I had not noticed there were some challenges that used them. I was going to suggest we cut them out.  Oops.

Anyway, I've added some changes to simplify things a bit.  I realised that using `state` as an intermediary wasn't necessary and we could just see if `global.MathJax` was defined or not.  I'm going to double check this doesn't break anything, but I think it's okay.

2019-10-30 02:20 UTC, scissorsneedfoodtoo commented
@ojeytonwilliams, awesome! Thank you for simplifying this much further. It's much easier to reason about now.

I also thought it would be better to remove the backticks until I reviewed the MathJax documentation again. Doesn't look great now, but I'm glad it's working as intended.

2019-10-30 08:05 UTC, ojeytonwilliams approved these changes

2019-10-30 08:08 UTC, ojeytonwilliams commented
@scissorsneedfoodtoo if you're happy I think we're basically there. However, since I've been tweaking the code @ahmadabdolsaheb could give this a quick review?

2019-10-30 12:46 UTC, ahmadabdolsaheb commented
tested locally, LGTM

2019-10-30 12:46 UTC, merged