Create devops.md
freeCodeCamp/freeCodeCamp pull request #37384
Opened 2019-10-17 22:57 UTC by mathias3

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-11-09 20:26 UTC, Qondor requested changes

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +Dziękujemy za zainteresowanie dowiedzeniem się tym, jak robimy DevOps dla platformy na freeCodeCamp.org.
```suggestion
Dziękujemy za zainteresowanie się tym, jak robimy DevOps dla platformy na freeCodeCamp.org.
```

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +Staraliśmy się, aby język w tym przewodniku był jak najprostszy dla wszystkich. Jednak tutaj możesz znaleźć  techniczny żargon. Nie jest to wyczerpujący przewodnik po wszystkich operacjach i ma być w
```suggestion
Staraliśmy się, aby język w tym przewodniku był jak najprostszy dla wszystkich. Znaleźć możesz tutaj jednak techniczny żargon. Nie jest to wyczerpujący przewodnik po wszystkich operacjach i ma być wykorzystywany tylko jako punkt odniesienia dla zrozumienia systemów.
```

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +Zazwyczaj gałąź `master` jest łączona w gałęzią [`produkcyjny-stage`](https://github.com/freeCodeCamp/freeCodeCamp/tree/production-staging) raz dziennie i wydawana w izolowanej infrastrukturze. Nazyw
```suggestion
Zazwyczaj gałąź `master` jest łączona z gałęzią [`produkcyjny-stage`](https://github.com/freeCodeCamp/freeCodeCamp/tree/production-staging) raz dziennie i wydawana w izolowanej infrastrukturze. Nazywamy to naszą aplikacją "staging/beta".
```

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +Jest ona identyczna z naszym środowiskiem produkcyjnym w `freeCodeCamp.org`, innym niż wykorzystującym osobny zestaw baz danych, serwerów, web-proxy, itp. Ta izolacja pozwala nam testować ciągły rozw
```suggestion
Jest ona identyczna z naszym środowiskiem produkcyjnym we `freeCodeCamp.org`, innym niż wykorzystującym osobny zestaw baz danych, serwerów, web-proxy, itp. Ta izolacja pozwala nam testować ciągły rozwój i funkcje w scenariuszu "production like", bez wpływu na zwykłych użytkowników platform freeCodeCamp.org.
```

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +Dziękujemy Ci za zgłaszanie błędów, które napotykasz i pomagamy w ulepszaniu freeCodeCamp.org. Rządzisz!
```suggestion
Dziękujemy Ci za zgłaszanie błędów, które napotykasz, pomagasz w ten sposób w ulepszaniu freeCodeCamp.org. Rządzisz!
```

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +Zespół dev-team łączy zmiany z gałęzi `master` do `production-stage`, gdy tylko je wypuszczą. Zazwyczaj górny commit powinien być tym, co widzisz na żywo na stronie. Możesz określić dokładną wersję w
```suggestion
Zespół dev-team łączy zmiany z gałęzi `master` do `production-stage` gdy tylko je wypuszczą. Zazwyczaj górny commit powinien być tym, co widzisz na żywo na stronie. Możesz określić dokładną wersję wdrożonej wersji odwiedzając dzienniki budowy i wdrażania dostępne poniżej w sekcji status.
```
"górny"? Was it "top commit" in the original version? Then it should be something like "ostatni" maybe.

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +Zespół dev-team łączy zmiany z gałęzi `production-stage` na `production-current`, gdy tylko je wypuszczą. Górne commit powinno być to, co widzisz na żywo na stronie. Możesz określić dokładną wersję w
```suggestion
Zespół dev-team łączy zmiany z gałęzi `production-stage` na `production-current`, gdy tylko je wypuszczą. Górne commit powinno być to, co widzisz na żywo na stronie. Możesz określić dokładną wersję wdrożonej wersji, odwiedzając dzienniki budowy i wdrażania dostępne poniżej w sekcji statusu.
```
Again, "top commit" =/= "górny commit".

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +> Uwaga: W nadchodzących dniach usprawnilibyśmy ten przepływ, który można osiągnąć dzięki prośbom o wyciągnięcie, w celu lepszego zarządzania dostępem i przejrzystości.
```suggestion
> Uwaga: W nadchodzących dniach usprawnimy ten przepływ, który można osiągnąć dzięki prośbom o wyciągnięcie, w celu lepszego zarządzania dostępem i przejrzystości.
```

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +3. Sprawdzić, czy urządzenie Travis CI przechodzi przez odgałęzienie główne w górę rzeki.
```suggestion
3. Sprawdź, czy urządzenie Travis CI przechodzi przez odgałęzienie główne w górę rzeki.
```

2019-11-09 20:26 UTC, Qondor commented on docs/i18n-languages/polish/devops.md
> +5. Przesunięcie zmian z fazy master na fazę produkcji
```suggestion
5. Przesuń zmianę z fazy master na fazę produkcji
```

2019-11-10 20:58 UTC, closed without merging

2019-11-10 20:59 UTC, mathias3 commented
changec included in make Contributing.md in polish #37350