#37410  Fixed the issue of Github icon background not covering on hover.
freeCodeCamp/freeCodeCamp pull request #37414
Opened 2019-10-20 11:23 UTC by MathewtheCoder

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37410

2019-10-21 12:44 UTC, Mathew1706 commented
@ahmadabdolsaheb Can you please review this PR ?

2019-10-21 12:52 UTC, raisedadead commented
Thanks for your patience, this PR will be reviewed in due course of time.

2019-10-21 15:06 UTC, moT01 requested changes
You are targeting the `last-child`, so only the last icon will have the styles you applied...
<img width="209" alt="Screen Shot 2019-10-21 at 10 07 38 AM" src="https://user-images.githubusercontent.com/20648924/67217619-a6550f80-f3ea-11e9-880f-82b4d5c09e2a.png">
<img width="203" alt="Screen Shot 2019-10-21 at 9 58 32 AM" src="https://user-images.githubusercontent.com/20648924/67216797-64779980-f3e9-11e9-8eb9-385f29a1152c.png">
<img width="198" alt="Screen Shot 2019-10-21 at 9 58 25 AM" src="https://user-images.githubusercontent.com/20648924/67216799-65103000-f3e9-11e9-9b8f-f74bc6d49f5e.png">
<img width="199" alt="Screen Shot 2019-10-21 at 9 58 15 AM" src="https://user-images.githubusercontent.com/20648924/67216800-65103000-f3e9-11e9-864a-b15dbb14bbb2.png">

Anyone else want to weigh in on what they think about the circular background on hover? I'm not sure we need a hover effect at all here - the mouse goes to `pointer` on hover, so it's obvious that it's a link. Also, you can't really see the background on the linkedin icon. I think I would prefer nothing but the mouse, or perhaps change the color of the icon to a lighter blue or gray instead; similar to the github icon at the bottom of this page.

2019-10-21 15:25 UTC, raisedadead commented
Thanks for these screenshots and the QA, Tom.

I agree with you.

> Anyone else want to weigh in on what they think about the circular background on hover?

We do not need any hover or highlight effects. The pointer is good as it is.

@MathewtheCoder Can you please make these changes? Also now taking a look, I think you simply put these from your browser's debugging window.

I would recommend taking a look at our [guidelines for contributing](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md) and setting up things on your local machine or GitPod.

2019-10-21 15:47 UTC, MathewtheCoder commented
@raisedadead Yes i will remove the background on hover. 

>  Can you please make these changes? Also now taking a look, I think you simply put these from your browser's debugging window.
I had setup the application locally but was focused on the github icon that i forgot to check for other references. I will make the necessary change and push.

2019-10-23 05:47 UTC, MathewtheCoder commented
@raisedadead The changes you requested have been implemented.

2019-10-23 09:50 UTC, raisedadead requested changes

2019-10-23 09:50 UTC, raisedadead commented on client/src/components/profile/components/social-icons.css
> -  margin: 0 0 1.5em 0;
Did you test this locally? Share a few screenshot on how it looks.

2019-10-23 16:17 UTC, moT01 requested changes
This doesn't completely remove the hover effect...

nothing hovered...
<img width="360" alt="Screen Shot 2019-10-23 at 10 55 12 AM" src="https://user-images.githubusercontent.com/20648924/67413238-67f45780-f586-11e9-8acb-1d9517756c4b.png">

twitter hovered...
<img width="256" alt="Screen Shot 2019-10-23 at 10 59 15 AM" src="https://user-images.githubusercontent.com/20648924/67413255-6e82cf00-f586-11e9-8b4f-6a212a409c2c.png">

It's pretty subtle, and I'm with that if you are @raisedadead - it's better than it is now.

But removing the margin misaligned the icons, they are all pushed left a little bit and not centered anymore.

2019-10-23 16:33 UTC, raisedadead commented
> But removing the margin misaligned the icons, they are all pushed left a little bit and not centered anymore.

Yup I know, I left a comment and I am pretty sure this was not tested locally. We should wait for @MathewtheCoder to get back to us. 

I am fine with the subtle highlight that still remains (although now you said it, it does trigger my OCD 😅)

2019-10-24 19:40 UTC, Mathew1706 commented
@moT01 @raisedadead Reverted the margin that was present on the last item and also fixed the issue you mentioned earlier about the slight highlight on hover.
![Oct-25-2019 01-08-15](https://user-images.githubusercontent.com/52909440/67519296-2c5fa780-f6c4-11e9-9b13-8fab622aa8e3.gif)

2019-10-25 19:51 UTC, moT01 requested changes
Alright @MathewtheCoder, I was ready to say that this looks good - but I noticed one last thing thanks to @rickysyamsi's PR(https://github.com/freeCodeCamp/freeCodeCamp/pull/37499) for the same issue... the focus state of the icons still show the old background...
<img width="105" alt="Screen Shot 2019-10-25 at 2 48 59 PM" src="https://user-images.githubusercontent.com/20648924/67599890-a03a9800-f736-11e9-8105-12f2a356fd52.png">
Add the suggestion and we're good to go. You can simply click the "commit suggestion" button to do that if you want.

This is being really nit picky - but, we might as well make it right since we're here.

2019-10-25 19:51 UTC, moT01 commented on client/src/components/profile/components/social-icons.css
> +.social-media-icons > a:hover {
```suggestion
.social-media-icons > a:hover,
.social-media-icons > a:focus {
```

2019-10-25 20:00 UTC, moT01 commented
Hey, @Mathew1706 / @MathewtheCoder - I'm not sure if you noticed, but you have two names here making posts on this PR. I had a similar problem in the past at one point, it had to do with my local git configuration or something. Maybe [check this out](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) if it's not supposed to be like that

2019-10-26 11:56 UTC, MathewtheCoder commented
@moT01 I have committed your hint. And thanks for pointing out the issue with my git account.

2019-10-27 15:31 UTC, moT01 approved these changes
LGTM @MathewtheCoder 🎉 Thanks for fixing all these 🎉

2019-10-31 12:18 UTC, raisedadead approved these changes

2019-10-31 12:19 UTC, merged