fix(client): Improve client validation accessibility
freeCodeCamp/freeCodeCamp pull request #37459
Opened 2019-10-22 13:57 UTC by kishore-devaraj

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37377

**Little Description:**
Added the check icon at the end of the FormControl Input field when the there is no error or warning state for more accessibility.

2019-10-23 13:47 UTC, raisedadead requested changes
I think this needs more work, the grayed out version of the check can be misleading, and it turning green is not very much noticeable.

Maybe the checkbox should not come up until the url has been validated. And once it does it should be green as it does in the final state.

Also we should add placeholder URLs to all these fields.

2019-10-23 19:23 UTC, kishore-devaraj commented
@raisedadead I have updated the PR with the following:
1. No more grayed out version of check icon.
2. Check icon (Green) appears only when the validation is correct.
3. Dummy placeholder added for all the fields in internet presence.

2019-10-23 19:35 UTC, raisedadead commented
Umm, you have a bunch of unrelated commits in here for some reason. You would need a rebase.

Reach out to [contributors chat room](https://gitter.im/FreeCodeCamp/Contributors) if you need help with that.

2019-10-24 11:27 UTC, kishore-devaraj commented
@raisedadead Did a rebase and force pushed only commits required for this PR.

2019-10-24 11:47 UTC, raisedadead requested changes
Nitpicks.

2019-10-24 11:47 UTC, raisedadead commented on client/src/components/settings/Internet.js
> +                placeholder='https://www.linkedin.com/user-name'
```suggestion
                placeholder='https://www.linkedin.com/in/user-name'
```

2019-10-24 11:47 UTC, raisedadead commented on client/src/components/settings/Internet.js
> +                placeholder='https://user-name.com'
```suggestion
                placeholder='https://example.com'
```

2019-10-25 08:13 UTC, kishore-devaraj commented
@raisedadead Hope, everything is fine now.

2019-11-06 14:13 UTC, raisedadead approved these changes

2019-11-06 14:13 UTC, merged