Improved Russian translate
freeCodeCamp/freeCodeCamp pull request #37538
Opened 2019-10-25 19:26 UTC by greggubarev

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

2019-12-21 21:09 UTC, RandellDawson commented
@greggubarev Can you fix the merge conflict so we can get a final review? 

Thanks

2019-12-23 06:34 UTC, greggubarev commented
> @greggubarev Can you fix the merge conflict so we can get a final review?
> 
> Thanks

done

2020-01-24 06:31 UTC, greggubarev commented
@RandellDawson can you review my PR please?

2020-03-26 19:16 UTC, RandellDawson requested changes
@greggubarev See my suggestion.

2020-03-26 19:16 UTC, RandellDawson commented on curriculum/challenges/russian/03-front-end-libraries/bootstrap/add-font-awesome-icons-to-our-buttons.russian.md
> +  - text: Ваша иконка <code>fa-thumbs-up</code>  должен находиться внутри вашей кнопки «Нравится».
"Like" should not be translated here.

2020-03-26 19:17 UTC, RandellDawson requested changes

2020-03-26 19:17 UTC, RandellDawson commented on curriculum/challenges/russian/03-front-end-libraries/bootstrap/add-font-awesome-icons-to-our-buttons.russian.md
> +
Please remove the extra line.
```suggestion

```

2020-03-26 19:17 UTC, RandellDawson commented on curriculum/challenges/russian/03-front-end-libraries/bootstrap/add-font-awesome-icons-to-our-buttons.russian.md
> +
Please remove the extra line.
```suggestion

```

2020-04-05 19:54 UTC, greggubarev commented on curriculum/challenges/russian/03-front-end-libraries/bootstrap/add-font-awesome-icons-to-our-buttons.russian.md
> +  - text: Ваша иконка <code>fa-thumbs-up</code>  должен находиться внутри вашей кнопки «Нравится».
done!

2020-04-05 19:54 UTC, RandellDawson approved these changes

2020-04-05 21:51 UTC, merged

2020-04-05 21:51 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉