fix(curriculum): Improved Use Recursion to Create a Countdown
freeCodeCamp/freeCodeCamp pull request #37548
Opened 2019-10-25 22:55 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Since the new challenge [Use Recursion to Create a Countdown]() was released to production, there have been many confused users on how the challenge is supposed to work.  The confusion stems from the fact that we have a helper function behind the scenes which is technically apart of the challenge tests.  The function `countdown` function does not need to return anything, so users can really test it directly.  This is coupled with the fact that unless they understand the 1st argument is actually going to be an empty array behind the scenes.

I have taken a first shot at rewriting the challenge by sticking to the way we have written other such challenges which have functions that actually return values the users can test.  Any thoughts on how to improve this challenge further are welcomed.

See below for several forum discussions of this challenge.

* https://www.freecodecamp.org/forum/t/basic-javascript-use-recursion-to-create-a-countdown/322222

* https://www.freecodecamp.org/forum/t/use-recursion-to-create-a-countdown/323606

* https://www.freecodecamp.org/forum/t/confused-of-referenceerror-myarray-is-not-defined/323822

2019-10-27 00:18 UTC, Manish-Giri commented
While I agree that this particular challenge needs some improvements, I wonder if it might be a bit tricky for beginners to conceptualize a recursive solution that uses `.concat()` - create an array with `n` in every call and merge it with the array being returned from the next recursive call. The examples used with `.push()` introduced in the earlier challenge(s) were pretty basic, so this might be quite a big leap (especially for beginners).

Maybe, we could add some explanation about how `myArray` is being set up and used behind the scenes in the current challenge, and (potentially) how campers are expected to use it? This seems to be what's confusing most campers, based on the forum posts and is also what confused me, tbh. This way, we can also be consistent with the method of using `.push()`, following from the previous challenge. 

But yes, this way there is no return value from the recursion, so we would need to consider which of the two approaches is better.

2019-10-27 01:19 UTC, RandellDawson commented
@Manish-Giri The users will have already learned unshift, so the following solution could be used:
```js
function countdown(n) {
  if (n < 1) {
    return [];
  } else {
    const arr = countdown(n - 1);
    arr.unshift(n);
    return arr;
  }
}
```

2019-10-27 21:34 UTC, Manish-Giri commented
@RandellDawson Sounds good. The example would help.

2019-10-27 21:39 UTC, RandellDawson commented
I will wait until a couple other mods chime in before committing further changes.

2019-10-27 22:47 UTC, danshil commented
I am a student who just tried to complete the project. The confusion stems from this problem having a global myArray variable that is being manipulated by this function. This is different from any of the preceding problems, and the fact that there is a global variable is not identified in the problem text. This leads to problems when you try to return algorithms.

A simple statement such as "There is a global variable called _myArray_ and you are adding values to this array..."
Or even better, just include a `const myArray = [];` above the function and let students figure out what's going on.

2019-10-27 22:56 UTC, RandellDawson commented
> The fact that there is a global variable is not identified in the problem text. 

There is no global variable being used here.

2019-10-28 21:33 UTC, Ieahleen commented
much less confusing like this... even if it has become a variation of the previous one, [Use Recursion to Create a Range of Numbers](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-range-of-numbers)

seems a difficult situation! would there be an other simple algorithm that could use recursion, but is not the usual factorial calculation, or countdown? even if it is just making mandatory solving something like reversing a string with recursion. in this way there is some variation in the challenges, but they are not too ermetic for new learners

2019-10-28 22:06 UTC, RandellDawson commented
@Ieahleen The trick is having an example which is similar enough in the description section of the challenge, so the solution only takes slight changes.  Otherwise, we are creating a challenge which would belong in one of the 3 algorithm sections (which defeats the purpose of having it in the Basic JavaScript section). 

Another "fairly" simple recursive problem would be to first show how recursion could be use to sum the elements of an array (like below):
```js
function sumArrayElements(arr) {
  if (arr.length <= 1) {
    return arr[0] || 0;
  }
  else {
    return arr.pop() + sumArrayElements(arr);
  }
}

sumArrayElements([5, 2, 3]); // 10
```
and then ask the user to create a recursive solution to multiply the elements of an array (finding the product):
```js
function multiplyArrayElements(arr) {
  if (arr.length <= 1) {
    return arr[0] || 0;
  }
  else {
    return arr.pop() * multiplyArrayElements(arr);
  }
}

multiplyArrayElements([5, 2, 3]); // 30
```
However, this seem to easy (only have to change `+` to a `*` to solve.

2019-10-29 09:20 UTC, ojeytonwilliams commented
It seems to me that the [previous challenge](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-range-of-numbers) is the trickier one, since it's a function of two variables.  At least I had more difficulty with it when I re-tried it.  Might be better to have that function be the final challenge.

So, what I think is that the second recursion challenge should be to create 

```js
function countup(n) {
  if (n < 1) {
    return [];
  } else {
    const countArray = countup(n - 1);
    countArray.push(n);
    return countArray ;
  }
}
```

and the final challenge should be to create

```js
function rangeOfNumbers(startNum, endNum) {
  if (endNum < startNum) {
    return [];
  } else {
    var numbers = rangeOfNumbers(startNum, endNum - 1);
    numbers.push(endNum);
    return numbers;
  }
}
```

This would make them quite similar, but I think recursion is a tricky enough concept that doing a few variations on a theme would not hurt.

2019-11-01 23:11 UTC, Writhyn commented
Also as someone trying to solve this, my problem was that it almost sounded like my function was supposed to *create* the myArray array. There was no indication that myArray was already defined as an empty array in the system to be used for the tests. Simply putting `const myArray = [];` above the "change code below this line" would make this crystal clear with no other changes.

2019-11-27 00:46 UTC, RandellDawson commented
@ojeytonwilliams I shifted things around, so the 2nd to last recursion challenge is the Use Recursion to Create a Countdown challenge.  It has an example in it along with the content that was originally in the now 3rd challenge (Use Recursion to Create a Range of Numbers).  Do we need an example in the 3rd one now or is the information and example in the now 2nd challenge enough for the user to be able to solve the last one without an example?  I feel any example using a range of any sort would give too much away.

2019-11-27 05:27 UTC, raisedadead approved these changes
Platform code LGTM.

2019-12-01 00:10 UTC, moT01 requested changes
Overall, this looks good - I made a number of suggestions, there's a few that are my opinion and could maybe be left alone - others that might have been preexisting. But some of them should probably be fixed. Let me know if you if you disagree.

2019-12-01 00:24 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown.md
>    - text: Your code should not rely on any kind of loops (<code>for</code> or <code>while</code> or higher order functions such as <code>forEach</code>, <code>map</code>, <code>filter</code>, or <cod
@moT01 It seems your suggestion also removes a necessary space before the `- text` that will cause the tests to fail if removed.

2019-12-01 01:59 UTC, moT01 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown.md
>    - text: Your code should not rely on any kind of loops (<code>for</code> or <code>while</code> or higher order functions such as <code>forEach</code>, <code>map</code>, <code>filter</code>, or <cod
I modified it.

2019-12-01 03:42 UTC, RandellDawson commented
@moT01 Changes made.

2019-12-01 14:10 UTC, moT01 approved these changes
Looks like that space made travis fail.

2019-12-01 14:13 UTC, moT01 requested changes

2019-12-01 14:13 UTC, moT01 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/use-recursion-to-create-a-countdown.md
> +   - text: Your code should not rely on any kind of loops (<code>for</code>, <code>while</code> or higher order functions such as <code>forEach</code>, <code>map</code>, <code>filter</code>, and <cod
```suggestion
  - text: Your code should not rely on any kind of loops (<code>for</code>, <code>while</code> or higher order functions such as <code>forEach</code>, <code>map</code>, <code>filter</code>, and <code>reduce</code>).
```

2019-12-01 16:35 UTC, moT01 approved these changes
LGTM 🎉 - hey @ojeytonwilliams, you have an open PR that works on some of these files I think - do you want to take a quick look at this and make sure it's not going to create any complications.

2019-12-02 16:48 UTC, ojeytonwilliams commented
@moT01 it's fine, I'll just review and merge this.  If there are problems with my PR, I'll sort them out.

2019-12-02 16:57 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2019-12-02 16:58 UTC, merged