Update README.md
freeCodeCamp/freeCodeCamp pull request #37585
Opened 2019-10-27 23:23 UTC by thegodland

make more readable

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2020-03-20 17:08 UTC, thecodingaviator requested changes

2020-03-20 17:08 UTC, thecodingaviator commented on docs/i18n-languages/chinese/README.md
> +请不要在GitHub上为安全问题创建Issues。作为替代，请发送E-mail到`security@freecodecamp.org`，我们会立刻对此进行调查。
```suggestion
请不要在GitHub上为安全问题创建Issues。作为替代，请发送个E-mail到`security@freecodecamp.org`，我们会立刻对此进行调查。
```

2020-03-22 03:30 UTC, S1ngS1ng approved these changes
As suggested by @thegodland , "请发送E-mail到\`security@freecodecamp.org\`" looks good to me.

2020-03-22 09:23 UTC, thecodingaviator approved these changes

2020-03-22 09:24 UTC, thecodingaviator commented
@raisedadead Can we have this merged?

2020-03-22 10:44 UTC, merged