Improved RU translate
freeCodeCamp/freeCodeCamp pull request #37640
Opened 2019-10-31 19:36 UTC by povar163

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-12-23 06:43 UTC, greggubarev commented
LGTM

2019-12-23 18:08 UTC, RandellDawson requested changes
@povar163 See requested changes.

2019-12-23 18:08 UTC, RandellDawson commented on curriculum/challenges/russian/06-information-security-and-quality-assurance/information-security-with-helmetjs/understand-bcrypt-hashes.russian.md
> +  - текст: BCrypt является зависимостью
@povar163 You should not be translating the yaml id
```suggestion
  - text: BCrypt является зависимостью
```

2019-12-23 18:08 UTC, RandellDawson commented on curriculum/challenges/russian/06-information-security-and-quality-assurance/information-security-with-helmetjs/understand-bcrypt-hashes.russian.md
> +  - текст: BCrypt был должным образом необходим
@povar163 You should not be translating the yaml id
```suggestion
  - text: BCrypt был должным образом необходим
```

2020-03-26 20:00 UTC, RandellDawson commented
Hi @povar163 

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened or create a new PR, if you still wish to make the changes you originally added plus any additional change requests asked of you.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding!

2020-03-26 20:00 UTC, closed without merging