fix(challenge): account for browser zoom, add note to challenge
freeCodeCamp/freeCodeCamp pull request #37687
Opened 2019-11-05 07:03 UTC by lasjorg

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Second go at fixing this challenge. Forum [confirmation](https://www.freecodecamp.org/forum/t/is-there-a-glitch-in-this-challenge/325152/62) that this should work. I also added a note about the zoom.

BTW, how do we update the hint forum post?

Closes #18045

2019-11-13 15:27 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2019-11-14 01:36 UTC, lasjorg commented
Let's just the regex, it's safer I think.

2019-11-14 08:38 UTC, ojeytonwilliams requested changes
I think I'm finally caught up on the discussions around this.  I agree that, sadly, regex is the way to go.

With that in mind:

2019-11-14 08:38 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/adjust-the-height-of-an-element-using-the-height-property.english.md
> +<strong>Note:</strong> You may need to be at 100% zoom to pass the test on this challenge.
```suggestion
```
No longer needed with the current test.

2019-11-14 15:39 UTC, ojeytonwilliams approved these changes
Thanks @lasjorg, LGTM now!

2019-11-15 00:00 UTC, RandellDawson requested changes
Similar problems as #37688. I can pass the challenge with the following which do not actually affect the height.
```css
  h4 {
    text-align: center;
    Height: 25px;
  }
```
OR

```css
  h4 {
    text-align: center;
    max-height: 25px;
  }
```
OR
```css
  h4 {
    text-align: center;
    myheight: 25px;
  }
```

2019-11-16 01:51 UTC, lasjorg commented
Reverted, same argument applies as in https://github.com/freeCodeCamp/freeCodeCamp/pull/37688#issuecomment-554590238

2019-11-19 17:05 UTC, moT01 approved these changes
I'm fine with it like this, I tested it pretty thoroughly.

2019-11-26 03:40 UTC, RandellDawson approved these changes

2019-11-26 03:40 UTC, merged

2019-11-26 03:40 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉