Changes to "Iterate with JavaScript While Loops - English" challenge description
freeCodeCamp/freeCodeCamp pull request #37683
Opened 2019-11-04 23:10 UTC by Kbarias

- [X] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X ] My pull request targets the `master` branch of freeCodeCamp.
- [X ] None of my changes are plagiarized from another source without proper attribution.
- [ X] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ X] My changes do not use shortened URLs or affiliate links.

Closes #37682

2019-11-04 23:28 UTC, RandellDawson requested changes
@ceejayoz See my suggested changes.  You can click the `Commit suggestion` if you do not object to the suggestion.

2019-11-04 23:28 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/iterate-with-javascript-while-loops.english.md
> +The code <code>ourArray.push(i)</code> and <code>i++</code> will continue to execute while <code>i</code> is less than 5. Thus, this <code>while</code> loop will run 5 times appending the numbers 0 t
@Kbarias If you click on the Details link, you will see the following error message for the Linting Tests:
> Fenced code blocks should be surrounded by blank lines [Context: "```".  I also recommend a shorter version of the code explanation.

You need to make sure there is an extra line above and below code fence ``` blocks. 
```suggestion

In the code example above, the <code>while</code> loop will execute 5 times and append the numbers 0 through 4 to <code>ourArray</code>.
```

2019-11-05 14:34 UTC, Kbarias commented
Hi @RandellDawson , thank you for the suggested changes. I updated the commit to how you suggested it.

2019-11-05 14:51 UTC, RandellDawson approved these changes

2019-11-05 17:39 UTC, moT01 approved these changes
This LGTM. But I did notice that what the user needs to do for the challenge, is the exact same as the example code. Perhaps we can merge this, and create a new issue around changing either the example or the challenge.

2019-11-05 17:54 UTC, RandellDawson commented
@moT01 Open a PR with your suggested change for the challenge instructions and solution.  Sounds like a good change to implement.

2019-11-06 18:26 UTC, merged

2019-11-06 18:27 UTC, RandellDawson commented
Congrats @Kbarias on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝