fix(curriculum): added new test to Give Links Meaning by Using Descriptive Link Text challenge to specifically for href attribute
freeCodeCamp/freeCodeCamp pull request #37699
Opened 2019-11-06 05:04 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x]  My changes do not use shortened URLs or affiliate links.

The original last test for the challenge was testing more than just if the `a` element was missing a closing tag.  This PR changes the last test to only validate the a tag has a matching closing tag and adds another test which validates the `href` attribute value remains an empty string.

2019-11-11 16:50 UTC, thecodingaviator approved these changes

2019-11-15 15:55 UTC, moT01 requested changes
Couple small grammar changes, other than that - LGTM

2019-11-15 15:55 UTC, moT01 commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/give-links-meaning-by-using-descriptive-link-text.english.md
> +  - text: You <code>a</code> element should have a closing tag.
```suggestion
  - text: Your <code>a</code> element should have a closing tag.
```

2019-11-15 15:55 UTC, moT01 commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/give-links-meaning-by-using-descriptive-link-text.english.md
> +  - text: Your <code>a</code> element should have a <code>href</code> attribute with a value of an empty string <code>""</code>.
```suggestion
  - text: Your <code>a</code> element should have an <code>href</code> attribute with a value of an empty string <code>""</code>.
```

2019-11-15 16:09 UTC, moT01 approved these changes
LGTM @RandellDawson 🎉

2019-11-15 16:14 UTC, merged