fix: make help button use subforum topics
freeCodeCamp/freeCodeCamp pull request #37741
Opened 2019-11-12 04:27 UTC by moT01

Not sure if this is what you had in mind @raisedadead, but it's what I came up with. There may be issue's in the future if a block name changes, but it seems like it's either this or go and change the challengeType of a bunch of the challenges since they are kind of scattered and mixed up in places. Would that be fine to do, or would it potentially cause issues? I'll keep this as a draft for now, in case you want to go in that or another direction.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #37691

2019-11-12 10:48 UTC, raisedadead commented
I am fine with the current approach on the PR. We should add tests so that it is caught if a challenge block name changes. 

For example a simple test for all the current block names in to go with this help button util component will cross tie them both?

Anyway I do not think it would be a very nice idea to change the challenge types now that the new curriculum is headed our way. Might as well deal them then

2019-11-14 17:53 UTC, ojeytonwilliams requested changes
Looks great!

Just the one nitpick:

2019-11-14 17:53 UTC, ojeytonwilliams commented on curriculum/test/test-challenges.js
> +            throw new AssertionError(invalidBlock);
```suggestion
            throw new Error(invalidBlock);
```
I doubt error type really matters, but just in case.

2019-11-14 18:04 UTC, ojeytonwilliams commented
I've checked it locally and the tests work nicely.  If you create a block that's not in `helpCategory` it won't pass the tests.

2019-11-15 14:14 UTC, ojeytonwilliams approved these changes

2019-11-15 14:19 UTC, moT01 commented
I committed your suggestion @ojeytonwilliams, the only other thing that might be an issue...
`if (challenge.challengeType !== 7 && invalidBlock) {`
I added the check for challengeType 7, those are the certificates which have no challenge page or help button - they were throwing an error because nothing was added for them as a helpCategory. There's also types 8 (quiz) and 9 (invalid) - there must not be any of those types in the current curriculum, but if there ever is, it would probably throw that error.

2019-11-15 14:34 UTC, ojeytonwilliams commented
@moT01 I think that's fine.  The error you've created should tell anyone that triggers it why it's happening and how to fix it.  They can either create another exception or a new helpCategory.

Any idea what those challengeTypes are supposed to be used for?

2019-11-15 14:44 UTC, moT01 commented
quizzes and invalid challenges 😛

2019-11-15 17:30 UTC, raisedadead approved these changes

2019-11-15 17:33 UTC, merged