fix(curriculum): changed test text to use should for Front End Libraries
freeCodeCamp/freeCodeCamp pull request #37762
Opened 2019-11-15 20:24 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to PR #36860 

This PR makes sure all challenges' tests in the Front End Libraries" section use "should " or "should not".

2019-11-19 23:57 UTC, moT01 requested changes

2019-11-19 23:57 UTC, moT01 commented on curriculum/challenges/english/03-front-end-libraries/bootstrap/call-out-optional-actions-with-btn-info.english.md
> +  - text: All your <code>button</code> elements should have closing tags.
```suggestion
  - text: All of your <code>button</code> elements should have closing tags.
```

2019-11-19 23:57 UTC, moT01 commented on curriculum/challenges/english/03-front-end-libraries/bootstrap/create-a-bootstrap-headline.english.md
> +  - text: You should add a <code>h3</code> element to your page.
```suggestion
  - text: You should add an <code>h3</code> element to your page.
```

2019-11-19 23:57 UTC, moT01 commented on curriculum/challenges/english/03-front-end-libraries/jquery/delete-your-jquery-functions.english.md
> +  - text: YOu should leave your <code>$&#40document&#41.ready&#40function&#40&#41 {</code> to the beginning of your <code>script</code> element.
```suggestion
  - text: You should leave your <code>$&#40document&#41.ready&#40function&#40&#41 {</code> at the beginning of your <code>script</code> element.
```

2019-11-19 23:57 UTC, moT01 commented on curriculum/challenges/english/03-front-end-libraries/jquery/target-the-children-of-an-element-using-jquery.english.md
> +  - text: You should onlu use jQuery to add these classes to the element.
```suggestion
  - text: You should only use jQuery to add these classes to the element.
```

2019-11-20 00:13 UTC, RandellDawson commented
@moT01 I have committed your suggested changes.

2019-11-20 00:22 UTC, moT01 approved these changes
🎉 LGTM 🎉

2019-11-20 03:56 UTC, cmccormack approved these changes
These all look good to me; however, I would have preferred to have `you` and `your` removed from most of the comments as it seems a bit personal.

For example:
```yaml
- text: You should add an <code>i</code> element with the classes <code>fas</code> and <code>fa-thumbs-up</code>.
```
could be rewritten
```yaml
- text: An <code>i</code> element with the classes <code>fas</code> and <code>fa-thumbs-up</code> should be added.
```

Again, this looks good to me and I approve as-is, if you agree with what I stated above I could do the work to go through them again, just let me know.

2019-11-20 04:00 UTC, Manish-Giri approved these changes
LGTM 💯

2019-11-20 05:02 UTC, RandellDawson commented
@cmccormack According to the current [Writing challenge descriptions/instructions](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-work-on-coding-challenges.md#writing-challenge-descriptionsinstructions) section, the challenge text should be written using the second person "you" and most of the tests in the curriculum seem to be written this way.  I do not think it necessary, but you can create a separate issue where we can all discuss it I suppose.  In the mean time, I think this PR can be merged now.

2019-11-22 12:44 UTC, ojeytonwilliams commented
I agree that there's no need to hold this up pending a change in the style guide.

2019-11-22 12:44 UTC, merged