fix(curriculum): changed test text to use should for Coding Interview Prep - part 2 of 2
freeCodeCamp/freeCodeCamp pull request #37766
Opened 2019-11-15 21:55 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to PR #36860 

This PR makes sure all challenges' tests in the following sections of the `Coding Interview Prep` section use "should " or "should not".

* Project Euler
* Rosetta Code

2019-11-19 22:40 UTC, moT01 requested changes
Couple minor things...

2019-11-19 22:40 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/date-format.english.md
> +  - text: <code>getDateFormats</code> should returned an array with 2 elements.
```suggestion
  - text: <code>getDateFormats</code> should return an array with 2 elements.
```

2019-11-19 22:40 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/topological-sort.english.md
> +  - text: <code>topologicalSort</code> should return correct library order..
```suggestion
  - text: <code>topologicalSort</code> should return correct library order.
```

2019-11-19 22:40 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/topological-sort.english.md
> +  - text: <code>topologicalSort</code> should return correct library order..
```suggestion
  - text: <code>topologicalSort</code> should return correct library order.
```

2019-11-19 22:40 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/topological-sort.english.md
> +  - text: <code>topologicalSort</code> should return correct library order..
```suggestion
  - text: <code>topologicalSort</code> should return correct library order.
```

2019-11-19 22:40 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/topological-sort.english.md
> +  - text: <code>topologicalSort</code> should ignore unorderable dependencies..
```suggestion
  - text: <code>topologicalSort</code> should ignore unorderable dependencies.
```

2019-11-19 22:40 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/y-combinator.english.md
> +  - text: Y mushouldst return a function.
```suggestion
  - text: Y should return a function.
```

2019-11-19 23:47 UTC, RandellDawson commented
@moT01 I committed your suggested changes.  Thanks for the review.

2019-11-19 23:59 UTC, moT01 approved these changes
🎉 LGTM @RandellDawson 🎉

2019-11-20 15:01 UTC, Manish-Giri approved these changes
LGTM 💯

2019-11-20 15:01 UTC, merged