fix(curriculum): changed test text to use should for Information Security and Quality Assurance
freeCodeCamp/freeCodeCamp pull request #37763
Opened 2019-11-15 20:59 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Related to PR #36860 

This PR makes sure all challenges' tests in the `Information Security and Quality Assurance` section use "should " or "should not".

2019-11-19 23:45 UTC, moT01 requested changes

2019-11-19 23:45 UTC, moT01 commented on curriculum/challenges/english/06-information-security-and-quality-assurance/advanced-node-and-express/logging-a-user-out.english.md
> +  - text: <code>req.Logout</code> should be called in your <code>\/logout</code> route.
```suggestion
  - text: <code>req.Logout</code> should be called in your <code>/logout</code> route.
```

2019-11-19 23:45 UTC, moT01 commented on curriculum/challenges/english/06-information-security-and-quality-assurance/advanced-node-and-express/logging-a-user-out.english.md
> +  - text: Logout should redirect to the home page \/.
```suggestion
  - text: Logout should redirect to the home page.
```

2019-11-19 23:45 UTC, moT01 commented on curriculum/challenges/english/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/test-if-a-value-falls-within-a-specific-range.english.md
> +  - text: You should use approximately(actual, expected, range) - You should Chose the correct range.
```suggestion
  - text: You should use approximately(actual, expected, range) - You should choose the correct range.
```

2019-11-19 23:45 UTC, moT01 commented on curriculum/challenges/english/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/test-if-a-value-falls-within-a-specific-range.english.md
> +  - text: You should use approximately(actual, expected, range) - You should chose the correct range.
```suggestion
  - text: You should use approximately(actual, expected, range) - You should choose the correct range.
```

2019-11-20 00:11 UTC, RandellDawson commented
@moT01 I have committed your suggested changes.

2019-11-20 00:24 UTC, moT01 approved these changes
🎉 LGTM 🎉

2019-11-20 01:22 UTC, Manish-Giri commented on curriculum/challenges/english/06-information-security-and-quality-assurance/advanced-node-and-express/how-to-use-passport-strategies.english.md
> +  - text: A POST request to /login should correctly redirect to /
```suggestion
  - text: A POST request to /login should correctly redirect to /.
```

2019-11-20 01:24 UTC, Manish-Giri requested changes
Add a missing period for consistency.

2019-11-20 05:07 UTC, RandellDawson commented
@Manish-Giri I committed your suggested change.

2019-11-20 14:58 UTC, Manish-Giri approved these changes
LGTM 💯

2019-11-20 14:58 UTC, merged