fix(curriculum): English editing
freeCodeCamp/freeCodeCamp pull request #37814
Opened 2019-11-23 13:28 UTC by waldoluisribeiro

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-11-23 22:04 UTC, RandellDawson requested changes
@waldoluisribeiro See my suggestions.

2019-11-23 22:04 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function.english.md
> +The <code>class</code> syntax simply replaces the constructor function:
@waldoluisribeiro I am thinking `creation` should be left in here.

2019-11-23 22:04 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function.english.md
> +The <code>Vegetable</code> class allows you to create a vegetable object with a property <code>name</code>, which is passed to the constructor.
```suggestion
The <code>Vegetable</code> class allows you to create a vegetable object with a property <code>name</code>that gets passed to the constructor.
```

2019-11-24 01:51 UTC, RandellDawson approved these changes

2019-11-24 02:27 UTC, Manish-Giri requested changes
Minor changes.

2019-11-24 02:27 UTC, Manish-Giri commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/es6/use-class-syntax-to-define-a-constructor-function.english.md
> +ES6 provides new syntax to create objects, using the keyword <dfn>class</dfn>.
```suggestion
ES6 provides new syntax to create objects, using the <dfn>class</dfn> keyword.
```

Being consistent with other such `dfn`/`code` statements.

Also, IMO, `"a new syntax"` was fine here.

2019-11-24 16:08 UTC, RandellDawson commented
@Manish-Giri Please merge if you are satisfied with the current changes.

2019-11-24 21:38 UTC, Manish-Giri approved these changes
LGTM.

2019-11-24 21:38 UTC, merged