feat: add minimal form to modal
freeCodeCamp/freeCodeCamp pull request #37903
Opened 2019-12-09 21:11 UTC by ahmadabdolsaheb

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2019-12-09 21:20 UTC, ahmadabdolsaheb commented
The modal should be functional. 
There are some wiring that I am working on taking out.

2019-12-10 19:08 UTC, ahmadabdolsaheb commented
@ojeytonwilliams a quick review is appreciated.

2019-12-11 10:17 UTC, ojeytonwilliams requested changes
I wasn't able to test the behaviour properly without Stripe test keys, but I looked at what I could.

Comments below:

2019-12-11 10:17 UTC, ojeytonwilliams commented on client/src/components/Donation/components/StripeCardForm.js
> -  CardCVCElement
I think we'd be better of including this, to reduce the chance that a bank rejects the charge.  If the concern is that it's taking up too much space, why not put it on the same row as 'Your Card Expiration Month:'?  That's currently taking a full row for 5 characters.

Something like this:
![image](https://user-images.githubusercontent.com/15801806/70612288-f55b3c00-1c06-11ea-8565-5c3414ef7f91.png)

2019-12-11 10:17 UTC, ojeytonwilliams commented on client/src/components/Donation/components/StripeCardForm.js
> -  CardCVCElement
We can make space by using 'Expiration Date:' or 'Expiration Month:' since it's clear from 'Your Card Number' what's going on.

2019-12-11 13:50 UTC, ahmadabdolsaheb commented on client/src/components/Donation/components/DonationModal.js
> +            Help us create even more learning resources for you and your family.
I see your point. we can a/b test different copies once this goes live.

2019-12-11 14:26 UTC, ahmadabdolsaheb commented on client/src/components/Donation/components/MinimalDonateForm.js
> +  return navigate(`${apiLocation}/signin?returnTo=donate`);
yes, the button that uses that will not be displayed since the user is always signed in.
I will go ahead and take it out anyways.

2019-12-11 14:28 UTC, ahmadabdolsaheb commented on client/src/components/Donation/components/MinimalDonateForm.js
> +    if (donationDuration === 'onetime') {
I think we should keep it so it would show the label correctly if we change the payment defaults.

2019-12-12 14:48 UTC, raisedadead approved these changes

2019-12-12 14:48 UTC, merged