Added clearer instructions to the "Create Many Records with model.create()" challenge
freeCodeCamp/freeCodeCamp pull request #38026
Opened 2020-01-08 15:44 UTC by Anonyma

The previous instructions were causing confusion:
https://www.freecodecamp.org/forum/t/mongodb-and-mongoose-create-many-records-with-model-create/208546
https://github.com/freeCodeCamp/freeCodeCamp/issues/36447

- [ x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] None of my changes are plagiarized from another source without proper attribution.
- [x ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ x] My changes do not use shortened URLs or affiliate links.

Closes #36447

2020-03-27 10:01 UTC, ojeytonwilliams submitted a review, later dismissed
Sorry for the extremely late review, this should have been looked at sooner.  Comments below:

2020-03-27 10:01 UTC, ojeytonwilliams commented on curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model.create.english.md
> +Add a function expecting an <code>arrayOfPeople</code> argument which creates many people through <code>Model.create()</code>.
```suggestion
Modify the <code>createManyPeople</code> function to create many people through <code>Model.create()</code> and the argument <code>arrayOfPeople</code>.
```
The function already exists. If a user creates a function with a different name, they would need to modify code in sections we've told them not to touch.

2020-08-30 03:20 UTC, moT01 reviewed
I'm kind of leaning towards not adding these changes. If you open the [repl.it link](https://repl.it/repls/NanoHumbleBrackets#myApp.js) or [the boilerplate](https://github.com/freeCodeCamp/boilerplate-mongomongoose/blob/gomix/myApp.js#L87) it's fairly clear what to do. The function is there to be modified - and users in this area can figure that out I think. I guess the bigger reason I am leaning that way is because I would say we should modify the instructions in those two spots as well if we add this - which isn't worth it in my opinion.

2020-08-31 16:46 UTC, Sky020 commented
@moT01 I have **not** seen this confusion come up on the forum. So, I do not think there is a need to change the instructions. However, adding this would do no harm.

Personally, because the challenge occurs in the `myApp.js` file, I prefer the _extended_ instructions being in the `myApp.js` file. So, if any instructions are to change, I would have them be the ones in the boilerplate.

2020-09-02 15:37 UTC, moT01 submitted a review, later dismissed
Sounds good to me @Sky020 - I say we add these changes to both places then. What do you think? I'll make a PR to the boilerplate.

If so, this LGTM 🎉

2020-09-02 16:07 UTC, nhcarrigan submitted a review, later dismissed
If we are on-board with adding the clarification, this PR fits that need and LGTM!

2020-09-02 16:20 UTC, Sky020 commented
@RandellDawson If you are happy with these changes, could you merge this? Personally, I am still on the edge with making changes to this lesson file, and would close #36447 with Tom's PR of the boilerplate.

2020-09-02 18:53 UTC, RandellDawson requested changes
Sorry, but I think the wording could be improved.

2020-09-02 18:53 UTC, RandellDawson commented on curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model.create.english.md
> +Modify the <code>createManyPeople</code> function to create many people through <code>Model.create()</code> and the argument <code>arrayOfPeople</code>.
```suggestion
Modify the <code>createManyPeople</code> function to create many people using <code>Model.create()</code> with the argument <code>arrayOfPeople</code>.
```

2020-09-02 18:53 UTC, RandellDawson commented on curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/create-many-records-with-model.create.english.md
> +(You can reuse the model you instantiated in the previous exercise)
```suggestion
<strong>Note: </strong> You can reuse the model you instantiated in the previous exercise.
```

2020-09-02 22:42 UTC, RandellDawson approved these changes

2020-09-02 23:00 UTC, Sky020 approved these changes
Thank you, for your contribution, @Anonyma ! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

2020-09-02 23:01 UTC, merged