Removed typo from Instructions
freeCodeCamp/freeCodeCamp pull request #38066
Opened 2020-01-14 15:44 UTC by nickBlack4

Removed the word 'with' which doesn't belong.

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution.
- [ ] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [ ] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2020-01-14 15:46 UTC, thecodingaviator approved these changes

2020-01-14 15:55 UTC, thecodingaviator requested changes

2020-01-14 15:55 UTC, thecodingaviator commented on curriculum/challenges/english/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-on-api-endpoints-using-chai-http.english.md
>  Replace <code>assert.fail()</code>. Test the status and the text.response. Make the test pass.
```suggestion
Replace <code>assert.fail()</code>. Test the status and the <code>text.response</code>. Make the test pass.
```

2020-01-14 16:08 UTC, nickBlack4 reviewed
looks good to me!

2020-01-14 16:21 UTC, RandellDawson commented on curriculum/challenges/english/06-information-security-and-quality-assurance/quality-assurance-and-testing-with-chai/run-functional-tests-on-api-endpoints-using-chai-http.english.md
> +Don't send a name in the query, the endpoint responds with <code>'hello Guest'</code>.
Do we really need the code tags surrounding the string?
```suggestion
Don't send a name in the query, the endpoint responds with "hello Guest".
```

2020-01-14 17:32 UTC, RandellDawson approved these changes
LGTM  @thecodingaviator What do you think about the recent changes?

2020-01-15 02:48 UTC, thecodingaviator approved these changes
LGTM!

2020-01-15 02:49 UTC, merged

2020-01-15 02:49 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝