fix(curriculum): Added test to Return a Sorted Array Without Changing the Original Array challenge to validate new array is returned
freeCodeCamp/freeCodeCamp pull request #38105
Opened 2020-01-23 17:36 UTC by RandellDawson

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

This PR adds a new test to the [Return a Sorted Array Without Changing the Original Array](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array) challenge.  The test validates the array returned by the `nonMutatingSort` function actually is a different array than the `globalArray` variable.

Before adding the new test, the following code passes, which defeats the whole point of the challenge.
```javascript
var globalArray = [5, 6, 3, 2, 9];
function nonMutatingSort(arr) {
  // Add your code below this line  
  return arr.sort((a, b) => a - b);
  // Add your code above this line
}
```

2020-01-25 08:54 UTC, thecodingaviator reviewed
I'm pretty sure I'm missing something over here but isn't your solution failing the challenge test which checks that the `globalArray` variable does not change?
![image](https://user-images.githubusercontent.com/34807532/73118750-70da3800-3f7e-11ea-8bb2-8076f99faf67.png)

2020-01-25 14:45 UTC, RandellDawson commented
@thecodingaviator When I run the tests on the production site (using Chrome), I get the following:
![image](https://user-images.githubusercontent.com/5313213/73122842-30f36080-3f3e-11ea-87ea-d0e530e1544f.png)

2020-01-29 01:21 UTC, Manish-Giri commented
The original test doesn't pass for me, on using `arr.sort()` directly -

![Screenshot 2020-01-28 20 19 57](https://user-images.githubusercontent.com/11348778/73319875-a8a9df80-420b-11ea-9229-56b8f7dd1fc1.png)

Tested on chrome and safari.

2020-01-29 02:32 UTC, RandellDawson commented
Take out the call to the function and you will see that it passes all the tests.

2020-01-29 10:02 UTC, ojeytonwilliams requested changes

2020-02-14 17:00 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array.english.md
> +    testString: assert(nonMutatingSort(globalArray) !== globalArray);
@ojeytonwilliams If we are no longer comparing to `globalArray`, then what should the `text` say?

2020-02-17 11:40 UTC, ojeytonwilliams requested changes
@RandellDawson no need to change the test, but I think the text could better reflect what the test is really checking.

2020-02-17 11:40 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/return-a-sorted-array-without-changing-the-original-array.english.md
> +  - text: The function should return a new array, and not mutate the <code>globalArray</code> variable.
```suggestion
  - text: The function should return a new array, not the array passed to it.
```
This test doesn't check if the array's mutated (other tests cover that, anyway).

2020-02-18 16:19 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2020-02-24 14:06 UTC, moT01 approved these changes
LGTM @RandellDawson 🎉  

Are we okay to merge this ahead of https://github.com/freeCodeCamp/freeCodeCamp/pull/37912 @ojeytonwilliams? Or should we wait?

2020-02-24 14:30 UTC, ojeytonwilliams commented
@moT01 that PR's easy enough to update, so no need to wait.  I'll merge now.

2020-02-24 14:30 UTC, merged

2020-02-24 14:52 UTC, moT01 commented
Why is it showing that this failed the testing in the commit history.