fix: adding test to check if flat or flatMap method was used in the steamroller challenge
freeCodeCamp/freeCodeCamp pull request #38158
Opened 2020-02-04 09:09 UTC by hassaanp

The Steamroller Challenge in the Intermediate Algorithms section of the Javascript Algorithms and Data Structures course allowed using the methods `flat` and `flatMap`. This defeats the purpose of the challenge.

I have added a test that ensures that said methods are not allowed.
I have only added the test for the English language.

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #38133

Tested and verified locally using the Docker build of the platform.

2020-02-04 13:43 UTC, moT01 reviewed
For the most part, this looks like it works and would probably be good enough. But you can still pass using the method when you add a line break...
<img width="969" alt="Screen Shot 2020-02-04 at 7 41 34 AM" src="https://user-images.githubusercontent.com/20648924/73749884-d1f1d080-4721-11ea-987b-362615307e1a.png">

2020-02-04 17:21 UTC, RandellDawson requested changes
@hassaanp I have made some suggestions.  Also, the instructions need to be changed to reflect that the `flat` and `flatMap` methods are not to be used.

2020-02-04 17:21 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller.english.md
> +    testString: assert(!code.match(/\.flat\(.*?\)/)) || assert(!code.match(/\.flatMap\(.*?\)/));
Allow for spaces and there only needs to be a single assert:
```suggestion
    testString: assert(!code.match(/\.flat\([\s\S]*\)/) && !code.match(/\.flatMap\([\s\S]*\)/));
```

2020-02-04 17:21 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller.english.md
> +  - text: You should not use the <code>.flat()</code> or <code>.flatMap()</code> methods.
I suggest a small change in the test's `text`.
```suggestion
  - text: Your solution should not use the <code>Array.prototype.flat()</code> or <code>Array.prototype.flatMap()</code> methods.
```

2020-02-04 19:05 UTC, hassaanp commented
Hey @RandellDawson,

Thank you for the suggestions. I have updated the pull request with the changes.

Also, tested it locally before pushing.

2020-02-04 20:57 UTC, RandellDawson commented
@hassaanp FYI - You can click the Commit changes button and create commits without having to push back up to the repo.

2020-02-04 20:57 UTC, RandellDawson approved these changes

2020-02-04 22:00 UTC, Manish-Giri approved these changes
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍 We're happy to accept these changes and look forward to future contributions. 📝

2020-02-04 22:00 UTC, merged

2020-02-05 00:15 UTC, RandellDawson commented
I have removed the solution that used **.flat()** from the [Challenge Guide forum topic](https://www.freecodecamp.org/forum/t/freecodecamp-challenge-guide-steamroller/16079).

2020-02-05 05:38 UTC, hassaanp commented
Thank you @RandellDawson for guiding me through.