fixed - #38047 (modified add-images-to-your-website.english.md)
freeCodeCamp/freeCodeCamp pull request #38155
Opened 2020-02-03 17:37 UTC by philipobiorah

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [ ] None of my changes are plagiarized from another source without proper attribution. - Modifications form RandellDawson  comments on #38047 
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x ] My changes do not use shortened URLs or affiliate links.

Closes #38047

2020-02-03 17:43 UTC, RandellDawson requested changes
@philipobiorah See my suggested change.

2020-02-03 17:43 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.english.md
> +Finally, don't forget to give your <code>img</code>element an <code>alt</code>  attribute with applicable text.
You are missing a space between the `</code>` and the word `element`
```suggestion
Finally, don't forget to give your <code>img</code> element an <code>alt</code>  attribute with applicable text.
```

2020-02-03 17:46 UTC, RandellDawson approved these changes
I think this PR looks good.

2020-02-03 17:50 UTC, philipobiorah commented
Thanks

2020-02-03 22:50 UTC, Manish-Giri requested changes
There's an extra period at the end of the sentence.

2020-02-03 22:50 UTC, Manish-Giri commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.english.md
> +Within the existing <code>main</code> element, insert an <code>img</code> element before the existing <code>p</code> elements..
```suggestion
Within the existing <code>main</code> element, insert an <code>img</code> element before the existing <code>p</code> elements.
```

2020-02-04 14:42 UTC, raisedadead commented
Hi @philipobiorah 

Thanks for your PR, and congrats on your first contribution to the codebase 🎉 !

I recommend you use a more meaningful and succinct title for the PR next time, for example like the one I updated this PR to.

Thanks and happy contributing!

2020-02-04 14:42 UTC, raisedadead approved these changes

2020-02-04 14:42 UTC, merged