fix: added white space checks including newlines to ensure proper validation of trim method
freeCodeCamp/freeCodeCamp pull request #38166
Opened 2020-02-05 06:25 UTC by hassaanp

Fixed the trim method validation by adding checks for newlines for the regex challenge [remove whitespaces from start and end](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end).

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #38165

2020-02-05 11:13 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2020-02-05 16:44 UTC, Manish-Giri requested changes

2020-02-05 16:44 UTC, Manish-Giri commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/remove-whitespace-from-start-and-end.english.md
> +  - text: Your solution should not use the <code>String.prototype.trim()</code> method.
Might be a better idea to use the full form, `String.prototype.prim()`, earlier in the `Note` -  

> The .trim() method would work here, but you'll need to complete this challenge using regular expressions.

and then just use `.trim()` (_or you could go for the full form too_) in the test case - 

> Your solution should not use the String.prototype.trim() method.

Also, while we're at it, wasn't the general convention to use a space after **Note** followed by the text, unless the note spanned multiple lines...

2020-02-06 07:30 UTC, hassaanp commented
@Manish-Giri addressed your comments in the commit - kindly review please.

2020-02-06 15:28 UTC, RandellDawson approved these changes
LGTM @Manish-Giri Merge when if you are OK with the changes.

2020-02-09 06:19 UTC, hassaanp commented
@Manish-Giri ping

2020-02-12 06:47 UTC, merged