fixed sample package.json dependencies for challenge 587d7fb4367417b2b2512c00
freeCodeCamp/freeCodeCamp pull request #38212
Opened 2020-02-14 00:56 UTC by JoelLau

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2020-02-14 00:58 UTC, JoelLau commented
## More Information

_Pull Request also fixes the examples found in other languages_

| Current | Fixed |
| ------- | ----- |
|  ![image](https://user-images.githubusercontent.com/29514264/74491874-f317a580-4f07-11ea-9c2c-a69262b5edf8.png) | ![image](https://user-images.githubusercontent.com/29514264/74491920-12aece00-4f08-11ea-818d-7f3a20de0089.png) |

2020-02-14 01:11 UTC, RandellDawson commented
@JoelLau Why did you close your PR?

2020-03-05 15:30 UTC, thecodingaviator requested changes
Please take the changes made to this file off the PR i.e. revert it to its original state. Afaik, the formatting on the real challenge will remain unaffected by these changes and so they're moot.

2020-03-05 15:30 UTC, thecodingaviator commented on curriculum/challenges/english/05-apis-and-microservices/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm.english.md
&nbsp;

2020-03-05 19:39 UTC, thecodingaviator reviewed
Thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding. ✈️

2020-03-05 19:39 UTC, closed without merging