Update solution for use-breadth-first-search-in-a-binary-search-tree.english.md
freeCodeCamp/freeCodeCamp pull request #38221
Opened 2020-02-16 07:16 UTC by sagarkharbe

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] None of my changes are plagiarized from another source without proper attribution.
- [x] All the files I changed are in the same world language (for example: only English changes, or only Chinese changes, etc.)
- [x] My changes do not use shortened URLs or affiliate links.

Closes #XXXXX

2020-04-22 16:53 UTC, moT01 requested changes
Probably don't need that in there? Other than that, looks good to me.

2020-04-22 16:53 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/use-breadth-first-search-in-a-binary-search-tree.english.md
> +var displayTree = tree => console.log(JSON.stringify(tree, null, 2));
```suggestion
```

2020-04-22 16:55 UTC, moT01 commented
I already added this to the guide.

2020-04-27 12:27 UTC, moT01 approved these changes
LGTM @sagarkharbe 🎉 

For future reference, it's good to give your branch a more descriptive name and start it with a scope. See `#3` just below [here in the docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#making-changes-locally)

2020-04-27 18:07 UTC, Sky020 commented
I am fine with the code, as it passes. However, I am clarifying that it is OK that it does not match the seed code?

2020-04-27 19:44 UTC, moT01 commented
I didn't look close enough. I thought log was for debugging when @sagarkharbe was making his solution or something. It's really probably fine, but we might as well add it back in I think. Sorry about that @sagarkharbe, if you don't mind adding that back.

Nice catch @Sky020.

2020-04-27 19:53 UTC, moT01 commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/use-breadth-first-search-in-a-binary-search-tree.english.md
> +function Node(value) {
```suggestion
var displayTree = tree => console.log(JSON.stringify(tree, null, 2));
function Node(value) {
```

2020-04-28 21:30 UTC, moT01 approved these changes
LGTM :tada:

2020-04-28 22:11 UTC, ShaunSHamilton approved these changes
LGTM 👍

2020-04-28 22:35 UTC, moT01 commented
Congratulations on your first contribution to freeCodeCamp @sagarkharbe 🎉

We look forward to future contributions 🎉

2020-04-28 22:36 UTC, merged