add: solution to project euler problem 20
freeCodeCamp/freeCodeCamp pull request #38257
Opened 2020-02-25 05:30 UTC by kogoking

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Adding solution for Project Euler problem 20 md file.

2020-02-25 07:48 UTC, ojeytonwilliams requested changes
Small nitpick, but this looks good otherwise.

2020-02-25 07:48 UTC, ojeytonwilliams commented on curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-20-factorial-digit-sum.english.md
> +sumFactorialDigits(100);
```suggestion
```
This isn't required and makes the solution a little slower.

2020-02-25 08:21 UTC, kogoking commented
> Small nitpick, but this looks good otherwise.

Thanks for pointing it out. Do I only need to commit now? Contributing for the first time.

2020-02-25 08:46 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2020-02-25 08:47 UTC, ojeytonwilliams commented
>  Do I only need to commit now? 

Adding an extra commit that removes the line is perfect, thanks!

2020-02-26 07:58 UTC, Manish-Giri commented on curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-20-factorial-digit-sum.english.md
> +function sumFactorialDigits(n)
```suggestion
function sumFactorialDigits(n) {
```

2020-02-26 07:58 UTC, Manish-Giri commented on curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-20-factorial-digit-sum.english.md
> +{
```suggestion

```

2020-02-26 07:59 UTC, Manish-Giri requested changes
More nitpicking (sorry!), but a minor style change...

2020-02-26 19:22 UTC, Manish-Giri approved these changes
LGTM. Congratulations on your first pull request 💯

2020-02-26 19:22 UTC, merged