add: solution to project euler problem 22 md file
freeCodeCamp/freeCodeCamp pull request #38263
Opened 2020-02-25 17:25 UTC by kogoking

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Adding solution to Project Euler problem 22 md file

2020-02-26 12:27 UTC, kogoking commented
> 
> 
> @kogoking Please review our checklist and mark appropriately. Also, did you test your solution locally and run `npm run test` to validate your added solution passes all the tests?

What exactly did I mark incorrectly? My solution passes test only if the two arrays from Challenge Seed (test1 & test2) are kept as it is before running test, mentioned it in the comments at end. Let me know whats wrong, just started contributing.

2020-02-26 13:54 UTC, RandellDawson commented
> What exactly did I mark incorrectly?

You did not check the boxes letting us know you have read the contributing guidelines and various other things.

>My solution passes test only if the two arrays from Challenge Seed (test1 & test2) are kept as it is before running test, mentioned it in the comments at end. Let me know whats wrong, just started contributing.

If you read the contributing guidelines, you will know that solutions must contain all original seed code with any changes needed to pass the challenge tests.  Make sure to add those declarations back into your solution.

2020-03-10 18:02 UTC, kogoking reviewed
Are these changes alright?

2020-03-11 09:39 UTC, ojeytonwilliams requested changes
Looks good, just one minor issue:

2020-03-11 09:39 UTC, ojeytonwilliams commented on curriculum/challenges/english/08-coding-interview-prep/project-euler/problem-22-names-scores.english.md
> +  arr = arr.sort();
```suggestion
  arr = [...arr].sort();
```
Since the next line modifies the array passed to `nameScores`, it's best to defensively copy it.

2020-03-11 13:30 UTC, ojeytonwilliams approved these changes

2020-03-13 21:31 UTC, RandellDawson approved these changes

2020-03-13 21:31 UTC, merged

2020-03-13 21:31 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

2020-03-13 21:38 UTC, RandellDawson commented
@kogoking I added your solution to the forum hints/solutions topic for this challenge.