fix (curriculum): made the order of the required code to be redundant
freeCodeCamp/freeCodeCamp pull request #38320
Opened 2020-03-05 07:39 UTC by hassaanp

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38311

Added checks for all possible positions for the required code.

2020-03-05 15:25 UTC, thecodingaviator requested changes
Is there no better way we can check this? Directly checking CSS or something like that?

2020-03-05 17:57 UTC, RandellDawson commented
@thecodingaviator Yes, I agree.  I started working on incorporating a CSS parser that will avoid us having to write these complicated regex asserts.  The idea is to have a set of global helper function available for us to use in the Tests.  Once such helper lets us check specific CSS values with the parser.

2020-03-05 19:49 UTC, thecodingaviator commented
@RandellDawson I have no idea what an ETA on that might be, so do you think we should go ahead with this PR or wait for yours?

2020-03-05 20:41 UTC, RandellDawson requested changes
@hassaanp @thecodingaviator If we want a more concise regular expression, then you can use my suggestions.  We could use something like this across all such CSS challenges, but the CSS parser I hope to have implemented soon will let us do these checks without regular expression. 

@hassaanp Please hold off on any other changes like this one until I get the CSS parser implemented.

Thanks

2020-03-05 20:41 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/create-movement-using-css-animation.english.md
> +    testString: assert(code.match(/50%\s*?{\s*?background-color:\s*?green;\s*?top:\s*?50px;\s*?left:\s*?25px;\s*?}/gi) || code.match(/50%\s*?{\s*?left:\s*?25px;\s*?background-color:\s*?green;\s*?top:
I have tested the below regex that is much simpler.  Please click the `Commit suggestion` if you agree.
```suggestion
    testString: assert(code.match(/50%\s*?{[\s\S]*?left:\s*?25px(;[\s\S]*?|\s*?)}/gi));
```

2020-03-05 20:41 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/create-movement-using-css-animation.english.md
> +    testString: assert(code.match(/0%\s*?{\s*?background-color:\s*?blue;\s*?top:\s*?0(px)?;\s*?left:\s*?0(px)?;\s*?}/gi) || code.match(/0%\s*?{\s*?background-color:\s*?blue;\s*?left:\s*?0(px)?;\s*?to
I have tested the below regex that is much simpler.  The extra `[^50]` added before the `0%` was to make sure the `50` and the `100` were not caught in the match.  Please click the `Commit suggestion` if you agree.
```suggestion
    testString: assert(code.match(/[^50]0%\s*?{[\s\S]*?left:\s*?0px(;[\s\S]*?|\s*?)}/gi));
```

2020-03-05 20:41 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/create-movement-using-css-animation.english.md
> +    testString: assert(code.match(/100%\s*?{\s*?background-color:\s*?yellow;\s*?top:\s*?0(px)?;\s*?left:\s*?-25px;\s*?}/gi) || code.match(/100%\s*?{\s*?left:\s*?-25px;\s*?background-color:\s*?yellow;
I have tested the below regex that is much simpler. Please click the Commit suggestion if you agree.
```suggestion
    testString: assert(code.match(/100%\s*?{[\s\S]*?left:\s*?-25px(;[\s\S]*?|\s*?)}/gi));
```

2020-03-06 06:09 UTC, thecodingaviator commented
@RandellDawson I like your suggestions and if we're looking for a quick fix to this challenge, this should work, however, since it is unlikely these changes would be deployed soon and because the RWD section is under code freeze, I think it best to hold off this PR for now.

cc: @freeCodeCamp/moderators

2020-03-06 06:13 UTC, RandellDawson commented
@thecodingaviator The OP can still commit these suggestions.  We just need to wait until the code freeze is over before merging.  Technically, since only the `testString`s are changed, we could probably go ahead an merge this (with @raisedadead's permission), because the changes will not need a translation.

2020-03-06 06:14 UTC, raisedadead approved these changes

2020-03-06 06:15 UTC, raisedadead commented
Once all QA is done, let me know or assign me to this I will land this.

2020-03-06 06:18 UTC, RandellDawson commented
@hassaanp Please see the suggestions above.

2020-03-06 06:42 UTC, hassaanp commented
> @hassaanp Please see the suggestions above.

Thanks for the suggestions. I have applied them.

2020-03-06 06:43 UTC, hassaanp commented
@raisedadead please go ahead and merge

2020-03-06 07:08 UTC, thecodingaviator approved these changes

2020-03-06 07:14 UTC, merged