Adding a solution for searching within a linked list future students
freeCodeCamp/freeCodeCamp pull request #38326
Opened 2020-03-07 00:02 UTC by kmwarter

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-03-07 01:06 UTC, RandellDawson requested changes
@kmwarter Although your solution does pass the tests as they are currently written.  I realized after testing your code, that the current tests to not reflect the requirements of the actual challenge.   The instructions indicate adding a working `isEmpty` method, so you will need need to add a working `isEmpty` method to the solution before we can merge this PR.  Also, you need to remove the ``// solution required` comment from the solution also.

In the mean time, I will create a separate commit on this PR to add/update the tests accordingly, so we would have a valid solution and applicable working tests.

2020-03-09 13:20 UTC, RandellDawson commented
@kmwarter I have made the necessary changes to the tests.  You just need to need to make the changes I mentioned in my first comment above.

2020-03-20 06:00 UTC, kmwarter commented
Good catch. I added the isEmpty method too. Thanks!

2020-03-20 14:28 UTC, RandellDawson approved these changes
@moT01 @ojeytonwilliams Since I added a commit with test changes and new tests to this PR, can you both review this one before it gets merged?  Thanks.

2020-03-20 17:12 UTC, moT01 approved these changes
LGTM 🎉

2020-03-21 02:33 UTC, Manish-Giri requested changes

2020-03-21 02:33 UTC, Manish-Giri commented on curriculum/challenges/english/08-coding-interview-prep/data-structures/search-within-a-linked-list.english.md
> +  - text: Your <code>elementAt</code> method should return <code>undefined</code> if the given index is not found at a given index in linked list.
```suggestion
  - text: Your <code>elementAt</code> method should return <code>undefined</code> if the given element is not found at a given index in linked list.
```

2020-03-21 04:15 UTC, RandellDawson commented
@Manish-Giri Thanks for catching that typo.  Looks like this one is good to be approved by you now?

2020-03-21 04:16 UTC, Manish-Giri approved these changes

2020-03-21 04:16 UTC, Manish-Giri commented
@RandellDawson Yes, looks good.

2020-03-21 14:30 UTC, moT01 approved these changes
Congratulations on your first contribution to freeCodeCamp @kmwarter! 🎉 We look forward to future contributions. 

For future reference, it's nice if you can make your branch name a little more descriptive. Thanks and happy coding!

2020-03-21 14:30 UTC, merged