fix: use example in modifying an object within a nested object exerci…
freeCodeCamp/freeCodeCamp pull request #38468
Opened 2020-03-29 21:04 UTC by AshNaz87

…se to explain how to do so

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38467

2020-03-29 21:05 UTC, AshNaz87 commented
<img width="721" alt="Screenshot 2020-03-29 at 21 59 29" src="https://user-images.githubusercontent.com/20570746/77860844-584dfe80-7209-11ea-9eb5-3ba0f9070b20.png">

2020-03-29 21:45 UTC, RandellDawson submitted a review, later dismissed
See my suggestions for making the wording a bit more concise.

2020-03-29 21:45 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/modify-an-object-nested-within-an-object.english.md
> +<code>nestedObject</code> has three unique keys: <code>id</code>, whose value is a number, <code>date</code> whose value is a string, and <code>data</code>, whose value is an object which has yet ano
```suggestion
<code>nestedObject</code> has three properties: <code>id</code> (value is a number), <code>date</code>(value is a string), and <code>data</code> (value is an object with its nested structure). While structures can quickly become complex, we can still use the same notations to access the information we need. To assign the value <code>10</code> to the <code>busy</code> property of the nested <code>onlineStatus</code> object, we use dot notation to reference the property:
```

2020-03-29 21:45 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/modify-an-object-nested-within-an-object.english.md
> +Here we've defined an object, <code>userActivity</code>, which includes another object nested within it. Set the value of the <code>online</code> key to <code>45</code>.
```suggestion
Here we've defined an object <code>userActivity</code> that includes another object nested within it. Set the value of the <code>online</code> key to <code>45</code>.
```

2020-04-03 10:58 UTC, AshNaz87 commented
@RandellDawson Is this good to go?

2020-05-13 12:26 UTC, moT01 approved these changes
LGTM @AshNaz87 🎉

2020-05-13 12:49 UTC, ShaunSHamilton requested changes
Just some nitpicking.

2020-05-13 12:49 UTC, Sky020 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/modify-an-object-nested-within-an-object.english.md
> +<code>nestedObject</code> has three properties: <code>id</code> (value is a number), <code>date</code>(value is a string), and <code>data</code> (value is an object with its nested structure). While
```suggestion
<code>nestedObject</code> has three properties: <code>id</code> (value is a number), <code>date</code> (value is a string), and <code>data</code> (value is an object with its nested structure). While structures can quickly become complex, we can still use the same notations to access the information we need. To assign the value <code>10</code> to the <code>busy</code> property of the nested <code>onlineStatus</code> object, we use dot notation to reference the property:
```

2020-05-13 12:49 UTC, Sky020 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/modify-an-object-nested-within-an-object.english.md
> +Here we've defined an object <code>userActivity</code> that includes another object nested within it. Set the value of the <code>online</code> key to <code>45</code>.
```suggestion
Here we've defined an object <code>userActivity</code>, which includes another object nested within it. Set the value of the <code>online</code> key to <code>45</code>.
```

2020-05-13 12:59 UTC, ShaunSHamilton approved these changes
LGTM 👍

2020-05-13 12:59 UTC, moT01 commented
Lets try again...

2020-05-15 21:41 UTC, moT01 approved these changes
LGTM @AshNaz87 🎉 Thanks for contributing to freeCodeCamp 🎉

2020-05-15 21:41 UTC, merged