Remove double slashes in Strip control codes challenge
freeCodeCamp/freeCodeCamp pull request #38466
Opened 2020-03-29 16:28 UTC by agatapst

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38436

2020-03-29 17:49 UTC, RandellDawson requested changes
@agatapst Since most of the `testString`s have been modified, can you please go ahead and remove the unnecessary assert message arguments?  You can click `Commit suggestion` for each and a commit will be made.

2020-03-29 17:49 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md
>      testString: assert(typeof strip == 'function', '<code>strip</code> should be a function.');
```suggestion
    testString: assert(typeof strip == 'function');
```

2020-03-29 17:49 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md
> +    testString: assert(typeof strip("abc") == 'string', '<code>strip("abc")</code> should return a string.');
```suggestion
    testString: assert(typeof strip("abc") == 'string');
```

2020-03-29 17:49 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md
> +    testString: assert.equal(strip("\ba\x00b\n\rc\fd\xc3"), "abcd", '<code>strip("\ba\x00b\n\rc\fd\xc3")</code> should return <code>"abcd"</code>.');
```suggestion
    testString: assert.equal(strip("\ba\x00b\n\rc\fd\xc3"), "abcd");
```

2020-03-29 17:49 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md
> +    testString: assert.equal(strip("\u0000\n abc\u00E9def\u007F"), " abcdef", '<code>strip("\u0000\n abc\u00E9def\u007F")</code> should return <code>" abcdef"</code>.');
```suggestion
    testString: assert.equal(strip("\u0000\n abc\u00E9def\u007F"), " abcdef");
```

2020-03-29 17:49 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md
> +    testString: assert.equal(strip("a\n\tb\u2102d\u2147f"), "abdf", '<code>strip("a\n\tb\u2102d\u2147f")</code> should return <code>"abdf"</code>.');
```suggestion
    testString: assert.equal(strip("a\n\tb\u2102d\u2147f"), "abdf");
```

2020-03-29 17:49 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md
>      testString: assert.equal(strip("Français."), "Franais.", '<code>strip("Français.")</code> should return <code>"Franais."</code>.');
```suggestion
    testString: assert.equal(strip("Français."), "Franais.");
```

2020-03-29 17:49 UTC, RandellDawson commented on curriculum/challenges/english/08-coding-interview-prep/rosetta-code/strip-control-codes-and-extended-characters-from-a-string.english.md
> +    testString: assert.equal(strip("123\tabc\u0007DEF\u007F+-*/€æŧðłþ"), "123abcDEF+-*/", '<code>strip("123\tabc\u0007DEF\u007F+-*/€æŧðłþ")</code> should return <code>"123abcDEF+-*/"</code>.');
```suggestion
    testString: assert.equal(strip("123\tabc\u0007DEF\u007F+-*/€æŧðłþ"), "123abcDEF+-*/");
```

2020-03-29 21:03 UTC, agatapst commented
@RandellDawson Yes, thank you! 😊

2020-03-30 08:26 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2020-03-30 14:03 UTC, RandellDawson approved these changes

2020-03-30 15:23 UTC, merged

2020-03-30 15:23 UTC, ojeytonwilliams commented
@agatapst Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝