fix(Curriculum): make sure the nested input element in the form is th…
freeCodeCamp/freeCodeCamp pull request #38480
Opened 2020-03-31 21:41 UTC by AshNaz87

…e existing element given in the editor

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38478

2020-04-01 00:35 UTC, RandellDawson requested changes
@AshNaz87 See the changes I have suggested.

2020-04-01 00:35 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md
> +Nest the existing input element inside a <code>form</code> element, and add the <code>action="/submit-cat-photo"</code> attribute to the form element.
```suggestion
Nest the existing input element inside a <code>form</code> element and add assign <code>"/submit-cat-photo"</code> to the <code>action</code> attribute of the <code>form</code> element.
```

2020-04-01 00:35 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md
> +  - text: The existing input element should be nested within a <code>form</code> element.
```suggestion
  - text: The existing <code>input</code> element should be nested within a <code>form</code> element.
```

2020-04-01 00:35 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md
> +    testString: assert.isTrue(document.querySelector('form input').getAttribute('type') === 'text' && document.querySelector('form input').getAttribute('placeholder') === 'cat photo URL');
Just call `document.querySelector` once:
```suggestion
    testString: const inputElem = document.querySelector('form input'); assert(inputElem.getAttribute('type') === 'text' && inputElem.getAttribute('placeholder') === 'cat photo URL');
```

2020-04-01 00:39 UTC, RandellDawson commented
Once we get this approved, we will need the Chinese team to make the applicable changes to the Chinese file to match the English changes to the `text` that has been changed.  I have added a `status: blocked` label in the mean time, so we know not to merge it until the Chinese team has added a commit.

2020-04-01 06:18 UTC, AshNaz87 commented
Thanks @RandellDawson

2020-04-01 06:54 UTC, ojeytonwilliams submitted a review, later dismissed
LGTM :+1:

2020-04-02 15:55 UTC, hassaanp submitted a review, later dismissed

2020-04-02 21:51 UTC, RandellDawson commented
@freeCodeCamp/chinese Since we now have 2 approvals of the English version, we need one member on the Chinese team to a commit and another member approve the commit, so we can merge this PR.

The `Instructions` section and the one `text` in the `Tests` section needs translating.

Thank you.

2020-04-02 23:06 UTC, Manish-Giri requested changes
![Untitled](https://user-images.githubusercontent.com/11348778/78307802-c7329c80-7514-11ea-92be-9f1a0538387d.png)

This doesn't make much sense -

> and add assign "/submit-cat-photo" to the action attribute of the form element

I'm guessing the idea was to replace "add" with "assign", perhaps. Either way, pick one.

2020-04-03 00:41 UTC, RandellDawson submitted a review, later dismissed
@AshNaz87 I have added a suggestion based on @Manish-Giri's observation.

2020-04-03 00:41 UTC, RandellDawson commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/create-a-form-element.english.md
> +Nest the existing input element inside a <code>form</code> element and add assign <code>"/submit-cat-photo"</code> to the <code>action</code> attribute of the <code>form</code> element.
```suggestion
Nest the existing input element inside a <code>form</code> element and assign <code>"/submit-cat-photo"</code> to the <code>action</code> attribute of the <code>form</code> element.
```

2020-04-03 08:13 UTC, Manish-Giri submitted a review, later dismissed

2020-04-03 13:50 UTC, RandellDawson commented
@freeCodeCamp/chinese Still waiting on the necessary translations of this challenge.

2020-04-03 14:01 UTC, raisedadead commented
> Still waiting on the necessary translations of this challenge.

IMHO we should create an issue and move ahead to respect everyones volunteer contributions and time?

2020-04-03 14:55 UTC, miyaliu666 commented
> @freeCodeCamp/chinese Still waiting on the necessary translations of this challenge.

I've talked with @ZhichengChen 10 hours ago. It looks like we should commit to his repo first since it hasn't been merged to master. He'll figure out how to handle it. I agree with Mrugesh we can create issues when there're more tasks like this. Thanks!

2020-04-03 15:28 UTC, RandellDawson commented
@raisedadead I thought we agreed to keep the English and Chinese in sync.  Am I missing something.

> It looks like we should commit to his repo first since it hasn't been merged to master. He'll figure out how to handle it. 

I thought all the Responsive Web Design Chinese translation PRs have already been merged.

2020-04-03 15:34 UTC, raisedadead commented
> I thought we agreed to keep the English and Chinese in sync. Am I missing something.

Yes we did. And after having talks with the community members (like Miya mentioned) we concluded that we would be lagging behind in the translations. This is simply because our contributors are volunteers and its a logistical issue to get in the translations right away.

We should hence track changes that need i18n as issues to avoid undue delays in the english version.

2020-04-03 15:42 UTC, RandellDawson commented
@raisedadead I sent you message on Gitter.

2020-04-18 10:40 UTC, amirabbaska reviewed
Nice

2020-07-27 19:04 UTC, RandellDawson commented
I resolved the merge conflict, but then the PR was failing for linting issue involving the use of a bare url being used in the markdown.  I replace `<code></code>` with single backticks and the linting passed.  I created a separate commit for the change to backticks.

2020-08-11 17:44 UTC, RandellDawson approved these changes
I am fine with these changes.

2020-08-11 17:45 UTC, RandellDawson commented
@moT01 @ojeytonwilliams @nhcarrigan @Sky020 Can one of you review the PR and either approve or request changes?

Thank you.

2020-08-11 18:00 UTC, naomi-lgbt reviewed
![image](https://user-images.githubusercontent.com/63889819/89931799-8ed95400-dbc1-11ea-8abd-73ebcc9ac01b.png)

This passes the tests (both before the changes in this PR and after) - is this something we want to take into consideration and account for, while we are making changes to this challenge?

2020-08-11 18:16 UTC, ShaunSHamilton approved these changes
LGTM 👍 . Whilst I agree with @nhcarrigan that catching a case like that would be better, it is another issue, we might tackle later. The tests can also be passed by deleting the `main` element, among others.

So, we either create another test checking for changes in the seed. Or, we change the current test to ensure nothing but the `input` is within the `form`?

2020-08-11 19:32 UTC, S1ngS1ng approved these changes

2020-08-11 19:36 UTC, S1ngS1ng commented
@RandellDawson Please lemme know if we need to apply the same changes to [this file](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/chinese/01-responsive-web-design/basic-html-and-html5/create-a-form-element.chinese.md). If so, I should be able to create a PR for it by EOD today.
Or instead, should we wait on merging this PR first?

2020-08-11 19:39 UTC, RandellDawson commented
> This passes the tests (both before the changes in this PR and after) - is this something we want to take into consideration and account for, while we are making changes to this challenge?

As far as the HTML5 specification goes, you could technically leave off the closing `main` tag and it will render just fine in all modern browsers.  There are elements that **must** have closing tags (i.e h1-h6), there are elements that never have a closing tag (i.e. self-closing tags like `input` and `br`, and per the HTML5 specification most other elements (with some very specific edge cases) the closing tag is optional.   Having a matching closing tag on an element where it is optional is more about making the code more readable that a syntax requirement.  See below using @Sky020's example.  The out-of-place closing `main` tag is literally ignored (does not display in the browser) and when the DOM is constructed, a closing `main` tag is put into the proper location.

![image](https://user-images.githubusercontent.com/5313213/89940692-c7335f00-dbce-11ea-89ec-19303a3dd978.png)

You could easily the closing `main` tag is optional by removing it from the HTML code:

![image](https://user-images.githubusercontent.com/5313213/89940916-21ccbb00-dbcf-11ea-999e-6413eff825c5.png)

We currently have many challenges where we validate the closing tags are present even when technically leaving them off would be perfectly valid HTML.  An HTML validator might possibly flag HTML with closing tags in the wrong order or missing, but we only check in those challenges to avoid trying to explain the cases where it does not matter.  Plus, as I said before, adding closing tags makes the code more readable just as indenting code does.

I said all the above to see, we do not have to worry about writing a test for an out of place closing `main` tag for this challenge.

2020-08-11 20:06 UTC, RandellDawson commented
@S1ngS1ng Yes, let's wait until this PR is merged, then you can make the changes to the Chinese version to keep everything in sync.

Thanks.

2020-08-31 05:50 UTC, merged

2020-08-31 05:50 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉