fix(Curriculum): ensure code that includes and is not equal to the fl…
freeCodeCamp/freeCodeCamp pull request #38497
Opened 2020-04-03 19:45 UTC by AshNaz87

…at or flatMap methods do not fail the test suite

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38491

2020-04-08 11:54 UTC, hassaanp approved these changes

2020-04-12 03:32 UTC, moT01 requested changes
```
function steamrollArray(arr) {
  return arr.flat(Infinity);
}
```
This would still pass, or it would pass if you use spaces.

2020-04-12 03:32 UTC, moT01 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller.english.md
> +    testString: assert(!code.match(/\w+?\s*\.flat\(\)/) && !code.match(/\w+?\s*\.flatMap\(\)/));
```suggestion
    testString: assert(!code.match(/\.\s*flat\s*\(/) && !code.match(/\.\s*flat\s*\(/));
```

2020-04-16 09:41 UTC, snigo requested changes

2020-04-16 09:41 UTC, snigo commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/steamroller.english.md
> +    testString: assert(!code.match(/\w+?\s*\.flat\(\)/) && !code.match(/\w+?\s*\.flatMap\(\)/));
```suggestion
    testString: assert(!/\.\s*flat(?:Map)?\W|\[\s*(["'`])flat(?:Map)?\1\s*\]/.test(code));
```

Will catch `.flat`, `['flat']` as well as `.flatMap` and `['flatMap']` using any combination of literal strings

2020-04-22 19:43 UTC, lasjorg commented
@moT01 @AshNaz87 Any update on this? We are still getting a few forum threads every now and then about it.

Latest example
https://www.freecodecamp.org/forum/t/steamroller-test-for-not-using-flat-or-flatmap-fails-yet-my-solution-does-not-use-either/377351

2020-04-22 20:46 UTC, AshNaz87 commented
@moT01 What are your thoughts?

2020-04-23 19:58 UTC, moT01 approved these changes
LGTM @AshNaz87 🎉 Thanks for contributing to freeCodeCamp 🎉 

@snigo has a point about being able to use bracket notation. But I doubt many will actually do that - and if they do, they're only cheating themselves. I think it's more important to just get this added so people aren't failing the challenge with code that should pass. If someone wants to make another PR with @snigo's suggestions, I would be fine with that.

2020-04-23 19:59 UTC, merged