Fix/functional programming challange
freeCodeCamp/freeCodeCamp pull request #38516
Opened 2020-04-09 09:11 UTC by kundan59

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38513

Added missing "return" word to make the challenge more clear.

2020-04-09 10:06 UTC, ojeytonwilliams requested changes

2020-04-09 10:06 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/pass-arguments-to-avoid-external-dependence-in-a-function.english.md
> +Write the <code>incrementer</code> function so it takes an argument, and then return a result after increases the value by one.
```suggestion
Write the <code>incrementer</code> function so it takes an argument, and then returns a result after increasing the value by one.
```
Minor grammar nitpicks.

2020-04-09 10:21 UTC, kundan59 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/pass-arguments-to-avoid-external-dependence-in-a-function.english.md
> +Write the <code>incrementer</code> function so it takes an argument, and then return a result after increases the value by one.
@ojeytonwilliams update Pr after eliminating grammatical mistakes. Please have a look thanks.

2020-04-09 10:57 UTC, kundan59 commented
@ojeytonwilliams update Pr after eliminating grammatical mistakes. Please have a look thanks.

2020-04-09 12:18 UTC, ojeytonwilliams approved these changes
LGTM 👍

2020-04-12 02:20 UTC, moT01 approved these changes
LGTM @kundan59 🎉 Thank you for contributing to freeCodeCamp 🎉

2020-04-12 02:20 UTC, merged