update description of "Nest an anchor element in a paragraph" as discussed in #38507
freeCodeCamp/freeCodeCamp pull request #38524
Opened 2020-04-10 09:41 UTC by Ieahleen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38507 

As discussed in #38507 , I'm removing the phrase in parenthesis. It seems the more agreed upon way, and the less disrupting for translations.

2020-04-10 09:46 UTC, thecodingaviator requested changes

2020-04-10 09:46 UTC, thecodingaviator commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.english.md
> +Now nest the existing <code>a</code> element within a new <code>p</code> element. The new paragraph should have text that says "View more cat photos", where "cat photos" is a link, and the rest of th
```suggestion
Nest the existing <code>a</code> element within a new <code>p</code> element. The new paragraph should have text that says "View more cat photos", where "cat photos" is a link, and the rest is plain text.
```
Edited for brevity.

2020-04-12 01:50 UTC, moT01 commented
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

2020-05-08 23:09 UTC, ShaunSHamilton approved these changes
LGTM 👍

2020-07-12 01:34 UTC, erictleung approved these changes

2020-07-13 13:14 UTC, thecodingaviator approved these changes

2020-08-27 19:19 UTC, thecodingaviator approved these changes

2020-08-27 19:20 UTC, thecodingaviator commented
Whoops my bad. Double reviewed it. Didn't see it was a blocked one and that I had already been here.

2020-08-31 03:01 UTC, moT01 approved these changes
Thanks for fixing this up @Ieahleen 🎉

2020-08-31 03:01 UTC, merged