feat: enable GitHub integration
freeCodeCamp/freeCodeCamp pull request #38612
Opened 2020-04-22 21:06 UTC by raisedadead

2020-04-22 21:17 UTC, raisedadead commented
Definitely do not want the comments.

2020-04-23 10:17 UTC, ojeytonwilliams requested changes

2020-04-23 10:17 UTC, ojeytonwilliams commented on .github/workflows/cypress.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          record: true
          build: npm run build
```
The order meant some `with` entries were being interpreted as `env` entries.

Also, I saw this when setting up the CYPRESS_RECORD_KEY: 
> Secrets are not passed to workflows that are triggered by a pull request from a fork.

presumably that means PR runs won't get recorded.

2020-04-23 10:19 UTC, ojeytonwilliams commented
I did not get any comments when I did this on my fork: https://github.com/ojeytonwilliams/freeCodeCamp/pull/7

Could there be a dashboard setting that's enabling them?

2020-04-23 10:41 UTC, raisedadead commented
This PR is more of a spike to gauge: if we even want to use https://cypress.io for storing recordings, it will be useful to check when something breaks. Currently CI have logs only.

I will add you to the dashboard today.

I have used this in past (on my website), its good.

2020-04-29 11:21 UTC, raisedadead commented
Closing in favor of https://github.com/freeCodeCamp/freeCodeCamp/pull/38678 for convention

2020-04-29 11:21 UTC, closed without merging