Data Cleaning/Viz- Subplot Method Arguments
freeCodeCamp/freeCodeCamp pull request #38655
Opened 2020-04-27 00:46 UTC by rayjohnson529

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-05-05 16:19 UTC, erictleung approved these changes
See suggestions

2020-05-05 16:19 UTC, erictleung commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/data-cleaning-and-visualizations.english.md
> +  text: 'When using MatPlotLib's global API, the following code does what in what order?:
Matplotlib is just capitalized, the apostrophe here in `Matplolib's` needs to be escaped, and the original wording of the question felt awkward. Here's a suggested change

```suggestion
  text: 'When using Matplotlib''s global API, what does the order of numbers mean here?:
```

2020-05-05 16:19 UTC, erictleung commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/data-cleaning-and-visualizations.english.md
> +    - 'My figure will have one column, two rows, and I am goin to start drawing in the first (left) plot.'
Typo

```suggestion
    - 'My figure will have one column, two rows, and I am going to start drawing in the first (left) plot.'
```

2020-05-05 16:19 UTC, erictleung requested changes
See comments

2020-05-06 21:15 UTC, beaucarnes approved these changes

2020-05-14 01:04 UTC, merged