fix(learn): fixed typo "in the left" should be "at the left"
freeCodeCamp/freeCodeCamp pull request #38651
Opened 2020-04-26 20:28 UTC by farjadfazli

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-04-26 20:50 UTC, ShaunSHamilton requested changes
This is what makes sense to me.

2020-04-26 20:50 UTC, Sky020 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator.english.md
> +The most basic operator is the equality operator <code>==</code>. The equality operator compares two values and returns <code>true</code> if they're equivalent or <code>false</code> if they are not.
```suggestion
The most basic operator is the equality operator <code>==</code>. The equality operator compares two values and returns <code>true</code> if they're equivalent or <code>false</code> if they are not. Note that equality is different from assignment (<code>=</code>), which assigns the value on the right of the operator to a variable on the left.
```

2020-04-26 20:58 UTC, farjadfazli commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/comparison-with-the-equality-operator.english.md
> +The most basic operator is the equality operator <code>==</code>. The equality operator compares two values and returns <code>true</code> if they're equivalent or <code>false</code> if they are not.
Yes that works too!

2020-04-29 15:27 UTC, ShaunSHamilton approved these changes
LGTM 👍

2020-05-02 13:17 UTC, moT01 approved these changes
LGTM @farjadfazli 🎉 Congratulations on your first contribution to freeCodeCamp 🎉 

For future reference, it's good to give your branch a more descriptive name and start it with a scope. See `#3` just below [here in the docs](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/docs/how-to-setup-freecodecamp-locally.md#making-changes-locally)

2020-05-02 13:17 UTC, merged

2020-05-02 15:03 UTC, farjadfazli commented
Thank you! I will keep the branch naming in mind for next time 👍