feat: enable github integration
freeCodeCamp/freeCodeCamp pull request #38678
Opened 2020-04-29 11:18 UTC by raisedadead

2020-04-29 15:57 UTC, ojeytonwilliams requested changes

2020-04-29 15:57 UTC, ojeytonwilliams commented on .github/workflows/cypress.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          record: true
          build: npm run build
```
The original order has various 'with' properties being interpreted as being part of  'env'

2020-04-30 07:22 UTC, ojeytonwilliams approved these changes
Looks good!  One thing I'm not 100% on is which branches will be watched?  If it triggers on every push and every PR I imagine we'll use up the quota.  That is unless fCC qualifies as [a non-commercial entity](https://www.cypress.io/oss-plan/).

Regardless, we might as well try this and see.

2020-04-30 09:20 UTC, raisedadead commented
Great news!

Our OSS Application just came through:

![image](https://user-images.githubusercontent.com/1884376/80694266-e4e22a00-8af1-11ea-973a-26ea2886b6d2.png)

2020-04-30 09:32 UTC, raisedadead commented
I checked everything we have unlimited runs, and even then I am restricting this to pushes to `master`, `production-**` and all pull requests.

2020-04-30 09:33 UTC, merged