NumPy Algebra and Size: Size and Efficiency Question
freeCodeCamp/freeCodeCamp pull request #38725
Opened 2020-05-03 22:25 UTC by rayjohnson529

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-05-07 02:40 UTC, erictleung requested changes
Small formatting suggestion

2020-05-07 02:40 UTC, erictleung commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/numpy-algebra-and-size.english.md
> +    - NumPy objects take up much less memory than Standard Python objects; operations on Standard Python objects complete very quickly compared to comparable objects on Numpy Object.
Being consistent with other mentions

```suggestion
    - NumPy objects take up much less memory than Standard Python objects; operations on Standard Python objects complete very quickly compared to comparable objects on NumPy Object.
```

2020-05-08 22:14 UTC, rayjohnson529 commented
Makes sense, thanks for catching that!

2020-05-08 22:16 UTC, erictleung approved these changes

2020-05-12 09:35 UTC, merged