Add previously written methods to challenge seed in "Remove an Element from a Max Heap"
freeCodeCamp/freeCodeCamp pull request #38834
Opened 2020-05-16 14:27 UTC by tywmick

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

[Remove an Element from a Max Heap](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/remove-an-element-from-a-max-heap) currently tells students to add the `insert` method they just wrote in the [previous lesson](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/insert-an-element-into-a-max-heap) to their code in this lesson as well, but unless the student made an effort to save their previous code, they can't go back and copy it, in which case they have to rewrite it from scratch.

This change copies the methods over from the previous lesson's solution to this lesson's challenge seed so students don't have to needlessly duplicate effort.

I also made a couple quick changes to the previous lesson's solution to bring it in line with its instructions (making the starting heap `[null]` instead of `[undefined]` and only returning *inserted* elements in the `print` method).

2020-05-25 15:04 UTC, moT01 commented
I have blocked this for now. See the [pinned code freeze issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/38308)

2020-05-27 19:36 UTC, raisedadead commented
Limitations removed on Coding Interview Prep Challenges.

2020-06-05 02:12 UTC, tinktink1 submitted a review, later dismissed
I have reviewed your changes and they look good to me. I think your instructions update are good! Your code is also formatted well.

2020-07-08 21:48 UTC, moT01 reviewed
Curious why we don't just start the array empty?

2020-07-08 21:48 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/insert-an-element-into-a-max-heap.english.md
> +		return this.heap.slice(1);
```suggestion
		return this.heap;
```

2020-07-08 21:48 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/insert-an-element-into-a-max-heap.english.md
> +	this.heap = [null];
```suggestion
	this.heap = [];
```

2020-07-08 21:48 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/insert-an-element-into-a-max-heap.english.md
> +		while (ele > arr[Math.floor(index / 2)] && index > 1) {
```suggestion
		while (ele > arr[Math.floor(index / 2)]) {
```

2020-07-08 21:48 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/remove-an-element-from-a-max-heap.english.md
> +  this.heap = [null];
```suggestion
  this.heap = [];
```

2020-07-08 21:48 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/remove-an-element-from-a-max-heap.english.md
> +    while (ele > arr[Math.floor(index / 2)] && index > 1) {
```suggestion
    while (ele > arr[Math.floor(index / 2)]) {
```

2020-07-08 21:48 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/remove-an-element-from-a-max-heap.english.md
> +    return this.heap.slice(1);
```suggestion
    return this.heap;
```

2020-07-13 21:02 UTC, tywmick commented
@moT01 Oh, that's just based on a tip from the description of [Insert an Element into a Max Heap](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/insert-an-element-into-a-max-heap) to make the math easier:

> For instance, consider this array representation of a binary min heap:
>
> <code>[ 6, 22, 30, 37, 63, 48, 42, 76 ]</code>
>
> The root node is the first element, 6. Its children are 22 and 30. If we look at the relationship between the array indices of these values, for index i the children are 2 * i + 1 and 2 * i + 2. Similarly, the element at index 0 is the parent of these two children at indices 1 and 2. More generally, we can find the parent of a node at any index with the following: Math.floor( (i - 1) / 2 ). These patterns will hold true as the binary tree grows to any size. Finally, we can make a slight adjustment to make this arithmetic even easier by skipping the first element in the array. Doing this creates the following relationship for any element at a given index i:
>
> Example Array representation:
>
> <code>[ null, 6, 22, 30, 37, 63, 48, 42, 76 ]</code>
>
> An element's left child: i * 2
>
> An element's right child: i * 2 + 1
>
> An element's parent: Math.floor( i / 2 )

We can take out the `null` at index 0—we'll just also have to change the math to find child and parent elements. But either way's cool with me. 👍🏼

2020-09-02 23:37 UTC, moT01 approved these changes, later dismissed
LGTM @tywmick 🎉

2020-09-03 12:23 UTC, ShaunSHamilton requested changes
We should remove the line requesting the camper to add their `insert` method, if we do this.

2020-09-03 12:58 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/remove-an-element-from-a-max-heap.english.md
>    // change code above this line
```suggestion
  // change code below this line
  
  // change code above this line
```

2020-09-03 14:28 UTC, moT01 commented
I added your suggestions @Sky020 & @RandellDawson

2020-09-03 14:52 UTC, Sky020 approved these changes
LGTM 👍

2020-09-03 15:40 UTC, moT01 approved these changes
Thanks for contributing to freeCodeCamp @tywmick 🎉

2020-09-03 15:40 UTC, merged

2020-09-03 17:50 UTC, tywmick commented
> We should remove the line requesting the camper to add their `insert` method, if we do this.

Whoops, thanks for catching that one!