fix(learn): clarify description for finders keepers
freeCodeCamp/freeCodeCamp pull request #38846
Opened 2020-05-19 00:00 UTC by Moonsolol

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `master` branch of freeCodeCamp.
- [x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38832 

Used @ojeytonwilliams wording for the fix

2020-05-19 09:44 UTC, ShaunSHamilton requested changes
Just some formatting changes.

2020-05-19 09:44 UTC, Sky020 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting/finders-keepers.english.md
> +Create a function that looks through an array, arr, and returns the first element in the array that passes a 'truth test'. That is to say, given an element x, the 'truth test' is passed if func(x) is
```suggestion
Create a function that looks through an array, <code>arr</code>, and returns the first element in the array that passes a 'truth test'. That is to say, given an element <code>x</code>, the 'truth test' is passed if <code>func(x)</code> is <code>true</code>. If no element passes the test, return <code>undefined</code>.
```

2020-06-05 11:07 UTC, kushagra010 commented
Hi,
I am a beginner and want to contribute. Can I work on this @Sky020 .

2020-06-05 11:30 UTC, Sky020 commented
@kushagra010 , This is a pull-request that is likely to close the issue. So, if you opened a different pull-request, this one would be prioritised.

You are welcome to work on issues with the labels _help wanted_ or _first-timers welcome_, provided there is not already an **open** PR linked to close them.

2020-06-13 09:59 UTC, thecodingaviator reviewed
Hi,

As there has been no response from your end for a while, we are closing this PR.

Feel free to request this PR to be reopened, if you still wish to make the changes you originally added.  Also, remember to update your fork, so you have the latest version of master in case it has changed significantly.

Happy Coding! ✈️

2020-06-13 09:59 UTC, closed without merging

2020-06-13 11:24 UTC, kushagra010 commented
Hi @thecodingaviator , can I work on this issue

2020-06-13 12:38 UTC, thecodingaviator commented
@kushagra010 please go ahead

2020-06-13 12:50 UTC, Sky020 commented
@thecodingaviator , the issue is labelled with _first-timers only_. So, I suggest we either remove that, seeing as the issue has been up a while. Or, we will have to prioritise _first-timers_...

2020-06-13 12:55 UTC, thecodingaviator commented
@Sky020 my bad. Last I checked, a couple of hours ago, @kushagra010 had no commits. It seems like they have had a PR merged since then. @kushagra010 if you haven't started work on the PR already, we'd like to leave the issue open for the first-timers. If you have, no worries.

2020-06-13 13:19 UTC, kushagra010 commented
@thecodingaviator I have already created a PR .