fix(curriculum): python for everybody
freeCodeCamp/freeCodeCamp pull request #38953
Opened 2020-05-29 12:40 UTC by Sky020

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38925

2020-05-29 12:53 UTC, ojeytonwilliams commented
Hey @Sky020 what do you think about using markdown instead?  I'd rather we use it as much as possible, so when people look at the curriculum for inspiration they see how it can be done.

I appreciate that switching is a chore, so I'd be happy to make the changes myself.

2020-05-29 13:08 UTC, Sky020 commented
@ojeytonwilliams , sure. Shall i refactor the questions as well?

2020-05-29 13:20 UTC, ojeytonwilliams commented
@Sky020 wherever possible, please.  It should make things easier to read.  However, if there are things that are hard to express in Markdown, don't worry about them.

2020-05-29 15:42 UTC, Sky020 commented
There is conflict with these and #38949, #38951. This should be prioritised.

2020-05-29 17:58 UTC, ojeytonwilliams requested changes
Nice work @Sky020.  I found a few problems when I went through this, but I think they were all pre-existing issues.  Might as well fix them here, since they're all pretty minor.

2020-05-29 17:58 UTC, ojeytonwilliams commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/comparing-and-sorting-tuples.english.md
> +        print( sorted( [ (k,v) for k,v in counts.items() ] ) )
```suggestion
        print( sorted( [ (v,k) for k,v in counts.items() ] ) )
```
The code in the question flips the tuple, so the answer has to as well. Also, it should look better in a ```py block, see https://github.com/freeCodeCamp/freeCodeCamp/issues/38942

2020-05-29 17:58 UTC, ojeytonwilliams commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/comparing-and-sorting-tuples.english.md
> +        print( sorted( [ (k,v) for k,v in counts.keys() ] ) )
```suggestion
        print( sorted( [ (v,k) for k,v in counts.keys() ] ) )
```
Just so it's not completely obvious which the right answer is!

2020-05-29 17:58 UTC, ojeytonwilliams commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/regular-expressions.english.md
> +        \.
```suggestion
        \\.
```
For some reason \\. escapes the dot (not sure why), but that means you need an extra slash.

2020-05-29 17:58 UTC, ojeytonwilliams commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/networking-write-a-web-browser.english.md
>      ```
It's slightly out of scope of this PR, but the indentation is wrong above.  Could you line everything (lines 33 through 34) up with `data`?

It should be

```py
while True:
    data = mysock.recv(512)
    if len(data) < 1:
        break
    print(data.decode(),end='')
mysock.close()
```

2020-05-29 18:28 UTC, Sky020 commented
@ojeytonwilliams , Thank you, for catching those. I have committed those changes.

2020-05-31 09:53 UTC, ojeytonwilliams approved these changes
LGTM 👍

2020-05-31 12:57 UTC, moT01 approved these changes
LGTM @Sky020 🎉 Thanks for contributing to freeCodeCamp 🎉

2020-05-31 12:57 UTC, merged