fix: more conditional structures python
freeCodeCamp/freeCodeCamp pull request #38981
Opened 2020-06-01 06:39 UTC by niteshseram

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38926

Made some changes to the question as well answer.

2020-06-01 12:01 UTC, ShaunSHamilton requested changes
Just in keeping with the rest of the MD format.

2020-06-01 12:01 UTC, Sky020 commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/more-conditional-structures.english.md
> +      None
```suggestion
        None
```

2020-06-01 13:50 UTC, ShaunSHamilton submitted a review, later dismissed
LGTM 👍

2020-06-03 05:59 UTC, scissorsneedfoodtoo requested changes

2020-06-03 06:57 UTC, niteshseram commented
@scissorsneedfoodtoo I have made the changes. Have a look if it is fine.

2020-06-03 06:58 UTC, niteshseram commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/more-conditional-structures.english.md
> +    Which line/lines should be surrounded by a try and catch block?
@scissorsneedfoodtoo I have made the changes. Have a look if it is fine.

2020-06-03 11:36 UTC, Sky020 commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/more-conditional-structures.english.md
> +    Which line/lines should be surrounded by a try and catch block?
@scissorsneedfoodtoo , thank you, for catching that. I have spent too much time with JS.

2020-06-04 15:14 UTC, moT01 reviewed
I see that there is an [open PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/39005) to add line numbers to this challenge, do we want to add those here?

Edit: Also, it seems like the code doesn't execute if there's no `except` block...
<img width="492" alt="Screen Shot 2020-06-04 at 10 24 14 AM" src="https://user-images.githubusercontent.com/20648924/83776334-ab9b5d80-a64d-11ea-9bc5-f75f3645a7df.png">
With except block, all the code executes... (output is on the right)
<img width="518" alt="Screen Shot 2020-06-04 at 10 24 37 AM" src="https://user-images.githubusercontent.com/20648924/83776382-b81fb600-a64d-11ea-99d6-c2f0cb6eb659.png">
Not sure if we want to adjust this further or not. You could maybe put an `except` block in there to start.
```
temp = "5 degrees"
cel = 0
fahr = float(temp)
cel = (fahr - 32.0) * 5.0 / 9.0
except:
  print('error converting to celsius')
print(cel)
```

I think you could also possibly argue that the solution could be answer 2 (line 3), 3 (lines 3 and 4), or 4 (line 4). The try block could go anywhere you want really. Perhaps there should be more clarification in the question. `Which line(s) should be in a 'try' block to check if 'temp' got converted to a float and 'cel' was properly calculated?` Although, that seems to make the answer too obvious.

How about `Which lines(s) should be in a 'try' block to ensure all the code is executed?` And the example looks like my above example.

2020-06-04 15:47 UTC, niteshseram commented
> How about `Which lines(s) should be in a 'try' block to ensure all the code is executed?` And the example looks like my above example.

@moT01 I think this looks good to me. And about line numbers, even I was thinking to add. Should I go for it here itself?

2020-06-04 15:52 UTC, moT01 commented
I don't mind you going for it, I think it will be accepted - but someone may come in with a minor tweak or alternate suggestion.

2020-06-05 05:31 UTC, scissorsneedfoodtoo commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/more-conditional-structures.english.md
> +    Which line/lines should be surrounded by a try and catch block?
@niteshseram, great, thanks for making those changes. And no problem @Sky020, I barely noticed it myself for the same reason!

2020-06-05 05:34 UTC, scissorsneedfoodtoo approved these changes

2020-06-05 05:34 UTC, scissorsneedfoodtoo commented
The changes @moT01 suggested sound great, and should cover all issues where another answer is possible, or the question is seen as invalid because it wouldn't run without adding `except`.

2020-06-06 09:50 UTC, merged