Add: // Only change code.......comments
freeCodeCamp/freeCodeCamp pull request #39004
Opened 2020-06-04 13:13 UTC by kushagra010

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38906

2020-06-04 13:24 UTC, kushagra010 commented
Hi,
I am a beginner and wanted to contribute to this issue, I made the required changes. Please review it @ojeytonwilliams.
Thankyou.

2020-06-04 14:06 UTC, ojeytonwilliams requested changes
HI @kushagra010 thanks for the PR.

While we did consider adding comments to the code, we decided on a different solution. We can allow the user to modify `bob` if we add to the `<section id='challengeSeed'>` by including 

````md
### After Test
<div id='js-teardown'>

```js
if (bob) {
  bob = new Person("Bob Ross");
}
```
</div>
````

could you test that out and, if it works as desired, update the PR?

2020-06-04 14:48 UTC, kushagra010 commented
After the rquired changes , the test was not successful, can you help me out @ojeytonwilliams.

2020-06-04 14:57 UTC, ojeytonwilliams commented
I'd take a look at the contributing guidelines - there's a [section](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=challenge-template) on the structure of the challenges that should help you out.

2020-06-07 14:52 UTC, ojeytonwilliams requested changes

2020-06-07 14:52 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person.english.md
> +</div>
```suggestion

</div>
```
To fix the lint error.

2020-06-07 14:52 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person.english.md
> +  };
```suggestion
  };
```

2020-06-07 14:52 UTC, ojeytonwilliams commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/make-a-person.english.md
> +  // Only change code above this line
```suggestion
```
As discussed in the issue, there's no need to heavily restrict what the user changes.  As long as they keep

```js
var Person = function(firstAndLast) {
```

unchanged they can alter whatever they want.

2020-06-12 08:27 UTC, kushagra010 commented
Thankyou @ojeytonwilliams , for your guidance.
I have made the required changes, please review it.

2020-06-12 09:03 UTC, ojeytonwilliams submitted a review, later dismissed
LGTM :+1: 

Nice work @kushagra010!

2020-06-12 09:24 UTC, kushagra010 commented
Thankyou,
So what about merging now. Since this would be my first merging, so I am bit excited about it.

2020-06-12 09:33 UTC, ojeytonwilliams commented
Typically we merge after two reviews, in case the first reviewer misses something.  I've let the moderators know that this is ready for a final review. They are volunteers with other demands on their time, though, so I can't tell you exactly when that will happen.

2020-06-12 12:18 UTC, Manish-Giri requested changes
@kushagra010  The check for the `bob` object should be placed in the "After Test" section, so that it can be run once the user's code has been submitted -
```
### After Test

<div id='js-teardown'>

```js
if(bob){
  bob = new Person("Bob Ross");
}

</div>
```

Note - Do add the closing set of backticks after the `if` block, I couldn't put it here because it wouldn't format the code section correctly otherwise.

2020-06-12 13:29 UTC, kushagra010 commented
I have done the suggested changes. Please review it @Manish-Giri

2020-06-13 05:30 UTC, Manish-Giri approved these changes
LGTM 💯 

@ojeytonwilliams If you could take a final look and merge if everything sounds good.

2020-06-13 09:47 UTC, merged

2020-06-13 09:47 UTC, ojeytonwilliams commented
@kushagra010  Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

2020-06-13 11:20 UTC, kushagra010 commented
Thank you @ojeytonwilliams for your guidance.