Python for everybody line numbers
freeCodeCamp/freeCodeCamp pull request #39005
Opened 2020-06-04 14:14 UTC by borntofrappe

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Following @scissorsneedfoodtoo advice, the pull request add lines numbers to the code block of those challenges which directly ask for a line number

2020-06-04 15:12 UTC, ShaunSHamilton requested changes
Small alignment fix

2020-06-04 15:12 UTC, Sky020 commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/iterations-loop-idioms.english.md
> +    6         break
```suggestion
    5        smallest = itervar
    6        break
```

2020-06-04 15:12 UTC, Sky020 commented on curriculum/challenges/english/07-scientific-computing-with-python/python-for-everybody/iterations-loop-idioms.english.md
> +    6         break
```suggestion
    5        smallest = itervar
    6        break
```

2020-06-04 16:28 UTC, borntofrappe commented
I might have been too quick to update the changes. I understand the alignment issue, but the number of indents is what matters most in python.

```python
4     if smallest is None or itervar < smallest:
5         smallest = itervar
```

One space to separate the number column, and then 4 or 8 depending on the level of indentation.

What do you think @Sky020?

2020-06-04 17:12 UTC, Sky020 commented
@borntofrappe , You are right. I did not ensure there were **4** spaces (two tabs) between blocks. Thank you, for spotting that.

Hold off on fixing anything just now; let us see what is coming of #38981 . Just to prevent any unnecessary merge conflicts.

2020-07-16 13:05 UTC, ahmadabdolsaheb commented
Thanks for bringing this issue to our attention. I believe line numbers have been implemented globally for code blocks, so we could close this PR for now? 

![image](https://user-images.githubusercontent.com/4591597/87673966-00b6ad00-c77e-11ea-8fe1-985827ba75e0.png)

2020-07-16 14:28 UTC, ojeytonwilliams commented
Thanks for the PR @borntofrappe, but, as Ahmad pointed out, line numbers are now being provided globally by the Prismjs plugin.

2020-07-16 14:28 UTC, closed without merging