Converted Video Questions to Markdown (in 08-data-analysis-with-python) (#38991)
freeCodeCamp/freeCodeCamp pull request #39022
Opened 2020-06-07 10:15 UTC by JapneetSingh5

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-06-07 13:32 UTC, ShaunSHamilton requested changes

2020-06-07 13:32 UTC, Sky020 commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/parsing-html-and-saving-data.english.md
> +  ```method we can we use for parsing HTML documents and extracting tables?
```suggestion
  text: |
     What Python library has the `.read_html()` method we can we use for parsing HTML documents and extracting tables?
```

2020-06-07 13:32 UTC, Sky020 commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/python-iteration-and-modules.english.md
> +       ```
```suggestion
      ```
```

2020-06-07 13:32 UTC, Sky020 commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/reading-data-from-databases.english.md
> +    - The ```python Cursor ```instance has an```python .execute()``` method which will receive SQL parameters to run against the database.
```suggestion
    - |
      The `Cursor` instance has a `.run()` method which allows you to run SQL queries.
    - |
      The `Cursor` instance has a `.select()` method which allows you to select records.
    - |
      The `Cursor` instance has an `.execute()` method which will receive SQL parameters to run against the database.
```

2020-06-07 13:32 UTC, Sky020 commented on curriculum/challenges/english/08-data-analysis-with-python/numpy/basics-of-numpy.english.md
> +    'What will the following code print?:
```suggestion
    What will the following code print?:
```

2020-06-07 13:32 UTC, Sky020 commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/reading-data-csv-and-txt.english.md
>    solution: 2
```suggestion
    - |
       ```python
       import pandas as pd
       df = pd.csv("data.csv")
       ```
    - |
       ```python
       import pandas as pd<br>
       df = pd.read_csv("data.csv")
       ```
    - |
       ```python
       import pandas as pd
       pd.read_csv("data.csv")
       ```
    - |
       ```python
       import pandas as pd<br>
       df = pd.csv_reader("data.csv")
       ```
  solution: 2
```

2020-06-07 13:32 UTC, Sky020 commented on curriculum/challenges/english/08-data-analysis-with-python/numpy/basics-of-numpy.english.md
> +       [3. 5.]`
```suggestion
    - |
       ```python
       [[1.0 2.0 3.0]
       [3.0 4.0 5.0]]
       ```
    - |
       ```python
       [[1. 2. 3.]
       [3. 4. 5.]]
       ```
    - |
       ```python
       [[1. 3.]
       [2. 4.]
       [3. 5.]
       ```
```

2020-06-07 13:44 UTC, JapneetSingh5 commented
Thankyou for the suggestions, @Sky020 , goes a long way in improving my abilities and my love for open source!

2020-06-07 14:12 UTC, JapneetSingh5 commented
opened a new pull request, https://github.com/freeCodeCamp/freeCodeCamp/pull/39023

2020-06-07 14:27 UTC, Sky020 commented
@JapneetSingh5 , you can keep everything in the same PR. It makes keeping track of changes much easier, as well as build fails. If we see a build fail, we can either fix what is causing the failure, or, if the build freezes (sometimes happens) we can run them again from the same PR.

2020-06-07 14:32 UTC, ShaunSHamilton requested changes

2020-06-07 14:32 UTC, Sky020 commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/python-iteration-and-modules.english.md
> +      ```
```suggestion
    - |
       ```python
       for key in user.items():
           print(key)
       ```
    - |
       ```python
       for key, value in user.all():
           print(key, value)
           print(value)
       ```
    - |
       ```python
       for key, value in user.items():
           print(key, value)
       ```
    - |
       ```python
       for key, value in user
           print(key, value)
       ```
```

2020-09-02 18:26 UTC, moT01 reviewed
LGTM @JapneetSingh5 🎉 This looks like a good PR that would have been merged. However, a PR was previously merged that changed all these to use the correct format already. I don't believe this is necessary anymore, so I am going to close it - if anyone disagrees, let me know and we can re-open it. Thanks and happy coding 🎉

2020-09-02 18:26 UTC, closed without merging