fix: start-server-and-test to organise e2e tests
freeCodeCamp/freeCodeCamp pull request #39036
Opened 2020-06-09 21:10 UTC by raisedadead

2020-06-09 21:15 UTC, raisedadead reviewed
Quick note:

Maybe use the healthcheck endpoint instead of waiting on the port 3000 to avoid the error with access tokens.

<details>

<summary> Details </summary>

![image](https://user-images.githubusercontent.com/1884376/84200446-73b86e00-aac4-11ea-87a7-e53f9c27f04b.png)

</details>

2020-06-12 07:59 UTC, ojeytonwilliams requested changes

2020-06-12 07:59 UTC, ojeytonwilliams commented on package.json
> +    "e2e:prd:run": "npm run build && start-test start 'http://localhost:3000/status/ping|8000' cypress:dev:run",
```suggestion
    "e2e:dev:watch": "start-test develop ':3000/status/ping|8000' cypress:dev:watch",
    "e2e:dev:run": "start-test develop ':3000/status/ping|8000' cypress:dev:run",
    "e2e:prd:watch": "npm run build && start-test ':3000/status/ping|8000' cypress:dev:watch",
    "e2e:prd:run": "npm run build && start-test ':3000/status/ping|8000' cypress:dev:run",
```
We can make it a little more concise by using the 'start' convention and the url shortcuts.  Is it still clear what's going on?

2020-06-12 19:23 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2020-06-13 09:24 UTC, merged