Remove example code from challenge seed
freeCodeCamp/freeCodeCamp pull request #39083
Opened 2020-06-16 18:48 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39081

Per the linked issue, I've removed the example code from the challenge seed. The example code is already present in the challenge instructions (without the variable declaration).

2020-06-16 20:19 UTC, ShaunSHamilton submitted a review, later dismissed
<s>LGTM 👍 </s>
Ignore this. The tests need to be changed as well, @nhcarrigan . The tests are taking into account the extra line of code you removed...

2020-06-16 20:26 UTC, nhcarrigan commented
Ah, thank you! I was trying to figure out why that test was failing.
I just stepped out so I won't be able to fix this until later this evening. 🙂

2020-06-17 01:25 UTC, nhcarrigan commented
@Sky020 Okay I fixed the tests. 
Took a good 30 minutes to figure out why my first fix wasn't working, only to realise it was a different test failing. 😅 Should be good to go now!

2020-06-17 01:56 UTC, lasjorg submitted a review, later dismissed
I guess it's fine to allow for more than one Math.random/Math.floor in the code (`>=`).

Tested in Gitpod, LGTM.

---

Just for future reference.

1. Please test your code locally when making changes to the test code. Make sure the tests pass before pushing the code.

2. Prefer creating a new branch for your PRs. It's better not to make changes to your master branch (read: [Making changes locally](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally)).

2020-06-17 02:01 UTC, nhcarrigan commented
Ah, thank you! Those are good tips and I will take them to heart. 🙂 
My thought process with the `>=` was to allow for possible instances where the user had written an extra line or did not clean up their code.

2020-06-17 06:31 UTC, thecodingaviator requested changes

2020-06-17 06:31 UTC, thecodingaviator commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/generate-random-whole-numbers-with-javascript.english.md
>    - text: You should be using <code>Math.random</code> to generate a random number.
```suggestion
  - text: You should use <code>Math.random</code> to generate a random number.
```
To maintain consistency with what we say in the last test

2020-06-17 16:56 UTC, thecodingaviator approved these changes

2020-06-17 21:55 UTC, ShaunSHamilton approved these changes
LGTM 👍

2020-06-22 10:43 UTC, merged