fix(learn): Organized the Certifications on Settings to match the main page
freeCodeCamp/freeCodeCamp pull request #39146
Opened 2020-06-27 02:46 UTC by JovaniTarnowski

Fixes freeCodeCamp/freeCodeCamp#39129

Checklist:

- [X ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39129

2020-06-28 01:50 UTC, RandellDawson commented
@ojeytonwilliams @raisedadead Do we really want to have to maintain the same data in two places?  Would it not be better to have this information pulled from a common place?

2020-06-28 08:47 UTC, ojeytonwilliams commented
> Do we really want to have to maintain the same data in two places? Would it not be better to have this information pulled from a common place?

Yep, it would be better.  However, I think that refactor should wait until after beta has been pushed to production, since the beta branch has been QA'd a fair bit and we want to make sure the launch is a smooth as possible.

2020-07-02 09:57 UTC, PeterF521 submitted a review, later dismissed

2020-07-02 10:51 UTC, ojeytonwilliams requested changes
It works nicely, but the second copy should go.

2020-07-02 10:51 UTC, ojeytonwilliams commented on client/src/resources/certAndProjectMap.js
> +  },
```suggestion
```
This copy was redundant.

2020-07-02 11:47 UTC, ojeytonwilliams approved these changes

2020-07-02 11:48 UTC, merged

2020-07-02 11:49 UTC, ojeytonwilliams commented
Thanks for sorting this out, @JovaniTarnowski, much appreciated!