Add descriptive titles for Extensible Prime Generator challenge
freeCodeCamp/freeCodeCamp pull request #39246
Opened 2020-07-13 22:04 UTC by KartikSoneji

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Adds descriptive titles instead of just `primeGenerator should be a function.`.

2020-07-23 23:04 UTC, naomi-lgbt requested changes

2020-07-23 23:04 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/extensible-prime-generator.english.md
> +  - text: <code>primeGenerator(20, true)</code> return an array with the first 20 prime numbers.
```suggestion
  - text: <code>primeGenerator(20, true)</code> should return an array with the first 20 prime numbers.
```
Lost a word here.

2020-07-23 23:05 UTC, nhcarrigan commented
As an aside, would it be more ideal to have the test `text` indicate the actual array that should be returned?
The first array is a little long, but not terribly so.

2020-07-23 23:40 UTC, KartikSoneji commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/extensible-prime-generator.english.md
> +  - text: <code>primeGenerator(20, true)</code> return an array with the first 20 prime numbers.
Thanks for catching that!

2020-07-24 00:01 UTC, KartikSoneji commented
@nhcarrigan This is what it looks like, let me know if I should make the changes.

![image](https://user-images.githubusercontent.com/25801283/88349842-e0cf4c80-cd6e-11ea-80a4-f711c5efa443.png)

2020-07-24 00:02 UTC, nhcarrigan commented
I'm not opposed to that, and I think it makes it more clear. 

I would definitely be open to other opinions though. 🙂

2020-07-24 02:05 UTC, naomi-lgbt approved these changes
LGTM!

2020-07-24 06:28 UTC, RandellDawson approved these changes
Looks good.

2020-07-24 06:28 UTC, merged

2020-07-24 06:28 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉