Fixed-pass-an-arrays-props
freeCodeCamp/freeCodeCamp pull request #39268
Opened 2020-07-16 12:02 UTC by Himanshunitrr

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-07-16 22:35 UTC, RandellDawson requested changes
@Himanshunitrr See my suggested changes.

2020-07-16 22:35 UTC, RandellDawson commented on curriculum/challenges/english/03-front-end-libraries/react/pass-an-array-as-props.english.md
> +    testString: assert((function() { const mockedComponent = Enzyme.mount(React.createElement(ToDo)); return ( mockedComponent.find('p').get(0).props.children === mockedComponent.find('List').get(0).
To simplify the code (not so many ||s) and to allow for any number of spaces before or after the comma, I suggest the following:
```suggestion
    testString: |
      assert((function() {
        const mockedComponent = Enzyme.mount(React.createElement(ToDo));
        return (
          mockedComponent.find('p').get(0).props.children.replace(/\s*,\s*/g,',') === mockedComponent.find('List').get(0).props.tasks.join(',').replace(/\s*,\s*/g,',') &&
          mockedComponent.find('p').get(1).props.children.replace(/\s*,\s*/g,',') === mockedComponent.find('List').get(1).props.tasks.join(',').replace(/\s*,\s*/g,',')
        );
      })());
```

2020-07-17 03:32 UTC, Himanshunitrr commented
I was too thinking to use regex, Thanks for your valuable review.

2020-07-17 18:59 UTC, RandellDawson approved these changes

2020-07-17 19:01 UTC, RandellDawson commented
Now it looks good to me.

2020-07-17 19:39 UTC, Manish-Giri approved these changes
LGTM 💯 

@Himanshunitrr For future PRs, please include the corresponding issue # (if there is one) in the PR body, so that it gets closed when the PR is merged. I have edited this one to include it. 

Thanks for your contribution!

2020-07-17 20:11 UTC, merged

2020-07-17 20:11 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉