Fix/delayofflinewarning
freeCodeCamp/freeCodeCamp pull request #39291
Opened 2020-07-19 12:19 UTC by ruhci28

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `master` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39250 

I delayed the offline warning for 5 seconds when the user is offline. The warning will not be shown if in the meantime the user get their connection back with the internet .  The warning will disappear after the user come online.

2020-07-20 08:36 UTC, ojeytonwilliams requested changes
It's looking good, but could you revert the changes to the challenge?

2020-07-20 08:36 UTC, ojeytonwilliams commented on curriculum/challenges/english/03-front-end-libraries/react/add-event-listeners.english.md
> +      );
```suggestion
      message: this.state.message + 'You pressed the enter key! '
    });
```
This should revert the changes.

2020-07-20 15:19 UTC, ruhci28 commented on curriculum/challenges/english/03-front-end-libraries/react/add-event-listeners.english.md
> +      );
yeah sure

2020-07-20 16:59 UTC, ojeytonwilliams submitted a review, later dismissed
Great work, @ruhci28!  Looks good to me :+1:

2020-07-20 17:32 UTC, naomi-lgbt submitted a review, later dismissed
LGTM - gave this a test on a local instance. Simulating offline-status with dev tools correctly generated the warning after a few seconds. 🙂

2020-07-20 18:36 UTC, RandellDawson commented on client/src/components/OfflineWarning/OfflineWarning.js
> +var id;
Can we use `let` here`?
```suggestion
let id;
```

2020-07-20 19:21 UTC, ruhci28 commented on client/src/components/OfflineWarning/OfflineWarning.js
> +var id;
Yeah

2020-07-21 09:35 UTC, ruhci28 commented on client/src/components/OfflineWarning/OfflineWarning.js
> +var id;
@RandellDawson i apply the changes

2020-07-21 09:56 UTC, ojeytonwilliams approved these changes
@RandellDawson it's ready to merge when you're happy with it.

2020-07-22 12:25 UTC, RandellDawson approved these changes

2020-07-22 12:26 UTC, merged

2020-07-22 12:26 UTC, RandellDawson commented
Congrats @ruhci28 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝

2020-07-22 14:01 UTC, ruhci28 commented
Thank you . A big thanks to @ojeytonwilliams  for guiding me .

2020-07-22 14:04 UTC, ojeytonwilliams commented
You're very welcome, @ruhci28.  Thanks for helping improve freeCodeCamp - it's much appreciated.