fix: resolve #39301
freeCodeCamp/freeCodeCamp pull request #39304
Opened 2020-07-23 22:02 UTC by Aviel212

Add a test to check the "MyComponent" constructor's parameters (params) and to check that the super function exists in the constructor.

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-07-23 22:04 UTC, yardenshoham submitted a review, later dismissed

2020-07-23 22:45 UTC, naomi-lgbt requested changes

2020-07-23 22:45 UTC, nhcarrigan commented on curriculum/challenges/english/03-front-end-libraries/react/write-a-react-component-from-scratch.english.md
> +  - text: <code>MyComponent</code> should have a constructor with <code>props</code> calling <code>super</code>.
```suggestion
  - text: <code>MyComponent</code> should have a constructor calling <code>super</code> with <code>props</code>.
```

I recommend changing the verbiage here, as "props calling super" doesn't seem clear or accurate. 🙂 The suggested verbiage here comes from [this comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/39301#issuecomment-663088086).

2020-08-25 11:30 UTC, Sky020 approved these changes
LGTM 👍 . Thank you, for getting this PR out.

@RandellDawson , With this PR, I would be happy with this as is. However, I can see campers getting annoyed at the instructions not telling them to pass `props` from the constructor to `super`. Do you think the instructions need a similar addition?

Currently, the only mention of the constructor in the instructions is:
> Make sure to call the constructor for your component, too.

The fCC-console gives a warning to check the browser console, and the browser console does give very useful errors, if the `super` call is missing.

2020-08-25 11:43 UTC, RandellDawson commented
@Sky020 Thinking of how we are currently giving "hints" (targeted tests) in the new project-based curriculum, the hints (similar to the current tests) will give reminders on syntax.  If a previous step in a project introduces a concept or syntax, then following steps may or may not restate the same information, but the hints would be relied upon as the reminder about the syntax.

Applying the same logic here, in a [previous challenge](https://www.freecodecamp.org/learn/front-end-libraries/react/create-a-react-component), the user has already been told about adding the `super` call, so I think it is completely fine to not include it in the description/instructions of this challenge.  Since, the instructions give the helpful hint of "Make sure to call the constructor for your component, too." and the FCC console gives even more hints, I do not think it is necessary to spell things out further.

2020-08-25 14:54 UTC, naomi-lgbt approved these changes
LGTM! Congratulations on submitting your first PR~! 🥳

2020-08-25 15:39 UTC, RandellDawson approved these changes

2020-08-25 15:41 UTC, merged