feat: Add GitHub Action to label merge conflicts
freeCodeCamp/freeCodeCamp pull request #39317
Opened 2020-07-24 20:59 UTC by RandellDawson

Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

I found [this GitHub Action](https://github.com/mschilde/auto-label-merge-conflicts) that adds `status: merge conflict` to any PRs that have merge conflicts anytime a push is made to specific branches (I targeted `master` and `next-curriculum` for now).

This action has the added bonus of removing any `status: merge conflict` label if a PR no longer has a merge conflict.

I tested the action out on a personal repo and seems to work as advertised.  If we like this one, I think I could tweak this action, so it also adds a comment to the PR that tags OP.  This would make it so that the GitHub notification feature marks it as a `mention` instead of just `subscribed`, in order to draw more attention these PRs.

2020-07-26 16:36 UTC, raisedadead commented
Thanks. 

> I targeted `master` and `next-curriculum` for now

Let's just make it universal. A merge conflict is a conflict regardless.

2020-07-26 23:49 UTC, RandellDawson commented
@raisedadead You mean across all repos under the freeCodeCamp organization or just all the branches under the freeCodeCamp repo?

2020-07-27 04:17 UTC, raisedadead commented
Just all the branches on freeCodeCamp repo

2020-07-27 05:16 UTC, RandellDawson commented
@raisedadead OK.  I have edited the yml file to activate across all branches of this repo.

2020-07-27 07:29 UTC, ojeytonwilliams requested changes
Looks good as is, but I've suggested a couple of minor changes.

2020-07-27 07:29 UTC, ojeytonwilliams commented on .github/workflows/label_merge_conflicts.yml
> +      - uses: mschilde/auto-label-merge-conflicts@master
```suggestion
      - uses: mschilde/auto-label-merge-conflicts@v2.0
```
Same as above.

2020-07-27 07:29 UTC, ojeytonwilliams commented on .github/workflows/label_merge_conflicts.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-18.04
```
We should lock the version, just in case.

2020-07-27 08:04 UTC, ojeytonwilliams approved these changes

2020-07-27 08:05 UTC, ojeytonwilliams commented on .github/workflows/label_merge_conflicts.yml
> +      - uses: mschilde/auto-label-merge-conflicts@master
Nevermind, v2.0 does not have a feature we want https://github.com/mschilde/auto-label-merge-conflicts/commit/f842c977cada4f2f391aa98bfbe126e24ccedd57, so master should be fine for now.

2020-07-27 09:16 UTC, merged