Changing test order to test for the value after execution has finished
freeCodeCamp/freeCodeCamp pull request #39363
Opened 2020-08-03 21:27 UTC by multiwebinc

Checklist:

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `master` branch of freeCodeCamp.
- [ x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39362

2020-08-03 21:35 UTC, naomi-lgbt requested changes

2020-08-03 21:35 UTC, nhcarrigan commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/avoid-mutations-and-side-effects-using-functional-programming.english.md
> +    testString: assert(fixedValue === 4);
```suggestion
  - text: Your function <code>incrementer</code> should not change the value of <code>fixedValue</code> (which is <code>4</code>).
    testString: incrementer(); assert(fixedValue === 4);
```

Changing the order itself does not appear to be sufficient for testing - adding a function call before the assert statement will verify that the value of `fixedValue` has not changed.

2020-08-03 23:04 UTC, RandellDawson commented
@multiwebinc I like @nhcarrigan's suggestion, but also, I would leave the order of the tests the same, but also include @nhcarrigan's suggestion.

@nhcarrigan See the other issue I created for this challenge.

2020-08-03 23:55 UTC, naomi-lgbt requested changes

2020-08-03 23:55 UTC, nhcarrigan commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/avoid-mutations-and-side-effects-using-functional-programming.english.md
> +    testString: assert(fixedValue === 4);
```suggestion
  - text: Your function <code>incrementer</code> should not change the value of <code>fixedValue</code> (which is <code>4</code>).
    testString: incrementer(); assert(fixedValue === 4);
  - text: Your <code>incrementer</code> function should return a value that is one larger than the <code>fixedValue</code> value.
    testString: const newValue = incrementer(); assert(newValue === 5);
```

This suggestion restores the original order of the tests, per @RandellDawson's comment.

2020-08-04 02:32 UTC, RandellDawson approved these changes

2020-08-04 02:35 UTC, naomi-lgbt approved these changes
LGTM!

2020-08-04 19:48 UTC, merged