feat: add intro text to email sign up page
freeCodeCamp/freeCodeCamp pull request #39409
Opened 2020-08-14 15:36 UTC by ahmadabdolsaheb

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-08-14 17:27 UTC, ojeytonwilliams requested changes
One thing I noticed was it says `We have updated your preferences. You can now continue using freeCodeCamp!` in `api-server/server/boot/settings.js`, it should probably just say `We have updated your preferences.`.  Sorry, I should have caught that before.


Also a couple of nitpicks:

2020-08-15 09:47 UTC, ahmadabdolsaheb commented
@ojeytonwilliams should be ready.

2020-08-15 09:51 UTC, raisedadead requested changes

2020-08-15 09:51 UTC, raisedadead commented on api-server/server/boot/settings.js
> +      message: 'We have updated your preferences. '
```suggestion
      message: `We have updated your preferences.`
```

Drop the space and lets use backticks.

2020-08-15 21:01 UTC, merged