feat(learn): add word frequency challenge to rosetta section
freeCodeCamp/freeCodeCamp pull request #39424
Opened 2020-08-17 20:57 UTC by moT01

Made a PR in place of https://github.com/freeCodeCamp/freeCodeCamp/pull/38571 since the user was not responding and blocked edits from maintainers.

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-08-24 16:27 UTC, RandellDawson requested changes
@moT01 See my suggested changes.

Also, what should the following call return?
```
wordFrequency("c d a d c a b d c d c", 1)
```
I ask, because in this case, "c" and "d" would both have a frequency of `4`, so what determines which letter should be shown?

2020-08-24 16:27 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/word-frequency.english.md
> +  - text: <code>wordFrequency</code> should return the expected output for <code>("Hello hello world", 2)</code>
```suggestion
  - text: <code>wordFrequency("Hello hello world", 2)</code> should return <code>[['hello', 2], ['world', 1]]</code>
```

2020-08-24 16:27 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/word-frequency.english.md
> +  - text: <code>wordFrequency</code> should return the expected output for <code>("The quick brown fox jumped over the lazy dog", 4)</code>
```suggestion
  - text: <code>wordFrequency("The quick brown fox jumped over the lazy dog", 4)</code> should return  <code>[['the', 2], ['brown', 1], ['dog', 1], ['fox', 1]]</code>
```

2020-08-24 16:27 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/word-frequency.english.md
> +  - text: <code>wordFrequency</code> should return the expected output for <code>("Opensource opensource open-source open source", 1)</code>
```suggestion
  - text: <code>wordFrequency("Opensource opensource open-source open source", 1)</code> should return 
 <code>[['opensource', 2]]</code>
```

2020-08-24 16:27 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/word-frequency.english.md
> +  - text: <code>wordFrequency</code> should return the expected output for <code>("Apple application App apply applicative aPP aPPlE able", 3)</code>
```suggestion
  - text: <code>wordFrequency("Apple application App apply applicative aPP aPPlE able", 3)</code> should return <code>[['app', 2], ['apple', 2], ['able', 1]]</code>
```

2020-08-24 16:27 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/word-frequency.english.md
> +  - text: <code>wordFrequency</code> should return the expected output for <code>("c d a d c a b d d c", 4)</code>
```suggestion
  - text: <code>wordFrequency("c d a d c a b d d c", 4)</code> should return <code>[['d', 4], ['c', 3], ['a', 2], ['b', 1]]</code>
```

2020-08-24 16:27 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/word-frequency.english.md
> +  - text: <code>wordFrequency</code> should return an empty array for <code>("", 5)</code>
```suggestion
  - text: <code>wordFrequency("", 5)</code> should return <code>[]</code>
```

2020-08-25 08:00 UTC, thecodingaviator commented
> Also, what should the following call return?
> 
> ```
> wordFrequency("c d a d c a b d c d c", 1)
> ```
> 
> I ask, because in this case, "c" and "d" would both have a frequency of `4`, so what determines which letter should be shown?

The Rosetta spec says "Words of equal frequency can be listed in any order."

2020-08-25 11:29 UTC, RandellDawson commented
> The Rosetta spec says "Words of equal frequency can be listed in any order."

If that is the case @moT01, wouldn't we need to have two solutions for test 4, to allow both of the following?
```
[['app', 2], ['apple', 2], ['able', 1]]
```
and
```
[['apple', 2], ['app', 2], ['able', 1]]
```

2020-08-25 11:35 UTC, Sky020 commented
>  wouldn't we need to have two solutions for test 4, to allow both of the following?

@RandellDawson My understanding of `deepEqual` was that it allows for element order to be different.

2020-08-25 11:44 UTC, RandellDawson commented
> @RandellDawson My understanding of deepEqual was that it allows for element order to be different.

@Sky020 If that is the case, then no extra solution should be necessary. Thanks for pointing that out.

2020-08-25 11:56 UTC, Sky020 commented
@RandellDawson Forgive me. I spoke too soon; after testing, I can confirm that `deepEqual` in Chaijs does care about element order. We would need to use `sameDeepMembers`

2020-08-25 12:07 UTC, RandellDawson commented
> 'application' appears the same number of times as 'able'

@Sky020 I only see the word "application" once in the test code.  The other word is "applicative".

Right after your first reply, I tested and discovered (as you did) that `deepEqual` will not work.  Also, unless I am mistaken, using `sameDeepMembers` also only allows `[['app', 2], ['apple', 2], ['able', 1]]` to pass the 4th test.

2020-08-25 12:34 UTC, Sky020 commented
@RandellDawson , From what I have tested, `sameDeepMembers` passes with different order consistently:
![image](https://user-images.githubusercontent.com/51722130/91174566-5bc1b500-e6d7-11ea-8452-043a5b47faef.png)

I now see the issue with using it, though:
> return the n most common words in the file (and the number of their occurrences) **in decreasing frequency**.

So, we will need multiple solutions, as you mentioned in your original comment about this.

2020-08-29 19:28 UTC, moT01 commented
> Why is this not a valid answer:
> 
> [['apple', 2],['app', 2],['application', 1]];
> 

The way I understand it, that should be valid - meaning there could be a whole heck of a lot of solutions for that test. So you already mentioned that the first two words could be in any order, and then the last word could be any of the other four words that appear once. Making a total of 8 different solutions. I can try and fix it up - maybe make the sentences a little easier.

2020-08-30 01:36 UTC, moT01 commented
DeepEqual seems to be working for me - when I change the order of things, the tests don't pass. I must be missing something for why it doesn't work. Someone may have to explain it to me.

I simplified some of the tests so we don't have to check for multiple different solutions. If anyone has any better ideas, let me know.

2020-08-31 16:12 UTC, ojeytonwilliams commented
Can't we just `.sort()` the two arrays we want to compare with `.deepEqual`? Then the tests would be more forgiving about implementation details.  If we go that way, I think we'd need to change the wording to reflect that.  i.e. `<code>wordFrequency("c d a d c a b d d c", 4)</code> should return <code>[['d', 4], ['c', 3], ['a', 2], ['b', 1]]</code>` -> `<code>wordFrequency("c d a d c a b d d c", 4)</code> should return an array containing <code>['d', 4], ['c', 3], ['a', 2], ['b', 1]</code>

2020-08-31 18:19 UTC, moT01 commented
The challenge states to return the array in a specific order, so I think sorting is out.

2020-08-31 18:46 UTC, ojeytonwilliams commented
Oh, sorry, I skimmed.  What about `xs.sort((x,y) => y[1] - x[1] ? y[1] - x[1] : x[0].localeCompare(y[0]))` ? It should break ties on the order of the words.

2020-08-31 20:00 UTC, moT01 commented
Still not sure what's wrong with deepEqual - seemed to work when I tested it.

2020-08-31 20:04 UTC, Sky020 commented
@moT01 My testing revealed that, whilst this is an answer and passes the tests:
```
[['app', 2], ['apple', 2], ['able', 1]]
```
This should also pass the tests, but does not with `deepEqual`:
```
[['apple', 2], ['app', 2], ['able', 1]]
```

_provided it is tested against: `[['app', 2], ['apple', 2], ['able', 1]]`_

2020-08-31 20:09 UTC, moT01 commented
I changed a few of the tests so there's only one correct answer. Perhaps that wasn't what we wanted to do. Seemed like an easy solution.

2020-08-31 20:17 UTC, RandellDawson commented
I think it should work regardless what tests we include or not include.  In fact, I think the test case I came up with should be included, since the instructions state that words with the same frequency can be any any order.  It is only one additional array to test against in the test, so I think that is the way to go.

2020-09-02 22:09 UTC, moT01 commented
I changed one of the challenges back to have multiple possible solutions. The only way I could figure out to test it was to stringify the array before comparing.

2020-09-02 22:46 UTC, RandellDawson submitted a review, later dismissed

2020-09-02 22:47 UTC, RandellDawson commented
@Sky020 I am happy with these latest changes that @moT01 made.  Merge if you approve.

2020-09-03 11:14 UTC, Sky020 requested changes
@moT01 I realise it is in the last test, but should we not add something to the instructions about returning an empty array?

Currently, the only mention (in the instructions) of what to return is:
> The function should return a 2D array...

Of which, `[]` is not.

2020-09-03 11:14 UTC, Sky020 commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/word-frequency.english.md
> +Your function should be case insensitive, for example, the strings "Hello" and "hello" should be treated the same.
```suggestion
The function should return an empty array, if no string is provided.
The function should be case insensitive, for example, the strings "Hello" and "hello" should be treated the same. 
```

2020-09-03 12:52 UTC, RandellDawson commented
@Sky020 I am still happy with these changes.  Merge if you approve.

2020-09-03 13:05 UTC, Sky020 approved these changes
Thank you, for your contribution! 👍

We are happy to accept these changes and look forward to future contributions. 🎉

2020-09-03 13:06 UTC, Sky020 commented
@RandellDawson I am not allowed to merge, unless one more approving review gets made. So, you can do so, please.

2020-09-03 13:30 UTC, RandellDawson approved these changes

2020-09-03 13:30 UTC, merged