Tools: Add CI tests for dev script on all supported OS
freeCodeCamp/freeCodeCamp pull request #39456
Opened 2020-08-23 16:04 UTC by Twaha-Rahman

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39453

This PR adds workflow that'll run on every push to the master branch and make sure that the dev server will run each of the following OS ->

1. Ubuntu-16.04
4. Windows (Latest Version)
5. MacOS (Latest Version)

2020-08-24 10:45 UTC, raisedadead requested changes
I think this can be part of the Node.js test CI we already have. Also I think we can get away with only ubuntu-18.04

2020-08-24 15:47 UTC, Twaha-Rahman commented
Ignore all the checks failing for now.... I'll fix them.

The workflows currently install MongoDB using images, which is only available in `linux`. So... for other OS we'll have manually install it using the terminal.

2020-08-26 01:38 UTC, Twaha-Rahman commented
Ok.... here's the latest update: I got everything running in Windows. Now I just need to kill the process after a given time cause otherwise the script `npm run develop` will run for 6 hours straight. (This won't be that difficult)

After the Windows part is finished I'll look into the MacOS part.

2020-08-27 15:42 UTC, Twaha-Rahman commented
Progress so far: Workflows can now install and run MongoDB on all OS.

Now I'm working on testing each script. (A working PoC is already implemented but it takes a LOT of time to run. I'm currently optimizing and refactoring it)

2020-08-31 06:31 UTC, Twaha-Rahman commented
Finished writing everything to check the `develop` and `build` scripts on all OS. Let me know what you guys think.

2020-08-31 06:32 UTC, Twaha-Rahman commented
Btw... the Windows check will fail currently due to #39458

2020-08-31 08:29 UTC, ojeytonwilliams commented
Hey, @Twaha-Rahman, thanks for all the hard work you've been putting into this!  

Regarding the Window's check, has that problem been fixed on master?  If so, could you rebase, so we can confirm?

2020-08-31 11:43 UTC, Twaha-Rahman commented
> Regarding the Window's check, has that problem been fixed on master?

@ojeytonwilliams I don't think so. The issue barely got any proper response. I'll look into it later on.

2020-08-31 12:03 UTC, ojeytonwilliams commented
@Twaha-Rahman, ah, I thought https://github.com/freeCodeCamp/freeCodeCamp/pull/39475 and https://github.com/freeCodeCamp/freeCodeCamp/pull/39454 together fixed the outstanding issues. Are you still encountering problems?  

> I'll look into it later on.

No rush at all, take whatever time you need.

2020-09-17 13:38 UTC, ojeytonwilliams commented
Hey @Twaha-Rahman, I'm just trying to see if this latest commit fixes the build problems on Windows.

2020-09-17 14:01 UTC, Twaha-Rahman commented
@ojeytonwilliams Looks like it did the trick for Windows!

2020-09-17 15:59 UTC, raisedadead commented
Thanks, a lot for this PR @Twaha-Rahman 

I think we are trying to overdo this a little bit here. 

Like I said before I still believe:

> ... I think we can get away with only ubuntu-18.04

My rationale being:

There will always be pitfalls like #39458 and #37865 with Windows. Not saying that we should not address those, but it's not worth the hassle.

Our bottom-line is the final build gets deployed in a Unix environment - specifically on Ubuntu. The development env should be close to it too? Meaning we can make sure the CI is testing a build for Ubuntu only? 

I know it's an unpopular opinion. 

I also understand some of us are developing on Windows and macOS. I personally had been on macOS and have switched to Ubuntu on WSL2 since a week.

Right now the status quo as I understand is:

1. **GitPod**

   Works perfectly, but needs internet access at all times.

2. **Ubuntu and macOS**

   Work fine already with the native setup (Git, MongoDB, Node.js all are installed natively).

3. **Windows**

   Painful with the native setup (Git bash with Git for Windows and official binaries from MongoDB and Node.js)

4. **Docker** 

   A complete mess. It was an attempt unify the development flow but has become a pain point. Should be removed from docs and workflow.

IMHO, if we made it so that everyone was developing in a Unix env (regardless of the OS they are on), we would be needing to test builds only for Ubuntu-18-04. The time and build resources saved is worth not needing to build for all other OS flavors.

Luckily, it's possible. 

We need to work on the development for Windows so that is close to Ubuntu and remove the docker workflows. A CI test is only an indicator of catching issues early-on, it would not solve the pain of going about setting up tools in the first place. I think we should focus on getting the setup right first.

2020-09-18 05:48 UTC, Twaha-Rahman commented
@raisedadead I see your point. So let's just keep CI tests for Ubuntu.

2021-02-01 05:08 UTC, raisedadead reviewed
Closing this stale for now, for a head branch rename. Thanks for your PR. 

I think we can use tools like `wait-on` or `start-server-and-test` instead, if all we are testing the `develop` run-script is working.

2021-02-01 05:08 UTC, closed without merging