fix global flag in Regex by resetting last Index
freeCodeCamp/freeCodeCamp pull request #39457
Opened 2020-08-23 23:52 UTC by yyazdi13

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #37890 

Hi I'm pretty new at this so I just tried to follow along with a similar solution used in PR #37941. Please let me know if I need to improve anything

2020-08-24 09:03 UTC, Sky020 requested changes
Thank you, for making a PR for this. Could you also please add this to the final 2 tests, and, while we are at it, could you fix the final test so it matches the `text`?

Instead of `"Can me if you can."` -> `"Catch me if you can."`

@ojeytonwilliams In the issue, you mentioned adding this to the `js-teardown`, do you still think that is would be beneficial to do? Or, just move on with this implementation?

2020-08-24 13:57 UTC, yyazdi13 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/match-anything-with-wildcard-period.english.md
>      testString: assert(!unRegex.test("There is a bug in my code."));
okay no problem, I will take a look

2020-08-31 10:06 UTC, ojeytonwilliams approved these changes
@Sky020 it would be cleaner to do it in the teardown, but this is fine.

LGTM :+1:

2020-08-31 10:14 UTC, Sky020 approved these changes
I am happy with moving this forward 👍

2020-08-31 11:29 UTC, merged

2020-08-31 11:30 UTC, thecodingaviator commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝