Chore: validate build variables
freeCodeCamp/freeCodeCamp pull request #39474
Opened 2020-08-26 13:56 UTC by ojeytonwilliams

This should make the pipelines (wherever they end up) easier to manage, since we'll get warnings as early as possible.

2020-08-30 15:33 UTC, raisedadead requested changes
While you are cleaning up servicebot, lets remove everything about it? A partial remove kind of leaves it dangling.

2020-08-31 08:16 UTC, ojeytonwilliams commented
@raisedadead if you're happy I didn't rip out too much, let me know and I'll clean up the commits.

2020-09-01 05:45 UTC, raisedadead approved these changes, later dismissed
Looks good, if you can cleanup the commits should be ready to go in.

2020-09-01 07:53 UTC, ojeytonwilliams commented on tools/scripts/build/ensure-env.js
> +  for (const key of variables) {
```suggestion
  for (const key of expectedVariables) {
```
I'll make this change this while I rebase.

2020-09-03 18:44 UTC, raisedadead approved these changes

2020-09-03 18:44 UTC, merged