Remove beta statement
freeCodeCamp/freeCodeCamp pull request #39497
Opened 2020-08-31 15:19 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

While reviewing the contributing documentation to find an answer for a camper, I ran across a line that stated the video challenges were in beta and not available on the `.org` website. As this is no longer the case, the line should be removed.

2020-08-31 15:58 UTC, Sky020 requested changes
Nice catch, but what about the next few lines as well, talking about how many of the videos do not have questions yet?

Do we plan to have more video challenges made? Is majority of this guide redundant?

2020-08-31 16:02 UTC, nhcarrigan commented
A good point - I do think the clarification on how the video challenges differ from the editor-based challenges is important. I also admit to only catching the one line and not auditing the full doc, but I can look in to it further. :)

2020-09-03 09:17 UTC, raisedadead approved these changes

2020-09-03 09:17 UTC, merged

2020-09-03 09:18 UTC, raisedadead commented
I merged this as is, please feel free to update the document in later audits :)