Fix tests failing due to whitespaces and trailing forward slash in Advanced Node and Express
freeCodeCamp/freeCodeCamp pull request #39534
Opened 2020-09-06 12:27 UTC by piouson

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39533

2020-09-06 18:25 UTC, Sky020 requested changes
I have not tested the need for the lazy matching, but the `\s` flag checks for all kinds of whitespace (`\r\n\t\f\v`), and the `g` flag should negate the need for `+`

2020-09-06 18:25 UTC, Sky020 commented on curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.english.md
> +    testString: getUserInput => $.get(getUserInput('url')+ '/_api/routes.js') .then(data => { assert.match(data.replace(/[\s\r\n]+/g,""), /('|")\/auth\/github\/?('|")[^]*?get.*?passport.authenticate.
```suggestion
    testString: getUserInput => $.get(getUserInput('url')+ '/_api/routes.js') .then(data => { assert.match(data.replace(/\s/g,""), /('|")\/auth\/github\/?('|")[^]*?get.*?passport.authenticate.*?github/gi, 'Route auth/github should only call passport.authenticate with github'); }, xhr => { throw new Error(xhr.statusText); })
```

2020-09-06 18:25 UTC, Sky020 commented on curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.english.md
> +    testString: getUserInput => $.get(getUserInput('url')+ '/_api/routes.js') .then(data => { assert.match(data.replace(/[\s\r\n]+/g,""), /('|")\/auth\/github\/callback\/?('|")[^]*?get.*?passport.aut
```suggestion
    testString: getUserInput => $.get(getUserInput('url')+ '/_api/routes.js') .then(data => { assert.match(data.replace(/\s/g,""), /('|")\/auth\/github\/callback\/?('|")[^]*?get.*?passport.authenticate.*?github.*?failureRedirect:("|')\/\2/gi, 'Route auth/github/callback should accept a get request and call passport.authenticate for github with a failure redirect to home'); }, xhr => { throw new Error(xhr.statusText); })
```

2020-09-06 21:22 UTC, RandellDawson commented
@Sky020 If we are fixing the regex, can you adjust the regex for both of your suggestions to make use of the capture groups for the single or double quotes.  For example:
Change:
```js
/('|")\/auth\/github\/callback\/?('|")[^]*?get.*?passport.authenticate.*?github.*?failureRedirect:("|')\/\2/gi
```
to:
```js
/('|")\/auth\/github\/callback\/?\1[^]*?get.*?passport.authenticate.*?github.*?failureRedirect:("|')\/\2/gi
```

2020-09-06 22:12 UTC, piouson commented
> I have not tested the need for the lazy matching, but the `\s` flag checks for all kinds of whitespace (`\r\n\t\f\v`), and the `g` flag should negate the need for `+`

I suppose only the first test requires the lazy matching, but I left both lazy..

2020-09-06 22:14 UTC, Sky020 commented on curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.english.md
> +    testString: getUserInput => $.get(getUserInput('url')+ '/_api/routes.js') .then(data => { assert.match(data.replace(/\s/g,""), /('|")\/auth\/github\/callback\/?\1[^]*?get.*?passport.authenticate.
```suggestion
    testString: getUserInput => $.get(getUserInput('url')+ '/_api/routes.js') .then(data => { assert.match(data.replace(/\s/g,""), /('|")\/auth\/github\/callback\/?\1[^]*?get.*?passport.authenticate.*?github.*?failureRedirect:( |)("|')\/\2/gi, 'Route auth/github/callback should accept a get request and call passport.authenticate for github with a failure redirect to home'); }, xhr => { throw new Error(xhr.statusText); })
```

2020-09-06 22:14 UTC, Sky020 commented on curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/implementation-of-social-authentication.english.md
> +    testString: getUserInput => $.get(getUserInput('url')+ '/_api/routes.js') .then(data => { assert.match(data.replace(/\s/g,""), /('|")\/auth\/github\/callback\/?\1[^]*?get.*?passport.authenticate.
Unlikely, but we cannot assume the camper will always use the same kind of quote.

2020-09-06 22:18 UTC, Sky020 commented
@piouson Thank you, for making those changes. Unfortunately, I had a brain-freeze moment. So, could you update to remove the `( |)` again?

You were correct in removing it in the first place, because of the `.replace()`

2020-09-06 22:23 UTC, RandellDawson commented
@Sky020 Technically, the second set of quotes around `/` can be either `"` or `'`.  While not likely, the user could use double quotes for one and single quotes for the other.

2020-09-06 22:41 UTC, piouson commented
> @Sky020 Technically, the second set of quotes around `/` can be either `"` or `'`. While not likely, the user could use double quotes for one and single quotes for the other.

ahah I realise now, best to leave it as separate capture groups..

> @piouson Thank you, for making those changes. Unfortunately, I had a brain-freeze moment. So, could you update to remove the `( |)` again?
> 
> You were correct in removing it in the first place, because of the `.replace()`

good catch, indeed that was my initial idea, I missed that, but all should be good now, thank you!

2020-09-07 01:21 UTC, RandellDawson approved these changes
LGTM

2020-09-07 10:22 UTC, Sky020 approved these changes
Thank you, @piouson ! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

2020-09-08 16:55 UTC, moT01 approved these changes
Thanks for contributing to freeCodeCamp @piouson 🎉

2020-09-08 16:55 UTC, merged