Fixed implement-map-and-filter-on-prototype challenge by adding a hint on how to access array instance from the method being defined
freeCodeCamp/freeCodeCamp pull request #39548
Opened 2020-09-09 12:24 UTC by nibble0101

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39486

This pull request updates the following challenges by giving a hint to the learner on how to access the `Array` instance while implementing custom `map` and `filter`  array methods.
-  [implement map on a prototype](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype)
- [implement the filter method on a prototype](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype)

2020-09-09 13:38 UTC, RandellDawson commented
@nibble0101 If we accept the additional note, it would be best to use markdown syntax instead of `ul` and `li` elements.  You can create a list by prefixing the line with `- ` or `* `.

2020-09-09 13:53 UTC, nibble0101 commented
@RandellDawson  I did use markdown at first but after checking on Gitpod, the list isn't displaying.

2020-09-09 14:02 UTC, RandellDawson commented
You must have a empty single line after the the opening `section` tag and before the closing `section` tag for the markdown to work.  The documentation does not reflect this currently, but since we will soon be using a completely different challenge file template, there is no need to update the documentation at this time.

2020-09-09 17:26 UTC, raisedadead requested changes
The `pathMigration` file is no longer needed. Can you rebase against master to get the latest changes, thanks.

2020-09-09 18:15 UTC, nibble0101 commented
@raisedadead  
> Can you rebase against master to get the latest changes.

What does that mean?

2020-09-09 18:21 UTC, raisedadead commented
> What does that mean?

https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=conflicts-on-a-pull-request

2020-09-09 18:22 UTC, RandellDawson commented
> What does that mean?

@nibble0101 

```sh
git pull --rebase upstream master
```
This will get all the changes that might have been merged to `master` since you first started working on this PR and then adds your commits on top.  If there are any merge conflicts, you will have to resolve them.

Also, you want to make sure to remove the `api-server/server/resources/pathMigration.json` which got created.

2020-09-09 19:14 UTC, nibble0101 commented
@RandellDawson  Thanks. I keep getting "Current branch is up to date" whether i run that command from the main branch or from the i am working on.

2020-09-11 22:22 UTC, RandellDawson requested changes
I am not opposed to adding the extra note as we are not planning on completely rewriting or rearranging the other challenges that would cover `this` for thoroughly.

I just have two small formatting changes.

2020-09-11 22:22 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/implement-map-on-a-prototype.english.md
> +Note:
```suggestion
**Notes:** 
```

2020-09-11 22:22 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/implement-the-filter-method-on-a-prototype.english.md
> +Note:
```suggestion
**Notes:** 
```

2020-09-14 16:40 UTC, moT01 commented
I'm not a fan of how big the text gets when there's a list...

![Screen Shot 2020-09-14 at 11 14 08 AM](https://user-images.githubusercontent.com/20648924/93110922-8e7a2000-f67b-11ea-87bd-16d31babe62d.png)

It makes the notes feel more important than the description. I'm really not a fan of the list itself either. I feel like these notes could be integrated into the description and instructions. Maybe something like this...?

![Screen Shot 2020-09-14 at 11 33 37 AM](https://user-images.githubusercontent.com/20648924/93112929-2b3dbd00-f67e-11ea-9c72-b2add57aa3e4.png)

After trying to come up with a suggestion, I felt there was a lot that could be changed up. I didn't see a need for the first note. Perhaps I am getting outside the scope of this issue, but I feel like it should look something like the above. If we don't want to rewrite it that much, I still vote for integrating the notes into the description/instructions. That my opinion, although, if others don't want to go that route, I can live with it.

2020-09-14 17:01 UTC, RandellDawson commented
@moT01 Inserting the notes into the instructions section is fine too.  However, for the last sentence of the description section, I would prefer:

> You could use a `for` loop or the `Array.prototype.forEach` method.

The challenges should be written from the second person point of view.

2020-09-18 20:46 UTC, nibble0101 commented
@RandellDawson  and @moT01 . What is the final decision here?

2020-09-18 21:58 UTC, moT01 commented
I think we want to go with my suggestion and Randell's modification - I dunno, what do you think of that @nibble0101?

2020-09-18 22:41 UTC, RandellDawson commented
@nibble0101 I discussed with @moT01 that I would be on board with using his suggestion with my adjustment.

2020-09-19 06:26 UTC, nibble0101 commented
@RandellDawson, @moT01. I am okay with your suggestions above.

2020-09-19 08:19 UTC, nibble0101 commented
@RandellDawson  @moT01  @raisedadead  I am completely confused by these git commands. I am not sure I am doing the right thing anymore. I closed this PR without knowing twice already. I am closing this PR and  and opening another one.

2020-09-19 08:19 UTC, closed without merging