fix(learn): React propTypes challenge, improve test text
freeCodeCamp/freeCodeCamp pull request #39682
Opened 2020-09-24 21:28 UTC by walterpalagi

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39204

See RandellDawson's [request](https://github.com/freeCodeCamp/freeCodeCamp/issues/39204#issuecomment-698545162).

2020-09-24 23:25 UTC, RandellDawson requested changes
@walterpalagi Thanks for the PR.  I have made a small suggestion.  Since number is not a value or a variable name, the code tags are not needed. If you agree, you can simply click the `Commit suggestion` button and create a custom commit message like `fix: removed code tags around number`.

2020-09-24 23:25 UTC, RandellDawson commented on curriculum/challenges/english/03-front-end-libraries/react/use-proptypes-to-define-the-props-you-expect.english.md
> +  - text: The <code>Items</code> component should include a <code>propTypes</code> check to require a value for <code>quantity</code> and ensure that its value is a <code>number</code>.
"number" should not have code tags around it.
```suggestion
  - text: The <code>Items</code> component should include a <code>propTypes</code> check to require a value for <code>quantity</code> and ensure that its value is a number.
```

2020-09-25 05:48 UTC, walterpalagi commented
Done!

2020-09-25 05:49 UTC, RandellDawson approved these changes
LGTM

2020-09-25 05:50 UTC, nhcarrigan approved these changes
LGTM! 🥳

2020-09-25 06:11 UTC, merged

2020-09-25 06:11 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉