fix(learn) : Updated the regex in test
freeCodeCamp/freeCodeCamp pull request #39701
Opened 2020-09-27 06:55 UTC by mainak-debnath

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39687 

Updated the regex in test so that the function also work with negative numbers.

2020-09-27 17:53 UTC, nhcarrigan approved these changes, later dismissed
LGTM~! 🥳 

Thank you for your contributions to freeCodeCamp!

2020-09-27 18:33 UTC, Sky020 requested changes
There is no need to check for spaces if we use `replace` on the code. Also, `\d` is clear enough.

2020-09-27 18:33 UTC, Sky020 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments.english.md
> +    testString: assert(/functionWithArgs\s*\(\s*[-+]?[0-9]*\.?[0-9]*.\s*,\s*[-+]?[0-9]*\.?[0-9]*.\s*\)\s*/.test(code.replace(/\s/g, '')));
```suggestion
    testString: assert(/functionWithArgs\([-+]?\d*\.?\d*.,[-+]?\d*\.?\d*.\)/.test(code.replace(/\s/g, '')));
```

2020-09-27 21:25 UTC, Sky020 requested changes
Sorry, but I missed this. There is no reason for the un-escaped `.`

I could fully expect a camper to do this (and accidentally pass):
```
functionWithArgs(a, b);
```

2020-09-27 21:25 UTC, Sky020 commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/passing-values-to-functions-with-arguments.english.md
> +    testString: assert(/functionWithArgs\([-+]?\d*\.?\d*.,[-+]?\d*\.?\d*.\)/.test(code.replace(/\s/g, '')));
```suggestion
    testString: assert(/functionWithArgs\([-+]?\d*\.?\d*,[-+]?\d*\.?\d*\)/.test(code.replace(/\s/g, '')));
```

2020-09-28 01:17 UTC, mainak-debnath commented
@Sky020 Is this ok?

2020-09-28 09:19 UTC, Sky020 approved these changes
Thanks for that, @mainak-debnath . This LGTM 👍

2020-09-28 14:55 UTC, nhcarrigan approved these changes
LGTM! 🥳 

Thank you for contributing to freeCodeCamp!

2020-09-28 15:03 UTC, merged

2020-09-28 15:04 UTC, Sky020 commented
@mainak-debnath , for this pull request (PR)! 

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝