feat(learn): migrate instructions from adnode boilerplate
freeCodeCamp/freeCodeCamp pull request #39791
Opened 2020-10-03 13:29 UTC by Sky020

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39720

Boilerplate PR: https://github.com/freeCodeCamp/boilerplate-advancednode/pull/15

I tried as much as possible to not change unrelated content, but I also took the opportunity to change the instructions with previously discussed versioning additions, and formatting to use GitHub Flavoured MD.

2020-10-06 16:11 UTC, moT01 approved these changes, later dismissed
LGTM 🎉

2020-10-07 00:49 UTC, RandellDawson requested changes
See my one suggestion that seems to make the sentence more readable.

2020-10-07 00:49 UTC, RandellDawson commented on curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/how-to-put-a-profile-together.md
> +Pass the object containing the variable `username` equaling `req.user.username` into the render method of the profile view. Then, go to your `profile.pug` view, and add the following line below the e
```suggestion
Pass an object containing the property `username` and value of `req.user.username` as the second argument for the render method of the profile view. Then, go to your `profile.pug` view, and add the following line below the existing `h1` element, and at the same level of indentation:
```

2020-10-07 10:23 UTC, Sky020 commented
@RandellDawson Thanks, for that. It is much clearer.

2020-10-14 20:33 UTC, RandellDawson approved these changes

2020-10-14 20:34 UTC, RandellDawson commented
@moT01 I believe this PR combined with the boilerplate PR referenced in the PR body are good to go.  We can merge this and then merge the boilerplate once these changes hit production.

2020-10-15 14:37 UTC, moT01 approved these changes
👍 🎉 🚀 @Sky020

2020-10-15 14:37 UTC, merged