fix(learn): update helmet and bcrypt instructions so we can remove them from boilerplates
freeCodeCamp/freeCodeCamp pull request #39954
Opened 2020-10-12 04:09 UTC by moT01

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39720

2020-10-12 17:00 UTC, Sky020 commented
Tom, is this a work-in-progress?

I would have expected all of the information that was in the boilerplate to be ported over to the relevant lessons (eg):
```
/** 5) Avoid inferring the response MIME type - `helmet.noSniff()` */

// Browsers can use content or MIME sniffing to override response `Content-Type`
// headers to guess and process the data using an implicit content type.
// While this can be convenient in some scenarios, it can also lead to
// some dangerous attacks.
// This middleware sets the X-Content-Type-Options header to `nosniff`,
// instructing the browser to not bypass the provided `Content-Type`.
```

2020-10-12 17:19 UTC, moT01 commented
Nice catch - I think that sounds a little better, I'll update the PR to the main repo.

2020-10-22 21:37 UTC, Sky020 requested changes
Minor filename mention change.

Second comment I leave up to you, but the description does already mention the new project starter code. If you think this is a useful statement to ensure campers do not get confused, then dismiss this suggestion.

After this, this PR looks good.

2020-10-22 21:37 UTC, Sky020 commented on curriculum/challenges/english/09-information-security/information-security-with-helmetjs/install-and-require-helmet.md
> +All your code for these lessons goes in the `myapp.js` file between the lines of code we have started you off with. Do not change or delete the code we have added for you.
```suggestion
All your code for these lessons goes in the `myApp.js` file between the lines of code we have started you off with. Do not change or delete the code we have added for you.
```

2020-10-22 21:37 UTC, Sky020 commented on curriculum/challenges/english/09-information-security/information-security-with-helmetjs/understand-bcrypt-hashes.md
> +Remember that this is using a new boilerplate. Add all your code for these lessons in the `server.js` file between the code we have started you off with. Do not change or delete the code we have adde
```suggestion
Add all your code for these lessons in the `server.js` file between the code we have started you off with. Do not change or delete the code we have added for you.
```

2020-10-26 18:46 UTC, Sky020 approved these changes
LGTM 👍

2020-11-05 03:11 UTC, RandellDawson approved these changes
LGTM

2020-11-05 03:11 UTC, merged

2020-11-05 03:11 UTC, RandellDawson commented
Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉