feat(learn): migrate mongodb-mongoose instructions to learn
freeCodeCamp/freeCodeCamp pull request #39970
Opened 2020-10-13 18:44 UTC by Sky020

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related to: #39720 

The only adjustments to the tests made are superficial.

Linked to boilerplate:

2020-10-20 16:01 UTC, Sky020 commented on curriculum/challenges/english/05-apis-and-microservices/mongodb-and-mongoose/install-and-set-up-mongoose.md
> +Add mongodb and mongoose to the project’s `package.json`. Then, require mongoose in `myApp.js`. Store your MongoDB Atlas database URI in the private `.env` file as `MONGO_URI`. Surround the the URI w
```suggestion
Add `mongodb` and `mongoose` to the project’s `package.json`. Then, require mongoose as `mongoose` in `myApp.js`. Store your MongoDB Atlas database URI in a private `.env` file as `MONGO_URI`. Surround the the URI with single or double quotes, and make sure no space exists between both the variable and the `=`, and the value and `=`. Connect to the database using the following syntax:
```

2020-10-26 19:25 UTC, moT01 approved these changes, later dismissed
I am going to approve this since the PR does what it's supposed to do - moves any instructions from the boilerplate to here. But I really think they could use some help. The second lesson really got me lost. Perhaps something for another PR. Did you go through these at all @Sky020? Any thoughts on that.

2020-10-26 19:39 UTC, Sky020 commented
> The second lesson really got me lost. Perhaps something for another PR. Did you go through these at all @Sky020? Any thoughts on that.

@moT01 The _Create a Model_ lesson? To be honest, I cannot remember how much of this I went through, but nothing has changed...The camper is still required to go to the Mongoose docs to see how to structure a schema.

I suppose this line could be changed from:
> Now, create a model called `Person` from the `personSchema`.

To:
> Now, use the `Person` variable to create a model from the `personSchema` as per the documentation.

2020-11-03 02:02 UTC, RandellDawson requested changes
@Sky020 Just a few suggestions and then in future PRs, we can clean up the verbiage of a few of the challenges a bit more.

2020-11-03 13:25 UTC, RandellDawson approved these changes

2020-11-03 13:30 UTC, RandellDawson commented
@moT01 If you are ok with this PR, go ahead and merge it.  I already approved https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/31.

2020-11-03 14:22 UTC, moT01 approved these changes
Thanks for working on this @Sky020 🎉

2020-11-03 14:22 UTC, merged