Adjust user stories, add instructions
freeCodeCamp/freeCodeCamp pull request #40218
Opened 2020-11-11 17:59 UTC by nhcarrigan

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related #39721 

* Modifies verbiage to use second person
* Adds standard description
* Brings instructions over from boilerplate readme

2020-11-11 23:14 UTC, RandellDawson requested changes
@nhcarrigan When I look at the boilerplate, I can not tell how many tests there need to be.  There are not `test('test text', function(done) { })` as there are in other boilerplates.  Can the boilerplates be changes to explain what test to write like is done in PR https://github.com/freeCodeCamp/freeCodeCamp/pull/39976 ?

2020-11-11 23:42 UTC, nhcarrigan commented
Should be fixed 🙂

2020-11-19 16:41 UTC, RandellDawson commented on curriculum/challenges/english/09-information-security/information-security-projects/stock-price-checker.md
> +- Clone <a href='https://github.com/freeCodeCamp/boilerplate-project-stockchecker/'>this GitHub repo</a> and complete your project locally.
```suggestion
- Clone <a href='https://github.com/freeCodeCamp/boilerplate-project-stockchecker/' target='_blank'>this GitHub repo</a> and complete your project locally.
```

2020-11-20 20:26 UTC, moT01 submitted a review, later dismissed
I think I'm fine with this - LGTM 🎉

2020-11-25 10:55 UTC, Sky020 requested changes
This does not have to do with your PR, but is an issue with the tests/user story not matching.

2020-11-25 10:55 UTC, Sky020 commented on curriculum/challenges/english/09-information-security/information-security-projects/stock-price-checker.md
> +  - text: The `stockData` property includes the `stock` ticker as a string, the `price` (decimal in string format), and `likes` as a number.
```suggestion
  - text: The `stockData` property includes the `stock` ticker as a string, the `price` as a number, and `likes` as a number.
```

2020-11-25 16:42 UTC, Sky020 approved these changes
Thanks, Nicholas. LGTM 👍 

@moT01 Tom, if you are still happy with this, I am.

2020-11-25 17:16 UTC, RandellDawson approved these changes

2020-11-25 17:54 UTC, moT01 approved these changes
LGTM 🎉 

Side note:
Seems like we could use a heading on most of these projects here...
![Screen Shot 2020-11-25 at 11 26 59 AM](https://user-images.githubusercontent.com/20648924/100264568-9d4f3f80-2f14-11eb-9413-e7b77387b743.png)

It kind of abruptly gets into the instructions - maybe simply `Instructions` or `Complete the following in the boilerplate:`

Certainly something for another issue though - maybe I'll make one. Thanks for the work and reviews on this everyone 🎉

2020-11-25 17:55 UTC, merged