#40220 Bug(learn) - List item's font size larger than surrounding text
freeCodeCamp/freeCodeCamp pull request #40224
Opened 2020-11-12 12:29 UTC by prolland006

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-11-12 12:39 UTC, ieahleen commented
Thank you for your PR, but please go through the checklist, and add the issue number fixed by this PR

2020-11-12 13:36 UTC, prolland006 commented
#40220 Bug(learn) - List item's font size larger than surrounding text

2020-11-12 16:15 UTC, RandellDawson commented
@prolland006 Please read our [contributing documentation](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=proposing-a-pull-request), specifically item number 4.

2020-11-13 14:22 UTC, moT01 submitted a review, later dismissed
Thanks for the PR @prolland006 🎉 For future reference, it's also best to start your branch with one of things described under [#3 here](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally). You can just leave this one though.

I'm fine with these changes - this group of styles could possibly go in [the description component css](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/client/src/templates/Challenges/components/challenge-description.css) instead of here. It works either way, but I do think that file is a little more appropriate - so if you want to move them there, you can @prolland006 - or you can just leave it and we'll see what another reviewer thinks.

2020-11-13 17:19 UTC, prolland006 commented
@moT01 I did your modification : change the place of css.

2020-11-13 17:42 UTC, moT01 approved these changes, later dismissed
LGTM 🎉

2020-11-13 17:55 UTC, nhcarrigan requested changes
Heya @prolland006~!

Thank you for your contribution - I've got one slight change to add.

2020-11-13 17:55 UTC, nhcarrigan commented on client/src/templates/Challenges/components/challenge-description.css
> +}
```suggestion
#description p,
#instructions p,
#description ul,
#instructions ul {
  font-family: 'Lato', sans-serif;
}
```
If we are going this route, we need to also set this for the instructions section as well.

2020-11-13 18:30 UTC, RandellDawson requested changes, later dismissed
@nhcarrigan Can you change your suggestion to also include `#description ol` and `#instructions ol` to be able to properly display projects like the `Personal Library`, so:

![image](https://user-images.githubusercontent.com/5313213/99107725-22dd0200-259b-11eb-9b9b-5ea4e83eb7fe.png)


becomes:

![image](https://user-images.githubusercontent.com/5313213/99107770-2ff9f100-259b-11eb-8975-da13833cf281.png)

2020-11-13 18:31 UTC, nhcarrigan commented
Updated 🙂

2020-11-13 18:32 UTC, RandellDawson commented
> Updated

You beat me to it.

2020-11-13 19:11 UTC, RandellDawson commented
@prolland006 If you can make the suggested change, we can get this PR merged.  Thanks.

2020-11-13 19:27 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

Please note that our workflow requires at least one additional approving review before this can be merged.

2020-11-13 19:55 UTC, moT01 approved these changes
LGTM 🎉 Thanks for fixing this issue @prolland006 and congratulations on your first contribution to this repo 🎉

2020-11-13 19:56 UTC, merged