fixed issue offline warning message is hard to read in dark mode
freeCodeCamp/freeCodeCamp pull request #40237
Opened 2020-11-15 14:59 UTC by nullaf

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40193

2020-11-15 16:02 UTC, nhcarrigan requested changes
This should be kept in one div, not a nested div, I believe.

2020-11-15 16:02 UTC, nhcarrigan commented on client/src/components/OfflineWarning/OfflineWarning.js
>      <div className='offline-warning'>
```suggestion
    <div className='offline-warning alert-info'>
```

2020-11-15 16:02 UTC, nhcarrigan commented on client/src/components/OfflineWarning/OfflineWarning.js
> +      </div>
```suggestion
      You appear to be offline, your progress may not be being saved.
```

2020-11-15 16:37 UTC, nhcarrigan approved these changes
LGTM~! Pulled this down locally, tested the offline notice. Contrast is at 4.53 now, which puts it within AA standard.

Congratulations on your first pull request~! We look forward to future contributions!

Please note that our workflow requires at least one additional approval before this can be merged. 

Additionally, I recommend reviewing our [contributing guidelines](https://contribute.freecodecamp.org), specifically the section regarding creating a new branch for your work - it is, in general, a good idea to keep your `master` branch clean. 🙂

2020-11-16 11:31 UTC, ahmadabdolsaheb approved these changes

2020-11-16 11:32 UTC, merged