type checking and additional test for isBalanced binary search tree
freeCodeCamp/freeCodeCamp pull request #40323
Opened 2020-11-26 12:43 UTC by ngschaider

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

This bug was introduced in PR #35033
Since the according pull request got merged the tested isBalanced method can be empty and the test would pass (empy function without return statement returns `undefined` which is falsy).

I essentially changed the comparison of the returned value from `!testedFunction()` to `testedFuntion() === false` which enforces testedFunction to return false in order for the test to pass.

I also added another test with a balanced binary search tree where the result of the function has to be true.

2020-11-26 16:20 UTC, nhcarrigan requested changes, later dismissed
Hello~!

The solution code does not pass these changes for me (locally), but the solution provided in the forum post does. I'm not sure if this is an error on my end or if the challenge solution needs an update.

One slight nitpick: can we wrap the Booleans in the test string in code blocks?

2020-11-26 16:20 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/find-the-minimum-and-maximum-height-of-a-binary-search-tree.md
> +  - text: The <code>isBalanced</code> method should return false if the tree is an unbalanced binary search tree.
```suggestion
  - text: The <code>isBalanced</code> method should return <code>false</code> if the tree is an unbalanced binary search tree.
```

2020-11-26 16:20 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/find-the-minimum-and-maximum-height-of-a-binary-search-tree.md
>    - text: The <code>isBalanced</code> method should return true if the tree is a balanced binary search tree.
```suggestion
  - text: The <code>isBalanced</code> method should return <code>true</code> if the tree is a balanced binary search tree.
```

2020-11-26 18:03 UTC, RandellDawson commented
I checked both the forum guide solution and the solution in the challenge file locally and both with the proposed changes of this PR.

2020-11-26 18:25 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

As a note: Our workflow requires at least one additional approving review before this can be merged.

(Yes, the error with the challenge seed was an nhcarrigan error - grabbed the solution code from a similarly named challenge by accident 😅 )

2020-11-27 04:33 UTC, moT01 approved these changes
LGTM @ngschaider 🎉 Congratulations on your first contribution to this freeCodeCamp repository 🎉 We welcome future contributions 😄

2020-11-27 04:33 UTC, merged