feat(curriculum): add extension tests for css-flexbox curriculum modules
freeCodeCamp/freeCodeCamp pull request #40473
Opened 2020-12-17 14:51 UTC by luqven

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #39608

Replaces #40272

Changes:

Adds a test that validates the presence of `follow-btn` on the page and that its display property is not set to `none` to the following:

- css-flexbox/add-flex-superpowers-to-the-tweet-embed.md
- css-flexbox/apply-the-flex-direction-property-to-create-a-column-in-the-tweet-embed.md
- css-flexbox/apply-the-flex-direction-property-to-create-rows-in-the-tweet-embed.md
- css-flexbox/use-the-align-items-property-in-the-tweet-embed.md
- css-flexbox/use-the-justify-content-property-in-the-tweet-embed.md

2020-12-17 16:48 UTC, nhcarrigan requested changes
Our challenge template has changed - since the test runner is no longer using `YAML` strings, we do not need the `testString` property any more. 🙂

2020-12-17 16:48 UTC, nhcarrigan commented on curriculum/challenges/english/01-responsive-web-design/css-flexbox/add-flex-superpowers-to-the-tweet-embed.md
> +testString: assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```suggestion
assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```

2020-12-17 16:48 UTC, nhcarrigan commented on curriculum/challenges/english/01-responsive-web-design/css-flexbox/apply-the-flex-direction-property-to-create-a-column-in-the-tweet-embed.md
> +testString: assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```suggestion
assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```

2020-12-17 16:48 UTC, nhcarrigan commented on curriculum/challenges/english/01-responsive-web-design/css-flexbox/apply-the-flex-direction-property-to-create-rows-in-the-tweet-embed.md
> +testString: assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```suggestion
assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```

2020-12-17 16:48 UTC, nhcarrigan commented on curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-align-items-property-in-the-tweet-embed.md
> +testString: assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```suggestion
assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```

2020-12-17 16:48 UTC, nhcarrigan commented on curriculum/challenges/english/01-responsive-web-design/css-flexbox/use-the-justify-content-property-in-the-tweet-embed.md
> +testString: assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```suggestion
assert($('.follow-btn').length > 0 && $('.follow-btn').css('display') !== 'none');
```

2020-12-17 18:23 UTC, luqven commented
> Our challenge template has changed - since the test runner is no longer using `YAML` strings, we do not need the `testString` property any more. 🙂

thanks ❤️ , still getting used to the changes 🤦🏼. Committed your suggestions.

2020-12-17 19:13 UTC, RandellDawson commented
@luqven FYI - You can test that a challenge passes all the tests by performing the following commands locally:
```bash
cd curriculum
npm run test -- -g 'title of challenge'
```
If all the tests pass, you at least know pushing the changes should not fail for that reason.

2021-01-12 17:51 UTC, lasjorg commented
@nhcarrigan is anything still blocking this?

@luqven I would prefer if this didn't close the issue. I'm not convinced we have found the right solution for the issues with dark mode extensions and the color challenges.

2021-01-12 17:53 UTC, nhcarrigan commented
Yes, we are still in a code freeze and are not merging any PRs to challenge files at this time. 🙂

2021-01-13 21:12 UTC, lasjorg commented
@nhcarrigan Thanks for pinning the code freeze issue again.

2021-01-14 22:13 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Note: In order to test this, I had to force my ad-blocker to hide the element with a custom filter:
![image](https://user-images.githubusercontent.com/63889819/104655560-bb166680-5672-11eb-8e19-05adbada5f2e.png)


Thank you for your pull request! We look forward to additional contributions! 

Please note that we are currently in a code freeze and are not merging PRs to curriculum files for the time being.

2021-01-14 22:15 UTC, nhcarrigan commented
> I would prefer if this didn't close the issue. I'm not convinced we have found the right solution for the issues with dark mode extensions and the color challenges.

I agree. I went ahead and edited the PR to remove that link.

2021-01-15 23:26 UTC, nhcarrigan requested changes
Hey @luqven,

Actually, would you mind moving these tests to the top of each file's test suites? That way, if a camper has the correct code but is failing due to an extension, this test will be the first thing they see in the console.

2021-01-31 16:06 UTC, RandellDawson commented
@luqven It has been a while since we last heard from you.  To get this PR merged, can you please make the changes last requested by @nhcarrigan?

Thank you.

2021-02-01 07:58 UTC, raisedadead commented
Hey @nhcarrigan is this additional review something that we could take up ourselves in interest of time. We are going to be doing a head branch rename and would like to merge any PRs we absolutely can

2021-02-01 12:24 UTC, nhcarrigan commented
Yes we can absolutely handle the changes ourselves.🙂

2021-02-01 12:33 UTC, luqven commented
Hey all, apols for the delay. This got drowned out in hundred of notifications.

I can have this in after 5 pm est today. But please feel free to take it off my hands if need be.

2021-02-01 14:15 UTC, raisedadead commented
No worries @luqven we should be able to add the changes, we typically do not rush anyone. But we are in the middle of moving from `master` to `main` and hence the urgency. Nick should be able to get this in later.

Thanks for your work on the PR.

2021-02-01 14:24 UTC, nhcarrigan commented
I've gone ahead and pushed the update.

@raisedadead am I good to merge after CI passes?

2021-02-01 14:26 UTC, raisedadead commented
> am I good to merge after CI passes?

Yes.

2021-02-01 15:57 UTC, merged

2021-02-01 15:57 UTC, nhcarrigan commented
Thank you for your contribution to the project! 👍
We are happy to accept these changes and look forward to future contributions. 🎉