Changed the question to one with no ambiguity
freeCodeCamp/freeCodeCamp pull request #40488
Opened 2020-12-18 14:59 UTC by yaseen221

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2020-12-18 15:24 UTC, yaseen221 commented
This change has been discussed upon on issue #40410. This change seems the most appropriate approach to resolve the issue.

2020-12-18 16:15 UTC, ShaunSHamilton submitted a review, later dismissed
This LGTM 👍 

---

For future reference, once this is merged, your `master` branch will be spoiled, and need to be rebased. This is why we recommend you work off of a new branch for a PR, as described here: https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally

2020-12-18 16:24 UTC, yaseen221 commented
I was having trouble with my WSL2 that's why I used Gitpod. Will work off a new branch locally next time. Thanks @ShaunSHamilton

2020-12-18 16:29 UTC, ieahleen commented
@yaseen221 you can still make a beanch in gitpod, choose Terminal->Open new terminal from above and make a new branch from the terminal, and work in the new branch. GitPod is still considered "locally", even if it's a cloud environment. It's because it pollutes your github fork that you shouldn't

2020-12-18 16:40 UTC, ShaunSHamilton commented
@yaseen221 Feel free to reach out for help, if you get stuck with stuff like that on the Discord server, or on the forum. We have a few developers on these platforms who use WSL2 for freeCodeCamp deving.

2020-12-18 17:05 UTC, nhcarrigan requested changes
This is very much a nitpick, but can we correct the casing on `Markdown`? 🙂

2020-12-18 17:05 UTC, nhcarrigan commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/jupyter-notebooks-cells.md
> +Code, MarkDown, and Python
```suggestion
Code, Markdown, and Python
```

2020-12-18 17:05 UTC, nhcarrigan commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/jupyter-notebooks-cells.md
> +Code, MarkDown, and Raw
```suggestion
Code, Markdown, and Raw
```

2020-12-18 17:05 UTC, nhcarrigan commented on curriculum/challenges/english/08-data-analysis-with-python/data-analysis-with-python-course/jupyter-notebooks-cells.md
> +MarkDown, Python, and Raw
```suggestion
Markdown, Python, and Raw
```

2020-12-18 17:18 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions! Please note that we are in a code freeze at the moment, and merging will have to wait until that is lifted.

@ShaunSHamilton if you are still happy with these changes, would you mind reapproving? 🙂

2020-12-18 19:22 UTC, ShaunSHamilton approved these changes
LGTM 👍 

Thanks, for catching the name, @nhcarrigan . I had always thought it was _MarkDown_...

2020-12-18 19:40 UTC, nhcarrigan commented
I wasn't sure, myself. I did some extensive searching, though, and it seems all the primary documentation refers to it as `Markdown`.

2021-01-21 05:00 UTC, merged

2021-01-21 05:00 UTC, RandellDawson commented
Congrats @yaseen221 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝