Text in Basic Data Structures lesson is better clarified.
freeCodeCamp/freeCodeCamp pull request #40492
Opened 2020-12-19 18:55 UTC by GJ-16

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `master` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40412

2020-12-20 12:24 UTC, ShaunSHamilton requested changes
Nitpick

2020-12-20 12:24 UTC, ShaunSHamilton commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-data-structures/add-items-using-splice.md
> +Here we begin with an array of numbers. We then pass the following to splice(). The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the remaining argument
```suggestion
Here, we begin with an array of numbers. Then, we pass the following to `splice()`: The index at which to begin deleting elements (3), the number of elements to be deleted (1), and the remaining arguments (13, 14) will be inserted starting at that same index. Note that there can be any number of elements (separated by commas) following `amountToDelete`, each of which gets inserted.
```

2020-12-20 12:58 UTC, ShaunSHamilton approved these changes
This LTGM 👍 

Thank you, for this PR, and congrats on your first PR to this repo. We look forward to future contributions.

2020-12-20 13:36 UTC, GJ-16 commented
@ShaunSHamilton Thank you.
What is LTGM?

2020-12-20 14:07 UTC, ieahleen commented
@GJ-16 it's "Looks Good To Me"

2020-12-20 14:11 UTC, ShaunSHamilton commented
@GJ-16 Haha, it was a typo on my  part. As @ieahleen said, LGTM

2020-12-20 14:15 UTC, GJ-16 commented
I didn't know, I Googled and google said "Long Term Growth Model". So I was confused.

2020-12-20 16:28 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

Please note that we are currently in a code freeze, so this cannot be merged until the freeze is lifted. 🙂

2020-12-20 17:30 UTC, GJ-16 commented
@nhcarrigan Thanks so much, Thanks for the information mate.

2021-01-21 05:02 UTC, merged

2021-01-21 05:02 UTC, RandellDawson commented
Congrats @J-16 on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝