translated comments to Chinese
freeCodeCamp/freeCodeCamp pull request #40526
Opened 2020-12-23 13:40 UTC by miyaliu666

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

2020-12-23 14:08 UTC, RandellDawson requested changes
See my suggested change.  You can click "Commit suggestion" and add an applicable commit message.

2020-12-23 14:08 UTC, RandellDawson commented on curriculum/dictionaries/chinese/comments.js
> +    text: '应该显示 'carrot''
Because the string contains `'`, the entire string needs to be wrapped in double quotes.
```suggestion
    text: "应该显示 'carrot'"
```

2020-12-24 20:18 UTC, RandellDawson requested changes
@nhcarrigan Can you commit these changes on behalf of @miyaliu666 ?

2020-12-24 20:18 UTC, RandellDawson commented on curriculum/dictionaries/chinese/comments.js
> +    text: '现在，在 console.log() 之前添加 console.clear()，清除浏览器控制台的内容，通过测试。'
```suggestion
    text:
      '现在，在 console.log() 之前添加 console.clear()，清除浏览器控制台的内容，通过测试。'
```

2020-12-24 20:18 UTC, RandellDawson commented on curriculum/dictionaries/chinese/comments.js
> +    text: '检查两个控制台的差异。freeCodeCamp 控制台应该打印两次变量，分别对应这个挑战的每一个测试。浏览器控制台应该只打印一次变量，因为你清除了第一次的打印结果。'
```suggestion
    text:
      '检查两个控制台的差异。freeCodeCamp 控制台应该打印两次变量，分别对应这个挑战的每一个测试。浏览器控制台应该只打印一次变量，因为你清除了第一次的打印结果。'
```

2020-12-24 20:18 UTC, RandellDawson commented on curriculum/dictionaries/chinese/comments.js
> +    text: '有一个函数（代表茶的种类）和需要几杯茶，下面的函数返回一个数组，包含字符串（每个字符串表示一杯特别种类的茶）。'
```suggestion
    text:
      '有一个函数（代表茶的种类）和需要几杯茶，下面的函数返回一个数组，包含字符串（每个字符串表示一杯特别种类的茶）。'
```

2020-12-28 12:47 UTC, raisedadead approved these changes

2020-12-28 12:48 UTC, merged