Clarify sudoku solver instructions
freeCodeCamp/freeCodeCamp pull request #40604
Opened 2021-01-02 06:11 UTC by vicky11z

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40413

Tested locally, here is what it looks like:
<img width="800" alt="Screen Shot 2021-01-01 at 10 10 22 PM" src="https://user-images.githubusercontent.com/4792589/103451886-4c063e80-4c7e-11eb-9442-4c51c63e6a92.png">

2021-01-02 17:44 UTC, nhcarrigan requested changes

2021-01-02 17:44 UTC, nhcarrigan commented on curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/sudoku-solver.md
>  -   All routing logic can go into `/routes/api.js`
```suggestion
-   All puzzle logic can go into `/controllers/sudoku-solver.js`
  - The `validate` function should take a given puzzle string and check it to see if it has 81 valid characters for the input.
  - The `check` functions should be validating against the *current* state of the board.
  - The `solve` function should handle solving any given valid puzzle string, not just the test inputs and solutions. You are expected to write out the logic to solve this.
-   All routing logic can go into `/routes/api.js`
```
This should correct the linting issue. 🙂

2021-01-02 18:49 UTC, RandellDawson commented
I honestly had not noticed the new parser makes the lists indented by 4.  However, if we change the entire `Instructions`section to the following, it looks as intended and the linter no longer complains.
```markdown
- All puzzle logic can go into `/controllers/sudoku-solver.js`
- The `validate` function should take a given puzzle string and check it to see if it has 81 valid characters for the input.
  - The `check` functions should be validating against the *current* state of the board.
  - The `solve` function should handle solving any given valid puzzle string, not just the test inputs and solutions. You are expected to write out the logic to solve this.
- All routing logic can go into `/routes/api.js`
- See the `puzzle-strings.js` file in `/controllers` for some sample puzzles your application should solve
- To run the challenge tests on this page, set `NODE_ENV` to `test` without quotes in the `.env` file
- To run the tests in the console, use the command `npm run test`. To open the Repl.it console, press Ctrl+Shift+P (Cmd if on a Mac) and type "open shell"
- ```

2021-01-05 01:12 UTC, vicky11z commented
Thanks for taking a look! I took @RandellDawson 's recommendation since when I just tried to decrease the spaces down to 2, the instructions I added were no longer at the correct indentation level.

2021-01-15 22:08 UTC, RandellDawson approved these changes
LGTM

@nhcarrigan What do you think?

2021-01-15 22:15 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

Please note that we are currently in a code freeze and are not merging PRs to curriculum lessons for the time being. 🙂

2021-01-16 19:58 UTC, merged