fix(learn): correct LCG equation in description
freeCodeCamp/freeCodeCamp pull request #40615
Opened 2021-01-03 23:52 UTC by leungkimho

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

In the Rosetta Code: Linear congruential generator (LCG), the equation for the LCG in the description is difficult to interpret for order of operations.  While working through the challenge, I interpreted the equation from the description as r(n+1) = (a * r(n)) + (c * mod m).

Correcting parentheses in markdown to reflect operator precedence and be consistent with references.

- [Wikipedia article referenced from challenge](https://en.wikipedia.org/wiki/Linear_congruential_generator)
- [Assignment in COS126 course from Princeton](https://www.cs.princeton.edu/courses/archive/spring03/cs126/assignments/cycle.html)

2021-01-05 13:14 UTC, ShaunSHamilton requested changes
I was not a fan of the missing argument in the `\mod` operator. This fixes that. Otherwise, typically, we do not take PRs with changes to both languages - for this case of an equation change, I can understand it being an exception, but I will defer to others for confirmation.

@RandellDawson Is it alright for this type of change to be done to both the Chinese and English in this PR?

2021-01-05 13:14 UTC, ShaunSHamilton commented on curriculum/challenges/chinese/10-coding-interview-prep/rosetta-code/linear-congruential-generator.md
> +$$r_{n + 1} = (a \times r_n + c)\mod m$$
```suggestion
$$r_{n + 1} = (a \times r_n + c) \bmod m$$
```

2021-01-05 13:14 UTC, ShaunSHamilton commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/linear-congruential-generator.md
> +$$r_{n + 1} = (a \times r_n + c)\mod m$$
```suggestion
$$r_{n + 1} = (a \times r_n + c) \bmod m$$
```

2021-01-05 17:14 UTC, leungkimho commented
@ShaunSHamilton Thanks for those changes!  I wasn't familiar with Markdown enough to figure out why the large space was still there.

Some context on why I made the changes to both languages, but of course make any changes necessary to keep with the development process:
- I'm assuming that the language of equations is universal.
- I checked the Chinese file and it was still in English.  I'm assuming this is awaiting translation,, so I was thinking about maintaining consistency across the files.

Still new to GitHub and haven't gotten this far as to having a discussion and making changes, so please let me know if there were any procedural things I made mistakes on.  Thanks!

2021-01-05 18:42 UTC, RandellDawson commented
> @RandellDawson Is it alright for this type of change to be done to both the Chinese and English in this PR?

Yes but the only reason is that the change is not something that would require a translation.

2021-01-05 18:52 UTC, ShaunSHamilton submitted a review, later dismissed
This LGTM 👍 

Thank you, for making this change.

2021-01-15 20:10 UTC, RandellDawson submitted a review, later dismissed
@leungkimho Since I last commented, we have started no longer accepting curriculum-related PRs with changes to non-English files.  The other languages will get the translated content from another source.  So can you please revert the change to the Chinese file?  Thank you.

2021-01-16 03:01 UTC, leungkimho reviewed
No worries!  There should be a new commit with the Chinese file reverted back.  Let me know if I did that correctly and if you need anything else.

2021-01-16 11:05 UTC, ShaunSHamilton approved these changes
This LGTM 👍

2021-01-21 06:04 UTC, nhcarrigan approved these changes
LGTM~! 🥳 Pulled down locally, KaTeX renders correctly, formula matches the Wikipedia example.

Thank you for your pull request! We look forward to additional contributions!

2021-01-21 06:05 UTC, merged

2021-01-21 06:07 UTC, nhcarrigan commented
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝