Add spanish translation of comments.js
freeCodeCamp/freeCodeCamp pull request #40628
Opened 2021-01-05 01:12 UTC by itsMeNicoG

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

I've added a spanish folder and the respective comments.js file to the curriculum/dictionaries directory.

2021-01-05 02:42 UTC, RandellDawson requested changes
@itsMeNicoG I noticed a few issues.  I documented a few words that should not have been translated.

@RafaelDavisH @raisedadead If I am not mistaken, the folder name should be `espanol` instead of `spanish`.  If so, can you reply back to this PR to let the contributor know?

Thank you.

2021-01-05 02:42 UTC, RandellDawson commented on curriculum/dictionaries/spanish/comments.js
> +      'responseFromServer es establecido a true para representar una respuesta no satisfactoria del servidor'
The English text for this key is:
> responseFromServer is set to false to represent an unsuccessful response from a server

I believe you meant to put `false` in this line:
```suggestion
      'responseFromServer es establecido a false para representar una respuesta no satisfactoria del servidor'
```

2021-01-05 02:42 UTC, RandellDawson commented on curriculum/dictionaries/spanish/comments.js
> +    text: 'Usa console.log() para imprimir la variable de salida.'
The English text for this id is:
> Use console.log() to print the output variable.

`output` is a variable name and should not be translated.

2021-01-05 02:42 UTC, RandellDawson commented on curriculum/dictionaries/spanish/comments.js
> +    text: 'Variable de conteo global:'
The English text is:
> Global count variable:

The variable named `count` should not be translated.

2021-01-05 02:42 UTC, RandellDawson commented on curriculum/dictionaries/spanish/comments.js
> +      'Define el contador reductor que aumentará o disminuirá el estado en función de la acción que reciba'
The English text is:
> Define the counter reducer which will increment or decrement the state based on the action it receives

The word `counter` should not be translated as it represents a code variable.

2021-01-05 04:15 UTC, itsMeNicoG commented
Thanks for the review. I've now corrected the variable names that were translated by mistake. I'm still waiting for confirmation on the folder's name and can update it if necessary.

2021-01-05 05:26 UTC, RafaelDavisH commented
@itsMeNicoG thanks for the quick changes. Please do change the folder to "espanol". We are following this convention for consistency. Thanks again. 🙏

2021-01-05 06:11 UTC, itsMeNicoG commented
@RafaelDavisH folder has now been renamed as required. Please let me know if there are any other changes to be made.

2021-01-05 06:44 UTC, RafaelDavisH reviewed
LGTM 🥳 Thanks for making these translations and changes @itsMeNicoG 🎉

2021-01-06 06:15 UTC, RandellDawson approved these changes

2021-01-06 06:15 UTC, RandellDawson commented
@raisedadead I am good with these changes now.

2021-01-06 06:22 UTC, merged