fix: Updated instructions for challenge #35765
freeCodeCamp/freeCodeCamp pull request #40658
Opened 2021-01-11 00:27 UTC by martinmilani

Checklist:

- [X ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X ] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #35765

Change the instructions line as suggested by @RandellDawson on https://github.com/freeCodeCamp/freeCodeCamp/issues/35765#issuecomment-739460839

2021-01-11 04:06 UTC, erictleung requested changes
Just a small comment. Otherwise, thanks for taking time to make these changes!

2021-01-11 04:06 UTC, erictleung commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups.md
> +Use capture groups in `reRegex`  to match a string that consists of only the same number repeated exactly three times separated by single spaces.
Is there a reason for this space?

```suggestion
Use capture groups in `reRegex` to match a string that consists of only the same number repeated exactly three times separated by single spaces.
```

2021-01-11 20:11 UTC, martinmilani commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/regular-expressions/reuse-patterns-using-capture-groups.md
> +Use capture groups in `reRegex`  to match a string that consists of only the same number repeated exactly three times separated by single spaces.
Just a mistake

2021-01-11 23:05 UTC, erictleung approved these changes

2021-01-15 20:03 UTC, RandellDawson approved these changes
LGTM

2021-01-21 03:39 UTC, merged