fix(learn): update seed code for D3.js challenge
freeCodeCamp/freeCodeCamp pull request #40699
Opened 2021-01-14 22:13 UTC by lucassorenson

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `master` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40685

As the issue states, this is just changing some of the comments in the challenges seed code to make the solution a bit clearer.

2021-01-14 22:44 UTC, ShaunSHamilton commented
Hey there,

Thank you, for opening this PR. For future reference, please look out more for the issues with the _help wanted_ labels, as these are the issues which have been triaged, and a course-of-action has been determined. Specifically, with this, we are keeping careful watch over the comments being used, as they need to be translated.

@RandellDawson Which exactly are the pre-approved comments to be used?

2021-01-14 22:45 UTC, nhcarrigan commented
```json
  {
    id: 'axnbgg',
    text: 'Change code above this line'
  },
  {
    id: 'i2kck7',
    text: 'Change code below this line'
  },
  {
    id: 'dlbobn',
    text: 'Change this line'
  },
  ```
  
  All three of these proposed comments are present in our dictionary. 🙂

2021-01-14 22:52 UTC, lucassorenson commented
@ShaunSHamilton Sorry, I didn't realize that! I will look out for those tags in the future.

2021-01-14 23:20 UTC, ShaunSHamilton commented
@lucassorenson Turns out, there are no changes needed 👍 

Thanks, @nhcarrigan

2021-01-15 22:18 UTC, martinmilani approved these changes, later dismissed

2021-01-21 17:47 UTC, moT01 reviewed
I'm fine with this as-is, but I'm wondering if the comments should be `Add your code above/below this line` since they are adding code and not changing it. Pretty minor, the message gets across either way.

2021-01-21 19:36 UTC, martinmilani commented
> 
> 
> I'm fine with this as-is, but I'm wondering if the comments should be `Add your code above/below this line` since they are adding code and not changing it. Pretty minor, the message gets across either way.

It seems like a more accurate approach

2021-01-22 02:27 UTC, nhcarrigan requested changes
Creating suggestions, per the discussion above.

2021-01-22 02:27 UTC, nhcarrigan commented on curriculum/challenges/english/04-data-visualization/data-visualization-with-d3/change-the-presentation-of-a-bar-chart.md
> +    /* Change code below this line */
```suggestion
    /* Add your code below this line */
```

2021-01-22 02:27 UTC, nhcarrigan commented on curriculum/challenges/english/04-data-visualization/data-visualization-with-d3/change-the-presentation-of-a-bar-chart.md
> +    /* Change code above this line */
```suggestion
    /* Add your code above this line */
```

2021-02-02 23:55 UTC, nhcarrigan commented
@lucassorenson have you had a chance to review the suggestions above?

2021-02-03 15:56 UTC, lucassorenson commented
@nhcarrigan Hey, sorry, I haven't checked back since I saw the "No further changes required" comment, so I didn't see the rest. I can go change that later today if it still needs to get done.

2021-02-03 17:01 UTC, nhcarrigan commented
Yes please - you can commit the suggestions directly through GitHub by switching the PR to `files` view, selecting `add suggestion to batch` for each relevant suggestion, then `commit suggestions`.

2021-02-05 16:28 UTC, nhcarrigan approved these changes
Looks good to me.

2021-02-10 11:36 UTC, merged