fix(learn): address escaped backticks
freeCodeCamp/freeCodeCamp pull request #40717
Opened 2021-01-16 08:26 UTC by nhcarrigan

Addresses the instances of escaped backticks - where a backtick is
preceded by a backslash.  In most cases, this was left over from the
old parser. In some cases, a backtick was intended to be wrapped in
code tags and has been adjusted accordingly.

This issue came to light due to a bug in the translation flow on
Crowdin.

Signed-off-by: nhcarrigan <nhcarrigan@gmail.com>

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `master` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2021-01-16 11:21 UTC, ojeytonwilliams reviewed
Hey Nick, I found a couple of bugs introduced by my formatter during the review.  In the general spirit of fixing bugs that it introduced, I pushed commits to deal with them.

2021-01-16 19:30 UTC, nhcarrigan commented
Hey @ojeytonwilliams can you revert the last commit?

Those funky extra backticks are actually part of the text string from Rosetta Code and should be preserved:

![image](https://user-images.githubusercontent.com/63889819/104821074-3c463880-57ee-11eb-81f4-e73fa7ccf89d.png)

2021-01-17 10:22 UTC, ojeytonwilliams requested changes
I thought that `"` was just the formatter being weird, thanks for fixing that.

2021-01-17 10:22 UTC, ojeytonwilliams commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/s-expressions.md
> +For this, the reader need not recognize "<ocde>\\</code>" for escaping, but should, in addition, recognize numbers if the language has appropriate data types.
```suggestion
For this, the reader need not recognize "<code>\\</code>" for escaping, but should, in addition, recognize numbers if the language has appropriate data types.
```

2021-01-17 17:24 UTC, nhcarrigan commented
> I thought that " was just the formatter being weird, thanks for fixing that.

Yeah it seems strange, but that's the text on the Rosetta Code page too.

2021-01-19 09:32 UTC, ojeytonwilliams approved these changes, later dismissed
LGTM :+1:

2021-01-21 01:43 UTC, RandellDawson approved these changes
@nhcarrigan Thank you for those last two commits to fix the couple of bugs that were still showing up after the original commits.  LGTM

2021-01-21 02:01 UTC, merged