Add gap script for production
freeCodeCamp/freeCodeCamp pull request #40807
Opened 2021-01-27 12:01 UTC by ahmadabdolsaheb

2021-01-28 19:46 UTC, ahmadabdolsaheb commented on client/utils/tags.js
> +    <script href={pathToGap} id='gap' key='gap' rel='stylesheet' />
```suggestion
    <script href={pathToGap} id='gap' key='gap' type='text/javascript' />
```

2021-03-31 21:18 UTC, nhcarrigan approved these changes, later dismissed
Looks good to me.

2021-04-14 08:30 UTC, ojeytonwilliams requested changes

2021-04-14 08:30 UTC, ojeytonwilliams commented on client/utils/tags.js
> +import { homeLocation } from '../../config/env.json';
```suggestion
import env from '../../config/env.json';

const { homeLocation } = env;
```
I'm not 100% sure how this interacts with Webpack (but they've [dropped support for this](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#json-modules)), so let's err on the side of caution.

2021-04-14 08:30 UTC, ojeytonwilliams commented on client/utils/tags.js
> +};
```suggestion
```
Do we just want the host?  If so, we can use the URL object.  Since it's a one-liner, I'll suggest the code below.

2021-04-14 08:30 UTC, ojeytonwilliams commented on client/utils/tags.js
> +  const parsedHomeUrl = psl.parse(urlStripper(homeLocation));
```suggestion
  const parsedHomeUrl = psl.parse(new URL(homeLocation).host);
```

2021-04-15 09:37 UTC, ojeytonwilliams approved these changes, later dismissed
LGTM :+1:

2021-04-15 12:41 UTC, ahmadabdolsaheb commented
I am just adding the Chinese and the Dev gap scripts, so we could test the script in development before it goes live. Thanks for your patience.

2021-04-16 07:26 UTC, ahmadabdolsaheb commented
@ojeytonwilliams, now it should be ready.

2021-04-16 07:36 UTC, ojeytonwilliams requested changes
Just some typos

2021-04-16 07:36 UTC, ojeytonwilliams commented on client/utils/tags.js
> +  // inject gap for developement
```suggestion
  // inject gap for staging
```
Nitpick

2021-04-16 07:36 UTC, ojeytonwilliams commented on client/utils/tags.js
> +  // inject gap all production languages exept Chinese
```suggestion
  // inject gap all production languages except Chinese
```
Nitipick

2021-04-16 07:45 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-04-16 08:59 UTC, raisedadead approved these changes

2021-04-16 08:59 UTC, merged