update(curriculum): explicitise use-the-env-file
freeCodeCamp/freeCodeCamp pull request #40898
Opened 2021-02-03 19:00 UTC by ShaunSHamilton

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

As is. Finally pushed me over the edge - campers misunderstanding the `.env` file.

2021-02-03 19:23 UTC, nhcarrigan requested changes
One very small nitpick - otherwise, looks good to me.

2021-02-03 19:23 UTC, nhcarrigan commented on curriculum/challenges/english/05-apis-and-microservices/basic-node-and-express/use-the-.env-file.md
> +Create a `.env` file in the root of your project directory, and store the variable `MESSAGE_STYLE=uppercase` in it. Then, in the GET `/json` route handler that you created in the last challenge trans
```suggestion
Create a `.env` file in the root of your project directory, and store the variable `MESSAGE_STYLE=uppercase` in it. Then, in the GET `/json` route handler that you created in the last challenge, transform the response object’s message to uppercase if `process.env.MESSAGE_STYLE` equals `uppercase`. The response object should become `{"message": "HELLO JSON"}`.
```
Nitpick.

2021-02-03 19:31 UTC, nhcarrigan approved these changes

2021-02-04 18:32 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-02-04 18:43 UTC, merged