fix: show username on cert if name is private
freeCodeCamp/freeCodeCamp pull request #40897
Opened 2021-02-03 18:33 UTC by moT01

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #40765

2021-02-03 19:04 UTC, ShaunSHamilton commented
Ideally, should we be **not** even fetching `cert.name`, if `showName` is false?

2021-02-03 20:44 UTC, moT01 commented
Good call @ShaunSHamilton 👍 - I think I fixed it.

2021-02-03 22:31 UTC, ShaunSHamilton requested changes
Small change, just because I like this wherever I can.

2021-02-03 22:31 UTC, ShaunSHamilton commented on client/src/client-only-routes/ShowCertification.js
> +  const displayName = userFullName ? userFullName : username;
```suggestion
  const displayName = userFullName ?? username;
```

2021-02-04 08:00 UTC, raisedadead approved these changes

2021-02-04 08:00 UTC, merged