Removed outline: none on Menu button
freeCodeCamp/freeCodeCamp pull request #40914
Opened 2021-02-04 17:27 UTC by Sembauke

Removed outline: none on  MenuButton so the outline becomes visible when pressing Tab.  Ref issue #40873.

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2021-02-05 05:20 UTC, raisedadead reviewed
I am not sure if this addresses the issue the a11y entirely?

2021-02-05 09:02 UTC, Sembauke commented
> I am not sure if this addresses the a11y issue entirely?

I Don't understand what you mean?

2021-02-05 11:06 UTC, ShaunSHamilton requested changes
I think we are looking more for:
```css
.toggle-button-nav:focus {
    outline: 5px auto -webkit-focus-ring-color !important;
    outline-offset: -3px;
}
```
As this will match the look of the Sign-in button.
---
I have removed the mention of this PR _closing_ the issue, as something still needs to be done (and we have not decided yet) about the certificate widget.

2021-02-05 19:05 UTC, raisedadead commented
@Sembauke if you get a chance can you update the PR with the recommend css changes mentioned above, as for the other issues we can leave it open for discussion.

Thanks for your work on this.

2021-02-05 21:07 UTC, Sembauke commented
> @Sembauke if you get a chance can you update the PR with the recommend css changes mentioned above, as for the other issues we can leave it open for discussion.
> 
> Thanks for your work on this.

No problem! I am new to GitHub and I am loving the kind support my first PR is getting

2021-02-05 21:51 UTC, nhcarrigan approved these changes
Looks good to me. Resolves the issue with keyboard focus.

As an aside, the outline appears when the dropdown is enabled - seems a bit odd, but I can live with it.

Keyboard Focus:

![image](https://user-images.githubusercontent.com/63889819/107092842-18589000-67b9-11eb-813a-8709800ca3a6.png)

On-Click: 
![image](https://user-images.githubusercontent.com/63889819/107092873-23132500-67b9-11eb-96a7-2c754d176d31.png)

2021-02-06 09:37 UTC, merged

2021-02-06 09:38 UTC, raisedadead commented
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @Sembauke, for this pull request and contributing to the code-base for the first time.

We will be looking forward for more contributions in future.

Cheers and happy contributing!