Dry certification config
freeCodeCamp/freeCodeCamp pull request #40927
Opened 2021-02-05 15:54 UTC by ahmadabdolsaheb

2021-02-06 20:18 UTC, ahmadabdolsaheb commented
@ojeytonwilliams should we produce these cert maps when building the curriculum?

2021-02-08 10:24 UTC, ojeytonwilliams commented
@ahmadabdolsaheb yes, I'd say so.  Shaun's been working on https://github.com/freeCodeCamp/freeCodeCamp/pull/39695 which is looking to do that.  For the 'building' part, we still need to work out how to keep the ability to quickly live-reload challenges in the browser whenever you change a challenge.  If we require the entire curriculum to be reloaded, this makes the process very slow and frustrating.  I'm not sure how best to solve this, yet.

Also, I think we should consider using `meta.yml` over `meta.json`, simply because we repeat the titles in the meta.json purely to help humans order the challenges correctly.  Effectively they're comments masquerading as code, which is another source of confusion.

2021-02-10 08:43 UTC, raisedadead requested changes

2021-02-10 08:43 UTC, raisedadead commented on config/misc.js
>  exports.oldDataVizId = '561add10cb82ac38a17513b3';
This should be moved to the area other cert-ids are defined.

2021-02-18 05:16 UTC, raisedadead reviewed
Mind resolving the conflict on this PR?

2021-02-18 18:44 UTC, ahmadabdolsaheb commented
Since the completion hours are read from the translations, it seems that they fine not being pulled from the config.

2021-02-22 14:31 UTC, ojeytonwilliams commented
So, it's kind of annoying that I could introduce a bug (fixed by the last commit) that didn't cause any tests to fail.  It's in `randomAPIs` though, so maybe it's not a huge deal.

2021-02-22 14:33 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

I did rebase and add a commit, though, so another review would be good.

2021-02-23 04:20 UTC, raisedadead approved these changes

2021-02-23 04:20 UTC, raisedadead commented
@nhcarrigan please review and merge when you get a chance.

2021-02-23 04:38 UTC, nhcarrigan approved these changes
Looks good to me.

Testing locally: claiming cert, attempting to claim cert w/o projects, and viewing cert all appear to function as intended.

2021-02-23 04:38 UTC, merged