feat: translation status banner
freeCodeCamp/freeCodeCamp pull request #41001
Opened 2021-02-08 17:35 UTC by scissorsneedfoodtoo

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Basic working version of the translation status banner.

2021-02-08 17:39 UTC, nhcarrigan commented
Whoops - failing test is my fault. Didn't plan for booleans in the translation objects. Will push a commit to resolve.

2021-02-08 17:40 UTC, nhcarrigan commented
![test](https://user-images.githubusercontent.com/63889819/107259300-b040be80-69f1-11eb-819e-1d5c72c70db0.gif)

On smaller screens, do we want the banner to shift down on menu toggle? Or allow the search bar to overlap?

2021-02-08 17:48 UTC, scissorsneedfoodtoo commented
Thanks for catching those things @nhcarrigan, especially that bit with the banner on mobile screens. I can't remember how we used to handle it on News back in the day. Do you remember @ahmadabdolsaheb?

Looks a bit off since it's not quite completely covered. May be better to shift it down with the menu toggle, but that's just me.

Not sure if booleans are the best way to go here, but it was just a fast way to get things working. Feel free to make any necessary changes.

2021-02-08 18:21 UTC, nhcarrigan commented
Rather than shifting it down (and thus having to shift down the entire page content) what if we shrink it to match the height of the search bar?

![test](https://user-images.githubusercontent.com/63889819/107264118-6eb31200-69f7-11eb-93a6-9d455d47fed3.gif)

2021-02-08 19:18 UTC, raisedadead reviewed
Let's change the banner message to something like:

```md
Translations for these parts are in progress, you can help [here](https://contribute.freecodecamp.org/#/how-to-translate-files).
```

2021-02-08 20:34 UTC, RandellDawson commented
When this PR is merged, we need to run the Crowdin UI upload workflow, so @miyaliu666 and @RafaelDavisH can make the translations.

2021-02-09 03:35 UTC, nhcarrigan commented
@scissorsneedfoodtoo if you want to take another look, I think I'm happy with this.

2021-02-09 05:15 UTC, scissorsneedfoodtoo commented
@nhcarrigan, that's a great idea. Looks much cleaner that way. I'll make that change now, along with adding a link to the contribute docs.

2021-02-09 05:48 UTC, raisedadead commented
Is this ready for review, we can add the translations for the strings after the fact. If yes, a quick screenshot in here, and we can get this signed-off with Quincy before going live.

2021-02-09 05:57 UTC, nhcarrigan commented
Sure - give me a moment to spin it up

2021-02-09 06:00 UTC, nhcarrigan commented
![image](https://user-images.githubusercontent.com/63889819/107322264-0137cd80-6a59-11eb-9b35-dae6d5a04735.png)

@raisedadead here is how it currently looks. I think @scissorsneedfoodtoo is taking one last look at it.

2021-02-09 06:12 UTC, raisedadead requested changes
Friendlier.

2021-02-09 06:12 UTC, raisedadead commented on client/i18n/locales/english/intro.json
> +    "translation-banner": "Translations for this section are in progress.",
```suggestion
    "translation-banner": "Help us translate these parts of the curriculum,",
```

2021-02-09 06:12 UTC, raisedadead commented on client/i18n/locales/english/intro.json
> +    "translation-link": "You can help"
```suggestion
    "translation-link": "here."
```

2021-02-09 06:13 UTC, raisedadead requested changes

2021-02-09 06:13 UTC, raisedadead commented on client/i18n/intro-schema.js
> +    'translation-banner': 'Translation in progress',
```suggestion
    'translation-banner': "Help us translate these parts of the curriculum,",
```

2021-02-09 06:13 UTC, raisedadead commented on client/i18n/intro-schema.js
> +    'translation-link': 'You can help'
```suggestion
    'translation-link': "here."
```

2021-02-09 06:51 UTC, scissorsneedfoodtoo commented
Sorry all, just seeing your comments now. I had a quick call with Quincy a bit earlier to go over the text and updated it based on his input. Other than that made a few stylistic changes and tried to get the functionality closer to the banner over on News.

2021-02-09 06:53 UTC, raisedadead commented
Sure, no worries, just wanted to make sure we have the message a tad friendly. This looks good. Please mark it ready when done and will merge and deploy.

2021-02-09 07:02 UTC, scissorsneedfoodtoo commented
Okay, this should be ready for review if anyone wants to take another look.

And here's are some screenshots just in case:

![image](https://user-images.githubusercontent.com/2051070/107327095-dba9d300-6aef-11eb-94e1-b522e977afbc.png)

![image](https://user-images.githubusercontent.com/2051070/107327147-fa0fce80-6aef-11eb-8bae-7f22ddb09776.png)

2021-02-09 07:07 UTC, raisedadead commented on client/i18n/locales/english/intro.json
> +    "isTranslated": false,
```suggestion
    "isTranslated": true,
```

This should be set to `true`??

2021-02-09 07:15 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +    "isTranslated": false,
Sorry! Forgot to set that back.

2021-02-09 07:56 UTC, raisedadead approved these changes
The broken cypress test is not related to this PR, I am disabling it in a separate PR.

2021-02-09 07:56 UTC, merged