fix: typos and grammatical errors in intro.json
freeCodeCamp/freeCodeCamp pull request #41093
Opened 2021-02-13 07:28 UTC by erickmack

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

2021-02-13 07:57 UTC, ojeytonwilliams submitted a review, later dismissed
LGTM 👍

2021-02-13 15:07 UTC, Nitesh-thapliyal approved these changes, later dismissed
LGTM👍

2021-02-13 15:39 UTC, RandellDawson commented on client/i18n/locales/english/intro.json
> +      "In the Machine Learning with Python Certification, you'll use the TensorFlow framework to build several neural networks, and you'll explore more advanced techniques like natural language proce
```suggestion
      "In the Machine Learning with Python Certification, you'll use the TensorFlow framework to build several neural networks, and explore more advanced techniques like natural language processing and reinforcement learning.",
```

2021-02-13 15:40 UTC, RandellDawson requested changes
@erickmack See my one suggestion.

2021-02-13 17:31 UTC, erickmack commented
> 
> 
> @erickmack See my one suggestion.

I like it 👍

2021-02-14 23:15 UTC, ojeytonwilliams approved these changes

2021-02-16 14:11 UTC, raisedadead commented
Hi @RandellDawson this is pending your review. Just a gentle reminder if you are happy with this.

2021-02-16 14:49 UTC, RandellDawson approved these changes

2021-02-16 14:50 UTC, merged

2021-02-16 14:51 UTC, RandellDawson commented
@erickmack Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We're happy to accept these changes, and look forward to future contributions. 📝