fix: updated solution for Convert JSON Data to HTML
freeCodeCamp/freeCodeCamp pull request #41134
Opened 2021-02-15 23:17 UTC by fotscode

Checklist:

- [ x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Resolves issue [#41133 ](https://github.com/freeCodeCamp/freeCodeCamp/issues/41133)

2021-02-15 23:40 UTC, ShaunSHamilton requested changes
This was partially my fault, but you can use the `commit suggestion` button to commit this change

2021-02-15 23:40 UTC, ShaunSHamilton commented on curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/convert-json-data-to-html.md
> +assert(__helpers.removeWhiteSpace(code).match(html(\+=|=html\+))
```suggestion
assert(__helpers.removeWhiteSpace(code).match(/html(\+=|=html\+/g))
```

2021-02-15 23:45 UTC, ShaunSHamilton commented
Also, for future reference, in GitHub, words like `Closes ` are keywords which used to help link things like issues and PRs. So, when you create a PR that resolves an existing issue, you can automatically close the issue (once the PR is merged), by including `Closes #XXXXX` in the PR body. (where `XXXXX` is the PR number.

I have edited your PR body to include this.

2021-02-16 10:03 UTC, ojeytonwilliams requested changes

2021-02-16 10:03 UTC, ojeytonwilliams commented on curriculum/challenges/english/04-data-visualization/json-apis-and-ajax/convert-json-data-to-html.md
> +assert(__helpers.removeWhiteSpace(code).match(/html(\+=|=html\+/g))
```suggestion
assert(__helpers.removeWhiteSpace(code).match(/html(\+=|=html\+)/g))
```
This should fix things.

2021-02-16 16:18 UTC, RandellDawson approved these changes
LGTM

2021-02-16 16:23 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-02-16 16:24 UTC, ojeytonwilliams commented
@ShaunSHamilton if you're happy, I think this is good to merge.

2021-02-16 16:27 UTC, ShaunSHamilton commented
Congrats, on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

2021-02-16 16:27 UTC, ShaunSHamilton approved these changes

2021-02-16 16:27 UTC, merged