docs: update moderator handbook
freeCodeCamp/freeCodeCamp pull request #41226
Opened 2021-02-22 21:08 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Updates the handbook to rewrite the Discord section for the new chat server, removing Discord entirely.

2021-02-23 04:05 UTC, raisedadead reviewed
Holding this up for a bit to coincide with the announcement.

2021-02-23 04:09 UTC, nhcarrigan commented
Sounds good.

2021-02-24 19:05 UTC, marsonya requested changes

2021-02-24 19:05 UTC, marsonya commented on docs/moderator-handbook.md
> +In all other situations - even situations where the code of conduct is violated - moderators should not delete the message as these are an important historic record. When you do delete a message, mak
```suggestion
In all other situations - even situations where the code of conduct is violated - moderators should not delete the messages as they are important historic records. When you do delete a message, make sure you take a screenshot of it first! The screenshot can be logged in the #mod-log channel.
```

2021-02-24 19:05 UTC, marsonya commented on docs/moderator-handbook.md
> +4. **Deleting messages** Moderators have the ability to delete messages on our chat server. They should only exercise this ability in four very specific situations:
```suggestion
4. **Deleting messages** Moderators can delete messages on our chat server. They should only exercise this ability in four very specific situations:
```

2021-02-24 19:12 UTC, raisedadead approved these changes

2021-02-24 19:13 UTC, marsonya approved these changes

2021-02-24 19:16 UTC, nhcarrigan commented
@raisedadead before landing this, I asked Quincy to give it a once-over as well to make sure everything is still accurate and up-to-date.

2021-02-24 19:18 UTC, raisedadead commented
I will let you merge this instead. Thanks for letting me know.

2021-02-24 22:33 UTC, QuincyLarson approved these changes
This all looks solid. No further edits recommended from me.

2021-02-24 22:42 UTC, merged