add Big heading landing in home page
freeCodeCamp/freeCodeCamp pull request #41251
Opened 2021-02-24 23:26 UTC by menosvelasco

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

2021-02-24 23:32 UTC, nhcarrigan requested changes
You appear to have used version ^7.0.0 of `npm`, which includes breaking changes in the way `package-lock.json` files are handled. We are currently supporting version ^6.0.0, and the changes to the `package-lock.json` will need to be reverted.

Additionally, are the changes to the client related to an open issue or discussion? If not, please provide the context for these changes. Why are they needed?

2021-02-24 23:33 UTC, menosvelasco commented
Hi, this is my first time contributing to open source if I have missed a step or I'm doing something wrong. please let me know, I want to learn.

2021-02-24 23:35 UTC, nhcarrigan commented
I'll leave some more specific comments directly on the files to help clarify my concerns. 🙂

2021-02-24 23:36 UTC, menosvelasco reviewed
I added this change just because this is my first time contributing to open source

2021-02-24 23:38 UTC, nhcarrigan requested changes

2021-02-24 23:38 UTC, nhcarrigan commented on client/i18n/locales/english/translations.json
> +    "big-heading-4": "Earn certifications.",
This change here is adding a new key to be translated through the `reacti18next` functions...

2021-02-24 23:38 UTC, nhcarrigan commented on client/src/components/landing/components/LandingTop.js
> +          <p className='big-heading'>{t('landing.big-heading-4')}</p>
And the key is used here, but is not replacing any existing un-translated text. So I am confused about the addition of text to the client. Why is this being added?

2021-02-24 23:38 UTC, nhcarrigan commented on package-lock.json
> +  "lockfileVersion": 2,
lockfile Version 2 is used in `npm` versions 7 and higher - our codebase officially supports `npm` major version 6. The changes to this file should be removed from your commit.

2021-02-24 23:48 UTC, menosvelasco commented
so I should remove the package-lock.json?


On Wed, Feb 24, 2021 at 3:38 PM nhcarrigan <notifications@github.com> wrote:

> *@nhcarrigan* requested changes on this pull request.
> ------------------------------
>
> In client/i18n/locales/english/translations.json
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251#discussion_r582383086>
> :
>
> > -    "big-heading-2": "Build projects.",
> -    "big-heading-3": "Earn certifications.",
> +    "big-heading-2": "Learn to solve problems.",
> +    "big-heading-3": "Build projects.",
> +    "big-heading-4": "Earn certifications.",
>
> This change here is adding a new key to be translated through the
> reacti18next functions...
> ------------------------------
>
> In client/src/components/landing/components/LandingTop.js
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251#discussion_r582383467>
> :
>
> > @@ -30,6 +30,7 @@ function LandingTop({ page }) {
>            </h1>
>            <p className='big-heading'>{t('landing.big-heading-2')}</p>
>            <p className='big-heading'>{t('landing.big-heading-3')}</p>
> +          <p className='big-heading'>{t('landing.big-heading-4')}</p>
>
> And the key is used here, but is not replacing any existing un-translated
> text. So I am confused about the addition of text to the client. Why is
> this being added?
> ------------------------------
>
> In package-lock.json
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251#discussion_r582383918>
> :
>
> > @@ -1,8 +1,19712 @@
>  {
>    "name": "@freecodecamp/freecodecamp",
>    "version": "0.0.1",
> -  "lockfileVersion": 1,
> +  "lockfileVersion": 2,
>
> lockfile Version 2 is used in npm versions 7 and higher - our codebase
> officially supports npm major version 6. The changes to this file should
> be removed from your commit.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251#pullrequestreview-598032058>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKTZINYCCTF6W5UH4GZFNTTAWEXZANCNFSM4YFN6PAQ>
> .
>

2021-02-24 23:51 UTC, nhcarrigan commented
You'll want to revert the changes made to the `package-lock.json`, yes. Note that you don't want to delete the file entirely. `git` offers a few ways to do this - personally, I'd `reset` against our `main` branch and make the other two changes again. 

If needed, I can revert it for you.

2021-02-24 23:55 UTC, menosvelasco commented
yes. go ahead and do it for me.
I'm sorry

On Wed, Feb 24, 2021 at 3:52 PM nhcarrigan <notifications@github.com> wrote:

> You'll want to revert the changes made to the package-lock.json, yes.
> Note that you don't want to delete the file entirely. git offers a few
> ways to do this - personally, I'd reset against our main branch and make
> the other two changes again.
>
> If needed, I can revert it for you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251#issuecomment-785470554>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKTZIKIDUGEYJT26V4ZOATTAWGKRANCNFSM4YFN6PAQ>
> .
>

2021-02-25 00:05 UTC, menosvelasco commented
it would be appreciated if you could send me some resources contributing to
open source.

On Wed, Feb 24, 2021 at 3:55 PM Manuel Velasco <manuelvelasco2020@gmail.com>
wrote:

> yes. go ahead and do it for me.
> I'm sorry
>
> On Wed, Feb 24, 2021 at 3:52 PM nhcarrigan <notifications@github.com>
> wrote:
>
>> You'll want to revert the changes made to the package-lock.json, yes.
>> Note that you don't want to delete the file entirely. git offers a few
>> ways to do this - personally, I'd reset against our main branch and make
>> the other two changes again.
>>
>> If needed, I can revert it for you.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251#issuecomment-785470554>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AMKTZIKIDUGEYJT26V4ZOATTAWGKRANCNFSM4YFN6PAQ>
>> .
>>
>

2021-02-25 00:12 UTC, nhcarrigan commented
A great place to start is our [contributing documentation](https://contribute.freecodecamp.org).

2021-02-25 00:53 UTC, nhcarrigan commented
Thank you for opening this pull request.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Reason: The content of our landing page directly impacts our SEO - as such, we generally do not make changes without input from Quincy.

Thank you and happy coding.

2021-02-25 00:53 UTC, closed without merging

2021-02-25 01:06 UTC, menosvelasco commented
you want me to close it?
delete the branch?


On Wed, Feb 24, 2021 at 4:54 PM nhcarrigan <notifications@github.com> wrote:

> Closed #41251 <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/41251#event-4373939449>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMKTZIPQU2UU2VFCB65OP7LTAWNTHANCNFSM4YFN6PAQ>
> .
>