docs: establish i18n for message boxes
freeCodeCamp/freeCodeCamp pull request #41326
Opened 2021-03-01 17:42 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #XXXXX

Sets up the i18n mapping for Chinese and Spanish for the message/alert boxes. Based on a discussion with Oliver, I think the best flow here is to:

- Add a language mapping when we are ready to download and serve the docs in that language
- Have a proofreader(s) provide the translations for that language 
- No need to upload on crowdin as these translations shouldn't change

2021-03-01 17:48 UTC, nhcarrigan commented
@miyaliu666 and @RafaelDavisH - these are machine translations - could you verify when you have time?

2021-03-01 18:07 UTC, RafaelDavisH commented
I added comments in the code or you prefer a PR to suggest changes?

2021-03-01 18:19 UTC, ojeytonwilliams requested changes
I don't think the lack of `/` will matter, but it might as well be there.  Just in case.

2021-03-01 18:19 UTC, ojeytonwilliams commented on docs/index.html
> +              '/i18n/chinese': '笔记',
```suggestion
              '/i18n/chinese/': '笔记',
```

2021-03-01 18:19 UTC, ojeytonwilliams commented on docs/index.html
> +              '/i18n/chinese': '小费',
```suggestion
              '/i18n/chinese/': '小费',
```

2021-03-01 18:19 UTC, ojeytonwilliams commented on docs/index.html
> +              '/i18n/chinese': '警告',
```suggestion
              '/i18n/chinese/': '警告',
```

2021-03-01 18:19 UTC, ojeytonwilliams commented on docs/index.html
> +              '/i18n/chinese': '注意力',
```suggestion
              '/i18n/chinese/': '注意力',
```

2021-03-01 21:39 UTC, nhcarrigan commented
> I added comments in the code or you prefer a PR to suggest changes?

Comments here is fine - I can apply them directly in a commit

2021-03-02 07:48 UTC, ojeytonwilliams approved these changes, later dismissed
LGTM :+1: 

Once Miya and Rafa are happy, I think this can go in.  Then we can add other languages as needed (Portuguese next, since we have the docs already?).

2021-03-04 12:57 UTC, miyaliu666 commented on docs/index.html
> +              '/i18n/chinese/': '笔记',
注意

2021-03-04 12:59 UTC, raisedadead commented on docs/index.html
> +              '/i18n/chinese/': '笔记',
```suggestion
              '/i18n/chinese/': '注意',
```

Adding Miya's comment.

2021-03-04 13:00 UTC, miyaliu666 submitted a review, later dismissed

2021-03-04 13:00 UTC, miyaliu666 commented on docs/index.html
> +              '/i18n/chinese/': '小费',
提示

2021-03-04 13:00 UTC, miyaliu666 commented on docs/index.html
> +              '/i18n/chinese/': '注意力',
注意

2021-03-04 13:00 UTC, miyaliu666 commented on docs/index.html
> +              '/i18n/chinese/': '笔记',
注意

2021-03-04 16:01 UTC, nhcarrigan commented
Thanks @miyaliu666!

2021-03-05 00:24 UTC, nhcarrigan commented
@RafaelDavisH if you could verify the Spanish translations are correct this will be ready to merge I think.

2021-03-05 02:06 UTC, nhcarrigan commented
Thanks @RafaelDavisH!

2021-03-05 03:30 UTC, RandellDawson commented
@ojeytonwilliams Is the person who will proofread the Portuguese different than the one who made most of the translations?  We would not want a proofreader to approve their own translations.

2021-03-09 06:00 UTC, raisedadead approved these changes

2021-03-09 06:00 UTC, merged

2021-03-09 06:01 UTC, raisedadead commented
> Is the person who will proofread the Portuguese different than the one who made most of the translations? We would not want a proofreader to approve their own translations.

You are correct, we should encourage them to get at least one more person to help them.