Add unmatched quote to factors-of-a-mersenne-number
freeCodeCamp/freeCodeCamp pull request #41415
Opened 2021-03-08 09:34 UTC by melusc

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

They are not all in the same language folder but in the same language.

All I changed was adding an unmatched quote.

2021-03-08 13:08 UTC, RandellDawson requested changes
@melusc We are actually planning to remove quotation marks for representing strings in returned values for translation purposes.  Instead, see the following on how all the test cases should be for this challenge.  Would you mind replacing the rest of them?

Thank you.

2021-03-08 13:08 UTC, RandellDawson commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/factors-of-a-mersenne-number.md
> +`check_mersenne(929)` should return "M929 = 2^929-1 is composite with factor 13007"
```suggestion
`check_mersenne(929)` should return the string `M929 = 2^929-1 is composite with factor 13007`
```

2021-03-08 13:14 UTC, melusc commented
I replaced the rest and added a fullstop on line 85 that was missing.

2021-03-09 09:25 UTC, gikf commented
Hey @melusc 

This PR seems to make similar changes as the existing PR #41280. As such, we are going to close this as duplicate.

If you feel you have additional changes to expand upon this PR, please feel free to push your commits and request this PR be reopened.

Thanks again! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://chat.freecodecamp.org/channel/contributors).

2021-03-09 09:25 UTC, closed without merging