Fix: Code blocks overflowing parents
freeCodeCamp/freeCodeCamp pull request #41438
Opened 2021-03-10 18:38 UTC by PatrickFranz

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41418

2021-03-12 05:54 UTC, nhcarrigan requested changes

2021-03-12 05:54 UTC, nhcarrigan commented on client/src/components/layouts/prism.css
> +
```suggestion
pre[class*='language'] code[class*='language-'] {
  white-space: nowrap;
  overflow: auto;
}

.video-quiz-option {
  max-width: 90%;
}
```

I spoke with @ahmadabdolsaheb and it does sound like horizontal scroll is the desired approach.

This CSS change will preserve the horizontal scroll that exists on the code within a video challenge question, while adding it to the video challenge answer. It also shrinks the answer text width a bit to account for the select button.

Certainly open to better CSS approaches for this same effect, though 🙂

2021-03-16 10:24 UTC, ahmadabdolsaheb commented
The original issue seems to persist.
<img width="520" alt="Screen Shot 2021-03-16 at 1 19 23 PM" src="https://user-images.githubusercontent.com/4591597/111293530-6b482180-865a-11eb-8153-011cb49167f5.png">

2021-03-16 17:19 UTC, raisedadead commented
Hi @ahmadabdolsaheb since the linked issue is for a first timer could you guide with the exact changes that need to be done in the corresponding files.

2021-03-18 09:44 UTC, ahmadabdolsaheb commented
@PatrickFranz, thanks for your patience. It seem the issue is more involved than initially expected. I will be pushing additional changes to resolve the issue across our platform upcoming days.

2021-03-18 13:39 UTC, raisedadead commented
Thanks for the clarification @ahmadabdolsaheb in that case do you mind approving the current changes to get this PR moving forward.

2021-03-18 19:23 UTC, PatrickFranz commented
> The original issue seems to persist.
> <img alt="Screen Shot 2021-03-16 at 1 19 23 PM" width="520" src="https://user-images.githubusercontent.com/4591597/111293530-6b482180-865a-11eb-8153-011cb49167f5.png">

Do you have a URL for this? I'd like to see why that code block isn't affected by the rule change.

2021-03-20 17:14 UTC, PatrickFranz commented
OK, so not sure what to do here. Should I close it? Keep waiting? @ahmadabdolsaheb could you provide some clear direction on what we're doing with this?

2021-03-23 04:51 UTC, nhcarrigan approved these changes
Hey @PatrickFranz, 

Thanks for your patience on this. Your changes look good to me, and the initial issue is resolved on my end:
![image](https://user-images.githubusercontent.com/63889819/112094481-9352eb80-8b58-11eb-8ab3-f6b868653f77.png)


I do think we will need to circle back and style this scrollbar, but that can be done in a separate PR at a later time.

![image](https://user-images.githubusercontent.com/63889819/112094561-c0070300-8b58-11eb-856f-d1f2bae24cd3.png)

This looks good to me.

2021-03-23 04:53 UTC, raisedadead approved these changes

2021-03-23 04:53 UTC, merged

2021-03-23 05:40 UTC, nhcarrigan commented
Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.