fix(client): change repl.it validation to replit for migration
freeCodeCamp/freeCodeCamp pull request #41457
Opened 2021-03-12 23:21 UTC by ShaunSHamilton

Checklist:

The migration has already taken place. As far as I can tell, all old URLs are redirected to `replit.com`. So, there should be no reason someone submits a `repl.it/@...` url

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Related to #41444 

Changes the editor URL validation to match new Replit.com migration

2021-03-13 05:37 UTC, raisedadead approved these changes, later dismissed

2021-03-13 15:43 UTC, nhcarrigan requested changes
Hey @ShaunSHamilton,

I opened up Replit today and tried to generate a new invite link on one of my repls. It's still using the old domain for the `join` links it seems:

![image](https://user-images.githubusercontent.com/63889819/111035509-c31f2800-83cf-11eb-8e9d-ba34e6150c8e.png)

2021-03-13 16:29 UTC, ShaunSHamilton commented
@nhcarrigan Thanks, for catching that. I do wonder if that will change...

2021-03-15 13:58 UTC, nhcarrigan approved these changes
Looks good to me.

2021-03-15 14:07 UTC, raisedadead approved these changes

2021-03-15 14:07 UTC, merged