docs: change node alias from stable to lts
freeCodeCamp/freeCodeCamp pull request #41503
Opened 2021-03-16 11:14 UTC by ojeytonwilliams

As discussed in
https://freecodecamp.crowdin.com/translate/457d487b1586f10d2fba3c4ccb9c5453/5364/en-esem?filter=basic&value=0#q=732016
the `stable` alias just points to the latest version of node you have install.  See the [nvm docs](https://github.com/nvm-sh/nvm#usage) for confirmation.

2021-03-16 15:32 UTC, raisedadead requested changes
The current behaviour is intended to make sure we are using the version we have tested with. So, its indeed ideal for us to use the lts version we are using to be the default that nvm loads up.

Let me know if that clarifies things, if yes do you mind closing?

2021-03-16 16:17 UTC, ojeytonwilliams commented
Right, but that's what this does.  

```console
nvm install 'lts/*' --reinstall-packages-from=default
nvm alias default lts/*
```
sets installs the latest LTS and then sets it as default.

```console
nvm install 'lts/*' --reinstall-packages-from=default
nvm alias default stable
```
sets installs the latest LTS and then sets whatever happens to be the most recent version of node install to be the default (that should be lts/*, but it might not be).

2021-03-16 17:16 UTC, raisedadead commented
You are correct. That is exactly the behavior we want & is intentional. We will not have more than on version installed at any given time.

2021-03-16 17:26 UTC, ojeytonwilliams commented
I'm not with you. Isn't the behaviour we want that we install and default to `lts/*`?  In this case, the change in this PR does exactly that, but doesn't rely on a deprecated alias.

2021-03-17 11:12 UTC, raisedadead commented
I am f*** stupid. Sorry about closing this.

2021-03-17 11:12 UTC, raisedadead approved these changes

2021-03-18 12:39 UTC, nhcarrigan approved these changes
Looks good to me. Thanks Oliver!

2021-03-18 12:39 UTC, merged