tools: test all languages in CI
freeCodeCamp/freeCodeCamp pull request #41512
Opened 2021-03-17 09:40 UTC by ojeytonwilliams

This doesn't change the `CLIENT_LOCALE` yet, I just wanted to test changing `CURRICULUM_LOCALE`, but if that works I think we can change both.

2021-03-17 13:58 UTC, ojeytonwilliams commented
TODO (in separate PRs before merging this)

- [ ] make comment checks handle comments that are substrings of other comments
- [ ] improve client tests and ensure they pass in all languages

2021-03-17 14:28 UTC, ojeytonwilliams commented
The root cause of the failing client checks is that the `NavLinks` component depends on `env.json` and the tests don't.  I think this is just a bad pattern and we should use React's Context instead.

2021-03-31 19:16 UTC, ojeytonwilliams commented
@nhcarrigan any idea why the final check isn't passing when the rest are?

2021-03-31 19:17 UTC, nhcarrigan commented
Ahhhh hold on. Lemme look at the branch protection rules.

2021-03-31 19:18 UTC, nhcarrigan commented
![image](https://user-images.githubusercontent.com/63889819/113198696-14764680-921b-11eb-98bb-02638ede91dd.png)

Yeah, so the change in the matrix triggered a change in the CI names - simple enough to switch this over, but can you confirm that we want all three test suites running on each PR? Need to know which checks are required.

/cc @raisedadead

2021-03-31 19:42 UTC, ojeytonwilliams commented
Oh, wait, is it just that the CI expected that because of the old config? And, yep, we want to run it on each PR. At least initially, so we can be confident everything's working as expected.

We might need to change the process if we add too many languages, though.

2021-03-31 19:44 UTC, nhcarrigan commented
Yeah the config is looking for the old CI ("old" meaning just before you changed it lol) - I'll flip it to look for the three new ones instead.

2021-03-31 20:15 UTC, ojeytonwilliams commented
If I understand this (which I might not), once this PR is in, it'll change the requirements for new PRs, but not old ones.  So, we should be okay, right?

In principle an existing PR could have an issue which the new language tests catch, but those tests would run on merge.  It's not ideal, but we should get warned if there's a problem.

2021-03-31 20:39 UTC, nhcarrigan commented
Well, the trick is in the timing for setting the `required` flag - if I switch it now, before this is approved, we end up with PRs that are potentially looking for CI tests that don't exist yet. So they'll be stuck on "Waiting for status" (like this one).

2021-03-31 20:40 UTC, nhcarrigan approved these changes, later dismissed
I keep talking about it but I guess I could actually approve it.

2021-03-31 20:46 UTC, ojeytonwilliams commented
> Well, the trick is in the timing for setting the `required` flag - if I switch it now, before this is approved, we end up with PRs that are potentially looking for CI tests that don't exist yet. So they'll be stuck on "Waiting for status" (like this one).

Ah, I guess I don't understand. How're you setting this flag?

2021-03-31 20:57 UTC, nhcarrigan commented
The setting is on the branch protection configuration.

When I turn on those three as "required status checks", PRs will be blocked from merge until those checks pass.
But since those checks don't technically exist in our repo (yet), they can't pass.

2021-03-31 21:43 UTC, ojeytonwilliams commented
Awesome, thanks Nick.  I probably should have known that!  

I think we can use admin powers to bypass that for this PR, then we should be able to set them as required without putting other PRs in an impossible situation.  Let's give Mrugesh a chance weigh in (and review it), though.

2021-04-01 04:55 UTC, raisedadead requested changes
I propose we add a third job to the workflow file with the language matrix consisting of [chinese, espanol] and leave the curent job (`test`) as is. That is makes it so that we have the current mandatory check and additional indicative checks in chinese and espanol.

In future, we can consider a dedicated workflow file for testing all languages, that we do not need to run on all PRs. The point being our consistency will grow over time and by the time we are ready for newer languages our coverage of the existing bugs would have increased.

2021-04-01 07:04 UTC, ojeytonwilliams commented on .github/workflows/node.js-tests.yml
> +    name: Test Languages
'Test Languages' isn't a great name, but nothing else leapt to mind

2021-04-01 07:09 UTC, raisedadead commented on .github/workflows/node.js-tests.yml
> +    name: Test Languages
```suggestion
  test-localization:
    name: Localize
```

How about this?

2021-04-01 10:29 UTC, raisedadead approved these changes

2021-04-01 13:20 UTC, nhcarrigan approved these changes
Looks good to me.

2021-04-01 13:20 UTC, merged