Add api stripe checkout integration
freeCodeCamp/freeCodeCamp pull request #41666
Opened 2021-03-30 11:13 UTC by ahmadabdolsaheb

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

2021-04-01 06:38 UTC, scissorsneedfoodtoo commented
Tested this locally with several test cards on the donate page and after completing a certification. The donations all show up on the Stripe's Test Data dashboard, and the redirect after donating on the donation page works as expected.

Everything LGTM :+1: :+1:

2021-04-01 06:38 UTC, scissorsneedfoodtoo approved these changes, later dismissed

2021-04-01 09:06 UTC, ojeytonwilliams requested changes

2021-04-01 09:06 UTC, ojeytonwilliams commented on client/src/components/Donation/DonateForm.js
> +    console.log({ processing, success, error, redirecting });
```suggestion
```

2021-04-01 09:06 UTC, ojeytonwilliams commented on client/src/redux/donation-saga.js
> +    yield put(addDonationError(data.message));
```suggestion
    const err =
      error.response && error.response.data
        ? error.response.data.message
        : defaultDonationError;
    yield put(addDonationError(err));
```
Saves a couple of lines.

2021-04-01 09:48 UTC, ahmadabdolsaheb commented on api-server/src/server/boot/donate.js
> +        cancel_url: donationUrls.cancelUrl
We don't need to, they will come back to the client they came from :)

2021-04-01 09:53 UTC, ojeytonwilliams commented on api-server/src/server/boot/donate.js
> +        cancel_url: donationUrls.cancelUrl
Not for the /news redirect, surely?

2021-04-01 09:55 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-04-01 09:56 UTC, ojeytonwilliams commented
@scissorsneedfoodtoo could you give this a final approve if you're happy?  We lost your first review when we added some commits.

2021-04-01 10:11 UTC, ahmadabdolsaheb commented on api-server/src/server/boot/donate.js
> +        cancel_url: donationUrls.cancelUrl
So when creating the session in our api, we will pass the localized client url from which the button was clicked. 
When the donation is complete, stripe will use that redirect url and send users back to the desired client.

2021-04-02 06:25 UTC, scissorsneedfoodtoo commented
Thanks for your patience, and also thanks for catching those things @ojeytonwilliams.

I was having some trouble testing this because it occasionally it would say that the page at `/donate/create-stripe-session` didn't exist.

It may have been an issue with my cache or keys, though. After checking the keys and doing a hard refresh everything seems to be fine.

2021-04-02 06:29 UTC, scissorsneedfoodtoo commented on api-server/src/server/boot/donate.js
> +        cancel_url: donationUrls.cancelUrl
I just tested this in other locales and can confirm that we only redirect to the English version of the news or back to the donate page on success or failure.

It seems like we could add something like this to `config/donation-settings.js`, or somewhere else in the config directory to get localized redirects:

```js
const envData = require('./env.json');

const { clientLocale } = envData;

...

const donationUrls = {
  espanol: {
    successUrl:
      'https://www.freecodecamp.org/espanol/news/thank-you-for-donating/',
    cancelUrl: 'https://www.freecodecamp.org/espanol/donate/'
  },
  chinese: {
    successUrl: 'https://chinese.freecodecamp.org/news/thank-you-for-donating/',
    cancelUrl: 'https://chinese.freecodecamp.org/donate/'
  },
  english: {
    successUrl: 'https://www.freecodecamp.org/news/thank-you-for-donating/',
    cancelUrl: 'https://www.freecodecamp.org/donate/'
  }
}[clientLocale];

...
```

But we don't have "Thank You for Donating" pages set up for the other locales yet, so I'm fine with putting this off for a bit until we create those.

2021-04-02 06:33 UTC, scissorsneedfoodtoo approved these changes

2021-04-02 06:33 UTC, merged

2021-04-02 07:31 UTC, ojeytonwilliams commented
Ahmad and I ran into that too, when testing it out. You need all the donation keys to be present for that page to get created. There's a warning, but it's not obvious (we missed it).

2021-04-02 09:38 UTC, scissorsneedfoodtoo commented
Awesome, thanks for confirming that. Good to know it wasn't just me. I remember having trouble until I added the Stripe and PayPal keys back in. They were already present, but I might have accidentally changed one in the `.env` file without noticing.