fix(curriculum) regex compatibility issue for Safari
freeCodeCamp/freeCodeCamp pull request #41725
Opened 2021-04-01 18:41 UTC by Sembauke

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41724

2021-04-02 05:34 UTC, raisedadead commented
@freeCodeCamp/moderators can someone with safari browser pull this down and test it.

2021-04-02 08:30 UTC, ojeytonwilliams requested changes
Just the one typo.  Aside from that, this LGTM.  It should be fine in Safari, because lookahead is universally supported, according to [caniuse](https://caniuse.com/?search=lookahead).

That said, I agree that we should get a confirmation from a Safari user.

2021-04-02 08:30 UTC, ojeytonwilliams commented on curriculum/challenges/english/01-responsive-web-design/basic-css/change-a-variable-for-a-specific-area.md
> +The `peguin` class should not contain the `background-color` property
```suggestion
The `penguin` class should not contain the `background-color` property
```

2021-04-02 10:25 UTC, ojeytonwilliams approved these changes, later dismissed
LGTM :+1:

2021-04-02 11:49 UTC, ahmadabdolsaheb commented
@moT01, could you double check this. I am getting errors with `Loadable` when visiting a page with editor on Safari locally. (chrome is fine)

2021-04-03 10:52 UTC, ojeytonwilliams commented
@ahmadabdolsaheb it's possibly a silly question, but do you see the `Loadable` error in GitPod?

2021-04-08 15:57 UTC, moT01 reviewed
Yea, Safari isn't working great for me either. Using `npm run develop` I get this on any page with the editor:
<img width="810" alt="Screen Shot 2021-04-08 at 10 34 03 AM" src="https://user-images.githubusercontent.com/20648924/114055940-cd113b00-9856-11eb-84be-104f2bd8344c.png">

And it's stuck there. If I `npm run build` it works.

I left one suggestion, the period isn't escaped there. There are few other cases not handled.


It passes if the property is outside the selector:
<img width="774" alt="Screen Shot 2021-04-08 at 10 45 25 AM" src="https://user-images.githubusercontent.com/20648924/114057275-0a29fd00-9858-11eb-87cc-b2109d110ee4.png">

It passes if extra characters are added in front of the property:
<img width="777" alt="Screen Shot 2021-04-08 at 10 46 01 AM" src="https://user-images.githubusercontent.com/20648924/114057659-5d03b480-9858-11eb-8d85-c20ba913bbbd.png">

I don't think these are terrible and necessarily need to be fixed. But if we wanted to handle these, we could possibly check the regex in conjunction with checking the color rendered? Or I have used [something like this](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/css-variables-skyline/part-058.md#--hints--) before to isolate the properties within a class.

2021-04-08 15:57 UTC, moT01 commented on curriculum/challenges/english/01-responsive-web-design/basic-css/change-a-variable-for-a-specific-area.md
> +  code.match(/.penguin\s*?{[\s\S]*--penguin-belly\s*?:\s*?white\s*?;[\s\S]*}/gi)
```suggestion
  code.match(/\.penguin\s*?{[\s\S]*--penguin-belly\s*?:\s*?white\s*?;[\s\S]*}/gi)
```

2021-04-08 16:58 UTC, moT01 approved these changes
LGTM 🎉

Unless it's determined that my other concerns should be fixed. I think it's fine for now.

2021-04-09 04:39 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-04-09 04:39 UTC, merged