feat(Cypress) Enabling parallelization Cypress
freeCodeCamp/freeCodeCamp pull request #41782
Opened 2021-04-08 16:11 UTC by Sembauke

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Thanks for the help @ojeytonwilliams  and @raisedadead

2021-04-08 16:12 UTC, ojeytonwilliams submitted a review, later dismissed
This looks familiar :)

LGTM :+1:

2021-04-08 16:22 UTC, raisedadead requested changes
Also please rename the `cypress.yml` to `cypress-pr.yml`

2021-04-08 16:22 UTC, raisedadead commented on .github/workflows/cypress.yml
>  name: Cypress
```suggestion
name: Cypress - Pull Request
```

2021-04-08 16:22 UTC, raisedadead commented on .github/workflows/cypress-push.yml
> +name: Cypress
```suggestion
name: Cypress - Push
```

2021-04-08 17:34 UTC, ojeytonwilliams commented
@Sembauke could you commit the rename Mrugesh suggested? We know the tests pass now, so it's not a problem if they never complete on this PR.

2021-04-08 17:44 UTC, Sembauke commented
> @Sembauke could you commit the rename Mrugesh suggested? We know the tests pass now, so it's not a problem if they never complete on this PR.

I already comitted them https://github.com/freeCodeCamp/freeCodeCamp/pull/41782/commits/6bbba5f5596eac31a05904a6790406c69333b8d9

2021-04-08 18:17 UTC, Sembauke commented
> @Sembauke could you commit the rename Mrugesh suggested? We know the tests pass now, so it's not a problem if they never complete on this PR.

What should I do with the conflict?

2021-04-08 18:51 UTC, ojeytonwilliams commented
> What should I do with the conflict?

```
git checkout main
git pull upstream main
git checkout Enabeling-parallel
git merge main 
git push
```
That should prompt you to fix the conflict (if you use VSCode it'll guide you).  Let us know if you run into any problems.

2021-04-09 04:11 UTC, raisedadead approved these changes

2021-04-09 04:14 UTC, ojeytonwilliams approved these changes
LGTM 👍

2021-04-09 04:14 UTC, merged