fix(curriculum): fluid containers test not specific
freeCodeCamp/freeCodeCamp pull request #41866
Opened 2021-04-20 11:43 UTC by jonathankerr

This resolves an issue where a user could pass the bootstrap fluid containers lesson by including `style` and/ or `link` in their `div` as well as not nesting all elements after the closing tag going against the test:

`All HTML elements after the closing style tag should be nested in`

Tested locally.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41863

2021-04-20 13:44 UTC, ShaunSHamilton requested changes
Thank you, for being eager to contribute. In this instance, it is not of much consequence, but, in general, it is best to wait for an issue to be `triaged`, and opened up for contribution, before opening a PR.

---

Otherwise, see the requested change - as we should continue allowing tests to pass when Campers adjust the code not being tested, I am not a fan of the strict equality for the number of children.

That is, Campers like to play with the code by adding paragraphs and such, and, as we do not have _Only change this line_ comments, they should be allowed to pass by doing so.

2021-04-20 13:44 UTC, ShaunSHamilton commented on curriculum/challenges/english/03-front-end-libraries/bootstrap/use-responsive-design-with-bootstrap-fluid-containers.md
> +assert($('.container-fluid').children().length === 8 && !$('.container-fluid').has("style").length && !$('.container-fluid').has("link").length);
```suggestion
assert($('.container-fluid').children().length >= 8 && !$('.container-fluid').has("style").length && !$('.container-fluid').has("link").length);
```

2021-04-20 14:07 UTC, jonathankerr commented
> 
> 
> Thank you, for being eager to contribute. In this instance, it is not of much consequence, but, in general, it is best to wait for an issue to be `triaged`, and opened up for contribution, before opening a PR.
> 
> Otherwise, see the requested change - as we should continue allowing tests to pass when Campers adjust the code not being tested, I am not a fan of the strict equality for the number of children.
> 
> That is, Campers like to play with the code by adding paragraphs and such, and, as we do not have _Only change this line_ comments, they should be allowed to pass by doing so.

Noted, thanks @ShaunSHamilton 👍

2021-04-23 07:34 UTC, gikf approved these changes
LGTM :+1: 

Fixes issue with test passing when opening `div` tag is positioned before `link` and/or `style` tags, what instructions specifically say not to do.

2021-04-23 14:14 UTC, ShaunSHamilton approved these changes
This LGTM 👍

2021-04-23 14:14 UTC, merged