fix: generate csrf tokens on server not client
freeCodeCamp/freeCodeCamp pull request #41908
Opened 2021-04-23 11:10 UTC by ojeytonwilliams

This is part of the set of changes we need to remove `crypto` in the client.  It was never necessary, since we can always send the token out from the server as a cookie and back as a header, never needing to use `_csrf` (and `crypto` to generate tokens) on the client.

2021-04-26 12:12 UTC, ahmadabdolsaheb commented
Although it seems to be setting the I see the 'CSRF-Server-Token' right after auth, so I assume it is working properly.

2021-04-26 13:10 UTC, ojeytonwilliams commented
Do you mean it's setting `_csrf`?  I've investigated a little and `Session` duration leaves it up to the browser how long those cookies stick around.  With Firefox it survives page reload, but not closing down of the browser.  Brave, in contrast keeps it until you actively log out of fcc.

2021-04-27 18:54 UTC, raisedadead approved these changes

2021-04-27 19:43 UTC, raisedadead requested changes

2021-04-27 19:43 UTC, raisedadead commented on api-server/src/server/middlewares/csurf.js
> +      res.cookie('CSRF-Server-Token', req.csrfToken(), opts);
```suggestion
      res.cookie('csrf_token', req.csrfToken(), opts);
```

2021-04-27 19:44 UTC, raisedadead requested changes

2021-04-27 19:44 UTC, raisedadead commented on client/src/utils/ajax.js
> +    typeof window !== 'undefined' && cookies.get('CSRF-Server-Token');
```suggestion
    typeof window !== 'undefined' && cookies.get('csrf_token');
```

2021-04-28 13:36 UTC, raisedadead approved these changes

2021-04-30 06:42 UTC, ahmadabdolsaheb approved these changes

2021-04-30 06:42 UTC, merged

2021-04-30 06:44 UTC, ahmadabdolsaheb commented
Just a heads up that we should test the token in .dev before it goes to production.