Record Collection - variable names shouldn't be keywords
freeCodeCamp/freeCodeCamp pull request #41904
Opened 2021-04-22 22:18 UTC by jeremylt

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes: N/A

I'd be happy with any other variable names, but we really shouldn't show learners naming a variable after a keyword.

Using a proper variable name has the side benefit of fixing the syntax highlighting for this problem.

2021-04-22 23:07 UTC, ShaunSHamilton requested changes
I like this change, and have always been irked by the use of a reserved word.

The first suggestion is me being pinnikity. The second is because, currently, it sounds as though there is a property key `records`.

2021-04-22 23:07 UTC, ShaunSHamilton commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/record-collection.md
> +You are given an object representing a part of your musical album collection. Each album has a unique id number as its key and several other properties. Not all albums have complete information.
```suggestion
You are given an object literal representing a part of your musical album collection. Each album has a unique id number as its key and several other properties. Not all albums have complete information.
```

2021-04-22 23:07 UTC, ShaunSHamilton commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/record-collection.md
> +You start with an `updateRecords` function that takes an object containing `records`, an `id`, a `prop` (like `artist` or `tracks`), and a `value`. Complete the function using the rules below to modi
```suggestion
You start with an `updateRecords` function that takes an object literal, `records`, containing the musical album collection, an `id`, a `prop` (like `artist` or `tracks`), and a `value`. Complete the function using the rules below to modify the object passed to the function.
```

2021-04-23 15:07 UTC, jeremylt commented
That rewording makes sense to me.

2021-04-23 19:05 UTC, ShaunSHamilton approved these changes
This LGTM 👍 . Thanks, Jeremy.

2021-04-23 19:50 UTC, Sembauke approved these changes
LGTM 👍 🥇

2021-04-23 19:51 UTC, merged