fix(curriculum): HTML-challenges: links are inconsistent.
freeCodeCamp/freeCodeCamp pull request #41900
Opened 2021-04-22 20:04 UTC by EboranBokaj

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41899

Updated links in Html- challenges from thisislink.com to www.thisislink.com so they are consistent.
Updated regex that broke with the first commit.

2021-04-23 12:23 UTC, EboranBokaj commented
Hi, I hope everything is as it should be. This is my first PR so if there is anything I need to change please let me know, I appreciate the feedback. Thanks!

2021-04-23 17:04 UTC, ieahleen commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/add-images-to-your-website.md
> +assert(/^https:\/\/www.bit\.ly\/fcc-relaxing-cat$/i.test($('img').attr('src')));
the dot needs to be escaped
```suggestion
assert(/^https:\/\/www\.bit\.ly\/fcc-relaxing-cat$/i.test($('img').attr('src')));
```

2021-04-23 17:05 UTC, ieahleen commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements.md
> +assert(/^https?:\/\/www.freecatphotoapp\.com\/?$/i.test($('a').attr('href')));
```suggestion
assert(/^https?:\/\/www\.freecatphotoapp\.com\/?$/i.test($('a').attr('href')));
```

2021-04-23 18:52 UTC, gikf requested changes
Looking at the list of files in issue, there's one missing in PR.

2021-04-23 18:55 UTC, gikf commented
@EboranBokaj for future - it's best to make changes on a separate branch, not the `main` branch of the fork. Take look at point 3 and further at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally

2021-04-26 10:56 UTC, raisedadead commented
> Looking at the list of files in issue, there's one missing in PR.

Hey @gikf thanks for the QA. Do you mind letting us know which one? Thanks.

2021-04-26 11:12 UTC, gikf commented
This one https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/nest-an-anchor-element-within-a-paragraph.md

2021-04-26 11:19 UTC, raisedadead commented
Hi @EboranBokaj can update the one missed file as shared by @gikf above. This is almost good to go. Thanks.

2021-04-26 11:21 UTC, EboranBokaj commented
Hi, I will update it now, sorry I had a lot of work during the weekend...

2021-04-26 11:30 UTC, EboranBokaj commented
Thanks for the feedback @gikf, I will make sure to use a new branch the next time!

2021-04-26 16:54 UTC, gikf approved these changes

2021-04-26 17:04 UTC, raisedadead approved these changes

2021-04-26 17:04 UTC, merged

2021-04-26 17:11 UTC, raisedadead commented
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks @EboranBokaj, for this pull request and contributing to the code-base for the first time.

We will be looking forward for more contributions in future.

Cheers and happy contributing!