fix(curriculum): tabindex order lesson
freeCodeCamp/freeCodeCamp pull request #41901
Opened 2021-04-22 20:59 UTC by moT01

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #36066

Tried a creative solution on this one. Added an element to the page so users always start at the beginning of their tab order.

2021-04-23 08:37 UTC, Sembauke requested changes

2021-04-23 08:37 UTC, Sembauke commented on curriculum/challenges/english/01-responsive-web-design/applied-accessibility/use-tabindex-to-specify-the-order-of-keyboard-focus-for-several-elements.md
> +Another thing to note is that some browsers may place a you in the middle of your tab order when an element is clicked. An element has been added to the page that ensures you will always start at the
```suggestion 
Another thing to note is that some browsers may place you in the middle of your tab order when an element is clicked. An element has been added to the page that ensures you will always start at the beginning of your tab order.
```

2021-04-24 09:14 UTC, Sembauke approved these changes
LGTM 👍

2021-04-26 19:25 UTC, raisedadead approved these changes

2021-04-26 19:25 UTC, merged