Replaced the text with replit.com to Replit and repl.it to Replit/replit.com on the files outside curriculum.
freeCodeCamp/freeCodeCamp pull request #41941
Opened 2021-04-28 16:47 UTC by gmfuster

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41444

I hope this PR is OK.  I forgot to refresh before I changed so got a ton of conflicts and was a bit confused on resolving them, but I think I got it right.  These changes are only for the English curriculum.  Chinese and Spanish still have the repl.it.

2021-04-28 17:17 UTC, ShaunSHamilton requested changes
Thanks, for getting this out.

One minor thing that caught my eye - probably was included a few PRs ago.

2021-04-28 17:17 UTC, ShaunSHamilton commented on curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/personal-library.md
> +-   Use [our Replit starter project](https://replit.com/github/freeCodeCamp/boilerplate-project-library)) to complete your project.
```suggestion
-   Use [our Replit starter project](https://replit.com/github/freeCodeCamp/boilerplate-project-library) to complete your project.
```

2021-04-28 17:19 UTC, ShaunSHamilton commented
Also, you likely had issues, because you are working off of your main branch. This is discouraged, as it soils your main after a merge, and prevents you from easily working on other PRs until this is merged.

Here is the recommended workflow: https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally

2021-04-28 17:20 UTC, raisedadead commented
> I forgot to refresh before I changed so got a ton of conflicts and was a bit confused on resolving them, but I think I got it right.

We recommend using branches to avoid frustrations like this. No worries, I think you are almost in the clear. However please give the contributing docs a good read.

2021-04-29 00:03 UTC, gmfuster commented
@raisedadead  @ShaunSHamilton  Yes I think I only have one branch.  I'll check that out again and try with 2 branches.  I am using GitHub desktop though, I'm guessing that does not matter.  I'll make the additional change about the parenthesis tomorrow.  I think I'll do that one before I try to get 2 branches, just in case I mess it up.  But I'll refresh right before.  Again, thank you for your help.

2021-04-29 09:52 UTC, raisedadead commented
@gmfuster do not worry about this PR. We have added the requested changes. @ShaunSHamilton will review this when he gets a chance. 

But this looks mostly good.

Here is what you should do next:

1. Wait for this PR to be merged.
2. Fix your fork and your local copy on the machine by following these instructions: https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally

You will be needing to this **after** this PR has been merged and **before** you send in your next PR.

2021-04-29 09:52 UTC, raisedadead approved these changes

2021-04-29 10:12 UTC, ShaunSHamilton approved these changes
LGTM 👍 . Thank you, for your contribution. We look forward to more just like it!

2021-04-29 10:13 UTC, merged