fix(client): footer inconsistency when visiting /learn
freeCodeCamp/freeCodeCamp pull request #42096
Opened 2021-05-11 10:29 UTC by saeedtlb

Before this If we navigate to menu and select curriculum we saw Footer and then if we refresh the page the browser would put / at the end of URL and it would look like **/learn/** and this time we wont see the Footer. So I edit the regex and make it to not show Footer even if it has / at the end of URL.

Look at the example which run in prev code and new one:
```diff
- /\/learn\//.test('/learn') // false
+ /\/learn\/?/.test('/learn/') // true
```
So in both situation we wont see Footer on this page.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #41922

2021-05-11 12:55 UTC, ahmadabdolsaheb commented
The rest of the logic would also need to change since we would like to show footer everywhere but challenge pages.
So the logic should be similar to the followings ...
```js
const isChallenge = 
    (splitPath.length === 4 && splitPath[0]) === 'learn' ||
    (splitPath.length === 5 && splitPath[1]) === 'learn';
```

The, do no show footer if (isChallenge).

Additionally, package-lock.json should not be included in this pr.

2021-05-11 13:51 UTC, saeedtlb commented
Oh, I got it. We want to show footer everywhere except the page we can write code. So I test this regex instead of prev one and it would work I think.
```diff
- /\/learn\/?/.test('/learn/')
+ /\/learn\/./.test('/learn/')
```
This regex return true if we have another part besides /learn in URL.

And if we have other parts next to /learn we would still get false from the next condition so in this situations we have Footer but as soon as we enter the challenge page which it'll contain 4 part in URL the next condition will return true as well so we won't get Footer on challenge page.

2021-05-11 23:44 UTC, SAJJAD330 commented
Can we talk in whatsup .  My whatsup +923409094330

2021-05-12 01:05 UTC, paulywill requested changes, later dismissed
Can you re-submit without removing the `package-lock.json` being deleted?

2021-05-12 07:59 UTC, ahmadabdolsaheb commented
The following two paths belong to challenges:

/espanol/learn/responsive-web-design/css-flexbox/use-display-flex-to-position-two-boxes
/learn/responsive-web-design/css-flexbox/use-display-flex-to-position-two-boxes

Everywhere else on learn we would like to have a footer.

As you see they are either 4 or 5 parts to the path. That is the reason we would need to find the path for the challenge and conditionally not show the footer for it.

2021-05-12 09:49 UTC, saeedtlb commented
> The following two paths belong to challenges:
> 
> /espanol/learn/responsive-web-design/css-flexbox/use-display-flex-to-position-two-boxes
> /learn/responsive-web-design/css-flexbox/use-display-flex-to-position-two-boxes
> 
> Everywhere else on learn we would like to have a footer.
> 
> As you see they are either 4 or 5 parts to the path. That is the reason we would need to find the path for the challenge and conditionally not show the footer for it.

If we see the page in English language the challenge pages would have 4 parts but if the language is Chinese or Español the challenge pages got 5 parts(exp: /espanol/learn/).

So the first condition check that we got /learn in URL. The second condition is like below which contain 2 part:
`
const isSuperBlock =
    /2|3/g.test(splitPath.length) ||
    (splitPath.length === 4 && splitPath[1]) === 'learn';
`

The first part says if we have 3 or 4 part in URL return true.
The second part says if we have 4 parts in URL **AND** the second part is equal to "learn" then return true;

@ahmadabdolsaheb

2021-05-12 11:02 UTC, ahmadabdolsaheb commented
Here are a few points to consider.
1. we would like to find challenges instead of superblocks this time which means the path would be 4 or 5.
2. the length of the path itself is not an indicator of a challenge path. the length should be considered in relation to where learn is placed in the path.
3. I suggest using the above-mentioned suggestion to find a challenge path.
4. The pr does not need to alter the package-lock.

2021-05-20 11:42 UTC, ahmadabdolsaheb commented
@saeedtlb how is the progress on your side. let me know if I could be of any help.

2021-05-21 11:34 UTC, saeedtlb commented
Hi,
Thank you for following up with me. Actually I am not familiar with gatsby
structure and workflow so I decided to work on the subject that I've
experienced on them(My personal projects are created with next and
create-react-app).
I'm actually a beginner on open source so I'm looking for a good open
source project to create my github and C.V look better.
By the way thanks for your kind words.

On Thu, May 20, 2021 at 4:12 PM Ahmad Abdolsaheb ***@***.***>
wrote:

> @saeedtlb <https://github.com/saeedtlb> how is the progress on your side.
> let me know if I could be of any help.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/42096#issuecomment-845017606>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALZEK7YVD7Z5W4CVLJGGG7LTOTYTVANCNFSM44VBMTGQ>
> .
>

2021-05-22 11:52 UTC, ahmadabdolsaheb commented
@saeedtlb, no worries. I went ahead and added what we have discussed to this pr. 
There are other issues that you might be interested in. Let me know if I could be of any help.

2021-05-22 12:36 UTC, saeedtlb commented
@ahmadabdolsaheb <https://github.com/ahmadabdolsaheb> , Thank you so much.
You're so kind.

On Sat, May 22, 2021 at 4:22 PM Ahmad Abdolsaheb ***@***.***>
wrote:

> @saeedtlb <https://github.com/saeedtlb>, no worries. I went ahead and
> added what we have discussed to this pr.
> There are other issues that you might be interested in. Let me know if I
> could be of any help.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/42096#issuecomment-846397250>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALZEK7ZJWEWVGJ5ECPQIQ5DTO6LIDANCNFSM44VBMTGQ>
> .
>

2021-05-22 12:51 UTC, Sembauke approved these changes
Hey @saeedtlb,

LGTM

Congrats on your first pull request we appreciate your work 🥇
I hope to see more of you in the future 👍

2021-05-22 16:18 UTC, saeedtlb commented
Thanks Bro @Sembauke,
I learned lot from your code.

2021-05-23 20:17 UTC, ahmadabdolsaheb approved these changes

2021-05-23 22:30 UTC, merged