feat(curriculum): add solution
freeCodeCamp/freeCodeCamp pull request #42130
Opened 2021-05-14 08:14 UTC by gikf

- Adds solution.
- Ensures tests are using test matrices defined in background.
- Positions matrix in example evenly between paragraphs.
- Slightly improves description text.
- Tested on local fork.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

2021-05-14 16:17 UTC, nhcarrigan requested changes

2021-05-14 16:17 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-81-path-sum-two-ways.md
> +Find the minimal path sum from the top left to the bottom right by only moving right and down in `matrix`, a 2D array representing matrix. Maximum matrix size used in the tests will be 80 by 80.
```suggestion
Find the minimal path sum from the top left to the bottom right by only moving right and down in `matrix`, a 2D array representing a matrix. The maximum matrix size used in the tests will be 80 by 80.
```
Nitpicks.

2021-05-17 15:53 UTC, nhcarrigan approved these changes
Looks good to me.

2021-05-17 17:43 UTC, moT01 approved these changes
LGTM @gikf 🎉 Thanks for contributing to freeCodeCamp 🎉

2021-05-17 17:43 UTC, merged