converted JSX component to Pascal Case
freeCodeCamp/freeCodeCamp pull request #42157
Opened 2021-05-17 04:03 UTC by kailaa-sri

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #38850

In ToggleSetting.js and ToggleButton.js changed the imported JSX to Pascal case

2021-05-17 07:07 UTC, raisedadead requested changes
Did you mean to refer to `#38850` intentionally?

2021-05-17 08:57 UTC, kailaa-sri commented
> Did you mean to refer to `#38850` intentionally?
![image](https://user-images.githubusercontent.com/59409693/118461934-cb6f4880-b71b-11eb-9d9a-3b173eefa3dd.png)

No but it resolves these warnings.

2021-05-17 09:11 UTC, ojeytonwilliams requested changes
Could you apply `npm run format` to this?  I'm not sure why the commit hook failed, but this won't pass the linting step.

2021-05-17 09:11 UTC, ojeytonwilliams commented on client/src/components/helpers/ToggleButton.js
> +    ToggleButton as tb
```suggestion
    ToggleButtonGroup,
    ToggleButton as BootstrapToggleButton
```
How about this?  It's a little verbose, but bsbg and tb don't mean anything unless you look them up or already know what they mean.

2021-05-17 09:31 UTC, ojeytonwilliams commented
@kailaa-sri you're welcome to push those changes as a commit to this PR if you'd like.  There's no need to open a new one.

2021-05-17 13:14 UTC, raisedadead commented
> No but it resolves these warnings.

Could you remove the references to the unrelated issue. You can edit your last commit after you have made changes with `git commit --amend` and push to the same PR branch with `git push origin <branch name> --force`

Thanks.

2021-05-29 16:14 UTC, raisedadead commented
Please reopen a fresh PR when ready.

2021-05-29 16:14 UTC, closed without merging