fix(curriculum): rework Project Euler 85
freeCodeCamp/freeCodeCamp pull request #42181
Opened 2021-05-18 16:43 UTC by gikf

- Reworks challenge to use argument in function call.
- Adds solution.
- Related to #40896.
- Tested on local fork.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

2021-05-20 13:50 UTC, Sembauke requested changes

2021-05-20 13:50 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-85-counting-rectangles.md
> +Although there may not exists rectangular grid that contains exactly `n` rectangles, find the area of the grid with the nearest solution.
I suggest placing "a" between exists and rectangular

2021-05-24 17:43 UTC, raisedadead approved these changes

2021-05-24 17:43 UTC, merged

2021-05-31 22:08 UTC, moT01 commented
I added this solution to the forum guide article