Add color palette to tailwind config file
freeCodeCamp/freeCodeCamp pull request #42198
Opened 2021-05-20 23:08 UTC by ChrisPrzR

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x] All the files I changed are in the same world language, for example: only English changes, or only Chinese changes, etc.

Closes #42186

2021-05-21 07:47 UTC, gikf commented
Hey @ChrisPrzR,

We would love to be able to merge your changes but it looks like there are an errors with the style linting reported by CI checks. ⚠️

Once you resolve these issues, we will be able to review your PR and merge it. 😊

2021-05-21 12:55 UTC, nhcarrigan requested changes
Hey there @ChrisPrzR 

These suggestions should resolve the linting issues.

2021-05-21 12:55 UTC, nhcarrigan commented on tools/ui-components/tailwind.config.js
> +      //Accent Colors - Primary
```suggestion
      // Accent Colors - Primary
```

2021-05-21 12:55 UTC, nhcarrigan commented on tools/ui-components/tailwind.config.js
> +      //Accent Colors - Secondary
```suggestion
      // Accent Colors - Secondary
```

2021-05-21 12:55 UTC, nhcarrigan commented on tools/ui-components/tailwind.config.js
> +      //Colors in variables.css
```suggestion
      // Colors in variables.css
```

2021-05-21 12:55 UTC, nhcarrigan commented on tools/ui-components/tailwind.config.js
> +      red: '#ffadad',
```suggestion
      red: '#ffadad',
```

2021-05-21 12:55 UTC, nhcarrigan commented on tools/ui-components/tailwind.config.js
> +      yellowLight: '#ffc300',
```suggestion
      yellowLight: '#ffc300'
```

2021-05-21 14:16 UTC, ChrisPrzR commented
@gikf @nhcarrigan  Thank you! I've applied the suggested changes .

2021-05-21 18:30 UTC, huyenltnguyen requested changes
@ChrisPrzR Thank you for this PR and for the fix in variables.css ealier!

There are a couple more changes we need to make, and the PR will be good to go then.

As you can see in this file, we are having quite a lot of colors with the name "dark", but some of them are actually dark, as in shade; while the other refer to the dark theme. We will need to work on a new set of color tokens (partially discussed in https://github.com/freeCodeCamp/freeCodeCamp/issues/42186#issuecomment-845829904), but to avoid confusion for now, I'd suggest:
- If the color is dark in shade, we name it `dark[Color]`
- If the color is used in dark theme, we name it `[color]Dark`

2021-05-21 18:47 UTC, ChrisPrzR commented
@huyenltnguyen these changes look great, I like the readability improvement. Would you suggest leaving dark colors used in both themes as dark[Color] ?

2021-05-21 19:06 UTC, huyenltnguyen commented
Yes, leaving them `dark[Color]` would be fine, although I could imagine it would cause confusion for other readers still, with all the "dark" suffixes and prefixes.

But don't worry about it. We will change them soon as we add the dark theme support to our component library 🙂

2021-05-21 19:09 UTC, huyenltnguyen approved these changes
LGTM 👍 

Thank you again for the PR and we are looking forward to your future contributions.

Stay safe and happy coding!

2021-05-22 04:38 UTC, nhcarrigan approved these changes

2021-05-22 04:39 UTC, nhcarrigan commented
Before I merge, @huyenltnguyen and @ahmadabdolsaheb can you confirm this does resolve the linked issue?

2021-05-22 07:53 UTC, huyenltnguyen commented
Thanks for checking @nhcarrigan! 

Some idea came up after we opened the issue up for contributions, and the puzzle has more pieces now. This PR adds one in, so I have replaced the word "closes" to "ref" in the PR description to keep the issue around. I will go back and update the label of the issue to "discussing".

2021-05-22 10:03 UTC, merged