Remove prisim from app chunk
freeCodeCamp/freeCodeCamp pull request #42230
Opened 2021-05-24 10:27 UTC by ahmadabdolsaheb

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-05-24 11:34 UTC, ShaunSHamilton commented
Hey Ahmad,

There is a good chance this is just my run of GitPod, but I thought I would mention it. I cannot view the solutions (I do see Prism in the webpack internals):
![image](https://user-images.githubusercontent.com/51722130/119341665-f877aa00-bc8b-11eb-8123-c5218ff1ff93.png)

I also see this error (likely nothing more than #39719 )
```console
Warning: Failed prop type: Invalid prop `files` of type `object` supplied to `SolutionViewer`, expected an array.
    in SolutionViewer (created by ProjectModal)
    in ProjectModal (created by CertificationSettings)
    in section (created by CertificationSettings)
    in CertificationSettings (created by withI18nextTranslation(CertificationSettings))
```

2021-05-24 12:51 UTC, raisedadead requested changes

2021-05-24 12:51 UTC, raisedadead commented on client/src/components/profile/components/TimeLine.js
> +// import SolutionViewer from '../../SolutionViewer/SolutionViewer';
```suggestion
```

Drop the comment.

2021-05-25 07:54 UTC, ahmadabdolsaheb commented
> Hey Ahmad,
> 
> There is a good chance this is just my run of GitPod, but I thought I would mention it. I cannot view the solutions (I do see Prism in the webpack internals):

That is interesting because I do not see the issue when developing and building locally.

2021-05-25 09:15 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-05-25 09:42 UTC, ShaunSHamilton approved these changes
This LGTM 👍 
_Turns out all I needed to do was refresh the page_ - same thing happens on `.dev` 🤦

2021-05-25 09:55 UTC, raisedadead commented
> Turns out all I needed to do was refresh the page - same thing happens on .dev 

Can you please elaborate, what you mean by "same thing happens on .dev"? This has not been shipped yet. Did you mean whatever issue you were reporting was pre-existing?

2021-05-25 10:09 UTC, ShaunSHamilton commented
> Did you mean whatever issue you were reporting was pre-existing?

Yes. Oliver suggested it has to do with Redux not refreshing. What I experience is:
1) Complete a JS Project (Palindrome Checker)
2) Submit project
3) Navigate to `/settings`
4) Click on `Show Code` button in Certification section of settings page for submitted project
5) See modal appear saying "[no solution]"
6) Be sad, and bother Oliver. Refresh page
7) Click `Show Code` again
8) Modal appears with code - sadness diminishes

This happens on both a Gitpod instance of this PR, as well as on `.dev` for me. Does not happen on current production, but it would be most accurate to test with a new account which I have not.

2021-05-25 10:15 UTC, raisedadead commented
We do not care about any developer environments, what I am interested in why would you have a difference in experience between staging and production.

2021-06-03 14:24 UTC, raisedadead approved these changes

2021-06-03 14:25 UTC, merged