Typo in Rosetta Code Challenge : "Sudoku"
freeCodeCamp/freeCodeCamp pull request #42253
Opened 2021-05-26 07:56 UTC by DySQRD

It is stated blank fields are represented by 0s when they are actually -1s.

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-05-30 06:21 UTC, gikf requested changes

2021-05-30 06:21 UTC, gikf commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/sudoku.md
> +Write a function to solve a partially filled-in normal 9x9 [Sudoku](https://en.wikipedia.org/wiki/Sudoku) grid and return the result. The blank fields are represented by -1s. [Algorithmics of Sudoku]
```suggestion
Write a function to solve a partially filled-in normal 9x9 [Sudoku](https://en.wikipedia.org/wiki/Sudoku) grid and return the result. The blank fields are represented by `-1`. [Algorithmics of Sudoku](https://en.wikipedia.org/wiki/Algorithmics_of_sudoku) may help implement this.
```
Just a small change as that's reference to the code,, and I think pluralizing with 's' can be left out.

2021-06-08 06:04 UTC, raisedadead approved these changes
The OP seems to have gotten busy, @gikf I have gone ahead and applied the requested changes, please merge if happy.

2021-06-08 08:49 UTC, gikf approved these changes

2021-06-08 08:50 UTC, merged