fix(curriculum): rework Project Euler 97
freeCodeCamp/freeCodeCamp pull request #42276
Opened 2021-05-27 15:42 UTC by gikf

- Reworks challenge to use argument in function call.
- Adds solution.
- Changes expected return type to string, otherwise for cases where 10th digit from the end is `0`, it wasn't possible to show all 10 last digits.
- Changes slightly challenge to allow adding more tests.
- Adds more tests. Primes for tests are taken from short list at https://primes.utm.edu/primes/download.php
- Changes function name to include word `large` instead of shortened `lrg`.
- Uses MathJax to improve look of math notation.
- Related to #40896.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2021-05-27 18:18 UTC, nhcarrigan requested changes
Some nitpicks.

2021-05-27 18:18 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-97-large-non-mersenne-prime.md
> +Find the last ten digits of non-Mersenne prime in the form $multiplier × 2^{power} + 1$.
```suggestion
Find the last ten digits of that non-Mersenne prime in the form $multiplier × 2^{power} + 1$.
```

2021-05-27 18:18 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-97-large-non-mersenne-prime.md
> +`largeNonMersennePrime(19, 6833086)` should return string `3637590017`.
```suggestion
`largeNonMersennePrime(19, 6833086)` should return the string `3637590017`.
```

2021-05-27 18:18 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-97-large-non-mersenne-prime.md
> +`largeNonMersennePrime(27, 7046834)` should return string `0130771969`.
```suggestion
`largeNonMersennePrime(27, 7046834)` should return the string `0130771969`.
```

2021-05-27 18:18 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-97-large-non-mersenne-prime.md
> +`largeNonMersennePrime(6679881, 6679881)` should return string `4455386113`.
```suggestion
`largeNonMersennePrime(6679881, 6679881)` should return the string `4455386113`.
```

2021-05-27 18:18 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-97-large-non-mersenne-prime.md
> +`largeNonMersennePrime(28433, 7830457)` should return string `8739992577`.
```suggestion
`largeNonMersennePrime(28433, 7830457)` should return the string `8739992577`.
```

2021-05-27 19:29 UTC, nhcarrigan approved these changes

2021-05-27 19:38 UTC, Sembauke approved these changes

2021-05-27 19:38 UTC, merged

2021-05-31 22:17 UTC, moT01 commented
I added this solution to the forum guide article