Feat : Typescript migration for files under client/src/component/search folder.
freeCodeCamp/freeCodeCamp pull request #42327
Opened 2021-06-02 05:37 UTC by krishna-saurav

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Below changes are implemented:
- Renamed the files to .tsx/.ts
- Added types/interface as required.
- Removed the Proptypes
- tested the code in gitpod
- Renamed the files in kebab case
- Formatted the files using prettier
-Resolved most of the Eslint issues.

2021-06-02 05:42 UTC, krishna-saurav commented
@ojeytonwilliams  Please review.

2021-06-04 18:45 UTC, samarmohan commented
Hey, can you fix the conflicts, please?

2021-06-05 04:16 UTC, krishna-saurav commented
> Nice job(!), but can you fix the conflicts, please? Thank you!



> Nice job(!), but can you fix the conflicts, please? Thank you!

@samarmohan  done!!

2021-06-17 12:04 UTC, raisedadead reviewed
Hey there,

Thank you for taking the time to contribute to the TypeScript migration. 

The main issue has been updated a lot over the last few days, and so we suggest you re-read it and update this pull request to match if you have the time.

The main goals for a PR are:
- [ ] Changing the filename from `PascalCase` to `kebab-case` and ensuring that the imports in code are all still valid.
- [ ] Changing the file extension to .tsx (if a file has React JSX syntax)
- [ ] Fixing as many TypeScript and Eslint errors as you can while refactoring the code.

If you need any assistance, please reach out in our [contributing chat room](https://chat.freecodecamp.org/channel/contributors).

2021-06-24 14:24 UTC, ShaunSHamilton requested changes
Hello there. Thank you, for taking the time to make these changes.

I do not think we should be making any changes to `redux/` files, at this time. So, would you mind reverting the changes to those files?

2021-06-24 14:32 UTC, krishna-saurav commented
@ShaunSHamilton  np at all. I'll revert the changes related to redux.

2021-06-24 21:14 UTC, nhcarrigan requested changes
Hey there,

Looks like a stray merge conflict made it into this PR.

2021-06-24 21:14 UTC, nhcarrigan commented on client/src/components/search/searchBar/search-bar.tsx
> +<<<<<<< HEAD:client/src/components/search/searchBar/SearchBar.js
Merge conflict starts here

2021-06-24 21:14 UTC, nhcarrigan commented on client/src/components/search/searchBar/search-bar.tsx
> +>>>>>>> 918483ed0c (typescript migration for files under search folder):client/src/components/search/searchBar/search-bar.tsx
Merge conflict ends here.

2021-06-24 21:34 UTC, krishna-saurav commented on client/src/components/search/searchBar/search-bar.tsx
> +<<<<<<< HEAD:client/src/components/search/searchBar/SearchBar.js
Yes. Resolved it.

2021-06-25 15:57 UTC, merged