fix(curriculum): rework Project Euler 43
freeCodeCamp/freeCodeCamp pull request #42347
Opened 2021-06-03 11:55 UTC by gikf

- Reworks challenge to use argument in function call.
- Changes expected return type to match more original challenge and allow for easier adding more tests. This resulted however with some wording which might not be currently as clear as desired. Any help in that is appreciated.
- Adds more tests.
- Adds solution.
- Uses MathJax to improve look of math notation in example.
- Related to #40896.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2021-06-05 08:06 UTC, Sembauke requested changes

2021-06-05 08:06 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-43-sub-string-divisibility.md
> +Find sum of the all 0 to `n` pandigital numbers with sub-strings fulfilling `n - 2` of these divisibility properties.
```suggestion
Find the sum of all 0 to `n` pandigital numbers with sub-strings fulfilling `n - 2` of these divisibility properties.
```

2021-06-05 14:02 UTC, Sembauke approved these changes

2021-06-08 06:13 UTC, raisedadead approved these changes

2021-06-08 06:13 UTC, merged