fix(curriculum): improve description and tests descriptions
freeCodeCamp/freeCodeCamp pull request #42387
Opened 2021-06-06 19:06 UTC by gikf

This ended up a bit more elaborate than expected.
- Clarifies a bit what will be input and what is expected output.
- Adds example.
- Adds, for consistency, sorting of output array with closest pair. Both in solution and in description.
- Adds third test, after adjusting existing third array with points to not have multiple point pairs with the same - closest - distance. Otherwise it would be needed to include in description how deal with such cases, This would make it even more complicated.
- Makes tests descriptions more explicit, including expected values.
- Uses MathJax to improve look of math notation.
- Removes external links, per #40749.
- For consistency in background code positions answer for each points array below of the array.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2021-06-11 18:53 UTC, moT01 requested changes
Found one little typo and reworded that sentence. It doesn't have to be reworded to what I want - I thought it sounded a little better - but, the typo should be fixed. Other than that, LGTM 🎉 

I added this solution to the forum guide article

2021-06-11 18:53 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/closest-pair-problem.md
> +**Note:** In the `pair` array, sort poinits by the `x` coordinate, incrementing.
```suggestion
**Note:** Sort the `pair` array by their `x` values in incrementing order.
```

2021-06-11 19:54 UTC, gikf commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/closest-pair-problem.md
> +**Note:** In the `pair` array, sort poinits by the `x` coordinate, incrementing.
Suggestion is definitely better :+1:

2021-06-11 21:42 UTC, moT01 commented
what

2021-06-11 22:10 UTC, moT01 approved these changes
LGTM 🎉

2021-06-14 06:31 UTC, raisedadead approved these changes

2021-06-14 06:31 UTC, merged