fix(curriculum): improve description and tests descriptions
freeCodeCamp/freeCodeCamp pull request #42408
Opened 2021-06-08 13:49 UTC by gikf

- Makes tests descriptions more explicit.
- Adds example of input string to description.
- Moves few sentences to separate general case from example.
- Adds test for expected return type.
- Removes external links, per #40749.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2021-06-08 14:50 UTC, Sembauke requested changes

2021-06-08 14:50 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/topological-sort.md
> +Input of the function will be a multiline string, each line will consist of name of the library, followed by it dependencies (if exist).
```suggestion
The input of the function will be a multiline string, each line will consist of the name of the library, followed by its dependencies (if exist).
```

2021-06-08 14:50 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/topological-sort.md
> +Write a function that will return list with valid compile order of libraries from their dependencies.
```suggestion
Write a function that will return a list with valid compile order of libraries from their dependencies.
```

2021-06-11 18:39 UTC, moT01 approved these changes
LGTM 🎉 

I added this solution to the forum guide article

2021-06-14 06:31 UTC, raisedadead approved these changes

2021-06-14 06:31 UTC, merged