Fixed minor indentation for readability
freeCodeCamp/freeCodeCamp pull request #42451
Opened 2021-06-12 05:11 UTC by dogfood654

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

*Fixed minor indentation error noticed when doing tutorial*

Before
```js
function lookUpProfile(name, prop){
// Only change code below this line

// Only change code above this line
}
```

After
```js
function lookUpProfile(name, prop) {
    // Only change code below this line

    // Only change code above this line
}
```

2021-06-14 16:00 UTC, gikf requested changes
Could you change indentation to the 2 spaces, as that's the preferred value for the code?

2021-06-16 10:52 UTC, gikf approved these changes

2021-06-16 13:35 UTC, ShaunSHamilton approved these changes
This LGTM 👍

2021-06-16 13:35 UTC, merged

2021-06-16 13:35 UTC, ShaunSHamilton commented
Congrats on your first pull request (PR)! 🎉

Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝