fix(client): downgrade normalize-url to fix Safari issue
freeCodeCamp/freeCodeCamp pull request #42490
Opened 2021-06-14 20:06 UTC by moT01

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42431

This seems to be the cause of the issues. More context:
https://github.com/sindresorhus/normalize-url/issues/105

It would be nice if another Safari user could test this out.

2021-06-14 22:59 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

Further context: https://github.com/sindresorhus/normalize-url#install Also, 4.5.1 has the latest security fix, so it shouldn't be a regression.

2021-06-15 07:21 UTC, raisedadead requested changes
While you are at this can you please update the renovate config to have this ignored?

2021-06-15 07:30 UTC, ojeytonwilliams commented
We'd want to let it keep creating minor and patch updates, though. https://docs.renovatebot.com/configuration-options/#allowedversions should do the trick.

2021-06-15 07:32 UTC, ojeytonwilliams commented
Also, since the problem is quite frustrating for Safari users, can we get this merged soon?

2021-06-15 07:47 UTC, raisedadead commented
Sure go ahead and add the config as you see fit and merge.

2021-06-15 09:06 UTC, merged