fix(client): store challenge panes sizes
freeCodeCamp/freeCodeCamp pull request #42519
Opened 2021-06-15 21:39 UTC by victor-duarte

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #39088

- Base on [Re-Flex Storage demo](https://github.com/leefsmp/Re-Flex/blob/master/src/demo/demo.jsx#L711) example
- Aims to add functionality on desktop view

### Steps to test

1. Open challenge view
2. Resize a pane
3. Either refresh window or go to next challenge

**Ouput**
Window should retain resize made by user

2021-06-16 06:35 UTC, raisedadead requested changes
Thanks for the PR. Mind taking a look at the tests, please?

2021-06-16 20:19 UTC, victor-duarte commented
> Thanks for the PR. Mind taking a look at the tests, please?

@raisedadead, a code update has been submitted and test are passing.

Any comments or suggestions are welcome.

2021-06-17 07:24 UTC, raisedadead reviewed
Thanks @victor-duarte - I have requested a review from the team and someone will get back to you if further changes are needed. 

Thanks a lot for working on this.

2021-06-17 09:00 UTC, ojeytonwilliams requested changes
Thanks for taking the time to put this together, @victor-duarte. It really is a nice PR.

I have made a few, minor suggestions on things that could be refactored, but I think it's already in a good state.

2021-06-17 14:16 UTC, victor-duarte commented on client/src/templates/Challenges/classic/Show.js
> +    flex: 0.5
You are correct. It has been updated to use the original value. 👍🏻

2021-06-17 14:29 UTC, victor-duarte commented on client/src/templates/Challenges/classic/Show.js
> +import { isBrowser } from '../../../../utils';
Gotcha, this is cleaner and consistent.

2021-06-17 15:05 UTC, ojeytonwilliams approved these changes
Thanks for making those changes @victor-duarte 

LGTM :+1:

2021-06-17 18:20 UTC, raisedadead approved these changes

2021-06-17 18:20 UTC, merged

2021-06-17 18:21 UTC, raisedadead commented
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks, @victor-duarte, for this pull request and for contributing to the code-base for the first time.

We will be looking forward to more contributions in future.

Cheers and happy contributing!