fix(curriculum): improve description and tests descriptions
freeCodeCamp/freeCodeCamp pull request #42546
Opened 2021-06-17 12:56 UTC by gikf

- Clarifies expected input and output.
- Replaces example in description with smaller one, to keep the current one as a main test.
- Adds test for thinning smaller image.
- Replaces image in the seed code for smaller one.
- Replaces html with markdown and MathJax.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2021-06-23 17:00 UTC, nhcarrigan requested changes
Couple of nitpicks.

2021-06-23 17:00 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/zhang-suen-thinning-algorithm.md
> +`thinImage(testImage1)` should return thinned image as in example.
```suggestion
`thinImage(testImage1)` should return a thinned image as in the example.
```

2021-06-23 17:00 UTC, nhcarrigan commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/zhang-suen-thinning-algorithm.md
> +`thinImage(testImage2)` should return thinned image.
```suggestion
`thinImage(testImage2)` should return a thinned image.
```

2021-06-24 14:38 UTC, raisedadead approved these changes

2021-06-28 07:46 UTC, merged