Ensure the props variable is present, but doesn't have to be the only word
freeCodeCamp/freeCodeCamp pull request #42577
Opened 2021-06-20 12:09 UTC by kealanparr

Checklist:
- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod. ![image](https://user-images.githubusercontent.com/25173414/122673402-36eb8080-d1c8-11eb-8c3b-fa4b0427309a.png)

I was working on "Render State in the User Interface" React challenge in the "Front End Libraries Development" certification

The tests read as such: 
MyComponent should have a key name with value freeCodeCamp stored in its state.
MyComponent should render an h1 header enclosed in a single div.
The rendered h1 header should contain text rendered from the component's state.

I passed the first two, but didn't pass the third, and eventually worked out my code looked like the below:

![ok1](https://user-images.githubusercontent.com/25173414/122673396-2affbe80-d1c8-11eb-9346-7bf03d8c91f2.JPG)
![ok2](https://user-images.githubusercontent.com/25173414/122673398-2b985500-d1c8-11eb-9340-8d513684c868.JPG)

I looked at the test's code and saw why I failed the third. I could ONLY include the string "freeCodeCamp" but that isn't explained in the test.
The test isn't descriptive as by the tests definition, my h1 header did contain the name rendered from the state.

I think it would be helpful if we either:
1) Rename the test to explain the h1 header should ONLY contain the name rendered from the state
2) Just check that the word appears somewhere in the string

I personally thought number 2 made more sense, and this prompted me to create the attached PR.

Thanks!

2021-06-20 12:55 UTC, ShaunSHamilton requested changes
Hey there,

Thank you, for taking the time to open this PR.

Would you mind clarifying why you are changing one of the tests you passed? I understand why the code in the screenshot did not pass the tests. However, it did pass this test.

The first test should not change, as the instructions are quite clear the `value` of `this.state.name` must be `freeCodeCamp`.

2021-06-20 13:16 UTC, gikf commented
If really needed, I'd consider going with option number 1. Note in the instructions seems to also put emphasis that `h1` should include only value from state.

2021-06-20 13:31 UTC, kealanparr commented
@ShaunSHamilton  -> My mistake! I jumped the gun and edited the wrong test.

@gikf -> I have edited the test assertion to be more descriptive. I did notice the instructions were clear, I thought thought the test assertion could be made a little clearer too.

I know this will need translations, but what do you think about the English wording?

2021-06-20 22:22 UTC, ShaunSHamilton approved these changes
This makes sense to me 👍 . Thank you, for making this PR.

2021-06-20 22:26 UTC, ShaunSHamilton commented
For future PRs, please read the contributors docs here: https://contribute.freecodecamp.org/#/

Specifically, read about:
- commit message format
- PR naming convention
- working off a new branch (once this is merged, your `main` branch will be soiled for other PRs)

If you have any issues with contributing, be sure to join us on the [contributors channel](https://chat.freecodecamp.org/channel/contributors), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

2021-06-21 04:29 UTC, gikf approved these changes
Looks good! :+1:

2021-06-21 04:29 UTC, merged

2021-06-21 11:02 UTC, kealanparr commented
Thanks very much to the both of you.
The specific reading you mentioned is noted.