Feat/component typescript migration
freeCodeCamp/freeCodeCamp pull request #42585
Opened 2021-06-21 16:18 UTC by sharmaabhinav

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-06-21 16:38 UTC, ShaunSHamilton requested changes
Hello there. Thank you, for taking the time to contribute.

We would appreciate general better naming conventions. We do not have much of a guide for this _yet_ . The main reason for this is when we are using text search, it makes it easier to find things, when the names are unique. Thank you, again.

2021-06-21 16:38 UTC, ShaunSHamilton commented on client/src/components/AppMountNotifier.tsx
> +class AppMountNotifier extends Component<MyProps> {
```suggestion
type AppMountNotifierProps = {
  appMount: () => void;
  render: () => ReactNode;
};

class AppMountNotifier extends Component<AppMountNotifierProps> {
```

2021-06-21 16:57 UTC, sharmaabhinav commented on client/src/components/AppMountNotifier.tsx
> +class AppMountNotifier extends Component<MyProps> {
Thanks for point out . Fixed

2021-06-21 17:43 UTC, ShaunSHamilton commented
Hey there,

Thank you for taking the time to contribute to the TypeScript migration.

The main issue has been updated a lot over the last few days, and so we suggest you re-read it and update this pull request to match if you have the time.

The main goals for a PR are:

- [ ] Changing the filename from PascalCase to kebab-case and ensuring that the imports in code are all still valid.
- [x] Changing the file extension to .tsx (if a file has React JSX syntax)
- [x] Fixing as many TypeScript and Eslint errors as you can while refactoring the code.
If you need any assistance, please reach out in our contributing chat room.

2021-06-22 13:01 UTC, sharmaabhinav commented
> Hey there,
> 
> Thank you for taking the time to contribute to the TypeScript migration.
> 
> The main issue has been updated a lot over the last few days, and so we suggest you re-read it and update this pull request to match if you have the time.
> 
> The main goals for a PR are:
> 
> * [x]  Changing the filename from PascalCase to kebab-case and ensuring that the imports in code are all still valid.
> * [x]  Changing the file extension to .tsx (if a file has React JSX syntax)
> * [x]  Fixing as many TypeScript and Eslint errors as you can while refactoring the code.
>   If you need any assistance, please reach out in our contributing chat room.

Took care of file name change also

2021-06-24 19:59 UTC, ShaunSHamilton requested changes
Type packages should not be installed in the root directory. These changes can be reverted, as the package is already installed on `next`.

2021-06-25 12:46 UTC, ShaunSHamilton approved these changes
This LGTM 👍

2021-06-25 14:45 UTC, merged