fix(curriculum): clean-up Project Euler 101-120
freeCodeCamp/freeCodeCamp pull request #42597
Opened 2021-06-22 13:32 UTC by gikf

- Cleans description.
- Changes generic `eulerXXX` function name.
- Adds missing test data.
- Adds placeholders for images.
- Uses MathJax, a lot.
- Related to #40896.
- Challenge 102 is already reworked and didn't need clean-up.

Should images be committed to https://github.com/freeCodeCamp/cdn? Other Project Euler challenges having images seem to have them somewhere else, ie. https://cdn-media-1.freecodecamp.org/project-euler/right-triangles-integer-coordinates-2.png

- [ ] Add images
https://projecteuler.info/project/images/p107_1.png
https://projecteuler.info/project/images/p107_2.png
https://projecteuler.info/project/images/p109.png
https://projecteuler.info/project/images/p114.png
https://projecteuler.info/project/images/p116_1.png
https://projecteuler.info/project/images/p116_2.png
https://projecteuler.info/project/images/p116_3.png
https://projecteuler.info/project/images/p117.png

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2021-06-22 16:20 UTC, nhcarrigan commented
> Should images be committed to https://github.com/freeCodeCamp/cdn? Other Project Euler challenges having images seem to have them somewhere else, ie. https://cdn-media-1.freecodecamp.org/project-euler/right-triangles-integer-coordinates-2.png

Those are on our S3 instance, I believe. @raisedadead would you rather these images go on S3 or on our CDN repo?

2021-06-28 07:48 UTC, raisedadead commented
Sorry for the delay in the reply, I think we should put all the curriculum-related images on the CDN repo.

2021-06-29 09:39 UTC, Sembauke requested changes

2021-06-29 09:39 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-109-darts.md
> +At the centre of the board are two concentric circles called the bull region, or bulls-eye. The outer bull is worth 25 points and the inner bull is a double, worth 50 points.
```suggestion
At the center of the board are two concentric circles called the bull region, or bulls-eye. The outer bull is worth 25 points and the inner bull is a double, worth 50 points.
```

2021-06-29 09:39 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-109-darts.md
> +There are many variations of rules but in the most popular game the players will begin with a score 301 or 501 and the first player to reduce their running total to zero is a winner. However, it is n
```suggestion
There are many variations of rules but in the most popular game the players will begin with a score of 301 or 501 and the first player to reduce their running total to zero is a winner. However, it is normal to play a "doubles out" system, which means that the player must land a double (including the double bulls-eye at the center of the board) on their final dart to win; any other dart that would reduce their running total to one or lower means the score for that set of three darts is "bust".
```

2021-06-29 09:39 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-109-darts.md
>  Note that D1 D2 is considered different to D2 D1 as they finish on different doubles. However, the combination S1 T1 D1 is considered the same as T1 S1 D1. In addition we shall not include misses in
```suggestion
Note that D1 D2 is considered different from D2 D1 as they finish on different doubles. However, the combination S1 T1 D1 is considered the same as T1 S1 D1. In addition, we shall not include misses in considering combinations; for example, D3 is the same as 0 D3 and 0 0 D3. Incredibly there are 42336 distinct ways of checking out in total. How many distinct ways can a player checkout with a score less than 100?
```

2021-06-29 09:39 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/project-euler/problem-116-red-green-or-blue-tiles.md
> +Assuming that colours cannot be mixed there are 7 + 3 + 2 = 12 ways of replacing the black tiles in a row measuring five units in length. How many different ways can the black tiles in a row measurin
```suggestion
Assuming that colors cannot be mixed there are 7 + 3 + 2 = 12 ways of replacing the black tiles in a row measuring five units in length. How many different ways can the black tiles in a row measuring fifty units in length be replaced if colors cannot be mixed and at least one colored tile must be used?
```

2021-06-29 19:03 UTC, gikf commented
Blocked waiting for https://github.com/freeCodeCamp/cdn/pull/75

2021-06-29 19:05 UTC, raisedadead approved these changes
The CDN PR has been merged.

2021-06-30 12:25 UTC, Sembauke approved these changes

2021-06-30 12:25 UTC, merged