Update object keys referenced in instructions to match provided object
freeCodeCamp/freeCodeCamp pull request #42613
Opened 2021-06-23 22:23 UTC by braxex

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Because each movie object has both `Rated` and `imdbRating` key/value pairs, simply referencing `rating` could be confusing to campers. IMO explicitly referencing the keys by name (`Title` and `imdbRating`) removes ambiguity in the non-important part of this challenge and helps campers focus on learning about `.map()`.

2021-06-24 03:50 UTC, 0xf10yd approved these changes

2021-06-24 03:51 UTC, 0xf10yd submitted a review, later dismissed

2021-06-24 10:49 UTC, ShaunSHamilton commented
Hello there. Thank you, for taking the time to open this PR.

Whilst not necessarily done in the clearest way, I believe the intent behind the challenge being this way is to show the Camper the `map` method returns a completely new array, and does not need to have the same properties/structure as the original.

That is, it is common to use `map` to iterate over an array of object literals, and return a new object literal array with a different signature. So, I would not make this proposed change.

2021-06-24 14:28 UTC, braxex commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array.md
> +The `watchList` array holds objects with information on several movies. Use `map` on `watchList` to assign a new array of objects with only `Title` and `imdbRating` keys to the `ratings` variable. Th
```suggestion
The `watchList` array holds objects with information on several movies. Use `map` on `watchList` to assign a new array of objects to the `ratings` variable. Each movie in the new array should have a `title` key with the name of the film and a `rating` key with the IMDB rating. The code in the editor currently uses a `for` loop to do this, so you should replace the loop functionality with your `map` expression.
```

2021-06-24 14:29 UTC, braxex commented
> Whilst not necessarily done in the clearest way, I believe the intent behind the challenge being this way is to show the Camper the `map` method returns a completely new array, and does not need to have the same properties/structure as the original.
> 
> That is, it is common to use `map` to iterate over an array of object literals, and return a new object literal array with a different signature. So, I would not make this proposed change.

Hmm... that's a good point, @ShaunSHamilton. Maybe it would make sense to just tweak the instruction language then and keep the expected challenge outcome the same. Something like [this suggestion I just made](https://github.com/freeCodeCamp/freeCodeCamp/pull/42613/files#r657999580):

![Screen Shot 2021-06-24 at 09 28 45](https://user-images.githubusercontent.com/27705928/123280660-95697500-d4ce-11eb-8e03-40f9d6474f14.png)

2021-06-24 16:20 UTC, ShaunSHamilton commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array.md
> +The `watchList` array holds objects with information on several movies. Use `map` on `watchList` to assign a new array of objects with only `Title` and `imdbRating` keys to the `ratings` variable. Th
I think this works well 👍

2021-06-24 22:31 UTC, braxex commented
@0xf10yd Committing my suggestion dismissed your previous review, but it also won't let me re-request review. So I'm doing it this way I guess. 🤷‍♂️ Re-review please?

2021-06-24 22:39 UTC, 0xf10yd approved these changes, later dismissed

2021-06-27 12:49 UTC, ShaunSHamilton requested changes
One last change, then this LGTM.

2021-06-27 12:49 UTC, ShaunSHamilton commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/use-the-map-method-to-extract-data-from-an-array.md
> +The `watchList` array holds objects with information on several movies. Use `map` on `watchList` to assign a new array of objects to the `ratings` variable. Each movie in the new array should have a
```suggestion
The `watchList` array holds objects with information on several movies. Use `map` on `watchList` to assign a new array of objects to the `ratings` variable. Each movie in the new array should have only a `title` key with the name of the film, and a `rating` key with the IMDB rating. The code in the editor currently uses a `for` loop to do this, so you should replace the loop functionality with your `map` expression.
```

2021-06-27 17:24 UTC, ShaunSHamilton approved these changes
Thank you, for making those changes. I am happy with this 👍

2021-06-28 13:57 UTC, braxex commented
Works for me. 👍  Just need one more review and we're good to go.

2021-06-28 14:25 UTC, gikf approved these changes
Looks good to me, makes instructions a bit clearer. :+1:

2021-06-28 14:25 UTC, merged