feat(client) Renamed Learn.js to learn.tsx
freeCodeCamp/freeCodeCamp pull request #42644
Opened 2021-06-26 08:52 UTC by sharmaabhinav

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-06-26 13:28 UTC, thecodingaviator commented on client/src/components/layouts/learn.tsx
> +  children: React.ReactNode;
Try to leave optional props as optional

2021-06-26 13:29 UTC, thecodingaviator submitted a review, later dismissed

2021-06-26 13:29 UTC, thecodingaviator commented on client/src/components/layouts/learn.tsx
> +  children: React.ReactNode;
Try to leave optional props as optional

2021-06-26 20:22 UTC, thecodingaviator reviewed
The optional props issue looks good now. Fix the lining and this should be good to go

2021-06-28 20:30 UTC, ShaunSHamilton requested changes
Just nitpicks for consistency

2021-06-28 20:30 UTC, ShaunSHamilton commented on client/src/components/layouts/learn.tsx
> +type fetchState = {
```suggestion
type FetchState = {
```

2021-06-28 20:30 UTC, ShaunSHamilton commented on client/src/components/layouts/learn.tsx
> +type user = {
```suggestion
type User = {
```

2021-06-28 20:30 UTC, ShaunSHamilton commented on client/src/components/layouts/learn.tsx
> +  (fetchState: fetchState, isSignedIn, user: user) => ({
```suggestion
  (fetchState: FetchState, isSignedIn, user: User) => ({
```

2021-06-28 20:30 UTC, ShaunSHamilton commented on client/src/components/layouts/learn.tsx
> +  user: user;
```suggestion
  fetchState: FetchState;
  user: User;
```

2021-06-29 12:55 UTC, sharmaabhinav commented on client/src/components/layouts/learn.tsx
> +        /* @ts-ignore  */}
Migration of `DonationModal.tsx` is required to fix hence added this a last option as per guidelines

2021-06-29 13:36 UTC, ShaunSHamilton approved these changes
This LGTM 👍

2021-06-29 13:37 UTC, ShaunSHamilton commented
@thecodingaviator Feel free to merge, if you are happy 🙂

2021-06-29 14:01 UTC, merged

2021-06-29 14:01 UTC, thecodingaviator reviewed
LGTM!