feat(i18n): enable italian contributing documentation
freeCodeCamp/freeCodeCamp pull request #42662
Opened 2021-06-28 18:18 UTC by ieahleen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

I hope I did it correctly.
The italian documentation is 100% translated and approved, and with curriculum announcement being near I hope it will be useful to future italian contributors.

2021-06-28 18:36 UTC, nhcarrigan requested changes

2021-06-28 18:36 UTC, nhcarrigan commented on .github/workflows/crowdin-i18n-docs.download.yml
> +      - name: Crowdin Download Italian  Translations
```suggestion
      - name: Crowdin Download Italian Translations
```
One very small nit-pick.

2021-06-28 19:41 UTC, nhcarrigan approved these changes
Looks good to me - thanks for taking care of this!

2021-06-29 05:42 UTC, raisedadead approved these changes

2021-06-29 05:42 UTC, merged