fix(client): allow regex to match windows-like paths
freeCodeCamp/freeCodeCamp pull request #42720
Opened 2021-07-02 12:42 UTC by gikf

* Changes regex to allow matching windows-like paths.
* Changes which matched group is used later, due to the previous change.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42719

2021-07-02 14:19 UTC, ShaunSHamilton requested changes
What about something we have done in the past: https://github.com/freeCodeCamp/freeCodeCamp/pull/39454/files

2021-07-02 14:19 UTC, ShaunSHamilton commented on client/utils/buildChallenges.js
> +    const blockName = filePath.match(blockNameRe)[2];
```suggestion
    const blockNameRe = /\d\d-[-\w]+\/([^/]+)\//;
    const posix = path
      .normalize(filePath)
      .split(path.sep)
      .join(path.posix.sep);
    const blockName = posix.match(blockNameRe)[1];
```

2021-07-02 14:56 UTC, gikf commented on client/utils/buildChallenges.js
> +    const blockName = filePath.match(blockNameRe)[2];
Good idea :rocket:

2021-07-02 18:22 UTC, ShaunSHamilton approved these changes
This appears to work 👍

2021-07-05 10:58 UTC, Sembauke commented
Hey @ShaunSHamilton,

I do not know on which OS you develop, but it would be handy to have someone test this on Linux and Windows.

2021-07-05 19:24 UTC, ShaunSHamilton commented
> Hey @ShaunSHamilton,
> 
> I do not know on which OS you develop, but it would be handy to have someone test this on Linux and Windows.

I have tested on Windows 10 and Ubuntu 20.04 (WSL 2)

2021-07-06 06:40 UTC, raisedadead approved these changes

2021-07-06 06:40 UTC, merged