feat(client): refactor Flash/redux into TS
freeCodeCamp/freeCodeCamp pull request #42725
Opened 2021-07-02 23:30 UTC by ShaunSHamilton

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #42256 

This is hopefully a simplification of our current Redux logic, whilst providing the best typing we could hope for.
What this PR might accomplish:
- [x] Refactor `components/Flash/redux` into TypeScript
- [x] Simplify Redux logic for types
- [ ] Simplify Redux logic for actions
- [x] Simplify Redux logic for reducers
- [ ] Aggregate types and initial values for app state across client

2021-07-13 16:06 UTC, moT01 commented
I rebased this locally and got a small conflict - so I pushed the changes.

2021-07-13 16:30 UTC, ShaunSHamilton commented on client/src/redux/index.js
> -  // TODO: Why return a string or empty objet literal?
This comment still applies...

2021-07-13 16:47 UTC, moT01 approved these changes, later dismissed
I didn't see any problems with this. A PR was merged that changes [some linting config](https://github.com/freeCodeCamp/freeCodeCamp/pull/42818), causing typescript errors in many files, here and elsewhere. I don’t think this PR needs to be held up for that. I looked at the code, didn’t see anything out of place - played with it locally, everything seemed to work. LGTM 👍 🎉

2021-07-23 17:27 UTC, ojeytonwilliams requested changes
Just so we're on the same page: the objective here is to

- start replacing `redux-actions`
- type the custom code that replaces it

Is that a fair assessment?

2021-07-23 17:35 UTC, ShaunSHamilton commented on client/src/redux/types.ts
> +  message: ({ id: string } & FlashMessageArg) | Record<string, never>;
Well, this is specific in that:
a) A flash message cannot (should not) be created without `message` and `type` properties.
b) The FlashState can exist as an empty object literal (`Record<string, never>`)

2021-07-23 17:40 UTC, ShaunSHamilton commented on client/src/redux/types.ts
> +// const allApps = [FlashApp];
> Is that a fair assessment?

At the end of the day, I would hope to remove more than just `redux-actions`: `observable`, `rxjs`, `redux-saga`

Realistically, I will not get to those in this sprint (TS-focussed migration) - I will try not to make too many unnecessary changes.

_After that, we would just need to get rid of (in order): Redux, Gatsby, and the client_ 😄

2021-07-23 17:40 UTC, ShaunSHamilton commented
> Is that a fair assessment?

At the end of the day, I would hope to remove more than just `redux-actions`: `observable`, `rxjs`, `redux-saga`

Realistically, I will not get to those in this sprint (TS-focussed migration) - I will try not to make too many unnecessary changes.

_After that, we would just need to get rid of (in order): Redux, Gatsby, and the client_ 😄

2021-10-19 16:34 UTC, moT01 reviewed
I tested this out and looked over the code decently - everything seems to be working. Left one comment. Other than that curiosity, this LGTM 🎉

2021-10-20 14:48 UTC, moT01 submitted a review, later dismissed
LGTM 🎉

2021-10-20 15:50 UTC, ojeytonwilliams requested changes
Just some nitpicks, this looks good :+1:

2021-10-20 17:22 UTC, ojeytonwilliams approved these changes

2021-10-20 17:58 UTC, moT01 approved these changes
LGTM 🎉

2021-10-20 17:58 UTC, merged