Feat/default layout typescript migration
freeCodeCamp/freeCodeCamp pull request #42741
Opened 2021-07-04 10:18 UTC by sharmaabhinav

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-07-05 21:56 UTC, ShaunSHamilton requested changes

2021-07-05 21:56 UTC, ShaunSHamilton commented on client/src/components/layouts/default.tsx
> +// @ts-ignore
Hey there. Would you mind changing these to `@ts-expect-error` - that way, you can also remove the `ban-ts-comment` comment.

2021-07-27 20:10 UTC, nhcarrigan commented
@sharmaabhinav it looks like you've got some TypeScript compilation errors that still need to be resolved.

2021-07-27 20:22 UTC, ShaunSHamilton commented
For the most part, the FlashMessage type should look like this: https://github.com/freeCodeCamp/freeCodeCamp/pull/42725/files

2021-10-27 05:36 UTC, closed without merging