fix: recognize background-image as correct (#42738)
freeCodeCamp/freeCodeCamp pull request #42745
Opened 2021-07-04 20:00 UTC by ajl223

The page mentioned in #42738 before would not accept background-image and background, now it should.

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #42738

2021-07-04 20:19 UTC, ieahleen commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image.md
> +    /background(-image)?:\s*?url\(\s*("|'|)https:\/\/cdn-media-1\.freecodecamp\.org\/imgr\/MJAkxbh\.png\1\s*\)/gi
```suggestion
    /background(-image)?:\s*?url\(\s*("|'|)https:\/\/cdn-media-1\.freecodecamp\.org\/imgr\/MJAkxbh\.png\2\s*\)/gi
```

as there is a new capture group this needs to be changed to

2021-07-04 20:19 UTC, ieahleen requested changes

2021-07-04 20:19 UTC, ieahleen commented on curriculum/challenges/english/01-responsive-web-design/applied-visual-design/create-texture-by-adding-a-subtle-pattern-as-a-background-image.md
> +    /background(-image)?:\s*?url\(\s*("|'|)https:\/\/cdn-media-1\.freecodecamp\.org\/imgr\/MJAkxbh\.png\1\s*\)/gi
```suggestion
    /background(-image)?:\s*?url\(\s*("|'|)https:\/\/cdn-media-1\.freecodecamp\.org\/imgr\/MJAkxbh\.png\2\s*\)/gi
```

as there is a new capture group this needs to be changed too

2021-07-04 20:23 UTC, ieahleen commented
Please make sure to run the tests locally before submitting a PR that changes tests
Like shown in https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges

2021-07-04 20:45 UTC, ieahleen commented
Hey @ajl223 

We would love to be able to merge your changes but it looks like there is an error with the CI build. ⚠️

Once you resolve these issues, we will be able to review your PR and merge it. 😊

---

Feel free to reference the [contributing guidelines](https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges) for instructions on running the CI build locally. ✅

2021-07-04 20:54 UTC, ajl223 commented
Yeah sure I will soon sorry for the late reply

2021-07-05 06:50 UTC, ieahleen approved these changes
LGTM 👍 

Congratulations on your first PR!

Note that two approving reviews are needed for a PR to be accepted

2021-07-05 10:28 UTC, Sembauke approved these changes

2021-07-05 10:28 UTC, merged