Feat/layout selector typescript migration
freeCodeCamp/freeCodeCamp pull request #42748
Opened 2021-07-05 06:05 UTC by sharmaabhinav

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-07-09 09:27 UTC, ojeytonwilliams requested changes
Thanks for this PR, @sharmaabhinav.  Tiny nitpicks aside, this looks good.

2021-07-09 09:27 UTC, ojeytonwilliams commented on client/utils/gatsby/layout-selector.tsx
> +};
```suggestion
interface Location {
  pathname: string;
}
```
Nitpick, we prefer interfaces over type aliases: https://contribute.freecodecamp.org/#/codebase-best-practices?id=interfaces-and-types

2021-07-09 09:27 UTC, ojeytonwilliams commented on client/utils/gatsby/layout-selector.tsx
> +};
```suggestion
interface LayoutSelectorProps = {
  props: {
    location: Location;
  };
  element: React.ReactElement;
}
```
Same as above.

2021-07-09 12:03 UTC, ojeytonwilliams approved these changes
Perfect, thanks @sharmaabhinav. LGTM :+1:

2021-07-12 07:03 UTC, huyenltnguyen approved these changes
LGTM 👍

2021-07-12 07:05 UTC, merged