feat: convert solutionForm to ts
freeCodeCamp/freeCodeCamp pull request #42766
Opened 2021-07-06 15:20 UTC by Sembauke

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-07-06 16:26 UTC, ojeytonwilliams requested changes
Thanks for persevering with this, Sem.  Just two nitpicks:

2021-07-06 16:26 UTC, ojeytonwilliams commented on client/src/templates/Challenges/projects/SolutionForm.tsx
> +  isSubmitting?: boolean;
```suggestion
```
We can drop this - it's never used.

2021-07-06 16:26 UTC, ojeytonwilliams commented on client/src/templates/Challenges/projects/SolutionForm.tsx
> +        }
```suggestion
        solutionLink =
          solutionLink +
          (description?.includes('Colaboratory')
            ? 'https://colab.research.google.com/drive/1i5EmInTWi1RFvFr2_aRXky96YxY6sbWy'
            : 'https://replit.com/@camperbot/hello');
```
Nitpick.

2021-07-06 17:05 UTC, ojeytonwilliams approved these changes, later dismissed
LGTM :+1:

2021-07-06 21:13 UTC, ShaunSHamilton requested changes
Sorry, but i am going to nitpick, and ask that the file name be changed to kebab. Otherwise, this LGTM

2021-07-07 08:32 UTC, ShaunSHamilton approved these changes
This LGTM 👍 . Thank you, for that change

2021-07-07 08:38 UTC, ojeytonwilliams approved these changes
LGTM 👍

2021-07-07 08:38 UTC, merged