fix: update regex to account for bracket notation
freeCodeCamp/freeCodeCamp pull request #42881
Opened 2021-07-15 22:44 UTC by alirezaghey

Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes  #42877

fix minor bug in regex referring to literal dots with a dot

2021-07-16 00:04 UTC, awu43 commented on curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/set-up-passport.md
> +        /secret:( |)process\.env(\.SESSION_SECRET|\["SESSION_SECRET"\])/gi,
```suggestion
        /secret:( |)process\.env(\.SESSION_SECRET|\[(?<q>"|')SESSION_SECRET\k<q>\])/gi,
```

Single quotes are also valid.

2021-07-16 20:01 UTC, gikf approved these changes, later dismissed
LGTM :+1: 

I've tested all three possible options.

2021-07-17 09:51 UTC, ieahleen requested changes

2021-07-17 09:51 UTC, ieahleen commented on curriculum/challenges/english/06-quality-assurance/advanced-node-and-express/set-up-passport.md
> +        /secret:( |)process\.env(\.SESSION_SECRET|\[(?<q>"|')SESSION_SECRET\k<q>\])/gi,
```suggestion
        /secret:( |)process\.env(\.SESSION_SECRET|\[(?<q>"|')SESSION_SECRET\k<q>\])/g,
```

variables and method names are case sensitive, the `i` flag would pass stuff that doesn't work

2021-07-17 16:17 UTC, ieahleen approved these changes
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

2021-07-17 16:29 UTC, gikf approved these changes

2021-07-17 16:29 UTC, merged