i18n: adding first few motivational quotes and compliments in italian
freeCodeCamp/freeCodeCamp pull request #42935
Opened 2021-07-19 20:16 UTC by ieahleen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-07-19 20:18 UTC, nhcarrigan approved these changes
Thanks for getting these started!

2021-07-19 20:48 UTC, nhcarrigan requested changes
Mentioned in chat.

2021-07-19 20:48 UTC, nhcarrigan commented on client/i18n/locales/italian/motivation.json
> +    "Tu sei un mago, harry",
```suggestion
    "Tu sei un mago, Harry",
```

2021-07-19 20:49 UTC, nhcarrigan approved these changes

2021-07-20 02:50 UTC, moT01 approved these changes
LGTM @ieahleen 🎉

2021-07-20 02:50 UTC, merged