feat(client): ts-migrate (/client/src/components/layouts/Certification.js)
freeCodeCamp/freeCodeCamp pull request #42939
Opened 2021-07-20 03:49 UTC by RaymenDeol

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #42256

2021-07-20 15:53 UTC, nhcarrigan commented on client/src/components/layouts/certification.tsx
> +class CertificationLayout extends Component <CertificationProps> {
```suggestion
class CertificationLayout extends Component<CertificationProps> {
```
It's nitpicky, but this is what the linter wants. :)

2021-07-23 14:26 UTC, ojeytonwilliams requested changes, later dismissed
Another linting issue, I'm afraid, but aside from that this looks good.

2021-07-23 14:26 UTC, ojeytonwilliams commented on client/src/components/layouts/certification.tsx
> +      <Fragment>
```suggestion
      <>
```
We recently changed the eslint rules to require the shorthand: https://github.com/freeCodeCamp/freeCodeCamp/pull/42963/

2021-07-23 14:26 UTC, ojeytonwilliams commented on client/src/components/layouts/certification.tsx
> +      </Fragment>
```suggestion
      </>
```

2021-07-27 20:58 UTC, nhcarrigan submitted a review, later dismissed

2021-07-27 20:58 UTC, nhcarrigan commented on client/src/components/layouts/certification.tsx
> +import React, { Fragment, Component } from 'react';
```suggestion
import React, { Component } from 'react';
```
In combination with Oliver's suggestion, we'll need to remove the unused import.

2021-09-22 15:42 UTC, ShaunSHamilton approved these changes
LGTM 👍

2021-09-23 07:15 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-09-23 07:15 UTC, merged

2021-09-23 07:15 UTC, ojeytonwilliams commented
@RaymenDeol Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the codebase! 👍
We're happy to accept these changes, and look forward to future contributions. 📝