feat(client): add new coder survey link to learn
freeCodeCamp/freeCodeCamp pull request #42955
Opened 2021-07-21 10:52 UTC by ShaunSHamilton

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

If the space looks to large, it looks less so when there is a _Go to current challenge_ button.
![image](https://user-images.githubusercontent.com/51722130/126477205-dd18fb74-46e0-4222-8990-67434f73904e.png)

2021-07-21 14:54 UTC, nhcarrigan requested changes

2021-07-21 14:54 UTC, nhcarrigan commented on client/i18n/locales/chinese-traditional/translations.json
> +    "coder-survey": "<0>Take the 2021 New Coder Survey<0> (it takes about 10 minutes – do it for science)"
```suggestion
    "coder-survey": "<0>Take the 2021 New Coder Survey</0> (it takes about 10 minutes – do it for science)"
```

2021-07-21 14:54 UTC, nhcarrigan commented on client/i18n/locales/chinese/translations.json
> +    "coder-survey": "<0>Take the 2021 New Coder Survey<0> (it takes about 10 minutes – do it for science)"
```suggestion
    "coder-survey": "<0>Take the 2021 New Coder Survey</0> (it takes about 10 minutes – do it for science)"
```

2021-07-21 14:54 UTC, nhcarrigan commented on client/i18n/locales/english/translations.json
> +    "coder-survey": "<0>Take the 2021 New Coder Survey<0> (it takes about 10 minutes – do it for science)"
```suggestion
    "coder-survey": "<0>Take the 2021 New Coder Survey</0> (it takes about 10 minutes – do it for science)"
```

2021-07-21 14:54 UTC, nhcarrigan commented on client/i18n/locales/espanol/translations.json
> +    "coder-survey": "<0>Take the 2021 New Coder Survey<0> (it takes about 10 minutes – do it for science)"
```suggestion
    "coder-survey": "<0>Take the 2021 New Coder Survey</0> (it takes about 10 minutes – do it for science)"
```

2021-07-21 14:54 UTC, nhcarrigan commented on client/i18n/locales/italian/translations.json
> +    "coder-survey": "<0>Take the 2021 New Coder Survey<0> (it takes about 10 minutes – do it for science)"
```suggestion
    "coder-survey": "<0>Take the 2021 New Coder Survey</0> (it takes about 10 minutes – do it for science)"
```

2021-07-21 14:54 UTC, nhcarrigan commented on client/i18n/locales/portuguese/translations.json
> +    "coder-survey": "<0>Take the 2021 New Coder Survey<0> (it takes about 10 minutes – do it for science)"
```suggestion
    "coder-survey": "<0>Take the 2021 New Coder Survey</0> (it takes about 10 minutes – do it for science)"
```

2021-07-21 14:58 UTC, ShaunSHamilton commented
@QuincyLarson Should the link open in a new tab?

2021-07-21 14:58 UTC, nhcarrigan approved these changes

2021-07-21 15:38 UTC, moT01 approved these changes
LGTM 🎉

2021-07-23 04:05 UTC, QuincyLarson approved these changes

2021-07-23 06:03 UTC, merged