Add 5th test to Anonymous Message Board project challenge
freeCodeCamp/freeCodeCamp pull request #43041
Opened 2021-07-28 09:15 UTC by HOuadhour

This is the 5th task from the task lists in #41323 
You can send a POST request to `/api/replies/{board}` with form data including `text`, `delete_password`, & `thread_id`.
This will update the `bumped_on` date to the comment's date. In the thread's replies array, an object will be saved with at least the properties `_id`, `text`, `created_on`, `delete_password`, & `reported`.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

It doesn't close but solves task number 5 from #41323

2021-07-30 23:40 UTC, HOuadhour commented
@moT01 
Do you think is it good, should I continue to implement the rest, or should I wait?

2021-08-01 06:23 UTC, gikf commented
Hey @HOuadhour, would you have on hand project version for which this added tests is passing?

2021-08-01 08:33 UTC, HOuadhour commented
@gikf 
Yes I have [My Replit](https://Anonymous-Message-Board.teknician.repl.co)

2021-08-01 11:08 UTC, gikf approved these changes, later dismissed
Seems to be okay :+1: 

Although the example demo project - https://anonymous-message-board.freecodecamp.rocks/ - will need to be updated, as it uses different dates for `created_on` and thread `bumped_on`.

2021-08-02 14:52 UTC, HOuadhour commented
@gikf 
I agree with you when we add a reply
the `bumped_on` must equal to `created_on` that belongs to the reply.
Also, there is another problem
The test has never mentioned `replycount` field which we needed when we fetch the most 10 threads.

I am writing the rest of the tests.

2021-08-02 18:25 UTC, moT01 reviewed
I think we should be trying to test for only what the user stories are asking for. If I am looking at this right, that means we wouldn't want to check anything about the `replyCount`. The user story asks for `_id`, `text`, `created_on`, `delete_password`, and `reported` properties. This only appears to check for the `_id` and `text`. I don't think it's a huge deal not to include those, but wouldn't it be pretty easy to add a quick check? Actually, it appears like neither the example project, or your demo include that in the response...
![Screen Shot 2021-08-02 at 12 54 56 PM](https://user-images.githubusercontent.com/20648924/127904947-c7cbf2db-7614-445d-9c92-80ed8441dac1.png)
So, I'm wondering if we shouldn't add a test for those - or perhaps, if we should remove that text from the user story.

I actually couldn't get your example to pass:
![Screen Shot 2021-08-02 at 12 52 48 PM](https://user-images.githubusercontent.com/20648924/127904119-2dad6ae8-b9a9-4843-9779-9649e3f96e37.png)
 
 Not sure what the problem was - I assume it was able to pass for both of you. On a second look, I think it's the `replyCount` test - that field isn't included in any response, yet it's being checked. When I comment out that test, the project passes.

2021-08-02 18:34 UTC, HOuadhour commented
@moT01 
Yes because I changed it today in my `replit` to do not include the `replycount`.
That's why you didn't get it passed.
I am finishing all of the tests.
And I will add one pull request to solve them all

2021-08-02 18:38 UTC, moT01 commented
I made a PR to the demo project for adding @gikf's suggestion/fix

2021-08-02 20:30 UTC, HOuadhour commented
I think I did a mistake, I did my second commit and I forgot to fetch from the upstream repo first.
I don't know if it's okay, or Do I have to fetch again and repush?

2021-08-03 13:08 UTC, moT01 commented
That should be fine in this case @HOuadhour. I would recommend that you not work on the `main` branch of your fork. You should create new branch to work on - it's not necessary this time

Here's some helpful links:
[Info on creating a new branch](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally) - see step 3
[Info on creating a PR](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request)

2021-08-26 22:00 UTC, moT01 submitted a review, later dismissed
I would be fine merging this - I played around with it quite a bit, got the demo project to pass with a few changes (made in linked PR).

LGTM 🎉

2021-08-28 19:27 UTC, HOuadhour commented on curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md
> +    const checkData = await fetch(`${url}/api/replies/fcc_test?thread_id=${thread_id}`);
Yes because the post request won't return anything it will just redirect

2021-08-28 19:36 UTC, HOuadhour commented on curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md
>  You can send a PUT request to `/api/threads/{board}` and pass along the `thread_id`. Returned will be the string `success`. The `reported` value of the `thread_id` will be changed to `true`.
I think maybe we just change the user story text to clarify it.
If we change the demo project to meet the description.
All other students need to change their projects too.

2021-08-28 19:43 UTC, HOuadhour commented on curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md
>  You can send a PUT request to `/api/replies/{board}` and pass along the `thread_id` & `reply_id`. Returned will be the string `success`. The `reported` value of the `reply_id` will be changed to `tru
If you recommend this one, so the demo project must be changed too.

2021-09-16 14:45 UTC, ShaunSHamilton commented
Hey all,

Apologies for the delay on this, but can we get an update.

@nhcarrigan If we you are happy with these user stories and tests, we will need to change the example project to match. Although, I am confused as to why the final 3 user stories do not match what the example project does.

2021-09-16 15:59 UTC, nhcarrigan commented
Not sure what's up, but I can't delete my own thread - probably passing the ID incorrectly.

A `PUT` request returned the string `reported`. `DELETE` is just giving me `invalid password` lol.

2021-09-23 18:41 UTC, nhcarrigan commented
> Although, I am confused as to why the final 3 user stories do not match what the example project does.

@ShaunSHamilton could you clarify? I'm not getting it.

2021-09-23 19:29 UTC, ShaunSHamilton commented
> A PUT request returned the string reported

@nhcarrigan I mean that. The fact that the user story has not changed, but the example does not follow this.

2021-09-23 20:58 UTC, nhcarrigan commented
It did when I did a `curl` to the API manually.

The front end displays something else, but the API does match the user story.

2022-01-07 07:55 UTC, raisedadead commented
I am auditing PRs in limbo. @ShaunSHamilton & @nhcarrigan can you guide with the next action items?

2022-01-13 19:23 UTC, nhcarrigan requested changes
update to reflect example project

2022-01-13 19:23 UTC, nhcarrigan commented on curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md
>  You can send a PUT request to `/api/replies/{board}` and pass along the `thread_id` & `reply_id`. Returned will be the string `success`. The `reported` value of the `reply_id` will be changed to `tru
```suggestion
You can send a PUT request to `/api/replies/{board}` and pass along the `thread_id` & `reply_id`. Returned will be the string `reported`. The `reported` value of the `reply_id` will be changed to `true`.
```

2022-01-13 19:23 UTC, nhcarrigan commented on curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md
> +      assert.equal(reported, "success");
```suggestion
      assert.equal(reported, "reported");
```

2022-01-13 19:23 UTC, nhcarrigan commented on curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md
>  You can send a PUT request to `/api/threads/{board}` and pass along the `thread_id`. Returned will be the string `success`. The `reported` value of the `thread_id` will be changed to `true`.
```suggestion
You can send a PUT request to `/api/threads/{board}` and pass along the `thread_id`. Returned will be the string `reported`. The `reported` value of the `thread_id` will be changed to `true`.
```

2022-01-13 19:23 UTC, nhcarrigan commented on curriculum/challenges/english/09-information-security/information-security-projects/anonymous-message-board.md
> +      assert.equal(reported, "success");
```suggestion
      assert.equal(reported, "reported");
```

2022-01-13 19:30 UTC, nhcarrigan approved these changes
As it stands, this now allows the example project to pass all tests except the functional tests one (which is resolved in https://github.com/freeCodeCamp/demo-projects/pull/94) - I'd be happy to land this.

2022-01-13 19:36 UTC, ShaunSHamilton approved these changes
LGTM 👍

2022-01-13 20:38 UTC, merged

2022-01-13 20:39 UTC, ShaunSHamilton commented
Thank you, for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉

Thanks, for your patience as we hashed this out. This project should probably get further improvement, but this PR does tonnes!