fix(curriculum): grid area template lesson
freeCodeCamp/freeCodeCamp pull request #43059
Opened 2021-07-29 00:02 UTC by moT01

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #38959

2021-08-01 11:53 UTC, gikf approved these changes, later dismissed
Looks okay to me :+1:

2021-08-03 10:59 UTC, ShaunSHamilton requested changes
@moT01 The next lesson's solution and seed do not match this.

I realise this is not the same as the upcoming curriculum, but it does not make much sense mentioning the next step being a resolution to the topic.

2021-08-04 01:13 UTC, moT01 commented
Want to take another look when you get a chance @ShaunSHamilton? I tried to line it up with the next lesson better.

2021-08-04 11:00 UTC, ShaunSHamilton reviewed
This makes sense. Just one thing I would do:

2021-08-04 11:00 UTC, ShaunSHamilton commented on curriculum/challenges/english/01-responsive-web-design/css-grid/divide-the-grid-into-an-area-template.md
> +The code above groups the cells of the grid into four areas; `header`, `advert`, `content`, and `footer`. Every word represents a cell and every pair of quotation marks represent a row. Defining the
```suggestion
The code above groups the cells of the grid into four areas; `header`, `advert`, `content`, and `footer`. Every word represents a cell and every pair of quotation marks represent a row.
```

2021-08-04 11:00 UTC, ShaunSHamilton commented on curriculum/challenges/english/01-responsive-web-design/css-grid/divide-the-grid-into-an-area-template.md
> +Change the template so the `footer` area spans the entire bottom row.
```suggestion
Change the template so the `footer` area spans the entire bottom row. Defining the areas won't have any visual effect right now. Later, you will make an item use an area to see how it works.
```

2021-08-04 14:39 UTC, ShaunSHamilton approved these changes
Thanks for that back-and-forth, Tom. This LGTM 👍

2021-08-06 04:51 UTC, gikf approved these changes

2021-08-06 04:52 UTC, merged