feat(tools): test navigation links
freeCodeCamp/freeCodeCamp pull request #43080
Opened 2021-07-30 17:15 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

The changes made in #42995 created an issue where we were no longer testing that the forum and news links rendered correctly.

This PR adds a small Cypress test that validates the links have the correct `href` attribute, allowing us to verify that the `t` function is returning the actual link.

2021-07-30 17:49 UTC, ojeytonwilliams requested changes
Could you collapse this to one test? There's a bit of overhead for each `it` so it should run faster with only one.

2021-07-30 17:51 UTC, nhcarrigan commented
Sure thing!

2021-07-30 19:24 UTC, ojeytonwilliams approved these changes
Cheers, LGTM 👍

2021-07-31 07:21 UTC, raisedadead approved these changes

2021-07-31 07:21 UTC, merged