fix(client): removes cut off in certificate page
freeCodeCamp/freeCodeCamp pull request #43090
Opened 2021-07-31 14:44 UTC by victor-duarte

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43060

The change is tested against `production` in dev tools since I was not able to reproduce it in `develop`.

I had a hiccup when trying to reproduce the issue. The markup output after the redirection when pasting the URL is different between `develop` and `production`, it seems the conditions are manage differently ([see layout-selector.tsx](https://github.com/freeCodeCamp/freeCodeCamp/blob/main/client/utils/gatsby/layout-selector.tsx)). Not sure if this is an issue or simply a configuration I was not able to figure out.

Regarding the issue, there seems to be a conflict due to the nesting and how the props `flex`, `height` are being used throughout the different wrappers. In a previous [PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/39154) some styles were added which seems to be in part contributing to the experienced behavior. I was not able to understand what exactly was the intention so the fix being provided tries to be the least invasive after a trying different approaches.

When through a couple of pages and it seems it is not affecting any layouts.

2021-08-01 20:34 UTC, vishnuaq approved these changes
Appreciate

2021-08-01 20:35 UTC, vishnuaq approved these changes
Changes approved

2021-08-02 17:10 UTC, moT01 requested changes
It's rare - but when a page doesn't have enough content and you remove that height, the footer will not be at the bottom:
![Aug-02-2021 11-58-46](https://user-images.githubusercontent.com/20648924/127897587-6e074cfd-85a8-4bfa-a3d2-38c23f354dc5.gif)
Assuming that is correct, I don't think we should go this route.

2021-08-02 19:50 UTC, victor-duarte commented
@moT01, that could be the reason of why the value. Good catch.
Will take another stab at it.

2021-08-12 09:44 UTC, Sembauke approved these changes

2021-08-12 09:44 UTC, Sembauke commented
Thanks @victor-duarte for your hard works and your other PRS.
This looks good to me 👍

2021-08-12 18:26 UTC, raisedadead approved these changes

2021-08-18 11:23 UTC, raisedadead commented
Hey @moT01 mind merging this if you are happy with changes as requested?

2021-08-18 14:23 UTC, moT01 approved these changes
LGTM 🎉 Sorry for the delay here @victor-duarte - thanks for fixing this 👍

2021-08-18 14:23 UTC, merged