Unify donation  loading state
freeCodeCamp/freeCodeCamp pull request #43179
Opened 2021-08-11 13:14 UTC by ahmadabdolsaheb

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-08-12 09:00 UTC, ahmadabdolsaheb commented
the main question is, which one of the following scenarios offer a higher perceived performance  and a better user experience:
1)load each button individually (paypal loads faster and some times google/apple pay is not supported)
2)show a spinner until both load (or until one loads and we know the other is not supported)

2021-08-12 13:41 UTC, ShaunSHamilton commented
> higher perceived performance

What does Lighthouse say about the content/interactivity?

> a better user experience

Personally, one where all buttons appear at same time (**2**), because as I am reading the description of why/what I am about to do (donate), I do not want my eyes distracted 2-3 times as the buttons appear.

2021-08-13 12:12 UTC, ahmadabdolsaheb commented
@ShaunSHamilton it is hard to say because it would depend on wether the browser that visits our website has google pay enabled or not. 

Since the loader is going to be on the modal as well were there is not much read, it might effect the perceived performance. It is hard to tell if it matter much donation wise, but I think it is a good idea to unify the states at this point and optimize it with A/B testing in upcoming prs.

2021-08-13 12:26 UTC, ShaunSHamilton commented
> Since the loader is going to be on the modal 

Is there a specific reason we do not just link to `/donate` on the modal? (no pay buttons)

2021-08-13 12:33 UTC, ahmadabdolsaheb commented
> > Since the loader is going to be on the modal
> 
> Is there a specific reason we do not just link to `/donate` on the modal? (no pay buttons)

The longer the user journey the less likely it will be completed. Although I would love to A/B test that to see if the users are affected. That way we can clean up a lot of the components.

2021-08-17 00:02 UTC, moT01 approved these changes, later dismissed
Well, I didn't see any problems with this. LGTM 🎉

2021-08-19 10:38 UTC, ShaunSHamilton submitted a review, later dismissed
LGTM 👍 . Discussed some clean-up (unused stuff) with Ahmad, and he will do that in another open PR of his.

2021-08-19 13:29 UTC, ojeytonwilliams requested changes
Just some nitpicks.

2021-08-19 13:29 UTC, ojeytonwilliams commented on client/src/components/Donation/DonateForm.tsx
> +      },
```suggestion
      donationFormState: { loading },
```
If we pull out the booleans here, `paymentButtonsLoading` doesn't make much sense in isolation.

2021-08-19 13:29 UTC, ojeytonwilliams commented on client/src/components/Donation/DonateForm.tsx
> +    const paymentButtonsLoading = stripe && paypal;
```suggestion
    const paymentButtonsLoading = loading.stripe && loading.paypal;
```
With this change, the nature of `stripe` and `paypal` are obvious.

2021-08-19 13:29 UTC, ojeytonwilliams commented on client/src/components/Donation/DonateForm.tsx
> +            isPaypalLoading={paypal}
```suggestion
            isPaypalLoading={loading.paypal}
```

2021-08-19 18:22 UTC, ojeytonwilliams approved these changes

2021-08-19 18:33 UTC, ShaunSHamilton approved these changes
This still LGTM 👍

2021-08-19 19:47 UTC, moT01 approved these changes
🚀

2021-08-19 19:47 UTC, merged