Exercise tracker test and description improvement
freeCodeCamp/freeCodeCamp pull request #43205
Opened 2021-08-14 18:14 UTC by NoorFakhry

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #43184

2021-08-15 06:14 UTC, Akaatsukhi commented
`e`

2021-08-15 15:27 UTC, NoorFakhry commented on curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.md
> -    assert.isArray(res);
Here I forgot to convert the response to JSON and get the array from it.

2021-08-15 15:27 UTC, NoorFakhry commented on curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.md
> +    const users = await res.json();
So, I did it here

2021-08-15 15:29 UTC, NoorFakhry commented on curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.md
> -    assert(true);
Here, the check I made here was only that the user can create a new user, while I should test if he can create a new exercise

2021-08-15 15:29 UTC, NoorFakhry commented on curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/exercise-tracker.md
> +      assert.isString(actual.date);
Added a check that the date is a string

2021-08-18 11:08 UTC, raisedadead requested changes, later dismissed
Do you mind resolving the merge conflict and checking off the checkboxes in the PR description as requested by the guidelines?

If you need help, please reach out to the chat.

2021-08-18 15:45 UTC, ShaunSHamilton requested changes
Thank you, for taking the time to contribute to this.

Please, do likewise for the other tests - using `assert(true)` is not the most idiomatic way to test for the response success.

2021-08-18 15:45 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +  } else {
```suggestion
  assert.truthy(res.ok);
  if (!res.ok) {
```

2021-08-18 15:45 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +The `Get` request to `/api/users` returns an array.
```suggestion
The `GET` request to `/api/users` returns an array.
```

2021-08-18 15:45 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +Each element in the array is an object containing a user's `username` and `_id`.
As each user-story/test is separate, it helps to be specific - not to implicitly refer to something in another test

```suggestion
Each element in the `GET /api/users` array is an object literal containing a user's `username` and `_id`.
```

2021-08-18 18:16 UTC, NoorFakhry commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +  };
Changed the logic of making sure that the request works as intended.

2021-08-18 18:17 UTC, NoorFakhry commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +    throw new Error(`${res.status} ${res.statusText}`)
Changed the logic of making sure that the request works as intended.

2021-08-18 18:17 UTC, NoorFakhry commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +  };
Changed the logic of making sure that the request works as intended.

2021-08-18 18:17 UTC, NoorFakhry commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +    };
Changed the logic of making sure that the request works as intended.

2021-08-18 18:57 UTC, NoorFakhry commented
Hey @ShaunSHamilton, I made the changes that you asked for, can you Kindly take a look at them and tell me if there are any more changes that need to be done.
Right now I can not check the changes locally because there is an error when opening the page where I made the changes, I am going to try to know what the causes are, the error says It is happening in a file called SuperBlockIntro.js

2021-08-19 16:45 UTC, nhcarrigan commented
Heya @NoorFakhry,

Giving this a review shortly. I'm not seeing the `SuperBlockIntro.js`, which may be caused by some outdated cache files on your end. Running `npm run clean-and-develop` should resolve that.

2021-08-19 17:27 UTC, nhcarrigan requested changes
A few nitpicks, and these syntax errors prevent the tests from running.

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +      const logRes = await fetch(url + `api/users/${_id}/logs`);
```suggestion
      const logRes = await fetch(url + `/api/users/${_id}/logs`);
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +    const addRes = await fetch(url + `api/users/${_id}/exercises`, {
```suggestion
    const addRes = await fetch(url + `/api/users/${_id}/exercises`, {
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +      const logRes = await fetch(url + `api/users/${_id}/logs`);
```suggestion
      const logRes = await fetch(url + `/api/users/${_id}/logs`);
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +    const {_id, username} = res.json();
```suggestion
    const {_id, username} = await res.json();
```
These are asynchronous.

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +    const {_id, username} = res.json();
```suggestion
    const {_id, username} = await res.json();
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +    const {_id, username} = res.json();
```suggestion
    const {_id, username} = await res.json();
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +      'Content-Type': 'application/x-www-form-urlencoded'}
```suggestion
      'Content-Type': 'application/x-www-form-urlencoded'
```
Oops

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +async(getUserInput){
```suggestion
async(getUserInput) => {
```
Missing arrow.

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +async(getUserInput){
```suggestion
async(getUserInput) => {
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +async(getUserInput){
```suggestion
async(getUserInput) => {
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +async(getUserInput){
```suggestion
async(getUserInput) => {
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +  const url = getUserInput(url);
```suggestion
  const url = getUserInput('url');
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +  const url = getUserInput(url);
```suggestion
  const url = getUserInput('url');
```

2021-08-19 17:27 UTC, nhcarrigan commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +  const url = getUserInput(url);
```suggestion
  const url = getUserInput('url');
```

2021-08-19 17:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +  assert.truthy(res.ok);
@NoorFakhry Just in case you are not aware, you can click the `commit suggestion` button on each suggestion of a review to commit that suggestion.

2021-08-25 20:20 UTC, naomi-lgbt approved these changes
This is looking good. Thanks for all the effort you put in to this.

2021-08-26 11:26 UTC, ShaunSHamilton approved these changes
This LGTM 👍 . Thank you, for tackling this.

2021-08-26 11:27 UTC, merged