feat: add card form
freeCodeCamp/freeCodeCamp pull request #43239
Opened 2021-08-18 20:57 UTC by ahmadabdolsaheb

Checklist:

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-08-18 22:30 UTC, ShaunSHamilton requested changes
Just because it caught my eye

2021-08-18 22:30 UTC, ShaunSHamilton commented on client/src/components/Donation/DonateForm.tsx
> +class DonateForm extends Component<DonateFormProps, DonateFromComponentState> {
```suggestion
class DonateForm extends Component<DonateFormProps, DonateFormComponentState> {
```

2021-08-18 22:30 UTC, ShaunSHamilton commented on client/src/components/Donation/DonateForm.tsx
> +type DonateFromComponentState = {
```suggestion
type DonateFormComponentState = {
```

2021-08-31 11:57 UTC, ahmadabdolsaheb commented
We are moving in another direction and as a result we would not be integrating square for the time being.

2021-08-31 11:57 UTC, closed without merging