feat(e2e): Add cypress globals to eslint overrides
freeCodeCamp/freeCodeCamp pull request #43234
Opened 2021-08-18 15:45 UTC by christianztamayo

This diff eliminates the need to add `/* global cy */` on top of cypress tests.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2021-08-19 12:48 UTC, gikf requested changes, later dismissed
Hey @christianztamayo 

could you revert changes in docs in non-English languages? These files should not be changed directly. When needed they will be updated using the translation workflow.

2021-08-19 13:52 UTC, christianztamayo commented
Sure @gikf. I also squashed the branch and rebased to latest `main`

2021-08-24 08:15 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-08-24 13:38 UTC, nhcarrigan approved these changes

2021-08-24 14:29 UTC, merged

2021-08-24 14:29 UTC, ojeytonwilliams commented
@christianztamayo Thank you for your contribution to the site! :+1:
We're happy to accept these changes, and look forward to future contributions. :memo: