fix: unhide this string
freeCodeCamp/freeCodeCamp pull request #43292
Opened 2021-08-24 19:29 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #42656 

Okay, I'm not sure why this string is being hidden in the workflow, but since it's a one-off case I went ahead and added a step to go back and unhide it.

This will allow us to unhide other individual strings in the future, if needed.

2021-08-25 14:26 UTC, ojeytonwilliams requested changes
Just some nitpicks.

2021-08-25 14:26 UTC, ojeytonwilliams commented on tools/crowdin/actions/unhide-specific-string/index.js
> +// eslint-disable-next-line import/no-unresolved
```suggestion
```

2021-08-25 14:26 UTC, ojeytonwilliams commented on tools/crowdin/actions/unhide-specific-string/index.js
> +  const targetFile = fileResponse.find(el => el.path.endsWith(filename));
```suggestion
  const targetFile = fileResponse.find(el => el.path.endsWith(filename));
```
How about `path.baseName(el.path) === filename`?  I doubt the above code will ever be an issue, but I think `baseName` is a bit more robust.

2021-08-25 17:17 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-08-26 03:02 UTC, raisedadead approved these changes

2021-08-26 03:02 UTC, merged