(fix)Sort an array alphabetically using the sort Method - Array is returned from the function #43417
freeCodeCamp/freeCodeCamp pull request #43425
Opened 2021-09-09 21:08 UTC by vamagithub

Checklist:

- [ x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes #43417

2021-09-10 07:33 UTC, Sembauke submitted a review, later dismissed

2021-09-10 10:07 UTC, Pranav108 submitted a review, later dismissed

2021-09-10 10:31 UTC, gikf reviewed
I think return statement can be added as well (although it probably should be within the lines indicated for changing), but making in instructions explicit what function should return, would be more helpful for clarity.

2021-09-11 20:08 UTC, gikf requested changes
I think "the sorted array" would be correct here, but as I'm not entirely sure I'll defer with it to others.

Below is small suggestion to make wording more consistent with curriculum.

2021-09-11 20:08 UTC, gikf commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method.md
> +Use the `sort` method in the `alphabeticalOrder` function to sort the elements of `arr` in alphabetical order. The function will return a sorted array.
```suggestion
Use the `sort` method in the `alphabeticalOrder` function to sort the elements of `arr` in alphabetical order. The function should return a sorted array.
```

2021-09-12 10:57 UTC, ieahleen commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method.md
> +Use the `sort` method in the `alphabeticalOrder` function to sort the elements of `arr` in alphabetical order. The function should return a sorted array.
```suggestion
Use the `sort` method in the `alphabeticalOrder` function to sort the elements of `arr` in alphabetical order. The function should return the sorted array.
```

a small nitpicking

2021-09-13 12:51 UTC, vamagithub commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/functional-programming/sort-an-array-alphabetically-using-the-sort-method.md
> +Use the `sort` method in the `alphabeticalOrder` function to sort the elements of `arr` in alphabetical order. The function should return a sorted array.
Done.

2021-09-13 14:28 UTC, gikf approved these changes
Looks good! :+1:

2021-09-13 14:43 UTC, ieahleen approved these changes
LGTM :+1:

2021-09-13 15:22 UTC, merged

2021-09-13 15:55 UTC, gikf commented
Hi @vamagithub. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝