fix: remove name requirment from donation
freeCodeCamp/freeCodeCamp pull request #43486
Opened 2021-09-18 11:20 UTC by ahmadabdolsaheb

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-09-18 12:17 UTC, ShaunSHamilton requested changes
I see the field is optional, but I wonder if there is a reason to include it if it exists?

2021-09-18 12:17 UTC, ShaunSHamilton commented on api-server/src/server/utils/donation.js
> +    console.log();
```suggestion
```

2021-09-18 13:00 UTC, ShaunSHamilton approved these changes
This LGTM 👍

2021-09-18 19:39 UTC, hamzawaleed0102 commented
Looks good to me!

2021-09-18 19:39 UTC, hamzawaleed0102 approved these changes

2021-09-20 07:56 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-09-20 07:56 UTC, merged