feat: add introsos for rdbms
freeCodeCamp/freeCodeCamp pull request #43589
Opened 2021-09-27 21:30 UTC by moT01

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #42509

2021-09-28 08:35 UTC, Sembauke requested changes, later dismissed

2021-09-28 08:35 UTC, Sembauke commented on client/i18n/locales/english/intro.json
> +          "Finally, you will learn Git, the version control system, and GitHub, a code repositoy hosting service. Two essential tools for every developer."
```suggestion
          "Finally, you will learn Git, the version control system, and GitHub, a code repository hosting service. Two essential tools for every developer."
```

2021-09-28 15:45 UTC, ShaunSHamilton requested changes
My nitpicks which you may just dismiss.

I struggled to read through the first sentence in a natural way. I included the `...everything from...`, because there is a `...to...`

2021-09-28 15:45 UTC, ShaunSHamilton commented on client/i18n/locales/english/intro.json
> +          "These courses start you off with basic Bash commands. Using the terminal, you will learn how to navigate and manipulate a file system, scripting in Bash, all the way to advanced usage and
```suggestion
          "These courses start you off with basic Bash commands. Using the terminal, you will learn everything from navigating and manipulating a file system, scripting in Bash, all the way to the advanced usage of and connection to a database.",
```

2021-09-28 15:45 UTC, ShaunSHamilton commented on client/i18n/locales/english/intro.json
> +          "Finally, you will learn Git, the version control system, and GitHub, a code repository hosting service. Two essential tools for every developer."
```suggestion
          "Finally, you will learn Git, the version control system, and GitHub, a code repository hosting service - two essential tools for every developer."
```

2021-09-28 17:49 UTC, ShaunSHamilton submitted a review, later dismissed
👍 LGTM 🚢

2021-09-29 07:39 UTC, scissorsneedfoodtoo approved these changes, later dismissed
Everything LGTM :+1: :+1:

2021-09-29 07:49 UTC, ojeytonwilliams reviewed
@moT01 My two cents, to do with as you wish!

2021-09-29 07:49 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +      "For these courses, you will use real developer tools and software like VS Code, PostgreSQL, and the Linux / Unix command line to complete interactive tutorials and build projects."
```suggestion
      "For these courses, you will use real developer tools and software including VS Code, PostgreSQL, and the Linux / Unix command line to complete interactive tutorials and build projects."
```
Nitpick.

2021-09-29 07:49 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +          "These courses start you off with basic Bash commands. Using the terminal, you will learn everything from navigating and manipulating a file system, scripting in Bash, all the way to the ad
```suggestion
          "These courses start you off with basic Bash commands. Using the terminal, you will learn everything from navigating and manipulating a file system, scripting in Bash, all the way to advanced database usage.",
```
"advanced usage of and connection to" is a bit of a mouthful and I'm not sure mentioning "connection" adds much.

2021-10-04 04:25 UTC, Nirajn2311 reviewed
Some things I felt that could be written better. It's up to you to accept or dismiss it.

2021-10-04 04:25 UTC, Nirajn2311 commented on client/i18n/locales/english/intro.json
> +          "These courses start you off with basic Bash commands. Using the terminal, you will learn everything from navigating and manipulating a file system, scripting in Bash, all the way to advanc
Something about "start you off" doesn't sound right here. Maybe you can change it to:
```suggestion
          "In these courses you start off with the basic Bash commands. Using the terminal, you will learn everything from navigating and manipulating a file system, scripting in Bash, all the way to advanced database usage.",
```

or

```suggestion
          "These courses start off with basic Bash commands. Using the terminal, you will learn everything from navigating and manipulating a file system, scripting in Bash, all the way to advanced database usage.",
```

2021-10-04 04:25 UTC, Nirajn2311 commented on client/i18n/locales/english/intro.json
> +          "Finally, you will learn Git, the version control system, and GitHub, a code repository hosting service - two essential tools for every developer."
```suggestion
          "Finally, you will learn Git, the version control system, and GitHub, a code repository hosting service - two essential tools of every developer."
```

2021-10-07 14:52 UTC, gikf approved these changes
Looks good :+1:

2021-10-07 15:13 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-10-07 15:14 UTC, merged