fix : Added tests for curriculum order
freeCodeCamp/freeCodeCamp pull request #43581
Opened 2021-09-27 08:44 UTC by ankitkumarsamota121

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #43407

**Added tests for curriculum order.** 
- Checks for unique superBlock and superOrder
- Checks for unique order numbers for each block in a superBlock
- Console Warning if the order numbers do not start at 1 or are not contiguous
- Checks for unique challenge IDs inside each block

Also modified the order numbers and superOrder for legacy certification blocks.

2021-09-27 16:16 UTC, nhcarrigan requested changes
Hey there,

Thanks for getting this started - a quick nitpick on the spelling here.

Additionally, it looks like this test timed out on the GitHub action (which caps at 6 hours of runtime). Can you confirm that this test does not take 6 hours locally?

2021-09-27 16:16 UTC, nhcarrigan commented on curriculum/test/test-curriculum-order.js
> +            console.warn(`orders for ${key} are not contiguos`);
```suggestion
    it('order numbers are expected to be contiguous for each superBlock', function () {
      Object.keys(superBlocks).forEach(key => {
        const orders = Object.keys(superBlocks[key]).map(toNumber);
        orders.sort((a, b) => a < b);

        // expect(orders).to.deep.equal([...Array(orders.length).keys()]);
        for (let i = 1; i < orders.length; i++) {
          if (orders[i] !== orders[i - 1] + 1) {
            console.warn(`orders for ${key} are not contiguous`);
```

2021-09-30 13:45 UTC, ankitkumarsamota121 commented
Hi, I can confirm that this test does not take 6 hours locally. But I have observed that the complete test suite does not complete in the specified time. I ran the test suite just after cloning the repo and all the tests were passing in a few minutes. The only changes I have made are the addition of the tests for curriculum order (`curriculum/test/test-curriculum-order.js`) and changes of order and superOrder in the legacy challenges. 

I am unable to figure out what is causing the issue. Are there any other tests that depend on the order and superOrder in metafiles?

2021-10-05 07:59 UTC, ojeytonwilliams commented
As far as I can tell it's an issue with how our curriculum tests are structured.  Because we pass the `--delay` flag to `mocha` we need to invoke the `run()` command once all the tests are ready to go.  Since run is invoked by `test-challenges.js` I suspect there's a race condition between the two test files.

I 'solved' it locally by copying the new tests into `populateTestsForLang`, which makes sure all the `describe`s get called before `run`, which isn't terribly elegant, but seems to work.  The smart approach is probably to pass `--file` to `mocha` to specify `test-challenges.js` and rework `test-curriculum-order` to return a function analogous to `populateTestsForLang` which can be called before `run()`.

2021-11-02 10:31 UTC, raisedadead commented
Hi, 

We are closing old issues/pull requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull request.

Thanks for your understanding. 

Happy contributing.

2021-11-02 10:31 UTC, closed without merging