Feat/add foundational math cert
freeCodeCamp/freeCodeCamp pull request #43605
Opened 2021-09-29 04:06 UTC by moT01

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-09-29 12:48 UTC, ShaunSHamilton commented on client/src/templates/Introduction/components/Block.js
> +          challenge.superBlock !== 'foundational-math');
Should we not give this a new `challengeType`? I would prefer that.

2023-03-07 21:38 UTC, moT01 commented
I think we should get this in - it adds the college algebra cert behind the upcoming flag. Hopefully, it isn't too bloated.

2023-03-08 16:31 UTC, Sboonny reviewed
Translation and intro can be ignored and you don't need to add them for the other languages there, unless you are changing something in the 4 files `links`, `meta-tags`, `motiviation`, and `trending`. You can ask Naomi to be sure about this

https://contribute.freecodecamp.org/#/how-to-enable-new-languages?id=client-ui

2023-03-08 18:52 UTC, raisedadead approved these changes

2023-03-09 18:02 UTC, ShaunSHamilton commented on tools/scripts/seed/certified-user-data.js
> +  isCollegeAlgebraPyCertV8: false,
```suggestion
  isCollegeAlgebraPyCertV8: true,
```

I guess this is not forced, but we should add projects to the `completedChallenges` too.

2023-03-09 18:08 UTC, ShaunSHamilton requested changes

2023-03-09 18:08 UTC, ShaunSHamilton commented on curriculum/challenges/english/17-college-algebra-with-python/build-a-multi-function-calculator/multi-function-calculator.md
> +## --hints--
This should be removed, or should be `# --hints--`
```suggestion
```

2023-03-09 18:08 UTC, ShaunSHamilton commented on curriculum/challenges/english/17-college-algebra-with-python/build-a-graphing-calculator/graphing-calculator.md
> +## --hints--
```suggestion
```

2023-03-09 18:08 UTC, ShaunSHamilton commented on curriculum/challenges/english/17-college-algebra-with-python/build-a-financial-calculator/financial-calculator.md
> +## --hints--
```suggestion
```

2023-03-09 18:08 UTC, ShaunSHamilton commented on curriculum/challenges/english/17-college-algebra-with-python/build-a-data-graph-explorer/data-graph-explorer.md
> +## --hints--
```suggestion
```

2023-03-09 18:08 UTC, ShaunSHamilton commented on curriculum/challenges/english/17-college-algebra-with-python/build-three-math-games/three-math-games.md
> +## --hints--
```suggestion
```

2023-03-09 18:08 UTC, ShaunSHamilton commented on curriculum/challenges/english/17-college-algebra-with-python/build-a-multi-function-calculator/multi-function-calculator.md
> +## --hints--
<img width="472" alt="image" src="https://user-images.githubusercontent.com/51722130/224116882-38cd934e-73cf-4fa4-bcdd-0513b8c849ee.png">

2023-03-10 04:50 UTC, moT01 commented on client/src/templates/Introduction/components/block.tsx
> +      if (isProjectBlock && !isOdinProject)
There must have been some reason for it. I don't recall at the moment, adding this made the odin project not display correctly or something maybe.

2023-03-10 10:55 UTC, ShaunSHamilton approved these changes
LOTM 👍

2023-03-10 10:55 UTC, merged