fix(UI): prevent dup navigation on account delete
freeCodeCamp/freeCodeCamp pull request #43702
Opened 2021-10-03 18:46 UTC by Uzair-Fasih

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #39508

As I understand the issue happens because `deleteAccountSaga` navigates user to `/`, while the component `ShowSettings` rerenders and subsequently triggers the navigation to `/signin` as `isSignedIn` is no longer true. A less intrusive fix is to track if `isSignedIn` changes from true to false, and prevent navigation if that is the case. 

`isSignedIn` only goes from `true` to `false` for account delete. Signing out is a get request to server which redirects to some other page.

2021-10-11 13:04 UTC, Sembauke requested changes
Hey @Uzair-Fasih,

thank you for working on this.

Everything looks good, but when trying to access `/settings` directly, I get redirected to `/sigin`. I think we should also redirect to `/learn`.

2021-10-16 15:29 UTC, Sembauke approved these changes
LGTM 👍

2021-10-18 08:35 UTC, ojeytonwilliams requested changes

2021-12-04 11:43 UTC, raisedadead commented
Please reopen a fresh PR if you are still interested in fixing this, meanwhile we are freeing up the issue for others.

2021-12-04 11:43 UTC, closed without merging