feat(client): language dropdown in the side menu is now a drop down
freeCodeCamp/freeCodeCamp pull request #43729
Opened 2021-10-05 15:12 UTC by shangyilim

As suggested in #42951  I have made the following changes:
1. Make text wrap in the navigation menu items.
2. Added language dropdown menu in place of the language selection.
3. Prevent language dropdown menu from closing when selecting a language until after a language is selected.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42951

Screenshots:
1. Text wrap
![image](https://user-images.githubusercontent.com/6754603/136035856-fe59d10f-57e7-4ffb-924a-b728d885c782.png)
2. Language Dropdown
![image](https://user-images.githubusercontent.com/6754603/136050771-70e55029-849e-4793-8779-a2410b6f7d71.png)
![image](https://user-images.githubusercontent.com/6754603/136050905-5a79fa94-5789-4fd6-8f49-a4f04619e872.png)

2021-10-05 15:41 UTC, raisedadead approved these changes, later dismissed
Thanks for this PR. This looks great.

2021-10-05 16:01 UTC, ojeytonwilliams requested changes
Hi @shangyilim this looks neat, nice job!  I did find a couple of issues that need addressing, though:

2021-10-05 16:13 UTC, moT01 commented on client/src/components/Header/components/nav-links.tsx
> +                {langDisplayNames[lang]}
What about "change language" as the drop down without showing English
```
Change Language v
  English <check>
  Chinese
  Espanol
  ...
```

2021-10-06 04:04 UTC, Nirajn2311 commented on client/src/components/Header/components/nav-links.tsx
> +                {langDisplayNames[lang]}
Wouldn't it be better if "Change language" was shown first and below it the current language with the chevron. Something like:
```
Change Language
English v
  Chinese
  Espanol
  ...
```

This way you'll know the current chosen language also.

2021-10-06 17:08 UTC, shangyilim commented on client/src/components/Header/components/nav-links.tsx
> +    void navigate({
thanks for the pointers! got it fixed

2021-10-07 10:28 UTC, ojeytonwilliams requested changes
Thanks for sorting out the navigation, the latest changes look good :+1:   We'll definitely want to double-check on staging, though @raisedadead 

I did notice one weird quirk: if you have the dropdown open on mobile, it now takes two clicks to close the menu.  The first click collapses the dropdown and the second collapses the menu:
![Menu](https://user-images.githubusercontent.com/15801806/136367356-d8986bae-cf69-444d-b4e6-ea208647bb2c.gif)

2021-10-07 10:53 UTC, shangyilim commented
@ojeytonwilliams, thanks for the comment. I intentionally left the menu open because the select element lives inside the nav bar. If we were to hide the menu immediately, the drop doen options will be gone as well. I'm not sure what the expected behavior should be.

2021-10-07 11:14 UTC, raisedadead commented
I think the current behaviour of the menu is fine, @shangyilim thanks for your hard work on this.

2021-10-07 12:34 UTC, ojeytonwilliams submitted a review, later dismissed
LGTM :+1: 

I slightly prefer having a single click collapse everything, but that's just a minor thing. This PR is solid and solves the original problem.  Thanks for putting this together and for the productive discussion @shangyilim

2021-10-07 16:38 UTC, moT01 reviewed
This is looking good 👍 It's a little tricky to test, but here's my findings and concerns...

When I open a link locally, I get redirected to `http://chinese./learn` or `http://www./italian/learn` - I am going to assume that will work in production - I guess I expected to see a `localhost` in there or something.

The styling doesn't look too far off from a browsers default style. I am fine with this for now, but I would have preferred maybe some more padding and something that looks a little more like the rest of the buttons.

This appears to open links in the same tab (with redirection). The production behavior opens links in a new tab. I'm not sure if there was a reason for that. I'm fine using the redirect. If we keep that, this will also close https://github.com/freeCodeCamp/freeCodeCamp/issues/43639

2021-10-07 16:58 UTC, ojeytonwilliams commented
> When I open a link locally, I get redirected to http://chinese./learn or http://www./italian/learn - I am going to assume that will work in production - I guess I expected to see a localhost in there or something.

That is a bit odd, actually.  Could you copy `sample.env` over `.env` (clean cache, etc. etc.) and check it's still happening?

2021-10-07 17:40 UTC, ojeytonwilliams commented
Thanks @moT01, it worked on GitPod, so potentially it's just a local config issue.  Still needs investigating before we merge, though.

2021-10-13 13:43 UTC, ojeytonwilliams approved these changes
Sorry for the delay on this, @shangyilim.  Tom's right - this just a local dev issue, not a real problem.

Thanks for your patience and hard work on this. LGTM :+1:

2021-10-14 20:47 UTC, moT01 approved these changes
LGTM @shangyilim 🎉 

Hey @ahmadabdolsaheb - want to take a quick look at this and make sure we're okay with the drop down style for now. There's images in comments above, you don't need to run it.

2021-10-15 10:27 UTC, ojeytonwilliams commented
Good catch, Nick.  The select element just needs expanding to fill the parent.  Probably best to do this before merging, so we don't forget.

2021-10-15 12:40 UTC, ahmadabdolsaheb commented
Thanks @shangyilim for the pr.  I agree with Nick and Oliver about adjusting the width of the select element in this pr. We can customize the select further in future iterations.

2021-10-15 13:08 UTC, merged