refactor: change phrasing in challenges to make it easier to read
freeCodeCamp/freeCodeCamp pull request #43732
Opened 2021-10-05 17:50 UTC by import-brain

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

When I went through this challenge on the website, the wording was a bit confusing, so I fixed it.

2021-10-07 17:07 UTC, amyjtech submitted a review, later dismissed

2021-10-11 08:54 UTC, Sembauke requested changes

2021-10-11 15:19 UTC, Sembauke approved these changes

2021-10-14 20:54 UTC, moT01 approved these changes
LGTM 🎉

2021-10-14 20:54 UTC, merged