feat(client): ts-migration for Introduction templates
freeCodeCamp/freeCodeCamp pull request #43752
Opened 2021-10-06 22:00 UTC by Ismailtlem

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to the issue  #43778

2021-10-08 14:47 UTC, ShaunSHamilton requested changes
Thank you, for taking the time to contribute again, Ismail.

This PR is solid, but there is a glaring issue that TS annoyingly does not recognise, because Redux is not typed yet.

Otherwise, could you also rename the files to `kebab-case`?

2021-10-15 14:30 UTC, ShaunSHamilton requested changes
Sorry about this again, but I got confused with the typing, because I missed the transformation in the dispatch.

2021-10-28 14:21 UTC, ShaunSHamilton submitted a review, later dismissed
Thank you, for bearing with me. I resolved the conflicts, and pushed minor changes.

TLGTM 👍

2021-11-15 12:41 UTC, ojeytonwilliams commented on client/src/redux/prop-types.ts
> +
Now we have this, can we remove the StepsPropType?

2021-11-20 18:47 UTC, BIOSTYMA approved these changes

2021-11-24 18:20 UTC, moT01 approved these changes, later dismissed
LGTM @Ismailtlem :tada:

2021-11-27 19:44 UTC, ShaunSHamilton approved these changes
I just added some types to remove the need for `eslint-disable` lines.

@moT01 Please merge, if you are still happy.

2021-11-30 18:36 UTC, moT01 approved these changes
LGTM @Ismailtlem :tada: Thanks for contributing to freeCodeCamp :tada:

2021-11-30 18:36 UTC, merged