CHORE: migrate intro component
freeCodeCamp/freeCodeCamp pull request #43784
Opened 2021-10-08 17:14 UTC by RobertoMSousa

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes part of #43778

Migrate the intro component and the test files.

2021-10-11 08:51 UTC, Sembauke submitted a review, later dismissed

2021-10-12 14:28 UTC, naomi-lgbt requested changes
A tiny nitpick, but AFAIK this is how we've been naming the prop interfaces.

2021-10-12 21:44 UTC, RobertoMSousa commented
fixed @nhcarrigan, Thanks for the feedback
Usually if the props are not exported just like this case there is no need to specify the source on the name.
But more than happy to follow the code convention 🙂

2021-10-13 22:01 UTC, naomi-lgbt approved these changes
I think I'm happy with this. Nice work!

2021-10-14 13:18 UTC, Sembauke approved these changes

2021-10-14 13:19 UTC, merged