chore(client): migrate TestSuite component to TypeScript
freeCodeCamp/freeCodeCamp pull request #43794
Opened 2021-10-09 09:48 UTC by sitek94

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Is part of #43778

Migrated TestSuite component to TypeScript.

2021-11-22 06:35 UTC, raisedadead commented on client/src/redux/prop-types.ts
> +} & ChallengeTest;
@ShaunSHamilton is this resolved and ready?

2021-11-25 14:18 UTC, moT01 commented
✅ rebased
✅ conflicts fixed

2021-11-25 15:19 UTC, ojeytonwilliams requested changes
The `videoUrl`s can be required (removing the ?s doesn't flag up any errors, so I think we're good)

2021-11-25 15:19 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/tool-panel.tsx
> +  videoUrl?: string;
```suggestion
  videoUrl: string;
```

2021-11-25 15:19 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/side-panel.tsx
> +  videoUrl?: string;
```suggestion
  videoUrl: string;
```

2021-11-27 19:59 UTC, ShaunSHamilton approved these changes
Thanks, for your patience, @sitek94 .

I have just pushed the changes Oliver suggested, with one of my own.

This LGTM 👍 

cc @ojeytonwilliams

2021-11-29 08:58 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

Thanks @sitek94!

2021-11-29 08:58 UTC, merged