chore(client): migrate landing.test.js to ts
freeCodeCamp/freeCodeCamp pull request #43889
Opened 2021-10-15 20:29 UTC by JasmineSun33

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes one task from #43778

2021-10-18 19:49 UTC, naomi-lgbt requested changes

2021-10-26 18:53 UTC, nhcarrigan submitted a review, later dismissed

2021-11-29 22:13 UTC, ShaunSHamilton approved these changes
This LGTM 👍

2021-12-09 03:26 UTC, moT01 reviewed
LGTM @JasmineSun33 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

2021-12-09 03:27 UTC, merged