feat(i18n): Add more motivational phrases and quotes in Spanish
freeCodeCamp/freeCodeCamp pull request #43970
Opened 2021-10-22 14:50 UTC by RafaelDavisH

Add more motivational phrases and quotes in Spanish

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

2021-10-22 14:54 UTC, naomi-lgbt submitted a review, later dismissed
Somehow got one of those smart quotes in here.

2021-10-22 16:07 UTC, majestic-owl448 approved these changes

2021-10-22 17:51 UTC, ejcheng submitted a review, later dismissed

2021-10-25 03:57 UTC, raisedadead submitted a review, later dismissed

2021-10-25 11:05 UTC, majestic-owl448 requested changes
With these it should work maybe

2021-10-25 16:25 UTC, majestic-owl448 submitted a review, later dismissed

2021-10-25 17:38 UTC, majestic-owl448 approved these changes

2021-10-25 17:39 UTC, raisedadead approved these changes

2021-10-25 17:39 UTC, merged