feat(client): ts-migration for EditorTabs component
freeCodeCamp/freeCodeCamp pull request #44006
Opened 2021-10-25 21:53 UTC by Ismailtlem

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #43778

2021-10-27 16:52 UTC, naomi-lgbt requested changes
Quick linter issue 🙂

2021-11-09 13:32 UTC, Ismailtlem commented
@nhcarrigan any feedback left ?

2021-11-09 14:17 UTC, ShaunSHamilton requested changes
Thank you, for another one, Ismail.

Small changes, then this is good to go.

2021-11-09 14:17 UTC, ShaunSHamilton commented on client/src/templates/Challenges/classic/editor-tabs.tsx
> +type VisibleEditorsType = {
Some devs do not like being explicit (👀 @ojeytonwilliams 👀 )

```suggestion
type VisibleEditors = {
```

2021-11-09 14:17 UTC, ShaunSHamilton commented on client/src/templates/Challenges/classic/editor-tabs.tsx
> +  (visibleEditors: VisibleEditorsType, challengeFiles: ChallengeFiles) => ({
```suggestion
  (visibleEditors: VisibleEditors, challengeFiles: ChallengeFiles) => ({
```

2021-11-09 14:17 UTC, ShaunSHamilton commented on client/src/templates/Challenges/classic/editor-tabs.tsx
> +  visibleEditors: VisibleEditorsType;
```suggestion
  visibleEditors: VisibleEditors;
```

2021-11-09 14:17 UTC, ShaunSHamilton commented on client/src/templates/Challenges/classic/editor-tabs.tsx
> +        {/* eslint-disable-next-line @typescript-eslint/no-unsafe-call*/}
```suggestion
        {/* eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call */}
```

2021-11-09 14:17 UTC, ShaunSHamilton commented on client/src/templates/Challenges/classic/editor-tabs.tsx
> +/* eslint-disable @typescript-eslint/no-unsafe-member-access */
No need to enable this globally

```suggestion
```

2021-11-10 14:41 UTC, ShaunSHamilton approved these changes
Thank you, for handling that 👍 

This LGTM

2021-11-10 16:49 UTC, nhcarrigan approved these changes
Looks good to me!

2021-11-10 16:50 UTC, merged