feat(client): ts-migration for the Mobile Layout component
freeCodeCamp/freeCodeCamp pull request #44082
Opened 2021-10-31 20:52 UTC by Ismailtlem

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to the issue  #43778

2021-11-01 12:14 UTC, Sembauke submitted a review, later dismissed

2021-11-03 20:09 UTC, nhcarrigan requested changes
Can we rename the file to `mobile-layout.tsx`? I believe that's the convention we've been using.

2021-11-03 21:15 UTC, nhcarrigan approved these changes, later dismissed
Looks good to me!

2021-11-09 15:38 UTC, ojeytonwilliams requested changes
Hey @Ismailtlem this looks good, I just had one question about optional types:

2021-11-09 15:38 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/mobile-layout.tsx
> +  testOutput?: JSX.Element;
```suggestion
  hasPreview: boolean;
  instructions: JSX.Element;
  moveToTab: typeof moveToTab;
  preview: JSX.Element;
  testOutput: JSX.Element;
```
Do these need to be optional?

2021-11-09 20:06 UTC, Ismailtlem commented on client/src/templates/Challenges/classic/mobile-layout.tsx
> +  testOutput?: JSX.Element;
I don't think so @ojeytonwilliams

2021-11-09 20:29 UTC, ojeytonwilliams approved these changes
LGTM 👍

2021-11-09 20:30 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/mobile-layout.tsx
> +  testOutput?: JSX.Element;
Thanks @Ismailtlem

2021-11-10 08:29 UTC, Sembauke approved these changes

2021-11-10 08:29 UTC, merged

2021-11-10 08:29 UTC, Sembauke commented
Hey @Ismailtlem, thank you for taking this on!