feat: highlight editable region
freeCodeCamp/freeCodeCamp pull request #44123
Opened 2021-11-04 14:49 UTC by ojeytonwilliams

This gives the editable region a lighter background than the rest of the editor.  Hopefully this will draw the user's eye to the right part of the page.

Before:

![BeforeDay](https://user-images.githubusercontent.com/15801806/140335766-fb0320d9-bd7b-4158-95d1-0954f99e3de7.png)
![BeforeNight](https://user-images.githubusercontent.com/15801806/140335779-173ed232-29fb-4bf2-889d-48c699420692.png)

and after:

![AfterDay](https://user-images.githubusercontent.com/15801806/140335842-d955ecfb-0920-4e71-9832-2b115c159ee2.png)
![AfterNight](https://user-images.githubusercontent.com/15801806/140335859-0b6fef28-f985-49be-b583-02a0d676cd44.png)

2021-11-04 15:43 UTC, nhcarrigan approved these changes, later dismissed
TBH I really love this.

2021-11-04 15:54 UTC, ojeytonwilliams commented
@nhcarrigan I forget if it was @ahmadabdolsaheb's idea, but he's the one that realised it could be done so simply.

2021-11-04 19:55 UTC, ShaunSHamilton requested changes
Personally, i am not a fan of this border (against the new background):
![image](https://user-images.githubusercontent.com/51722130/140410095-6b5d04a1-626d-42cc-a442-28c87d4b639b.png)

Also, changing the theme in editor results in the background not showing:
![image](https://user-images.githubusercontent.com/51722130/140410379-d96b0b7c-5aa1-4f4c-89ec-7f258699e720.png)

A refresh also does not yield any background for the light theme?

2021-11-04 19:55 UTC, ShaunSHamilton commented on client/src/templates/Challenges/classic/editor.tsx
> +    console.log('editorWillMount', props);
```suggestion
```

2021-11-04 20:01 UTC, ShaunSHamilton commented on client/src/templates/Challenges/classic/editor.tsx
> +    console.log('editorWillMount', props);
`usesMultifileEditor` is always `false`, from what I can see?

2021-11-04 21:27 UTC, ojeytonwilliams commented
> Also, changing the theme in editor results in the background not showing:

What steps should I take to see this?

The border is helpful, imo, since it helps you see where you're working. That said, we at least want to adjust the style @ahmadabdolsaheb :)

2021-11-05 00:24 UTC, ShaunSHamilton commented
> What steps should I take to see this?

What I did was:
1) Develop client
2) Open `/learn`
3) Change theme to prevent permanent eye damage
4) Navigate to an UPCOMING challenge
5) Change theme to cause permanent eye damage
6) See there is no highlight

2021-11-05 11:22 UTC, ojeytonwilliams commented
@ShaunSHamilton I followed your ophthalmic instructions and got this:

![image](https://user-images.githubusercontent.com/15801806/140503000-c6681eb5-86c5-4470-830b-637be2031eab.png)

which looks right to me.

2021-11-05 12:38 UTC, ShaunSHamilton approved these changes
After doing something, the highlighting appeared for the Light theme. I do not know what changed 🤷‍♂️

2021-11-05 15:41 UTC, nhcarrigan approved these changes
While I miss the poor console log that @ShaunSHamilton yeeted, I'm still happy with this. 🙂

2021-11-05 15:41 UTC, merged

2021-11-06 08:41 UTC, ahmadabdolsaheb commented
Great functionality @ojeytonwilliams. I like how the editor UI in maturing. We could re-adjust the contrast around the editable region and play around with the borders to see if it would look better, but that should be straight forward.