chore: rename cafe menu
freeCodeCamp/freeCodeCamp pull request #44201
Opened 2021-11-18 17:02 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-11-19 19:27 UTC, ShaunSHamilton requested changes

2021-11-19 19:27 UTC, ShaunSHamilton commented on utils/preformatted-block-names.json
> +  "learn-basic-css-by-building-a-cafe-menu": "CSS Cafe Menu",
We discussed this, no?

```suggestion
  "learn-basic-css-by-building-a-cafe-menu": "Learn Basic CSS by Building a Cafe Menu",
```

2021-11-19 19:37 UTC, ShaunSHamilton approved these changes, later dismissed
GTGTLTM 👍

2021-11-20 04:14 UTC, moT01 approved these changes
LGTM 🎉

2021-11-20 04:22 UTC, merged