chore: rename css skyline
freeCodeCamp/freeCodeCamp pull request #44211
Opened 2021-11-18 20:08 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-11-19 19:58 UTC, ShaunSHamilton requested changes

2021-11-19 19:58 UTC, ShaunSHamilton commented on client/src/pages/learn/responsive-web-design/learn-css-variables-by-building-a-city-skyline/index.md
> +block: Learn CSS Variables by Building a City Skyline
I am not sure if this was your doing, or if some of them just look like this 🤷‍♂️ 

```suggestion
block: learn-css-variables-by-building-a-city-skyline
```

2021-11-19 21:47 UTC, ShaunSHamilton submitted a review, later dismissed

2021-11-20 12:02 UTC, ShaunSHamilton approved these changes

2021-11-20 14:34 UTC, moT01 approved these changes
LGTM :tada:

2021-11-20 14:34 UTC, merged