fix(cirriculum): add better testcase for insert-an-element-into-a-max-heap challenge
freeCodeCamp/freeCodeCamp pull request #44285
Opened 2021-11-25 14:49 UTC by Prathamesh010

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44269

2021-11-25 16:05 UTC, gikf reviewed
This makes code from the issue not pass, but some other faulty solutions can now pass, for example:
```js
var MaxHeap = function() {
  // Only change code below this line
      this.heap = [null];
      this.insert = value => {
        this.heap[1] = value;
      }
      this.print = () => {
        return this.heap;
      }
  // Only change code above this line
};
```

What do you think about checking order of the whole heap (minus possible `null` as first element)? Shouldn't those be the same for any correct implementation?

2021-11-26 04:31 UTC, Prathamesh010 commented
Yes, Checking the order of the final heap to determine the result is a better way to test it.

2021-11-26 08:59 UTC, gikf requested changes
Thanks for the update. I've included couple notes below.

2021-11-26 08:59 UTC, gikf commented on curriculum/challenges/english/10-coding-interview-prep/data-structures/insert-an-element-into-a-max-heap.md
> +    return (result.length == 6) ? (result == solution) : (result == solutionWithoutNull);
`result` is here stringified version of the heap array, so length `6` will neither be right for version with null nor without.

Assuming length of the heap array will be checked, it should be compared to `7`, as that's how are ordered comparisons with solutions later in the ternary operator.

And from the nitpicking - those variables can be declared with `const`.

2021-11-26 10:54 UTC, Prathamesh010 commented
I made the changes. 
Also, I noticed that the provided [solution](https://forum.freecodecamp.org/t/freecodecamp-challenge-guide-insert-an-element-into-a-max-heap/301703) on the forum needs some changes. 

```javascript
while (ele > arr[Math.floor(index / 2)] && index > 1) {
      arr[index] = arr[Math.floor(index / 2)];
      arr[Math.floor(index / 2)] = ele;
      index = arr[Math.floor(index / 2)]; // this should be index = Math.floor(index/2)
}
```

2021-11-26 15:35 UTC, gikf approved these changes
Looks good to me :+1: 

I've tried few implementations, which were giving the expected result as here. If that won't be enough, some alternative could be more manually checking if returned heap array follows max heap conditions.

2021-11-29 20:43 UTC, nhcarrigan approved these changes
This looks good to me.

2021-11-29 20:43 UTC, merged

2021-11-29 20:43 UTC, nhcarrigan commented
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉