Getting rid of extra whitespace.
freeCodeCamp/freeCodeCamp pull request #44301
Opened 2021-11-27 15:09 UTC by animesharma3

My first open source contributions.
I just got rid of the extra whitespace, that way the document looks better.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2021-11-27 17:31 UTC, raisedadead approved these changes
#### :sparkles: :sparkles: **AWESOME! LGTM.** :sparkles: :sparkles: 

Thanks, @., for this pull request and for contributing to the code-base for the first time.

We will be looking forward to more contributions in future.

Cheers and happy contributing!

2021-11-27 18:39 UTC, ShaunSHamilton requested changes
Thank you, for taking the time to open this. However, our Prettier config does not allow this format to pass our Lint checks - for good reason.

I suggest following [this section](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=follow-these-steps-to-get-your-development-environment-ready) of the Contributor's Docs to see how to set up your local environment for contributing to this repository.

2021-11-27 18:39 UTC, ShaunSHamilton commented on HoF.md
> +> ### Thank you for your contributions :pray:
```suggestion

> ### Thank you for your contributions :pray:
```

2022-01-07 09:19 UTC, raisedadead commented
Hi, 

We are closing old issues/pull-requests that we think are stale. If you need still need help with this or are fixing this, please open a fresh issue/pull-request.

Thanks for your understanding. 

Happy contributing.

2022-01-07 09:19 UTC, closed without merging