Change in broken link and  i resolved it
freeCodeCamp/freeCodeCamp pull request #44327
Opened 2021-11-30 06:41 UTC by gourcool

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #44293

2021-11-30 09:30 UTC, gikf requested changes
Could you make similar change to the other python projects in _Scientific Computing with Python Projects_?

Note for future - it is recommended to make changes on a separate branch, than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally.

2021-11-30 09:48 UTC, gourcool commented on curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter.md
> +- [Learn Python Video Course](https://www.freecodecamp.org/news/learn-python-basics-in-depth-video-course/) (10 hours)
Can you please assign these changes to me I happy to help

2021-11-30 09:57 UTC, gikf commented on curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter.md
> +- [Learn Python Video Course](https://www.freecodecamp.org/news/learn-python-basics-in-depth-video-course/) (10 hours)
I'm not able to suggest changes to those files, like to one above, as they weren't changed in the PR yet, and github doesn't give such option.

You can add changes in new commit and push it to the same branch, the PR will be updated with new commit.

2021-11-30 09:58 UTC, gourcool commented on curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter.md
> +- [Learn Python Video Course](https://www.freecodecamp.org/news/learn-python-basics-in-depth-video-course/) (10 hours)
ok thanks

2021-11-30 10:38 UTC, Mateusza-jpg commented
Część potrzebuje pomocy


wt., 30 lis 2021, 10:31 użytkownik Krzysztof G. ***@***.***>
napisał:

> ***@***.**** requested changes on this pull request.
>
> Could you make similar change to the other python projects in *Scientific
> Computing with Python Projects*?
>
> Note for future - it is recommended to make changes on a separate branch,
> than the main branch. See more about it in point 3 at
> https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally?id=making-changes-locally
> .
> ------------------------------
>
> In
> curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/arithmetic-formatter.md
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/44327#discussion_r759084430>
> :
>
> > @@ -13,7 +13,7 @@ You will be [working on this project with our Replit starter code](https://repli
>
>  We are still developing the interactive instructional part of the Python curriculum. For now, here are some videos on the freeCodeCamp.org YouTube channel that will teach you everything you need to know to complete this project:
>
>
>
>  - [Python for Everybody Video Course](https://www.freecodecamp.org/news/python-for-everybody/) (14 hours)
>
> -- [Learn Python Video Course](https://www.freecodecamp.org/news/learn-python-video-course/) (10 hours)
>
> +- [Learn Python Video Course](https://www.freecodecamp.org/news/learn-python-basics-in-depth-video-course/) (10 hours)
>
>
> ⬇️ Suggested change
>
> -- [Learn Python Video Course](https://www.freecodecamp.org/news/learn-python-basics-in-depth-video-course/) (10 hours)
>
> +- [Learn Python Video Course](https://www.freecodecamp.org/news/learn-python-basics-in-depth-video-course/) (4 hours)
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/44327#pullrequestreview-818762692>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWWV7HEGGQELJGTV4SJBYGTUOSKWFANCNFSM5JA7BFZA>
> .
>

2021-12-08 14:17 UTC, ShaunSHamilton requested changes
Thank you, for taking the time to open this.

However, it seems we might be going with a different solution for all of the challenges. I will leave this open for now, until we have decided on the best way to resolve the issue.

2022-01-13 21:27 UTC, nhcarrigan commented
@ShaunSHamilton do you recall where that discussion was? And what the plan for this PR is?

2022-01-14 07:15 UTC, ShaunSHamilton commented
@nhcarrigan The discussion was on the linked issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/44293#issuecomment-988845198

2022-01-14 17:01 UTC, nhcarrigan commented
Thanks @ShaunSHamilton you're the best 🙂 

@gourcool apologies for the delay on reviewing this contribution. It looks like the consensus is to remove the "We are still developing..." text, as well as the subsequent links. Would you be interested in updating your PR to reflect that?

2022-02-02 11:00 UTC, ahmadabdolsaheb commented
@gourcool, It would be great if we could update the pr based on the above feedback so we could move forward with merging your solution.

Let us know if you need any help.

2022-02-23 08:25 UTC, closed without merging