feat: add footer dec 2021
freeCodeCamp/freeCodeCamp pull request #44413
Opened 2021-12-08 09:48 UTC by ahmadabdolsaheb

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Once this is merged, I will update the footer for the forum and news.

2021-12-08 12:59 UTC, raisedadead submitted a review, later dismissed

2021-12-08 14:35 UTC, nhcarrigan requested changes
These truncated links all 404 for me.

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article6link": "https://www.freecodecamp.org/news/the-model-view-c…attern-mvc-architecture-and-frameworks-explained/",
```suggestion
  "article6link": "https://www.freecodecamp.org/news/the-model-view-controller-pattern-mvc-architecture-and-frameworks-explained/",
```

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article7link": "https://www.freecodecamp.org/news/front-end-develo…front-end-development-explained-in-plain-english/",
```suggestion
  "article7link": "https://www.freecodecamp.org/news/front-end-developer-what-is-front-end-development-explained-in-plain-english/",
```

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article8link": "https://www.freecodecamp.org/news/what-is-a-full-s…developer-back-end-front-end-full-stack-engineer/",
```suggestion
  "article8link": "https://www.freecodecamp.org/news/what-is-a-full-stack-developer-back-end-front-end-full-stack-engineer/",
```

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article10link": "https://www.freecodecamp.org/news/bash-sleep-how-t…ke-a-shell-script-wait-n-seconds-example-command/",
```suggestion
  "article10link": "https://www.freecodecamp.org/news/bash-sleep-how-to-make-a-shell-script-wait-n-seconds-example-command/",
```

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article20link": "https://www.freecodecamp.org/news/javascript-tolow…onvert-a-string-to-lowercase-and-uppercase-in-js/",
```suggestion
  "article20link": "https://www.freecodecamp.org/news/javascript-tolowercase-how-to-convert-a-string-to-lowercase-and-uppercase-in-js/",
```

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article24link": "https://www.freecodecamp.org/news/the-best-way-to-…python-python-programming-tutorial-for-beginners/",
```suggestion
  "article24link": "https://www.freecodecamp.org/news/the-best-way-to-learn-python-python-programming-tutorial-for-beginners/",
```

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article25link": "https://www.freecodecamp.org/news/word-count-in-go…ords-and-characters-in-a-google-doc-or-word-file/",
```suggestion
  "article25link": "https://www.freecodecamp.org/news/word-count-in-google-docs-tutorial-counting-words-and-characters-in-a-google-doc-or-word-file/",
```

2021-12-08 14:35 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article26link": "https://www.freecodecamp.org/news/how-to-use-node-…variables-with-a-dotenv-file-for-node-js-and-npm/",
```suggestion
  "article26link": "https://www.freecodecamp.org/news/how-to-use-node-environment-variables-with-a-dotenv-file-for-node-js-and-npm/",
```

2021-12-09 06:39 UTC, ahmadabdolsaheb commented
> These truncated links all 404 for me.

Thanks for catching that. 🙏

2021-12-09 15:09 UTC, nhcarrigan approved these changes

2021-12-09 15:11 UTC, ShaunSHamilton approved these changes
LGTM 👍

2021-12-09 15:11 UTC, merged