Update staff forum section link in Moderator Handbook
freeCodeCamp/freeCodeCamp pull request #44529
Opened 2021-12-20 15:21 UTC by lasjorg

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

The current staff forum link is wrong.

2021-12-20 17:02 UTC, gikf reviewed
This link is for forum mods only, right? Maybe it'd be beneficial to add information about that by the link.

2021-12-20 17:48 UTC, raisedadead requested changes
I agree with @gikf - how about something like this.

2021-12-20 17:48 UTC, raisedadead commented on docs/moderator-handbook.md
> +You can ask questions and report incidents in the [staff forum section](https://forum.freecodecamp.org/c/mod-team/4).
```suggestion
As a moderator, you can ask questions and report incidents in the [staff forum section](https://forum.freecodecamp.org/c/mod-team/4).
```

2021-12-20 21:51 UTC, ShaunSHamilton approved these changes
LGTM 👍

2021-12-21 04:08 UTC, raisedadead approved these changes

2021-12-21 04:08 UTC, merged