fix: make gatsby id static for hot reloading
freeCodeCamp/freeCodeCamp pull request #44542
Opened 2021-12-21 18:01 UTC by moT01

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44514

2021-12-21 20:01 UTC, ojeytonwilliams requested changes
This should do the trick, but I think it would be good to add a uniqueness check (in case of weirdness) and turn hot-reloading back.  It's not a lot of code and it means we can test the reloading.

2021-12-22 15:10 UTC, moT01 commented
Can you clarify what you mean by "turn hot-reloading back".

2021-12-22 15:18 UTC, ojeytonwilliams commented
:man_facepalming: I wasn't thinking straight.  You can ignore that comment.

2021-12-22 15:20 UTC, moT01 commented
That part of the comment or the whole thing - do we still want the uniqueness check?

2021-12-22 15:29 UTC, ojeytonwilliams commented
>  do we still want the uniqueness check?

I think so. It's *really* confusing when the ids clash, so it's worth guarding against that.

2021-12-22 18:34 UTC, cronlabspl commented
> so it's worth guarding against that.

True.

2022-01-07 07:53 UTC, raisedadead commented
To fix tests & update the status, when ready.

2022-01-07 11:55 UTC, cronlabspl commented
> To fix tests & update the status, when ready.

Sorry, what?

2022-01-10 08:26 UTC, ojeytonwilliams approved these changes
@moT01 I realised how painful it was that this was broken, so I went ahead and added the tests.  I hope that's okay!

2022-01-10 08:50 UTC, cronlabspl approved these changes
Looks good to me 👍

2022-01-10 08:53 UTC, cronlabspl approved these changes
Looks good to me 👍

2022-01-10 08:57 UTC, ojeytonwilliams commented on client/plugins/fcc-source-challenges/create-challenge-nodes.js
> -        { id: crypto.randomUUID() }
This is part of the client build process, so won't effect the performance of the site.  If you do find it's slow, though, please open an issue so we can fix it.

2022-01-10 09:00 UTC, ShaunSHamilton approved these changes
LGTM 👍

2022-01-10 09:03 UTC, merged