docs: expand the responsible disclosure
freeCodeCamp/freeCodeCamp pull request #44549
Opened 2021-12-22 05:18 UTC by raisedadead

2021-12-22 16:25 UTC, nhcarrigan requested changes
Tiny nit.

2021-12-22 16:25 UTC, nhcarrigan commented on docs/security.md
> +We consider using tools & online utilities to report issues with SPF & DKIM configs, or SSL Server tests, etc. in the category of ["beg bounties"](https://www.troyhunt.com/beg-bounties/) are unable t
```suggestion
We consider using tools & online utilities to report issues with SPF & DKIM configs, or SSL Server tests, etc. in the category of ["beg bounties"](https://www.troyhunt.com/beg-bounties/) and are unable to respond to these reports.
```

2021-12-22 16:35 UTC, nhcarrigan approved these changes

2021-12-23 05:33 UTC, raisedadead commented
Merging this to update the autoreply.

2021-12-23 05:33 UTC, merged