docs: add FAQ about paths to being a moderator
freeCodeCamp/freeCodeCamp pull request #44701
Opened 2022-01-06 18:20 UTC by erictleung

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #44408

These suggestions are probably not exhaustive, nor entirely correct (because I'm not as versed in the other sub-communities, e.g., the forums). Please suggest any changes that you feel might be helpful.

2022-01-06 20:21 UTC, nhcarrigan requested changes
This is awesome. Thanks for getting this going! One tiny fix, and then I think this is good to go.

> These suggestions are probably not exhaustive, nor entirely correct

It may not be comprehensive, but it is definitely a great starting point that we can iterate on as needed. 🙂

2022-01-06 20:21 UTC, nhcarrigan commented on docs/FAQ.md
> +freeCodeCamp make freeCodeCamp a safe and welcoming community.
```suggestion
Our community moderators are our heroes. Their voluntary contributions make
freeCodeCamp a safe and welcoming community.
```

2022-01-06 20:49 UTC, erictleung commented
@nhcarrigan thanks for taking a look! Nice spelling catch. In looking at the plural of hero, TIL that Heros is a kind of fish in South America https://en.wikipedia.org/wiki/Heros_(fish)

2022-01-06 21:09 UTC, nhcarrigan approved these changes
🐟

2022-01-07 07:45 UTC, raisedadead approved these changes

2022-01-07 07:47 UTC, raisedadead commented
Eric, Thanks for taking the time to contribute. This is going to be of help quite a lot.

2022-01-07 07:47 UTC, merged