fix: ensure index.html is always first in source map
freeCodeCamp/freeCodeCamp pull request #44720
Opened 2022-01-07 23:29 UTC by bbsmooth

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This PR sets us up to finish [issue 44626](https://github.com/freeCodeCamp/freeCodeCamp/issues/44626) by ensuring that the HTML in index.html will always be processed first when building the source map. The `index` property on the source map contains a string that combines index.html and styles.css (which is then used for the assert tests in each step). Currently the order is determined by which file was edited last, with the the most recently edited file being placed **last** in the combined string. This is causing an issue when checking for proper placement of the DOCTYPE declaration. The user edits index.html to add the DOCTYPE, which places it after styles.css in the `index` string. By default, if styles.css does not have any content then the system adds `/*fcc*/` to styles.css, which then comes before the DOCTYPE declaration in the `index` string, adding extra complexity when checking that DOCTYPE is the first element in index.html.

Furthermore, while this DOCTYPE check is usually done during the first step in the course and the user has not been instructed to add anything to styles.css, they technically are able to, and this fix would allow the test to ignore anything they add there as well as anything adding in styles.css would come after the HTML in index.html.

I have also included a modified DOCTYPE test for the Ferris Wheel course so you can see what the new assert would look like and test it for yourselves. I will wait for this fix to be merged before fixing the other courses just in case this isn't approved or changes have been made that might affect how we do the tests.

2022-01-08 09:32 UTC, ojeytonwilliams requested changes
Thanks @bbsmooth, I like the approach here and I think we should extend it to handle later projects (ones with more files).

Also, good point about the `/*fcc*/` comments.  I've been meaning to clean them up for a while, but I'll take care of that in another PR.

2022-01-08 09:32 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/build.js
> +  const source = fixedChallengeFiles.reduce(
```suggestion
  // Make sure index.html is always first
  const source = sortChallengeFiles(challengeFiles).reduce(
```
I think we'll always want the `index.html` to be first, even when we're looking at steps that have `js` or `jsx` files.  `sortChallengeFiles` can be found in utils/sort-challengefiles.js

2022-01-08 10:17 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/build.js
> +  const source = fixedChallengeFiles.reduce(
Sorry, that won't work.  I'd forgotten that the `ext` property gets transformed, so `sortChallengeFiles` doesn't know what to do with these.  I'll make that function more robust and then this should be okay.

2022-02-06 18:07 UTC, bbsmooth commented
This PR got the ball rolling but was never used and can be closed.

2022-02-06 18:07 UTC, closed without merging