fix: small lint fix in challenges functions
freeCodeCamp/freeCodeCamp pull request #44728
Opened 2022-01-08 16:14 UTC by thomscoder

This commit should solve issue #44721.
It's more like a UI fix rather than an Issue.
The "issue" was an extra space on certain named function:
https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/refactor-global-variables-out-of-functions

<img width="411" alt="Schermata 2022-01-08 alle 17 02 42" src="https://user-images.githubusercontent.com/78874117/148651233-24d754d7-3e56-4cf2-81ae-1b5a758d9bd3.png">

It's probably the linter default format according to eslint docs: https://eslint.org/docs/rules/space-before-function-paren but I didn't want to touch linter config for now cause a simple find all and replace should solve it.

2022-01-08 19:06 UTC, nhcarrigan requested changes
Hey there,

Please revert your changes to the non-English files. When the English file is changed, our automation will upload the changes to our translation platform, and from there they will be pulled down to the codebase.

2022-01-08 19:35 UTC, thomscoder commented
> Hey there,
> 
> Please revert your changes to the non-English files. When the English file is changed, our automation will upload the changes to our translation platform, and from there they will be pulled down to the codebase.

Hello there,
thank you for the heads up! Done

2022-01-10 20:24 UTC, nhcarrigan approved these changes
This looks good to me.

A quick note to the team that this fixes the spacing issue, but there's further discussion to be had on the linked issue.

2022-01-10 23:56 UTC, jdwilkin4 approved these changes
LGTM! 👍

2022-01-10 23:57 UTC, merged