feat: update footer January 22
freeCodeCamp/freeCodeCamp pull request #44749
Opened 2022-01-11 12:45 UTC by ahmadabdolsaheb

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-01-11 18:14 UTC, nhcarrigan requested changes

2022-01-11 18:14 UTC, nhcarrigan commented on client/i18n/locales/english/trending.json
> +  "article9title": "Basic HTML5 Template ",
```suggestion
  "article9title": "Basic HTML5 Template",
```
Extra space.

2022-01-12 10:58 UTC, Sembauke approved these changes

2022-01-12 11:02 UTC, ShaunSHamilton approved these changes
LGTM 👍

2022-01-12 14:21 UTC, nhcarrigan approved these changes

2022-01-12 14:21 UTC, merged

2022-01-12 14:21 UTC, nhcarrigan commented
Thanks Ahmad!