update step-36.md
freeCodeCamp/freeCodeCamp pull request #44840
Opened 2022-01-19 16:14 UTC by Abdullah-Irfan-web

changed 'a' elements to 'img' elements

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-01-19 16:41 UTC, Abdullah-Irfan-web commented
okay i have reviewed it on codesee

On Wed, Jan 19, 2022 at 10:01 PM Abdullah Irfan ***@***.***>
wrote:

> can you please tell me what i am suppose to do here
>
> On Wed, Jan 19, 2022 at 9:46 PM codesee-architecture-diagrams[bot] <
> ***@***.***> wrote:
>
>> 👀 Review this PR in a CodeSee Review Map
>> <https://app.codesee.io/r/reviews?pr=44840&src=https%3A%2F%2Fgithub.com%2FfreeCodeCamp%2FfreeCodeCamp>
>> Preview the Review Map
>>
>> [image: Review these changes using an interactive CodeSee Map]
>> <https://app.codesee.io/r/reviews?pr=44840&src=https%3A%2F%2Fgithub.com%2FfreeCodeCamp%2FfreeCodeCamp>
>> Legend
>>
>> [image: CodeSee Map Legend]
>> <https://camo.githubusercontent.com/e169ec986a332c10dc75bdc851178cd62b5a2f014f632fdba6a9f4d9715f649a/68747470733a2f2f6170702e636f64657365652e696f2f4c6567656e645f76322e706e67>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/freeCodeCamp/freeCodeCamp/pull/44840#issuecomment-1016628949>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AULZGBCLZHMCXFMZQE6MR3TUW3PVBANCNFSM5MKLTTNA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-01-19 17:45 UTC, jdwilkin4 requested changes

2022-01-19 17:45 UTC, jdwilkin4 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/step-036.md
> +The `input` element allows you several ways to collect data from a web form. Like images (`img`) elements, `input` elements are <dfn>self-closing</dfn> and do not need closing tags.
In the second sentence, we should change images (`img`) elements to just say `img` elements. 

Proposed change: Like `img`elements,

2022-01-20 08:21 UTC, jdwilkin4 commented
Hi @Abdullah-Irfan-web ! 
Thank you for making these changes.
We recently just merged another PR that fixed this issue so we are going to go ahead and close this PR.
If you are interested in looking for more good first issues, then you can look into this freeCodeCamp repo to contribute to.
https://github.com/freeCodeCamp/Developer_Quiz_Site/issues

Happy coding!

2022-01-20 08:21 UTC, closed without merging

2022-01-20 08:22 UTC, Sembauke commented
Hey @Abdullah-Irfan-web,

Thank you for opening this pull-request. Unfortunately this issue has already been fixed by #44842.

This means we will not be accepting your pr.

Thank you for your understanding,
Have a great day and we hope to see more of you in the future, happy coding 😄