fix#44806: add test to exercise tracker
freeCodeCamp/freeCodeCamp pull request #44862
Opened 2022-01-21 09:30 UTC by c-ehrlich

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44806

* Add a test to prevent incorrectly functioning code from passing the Exercise Tracker project requirements - see Issue#44806 for more details.
* Date of addExerciseTwoRes was changed to allow a one day buffer on either side of the new request (the existing tests have this also)
* I tried to choose a descriptive name for the new res - let me know if something shorter is preferred.

2022-01-31 12:05 UTC, ShaunSHamilton requested changes
Thank you, for taking the time to contribute.

Just a small fix

2022-01-31 12:05 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +        url + `/api/users/${_id}/logs/from=1990-01-02&to=1990-01-04&limit=1`
```suggestion
        url + `/api/users/${_id}/logs?from=1990-01-02&to=1990-01-04&limit=1`
```

2022-01-31 12:35 UTC, ShaunSHamilton approved these changes
Thanks for this.

This LGTM 👍

2022-02-10 20:33 UTC, moT01 approved these changes
LGTM @c-ehrlich 🎉 Thanks for fixing this and congratulations on your first PR for the freeCodeCamp repo 🎉 We welcome future contributions 👍

2022-02-10 20:33 UTC, merged