fix: fix editor output for set and maps
freeCodeCamp/freeCodeCamp pull request #44966
Opened 2022-01-29 17:49 UTC by Ismailtlem

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #44306

2022-01-31 15:00 UTC, ShaunSHamilton requested changes
Small change. It is a bit of a hacky approach, but it is _kilometres_ better than `{}`

2022-01-31 15:00 UTC, ShaunSHamilton commented on client/src/utils/format.js
> +      ([k, v]) => `${k}=>${v}`
```suggestion
      ([k, v]) => `${k} => ${v}`
```

2022-01-31 17:51 UTC, ojeytonwilliams commented
Thanks @Ismailtlem.  I think we need to fix `format` too, because it's using node's `util` in the tests, but `util/` in production :(  Also we should explicitly install the 'util' lib in the client and fallback to it. i.e update the following:
https://github.com/freeCodeCamp/freeCodeCamp/blob/d58e5e5bddcd14be89ac2e2d240205edbd05e536/client/gatsby-node.js#L232

Let me know if you're interested in tackling that.  If not, no worries, I'll get to it one of these days!

2022-01-31 21:05 UTC, nhcarrigan commented
@ojeytonwilliams to clarify, is that a blocker on this PR?

2022-01-31 22:48 UTC, ojeytonwilliams commented
No, sorry for being vague. This PR shouldn't be blocked for that. Tests can come separately.

2022-02-01 22:28 UTC, nhcarrigan approved these changes
<img width="306" alt="image" src="https://user-images.githubusercontent.com/63889819/152062267-0cf73d7f-e89e-46e2-834f-2389fa1c1580.png">

Looks good to me!

2022-02-02 09:04 UTC, Sembauke approved these changes

2022-02-02 11:53 UTC, ShaunSHamilton approved these changes
Thank you for your contribution to the page! 👍
We are happy to accept these changes, and look forward to future contributions. 🎉

2022-02-02 11:53 UTC, merged