feat: split rdbms into individual blocks and two challengeTypes
freeCodeCamp/freeCodeCamp pull request #44978
Opened 2022-01-31 14:56 UTC by moT01

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-02-10 15:28 UTC, ojeytonwilliams requested changes
One minor style issue, the notes look a little different to the rest:

![image](https://user-images.githubusercontent.com/15801806/153439889-3077b585-136a-494c-afc9-2bd9ab09a778.png)

2022-02-10 15:28 UTC, ojeytonwilliams commented on client/src/templates/Challenges/codeally/show.tsx
> +    this.handleSubmit = this.handleSubmit.bind(this);
```suggestion
```
We can just use arrow functions below and not worry about binds.

2022-02-10 15:28 UTC, ojeytonwilliams commented on client/src/templates/Challenges/codeally/show.tsx
> +  }): void {
```suggestion
  handleSubmit = ({
    showCompletionModal
  }: {
    showCompletionModal: boolean;
  }) => {
```

2022-02-10 15:28 UTC, ojeytonwilliams commented on client/src/templates/Challenges/codeally/show.tsx
> +                    // eslint-disable-next-line @typescript-eslint/unbound-method
```suggestion
```

2022-02-10 15:28 UTC, ojeytonwilliams commented on client/src/templates/Challenges/codeally/show.tsx
> +                      // eslint-disable-next-line @typescript-eslint/unbound-method
```suggestion
```

2022-02-10 15:28 UTC, ojeytonwilliams commented on client/src/templates/Challenges/codeally/show.tsx
> +                {/*(!isSignedIn || challengeType === 12) && <Spacer size={2} />*/}
```suggestion
```
Can this go?

2022-02-10 16:44 UTC, moT01 commented on api-server/src/server/boot/challenge.js
> +  };
Going to mark this resolved, let me know if you think something should be changed here.

2022-02-10 16:54 UTC, moT01 commented on api-server/src/common/models/user.js
> +      ) {
Not sure - I suppose if it's not an array, the length check may fail, which might not cause any problems. I just copied what was in the completeChallenges function above this.

2022-02-10 16:57 UTC, moT01 commented on api-server/src/common/models/user.js
> +      ) {
Going to mark this resolved. Let me know if you think something needs to be changed here.

2022-02-10 17:01 UTC, moT01 commented on api-server/src/common/models/user.js
> +        this.partiallyCompletedChallenges = user.partiallyCompletedChallenges;
not sure - again, just copied the completedChallenges function above. It does seem odd though, doesn't it. Maybe something to do with those observables that I never quite figured out how they work.

Going to mark this resolved. Let me know if you think something should be done here.

2022-02-10 18:13 UTC, moT01 commented
I squashed the commits, rebased, and fixed a few things. This should be good to go again 🤞

2022-02-11 09:33 UTC, ojeytonwilliams requested changes

2022-02-11 09:33 UTC, ojeytonwilliams commented on client/src/templates/Challenges/codeally/show.tsx
> +                    {challengeType === 13
```suggestion
                    {challengeType === challengeTypes.codeAllyCert
```

2022-02-11 14:44 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

Thanks for bearing with me, @moT01!

2022-02-11 15:23 UTC, ShaunSHamilton approved these changes
LTMG 👍 

I fought everything I had to not suggest changes like `[2, 4, 5, 13].include(challenge.challengeType)`, because that is not Tom's fault... _it is Oliver's_ 😁

2022-02-11 15:23 UTC, ShaunSHamilton commented on client/utils/challenge-types.js
> +const codeAllyCert = 13;
It seems like we have both `codeAlly` challenge types, as well as `codeRoad` challenge types.

Edit: Never mind, it is just the comments that mention CodeRoad.

2022-02-11 15:39 UTC, merged