fix: strip js comments
freeCodeCamp/freeCodeCamp pull request #45133
Opened 2022-02-15 18:42 UTC by nhcarrigan

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #45127

I'm not sure why the `removeJSComments` helper was not being made available, but this PR enables it + fixes the tests in the linked issue.

2022-02-15 18:59 UTC, ShaunSHamilton requested changes
Something like this should work more better.

2022-02-15 18:59 UTC, ShaunSHamilton commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword.md
> +(getUserInput) => assert(!__helpers.removeJSComments(getUserInput('index')).match(/var/g));
```suggestion
assert.notMatch(__file('script.js'), /var/);
```

2022-02-15 18:59 UTC, ShaunSHamilton commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/declare-a-read-only-variable-with-the-const-keyword.md
> +  assert(!__helpers.removeJSComments(getUserInput('index')).match(/fCC/));
```suggestion
  assert.notMatch(__file('script.js'), /fCC/);
```

2022-02-15 19:35 UTC, ShaunSHamilton approved these changes
LGTM 👍 

---

Just so we are on the same page:
1) The global flag is redundant, and actually just a performance hit
2) There is not specific need here for the named assertions - I just happen to be in the habit of trying to use them.

2022-02-15 19:46 UTC, nhcarrigan commented
Do we want to close the other issue? This only fixes these challenges, not the underlying cause.

2022-02-24 10:59 UTC, raisedadead approved these changes

2022-02-24 10:59 UTC, merged