fix(i18n) : added ctrl + enter to run the tests buttun
freeCodeCamp/freeCodeCamp pull request #45278
Opened 2022-02-27 16:10 UTC by HenMoshe

fix(i18n) : added ctrl + enter to run the tests buttun as asked in #45175

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45175

2022-02-27 17:26 UTC, ShaunSHamilton requested changes, later dismissed
Thank you, for taking the time to contribute.

Just a small edit:

2022-02-27 17:26 UTC, ShaunSHamilton commented on client/i18n/locales/english/translations.json
> +    "run-test": "Run the Tests(Ctrl + Enter)",
```suggestion
    "run-test": "Run the Tests (Ctrl + Enter)",
```

2022-02-27 17:37 UTC, HenMoshe commented on client/i18n/locales/english/translations.json
> +    "run-test": "Run the Tests(Ctrl + Enter)",
Commited! Thanks! :)

2022-02-28 04:35 UTC, raisedadead approved these changes

2022-02-28 05:24 UTC, nhcarrigan approved these changes

2022-02-28 05:25 UTC, merged

2022-02-28 05:25 UTC, nhcarrigan commented
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉