chore(i18n,learn): processed translations
freeCodeCamp/freeCodeCamp pull request #45333
Opened 2022-03-03 12:59 UTC by camperbot

This PR was opened auto-magically by Crowdin.

2022-03-03 14:36 UTC, Sembauke submitted a review, later dismissed

2022-03-03 18:49 UTC, nhcarrigan requested changes
Blocked pending fix of a misconfugration in the download settings

2022-03-04 09:58 UTC, ieahleen commented
if the fix was #45336 then this can go in

2022-03-04 13:53 UTC, nhcarrigan commented
Yep, this is unblocked now.

2022-03-04 14:01 UTC, nhcarrigan approved these changes

2022-03-04 14:16 UTC, raisedadead approved these changes

2022-03-04 14:16 UTC, merged