feat: add database cert alert
freeCodeCamp/freeCodeCamp pull request #45346
Opened 2022-03-04 13:53 UTC by ahmadabdolsaheb

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-03-04 14:06 UTC, raisedadead commented
This PR is valuable. 

I have temporarily targeted it to a temporary `next` branch with Tom's work that this depends on. We can finalize the details later, but I wanted to closely look at the differences. 

For now, #45347 will revert #45169

2022-03-07 10:32 UTC, ojeytonwilliams requested changes

2022-03-07 10:32 UTC, ojeytonwilliams commented on client/src/utils/is-a-cert.ts
> +export function IsNewRespCert(superBlock: string): boolean {
```suggestion
export function isNewRespCert(superBlock: string): boolean {
```
Nitpick

2022-03-07 10:32 UTC, ojeytonwilliams commented on client/src/utils/is-a-cert.ts
> +export function IsRelationalDbCert(superBlock: string): boolean {
```suggestion
export function isRelationalDbCert(superBlock: string): boolean {
```

2022-03-08 08:29 UTC, ojeytonwilliams approved these changes, later dismissed
LGTM.

It doesn't seem worth it to split these tiny functions off into their own file, but the functionality is good.

~Is the plan to merge this after publishing the news article?~ Nevermind, I see that it's going into the next branch!

2022-03-08 15:19 UTC, moT01 commented
I think we want to go with a forum post here. I can create it and share a link.

2022-03-08 15:22 UTC, raisedadead commented
Thanks @moT01 

Once you have done that, we can get this in once we have your PR recreated to `main` followed by re-targeting this PR to `main` as well.

2022-03-10 04:12 UTC, moT01 commented
I made the forum post and pushed the link to this PR

> Once you have done that, we can get this in once we have your PR recreated to main followed by re-targeting this PR to main as well.

Can you explain the process a little more to me @raisedadead? I'm not sure I understand. I assumed we would merge this to next, merge my security issue fix/webhook PR to next, then merge a PR of next into main or something. Those are the only two PR's that should be needed.

Do we just want to re-target both of them to main? I think that's what you meant - looks like maybe just a typo there that confused me. I'm fine with it either way.

2022-03-10 04:44 UTC, raisedadead commented
> Do we just want to re-target both of them to main? I think that's what you meant

Yes - that's exactly the plan. We can start by landing the security fix PR first on `main`

2022-03-14 16:21 UTC, nhcarrigan approved these changes, later dismissed
This looks good to me, aside from one nitpick question.

2022-03-14 16:21 UTC, nhcarrigan commented on client/i18n/locales/english/intro.json
> +    "read-database-cert-article": "Please read this article before proceeding."
Nitpick, but do we want to call it "article" or "forum post"?

2022-03-14 17:11 UTC, naomi-lgbt approved these changes
Nitpick resolved, now this looks gooder.

2022-03-15 09:30 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-03-15 09:31 UTC, merged