fix: webhook process
freeCodeCamp/freeCodeCamp pull request #45385
Opened 2022-03-08 14:06 UTC by moT01

Does:
-this moves the showIframe state that was in the component to redux
-tokens now get created when clicking the start project button
-tokens get deleted when signing out, resetting account, deleting account
-can delete token from settings page
-renames webhookToken to userToken

Doesn't do:
~~-There's no longer a way for users to manually delete or renew their tokens. Do we want to have that ability?~~ added^^
-Possibly want to add a loader after users click 'start' so they don't click around while their token is being created.
~~-If we want to rename 'webhook token' to something else, now would be the time - before we create the collection on production. I wouldn't mind doing that. I was thinking 'user token'. 'auth token' could be confused with the other auth token? Pretty minor.~~ added^^

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45345

2022-03-08 15:08 UTC, raisedadead commented
> There's no longer a way for users to manually delete or renew their tokens. Do we want to have that ability?


That's a good question. I think we give them the ability in the settings page, just as a troubleshooting measure?

2022-03-09 10:02 UTC, ojeytonwilliams requested changes
> -If we want to rename 'webhook token' to something else, now would be the time - before we create the collection on production. I wouldn't mind doing that. I was thinking 'user token'. 'auth token' could be confused with the other auth token? Pretty minor.

Yep, I think we should.

2022-03-09 10:02 UTC, ojeytonwilliams commented on client/src/utils/tone/index.ts
> -  [FlashMessages.DeleteTokenErr]: TRY_AGAIN,
I think we can use this, since we're allowing users to manually delete tokens.

2022-03-09 16:33 UTC, ojeytonwilliams submitted a review, later dismissed

2022-03-11 17:29 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-03-11 18:51 UTC, nhcarrigan commented
Everything on our end is looking good - just one thing @moT01:

- I might be missing something, but I can't seem to get a CodeRoad container to pick up a new token. When I `printenv` it shows the old one still.

2022-03-11 19:45 UTC, moT01 commented
You have to wait five minutes for your container to shut down. Then when it starts back up, it should have the new one. Perhaps you tried that, and there is an issue. Since you posted that an hour ago, it should work now. Care to give it another try and check again @nhcarrigan?

How to tell the difference between running/not running VM's when they load:
-A container that is shut down will go through all the loading steps [in this picture](https://forum.freecodecamp.org/t/how-to-troubleshoot-the-web-version-of-the-relational-database-curriculum/500231#you-are-stuck-on-the-last-step-of-loading-remote-environment-3)
-A running container will only go through the steps after that screen. It's just a couple steps - maybe something like 'finalizing load' or 'loading virtual machine'

2022-03-11 21:39 UTC, nhcarrigan commented
I'll give it another shot - I did wait a while before trying, and saw the loading screen. But my container opened with the same terminal open I had before.

2022-03-11 21:58 UTC, nhcarrigan approved these changes
Triaged the token regen issue with Tom, it's not an issue on our side it's related to CodeRoad. Shouldn't block this PR so I think we're good to go here.

2022-03-11 21:58 UTC, merged