chore: fixed mistakes in the source string
freeCodeCamp/freeCodeCamp pull request #45448
Opened 2022-03-17 06:48 UTC by fhsinchy

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

I've removed the extra quotation mark from the __You have either deleted the `main` element or it is missing an opening tag or closing tag."__ and the extra __it__ from the __You have it put it somewhere else.__  line.

2022-03-17 10:57 UTC, Sembauke approved these changes, later dismissed

2022-03-17 12:13 UTC, gikf requested changes

2022-03-17 12:13 UTC, gikf commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804e7.md
> +Your `footer` element should the below the closing `main` element tag. You have put it somewhere else.
```suggestion
Your `footer` element should be below the closing `main` element tag. You have put it somewhere else.
```
In first sentence, the first _the_, seems to be slightly off as well.

2022-03-18 15:19 UTC, Sembauke approved these changes

2022-03-18 15:32 UTC, gikf approved these changes

2022-03-18 15:42 UTC, merged

2022-03-18 15:44 UTC, gikf commented
Hi @fhsinchy. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

2022-03-18 15:50 UTC, fhsinchy commented
Thank you @gikf. I'll keep fixing the issues I encounter during translation.