docs: add development guide for ui-components
freeCodeCamp/freeCodeCamp pull request #45488
Opened 2022-03-21 11:07 UTC by huyenltnguyen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #44668

This PR adds a development guide for `ui-components`. 

I think I will revisit the doc and make it more comprehensive as we go. We have been gradually standardizing the development process, but we are in an early phase still, so I'm keeping the doc high-level for now to avoid overwhelming new contributors.

I'm not a native-English speaker, so please help check for grammar errors or what could be improved 🙂.

2022-03-21 13:13 UTC, raisedadead requested changes
Quick nit-picks.

2022-03-21 13:13 UTC, raisedadead commented on docs/how-to-work-on-the-component-library.md
> +freeCodeCamp has been using Bootstrap components in the UI. However, we are moving away from it and building our own component library, which helps standardize our UX/UI patterns and improve the acce
```suggestion
> [!NOTE]
>
> freeCodeCamp has been using Bootstrap components in the UI. However, we are moving away from it and building our own component library, which helps standardize our UX/UI patterns and improve accessibility. The project is tracked in [this GitHub issue](https://github.com/freeCodeCamp/freeCodeCamp/issues/44668).
```

2022-03-21 13:13 UTC, raisedadead commented on docs/how-to-work-on-the-component-library.md
> +The new library is called `ui-components`. The components are built mostly from scratch with basic HTML elements and [Tailwind CSS](https://tailwindcss.com/). The following steps are recommended when
```suggestion
The following steps are recommended when working on a new component:
```

2022-03-21 13:13 UTC, raisedadead commented on docs/how-to-work-on-the-component-library.md
> +# How to Work on the Component Library
```suggestion
Welcome to freeCodeCamp's `ui-components` library. The components are built mostly from scratch with basic HTML elements and [Tailwind CSS](https://tailwindcss.com/). 

# How to Work on the Component Library
```

2022-03-21 14:39 UTC, raisedadead approved these changes, later dismissed

2022-03-21 16:40 UTC, Ismailtlem reviewed
One small thing

2022-03-21 16:53 UTC, Ismailtlem commented on docs/how-to-work-on-the-component-library.md
> +- [React Bootstrap v0.33 Docs](https://react-bootstrap-v3.netlify.app/components/)
this url : https://react-bootstrap-v3.netlify.app/components/ doesn't exist, maybe just https://react-bootstrap-v3.netlify.app/ is enough

2022-03-22 01:56 UTC, huyenltnguyen commented on docs/how-to-work-on-the-component-library.md
> +- [React Bootstrap v0.33 Docs](https://react-bootstrap-v3.netlify.app/)
```suggestion
- [React Bootstrap v0.33 Docs](https://react-bootstrap-v3.netlify.app)
```

2022-03-22 06:08 UTC, raisedadead approved these changes

2022-03-22 07:20 UTC, Ismailtlem approved these changes
LGTM

2022-03-22 07:53 UTC, merged