fix(curriculum): `PUT /api/threads/:board` test
freeCodeCamp/freeCodeCamp pull request #45540
Opened 2022-03-26 12:55 UTC by harmonify

As far as I understand, this test case is supposed to assert a PUT request to `/api/threads/:board` route but instead of sending `thread_id` field like the boilerplate's client form, it sent a `report_id` field instead.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2022-03-29 17:43 UTC, nhcarrigan requested changes
Looking at the demo project, the route expects `report_id` - rather than changing the test, the user story text above should be changed to require passing a `report_id`.

2022-03-30 18:13 UTC, harmonify commented
Now that I take a look again in the client side of the project, it seems the issue is the inconsistency between the views when calling the API.
`index.html` send a `thread_id` to report a thread, meanwhile `board.html` and `thread.html` send a `report_id` to report a thread.
What do you think about it?

2022-04-13 18:30 UTC, nhcarrigan commented
We should definitely standardise those. Personally, I'd be in favour of making them all `thread_id`.

2022-05-17 07:05 UTC, raisedadead commented
Can we keep moving forward or close as stale for now (owing to other competing priorities that you may have)?

2022-05-26 07:23 UTC, closed without merging