chore: migrate instructions to learn
freeCodeCamp/freeCodeCamp pull request #45568
Opened 2022-03-29 19:07 UTC by nhcarrigan

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #43836 

This PR migrates the last of the python project instructions to `/learn`.

2022-03-30 18:55 UTC, Sembauke requested changes

2022-03-30 18:55 UTC, Sembauke commented on curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/book-recommendation-engine-using-knn.md
> +After importing and cleaning the data, use `NearestNeighbors` from `sklearn.neighbors` to develop a model that shows books that are similar to a given book. The Nearest Neighbors algorithm measures d
```suggestion
After importing and cleaning the data, use `NearestNeighbors` from `sklearn.neighbors` to develop a model that shows books that are similar to a given book. The Nearest Neighbors algorithm measures the distance to determine the “closeness” of instances.
```

2022-03-30 18:55 UTC, Sembauke commented on curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/book-recommendation-engine-using-knn.md
> +Notice that the data returned from `get_recommends()` is a list. The first element in the list is the book title passed in to the function. The second element in the list is a list of five more lists
```suggestion
Notice that the data returned from `get_recommends()` is a list. The first element in the list is the book title passed into the function. The second element in the list is a list of five more lists. Each of the five lists contains a recommended book and the distance from the recommended book to the book passed into the function.
```

2022-03-30 18:55 UTC, Sembauke commented on curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/cat-and-dog-image-classifier.md
> +Found 50 images belonging to 1 classes.
```suggestion
Found 50 images belonging to 1 class.
```

2022-03-30 18:55 UTC, Sembauke commented on curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/cat-and-dog-image-classifier.md
> +After your run the cell, you should see all 50 test images with a label showing the percentage sure that the image is a cat or a dog. The accuracy will correspond to the accuracy shown in the graph a
```suggestion
After your run the cell, you should see all 50 test images with a label showing the percentage of "sure" that the image is a cat or a dog. The accuracy will correspond to the accuracy shown in the graph above (after running the previous cell). More training images could lead to a higher accuracy.
```

2022-04-06 15:56 UTC, moT01 reviewed
This is looking good @nhcarrigan 👍 Here's a few things I noticed:

A few of the projects have comments in the cells or files that we won't be able to translate. I don't think this is a problem - they aren't all that important, but we could move them here if we want them translated. I would be fine leaving them how they are.

I noticed [a PR to remove the instructions from the cat and dog boilerplate.](https://github.com/freeCodeCamp/boilerplate-cat-and-dog-image-classifier/pull/4) Do we want to remove the instructions from all the boilerplates?

At the top of each notebook there's a short paragraph: `Note: You are currently reading this using Google Colaboratory...` Do we want to move that paragraph to these markdown files? Side note: that PR I linked removes that paragraph from the notebook.

^ This is the only one we may want to address on this PR. If we decide to leave that paragraph in the notebooks, I would be fine merging this. I left one suggestion in the code that's pretty minor.

2022-04-06 15:56 UTC, moT01 commented on curriculum/challenges/english/11-machine-learning-with-python/machine-learning-with-python-projects/rock-paper-scissors.md
> +Copy your project's URL and submit it to freeCodeCamp.
```suggestion
Copy your project's URL and submit it below.
```

2022-04-06 16:06 UTC, nhcarrigan commented
> I noticed https://github.com/freeCodeCamp/boilerplate-cat-and-dog-image-classifier/pull/4 Do we want to remove the instructions from all the boilerplates?

The cat and dog one was the only notebook that had a bunch of instructions throughout the entire thing - the rest just have the initial paragraph.

2022-04-06 16:15 UTC, moT01 commented
Well, they mostly all have the instructions you moved here. The [book recommendation project](https://github.com/freeCodeCamp/boilerplate-book-recommendation-engine/blob/master/fcc_book_recommendation_knn.ipynb) for example, has all the same instructions that will be added here. You're saying we don't want to remove those?

2022-04-07 09:33 UTC, Sembauke approved these changes

2022-04-07 16:54 UTC, nhcarrigan commented
> It's fine to leave them for now, just wondering if we want to or not.

I could remove the instructions, but we should probably leave the "watch this video about collab" link because it's a helpful resource and would make less sense on `/learn` IMHO.

2022-04-12 14:20 UTC, moT01 approved these changes
Alright, lets go with this then 🚀 I'll make an issue about removing instructions from the notebooks.

2022-04-12 14:20 UTC, merged