Chore: Added article links in italian footer
freeCodeCamp/freeCodeCamp pull request #45586
Opened 2022-03-31 16:34 UTC by alevanni

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-04-01 19:25 UTC, ieahleen commented on client/i18n/locales/italian/trending.json
> +"article7title":"Donare un milione di dollari a freeCodeCamp",
questo forse è troppo lungo, il massimo sono 28 caratteri

2022-04-01 19:26 UTC, ieahleen commented on client/i18n/locales/italian/trending.json
> +"article29link":"https://www.freecodecamp.org/italian/news/funzioni-di-callback-javascript-cosa-sono-le-callback-in-js-e-come-usarle/"}
```suggestion
"article29link":"https://www.freecodecamp.org/italian/news/funzioni-di-callback-javascript-cosa-sono-le-callback-in-js-e-come-usarle/"
}

```

2022-04-05 10:37 UTC, ieahleen commented on client/i18n/locales/italian/trending.json
> +"article4link":"https://www.freecodecamp.org/italian/news/figure-in-css-spiegate/"
```suggestion
"article4link":"https://www.freecodecamp.org/italian/news/figure-in-css-spiegate/",
```

2022-04-05 10:37 UTC, ieahleen commented on client/i18n/locales/italian/trending.json
> +"article4link":"https://www.freecodecamp.org/italian/news/figure-in-css-spiegate/"
```suggestion
"article4link":"https://www.freecodecamp.org/italian/news/figure-in-css-spiegate/",
```

2022-04-05 13:44 UTC, raisedadead approved these changes, later dismissed

2022-04-05 18:07 UTC, nhcarrigan requested changes

2022-04-05 18:07 UTC, nhcarrigan commented on client/i18n/locales/italian/trending.json
> +  "article27link": "freecodecamp.org/italian/news/javascript-date-now-come-ottenere-la-data-corrente-in-javascript/",
```suggestion
  "article27link": "https://www.freecodecamp.org/italian/news/javascript-date-now-come-ottenere-la-data-corrente-in-javascript/",
```

2022-04-06 14:37 UTC, nhcarrigan approved these changes

2022-04-08 10:47 UTC, ieahleen approved these changes

2022-04-08 10:55 UTC, merged