chore: migrate locale test to TypeScript
freeCodeCamp/freeCodeCamp pull request #45608
Opened 2022-04-02 10:18 UTC by Sembauke

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-04-05 19:51 UTC, nhcarrigan approved these changes
Not sure what's up with the CodeSee map, but this seems fine.

2022-04-11 15:51 UTC, ojeytonwilliams requested changes
Thanks for taking this on, @Sembauke, it's great that we're taking one more step on the road to 100% TypeScript.

I think we can improve type safety and make @ShaunSHamilton happy (it involves an enum):

2022-04-11 15:51 UTC, ojeytonwilliams commented on config/i18n/all-langs.ts
> +export const langDisplayNames: Record<string, string> = {
```suggestion
export const langDisplayNames = {
```
This change would reduce type safety.  There's a few ways to go here, but the DRYest approach I can think of is to use an enum like this

```ts
export enum LangNames {
  English = 'english',
  Espanol = 'espanol',
  ...
}
```
And then wherever we have the string `'english'` we'd have `LangNames.English`.  This should cut down on the number of hoops we need to jump through to convince TS we know what we're doing.

2022-04-27 15:29 UTC, Sembauke commented
Will open a new pr soon for this

2022-04-27 15:29 UTC, closed without merging