Update 614206033d366c090ca7dd42.md
freeCodeCamp/freeCodeCamp pull request #45668
Opened 2022-04-11 02:00 UTC by yuanhepeng

make the wording clearer

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes#45629

2022-04-11 03:16 UTC, yuanhepeng commented
em...I want to change to "Request changes"...
![image](https://user-images.githubusercontent.com/39111057/162659328-724b27d0-fd2b-4111-a240-289716bdc022.png)

2022-04-11 08:05 UTC, huyenltnguyen submitted a review, later dismissed
LGTM

2022-04-11 08:10 UTC, raisedadead commented
You are unable to request changes as the author. The idea way is you should work on your local copy (your machine, GitPod) and push them up before creating a PR. If you want to add more changes to a give PR, you can add more changes, create more commits and push them to the same branch.

Please check out our [contributing guidelines](https://contribute.freecodecamp.org) and GitHub's docs if you need more help or reach out to the [contributors chat room](https://chat.freecodecamp.org/channel/contributors).

2022-04-11 08:12 UTC, raisedadead approved these changes, later dismissed

2022-04-11 08:52 UTC, yuanhepeng commented
I just added a link, points to an article，I want to explain the concept more clearly

2022-04-11 08:54 UTC, yuanhepeng commented
I want to open this article in a new tab, I tried target="_blank" and rel="external", but it doesn't seem to have achieved the effect.

2022-04-12 12:57 UTC, moT01 commented
I kind of lean towards just improving the wording like was discussed in the issue. I'm not completely against the link if others are in favor of it, but we usually try to avoid links in the descriptions/instructions. On rare occasions, we do use them - I don't think it's needed here, though.

2022-04-12 13:40 UTC, huyenltnguyen commented
@moT01 Agreed. We are sending the user to an article in this case, and the user would need to consume the content and scroll a bit further down to find the font list, which might distract them from the challenge. We could add a small section to the challenge description for a list of fonts the user could from, but I'm not really sure if that is really needed.

2022-04-12 14:34 UTC, nhcarrigan requested changes

2022-04-12 14:34 UTC, nhcarrigan commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/614206033d366c090ca7dd42.md
> +Change the font for both the `h1` and `h2` elements to `Verdana`, and use another web-safe font in the <a href="https://www.freecodecamp.org/news/html-font-css-font-family-example-serif-and-sans-seri
```suggestion
Change the font for both the `h1` and `h2` elements to `Verdana`, and use another web-safe font in the sans-serif family as a fallback.
```
Per above 🙂

2022-04-13 02:10 UTC, closed without merging

2022-04-13 04:09 UTC, huyenltnguyen commented
@yuanhepeng Thanks for addressing our feedback! 

I approved the other PR, but just wanted to put a note here 🙂 You shouldn't need to create a new PR to update the change. If you clicked the "Commit suggestion" button in @nhcarrigan's https://github.com/freeCodeCamp/freeCodeCamp/pull/45668#discussion_r848512888, a new commit would be added to the branch with the suggested change. 

Anyway, thank you for your patience and your contribution to freeCodeCamp!