chore(i18n,docs): processed translations
freeCodeCamp/freeCodeCamp pull request #45708
Opened 2022-04-18 12:09 UTC by camperbot

This PR was opened auto-magically by Crowdin.

2022-04-18 13:33 UTC, raisedadead submitted a review, later dismissed

2022-04-18 14:19 UTC, naomi-lgbt requested changes

2022-04-18 14:19 UTC, nhcarrigan commented on docs/i18n/espanol/how-to-work-on-coding-challenges.md
> +   cd currículum
blocking while I fix this one in Crowdin

2022-04-18 14:26 UTC, nhcarrigan approved these changes, later dismissed

2022-04-18 14:30 UTC, raisedadead submitted a review, later dismissed

2022-04-19 15:43 UTC, nhcarrigan approved these changes

2022-04-20 07:27 UTC, raisedadead approved these changes

2022-04-20 07:27 UTC, merged