chore: typescript migration of client/components/formHelpers/Form.test.js to ts
freeCodeCamp/freeCodeCamp pull request #45726
Opened 2022-04-19 13:45 UTC by matheuspor

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Is part of #43778

2022-04-19 17:47 UTC, nhcarrigan approved these changes, later dismissed
Think this is good to go.

2022-04-19 18:02 UTC, raisedadead requested changes
A quick nitpick about the file name casing, we would want to use kebab-case or at least lowercase in this PRs case.

2022-04-19 18:12 UTC, matheuspor commented
Oh, my bad @raisedadead. It's fixed now :+1:

2022-04-20 04:49 UTC, raisedadead approved these changes

2022-04-20 12:37 UTC, Sembauke approved these changes

2022-04-20 12:37 UTC, merged