Updated HTML tag for English version issue #45765
freeCodeCamp/freeCodeCamp pull request #45783
Opened 2022-04-25 23:47 UTC by Kas1680

Checklist:

- [x ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #45765 

I apologize for making multiple PRs for this issue as I am still trying to figure out how to work with GitHub. It should work this time.

2022-04-26 11:21 UTC, gikf requested changes
One more suggestion below.

Please use the _Commit suggestion_ button under the change suggestion, or commit change locally and push it to the same branch. Committing to the same branch will add commit to the PR. Please don't create another, new PR.

If you need help, join us in [our chat room](https://chat.freecodecamp.org/channel/contributors) or [the forum](https://forum.freecodecamp.org/c/contributors/3), our moderators will guide you through this.

2022-04-26 11:21 UTC, gikf commented on curriculum/challenges/english/01-responsive-web-design/basic-html-and-html5/define-the-head-and-body-of-an-html-document.md
> +   <div>
```suggestion
    <div>
```

2022-04-30 19:31 UTC, gikf approved these changes

2022-05-02 12:51 UTC, Sembauke approved these changes

2022-05-02 12:51 UTC, merged