fix(curriculum): extra word in step 47 cafe menu project
freeCodeCamp/freeCodeCamp pull request #45941
Opened 2022-05-13 09:39 UTC by Dario-DC

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-05-13 15:37 UTC, nhcarrigan requested changes
One more grammar fix while we're here 😁

2022-05-13 15:37 UTC, nhcarrigan commented on curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3cade99dda4e6071a85dfd.md
> +You will come back to styling the menu in a few steps, but for now, go ahead add a second `section` element below the first for displaying the desserts offered by the cafe.
```suggestion
You will come back to styling the menu in a few steps, but for now, go ahead and add a second `section` element below the first for displaying the desserts offered by the cafe.
```

2022-05-15 14:46 UTC, nhcarrigan approved these changes
Looks good to me!

2022-05-15 20:02 UTC, lynxlynxlynx approved these changes

2022-05-15 20:03 UTC, merged

2022-05-15 20:03 UTC, lynxlynxlynx commented
Thanks and congratulations on your first accepted submission!