Adding Portuguese top30 links to footer
freeCodeCamp/freeCodeCamp pull request #46008
Opened 2022-05-17 11:49 UTC by DanielRosa74

Changing the links on the Trending List of the footer on the Portuguese editorial to the top 30 Portuguese articles

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2022-05-17 12:13 UTC, ieahleen requested changes
A lot of the titles are too long, try to put the longest in the last column (20-29) but even there there are some that are too long

![image](https://user-images.githubusercontent.com/26656284/168808161-f381eb2d-5f00-444f-8755-b1b44fa7dd1a.png)

2022-05-17 18:01 UTC, ieahleen commented on client/i18n/locales/portuguese/trending.json
> +  "article6title":"Remover arquivos no Windows",
This one is still too long - maybe exchanging it with SQL em Python would work?

2022-05-17 21:10 UTC, ieahleen approved these changes
Perfect!

![image](https://user-images.githubusercontent.com/26656284/168910737-7eb4cebf-1665-4247-8ec3-625767fd7542.png)

2022-05-18 07:49 UTC, Sembauke approved these changes

2022-05-18 07:49 UTC, merged