added hint about using media types
freeCodeCamp/freeCodeCamp pull request #46055
Opened 2022-05-18 18:28 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #45515

although docs have screen with (max-width) on `media` queries, the curriculum doesn't teach media type,.

but giving the answer outright is weird with *ask for help* button added.

so I added a link about media type, and example if needed.

2022-05-19 16:50 UTC, moT01 requested changes
We want to avoid using external links in our challenges if we can @Sboonny. I would change these to something closer to the suggestion. Maybe:
```
You should have a `@media (max-width: 800px)` rule
```
This rules out any possible types that might not pass the tests - `screen` or whatever else

2022-05-19 17:07 UTC, Sboonny commented
I wonder if this too lenient, because the less code policy. I do like it though, what do you think about 

 ```
Your `media` should use `(max-width: 800px)` rule only
```

2022-05-19 17:13 UTC, Sboonny commented
@moT01 I did lose my gitpod workplace, because I made a lot of PRs.

 I am closing this and implementing new one with your suggestion in it

2022-05-23 11:03 UTC, Sboonny commented
Don't approve yet
There Is a bug

2022-05-25 16:06 UTC, huyenltnguyen approved these changes
LGTM

2022-05-26 07:28 UTC, raisedadead approved these changes

2022-05-26 14:05 UTC, moT01 approved these changes
LGTM @Sboonny 🎉 Thanks for contributing to freeCodeCamp 🎉

2022-05-26 14:05 UTC, merged