feat: add a leading submitChallenge debounce
freeCodeCamp/freeCodeCamp pull request #46085
Opened 2022-05-20 13:02 UTC by ahmadabdolsaheb

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The submission is a bit laggy.

As opposed to username verification where we need to wait a certain time to verify then user's intention, we could take the leading function call and debounce the rest.

2022-05-20 13:06 UTC, ahmadabdolsaheb commented
Converted to draft after submission. sorry for the noise. 
I am looking into registering the first submitChallenge request in a period of time instead.

2022-05-20 13:23 UTC, raisedadead reviewed
Can we add a tiny progress animation inside the button while the request completes, or that's not possible because the page navigates away?

2022-05-20 13:30 UTC, ahmadabdolsaheb commented
That is a great idea. We could disable the button and show a loader next to the button text while waiting to hear back from the server.

2022-05-20 13:52 UTC, ojeytonwilliams reviewed
Just to confirm I understand: this immediately sends the first submit request, but if the servers are slow then a user clicking over and over will not send another request until they stop clicking for 2 seconds, then click again?

2022-05-20 15:47 UTC, ahmadabdolsaheb commented
Yes that is the expected result. Upon further testing it seems to be executing more than expected. I am looking into it.

2022-05-20 16:29 UTC, ojeytonwilliams commented
@ahmadabdolsaheb oh, it seemed fine to me.  I replaced the submit call with a console log and it worked as I described.

Also, do we want both leading and trailing to be true?  It felt a bit odd to click multiple time and for nothing to happen.

2022-05-20 19:48 UTC, ahmadabdolsaheb commented
Yes it debounces the logs, but not the action. :) 

You can test it on the other tryTo function. 

To illustrate it better, debounce a function with the leading option and put the log in it. It should work as expected. 

But when you add the action, it will execute the action and the log on each click.

2022-05-20 21:39 UTC, ojeytonwilliams commented
> But when you add the action, it will execute the action and the log on each click.

Well, that's a bit odd! We can dig into it on Monday, if you like.

2022-05-23 13:15 UTC, ahmadabdolsaheb commented
It turns out the component was re-rendering and creating a new debounce each time, so we presisted it with a ref.

2022-05-26 07:21 UTC, raisedadead approved these changes, later dismissed

2022-05-26 12:59 UTC, ojeytonwilliams requested changes

2022-05-26 12:59 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/editor.tsx
> +    debounce(props.submitChallenge, 1000, { leading: true, trailing: true })
```suggestion
    debounce(props.submitChallenge, 1000, { leading: true, trailing: false })
```
Sorry Ahmad, I know I suggested this, but it doesn't work as I hoped.  If you click rapidly, you'll get both the leading and the trailing calls, so you'll submitChallenge twice and end up skipping a step.

2022-05-26 14:24 UTC, ojeytonwilliams approved these changes

2022-05-26 16:13 UTC, raisedadead approved these changes

2022-05-26 16:13 UTC, merged

2022-05-26 16:14 UTC, moT01 commented
LGTM 🎉