fix(curriculum): external roman numeral links in JS projects
freeCodeCamp/freeCodeCamp pull request #46171
Opened 2022-05-27 07:46 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

clear the 50th task in #40749

2022-05-27 08:41 UTC, raisedadead requested changes
Nitpicking on formating.

2022-05-27 08:41 UTC, raisedadead commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/roman-numeral-converter.md
> +All roman numerals answers should be provided in upper-case.
```suggestion
| Roman numerals | Arabic numerals |
|----------------|-----------------|
| M              | 1000            |
| CM             | 900             |
| D              | 500             |
| CD             | 400             |
| C              | 100             |
| XC             | 90              |
| L              | 50              |
| XL             | 40              |
| X              | 10              |
| IX             | 0               |
| V              | 5               |
| IV             | 4               |
| I              | 1               |

All roman numerals answers should be provided in upper-case.
```

2022-05-27 08:41 UTC, raisedadead commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-roman-numeral-converter-project/roman-numeral-converter.md
> +All roman numerals answers should be provided in upper-case.
```suggestion
| Roman numerals | Arabic numerals |
|----------------|-----------------|
| M              | 1000            |
| CM             | 900             |
| D              | 500             |
| CD             | 400             |
| C              | 100             |
| XC             | 90              |
| L              | 50              |
| XL             | 40              |
| X              | 10              |
| IX             | 0               |
| V              | 5               |
| IV             | 4               |
| I              | 1               |

All roman numerals answers should be provided in upper-case.
```

2022-05-27 09:25 UTC, Sembauke approved these changes

2022-05-27 11:01 UTC, raisedadead approved these changes

2022-05-27 11:01 UTC, merged

2026-03-28 20:28 UTC, WestonG40 commented
Co-authored-by: @NicholausJ  <email@example.com>

2026-03-28 20:29 UTC, WestonG40 commented
Co-authored-by: @WestonG40 <email@example.com>