fix(curriculum): external symmetric difference link in CIP
freeCodeCamp/freeCodeCamp pull request #46288
Opened 2022-06-02 07:15 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

clear task 89 #40749

2022-06-02 13:22 UTC, Sembauke approved these changes

2022-06-02 13:24 UTC, Sembauke requested changes, later dismissed

2022-06-02 17:56 UTC, jeremylt commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/symmetric-difference.md
> +Assuming *A* and *B* are an array with their value set to `[variable1, variable2, variable3]`, and `[variable1, variable3, variable4]` respectively. If we try to compute *A* and *B*, it will result i
I think numbers would be clearer here

```suggestion
For sets `A = [1, 2, 3]`, and `B = [1, 3, 4]`, the symmetric difference of *A* and *B* is `[2, 4]`.
```

2022-06-02 18:29 UTC, jeremylt approved these changes
LGTM

2022-06-03 06:31 UTC, raisedadead approved these changes

2022-06-03 07:52 UTC, merged