feat(api): discourse integration
freeCodeCamp/freeCodeCamp pull request #46292
Opened 2022-06-02 12:23 UTC by ShaunSHamilton

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #42837

Testing is difficult, because some people do not want me to include the client changes in the same PR....

2022-06-03 10:21 UTC, Sembauke approved these changes
LGTM 👍  

I will get a more thorough review in when client changes are added in another pr.

Note, to my knowledge you do not need to add `.json` at the end of an endpoint when you set the `Content-Type` to `application/json`

2022-06-03 10:59 UTC, ojeytonwilliams requested changes

2022-06-03 10:59 UTC, ojeytonwilliams commented on api-server/src/server/boot/settings.js
> +const { DISCOURSE_SECRET, API_LOCATION } = process.env;
For consistency, the secret should come via the secrets config.

2022-06-03 10:59 UTC, ojeytonwilliams commented on api-server/src/server/boot/settings.js
> +function connectDiscourse(req, res) {
The comments in this function seem redundant since the code is self-explanatory.

2022-06-03 10:59 UTC, ojeytonwilliams commented on api-server/src/server/boot/settings.js
> +  // Query string will include `sig` and `sso` with some user info
The comments after this one seem redundant.

2022-06-03 10:59 UTC, ojeytonwilliams commented on api-server/src/server/boot/settings.js
> +}
These seem important!

2022-06-03 10:59 UTC, ojeytonwilliams commented on api-server/src/server/boot/settings.js
> +  // Should this just redirect to /settings ?
Generally users will want to go back to where they were, no?

2022-06-03 10:59 UTC, ojeytonwilliams commented on api-server/src/server/boot/user.js
> +const { DISCOURSE_API_KEY, FORUM_LOCATION } = process.env;
If the api key is a secret, it should come from the secrets config.

2022-06-03 10:59 UTC, ojeytonwilliams commented on api-server/src/server/boot/user.js
> +          'Api-Username': 'Sky020'
This looks unfinished.

2022-10-28 23:00 UTC, naomi-lgbt commented
Are we still planning to implement this?

2022-10-29 18:30 UTC, ShaunSHamilton commented
@naomi-lgbt Thanks for the ping. Yes, we are, but we should add stuff like this to the new API.

2022-10-29 18:30 UTC, closed without merging