Fix/external cocktail link in cip
freeCodeCamp/freeCodeCamp pull request #46347
Opened 2022-06-05 06:28 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

clear task 109 in #40749

2022-06-05 17:01 UTC, huyenltnguyen submitted a review, later dismissed

2022-06-06 06:31 UTC, Sembauke requested changes

2022-06-06 06:31 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/sorting-algorithms-cocktail-sort.md
> +Cocktail sort works by iterating through the list, comparing adjacent elements and swapping them if they’re in the wrong order. This algorithm operates by traversing through a given array in both dir
```suggestion
Cocktail sort works by iterating through lists, comparing adjacent elements and swapping them if they’re in the wrong order. This algorithm operates by traversing through a given array in both directions.
```

2022-06-06 11:03 UTC, Sembauke submitted a review, later dismissed

2022-06-06 14:58 UTC, jeremylt approved these changes, later dismissed

2022-06-07 08:10 UTC, scissorsneedfoodtoo commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/sorting-algorithms-cocktail-sort.md
> +Cocktail sort works by iterating through lists, comparing adjacent elements and swapping them if they’re in the wrong order. This algorithm operates by traversing through a given array in both direct
Not necessary, but we could add in a serial comma here:

```suggestion
Cocktail sort works by iterating through lists, comparing adjacent elements, and swapping them if they’re in the wrong order. This algorithm operates by traversing through a given array in both directions.
```

2022-06-07 08:10 UTC, scissorsneedfoodtoo commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/sorting-algorithms-cocktail-sort.md
> +Cocktail sort works by iterating through lists, comparing adjacent elements and swapping them if they’re in the wrong order. This algorithm operates by traversing through a given array in both direct
Also not necessary, but we may be able to combine these two sentences:

```suggestion
Cocktail sort works by iterating through lists in both directions, comparing adjacent elements, and swapping them if they’re in the wrong order.
```

2022-06-07 10:11 UTC, scissorsneedfoodtoo approved these changes
~~Thanks again for your help, @Sboonny.~~

~~Everything LGTM :+1: :+1:~~

2022-06-07 10:53 UTC, scissorsneedfoodtoo submitted a review, later dismissed
Sorry I missed this earlier, @Sboonny, but I double checked and it seems like the current definition of cocktail sort is very close to the one used in this article: https://www.growingwiththeweb.com/2016/04/cocktail-sort.html

Would it be possible to update the description here? I'd be fine with going back to text that's close to the original description, but without the external links.

2022-06-07 11:01 UTC, Sboonny commented
No worries I will redo it👌

2022-06-10 13:45 UTC, moT01 reviewed
I guess I would be fine with it like this if others are. I think this would be quite difficult to solve with the given information. I suppose any sort would solve it, but I'm not sure this explains how a cocktail sort really works. I would need to look it up. I don't think it's too much of an issue, just pointing it out. Maybe this would be one where we keep one of the links - or maybe add this one, `https://rosettacode.org/wiki/Sorting_algorithms/Cocktail_sort`

2022-06-10 14:09 UTC, Sboonny commented
> I'm not sure this explains how a cocktail sort really works. I would need to look it up. I don't think it's too much of an issue, just pointing it out. Maybe this would be one where we keep one of the links - or maybe add this one, https://rosettacode.org/wiki/Sorting_algorithms/Cocktail_sort

I will research it more, if I can't provide sufficient description for it, I will add link back

2022-06-13 20:00 UTC, moT01 commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/sorting-algorithms-cocktail-sort.md
> +Cocktail sorting checks if the element `arr[0]` of the **firstSide** is bigger than the one following it, then it swaps their positions, a similar process happens to the **secondSide** it's checking
What do you think of this @Sboonny?

```suggestion
The [cocktail shaker](https://rosettacode.org/wiki/Sorting_algorithms/Cocktail_sort) sort is an improvement on the Bubble Sort. Given an array of numbers, the cocktail shaker sort will traverse the array from start to finish, moving the largest number to the end. Then, traverse the array backwards and move the smallest number to the start. It repeats these two passes, moving the next largest/smallest number to its correct position in the array until it is sorted.
```

2022-06-14 07:03 UTC, Sembauke approved these changes

2022-06-14 12:46 UTC, moT01 approved these changes
LGTM 🎉

2022-06-14 12:59 UTC, merged