fix(curriculum): external y-combinator links in CIP
freeCodeCamp/freeCodeCamp pull request #46360
Opened 2022-06-06 05:03 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

clear task 112 in #46349

2022-06-06 11:08 UTC, Sembauke requested changes

2022-06-06 11:08 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/y-combinator.md
> +Define the stateless Y combinator function and use it to compute factorial. The `factorial(N)` function is already given to you.
```suggestion
Define the stateless Y combinator function and use it to compute the factorials. The `factorial(N)` function is already given to you. 
```

2022-06-06 11:20 UTC, Sembauke approved these changes

2022-06-07 10:08 UTC, scissorsneedfoodtoo approved these changes
Awesome. Thanks again for all of your help improving this and the other interview prep challenges, @Sboonny.

Everything LGTM :+1:

2022-06-07 10:15 UTC, merged