feat(UI): add quotes when tests pass
freeCodeCamp/freeCodeCamp pull request #46429
Opened 2022-06-09 20:55 UTC by JordanMooree

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #46178

@ahmadabdolsaheb This seems to function as expected but I have a few thoughts and questions:
- Would we want styling applied to the quote? It looks pretty basic if it's just a `p` tag.
- I used compliments instead of quotes from `motivation.json` since that was the way it was done in the legacy RWD. Would you rather see the quote? If the quote is preferred, should I add in the author as well? 
- Please provide feedback on any naming conventions or if there is another approach I should take on this

2022-06-15 20:57 UTC, JordanMooree commented
It looks like the best way to address this is to put `<q>` tag around the quote so that [most browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q#browser_compatibility) will implement the text surrounded by quotation marks. More about [`<q>` tags here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/q).

As for the success message, I have a few ideas:

- We can remove the text `Congratulations, your code passes.` and replace it with the quote 
- We can let go of the congratulations text altogether and only display a quote, a big check mark, and all other features that are soon to come maybe something like the legacy RWD:
![image](https://user-images.githubusercontent.com/27147016/173926929-61fbfd69-8b16-4dce-bd56-2f728d0974e0.png)

Let me know what you think @ahmadabdolsaheb

2022-06-16 13:45 UTC, ahmadabdolsaheb commented
Thanks for the suggestions: I am discussing the above scenarios on the related issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/46178#issuecomment-1157678916.

Once we get some feedback, we can move forward with the implementation.

2022-06-18 07:51 UTC, ahmadabdolsaheb commented
you could go with the following mock:
<img width="568" alt="Screen Shot 2022-06-16 at 3 50 18 PM" src="https://user-images.githubusercontent.com/4591597/174428411-fdc96c0e-ee40-4ddd-9775-72fdba38189f.png">

The current congratulatory message could be set to sr-only.

2022-06-18 16:30 UTC, JordanMooree commented
@ahmadabdolsaheb I've made the changes, any accessibility issues to address for these changes?

2022-06-19 06:50 UTC, ahmadabdolsaheb commented
It looks good.  let's get this the progress bar in first so the completion state is more obvious. 
https://github.com/freeCodeCamp/freeCodeCamp/pull/46536/

2022-06-27 13:20 UTC, ahmadabdolsaheb commented
@JordanMooree, the progress bar is open to contributors if you want to take it.

2022-06-27 18:29 UTC, JordanMooree commented
@ahmadabdolsaheb sounds good, I'll take it 👍

2022-10-13 09:34 UTC, Sembauke commented
Hey @JordanMooree,
Are you still working on this, otherwise we can open this for other contributors!

Have a nice day, and happy coding.

2022-10-13 12:37 UTC, JordanMooree commented
Hey @Sembauke, Ahmad stated once the progress bar gets merged that this one should be good to go! 

I can get this pr rebased as soon as the progress bar gets merged

2022-12-19 15:10 UTC, raisedadead commented
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

2023-06-06 12:18 UTC, ahmadabdolsaheb commented
We have a progress bar, so this should be ready to go.

2023-06-07 13:59 UTC, ahmadabdolsaheb commented on client/src/templates/Challenges/classic/lower-jaw.tsx
> +
```suggestion
```

2023-06-07 14:07 UTC, ahmadabdolsaheb approved these changes

2023-06-07 15:53 UTC, raisedadead requested changes
This being a new feature, we should add a test. In this case, a unit test would be enough. 


Can we go ahead and add a jest-based test, please?

2023-06-07 17:55 UTC, bbsmooth commented
I think this is a cool concept and will make the steps much more interesting, but I am concerned about some of these quotes. I just got the following quote after passing a step:

`They're in another castle.`

Now maybe I'm showing my age here, but I have absolutely no idea how this quote relates to success. And looking through `motivation.json` I am finding many more quotes that I don't understand how they imply success.

Visually, I can see the checkmark icon next to the quote which is a tip-off that I passed the step. But if I am listening to the page then I will not know about the checkmark icon because we currently have it hidden from screen reader users. But now I am thinking that we should unhide it and give it an accessible name like "Step completed" so that screen reader users will get a clear message that they passed the step. Then, they would hear the following:

"Step completed. They're in another castle."

So if they are like me and have no idea what "They're in another castle." refers to, at least it will be clear up front that they successfully completed the step.

2023-06-07 19:06 UTC, raisedadead commented
Oh wow! That is a good catch @bbsmooth, and yes, I agree that some of the quotes may not make sense to some of the users. But that should be for another issue/PR.

2023-06-16 15:53 UTC, ahmadabdolsaheb commented
This is the latest state of the lower jaw quote, where it will live on a row of its own. closes https://github.com/freeCodeCamp/freeCodeCamp/issues/50634

<img width="607" alt="Screenshot 2023-06-16 at 6 46 33 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/0d0c3446-0595-4d8c-9342-333c8de727f7">

2023-06-16 16:19 UTC, bbsmooth commented
Functionally, LGTM.

I am noticing one small style discrepancy though:

![style-issue](https://github.com/freeCodeCamp/freeCodeCamp/assets/5926192/f4b1a2ec-1a05-41a3-8c64-d01095709aa6)

As you narrow the frame, the check mark icon gets smaller but the quote icon stays the same. I'm assuming the quote icon is the way we want it to work and the check mark icon needs to be fixed. Should we fix this in this PR?

2023-06-16 19:19 UTC, ahmadabdolsaheb commented
I noticed that it is happening with the other two icons as well so it is independent of the quote icon.
<img width="378" alt="Screenshot 2023-06-16 at 10 18 28 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/110c5fa6-6b54-43d9-a6e8-ad27c54ef64b">

We could address it in another issue/pr.

2023-06-20 02:34 UTC, JordanMooree commented
Sorry for coming back a bit late to this - do we want to address this style issue in this PR?

2023-06-20 07:33 UTC, ahmadabdolsaheb commented
it will be another pr since it was a pre existing issue. However, it would be great if you could add a cypress test to check look for the quote element when the code passes.

2023-06-20 15:35 UTC, JordanMooree commented
Sounds good, I could add that.

2023-06-24 03:45 UTC, closed without merging

2023-06-24 04:09 UTC, JordanMooree commented
It's been a while since using GitHub haha (accidentally ran `git push -f`) here is the other PR #50798  I have opened @ahmadabdolsaheb