Fix(curriculum): external Tower of Hanoi link in CIP
freeCodeCamp/freeCodeCamp pull request #46434
Opened 2022-06-10 07:54 UTC by Sboonny

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Tower of hanoi #40749

2022-06-10 09:17 UTC, Sembauke requested changes

2022-06-10 09:17 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/towers-of-hanoi.md
> +For example, object with these parameters `(4, 'A', 'B', 'C')`, will have a nested array `[['A', 'C'], ['B', 'A']]` indicating that the 1st move was to move a object from stack `A` to `C`, and the 2n
```suggestion
For example, objects with these parameters `(4, 'A', 'B', 'C')`, will have a nested array `[['A', 'C'], ['B', 'A']]` indicating that the 1st move was to move an object from stack `A` to `C`, and the 2nd move was to move an object from stack `B` to `A`.
```

2022-06-10 09:17 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/towers-of-hanoi.md
> +Write a function that return the moves to stack the objects in a nested array.
```suggestion
Write a function that returns the moves to stack the objects in a nested array.
```

2022-06-10 11:56 UTC, Sembauke submitted a review, later dismissed

2022-06-10 19:19 UTC, jeremylt commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/towers-of-hanoi.md
> +Solve the Towers of Hanoi problem. You have the number of objects as the first parameters, and strings used to identify each of the stacks of objects. create a nested array containing the list of mov
perhaps:
```suggestion
Solve the Towers of Hanoi problem. The number of objects will be given as the first parameter, and followed by the strings used to identify each of the stacks of objects. Create a nested array containing the list of moves, `["source", "destination"]`.
```

2022-06-10 19:20 UTC, jeremylt commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/towers-of-hanoi.md
> +For example, objects with these parameters `(4, 'A', 'B', 'C')`, will have a nested array `[['A', 'C'], ['B', 'A']]` indicating that the 1st move was to move an object from stack `A` to `C`, and the
```suggestion
For example, the parameters `(4, 'A', 'B', 'C')`, will result in nested array of moves `[['A', 'C'], ['B', 'A']]`, indicating that the 1st move was to move an object from stack `A` to `C` and the 2nd move was to move an object from stack `B` to `A`.
```

2022-06-12 10:52 UTC, Nirajn2311 commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/towers-of-hanoi.md
> +Solve the Towers of Hanoi problem. The number of objects will be given as the first parameter, and followed by the strings used to identify each of the stacks of objects. Create a nested array contai
```suggestion
Solve the Towers of Hanoi problem. The number of objects will be given as the first parameter, followed by the strings used to identify each stack of objects. Create a nested array containing the list of moves, `["source", "destination"]`.
```

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-06-12 15:49 UTC, Nirajn2311 approved these changes
LGTM 👍

2022-06-13 08:27 UTC, raisedadead approved these changes

2022-06-13 08:27 UTC, merged