fix(curriculum)missing test in step 27 of city skyline project
freeCodeCamp/freeCodeCamp pull request #46482
Opened 2022-06-13 10:49 UTC by ieahleen

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-06-13 12:40 UTC, ShaunSHamilton requested changes

2022-06-13 12:40 UTC, ShaunSHamilton commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98e3.md
> +assert.equal(new __helpers.CSSHelp(document).getStyle('.bb4')?.backgroundColor, 'var(--building-color4)')
```suggestion
assert.equal(new __helpers.CSSHelp(document).getStyle('.bb4')?.getPropVal('background-color', true), 'var(--building-color4)')
```

2022-06-13 15:46 UTC, ShaunSHamilton commented
@ieahleen Yes please. The `.getPropVal(..., true)` is necessary for CSS functions like `var`, `calc`, etc. Otherwise code like this fails:
```css
 background-color: var( --building-color);
```

2022-06-14 04:51 UTC, Sboonny approved these changes
LGTM

2022-06-14 09:56 UTC, ShaunSHamilton approved these changes
This LGTM 👍 

Thank you, Ilenia

2022-06-14 09:56 UTC, merged