fix(curriculum): external S-expressions link in CIP
freeCodeCamp/freeCodeCamp pull request #46533
Opened 2022-06-17 05:38 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

S-experrison #40749

2022-06-17 07:16 UTC, Sembauke requested changes

2022-06-17 07:16 UTC, Sembauke commented on curriculum/challenges/english/10-coding-interview-prep/rosetta-code/s-expressions.md
> +<a href="https://rosettacode.org/wiki/S-expressions" target="_blank" rel="noopener noreferrer nofollow">S-Expressions</a> present data as binary tree structure, making it possible to reference part o
```suggestion
<a href="https://rosettacode.org/wiki/S-expressions" target="_blank" rel="noopener noreferrer nofollow">S-Expressions</a> present data as a binary tree structure, making it possible to reference part of the data easily. This makes it convenient to parse and store data also.
```

2022-06-21 17:31 UTC, huyenltnguyen approved these changes

2022-06-22 07:01 UTC, Sembauke approved these changes

2022-06-22 07:01 UTC, merged