chore: update stripe
freeCodeCamp/freeCodeCamp pull request #46604
Opened 2022-06-21 15:01 UTC by ojeytonwilliams

I'm not sure why https://github.com/freeCodeCamp/freeCodeCamp/pull/46571 failed in the way it did, but this should fix it.

2022-06-21 15:22 UTC, raisedadead requested changes
Mind throwing `--save-exact` to the installation real quick? Helps avoid a few runs.

2022-06-21 16:06 UTC, raisedadead commented
Yes.

2022-06-21 16:07 UTC, raisedadead approved these changes

2022-06-22 13:59 UTC, ahmadabdolsaheb approved these changes

2022-06-22 13:59 UTC, merged