Fix/html validation building magazine project
freeCodeCamp/freeCodeCamp pull request #46613
Opened 2022-06-21 21:56 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46537

2022-06-27 13:27 UTC, moT01 requested changes

2022-06-27 15:33 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-grid-by-building-a-magazine/61437d575fb98f57fa8f7f36.md
> +You should have an opening `<html>` tag, and it should have `lang` of `en`.
Well, I should be more careful, I changed the wrong test. Thank you for testing it out. it would have been embarassing if it was merged

2022-06-27 17:35 UTC, Garyboyer22 commented
Hey sorry to bother you, I have a favor to ask, someone keeps getting into
my phone, is there any way I can tell how the are doing it..or away to stop
it..and to fix what they changed..thanks for your time


garyboyer

On Mon, Jun 27, 2022, 12:08 PM Tom ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> curriculum/challenges/english/14-responsive-web-design-22/learn-css-grid-by-building-a-magazine/61437d575fb98f57fa8f7f36.md
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/46613#discussion_r907387608>
> :
>
> > @@ -43,10 +43,10 @@ Your `html` element should have an opening tag.
>  assert(code.match(/<html\s*>/gi));
>  ```
>
> -Your `html` element should have a closing tag.
> +You should have an opening `<html>` tag, and it should have `lang` of `en`.
>
> The test above this one for the opening html tag is failing now with the
> regex it has. We could probably just get rid of that test - or change the
> regex.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/46613#pullrequestreview-1020195804>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY5BQP2FFHSBY67DFNCB2A3VRHGYBANCNFSM5ZN7ELZQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-06-28 21:46 UTC, moT01 approved these changes
LGTM 🎉 

The automated tests found it:
![Screen Shot 2022-06-28 at 4 37 25 PM](https://user-images.githubusercontent.com/20648924/176304160-68ced514-975e-426c-ad54-28e78c6b8e48.png)

The red 'X' means one of our automated tests failed - we can't (shouldn't) merge a PR until all the automated tests pass. You have a number of other open PR's where one or more of those tests are failing. You can click the details button next to a failing test to try and help you figure out what isn't passing - you should try and take a look at those and see if you can get them to pass. Sometimes the tests are flaky and fail for no real reason - then we usually just re-run the tests.

2022-07-07 15:02 UTC, Sembauke approved these changes

2022-07-07 15:02 UTC, merged