chore(curriculum): validate picasso painting
freeCodeCamp/freeCodeCamp pull request #46670
Opened 2022-06-26 09:37 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Contribute to #46540

2022-06-26 19:00 UTC, ieahleen requested changes
I think you deleted a piece while adding the lang attribute in the description

2022-06-26 19:06 UTC, ieahleen approved these changes, later dismissed

2022-06-29 21:38 UTC, moT01 approved these changes
LGTM 🎉

2022-06-30 08:26 UTC, majestic-owl448 approved these changes

2022-06-30 08:26 UTC, merged