feat(docs): new language lead handbook
freeCodeCamp/freeCodeCamp pull request #46680
Opened 2022-06-27 12:03 UTC by ieahleen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

After having discussed it on chat, and noticing certain questions coming up often, it was time to start this documentation.
To be updated as new questions come up.

2022-06-27 12:45 UTC, Dario-DC commented on docs/language-lead-handbook.md
> +In the `.csv` file you will find that the English language occupies the first three columns, `Term:English` is the column for the English term, `Description:English` us the column for the English des
```suggestion
In the `.csv` file you will find that the English language occupies the first three columns, `Term:English` is the column for the English term, `Description:English` is the column for the English description, and `Part:English` is for the grammar role, or part of the sentence, of the term.
```

2022-06-27 12:52 UTC, Sembauke requested changes

2022-06-27 12:56 UTC, Sembauke submitted a review, later dismissed

2022-06-27 16:56 UTC, DanielRosa74 approved these changes, later dismissed
LGTM

2022-06-29 16:22 UTC, nhcarrigan requested changes

2022-06-29 16:22 UTC, nhcarrigan commented on docs/language-lead-handbook.md
> +After you have made the changes and saved the file, you will need to make a PR with the proposed changes. After the PR is accepted, the script to update the Crowdin Glossary. Your glossary changes wi
```suggestion
After you have made the changes and saved the file, you will need to make a PR with the proposed changes. After the PR is accepted, you will need to run the GitHub Action workflow to update the Crowdin Glossary. Your glossary changes will not have immediate effects, but they will come.
```

2022-06-29 16:22 UTC, nhcarrigan commented on docs/language-lead-handbook.md
> +> In programs like Microsoft Excel you can hide the columns of the other languages to free screen real-estate and see the English columns and the target language columns near each other.
```suggestion
> In programs like Microsoft Excel you can hide the columns of the other languages to free up screen real-estate and see the English columns and the target language columns near each other.
```

2022-06-29 16:22 UTC, nhcarrigan commented on docs/language-lead-handbook.md
> +> An updated glossary helps in having an homogeneus translation of technical terms.
```suggestion
> An updated glossary helps in having an homogenous translation of technical terms.
```

2022-06-29 16:26 UTC, ieahleen commented on docs/language-lead-handbook.md
> +> An updated glossary helps in having an homogeneus translation of technical terms.
```suggestion
> An updated glossary helps in having an homogeneous translation of technical terms.
```

2022-06-29 16:28 UTC, nhcarrigan submitted a review, later dismissed

2022-06-29 17:09 UTC, sidemt reviewed
I'm sorry my review was in pending status. I suggest adding a few things.

2022-06-29 19:35 UTC, naomi-lgbt approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-01 15:34 UTC, Sembauke approved these changes

2022-07-01 15:34 UTC, merged