chore(curriculum): validate registration form project
freeCodeCamp/freeCodeCamp pull request #46707
Opened 2022-06-29 10:42 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [xc] I have tested these changes either locally on my machine, or GitPod.

Contribute to #46540

I decided to break the step into two, because this is still early and I don't want to overwhelm the campers

2022-06-29 17:02 UTC, ieahleen approved these changes, later dismissed
I approve, see if you think the comments could improve the text.

2022-06-29 17:02 UTC, ieahleen commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62bc29efa036af159e1a1392.md
> +Nest a self-closing `link` element in the `head` element. Give it a `rel` attribute value of `stylesheet` and an `href` attribute value of `styles.css`.
```suggestion
Nest a self-closing `link` element within the `head` element. Give it a `rel` attribute with value of `stylesheet` and an `href` attribute with a value of `styles.css`.
```

2022-06-29 17:13 UTC, ieahleen approved these changes, later dismissed

2022-06-30 11:50 UTC, Sboonny commented
running

> npm run update-step-titles

gave me this error

![image](https://user-images.githubusercontent.com/88248797/176670208-094e4d1c-772c-489c-8181-0a8ee6a5d60d.png)

2022-06-30 18:42 UTC, Sboonny commented
there were two duplicated `step 42` and `step 43`, I had to delete them and fix the meta 

> npm run update-step-titles 

runs without issue, but it won't hurt to double-check if I did something wrong

2022-07-11 11:39 UTC, Sboonny commented
@lasjorg I have cleared tab issues 👍

2022-07-11 13:04 UTC, moT01 requested changes
Something isn't quite right here. So you added a new step 5 and deleted the old step 42? I don't think step 42 needed to be deleted - it adds a good amount of styling to the form. Also, the code from the deleted step is still in the seed of steps after it. If you checkout this PR and go from step 43 to 44, the look of the form changes a lot cause the seed code from the delete step is still on 44 - but the user never adds that code as far as I can tell.

2022-07-11 15:25 UTC, Sboonny commented
@moT01 nice catch, I deleted a step after the merge conflict. but I can't recreate it `npm run lint:challenges` run with error, I will open a third pr

2022-07-11 15:25 UTC, closed without merging