fix: use regex to filter tests
freeCodeCamp/freeCodeCamp pull request #46751
Opened 2022-07-03 10:50 UTC by rsapkf

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The `1_unit-tests.js` file in [boilerplate-project-sudoku-solver](https://github.com/freeCodeCamp/boilerplate-project-sudoku-solver/blob/012734bd0a8dc2a57b9bcbbc28f1970ab23c16c7/tests/1_unit-tests.js#L7) contains a typo. The `UnitTests` should be `Unit Tests`. Fixing that typo by oneself causes the `All 12 unit tests are complete and passing.` test to fail even if all the tests are valid. Adding the `Unit ?Tests` regex ensures all previously passing tests are still valid as well as new changes do not affect the tests.

In general, adding a case insensitive regex based filter makes sure all other valid variations of the words will also work.

2022-07-05 23:55 UTC, nhcarrigan requested changes
We can make the regex a bit more lenient by allowing any number of spaces.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-05 23:55 UTC, nhcarrigan commented on curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/sudoku-solver.md
> +      return !!test.context.match(/Unit ?Tests/gi);
```suggestion
      return !!test.context.match(/Unit\s*Tests/gi);
```

2022-07-05 23:55 UTC, nhcarrigan commented on curriculum/challenges/english/06-quality-assurance/quality-assurance-projects/sudoku-solver.md
> +      return !!test.context.match(/Functional Tests/gi);
```suggestion
      return !!test.context.match(/Functional\s*Tests/gi);
```

2022-07-08 08:08 UTC, gikf approved these changes

2022-07-13 09:43 UTC, raisedadead approved these changes

2022-07-13 09:43 UTC, merged