docs: add how to translate info boxes headers
freeCodeCamp/freeCodeCamp pull request #46908
Opened 2022-07-15 13:08 UTC by ieahleen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46852 

This add how to translate the headers of these boxes in the translated docs:

2022-07-15 13:41 UTC, raisedadead approved these changes, later dismissed

2022-07-15 13:50 UTC, Sembauke requested changes, later dismissed

2022-07-15 13:50 UTC, Sembauke commented on docs/language-lead-handbook.md
> +Inside the object of the label property, before the `'/'` property, you would add a new property for your language, like `/i18n/<langauge>/`.
```suggestion
Inside the object of the label property, before the `'/'` property, you would add a new property for your language, like `/i18n/<language>/`.
```

2022-07-15 14:12 UTC, ieahleen commented on docs/language-lead-handbook.md
> +Inside the object of the label property, before the `'/'` property, you would add a new property for your language, like `/i18n/<langauge>/`.
lol, thanks

2022-07-15 14:46 UTC, DanielRosa74 approved these changes
LGTM

2022-07-16 07:13 UTC, Sboonny approved these changes

2022-07-16 07:13 UTC, Sboonny commented
LGTM, thank you.

2022-07-16 07:33 UTC, merged