fix: substitute moment in npm challenges
freeCodeCamp/freeCodeCamp pull request #46924
Opened 2022-07-16 08:46 UTC by ieahleen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #42294

The challenges work as is, but it looses the interactivity. As there is only one version of moment, the challenge Manage npm Dependencies By Understanding Semantic Versioning doesn't require any changes as there isn't a different version to ask the camper to change it to.

2022-07-20 14:29 UTC, naomi-lgbt commented
Hey @ieahleen - here's an empty example package we can use for these lessons: https://www.npmjs.com/package/@freecodecamp/example

I published a few different versions to cover the concepts in the lessons, let me know if you need any more versions.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/63889819/180007855-ca01ed34-6f8e-403b-8e93-17a8b0fcce06.png">


__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-07-22 10:44 UTC, ieahleen commented
Done, thank you @naomi-lgbt ! Now this is ready for review

2022-07-22 12:48 UTC, ShaunSHamilton requested changes
I do not know why the test is failing. While we are here, can we update the formatting to be consistent with majority of the curriculum:

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-tilde-character-to-always-use-the-latest-patch-version-of-a-dependency.md
> +"@freecodecamp/example" version should match "~1.2.13"
```suggestion
`"@freecodecamp/example"` version should match `"~1.2.13"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-tilde-character-to-always-use-the-latest-patch-version-of-a-dependency.md
> +"dependencies" should include "@freecodecamp/example"
```suggestion
`"dependencies"` should include `"@freecodecamp/example"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-tilde-character-to-always-use-the-latest-patch-version-of-a-dependency.md
> +Use the tilde (`~`) character to prefix the version of @freecodecamp/example in your dependencies, and allow npm to update it to any new PATCH release.
```suggestion
Use the tilde (`~`) character to prefix the version of `@freecodecamp/example` in your dependencies, and allow npm to update it to any new _patch_ release.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-tilde-character-to-always-use-the-latest-patch-version-of-a-dependency.md
> +In the package.json file, your current rule for how npm may upgrade @freecodecamp/example is to use a specific version (1.2.13). But now, you want to allow the latest 1.2.x version.
```suggestion
In the package.json file, your current rule for how npm may upgrade `@freecodecamp/example` is to use a specific version (1.2.13). But now, you want to allow the latest 1.2.x version.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-caret-character-to-use-the-latest-minor-version-of-a-dependency.md
> +Your current version of @freecodecamp/example should be "~1.2.13" which allows npm to install to the latest 1.2.x version. If you were to use the caret (^) as a version prefix instead, npm would be a
```suggestion
Your current version of `@freecodecamp/example` should be "~1.2.13" which allows npm to install to the latest 1.2.x version. If you were to use the caret (^) as a version prefix instead, npm would be allowed to update to any 1.x.x version.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-caret-character-to-use-the-latest-minor-version-of-a-dependency.md
> +Use the caret (`^`) to prefix the version of @freecodecamp/example in your dependencies and allow npm to update it to any new MINOR release.
```suggestion
Use the caret (`^`) to prefix the version of `@freecodecamp/example` in your dependencies and allow npm to update it to any new MINOR release.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-caret-character-to-use-the-latest-minor-version-of-a-dependency.md
> +"dependencies" should include "@freecodecamp/example"
```suggestion
`"dependencies"` should include `"@freecodecamp/example"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/use-the-caret-character-to-use-the-latest-minor-version-of-a-dependency.md
> +"@freecodecamp/example" version should match "^1.x.x"
```suggestion
`"@freecodecamp/example"` version should match `"^1.x.x"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/remove-a-package-from-your-dependencies.md
> +Remove the @freecodecamp/example package from your dependencies.
```suggestion
Remove the `@freecodecamp/example` package from your dependencies.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/remove-a-package-from-your-dependencies.md
> +"dependencies" should not include "@freecodecamp/example"
```suggestion
`"dependencies"` should not include `"@freecodecamp/example"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/manage-npm-dependencies-by-understanding-semantic-versioning.md
> +In the dependencies section of your package.json file, change the `version` of @freecodecamp/example to match MAJOR version 1, MINOR version 2 and PATCH version 13
```suggestion
In the dependencies section of your `package.json` file, change the version of `@freecodecamp/example` to match MAJOR version 1, MINOR version 2 and PATCH version 13
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/manage-npm-dependencies-by-understanding-semantic-versioning.md
> +"dependencies" should include "@freecodecamp/example"
```suggestion
`"dependencies"` should include `"@freecodecamp/example"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/manage-npm-dependencies-by-understanding-semantic-versioning.md
> +"@freecodecamp/example" version should be "1.2.13"
```suggestion
`"@freecodecamp/example"` version should be `"1.2.13"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm.md
> +Add version "1.1.0" of the "@freecodecamp/example" package to the `dependencies` field of your package.json file.
```suggestion
Add version "1.1.0" of the `@freecodecamp/example` package to the `dependencies` field of your `package.json` file.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm.md
> +**Note:** @freecodecamp/example is a faux package used as a learning tool.
```suggestion
**Note:** `@freecodecamp/example` is a faux package used as a learning tool.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm.md
> +"dependencies" should include "@freecodecamp/example"
```suggestion
`"dependencies"` should include `"@freecodecamp/example"`.
```

2022-07-22 12:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/05-back-end-development-and-apis/managing-packages-with-npm/expand-your-project-with-external-packages-from-npm.md
> +"@freecodecamp/example" version should be "1.1.0"
```suggestion
`"@freecodecamp/example"` version should be `"1.1.0"`.
```

2022-07-22 13:41 UTC, ShaunSHamilton approved these changes
LGTM 👍

2022-07-28 07:08 UTC, Sembauke approved these changes

2022-07-28 07:09 UTC, merged