fix(client): worker executor task once
freeCodeCamp/freeCodeCamp pull request #46951
Opened 2022-07-19 11:29 UTC by masterX89

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46949

2022-07-21 15:31 UTC, ojeytonwilliams requested changes
@masterX89 thanks for digging into this!  I think we can tweak your solution to make it a little clearer what's really happening:

2022-07-21 15:31 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/worker-executor.js
> +        const listener = self._events[event][i];
```suggestion
      const listeners = self._events[event].slice();
      for (let listener of listeners) {
```
The real issue is the splice, but we can work around it by copying the listener array.

2022-07-21 15:31 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/worker-executor.js
> +      }
```suggestion
      }
```
Completes above suggestion.

2022-07-21 15:53 UTC, masterX89 commented
Thanks for suggestions, I changed it to what the comment suggested, it makes the function much more clear😊

2022-07-21 15:57 UTC, ojeytonwilliams commented
@masterX89 it was only due to your efforts that I understood what was going on. Thanks again.

I can't see how your fix to `.once` could break anything, but I'll give this a proper QA tomorrow.

2022-07-22 16:18 UTC, ojeytonwilliams approved these changes
I tried it out on a few JS challenges and all seems to be fine. Nice work, @masterX89!

2022-08-08 12:04 UTC, masterX89 commented
Hi, @moT01 @Sboonny,
I think this issue, if fixed, could help resolve the TypeScript Migration for /client/src/templates/Challenges/utils/worker-executor.js and worker-executor.test.js
When you have time could you please take a look at this PR?
Thank you in advance :)

2022-08-08 12:16 UTC, Sboonny commented
@masterX89 I haven't interacted with that file before, but I will pass it to our chat to give it some spot light which it deserves

2022-08-08 12:19 UTC, masterX89 commented
Thank you very much~😊

2022-08-08 16:20 UTC, moT01 approved these changes
LGTM @masterX89 🎉 Thanks for contributing to freeCodeCamp 🎉

2022-08-08 16:20 UTC, merged