fix: allow HTML multiline tag syntax
freeCodeCamp/freeCodeCamp pull request #46983
Opened 2022-07-22 03:10 UTC by gabrielrochamd

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46978

2022-07-22 07:47 UTC, Sboonny approved these changes
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @gabrielrochamd, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2022-07-24 10:44 UTC, Sboonny requested changes
Sorry @gabrielrochamd, should have noticed it, but we are changing from jQuery to JavaScript

2022-07-24 10:44 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f332a88dc25a0fd25c7687a.md
> +assert($('p')[0].innerText === 'Est. 2020');
```suggestion
assert(document.querySelector("p").innerText === "Est. 2020")
```

2022-07-24 18:08 UTC, gabrielrochamd commented
@Sboonny I accidentally accepted the changes without editing commit message. Should I amend it?

2022-07-24 18:35 UTC, Sboonny commented
@gabrielrochamd all good thank you 👍

2022-07-24 18:36 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-07-27 21:25 UTC, naomi-lgbt approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-07-27 21:25 UTC, merged

2022-07-27 21:26 UTC, naomi-lgbt commented
Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝