feat: add some description for secure multiplayer project
freeCodeCamp/freeCodeCamp pull request #47004
Opened 2022-07-23 10:34 UTC by ieahleen

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44192

This is minimum effort, but it adds some instructions.

The alternative would be to bring a lot of what's in the tests in the instructions and make the tests more terse

2022-07-23 11:40 UTC, Sboonny submitted a review, later dismissed
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-07-23 16:41 UTC, ShaunSHamilton requested changes
Minor request

2022-07-23 16:41 UTC, ShaunSHamilton commented on curriculum/challenges/english/09-information-security/information-security-projects/secure-real-time-multiplayer-game.md
> +- the headers say that the site is powered by "PHP 7.4.3"
```suggestion
Create a secure multiplayer game in which each player can move their avatar, there is at least one collectible item, and the rank of the players is calculated based on their score.

For details consult the tests below.

Make sure that your game is secure! Include these security measures:

- The client should not be able to guess/sniff the MIME type
- Prevent XSS attacks
- Do not cache anything from the website in the client
- The headers say that the site is powered by `PHP 7.4.3`
```

2022-07-24 07:43 UTC, ieahleen commented on curriculum/challenges/english/09-information-security/information-security-projects/secure-real-time-multiplayer-game.md
> +- the headers say that the site is powered by "PHP 7.4.3"
minor request granted

2022-07-24 07:51 UTC, Sboonny approved these changes

2022-07-24 09:41 UTC, ShaunSHamilton approved these changes
LGTM 👍

2022-07-24 09:43 UTC, merged