fix: update Basic Node and Express challenge text
freeCodeCamp/freeCodeCamp pull request #47048
Opened 2022-07-27 11:10 UTC by scissorsneedfoodtoo

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/46910

This updates the challenge text for a couple of challenges where learners should no longer have to install `body-parser` or `dotenv` themselves.

As mentioned in https://github.com/freeCodeCamp/boilerplate-express/pull/98, if it's decided that we should't preinstall the `dotenv` package for local development, I can remove the commit that updates the challenge text here.

2022-07-27 12:36 UTC, Sboonny submitted a review, later dismissed
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-07-27 18:52 UTC, Sembauke requested changes

2022-07-27 18:52 UTC, Sembauke commented on curriculum/challenges/english/05-back-end-development-and-apis/basic-node-and-express/use-body-parser-to-parse-post-requests.md
> +As you can see, the body is encoded like the query string. This is the default format used by HTML forms. With Ajax, you can also use JSON to handle data having a more complex structure. There is als
```suggestion
As you can see, the body is encoded like the query string. This is the default format used by HTML forms. With Ajax, you can also use JSON to handle data having a more complex structure. There is also another type of encoding: multipart/form-data. This one is used to upload binary files. In this exercise, you will use a URL encoded body. To parse the data coming from POST requests, you must use the `body-parser` package. This package allows you to use a series of middleware, which can decode data in different formats.
```

2022-07-27 18:52 UTC, Sembauke commented on curriculum/challenges/english/05-back-end-development-and-apis/basic-node-and-express/use-body-parser-to-parse-post-requests.md
> +`body-parser` has already been installed, and is in your project's `package.json` file. `require` it at the top of the `myApp.js` file and store it in a variable named `bodyParser`. The middleware to
```suggestion
`body-parser` has already been installed and is in your project's `package.json` file. `require` it at the top of the `myApp.js` file and store it in a variable named `bodyParser`. The middleware to handle URL encoded data is returned by `bodyParser.urlencoded({extended: false})`. Pass the function returned by the previous method call to `app.use()`. As usual, the middleware must be mounted before all the routes that depend on it.
```

2022-07-27 21:04 UTC, ieahleen commented on curriculum/challenges/english/05-back-end-development-and-apis/basic-node-and-express/use-the-.env-file.md
> +If you are working locally, you will need the `dotenv` package. It loads environment variables from your `.env` file into `process.env`. The `dotenv` package has already been installed, and is in you
```suggestion
If you are working locally, you will need the `dotenv` package. It loads environment variables from your `.env` file into `process.env`. The `dotenv` package has already been installed, and is in your project's `package.json` file. At the top of your `myApp.js` file, import and load the variables with `require('dotenv').config()`.
```

2022-07-28 08:25 UTC, scissorsneedfoodtoo commented
Thank you for catching those things @Sembauke and @ieahleen, and for your helpful suggestions.

This should be ready for another round of reviews.

2022-07-28 08:44 UTC, Sboonny approved these changes

2022-07-28 10:23 UTC, Sembauke approved these changes

2022-07-28 10:23 UTC, merged