TYPO: improved words
freeCodeCamp/freeCodeCamp pull request #47070
Opened 2022-07-28 18:35 UTC by Kartik2220

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2022-07-28 18:46 UTC, Sboonny requested changes
I don't think they are typos, but thank you for trying to improve them

2022-07-28 18:46 UTC, Sboonny commented on docs/how-to-open-a-pull-request.md
> +Whenever you opening a Pull Request(PR), you can use the below to determine the type, scope (optional), and description.
```suggestion
Whenever you open a Pull Request(PR), you can use the below to determine the type, scope (optional), and description.
```

2022-07-28 18:46 UTC, Sboonny commented on docs/how-to-open-a-pull-request.md
> +Keep it short,to the point (less than 30 characters) and simple, you can add more information in the PR description box and comments.
```suggestion
Keep it short, to the point (less than 30 characters) and simple, you can add more information in the PR description box and comments.
```

2022-07-28 18:46 UTC, Sboonny commented on docs/how-to-open-a-pull-request.md
> +4. In the body of your PR include a more detailed summary of the changes you made and why you changed.
```suggestion
4. In the body of your PR, include a more detailed summary of the changes you made and how your changes are helpful.
```

2022-07-29 06:28 UTC, Sboonny submitted a review, later dismissed
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Kartik2220, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2022-07-29 06:41 UTC, Kartik2220 commented
give me improvements suggestions if needed :)

2022-07-29 08:16 UTC, Sboonny commented
> give me improvements suggestions if needed :)

@Kartik2220 sure. 

Mentioning the old change was worse than the current one, and following our pr title guidelines will make maintainers take you more seriously

2022-07-29 15:46 UTC, jeremylt commented on docs/how-to-open-a-pull-request.md
> +Keep it short (less than 30 characters), to the point and simple, you can add more information in the PR description box and comments.
```suggestion
Keep it short (less than 30 characters) and simple; you can add more information in the PR description box and comments.
```

2022-07-29 15:46 UTC, jeremylt commented on docs/how-to-open-a-pull-request.md
> +4. In the body of your PR, include a more detailed summary of the changes you made and how your changes are helpful.
```suggestion
4. Include a more detailed summary of the changes you made and how your changes are helpful in the body of your PR.
```

2022-07-29 15:47 UTC, jeremylt reviewed
If we are doing to change the wording around, we should actually make changes for grammatical correctness.

Just changing the wording isn't value added, IMHO.

2022-07-29 15:48 UTC, jeremylt commented
Side note - your PRs are not using the documentation that you are trying to edit. The titles don't match the recommended format.

2022-07-29 15:56 UTC, Kartik2220 commented
> Side note - your PRs are not using the documentation that you are trying to edit. The titles don't match the recommended format.

can you explain me brifly what i have to improve ?

2022-07-29 15:57 UTC, jeremylt commented
> can you explain me brifly what i have to improve ?

https://github.com/freeCodeCamp/freeCodeCamp/blob/972dbd5c27579ffc77c10acc6fec8170943cf1dd/docs/how-to-open-a-pull-request.md?plain=1#L8

2022-07-29 16:03 UTC, Kartik2220 commented
> > can you explain me brifly what i have to improve ?
> 
> https://github.com/freeCodeCamp/freeCodeCamp/blob/972dbd5c27579ffc77c10acc6fec8170943cf1dd/docs/how-to-open-a-pull-request.md?plain=1#L8

i changed typo to FIX is it okay ?

2022-07-29 16:05 UTC, jeremylt commented
You probably want `doc` since you are changing the documentation, like it says here:
https://github.com/freeCodeCamp/freeCodeCamp/blob/972dbd5c27579ffc77c10acc6fec8170943cf1dd/docs/how-to-open-a-pull-request.md?plain=1#L27

2022-07-29 16:07 UTC, Kartik2220 commented
> You probably want `doc` since you are changing the documentation, like it says here:
> 
> https://github.com/freeCodeCamp/freeCodeCamp/blob/972dbd5c27579ffc77c10acc6fec8170943cf1dd/docs/how-to-open-a-pull-request.md?plain=1#L27



> You probably want `doc` since you are changing the documentation, like it says here:
> 
> https://github.com/freeCodeCamp/freeCodeCamp/blob/972dbd5c27579ffc77c10acc6fec8170943cf1dd/docs/how-to-open-a-pull-request.md?plain=1#L27

YES DONE

2022-07-29 16:08 UTC, jeremylt commented
Thanks for the fix. 

There's no need to scream in ALL CAPS.

2022-07-29 16:35 UTC, jeremylt approved these changes

2022-07-29 19:18 UTC, Sboonny approved these changes

2022-07-29 19:44 UTC, merged