added clarification to instructions
freeCodeCamp/freeCodeCamp pull request #47125
Opened 2022-08-02 13:40 UTC by shawn-carrie

2022-08-02 15:01 UTC, Sboonny requested changes
when I checked the content on [grammerly report](https://www.grammarly.com/report?alerts=NobwRAxghgLgpgcwPYCcCeYBcYDCSC2ADgAoCuAdhDGADRgIpKmFZhmUymwCWS5tkWIlRoAEqXxR%2B2dlS4xe5AATdlEAoSbkAJgHp1RADZwAHkoDOccvEpxzA9RWqYAjAF8a4aPGTpWAETh4FHxVOBR7OgYmFmwAcRQofEkUByFfMQkpAKDw0PJwpVJLJQAKKF0pXRgACzhqmu5zGiUgiAA6AEoHLWd3T0EfEVZiQygEbigUJvwBaOYRsYmpmbSh9HFJaTAAVXJUbgnyKEMldWsrajpHaywXAE4PL3Th7AB1VG0cGqRuCDg5owFtgAKLkGpSf74S5rYQbLLbD4obRnH5-AHXXpYABMbgAukA&page=plagiarism&breadcrumbs=true) it showed plagriarism. 

Is this text copied from somewhere?

2022-08-02 15:08 UTC, Sboonny commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/using-objects-for-lookups.md
> +Convert the switch statement into an object called `lookup` – which will store coded words from the [The International Radiotelephony Spelling Alphabet](https://en.wikipedia.org/wiki/NATO_phonetic_al
We are against the usage of external links, we are trying to make freeCodeCamp self sufficient

2022-08-02 15:48 UTC, jeremylt commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/using-objects-for-lookups.md
> +const lastLetter = reverseAlphabet[25];
The change from `alpha` to `reverseAlphabet` is the only part of this PR that I think we should keep, honestly

2022-08-02 15:48 UTC, jeremylt commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/using-objects-for-lookups.md
> +let value = 2;
No, `const` is correct here

2022-08-06 12:14 UTC, Sboonny commented
Thank you for your pull request, you can open new pull requests with jeremy suggestion if you want.

But we are closing this pull request. Please suggest links and other details to add the challenge's corresponding guide post through [a forum topic](https://forum.freecodecamp.org/new-topic?category=Contributors&title=&body=**What%20is%20your%20hint%20or%20solution%20suggestion%3F**%0A%0A%0A%0A%0A**Challenge%3A**%0A%0A%0A**Link%20to%20the%20challenge%3A**) instead.

If you think we're wrong in closing this pull request, please request for it to be reopened. Thank you, and happy coding.

2022-08-06 12:14 UTC, closed without merging