fix(curriculum): Changed Mongoose version to avoid warnings in boilerplate's Node console when working on Mongoose challenges
freeCodeCamp/freeCodeCamp pull request #47129
Opened 2022-08-02 17:34 UTC by RandellDawson

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

As mentioned [in this PR's comments](https://github.com/freeCodeCamp/boilerplate-mongomongoose/pull/36#issuecomment-1202987911), I found simply removing `mongodb` and changing `mongoose` version to `^5.11.15` gets rid of all the warning messages in the Node console and does not affect any of the challenges in the MongoDB and Mongoose section challenges.  See [related boilerplate PR]() where I change the `package.json` to remove `mongodb` and change the `mongoose` version to `^5.11.15`.

This PR updates the instructions and tests to work with the changes in the corresponding boilerplate PR (mentioned above).

2022-08-02 21:02 UTC, naomi-lgbt approved these changes, later dismissed
This is a good idea.

I wonder if we should update the block description:
> Mongoose is a popular npm package that is often installed alongside Mongo.

2022-08-02 21:14 UTC, RandellDawson commented
> This is a good idea.
> 
> I wonder if we should update the block description:
> 
> > Mongoose is a popular npm package that is often installed alongside Mongo.

Probably.  What did you have in mind?

2022-08-02 22:01 UTC, RandellDawson commented
**Update:**  I have confirmed using a replit, that installing `mongoose@5.11.15` without also installing `mongodb` as a dependency does not affect the project.  I was able to use my same code that passed with both `mongodb@~3.6.0` and `mongoose@~5.4.0` with no warning messages and passed all the challenges.

2022-08-02 23:16 UTC, naomi-lgbt commented
> Probably. What did you have in mind?

Maybe something like "Mongoose is a popular npm package for interacting with MongoDB"?

> we could rename the section to just Mongoose

I think the course name is okay - we are teaching campers about MongoDB. It's just the mention of the `mongo` package that needs to be removed.

2022-08-02 23:21 UTC, RandellDawson commented
> Maybe something like "Mongoose is a popular npm package for interacting with MongoDB"?

I like it.

2022-08-03 01:03 UTC, naomi-lgbt commented
Sure I can do that!

2022-08-03 03:04 UTC, scissorsneedfoodtoo requested changes

2022-08-03 03:04 UTC, scissorsneedfoodtoo commented on curriculum/challenges/english/05-back-end-development-and-apis/mongodb-and-mongoose/install-and-set-up-mongoose.md
> +        'Wrong version of "mongoose". It should be ~5.11.15'
Just noticed one character here that can be updated:

```suggestion
        'Wrong version of "mongoose". It should be ^5.11.15'
```

2022-08-03 04:59 UTC, scissorsneedfoodtoo approved these changes

2022-08-03 05:32 UTC, Sboonny approved these changes

2022-08-03 05:36 UTC, Sboonny commented
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-08-03 05:36 UTC, merged