Added spacing fix to catch end of line spaces
freeCodeCamp/freeCodeCamp pull request #47134
Opened 2022-08-03 01:58 UTC by hanswang123456

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #47128

Added fix for spacing after tags/comments in step 6 of cat-photo-app.

2022-08-03 05:47 UTC, Sboonny requested changes
Test fails if someone doesn't add space after the text

![image](https://user-images.githubusercontent.com/88248797/182532929-44c47dcb-1028-4f93-8060-c90414dc1424.png)

2022-08-03 05:47 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc23991f86c76b9248c6eb8.md
> +    .match(/<\/h2>\s+\n\s{6}<!--\s*todo:\s+add\s+link\s+to\s+cat\s+photos\s*-->/)
```suggestion
    .match(/<\/h2>\s*\n\s{6}<!--\s*todo:\s+add\s+link\s+to\s+cat\s+photos\s*-->/)
```

2022-08-03 05:47 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc23991f86c76b9248c6eb8.md
> +assert(code.toLowerCase().match(/-->\s+\n\s{6}<p>/));
```suggestion
assert(code.toLowerCase().match(/-->\s*\n\s{6}<p>/));
```

2022-08-05 07:09 UTC, Sboonny commented
Sorry for leaving you hanging, but I haven't approved the PR after the changes, because the issue is still in waiting triage and none else has toned and gave his opinion on it

2022-08-05 13:06 UTC, closed without merging

2022-08-05 13:10 UTC, hanswang123456 commented
No worries, I had to redo a bit of the pull request and move it to a new branch on my fork.