Fix/update cat photo app bug of not checking type attribute
freeCodeCamp/freeCodeCamp pull request #47152
Opened 2022-08-04 05:40 UTC by kelvinyy

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47106

2022-08-04 06:31 UTC, Sboonny requested changes
Thank you for adding the test and taking care of it, but the campers who fail the test won't know that they required to put in `type` attribute

Can you change this into its own hint something like this

> Both radio buttons should have a `type` attribute. Check that there is a space after the opening tag's name and/or there are spaces before all attribute names.
> ```js
> const radioButtons = [...document.querySelectorAll('input[type="radio"]')];
> assert(radioButtons.every((btn) => btn.hasAttribute('type')));
> ```

2022-08-04 11:29 UTC, Sboonny requested changes
Wow, thank you for the quick update.

Nitpicks about the formating

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804de.md
> +
```suggestion
```

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804de.md
> +
```suggestion
```

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5ef9b03c81a63668521804de.md
> +
```suggestion
```

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5f1a80975fc4bcae0edb3497.md
> +Both radio buttons should have a `type` attribute. Check that there is a space after the opening tag's name and/or there are spaces before all attribute names.
```suggestion

Both radio buttons should have a `type` attribute. Check that there is a space after the opening tag's name and/or there are spaces before all attribute names.
```

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5f1a80975fc4bcae0edb3497.md
> +
```suggestion
```

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5f1a80975fc4bcae0edb3497.md
> +
```suggestion
```

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5f1a80975fc4bcae0edb3497.md
> +
```suggestion
```

2022-08-04 11:29 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5f1a80975fc4bcae0edb3497.md
> +
```suggestion
```

2022-08-04 14:32 UTC, Sboonny commented
I have fixed two spaced I didn't notice first, after the test have passed I will approve it. So

#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @kelvinyy, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2022-08-05 10:15 UTC, Sembauke approved these changes

2022-08-05 10:19 UTC, Sboonny approved these changes

2022-08-05 10:19 UTC, merged