fix(curriculum) changed wording on step 55
freeCodeCamp/freeCodeCamp pull request #47182
Opened 2022-08-06 06:46 UTC by DylanDevelops

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47175

Changed the wording since there was confusion on the forums.

2022-08-06 08:09 UTC, Sboonny reviewed
nitpicks

2022-08-06 08:09 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60ffe9cb47809106eda2f2c9.md
> +Change the `margin property to include `1em` on the top and bottom. Be sure to leave the right and left margins at `auto` and then set the width as described above.
```suggestion
Change the `margin` property to include `1em` on the top and bottom. Be sure that the right and left margins are set to `auto`, then set the width as described above.
```

2022-08-06 10:02 UTC, Sboonny submitted a review, later dismissed
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-08-06 18:50 UTC, bbsmooth requested changes
I think this should be split into three sentences. The second sentence has two separate instructions in it that are unrelated. Bu if you only want two sentences then it would make more sense to combine the first two instructions which are related.

> Change the margin property to include 1em on the top and bottom,  while leaving the right and left margins set to `auto`. And/Then set the width as described above.

Although there is nothing wrong with starting a sentence with "And" I know that people are taught no to, so start it with "Then" if that makes you feel more comfortable.

2022-08-07 00:22 UTC, DylanDevelops commented
I changed the final word from `And/Then` to `Finally`. Hopefully this is good. If you want me to revert back to `And/Then` I can just let me know. Also, I added codeblocks to a couple words in the text that needed it.

2022-08-07 00:28 UTC, bbsmooth commented
Sorry, I probably wasn't as clear as I could have been. I didn't mean to literally use "And/Then" in the solution. It was more of an either/or sort of thing. Personally, I would start the last sentence as "And then set the width as described above." But I understand that some people have an aversion to starting a sentence with "And". So you can drop it completely and just make it "Then set the width as described above."

"Finally" works too, but personally I think it is a little overkill here. We are only asking them to do two things: change top/bottom margins and set min width. I think "Finally" would work better if we were asking them to do a lot more. But it's not a deal breaker for me. I'll let others decide.

2022-08-07 00:38 UTC, DylanDevelops commented
@bbsmooth Should I just hold off to make another edit until I get another response or just go with either `and/then`. i can do whatever. I agree with `finally` feeling like overkill. I can do whatever, however.

2022-08-07 00:46 UTC, bbsmooth commented
Just go with "Then set the width as described above." to avoid the inevitable grammar war.

2022-08-07 00:51 UTC, DylanDevelops commented
> Just go with "Then set the width as described above." to avoid the inevitable grammar war.

That works for me! Thank you @bbsmooth!

2022-08-07 03:43 UTC, bbsmooth approved these changes

2022-08-07 04:11 UTC, Sboonny approved these changes

2022-08-07 04:11 UTC, merged

2022-08-07 04:15 UTC, bbsmooth commented
Ahh, I didn't realize I had that type of approval power :smile:

2022-08-07 05:46 UTC, DylanDevelops commented
> Ahh, I didn't realize I had that type of approval power 😄

haha! are you a member of freecodecamp? how do you have that power lol