chore(client): Typescript migration of __mocks__/gatsby.js
freeCodeCamp/freeCodeCamp pull request #47272
Opened 2022-08-12 20:26 UTC by SadmanSyfe

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes part of #43778

2022-08-13 16:49 UTC, Sembauke approved these changes, later dismissed

2022-08-19 11:53 UTC, ojeytonwilliams requested changes
Hey @SadmanSyfe, thanks for taking this on. I think there are a few things we need to do differently:

2022-08-19 11:53 UTC, ojeytonwilliams commented on client/src/__mocks__/gatsby.ts
> +import { LinkProps } from '@reach/router';
```suggestion
import { GatsbyLinkProps } from 'gatsby';
```
As I understand it, we're trying to replace gatsby's link, not reach router's.

2022-08-19 11:53 UTC, ojeytonwilliams commented on client/src/__mocks__/gatsby.ts
> -      to,
I believe these are all part of GatsbyLinkProps, so we should be discarding them.

2022-08-19 11:53 UTC, ojeytonwilliams commented on client/src/__mocks__/gatsby.ts
> +    const pathPrefix: string =
```suggestion
    const pathPrefix =
```
TS can infer this.

2022-08-19 16:54 UTC, closed without merging

2022-08-19 17:22 UTC, ojeytonwilliams commented
Hey @SadmanSyfe, don't feel like you have to delete the branch because git got a little messy.  It's definitely recoverable. I recommend reaching out in discord if you'd like some help!

2022-08-19 17:31 UTC, SadmanSyfe commented
> Hey @SadmanSyfe, don't feel like you have to delete the branch because git got a little messy. It's definitely recoverable. I recommend reaching out in discord if you'd like some help!

@ojeytonwilliams Thank you for your advice. 😄 

> Hey @SadmanSyfe, thanks for taking this on. I think there are a few things we need to do differently:

I will create a new PR solving these issues.

2022-08-19 18:19 UTC, ojeytonwilliams commented
Awesome, thanks @SadmanSyfe!