fix: Updated step 12 for the CatPhotoApp
freeCodeCamp/freeCodeCamp pull request #47345
Opened 2022-08-20 11:41 UTC by Jagrutiti

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #47010 

Screenshot:
![image](https://user-images.githubusercontent.com/28809492/185744268-b9006237-b361-4389-9fda-796803a375c5.png)

2022-08-22 07:24 UTC, Sembauke requested changes

2022-08-22 07:24 UTC, Sembauke commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md
> +You can turn words inside of a `p` element into a link by surrounding them with an opening `<a>` tag and closing `</a>` tag. In the text of your `p` element, turn the words `cat photos` into a link t
```suggestion
You can turn words inside of a `p` element into a link by surrounding them with an opening `<a>` tag and closing `</a>` tag. Inside the `p` element, turn the words `cat photos` into a link to `https://freecatphotoapp.com`.
```

2022-08-22 18:48 UTC, naomi-lgbt requested changes
I've added a comment here, but I'm not sure if this is the best approach as opposed to splitting the step up (as proposed in another PR).

2022-08-22 18:48 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa22d1b521be39a3de7be0.md
> +You can turn words inside of a `p` element into a link by surrounding them with an opening `<a>` tag and closing `</a>` tag. Inside the `p` element, turn the words `cat photos` into a link to `https:
This change clarifies how to nest the new `a` element, but completely omits the instruction to remove the *old* `a` element.

2022-09-14 19:55 UTC, gikf commented
Hey @Jagrutiti 

Thank you for opening this pull request.

As there was different PR changing the relevant step - #47320 -  merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

2022-09-14 19:55 UTC, closed without merging