fix: only allow display flex in media query build project landing page project
freeCodeCamp/freeCodeCamp pull request #47382
Opened 2022-08-25 12:43 UTC by Sembauke

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #46887

2022-08-25 18:18 UTC, hanswang123456 reviewed
This does resolve the issue, especially with the updated description.

2022-09-15 17:05 UTC, moT01 requested changes
I don't think we should require the property to be in a media query. This would break already completed projects that did not put it there. If we can, we should stick with current test (text) that just checks if the project uses the property at least once - and adjust the test so it can be in, or not in, a media query.

Also, when we get this figured out - we want to mimic the changes in the duplicate legacy RWD project.

2022-09-16 19:44 UTC, hanswang123456 commented on curriculum/challenges/english/14-responsive-web-design-22/build-a-product-landing-page-project/build-a-product-landing-page.md
> +Your media query should contain a `display` property with the value set to `flex` or `inline-flex`
I think giving such detailed instruction isn't necessary. Just let the user know they need to use flexbox.

2022-09-16 19:45 UTC, hanswang123456 commented
> I don't think we should require the property to be in a media query. This would break already completed projects that did not put it there. If we can, we should stick with current test (text) that just checks if the project uses the property at least once - and adjust the test so it can be in, or not in, a media query.
> 
> Also, when we get this figured out - we want to mimic the changes in the duplicate legacy RWD project.

Perhaps keep the old code and add on the checks for media query CSS

2022-09-18 13:57 UTC, closed without merging