Changed descriptions of id from properties to attributes
freeCodeCamp/freeCodeCamp pull request #47432
Opened 2022-09-01 17:09 UTC by adameshg

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47423

The text in 3 challenges in the Responsive Web Design curriculum incorrectly referred to `ids` as "properties" rather than "attributes". This PR fixes this error :)

2022-09-01 18:19 UTC, Sboonny reviewed
What do you think of Shaun [comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/47423#issuecomment-1233271399)?

His suggestion is helpful for translation.

2022-09-01 18:25 UTC, adameshg commented
> What do you think of Shaun [comment](https://github.com/freeCodeCamp/freeCodeCamp/issues/47423#issuecomment-1233271399)?
> 
> His suggestion is helpful for translation.

Ah, my bad, I'd missed that -- thank you for pointing it out! To make sure I'm understanding correctly, should the values in all 3 examples be `first-name`, `last-name`, `email`, `new-password`?

2022-09-01 19:04 UTC, Sboonny requested changes
No worries, I thought we missed something out.

> Ah, my bad, I'd missed that -- thank you for pointing it out! To make sure I'm understanding correctly, should the values in all 3 examples be `first-name`, `last-name`, `email`, `new-password`?

Not really, the values don't need to be altered. We can change the arrangement only

2022-09-01 19:04 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff8b9dab5ac88e4d3d43a3.md
> +Use these values for the respective `id` attributes: `first-name`, `last-name`, `email`, `new-password`
```suggestion
Use `first-name`, `last-name`, `email`,  and `new-password` as values for the respective `id` attributes.
```

2022-09-01 19:04 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff8e998d3e7eae14d6ae3b.md
> +Use these values for the respective `id` attributes: `personal-account`, `business-account`, `terms-and-conditions`
```suggestion
Use `personal-account`, `business-account`, and `terms-and-conditions` as values for the respective `id` attributes.
```

2022-09-01 19:04 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/62ff919a7b5612c0670923a5.md
> +Use these values for the respective `id` attributes: `profile-picture`, `age`, `referrer`, `bio`
```suggestion
Use `profile-picture`, `age`, `referrer`, and `bio` as values for the respective `id` attributes.
```

2022-09-02 04:01 UTC, Sboonny approved these changes
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @adameshg, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2022-09-02 05:19 UTC, SaadAnsari17 commented
> Checklist:
> 
> * [x]  I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
> * [x]  My pull request has a descriptive title (not a vague title like `Update index.md`)
> * [x]  My pull request targets the `main` branch of freeCodeCamp.
> * [x]  I have tested these changes either locally on my machine, or GitPod.
> 
> Closes #47423
> 
> The text in 3 challenges in the Responsive Web Design curriculum incorrectly referred to `ids` as "properties" rather than "attributes". This PR fixes this error :)

Kindly check if a pr is already made before making your own pr.

2022-09-02 05:22 UTC, Sboonny commented
@SaadAnsari17 they have not broken our guidelines, so there is no warranty for that warning/request.

2022-09-02 16:58 UTC, jeremylt approved these changes

2022-09-02 16:58 UTC, merged