feat: standardize view button text
freeCodeCamp/freeCodeCamp pull request #47525
Opened 2022-09-15 15:57 UTC by Hdanzo

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #46497

Add new translation keys 
Delete unused translation keys 
Fix tests broken with new functionalities

2022-09-15 19:36 UTC, Sboonny commented
I have closed this and reopened it, because cypress test looks weird.

2022-09-27 19:44 UTC, Sboonny approved these changes
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Hdanzo, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2022-09-28 18:54 UTC, Sboonny requested changes
I had a meeting with @ahmadabdolsaheb, and we discussed the pull request and there are issues and I didn't notice

2022-09-28 18:54 UTC, Sboonny commented on client/i18n/locales/english/translations.json
> +    "view-project": "View <0>Project</0>",
There is may cause confusion to screen readers, and translation team

```suggestion
```

2022-09-28 18:54 UTC, Sboonny commented on client/src/components/solution-display-widget/index.tsx
> +    );
with deletion of other view variation, we can have simple translated view text
```suggestion
 const viewText = t('buttons.view')
```

2022-09-28 18:54 UTC, Sboonny commented on client/src/components/solution-display-widget/index.tsx
>        {showOrViewText}
```suggestion
      {viewText}

2022-09-28 18:54 UTC, Sboonny commented on client/src/components/solution-display-widget/index.tsx
> +      </Trans>
```suggestion
      {viewText}
```

2022-09-28 18:54 UTC, Sboonny commented on client/src/components/solution-display-widget/index.tsx
> +          </Trans>
```suggestion
      {viewText}
```

2022-09-28 18:54 UTC, Sboonny commented on client/src/components/solution-display-widget/index.tsx
> +          </Trans>
```suggestion
      {viewText}
```

2022-09-29 06:15 UTC, Sboonny commented on client/src/components/solution-display-widget/index.tsx
> +      title='view code button'
Adding a title will add a tooltip, if we are going to keep it around, we need it to be descriptive of what the button for, like `navigate to solution of this certifcation` and it needs to be translatable.

we can cross that bridge another time, so here is my suggestion

```suggestion
```

If you want to add it, you can add descriptive title in `.json` file and use it as a value for the title. `viewText` is a good example

2022-09-30 04:13 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-09-30 07:39 UTC, ahmadabdolsaheb approved these changes

2022-09-30 07:39 UTC, merged