description change of learn-css-variables-by-building-a-city-skyline
freeCodeCamp/freeCodeCamp pull request #47796
Opened 2022-10-03 12:38 UTC by nayabatir1

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #47740

`learn-css-variables-by-building-a-city-skyline` description changed as per comment

2022-10-03 14:09 UTC, jeremylt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98d5.md
> +Try to center your `.bb1` element, using these style properties: `display: flex;`, `flex-direction: column;`, and `align-items: center;`.
```suggestion
Center your `.bb1` element by using these style properties: `display: flex;`, `flex-direction: column;`, and `align-items: center;`.
```

2022-10-03 15:29 UTC, moT01 commented
There's a [duplicate of the issue with some more suggestions](https://github.com/freeCodeCamp/freeCodeCamp/pull/47796) I like a little better. "Center the parts of your building by turning the .bb1 element into a flexbox parent. Use the flex-direction and align-items properties to center the children." is the example I gave there.

2022-10-03 15:36 UTC, Sboonny commented
I agree with Tom, again sorry @nayabatir1 for the confusion

2022-10-04 12:15 UTC, ShaunSHamilton commented
Hello there,

Please edit this PR title to match our recommended title format: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request

2022-10-04 17:49 UTC, nayabatir1 commented
> Hello there,
> 
> Please edit this PR title to match our recommended title format: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request

Done

2022-10-06 09:44 UTC, ieahleen requested changes
> Done

This is not a documentation change... the automatically applied label https://github.com/freeCodeCamp/freeCodeCamp/labels/scope%3A%20curriculum could be an hint toward the scope

Please consult our [contributing documentation](https://contribute.freecodecamp.org/#/), specifically [How to open a Pull Request (PR)](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=how-to-open-a-pull-request-pr)

2022-10-06 16:28 UTC, nayabatir1 commented
> > Done
> 
> This is not a documentation change... the automatically applied label [ scope: curriculum](https://github.com/freeCodeCamp/freeCodeCamp/labels/scope%3A%20curriculum) Lessons, Challenges, Projects and other Curricular Content in curriculum directory. could be an hint toward the scope
> 
> Please consult our [contributing documentation](https://contribute.freecodecamp.org/#/), specifically [How to open a Pull Request (PR)](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=how-to-open-a-pull-request-pr)

Updated

2022-10-11 18:11 UTC, ieahleen commented
The linked issue is still with https://github.com/freeCodeCamp/freeCodeCamp/labels/scope%3A%20curriculum and has not been opened to contributions, as such I am blocking this until consense ahs been reached.

2022-10-11 18:26 UTC, nayabatir1 commented
Hey @ieahleen is there anything that is pending from my end, do let me know as I'm not clear what needs to be done here.

2022-10-11 18:36 UTC, ieahleen commented
You have opened the PR prematurely, the issue was not open for contributions and is still being discussed

2022-10-12 12:17 UTC, closed without merging