Issue/43778/typescript migration
freeCodeCamp/freeCodeCamp pull request #47813
Opened 2022-10-04 03:45 UTC by DerrykBoyd

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

ref #43778

2022-10-06 15:16 UTC, ShaunSHamilton requested changes
Thank you for taking the time to contribute.

If I am not mistaken, the reason the `_concatHtml` function was created was to facilitate the TS migration of the `build.ts` file without needing to migrate `builders.js`.

However, now that the `builders.js` file is migrated, we can remove the intermediate function.

2022-10-06 15:16 UTC, ShaunSHamilton commented on client/src/templates/Challenges/utils/build.ts
>  const _concatHtml = ({
This can be deleted, and its references can be replaced with the import.

2022-10-06 16:55 UTC, ShaunSHamilton approved these changes
Thank you for making that change.

This LGTM 👍

2022-10-06 17:44 UTC, DerrykBoyd commented
> Thank you for making that change.
> 
> This LGTM 👍

No Problem!

Should we remove the `waiting update` label for this now?

2022-10-11 18:42 UTC, naomi-lgbt approved these changes
banger pr, thanks for contributing!

2022-10-11 18:42 UTC, merged