fix(curriculum): feedback on Learn Css Variables By Building A City S…
freeCodeCamp/freeCodeCamp pull request #48010
Opened 2022-10-12 17:37 UTC by nayabatir1

…kyline instruction updated

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47555

2022-10-13 09:43 UTC, Sembauke requested changes
Hey @nayabatir1,

This does not look like our style of writing, can you look up a couple of challenges and 
see if you can give it the "freeCodeCamp" style?

Have a nice day and happy coding.

2022-10-13 09:45 UTC, nayabatir1 commented
Hey @Sembauke what do you mean by fcc style?
Can you share some examples for reference

2022-10-13 15:21 UTC, ieahleen commented
Can you please use a descriptive title? the title of the issue is not a descriptive title for the PR

2022-10-13 17:11 UTC, nayabatir1 commented
@ieahleen can pls confirm, is it appropriate ?

2022-10-13 17:15 UTC, ieahleen commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98d5.md
> +1. Turn your `.bb1` element into a flexbox parent so you can center the parts of the building.<br>- hint: You should give `.bb1` a `display` of `flex`
The `hints` are what go in the next section to display when a test fail.

It seems you misinterpreted what was intended with "split in 3 different steps"

please check our documentation and look at how the project works in the curriculum.

2022-10-13 17:16 UTC, ieahleen commented
And to add to that, it was decided to not divide in three steps, but to make the stepp less 'handolding', with the wording mentioned in https://github.com/freeCodeCamp/freeCodeCamp/issues/47555#issuecomment-1275090120

2022-10-13 17:59 UTC, nayabatir1 commented
@ieahleen I've updated the pr. Do let me know if I missed anything.

2022-10-14 08:49 UTC, ieahleen requested changes
Please follow the decision in the issue, do not do random changes

2022-10-14 08:49 UTC, ieahleen commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98d5.md
> +You should give `.bb1` a `display` of `flex`.
```suggestion
You should give the `.bb1` element a `display` of `flex`.
```

2022-10-14 08:49 UTC, ieahleen commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98d5.md
> +`.bb1` should have a `flex-direction` property.<br>You should give `.bb1` a `flex-direction` of `column`
```suggestion
You should give the `.bb1` element a `flex-direction` of `column`.
```

2022-10-14 08:49 UTC, ieahleen commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98d5.md
> +Your `.bb1` should have an `align-items` property.<br>You should give `.bb1` an `align-items` property of `center`
```suggestion
You should give the `.bb1` element a `align-items` of `center`.
```

2022-10-14 09:04 UTC, nayabatir1 commented
> Please follow the decision in the issue, do not do random changes

tbh I copied the changes from here
![image](https://user-images.githubusercontent.com/91016903/195807921-1e78c0d6-a949-4a39-bda1-7d9ea71bc141.png)

2022-10-14 09:17 UTC, ieahleen commented
That was the breakdown for splitting the challenge in three different steps, as it's not what it was decided to do, you don't need to take that wording

2022-10-14 23:44 UTC, naomi-lgbt approved these changes
banger pr, thanks for contributing!

2022-10-17 17:32 UTC, raisedadead approved these changes

2022-10-17 17:32 UTC, merged