fix: only fetch growthbook in browser contexts
freeCodeCamp/freeCodeCamp pull request #48112
Opened 2022-10-18 13:07 UTC by ojeytonwilliams

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This should stop the build from failing in CD.

The reason it passed in CI is that we don't provide a growthbookUri env var, so fetch was not called during the build process.

2022-10-18 13:49 UTC, raisedadead requested changes
Wrap this in a `try catch`; the current URI that we have for the Growthbook is unstable - it can go down (it's a single instance API and not even load balanced) and doesn't have a guaranteed uptime SLA like the main API.

You can test this by using `example.com` in your local development

2022-10-18 14:34 UTC, raisedadead submitted a review, later dismissed

2022-10-18 17:04 UTC, ahmadabdolsaheb commented
Thank @ojeytonwilliams for the fix.
Here is a nitpick. fetch is being called for every change in the isSignedIn prop. 
It would be great if we could fetch once outside of the component lifecycle.

2022-10-18 18:25 UTC, ojeytonwilliams commented
@ahmadabdolsaheb thanks for the review. It made me realise we could do a little more. 

By adding the parts of `user` we're interested in to the dependency array it will update the attributes as those change.  Is that what you'd like to happen?  If you're only interested in the initial state of the user, I'll revert those changes.

2022-10-19 07:01 UTC, ahmadabdolsaheb commented
@ojeytonwilliams, That makes sense.

2022-10-19 07:01 UTC, ahmadabdolsaheb approved these changes

2022-10-19 08:13 UTC, naomi-lgbt approved these changes
Let's get this in and unblock the pipeline.

2022-10-19 08:13 UTC, merged