feat(client): link Arabic new articles to freeCodeCamp searchbar
freeCodeCamp/freeCodeCamp pull request #48129
Opened 2022-10-19 06:42 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2022-10-19 08:07 UTC, naomi-lgbt requested changes
How many articles do we have on the Arabic news instance now?

I'll cc @scissorsneedfoodtoo and @RafaelDavisH for the specific threshold, but we may want to start this pointed to the english instance?

(Edited because /news/search returns two articles apparently)

2022-10-19 08:07 UTC, naomi-lgbt commented on client/src/utils/algolia-locale-setup.ts
> +    searchPage: 'https://www.freecodecamp.org/arabic/news/search/'
```suggestion
    searchPage: 'https://www.freecodecamp.org/news/search/'
``

2022-10-20 21:32 UTC, naomi-lgbt submitted a review, later dismissed
Should be good to go.

2022-10-21 06:40 UTC, scissorsneedfoodtoo commented
Just checked on Algolia and there are currently 90 published articles in Arabic. It should be fine to set the index to `news-ar` and the search page to `https://www.freecodecamp.org/arabic/news/search/` here.

I'm not sure why visiting https://www.freecodecamp.org/arabic/news/search/ only returns two articles. The Urdu search page only returns one, rather than all articles like it should. I can look more into that.

Regarding the threshold, for News we've just been using the correct index for each publication when it launches. We generally require that there are about around 25 published articles before launching a publication. That won't lead to a whole lot of hits, but it's a decent amount for a new publication.

In the past, the threshold has only applied to the search bar placeholder. When a publication first launches we use a general label like "Search our tutorials". But when a publication hits 100+ articles, we switch over to a numbered placeholder like "Search 100+ tutorials".

2022-10-21 07:06 UTC, scissorsneedfoodtoo approved these changes
Everything LGTM 👍

2022-10-21 10:29 UTC, sidemt approved these changes
LGTM
(For future reference: Other configs related to enabling a language is in #48128 )

2022-10-21 10:30 UTC, merged