feat: add Arabic language config to all langs
freeCodeCamp/freeCodeCamp pull request #48128
Opened 2022-10-19 06:30 UTC by Sboonny

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2022-10-19 06:46 UTC, Sboonny commented on config/i18n/all-langs.ts
> +    SuperBlocks.RespWebDesign,
```suggestion
    SuperBlocks.RespWebDesignNew,

2022-10-19 06:48 UTC, Sboonny commented
the new RWD is fully released, so I don't need to change `languagesWithAuditedBetaReleases`? 🤔

2022-10-19 08:10 UTC, naomi-lgbt requested changes
Yes, if the new RWD is translated, you'll need to add it to the `languagesWithAuditedBetaReleases` to move the new RWD to the top of the map.

This is also blocked as we have not enabled the curriculum downloads for Arabic and have 0 translations in this repository.

2022-10-20 21:31 UTC, naomi-lgbt approved these changes
With the hidden lang option, this should be good to merge.

We'll need to coordinate with @raisedadead for the deployment of the new instance.

2022-10-21 10:26 UTC, sidemt approved these changes
LGTM
For future reference: algolia-locale-setup.ts is updated in PR #48129

2022-10-21 10:30 UTC, merged