fix(curriculum):  Added description texts about spaces in step 154 #48160
freeCodeCamp/freeCodeCamp pull request #48196
Opened 2022-10-22 08:37 UTC by HatimZ

2022-10-22 10:27 UTC, ieahleen requested changes
Please use the text decided in https://github.com/freeCodeCamp/freeCodeCamp/issues/48087#issuecomment-1285704305

2022-10-22 11:46 UTC, HatimZ commented
I have made the respective changes according to https://github.com/freeCodeCamp/freeCodeCamp/issues/48087#issuecomment-1285704305.

Thanks.

2022-10-22 13:28 UTC, ieahleen requested changes

2022-10-22 13:28 UTC, ieahleen commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa226207f33d3ad4c6f546.md
> +Use the `+=` operator to add ` Your [weapon] breaks.`, with a space in front of `Your`, to the end of `text.innerText`. Replace `[weapon]` with the last item in the `inventory` array using `inventory
```suggestion
Use the `+=` operator to add `Your [weapon] breaks.`, with a space in front of `Your`, to the end of `text.innerText`. Replace `[weapon]` with the last item in the `inventory` array using `inventory.pop()`, which will remove the last item in the array AND return it so it appears in your string.
```
This space can be removed, it's not going to be shown and it's going to confuse future contributors.

2022-10-22 13:28 UTC, ieahleen commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa226207f33d3ad4c6f546.md
> +You should add `Your`, with a space before and after it, to `text.innerText`. Remember that spacing matters.
```suggestion
You should add `Your`, with a space before and after it, to `text.innerText`.
```

2022-10-22 17:28 UTC, ieahleen approved these changes
LGTM 👍

2022-10-22 17:48 UTC, HatimZ commented
Thanks!

2022-10-23 08:55 UTC, Sboonny approved these changes
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @HatimZ, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2022-10-23 08:55 UTC, merged

2022-10-23 13:53 UTC, HatimZ commented
Thanks @Sboonny . Its my pleasure. Sure I will be active in the future as well. Cheers!