fix(curriculum): describe different browser behavior (Survey Form)
freeCodeCamp/freeCodeCamp pull request #48280
Opened 2022-10-27 17:46 UTC by sidemt

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Affected page: https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form

There is this user story:
> 8. If you enter non-numbers in the number input, you will see an HTML5 validation error

This is true on Firefox, but on Chrome or Edge you can't type non-number characters into a number field.
You can check this behavior with the "Age" field in the demo project: https://survey-form.freecodecamp.rocks/

2022-10-27 18:46 UTC, naomi-lgbt requested changes

2022-10-27 18:46 UTC, naomi-lgbt commented on curriculum/challenges/english/01-responsive-web-design/responsive-web-design-projects/build-a-survey-form.md
> +1. If you enter non-numbers in the number input, either an HTML5 validation error will appear or you won't be able to type them (depending on your browser)
```suggestion
1. The number input should not accept non-numbers, either by preventing you from typing them or by showing an HTML5 validation error (depending on your browser).
```

Possibly clearer? Not sure.

2022-10-28 17:53 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/build-a-survey-form-project/build-a-survey-form.md
> +1. If you enter non-numbers in the number input, either an HTML5 validation error will appear or you won't be able to type them (depending on your browser)
```suggestion
1. The number input should not accept non-numbers, either by preventing you from typing them or by showing an HTML5 validation error (depending on your browser).
```
Should have made both suggestions at once - sorry.

2022-10-28 18:31 UTC, naomi-lgbt approved these changes

2022-10-29 15:08 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2022-10-29 17:25 UTC, merged