feat: add type to warn miss usage of attributes in formControl
freeCodeCamp/freeCodeCamp pull request #48696
Opened 2022-12-09 11:47 UTC by Sboonny

Co-authored-by: Oliver Eyton-Williams <ojeytonwilliams@gmail.com>

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

While using FormControl as component, I have added `value` attribute to the component, which leads to this error in the console

![image](https://user-images.githubusercontent.com/88248797/200156248-d4b6662d-917f-42af-a6b0-8c7df685220f.png)

With Ahmad and Oliver help, you can use FormControl, add the attribute and get warned for the need for the other attributes. 

I opened a new PR to reduce the scale of the FormGroup PR.

2022-12-19 15:15 UTC, raisedadead commented
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

2023-01-05 09:03 UTC, Sembauke requested changes
This is a somewhat more simplified version that also should work for the union types:
```ts
type Values = {
  value: string;
  onChange?: (event: React.ChangeEvent<FormControlElement>) => void;
  readOnly?: boolean;
} | {
  value?: never;
  onChange?: never;
  readOnly?: never;
}
```

2023-01-05 09:18 UTC, Sboonny commented
removed `undefined` from `onChange` and `readonly`, then added conditional typing to have the error back.

![image](https://user-images.githubusercontent.com/88248797/210744181-0aba3299-9d3a-49d2-856f-8e9be8d0aa14.png)
![image](https://user-images.githubusercontent.com/88248797/210744279-e7e5224b-6b54-4347-a160-6589d3926b6f.png)
![image](https://user-images.githubusercontent.com/88248797/210744397-e9445880-4b97-422a-9b41-155ae0ebb204.png)

2023-01-05 09:36 UTC, Sboonny commented
Here is context, I should have added:

The browser doesn't like it when we us use `value` without including `onChange` or `readonly` attributes to the `FormControl`, but TypeScript doesn't warn us about this.

This aims to add types that warn us about the missing `onChange` or `readonly` when using the `value` attribute, in the editor.

2023-01-17 12:26 UTC, ahmadabdolsaheb commented
We just need to make sure that both onChange and readOnly cannot be passed when there is a value.

2023-01-27 08:39 UTC, ahmadabdolsaheb approved these changes
Great job here. Just a tiny nitpick.

2023-01-27 08:39 UTC, ahmadabdolsaheb commented on tools/ui-components/src/form-control/types.ts
> +      readonly: never;
```suggestion
      readonly?: never;
```

2023-02-10 13:24 UTC, Sembauke approved these changes

2023-02-10 14:30 UTC, merged