fix(curriculum): updated seed text in cat photo app
freeCodeCamp/freeCodeCamp pull request #48720
Opened 2022-12-11 05:06 UTC by nayabatir1

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #47854

2022-12-11 06:07 UTC, Sboonny reviewed
Unfortunately, you need to change the files with the seed code of `<p>Click here to view more <a target="_blank" href="https://freecatphotoapp.com">cat photos</a>.</p>` and a like, as well.

2022-12-11 06:45 UTC, Sboonny commented
https://github.com/nayabatir1/freeCodeCamp/blob/f8fcbda51ec175e0e8bbfef4a34b9c491403e0db/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/62dabe2ef403a12d5d295273.md#L35-L42?plain=1

This should sort it, and hopefully pleases the curriculum test. Didn't test it yet tho

> <p>See more <a target="_blank" href="https://freecatphotoapp.com">cat photos</a> in our gallery.</p>

2022-12-11 12:19 UTC, Sboonny requested changes
there are two seed code left, one in step 14 https://github.com/nayabatir1/freeCodeCamp/blob/f8fcbda51ec175e0e8bbfef4a34b9c491403e0db/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa2407b521be39a3de7be1.md#L48?plain=1

The second which making the test fails is in step 13 https://github.com/nayabatir1/freeCodeCamp/blob/f8fcbda51ec175e0e8bbfef4a34b9c491403e0db/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/62dabe2ef403a12d5d295273.md#L77

----

About the deleted spacing, they were added as a support for beginners, deleting them is add an issue to the code seed again

2022-12-11 12:19 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc17dc8f86c76b9248c6eb5.md
> +    <p>See more cat photos in our gallery.</p>
```suggestion

    <p>See more cat photos in our gallery.</p>
    
```

2022-12-11 12:19 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc2385ff86c76b9248c6eb7.md
> +    <p>See more cat photos in our gallery.</p>
```suggestion
    <p>See more cat photos in our gallery.</p>
    
```

2022-12-11 12:19 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc23f9bf86c76b9248c6eba.md
> +      <p>See more cat photos in our gallery.</p>
```suggestion
      <p>See more cat photos in our gallery.</p>
      
```

2022-12-11 12:19 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc24614f86c76b9248c6ebd.md
> +      <p>See more cat photos in our gallery.</p>
```suggestion
      <p>See more cat photos in our gallery.</p>
      
```

2022-12-12 19:43 UTC, jeremylt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc17dc8f86c76b9248c6eb5.md
> +
```suggestion
    
```

2022-12-19 15:15 UTC, raisedadead commented
We are officially on Node.js 18 now. We have changed the merge requirements accordingly.

You will need to rebase this PR against the main branch OR Click the "Update branch" button to get the new checks going.

Thanks for your contribution.

2022-12-31 09:38 UTC, gikf requested changes
Test in step 4 needs to be changed to conform with new text:

https://github.com/freeCodeCamp/freeCodeCamp/blob/04fcc71bc943aa7b0cf77e06c9819ea98fdbea2a/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc17dc8f86c76b9248c6eb5.md?plain=1#L50

Should be

```js
/<!--todo:addlinktocatphotos--><p>seemorecatphotosinourgallery\.?<\/p>/i
```

2022-12-31 11:54 UTC, gikf reviewed
This should be the last failing test:

https://github.com/freeCodeCamp/freeCodeCamp/blob/889eb40fcc78016a9378a65eadf0ceefb78e2b86/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc23991f86c76b9248c6eb8.md?plain=1#L75

```
    .match(/see\s+more\s+cat\s+photos\s+in\s+our\s+gallery\.?$/)
```

There's also step 15, having still the old text https://github.com/freeCodeCamp/freeCodeCamp/blob/889eb40fcc78016a9378a65eadf0ceefb78e2b86/curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dfa30b9eacea3f48c6300ad.md?plain=1#L80

2022-12-31 18:24 UTC, gikf approved these changes
LGTM :+1:

2022-12-31 18:29 UTC, Sboonny approved these changes

2022-12-31 18:30 UTC, merged

2022-12-31 18:30 UTC, Sboonny commented
Thank you for the hard work. 🥳