Update troubleshooting docs
freeCodeCamp/freeCodeCamp pull request #48863
Opened 2022-12-28 21:58 UTC by oriooctopus

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This originated from https://discord.com/channels/692816967895220344/715074489422970962/1054213219436216350 and the subsequent messages in discord.

To me this solution is overly conservative since Free Code Camp is upgrading the node version people use anyways. I think that we should just change the `sample.env` file to avoid the problem altogether. However it didn't seem like people were on board for that just yet so I think for now we're just going to have this more conservative solution and if more and more people have the issue then we can change the file

2022-12-29 06:11 UTC, Sboonny reviewed
I wanted to open an issue for this, but didn't for these reasons:

- It's related to `Issues with installing the recommended prerequisites`.
- I haven't seen the error (and to be fair, I didn't ask for it too), so I don't know how common this is or is it related to a specific device, as the camper mentioned they are using a Mac.
- The issue maybe from MongoDB itself, and it should be reported in https://jira.mongodb.org/browse/WT-10442?jql=
- The developers who deal with database are on holiday.

In hindsight, I should have opened the issue and let the others decide 😓

2022-12-29 06:11 UTC, Sboonny commented on docs/troubleshooting-development-issues.md
> +
Can you move this to `Issues with installing the recommended prerequisites` section, maybe line 14 🤔, and apply this suggestion? If you see it fitting.

```suggestion
#### Can't access the database with newer node versions

In your env file, change the value of `MONGOHQ_URL` to `mongodb://127.0.0.1:27017/freecodecamp`.

```

2023-01-01 23:03 UTC, oriooctopus commented
Thanks for the comments! I incorporated all of them except for changing the message itself. I used some of your wording and kept some of my own

2023-01-02 17:33 UTC, raisedadead requested changes
Other than the cosmetic change, I am not in favor of adding this. Instead, the user should look up troubleshooting help on StackOverflow and elsewhere.

@freeCodeCamp/dev-team and @freeCodeCamp/moderators 

The troubleshooting section should be highly opinionated because things in the dev world change rapidly. We should not be gathering field notes for all hiccups and scenarios.

We essentially have two setups — a one-click "no-frills" setup with GitPod and a more traditional "get-your-hands-dirty" setup.

IMHO, it's OK to diagnose and send users to StackOverflow and other resources for "generic" issues such as this example.

This particular example is separate from how freeCodeCamp needs to be set up.

2023-01-02 17:33 UTC, raisedadead commented on docs/troubleshooting-development-issues.md
> +
```suggestion

```

The whole project setup guide/documentation is a "disclaimer", that is there are no guarantees. We do not need legal-speak here.

2023-01-02 18:13 UTC, Sboonny commented
I regret not opening an issue 😅.

> I think that we should just change the `sample.env` file to avoid the problem altogether.

2023-01-03 11:34 UTC, ojeytonwilliams commented
> We could change sample.env to mongodb://127.0.0.1:27017/freecodecamp.

We could, but has anyone been able to replicate the error? localhost works just fine for me on node 16, 17 and 18

Also, I agree with Mrugesh that we can't document every special case.  Particularly not when it's nothing to do with us beyond the fact we use Mongodb (and issues with Mongodb are easily Googled).

2023-01-03 12:59 UTC, raisedadead commented
Closing as discussed.

2023-01-03 12:59 UTC, closed without merging