feat(docs): add authors analytics manual
freeCodeCamp/freeCodeCamp pull request #48901
Opened 2023-01-03 10:40 UTC by ahmadabdolsaheb

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-01-03 10:51 UTC, Sembauke requested changes

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +Authors who have access to the publication's Google Analytics Property (News) can use the following guide to view their articles' engagement and search articles' analytics by publication language.
```suggestion
The following manual is for authors who have access to the Google Analytics Property (News) for their publication. It explains how to view their articles' engagement data and search for analytics by publication language.
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +1. Choose `News` from the top dropdown menu.
```suggestion
1. From the top dropdown menu, select `News`.
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +1. Click on `Reports` from the sidebar.
```suggestion
1. From the sidebar, click on Reports.
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +1. Select `Engagement` from the secondary sidebar.
```suggestion
1. From the secondary sidebar, select `Engagement`.
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +1. Choose `Page path and screen class` from the dropdown under the search bar.
```suggestion
1.  From the dropdown under the search bar, choose `Page path and screen class`.
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +### Search  language
```suggestion
### Search by Language
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +1. Choose an author name from the `Dimensions values` dropdown.
```suggestion
1. From the `Dimensions values` dropdown, choose an author's name.
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +### Filter reports by Author
```suggestion
### Filter Reports by Author
```

2023-01-03 10:51 UTC, Sembauke commented on docs/authors-analytics-manual.md
> +Use the following steps in order to search the engagement reports by a publication language:
```suggestion
To search for engagement reports by a specific language:
```

2023-01-03 11:08 UTC, ahmadabdolsaheb commented on docs/authors-analytics-manual.md
> +Authors who have access to the publication's Google Analytics Property (News) can use the following guide to view their articles' engagement and search articles' analytics by publication language.
```suggestion
If you are an author with access to the publication's Google Analytics Property (News), you can use this guide to view your articles engagement and search for articles by publication language."
```

2023-01-03 11:12 UTC, Sembauke approved these changes

2023-01-03 13:22 UTC, Sboonny reviewed
Typo and wrong header syntax.

2023-01-03 13:22 UTC, Sboonny commented on docs/authors-analytics-manual.md
> +If you are an author with access to the publication's Google Analytics Property (News), you can use this guide to view your articles engagement and search for articles by publication language."
```suggestion
If you are an author with access to the publication's Google Analytics Property (News), you can use this guide to view your articles engagement and search for articles by publication language.
```

2023-01-03 13:22 UTC, Sboonny commented on docs/authors-analytics-manual.md
> +
```suggestion
```

2023-01-03 13:22 UTC, Sboonny commented on docs/authors-analytics-manual.md
> +### Search by Language
```suggestion
## Search by Language
```

2023-01-06 09:36 UTC, ahmadabdolsaheb commented on docs/authors-analytics-manual.md
> +### Filter Reports by Author
```suggestion
## Filter Reports by Author
```

2023-01-06 09:39 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2023-01-06 09:56 UTC, merged