Corrected documentation for running single Cypress test
freeCodeCamp/freeCodeCamp pull request #48932
Opened 2023-01-05 08:37 UTC by AnshPhirani

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48917

2023-01-05 15:06 UTC, raisedadead submitted a review, later dismissed
Looks good. Could you:

- Update the PR title (use the edit button), more info here: https://contribute.freecodecamp.org/#/how-to-open-a-pull-request
  
  For example:
  ```
  docs: update command for running a single cypress test
  ```

  No need to change the commit message; that's fine.


- Add an example of a real test as a sample.

  For example, right below the command, you can add something like:
  ```
  npm run cypress -- run --spec=cypress/e2e/default/landing.js
  ```

Thanks.

2023-01-05 18:44 UTC, naomi-lgbt requested changes

2023-01-05 18:44 UTC, naomi-lgbt commented on docs/how-to-add-cypress-tests.md
> +  npm run cypress -- run --spec=cypress/e2e/default/landing.js
````suggestion
  npm run cypress -- run --spec=cypress/<path_to_test_file>
  ```
  
  For example:
 
  ```console
  npm run cypress -- run --spec=cypress/e2e/default/landing.js
  ```
````

2023-01-05 18:54 UTC, naomi-lgbt approved these changes

2023-01-06 01:18 UTC, moT01 approved these changes
LGTM @AnshPhirani 🎉 Thanks for contributing to freeCodeCamp 🎉

2023-01-06 01:18 UTC, merged