Feat: Convert 8 more Cypress files to Typescript
freeCodeCamp/freeCodeCamp pull request #49001
Opened 2023-01-12 01:10 UTC by a2937

Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

 I am going to convert the tests that I know work on my machine. I'm going to try to handle more advanced tests that involve the server components in my next batch hopefully.

2023-01-12 05:06 UTC, raisedadead requested changes
Thanks for the PR, could you rename the files to use `kebab-case`

2023-01-12 16:05 UTC, a2937 commented
Okie dokie. Everything should be in order now.

2023-01-13 05:48 UTC, raisedadead approved these changes

2023-01-13 05:53 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2023-01-13 05:53 UTC, merged