fix(docs): button padding in mobile device (#48848)
freeCodeCamp/freeCodeCamp pull request #49014
Opened 2023-01-13 13:50 UTC by Ankitchaudharyy

Checklist:
- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48848 

Added left and right padding as 0 (which overwrites `section.cover .cover-main > p:last-child a` from `vue.css:558`) in the buttton for mobile layout.

![Uploading Screenshot 2023-01-13 at 7.18.57 PM.png…]()

2023-01-13 15:38 UTC, Sboonny requested changes
Margin needs to be removed too, for 320px width layout

![image](https://user-images.githubusercontent.com/88248797/212357658-da956eab-792b-47e3-836d-ec38226379b4.png)

---

between 445px-450px the layout breaks.

![image](https://user-images.githubusercontent.com/88248797/212359158-b72d79cd-d6b1-422e-ab25-f4e1f0a44af5.png)

Here is a suggestion


```css
@media (max-width: 400px) {
section.cover .cover-main > p:last-child a:last-child {
  padding-left: 0;
  padding-right: 0;
  margin-right: 0;
  margin-left: 0;
 }
}
```

2023-01-13 15:43 UTC, Sboonny commented
Beside the changes, the test is failing because the file isn't format, quick references in contribution guide should show you commands to fix this.

2023-01-13 18:07 UTC, Ankitchaudharyy commented
> Beside the changes, the test is failing because the file isn't formatted, quick references in contribution guide should show you commands to fix this.

@Sboonny I went through the contribution guide, but didn't find one. Please provide me the link or any help.

2023-01-13 18:39 UTC, Ankitchaudharyy commented
No worries.
Thank you.

2023-01-13 19:00 UTC, Sboonny approved these changes
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Ankitchaudharyy, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2023-01-17 10:18 UTC, Nirajn2311 approved these changes

2023-01-17 10:18 UTC, merged