feat(client): add ES GTM id
freeCodeCamp/freeCodeCamp pull request #49057
Opened 2023-01-18 11:22 UTC by ahmadabdolsaheb

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-01-18 16:57 UTC, ojeytonwilliams requested changes

2023-01-18 16:57 UTC, ojeytonwilliams commented on client/src/analytics/index.ts
> +const gtmId = analyticsIDSelecor();
```suggestion
const analyticsIDSelector = () => {
  if (deploymentEnv === 'staging') return devAnalyticsId;
  else if (clientLocale === 'espanol') return prodAnalyticsESId;
  else return prodAnalyticsId;
};

const gtmId = analyticsIDSelector();
```
Nit

2023-01-19 09:45 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2023-01-19 11:17 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2023-01-19 11:17 UTC, merged