fix(client): cert project help post sans editable region
freeCodeCamp/freeCodeCamp pull request #49157
Opened 2023-01-26 19:59 UTC by ShaunSHamilton

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49141 

Seems like something Naomi did - forgot optional chaining

2023-01-27 13:35 UTC, ojeytonwilliams requested changes

2023-01-27 13:35 UTC, ojeytonwilliams commented on client/src/templates/Challenges/redux/create-question-epic.test.js
> +        editableRegionBoundaries: [],
```suggestion
```
The original error was caused by this being absent, so it makes sense to test for that.

2023-01-27 13:35 UTC, ojeytonwilliams commented on client/src/templates/Challenges/redux/create-question-epic.test.js
> +        editableRegionBoundaries: [],
```suggestion
```

2023-01-27 13:35 UTC, ojeytonwilliams commented on client/src/templates/Challenges/redux/create-question-epic.test.js
> +    });
```suggestion
    });
    it('should not throw if editableRegionBoundaries is undefined', () => {
      expect(() =>
        insertEditableRegions(multiCertChallengeFiles)
      ).not.toThrow();
    });
```

2023-01-27 13:49 UTC, ShaunSHamilton commented
@ojeytonwilliams Actually, I am just wondering. I grabbed those values from GraphQL (Gatsby). So, the `editableRegions` property should exist, it should just be an empty array?

2023-01-27 15:04 UTC, ojeytonwilliams commented
It starts off as one, but gets overwritten 

https://github.com/freeCodeCamp/freeCodeCamp/blob/0b6ba2cf736b8fdfd055bf64ab1ce7b9c93862c3/client/src/templates/Challenges/classic/editor.tsx#L816-L822

It seems fine to me to set it to `[]` rather than `undefined`.  Might as well keep the tests and `?`, though.

2023-02-02 16:08 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2023-02-02 17:46 UTC, moT01 approved these changes

2023-02-02 17:46 UTC, merged