fix: trust private network proxies
freeCodeCamp/freeCodeCamp pull request #49209
Opened 2023-01-31 10:56 UTC by ojeytonwilliams

If the downstream is inside a private network, the api will assume that
client is the first ip it doesn't recognise as being part of the
network.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This makes `req.ip` return the 'real ip', i.e. the address of the requesting client.  As such, express-rate-limit's [default keygen](https://github.com/express-rate-limit/express-rate-limit#keygenerator) will work.

Closes https://github.com/freeCodeCamp/freeCodeCamp/pull/49194

2023-01-31 15:14 UTC, raisedadead commented
What if we want to use something other than the default keygen? What if we want to change to a custom strategy because we can't use IP addresses at all?

2023-01-31 15:15 UTC, raisedadead requested changes
What if we want to use something other than the default keygen? What if we want to change to a custom strategy because we can't use IP addresses at all?


The key is to decide what our goals are (I wrote in detail about this in our DM):

Our intention with the code is to get a unique string for the user that can be used as a seed for the key generator helper from the middleware we are using. It could be an email; it could be an IP address; It could be their grandmother's name.

The default happens to be IP addresses. 

This could change quickly according to our needs so that we could use an email address depending on the behavior. 

We may want to use the customization we want, and there is a way to do that (which I have implemented in [#49194](https://github.com/freeCodeCamp/freeCodeCamp/pull/49194) - More crucially, the blast radius is limited by the endpoint that used the middleware – in this case, the mobile auth.

This change in your PR increases the blast radius of the whole API – a risk we are unwilling to take just because. 

Put the changes in [#49149](https://github.com/freeCodeCamp/freeCodeCamp/pull/49194) are better because they limit the scope and do not tie the API logic to who sits in front of it.

Today it's NGINX; tomorrow, it will be Consul; the next day, something else. The idea is to make every component as independent as possible. Relying on default means when we architect infra, we have to be cognizant the IP address that code depends on is set in a certain way.

2023-01-31 17:32 UTC, ojeytonwilliams commented
I see what you're saying, but getting the client IP from the rightmost (non-trusted) IP in `x-forwarded-for` is the defacto standard. We can deviate from that standard, but doing so increases the chance that we introduce a vulnerability.

The problem with using all of `x-forwarded-for` as a key is that we now have to overwrite it before it reaches the api and remember to keep rewriting it whenever we change the infrastructure. Failing to do so could introduce subtle vulnerabilities.  In contrast, if we use the rightmost IP then those same infra changes are more likely to cause an outage (i.e. we accidentally rate-limit a load-balancer or similar) than create a vulnerability. An outage is bad, of course, but we'd immediately know about it, unlike a vulnerability.

I can go into more details on the specifics, if you like. Also, I highly recommend having a skim of https://adam-p.ca/blog/2022/03/x-forwarded-for/ It is quite excellent (and the first paragraph summarizes it well).

2023-01-31 17:49 UTC, raisedadead commented
> The problem with using all of x-forwarded-for as a key is that we now have to overwrite it before it reaches...

Precisely what we should be doing for any header that is supposed to be used server side. This is like SecOps 101 because if you are not trusting the value, it might as well have been spoofed. So the key needs to be overwritten from a trusted source (not revealing it here for reasons of security, but you know the header we can use to overite the x-forwarder-for).

Long story short, follow standards or not – it all goes out the window if you do not follow common sense.

2023-01-31 18:47 UTC, ojeytonwilliams commented
> That is precisely what we should be doing for any header that is supposed to be used server side. This is like SecOps 101 because if you are not trusting the value, it might as well have been spoofed.

The safe way to figure that out is the following. Only trust the parts of `x-forwarded-for` that either come from a trusted source or that we set ourselves. It's the fact that we do trust these proxies that allows us to use the first IP we do not recognize, because that must be the one we want. That's exactly what NGINX does (right now) whenever it receives a request.

> So the key needs to be overwritten from a trusted source (not revealing it here for security reasons, but you know the header we can use to overwrite the x-forwarder-for)

It's is fair to say that we should not trust _all_ the IPs in `x-forwarded-for`, because the ones on the left can be spoofed. However, I'm not suggesting we do that. Also, to reiterate, it's not necessary to overwrite the key because the bits we care about have been set by a trusted source.

It's tricky to go deeper without talking about the details of our infra. If you're still not convinced, let's discuss this on a call.

2023-02-01 05:59 UTC, raisedadead commented
> because the bits we care about have been set by a trusted source.

That is NOT true. I want to avoid getting into the discussion of why.

Anyways,

I understand what you are saying, but you are getting ahead of yourself here.

The discussion is NOT about trusted proxies, or best practices, or any of that. You need to include the point that we may not (or probably can't) depend on IP addresses, which makes this discussion moot and a waste of time.

I am explicitly saying that IP addresses are just one of the Signals, and we may need more (like email addresses or some other criteria), which dictates the use of a custom keygen handler.

With #49194, we are picking up the value from a header WE KNOW can't be spoofed and setting it to `X-FORWARDER-FOR` "as a standard" without increasing the blast radius beyond the endpoint and the middleware.

That is not the case with this PR, hence this can be closed.

2023-02-01 09:56 UTC, ojeytonwilliams commented
> > because the bits we care about have been set by a trusted source.
>
> That is NOT true. I want to avoid getting into the discussion of why.

It has to be true. We should discuss this privately, though, due to the security implications.

> I am explicitly saying that IP addresses are just one of the Signals, and we may need more (like email addresses or some other criteria), which dictates the use of a custom keygen handler.

I understand that, but neither PR uses any signals beyond client IP, so let's discuss that when we use them.

2023-02-01 14:12 UTC, raisedadead commented
> We should discuss this privately, though, due to the security implications.

Sure, We should when we have more time to discuss general knowledge share and stuff. Maybe in the de-team meetings. :)

> I understand that, but neither PR uses any signals beyond client IP, so let's discuss that when we use them.

Correct.

#49194 starts the groundwork with the custom handler that, yes, uses an IP address right now but may be expanded or completely refactored with minor impact later if needed. This PR has zero scope for such a change. 

So, what do you mean here?

2023-02-01 15:21 UTC, ojeytonwilliams commented
Yep, we can discuss in the meeting or before if you'd like to move forward before then.

I didn't add it here because `req.ip` is what `keyGenerator` returns by default.

i.e. I could have done

```ts
    keyGenerator: req => {
      return req.ip;
    },
```

but it already does that. If you'd rather it's explicit, that's fine by me.

2023-02-01 17:07 UTC, raisedadead commented
I see you continue to keep missing these points:

1. We need the custom handler (for reasons I have mentioned already) – it doesn't matter if it is explicit or implicit because we can't rely on `req.ip` only. Period.
2. This PR adds a change that affects the whole of API, whereas #49194 does not.

It is mu humble opinion that we can move on (without needing to discuss the trusted proxies feature) because the above points are what we need.

2023-02-01 17:58 UTC, ojeytonwilliams commented
It's clear we will need a custom keygen in the long term. I never said otherwise. This is not the long term. As I keep saying, we don't need it yet, because the default does what the custom one would do. They are (in the short term) identical.

It's really not a big deal, but that's what it is.

It's also clear this can affect more than just the mobile auth, but that's an argument for careful QA, not for abandoning the approach.

> It is my humble opinion that we can move on (without needing to discuss the trusted proxies feature) because the above points are what we need.

Unfortunately not, because the keygen is contingent on how the IP arrives at the api. The latter is what we need to discuss privately.

2023-02-02 08:38 UTC, raisedadead commented
> but that's an argument for careful QA

Sure. 

I am happy to sit on this for weeks and months as long as @Sembauke and @Nirajn2311 are fine with the extended delays – there is no way it is getting past me with a quick QA because it affects my daily tasks.

If you can guarantee that the change is NOT going to affect remotely with a proper report of all the endpoints that are in the play and what effects it has I am happy to move forward.

> The latter is what we need to discuss privately.

The discussion is pertinent to using just the IP address. I am saying we need more. You are jumping into the implementation.

We can discuss the needing more (additional signals) bit here – I have laid out my points here.

2023-02-02 10:08 UTC, ojeytonwilliams commented
Let's continue this discussion after we've talked about the security considerations in private. There's nothing to be gained by talking here until we've done that.

2023-02-02 10:38 UTC, Nirajn2311 commented
> I am happy to sit on this for weeks and months as long as @Sembauke and @Nirajn2311 are fine with the extended delays – there is no way it is getting past me with a quick QA because it affects my daily tasks.

we were hoping to get this out by the end of this month

2023-02-02 11:27 UTC, raisedadead commented
> Let's continue this discussion after we've talked about the security considerations in private.

The considerations only matter if we use IP addresses "only", since we may not there is no point discussing.

2023-02-03 10:38 UTC, ojeytonwilliams commented
After a bit more thought, I realised I was wrong about the parts of XFF we can trust. Nothing changes about what we should do upstream (i.e. this PR), but we have to be very careful about the XFF we send to the api.

Sorry about that @raisedadead, I'll explain what I misunderstood in the call today.

2023-02-03 17:03 UTC, ojeytonwilliams commented
Having weighed up the pros and cons, we decided to go with https://github.com/freeCodeCamp/freeCodeCamp/pull/49194 i.e. an XFF header that we're overwriting.

For posterity.
- the pro of this PR are that the api is less likely to become vulnerable to XFF spoofing when the infrastructure changes
- the con is that we have to remember and account for the api's XFF handling when we change infrastructure

Ultimately, since both approaches introduce coupling between the api and the infra and both require caution when making changes, there was not a perfect choice, but we had to choose one.

2023-02-03 17:03 UTC, closed without merging