fix(curriculum): removed unnecessary z-index
freeCodeCamp/freeCodeCamp pull request #49200
Opened 2023-01-30 11:25 UTC by leslieyip02

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #48874 

I removed `z-index` from `#years` from step 42 onwards.

2023-01-30 14:28 UTC, Sboonny reviewed
I didn't mention removing it from the solution too, sorry about that 

Here is the file https://github.com/leslieyip02/freeCodeCamp/blob/67436e6c9b78b77cabf5b534214f2e09fd84110c/curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/6201a59be346d399c21d10b1.md#L493

----

It shouldn't affect anything keeping it, but the files will cleaner without it.

2023-01-30 16:15 UTC, Sboonny reviewed
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @leslieyip02, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2023-01-30 16:15 UTC, Sboonny approved these changes

2023-01-30 18:48 UTC, bbsmooth commented
Are we sure we don't need this? The years heading is using fixed positioning. When I remove `z-index` then the table content overlaps the heading.

2023-01-31 10:43 UTC, leslieyip02 commented
I've modified the CSS for the solution to prevent the table from overlapping with the headers. Could someone check if these changes are ok before I modify the rest of the files?

2023-03-07 17:09 UTC, Sboonny commented
Thank you for the hard work @leslieyip02, I have pushed a commit of the requested change because you shouldn't do more for mistake on our part, we should have done our due diligence.

2023-03-15 18:46 UTC, ShaunSHamilton requested changes

2023-03-15 18:46 UTC, ShaunSHamilton commented on curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/64076bbeba941114b0027b6a.md
> +Adding position `sticky` moved the element into its own stack, to ensure your `#years` don't get hidden by different stacks add `z-index` property set to `999` in `#years` CSS rule.
```suggestion
Adding position `sticky` moved the element into its own stack. To ensure your `#years` element does not get hidden by different stacks, add a `z-index` property set to `999` in the `#years` rule.
```

2023-03-15 18:46 UTC, ShaunSHamilton commented on curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/64076bbeba941114b0027b6a.md
> +assert(new __helpers.CSSHelp(document).getStyle('#years')?.getPropertyValue('z-index') === '999');
```suggestion
assert.equal(new __helpers.CSSHelp(document).getStyle('#years')?.getPropertyValue('z-index'), '999');
```

2023-03-16 12:07 UTC, ShaunSHamilton approved these changes
This looks good to me 👍

2023-03-16 12:09 UTC, merged