refactor(client): move to uiw react codemirror for challenge editor
freeCodeCamp/freeCodeCamp pull request #49323
Opened 2023-02-10 10:35 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2023-02-10 10:36 UTC, Sboonny commented on tools/challenge-editor/client/src/components/editor/editor.tsx
> +    setInput(change.text.join(' '));
Currently, with this logic, it looks like this, but works

![image](https://user-images.githubusercontent.com/88248797/218070565-d4e6c2aa-5e2c-4e7e-8af0-76ad3b057aa7.png)

Without it, looks like this but doesn't

[rec-tab.webm](https://user-images.githubusercontent.com/88248797/218070699-78ba7e07-8c21-485f-adc2-5d7a35c61f38.webm)

2023-02-10 10:39 UTC, Sboonny commented on tools/challenge-editor/client/src/components/editor/editor.tsx
> +    setInput(change.text.join(' '));
Oh it doesn't show the message, but the message say the change did happen, but the change doesn't happen.

And the old logic I mean 

```ts
 const handleChange = (
    editor: codemirror.Editor,
    data: codemirror.EditorChange,
    value: string
  ) => {
    setInput(value);
```

2023-02-10 10:46 UTC, Sboonny commented on tools/challenge-editor/client/package.json
> +    "@uiw/react-codemirror": "3.2.7",
higher than this will need codemirror 6

2023-02-10 17:03 UTC, Sboonny commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-transforms-by-building-a-penguin/619bcf239fc15905ecd66fce.md
```suggestion
# --description--

```

2023-02-10 17:07 UTC, Sboonny commented
`setInput(change.text.join('\n'));` does show the intended look, but it's buggy because it set the value to the `keydown` value, aka if you type `S` then input will set to `S`, and you can't really change the editor

2023-02-10 17:13 UTC, Sboonny commented on tools/challenge-editor/client/src/components/editor/editor.tsx
> +  const [input, setInput] = useState('hello');
```suggestion
  const [input, setInput] = useState('');
```

2023-04-04 08:15 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2023-04-05 17:15 UTC, naomi-lgbt commented
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/63889819/230155100-1193118d-b69e-419b-a37b-a0c1bfdff38d.png">

I get this error when trying to run the editor.

2023-04-05 17:56 UTC, Sboonny commented
Failure to complie is weird, the eslint errors are from the main repo and should be dismissible, I will look at it in the  morning.

2023-04-05 19:25 UTC, Sboonny commented
Yeab, this issue should exist in the main repo too, although I didn't test the main repo, I remember Kolade reporting it before he tested this PR. 🤔 


[rec-tab.webm](https://user-images.githubusercontent.com/88248797/230183703-d7ee44cf-f47e-4f27-9fa0-8bc8044aae28.webm)


The error is dismissible and you can interact with the app without issue. 👍

2023-04-07 03:58 UTC, naomi-lgbt commented
Will circle back and review in the morning 💜

2023-04-07 15:32 UTC, naomi-lgbt requested changes
<img width="1869" alt="image" src="https://user-images.githubusercontent.com/63889819/230635495-1f797297-5b43-42da-ac7f-8efcfdd06fb5.png">

We'll need to update the [CSS rule](https://github.com/freeCodeCamp/freeCodeCamp/blob/d23ff47967959f552af5185986239b685e689258/tools/challenge-editor/client/src/components/editor/editor.css#L9) to use the `CodeMirror` class instead.

The original look: 

![image](https://user-images.githubusercontent.com/88248797/230651415-5ea5986b-9e86-4037-baaa-1a22e58bdec1.png)

2023-04-07 17:35 UTC, Sboonny commented on tools/challenge-editor/client/src/components/editor/editor.css
> +  /* need to add important to overwrite the specifity of the classes in the repo */
```suggestion
  /* need to add important to overwrite the specifity of the classes in the dependecy */
```

2023-04-07 18:52 UTC, naomi-lgbt approved these changes
Okie dokie, looks good to me!

2023-04-07 19:19 UTC, merged