fix(bug) : Added reset & help button texts
freeCodeCamp/freeCodeCamp pull request #49336
Opened 2023-02-10 18:16 UTC by Vansh-Baghel

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49297

* Added reset and help text in the buttons.
* Button looks like this as discussed [here](https://forum.freecodecamp.org/t/new-help-button-not-obvious/571552/6): 
![free5](https://user-images.githubusercontent.com/103327712/218166022-c5306890-d784-4e38-8863-aa0dc9d815a9.png)

2023-02-10 18:45 UTC, Sboonny requested changes
About the pr name, the scope is the place where the change is implemented.

---

bbsmooth mentioned removing the aria-labels, to not annoy the screen reader.

Buttons center the text inside of them, you don't need the styling

lasjorg mentioned the need to respect the ability to translate, you can do so by using `t` function mentioned in the suggestion

2023-02-10 18:45 UTC, Sboonny commented on client/src/templates/Challenges/classic/lower-jaw.tsx
> +            style={{display: 'flex' , justifyContent: 'center' , alignItems : 'center'}}
```suggestion
```

2023-02-10 18:45 UTC, Sboonny commented on client/src/templates/Challenges/classic/lower-jaw.tsx
> +            <div style={{paddingLeft: '.3rem'}}>Reset</div>
```suggestion
           {t('buttons.reset-step')}
```

2023-02-10 18:45 UTC, Sboonny commented on client/src/templates/Challenges/classic/lower-jaw.tsx
> +            style={{display: 'flex' , justifyContent: 'center' , alignItems : 'center'}}
```suggestion
```

2023-02-10 18:45 UTC, Sboonny commented on client/src/templates/Challenges/classic/lower-jaw.tsx
>                aria-label={t('buttons.get-help')}
```suggestion
```

2023-02-10 18:45 UTC, Sboonny commented on client/src/templates/Challenges/classic/lower-jaw.tsx
> +            <div style={{paddingLeft: '.3rem'}}>Help</div>
```suggestion
          {t('buttons.get-help')}
```

2023-02-10 18:45 UTC, Sboonny commented on client/src/templates/Challenges/classic/lower-jaw.tsx
>              aria-label={t('buttons.reset-step')}
```suggestion
```

2023-02-11 07:47 UTC, Vansh-Baghel commented
Reset Button : 
```HTML
          <button
            className='btn fade-in'
            title={t('buttons.reset-step')}
            data-cy='reset-code-button'
            onClick={openResetModal}
          >
            <Reset />
            {t('buttons.reset-step')}
          </button>
```
Help Button:
```HTML
            <button
              className='btn fade-in'
              id='get-help-button'
              title={t('buttons.get-help')}
              data-cy='get-help-button'
              onClick={openHelpModal}
            >
              <Help />
             {t('buttons.get-help')}
            </button>
```
Is it good now?

2023-02-11 07:56 UTC, Sboonny commented
we should wait for Ahmad insights on the issue

2023-02-11 22:21 UTC, bbsmooth commented
Maybe it's just me, but I as still seeing the `aria-label` attribute on both of these buttons. Since we are now adding text to the buttons the `aria-label` needs to be removed.

2023-02-11 22:39 UTC, Sboonny commented
nope, they resolved the conversation, and haven't pushed the requested changes yet. I think, they are waiting on Ahmad feedback in the issue.

2023-03-07 15:56 UTC, closed without merging