fix: optional video ids the odin project
freeCodeCamp/freeCodeCamp pull request #49380
Opened 2023-02-14 09:35 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-02-18 06:21 UTC, naomi-lgbt approved these changes

2023-02-21 09:50 UTC, Nirajn2311 requested changes

2023-02-21 09:50 UTC, Nirajn2311 commented on client/src/templates/Challenges/odin/Show.tsx
> +                  <Spacer />
This `Spacer` needs to come before the video.
```suggestion
                  <Spacer />
                  <div className='video-wrapper'>
                    {!this.state.videoIsLoaded ? (
                      <div className='video-placeholder-loader'>
                        <Loader />
                      </div>
                    ) : null}
                    <VideoPlayer
                      bilibiliIds={bilibiliIds}
                      onVideoLoad={this.onVideoLoad}
                      title={title}
                      videoId={videoId}
                      videoIsLoaded={this.state.videoIsLoaded}
                      videoLocaleIds={videoLocaleIds}
                    />
                  </div>
```

2023-02-21 09:53 UTC, Nirajn2311 approved these changes

2023-02-21 10:13 UTC, merged