feat(client): change setting alert messages to more descriptive messages
freeCodeCamp/freeCodeCamp pull request #49396
Opened 2023-02-16 10:47 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The alert don't give a descriptive message, when campers interact with the save buttons.

Here is a better way to describe it, from Bruce comment here. https://github.com/freeCodeCamp/freeCodeCamp/pull/49216#discussion_r1103706841

> Although I do think it might help if we made those save alerts a little more specific. For example, if you save a change in the Personal Information, then instead of the alert just saying "We have updated your preferences" it might be nice if it said "We have saved your Personal Information changes".

---

Ref #49144.

2023-02-16 10:49 UTC, Sboonny commented
currently it doesn't work, and I don't know why. 🤣

2023-02-23 10:18 UTC, ojeytonwilliams requested changes
I'll take a look at the tests next, but I found a few issues (mostly with the verbiage):

2023-02-23 10:28 UTC, ojeytonwilliams commented on client/i18n/locales/english/translations.json
> +    "privacy-updated": "Your privacy setting has been updated",
```suggestion
    "username-updated": "We have updated your username to {{username}}",
    "privacy-updated": "We have updated your privacy settings",
```
This should fix the failing `username-change` tests.

2023-03-02 18:30 UTC, Sboonny commented on api-server/src/server/boot/settings.js
> +    'flash.portoflio-item-updated'
the test are working again, I think the issue was this typo

2023-03-21 08:40 UTC, raisedadead requested changes
This PR should be split into multiple parts because it introduces a breaking change. Please do the following:

- Introduce the new messages in the API side changes. 
- Wait for a deployment.
- Introduce the client-side changes using the new messages. 
- Wait for a deployment.
- Clean up the older messages, etc.

2023-03-21 08:52 UTC, Sboonny commented on api-server/src/server/boot/settings.js
> +// why is this failing? I haven't touched it.
```suggestion
```

2023-03-21 10:25 UTC, Sboonny commented
Didn't mean to request review sorry about that

2023-03-21 11:08 UTC, ojeytonwilliams commented
I think the order should be

1. expand the messages the client understands (including `updated-preferences`)
2. deploy
3. change the message the api sends
4. deploy
5. remove `updated-preferences` from client.

2023-03-21 11:15 UTC, Sboonny commented
I am keeping the PR open, if someone wanna test it fully.

Feel free to close it, when the 3 PRs are merged

2023-03-25 17:12 UTC, closed without merging