Correct RTL format in escape-sequences-in-strings.md
freeCodeCamp/freeCodeCamp pull request #49524
Opened 2023-02-26 08:57 UTC by atnakayrus

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #49515 

The *blockquote* were changed to **codeblocks** to ensure Right-to-left format

2023-02-26 10:23 UTC, gikf requested changes
Triple backticks cannot be used without specifying language. As the text is pseudocode it can be wrapped in the `<pre></pre>`.

---

As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

2023-02-26 10:23 UTC, gikf commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings.md
> +```
```suggestion
<pre>
```

2023-02-26 10:23 UTC, gikf commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/escape-sequences-in-strings.md
> +```
```suggestion
</pre>
```

2023-02-26 13:12 UTC, gikf commented
Hey @atnakayrus

Could you update the PR title to follow convention described in the contributing guidelines?

2023-02-26 15:08 UTC, atnakayrus commented
> Hey @atnakayrus
> 
> Could you update the PR title to follow convention described in the contributing guidelines?

Hey! will "Changing *quoteblocks* to *pre* to ensure left allignment in translated languages" be a good title? if not can you please suggest some title?

2023-02-26 15:15 UTC, atnakayrus commented
> Hey @atnakayrus
> 
> Could you update the PR title to follow convention described in the contributing guidelines?

Hey! can you please check if the current title fits the guidelines? if not can you please let me know what would be an appropriate title? Thanks in advance

2023-02-26 18:38 UTC, gikf approved these changes
LGTM :+1:

2023-02-27 06:09 UTC, Sboonny approved these changes
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @atnakayrus, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

2023-02-27 06:10 UTC, merged