feat(curriculum): make college algebra with python live
freeCodeCamp/freeCodeCamp pull request #49695
Opened 2023-03-13 15:31 UTC by moT01

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-03-14 12:20 UTC, Sboonny commented
there were missing dependencies issue, which is fixed in #49703, if your PR run into lint issue merge the latest branch 👍

2023-03-23 15:58 UTC, raisedadead approved these changes

2023-03-23 18:30 UTC, naomi-lgbt requested changes
Gotta please the linter gods

2023-03-23 18:30 UTC, naomi-lgbt commented on config/superblock-order.ts
> +        [SuperBlockStates.Current]: [SuperBlocks.CollegeAlgebraPy, SuperBlocks.ProjectEuler],
```suggestion
        [SuperBlockStates.Current]: [
          SuperBlocks.CollegeAlgebraPy,
          SuperBlocks.ProjectEuler
        ],
```

2023-03-23 18:30 UTC, naomi-lgbt commented on config/superblock-order.ts
> +        [SuperBlockStates.Current]: [SuperBlocks.CollegeAlgebraPy, SuperBlocks.ProjectEuler],
```suggestion
        [SuperBlockStates.Current]: [
          SuperBlocks.CollegeAlgebraPy,
          SuperBlocks.ProjectEuler
        ],
```

2023-03-23 18:30 UTC, naomi-lgbt commented on config/superblock-order.ts
> +        [SuperBlockStates.Current]: [SuperBlocks.CollegeAlgebraPy, SuperBlocks.ProjectEuler],
```suggestion
        [SuperBlockStates.Current]: [
          SuperBlocks.CollegeAlgebraPy,
          SuperBlocks.ProjectEuler
        ],
```

2023-03-23 18:48 UTC, naomi-lgbt commented
This may be out of scope for the PR, but I think this is the first live superblock with the assignment-style challenges.

Is it intentional that there is no feedback on the question when the answer is correct but the assignment is not completed?

![question](https://user-images.githubusercontent.com/63889819/227317645-8b370684-eccc-4f17-a772-9d7f4fc85d42.gif)

2023-03-23 18:50 UTC, moT01 commented on config/superblock-order.ts
> +        [SuperBlockStates.Current]: [SuperBlocks.CollegeAlgebraPy, SuperBlocks.ProjectEuler],
should be resolved

2023-03-23 18:58 UTC, naomi-lgbt approved these changes
Would be happy to get this in

2023-03-23 21:57 UTC, merged