docs: explain how to test single block/superblock
freeCodeCamp/freeCodeCamp pull request #49725
Opened 2023-03-15 15:26 UTC by ojeytonwilliams

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/49403

2023-03-15 15:50 UTC, ShaunSHamilton requested changes

2023-03-15 15:59 UTC, ojeytonwilliams commented on docs/how-to-work-on-coding-challenges.md
> +2. You can also test a block or a superblock of challenges by passing the environment variable `FCC_BLOCK` or `FCC_SUPERBLOCK` respectively. For example, on 'nix systems:
I meant unix-based systems in general, but we could just say "on Linux".

2023-03-15 16:25 UTC, Sembauke commented on docs/how-to-work-on-coding-challenges.md
> +2. You can also test a block or a superblock of challenges by passing the environment variable `FCC_BLOCK` or `FCC_SUPERBLOCK` respectively. For example, on 'nix systems:
```suggestion
2. To test a block or a superblock of challenges, you can pass the environment variables `FCC_BLOCK` or `FCC_SUPERBLOCK`, respectively. For instance, on Unix-based systems:
```

2023-04-24 09:31 UTC, Sembauke commented
@ojeytonwilliams Hey how's this going :)

2023-05-29 16:49 UTC, raisedadead commented
Hi, 

We are closing old issues/pull requests that we think are stale. If you still need help or are fixing this, please open a new issue/pull request.

Thanks for your understanding. 

Happy contributing.

2023-05-29 16:49 UTC, closed without merging