fix: disable portfolio description if over 288 characters
freeCodeCamp/freeCodeCamp pull request #49730
Opened 2023-03-16 13:20 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-03-16 13:34 UTC, raisedadead commented
Can you elaborate on the changes and the context in the OP when making a PR if you are not linking to a previous thread/issue?

Thanks.

2023-03-16 13:47 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2023-03-16 14:56 UTC, Sembauke commented
> Can you elaborate on the changes and the context in the OP when making a PR if you are not linking to a previous thread/issue?
> 
> Thanks.

I thought it would be straightforward enough when you read the title.

2023-03-16 15:24 UTC, raisedadead commented
Thanks for adding the details. 

Let's be mindful that the project is maintained and followed by people who may not be on all these meetings :)

2023-03-16 15:29 UTC, Sembauke commented
You are right.

2023-03-16 15:33 UTC, raisedadead requested changes, later dismissed
The change looks good, but where is the error message that the description can't be longer than 288? 

Also, since this is a criterion, let's make it concrete by setting a const somewhere up top in the file and avoid the magic number + a test to go along with this, so it doesn't pop-up again.

2023-03-16 15:48 UTC, Sembauke commented
> The change looks good, but where is the error message that the description can't be longer than 288?

This is already in place. Right under the textfield.

2023-03-16 16:40 UTC, moT01 commented
Update the branch to pass the "Localize" tests

2023-03-16 16:58 UTC, raisedadead commented
> This is already in place. Right under the textfield.

Perfect. Thanks for confirming.

As soon as the other nit pick and Tom's comments are addressed, this should be good to go.

2023-03-17 08:41 UTC, Sembauke commented
Hey @raisedadead 

Thanks for the requested changes, I have made the decision that putting the variable in the State interface was not a good idea (Making it a global variable in the beginning of the file), the state needs to be set before the React Component renders.  

In my opinion this is the most careful way of doing things, a.k.a. Making a function which looks for all the possible wronging that could happen set in one variable (isButtonDisabled), while allowing the other variables to be accessed.  

As for the tests, they check if it is possible to make a portfolio items, and check for the correct error handling if the input from the user is not valid in one of the textfields.

2023-03-17 08:44 UTC, Sembauke commented on client/src/components/helpers/form/block-save-button.tsx
> +  dataLabel?: string;
```suggestion
```

2023-03-17 09:08 UTC, raisedadead commented
Even better. I only wanted to avoid the magic number 288. But you seem to have found a way to refactor this, which works for me.

2023-03-17 09:09 UTC, raisedadead approved these changes

2023-03-17 11:27 UTC, merged