fix(curriculum) - clearer RecordCollection instructions
freeCodeCamp/freeCodeCamp pull request #49745
Opened 2023-03-17 19:40 UTC by jeremylt

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #49732

2023-03-17 19:41 UTC, jeremylt commented
Ideally a user should be able to understand or figure out what each function input means, but as we see on the forum, they just aren't quite equipped to do so by the time they reach this problem. These changes encapsulate the most common advice given to questions on the forum about this Challenge.

2023-03-20 18:21 UTC, Sboonny approved these changes
LGTM 🎉, thank you for your contribution to the page! 👍.

2023-03-20 19:04 UTC, RandellDawson commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-javascript/record-collection.md
> +The updateRecords function takes 4 arguments represented by the following function parameters:
```suggestion
The `updateRecords` function takes 4 arguments represented by the following function parameters:
```

2023-03-20 19:08 UTC, RandellDawson requested changes
See my suggestions and reasoning.

2023-03-24 19:27 UTC, jeremylt commented
I replied why I think the two remaining review comments are not the way to go in my opinion, so I think we are back to waiting on review.

2023-03-26 02:51 UTC, RandellDawson commented
@jeremylt I understand your intent.  I just wish there was a way to not make it so "wordy".  This is the first challenge where logic order matters but we are still really trying to get the users understanding how to use objects.  Is there a way to present the challenge instructions to guide the user to a specific order of logic?  That should make it easier for the user to just focus on the syntax needed.  Maybe the instructions can be written to explain the logic should be written in the same order as the rules?

2023-03-26 06:55 UTC, jeremylt commented
Do we want to that strongly push this challenge into 'exactly replicate our pseudo code'? We can always make more adjustments in the future. I think we can make the changes in this PR and then add even more hand holding if the questions on the forum show that this is still too much of a leap.

2023-03-26 14:33 UTC, RandellDawson commented
> Do we want to that strongly push this challenge into 'exactly replicate our pseudo code'?

I think so.  The new project-based curriculum is going to do just that. Plus, this challenge is not part of the Basic Algorithm section, so users at this point should not be required to flesh out the algorithm.  We do it for them with the pseudo code instructions.  In fact, I would even change the instructions to reflect that this part is pseudo code (we mention it a lot but never show an example).  None of this stops users from creating different solutions, but should definitely reduce the huge leap this particular challenge has historically created and also bridge the gap between seeing a full algorithm and having the users implement it.

Personally, I wish the project-based curriculum would do more of developing the algorithms for project use cases in the beginning instead of "do this" and "do that" to create a project.

2023-03-26 14:41 UTC, jeremylt commented
Personally I think that's the wrong approach.

Since we are directly of the opposite opinion here, I'm going to wait and only add text to the effect of "you should execute these conditions in this order" along with simplification of the bullet points using the assumption that the bullet points are coded exactly in that order if there is a broader consensus to do so. 

Students often and easily miss parts of the instructions, so I think making the instructions more robust to students missing sentences or putting things in different order is the right decision here.

2023-03-26 14:44 UTC, RandellDawson approved these changes

2023-03-26 14:50 UTC, RandellDawson commented
> Personally I think that's the wrong approach.

I am not sure what part of what I said is the wrong approach, but I will just approve the PR since I whatever I do here anymore is rejected.  I am done contributing here.

2023-03-27 17:23 UTC, merged