feat: comment on i18n failure
freeCodeCamp/freeCodeCamp pull request #49746
Opened 2023-03-17 20:45 UTC by naomi-lgbt

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related #49698 

Still need to test this, but should do the trick?

2023-03-23 22:33 UTC, ShaunSHamilton commented on .github/workflows/node.js-tests.yml
> +              body: "Hi,\n\nIt looks like the localization tests have failed. This is normal when there are significant curriculum changes in the English version.\n\nPlease check with the dev-team on
```suggestion
              body: "Hi,\n\nIt looks like the localization tests have failed. This is normal when there are significant curriculum changes in the English version.\n\nPlease check with the dev-team on [Discord](https://discord.gg/KVUmVXA) or our [forums](https://forum.freecodecamp.org) if this means a Crowdin sync is required to address the scenario. They will confirm and take over helping you through the PR.\n\nThanks for your understanding and contribution."
```

2023-03-23 23:08 UTC, ShaunSHamilton approved these changes
I am sad dev-team members do not get a nice message 🙃

2023-03-24 01:21 UTC, naomi-lgbt commented
> I am sad dev-team members do not get a nice message 🙃

That is borrowed from the no translation PR, because when we're intentionally breaking things we don't want to get spammed by the bot (:

2023-03-24 06:49 UTC, raisedadead requested changes
Minor change to the verbiage to make it more succinct.

2023-03-24 06:49 UTC, raisedadead commented on .github/workflows/node.js-tests.yml
> +              body: "Hi,\n\nIt looks like the localization tests have failed. This is normal when there are significant curriculum changes in the English version.\n\nPlease check with the dev-team on
```suggestion
              body: "Hi,\n\nIt looks like the localization tests have failed. This is expected when there are significant curriculum changes in the English version.\n\nThis could mean a Crowdin sync is required to address the scenario. Please check with our staff developer team, either on [Discord](https://discord.gg/KVUmVXA) or our [forums](https://forum.freecodecamp.org). They will confirm and take over helping you through the PR.\n\nThanks for your understanding and contribution."
```

2023-03-24 06:52 UTC, raisedadead approved these changes

2023-03-24 07:14 UTC, merged