feat(client): delete generic success message in the alert
freeCodeCamp/freeCodeCamp pull request #49780
Opened 2023-03-21 10:58 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #49396

This PR is open based on my understanding of this request https://github.com/freeCodeCamp/freeCodeCamp/pull/49396?notification_referrer_id=NT_kwDOBUKR3bM1NjIwNDM3NzY0Ojg4MjQ4Nzk3#pullrequestreview-1349922113

2023-03-21 11:17 UTC, Sboonny commented
To remove the blocked label, this PR should be merged #49781

2023-03-27 08:29 UTC, raisedadead commented
Deployments have not been done, this will only be reviewed when we cross that milestone.

2023-05-08 07:41 UTC, raisedadead approved these changes

2023-05-08 08:51 UTC, ojeytonwilliams requested changes
@Sboonny it doesn't have to be in this PR, but before we merge this could you update the new api's update-my-profileui endpoint to use the new message?

2023-05-08 14:57 UTC, ojeytonwilliams approved these changes

2023-05-08 14:58 UTC, merged