fix(curriculum): Remove webkit clip path from sr-only and its test
freeCodeCamp/freeCodeCamp pull request #49796
Opened 2023-03-22 15:52 UTC by Jiajun-Jiao

- Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #49792 

Made this change because -webkit-clip-path is no longer needed due to improved browser support for the standard clip-path property.

This is the screenshot after change:
<img width="1221" alt="Screenshot 2023-03-22 at 10 30 20" src="https://user-images.githubusercontent.com/97413019/226961018-d45e32d2-e519-42b6-9648-56153622514d.png">

All the following steps are also modified.
The files modified are all under 14-responsive-web-design-22 => learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet package.

These bullet points are achieved:
- Remove mention/instruction of -webkit-clip-path.
- Remove test looking for the property
- Remove the property from all following lessons/steps
- Only change the English files

2023-03-22 18:48 UTC, ShaunSHamilton requested changes
Thank you for taking the time to contribute.

**Requested Changes**

1) Step `43` is missing (it should also be changed)
2) The final step needs the solution code also updated

2023-03-22 18:48 UTC, ShaunSHamilton commented on curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/6201a59be346d399c21d10b1.md
As this is the last file for a project, it contains both the boilerplate (seed) and the solution code.

Please remove the `-webkit-clip-path` property here: https://github.com/freeCodeCamp/freeCodeCamp/pull/49796/files#diff-510dc1b574de1b5414ff2a90ca3fccbaeade55467d0f4478af833c3e09ff867bR441

2023-03-22 19:16 UTC, ShaunSHamilton approved these changes
Thank you for taking care of those changes. This looks good to me 👍

2023-03-23 04:49 UTC, gikf approved these changes

2023-03-23 04:49 UTC, merged

2023-03-23 04:49 UTC, gikf commented
Hi @Jiajun-Jiao. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝