feat: remove babel polyfill package
freeCodeCamp/freeCodeCamp pull request #49917
Opened 2023-04-01 09:51 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

after the three PRs are tests and merged, we can say goodbye to polyfill 

Ref #49916
Ref #49915
Ref #49914

2023-04-03 08:24 UTC, raisedadead requested changes, later dismissed
I do not see a need to split this into so many PRs – use multiple PRs wisely because they increase overhead on reviewers. In this case close the others add commits here.

2023-04-03 09:36 UTC, raisedadead approved these changes

2023-04-04 07:27 UTC, raisedadead commented
@Sboonny do not bother resolving any conflicts to this PR. We will tackle this after the renovate PRs are in.

2023-04-12 14:08 UTC, Sembauke approved these changes

2023-04-12 16:59 UTC, merged