chore: improve block namify
freeCodeCamp/freeCodeCamp pull request #49950
Opened 2023-04-04 18:37 UTC by naomi-lgbt

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

- Cleans up the preformatted names (we shouldn't need to preformat every block name that has HTML in it when we can preformat `HTML`)
- Removes edge case for `JavaScript`, in favour of `preformatted-words.json` to allow extension
- Adds `by` as a preposition it should not be title cased

This aims to solve some pain points I've seen in the review process for the new JavaScript projects. Leaving in draft to ensure I haven't broken anything (snapshots are being weird locally)

2023-04-05 20:28 UTC, raisedadead approved these changes
You write tests, you get approved.

2023-04-06 07:31 UTC, ojeytonwilliams requested changes

2023-04-06 07:31 UTC, ojeytonwilliams commented on utils/block-nameify.ts
> +const noFormatting = ['and', 'for', 'of', 'the', 'up', 'with', 'to', 'by'];
```suggestion
const noFormatting = ['and', 'for', 'of', 'the', 'up', 'with', 'to', 'by', 'a'];
```
I found in https://github.com/freeCodeCamp/freeCodeCamp/pull/49813/, that `'a'` was being uppercased, but it's more in this PR's scope than mine!

2023-04-06 07:31 UTC, ojeytonwilliams commented on utils/block-nameify.test.ts
> +    expect(result).toBe('and for of the up with by');
```suggestion
    const result = blockNameify('and-for-of-the-up-with-by-a');
    expect(result).toBe('and for of the up with by a');
```

2023-04-06 15:56 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2023-04-06 16:31 UTC, merged