server timezone/date issue and format fixed...tested asw
freeCodeCamp/freeCodeCamp pull request #49987
Opened 2023-04-06 22:29 UTC by mickeymind

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #44475 

Both submissions contain same code, in before case, submission is unfairly denied because the time zone of replit server differs from local time, causing incorrect insertion when checking for date.

Before:  Test case uses local time zone which checks for date of April 07 (1 day ahead of submission date). 

      Replit uses UTC time zone which can be up to 14 hours behind local time.

![image](https://user-images.githubusercontent.com/103330664/230502991-58df69c3-8bbe-45cc-b288-195bb6abd09a.png)

After: Test case uses UTC time zone which checks for date of April 06 (actual submission date). 

      Put simply, both servers now only output and check for UTC time zone, so doesn't matter what time zone you submit from 
     (as long as the code works)

![image](https://user-images.githubusercontent.com/103330664/230504087-ec98c3a8-de81-47ba-82ca-c36c5a6cb6dc.png)

2023-04-06 22:30 UTC, mickeymind commented
@farhanb99

2023-04-17 18:33 UTC, thecodingaviator approved these changes
This LGTM!

2023-04-17 20:04 UTC, naomi-lgbt requested changes
Clever solution! One nitpick on the formatting, then this looks good to me.

2023-04-17 20:04 UTC, naomi-lgbt commented on curriculum/challenges/english/05-back-end-development-and-apis/back-end-development-and-apis-projects/exercise-tracker.md
> +                                                    day: "2-digit", year: "numeric"}).replaceAll(',', '')
```suggestion
      date: new Date().toLocaleDateString("en-US", {
        timeZone: "UTC", weekday: "short", month: "short",
        day: "2-digit", year: "numeric"
```

Nitpicking the formatting.

2023-04-17 20:22 UTC, naomi-lgbt approved these changes
okie dokie, looks good to me!

2023-04-17 20:32 UTC, lasjorg commented
Does the requirement need to be changed to UTC?

---

Is the assumption here the server is Replit and that it is always UTC?

The test runs client-side (right?) against what comes back from a server. So right now, toDateString client/toDateString server. With this change, it is toUTCString client/toDateString server.

Maybe I'm just spacing out on the details, Date stuff is confusing.

2023-04-17 20:33 UTC, merged