fix: improvement in Use @if and @else to Add Logic To Your Styles module
freeCodeCamp/freeCodeCamp pull request #50132
Opened 2023-04-22 05:37 UTC by AnonSar

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50131

2023-04-24 16:39 UTC, lasjorg commented on curriculum/challenges/english/03-front-end-development-libraries/sass/use-if-and-else-to-add-logic-to-your-styles.md
> +If the value of the `$val` parameter is not `light`, `medium`, or `heavy`, then the `border` property should be set to `none`.
"If the value of the `$val` parameter" sounds a bit awkward. Maybe instead?

```suggestion
If the `$val` parameter value is not `light`, `medium`, or `heavy`, then the `border` property should be set to `none`.
```

2023-04-24 17:42 UTC, naomi-lgbt requested changes

2023-04-24 17:42 UTC, naomi-lgbt commented on curriculum/challenges/english/03-front-end-development-libraries/sass/use-if-and-else-to-add-logic-to-your-styles.md
> +And just like in JavaScript, `@else if` and `@else` directives test for more conditions:
```suggestion
And just like in JavaScript, the `@else if` and `@else` directives test for more conditions:
```

2023-04-25 16:25 UTC, lasjorg approved these changes
LGTM

2023-04-25 17:06 UTC, naomi-lgbt approved these changes
Works for me!

2023-04-25 17:07 UTC, merged