feat: add exercise C The Odin Project
freeCodeCamp/freeCodeCamp pull request #50257
Opened 2023-05-03 08:26 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-05-09 18:49 UTC, naomi-lgbt requested changes
A few nits.

2023-05-09 18:49 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-c.md
> +1. You should see a yellow background on the second element.
```suggestion
1. You should see a black background and white text on the first `button` element.
1. You should see a yellow background on the second `button` element.
```

It's not really clear what elements should be styled. `head` and `body` are also elements.

2023-05-09 18:49 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-c.md
> +    <link rel="stylesheet" href="style.css">
```suggestion
    <link rel="stylesheet" href="styles.css">
```

2023-05-09 18:49 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-c.md
> +    <link rel="stylesheet" href="solution.css">
```suggestion
    <link rel="stylesheet" href="styles.css">
```

2023-05-09 18:49 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-c.md
> +assert.equal(eitherOr()?.fontFamily, 'Helvetica, "Times New Roman", sans-serif');
```suggestion
assert.exists(eitherOr());
```

We should only test that the selector exists, here.

2023-05-09 20:56 UTC, naomi-lgbt approved these changes
Okie dokie

2023-05-10 06:28 UTC, Nirajn2311 approved these changes

2023-05-10 06:29 UTC, merged