feat: add exercise D The Odin Project
freeCodeCamp/freeCodeCamp pull request #50278
Opened 2023-05-04 13:01 UTC by Sembauke

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-05-09 17:51 UTC, naomi-lgbt requested changes, later dismissed
Since `.avatar.proportioned` and `.proportioned.avatar` both target the same element and are both valid selectors, we should allow both to pass.

2023-05-09 17:51 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-d.md
> +const style = new __helpers.CSSHelp(document).getStyle(`.avatar.proportioned`);
```suggestion
const style = new __helpers.CSSHelp(document).getStyle(`.avatar.proportioned`) || new __helpers.CSSHelp(document).getStyle(`.proportioned.avatar`);
```

2023-05-09 17:51 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-d.md
> +const style = new __helpers.CSSHelp(document).getStyle(`.avatar.proportioned`);
```suggestion
const style = new __helpers.CSSHelp(document).getStyle(`.avatar.proportioned`) || new __helpers.CSSHelp(document).getStyle(`.proportioned.avatar`)
```

2023-05-09 17:51 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-d.md
> +const style = new __helpers.CSSHelp(document).getStyle(`.avatar.proportioned`);
```suggestion
const style = new __helpers.CSSHelp(document).getStyle(`.avatar.distorted`) || new __helpers.CSSHelp(document).getStyle(`.distorted.avatar`);
```

This one was also looking for the wrong class.

2023-05-10 06:55 UTC, Nirajn2311 approved these changes

2023-05-12 04:24 UTC, moT01 approved these changes
LGTM 🎉 I'm gonna give it a merge.

Wondering if we should remove that save button that saves users code to the database on these. They feel more like mini challenges than projects you might need to save your code for.

2023-05-12 04:24 UTC, merged