feat: add exercise E The Odin Project
freeCodeCamp/freeCodeCamp pull request #50287
Opened 2023-05-05 09:45 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-05-08 16:37 UTC, naomi-lgbt requested changes

2023-05-08 16:37 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-e.md
> +console.log(getCorrectStyle()?.color)
```suggestion
```

2023-05-08 16:37 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-e.md
> +red text, a font size of 20px, and center aligned.
```suggestion
```

2023-05-09 17:26 UTC, naomi-lgbt approved these changes
I wanted to DRY this out with the `--after-seed-code--` but that triggers the JavaScript editor to appear 😔 

This is good as is.

2023-05-10 07:11 UTC, Nirajn2311 requested changes
Grammatical and spelling errors. Rest all are good to go.

2023-05-10 07:11 UTC, Nirajn2311 commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-e.md
> +You should have a background color of `yellow` on your decendants.
```suggestion
You should have a background color of `yellow` on your descendants.
```

2023-05-10 07:11 UTC, Nirajn2311 commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-e.md
> +You should have a text color of `red` on your decendants.
```suggestion
You should have a text color of `red` on your descendants.
```

2023-05-10 07:11 UTC, Nirajn2311 commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-e.md
> +You should have a font size of `20px` on your decendants.
```suggestion
You should have a font size of `20px` on your descendants.
```

2023-05-10 07:11 UTC, Nirajn2311 commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-e.md
> +You should center align the text on your decendants.
```suggestion
You should center align the text on your descendants.
```

2023-05-10 07:11 UTC, Nirajn2311 commented on curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-e.md
> +1. You should text that is center aligned for elements that are descendants of the `div` element.
```suggestion
1. You should see a `yellow` background for `p` elements that are descendants of the `div` element.
1. You should see a text color of `red` for elements that are descendants of the `div` element.
1. You should see a font size of `20px` for elements that are descendants of the `div` element.
1. You should center align text for elements that are descendants of the `div` element.
```

2023-05-10 12:54 UTC, Nirajn2311 approved these changes

2023-05-10 12:55 UTC, merged