feat(api): add update IsHonest value endpoint
freeCodeCamp/freeCodeCamp pull request #50281
Opened 2023-05-04 13:38 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #50280

2023-05-05 07:18 UTC, ojeytonwilliams requested changes
The success message is missing, but otherwise this looks good.

2023-05-05 07:18 UTC, ojeytonwilliams commented on api/src/routes/settings.ts
> +            type: Type.Literal('success')
```suggestion
            message: Type.Literal('buttons.accepted-honesty'),
            type: Type.Literal('success')
```

2023-05-05 07:18 UTC, ojeytonwilliams commented on api/src/routes/settings.ts
> +          type: 'success'
```suggestion
          message: 'buttons.accepted-honesty',
          type: 'success'
```

2023-05-05 07:18 UTC, ojeytonwilliams commented on api/src/routes/settings.test.ts
> +          type: 'success'
```suggestion
          message: 'buttons.accepted-honesty',
          type: 'success'
```

2023-05-05 13:25 UTC, ojeytonwilliams requested changes

2023-05-05 13:28 UTC, Sboonny commented on api/src/routes/settings.ts
> +          isHonest: Type.Boolean()
is that why, we have isBlocked and isHonest? 🤔 because we don't allow isHonest to be false, so we created another value for isBlocked.

2023-05-05 18:55 UTC, ojeytonwilliams commented on api/src/routes/settings.ts
> +          isHonest: Type.Boolean()
Not sure. All I know is that it should be called `hasAcceptedHonestyPolicy`.

2023-05-05 18:55 UTC, ojeytonwilliams approved these changes
LGTM 👍

2023-05-08 16:47 UTC, naomi-lgbt commented on api/src/routes/settings.test.ts
Do we want to add a test to catch that the server rejects an `isHonest: false` payload?

2023-05-08 18:14 UTC, ShaunSHamilton commented on api/src/routes/settings.test.ts
IMO, we should not be testing something from an external library (the fastify validator + TypeBox) like that.

2023-05-08 18:29 UTC, naomi-lgbt commented on api/src/routes/settings.test.ts
I disagree - if we are relying on this validator to ensure that an `isHonest: false` payload is rejected and does not get saved to the database, we should either test for that, or rely on our own logic instead.

2023-05-08 18:37 UTC, ShaunSHamilton commented on api/src/routes/settings.test.ts
If we do not trust the validator, we should not be using it - we should write our own validation, or create a custom validator.

Why do we not test that it also rejects `hello: "world"` on all routes?

2023-05-08 18:57 UTC, ojeytonwilliams commented on api/src/routes/settings.test.ts
It's not really about testing or trusting the validator. It's just that we want to test the endpoint.

The main point of these tests is to confirm that the blackbox behaves as expected. That way we can refactor as desired (including, if we need to, replace the validator).

2023-05-09 10:18 UTC, Sboonny reviewed
Fix to merge mistake

2023-05-09 10:18 UTC, Sboonny commented on api/src/routes/settings.test.ts
> +          .send({ honesty: true });
```suggestion
          .send({ isHonest: true });
```

2023-05-09 10:18 UTC, Sboonny commented on api/src/routes/settings.test.ts
> +          .send({ honesty: 'invalid' });
```suggestion
          .send({ isHonest: 'invalid' });
```

2023-05-09 10:18 UTC, Sboonny reviewed
Fix to merge mistake

2023-05-09 10:18 UTC, Sboonny reviewed
Fix to merge mistake

2023-05-09 11:17 UTC, ojeytonwilliams requested changes

2023-05-09 11:17 UTC, ojeytonwilliams commented on api/src/routes/settings.test.ts
> +          .send({ isHonest: 'invalid' });
```suggestion
          .send({ isHonest: false });
```
Since we're already checking invalid input, we can be little more focused.

2023-05-09 11:24 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2023-05-09 16:29 UTC, naomi-lgbt approved these changes

2023-05-09 16:29 UTC, merged