feat(client): generate challenge data as static files
freeCodeCamp/freeCodeCamp pull request #50369
Opened 2023-05-12 19:10 UTC by Nirajn2311

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

Ref - https://github.com/freeCodeCamp/freeCodeCamp/pull/50355#issuecomment-1544400365

Instead of relying on the generate page data by Gatsby, I'm generating the challenge data and storing them as individual files in the clients static folder so that mobile app can make use of them.

2023-05-18 10:49 UTC, Sembauke approved these changes

2023-05-22 19:54 UTC, naomi-lgbt requested changes
This isn't necessarily blocking, and if you can work with the weird directories that's fine.

But it looks like the `2022/responsive-web-design` is being parsed as a nested directory:

<img width="223" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/afd12944-5d30-4c44-9b19-484cafbf46a2">

Review suggestions will fix this. Can't reach far enough down the file, but would also need to declare the function:

```js
  function parse2022SuperBlock(superBlockName: string) {
    return superBlockName.replace(/\//g, '-');
  }
```

2023-05-22 19:54 UTC, naomi-lgbt commented on tools/scripts/build/build-external-curricula-data.ts
> +          const challengePath = `challenges/${superBlockKey}/${blockNames[j]}/${challengeId}`;
```suggestion
          const challengePath = `challenges/${parse2022SuperBlock(
            superBlockKey
          )}/${blockNames[j]}/${challengeId}`;
```

2023-05-22 19:54 UTC, naomi-lgbt commented on tools/scripts/build/build-external-curricula-data.ts
>        writeToFile(superBlockKey, superBlock);
writeToFile(parse2022SuperBlock(superBlockKey), superBlock);

2023-05-23 08:13 UTC, Nirajn2311 commented
> This isn't necessarily blocking, and if you can work with the weird directories that's fine.
> 
> But it looks like the `2022/responsive-web-design` is being parsed as a nested directory:

Yes, we're fine with this and actually I prefer it this way

2023-05-23 15:37 UTC, naomi-lgbt approved these changes
Works for me!

2023-05-23 15:37 UTC, merged