feat(client): check if visited profile exist
freeCodeCamp/freeCodeCamp pull request #50367
Opened 2023-05-12 13:17 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [] I have tested these changes either locally on my machine, or GitPod.

Because of the removal of the timer, the page render before the `maybeUser` data is fetched through the useEffect, this aims to delay it, but Idk if it actually will work because it isn't possible to test :(

You can find the issue if you visit https://www.freecodecamp.org/Sboonny in private mode

2023-05-12 15:06 UTC, naomi-lgbt requested changes

2023-05-12 15:06 UTC, naomi-lgbt commented on client/src/client-only-routes/show-profile-or-four-oh-four.tsx
> +  const hasPorfile = isEmpty(requestedUser) || isEmpty(maybeUser);
```suggestion
  const hasProfile = isEmpty(requestedUser) || isEmpty(maybeUser);
```

2023-05-12 15:06 UTC, naomi-lgbt commented on client/src/client-only-routes/show-profile-or-four-oh-four.tsx
> +  return hasPorfile ? (
```suggestion
  return hasProfile ? (
```

2023-05-15 18:31 UTC, naomi-lgbt commented
Is the aim to fix the issue where the default 404 page shows until the profile is loaded?

If so, testing this locally doesn't appear to resolve it.

2023-05-15 18:49 UTC, Sboonny commented
how did you test it? I couldn't mimic the way to produce the bug with the way that 404 is structured

2023-05-15 18:58 UTC, naomi-lgbt commented
- Open the network tab, throttle down to 3G speed to get the slow loading times.
- Visit `http://localhost:8000/twaha` - wait for it to load (takes forever)
- Click `Preview custom 404 page`

You should see the 404 pop up for a bit before switching to twaha's private profile.

2023-05-15 19:36 UTC, Sboonny commented
Nice, I can finally test, I should be able to sort it tomorrow morning

2023-05-16 05:33 UTC, Sboonny commented
I have wrapped error boundary around profile, so when it fails and we get runtime error, we display 404 page.

2023-05-16 17:11 UTC, naomi-lgbt commented
This is looking good. Just to confirm, are we okay with this error message displaying?

<img width="515" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/80948d1a-fa36-433d-9237-26fc501a05ab">

2023-05-16 18:32 UTC, Sboonny commented
I can sort it in another PR, because I want to refactor the loading component as well

2023-05-16 18:47 UTC, naomi-lgbt approved these changes
Okie dokie

2023-05-26 07:21 UTC, Nirajn2311 approved these changes

2023-05-26 07:21 UTC, merged

2023-05-26 08:06 UTC, raisedadead commented
> This is looking good. Just to confirm, are we okay with this error message displaying?

Hold up! 

I need to get up to speed on these changes, but that error message and screen were there specifically when the client got stuck loading. This can happen when we release a new bundle, and the client has a stale cache. 

Ex: You are working on your curriculum, we make a release, and then you submit challenges. Ideally, you do not see the difference, but depending on your ISP, DNS, etc., the new client bundle could take a bit to stream to your browser. 

In those cases, the client can't reach the API to update states and would need a quick reload.

The client (or rather the user) will not know about this unless they see a message that shows up after a pre-determined period.

2023-05-26 08:25 UTC, Sboonny commented
> that error message and screen were there specifically when the client got stuck loading. This can happen when we release a new bundle, and the client has a stale cache.

this behavior hasn't changed, what changed is the way we display this loading screen for the profile page.

2023-05-26 08:32 UTC, Sboonny commented
The reason I want to refactor this message is that Naomi shouldn't have never seen this message, because there isn't a message delay as far as I know.

There is a misunderstanding from my part on that component and I want to make it simpler and more easier to understand.