feat(api): get certslug route
freeCodeCamp/freeCodeCamp pull request #50515
Opened 2023-05-25 12:30 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50501

2023-09-20 15:48 UTC, Sboonny commented on api/src/utils/error-formatting.ts
> +    Object.hasOwn(certTypes, error.params.missingProperty as CertLogs)
hasOwn checks the `properties`, I need to use [valus](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values)

2024-01-25 10:47 UTC, Bushbaby02A reviewed
It's a fair plan and am definitely sure am gonna enjoy it

2024-01-25 10:47 UTC, Bushbaby02A commented on api/src/schemas.ts
> +      username: Type.String()
`string`

2024-03-01 09:42 UTC, ojeytonwilliams requested changes

2024-03-01 09:42 UTC, ojeytonwilliams commented on api/src/app.ts
> +  void fastify.register(certificateRoutes);
```suggestion
```
This is already registered on line 200

2024-03-12 10:08 UTC, Sembauke approved these changes

2024-04-11 06:57 UTC, raisedadead approved these changes

2024-04-11 06:57 UTC, merged