chore(build): add eslint caching
freeCodeCamp/freeCodeCamp pull request #50527
Opened 2023-05-26 19:48 UTC by jmetev1

Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes none 

Before this change, lint:js took a minute on my local. After, it takes 1 second. Also if you want, we could enable it on ci: https://enochchau.com/blog/2022/eslint-cache-ci/. I could add that here or as a separate pr.

2023-05-26 22:15 UTC, jmetev1 commented on client/package.json
> +    "eslint-plugin-testing-library": "^3.9.0",
added to avoid peer dependency warning

2023-05-26 22:15 UTC, jmetev1 commented on client/src/templates/Challenges/classic/mobile-layout.tsx
> +  setToolPanelPosition = (): void => {
some changes in typescript eslint packages started flagging this. which seems like a good thing right?

2023-05-26 22:17 UTC, jmetev1 commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.33.0",
this adds explicitly a dependency that we were using in eslintrc file.

2023-05-26 22:18 UTC, jmetev1 commented on package.json
> +    "babel-eslint": "^10.1.0",
eslintrc was using this already but we never explicitly installed it. Just happened to have it as a sub dependency.

2023-05-26 23:11 UTC, jmetev1 commented
all the tests passed last time except firefox tests. But i see on another branch they just ran them again and they passed so I'm now doing the same. I looked for a way to retrigger just that test but didn't see a way so i pulled from main and pushed.

2023-05-27 18:52 UTC, jmetev1 commented on package.json
> -    "eslint-plugin-prefer-object-spread": "1.2.1",
not being used

2023-05-27 18:56 UTC, jmetev1 commented on client/package.json
> -    "eslint": "7",
not used

2023-05-27 18:56 UTC, jmetev1 commented on client/package.json
> -    "@babel/types": "7.22.3",
not used

2023-05-28 19:29 UTC, jmetev1 commented
can my pr be reviewed even with pnpm lock conflicts? I've been assuming no but that mean I've been constantly fixing the lock file every time someone else gets merged.

2023-05-31 09:01 UTC, ojeytonwilliams requested changes
Thanks, @jmetev1. Local caching seems like a good idea, but I'd rather not do that in CI just to err on the side of caution.

 I just found the one other issue:

2023-05-31 09:02 UTC, ojeytonwilliams commented
> can my pr be reviewed even with pnpm lock conflicts?

Absolutely. It just can't be merged until they're resolved.

2023-05-31 15:48 UTC, jmetev1 commented on package.json
> +    "lint:js": "eslint --cache --cache-strategy content --max-warnings 0 .",
was this a reference to this line i took out? good eye. i caught it myself and fixed it, but didn't push! whoops

2023-05-31 15:52 UTC, ojeytonwilliams commented on package.json
> +    "lint:js": "eslint --cache --cache-strategy content --max-warnings 0 .",
No, I misread the diff :man_facepalming: Sorry! I'll suggest a fix (a real one this time)

2023-05-31 15:59 UTC, jmetev1 commented on package.json
> +    "lint:js": "eslint --cache --cache-strategy content --max-warnings 0 .",
yeah i had added that part specifically for ci caching. i can take it out.

2023-06-01 12:50 UTC, ojeytonwilliams approved these changes
Thanks for bearing with me @jmetev1 

This all LGTM :+1:

2023-06-01 15:23 UTC, jmetev1 commented
thanks!

2023-06-01 20:19 UTC, moT01 approved these changes
LGTM @jmetev1 🎉 Thanks for contributing to freeCodeCamp 🎉

2023-06-01 20:19 UTC, merged