feat: challenge helpers for non-step-based challenges
freeCodeCamp/freeCodeCamp pull request #50769
Opened 2023-06-20 22:37 UTC by naomi-lgbt

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

With work being done on things like the Odin Project, not all of our upcoming lessons will be step-based. This adds tools similar to the step-based tools for adding and manipulating the challenges and their order.

2023-06-22 07:29 UTC, ojeytonwilliams requested changes

2023-06-22 07:29 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/helpers/new-challenge-prompts.ts
> +  const title = await prompt({
```suggestion
  const dashedName = await prompt({
```
'name' and 'title' are back to front, also name is a bit too generic imo

2023-06-22 07:29 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/helpers/new-challenge-prompts.ts
> +  const name = await prompt({
```suggestion
  const title = await prompt({
```

2023-06-22 07:29 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/helpers/new-challenge-prompts.ts
> +    name: String(name.value),
```suggestion
    dashedName: String(dashedName.value),
```

2023-06-22 07:29 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/helpers/new-challenge-prompts.ts
> +  const title = await prompt({
Also, `prompt` is generic, so you can do something like 

```ts
  const { dashedName } = await prompt<{ dashedName: string }>({
    name: 'dashedName',
```
which is a little less awkward than either using `String` or `as { value: string }` to mollify TS.

2023-06-22 07:29 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/insert-challenge.ts
> +  })) as { id: string };
```suggestion
  const challengeAfter = await prompt<{id: string}>({
    name: 'id',
    message: 'Which challenge should come AFTER this new one?',
    type: 'list',
    choices: challenges.map(([id, title]) => ({
      name: title,
      value: id
    }))
  })
```
There's not much in it, but this seems a little cleaner.

2023-06-22 07:29 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/insert-challenge.ts
> +  meta.challengeOrder.push([challengeId.toString(), options.title]);
```suggestion
```
Only need the one.

2023-06-22 07:32 UTC, ojeytonwilliams requested changes
Ooops, missed these.

2023-06-22 07:32 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/insert-challenge.ts
> +  createChallengeFile(options.title, template, path);
```suggestion
  createChallengeFile(options.dashedName, template, path);
```

2023-06-22 07:32 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/create-next-challenge.ts
> +  createChallengeFile(options.title, template, path);
```suggestion
  createChallengeFile(options.dashedName, template, path);
```

2023-06-22 20:02 UTC, naomi-lgbt commented on tools/challenge-helper-scripts/insert-challenge.ts
> +  meta.challengeOrder.push([challengeId.toString(), options.title]);
Whoops

2023-06-22 22:38 UTC, ojeytonwilliams commented
Sorry, Naomi, I didn't do a good job with those suggestions. I'll push a cleanup commit in the morning.

2023-06-28 09:57 UTC, ojeytonwilliams requested changes
It's not really relevant to this PR, but I wonder if we should switch the meta.json format from

```
  "challengeOrder": [
    [
      "id": "587d7dbc367417b2b2512bb1",
      "title": "Create a Simple JSX Element"
    [,
```
to
```
  "challengeOrder": [
    {
      "id": "587d7dbc367417b2b2512bb1",
      "title": "Create a Simple JSX Element"
    },
```

Working with tuples is nasty and, weirdly, I don't think much code needs to change to accommodate this. What do you reckon?

Anyways, back on topic, some nitpicks:

2023-06-28 09:57 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/delete-challenge.ts
> +void (async () => await deleteChallenge())();
```suggestion
void createNextChallenge();
```

2023-06-28 09:57 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/insert-challenge.ts
> +void (async () => await insertChallenge())();
```suggestion
void insertChallenge();
```

2023-06-28 09:57 UTC, ojeytonwilliams commented on tools/challenge-helper-scripts/utils.ts
> +  fs.writeFileSync(`${path}${title}.md`, template);
Not a big deal, but there's nothing that needs to wait for this, so it could be async.

2023-07-11 07:30 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

<sub>IIFE are fine - I don't like _unnecessary_ ones!</sub>

2023-07-11 16:04 UTC, moT01 reviewed
These tools are fantastic @naomi-lgbt 🎉 I left one suggestion to try and minimize confusion. Not sure if I worded it the best - but if someone sees this, they may not know about the other tools without a mention of them.

2023-07-11 16:04 UTC, moT01 commented on docs/how-to-work-on-coding-challenges.md
> +There are a few helper scripts that can be used to manage the challenges in a block. Note that these commands should all be run in the block directory. For example:
```suggestion
> [!NOTE]
> If you want to work with the step-based challenges, refer to the [Work on Practice Projects](how-to-work-on-practice-projects.md) section.

There are a few helper scripts that can be used to manage the challenges in a block. Note that these commands should all be run in the block directory. For example:
```

2023-07-11 17:32 UTC, moT01 approved these changes

2023-07-11 17:32 UTC, merged

2023-07-31 00:23 UTC, lloydchang commented
> It's not really relevant to this PR, but I wonder if we should switch the meta.json format from
> 
> ```
>   "challengeOrder": [
>     [
>       "id": "587d7dbc367417b2b2512bb1",
>       "title": "Create a Simple JSX Element"
>     [,
> ```
> 
> to
> 
> ```
>   "challengeOrder": [
>     {
>       "id": "587d7dbc367417b2b2512bb1",
>       "title": "Create a Simple JSX Element"
>     },
> ```
> 
> Working with tuples is nasty and, weirdly, I don't think much code needs to change to accommodate this. What do you reckon?
> 
> Anyways, back on topic, some nitpicks:

I believe this relates to https://github.com/freeCodeCamp/classroom/issues/410#issuecomment-1657303141

Context: [feat: Detect changes coming from FCC API responses inside of the classroom mode project #410](https://github.com/freeCodeCamp/classroom/issues/410)