fix(curriculum): add description for C# exam
freeCodeCamp/freeCodeCamp pull request #50779
Opened 2023-06-22 12:12 UTC by moT01

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-06-29 07:12 UTC, Sembauke requested changes

2023-06-29 07:12 UTC, Sembauke commented on curriculum/challenges/english/19-foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam.md
> +- You must complete the exam in a single session.
```suggestion
- You must complete the entire exam in one session.
```

2023-06-29 07:12 UTC, Sembauke commented on curriculum/challenges/english/19-foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam.md
> +- If you exit the exam at any point, it will result in the loss of your progress.
```suggestion
- Exiting the exam at any point will result in the loss of your progress.
```

2023-06-29 07:12 UTC, Sembauke commented on curriculum/challenges/english/19-foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam.md
> +- The exam will comprise of multiple-choice questions.
```suggestion
- The exam consists of multiple-choice questions.
```

2023-06-29 07:12 UTC, Sembauke commented on curriculum/challenges/english/19-foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam.md
> +- There is no time limit, but your time will be recorded.
```suggestion
- There is no specific time limit, but your total time taken will be recorded.
```

2023-06-29 07:12 UTC, Sembauke commented on curriculum/challenges/english/19-foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam.md
> +- Complete the exam and answer a sufficent number of question correctly to qualify to claim your certification.
```suggestion
- To qualify for certification, you need to complete the exam and answer a sufficient number of questions correctly.
```

2023-06-29 07:12 UTC, Sembauke commented on curriculum/challenges/english/19-foundational-c-sharp-with-microsoft/foundational-c-sharp-with-microsoft-certification-exam/foundational-c-sharp-with-microsoft-certification-exam.md
> +Pass this exam to earn your Foundational C# with Microsoft Certification. Please familiarize yourself with the following guidelines and click the start button when you are ready to begin:
```suggestion
To earn your Foundational C# with Microsoft Certification, you need to pass this exam. Before starting the exam, please review the following guidelines:
```

2023-06-29 15:23 UTC, moT01 commented
Thanks for taking a look @Sembauke 👍 These suggestions didn't seem particularly necessary. Some were maybe a little better or maybe a little worse in cases. The wording seems more like a preference - I think they worked either way. I ended up adding many of them (with slight modifications). Hopefully, it's good enough 👍

2023-06-29 15:38 UTC, Sembauke commented
No problem @moT01, that's were the reviews are for.

2023-06-29 15:40 UTC, Sembauke approved these changes

2023-07-06 10:07 UTC, Sboonny approved these changes
LGTM

2023-07-06 10:07 UTC, merged