fix(curriculum): explain the box-sizing property
freeCodeCamp/freeCodeCamp pull request #50786
Opened 2023-06-23 00:00 UTC by CBID2

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #49156 

I explained the `box-sizing property` in two separate steps. One focuses on the `content-box` value and its purpose while the other focuses on the `border-box` value and how it differs from the former. Through these changes, I anticipate that campers would gain a better understanding of the steps.

2023-06-23 17:21 UTC, naomi-lgbt requested changes
It looks like there is still some confusion here. Here are the steps to resolve the issue.

From a clean branch:

- Use the `insert-step` tool to insert a new step 7
  - The new step 7 should instruct the campers to set the `box-sizing` property to `content-box` and explain the behaviour and the browser default.
- Update the old step7, which will now be step 8
  - Step 8 should be changed to tell the campers to change `box-sizing` to `border-box` and explain why the change matters.

2023-06-23 17:21 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/6494da0daf5df5197963671d.md
This step is empty?

2023-06-23 17:21 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-flexbox-by-building-a-photo-gallery/6493bc0d99879635209565aa.md
This step is empty?

2023-06-23 17:22 UTC, CBID2 commented
> It looks like there is still some confusion here. Here are the steps to resolve the issue.
> 
> 
> 
> From a clean branch:
> 
> 
> 
> - Use the `insert-step` tool to insert a new step 7
> 
>   - The new step 7 should instruct the campers to set the `box-sizing` property to `content-box` and explain the behaviour and the browser default.
> 
> - Update the old step7, which will now be step 8
> 
>   - Step 8 should be changed to tell the campers to change `box-sizing` to `border-box` and explain why the change matters.

I'll try

2023-06-26 19:13 UTC, naomi-lgbt commented
Closing in favour of #50795

2023-06-26 19:13 UTC, closed without merging