fix(types): adding create-redirect props to fix some unnecessary ts-ignores
freeCodeCamp/freeCodeCamp pull request #50810
Opened 2023-06-24 19:13 UTC by mateoguzmana

Checklist:
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Adding create-redirect props to fix some unnecessary ts-ignores.

2023-06-26 09:27 UTC, ojeytonwilliams requested changes
Hey @mateoguzmana thanks for putting the time in to tidy up the code base. Unfortunately, we do need these props.

I think the following changes should make the code a little less confusing:

2023-06-26 09:27 UTC, ojeytonwilliams commented on client/src/pages/certification.tsx
> +      <RedirectHome />
```suggestion
      <RedirectHome default />
```
We have to pass this prop for the component to be rendered. But `default={true}` is a little ugly and this seems nicer :shrug:

2023-06-26 16:25 UTC, mateoguzmana commented
> Hey @mateoguzmana thanks for putting the time in to tidy up the code base. Unfortunately, we do need these props.
> 
> I think the following changes should make the code a little less confusing:

I had the feeling this was somehow used :D, thanks a lot for clarifying @ojeytonwilliams! Fixed

2023-06-26 22:16 UTC, ojeytonwilliams approved these changes
Thanks, @mateoguzmana! LGTM 👍

2023-06-29 16:33 UTC, Sboonny approved these changes
LGTM

2023-06-29 16:33 UTC, merged