Chore(cirriculum) - provide further info on unordered lists
freeCodeCamp/freeCodeCamp pull request #50844
Opened 2023-06-30 00:01 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #47554

2023-06-30 03:37 UTC, bbsmooth commented
I could be wrong here, but I thought the complaint about this step was that the solution requires `list-style: none` and the `list-style` property hasn't been introduced yet. I think if we are going to fix the instructions for this step it should include an explanation of `list-style`.

2023-06-30 16:12 UTC, a2937 commented
Oh. I'll get right on that.

2023-07-06 21:34 UTC, naomi-lgbt requested changes

2023-07-06 21:34 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148defa9c01520fb9d178a0.md
> +While `ul`/`li` elements are great at providing bullets for list items, our radio buttons will instead be used to mark each list item. We
```suggestion
While `ul`/`li` elements are great at providing bullets for list items, your radio buttons will instead be used to mark each list item. You
```

2023-07-06 21:34 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148defa9c01520fb9d178a0.md
> +can control what the bullets look by using the `list-style` css property.  For example you can turn your bullets into the circles
```suggestion
can control what the bullets look by using the `list-style` css property. For example you can turn your bullets into the circles
```

2023-07-06 21:34 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148defa9c01520fb9d178a0.md
> +.circle-bullet {
```suggestion
ul {
```

2023-07-06 21:49 UTC, moT01 reviewed
I think this will work with @naomi-lgbt's suggestions - I tried to come up with some a little more concise:

````
While `ul`/`li` elements are great at providing bullets for list items,
your radio buttons don't need them. You can control what the bullets
look with the `list-style` property. For example you can turn your
bullets into circles with the following:
 
 ```css
.ul {
  list-style: circle;
}
```

Remove the default styling for the `.answers-list` items by settings
its style to `none`, and remove the unordered list padding.
````

It's not much different. I condensed a few words and added the specific value to use (`none`) in the instructions.

2023-07-06 23:28 UTC, a2937 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148defa9c01520fb9d178a0.md
> +.circle-bullet {
Applied.

2023-07-06 23:29 UTC, a2937 commented
Thank you for your suggestions.

2023-07-07 02:06 UTC, moT01 requested changes
My suggestions add the `# --description--` header back and put the whole description on one line.

2023-07-07 02:06 UTC, moT01 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148defa9c01520fb9d178a0.md
> +bullets into circles with the following:
```suggestion
# --description--

While `ul`/`li` elements are great at providing bullets for list items, your radio buttons don't need them. You can control what the bullets look with the `list-style` property. For example you can turn your bullets into circles with the following:
```

2023-07-07 02:06 UTC, moT01 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148defa9c01520fb9d178a0.md
> +its style to `none`, and remove the unordered list padding.
```suggestion
Remove the default styling for the `.answers-list` items by settings its style to `none`, and remove the unordered list padding.
```

2023-07-07 16:51 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-accessibility-by-building-a-quiz/6148defa9c01520fb9d178a0.md
> +.ul {
```suggestion
ul {
```

Nitpick - element selector, not class.

2023-07-07 17:09 UTC, naomi-lgbt approved these changes

2023-07-11 18:03 UTC, moT01 approved these changes
LGTM @a2937 🎉 Thanks for contributing to freeCodeCamp 🎉

2023-07-11 18:03 UTC, merged