chore(i18n,client): processed translations
freeCodeCamp/freeCodeCamp pull request #50850
Opened 2023-06-30 12:24 UTC by camperbot

This PR was opened auto-magically by Crowdin.

2023-06-30 16:24 UTC, naomi-lgbt approved these changes

2023-07-03 13:01 UTC, ShaunSHamilton requested changes

2023-07-03 16:59 UTC, naomi-lgbt commented on client/i18n/locales/swahili/translations.json
> +      "p7": "Kama taasisi ya kitaaluma ambayo hutoa vyeti kulingana na mafanikio, tunazingatia uaminifu wa kitaaluma. Ikiwa una maswali yoyote kuhusu sera hii au unashuku kuwa kuna mtu ameikiuka, una
Updated - re-running workflow now. Nice catch!

2023-07-03 17:02 UTC, naomi-lgbt approved these changes

2023-07-03 17:19 UTC, ShaunSHamilton approved these changes

2023-07-03 17:19 UTC, merged