feat(client): move certification to jsx element
freeCodeCamp/freeCodeCamp pull request #50899
Opened 2023-07-05 14:12 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-07-05 14:29 UTC, Sboonny commented
I use index to solve this fast, to know why we shouldn't use index, check this article https://robinpokorny.com/blog/index-as-a-key-is-an-anti-pattern/

2023-07-05 15:43 UTC, ojeytonwilliams requested changes

2023-07-05 15:43 UTC, ojeytonwilliams commented on client/src/components/settings/certification.tsx
> +    const { t } = useTranslation();
I'd either use `useTranslation` everywhere (and get rid of `withTranslation`) or pass the `t` function to this. Either is fine, but mixing them is just confusing.

2023-07-05 16:12 UTC, ojeytonwilliams approved these changes
Thanks, @Sboonny. This LGTM :+1:

2023-07-06 09:51 UTC, Sembauke approved these changes

2023-07-06 09:52 UTC, merged