bug fix: removed border from solution code
freeCodeCamp/freeCodeCamp pull request #50897
Opened 2023-07-05 12:51 UTC by blu3IceCube

I have fixed the border issue in the solution code in the certification ssection. Please review and do tell if you have some further instructions or concerns regarding this fix.

2023-07-05 13:13 UTC, Sboonny commented
Changing the bootstrap file isn't the right approach to solving this issue. 

To solve the issue move the classes added in https://github.com/freeCodeCamp/freeCodeCamp/pull/50693/files, to CSS selector that affects the challenges' layout, or not affect the setting layout.

2023-07-06 21:27 UTC, naomi-lgbt requested changes
Should please the linter.

2023-07-06 21:27 UTC, naomi-lgbt commented on client/src/components/layouts/global.css
>      border: 1px solid var(--secondary-color);
```suggestion
  border: 1px solid var(--secondary-color);
```

2023-07-19 19:01 UTC, naomi-lgbt commented
Thank you for your interest in contributing.

We typically merge the first pull request that comprehensively resolves the issue. As such, we are closing this in favour of #50968.

2023-07-19 19:01 UTC, closed without merging