feat(api): backend challenge submission endpoint
freeCodeCamp/freeCodeCamp pull request #50949
Opened 2023-07-12 07:37 UTC by Nirajn2311

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50433

2023-07-17 10:50 UTC, ojeytonwilliams requested changes
The code looks great, I just found one issue with how the tests are structured:

2023-07-17 12:04 UTC, Nirajn2311 commented on api/src/routes/challenge.test.ts
> +        beforeEach(async () => {
I think this was the only place that needed to be changed. The other ones which were in the tests you created follows the rule

2023-07-17 12:26 UTC, ojeytonwilliams commented on api/src/routes/challenge.test.ts
> +        beforeEach(async () => {
Unfortunately not. I didn't clean them up properly, so they interfere with your tests :(

2023-07-17 12:27 UTC, Nirajn2311 commented on api/src/routes/challenge.test.ts
> +        beforeEach(async () => {
Ahh. Then you can go ahead and update my PR.

2023-07-17 13:40 UTC, ojeytonwilliams approved these changes
Ah, you beat me to it. Thanks, @Nirajn2311!

LGTM :+1:

2023-07-19 14:32 UTC, raisedadead approved these changes

2023-07-19 15:33 UTC, Nirajn2311 commented
@raisedadead is there anything remaining to be done or can this be merged?

2023-07-19 19:02 UTC, merged