feat(client): remove bootstrap Form component
freeCodeCamp/freeCodeCamp pull request #50950
Opened 2023-07-12 11:04 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

I don't know why it doesn't provide styles change, or why its attribute doesn't change anything. 🤷

2023-07-12 18:28 UTC, Sboonny commented on client/src/components/Donation/stripe-card-form.tsx
> +      onSubmit={event => void handleSubmit(event)}
The other changes should be "affecting" the styles, except this one, it affects the functionality, as well

Although I think, that it is the same functionality, it doesn't hurt to check it.

2023-07-17 08:56 UTC, ahmaxed commented
Then form on the update-email.tsx is slightly effected. 
We can adopt the same ui for the update-email.tsx 's from as for the email inputs in settings.

2023-07-17 08:56 UTC, ahmaxed approved these changes

2023-07-17 09:45 UTC, ojeytonwilliams requested changes

2023-07-17 09:45 UTC, ojeytonwilliams commented on client/src/components/settings/keyboard-shortcuts.tsx
> +    <form
Are there any reasons to keep this form wrapper? a11y, maybe? It doesn't seem to be doing anything.

2023-07-17 09:45 UTC, ojeytonwilliams commented on client/src/components/settings/sound.tsx
> +    <form onSubmit={(e: React.FormEvent) => e.preventDefault()}>
Same again.

2023-07-17 14:34 UTC, ojeytonwilliams commented on client/src/components/settings/keyboard-shortcuts.tsx
> +    <form
Sure thing. Let's keep this focused!

2023-07-17 14:54 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2023-07-18 07:33 UTC, merged