fix(client): default examInProgress to false
freeCodeCamp/freeCodeCamp pull request #51079
Opened 2023-07-28 08:27 UTC by ShaunSHamilton

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Stumbled on this working on something else. `client/src/components/layouts/default.tsx` complained about the missing prop.

2023-07-28 09:32 UTC, ojeytonwilliams requested changes, later dismissed
We can make use of `ConnectedProps` to remove the ones that redux provides from the props. See: https://redux.js.org/usage/usage-with-typescript#typing-the-connect-higher-order-component

I can push a commit if you like.

2023-07-28 10:50 UTC, ShaunSHamilton commented
@ojeytonwilliams Yes please. I do not understand why it seems to work on some connected props.

2023-07-29 13:46 UTC, huyenltnguyen approved these changes

2023-07-29 13:59 UTC, Sboonny approved these changes
LGTM

2023-07-29 14:00 UTC, merged