ref: Improvement from feedback
freeCodeCamp/freeCodeCamp pull request #51104
Opened 2023-07-30 06:40 UTC by CallmeHongmaybe

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #49492

2023-07-30 06:45 UTC, CallmeHongmaybe commented
I've closed the original PR since it's getting messier over there. And upon working on your suggestions I think that it works better now, but one thing remains to be answered is that `updatePreviewSaga` somehow runs twice, which causes the error messages to appear twice as well. 

![Screen Shot 2023-07-29 at 14 13 32](https://github.com/freeCodeCamp/freeCodeCamp/assets/44527246/74488fa0-d3ab-4a5e-b329-94cff396ec1b)

2023-08-04 15:01 UTC, ojeytonwilliams commented
Sorry for the delay, @CallmeHongmaybe, I'm a little swamped at the moment. It does look like your code is working well, though!

> updatePreviewSaga somehow runs twice, which causes the error messages to appear twice as well.

That's something that will need to be address before we can get this PR in, even though it's a separate issue. I'll try and get that fixed soon so we can move forward with this.

In the mean time, if you have a chance to write tests that confirm that only one 404 message is shown that would be a huge help. Since, clearly, this is a unexpected interaction, it's best we have tests for it.

2023-09-17 06:21 UTC, CallmeHongmaybe commented
I think it's all good at this point.

2023-09-23 10:02 UTC, ojeytonwilliams commented
@raisedadead until the `updatePreviewSaga` is fixed, this can't go in. Also, we do need tests to confirm that the messages are only being shown once.

2023-10-11 08:56 UTC, Sembauke commented
@ojeytonwilliams I think that pr is in right?

2023-10-11 09:43 UTC, ojeytonwilliams commented
Not to my knowledge, @Sembauke. Which PR are you thinking of?

2023-10-11 20:21 UTC, naomi-lgbt commented on client/src/templates/Challenges/utils/frame.ts
> +            return `${urlAddr} does not exist. Only files that can be sourced are styles.css, script.s, or remote files`;
```suggestion
            return `${urlAddr} does not exist. Only files that can be sourced are styles.css, script.js, or remote files`;
```

2023-11-05 05:48 UTC, raisedadead commented
Hey @ojeytonwilliams what's the most productive way of moving this forward? I can't seem to make any sense of the thread above 😓 ?

2023-11-06 08:40 UTC, ojeytonwilliams commented
The issue is that these warnings are shown twice.

If memory serves, we need a couple of things.

The `updatePreviewSaga` gets triggered twice and so the message appears twice. At least that's what I think is wrong. So, either that needs to not happen or this code needs to handle it.

The other thing is that we need a test (playwright, maybe?) so we don't accidentally start firing off multiple messages again.

2023-11-06 10:25 UTC, raisedadead commented
Thanks for clarifying.

@CallmeHongmaybe if you are around, please add a test to lock the feature in.


@ojeytonwilliams Do you know if there ise a dedicated thread about the `updatePreview`saga? Who is the best person to investigate and keep this going forward, OR do you have pointers so I can report an issue?

It's a shame that this PR is sitting here and isn't getting maintainer attention, and I would like to unblock progress.

2023-11-06 12:44 UTC, ojeytonwilliams commented
> Do you know if there ise a dedicated thread about the updatePreviewsaga? Who is the best person to investigate and keep this going forward, OR do you have pointers so I can report an issue?

It's a tricky one to give pointers on, but I've taken a look and I think I have a fix.

2023-11-06 12:46 UTC, ojeytonwilliams requested changes

2023-11-14 13:38 UTC, CallmeHongmaybe commented on client/src/templates/Challenges/utils/frame.ts
> +          frameContext.window.console.error(importResult);
Alrighty.

2024-02-22 09:13 UTC, Sembauke commented
Hey @CallmeHongmaybe 

Thank you for working on this, it is working great. We want to make sure your code works by adding a test sourcing the wrong files in the editor. We recently switched from Cypress to Playwright. There should be enough examples in the repository.

If you need any help writing tests, let me know.

Have a nice day and happy coding :)

2024-02-22 10:03 UTC, raisedadead approved these changes

2024-06-24 10:37 UTC, closed without merging