fix: adjust `client/tools/download-trending.ts` to work without internet connection
freeCodeCamp/freeCodeCamp pull request #51286
Opened 2023-08-15 18:39 UTC by Riley-Brown

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

## Issue
`client/tools/download-trending.ts` was attempting to fetch the latest trending data when running the `pnpm develop`  command. This was preventing being able to run without an internet connection after the first initial running of `pnpm develop`

## Fix
- Adjusts `client/tools/download-trending.ts` to attempt to load `trending.json`  on fetch error from the local file system which will exist after running `pnpm develop` the first time with a connection

2023-08-15 21:01 UTC, raisedadead requested changes
If I understand this correctly, the fetch operation will always try to get the latest file copy. If it fails, it will fall back to the local copy (hopefully available from a previous run), or it will throw.

Can we wrap this whole logic in a development mode-only flag? IDK if we can reuse one @ojeytonwilliams?

2023-08-15 22:08 UTC, naomi-lgbt commented
We should be able to use `FREECODECAMP_NODE_ENV`, I think.

2023-08-16 07:02 UTC, ojeytonwilliams commented
> We should be able to use FREECODECAMP_NODE_ENV, I think.

That makes sense to me.

2023-08-16 07:49 UTC, raisedadead commented
@Riley-Brown do you mind making this adjustment, please?

2023-08-16 14:50 UTC, naomi-lgbt commented
To clarify, the logic should be:

- If `FREECODECAMP_NODE_ENV === "production"`, fetch from CDN, throw error on failure
- Else fetch from CDN, fetch locally on failure, throw error on local fetch failure.

2023-08-16 18:02 UTC, Riley-Brown commented
Updated to check for `process.env.FREECODECAMP_NODE_ENV === 'production'`

2023-08-16 21:20 UTC, naomi-lgbt approved these changes
Logically this looks correct.

2023-09-06 12:36 UTC, raisedadead approved these changes

2023-09-06 12:37 UTC, merged