refactor: remove extra passed prop to the Map component
freeCodeCamp/freeCodeCamp pull request #51327
Opened 2023-08-18 14:14 UTC by Sboonny

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-08-18 15:57 UTC, naomi-lgbt requested changes
So my understanding was this prop allowed us to filter out the current superblock from the map when viewing that superblock: 

<img width="621" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/1aa0baed-417f-4cdd-8a17-09356242585a">

That is, Responsive Web Design should not appear under "Browse our other free certifications" because I am currently looking at the Responsive Web Design certification.

This functionality appears to have been removed in #50435 and we should confirm this is intentional before removing this prop.

2023-08-23 15:12 UTC, moT01 commented
Yes, the intention was that "All maps should look the same" (mostly) - because we want to add the progress indicators to the maps.

2023-08-23 17:01 UTC, naomi-lgbt approved these changes
Thanks for confirming Tom

2023-08-24 09:50 UTC, Sembauke approved these changes

2023-08-24 09:50 UTC, merged