fix(UI): change the button style in searchbar
freeCodeCamp/freeCodeCamp pull request #51328
Opened 2023-08-18 14:27 UTC by mmatsumoto1026

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This PR was opened to change the background color, size, and the svg `fill` color of the search and reset button in the search bar when the camper hovers over them so that solving the issues described bellow.

Issues:
- When the night mode is on, the contrast between the background color of the buttons when the camper hovers over them(`--gray-05` #f5f6f7) and the `fill` color of `Magnifier` and `InputReset` svg image(`--gray-15` #d0d0d5) is low([contrast ratio](https://webaim.org/resources/contrastchecker/) is 1.42:1) so the svg icon images might not be easily recognized by people with moderately low vision as shown in bellow image.

![nightmode](https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/ed6a91ac-3162-4be4-a904-1193935c548a)

- Again When the night mode is on, the background color of the buttons when the camper hovers over them(`--gray-05` #f5f6f7) is quite light compared to the background color of universal nav bar(`--theme-color` #0a0a23), therefore it looks inflated and pops out a bit by [contrast effect with the background or neighboring colors](https://www.hy-factory.net/read/expansion_shrink_color_en.php). (This may differ from person to person)
- When the night mode is off, the contrast between the background color of the buttons when the camper hovers over them(`--gray-85` #1b1b32) and the background color of universal nav bar(`--theme-color` #0a0a23) is low, so when the camper hovers over the reset button, it looks like the "X" reset button  image is popped out from the search form input as shown in bellow image.

![lightmode](https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/3f77c774-76a9-4ade-8ead-c6aeda9ac833)

Solutions suggested in this PR(result is as shown in bellow image):
- Change the background color of the buttons and the fill color of the SVG image so that the contrast when the camper hovers over them is high enough(contrast ratio is 5.98:1).
- Resize the buttons to make them a bit smaller to avoid having they look like inflated and pops out a bit when the camper hovers over them, and also making them look more like a button.
- Unify the background color of the button when night mode is on and off, to solve the issue when night mode is off.

![suggestion](https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/d9318bda-87ee-4358-ad5b-af7001138ff2)

I've tested the code in Chrome, Firefox, Edge, and Brave on windows 11 PC locally, and also Chrome, Safari, Opera, and Brave on iPhone SE using the ngrok.

Test condition:
- All elements in search bar are fully responsive.
- From 80% to 400% in zoom, no collapsion or overlaping of elements are occured.

2023-08-21 16:53 UTC, naomi-lgbt requested changes
I don't believe we should be rounding the corners. That doesn't match the aesthetic of any of the other buttons on our platform.

2023-08-21 23:40 UTC, mmatsumoto1026 commented
Thanks for your review, @naomi-lgbt.

And I apologize for suggesting a style for the buttons that doesn't fit with the aesthetic of any of the other buttons on fCC's platform. That was simply my overlooking, and as a result of researching various search bars when drafting this pull request. So I agree with you and would push the code without `border-radius` property after testing locally.

2023-09-20 13:43 UTC, ahmaxed commented
Thank you for your PR. I see a small space between the button and its container that did not exist previously. If that is adjusted, this pr should be good to go.

2023-09-21 00:57 UTC, mmatsumoto1026 commented
Thanks for your review, @ahmaxed.

The height of the buttons were adjusted to match the height of the search box.

2023-09-21 09:09 UTC, ahmaxed commented on client/src/components/search/searchBar/searchbar.css
>    width: 26px;
```suggestion
  width: var(--header-element-size);
```

2023-09-21 09:09 UTC, ahmaxed approved these changes

2023-09-21 09:32 UTC, Sboonny commented on client/src/components/search/searchBar/searchbar.css
> +  width: var(--header-element-size);
```suggestion
  width: 26px;
```

2023-10-03 14:51 UTC, moT01 approved these changes
LGTM :tada:

2023-10-03 17:26 UTC, naomi-lgbt approved these changes

2023-10-03 17:27 UTC, merged