feat(tools): refactor challenge tests
freeCodeCamp/freeCodeCamp pull request #51432
Opened 2023-08-29 21:19 UTC by naomi-lgbt

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

This originally started because testing the curriculum locally (specifically in non-English) is very noisy:

<img width="940" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/9d44e610-3ca6-4798-9406-995d0791fe4c">

Realistically, challenge names only need to be unique within the same block (because we use the name as the slug). So the first change was to update the tool to track names within blocks.

Then I saw the comments about throwing the errors, so I adjusted both the `ChallengeTitles` and `MongoIds` classes to return values, which are passed into an assert to properly use the test suite:

<img width="953" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/1ae3dd90-007d-4575-97f7-a85d57b39082">

2023-09-06 13:04 UTC, raisedadead approved these changes
Nice work! We need to get the titles updated before we land this in?

2023-09-06 18:22 UTC, naomi-lgbt commented
Actually, I think I can refactor this further to look at the dashed name instead - that's where the slug comes from, so I think that's all we really need to worry about being unique.

2023-09-07 15:41 UTC, ojeytonwilliams requested changes
Nice work, Naomi! Just the one nitpick:

2023-09-07 15:41 UTC, ojeytonwilliams commented on curriculum/test/test-challenges.js
> +            );
```suggestion
            const dupeTitleCheck = challengeTitles.check(dashedName, block);
```
We don't need to check `pathAndTitle` any more.

2023-09-07 15:44 UTC, ojeytonwilliams approved these changes

2023-09-07 15:44 UTC, ojeytonwilliams commented on curriculum/test/test-challenges.js
> +            );
Yeah, maybe someday.

2023-09-07 16:25 UTC, merged