fix(Curriculum): Fixed assert cases
freeCodeCamp/freeCodeCamp pull request #51491
Opened 2023-09-05 20:33 UTC by adiyadav123

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51330 

Test images
![test](https://github.com/freeCodeCamp/freeCodeCamp/assets/103302549/478f67dd-a5b7-4908-9fb6-bc17a54a459b)

2023-09-06 06:10 UTC, Sembauke requested changes

2023-09-06 06:10 UTC, Sembauke commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646c5ace05e4be4211407935.md
> +
```suggestion
```

2023-09-06 06:12 UTC, Sembauke commented
As a new contributor, we encourage you to read our [contributing guidelines](https://contribute.freecodecamp.org).

We expect our contributors to be aware of the process specific to this project. Following the guidelines religiously earns you the respect of fellow maintainers and saves everyone time.

Some examples of this are:

1. Do not edit files directly through GitHub – while you can, it's not a good idea.
2. Make sure you follow the PR checklist and not just tick things off; otherwise, we won't take you seriously.
3. Use the correct way to link issues in the description of the PR by updating the `XXXXXX`. Do not just add issue numbers everywhere and anywhere you feel like.
4. Keep mentions and review requests to a minimum. We understand you are excited about contributing, and our maintainers will get back to you as soon as they get a chance.
5. Do not work directly off your `main` branch - create a new branch for the changes you are working on.

We appreciate you taking the time to help us, and we hope to see more contributions from you.

Happy Contributing.

2023-09-08 13:00 UTC, raisedadead commented
Thanks for taking the time to contribute. We have decided to go with another PR that satisfies the needs of the issue.

We are grateful for your help and look forward to future contributions.

Happy coding!

2023-09-08 13:00 UTC, closed without merging