chore: remove redundant job
freeCodeCamp/freeCodeCamp pull request #51543
Opened 2023-09-12 16:24 UTC by ojeytonwilliams

SHOW_NEW_CURRICULUM=true is the default, so we do not need both this and
test-upcoming.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2023-09-12 17:26 UTC, naomi-lgbt requested changes
tbh we should do the opposite and make `SHOW_NEW_CURRICULUM=true` NOT the default

2023-09-13 10:03 UTC, ojeytonwilliams commented
Yeah, that makes sense. It's a bit of a chore, though, since we'd have to change the pipelines, too (they're using SHOW_NEW_CURRICULUM=true).

I'd rather not while we're in the middle of the infra changes!

2023-09-13 10:44 UTC, raisedadead commented
I agree with both of you, and we should make the switch (or even better move to proper feature flags) as soon as we use containerized setups for deployments.

2023-09-13 10:44 UTC, raisedadead approved these changes

2023-09-13 14:26 UTC, naomi-lgbt approved these changes

2023-09-13 14:26 UTC, merged