feat(e2e, playwright): adding data labels for learn page html
freeCodeCamp/freeCodeCamp pull request #51552
Opened 2023-09-15 02:36 UTC by Ahmadkashif

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-09-15 08:37 UTC, ojeytonwilliams requested changes
Cheers, @Ahmadkashif, this should be more robust.

2023-09-15 08:37 UTC, ojeytonwilliams commented on client/src/components/Intro/components/intro-description.tsx
> +      </p>
```suggestion
      {[...Array(8).keys()].map(i => (
        <p key={i} data-playwright-test-label='learn-read-this-p'>
          {t(`learn.read-this.p${i + 1}`)}
        </p>
      ))}
```
This is getting a little too bulky and repetitive, so let's DRY it.

2023-09-15 09:07 UTC, ojeytonwilliams approved these changes
LGTM 👍

2023-09-19 08:39 UTC, Ahmadkashif commented
Hi @ojeytonwilliams @raisedadead :wave: 

How can I make sure this PR moves forward?

2023-09-19 10:51 UTC, ojeytonwilliams commented
Hey @Ahmadkashif, there's nothing else you need to do. It's just that we need two reviews, so someone else needs to take a look.

I've shared the PR with the team and hopefully someone will find the time soon.

2023-09-19 11:49 UTC, Sboonny approved these changes
LGTM

2023-09-19 11:49 UTC, merged