fix: stop generating prisma client during tests
freeCodeCamp/freeCodeCamp pull request #51794
Opened 2023-10-04 09:42 UTC by ojeytonwilliams

It will be generated before the tests are run so there's no need to keep
regenerating it.

Skipping it should improve testing performance substantially.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2023-10-04 15:44 UTC, naomi-lgbt requested changes

2023-10-04 21:19 UTC, ojeytonwilliams commented on api/src/db/prisma.ts
> +    execSync('pnpm prisma db push -- --skip-generate', {
That's right, but `prisma` itself is a script (`dotenv -e ../.env prisma db push`), so the `--` is necessary to get `dotenv` to pass the command along.

It's an annoying consequence of having a single .env in the root, meaning that prisma doesn't automagically pick up on our .env.

2023-10-05 15:27 UTC, naomi-lgbt approved these changes
Okie dokie.

2023-10-05 19:44 UTC, barcaholic10 commented
Nice

2023-10-06 15:43 UTC, ShaunSHamilton approved these changes
Works better to me 👍

2023-10-06 15:44 UTC, merged