test(e2e,playwright): show.tsx
freeCodeCamp/freeCodeCamp pull request #51809
Opened 2023-10-04 17:05 UTC by anand-harsh

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51705

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/94885893/a9b57c9a-b80d-46e6-a7c0-618acf35be09)

I was getting above warning so I splitted the code into two seperate files.

2023-10-05 15:17 UTC, naomi-lgbt requested changes

2023-10-05 15:17 UTC, naomi-lgbt commented on e2e/show-button.spec.ts
> +let page: Page;
```suggestion
```

Don't need to declare this, because...

2023-10-05 15:59 UTC, anand-harsh commented
Hi @naomi-lgbt , I have tried to resolve all issues. Kindly review and suggest if something more needed.
Without seed Title test is getting failed in chromium. So I added the seed only ion title and removed from other one. Thank you for helping with the issue.

2023-10-06 14:35 UTC, anand-harsh commented
Hi @naomi-lgbt , I have tried to resolve all issues. Kindly review and suggest if something more needed.
Without seed,  Title test is getting failed in chromium. So I added the seed only in title and removed from other one. Thank you for helping with the issue.

2023-10-07 05:56 UTC, anand-harsh commented
Hi @naomi-lgbt , I have resolved the issues. Kindly review and suggest if something more needed.
Without seed, Title test is getting failed in chromium. So I added the seed only in title and removed from other one. Thank you for helping with the issue.

2023-10-07 16:59 UTC, jdwilkin4 commented
HI @anand-harsh ! 

I removed the closes keyword from your PR because we don't want to close the hacktoberfest issue because it needs to stay open for multiple contributors 

You should only use the closes keyword when you want to automatically close an issue after the PR has been approved and merged.
In this case, we only want to simply mention it.

Thanks for understanding 👍

2023-10-07 23:24 UTC, anand-harsh commented
> HI @anand-harsh !
> 
> I removed the closes keyword from your PR because we don't want to close the hacktoberfest issue because it needs to stay open for multiple contributors
> 
> You should only use the closes keyword when you want to automatically close an issue after the PR has been approved and merged. In this case, we only want to simply mention it.
> 
> Thanks for understanding 👍

Sure Sir

2023-10-08 16:09 UTC, anand-harsh commented
Hi @naomi-lgbt, @huyenltnguyen , I have resolved the issues. Kindly review and suggest if something more needed.
Without seed, Title test is getting failed in chromium. So I added the seed only in title and removed from other one. Thank you for helping with the issue.

2023-10-11 06:35 UTC, huyenltnguyen reviewed
Looking at this again, I think we should consolidate the test files instead of having one for the button and one for the title.

2023-10-11 08:14 UTC, anand-harsh commented
> Looking at this again, I think we should consolidate the test files instead of having one for the button and one for the title.

Done this change. I consolidated both files in a single file and it is running now.

2023-10-11 15:04 UTC, anand-harsh commented
> Looking at this again, I think we should consolidate the test files instead of having one for the button and one for the title.

Hi @huyenltnguyen , Done this change. I consolidated both files in a single file and it is running now. Kindly check and suggest if more changes needed.

2023-10-11 18:46 UTC, naomi-lgbt approved these changes

2023-10-12 10:26 UTC, anand-harsh commented
@huyenltnguyen I did the changes and deleted seed and beforAll.

2023-10-12 18:10 UTC, naomi-lgbt approved these changes
A quick note that you don't need to continuously merge `main` into this branch.

Also, you shouldn't work directly off of your `main` branch.

2023-10-12 18:22 UTC, anand-harsh commented
> A quick note that you don't need to continuously merge `main` into this branch.
> 
> Also, you shouldn't work directly off of your `main` branch.

Sure, I will take care of this.

2023-10-13 04:39 UTC, huyenltnguyen approved these changes

2023-10-13 07:34 UTC, closed without merging