Changed example to fit the solution
freeCodeCamp/freeCodeCamp pull request #51810
Opened 2023-10-04 19:42 UTC by pushkar707

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50490

2023-10-04 20:06 UTC, lasjorg requested changes

2023-10-04 20:06 UTC, lasjorg commented on curriculum/challenges/english/03-front-end-development-libraries/sass/nest-css-with-sass.md
>    }
```suggestion
  ul {
    color: blue;
  }
```

2023-10-04 20:06 UTC, lasjorg commented on curriculum/challenges/english/03-front-end-development-libraries/sass/nest-css-with-sass.md
>    }
Please remove the extra spaces.

2023-10-04 21:49 UTC, jeremylt commented
This wasn't the example given in the linked issue.

Please use the changes agreed upon in the issue.

Also, please read and follow the [contribution guidelines](https://contribute.freecodecamp.org/) and the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).

2023-10-04 22:36 UTC, lasjorg commented
I would be fine with using @pushkar707 example. I would prefer if the div was a `section` or `article` element but that isn't super important.

I think using the descendant combinator is probably a good idea anyway.


```
article {
  height: 200px;
}

article p {
  color: white;
}

article ul {
  color: blue;
}
```

Or (I'm not married to the actual styles, they are just an example)

```
.products {
  width: min(1400px, 90%);
  margin-inline: auto;
}

.products article {
  padding: 1rem;
}

.products p {
  font-size: 1.2rem;
  line-height: 1.4;
}
```

I'm fine with either.

2023-10-05 02:51 UTC, pushkar707 commented
> I would be fine with using the example from @pushkar707. I would prefer if the div was a `section` or `article` element but that isn't super important.
> 
> I think using the descendant combinator is probably a good idea anyway.
> 
> 
> ```
> article {
>   height: 200px;
> }
> 
> article p {
>   color: white;
> }
> 
> article ul {
>   color: blue;
> }
> ```
> 
> Or (I'm not married to the actual styles, they are just an example)
> 
> ```
> .products {
>   width: min(1400px, 90%);
>   margin-inline: auto;
> }
> 
> .products article {
>   padding: 1rem;
> }
> 
> .products p {
>   font-size: 1.2rem;
>   line-height: 1.4;
> }
> ```
> 
> I'm fine with either.
> 
> ---
> 
> > I fixed the linking to the issue.
> 
> Thanks for catching that.

Okay @lasjorg,  I will fix the spaces and use your example. Should I also make a new Pr from a seperate branch or should I update this one?

2023-10-05 03:14 UTC, jeremylt commented
> please read and follow the contribution guidelines and the how to open a pull request guide.

These documents will tell you how to name your PR ;)

I keep unchecking boxes for you because if your PR isn't named per our naming conventions, then you haven't read these documents!

2023-10-05 15:32 UTC, closed without merging