test(e2e,playwright): FourOhFour component
freeCodeCamp/freeCodeCamp pull request #51827
Opened 2023-10-05 22:48 UTC by ArjunSingh-Rawat

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

resolves "UI Components/FourOhFour" https://github.com/freeCodeCamp/freeCodeCamp/issues/51705

camperbot cant code

2023-10-11 15:42 UTC, naomi-lgbt requested changes

2023-10-11 15:42 UTC, naomi-lgbt commented on e2e/four-oh-four.spec.ts
> +  test('should display 404 quote', async () => {
```suggestion
  test('should display 404 quote', async ({ page }) => {
```

2023-10-11 15:42 UTC, naomi-lgbt commented on e2e/four-oh-four.spec.ts
> +  test('should display curriculum link', async () => {
```suggestion
  test('should display curriculum link', async ({ page }) => {
```

2023-10-12 17:16 UTC, naomi-lgbt approved these changes
Looks good. You'll need to update this branch to the latest version of main for the tests to pass.

2023-10-12 18:16 UTC, ArjunSingh-Rawat commented
Hi, @naomi-lgbt I am new to contributing and this is my first pr, should i commit again with updated brach

2023-10-12 18:30 UTC, naomi-lgbt commented
Yes, you'll want to fetch the upstream `main`, merge it into your branch, and push the merge commit.

If you have questions or get stuck, feel free to ask in our [discord](https://discord.gg/PRyKn3Vbay).

2023-10-13 08:22 UTC, huyenltnguyen approved these changes

2023-10-13 16:38 UTC, closed without merging