test(e2e): exam show tests
freeCodeCamp/freeCodeCamp pull request #51840
Opened 2023-10-06 14:02 UTC by dzmdre

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-10-06 14:03 UTC, dzmdre commented
Looks like I have no "pnpm run seed:exams" on ci and can not click on the Start exam button
https://discord.com/channels/692816967895220344/715074489422970962/1159520223645409321

2023-10-06 14:19 UTC, dzmdre commented
Blocked by #51841

2023-10-10 06:36 UTC, dzmdre commented
Please  review

2023-10-11 18:09 UTC, naomi-lgbt requested changes

2023-10-11 18:09 UTC, naomi-lgbt commented on .github/workflows/e2e-playwright.yml
We should probably extrapolate this change to its own PR.

2023-10-11 19:47 UTC, naomi-lgbt approved these changes

2023-10-13 16:33 UTC, dzmdre commented on e2e/exam-started-show.spec.ts
> +      }
@huyenltnguyen thank you for your  review points. Just one more question from my side: should  we check  (test if its clickable) every radio button on every page?

2023-10-18 05:55 UTC, huyenltnguyen approved these changes
LGTM 👍

2023-10-18 16:04 UTC, merged