test(e2e,playwright): ms-trophy-show.tsx
freeCodeCamp/freeCodeCamp pull request #51855
Opened 2023-10-07 05:50 UTC by anand-harsh

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51705 

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/94885893/0ee56935-9993-40e2-bc74-909272ec503f)

2023-10-09 15:42 UTC, Ahmadkashif requested changes
Thank you for this amazing attempt @anand-harsh 💯 

I'll just add a few minor suggestions to try and improve this PR a little more.

2023-10-09 15:42 UTC, Ahmadkashif commented on e2e/ms-trophy-show.spec.ts
> +const verifyTrophy = translations.buttons['verify-trophy'];
```suggestion
const verifyTrophyButtonText = translations.buttons['verify-trophy'];
```

2023-10-09 15:42 UTC, Ahmadkashif commented on e2e/ms-trophy-show.spec.ts
> +const askForHelpButton = translations.buttons['ask-for-help'];
```suggestion
const askForHelpButtonText = translations.buttons['ask-for-help'];
```

2023-10-09 15:42 UTC, Ahmadkashif commented on e2e/ms-trophy-show.spec.ts
> +  const askHelp = page.getByTestId('verify-trophy-button');
```suggestion
  const askHelp = page.getByRole('button', { name: verifyTrophyButtonText })
    ).toBeVisible();
```

2023-10-09 15:42 UTC, Ahmadkashif commented on e2e/ms-trophy-show.spec.ts
> +  await expect(askHelp).toBeVisible();
```suggestion
```

2023-10-09 15:42 UTC, Ahmadkashif commented on e2e/ms-trophy-show.spec.ts
> +  await expect(askHelp).toContainText(verifyTrophy);
if this fails, try .toHaveText() or the suitable call from documentation.

2023-10-09 15:42 UTC, Ahmadkashif commented on e2e/ms-trophy-show.spec.ts
> +  const checkAnswer = page.getByTestId('ask-for-help-button');
```suggestion
  const checkAnswer = page.getByRole('button', { name: askForHelpButtonText })
    ).toBeVisible();
```

2023-10-09 15:42 UTC, Ahmadkashif commented on e2e/ms-trophy-show.spec.ts
> +  await expect(checkAnswer).toBeVisible();
```suggestion
```

2023-10-09 16:29 UTC, anand-harsh commented
@Ahmadkashif I have tried resolving all issues. Kindly check and suggest if something more needed. Thanks for helping me with this.

2023-10-10 17:42 UTC, Ahmadkashif approved these changes
LGTM

2023-10-11 18:07 UTC, naomi-lgbt approved these changes

2023-10-11 18:07 UTC, merged

2023-10-11 18:07 UTC, naomi-lgbt commented
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉