test(e2e,playwright): link-ms-user component
freeCodeCamp/freeCodeCamp pull request #51888
Opened 2023-10-10 06:03 UTC by shabeebk

With this commit, the playwright will test the  link-ms-user component for possible view for signedin/sighedout user.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #https://github.com/freeCodeCamp/freeCodeCamp/issues/51705

2023-10-10 06:03 UTC, shabeebk commented
camperbot cant code

2023-10-11 18:05 UTC, naomi-lgbt requested changes
This is looking good. Shouldn't need a global page variable, though.

2023-10-11 18:05 UTC, naomi-lgbt commented on e2e/link-ms-user.spec.ts
> +});
```suggestion
test.beforeEach(async ({ page }) => {
  await page.goto(
    '/learn/foundational-c-sharp-with-microsoft/write-your-first-code-using-c-sharp/trophy-write-your-first-code-using-c-sharp'
  );
});

test.afterEach(async ({ page }) => {
  await page.close();
});
```

2023-10-11 18:05 UTC, naomi-lgbt commented on e2e/link-ms-user.spec.ts
> +let page: Page;
```suggestion
import { test, expect } from '@playwright/test';
import translations from '../client/i18n/locales/english/translations.json';
```

2023-10-11 18:05 UTC, naomi-lgbt commented on e2e/link-ms-user.spec.ts
> +  test('Component has proper main heading and relevant sections', async () => {
```suggestion
  test('Component has proper main heading and relevant sections', async ({ page }) => {
```

2023-10-11 18:05 UTC, naomi-lgbt commented on e2e/link-ms-user.spec.ts
> +  test('Component has proper main heading and relevant sections', async () => {
```suggestion
  test('Component has proper main heading and relevant sections', async ({ page }) => {
```

2023-10-11 18:05 UTC, naomi-lgbt commented on e2e/link-ms-user.spec.ts
> +  test('Component has proper list of actions', async () => {
```suggestion
  test('Component has proper list of actions', async ({ page }) => {
```

2023-10-11 18:09 UTC, shabeebk commented
Adapted the suggestion and applied the commits.

2023-10-11 18:24 UTC, shabeebk reviewed
Accepted changes

2023-10-12 17:18 UTC, naomi-lgbt approved these changes

2023-10-12 21:10 UTC, moT01 approved these changes
LGTM @shabeebk :tada: Thanks for contributing to freeCodeCamp and happy hacktoberfest :tada:

2023-10-12 21:10 UTC, merged