chore: bump the required node version
freeCodeCamp/freeCodeCamp pull request #51916
Opened 2023-10-11 17:26 UTC by huyenltnguyen

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Bumps the required Node version to v18 as v16 is no longer maintained. This change also makes the CI and local environments consistent as we have already been running our CI jobs on Node 18.

2023-10-12 04:33 UTC, raisedadead commented
We might want to jump straight to v20 correct @ojeytonwilliams?

2023-10-12 09:28 UTC, ojeytonwilliams commented
Yeah, it's becoming LTS on the 24th, so I think we can go to 20 now.

For the CI, it's a little awkward. In an ideal world we'd test against both 18 and 20 until we're using 20 in production, but we're already queuing up a ton of actions as it is. Maybe we should just move to 20 in CI, too. What do you reckon?

2023-10-13 11:22 UTC, raisedadead commented
Yes - I agree

2023-10-13 13:33 UTC, ojeytonwilliams requested changes
Alrighty, then let's go with 20 here and I'll create a quick PR for CI.

2023-10-13 13:33 UTC, ojeytonwilliams commented on package.json
> +    "node": ">=18",
```suggestion
    "node": ">=20",
```

2023-10-13 15:07 UTC, ojeytonwilliams commented
Absolutely. Feel free to close my PR in favour of this one, if that works for you.

2023-10-13 15:27 UTC, closed without merging

2023-10-13 16:11 UTC, ojeytonwilliams commented
Thanks, @huyenltnguyen!