Editor
freeCodeCamp/freeCodeCamp pull request #51915
Opened 2023-10-11 17:01 UTC by Aman1919

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

related to  https://github.com/freeCodeCamp/freeCodeCamp/issues/51705

2023-10-11 19:24 UTC, naomi-lgbt requested changes

2023-10-11 19:24 UTC, naomi-lgbt commented on e2e/editor.spec.ts
> +});
```suggestion
test.beforeEach(async ({ page }) => {
  await page.goto(
    '/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-2'
  );
});

test.afterEach(async () => {
  await page.close();
});
```

Ideally we run the tests in isolation.

2023-10-11 19:24 UTC, naomi-lgbt commented on e2e/editor.spec.ts
> +let page: Page;
```suggestion
import { test, expect } from '@playwright/test';
```

We don't need a global page because...

2023-10-11 19:24 UTC, naomi-lgbt commented on e2e/editor.spec.ts
> +  test('Should be clicked and able to insert text', async () => {
```suggestion
  test('Should be clicked and able to insert text', async ({ page }) => {
```

We can get the `page` directly from the function args.

2023-10-12 19:06 UTC, naomi-lgbt approved these changes

2023-10-13 06:09 UTC, Ahmadkashif approved these changes

2023-10-13 07:26 UTC, huyenltnguyen approved these changes

2023-10-13 07:26 UTC, merged