test(e2e,playwright): OfflineWarning
freeCodeCamp/freeCodeCamp pull request #51910
Opened 2023-10-11 13:44 UTC by moradelboca

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51705 OfflineWarning Component

Draft PR as required to help with coding.

2023-10-17 20:15 UTC, Amit-Morade commented
Can I work on this?

2023-10-17 20:45 UTC, moradelboca commented
> Can I work on this?

Of course! Idk if I have to give you permissions or something like that in order to contribute to this PR. Any clue?

2023-11-07 19:16 UTC, moradelboca commented
> Hey @moradelboca, I noticed that this PR is still a draft. Is there anything we can help you with to get the PR ready for review?

I don't know what am I doing wrong. I created this PR to see if anyone had any idea.. a mod told me to do that in the ds server, but seems this isn't a good solution.
Any clue?

2023-11-09 18:48 UTC, Ahmadkashif requested changes
Hi @moradelboca 

Thank you for the PR. 

The error logs suggest that the first try to fetch the id for ofline-warning is failing. 

Can you try and fetch the id using our prescribed way? 
You can find the guidelines under the "how to contribute playwright tests" section on our docs.

2023-11-09 18:48 UTC, Ahmadkashif commented on client/src/components/OfflineWarning/offline-warning.tsx
>        <div className='offline-warning alert-info'>{message}</div>
```suggestion
       <div className='offline-warning alert-info'  data-playwright-test-label='offline-warning' >{message}</div>
```
We don't wanna add a specific div for identifying the element.

2023-11-09 18:48 UTC, Ahmadkashif commented on client/src/components/OfflineWarning/offline-warning.tsx
> +    <div data-playwright-test-label='offline-warning'>
```suggestion
```

2023-11-09 18:48 UTC, Ahmadkashif commented on client/src/components/OfflineWarning/offline-warning.tsx
> +    </div>
```suggestion
```

2023-11-30 01:05 UTC, rahulsuresh-git commented
@Ahmadkashif @moradelboca Is this still open?

2023-11-30 09:15 UTC, closed without merging