test(e2e,playwright): SEO component
freeCodeCamp/freeCodeCamp pull request #51949
Opened 2023-10-13 09:34 UTC by IgorShcherba

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51705

2023-10-13 09:35 UTC, IgorShcherba commented
camperbot cant code

2023-10-13 16:29 UTC, naomi-lgbt requested changes

2023-10-13 16:29 UTC, naomi-lgbt commented on e2e/seo.spec.ts
> +
```suggestion
```

We actually don't need this. Playwright will close the page automatically.

2023-10-18 21:43 UTC, naomi-lgbt requested changes
This will need an update with the latest state of `main` to get the tests passing. :3

2023-10-19 16:42 UTC, naomi-lgbt approved these changes

2023-10-22 11:10 UTC, huyenltnguyen approved these changes

2023-10-22 17:32 UTC, Ahmadkashif approved these changes

2023-10-24 16:36 UTC, merged