refactor/simplify playwright test: landing.spec.ts
freeCodeCamp/freeCodeCamp pull request #51977
Opened 2023-10-15 04:09 UTC by anand-harsh

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

#51705

2023-10-15 05:20 UTC, anand-harsh commented
Tests are passing in local but failing here. Why is it so?

2023-10-17 15:18 UTC, anand-harsh commented on e2e/landing.spec.ts
> +    }
I have updated the PR, can you please check if the changes are ok and suggest if some more needed. I can't replace it with getByText as there are card components like pieces and components of each card has been taken by getByTestId here.

2023-10-17 15:19 UTC, anand-harsh commented
@huyenltnguyen I have updated the PR, can you please check if the changes are ok and suggest if some more needed. I can't replace it with getByText as there are card components like pieces and components of each card has been taken by getByTestId here.

2023-10-18 06:57 UTC, huyenltnguyen approved these changes

2023-10-18 16:07 UTC, naomi-lgbt requested changes

2023-10-18 16:07 UTC, naomi-lgbt commented on e2e/landing.spec.ts
> +    await expect(btn).toContainText(superBlocks[item]);
```suggestion
  for (let index = 0; index < superBlocks.length; index++) {
    const btn = curriculumBtns.nth(index);
    await expect(btn).toContainText(superBlocks[index]);
```

Nitpick, but if we're going to deviate from the standard `i` for loop iterators, we should at least name it correctly.

2023-10-18 21:42 UTC, naomi-lgbt approved these changes

2023-10-18 21:42 UTC, merged