test(e2e,playwright): form-helper component
freeCodeCamp/freeCodeCamp pull request #51974
Opened 2023-10-14 18:09 UTC by shabeebk

With this commit, the playwright will test the  form-helper component for possible form views w/ and w/o github link.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #51705

2023-10-18 15:25 UTC, naomi-lgbt requested changes

2023-10-18 15:25 UTC, naomi-lgbt commented on e2e/form-helper.spec.ts
> +});
```suggestion
```

We don't need this - playwright does it automatically.

2023-10-18 16:23 UTC, shabeebk commented
Thanks for the review @naomi-lgbt. Applied the suggestion.

2023-10-18 16:54 UTC, shabeebk commented
I had to fix the lint and re-push the branch.

2023-10-18 20:06 UTC, naomi-lgbt approved these changes

2023-10-18 21:35 UTC, moT01 approved these changes
LGTM @shabeebk 🎉 Thanks for contributing to freeCodeCamp and happy hacktoberfest 🎉

2023-10-18 21:35 UTC, merged

2023-10-19 04:54 UTC, shabeebk commented
Thanks team.