style: tab text is hidden in lightmode
freeCodeCamp/freeCodeCamp pull request #52006
Opened 2023-10-17 07:19 UTC by nandirb

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51958

## Changes
### Tab 1
<img width="935" alt="old-1" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/58172661/50eea5b6-71ac-4400-bd3e-db602618b5e0">
<img width="935" alt="new-1" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/58172661/aeec6160-63e8-4586-8744-10944b9f5830">

### Tab 2
<img width="946" alt="old-2" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/58172661/ca9edc2a-fb43-4df7-931e-912bbff0d2ab">
<img width="946" alt="new-2" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/58172661/c7621bab-fd3b-4e6f-af7b-d6d6bc2bdd30">

2023-10-17 07:30 UTC, gikf requested changes
Hello,

Firstly, thank you for submitting this pull request!

This isn't what should be done to resolve the linked issue. See https://github.com/freeCodeCamp/freeCodeCamp/issues/51958#issuecomment-1765691688

Please note, there's no need to close this PR. If you have questions or need guidance refining your contribution, don't hesitate to ask. Our community is here to assist.

Thank you for your enthusiasm in contributing to our project. We eagerly await more contributions from you!

**Happy Contributing!** 🌟

2023-10-17 07:42 UTC, nandirb commented
@gikf  This issue was labeled under "**first timers only**"

According to your contribution documentation, an issue with the [first timers only](https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only) label is open for contribution

2023-10-17 07:45 UTC, nandirb commented
@ShaunSHamilton was commented on this issue that "An issue with the "first timers only label" is open for contribution. The first comprehensive PR created will be reviewed and merged"

2023-10-17 07:51 UTC, gikf commented
Hey @nandirb,

yes, that issue is open for contribution. At the same time linked comment - https://github.com/freeCodeCamp/freeCodeCamp/issues/51958#issuecomment-1765691688 - specified what exactly should be changed. Tabs should be removed and only information related to macOS/Linux should remain. That's not what this PR is changing.

2023-10-17 07:51 UTC, Sboonny commented
Hi @nandirb, please note that the issue is ready for contribution, but your solution doesn't align with what is needed to close the issue.

2023-10-17 07:54 UTC, nandirb commented
Thank you for your clarification @Sboonny and @gikf . If I remove the tab and remain only information related to macOS/Linux, could this issue be closed?

2023-10-17 08:04 UTC, gikf commented
No need to close the PR. If you push further commits to the PR branch - `nandirb:style/docs-tab-text-is-hidden-in-lightmode`, they will be added to this PR.

2023-10-17 09:49 UTC, Shreya1chaturvedi commented
hiii can i contribute to ur issue?

2023-10-20 13:42 UTC, gikf commented
Hey

Thank you for opening this pull request.

As there was different PR - #52018 - making all necessary changes, merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

2023-10-20 13:42 UTC, closed without merging