fix:Content misalignment on the profile page
freeCodeCamp/freeCodeCamp pull request #52008
Opened 2023-10-17 10:44 UTC by RickDeb2004

Checklist:

- [ done] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [done ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ done] My pull request targets the `main` branch of freeCodeCamp.
- [ done] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/113274631/b2f06f3f-a26e-4108-aa7a-1c3ea1f720d7)

2023-10-17 14:10 UTC, moT01 requested changes
This doesn't seem to fix the issue as-is @RickDeb2004. Just to clarify, your screen shot is on the [curriculum map](https://www.freecodecamp.org/learn) - the issue is on [a profile page](https://www.freecodecamp.org/mot01). I loaded up this PR and the buttons were still misaligned. I did a little digging and found that the problem was introduced on [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/51322) Hey @Sboonny, was this something that was just missed on that PR? or is something not working as expected?

2023-10-17 14:10 UTC, moT01 commented on client/src/components/profile/components/certifications.tsx
> +        <Col className='certifications text-center' sm={10} smPush={1}>
```suggestion
        <Col className='certifications' sm={10} smOffest={1}>
```

2023-10-19 03:07 UTC, RickDeb2004 commented
> This doesn't seem to fix the issue as-is @RickDeb2004. Just to clarify, your screen shot is on the [curriculum map](https://www.freecodecamp.org/learn) - the issue is on [a profile page](https://www.freecodecamp.org/mot01). I loaded up this PR and the buttons were still misaligned. I did a little digging and found that the problem was introduced on [this PR.](https://github.com/freeCodeCamp/freeCodeCamp/pull/51322) Hey @Sboonny, was this something that was just missed on that PR? or is something not working as expected?
> 
> Can you update the PR description so that it closes the associated issue @RickDeb2004. Also, make sure you do all the tasks in the PR checklist.

not able to see my changes as I have done some changes in profile directory.

2023-10-19 03:09 UTC, RickDeb2004 commented
> Checklist:
> 
> * [ done] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
> * [done ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
> * [ done] My pull request targets the `main` branch of freeCodeCamp.
> * [ done] I have tested these changes either locally on my machine, or GitPod.
> 
> Closes #XXXXX ![image](https://user-images.githubusercontent.com/113274631/275805720-b2f06f3f-a26e-4108-aa7a-1c3ea1f720d7.png)

close: #51955

2023-10-19 03:53 UTC, huyenltnguyen requested changes

2023-10-19 05:40 UTC, Sboonny commented
> Hey @Sboonny, was this something that was just missed on that PR? or is something not working as expected?

Hi @moT01, although I remember fixing this by adding `relative` className, it isn't there 🤔, so it is something missed that should have been accounted for in that PR. 

if this is merged with the switching to `smOffset`, please delete the logic around `smPush` as it is no longer necessary

2023-10-19 11:04 UTC, huyenltnguyen approved these changes

2023-10-24 21:28 UTC, moT01 approved these changes
LGTM @RickDeb2004 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

2023-10-24 21:28 UTC, merged