test(e2e, playwright): solution-viewer
freeCodeCamp/freeCodeCamp pull request #52016
Opened 2023-10-18 05:29 UTC by Insidiae

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #51705 

camperbot cant code

2023-10-18 16:03 UTC, naomi-lgbt requested changes

2023-10-18 16:03 UTC, naomi-lgbt commented on e2e/solution-viewer.spec.ts
> +});
```suggestion
```

We actually don't need this. Playwright does it automatically.

2023-10-18 20:05 UTC, naomi-lgbt approved these changes

2023-10-19 12:22 UTC, ahmaxed approved these changes

2023-10-19 12:22 UTC, merged