test(e2e,playwright): Landing, Header
freeCodeCamp/freeCodeCamp pull request #52104
Opened 2023-10-25 21:14 UTC by onukwilip

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Ref #51705 - Landing

2023-10-25 21:14 UTC, onukwilip commented
camperbot cant code

2023-10-26 16:57 UTC, naomi-lgbt requested changes
This will need a rebase with `main`. If you have questions on how to do that, feel free to pop in our Discord and we'll be happy to help.

2023-10-26 17:11 UTC, onukwilip commented
Thanks ☺️! Will do that

2023-10-27 23:36 UTC, onukwilip commented
Thanks for the review! I've successfully rebased with the `main` branch as per the steps you provided on the Discord server 😊

2023-11-03 05:42 UTC, onukwilip commented on e2e/landing.spec.ts
> +});
Ok, thanks. Will resolve that ☺️

2023-11-03 05:45 UTC, onukwilip commented
Thanks for the help ☺️. I'm apply the requested changes

2023-11-03 18:09 UTC, huyenltnguyen approved these changes
LGTM 👍 Thank you for your contribution @onukwilip!

2023-11-03 19:28 UTC, onukwilip commented
Happy to ☺️

2023-11-03 21:24 UTC, naomi-lgbt approved these changes

2023-11-03 21:24 UTC, merged