fix: check for margin-left and margin-right not present
freeCodeCamp/freeCodeCamp pull request #52202
Opened 2023-11-02 04:17 UTC by RockyPukar1

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52181

In this code update, I have checked to make sure that  margin-left and margin-right are not present so campers cannot use ```margin: 5px``` or ```margin: 5px 0``` or ```margin: 5px 0 5px 0``` which will set margin-left and margin-right. The campers have to compulsorily use ```margin-top: 5px``` and ```margin-bottom: 5px```.

2023-11-09 17:40 UTC, Sembauke approved these changes

2023-11-09 17:42 UTC, naomi-lgbt requested changes
nit

2023-11-09 17:42 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45a276c093334f0f6e9df4.md
> +Your `p` element nested in your `.item` elements should not have `margin-left`.
```suggestion
Your `p` elements nested in your `.item` elements should not have a `margin-left` set.
```

2023-11-09 17:42 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f45a276c093334f0f6e9df4.md
> +Your `p` element nested in your `.item` elements should not have `margin-right`.
```suggestion
Your `p` elements nested in your `.item` elements should not have a `margin-right` set.
```

2023-11-10 05:05 UTC, RockyPukar1 commented
@naomi-lgbt The requested change has been made.

2023-11-10 06:13 UTC, naomi-lgbt approved these changes

2023-11-10 06:13 UTC, merged

2023-11-10 06:13 UTC, naomi-lgbt commented
Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 🎉