docs: add playwright guide to /contribute sidebar
freeCodeCamp/freeCodeCamp pull request #52293
Opened 2023-11-08 18:24 UTC by huyenltnguyen

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Adds playwright guide to /contribute sidebar, because I keep finding myself going back to the Hacktoberfest issue to grab the link.

## Screenshots

<img width="1680" alt="Screenshot 2023-11-09 at 01 17 39" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/511535f5-78c2-4202-926e-de842bdabc67">

2023-11-08 19:11 UTC, gikf approved these changes

2023-11-09 09:44 UTC, raisedadead approved these changes

2023-11-09 09:45 UTC, raisedadead requested changes

2023-11-09 09:45 UTC, raisedadead commented on docs/_sidebar.md
> +  - [Work on Cypress Tests](how-to-add-cypress-tests.md)
You know what? Let's deprioritize this and move to the additional guides section while we are updating the sidebar.

2023-11-12 07:03 UTC, raisedadead approved these changes

2023-11-12 08:19 UTC, merged