Update README.md
freeCodeCamp/freeCodeCamp pull request #52323
Opened 2023-11-11 05:38 UTC by Sanober494

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

In README.md, Line 37 states "Here are our ten core certifications:", when there are actually 12 certifications mentioned below it.

2023-11-11 14:21 UTC, Sanober494 commented
In README.md, Line 37 states "Here are our ten core certifications:", when there are actually 12 certifications mentioned below it, this change is necessary since it doesn't reflect the actual number of courses below.

2023-11-12 08:39 UTC, Sanober494 commented
Yes, I have made the necessary changes.

2023-11-12 12:38 UTC, raisedadead requested changes

2023-11-12 12:38 UTC, raisedadead commented on README.md
> +Here are our 12 core certifications:
```suggestion
Here are our twelve core certifications:
```

2023-11-13 02:22 UTC, huyenltnguyen approved these changes

2023-11-20 18:34 UTC, naomi-lgbt approved these changes

2023-11-24 05:10 UTC, merged