feat(curriculum): add start to next 3 English blocks
freeCodeCamp/freeCodeCamp pull request #52368
Opened 2023-11-15 19:22 UTC by moT01

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-11-21 21:03 UTC, nieldakarla requested changes
Capitalized some words.

2023-11-21 21:03 UTC, nieldakarla commented on client/i18n/locales/english/intro.json
> +        "title": "Learn How to use Code-related Concepts and Terms",
```suggestion
        "title": "Learn How to Use Code-related Concepts and Terms",
```

Capitalized Use

2023-11-21 22:00 UTC, moT01 commented
Thanks for the review @nieldakarla :tada: I added your suggestions.

2023-11-24 18:55 UTC, nieldakarla approved these changes

2023-11-27 16:32 UTC, huyenltnguyen approved these changes

2023-11-28 19:05 UTC, moT01 commented on curriculum/challenges/_meta/learn-how-to-analyze-code-documentation/meta.json
> +  "helpCategory": "HTML-CSS"
Yup. I suppose we could change these files now, before it exists.

2023-11-28 19:05 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +      },
fixed 👍

2023-11-28 19:06 UTC, moT01 commented
Thanks for taking a look @huyenltnguyen 👍 I added some of your suggestions.

2023-11-29 03:03 UTC, huyenltnguyen approved these changes
LGTM

2023-11-29 12:47 UTC, Sembauke approved these changes

2023-11-29 12:47 UTC, merged