feat(curriculum): English Morning Evening Routine
freeCodeCamp/freeCodeCamp pull request #52393
Opened 2023-11-20 17:34 UTC by nieldakarla

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-12-15 05:21 UTC, moT01 reviewed
This looks real good @nieldakarla 🎉 

I didn't look over it too hard, mainly just went through it to make sure everything is working. The one main thing I didn't like is with the descriptions. Many of them could be shortened/condensed I think. They often have many instances of one or two sentences on their own line. I think they many times they could be combined into a few short paragraphs instead of something like 5 sentences, each on their own line. It looks a little weird in my opinion. I left some comments on a few of the challenges about this. There's a few that use quite a few examples, as well - maybe just a preference of mine, but I would try to stick with one or two examples to try and keep it shorter.

A few other things that I could mention:
- I noticed one challenge that had the examples in a bulleted list. I don't think any others did. I would try to keep things consistent and maybe not use that list.
- Some of the feedback is quite generic. e.g. "That's not right." This isn't really a problem, we default to a generic response like that if feedback isn't provided.

2023-12-15 14:40 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/65569ebbc9ef9f7b5b99827b.md
> +Listen to the audio and fill in the blank with the correct word that completes the sentence.
We discussed in the meeting to include this in each fill in the blank challenge, I thought? I've been adding:

```md
# --instructions--

Listen to the audio to complete the sentence below.
```

2023-12-15 15:41 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/65569ebbc9ef9f7b5b99827b.md
> +Listen to the audio and fill in the blank with the correct word that completes the sentence.
That's fine, I would put it in the `# --instructions--` header then.

2023-12-16 15:29 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/65569ebbc9ef9f7b5b99827b.md
> +Listen to the audio and fill in the blank with the correct word that completes the sentence.
For challenges that have actual content in the description I'll just delete this instruction.

2023-12-16 16:48 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/6557995f0d97e1b2837a3081.md
> +Remember: adjectives are words that describe or give more information about nouns. They can tell you how something looks, feels, or acts. For example:
@moT01 Thank you for the review! =D 

I think I've committed the changes you suggested. When you can, please have a look.

2023-12-18 23:44 UTC, naomi-lgbt requested changes

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/6557d782bc7613c06aa7dafd.md
> +The word `never` is an adverb used to mean "not at any time" or "not ever". It's often used to talk about things that someone doesn't do or hasn't done. For example:
```suggestion
The word `never` is an adverb used to mean `not at any time` or `not ever`. It's often used to talk about things that someone doesn't do or hasn't done. For example:
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/6557dc1aa6be93c1eb4e9efb.md
> +`if` doesn't suggest certainty of finding urgent updates.
```suggestion
`If` doesn't suggest certainty of finding urgent updates.
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/6557e026c053f9c362a1983e.md
> +Use the gerund of the ver `to come`
```suggestion
Use the gerund of the verb `to come`
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a21f5512be1f7dbfe4cad.md
> +If you add `y`to the noun `sleep`, You create the adjective `sleepy` which means feeling a need to sleep or being tired.
```suggestion
If you add `y` to the noun `sleep`, you create the adjective `sleepy` which means feeling a need to sleep or being tired. 
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a21f5512be1f7dbfe4cad.md
> +`Rain`+ `y` = `rainy` (having a lot of rain)
```suggestion
`snow` + `y` = `snowy` (having a lot of snow)
`rain` + `y` = `rainy` (having a lot of rain)
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a3132c16520fe6bf8f9be.md
> +`Multiple times` means "many times" or on "several occasions". It's used to indicate that an action or event happens repeatedly. For example:
```suggestion
`Multiple times` means many times or on several occasions. It's used to indicate that an action or event happens repeatedly. For example:
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a367638e3f401eb0235ea.md
> +
```suggestion
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a4e0c1176be0e1b785c96.md
> +The adverb `immediately` means "without delay" or "right away". It's used to emphasize the urgency or the need to do something at once. For example:
```suggestion
The adverb `immediately` means without delay or right away. It's used to emphasize the urgency or the need to do something at once. For example:
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a8b62e5681235c3fb5492.md
> +Let's review the usage of `them`and `their`. `Them` is used to refer to multiple people previously mentioned, and `their` shows possession or belonging to these people. For example:
```suggestion
Let's review the usage of `them` and `their`. `Them` is used to refer to multiple people previously mentioned, and `their` shows possession or belonging to these people. For example:
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a8b62e5681235c3fb5492.md
> +`I saw the kids. I gave them their toys.` (‘them’ refers to the kids; ‘their’ shows the toys belong to the kids)
```suggestion
`I saw the kids. I gave them their toys.` (`them` refers to the kids; `their` shows the toys belong to the kids)
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b258e8cd2985ed8412275.md
> +dashedName: marias-evening-activities
```suggestion
dashedName: task-79
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b283d10fee46040e0a893.md
> +Listen to the audio and asnwer the question.
```suggestion
Listen to the audio and answer the question.
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b2919ff561b60fcde19ae.md
> +Where does Maria go and what she does on Wednesdays?
```suggestion
Where does Maria go and what does she do on Wednesdays?
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b2919ff561b60fcde19ae.md
> +That is not the activity Mariaattenrs on Wednesdays.
```suggestion
That is not the activity Maria attends on Wednesdays.
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b2919ff561b60fcde19ae.md
> +That is not the activity Mariaattenrs on Wednesdays.
```suggestion
That is not the activity Maria attends on Wednesdays.
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b2919ff561b60fcde19ae.md
> +That is not the activity Mariaattenrs on Wednesdays.
```suggestion
That is not the activity Maria attends on Wednesdays.
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b32b2812874680f3198d3.md
> +Listen to the audio and complente the sentence
```suggestion
Listen to the audio and complete the sentence.
```

2023-12-18 23:44 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b38c1f5351d6c827c8e8f.md
> +Ther time of the day is wrong.
```suggestion
The time of the day is wrong.
```

2023-12-19 01:47 UTC, naomi-lgbt approved these changes

2023-12-21 01:38 UTC, DanielRosa74 approved these changes
LGTM, overall.

2023-12-21 01:38 UTC, merged