fix: rename shopping cart project for JS curriculum
freeCodeCamp/freeCodeCamp pull request #52436
Opened 2023-11-27 20:54 UTC by jdwilkin4

## Summary of changes

The JS team decided to rename the shopping cart project to "Learn basic OOP" instead of "Learn Data Strucutures"

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2023-11-27 22:58 UTC, naomi-lgbt requested changes

2023-11-27 22:58 UTC, naomi-lgbt commented on client/src/pages/learn/2022/javascript-algorithms-and-data-structures/learn-data-structures-by-building-a-shopping-cart/index.md
Believe the directory here needs a rename.

2023-11-28 09:59 UTC, huyenltnguyen approved these changes
LGTM.

I made some suggestions on the capitalization of the title. They aren't in the scope of the PR though, so feel free to punt on those.

2023-11-28 22:15 UTC, jdwilkin4 commented on client/i18n/locales/english/intro.json
> +        "title": "Learn Basic OOP By Building A Shopping Cart",
Good call. This is in line with the other projects 
I'll change it 👍

2023-11-30 08:59 UTC, Sembauke commented
@naomi-lgbt can you give this another look?

2023-11-30 17:06 UTC, naomi-lgbt approved these changes

2023-11-30 17:06 UTC, merged