feat(curriculum) add challenges to english block 1
freeCodeCamp/freeCodeCamp pull request #52472
Opened 2023-12-01 18:24 UTC by moT01

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-12-04 22:07 UTC, nieldakarla requested changes
Hey, it is looking good! Thanks for uploading more than 180 challenges! =D

Here are somethings we need to change:
Some dialogues changed after Quincy recorded them. So we'll have to remove:
task 140, 141, 144, 145, 155, 156, 157, 158, 159, 160, 161, 179, 180, 181, 

Some characters changed:

Change Tom to Sarah.
Task 166 , 167, 168, 169, 171, 173, 182

Change Shopie to Jake
175, 176, 177, 178, 178, 182

Dialogue titles to change:
 "Dialogue 5: End of The First Day"

2023-12-05 15:16 UTC, moT01 commented
Thanks for the review @nieldakarla. There are still a number of tasks in the last dialogue that reference Tom:
Tasks  151, 153, 160, 164, 165, and 166. Can you take a look at those and confirm that we still want to keep it as Tom or let me know if we want to change them to Sarah.

2023-12-05 15:36 UTC, nieldakarla requested changes
Good catch with the challenges that were still using Tom's name. 

I believe I've removed all elements that had to be removed. I've also checked some pronouns that were wrong due to the changes in characters.

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2600b0ffa811dac3853f.md
> +Jake: Hey. You are Tom, right? I'm Jake, from Security.
```suggestion
Jake: Hey. You are Sarah, right? I'm Jake, from Security.
``

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d26bc907ce0123546288a.md
> +The phrase `I'm here to` normally talks about purpose or intention. Jake uses this structure to explain why he's talking to Tom.
```suggestion
The phrase `I'm here to` normally talks about purpose or intention. Jake uses this structure to explain why he's talking to Sarah.
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d26bc907ce0123546288a.md
> +Focus on why Jake is there. It's about providing Tom with something.
```suggestion
Focus on why Jake is there. 
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2aee945ce2137bd8b8b8.md
> +Tom: Good to know. Thank you!
```suggestion
Jake: No, it isn't. It's the good-old swipe at the door. When you hear the click, it is unlocked, and you can get in or out.
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2c94279eb6143485eac6.md
> +What does Jake mean about Tom's first day? It's about to end.
```suggestion
Demonstrative pronoun

---

`is`

### --feedback--

Verb to be in the third person

---

`it`

### --feedback--

It is a pronoun!
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2d19c570e2146b5e8835.md
> +Sometimes, people use phrases to ask about experiences, feelings, or opinions. One such phrase is `How was it?` which is a general way to ask about something that just happened. Jake uses the phrase
```suggestion
Sometimes, people use phrases to ask about experiences, feelings, or opinions. `How was it?` is a general way to ask about something that just happened. 
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2d19c570e2146b5e8835.md
> +She isn't asking about Tom's location.
```suggestion
`What Sarah will do tomorrow.`

### --feedback--

He didn't ask about future plans.

---

`How was Sarah's first day in the office.`

---

`Where Sarah is going.`

### --feedback--

He isn't asking about Sarah's location.
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2d814b60b6149a03c699.md
> +Tom: Good, really good. See you tomorrow, then?
```suggestion
Jake: Well, five o'clock. I guess this is it for your first day. How was it?
Sarah: Good, really good. See you tomorrow, then?
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2d814b60b6149a03c699.md
> +After answering Jake's question, Why does Tom say `See you tomorrow`?
```suggestion
After answering Jake's question, Why does Sarah say `See you tomorrow`?
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2d814b60b6149a03c699.md
> +`He will meet her now.`
```suggestion
`They will meet now.`
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2d814b60b6149a03c699.md
> +`He hopes to see her tomorrow.`
```suggestion
`She hopes to see him tomorrow.`
```

2023-12-05 15:36 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2d814b60b6149a03c699.md
> +`He doesn't want to see her.`
```suggestion
`She doesn't want to see him.`
```

2023-12-05 15:38 UTC, nieldakarla commented
@moT01 I've just reviewed the challenges you asked. Already created another change request with the changes. =)

2023-12-12 15:28 UTC, nieldakarla reviewed
Thanks for making the changes. I removed some extra dots in two options and fixed a challenge so the question was more precise and the feedback appropriate.

2023-12-12 15:28 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/6568c3539307ad0f902d20e7.md
> +Listen again..
```suggestion
Listen again.
```

2023-12-12 15:28 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/6568c3539307ad0f902d20e7.md
> +Listen again..
```suggestion
Listen again.
```

2023-12-12 15:28 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cb2ee9d60f205d362b1de.md
> +4
```suggestion
Which of these is NOT a workplace item mentioned by Sophie and Tom?

## --answers--

`Standing desk`

### --feedback--

Tom mentions this workplace Item.

---

`Ergonomic chair`

### --feedback--

Tom mentions this workplace Item.

---

`Ergonomic mouse`

### --feedback--

Tom mentions this workplace Item.

---

`Cutting-edge gadgets`

## --video-solution--

4
```

I noticed the question in this challenge wasn't specific enough. I've also noticed the feedbacks were wrong. I've fixed that.

2023-12-12 15:58 UTC, nieldakarla approved these changes

2023-12-12 17:22 UTC, DanielRosa74 commented
Hi @moT01 and @nieldakarla !

Here's the items I found in my review:

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-950cf32ae4808e5921ee91ed78318ea7524dfad7ada08b334a50ef0edc8dc133

First Day at the Office - Task 3

Any chance we can remove "[Name]" and "[Job title]" from the backticks? I believe these should be translatable.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-7979a4b6935f155a5d48b1811f5978b7b9515649411fb5d57156c5d380a76932

First Day at the Office - Task 6

@nieldakarla, won't there be any description in a fill in the blanks task?

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-035cb6096020efcd49e33f41f168d470c962a8dde866179977884ddcb1a7fa32

First Day at the Office - Task 11

@nieldakarla, should the answers to choose from be in English in this case? It's an interpretation question. The language is simple, though, and that could be a reason to leave it as is. Also, the feedback will be translated, which might help the person understand the content of the answers if they got them wrong.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-d7eb4c9b0346f9b79ff9a41cd67ed198e7d9ad577731bab9727bdba36d64c9df

First Day at the Office - Task 15

Tom is not from Toronto. He's from Texas now. Mistake in the audio reference and the sentence.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-8b8e6f0c41f110410d1c722cae8bc768bd3e7170430f8b4d8cde677ad4e56228

First Day at the Office - Task 16

Tom is not from Toronto. He's from Texas now. Mistake in the audio reference and the sentence.

The question has to change to "What is Tom comparing California to?" Probably changing the other answers to US states would be better as well.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-640ba803ab7ed3c759a625e2339575bad92a9187209ac4c1398ebd76f90d053b

First Day at the Office - Task 17

Tom is not from Toronto. He's from Texas now. Mistake in the audio reference, feedbacks and the sentence.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-930654f9baa7abf5a7f81c57ca5c36e7cfbce847655bb64a517b338a80efe0eb

First Day at the Office - Task 18

Change Toronto to Texas. Mistake in the audio reference and the sentence.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-449c9ffa26f64fab60e4544bb1697c48cb7c2c28ad6e2fc7306795b0b1c3bca1

First Day at the Office - Task 19

Change Toronto to Texas. Mistake in the audio reference, description and the sentence. Also in the first answer and in the feedback to the right answer (California).

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-7f1bccb86272ecc42f77433bf501d8fbb68ae2d7f4433b55350a8cc84a78f1b5

First Day at the Office - Task 20

Change Toronto to Texas. Mistake in the audio reference and in one of the answers "He misses Toronto a lot.".

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-d95e4f46913ac579321f7e9cf8350e3578f52b3fb2b24a40f796165a391f9dfd

First Day at the Office - Task 21

Change Toronto to Texas. Mistake in the audio reference and the description.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-53fc3fee437a004d4785faf060c8ee657dc3220692243132f6b9e4210de683ca

First Day at the Office - Task 22

Could [place] be out of the backticks in the the description?

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-2e3a2ca5b6352b7b9586f36dd4d2904277791de6ec59ee62fc9ef4e295afadb8

First Day at the Office - Task 32

The audio reference (which I believe will be removed) is missing an "around" between "me" and "the".  This reflects in the sentence as well.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-e873ce25dcbc4ad461a7ad68d3bd7b635caacea18f2d82a8ce4303b46fa54167

First Day at the Office - Task 34

@nieldakarla, same question of task 11. Should the question (which most likely the A2 student is already familiar to) be translated? In this case, more than in 11, I see no reason for change.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-3c6aeb39793a113c22b2dc43e1415daad602ba6911af78a87c42b0c5416b62ec

First Day at the Office - Task 36

@nieldakarla, same question of task 34. If we keep 34 between backticks, maybe we should do the same here.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-40a70621cb5e3db4f6c3bee54d5767c41eebc64c7a5ce7daa4e091c305bd4f10

First Day at the Office - Task 38

The example references Tom as "Canadian". Please change to "Texan" or "a graphic designer from Texas" and "the graphic designer from Texas in our company".

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-b09bd864cd310e0f4686bd36c93d39eab8d6c28c912d350021d7c06c813baf40

First Day at the Office - Task 40

Could [place of origin] be out of the backticks in the the description? Also, it shows in round brackets here instead of square, as in other examples. The audio reference and the sentence say "Canada". Please change to "Texas".

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-15e85723012c08863e19843dc7b41437a77b1e4401cb406467b68d148b7b461e

First Day at the Office - Task 41

The audio reference says "Canada", but this should go away in the final version. No need to change, I suppose.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-bdf297a8d296019f2adc6292ad6b23047ef0b52a7aec5b8c33ec8d793187b6f3

First Day at the Office - Task 42

The sentence says "Canada". Please change to "Texas".

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-03b6d1063d74b4b5503370784dff5a303765a0704520384d5377017cee80f16e

First Day at the Office - Task 51

Please change "They" to "These" in the audio reference and sentence.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-c501e12a13f1280fcb38f6a1375122ef0f294bc0786e47df1045e135a758b845

First Day at the Office - Task 52

Audio reference says "They" instead of "These", but this should go away in the final version. No need to change, I suppose.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-65de1b9597a62e8efb31f124af45864b26dbbdde7eacdda3801051e9079d98ad

First Day at the Office - Task 55

@nieldakarla, using the plural for "things" in the description might confuse the learner, as we are explaining "this" and "that" here. How about "something close" and "something a bit far", instead?

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-29fb29ed77a7c2fb3277ad2d01be0ce5d698f0f355c4ad3132cc22097830ad21

First Day at the Office - Task 61

@nieldakarla, technically, "your" and "my" are not "pronouns", but "possessive adjectives", as they do not stand on their own, like pronouns do. Examples of possessive pronouns would be "mine", "yours" etc. Simple suggestion: replace "Pronouns" with "Words" in the beginning of the description.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-4bc72bfb59bce327962bc0e1722287b49796603039c6084a148c19bd772a768a

First Day at the Office - Task 61

Use lowercase in "standing" in both the sentence and the audio reference.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-10ce77bb1fcfc0b40a2f8718d3907699f5e042a32122bc1ad405c71e7c929561

First Day at the Office - Task 94

I think "breakfast", "lunch", and "dinner" should go in backticks in the description and in the feedbacks. 

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-21820af4c963353c521c499203a3a3d88631d58abdf45122578f45a6af61e104

First Day at the Office - Task 106

I believe the expression should be "places around here", both in the description and text.

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#diff-fa851dd54fb337aef65719df606ceab41b12027263e55dd409dc96697df16bb0

First Day at the Office - Task 107

@nieldakarla, this fill in the blank exercise has no description. Should it be like this?

https://github.com/freeCodeCamp/freeCodeCamp/pull/52472/files#dif [...]

2023-12-12 18:09 UTC, DanielRosa74 reviewed
Overall, I believe the backticks are correct. Added comments to moT01 and nieldakarla where I found something to change/discuss about.

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656caddea3aba304c6172571.md
> +`A Standing Desk, an _ chair and an _ mouse.`
Use lowercase in "standing" in both the sentence and the audio reference.

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cc3b856f1d01011bfc027.md
> +In English, the three main meals of the day are breakfast, lunch, and dinner. Breakfast is typically eaten in the morning, lunch is around midday, and dinner is in the evening.
I think "breakfast", "lunch", and "dinner" should go in backticks in the description and in the feedbacks.

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cc92ecdebaa1278505e87.md
> +`Places around` refers to locations in the nearby vicinity or area.
I believe the expression should be "places around here", both in the description and text.

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cc98cfe781112ace7d3ee.md
> +
@nieldakarla, this fill in the blank exercise has no description. Should it be like this? Suggestion: "Now let's use the expression we learned for referring to nearby places."

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cd1ca72b3e615a33c05b6.md
> +In English, you can use a certain structure to indicate that something isn't in a particular state or condition in the present.
In the description, I'd suggest replacing "isn't" with "is not" as in the audio and putting it in backticks to clarify this is what we are trying to explain here.

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cd31045ce74162adef6c7.md
> +What are Tom and Sophie planning to do?
As the answers are in English, we could leave the question in English as well, with backticks, thus.

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cd83ad397f61ce1259ad6.md
> +When you want to present one person to another, you can use the phrase `let me introduce you to [Name]`. For example: `Let me introduce you to Daniel.`
Could "[Name]" be removed from backticks here?

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cd8d68948d11d201308d4.md
> +The phrase `this is [Name]` is used to present someone in a conversation. It's a simple and direct way to make introductions. For example: `Daniel, this is Carol.`
Could "[Name]" be removed from backticks here?

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656cd9f4e30e6d1d81f0e62d.md
> +`This is Brian. He _ a web developer. This is Tom. He _ from Canada.`
Sentence: not "Canada", but "Texas".

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d1d1f46bc820629aecc0d.md
> +Watch the dialogue below and listen to how Brian refers to Sophia.
Typo: it's "Sophie", not "Sophia".

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d25e0c5d5aa11ade33754.md
> +In the dialogue, Jake introduces himself to Sarah with the phrase `I'm Jake, from Security.` The word `from` is a preposition that shows the origin or source. In this context, `from Security` tells w
Please replace "with the phrase" in the description with "saying". Also, @nieldakarla, how about having this question in English (backticks)?

2023-12-12 18:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656d2c2fedbd5f14055b7e7b.md
> +`Jake is not sure, but she thinks.`
Two issues in the answer "Jake is not sure, but she thinks." Change "she" to "he" and maybe rephrase: "Jake is not sure. He thinks what he is saying is true."

2023-12-13 22:14 UTC, DanielRosa74 approved these changes
LGTM

2023-12-13 22:25 UTC, naomi-lgbt approved these changes

2023-12-13 22:25 UTC, DanielRosa74 approved these changes
LGTM

2023-12-13 22:26 UTC, merged

2023-12-13 22:27 UTC, moT01 commented
Thanks for all the reviews and getting this in everyone 🎉