Freecodecamp mobile apps under footer
freeCodeCamp/freeCodeCamp pull request #52481
Opened 2023-12-03 20:58 UTC by arjunpras

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51630

Link to the issue - [link](https://github.com/freeCodeCamp/freeCodeCamp/issues/51630)

Link to screenshot 

- For Bigger Screens : [link](https://github.com/freeCodeCamp/freeCodeCamp/assets/96985754/561e1c4d-761e-4088-9cdc-22f4ae3f4a66)

- For Mobile devices : [link](https://github.com/freeCodeCamp/freeCodeCamp/assets/96985754/410d2441-1d46-4f9f-81f1-51bc55115781)

2023-12-06 12:18 UTC, Sembauke requested changes
Hey @arjunpras,

This is looking great already! Couple of notes and questions:

- We should change "Mobile Apps" to "Mobile App" as we only have one app we want to advertise. We should change this in the CSS-classes and the Header.

- Why are you nesting the image element in a anchor element?

2023-12-06 12:18 UTC, Sembauke commented on client/src/components/Footer/footer.css
> +}
```suggestion
.mobile-apps {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 2rem;
}
```

2023-12-06 12:18 UTC, Sembauke commented on client/src/components/Footer/footer.css
> +}
```suggestion
.mobile-apps-container {
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  align-items: center;
  width: 100%;
  max-width: 25rem;
}
```

2023-12-06 12:18 UTC, Sembauke commented on client/src/components/Footer/footer.css
> +  }
```suggestion
  .mobile-apps-container {
    flex-direction: row;
  }
```

2023-12-06 16:52 UTC, naomi-lgbt commented
> Why are you nesting the image element in a anchor element?

It turns the image into a clickable link - click the image, get taken to the app store. :3

2023-12-07 07:36 UTC, huyenltnguyen reviewed
We should have test coverage for this feature.

The tests can be added to https://github.com/freeCodeCamp/freeCodeCamp/blob/main/e2e/footer.spec.ts.

2023-12-08 16:49 UTC, Sboonny commented on client/src/components/Footer/index.tsx
> +              </a>
Shouldn't they be translatable?

2023-12-08 18:25 UTC, arjunpras commented on client/src/components/Footer/index.tsx
> +              {t('Mobile Apps')}
I have added mobile-app key in translations.json file only for English. I believe other languages do need this key too. so inorder to add this key, from where can I translate "mobile-app" to other language?

2023-12-13 12:39 UTC, Sembauke approved these changes

2023-12-13 17:30 UTC, huyenltnguyen reviewed
@arjunpras Thank you for the work!

There are a couple changes we should make still. I'm listing them here for transparency, but I'll handle the update myself tomorrow :)
- The links should open in a new tab and should probably be in a `ul`
- Playwright tests should be added
- The CSS could be reduced if we use layout components from `ui-components`. The `Spacer` component should also be used to ensure that we are using the standard spacing values

2023-12-14 04:50 UTC, arjunpras commented
Thanks @huyenltnguyen for letting me know more optimised solution 👍

2023-12-14 05:48 UTC, huyenltnguyen approved these changes
@Sembauke I'm approving my own code here. My code changes doubled the size of the PR, but it's mainly because of the additional tests. I'll let you handle the merge and do yell if there is anything jumps out at you.

---
@arjunpras Thank you again for the PR and congratulations on your first contribution to this repo 🎉
We look forward to your next.

Happy contributing!

2023-12-20 07:01 UTC, merged