feat: handle python input synchronously
freeCodeCamp/freeCodeCamp pull request #52526
Opened 2023-12-11 18:15 UTC by ojeytonwilliams

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

When putting this together I was lucky enough to find the discussion on https://github.com/pyodide/pyodide/issues/1219. Part of that discussion was about how to use synchronous http requests to block (credit to: https://jasonformat.com/javascript-sleep/) and therefore mimic the behaviour of Python's `input` in JS.

Prior to this PR, we had to make `input` async, which automatically meant any function that called it had to be async. This proved challenging, since it was hard to correctly transform all the code to use async await, let alone do so without altering the code's behaviour.

I still have a fair bit of cleanup to do, hence this being in draft, but I think this is good enough to test out.

2023-12-11 18:16 UTC, ojeytonwilliams commented on client/src/templates/Challenges/utils/build.ts
> +  // TODO: allow terminateWorker to be passed in as an option.
```suggestion
```
Already done.

2023-12-14 11:32 UTC, ShaunSHamilton requested changes
Nice job getting this working!

I got a few type errors in the `build.ts` file, and could not figure out if this was just my LSP doing what it does or an actual error. Could someone double-check whether they are still there?

2023-12-14 11:32 UTC, ShaunSHamilton commented on tools/client-plugins/browser-scripts/python-test-evaluator.ts
> +  console.log('python worker received message', e.data);
```suggestion
```

2023-12-14 14:03 UTC, ojeytonwilliams commented
> Nice job getting this working!

Thanks, it was a bit of a struggle!

> I got a few type errors in the `build.ts` file, and could not figure out if this was just my LSP doing what it does or an actual error. Could someone double-check whether they are still there?

If you're seeing errors in `composeFunctions` and when `checkFilesErrors` is called, those are pre-existing errors.

2023-12-14 15:57 UTC, ShaunSHamilton approved these changes
I am not breaking this with anything. So, I think we are GTMAP 👍

2023-12-18 19:22 UTC, naomi-lgbt approved these changes
<img width="590" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/6ca0f3eb-0aa8-4475-9d25-b0b97521b61a">

I did a python and it worked.

2023-12-18 19:22 UTC, merged

2023-12-18 19:35 UTC, ojeytonwilliams commented
Thanks Naomi!