feat: update donate page UI
freeCodeCamp/freeCodeCamp pull request #52524
Opened 2023-12-11 14:22 UTC by ahmaxed

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2023-12-11 19:50 UTC, ahmaxed commented
Once the copy has been approved by Quincy, I will finalize the pr accordingly.

2023-12-12 19:15 UTC, ahmaxed commented on client/src/components/Donation/donation-text-components.tsx
> +      <h2 data-playwright-test-label='faq-head'>{t('donate.faq')}:</h2>
```suggestion
      <h2 data-playwright-test-label='faq-head'>{t('donate.faq')}</h2>
```

2023-12-13 06:05 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "current-initiatives-1": "Creating new Javascript and Python curriculula",
```suggestion
    "current-initiatives-1": "Creating new Javascript and Python curricula",
```

2023-12-13 06:05 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "current-initiatives-2": "Creating English and math curriculula",
```suggestion
    "current-initiatives-2": "Creating English and math curricula",
```

2023-12-13 06:41 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "current-initiatives-4": "Creating a free accredited computer science degree",
```suggestion
    "current-initiatives-4": "Creating a free accredited computer science bachelor's degree",
```

2023-12-13 06:42 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "current-initiatives-3": "Translating our curriculum and tutorials to 32 languages",
```suggestion
    "current-initiatives-3": "Translating our curriculum and tutorials into 32 languages",
```

2023-12-13 06:42 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "support-benefits-1": "No more donation popups",
```suggestion
    "support-benefits-1": "No more donation prompt popups",
```

2023-12-13 06:46 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "crucial-contribution": "Your contribution will be crucial in creating resources that empower millions to learn new skills and support their families.",
```suggestion
    "crucial-contribution": "Your contribution will be crucial in creating resources that empower millions of people to learn new skills and support their families.",
```

2023-12-13 08:53 UTC, ahmaxed commented on client/src/components/Donation/donation-text-components.tsx
> +      <h1 data-playwright-test-label='main-head'>{t('donate.help-more')}</h1>
That is a pretty good consideration. 
I will do the research and update the donate page in the next iteration.

2023-12-13 08:54 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "community-achivements-3": "Merged <0>2,753</0> code contributions into our open sourcerepositories on GitHub",
```suggestion
    "community-achivements-3": "Merged <0>2,753</0> code contributions into our open source repositories on GitHub",
```

2023-12-13 08:55 UTC, ShaunSHamilton requested changes
This and the tests need updating. Everything else LGTM 👍

2023-12-13 08:56 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "community-achivements-3": "Merged <0>2,753</0> code contributions into our open sourcerepositories on GitHub",
Thanks for catching that. I will remove all periods so it is consistent with the other lists.

2023-12-13 08:58 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "community-achivements-4": "Translated <0>2,106,203</0> words to make our curriculum and tutorials more accessible to speakers of many world languages",
```suggestion
    "community-achivements-1": "Published <0>114</0> full-length courses on YouTube",
    "community-achivements-2": "Published <0>1,045</0> text-based coding tutorials and <0>20</0> free books through freeCodeCamp Press",
    "community-achivements-3": "Merged <0>2,753</0> code contributions into our open source repositories on GitHub",
    "community-achivements-4": "Translated <0>2,106,203</0> words to make our curriculum and tutorials more accessible to speakers of many world languages",
```

2023-12-13 09:08 UTC, ShaunSHamilton approved these changes
LGTM 👍

2023-12-13 09:12 UTC, huyenltnguyen approved these changes

2023-12-13 09:18 UTC, merged