Feat(curriculum) add Introductions in team meeting block 1.2
freeCodeCamp/freeCodeCamp pull request #52565
Opened 2023-12-17 02:27 UTC by nieldakarla

Challenges for the second block of the English Curriculum. 

Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Ref: #52400

2023-12-18 16:17 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657b400653813a1caa228aca.md
> +`A future plan`
```suggestion
A future plan
```

2023-12-18 17:44 UTC, moT01 reviewed
This is looking good @nieldakarla 🎉 

I just wrote down the things I found instead of making code suggestion in this UI. Here they are:

Task 3:
Answers should not be in backticks

Task 19:
Answers 3 and 4 are mixed up.

Task 40:
`User` should not be capitalized in the fill in the blank sentence

Task 44:
We shouldn’t use `+`’s in the description. This could be an alternative:

```
Phrases like `I really like [subject]`, with `subject` being a subject you like, or `I can't wait to do [activity]`, with `activity` being an activity you want to do, are sentences that show your excitement and interest about something.
```

Task 51:
`let` in the first blank answer should be capitalized

Task 52:
`this` in the first blank answer should be capitalized

Task 71:
`OK` -> `Okay`? - probably fine to leave it.

Task 81:
Missing period at end of fill in the blank sentence.

Task 86:
I think the answer is supposed to be 2 instead of 1

Task 88:
Has a dash in the challenge title: `Task-88` -> `Task 88`. Same issue with the title in the `meta.json` file.

Task 98:
In the blank answer `point`, We should remove the space in the answer.

2023-12-18 19:21 UTC, nieldakarla commented
I'll implement the changes now, @moT01. And, thank you for the alternative description you gave me. It was very helpful!

2023-12-18 20:23 UTC, DanielRosa74 requested changes
Minor tweaks needed. LGTM overall

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657cd9ae412af80b2a7ff265.md
> +`Even` is used to emphasize something unexpected or to include something in addition. For example, `She can speak many languages, even Tupí` means that it's surprising or notable that she can also sp
No stress mark on Tupi within the backticks

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657ce691d6c57c107e650c5e.md
> +THis line is about Tom's role and expertise, not about leading meetings.
lowercase the "H" in "This"

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657daa5ab8505427a5b99cd2.md
> +He is the team’s project manager.
Watch for the curly quote in "team's"

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657daa5ab8505427a5b99cd2.md
> +He is the team’s graphic designer.
Here too

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657daa5ab8505427a5b99cd2.md
> +He is the company’s CEO.
And here

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657dadfc7d21eb294c9f057e.md
> +`And I’m Bob, the team’s project manager`
Curly quotes

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657daf702ed04a29ee42de69.md
> +`Hi, Bob. It’s _ to meet you _.`
Curly quotes

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657df21cc45b1f66112fb8fc.md
> +`_! Lisa, it’s great to _ you _ our team, _ if just online.`
Curly quotes

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657df5d14291b56887825276.md
> +`I’m James and I’m _ to _ you with your _.`
Curly quotes

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657df6018a70e468f5dc016a.md
> +James doesn't metion being a team leader.
"mention" is misspelled

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e3ca1c4d9636e9012e1a9.md
> +To provide a detailed report of her team’s performance.
Curly quotes

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e4b7d381d567e8d97967c.md
> +`I'm responsible for the _ aspects of the project. He’s responsible for _ our _ to meet your needs.`
Curly quotes in "he's"

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e4db2e3fc8d7fb41b8b85.md
> +`Hey, Bob. How’s it _?`
Curly quotes in "how's"

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e4fd2ecf31280ef673f0d.md
> +She manages the company’s finances.
Curly quotes

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e51218ff18f8191b76ea9.md
> +`_ to _ you all. I'm David, the project _ from FCC _`
Missing a full stop at the end of the sentence.

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e5477269b94834908826f.md
> +`I’ll be your _ of contact and I’ll help make sure our _ is great.`
Curly quotes in both "I'll"

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e56e7034d2d858b6e9e00.md
> +The second `we` is not just about FCC corp.
Uppercase the C in corp

2023-12-18 20:23 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e59605c6f688785fbb46d.md
> +Maria' is not asking David to take over the meeting.
Remove this ' after Maria

2023-12-18 20:39 UTC, DanielRosa74 approved these changes
LGTM

2023-12-18 21:15 UTC, moT01 commented
I pushed the updated titles to the meta.json file

2023-12-18 21:22 UTC, moT01 approved these changes

2023-12-18 22:36 UTC, naomi-lgbt requested changes
Couple of nits, then happy to merge.

2023-12-18 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e4e3b02a2128049c344c8.md
> +audioPath: Acurriculum/js-music-player/We-Are-Going-to-Make-it.mp3
```suggestion
audioPath: curriculum/js-music-player/We-Are-Going-to-Make-it.mp3
```

2023-12-18 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657e523fcaaa0e823b3789e5.md
> +He is doctor from FCC Corp.
```suggestion
He is a doctor from FCC Corp.
```

2023-12-19 00:20 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657ca36eacc797817451ece6.md
> +Bob: Can you hand me that file, please? I need to review it before our meeting.
This has passed me by in the first review. This line is not in the dialogues, so there's no audio for that.

2023-12-19 01:06 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-introductions-in-an-online-team-meeting/657cd9ae412af80b2a7ff265.md
> +The word even highlights something extra or beyond what is usual.
Yes

2023-12-19 01:19 UTC, naomi-lgbt approved these changes

2023-12-19 09:20 UTC, merged