fix (cirriculum): allow space in cafe css project step 36
freeCodeCamp/freeCodeCamp pull request #52564
Opened 2023-12-17 00:47 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Ref https://github.com/freeCodeCamp/freeCodeCamp/issues/52549

I updated the challenge to no longer use regular expressions and removed jQuery in an effort to ensure classes can have a space before and after the equal sign. If there are no further issues and the other two pull requests are merged, then the issue can be closed.

2023-12-17 21:12 UTC, lasjorg requested changes

2023-12-17 21:12 UTC, lasjorg commented on curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3c866de7a5b784048f94b1.md
> +assert.equal(el.className,'item');
```suggestion
assert.equal(el.className, 'item');
```
Formatting nitpick

2023-12-17 22:19 UTC, lasjorg approved these changes
LGTM

2023-12-18 04:23 UTC, huyenltnguyen approved these changes

2023-12-18 04:24 UTC, merged