Updated scientific-computing-with-python description
freeCodeCamp/freeCodeCamp pull request #52713
Opened 2023-12-22 13:08 UTC by Humayun-glitch

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-01-03 11:02 UTC, zairahira requested changes

2024-01-03 11:02 UTC, zairahira commented on client/i18n/locales/english/intro.json
> +      "This comprehensive course will guide you through the fundamentals of scientific computing, including data structures, algorithms, and essential libraries like NumPy, pandas, and Matplotlib."
Currently, the certification is not teaching visualization or handling large data sets.
Same is the case with the mentioned libraries.

2024-01-03 21:21 UTC, Humayun-glitch reviewed
Updated according to the requested changes.

2024-01-24 15:29 UTC, ieahleen commented
Do you have issues with fixing this? Please reach out in the discord server.

2024-01-24 15:33 UTC, Humayun-glitch commented
No, actually. I have been very busy with my Bachelors final year project. Will get to this by this weekend.

2024-02-16 08:38 UTC, closed without merging