fix: added check for closing tag
freeCodeCamp/freeCodeCamp pull request #52748
Opened 2023-12-24 12:57 UTC by mishalp

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52731

The browser is automatically adding `</select>` tag for the self-closing tag `<select id="entry-dropdown" name="options" />` that contains some white spaces
So I added a check for the `select` tag that it should be empty(without white spaces)
The only way to pass the check is to manually use the closing tag `</select>`

2023-12-27 20:54 UTC, ieahleen requested changes
Thank you for your contribution!

2023-12-27 20:54 UTC, ieahleen commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63b60aaaa65f8922bfce6b7e.md
> +Your `select` element should empty and close with `</select>` tag.
```suggestion
Your `select` element should be empty and have a closing `</select>` tag.
```

2023-12-28 04:37 UTC, mishalp commented
why some of the tests are failed?

2023-12-28 08:51 UTC, mishalp commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63b60aaaa65f8922bfce6b7e.md
> +```
Yes, but if we trim the whitespaces this following code will not throw actual error
```
<div class="controls">
            <span>
              <label for="entry-dropdown">Add food or exercise:</label>
              <select id="entry-dropdown" name="options" />
              <button id="add-entry" type="button">Add Entry</button>
            </span>
          </div>
```
the browser will add `</select>` and ignore the button element, output like this
```
<div class="controls">
            <span>
              <label for="entry-dropdown">Add food or exercise:</label>
              <select id="entry-dropdown" name="options" >
             
         Add Entry

         </select>
            </span>
          </div>
```
that is why I didn't use trim, the user forced to close the tag like this
```
<select id="entry-dropdown" name="options" ></select>
```
any other solutions?

2023-12-30 15:11 UTC, huyenltnguyen approved these changes

2024-01-02 15:05 UTC, ieahleen approved these changes
LGTM 👍

2024-01-02 15:06 UTC, merged