fixed #52780
freeCodeCamp/freeCodeCamp pull request #52793
Opened 2023-12-27 21:10 UTC by pr2897

Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52780

2023-12-27 22:23 UTC, jdwilkin4 commented
Hi @pr2897 ! 

Thank you for opening this PR.

I have updated the title of your post to something more descriptive so the maintainers know what this PR is about at first glance. 👍

2023-12-27 22:28 UTC, jdwilkin4 requested changes
Add some comments to fix the language and missing back ticks for the hint text 👍

2023-12-27 22:28 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8f1d5f5ddbf74c07f733b.md
> +update method should be called
```suggestion
You should call the `update` function inside the `lose` function.
```

2023-12-27 22:28 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8f1d5f5ddbf74c07f733b.md
> +locations[5] should be passed as argument to update method
```suggestion
Your `update` function should have `locations[5]` for the argument.
```

2023-12-27 22:49 UTC, jdwilkin4 requested changes
Last two small comments and then it looks good to me 👍

2023-12-27 22:49 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8f1d5f5ddbf74c07f733b.md
> +assert.match(lose.toString(), /update/)
So technically this test only checks if the camper wrote `update` inside the `lose` function. 
It doesn't test if the camper calls it though.
We should update this test to check if the `update` function called

This should work

```suggestion
assert.match(lose.toString(), /update\(/);
```

2023-12-27 22:49 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8f1d5f5ddbf74c07f733b.md
> +assert.match(lose.toString(), /update\(locations\[5\]\)/)
add in missing semicolon 

```suggestion
assert.match(lose.toString(), /update\(locations\[5\]\)/);
```

2023-12-28 08:38 UTC, jdwilkin4 approved these changes

2023-12-30 15:12 UTC, huyenltnguyen approved these changes
LGTM 👍

@pr2897 Thank you for the PR and congratulations on your first contribution to this repo 🎉
We look forward to your next.

Happy contributing!

2023-12-30 15:13 UTC, merged