fix(curriculum): Resolve Sudoku solver open issues
freeCodeCamp/freeCodeCamp pull request #52884
Opened 2024-01-02 15:44 UTC by zairahira

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Partially Closes #52585 

Updated :
- Step 28: Have Campers create/instantiate a class and call the str/print method so they can see some output 
- Step 14: Split into more steps (14-17)

2024-01-11 13:17 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/6596e147789804474b4efa47.md
> +})
This works for me.

2024-01-11 13:33 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/6596e2744c80694d2e9a9712.md
> +})
```suggestion
({
    test: () => {
        const transformedCode = code.replace(/\r/g, "");
        const if_check = "if self.is_valid(next_empty, guess)"
        const if_block = __helpers.python.getBlock(transformedCode, if_check);
        const { block_body} = if_block;        
        assert(block_body.match(/if\s+self\.solver\(\):/));    
    }
})
```

2024-01-11 13:34 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/6596e2744c80694d2e9a9712.md
> +})
Removed unused variables

2024-01-11 13:34 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-classes-and-objects-by-building-a-sudoku-solver/6596e2744c80694d2e9a9712.md
> +})
```suggestion
({
    test: () => {
        const transformedCode = code.replace(/\r/g, "");
        const if_check = "if self.solver()"
        const if_block = __helpers.python.getBlock(transformedCode, if_check);
        const { block_body} = if_block;        
        assert(block_body.match(/return\s+True/));    
    }
})
```

2024-01-18 23:59 UTC, moT01 commented
There's some failing tests here @zairahira. Do you want to take a look at those?

2024-01-27 01:04 UTC, naomi-lgbt approved these changes

2024-01-29 11:59 UTC, ilenia-magoni requested changes
I think it's missing continuity in the seed code, like for example, step 31 has the sudoku board in the seed code, the instructions don't say anything about removing it, and it's not present in step 32. Is that for some particular reason? Also, is there a particular reason the sudoku board is not present in the code since the beginning of the project? How can we build the project without having data to test it with?

2024-01-29 13:24 UTC, Dario-DC reviewed
I see two main issues with this project:
- the tests allow you to right the code with wrong indentation and pass (I know this was not the purpose of this PR)
- the project is almost built from the top to the bottom of the prototype and having the part that prints the board at the beginning it's not ideal.

My suggestion is to restructure the project to have the example board in the seed code from the beginning, give more information about objects, instances and methods before creating the __init__ method (adding brief examples not strictly related to the project). The construction of the board should occur at the end of the project.

2024-04-15 12:36 UTC, closed without merging