fix: duplication in descriptions HTML foundations
freeCodeCamp/freeCodeCamp pull request #52909
Opened 2024-01-03 09:02 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-01-03 19:35 UTC, jdwilkin4 approved these changes
tested it locally and the changes look good to me 👍

2024-01-05 00:40 UTC, naomi-lgbt requested changes

2024-01-05 00:40 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-html-foundations/html-foundations-question-e.md
> +id: 637f4e2f72c65bc8e73dfe22
This ID changed. I'll need to sync it to the i18n instances.

2024-01-05 00:40 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-html-foundations/html-foundations-question-f.md
> +id: 637f4e3672c65bc8e73dfe23
This one too.

2024-01-05 00:40 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-html-foundations/html-foundations-question-g.md
> +id: 6376327e2724a688c04636e3
And this.

2024-01-05 00:40 UTC, naomi-lgbt commented on curriculum/challenges/english/16-the-odin-project/top-learn-html-foundations/html-foundations-question-h.md
> +id: 637633162724a688c04636e4
.

2024-01-05 01:04 UTC, naomi-lgbt commented
Once #52964 is in, I'll rebase and run a sync.

2024-01-05 09:04 UTC, Sembauke commented
thanks Naomi.

2024-01-23 07:06 UTC, naomi-lgbt approved these changes

2024-01-23 07:06 UTC, merged