fix(curriculum): Finished sentence
freeCodeCamp/freeCodeCamp pull request #52983
Opened 2024-01-05 19:10 UTC by farshed

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-01-05 19:17 UTC, gikf requested changes
@farshed Please make the change to the English file. Other languages, if needed will be updated using the translation workflow.

2024-01-05 19:31 UTC, farshed commented
@gikf It's done.

2024-01-05 19:33 UTC, gikf approved these changes

2024-01-06 03:59 UTC, huyenltnguyen approved these changes

2024-01-06 04:00 UTC, merged