Fix: Learn Greetings in your First Day at the Office - Task 32 - Sentence doesn't match audio
freeCodeCamp/freeCodeCamp pull request #53034
Opened 2024-01-08 11:35 UTC by aakash-a-dev

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53010

I created a PR while setting it up my vs code deleted the file itself and my previous PR was mistake so created new PR because I had to delete my previous Fork repo due to technical glitch.
For solving this issue I followed the steps commented in the respective issue:

In https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/chinese/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a14b0e1c43d0ffabd15a9.md:
Change the text in the AUDIO REFERENCE tag from Thanks, Maria, for showing me the place! to Thanks for showing me around the place, Maria.
In https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a18189b21f51037e518b4.md:
Change the text in the AUDIO REFERENCE tag from Thanks, Maria, for showing me around the place! to Thanks for showing me around the place, Maria.
Change the fill-in-the-blank sentence from Thanks, Maria, for _ me around the _. to Thanks for _ me around the _, Maria..

I hope for a Positive contribution forward.

2024-01-08 12:01 UTC, ieahleen requested changes
change the English files please, not the Chinese files

2024-01-08 12:20 UTC, aakash-a-dev commented
I have rectified the earlier misunderstanding I had. Sorry and Thank you for your feedback I rectified this time. I hope this time I am doing it correctly.

2024-01-08 13:08 UTC, ieahleen requested changes
Please remove the changes to the Chinese files, if the bot keeps answering they are still there.

2024-01-08 13:08 UTC, ieahleen commented on curriculum/challenges/chinese/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a14b0e1c43d0ffabd15a9.md
> +Tom: Everything looks great. Thanks for showing me around the place, Maria.
```suggestion
Tom: Everything looks great. Thanks, Maria, for showing me the place!
```

2024-01-08 13:08 UTC, ieahleen commented on curriculum/challenges/chinese/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a18189b21f51037e518b4.md
> +Tom: Thanks for showing me around the place, Maria.
```suggestion
Tom: Thanks, Maria, for showing me around the place!
```

2024-01-08 13:08 UTC, ieahleen commented on curriculum/challenges/chinese/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a18189b21f51037e518b4.md
> +        "text": "Everything looks great. Thanks, Maria, for showing me around the place!",
```suggestion
        "text": "Everything looks great. Thanks for showing me around the place, Maria.",
```

2024-01-08 14:09 UTC, aakash-a-dev reviewed
As per the guidance I modified the code. Thank you

2024-01-08 14:26 UTC, aakash-a-dev commented
It's showing 
GitHub - No translations via PRs / has-translation (pull_request_target) But I reverted to the original code

2024-01-08 16:15 UTC, ieahleen requested changes
please revert also this last change to the Chinese files

2024-01-08 16:15 UTC, ieahleen commented on curriculum/challenges/chinese/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a18189b21f51037e518b4.md
> +        "text": "Everything looks great. Thanks, Maria, for showing me around the place!",
```suggestion
        "text": "Everything looks great. Thanks for showing me around the place, Maria.",
```

2024-01-08 16:22 UTC, aakash-a-dev commented
Now I am crying but in Hope that this time I did the correction. Truly sorry for making you to review this code this much.

2024-01-08 17:39 UTC, gikf commented on curriculum/challenges/english/21-a2-english-for-developers/learn-greetings-in-your-first-day-at-the-office/656a14b0e1c43d0ffabd15a9.md
> +Tom: Everything looks great. Thanks, Maria, for showing me the place!.
```suggestion
Tom: Everything looks great. Thanks for showing me around the place, Maria.
```

2024-01-08 20:10 UTC, gikf approved these changes

2024-01-08 21:45 UTC, moT01 approved these changes
LGTM 🎉

2024-01-09 12:51 UTC, aakash-a-dev commented
Maam @ieahleen Can you check it please, I had done and got two review approved as well.

2024-01-10 17:51 UTC, ieahleen approved these changes
LGTM 👍 

Note you will need to reset your main branch to be in sync with the freeCodeCamp:main branch. This is a reason for which it is highly suggested to not work on the main branch but to create feature branches.

2024-01-10 17:52 UTC, merged