fix(cirriculum) - more correct solutions step 123 rpg project
freeCodeCamp/freeCodeCamp pull request #53052
Opened 2024-01-08 19:54 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/52962

It's a repeat of my last pull request for this issue before things got a little wonky.

2024-01-09 03:22 UTC, jdwilkin4 approved these changes

2024-01-09 16:54 UTC, naomi-lgbt requested changes
Spacing should be optional when it is not required by JavaScript.

2024-01-09 18:15 UTC, a2937 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8e4dc6a60f85bf256a0cb.md
> +assert.match(attack.toString(), /Math\.floor\(Math\.random\(\) \* xp(?: \+ 1)?\)(?: \+ 1)?/);
Thank you. I'll add your suggestions as soon as I can.

2024-01-10 03:27 UTC, naomi-lgbt approved these changes

2024-01-10 03:27 UTC, merged