fix(curriculum): RPG - Ternary anti-pattern
freeCodeCamp/freeCodeCamp pull request #53070
Opened 2024-01-09 14:06 UTC by altsun

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/52669

### Overview
- Remove step 140, update numbers of all steps after 140 
- Replace all `fighting === 2 ? winGame() : defeatMonster();` to original if-else statement
- Update description of step 147 (before is 148)

2024-01-10 03:41 UTC, jdwilkin4 commented
@altsun 

it looks like you are failing a few of the automated checks.

It is possible your changes might have caused an error in the test suite.
You can run tests locally by running the commands listed in the guide here
https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges

2024-01-10 13:15 UTC, jdwilkin4 requested changes

2024-01-10 14:32 UTC, altsun commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa1eec891ed731db227a36.md
>  If you play the game in its current state you might notice a bug. If your `xp` is high enough, the `getMonsterAttackValue` function will return a negative number, which will actually add to your tota
Should it be `<dfn>ternary operator</dfn>` instead of `<dfn>ternary</dfn> operator` for consistency

2024-01-10 15:33 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa1eec891ed731db227a36.md
>  If you play the game in its current state you might notice a bug. If your `xp` is high enough, the `getMonsterAttackValue` function will return a negative number, which will actually add to your tota
> Should it be <dfn>ternary operator</dfn>

Yeah, that is fine

2024-01-10 15:36 UTC, jdwilkin4 requested changes

2024-01-10 16:00 UTC, altsun commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa1eec891ed731db227a36.md
>  If you play the game in its current state you might notice a bug. If your `xp` is high enough, the `getMonsterAttackValue` function will return a negative number, which will actually add to your tota
Updated

2024-01-10 16:00 UTC, altsun commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa1eec891ed731db227a36.md
> +JavaScript has a conditional operator called the <dfn>ternary operator</dfn>. This can be used as a one-line `if-else` statement. The syntax is: `condition ? true : false`.
Updated following @huyenltnguyen's suggestion

2024-01-10 16:05 UTC, jdwilkin4 approved these changes
LGTM 👍

2024-01-10 17:13 UTC, altsun commented
> @altsun
> 
> it looks like you are failing a few of the automated checks.
> 
> It is possible your changes might have caused an error in the test suite. You can run tests locally by running the commands listed in the guide here https://contribute.freecodecamp.org/#/how-to-work-on-coding-challenges?id=testing-challenges

Not sure why my code changes cause this error: `RangeError: Maximum call stack size exceeded`. I will check this

2024-01-11 09:31 UTC, huyenltnguyen approved these changes
With the ternary being converted to `if-else`, we have 5 `if`s in the `attack` function. This failed a test in step 153 (currently 154) because it was expecting 4 `if`s.

I updated the test to expect 5 instead.

2024-01-11 11:10 UTC, altsun commented
> With the ternary being converted to `if-else`, we have 5 `if`s in the `attack` function. This failed a test in step 153 (currently 154) because it was expecting 4 `if`s.
> 
> I updated the test to expect 5 instead.

Thank you @huyenltnguyen

2024-01-11 15:57 UTC, naomi-lgbt approved these changes
Think this should be good to go.

2024-01-11 15:58 UTC, merged