chore: fix grammar error
freeCodeCamp/freeCodeCamp pull request #53162
Opened 2024-01-12 22:10 UTC by clarencepenz

Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine or GitPod.

2024-01-13 00:23 UTC, jdwilkin4 requested changes

2024-01-13 00:23 UTC, jdwilkin4 commented on docs/courses-vscode-extension.md
> +A GitHub Action automatically publishes the extension to the Visual Studio Marketplace, on the release of a new GitHub Release.
This one is actually intentional.
automagically is a word 
https://www.dictionary.com/browse/automagically

revert this back to the way it was

```suggestion
A GitHub Action automagically publishes the extension to the Visual Studio Marketplace, on the release of a new GitHub Release.
```

2024-01-13 14:17 UTC, gikf approved these changes

2024-01-14 17:45 UTC, jdwilkin4 approved these changes

2024-01-14 17:45 UTC, merged