fix(curriculum): RPG - Step 41 - 42: Passing with wrong code
freeCodeCamp/freeCodeCamp pull request #53169
Opened 2024-01-13 08:21 UTC by iprime2

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53163

2024-01-13 20:37 UTC, lasjorg commented
This is not what the issue is about. The tests should not allow for the functions to be invoked/called. Doing so will break the event handlers.

The parentheses `()` should _not_ be allowed when assigning the handler functions.

Incorrect:
```
button1.onclick = goStore();
button2.onclick = goCave();
button3.onclick = fightDragon();
```

Correct:
```
button1.onclick = goStore;
button2.onclick = goCave;
button3.onclick = fightDragon;
```


Also, the element event attribute is `onclick` - all lowercase. You should not change that.

2024-01-14 07:01 UTC, iprime2 commented
@lasjorg 
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/29702609/280089a4-1d2e-4f77-9530-c658045b3959)

2024-01-14 20:56 UTC, lasjorg commented
Please remove the comments from the code.

I just noticed we do not actually test for the correct function name. As long as we match on the start of the function name you can put whatever you want after. So this will pass as well.

```js
button1.onclick = goStoressss;
```

Also, thinking about this some more, we might want to create new tests specifically for the function invocations.

Maybe someone else will have some feedback on how best to handle this.

2024-01-15 04:22 UTC, iprime2 commented
I will create a new test to check the name of the function for steps 41 and 42.

2024-01-17 04:48 UTC, iprime2 commented
@lasjorg Can you please review my pull request.

2024-01-17 21:43 UTC, lasjorg commented
We shouldn't require semicolons, as such they can't be used for the function name test.


The assert for the function name should be (replace the name and button as needed)

> You should assign the `goStore` function reference to `button1.onclick`.

The assert for the function invocation should be (replace the name as needed):

> You should not call the `goStore` function. Remove the parentheses.

2024-01-18 04:46 UTC, iprime2 commented
Hey! So the test should pass without a semicolon; only then should it check the function name.
and have to change this from:
You should assign the `goStore` function reference to `button1.onclick.`
to:
You should not call the `goStore` function. Remove the parentheses.

2024-01-18 20:18 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c2fccf186146b59c6e96.md
> +assert.match(code, /button1\.onclick\s*=\s*goStore;/);
```suggestion
assert.match(code, /button1\.onclick\s*=\s*goStore\s*;?\s*$/m);
```
Using the `m` flag should allow us to match on the end.

2024-01-18 20:18 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c4a0e52767482c5202d4.md
> +assert.match(code, /button2\.onclick\s*=\s*goCave;/);
```suggestion
assert.match(code, /button2\.onclick\s*=\s*goCave\s*;?\s*$/m);
```

2024-01-18 20:18 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a3c4a0e52767482c5202d4.md
> +assert.match(code, /button3\.onclick\s*=\s*fightDragon;/);
```suggestion
assert.match(code, /button3\.onclick\s*=\s*fightDragon\s*;?\s*$/m);
```

2024-01-18 22:05 UTC, lasjorg commented
Please make all the requested changes.

If the "Commit suggestion" button is still active that change wasn't made and still needs to be made. You can use the "Commit suggestion" button to add the code as well.

2024-01-22 23:10 UTC, lasjorg requested changes
There are some issues and missing changes but never mind that. Read on.

---

The function invocation test will never run as is. The test before it will always catch the invocation.

I'm sorry to do this, but I think I have changed my mind and we should just remove the dedicated invocation tests.

I say we just combine them so we are left with just one test for each handler assignment.

---

Step 40

You should assign the `goStore` function reference to `button1.onclick`. Make sure not to call the function.

```js
assert.match(code, /button1\.onclick\s*=\s*goStore\s*;?\s*$/m);
```

---

Step 41

You should assign the `goStore` function reference to `button1.onclick`. Make sure not to call the function.

```js
assert.match(code, /button1\.onclick\s*=\s*goStore\s*;?\s*$/m);
```

You should assign the `goCave` function reference to `button2.onclick`. Make sure not to call the function.

```js
assert.match(code, /button2\.onclick\s*=\s*goCave\s*;?\s*$/m);
```

You should assign the `fightDragon` function reference to `button3.onclick`. Make sure not to call the function.

```js
assert.match(code, /button3\.onclick\s*=\s*fightDragon\s*;?\s*$/m);
```

Rechecking the `goStore` function in step 41 can't hurt just to make sure they do not change that in the process of adding the other two handlers.

---

Again, sorry for the extra work required but I think this change is for the best.

2024-01-23 17:51 UTC, iprime2 commented
hey @lasjorg as per your suggestion I implemented `assert.match(code, /button1\.onclick\s*=\s*goStore\s*;?\s*$/);` method to check but the test fails if I provide this correct input `button1.onclick = goStore;` .

2024-01-25 19:34 UTC, iprime2 reviewed
Solved.

2024-01-25 23:26 UTC, lasjorg requested changes
I think the code review is getting a little messy so instead here are the tests for the two steps in their entirety. This is exactly how they should look. If you have any doubts please just copy and paste them.


## Step 40

````md

# --hints--

You should use dot notation to access the `onclick` property of `button1`.

```js
assert.match(code, /button1\.onclick/);
```

You should not use `let` or `const`.

```js
assert.notMatch(code, /(let|const)\s+button1\.onclick/);
```

You should assign the `goStore` function reference to `button1.onclick`. Make sure not to call the function.

```js
assert.match(code, /button1\.onclick\s*=\s*goStore\s*;?\s*$/m);
```

````

---

## Step 41

````md

# --hints--

You should assign the `goStore` function reference to `button1.onclick`. Make sure not to call the function.

```js
assert.match(code, /button1\.onclick\s*=\s*goStore\s*;?\s*$/m);
```

You should use dot notation to access the `onclick` property of `button2`.

```js
assert.match(code, /button2\.onclick/);
```

You should not use `let` or `const` to assign `button2.onclick`.

```js
assert.notMatch(code, /(let|const)\s+button2\.onclick/);
```

You should assign the `goCave` function reference to `button2.onclick`. Make sure not to call the function.

```js
assert.match(code, /button2\.onclick\s*=\s*goCave\s*;?\s*$/m);
```

You should use dot notation to access the `onclick` property of `button3`.

```js
assert.match(code, /button3\.onclick/);
```

You should not use `let` or `const` to assign `button3.onclick`.

```js
assert.notMatch(code, /(let|const)\s+button3\.onclick/);
```

You should assign the `fightDragon` function reference to `button3.onclick`. Make sure not to call the function.

```js
assert.match(code, /button3\.onclick\s*=\s*fightDragon\s*;?\s*$/m);
```

````

2024-01-31 17:08 UTC, lasjorg approved these changes
This looks good.

Thank you, and sorry for the extra work, but we got there.

2024-02-02 10:39 UTC, Sembauke approved these changes

2024-02-02 10:39 UTC, merged