fix(curriculum): Attribute order shouldn't matter Music Player
freeCodeCamp/freeCodeCamp pull request #53186
Opened 2024-01-14 22:17 UTC by DivyaMaddipudi

Attribute order shouldn't matter Music Player Step 72 #53130

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53130

2024-01-15 13:29 UTC, JoyShaheb requested changes

2024-01-16 02:09 UTC, DivyaMaddipudi commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/6557421eb6a7a0f0500e3106.md
> +assert.match(code, /<button(?=.*\bclass="playlist-song-delete")(?=.*\baria-label="Delete [^"]*")(?=.*\bonclick="deleteSong\([^)]*\)")\s+(?:class|aria-label|onclick)="[^"]*"\s+(?:class|aria-label|oncl
@JoyShaheb, I tried your suggestion but it is failing though onclick is present as an attribute anywhere

2024-01-16 04:12 UTC, JoyShaheb commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/6557421eb6a7a0f0500e3106.md
> +assert.match(code, /<button(?=.*\bclass="playlist-song-delete")(?=.*\baria-label="Delete [^"]*")(?=.*\bonclick="deleteSong\([^)]*\)")\s+(?:class|aria-label|onclick)="[^"]*"\s+(?:class|aria-label|oncl
can you try this ?
```suggestion
assert.match(code, /<button(?=(?:(?=.*\bclass=['"]playlist-song-delete['"])(?=.*\baria-label=['"]Delete [^'"]*['"])(?=.*\bonclick=['"]deleteSong\([^)]*\)['"]))(?:.*\s+(?:class|aria-label|onclick)=['"][^'"]*['"])\s*>)/);
```

2024-01-16 05:08 UTC, DivyaMaddipudi commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/6557421eb6a7a0f0500e3106.md
> +assert.match(code, /<button(?=.*\bclass="playlist-song-delete")(?=.*\baria-label="Delete [^"]*")(?=.*\bonclick="deleteSong\([^)]*\)")\s+(?:class|aria-label|onclick)="[^"]*"\s+(?:class|aria-label|oncl
This works! Updated the code.

2024-01-16 06:18 UTC, JoyShaheb approved these changes
well done ! @gikf and @jdwilkin4  can you guys have a final look ?

2024-01-16 08:19 UTC, gikf reviewed
I cannot say I'm not confused how this works, but it indeed appears to allow the various ordering of the attributes.

Regex though doesn't check if the `song.title` and `song.id` are used as interpolated values - anything can be used in their place.

2024-01-19 00:27 UTC, moT01 requested changes
I think we need to check what @gikf mentioned here @DivyaMaddipudi - e.g. the code should not pass with `onclick="deleteSong()"`.

2024-01-29 16:34 UTC, jdwilkin4 commented
Hey @DivyaMaddipudi ! 

It looks like a couple of reviews were left for this PR

Did you have any questions about what changes needed to be made?

2024-02-05 17:02 UTC, Ksound22 commented
Thanks for your contribution, @DivyaMaddipudi.

We've moved on from this cuz another PR has fixed the issue.

2024-02-05 17:02 UTC, closed without merging