fix(curriculum): updating explanation for sort method in music player project
freeCodeCamp/freeCodeCamp pull request #53203
Opened 2024-01-16 05:42 UTC by jdwilkin4

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52936

2024-01-16 16:24 UTC, naomi-lgbt requested changes

2024-01-16 16:24 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/65a60b0b8b4f96085ac23463.md
> +Below your `if` statements, return the number `0` to sort the array in place.
```suggestion
Below your `if` statements, return the number `0` to leave the order of the two elements unchanged.
```

The `.sort()` method sorts the array in place.

2024-01-16 17:07 UTC, naomi-lgbt approved these changes

2024-01-18 04:49 UTC, huyenltnguyen approved these changes

2024-01-18 04:49 UTC, merged