fix(cirriculum)- use alternate instructions for oop step 55
freeCodeCamp/freeCodeCamp pull request #53216
Opened 2024-01-16 22:03 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #53201

The regex behind this was getting a little too complicated, thus I followed gikf's suggestion of just rewording things.

2024-01-16 22:24 UTC, naomi-lgbt approved these changes

2024-01-16 22:35 UTC, jdwilkin4 requested changes
The changes look good for step 55.
Let's also update step 57 since that was mentioned in the issue as having the same problem with the directions. 

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-intermediate-oop-by-building-a-platformer-game/step-57

2024-01-16 23:05 UTC, naomi-lgbt commented
While we're in there, "keyup" should be `keyup`

2024-01-17 22:00 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/64c734293def73808e609778.md
> +destructuring to pass in the `key` property from the event.
```suggestion
Add another `addEventListener` to the global `window` object and pass in the `keyup` event and use destructuring to pass in the `key` property from the event. 
```

This should not be on two lines.

2024-01-18 02:14 UTC, jdwilkin4 approved these changes

2024-01-18 02:48 UTC, merged