Feat(Curriculum) add 6.2 block challenges
freeCodeCamp/freeCodeCamp pull request #53238
Opened 2024-01-17 18:31 UTC by nieldakarla

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-03-11 12:09 UTC, Sembauke requested changes

2024-03-11 12:09 UTC, Sembauke commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-help-a-coworker-troubleshoot-on-github/656bc3bd0a323317d4117a49.md
> +PAst continuous is often used when an action is interrupted by another, as in `I was reading when the phone rang.` The reading was interupted by the phone ringing.
```suggestion
Past continuous is often used when an action is interrupted by another, as in `I was reading when the phone rang.` The reading was interrupted by the phone ringing.
```

2024-03-11 14:13 UTC, Sembauke requested changes

2024-03-11 14:13 UTC, Sembauke commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-help-a-coworker-troubleshoot-on-github/65a84bec88772eaff6e56679.md
> +Let's practice using the present perfect tense to talk about actions that started in the past and are still relevant now.
```suggestion
Imagine you're working on a project and have been trying different solutions over time. To express this ongoing effort, you can use the present perfect tense. This tense connects past actions to the present moment.

The present perfect tense is formed using the auxiliary verb `have` or `has` followed by the past participle of the main verb. For example, `I have been working on this for a long time` or `he has worked on this for a long time`.

Let's practice using the present perfect tense to talk about actions that started in the past and are still relevant now.
```

2024-03-11 14:13 UTC, Sembauke commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-help-a-coworker-troubleshoot-on-github/65a85418ea38cdc0a334dab2.md
> +`If the new app is not working, try rolling back to the previous version.`
```suggestion
`To roll back` means going back to an earlier state or version of something. For example:

`If the new app is not working, try rolling back to the old version.`

A `previous version` is an earlier form of something, like an older version of software. Let's use it in the same sentence as above:

`If the new app is not working, try rolling back to the previous version.`
```

2024-03-11 19:11 UTC, DanielRosa74 approved these changes
LGTM

2024-03-12 03:31 UTC, moT01 requested changes
A couple renaming suggestions to keep things consistent.

2024-03-12 03:31 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-help-a-coworker-troubleshoot-on-github/65b2b0e08ec66535fa8542eb.md
> +title: "Dialogue 3: Talking about Debugging"
```suggestion
title: "Dialogue 3: Talking About Debugging"
```

2024-03-14 08:13 UTC, Sembauke approved these changes

2024-03-14 13:32 UTC, moT01 approved these changes
LGTM 🎉

2024-03-14 13:32 UTC, merged

2024-05-17 05:27 UTC, miyaliu666 commented
@nieldakarla  Based on the order of dialogue, task-12 `Sarah: "Sure, Bob. What’s the problem?"` should be right after task-5 `Bob: Hey, Sarah. I was checking the branch we worked on yesterday when I saw a problem. I think we should open an issue on GitHub.` and before tasks 6-15.

And, I'm confused about tasks 6-15. Tasks 7-11 are teaching new words in `Bob: I pushed some changes to the repository earlier, but now the code won't compile. It's showing some strange errors.`, and tasks 13-15 are designed to practice these words -  I feel these should be before comprehension of this sentence, i.e. task 6.