feat: provide sensible default title/dashedName
freeCodeCamp/freeCodeCamp pull request #53269
Opened 2024-01-18 16:30 UTC by ojeytonwilliams

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This changes the order of questions so that the helper script can use challengeType to infer the likely title and dashedName.

```
? What type of challenge is this? fillInTheBlank
? What is the short name (in kebab-case) for this challenge? (task-30) 
```
then 

```
? What type of challenge is this? fillInTheBlank
? What is the short name (in kebab-case) for this challenge? task-30
? What is the title of this challenge? (Task 30) 
```

2024-01-18 17:39 UTC, naomi-lgbt requested changes
This helper script is specifically used in the challenge creation tools (written for non-step based challenges).

If we're looking for the ability to auto-detect and insert tasks instead of steps, we should update the step utilities for that.

2024-01-18 20:05 UTC, ojeytonwilliams commented
> This helper script is specifically used in the challenge creation tools (written for non-step based challenges).

Sure, the changes don't prevent that, though. They just provide a default that you can ignore if it's irrelevant.

Having said that, it occurs to me that if we make the question order: `challengeType` -> `title` -> `dashedName`, we can simply dasherize `title` to get the `dashedName` default. Or, better still, just ask for `challengeType` and `title`and infer `dashedName`. That should be correct the vast majority of the time and, if it's not, it's easily fixed.

> If we're looking for the ability to auto-detect and insert tasks instead of steps, we should update the step utilities for that.

The step utilities were built under the assumption that a block would have a single challenge type, but that's not the case for the English curriculum. There are three choices and a human has to pick, so this tool seems perfect for that.

2024-01-18 20:21 UTC, naomi-lgbt approved these changes

2024-01-19 01:11 UTC, moT01 approved these changes
LGTM 🎉

2024-01-19 01:11 UTC, merged