breaking(curriculum): add time-calculator to /learnFix/move probability calculator
freeCodeCamp/freeCodeCamp pull request #53282
Opened 2024-01-19 14:43 UTC by zairahira

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-01-23 07:55 UTC, ShaunSHamilton commented on curriculum/challenges/english/07-scientific-computing-with-python/scientific-computing-with-python-projects/probability-calculator.md
> +# Consider using the modules imported above.
```suggestion

```

2024-01-23 08:00 UTC, ShaunSHamilton requested changes
We might also want to think about adding runnable examples to the description; examples that include an output, and some indication as to what the output could/should be.

2024-01-23 15:06 UTC, ShaunSHamilton commented
> Example usage is already there, line 38 on wards. I hope that is what is being requested.

Right. I was going more for something that prints to the console. Currently, that example does nothing.

That is probably fine, because this project's API is so simple Campers can easily figure out adding `print(hat)`. 👍

2024-01-23 16:11 UTC, ShaunSHamilton approved these changes
<s>LGTM 👍 </s>

Oops: The `# --instructions` needs to be `description`

2024-01-24 06:40 UTC, ShaunSHamilton approved these changes
Failing test is unrelated.

2024-01-24 10:31 UTC, ihechikara approved these changes

2024-01-24 12:15 UTC, merged