Fix: create new step 18 for spreadsheet project.
freeCodeCamp/freeCodeCamp pull request #53315
Opened 2024-01-22 10:58 UTC by Vijaychandra-Govindapalle

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52987

I have created a new step 18 for spreadsheet project to properly teach `el.attribute` syntax. And updated step 17 accordingly

2024-01-31 23:25 UTC, jdwilkin4 requested changes

2024-01-31 23:25 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/65ae458e23954c3469e0c209.md
> +```
I don't think we need this test.
We can just use the first one with some updates.

```suggestion
```

2024-01-31 23:25 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/65ae458e23954c3469e0c209.md
> +```
```suggestion
You should have an `input.ariaLabel`.

```js
assert.match(code, /input\.ariaLabel\s*=/);

```
```

2024-01-31 23:25 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/65ae458e23954c3469e0c209.md
> +Attribute `aria-label` for the `input` element should be set to the same value as the `id` attribute.
```suggestion
You should assign `letter + number` to `input.ariaLabel`.
```

2024-02-01 20:25 UTC, gikf commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/65ae458e23954c3469e0c209.md
> +
````suggestion
```
````

2024-02-01 20:25 UTC, gikf commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/65ae458e23954c3469e0c209.md
> +
```suggestion
```

2024-02-01 20:25 UTC, gikf commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/65ae458e23954c3469e0c209.md
> +assert.match(code, /input\.ariaLabel\s*=\s*letter\s\+\snumber/);
```suggestion
assert.match(code, /input\.ariaLabel\s*=\s*letter\s*\+\s*number/);
```

2024-02-02 05:31 UTC, jdwilkin4 approved these changes
the changes look good to me 👍

2024-02-03 13:00 UTC, JoyShaheb approved these changes

2024-02-03 13:00 UTC, merged