Add donation animation AB test
freeCodeCamp/freeCodeCamp pull request #53343
Opened 2024-01-24 14:42 UTC by ahmaxed

This AB test pr adds a 20 second animation to the donation modal.
Make sure to compare the current donation animation with the AB tested version using a screen reader.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

closes #53335

2024-02-05 08:58 UTC, ahmaxed commented on client/src/components/Donation/donation-modal-body.tsx
> +  // donationAnimationFlag = true;
```suggestion
  // uncomment to testing the animation
  // recentlyClaimedBlock = true;
  // donationAnimationFlag = true;
```
Uncomment  donationAnimationFlag to test the animation.
Uncomment recentlyClaimedBlock to see how the modal will look on block completion.

2024-02-05 11:28 UTC, ahmaxed commented on client/src/components/Donation/multi-tier-donation-form.tsx
> +  console.log('isAnimationEnabled', isAnimationEnabled);
```suggestion
```

2024-02-05 12:25 UTC, ojeytonwilliams requested changes

2024-02-05 12:26 UTC, ojeytonwilliams requested changes

2024-02-05 12:26 UTC, ojeytonwilliams commented on client/src/components/Donation/donation-modal-body.tsx
> +  const handleBecomeSupprterClick = () => {
```suggestion
  const handleBecomeSupporterClick = () => {
```

2024-02-05 12:26 UTC, ojeytonwilliams commented on client/src/components/Donation/donation-modal-body.tsx
> +          onClick={handleBecomeSupprterClick}
```suggestion
          onClick={handleBecomeSupporterClick}
```
Oops, missed these.

2024-02-05 13:57 UTC, ahmaxed commented on client/i18n/locales/english/translations.json
> +    "animation-description": "This is a 20 second animation advertisement to encourage campers to become supporters of freeCodeCamp. The animation starts with a teddy bear who to become a supporter.
Thanks for catching that. I edited it a bit further to convey the message of the animation a bit better.

2024-02-06 14:20 UTC, ojeytonwilliams requested changes
It's looking good, Ahmad. The donation animation and disappears as expected.
 
Just a few minor things:

2024-02-06 14:20 UTC, ojeytonwilliams commented on client/src/components/Donation/donation.css
> +} */
```suggestion
```
Can this go?

2024-02-06 14:20 UTC, ojeytonwilliams commented on client/src/components/Donation/donation.css
> +  #donaition-animation {
```suggestion
  #donation-animation {
```
typo

2024-02-06 14:20 UTC, ojeytonwilliams commented on client/src/components/Donation/donation-modal-body.tsx
> +          id={'donaition-animation'}
```suggestion
          id={'donation-animation'}
```
Other half of the typo

2024-02-06 14:20 UTC, ojeytonwilliams commented on client/src/components/Donation/donation-modal-body.tsx
> +          alt={'asdfasd'}
```suggestion
          alt=''
```
Presumably the alt text is unnecessary because the `donate.animation-description` text plays that role.

2024-02-06 15:10 UTC, ahmaxed commented on client/src/components/Donation/donation-modal-body.tsx
> +        {donationAnimationFlag && isAnimationVisible ? (
Thanks, I grouped them into a component accordingly.

2024-02-06 15:30 UTC, ahmaxed commented on client/src/components/Donation/donation.css
> +} */
yes

2024-02-06 17:23 UTC, moT01 reviewed
This looks awesome @ahmaxed 🎉

Found a couple typos.

Couple other notes:

Wondering if we should put the images on the CDN?
Not sure why screen readers get to skip the animation.

Best part: "it graduates and becomes an education super hero helping people around the world."

2024-02-06 17:23 UTC, moT01 commented on client/src/components/Donation/donation-modal-body.tsx
> +      <div className='donation-animatoin-container' aria-hidden='true'>
```suggestion
      <div className='donation-animation-container' aria-hidden='true'>
```

2024-02-06 17:23 UTC, moT01 commented on client/i18n/locales/english/translations.json
> +    "animation-description": "This is a 20 second animated advertisement to encourage campers to become supporters of freeCodeCamp. The animation starts with a teddy bear who to becomes a supporter.
```suggestion
    "animation-description": "This is a 20 second animated advertisement to encourage campers to become supporters of freeCodeCamp. The animation starts with a teddy bear who becomes a supporter. As a result, distracting pop-ups disappear and the bear gets to complete all of its goals. Then, it graduates and becomes an education super hero helping people around the world."
```

2024-02-06 17:25 UTC, moT01 commented
I went ahead a committed my two suggestions so the tests could get started again - hope you don't mind.

2024-02-06 19:19 UTC, ahmaxed commented
Thanks for the review. 

The animation container is aria-disabled. I used a description in a p element instead. Adding the description as an img alt might have been a better idea. 

Let me know if any other accessibility considerations comes to mind. 🙏

2024-02-06 23:35 UTC, ojeytonwilliams commented
It is behind a CDN, but the caching rules don't include all svgs. At least, they shouldn't: https://github.com/freeCodeCamp/client-config/blob/master/serve.json

To get it in the cache, it will need to match the right pattern in serge.json

2024-02-07 07:51 UTC, ahmaxed commented
Thanks for that. After build, the svgs end up in public/static and get renamed with a 32-character hexadecimal string at the end. 

So, they should match the [serve.json](https://github.com/freeCodeCamp/client-config/blob/master/serve.json?rgh-link-date=2024-02-06T23%3A35%3A18Z) pattern.

2024-02-07 09:25 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2024-02-07 12:26 UTC, Sembauke approved these changes

2024-02-07 12:27 UTC, merged