fix: gotta account for the slug too I guess?
freeCodeCamp/freeCodeCamp pull request #53356
Opened 2024-01-25 11:20 UTC by naomi-lgbt

One day I'll refactor this. Maybe.

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Another pain point resolved - this time in #52884

2024-01-25 13:00 UTC, ojeytonwilliams requested changes

2024-01-25 13:00 UTC, ojeytonwilliams commented on tools/scripts/sync-i18n.ts
>          if (engId && langId && engId !== langId) {
```suggestion
        if (engId && engId !== langId) {
```
We know it exists, because of the condtional above.

2024-01-25 13:00 UTC, ojeytonwilliams commented on tools/scripts/sync-i18n.ts
> +        if (engSlug && langSlug && engSlug !== langSlug) {
```suggestion
        if (engSlug && engSlug !== langSlug) {
```

2024-01-25 19:15 UTC, ojeytonwilliams approved these changes

2024-01-26 07:56 UTC, Sembauke approved these changes

2024-01-26 07:56 UTC, merged