feat(i18n): enable korean downloads for client and curriculum
freeCodeCamp/freeCodeCamp pull request #53360
Opened 2024-01-25 18:15 UTC by AlisonYoon

Add Korean translation for the main freeCodeCamp curriculum.
Currently, Responsive Web Design certification course's Korean translation/proofreading work is done in Crowdin.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

2024-01-25 19:33 UTC, ilenia-magoni requested changes
You need to run prettier locally

2024-01-30 04:19 UTC, naomi-lgbt requested changes

2024-01-30 04:19 UTC, naomi-lgbt commented on package-lock.json
This file should not be present. We use `pnpm`, not `npm`.

2024-02-01 19:51 UTC, naomi-lgbt approved these changes

2024-02-02 10:59 UTC, ilenia-magoni approved these changes

2024-02-02 11:00 UTC, merged