feat(curriculum): adding animations to block 2.1
freeCodeCamp/freeCodeCamp pull request #53363
Opened 2024-01-25 22:19 UTC by DanielRosa74

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

2024-02-09 20:06 UTC, nieldakarla requested changes
Looks great Daniel! Thank you for these amazing animations! 🎉🎉
I just found that some of the challenges that need animations to be added. I've also noticed that some tasks on dialogue 4 are out of order and gave a suggestion about the correct order. Besides that, some details about the lessons.

2024-02-09 20:06 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/657e7116e4db87501f898f79.md
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/90112119/dd1bc608-7ec5-40ff-b5d6-9bf32cc32e19)
 I suggest we remove the spaces, this should fix the problem. 

`On weekdays, Sarah _ up at around 6. She _ ready for work after waking up. In the morning, Sarah _ breakfast at home. Then, she _ to the office at 8.`

2024-02-09 20:06 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/657e7194d581bf52d96d452d.md
Same thing here, remove the spaces separating the sentences. and put them all into the same backticks.

2024-02-09 20:06 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/657e76b48cd1db6c9f04a27a.md
We also need the audio on the next challenge the 129. I know it is not this one. It is just that as it was not edited I thought it would be best to mention it here.

2024-02-14 00:31 UTC, nieldakarla approved these changes
Thank you for the Updates, Daniel! It looks great. I think we can ship it.

2024-02-14 01:03 UTC, naomi-lgbt approved these changes

2024-02-14 01:44 UTC, merged