Updated description for step 5 of calorie counter project
freeCodeCamp/freeCodeCamp pull request #53413
Opened 2024-01-29 07:17 UTC by Mishra-Pravin

I understand that the instructions for adding the word “Lunch” inside the legend tag were unclear. Here’s a revised version of the instructions with your suggestion included.

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-01-29 07:49 UTC, JoyShaheb requested changes

2024-01-29 07:49 UTC, JoyShaheb commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63b60821c855d01b1eda3c0b.md
> +Now create a `fieldset` with an `id` set to `lunch`. Inside this `fieldset`, add a `legend` element with the text content `lunch`, and a `div` element with a `class` set to `input-container`.
Please use the solution my colleague @jdwilkin4 provided on the issue discussion, also put some space between the `description` and `hint` tags. Thank you for contributing 🙏

```suggestion
Next, create a `fieldset` element with the `id` set to `lunch`.

Within that element, create a `legend` element with the text `Lunch`, and an empty `div` with the `class` set to `input-container`.
```

2024-02-03 12:47 UTC, JoyShaheb approved these changes

2024-02-03 16:00 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2024-02-03 16:00 UTC, merged