Feat/2.2 dialogues
freeCodeCamp/freeCodeCamp pull request #53412
Opened 2024-01-29 02:52 UTC by DanielRosa74

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Please review this one after the review of Block 2.1 animations and the addition of the new NPC images to the CDN. Dialogue 2 has an NPC, and links are already adapted to the new image. In the old format, it will not show on screen.

2024-02-09 21:37 UTC, nieldakarla requested changes
Great work again! 🎉🎉
I found some challenges out of order. Not sure why those happened. I've added comments with the correct order.

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655795519e1068aac3351755.md
This group is also out of order, It should be: 15, 16, 17, 19, 20, 18, 14, 21

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/6557bb81a99580b97a8b1c3b.md
We should add James' question to the audio for context here.

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/6557bd443a1a57ba598bff47.md
We'll have to change the order here too: 23, 24, 22, 25

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a24f27d595bfb53f1bb3e.md
I think this audio could be just this part: Sophie: So, I'm here because I feel sleepy during the mornings. I don't get productive until it's almost midday

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a256c6fce94fb9c1cc841.md
This one could be just the last part: Do you have any tips on how to have a healthy morning routine?

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a5630b68570156ea7d80e.md
The audio is cutting before he finishes the sentence.

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a7c5211e5252cf8a4ed01.md
Out of order. It should be: 67, 66

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655a8d7c939fcf37604516e4.md
Include Jake's line for context.

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b29fb2c8b1861bf4fbab1.md
We should add his question for context.

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b38c1f5351d6c827c8e8f.md
It is missing this part at the beginning: I have a relaxing Sunday, too.

2024-02-09 21:37 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-your-morning-or-evening-routine/655b39e59c29d16d64a2ce8e.md
Can you please add a definition of "thought" with an example here?

2024-02-14 15:09 UTC, nieldakarla approved these changes
thank you for all the changes, Dani! This looks great!

2024-02-14 15:26 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2024-02-14 15:29 UTC, merged