chore(curriculum): add commas around strings in cypher project
freeCodeCamp/freeCodeCamp pull request #53418
Opened 2024-01-29 14:09 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #51036

2024-01-29 17:46 UTC, Dario-DC approved these changes
LGTM 🎉

2024-01-30 15:42 UTC, zairahira requested changes
As some of my suggestions are outside the scope of the changed files, I have added comments to the individual files.

Also, have a look at this change too:

Step 33

Line #23  

```diff
- You should still have a `text` variable with the value `Hello World`.
+ You should still have a `text` variable with the value `'Hello World'`.
```

2024-01-30 15:42 UTC, zairahira commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/6551eebe6cbb2e6cadf9b468.md
Line #18 

```diff
- Delete your `number` variable and its value. Then, declare another variable called `text` and assign the string `Hello World` to this variable.
+ Delete your `number` variable and its value. Then, declare another variable called `text` and assign the string `'Hello World'` to this variable.
```

2024-01-30 15:42 UTC, zairahira commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-string-manipulation-by-building-a-cipher/65688b5a1655a7a6caede847.md
Line #28 

```diff
- You should reassign `text` the string `Albatross`. Do not modify `text = 'Hello World'`.
+ You should reassign `text` the string `'Albatross'`. Do not modify `text = 'Hello World'`.
```

2024-02-02 12:46 UTC, zairahira approved these changes

2024-02-02 20:24 UTC, merged