fix(curriculum/python): improve shortest path algorithm project
freeCodeCamp/freeCodeCamp pull request #53428
Opened 2024-01-29 19:29 UTC by Dario-DC

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-07 10:28 UTC, ilenia-magoni requested changes
The title confuses me. What is algorithm design? I have not learn anything about that in this. I have learned about dictionaries, tuples and lists tho. Can't we change the name?

2024-05-13 11:27 UTC, fhsinchy approved these changes
I didn't find any issues or inconsistencies 👍

2024-05-14 09:43 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6578b13757611e2825beb8a5.md
> +You should have an `'age'` key with the value `2` just after `'species': 'guinea pig'`, inside your `copper` dictionary. Don't forget the comma.
The original name for this was "Learn Data Structures..." but the merge sort algorithm project has that name. 
I'm okay with changing the name, but not sure about which name we should use.

2024-05-14 09:43 UTC, Dario-DC commented
> The title confuses me. What is algorithm design? I have not learn anything about that in this. I have learned about dictionaries, tuples and lists tho. Can't we change the name?

The original name for this was "Learn Data Structures..." but the merge sort algorithm project has that name. 
I'm okay with changing the name, but not sure about which name we should use.

2024-05-20 09:15 UTC, Dario-DC commented
> The title confuses me. What is algorithm design? I have not learn anything about that in this. I have learned about dictionaries, tuples and lists tho. Can't we change the name?

Can we please get this merged and then deal with the new title in a separate PR? It's becoming a pain.

2024-05-20 09:17 UTC, ilenia-magoni approved these changes

2024-05-20 15:29 UTC, moT01 commented
Is this the way we typically do this? Don't we just make changes to English and then run an i18n sync after it gets merged?

2024-05-20 15:36 UTC, Dario-DC commented
> Is this the way we typically do this? Don't we just make changes to English and then run an i18n sync after it gets merged?

@moT01 To be honest, I'm following what Naomi told me to do (we already did it a couple of times) but I don't understand the point of doing it. If you have an answer, you're very welcome.

I can get rid of the changes to the i18n folders, but then test will fail for Italian and Portuguese. Can we merge the PR then?

2024-05-20 15:40 UTC, moT01 commented
No, if Naomi said to do it like this - we should do it like this. I wasn't sure, that's why I asked.

2024-05-21 14:36 UTC, ilenia-magoni approved these changes

2024-05-21 14:36 UTC, merged