fix:removed unnecessary optional chaining
freeCodeCamp/freeCodeCamp pull request #53467
Opened 2024-01-30 22:42 UTC by israelone

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #53465

2024-01-30 23:17 UTC, jdwilkin4 requested changes
Please update the hint text too.

This needs to be updated 

```md
You should set `userData?.currentSong` to `null`.
```
and this needs to be updated too

```md
You should set `userData?.songCurrentTime` to `0`.
```

2024-01-31 00:55 UTC, israelone commented
> Please update the hint text too.
> 
> This needs to be updated
> 
> ```
> You should set `userData?.currentSong` to `null`.
> ```
> 
> and this needs to be updated too
> 
> ```
> You should set `userData?.songCurrentTime` to `0`.
> ```

This has been taken care of

2024-01-31 05:33 UTC, gikf approved these changes

2024-01-31 06:08 UTC, jdwilkin4 approved these changes

2024-01-31 06:08 UTC, merged