fix(curriculam): Update hint text for step 61 of calorie counter project
freeCodeCamp/freeCodeCamp pull request #53509
Opened 2024-02-02 05:33 UTC by Nitz2611

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53499

2024-02-02 05:44 UTC, JoyShaheb requested changes
just a minor change

2024-02-02 05:44 UTC, JoyShaheb commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9bc53735149084390e5d0.md
> +You should display the first element in the `invalidInputMatch` array after `Invalid Input:`  text using template literal.
```suggestion
You should display the first element in the `invalidInputMatch` array after `Invalid Input: `  text using template literal.
```

2024-02-02 05:49 UTC, Nitz2611 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9bc53735149084390e5d0.md
> +You should display the first element in the `invalidInputMatch` array after `Invalid Input:`  text using template literal.
done

2024-02-02 09:50 UTC, Sembauke requested changes

2024-02-02 09:50 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9bc53735149084390e5d0.md
> +You should display the first element in the `invalidInputMatch` array after `Invalid Input: ` text using template literal.
```suggestion
You should display the first element of the `invalidInputMatch` array after the `Invalid Input:` text by using a template literal.
```

2024-02-02 10:10 UTC, Sembauke approved these changes

2024-02-04 06:54 UTC, JoyShaheb approved these changes
👍

2024-02-04 06:55 UTC, merged