fix(curriculum): Updated hints of step-67 in new js course to pass all tests
freeCodeCamp/freeCodeCamp pull request #53517
Opened 2024-02-02 14:13 UTC by shanmukh-sai2003

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53493 

I have chained the tests as a single assertion to make sure all the hints are satisfied.

![Screenshot 2024-02-02 193256](https://github.com/freeCodeCamp/freeCodeCamp/assets/104721888/15742f82-4d21-4fdb-b3cd-d8931f9a4d34)

![Screenshot 2024-02-02 193451](https://github.com/freeCodeCamp/freeCodeCamp/assets/104721888/b47209f5-10d2-4775-9c7d-67cdd11efe0d)

2024-02-02 21:02 UTC, ilenia-magoni requested changes
only the first test that fail determines what hint is shown, as such we want all tests to be different from each other

2024-02-05 13:08 UTC, shanmukh-sai2003 commented
updated the test to be different form each other.

2024-02-06 07:14 UTC, Ksound22 approved these changes
This PR resolved the issue.

Thanks for the amazing contribution!

2024-02-06 09:03 UTC, ilenia-magoni approved these changes

2024-02-06 09:04 UTC, merged