Fix: update directions and hint text for step 117 of RPG game
freeCodeCamp/freeCodeCamp pull request #53518
Opened 2024-02-02 15:47 UTC by itsmacr8

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #53502

2024-02-02 17:26 UTC, gikf reviewed
These are not the changes required by the linked issue. Please take another look at the post https://github.com/freeCodeCamp/freeCodeCamp/issues/53502#issue-2112928775

2024-02-03 12:49 UTC, itsmacr8 commented
I have updated the code.

2024-02-03 15:24 UTC, jdwilkin4 requested changes

2024-02-04 11:22 UTC, itsmacr8 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a8e271f8e3d1541f9624ad.md
> +Now, Start by assigning `monsters[fighting].name` to the `innerText` property of `monsterName`. Then, assign `monsterHealth` to the `innerText` property of `monsterHealthText`.
Okay.

2024-02-04 12:29 UTC, gikf approved these changes

2024-02-04 13:45 UTC, JoyShaheb approved these changes
LGTM 👍

2024-02-04 15:40 UTC, jdwilkin4 approved these changes
Congrats on your first contribution to our repository. 🎉
We look forward to future contributions. 👍

2024-02-04 15:40 UTC, merged

2024-02-05 11:22 UTC, itsmacr8 commented
Thank you so much for your support and help.