chore(curriculum): add quotes around strings in Role Playing Game
freeCodeCamp/freeCodeCamp pull request #53523
Opened 2024-02-03 16:21 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to https://github.com/freeCodeCamp/freeCodeCamp/issues/51036

2024-02-03 16:31 UTC, jdwilkin4 approved these changes

2024-02-04 06:58 UTC, JoyShaheb requested changes
are all the steps accepting both single and double quotes ? users might trip over using single/ double / backticks. @jdwilkin4 @ilenia-magoni

2024-02-04 12:07 UTC, ilenia-magoni commented
@JoyShaheb yes, all the steps accept both single and double quotes, I don't think I have seen a regex that doesn't have `('|")`, but if you think the tests need to be even more permissive we can open a new issue, here was just about the strings in the descriptions

2024-02-04 12:47 UTC, JoyShaheb approved these changes
since @ilenia-magoni 's solution is accurate to issue description, I'll make it a pass. But @jdwilkin4 and @gikf  what do you say about users who might trip over using backticks?

2024-02-04 12:49 UTC, merged