fix: eyes not blinking in english animations
freeCodeCamp/freeCodeCamp pull request #53544
Opened 2024-02-05 17:16 UTC by moT01

The eyes in the English animations aren't blinking sometimes. I found that the browser is cancelling the requests to load the images:

<img width="1066" alt="Screenshot 2024-02-05 at 11 13 26 AM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/20648924/8f37677a-09fe-4912-bcaa-81d450cc61cd">

Sometimes the images do seem to load. Perhaps some kind of issue with the timeouts in the components causing the browser to cancel the request. Not sure if this has always been an issue - pretty sure it used to work just fine. Anyway, this PR preloads all the images in a scene, which seems to fix the issue. If anyone has an alternative fix, feel free to share.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-02-07 10:10 UTC, ojeytonwilliams commented
I wasn't able to reproduce the bug. Chrome, Brave and Firefox all seem fine and all look like this:
![Blinky](https://github.com/freeCodeCamp/freeCodeCamp/assets/15801806/b96e75a7-dab6-4383-a8e5-b18707e7885a)

2024-02-09 14:15 UTC, moT01 commented
Hmm, perhaps we needed an issue with some more discussion. Daniel was able to reproduce it and I am able to consistently reproduce it. Not sure exactly why it's happening though.

2024-02-09 14:43 UTC, ojeytonwilliams commented
Could you link to the discussion where you see it? Also, is it consistently messed up across different browsers?

2024-02-09 15:20 UTC, moT01 commented
There is no discussion. Daniel messaged me on chat and I just looked into it. I was able to reproduce it on chrome and firefox - so it seemed like it was probably pretty prevalent.

2024-02-09 16:43 UTC, ojeytonwilliams commented
Sorry, I thought you meant a particular dialogue made it obvious.

Anyways, I've been staring at lots of dialogues and they're all blinking, so I'm not sure how to reproduce this.

2024-02-16 09:15 UTC, ojeytonwilliams commented
That's right, Huyen. I've only tested this on Linux. Just to confirm: you don't see the issue on this PR?

2024-02-19 16:44 UTC, zairahira commented
I was able to reproduce the issue in Linux(Chrome + Firefox). The eyes weren't blinking at all.

I have tested Tom's changes and now I can see the eyes are blinking:

[Screencast from 19-02-24 21:41:57.webm](https://github.com/freeCodeCamp/freeCodeCamp/assets/33151350/d2980206-d2d8-4fbc-99e8-1dcc0818b5c2)

2024-02-20 00:18 UTC, naomi-lgbt approved these changes

2024-02-21 06:20 UTC, huyenltnguyen approved these changes
Approving, but I'll let @ojeytonwilliams give the final signoff 🙂

2024-02-21 09:50 UTC, ojeytonwilliams requested changes
Thanks for confirming the fix works (and the explanation, Huyen). I'm happy with the fix, but I think it could be cleaned up a little.

2024-02-21 09:50 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/scene/scene.tsx
> +    img.src = src;
```suggestion
  const loadImage = (src: string | null) => {
    if (src) new Image().src;
```
It's a little cleaner and lets us tidy up below.

2024-02-21 09:50 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/scene/scene.tsx
> +    });
```suggestion
    setup.characters
      .map(({ character }) => Object.values(characterAssets[character]))
      .flat()
      .forEach(loadImage);
```
The linear pipeline is easier to read, imo.

2024-02-21 09:50 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/scene/scene.tsx
> +    });
```suggestion
    commands
      .map(({ background }) =>
        background ? `${backgrounds}/${background}` : null
      )
      .forEach(loadImage);
```
Again, this simplifies the logical flow.

2024-02-26 18:21 UTC, ojeytonwilliams approved these changes
Thanks, Tom. This LGTM :+1:

2024-02-26 18:22 UTC, merged