Add Webhook Feature with Optional Token
freeCodeCamp/freeCodeCamp pull request #53560
Opened 2024-02-06 01:04 UTC by werner33

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52542

This adds the following functionality: 

1) A form on the settings page where a user can add a URL (webhook) and an optional token.

2) When the token is added and when a challenge is completed, a small object is emitted to the URL provided. 

3) The webhook can be updated or deleted at any time on the settings page.

2024-02-06 16:34 UTC, ojeytonwilliams commented
Hi @werner33 thanks a ton for putting this together, it really helps to see the implementation. 

We've started discussing this internally, but it will take us a little time to figure out if this is something we can support. Typically we meet weekly, so, all being well, we should be able to get back to you next week. :crossed_fingers:

2024-02-06 23:09 UTC, werner33 commented
Thanks so much @ojeytonwilliams. I know more changes or refinements may be needed and I am happy to do them. Please let me know if you would like anything else.

2024-03-30 12:33 UTC, ShaunSHamilton requested changes
**Other Changes**:

The client should mention this feature being in "Beta"
  - We want it clear this feature is subject to major change

---

_Thank you for your patience on this_

2024-03-30 12:33 UTC, ShaunSHamilton commented on api-server/src/server/boot/settings.js
> +  const validate = ({ webhook }) => isURL(webhook, { require_protocol: true });
We should require `https` here.

2024-03-30 12:33 UTC, ShaunSHamilton commented on client/src/components/settings/webhook.tsx
> +    if (!isURL(newWebhook)) {
Validation should match server.

2024-03-30 12:33 UTC, ShaunSHamilton commented on api-server/src/server/utils/middleware.js
> +  } catch (error) {
This error is forgotten about. I would send it to the client, and make the client error more specific that the sent resource did not successfully respond.

2024-03-30 12:33 UTC, ShaunSHamilton commented on api-server/src/server/utils/middleware.js
> +    await triggerWebhook(webhook, webhookSecret, username);
URL validation should occur before making first contact.

2024-03-30 12:33 UTC, ShaunSHamilton commented on api-server/src/server/boot/challenge.js
> +      });
I cannot think of something more useful than just throwing away any error.

```suggestion
      }).catch(() => {});
```

2024-04-15 06:58 UTC, ShaunSHamilton commented
@werner33 We realise this feature has taken longer to get reviewed than desirable. If you do not mind, I can push the changes necessary to resolve my previous review?

2024-04-15 12:22 UTC, werner33 commented
Please feel free to make any changes. I don’t mind. I made some changes
that you might see there. Thanks so much!

On Mon, Apr 15, 2024 at 2:59 AM Shaun Hamilton ***@***.***>
wrote:

> @werner33 <https://github.com/werner33> We realise this feature has taken
> longer to get reviewed than desirable. If you do not mind, I can push the
> changes necessary to resolve my previous review?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/53560#issuecomment-2055710090>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFJB3JXBCQGNQK35WVQPF3Y5N3ELAVCNFSM6AAAAABC3DG5GWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANJVG4YTAMBZGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-15 17:14 UTC, ShaunSHamilton commented
@werner33 I am making changes to this PR, and should push them up tomorrow.

For the initial launch, we do want to restrict the URLs allowed in the webhooks. Would you mind sharing the URL **you** are interested in receiving on?

2024-04-16 04:22 UTC, raisedadead commented
Hey @werner33 do yo mind replying over on GitHub's UI - it seems the email reply has a bad format. Cheers.

2024-04-19 01:33 UTC, werner33 commented
@ShaunSHamilton Thank you so much for the work you are doing here. I really appreciate it. 

@raisedadead I saw your message today. I'm sorry I got very sick on the 15th and have only today been back on my computer at all. I think the info is resolved but please do let me know if anything else is needed. 

Thank you both very much!

2024-04-19 05:18 UTC, raisedadead commented
Hey @werner33 - No worries – we work async. I just wish you a speedy recovery. If we have any further questions we will let you know. Cheers.

2024-04-23 15:49 UTC, raisedadead commented
Hey @werner33 

Thanks a lot for your patience with this. We had a long meeting about this feature. We have unfortunately come to the conclusion that it will add significant challenges in moving this over to the new API.

In an ideal world we want to offload sending webhook events to a "micro-service". That's something I think we do not want to build into the current API.

I am happy to meet you to explain this in detail if you are interested in the technicals.

Thanks again, I think we like the idea of webhooks and we will build this in the new API with the GitHub-style experience you and I talked about.

It should be more powerful and secure that way.

Cheers!

2024-04-23 15:49 UTC, closed without merging

2024-04-23 21:12 UTC, werner33 commented
@raisedadead Man that is hugely disappointing. I was really hoping to make this a much bigger part of our program. 

Thank you for letting me know. Let me know if I can be helpful in the future. 

Thank you.