fix : multiple issues with the pass keyword in the python case converter project
freeCodeCamp/freeCodeCamp pull request #53602
Opened 2024-02-07 21:01 UTC by JBhrayn

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53392

I wrote test cases to rectify multiple issues where steps are able to succeed even if pass statement/s was erroneously present in the code when it shouldn't have been or vice versa. Also,  I updated the instructions to explicitly mention adding a pass statement in the early steps and implicitly in the succeeding ones.

2024-02-08 16:06 UTC, UltraStorm24 commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter-program/657e928716b77b2277980276.md
da fuck is this

2024-02-08 16:33 UTC, Dario-DC requested changes

2024-02-08 16:33 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter-program/657ef2a86d4e545cec9a85fb.md
> +For now, add a `pass` statement in the if statement body.
I wouldn't change the original sentence. It should be pretty clear that `pass` needs to be moved inside the new `if`.

2024-02-08 16:33 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter-program/657ef2a86d4e545cec9a85fb.md
> +You should add a `pass` statement in the `if` statement body.
Remove this test as it is very unlikely to show up.

2024-02-08 16:33 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter-program/657ef2a86d4e545cec9a85fb.md
> +    }
```suggestion
   test: () => {
        const commentless_code = __helpers.python.removeComments(code)
        const {block_body} = __helpers.python.getBlock(commentless_code, /for\s+char\s+in\s+pascal_or_camel_cased_string\s*/);
        assert.notMatch(block_body, /^\s+pass/);

    }
```

2024-02-08 16:33 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter-program/657ef2a86d4e545cec9a85fb.md
>  })
Please change the previous hint into:

You should write a new `if` statement with `char.isupper()` as the condition. Remember to add the colon at the end and use the `pass` keyword to fill the `if` statement body.

And the test into:

```
({
    test: () => {        
        const commentless_code = __helpers.python.removeComments(code)
        const transformedCode = commentless_code.replace(/\r/g, "");
        const {function_body} = __helpers.python.getDef("\n" + commentless_code, "convert_to_snake_case");
        assert.match(function_body, /\s+if\s+char\.isupper\s*\(\s*\)\s*:\s+pass/);
    }
})
```

2024-02-09 08:50 UTC, Dario-DC reviewed
Tests are passing now and this can be merged as it is but I'll ask you to change the "Closes #" into "partially solve #" in the PR description.

Otherwise it would be great if you could add a test in step 12 and step 14 to check that `pass` is removed.

2024-02-12 08:36 UTC, Dario-DC requested changes
After this change, it looks good to me.

2024-02-12 08:36 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-list-comprehension-by-building-a-case-converter-program/657f0353c9523d7d896873ea.md
> +        const { function_body } = main;
```suggestion
        const commentless_code = __helpers.python.removeComments(code);
        const transformedCode = commentless_code.replace(/\r/g, "");
        const main = __helpers.python.getDef("\n" + transformedCode, "main");
        const { function_body } = main;
```

2024-02-12 10:24 UTC, Dario-DC approved these changes
Thank you for your contribution 🎉

2024-02-13 18:28 UTC, ilenia-magoni approved these changes

2024-02-13 18:28 UTC, merged

2024-02-13 18:28 UTC, ilenia-magoni approved these changes