fix(curriculum): fix typos in expense tracker step 4
freeCodeCamp/freeCodeCamp pull request #53673
Opened 2024-02-12 23:38 UTC by shriyakalakata

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53672

2024-02-13 04:57 UTC, gikf approved these changes

2024-02-13 08:25 UTC, Dario-DC requested changes

2024-02-13 08:25 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/65822308ded1ba4632f66aa3.md
>  Create a dictionary with a key `amount` and value of the `amount` parameter and pass your new dictionary to the `.append()` call.
```suggestion
Create a dictionary with a key `'amount'` and value of the `amount` parameter and pass your new dictionary to the `.append()` call.
```

2024-02-13 18:24 UTC, ilenia-magoni approved these changes

2024-02-13 19:17 UTC, ilenia-magoni requested changes
I noticed you put extra quotes around this variable, please change that.

2024-02-13 19:17 UTC, ilenia-magoni commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-lambda-functions-by-building-an-expense-tracker/65822308ded1ba4632f66aa3.md
> +Create a dictionary with a key `'amount'` and value of the `'amount'` parameter and pass your new dictionary to the `.append()` call.
```suggestion
Create a dictionary with a key `'amount'` and value of the `amount` parameter and pass your new dictionary to the `.append()` call.
```

2024-02-13 20:28 UTC, ilenia-magoni approved these changes

2024-02-14 07:24 UTC, Dario-DC approved these changes

2024-02-14 07:24 UTC, merged