feat(tools): automatically lowercase directories
freeCodeCamp/freeCodeCamp pull request #53729
Opened 2024-02-14 21:53 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I wanted to use the lowercase directories plugin but because I forgot that the total number of directories underneath the relevant folders isn't known and can change over time, it was best to use a shell command.

2024-02-28 04:35 UTC, naomi-lgbt requested changes
Hmmm, I think it might be better to update the plugin to be recursive?

2024-03-16 12:24 UTC, Nightrider1983 commented on .github/workflows/crowdin-download.client-ui.yml
> +
000/$/

2024-05-23 14:38 UTC, ojeytonwilliams commented
Hi @a2937 are you still working on this? If you are, could you have a look at the merge conflict?

2024-05-23 20:01 UTC, a2937 commented
I will work on getting this finished as soon as I an able to though.

2024-05-24 09:51 UTC, ojeytonwilliams commented
Awesome, thanks @a2937. We just weren't sure if you were still working on this. There's no rush, though, please take whatever time you need.

2024-05-26 17:13 UTC, naomi-lgbt approved these changes

2024-06-03 08:29 UTC, Sembauke approved these changes

2024-06-03 08:29 UTC, merged