Chore(curriculum)(new javascript course): add quotes to strings in todo app
freeCodeCamp/freeCodeCamp pull request #54008
Opened 2024-03-07 03:27 UTC by 1jds

Checklist:

- [ x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This PR is related to #51036 about Quotes in Code Strings. I have looked over all of the steps in 'JavaScript Algorithms and Data Structures (Beta) --> Learn localStorage by Building a Todo App'. I only found five steps where quotation marks could be added (viz. steps 19-22, and step 46).

2024-03-07 07:34 UTC, Sembauke requested changes
Hey @1jds,

Thanks for taking this on. The hints should also be in quotes, could you change this?

2024-03-07 09:43 UTC, 1jds commented
@Sembauke 

Thank you for the suggestion. I have updated the PR in line with your request to put quotes around relevant strings in the hints as well.

2024-03-07 09:44 UTC, Sembauke approved these changes

2024-03-08 03:08 UTC, huyenltnguyen approved these changes

2024-03-08 03:08 UTC, merged