feat(curriculum): add English curriculum block 7.1 document code
freeCodeCamp/freeCodeCamp pull request #54014
Opened 2024-03-07 13:13 UTC by miyaliu666

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-04-25 23:19 UTC, naomi-lgbt requested changes

2024-04-25 23:19 UTC, naomi-lgbt commented on client/src/components/Progress/progress.tsx
This change should be reverted.

2024-05-06 17:40 UTC, moT01 reviewed
I hope you don't mind @miyaliu666, I push a few commits to this PR.

This LGTM 🎉 

The only thing I noticed is that `README` could maybe be in backticks? I'm not actually sure though. It's pretty minor, and I think it's fine for now.

2024-05-06 17:40 UTC, moT01 approved these changes

2024-05-06 20:59 UTC, naomi-lgbt approved these changes

2024-05-06 20:59 UTC, merged