fix(api): send msUsername in get session user endpoint
freeCodeCamp/freeCodeCamp pull request #54050
Opened 2024-03-11 18:59 UTC by Nirajn2311

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54049

2024-03-12 01:22 UTC, moT01 approved these changes
LGTM 🎉 

Only thing I potentially see is - do we want to delete the msUsername in the test after the test runs?

2024-03-21 09:12 UTC, ShaunSHamilton requested changes
Create many to create one is a bit odd.

2024-03-21 09:12 UTC, ShaunSHamilton commented on api/src/routes/user.test.ts
> +      });
```suggestion
      test('GET returns the msUsername if it exists', async () => {
        await fastifyTestInstance.prisma.msUsername.create({
          data: msUsernameData[0] as (typeof msUsernameData)[0]
        });

        const msUsernames = await fastifyTestInstance.prisma.msUsername.count();
        expect(msUsernames).toBe(1);

        const response = await superGet('/user/get-session-user');

        const { msUsername } = response.body.user.foobar;

        expect(msUsername).toBe(msUsernameData[0]?.msUsername);
      });
```

2024-03-21 09:12 UTC, ShaunSHamilton commented on api/src/routes/user.ts
> +          where: { userId: req.session.user.id }
After Oliver's PR, I believe this is what we now want:

```suggestion
          where: { userId: req.user?.id }
```

2024-03-28 16:13 UTC, ShaunSHamilton approved these changes

2024-03-28 16:14 UTC, ShaunSHamilton commented
Thanks, Niraj

2024-03-28 16:14 UTC, merged