chore: update Execa to v8
freeCodeCamp/freeCodeCamp pull request #54061
Opened 2024-03-12 14:31 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-03-14 16:06 UTC, Nirajn2311 approved these changes

2024-03-14 16:10 UTC, Nirajn2311 requested changes
My bad, pnpm hadn't installed the packages properly. The `precypress` command fails when using the updated package because the import fails as the package is pure ESM.

2024-03-14 16:13 UTC, Nirajn2311 commented
Yea that sounds like a good idea. We can do what execa does with node itself easily.

2024-03-15 08:48 UTC, ojeytonwilliams requested changes
There's a lot of unrelated changes in the lockfile, could you revert the changes and just `pnpm remove execa`?

2024-03-15 08:48 UTC, ojeytonwilliams commented on cypress-install.js
```suggestion
```
Cypress itself logs this, so we don't have to.

2024-03-15 08:48 UTC, ojeytonwilliams commented on cypress-install.js
>  const pkg = require('cypress/package.json');
```suggestion
```
Unnecessary if we're not logging.

2024-03-15 08:48 UTC, ojeytonwilliams commented on cypress-install.js
> +  console.log('Cypress installation finished with code:', code);
```suggestion
  if (code) {
    console.error('Cypress installation failed with code:', code);
  }
```
Again, Cypress logs for us, so we don't need to log if it worked.

2024-03-15 09:07 UTC, Sembauke commented
This should do it @ojeytonwilliams

2024-03-15 09:14 UTC, closed without merging

2024-03-15 09:15 UTC, Sembauke commented
Never mind I will open a fresh pr for this one.

2024-03-15 09:50 UTC, ojeytonwilliams commented
There's no need to open a new PR - it just creates noise.  The only reason to close this would be if we're not intended to make the change (and we are).