feat(curriculum): add animations to block 3.3 of the English Curriculum
freeCodeCamp/freeCodeCamp pull request #54115
Opened 2024-03-16 01:24 UTC by DanielRosa74

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

2024-03-18 22:13 UTC, nieldakarla requested changes
That is excellent, @DanielRosa74 ! I've added a few comments on 3 tasks that need to be reordered and missing sentences that weren't covered. 

I also suggest you include the missing sentences to the text of type 22 tasks. Maybe even adding a few blanks if necessary.

2024-03-18 22:13 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/65d750f42fb8c69d48edb565.md
Add Maria's sentence: He's been with us for some time, nearly ten years. He's tall and has curly hair. He always has this vigilant look, probably a result of his job.

I also suggest adding some gaps to the fill-in-the-blank to cover these new sentences.

2024-03-18 22:13 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/65d75185d536899fd3c01977.md
Add to 62 and 63: He sounds like a dedicated professional. I've always wondered what the folks in Security do around here. What are his responsibilities?

2024-03-18 22:13 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/65d87217064c730ef7bc63fe.md
Add space between Maria and Tom's lines.

2024-03-18 22:13 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/65d890f37666763b1c08e284.md
this one doesn't need Bob's line

2024-03-20 00:55 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/65d892ad7262d64a5db56906.md
Task 78 one doesn't need Bob's line

2024-03-20 00:58 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/65d8713fd64b650c269676cd.md
Add space between Maria and Tom's lines.

2024-03-20 01:00 UTC, nieldakarla approved these changes

2024-03-20 01:09 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-roles-and-responsibilies/65d8713fd64b650c269676cd.md
A new line has no effect on the template literals and, if I got it correctly, there can be only one fill-in-the-blank line.

2024-03-20 02:04 UTC, naomi-lgbt approved these changes

2024-03-20 02:04 UTC, merged