feat(curriculum): add English curriculum block 6.3 clarification on code understanding
freeCodeCamp/freeCodeCamp pull request #54124
Opened 2024-03-17 15:07 UTC by miyaliu666

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-04-25 23:23 UTC, naomi-lgbt requested changes
Tiny little detail here broke the tests

2024-04-25 23:23 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-ask-for-clarification-on-code-understanding/65f59409f39a43b8d90b53f7.md
> +# --description–-
```suggestion
# --description--
```

2024-04-26 03:22 UTC, miyaliu666 commented
@naomi-lgbt Thanks for reviewing the PRs. Should I update the status label after applying the review suggestions?

2024-05-06 18:22 UTC, moT01 requested changes
This looks good @miyaliu666 🎉 

Do you mind removing the `audioPath` from all the challenge files?

2024-05-07 13:06 UTC, moT01 approved these changes
LGTM 🎉

2024-05-07 18:36 UTC, naomi-lgbt requested changes

2024-05-07 18:36 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-ask-for-clarification-on-code-understanding/65f52fb434a8875cb666ede5.md
> +`seem to be` is used when you are not sure about something and you want to guess or suggest a possibility. For example, if you say `It seems to be working`, you are guessing that something is working
```suggestion
`Seem to be` is used when you are not sure about something and you want to guess or suggest a possibility. For example, if you say `It seems to be working`, you are guessing that something is working but you are not 100% sure.
```

If it's at the beginning of a sentence it should be capitalised.

2024-05-08 03:38 UTC, naomi-lgbt approved these changes

2024-05-08 03:38 UTC, merged