issue: #54047
freeCodeCamp/freeCodeCamp pull request #54123
Opened 2024-03-17 13:03 UTC by ajcruise007

remove monospace from titles

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #54047

2024-03-17 23:23 UTC, naomi-lgbt requested changes

2024-03-17 23:23 UTC, naomi-lgbt commented on client/src/components/layouts/global.css
> +  font-family: var()--font-family-sans-serif;
```suggestion
  font-family: var(--font-family-sans-serif);
```

2024-03-18 03:40 UTC, ajcruise007 commented on client/src/components/layouts/global.css
> +  font-family: var()--font-family-sans-serif;
Changes done @naomi-lgbt , was a typo my bad.

2024-03-18 04:06 UTC, ajcruise007 commented
hi @huyenltnguyen , how will I come to know that the issue is open for contribution?

2024-03-18 04:07 UTC, ajcruise007 commented
I'm a little bit new to open source, but I would love to contribute to this repo.

2024-04-03 04:13 UTC, ahmaxed commented
@ajcruise007,  let me know if you have any questions.

2024-04-04 06:02 UTC, huyenltnguyen approved these changes
I've updated the PR to remove the font family overrides.

They are no longer needed as sans-serif is the default font family:

https://github.com/freeCodeCamp/freeCodeCamp/blob/b0d547e07addea7dac45471b60c5ca2154f0d484/client/src/components/layouts/global.css#L17-L19

2024-04-04 10:28 UTC, Sembauke approved these changes

2024-04-05 01:37 UTC, naomi-lgbt approved these changes

2024-04-05 01:38 UTC, merged