fix(client): put /update-email behind authentication
freeCodeCamp/freeCodeCamp pull request #54128
Opened 2024-03-18 07:07 UTC by huyenltnguyen

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR:
- Updates the Update Email page to block access if the user is not logged in
- Is an alternative to #52571. The PR adds the signin check directly to `client/src/pages/update-email.tsx`, while mine converts the page to a client-only-route
  - Related discussion: https://github.com/freeCodeCamp/freeCodeCamp/pull/52571#discussion_r1500239514
- Closes #52568

**Note for reviewers:** The PR involves moving files around as well as renaming them. Reviewing by commits is recommended.

## Result

https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/369883c0-a2ea-421b-853b-abaa7ded4431

2024-03-18 08:08 UTC, huyenltnguyen reviewed
Tests passed locally but failed in CI. I'll dig deeper 🥲 

<img width="599" alt="Screenshot 2024-03-18 at 15 08 25" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/614d2341-96ca-4a74-b0a0-adfdee97e8dc">

2024-06-19 13:45 UTC, raisedadead approved these changes

2024-06-20 08:11 UTC, ojeytonwilliams requested changes
Nice work, @huyenltnguyen!

I think we can tidy up some stuff while we're here:

2024-06-20 08:11 UTC, ojeytonwilliams commented on e2e/update-email.spec.ts
> +    }
```suggestion
    await page.waitForURL(/\/learn\/?/);
```
I'm in two minds about this if this is an improvement, but it is a little more concise :shrug:

2024-06-25 14:12 UTC, ojeytonwilliams commented on e2e/update-email.spec.ts
> +    test.skip(browserName === 'firefox');
It seems fine to skip for now. Thanks for looking into this, @huyenltnguyen

2024-07-02 15:08 UTC, ojeytonwilliams approved these changes
Nice work, @huyenltnguyen!

LGTM :+1:

2024-07-02 15:08 UTC, merged