chore(curriculum) add quotes to strings intermediate OOP
freeCodeCamp/freeCodeCamp pull request #54174
Opened 2024-03-22 02:56 UTC by 1jds

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

**This PR relates to issue #51036**

The curriculum in question is: JavaScript Algorithms and Data Structures (Beta): Learn Intermediate OOP by Building a Platformer Game

I have made changes to the following steps: 11, 19, 20, 37, 39, 51, 54, 57, 60, 70, 98, 106, 108, 112

Step 11: There was a typo "the the browser screen"
Step 19: Quotation marks added around the hex color code
Step 20: Instructions changed slightly for clarity
Step 37: Quotation marks added around the word "block" and "none"
Step 39: Test altered slightly by adding a negative lookahead in the regex so as to accept a reference to the 'startGame' function but to not accept 'startGame' being invoked with parentheses. **I have tested this (and all the changes in this PR) in GitPod, but it would be worth reviewing this one closely to make sure the RegEx is ok.**
Step 51: Typo; the plural of axis is axes
Step 54: Added backticks around "ArrowLeft" so that it displays consistently with other steps
Step 57: Added clarification that " " has a space rather than being an empty string
Step 60: Added backticks around the number 8 to be consistent with Step 62 where the number 0 was already surrounded by backticks
Step 70: Added quotation marks around the hex color code
Step 98: Added quotation marks around the hex color code; updated the tests for this step to have more incremental hints
Step 106: Added quotation marks around "block" and made slight change to instructions for clarity
Step 108: Added quotation marks around "none"
Step 112: Added a comma in the 'seed' JS so that campers don't have to make changes to the code outside of the 'editable region'; updated the tests to accept either "checkpoints[index - 1].claimed === true" OR "checkpoints[index - 1].claimed" since ".claimed" references a boolean. **This may or may not be a desirable change. This should be looked at.**

2024-03-26 23:00 UTC, jdwilkin4 requested changes
Looks good.
Left a few comments 👍

2024-03-26 23:00 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/65b2bb4c279af3cd585ba777.md
> +You should have a checkpoint detection rule that checks for the following: `index === 0 || checkpoints[index - 1].claimed === true` or `index === 0 || checkpoints[index - 1].claimed`.
Let's revert this change for now. 
It is outside of the scope of this particular PR.
It is best to contain all related changes into one PR and then open up separate ones for other changes.
Plus there is probably are some other changes that can be made to this wording and tests but that should be handled in a separate issue and PR.

2024-03-26 23:00 UTC, jdwilkin4 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/65b2bb4c279af3cd585ba777.md
> +assert.match(code, /index\s*===\s*0\s*\|\|\s*checkpoints\[index\s*-\s*1\]\.claimed(?!\s*===\s*false)/i);
same note here

Let's revert this change for now. 
It is outside of the scope of this particular PR.

2024-03-27 11:12 UTC, Ksound22 reviewed
In step 1, aren't both `start-btn` and `canvas`  supposed to be surrounded with quotes too?

2024-03-28 11:36 UTC, 1jds commented
Hello, Ksound22, 

The instructions for Step 1 could be changed from this:
>In this project, you are going to learn intermediate Object Oriented Programming principles by building a platformer game. 
>All of the HTML and CSS have been provided for you.
>Start by using `document.getElementById()` to get the `#start-btn` and `#canvas` elements.
>Store them in `const` variables named `startBtn` and `canvas` respectively.

to the following:
>In this project, you are going to learn intermediate Object Oriented Programming principles by building a platformer game. 
>All of the HTML and CSS have been provided for you.
>Start by using `document.getElementById()` with `"start-btn"` and `"canvas"` to get the `#start-btn` and `#canvas` elements.
>Store them in `const` variables named `startBtn` and `canvas` respectively.

However, I wasn't sure whether this would be a desired change. I read the original instructions as pointing campers towards the DOM elements in question and leaving it up to them to fill in the blanks as to what exactly they would need to pass to `document.getElementById()`. The original issue was around disambiguating when something is a string (as opposed to, say, a variable name).

Either way could work, so I'm happy to go with what you all think is best.

2024-03-28 13:16 UTC, Ksound22 commented
> Hello, Ksound22,
> 
> The instructions for Step 1 could be changed from this:
> 
> > In this project, you are going to learn intermediate Object Oriented Programming principles by building a platformer game.
> > All of the HTML and CSS have been provided for you.
> > Start by using `document.getElementById()` to get the `#start-btn` and `#canvas` elements.
> > Store them in `const` variables named `startBtn` and `canvas` respectively.
> 
> to the following:
> 
> > In this project, you are going to learn intermediate Object Oriented Programming principles by building a platformer game.
> > All of the HTML and CSS have been provided for you.
> > Start by using `document.getElementById()` with `"start-btn"` and `"canvas"` to get the `#start-btn` and `#canvas` elements.
> > Store them in `const` variables named `startBtn` and `canvas` respectively.
> 
> However, I wasn't sure whether this would be a desired change. I read the original instructions as pointing campers towards the DOM elements in question and leaving it up to them to fill in the blanks as to what exactly they would need to pass to `document.getElementById()`. The original issue was around disambiguating when something is a string (as opposed to, say, a variable name).
> 
> Either way could work, so I'm happy to go with what you all think is best.

I think it's okay as it is then.

2024-04-01 15:33 UTC, jdwilkin4 approved these changes

2024-04-02 13:39 UTC, Sembauke approved these changes

2024-04-02 13:40 UTC, merged