feat(curriculum): Add play scene keyboard shortcut
freeCodeCamp/freeCodeCamp pull request #54195
Opened 2024-03-24 10:11 UTC by abhinavkgrd

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #52696

There is some issue with the translation, I have added the string to the english translation file, but its not getting translated and the key is directly printed  
<details>

<summary>Screenshot attached </summary>

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/46242073/83cd362d-ae59-45d2-b804-5f5b6d65d4ef)

</details>

2024-03-24 10:31 UTC, gikf commented
> There is some issue with the translation, I have added the string to the english translation file, but its not getting translated and the key is directly printed

Running `pnpm run clean:client` should fix that.

2024-04-01 09:17 UTC, abhinavkgrd commented
Just checking up, is anything blocking the PR?

2024-04-02 21:59 UTC, naomi-lgbt requested changes
Thanks for your efforts here! This is a bit of a tricky one, so...

Operating under the assumption that we **only** want `Ctrl+Space` to start the audio, and **not** to be able to stop it:

- First, `isPlaying` isn't an accurate variable name here, because that's not actually what we're passing to the `setIsPlaying` functions. We're passing a boolean representing whether it **should be playing** or not. Review comments propose a clearer variable name.
- Second, we're missing the `playScene` prop in the `Hotkeys` elements for both the fill in the blank layout and the odin layout.

2024-04-02 21:59 UTC, naomi-lgbt commented on client/src/templates/Challenges/components/scene/scene.tsx
> +  setIsPlaying: (isPlaying: boolean) => void;
```suggestion
  setIsPlaying: (shouldPlay: boolean) => void;
```

2024-04-02 21:59 UTC, naomi-lgbt commented on client/src/templates/Challenges/dialogue/show.tsx
> +  };
```suggestion
  setIsScenePlaying = (shouldPlay: boolean) => {
    this.setState({
      isScenePlaying: shouldPlay
    });
  };
```

2024-04-02 21:59 UTC, naomi-lgbt commented on client/src/templates/Challenges/fill-in-the-blank/show.tsx
> +  };
```suggestion
  setIsScenePlaying = (shouldPlay: boolean) => {
    this.setState({
      isScenePlaying: shouldPlay
    });
  };
```

2024-04-02 21:59 UTC, naomi-lgbt commented on client/src/templates/Challenges/odin/show.tsx
> +  };
```suggestion
  setIsScenePlaying = (shouldPlay: boolean) => {
    this.setState({
      isScenePlaying: shouldPlay
    });
  };
```

2024-04-03 17:04 UTC, naomi-lgbt approved these changes
I think this is fine as is. I played around with making it toggle start/stop, and restarting the dialogue a second time resulted in strange behaviour. Fixing that would be out of scope for this PR, so I'm happy to land as is. :3

2024-04-04 12:32 UTC, Sembauke requested changes

2024-04-04 12:32 UTC, Sembauke commented on client/i18n/locales/english/translations.json
> +    "navigate-next": "Navigate Next Exercise",
```suggestion
    "navigate-next": "Navigate To Next Exercise",
```

2024-04-04 12:32 UTC, Sembauke commented on client/i18n/locales/english/translations.json
>      "navigate-previous": "Navigate Previous Exercise",
```suggestion
    "navigate-previous": "Navigate To Previous Exercise",
```

2024-04-04 12:51 UTC, abhinavkgrd commented
Heyy @Sembauke , They are not in scope for this PR , Maybe it would be better to fix them in different PR? But, yes I can include them if you want.

2024-04-04 13:38 UTC, Sembauke approved these changes

2024-04-04 13:38 UTC, merged