fix: make it easier to show and focus shortcuts modal
freeCodeCamp/freeCodeCamp pull request #54201
Opened 2024-03-25 06:47 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-03-26 03:10 UTC, moT01 requested changes
I like the logged in experience, but if I am not logged in, I can see the shortcuts modal - then when I click the button to turn them on, I get an "access token required" message. Seems like we maybe need to disable the buttons and add a "sign in to enable keyboard shortcuts" cta or something - or maybe disable the modal if you aren't logged in.

2024-03-26 03:40 UTC, bbsmooth commented
> It will now also be enabled regardless of shortcuts being enabled.

I know I'm going to be labelled a killjoy here, but this is technically a WCAG violation unless you give the user a way to remap the "?" shortcut to something else. Keyboard shortcuts are turned on by default, and I'm guessing the overwhelming majority of people do not turn them off, so basically it's already as if the shortcut keys are on at all times. I don't see why we couldn't respect the very few people (if any) who want to turn the shorcuts off?

2024-03-26 06:57 UTC, Sembauke commented
I will revert that change, it does not add anything extra other than violate the accessibility guidelines. So the shortcuts are disabled by default, so there is no need to add a check "if the user is logged in".

2024-04-03 00:57 UTC, naomi-lgbt approved these changes

2024-04-12 18:14 UTC, moT01 approved these changes

2024-04-12 18:14 UTC, merged