feat(curriculum): add English curriculum block 7.3 analyzing code documentation
freeCodeCamp/freeCodeCamp pull request #54244
Opened 2024-03-29 11:27 UTC by miyaliu666

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-04-02 23:50 UTC, naomi-lgbt requested changes
This is looking good! I just have a couple of tiny nitpicks.

2024-04-02 23:50 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-analyze-code-documentation/66068d4033a07d9393291ef0.md
> +`provides`
```suggestion
`provide`
```

The documentation can provide examples.

2024-04-02 23:50 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-analyze-code-documentation/6606989c34f0be9d141130b1.md
> +`Calm down` is Sophie's decision to relax and reduce stress.
```suggestion
Part of Sophie's decision to relax and reduce stress.
```

Not sure we want to reveal the actual answer here.

2024-04-05 18:29 UTC, naomi-lgbt approved these changes
Should be good to land.

2024-04-12 19:16 UTC, moT01 requested changes

2024-04-12 19:16 UTC, moT01 commented on curriculum/challenges/_meta/learn-how-to-analyze-code-documentation/meta.json
> +      "title": "Dialogue 1: Analyzing API documentation"
```suggestion
      "title": "Dialogue 1: Analyzing API Documentation"
```

2024-04-12 19:16 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-analyze-code-documentation/6606682f3fbb93838673920d.md
> +title: "Dialogue 1: Analyzing API documentation"
```suggestion
title: "Dialogue 1: Analyzing API Documentation"
```

2024-04-12 19:17 UTC, moT01 approved these changes
LGTM 🎉

2024-04-12 19:41 UTC, merged