feat(client): fallback image for portfolio page
freeCodeCamp/freeCodeCamp pull request #54262
Opened 2024-04-01 05:21 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #49146

2024-04-02 21:40 UTC, naomi-lgbt requested changes
A few concerns here, which are resolved in the suggestion below.

- `onError` needs to be passed a function, not a string.
- We have to access the event target, because we're in a "native" HTML element.
- Rather than using the SVG which has no background, let's just point to our OG image.

2024-04-02 21:40 UTC, naomi-lgbt commented on client/src/components/profile/components/portfolio-projects.tsx
> +              onError="this.src=require('https://d33wubrfki0l68.cloudfront.net/2f7693e1933ac514c960f51ceae72c91c6716eb2/b2efd/img/fcc_primary_small.svg')"
```suggestion
              onError={({ currentTarget }) => {
                currentTarget.src =
                  'https://cdn.freecodecamp.org/platform/universal/fcc_meta_1920X1080-indigo.png';
              }}
```

2024-04-02 23:56 UTC, naomi-lgbt approved these changes
Works as expected on my end! Thanks for fixing this 💜

2024-04-09 08:39 UTC, Sembauke approved these changes

2024-04-09 08:40 UTC, merged