Feat(UI): added specific label for MacOS check-code button
freeCodeCamp/freeCodeCamp pull request #54276
Opened 2024-04-02 10:24 UTC by Rabberpoli

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54270

As suggested, I added the following label: “Check Your Code (⌘+ Enter)".
This kind of label would be showed only on MacOS devices (detected by `navigator.userAgent` property); for other OS standard label will be showed

2024-04-02 11:12 UTC, Sembauke requested changes

2024-04-02 11:42 UTC, Rabberpoli commented on client/i18n/locales/english/translations.json
> +    "check-code-3": "Check Your Code (⌘ + Enter)",
Hi @Sembauke, I updated translations.json with the change you requested

2024-04-02 15:53 UTC, Rabberpoli commented on client/src/templates/Challenges/classic/lower-jaw.tsx
> +  const getBtnCheckCodeLabel = () =>
Hi @huyenltnguyen! You're right; I was trying to modify less as I could to preserve original codebase; right now I did a simple refactor that in my opinion makes this piece of code more readable and clean.

Let me know what you think about it

2024-04-04 17:30 UTC, huyenltnguyen approved these changes

2024-04-05 06:48 UTC, Sembauke approved these changes

2024-04-05 06:49 UTC, Sembauke commented
Thanks for making this possible @Rabberpoli, quick note: We should only Merge main into this branch if it is absolutely necessary.

2024-04-05 06:49 UTC, merged