feat(curriculum): add English curriculum block 8.1 sharing progress and accomplishments
freeCodeCamp/freeCodeCamp pull request #54319
Opened 2024-04-07 11:43 UTC by miyaliu666

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-04-08 16:00 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/6610056e633ce41466b6c5bc.md
> +# --description–
```suggestion
# --description--
```



This got malformed somehow

2024-04-26 13:17 UTC, moT01 reviewed
A couple inconsistencies in the titles

2024-05-01 17:40 UTC, moT01 approved these changes
I committed my suggestions and a fix to one of the answers.

I didn't go over this with a fine-toothed comb, but I looked over it pretty good. Mainly, I looked at the files - as far as I could tell, the backticks were in all the right places, the questions and fill in the blanks all had the correct answers, and I didn't see any grammar issues.

I would be fine getting this in. We still have to add the videos where we will have another chance to make improvements or catch issues. LGTM @miyaliu666 🎉

2024-05-21 17:15 UTC, nieldakarla requested changes
Excellent job, @miyaliu666 ! 


I've added a couple changes, specially replacing "practice time". I'll request changes but once these are implemented I'll approve the PR.

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/66125530a1a9e92e0e08d594.md
> +It is used by Maria to positively acknowledge the information shared.
```suggestion
It is used by Maria to positively acknowledge the information shared. This word is capitalized.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/661256fe823f142fb9858beb.md
> +Practice time!
```suggestion
Listen to the audio and answer the question.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/661269c4ccdd4132db7517b8.md
> +Practice time!
```suggestion
Listen to the audio and answer the question.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/66126a21821998335a86a34b.md
> +This task involves summarizing a professional performance review conversation. It's important to capture the essence of such discussions, which often include updates on recent work, feedback, goal se
```suggestion
Listen to the dialogue and fill in the blanks with the correct words.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/661271c2b16aff3870604148.md
> +This task assesses your understanding of the time frame mentioned by Brian in his conversation with Sarah.
```suggestion
When people say `it's been a while`, they mean a long time has passed between today and the last time something happened. 
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/6612757ffdc16b3a22b08427.md
> +Practice time!
```suggestion
Listen to the audio and complete the sentence.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/6612762a058bb43b960e91ca.md
> +Practice time!
```suggestion
Listen to the audio and answer the question.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/66127755a52efa3c9a73065b.md
> +Practice time.
```suggestion
Listen to the audio and complete the sentence.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/661278160653ee3d9040ed68.md
> +Practice time!
```suggestion
Listen to the audio and answer the question.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/6612797faf03663ef83f4459.md
> +It is used here as part of an expression of congratulations or approval for good work or progress.
```suggestion
It is used here as part of an expression of congratulations or approval for good work or progress. This word is capitalized.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/661279c8d3bf0f3f6f23f21f.md
> +This task involves summarizing a professional conversation between Brian and Sarah, focusing on their recent activities and achievements.
```suggestion
Listen to the dialogue and answer the question.
```

2024-05-21 17:15 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-share-progress-and-accomplishments/661279c8d3bf0f3f6f23f21f.md
> +Brian and Sarah discussed their recent work, including app testing, UX design workshop attendance, and client meetings, all leading to positive progress on their project.
```suggestion
They discussed their work, a UX design workshop, and client meetings.
```

2024-05-23 15:01 UTC, nieldakarla approved these changes

2024-05-23 15:01 UTC, merged