feat(curriculum): add English curriculum block 8.2 updates and plans on tasks or projects
freeCodeCamp/freeCodeCamp pull request #54332
Opened 2024-04-09 05:36 UTC by miyaliu666

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-04-09 17:39 UTC, naomi-lgbt requested changes

2024-04-09 17:39 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-updates-and-plans-for-tasks-and-projects/6613d00727a7a64a5e010243.md
> +Practice time!
Do we not want to use our standard "Fill in the blanks in the dialogue below"?

2024-04-09 17:39 UTC, naomi-lgbt commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-updates-and-plans-for-tasks-and-projects/6613d0773359964ab8812659.md
> +Practice time.
And for these, "Answer the question below"?

2024-05-01 18:15 UTC, moT01 reviewed
I hope you don't mind @miyaliu666, I pushed some minor fixes. Take a look at the diff to see what I changed, or let me know if you want me to show you.

This looks good. The only concern I had is that the first two task descriptions are the "Practice time" style. Do we want to start with two tasks that don't explain anything and just throw users into it? I'm fine with it, just mentioning it.

2024-05-07 02:50 UTC, miyaliu666 commented
@naomi-lgbt I used "Fill in the blanks in the dialogue below" and "Please answer the question below" in Part 9 and 5 after I saw your comments here.

I'll add explanations for words in the first two tasks as @moT01 pointed out. Those words have been taught in previous blocks, but we can review them here because people may not learn the blocks in strict order.

2024-05-07 13:37 UTC, moT01 approved these changes
LGTM 🎉

2024-05-07 18:52 UTC, naomi-lgbt approved these changes

2024-05-07 18:52 UTC, merged