prevented spam filter step 10 from passing with incorrect values
freeCodeCamp/freeCodeCamp pull request #54364
Opened 2024-04-11 22:22 UTC by jenna5376

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #54337

Added checks to prevent step 10 of building a spam filter from passing if left-hand or right-hand side of `|` is empty

<img width="1440" alt="Screen Shot 2024-04-11 at 5 07 25 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/62906996/6147e8c5-92ca-403a-b70e-ddbe8577b0c2">

2024-04-12 05:51 UTC, Sembauke commented
<img width="633" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/46919888/95272378-dd7e-4055-aa41-a8324a305209">
I am still able to pass it this way

2024-04-15 09:18 UTC, Ksound22 commented
> I am still able to pass it this way <img alt="image" width="633" src="https://private-user-images.githubusercontent.com/46919888/321868731-95272378-dd7e-4055-aa41-a8324a305209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzI2MzEsIm5iZiI6MTcxMzE3MjMzMSwicGF0aCI6Ii80NjkxOTg4OC8zMjE4Njg3MzEtOTUyNzIzNzgtZGQ3ZS00MDU1LWFhNDEtYTgzMjRhMzA1MjA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA5MTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Yzg4OTM0ZjE5MjQ5YWI5ZjA2ZWJlOTBjZjdkNTZlNjQ5NDNlYzY4MzQ5M2NmZTQzMmIzZGJlZjBmM2U0ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.adnzhC64RmuGRlObOK6sgmZpkd4gIb3xg-YNnGMI8R4">

That didn't pass on my end
<img width="1399" alt="Screenshot 2024-04-15 at 10 16 55" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/65571316/85e0e61f-6a04-4186-a6cc-4b26c947e30e">

2024-04-15 09:27 UTC, Sembauke commented
> That didn't pass on my end

Yup @jenna5376 fixed it in the latest commit :)

2024-04-15 09:27 UTC, Sembauke approved these changes

2024-04-15 11:42 UTC, Ksound22 commented
@Sembauke what do we do about [#54378](https://github.com/freeCodeCamp/freeCodeCamp/pull/54378)?

2024-04-15 16:48 UTC, naomi-lgbt requested changes
Let's use the more specific assert method.

2024-04-15 16:48 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-regular-expressions-by-building-a-spam-filter/641cf198ec366c33d6504854.md
> +assert.isTrue(splitRegex.indexOf('please help') != -1);
```suggestion
assert.include(splitRegex, 'please help');
```

2024-04-15 16:48 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-regular-expressions-by-building-a-spam-filter/641cf198ec366c33d6504854.md
> +assert.isTrue(splitRegex.indexOf('assist me') != -1);
```suggestion
assert.include(splitRegex, 'assist me');
```

2024-04-15 17:04 UTC, naomi-lgbt approved these changes

2024-04-15 17:32 UTC, merged