fix: updated donation progress with heading
freeCodeCamp/freeCodeCamp pull request #54377
Opened 2024-04-12 14:57 UTC by JeevaRamanathan

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54156 

Updated Block Progress Bar with heading
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/64531160/e156ebf3-501a-4c46-bb34-1dbd8946e6c4)

2024-04-14 06:30 UTC, bbsmooth commented on client/src/components/Intro/learn-alert.tsx
> +            <h3>{`${value}%`}</h3>
```suggestion
            <p>{`${value}%`}</p>
```
This isn't acting as a heading.

2024-04-15 20:42 UTC, lasjorg commented
I haven't checked, but are we sure `.progress-bar-percent` isn't used elsewhere?

I'm not saying the linear-gradient with the animation is working well if it is used elsewhere, but changing it for all instances might not be the correct thing to do here.

Maybe we should make a new class or a modifier class (so it can exist with and without the gradient).

2024-04-17 10:57 UTC, JeevaRamanathan commented
Oops! Somehow I have missed that, animation has been removed now.
<hr/>

Ok, let's see if we hear any feedback from maintainers

2024-04-17 22:53 UTC, lasjorg commented
BTW, how does it look with the paragraph element?

I didn't check, but I would assume the element needs some styles to be larger and have more weight?

2024-04-19 17:57 UTC, jeem5110 commented
Updated view with `p` element
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/108048438/3dd36f8e-6b86-49d6-b0c9-7d8ade431d29)

2024-04-25 20:29 UTC, naomi-lgbt requested changes
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/a7840de7-33b5-4780-b383-e3ee89700c73)

The new text will need a specific colour set so it does not become illegible in night mode.

2024-04-25 21:47 UTC, jeem5110 commented
@naomi-lgbt, it has been updated with a specific color, and I hope the translation text, which is showing as "learn.donation-heading," will map with its corresponding value once it's live.

2024-04-25 21:53 UTC, JeevaRamanathan commented
@naomi-lgbt, it has been updated with a specific color, and I hope the translation text, which is showing as "learn.donation-heading," will map with its corresponding value once it's live.

2024-04-25 22:26 UTC, naomi-lgbt commented
> which is showing as "learn.donation-heading," will map with its corresponding value once it's live.

Yeah, that only shows because I was too lazy to clean the local files when I was switching branches.

2024-04-25 22:35 UTC, naomi-lgbt approved these changes

2024-04-26 00:49 UTC, moT01 approved these changes
LGTM 🎉 

Hey @ahmaxed, do you mind taking a look at this redesign before we merge?

2024-04-27 18:06 UTC, ahmaxed commented
This is the final state. Removed the hr as requested. Adding an animation would be nice. 

<img width="868" alt="Screenshot 2024-04-27 at 9 03 44 PM" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/4591597/606934ce-879a-431c-9497-fd04523ab20b">

2024-05-03 13:23 UTC, merged