feat(curriculum): add animations to block 4.2 of the English Curriculum
freeCodeCamp/freeCodeCamp pull request #54415
Opened 2024-04-16 23:17 UTC by DanielRosa74

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

2024-04-25 23:35 UTC, naomi-lgbt requested changes
Looks like the tests need to be updated to accept the new scenes.

2024-05-17 11:50 UTC, moT01 reviewed
This is looking good @DanielRosa74. The playback seems pretty consistent. I am still getting quite a few steps where the audio gets cut off a little early. Here's a list of the task numbers:

15-19,  23-24, 26, 30, 36-37, 39-43, 46-47, 50-53, 58, 68-70, 72-75, 94, 104-105

I used Chrome for testing. Do you want to take a quick look at some of those and see if you are seeing the same thing? And maybe make some adjustments. They could be off a little from adjustments you made because of the inconsistencies that were present from before.

2024-05-17 11:50 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-discuss-popular-trends-in-technology/661eb97a2eb89a1ecd9a507a.md
> +`It's _ secure, but like any technology, it has its challenges and privacy concerns.`
```suggestion
`Alice: It's _ secure, but like any technology, it has its challenges and privacy concerns.`
```

2024-05-17 20:31 UTC, DanielRosa74 commented
> This is looking good @DanielRosa74. The playback seems pretty consistent. I am still getting quite a few steps where the audio gets cut off a little early. Here's a list of the task numbers:
> 
> 15-19,  23-24, 26, 30, 36-37, 39-43, 46-47, 50-53, 58, 68-70, 72-75, 94, 104-105
> 
> I used Chrome for testing. Do you want to take a quick look at some of those and see if you are seeing the same thing? And maybe make some adjustments. They could be off a little from adjustments you made because of the inconsistencies that were present from before.

Changes made. The sentences were cutting off in those places indicated. This should fix them.

2024-05-17 22:48 UTC, DanielRosa74 commented
> Looks like the tests need to be updated to accept the new scenes.

Solved.

2024-05-20 15:48 UTC, moT01 approved these changes
LGTM 🎉

2024-05-20 22:05 UTC, naomi-lgbt approved these changes

2024-05-20 22:06 UTC, merged