Updated step74 of spreadsheet project and added step 75 and step 76
freeCodeCamp/freeCodeCamp pull request #54417
Opened 2024-04-17 04:17 UTC by sanskriti2005

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54327

2024-04-17 21:04 UTC, naomi-lgbt requested changes

2024-04-17 21:04 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/646d404259f512c1a9e86ac1.md
> +assert.match(code, /return\s+regex\.test\(str\);/);
```suggestion
assert.match(code, /return\s+regex\.test\(str\);?/);
```

Optional semi.

2024-04-17 21:04 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
> +You should use `console.log()` to return the `highPrecedence` function with the string `"5*3"`.
```suggestion
You should use `console.log()` to print the result of calling the `highPrecedence` function with the string `"5*3"`.
```

`console.log()` returns `void`.

2024-04-17 21:04 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
> +```
We should make this more granular.

- Test for a function call of `highPrecedence`
- Test that `5*3` is passed as the argument
- Test that the result is logged.

2024-04-17 21:04 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f49650572031c6ebdb8e3.md
> +Remove line code line `return regex.test(str);` and line `console.log(highPrecedence("5*3"))` as they were only for testing purposes.
```suggestion
Remove both the `console.log()` with your `highPrecedence` call, and the `return` statement from your `highPrecedence` function.
```

2024-04-17 21:04 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f49650572031c6ebdb8e3.md
> +Remove the line `console.log(highPrecedence("5*3"))`.
```suggestion
Your code should not log the result of `highPrecedence("5*3")`.
```

2024-04-17 21:04 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f49650572031c6ebdb8e3.md
> +```
````suggestion
Your `highPrecedence` function should not return a value.

```js
assert.isUndefined(highPrecedence("5*3"));
```
````

2024-04-17 21:04 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f49650572031c6ebdb8e3.md
> +```
````suggestion
```js
assert.notMatch(code, /console\.log\(highPrecedence\("5\*3"\)\)/);
```
````

2024-04-22 17:59 UTC, naomi-lgbt requested changes

2024-04-22 17:59 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
> +Print or log the results using `console.log()`.
```suggestion
You should call `console.log()`.
```

2024-04-22 17:59 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
> +Make a test call for the `highPrecedence` function.
````suggestion
You should call your `highPrecedence` function.

```js
assert.match(code, /highPrecedence\(.*\)/);
```

You should pass your `highPrecedence` call to your `console.log()` call.
````

2024-04-24 17:24 UTC, naomi-lgbt approved these changes

2024-04-27 11:18 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
The sei-colons here should be optional

2024-04-27 11:21 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
Also it's possible for the regex tests to not be this complicated

2024-04-27 11:22 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
> +assert.match(code, /console\.log\(.*\);/);
This works fine: 
```suggestion
assert.match(code, /console\.log\(/);
```

2024-04-27 11:25 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
> +
This works fine too:
```suggestion
assert.match(code, /console\.log\(highPrecedence\(/);
```

2024-04-27 11:27 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/661f48f412d7631a1d9c30e6.md
> +
And this works fine:
```suggestion
assert.match(code, /console\.log\(highPrecedence\(["']5\*3["']\)\);?/);
```

We should allow single quotes, and make the semi-colon optional.

2024-04-28 06:15 UTC, sanskriti2005 commented
@Ksound22 thank you for the review :)  

I will make the changes.

2024-05-01 20:32 UTC, Ksound22 reviewed
LGTM 👍🏾

2024-05-01 20:39 UTC, Ksound22 approved these changes

2024-05-02 06:34 UTC, merged