refactor(curriculum): update RPG project to accommodate new intro pyramid project
freeCodeCamp/freeCodeCamp pull request #54435
Opened 2024-04-18 03:52 UTC by jdwilkin4

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-04-18 10:07 UTC, Sembauke requested changes

2024-04-18 10:07 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa264d23cdaa45a20efada.md
> +After your `numbers` array, create a `while` loop. Your `while` loop should run while `numbers.length` is less than `10`.
```suggestion
After your `numbers` array, create a `while` loop that runs as long as `numbers.length` is less than `10`.
```

2024-04-18 10:07 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa27c40ca6f04ab8be5fac.md
> +`for` loops are declared with three expressions separated by semicolons. `for (a; b; c)`, where `a` is the initialization expression, `b` is the condition, and `c` is the final expression.
```suggestion
`for` loops are declared with three expressions separated by semicolons: `for (a; b; c)`, where `a` is the initialization expression, `b` is the condition, and `c` is the final expression.
```

2024-04-18 10:07 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa27c40ca6f04ab8be5fac.md
> +In this step, create a `for` loop where `i` is initialized to `0`, the loop runs while `i` is less than `10`, and `i` is incremented by `1` after each loop. Remember to use the increment operator `++
```suggestion
In this step, create a `for` loop where `i` is initialized to `0`, the loop runs as long as `i` is less than `10`, and `i` is incremented by `1` after each iteration using the increment operator `++`.
```

2024-04-18 16:44 UTC, Sembauke approved these changes

2024-04-22 17:10 UTC, naomi-lgbt approved these changes

2024-04-22 17:10 UTC, merged