fix(learn) : update the quiz cert footer
freeCodeCamp/freeCodeCamp pull request #54442
Opened 2024-04-18 14:34 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #54282

The wording for the description of the certification has been updated and the footer is now conditionally not present for the C# exam certification.

2024-04-18 19:10 UTC, naomi-lgbt requested changes
Not sure what a handing is, but probably not something either of us want.

2024-04-18 19:10 UTC, naomi-lgbt commented on client/src/client-only-routes/show-project-links.tsx
> +  const getCertHanding = (certName: string) => {
```suggestion
  const getCertHeading = (certName: string) => {
```

2024-04-18 19:10 UTC, naomi-lgbt commented on client/src/client-only-routes/show-project-links.tsx
> +      {t(getCertHanding(certName), { user: name })}
```suggestion
      {t(getCertHeading(certName), { user: name })}
```

2024-04-18 19:16 UTC, a2937 commented
Typo has been fixed.

2024-04-19 11:26 UTC, Sembauke commented
Hey @a2937,

Thank you for making this pr. Some of the test are failing could you take a look?

If you need any help with resolving the test errors let me know!

2024-04-22 18:59 UTC, a2937 commented
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/9373245/f21cfbd8-33db-4d91-90b4-939169b82237)

I don't understand why the tests are failing on GitHub. While I did modify my local development user account to gain this certificate (plus did a quick change back and forth on the tests) nothing seemed broken. The only reason why the tests failed locally were because the issuing dates were different the seed data results.

2024-04-22 20:29 UTC, naomi-lgbt requested changes
I had weirdness with `toBeNull()`.

2024-04-22 20:29 UTC, naomi-lgbt commented on e2e/certification.spec.ts
> +    expect(
```suggestion
    await expect(
```

2024-04-22 20:29 UTC, naomi-lgbt commented on e2e/certification.spec.ts
> +    ).toBeNull();
```suggestion
    ).toHaveCount(0);
```

2024-04-25 18:30 UTC, naomi-lgbt approved these changes

2024-04-25 21:36 UTC, jdwilkin4 approved these changes

2024-04-25 21:37 UTC, merged