fix(curriculum):Updated lessons in Number sorter project to better show how ``inputValues`` works
freeCodeCamp/freeCodeCamp pull request #54445
Opened 2024-04-19 10:15 UTC by sanskriti2005

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54434

2024-04-22 17:55 UTC, naomi-lgbt requested changes

2024-04-22 17:55 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-algorithmic-thinking-by-building-a-number-sorter/662236690376072dc79d9c27.md
> +Remove the `console.log()` calling on the `inputValues`.
```suggestion
Now that you have confirmed the data type of the `inputValues` elements, remove your `console.log()` call.
```

2024-04-23 08:40 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-algorithmic-thinking-by-building-a-number-sorter/6407b940b8983005578d0824.md
> +You need to get the values from your `select` elements. These values will currenly be strings and you will convert them into numbers.
```suggestion
You need to get the values from your `select` elements. These values will currently be strings and you will convert them into numbers.
```

2024-04-23 08:48 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-algorithmic-thinking-by-building-a-number-sorter/6621c5f02a5c272761db8661.md
> +assert.match(code, /console\.log\(.*\);/);
The semi-colon here should be optional. If a camper fails to use the semi-colon, the test will not pass, so the next hint and test won't be reached.
 
```suggestion
assert.match(code, /console\.log\(.*\);?/);
```

2024-04-23 08:50 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-algorithmic-thinking-by-building-a-number-sorter/6621c5f02a5c272761db8661.md
> +assert.match(code, /console\.log\(\s*inputValues\s*\);/);
```suggestion
assert.match(code, /console\.log\(\s*inputValues\s*\);?/);
```

2024-04-23 09:14 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-algorithmic-thinking-by-building-a-number-sorter/6621c5f02a5c272761db8661.md
> +In the next step, you will convert those strings into numbers.
```suggestion
Before going further, make sure you observe the data type of the printed result in the console.

In the next step, you will convert those strings into numbers.
```

2024-04-23 09:17 UTC, Ksound22 reviewed
I left some comments. Other than those, I think things look good.

I will approve when you implement the changes.

2024-04-23 13:48 UTC, sanskriti2005 commented
@Ksound22 Thank you for the review! I will make the changes

2024-04-23 21:53 UTC, naomi-lgbt requested changes

2024-04-23 21:53 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-algorithmic-thinking-by-building-a-number-sorter/6621c5f02a5c272761db8661.md
> +Before going further, make sure you observe the data type of the printed result in the console.
````suggestion
To see the result for the `inputValues` array, log out the `inputValues` array to the console. Then click on the sort button and open up the console. You should see an array of strings like this:

```js
[ '8', '2', '4', '1', '3' ]
```

Before going further, make sure you observe the data type of the printed result in the console.
````

Let's not repeat ourselves, though.

2024-04-24 15:27 UTC, naomi-lgbt approved these changes
Thanks for all of your work on this.

2024-04-24 20:12 UTC, jdwilkin4 approved these changes

2024-04-24 20:12 UTC, merged