test: remove api mocks from e2e tests
freeCodeCamp/freeCodeCamp pull request #54482
Opened 2024-04-22 11:16 UTC by ojeytonwilliams

- **test: use seed to recreate account after deletion**
- **test: seed the ms username to avoid mocking**
- **test: delete notes.spec - it's not used**
- **test: remove unnecessary mock**
- **test: remove another unnecessary mock**
- **test: remove user's acceptance of privacy**
- **chore: allow all seeded users to be modified**

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Rather than mocking the server's response, this modifies the db so that the api responds correctly.

This makes the e2e tests actually e2e tests as well as making them more useful for the api migration. i.e. if the migration breaks one of the routes and that route was mocked we wouldn't know.

2024-04-24 15:24 UTC, naomi-lgbt requested changes
If we have to use a regex here, we should probably escape the wildcards just to be safe.

2024-04-24 15:24 UTC, naomi-lgbt commented on e2e/link-ms-user.spec.ts
> +      /The Microsoft account with username "certifieduser" is currently linked to your freeCodeCamp account. If this is not your Microsoft username, remove the link./
```suggestion
      /The Microsoft account with username "certifieduser" is currently linked to your freeCodeCamp account\. If this is not your Microsoft username, remove the link\./
```

2024-04-24 15:39 UTC, ojeytonwilliams commented
This will fail until https://github.com/freeCodeCamp/freeCodeCamp/pull/54518 is merged, so I've blocked it for now.

2024-04-24 15:47 UTC, naomi-lgbt approved these changes

2024-05-03 09:12 UTC, huyenltnguyen approved these changes

2024-05-03 09:12 UTC, merged