feat(curriculum): add English curriculum block 9.2 requesting and receiving guidance from others
freeCodeCamp/freeCodeCamp pull request #54480
Opened 2024-04-22 08:43 UTC by miyaliu666

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-04-22 09:11 UTC, miyaliu666 commented
I don't see why task-46 doesn't show "description" when running locally.

2024-04-25 20:16 UTC, naomi-lgbt requested changes
One tiny nit

2024-05-16 16:55 UTC, moT01 requested changes
Looks good @miyaliu666 🎉 

Found a few things...

2024-05-16 16:55 UTC, moT01 commented on curriculum/challenges/_meta/learn-how-to-request-and-receive-guidance/meta.json
> +      "title": "Dialogue 1:Solving Coding Challenges"
```suggestion
      "title": "Dialogue 1: Solving Coding Challenges"
```

2024-05-16 16:55 UTC, moT01 commented on curriculum/challenges/_meta/learn-how-to-request-and-receive-guidance/meta.json
> +      "title": "Dialogue 2: Learning A New Technology"
```suggestion
      "title": "Dialogue 2: Learning a New Technology"
```

2024-05-16 16:55 UTC, moT01 commented on curriculum/challenges/_meta/learn-how-to-request-and-receive-guidance/meta.json
> +      "title": "Dialogue 3: Offering Assistance And Receiving Guidance"
```suggestion
      "title": "Dialogue 3: Offering Assistance and Receiving Guidance"
```

2024-05-16 16:55 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-request-and-receive-guidance/66250fc0d711192eebfff0e9.md
> +dashedName: dialogue-2-solving-coding-challenges
```suggestion
dashedName: dialogue-1-solving-coding-challenges
```

2024-05-16 16:55 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-request-and-receive-guidance/6625ceb55c430866094b40b9.md
> +title: "Dialogue 2: Learning A New Technology"
```suggestion
title: "Dialogue 2: Learning a New Technology"
```

2024-05-16 16:55 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-request-and-receive-guidance/6625ddee54d1db9090a4800f.md
> +title: "Dialogue 3: Offering Assistance And Receiving Guidance"
```suggestion
title: "Dialogue 3: Offering Assistance and Receiving Guidance"
```

2024-05-16 16:55 UTC, moT01 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-request-and-receive-guidance/6625d84e92201f802eac3973.md
> +# --description–-
```suggestion
# --description--
```

One of the dashes wasn't a regular dash or something - so the description wasn't showing up.

2024-05-17 11:04 UTC, moT01 approved these changes

2024-05-21 20:00 UTC, nieldakarla requested changes
This block looks great. Just made 2 adjustments to some descriptions.

2024-05-23 15:03 UTC, nieldakarla approved these changes

2024-05-25 19:58 UTC, naomi-lgbt approved these changes
Sorry for blocking this one too. 😔

2024-05-25 19:58 UTC, merged