feat: add note about the status of the english certification
freeCodeCamp/freeCodeCamp pull request #54500
Opened 2024-04-23 09:48 UTC by scissorsneedfoodtoo

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR adds a note about the current status of the English curriculum, and lets learners know that a claimable certification will be available sometime in the future.

2024-04-23 18:13 UTC, naomi-lgbt requested changes

2024-04-23 18:13 UTC, naomi-lgbt commented on client/i18n/locales/english/intro.json
> +    "note": "Note: This certification is currently in active development. While there isn't a claimable certification available for this section at the moment, one will be available soon. In the mean
```suggestion
    "note": "This certification is currently in active development. While there isn't a claimable certification available for this section at the moment, one will be available soon. In the meantime, you're welcome to explore the courses we have created below.",
```

2024-04-25 19:02 UTC, naomi-lgbt approved these changes

2024-04-25 23:48 UTC, jdwilkin4 approved these changes

2024-04-25 23:48 UTC, merged