fix(client): clarify what progress reset includes
freeCodeCamp/freeCodeCamp pull request #54542
Opened 2024-04-26 08:44 UTC by huyenltnguyen

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR updates the text in the progress reset modal to clarify what the action does.

Note: I'm not adding the big "WARNING!" text to the modal because it would bring inconsistency (the delete account modal doesn't have this text). We changed the reset modal to have its content displayed in `danger` color during the Modal migration, and I think this should suffice (we do communicate the critical level of the action through text, and not just text color, so this isn't an a11y concern).

Closes #53959

## Screenshots

| Before | After |
| --- | --- |
| <img width="942" alt="Screenshot 2024-04-26 at 15 43 12" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/5bd092a2-2dba-49f3-a037-afef78d5c8c3"> | <img width="969" alt="Screenshot 2024-04-26 at 15 27 34" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/25715018/e7c5c138-e493-4a5f-b2d0-3cc7a30cf71c"> |

2024-04-26 15:32 UTC, naomi-lgbt approved these changes

2024-04-29 05:44 UTC, Sembauke requested changes

2024-04-29 05:44 UTC, Sembauke commented on client/i18n/locales/english/translations.json
> +      "reset-item-1": "Your progress through each step/challenge (all completed challenge will be lost)",
```suggestion
      "reset-item-1": "Your progress through each step/challenge (all completed challenges will be lost)",
```

2024-04-29 05:57 UTC, Sembauke approved these changes

2024-04-29 06:09 UTC, merged