feat: convert progressbar test to Playwright
freeCodeCamp/freeCodeCamp pull request #54636
Opened 2024-05-03 09:13 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-03 20:12 UTC, naomi-lgbt requested changes
More logical test name?

2024-05-03 20:12 UTC, naomi-lgbt commented on e2e/progress-bar.spec.ts
> +  test('Declare JavaScript Variables Test', async ({ page }) => {
```suggestion
  test('should appear in the completion modal after user has submitted their code', async ({ page }) => {
```

2024-05-06 18:26 UTC, naomi-lgbt approved these changes

2024-05-07 15:58 UTC, huyenltnguyen approved these changes

2024-05-07 15:59 UTC, merged