fix(curriculum): prevent passing in case of <img> element not closed
freeCodeCamp/freeCodeCamp pull request #54644
Opened 2024-05-03 15:32 UTC by zxc-w

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54642

2024-05-03 19:57 UTC, zxc-w commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc24073f86c76b9248c6ebb.md
> +assert(/<img\s+src\s*=\s*"https:\/\/cdn\.freecodecamp\.org\/curriculum\/cat-photo-app\/relaxing-cat\.jpg"\s*(?:\/?>)/.test(code));
I thought of that too when I was trying to check it for the first time, you are correct.

2024-05-06 04:39 UTC, huyenltnguyen approved these changes

2024-05-06 09:15 UTC, Dario-DC approved these changes
LGTM :+1:

2024-05-06 09:21 UTC, Dario-DC requested changes
I've just realized that it doesn't take into account single quotes. Should we allow them? @huyenltnguyen

2024-05-06 15:41 UTC, zxc-w commented
@huyenltnguyen sure, I was just waiting to see if I should update it or not.

2024-05-06 16:25 UTC, Dario-DC approved these changes

2024-05-06 16:25 UTC, merged