feat: convert projects to Playwright
freeCodeCamp/freeCodeCamp pull request #54689
Opened 2024-05-07 13:18 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-10 19:51 UTC, Sembauke commented
> The tests are still failing because there is a stray } in the editor, causing the code to be invalid and blocking the submission. The solution code in the JSON file looks correct to me, so I'm still (pulling my hair) trying to figure out where that character comes from (both editor.evaluate() and editor.fill() gave the same result).

You deleted the parameter which disables bracket and quote completion in the editor.

<img width="916" alt="image" src="https://github.com/freeCodeCamp/freeCodeCamp/assets/46919888/0306b540-f58e-4879-81b0-b40b3d20fa2f">

This function has been added as even when filling or pasting code the editor completes brackets:

```
    // disable bracket completion when testing as it duplicates brackets when filling text
    const disableBracketCompletion =
      window.location.href.includes('testing=true');

    console.log(window.location.href, disableBracketCompletion);

    if (disableBracketCompletion) {
      editor?.updateOptions({
        autoClosingBrackets: 'never',
        autoClosingQuotes: 'never'
      });
    }
```

I should have left a comment about it.

2024-05-13 10:19 UTC, ojeytonwilliams commented
@huyenltnguyen yep, it's the cookies. The issue is that the cookies for `certifieduser` are used even after the db is seeded with `developmentuser`. The fix/workaround is to create storageStates for both so that you can switch between users.

I'll create a quick PR for that, so you can use it here.

2024-05-13 10:56 UTC, ojeytonwilliams commented
https://github.com/freeCodeCamp/freeCodeCamp/pull/54752 should help.

Once it's in, switching users means both changing storage state and seeding the desired user.

2024-05-14 07:59 UTC, ojeytonwilliams commented
> I think the second test.use runs before the tests and overrides the first test.use, which is why the conflict happened

Pretty much. It's not exactly a conflict, it's just that multiple `test.use` calls override each other. As far as I understand it, `test.use` simply set the Playwright config for that scope (the entire file or a single describe block), so making two calls in the same scope is equivalent to just making the second call.

2024-05-15 08:07 UTC, ojeytonwilliams requested changes

2024-05-15 08:07 UTC, ojeytonwilliams commented on e2e/projects.spec.ts
> +
```suggestion
  test.skip(
    ({ browserName }) => browserName !== 'chromium',
    'Only chromium allows us to use the clipboard API.'
  );

```
So we can paste below.

2024-05-15 08:07 UTC, ojeytonwilliams commented on e2e/projects.spec.ts
> +      '/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/palindrome-checker?testing=true'
```suggestion
      '/learn/javascript-algorithms-and-data-structures/javascript-algorithms-and-data-structures-projects/palindrome-checker'
```
It won't be necessary if we use the clipboard.

2024-05-15 08:07 UTC, ojeytonwilliams commented on e2e/projects.spec.ts
> +    }, contents);
```suggestion
    await page.evaluate(
      async contents => await navigator.clipboard.writeText(contents),
      contents
    );
    // Only runs on Chromium, so Control will work.
    await page.keyboard.press('Control+v');
```

2024-05-16 15:32 UTC, huyenltnguyen approved these changes
Hookay, I think the PR is good to go.

This is one heck of a test suite to write / rewrite 😰

2024-05-21 08:29 UTC, ojeytonwilliams commented on e2e/utils/request.ts
> +
```suggestion
```
We can just look in the network tab if there's an error.

2024-05-21 08:30 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/editor.tsx
> +
```suggestion
```

2024-05-21 15:37 UTC, ojeytonwilliams approved these changes
This was a struggle. Nice work, @Sembauke and @huyenltnguyen!

LGTM :+1:

2024-05-21 15:37 UTC, merged