fixed-wording-for-step-5-of-pyramid-project
freeCodeCamp/freeCodeCamp pull request #54735
Opened 2024-05-10 19:34 UTC by adityarajshekhawat

Checklist:

-  [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54608

Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-introductory-javascript-by-building-a-pyramid-generator/step-5

2024-05-10 19:54 UTC, jdwilkin4 reviewed
It looks like you have changed the wrong file.
You should only update the english files.
Please re read through the issue to get the correct file you are supposed to change.

2024-05-11 09:38 UTC, adityarajshekhawat commented
> It looks like you have changed the wrong file. You should only update the english files. Please re read through the issue to get the correct file you are supposed to change.

okay i will do that

2024-05-11 15:05 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef31a5be625914a0102cd.md
> +
```suggestion
```
Keep the empty lines consistent please

2024-05-11 15:06 UTC, ilenia-magoni requested changes

2024-05-11 15:06 UTC, ilenia-magoni commented on curriculum/challenges/arabic/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef31a5be625914a0102cd.md
> -
Please restore the arabic file to the original condition

2024-05-13 06:12 UTC, Ksound22 commented
We don't make changes to translation files. That's why one of the CIs is failing

2024-05-13 09:10 UTC, closed without merging

2025-02-22 11:53 UTC, tekluabayneh commented on curriculum/challenges/arabic/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660ef31a5be625914a0102cd.md
> -
Hi Ilenia-Magoni,

I noticed your contributions to the FreeCodeCamp repo and I'm really impressed with your work! I'm interested in contributing as well but I'm new to the process. Could you share some tips or advice on how I can get started and make meaningful contributions to the project?

I've tried navigating the codebase, but I found it challenging to locate the specific issue folders. Any guidance would be greatly appreciated.

Thank you for your time and help!

Best regards,
Teklu