chore(curriculum): remove pyodide from shortest path algorithm project
freeCodeCamp/freeCodeCamp pull request #54756
Opened 2024-05-13 11:54 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

https://github.com/freeCodeCamp/freeCodeCamp/blob/08f63a0b974c5ca17aa2b27b3ce5151fd0b2eea6/tools/client-plugins/browser-scripts/python-test-evaluator.ts#L122-L123

2024-05-14 20:19 UTC, naomi-lgbt approved these changes
No pyodide found in this block

2024-05-15 10:35 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6578b13757611e2825beb8a5.md
> +    copper = __locals.get("copper")
```suggestion
```

2024-05-15 10:36 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6578b13757611e2825beb8a5.md
>  ({ test: () => assert(__pyodide.runPython(`
```suggestion
({ test: () => assert(runPython(`
```

2024-05-15 10:36 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6578b13757611e2825beb8a5.md
> +    copper = __locals.get("copper")
```suggestion
({ test: () => assert(runPython(`
```

2024-05-15 10:38 UTC, Dario-DC requested changes
Something went wrong when fixing the conflicts

2024-05-15 13:09 UTC, Dario-DC approved these changes

2024-05-15 13:09 UTC, merged