chore(curriculum): add tests for globals in cash register
freeCodeCamp/freeCodeCamp pull request #54769
Opened 2024-05-13 17:52 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #53836

This one adds two tests for the cash register. One for `cid` and another for `price`.

2024-05-13 18:07 UTC, gikf commented
Couldn't it be checked if `cid` and `price` are declared and can be reassigned instead - basically to try reassign them? The importance of their value before running tests is marginal, and campers often change these when manually testing.

2024-05-13 19:32 UTC, a2937 commented
I'm a little confused. Can you explain what you mean by check for reassignment? I know how to check if a variable is defined. That's easy enough. But I'm not entirely sure what I should be looking for. Also I think I found out that if you modify a variable in one test; the new value stays into the next one.

2024-05-13 19:50 UTC, gikf commented
For example, for `price`:
```javascript
price = 10;
assert.strictEqual(price, 10);
```
If `price` is not declared, or declared with `const`, this will not pass.

2024-05-14 04:22 UTC, gikf commented
Ouch, sorry, that's likely caused by user code being transformed, so `const` ends up transformed to `var`.

But `price` is then correctly being changed in further tests, isn't it?

2024-05-14 09:06 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md
> +You have a variable called `cid`.
```suggestion
You should have a variable called `cid`. 
```

2024-05-14 09:07 UTC, ilenia-magoni commented
> But `price` is then correctly being changed in further tests, isn't it?

I have seen it not pass with
```js
const price = ...
const cid = ...
```

but I don't know if it was only that or something else

2024-05-14 18:13 UTC, a2937 commented
> > But `price` is then correctly being changed in further tests, isn't it?
> 
> I have seen it not pass with
> 
> ```js
> const price = ...
> const cid = ...
> ```
> 
> but I don't know if it was only that or something else

The variables do get modified in at least a few tests.

https://github.com/freeCodeCamp/freeCodeCamp/blob/4b27d6597817fccc84433e02a53de4820956cc21/curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md#L123-L134

2024-05-14 18:27 UTC, a2937 commented
> Ouch, sorry, that's likely caused by user code being transformed, so `const` ends up transformed to `var`.
> 
> But `price` is then correctly being changed in further tests, isn't it?

Yes. It is being modified in further tests. The solution still works even if `cid` and `price` are set as `const`.

2024-05-14 18:40 UTC, ilenia-magoni commented
> > I have seen it not pass with
> > ```js
> > const price = ...
> > const cid = ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but I don't know if it was only that or something else
> 
> The variables do get modified in at least a few tests.

Yeah, so I am confused on why I have seen it not pass, but your test doesn't work as it should

2024-05-22 22:27 UTC, a2937 commented
I don't know what to do here exactly. But it's essential that the `price` variable is modifiable for the other tests to pass. By some miracle the other tests aren't breaking. I don't think there's a single way to test the way we are with different cash drawer inputs and different prices; and have the two variables be unchanging. For now, whether it be bug or feature; it passes. My money is perhaps cached content. 

If that's the case, then we have the other tests to worry about.

2024-05-23 10:01 UTC, ilenia-magoni commented
more than cached content I would guess it's the code being converted to `var`

2024-06-05 19:34 UTC, gikf commented
I've checked with `var`, `let`, `const`, no issues with passing with otherwise good solution.

There's one case when tests (but all of them, not just new ones) confused the heck of me. I was starting with the seed code and I couldn't get the tests for global to pass `cid` and `price` are in the editor, but test are failing and console shows `RefferenceError`. The reason turned out simple - no html file with script linking the JS. This is kind of implied, but maybe it should be explicit.

2024-06-12 19:50 UTC, a2937 commented
Okay I have added a check to make sure that the html file is linking to script.js.

2024-06-13 10:20 UTC, ilenia-magoni commented
the PR was a bit too behind, so I took the liberty to make a merge

2024-06-13 10:27 UTC, ilenia-magoni requested changes
The tests are good, I left a comment for the wording of the hints. After that, it's good to go.

2024-06-13 10:27 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md
> +You should have the html file link to the Javascript
```suggestion
You should have the HTML file link to the JavaScript file.
```

2024-06-13 10:27 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md
> +You should have a variable called `price`.
```suggestion
You should have a global variable called `price`. 
```

2024-06-13 10:27 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/build-a-cash-register-project/build-a-cash-register.md
> +You should have a variable called `cid`.
```suggestion
You should have a global variable called `cid`. 
```

2024-06-13 18:50 UTC, ilenia-magoni approved these changes

2024-06-17 17:21 UTC, a2937 commented
@gikf I've added the changes in #55195 into my PR.

2024-06-17 18:21 UTC, gikf approved these changes
LGTM 👍 

@a2937 do you want to add anything else here?

2024-06-17 18:42 UTC, a2937 commented
I can't think of anything else?

2024-06-17 18:45 UTC, merged