fix(curriculum): Update description for Step 1 of the Luhn Algorithm Project
freeCodeCamp/freeCodeCamp pull request #54773
Opened 2024-05-13 19:51 UTC by MohamedRahimm

Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes #54733

2024-05-16 09:46 UTC, zairahira approved these changes

2024-05-20 13:49 UTC, Dario-DC requested changes

2024-05-20 13:49 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm/6565a536ba1f9f25bd30e88b.md
>  In this project, you will implement the Luhn Algorithm. This algorithm is a formula to validate a variety of identification numbers.
```suggestion

In this project, you will implement the Luhn Algorithm. This algorithm is a formula to validate a variety of identification numbers.
```

2024-05-20 13:49 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-how-to-work-with-numbers-and-strings-by-implementing-the-luhn-algorithm/6565a536ba1f9f25bd30e88b.md
>  In this project, you will implement the Luhn Algorithm. This algorithm is a formula to validate a variety of identification numbers.
That blank line is required

2024-05-21 07:25 UTC, Dario-DC approved these changes

2024-05-21 07:25 UTC, merged