feat: convert output test to Playwright
freeCodeCamp/freeCodeCamp pull request #54788
Opened 2024-05-14 11:39 UTC by Sembauke

- **feat: convert output test to Playwright**
- **chore: remove output test**

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-14 13:46 UTC, ojeytonwilliams requested changes

2024-05-14 16:20 UTC, Sembauke commented
Sorry i completely rushed this one

2024-05-14 18:49 UTC, naomi-lgbt approved these changes
Think this is good to go

2024-05-15 13:39 UTC, ojeytonwilliams approved these changes
Nice work, thanks @Sembauke! This LGTM :+1:

2024-05-15 13:40 UTC, merged