chore(curriculum): remove `__locals` from tower of hanoi puzzle project
freeCodeCamp/freeCodeCamp pull request #54784
Opened 2024-05-14 09:40 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-14 11:53 UTC, Sembauke approved these changes

2024-05-14 12:55 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-recursion-by-solving-the-tower-of-hanoi-puzzle/64de1469fccce61940f498c4.md
>      a['A'] == []
```suggestion
    rods['A'] == []
```

2024-05-14 12:55 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-recursion-by-solving-the-tower-of-hanoi-puzzle/64de1469fccce61940f498c4.md
>      a['B'] == []
```suggestion
    rods['B'] == []
```

2024-05-14 12:55 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-recursion-by-solving-the-tower-of-hanoi-puzzle/64de1469fccce61940f498c4.md
>      a['C'] == []
```suggestion
    rods['C'] == []
```

2024-05-14 12:55 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-recursion-by-solving-the-tower-of-hanoi-puzzle/657b6a4a49faec5c600287ba.md
>      hanoi(3, a, b, c)
```suggestion
    a, b, c = [3, 2, 1], [], []
    move(3, a, b, c)
```

2024-05-14 22:13 UTC, naomi-lgbt requested changes
![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/63889819/156dbb98-116c-48b0-acc9-64d5e4efb375)

Looks like quite a few instances of `__locals` still.

2024-05-15 08:10 UTC, ilenia-magoni commented
Thank you, now I should have got all of them!

2024-05-15 10:40 UTC, Dario-DC approved these changes

2024-05-15 16:41 UTC, naomi-lgbt approved these changes
No locals found in this block

2024-05-15 16:41 UTC, merged