fix(curriculum): acknowledge tracebacks in binary search tree
freeCodeCamp/freeCodeCamp pull request #54789
Opened 2024-05-14 11:46 UTC by zairahira

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54647

2024-05-15 09:51 UTC, Dario-DC requested changes

2024-05-16 12:56 UTC, Dario-DC approved these changes

2024-05-20 15:09 UTC, ilenia-magoni requested changes
The regex may need a small adjustmend

2024-05-20 15:09 UTC, ilenia-magoni commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-tree-traversal-by-building-a-binary-search-tree/65c646d4148ae3b2d1cbcac4.md
> +assert.match(code, /^(\s+)def\s+__init__.+?\1def\s+__str__\(\s*self\s*\)\s*:\s*\n\1\1pass/ms)
```suggestion
assert.match(code, /^(\s+)def\s+__init__.+?^\1def\s+__str__\(\s*self\s*\)\s*:\s*\n^\1\1pass/ms)
```

maybe? the other version wants at least 4 spaces, but it doesn't check that it is start of line + four spaces.

2024-05-21 11:35 UTC, ilenia-magoni approved these changes
LGTM

2024-05-21 11:35 UTC, merged