chore(curriculum): remove `__locals` from shortest path project
freeCodeCamp/freeCodeCamp pull request #54783
Opened 2024-05-14 09:34 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-14 12:50 UTC, Dario-DC requested changes

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557709b0aee699a6a00528c.md
>      "A" in graph
```suggestion
    "A" in my_graph
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557709b0aee699a6a00528c.md
>      graph["A"] == "B"
```suggestion
    my_graph["A"] == "B"
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557709b0aee699a6a00528c.md
>      "B" in graph
```suggestion
    "B" in my_graph
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557709b0aee699a6a00528c.md
>      graph["B"] == "A"
```suggestion
    my_graph["B"] == "A"
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557709b0aee699a6a00528c.md
>      len(graph) == 2
```suggestion
    len(my_graph) == 2
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557712d77ce2d9bd7e63afd.md
>      len(graph) == 3 and all(key in graph for key in key_list)
```suggestion
    key_list = ["A", "B", "C"]
    len(my_graph) == 3 and all(key in my_graph for key in key_list)
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557712d77ce2d9bd7e63afd.md
>      graph["A"] == "B"
```suggestion
    my_graph["A"] == "B"
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557712d77ce2d9bd7e63afd.md
>      type(graph["B"]) is list
```suggestion
    type(my_graph["B"]) is list
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557712d77ce2d9bd7e63afd.md
>      len(graph["B"]) == 2 and "A" in graph["B"] and "C" in graph["B"]
```suggestion
    len(my_graph["B"]) == 2 and "A" in my_graph["B"] and "C" in my_graph["B"]
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557712d77ce2d9bd7e63afd.md
>      graph["C"] == "B"
```suggestion
    my_graph["C"] == "B"
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      len(graph) == 4 and all(key in graph for key in key_list)
```suggestion
    key_list = ["A", "B", "C", "D"]
    len(my_graph) == 4 and all(key in my_graph for key in key_list)
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      type(graph["A"]) is list
```suggestion
    type(my_graph["A"]) is list
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      len(graph["A"]) == 2 and "B" in graph["A"] and "D" in graph["A"]
```suggestion
    len(my_graph["A"]) == 2 and "B" in my_graph["A"] and "D" in my_graph["A"]
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      type(graph["B"]) is list
```suggestion
    type(my_graph["B"]) is list
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      len(graph["B"]) == 2 and "A" in graph["B"] and "C" in graph["B"]
```suggestion
    len(my_graph["B"]) == 2 and "A" in my_graph["B"] and "C" in my_graph["B"]
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      type(graph["C"]) is list
```suggestion
    type(my_graph["C"]) is list
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      len(graph["C"]) == 2 and "B" in graph["C"] and "D" in graph["C"]
```suggestion
    len(my_graph["C"]) == 2 and "B" in my_graph["C"] and "D" in my_graph["C"]
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      type(graph["D"]) is list
```suggestion
    type(my_graph["D"]) is list
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557716aadbd2d9c42c0e69a.md
>      len(graph["D"]) == 2 and "A" in graph["D"] and "C" in graph["D"]
```suggestion
    len(my_graph["D"]) == 2 and "A" in my_graph["D"] and "C" in my_graph["D"]
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6557924d47c325bf27afbe51.md
>      sig = str(inspect.signature(foo))
```suggestion
    sig = str(inspect.signature(shortest_path))
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6566195b0a021bb660b2b4b1.md
>      type(graph["B"]) is list and all(type(i) is tuple for i in graph["B"])
```suggestion
    type(my_graph["B"]) is list and all(type(i) is tuple for i in my_graph["B"])
```

2024-05-14 12:50 UTC, Dario-DC commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-algorithm-design-by-building-a-shortest-path-algorithm/6566195b0a021bb660b2b4b1.md
>      len(graph["B"]) == 2 and all(t in graph["B"] for t in tuples)
```suggestion
    tuples = [("A", 3), ("C", 4)]
    len(my_graph["B"]) == 2 and all(t in my_graph["B"] for t in tuples)
```

2024-05-14 22:08 UTC, naomi-lgbt approved these changes
No locals found in block

2024-05-15 07:57 UTC, Dario-DC approved these changes

2024-05-15 07:58 UTC, merged