chore: remove unused meta
freeCodeCamp/freeCodeCamp pull request #54823
Opened 2024-05-15 23:16 UTC by moT01

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-16 20:35 UTC, moT01 commented
I'm gonna see if I can add some tests

2024-05-20 18:05 UTC, naomi-lgbt approved these changes

2024-05-30 12:24 UTC, ShaunSHamilton requested changes

2024-05-30 12:24 UTC, ShaunSHamilton commented on curriculum/get-challenges.js
> +      );
I assume we want to remove this?

```suggestion
```

2024-05-31 15:10 UTC, ojeytonwilliams approved these changes
Has validation :heart:. A+ would review again.

2024-05-31 19:30 UTC, ShaunSHamilton approved these changes

2024-05-31 19:31 UTC, merged

2025-07-13 17:15 UTC, Muhammad-Mubashar516 commented
Hello, I am a new contributor and I would like to work on this issue. Can you please assign it to me? Thank you!