fix(curriculum): last assertion for review DOM project step 5
freeCodeCamp/freeCodeCamp pull request #54841
Opened 2024-05-16 16:40 UTC by jdwilkin4

## Summary
Currently the test passes without changing the display to block as mentioned in this forum post here
https://forum.freecodecamp.org/t/review-dom-manipulation-by-building-a-rock-paper-scissors-game-step-5/690574

The update the last assertion fixes that
Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-16 20:27 UTC, JoyShaheb requested changes

2024-05-16 20:27 UTC, JoyShaheb commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/review-dom-manipulation-by-building-a-rock-paper-scissors-game/663d5697d80fef0eea026672.md
> +
whats this blank space doing here ?

2024-05-18 15:52 UTC, JoyShaheb approved these changes

2024-05-21 09:39 UTC, Ksound22 approved these changes

2024-05-21 16:41 UTC, merged