feat: convert adding development redirect tests to Playwright
freeCodeCamp/freeCodeCamp pull request #54897
Opened 2024-05-21 07:52 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-21 10:14 UTC, ojeytonwilliams requested changes
There's no need to check the response and try to find which url the browser is being redirected to. All we care about is which page the browser ends up at. i.e. `expect(page).toHaveUrl(expected)`

Given challenges.spec does this properly, I think it makes sense to consolidate the redirections into that file (maybe rename it redirects.spec.ts, too, since that's a better description).

2024-05-23 06:29 UTC, huyenltnguyen approved these changes

2024-05-30 07:22 UTC, ojeytonwilliams requested changes
Just one missing:

2024-05-30 07:22 UTC, ojeytonwilliams commented on e2e/redirect.spec.ts
> +  },
```suggestion
    input: '/learn/front-end-libraries',
    expected: 'learn/front-end-development-libraries'
  },
  {
    input: '/learn/front-end-libraries/bootstrap',
    expected: 'learn/front-end-development-libraries/bootstrap'
  },
```

2024-05-30 08:34 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2024-05-30 08:34 UTC, merged