Added functionality to merge steps 21 and 22
freeCodeCamp/freeCodeCamp pull request #54917
Opened 2024-05-22 11:08 UTC by vaibhav-ace

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54912

2024-05-23 10:30 UTC, ilenia-magoni requested changes
Thank you for your work, you are doing well!

I have left some comments on things to change

2024-05-23 10:30 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
> +Create two `div` elements. First inside `.cat-left-ear` element with class `cat-left-inner-ear`, and second inside `.cat-right-ear` element with class `cat-right-inner-ear`.
```suggestion
Create two `div` elements: the first inside the `.cat-left-ear` element with a class of `cat-left-inner-ear`, and the second inside the `.cat-right-ear` element with a class of `cat-right-inner-ear`.
```

2024-05-23 10:30 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
> +Your `div` elements should have the class `cat-left-inner-ear` and `cat-right-inner-ear`.
please divide this test into two, one for each div

2024-05-23 10:30 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
> +You should have a `div` element inside your `.cat-left-ear` and `.cat-right-ear` element.
This also please  change into two tests one for each element

2024-05-23 10:30 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ddd3f9f97a0667b964bdb.md
> +Create two `div` elements, one with the class `cat-left-inner-eye` inside the `.cat-left-eye` element and the second with the class `cat-right-inner-eye` inside the `.cat-right-eye` element.
```suggestion
Create two `div` elements, one with the class `cat-left-inner-eye` inside the `.cat-left-eye` element and an other with the class `cat-right-inner-eye` inside the `.cat-right-eye` element.
```

2024-05-23 10:30 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ddd3f9f97a0667b964bdb.md
> +You should have two `div` elements inside your `.cat-left-eye` element and `.cat-right-eye` element.
please have two different tests here

2024-05-23 10:30 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ddd3f9f97a0667b964bdb.md
> +Your `div` elements should have the class `cat-left-inner-eye` and `cat-right-inner-eye`.
please have two different tests here

2024-05-23 12:27 UTC, vaibhav-ace commented
Thanks a lot for the review and feedback. I highly appreciate the help as I try and get better in my contributions 🙏 I have made the necessary changes and hope they suffice the conditions for a merge. Please let me know if any further changes are required, I will be more than happy to work on them. 😄

2024-05-23 15:12 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
```suggestion
Create two `div` elements, the first inside the `.cat-left-ear` element with a class of `cat-left-inner-ear`, and the second inside the `.cat-right-ear` element with a class of `cat-right-inner-ear`.
```

2024-05-23 15:17 UTC, ilenia-magoni requested changes
Going well, the new hints require some adjustments!

2024-05-23 15:17 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
>  You should have a `div` element inside your `.cat-left-ear` element.
```suggestion
You should have one `div` element inside your `.cat-left-ear` element.
```

2024-05-23 15:17 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
> +You should have a `div` element inside your `.cat-right-ear` element.
```suggestion
You should have one `div` element inside your `.cat-right-ear` element.
```

2024-05-23 15:17 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
>  Your `div` element should have the class `cat-left-inner-ear`.
```suggestion
The new `div` element inside `.cat-left-ear` should have the class `cat-left-inner-ear`.
```

2024-05-23 15:17 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ce9d790d2a44de5f99e04.md
> +Your `div` element should have the class `cat-right-inner-ear`.
```suggestion
THe new `div` element inside `.cat-right-ear` should have the class `cat-right-inner-ear`.
```

2024-05-23 15:17 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ddd3f9f97a0667b964bdb.md
>  Your `div` element should have the class `cat-left-inner-eye`.
```suggestion
The new `div` element inside `.cat-left-eye` should have the class `cat-left-inner-eye`.
```

2024-05-23 15:17 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ddd3f9f97a0667b964bdb.md
> +Your `div` element should have the class `cat-right-inner-eye`.
```suggestion
The new `div` element inside `.cat-right-eye` should have the class `cat-right-inner-eye`.
```

2024-05-24 03:46 UTC, vaibhav-ace commented
Thanks for the suggestions. I've changed the code as per the feedback.

2024-05-24 08:49 UTC, ilenia-magoni approved these changes
LGTM 👍

2024-05-25 19:30 UTC, naomi-lgbt approved these changes

2024-05-25 19:30 UTC, merged