feat(api): finish update-my-email endpoint
freeCodeCamp/freeCodeCamp pull request #54921
Opened 2024-05-22 12:54 UTC by ojeytonwilliams

- **refactor: use reply.send instead of return**
- **refactor: remove unnecessary ?s**
- **test: check emailAuthLinkTTL is created**
- **feat: send create AuthToken and send email**
- **fix: change success response**

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-05-31 13:13 UTC, ShaunSHamilton requested changes
I did not want to hold this up, but, at the same time, knew I would not remember to fix this until it annoyed me again.

2024-05-31 13:13 UTC, ShaunSHamilton commented on api/src/routes/settings.test.ts
```suggestion
import { API_LOCATION } from '../utils/env';
```

2024-05-31 13:13 UTC, ShaunSHamilton commented on api/src/routes/settings.test.ts
> +        const expectedLink = `http://localhost:3000/confirm-email?email=${Buffer.from(unusedEmailOne).toString('base64')}&token=123&emailChange=true`;
```suggestion
        const expectedLink = `${API_LOCATION}/confirm-email?email=${Buffer.from(unusedEmailOne).toString('base64')}&token=123&emailChange=true`;
```

2024-05-31 13:37 UTC, ojeytonwilliams commented on api/src/routes/settings.test.ts
> +        const expectedLink = `http://localhost:3000/confirm-email?email=${Buffer.from(unusedEmailOne).toString('base64')}&token=123&emailChange=true`;
Thanks. I shouldn't have been lazy.

2024-06-03 06:26 UTC, ShaunSHamilton approved these changes
LGTM 👍

2024-06-03 07:08 UTC, Sembauke approved these changes

2024-06-03 07:08 UTC, merged