fix(curriculum): separate unreachable code and scope for pyramid project
freeCodeCamp/freeCodeCamp pull request #54920
Opened 2024-05-22 12:48 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54809

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/07433c57-3c72-4b43-b692-932e405820b1)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/9ca0f686-6840-41e9-b189-62ffcc210cea)

2024-05-29 15:46 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/6610c77d50636722e5b6be17.md
> +Add `console.log("This works!");` below the `return` statement.
```suggestion
Below the `return` statement, log the string `"This works!"` to the console.
```

2024-05-29 15:57 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/6610c77d50636722e5b6be17.md
> +An important thing to know about the `return` keyword is that it does not just define a value to be returned from your function, it also stops the execution of your function code. This means that any
```suggestion
After doing that, you will see that the string `"This works!"` does not display in the console, and the `console.log("This works!")` line is greyed out.

Copy and paste the line of code above the `return` statement. Now, the string `"This works!"` should appear in the console.

An important thing to know about the `return` keyword is that it does not just define a value to be returned from your function, it also stops the execution of your code inside a function or a block statement. This means any code after a `return` statement will not run.
```

2024-05-30 06:01 UTC, Ksound22 approved these changes

2024-06-02 18:29 UTC, lasjorg requested changes
Two new challenges were added, so step 51 is now 53.

2024-06-02 18:29 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/6610c6541c82551f95e765ab.md
Can you please edit the text in step 51 (now 53)

> If you try to access it outside of the function, you will either get `undefined` or an error.

To

> If you try to access it outside of the function, you get a reference error.

2024-06-02 18:29 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/6610c71600966a2191d3a64a.md
> +Returning a value from a function brings that value into the scope where the function was called. To bring your `"Testing"` value from the `padRow` function into the global scope, update your return
````md
Values returned out of functions are used by calling the function. You can use the function call directly as the value it returns, or capture the returned value in a variable. This way, you can use the value assigned to a locally scoped variable, outside the function it was created in.

```js
function getName() {
  const name = "Camper cat";
  return name;
}

console.log(getName()); // "Camper cat"

const capturedReturnValue = getName();
console.log(capturedReturnValue); // "Camper cat"

console.log(name); // reference error
```

To use your `"Testing"` value returned from the `padRow` function, update your `return` statement to return only the `test` variable.

````

---

This is just a suggestion, but I think what we have now can be misinterpreted in multiple ways. I suggest we simplify this and give a small code example.

2024-06-02 18:29 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/6610c77d50636722e5b6be17.md
> +Copy and paste the line of code above the `return` statement. Now, the string `"This works!"` should appear in the console.
```suggestion
Copy the console log and paste it above the `return` statement. Now, the string `"This works!"` should appear in the console.
```

2024-06-03 17:12 UTC, lasjorg requested changes

2024-06-03 17:12 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/6610c71600966a2191d3a64a.md
> +To use your `"Testing"` value returned from the `padRow` function, update your `return` statement to return only the `test` variable.
```suggestion
To use your `"Testing"` value, return it out of the `padRow` function by updating your `return` statement to return only the `test` variable.
```

Sorry, I missed this when I updated the text.

2024-06-04 00:19 UTC, lasjorg approved these changes
This looks good.

---

I was thinking that we could try to avoid the assert message for the two console logs in Step 55 if the camper typos the log string (just to avoid confusion) but I don't think we need to do that.

2024-06-04 00:20 UTC, merged