fix(learn): render note on /responsive-web-design/basic-css/
freeCodeCamp/freeCodeCamp pull request #54979
Opened 2024-05-24 21:12 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54974

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/00897745-bce3-49f6-bd2e-d12c4dbe60e7)

2024-05-27 17:45 UTC, naomi-lgbt approved these changes

2024-05-27 23:00 UTC, lasjorg commented
We don't need the `show` class either, do we?

2024-05-28 17:43 UTC, lasjorg requested changes

2024-05-28 17:43 UTC, lasjorg commented on client/src/pages/learn/responsive-web-design/basic-css/index.md
> +<div role="alert" class="alert alert-info show">
```suggestion
<div role="alert" class="alert alert-info">
```
Pretty sure the `show` class isn't used for anything here. Considering it is a utility class with `!important` it really should not be applied unless needed.

2024-05-29 15:06 UTC, lasjorg approved these changes

2024-05-29 15:06 UTC, merged