fix(curriculum): add example for arrow functions in Platformer Game
freeCodeCamp/freeCodeCamp pull request #54982
Opened 2024-05-25 19:21 UTC by aliarnoos

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54956

Summary: 

added an example function in how to use an arrow function with destruction of its parameters for **step 59** of the course **JavaScript Algorithms and Data Structures (Beta)**

2024-05-25 19:47 UTC, aliarnoos commented
This is my first contribution, so I would appreciate any feedback if I mess up any step of the process, or any feedback in general. Thank you :)

2024-05-26 18:16 UTC, naomi-lgbt requested changes
Thanks for your interest in contributing! We'll need to add the text explaining that the code is an example.

2024-05-26 18:16 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/64c72e52133d687e8e6a60f6.md
> +
````suggestion
Here is the syntax for using the destructuring assignment in the parameter list of the arrow function:

```js
btn.addEventListener('click', ({example}) => {
  console.log(example);
});
```

````

2024-05-26 18:17 UTC, naomi-lgbt commented
As an aside, you should always work off of a new branch and not your `main` branch.

2024-05-26 18:23 UTC, aliarnoos commented
Noted!, thank you so much

2024-05-26 18:29 UTC, naomi-lgbt approved these changes

2024-05-27 23:27 UTC, lasjorg commented
I'm not crazy about the example code. Considering it is the event object, and it won't have an `example` property on that object. So if they test it and run the code, it will just log `undefined`.

I would suggest using a more "real" example. Or at least some that works/does something.
```
const user = { id: 42, name: "arthur" };

function getUserId({ id }) {
  console.log(id); // 42
}

getUserId(user);
```

2024-05-27 23:39 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/64c72e52133d687e8e6a60f6.md
> +  console.log(example);
```suggestion
btn.addEventListener('click', ({ target }) => {
  console.log(target);
```

2024-05-29 19:42 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-intermediate-oop-by-building-a-platformer-game/64c72e52133d687e8e6a60f6.md
> +  console.log(example);
@aliarnoos please make the suggested change.

2024-05-29 20:24 UTC, lasjorg approved these changes
Looks good to me.

2024-05-29 20:24 UTC, merged