fix(curriculum): underscores in python for everybody challenge
freeCodeCamp/freeCodeCamp pull request #55013
Opened 2024-05-29 14:56 UTC by moT01

Parsing the markdown for this challenge with the CAP API was giving me issues. I was getting this: `<p>Most data needs to be _<em>_</em>__ before using it.</p>` This adjustment seems fine.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-31 15:21 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2024-05-31 16:08 UTC, ojeytonwilliams requested changes

2024-05-31 16:08 UTC, ojeytonwilliams commented on curriculum/challenges/english/23-python-for-everybody/python-for-everybody/visualizing-data-with-python.md
> +Most data needs to be **______** before using it.
```suggestion
Most data needs to be ______ before using it.
```
Should be fine

2024-06-05 08:15 UTC, ojeytonwilliams approved these changes

2024-06-06 06:43 UTC, huyenltnguyen approved these changes

2024-06-06 06:43 UTC, merged