fix(curriculum): english challenges for CAP
freeCodeCamp/freeCodeCamp pull request #55014
Opened 2024-05-29 16:10 UTC by moT01

Parsing the markdown from the CAP DB gave me some slight differences. This will fix those. The third one was being parsed like this: `<p>For example, if you're working with text, you'd use this data type, "_". If it's _ <em>, you'd choose "</em>".</p>` - probably an issue with the way I am parsing it - but since it's the only one with this issue, I thought it would be fine to just make a slight adjustment. The change doesn't really have any effect on what the challenge looks like.

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-05-31 15:43 UTC, ojeytonwilliams requested changes

2024-05-31 15:43 UTC, ojeytonwilliams commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-use-code-related-concepts-and-terms/663246e8f661af779398be0e.md
> +`For example, if you're working with text, you'd use this data type, " _ ". If it's _ _, you'd choose " _ ".`
```suggestion
`For example, if you're working with text, you'd use this data type, "\_". If it's _ _, you'd choose "\_".`
```
Escaping the `_` seems like a more natural solution.

2024-05-31 16:14 UTC, ojeytonwilliams commented
Sorry, Tom that change doesn't seem to work. When I was playing around with it, they appeared in the sentence.

Slightly leftfield idea, but maybe we should use a different character for the blanks? Something that doesn't mean anything as far as markdown is concerned, like `=`.

2024-05-31 16:22 UTC, ojeytonwilliams commented
Actually, I think the problem is that they're getting turned into html somewhere in the pipeline. That shouldn't happen, since they have to be split around the blanks first.

2024-06-03 21:11 UTC, moT01 commented
> use a different character ... like =

Yea, that might be a good idea. It's not as intuitive when creating the challenges. Underscore is more easily interpreted as a blank, but people could adjust. Not sure how much rewriting would be involved. All the challenges would have to be fixed, but that's probably an easy replace. Then the view component would need to be adjusted, probably also pretty easy.

2024-06-04 08:07 UTC, ojeytonwilliams commented
>  Wonder if = is used anywhere - since the lessons often talk about code, it may happen.

It _is_, but not in fill in the blank sentences. It wouldn't make a lot of sense to do so, because you'd never say `=`, you'd say "equals".

2024-06-20 14:36 UTC, ojeytonwilliams commented
Hey @moT01 where are we at with this? Is the plan to change to a different 'blank'?

2024-06-20 16:01 UTC, moT01 commented
It looks like the challenge that was causing issues on this PR was changed in a way that it no longer causes an issue. So we can merge this PR. As for changing the blanks to something else, I think we should maybe create a new issue for that. I'm on it.

2024-06-20 17:52 UTC, ojeytonwilliams approved these changes
LGTM 👍

2024-06-20 17:58 UTC, huyenltnguyen approved these changes

2024-06-20 17:58 UTC, merged