fix(curriculum):Added clarification for what text-align does
freeCodeCamp/freeCodeCamp pull request #55026
Opened 2024-05-30 05:42 UTC by sanjeevmurmu

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55018

2024-05-30 16:18 UTC, a2937 approved these changes
Looks Good To Me! 👍

2024-05-30 16:19 UTC, a2937 requested changes
Wait I see a minor issue.

2024-05-30 16:19 UTC, a2937 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-basic-css-by-building-a-cafe-menu/5f3477ae9675db8bb7655b30.md
> +In the previous step, you used a <dfn>type selector</dfn> to style the `h1` element. Center the content of `h2` and `p` elements by adding a new type selector for each one to the existing `style` ele
Wait I see a minor issue. You are missing a `the`.

2024-05-31 12:51 UTC, sanjeevmurmu reviewed
Added the

2024-05-31 19:13 UTC, gikf approved these changes
👍 
- - -
Note for future - it is recommended to make changes on a separate branch, rather than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/#/how-to-contribute-to-the-codebase?id=contributing-to-the-codebase.

2024-05-31 19:28 UTC, a2937 approved these changes
Looks Good To Me! 👍

2024-05-31 19:29 UTC, merged