fix(curriculum): changed typo "h2" to "output"
freeCodeCamp/freeCodeCamp pull request #55022
Opened 2024-05-29 19:26 UTC by andrebdinis

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55020

2024-05-29 19:54 UTC, lasjorg requested changes
I think we should add backticks to all the element type for consistency.

2024-05-29 19:54 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-recursion-by-building-a-decimal-to-binary-converter/63db7f4677d06d7500a13321.md
> +When you're ready to get started, use the `.getElementById()` method to get the input element with the id `number-input`, and store it in a variable called `numberInput`. Use the same method to get t
```suggestion
When you're ready to get started, use the `.getElementById()` method to get the `input` element with the id `number-input`, and store it in a variable called `numberInput`. Use the same method to get the `button` element with the id `convert-btn` and store it in a variable called `convertBtn`, and the `output` element with the id `result` and store it in a variable called `result`.
```

2024-05-30 15:25 UTC, lasjorg approved these changes
There wasn't really a consensus on this in the issue. But I think marking the element types is probably the right call.

So I will approve this, and we can wait and see if anyone disagrees with it.

2024-05-30 16:08 UTC, a2937 approved these changes
In my opinion, every element type needs to be properly placed inside of backticks so that the translators know that the word actually refers to a proper HTML element as those should not get translated. 

That being said, nice find. Looks good to me. 👍

2024-05-30 16:47 UTC, merged