fix(curriculum): combine step 150 and step 151 in js beta build a RPG
freeCodeCamp/freeCodeCamp pull request #55095
Opened 2024-06-05 15:22 UTC by altsun

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #54866

2024-06-05 16:12 UTC, naomi-lgbt requested changes
Just one nitpick.

2024-06-05 16:12 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa204c1e1d33348ff09944.md
> +assert.equal(attack.toString().match(/if/g).length, 4)
```suggestion
assert.lengthOf(attack.toString().match(/if/g), 4)
```

Specific assert method we can use here.

2024-06-06 02:11 UTC, altsun commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62aa204c1e1d33348ff09944.md
> +assert.equal(attack.toString().match(/if/g).length, 4)
Addressed

2024-06-06 06:23 UTC, Sembauke approved these changes

2024-06-07 00:28 UTC, naomi-lgbt approved these changes

2024-06-07 00:28 UTC, merged