feat: The Odin Project - Rock Paper Scissors Game
freeCodeCamp/freeCodeCamp pull request #55110
Opened 2024-06-07 10:26 UTC by Sembauke

- **feat: outline**
- **feat: partially add tests and add description**

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-06-24 18:32 UTC, naomi-lgbt requested changes

2024-06-25 06:44 UTC, Sembauke commented on curriculum/challenges/english/16-the-odin-project/top-build-a-rock-paper-scissors-game/build-a-rock-paper-scissors-game.md
> +1. Define two parameters for `playRound`. Parameter one `humanChoice` and parameter two `computerChoice`. Use these two parameters to take the human and computer choices as arguments.
Yes.

2024-06-25 15:39 UTC, naomi-lgbt approved these changes
Naomi's test this time really for sure v3

2024-06-27 15:55 UTC, moT01 approved these changes

2024-06-27 15:55 UTC, merged