feat(curriculum): added more tests to file: rosetta code Tokenize a string with escaping
freeCodeCamp/freeCodeCamp pull request #55142
Opened 2024-06-09 20:35 UTC by JLH13

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54687

This file had a comment that it needed more test cases. I added in three more.

2024-06-10 09:22 UTC, ilenia-magoni requested changes
Please properly add new tests. If you have questions you can reach out on Discord or the forum

2024-06-10 09:22 UTC, ilenia-magoni commented on curriculum/challenges/english/22-rosetta-code/rosetta-code-challenges/tokenize-a-string-with-escaping.md
> +
you only added some strints and arrays, doing nothing with them, as such, no new test has been added.

2024-06-20 14:38 UTC, ojeytonwilliams commented
Closing as stale.

2024-06-20 14:38 UTC, closed without merging

2024-06-23 06:58 UTC, naomi-lgbt commented on curriculum/challenges/english/22-rosetta-code/rosetta-code-challenges/tokenize-a-string-with-escaping.md
> -// TODO add more tests
These tests all need to be reflected in the test cases for the user's code above.