Fix pronouns for two tasks on block 2.1
freeCodeCamp/freeCodeCamp pull request #55151
Opened 2024-06-10 13:48 UTC by nieldakarla

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-06-10 19:23 UTC, DanielRosa74 reviewed
There's also a `he` here. It needs to be changed to `she` as well.

2024-06-10 19:24 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-how-to-talk-about-a-typical-workday-and-tasks/657e07a2fdda8d5ac93d415e.md
> +Sophie is describing what he does next in her routine after the first activity she mentioned.
There is also a `he` here. It needs to be changed to `she` as well.

2024-06-11 18:06 UTC, DanielRosa74 requested changes
Change suggested to line 36 of file 657e07a2fdda8d5ac93d415e.md

2024-06-11 20:28 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b6f641e5c3ab1afc6efc1.md
> +Before you learned to ask questions using `do,` you can also use it to create negative sentences by combining `do` (for I, you, we, they) or `does` (for he, she, it) with the word `not` and placing i
I'd suggest that the pronouns be surrounded by backslashes (e.g: `I`, `you`, `we`, `they`) in the parentheses.

2024-06-11 20:29 UTC, DanielRosa74 requested changes
Change suggested to 657b6f641e5c3ab1afc6efc1.md

2024-06-13 18:52 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b6f641e5c3ab1afc6efc1.md
> +Before you learned to ask questions using `do,` you can also use it to create negative sentences by combining `do` (for I, you, we, they) or `does` (for he, she, it) with the word `not` and placing i
```suggestion
Before you learned to ask questions using `do,` you can also use it to create negative sentences by combining `do` (for `I`, `you`, `we`, `they`) or `does` (for `he`, `she`, `it`) with the word `not` and placing it right before the main verb:
```

2024-06-13 18:53 UTC, nieldakarla commented on curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b6f641e5c3ab1afc6efc1.md
>  `It does not function` - (Subject + does + not + main verb)
```suggestion

`It does not function` - (Subject + `does` + `not` + main verb)
```

2024-06-13 18:56 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b6f641e5c3ab1afc6efc1.md
> +Before you learned to ask questions using `do,` you can also use it to create negative sentences by combining `do` (for I, you, we, they) or `does` (for he, she, it) with the word `not` and placing i
```suggestion
Before you learned to ask questions using `do,` you can also use it to create negative sentences by combining `do` (for `I`, `you`, `we`, `they`) or `does` (for `he`, `she`, `it`) with the word `not` and placing it right before the main verb:
```

2024-06-13 18:56 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b6f641e5c3ab1afc6efc1.md
>  `I do not work everyday` - (Subject + do + not + main verb)
```suggestion
`I do not work everyday` - (Subject + `do` + `not` + main verb)
```

2024-06-13 18:57 UTC, DanielRosa74 commented on curriculum/challenges/english/21-a2-english-for-developers/learn-conversation-starters-in-the-break-room/657b6f641e5c3ab1afc6efc1.md
>  `It does not function` - (Subject + does + not + main verb)
```suggestion
`It does not function` - (Subject + `does` + `not` + main verb)
```

2024-06-13 19:32 UTC, DanielRosa74 approved these changes
LGTM

2024-06-17 05:10 UTC, huyenltnguyen approved these changes

2024-06-17 05:11 UTC, merged