fix(curriculum):  Step 103 Pyramid Generator Text
freeCodeCamp/freeCodeCamp pull request #55162
Opened 2024-06-11 16:37 UTC by mpdillingerOSU

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes  #55158

First-time contributor! I have followed the exact recommended change -as set by @Ksound22 within the discussion of the issue. If I did anything incorrectly, please let me know! I want to continue contributing to this project in the future.

2024-06-11 17:50 UTC, ilenia-magoni commented
No, sorry, you made changes to the arabic file

2024-06-11 17:51 UTC, ilenia-magoni requested changes
No, sorry, you made changes to the arabic file

2024-06-11 18:52 UTC, mpdillingerOSU reviewed
Thank you for the note! My fault for not realizing that different languages still shared the same code file name when using the search function. Will remember that for the future!

2024-06-12 06:39 UTC, ilenia-magoni approved these changes
LGTM 👍

2024-06-12 09:12 UTC, Ksound22 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660f4e74f7fd3f4a99ac2e50.md
> +Directly below the declaration of `numbers`, declare a `shifted` variable, and assign it the result of calling `.shift()` on your `numbers` array. Then, on the next line, print the variable.
We can make the text simpler a bit:

```suggestion
Directly below your `numbers` array, declare a `shifted` variable and assign it the result of calling `.shift()` on the `numbers` array. On the next line, log the `shifted` variable to the console.
```

2024-06-13 06:16 UTC, Sembauke approved these changes

2024-06-13 06:40 UTC, merged