fix(api): handle 4XX errors get-public-profile
freeCodeCamp/freeCodeCamp pull request #55205
Opened 2024-06-17 10:36 UTC by ShaunSHamilton

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

There is probably a "Loopback" way to do this, but less LB3 == more better.

2024-06-17 14:28 UTC, ShaunSHamilton commented
> Do we know how to quantify our own use of this endpoint?

If I understand:
Best: Build and serve client, then view a profile at `/<username>` (e.g. `/developmentuser`)
Easiest: `npm run develop`, go to `/developmentuser`, click `Go to profile`, view network requests as both signed-in user and incognito user

2024-06-18 16:55 UTC, Nirajn2311 reviewed
If I understood the PR correctly, then it remove the public profile endpoint from loopback User model and we create our own logic and handler right? If that's the case then this is good to go from mobile perspective as we're not using this endpoint.

2024-06-19 13:16 UTC, raisedadead approved these changes
LGTM

2024-06-19 13:37 UTC, raisedadead requested changes
Sorry - some last minute nitpicks

2024-06-19 13:37 UTC, raisedadead commented on api-server/src/server/boot/randomAPIs.js
> +  const blockedUserAgentParts = ['python', 'google-apps-script'];
```suggestion
  const blockedUserAgentParts = ['python', 'google-apps-script', 'curl'];
```

2024-06-19 13:37 UTC, raisedadead commented on api-server/src/server/boot/randomAPIs.js
> +      return res.status(403).send('Forbidden');
```suggestion
      return res
        .status(400)
        .send(
          'This endpoint is no longer available outside of the freeCodeCamp ecosystem'
        );
```

2024-06-20 05:54 UTC, raisedadead approved these changes

2024-06-20 05:54 UTC, merged