fix: various typos fixed
freeCodeCamp/freeCodeCamp pull request #55277
Opened 2024-06-21 19:58 UTC by rohan220217

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55275

2024-06-21 20:11 UTC, ilenia-magoni requested changes
Please do as the bot says, remove the changes from non-english files

2024-06-21 20:13 UTC, ilenia-magoni commented
> Closes #55275

if your PR target multiple issues, you need to add that it closes the other issues too. But please solve only one issue.

2024-06-22 18:56 UTC, lasjorg requested changes

2024-06-22 18:56 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da4b16937be43ba24c63d.md
> +Your second `.then()` should not have semi-colon after it.
```suggestion
Your second `.then()` should not have a semicolon after it.
```

2024-06-22 19:26 UTC, lasjorg commented
As said, please remove the change for the binary typo. It is handled in another PR and does not belong in this PR.

2024-06-24 03:19 UTC, JoyShaheb approved these changes

2024-06-24 04:13 UTC, gikf commented
Hey @rohan220217

Thank you for opening this pull request.

As there was different PR - #55296 - making all necessary changes, merged recently, we are going to close this one.

Thank you and happy coding! 😊

---

If you have any questions, feel free to ask questions on the ['Contributors' category on our forum](https://forum.freecodecamp.org/c/contributors) or [the contributors chat room](https://discord.gg/PRyKn3Vbay).

2024-06-24 04:13 UTC, closed without merging