fix(curriculum): add back ticks to variable name Platformer Game step 20
freeCodeCamp/freeCodeCamp pull request #55287
Opened 2024-06-22 09:43 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54174

Add backticks to the `ctx` variable.

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/67df09d7-5daa-4a72-9537-6f8b726ee993)

2024-06-22 19:11 UTC, lasjorg approved these changes
LGTM.

---

Your "Closes" is pointing to an already merged PR. Please update the description to the correct issue or remove it.

2024-06-23 11:07 UTC, ilenia-magoni requested changes
The change is good, but blocking this until the linking to wrong pr is fixed

2024-06-24 03:18 UTC, JoyShaheb approved these changes

2024-06-24 08:57 UTC, ilenia-magoni approved these changes

2024-06-24 08:57 UTC, merged