fix(curriculum): demistify cat ear triangle Cat Painting step 22
freeCodeCamp/freeCodeCamp pull request #55290
Opened 2024-06-22 11:09 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #53607

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/3f350440-e04a-44ef-b8ec-f45e9622bede)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/8c6e251c-2d08-448f-bb2e-40daf0c589ae)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/b4bfc744-e60a-4969-a12a-09572147f843)

2024-06-23 15:38 UTC, ilenia-magoni commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6676a8b01e56ec1a1e07c202.md
> +Your `.cat-right-ear` selector should have a `background-color` property set to `white`. Don't forget to add a semi-colon.
```suggestion
Your `.cat-right-ear` selector should have a `background-color` property set to `white`. Don't forget to add a semicolon.
```

2024-06-24 18:10 UTC, naomi-lgbt requested changes

2024-06-24 18:10 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/646ceb843412c74edee27a79.md
> +Using a class selector, give the `.cat-right-ear` element `height` and `width` properties set to `100px`. Set the `background-color` to white. Set left and right border to `35px solid blue`. Set top
```suggestion
Using a class selector, give the `.cat-right-ear` element `height` and `width` properties set to `100px`. Set the `background-color` to white. Set the left and right borders to `35px solid blue`. Set the top and bottom borders to `35px solid red`.
```

2024-06-24 18:10 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6676a8a8d9861319ee901a90.md
> +You are going to make each ear look like a triangle.
```suggestion
Now you can begin working on your cat's ears.

Clean up your review code by removing the `.cat-right-ear` selector and all of its properties.
```

2024-06-24 18:10 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6676a8b01e56ec1a1e07c202.md
> +Within the same class selector adjust `height` and `width` to `0`. Set the left, right and top border to `transparent`.
```suggestion
Notice that you now have a white square with thick borders. The borders have diagonal edges which can be used to create triangles.

Within the same class selector adjust `height` and `width` to `0`. Set the left, right and top border to `transparent`.

Remove the `background-color` property, and you should see a triangle.
```

Let's actually have them complete the triangle.

2024-06-24 18:10 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6676a8b01e56ec1a1e07c202.md
> +
````suggestion

Your `.cat-right-ear` selector should not have a `background-color` property.

```js
assert(!new __helpers.CSSHelp(document).getStyle('.cat-right-ear')?.backgroundColor)
```

````

And test for it.

2024-06-24 18:10 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6676a8a8d9861319ee901a90.md
> +  background-color: white;
```suggestion
```

This'll have to get tossed from the seed.

2024-06-24 18:10 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6676a8a8d9861319ee901a90.md
> +```
```suggestion
```

And then we don't gotta test for it.

2024-06-25 00:29 UTC, naomi-lgbt commented on curriculum/challenges/english/14-responsive-web-design-22/learn-intermediate-css-by-building-a-cat-painting/6676a8b01e56ec1a1e07c202.md
> +
```suggestion
```


My fault, sorry

2024-06-25 15:40 UTC, naomi-lgbt approved these changes
Awesome! Thanks for all your work on this!

**Note to reviewers:** Once this is approved a second time, I'll run + push the i18n sync and merge

2024-07-02 07:33 UTC, Sembauke approved these changes

2024-07-02 07:33 UTC, merged

2024-07-02 07:36 UTC, ilenia-magoni commented
@Sembauke you did not let Naomi do the i18n sync, and now the `main` branch will fail

2024-07-02 10:38 UTC, Sembauke commented
I misunderstood, sorry about that.