fix(curriculum): example code, challenge
freeCodeCamp/freeCodeCamp pull request #55307
Opened 2024-06-24 23:56 UTC by lasjorg

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #50155

The challenge now shows mixins without arguments and with optional arguments.

I used the requirements and tests from [this PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/54657), slightly changing the tests.

---

As an aside, it doesn't seem like we are applying code highlighting for SCSS in the code blocks.

2024-06-25 07:17 UTC, Sembauke requested changes

2024-06-25 07:17 UTC, Sembauke commented on curriculum/challenges/english/03-front-end-development-libraries/sass/create-reusable-css-with-mixins.md
> +Use the `shape` mixin to give the `#square` element a width and height of `50px`, and the color `red`. For the `#rect-a` element a width of `100px`, a height of `50px`, and the color `blue`. Finally,
```suggestion
Use the `shape` mixin to give the `#square` element a width and height of `50px`, and the color `red`. For the `#rect-a` element a width of `100px`, a height of `50px`, and the color `blue`. Finally, for the `#rect-b` element add a width of `50px`, a height of `100px`, and the color `orange`.
```

2024-06-28 08:26 UTC, Sembauke approved these changes

2024-06-28 08:44 UTC, huyenltnguyen approved these changes

2024-06-28 09:13 UTC, merged