fix(curriculum): delineate span elements in typography
freeCodeCamp/freeCodeCamp pull request #55348
Opened 2024-06-27 09:28 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #51786

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/dbb96943-4962-4de2-933d-e77b63089126)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/b3c9bd4d-81ed-4236-827d-38d3563937b1)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/c73b6027-5275-4042-af3e-96cf3444f14a)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/f0fe583f-fc0d-47f8-abf6-3b721374309e)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/2f8aa4d7-c9e0-4da7-b45a-b24a5c1ff8f8)

2024-07-04 19:34 UTC, anishlukk123 commented
please resolve the failing tests

2024-07-05 09:19 UTC, ilenia-magoni commented
@anishlukk123 the failing tests need to be resolved after review. Once the PR is approved, then the new steps can be propagated to other languages

2024-07-18 19:37 UTC, moT01 requested changes
This is looking good @Supravisor 👍 

I left a number of grammar suggestions to try and make things a little more concise, while hopefully providing enough for it to be clear to campers what to do - mainly, how I would have liked to see it written - so it's kind of just my preference. Feel free to bring up any questions or comments on any of them.

2024-07-18 19:37 UTC, moT01 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/667d1bb875f5961913176069.md
> +assert(document.querySelector('.daily-value.small-text')?.lastElementChild?.querySelector('span > span')?.innerText === 'Total Fat');
```suggestion
assert.match(document.querySelector('.daily-value.small-text')?.lastElementChild?.querySelector('span')?.innerHTML, /^<span class=("|')bold\1>Total Fat<\/span> 8g\s?$/);
```

This test wasn't work quite right. It was passing by only checking Total Fat `span`. I came up with this.

2024-07-18 19:37 UTC, moT01 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f7de4487b64919bb4aa5e.md
> +Nest the `Cholesterol` `span` element and the text `0mg` in an additional `span` element for alignment.  This final part will nest a `span` element within a `span` element.
```suggestion
After your last `.divider`, create a new `p` element with the text `Cholesterol 0mg 0%`. Then, wrap the text `Cholesterol` in a `span` element, `0%` in another, and give each of them a class of `bold`.

Finally, nest the `span` element containing the text `Cholesterol` along with the text `0mg`, in an additional `span` element for alignment.
```

2024-07-18 19:37 UTC, moT01 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f7e7281626a92bbd62da8.md
> +As you did in the previous step, this will nest a `span` element within a `span` element.
```suggestion
Below your last `p` element, create another `p` element with the text `Sodium 160mg 7%`. Put `sodium` and `7%` each in their own `span` with a class of a `bold` like you did with the others.

Then, add an additional `span` element around `Sodium 160mg` for alignment again.
```

2024-07-18 19:37 UTC, moT01 commented on curriculum/challenges/english/14-responsive-web-design-22/learn-typography-by-building-a-nutrition-label/615f7ecb09de9a938ef94756.md
> +Also add an additional `span` element around the `Total Carbohydrate 37g` text to have it aligned to the left and `13%` to the right.  Here you will nest a `span` element within a `span` element.
```suggestion
Below your last `p` element, add another `p` element with the text `Total Carbohydrate 37g 13%`. Like before, use `span` elements to make the text `Total Carbohydrate` and `13%` bold. Then, wrap the nutrient and amount in a `span` for alignment again.
```

2024-07-22 19:22 UTC, moT01 approved these changes
LGTM @Supravisor 🎉  Hopefully this is clear enough.

Note, we will need to run a curriculum sync after this is merged.

2024-08-05 07:21 UTC, Sembauke approved these changes

2024-08-05 07:22 UTC, merged

2025-05-26 05:44 UTC, Sergeantkalpesh commented
<img width="959" alt="freecodepng" src="https://github.com/user-attachments/assets/eff7b0c9-0453-415d-bf5e-87f09a87fa95" />