feat: gracefully redirect root path in development only
freeCodeCamp/freeCodeCamp pull request #55403
Opened 2024-07-02 17:44 UTC by naomi-lgbt

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Maybe I'm wrong, maybe this is just a Naomi problem - I won't be offended if we close this.

But I work on apps that use port 3000 quite often. `localhost:3000` is in my history right next to `localhost:8000`. If I click the wrong one, I don't want a 404 page with a flash message. I want the API to read my mind and take me right where I meant to go. :3

2024-07-03 08:16 UTC, ojeytonwilliams requested changes

2024-07-03 08:16 UTC, ojeytonwilliams commented on api-server/src/server/index.js
> +if (process.env.NODE_ENV === 'development') {
```suggestion
if (process.env.FREECODECAMP_NODE_ENV === 'development') {
```
We use this one to differentiate between production and development. NODE_ENV is used that way by other software (like Jest and Express), but this is ours.

2024-07-03 20:40 UTC, ojeytonwilliams approved these changes

2024-07-04 03:52 UTC, raisedadead approved these changes

2024-07-04 03:52 UTC, merged