chore(curriculum): Python Polygon Area Calculator add quotes to string
freeCodeCamp/freeCodeCamp pull request #55433
Opened 2024-07-06 06:22 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #51036

2024-07-08 05:53 UTC, Sembauke approved these changes

2024-07-08 08:53 UTC, huyenltnguyen reviewed
On line 31, `Square(side=9)` should also be wrapped within quotes. And please help add punctuation to the sentence, too.

2024-07-08 16:35 UTC, naomi-lgbt approved these changes

2024-07-08 16:36 UTC, naomi-lgbt requested changes
I lied. Line 31 still isn't updated.

2024-07-10 07:43 UTC, huyenltnguyen approved these changes

2024-07-16 04:42 UTC, naomi-lgbt approved these changes
Whoops! Sorry for letting this one slip through the cracks.

2024-07-16 04:42 UTC, merged