chore(curriculum): Authors Page add quotes to strings
freeCodeCamp/freeCodeCamp pull request #55436
Opened 2024-07-06 10:23 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Related to #51036

2024-07-08 06:07 UTC, Sembauke requested changes

2024-07-08 06:07 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da4b16937be43ba24c63d.md
> +You should use the `fetch()` method to make a `GET` request to `"https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json"`.
```suggestion
You should use the `fetch()` method to make a `GET` request to `"https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json"`.
```

2024-07-08 06:07 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da42481d90c4314c99e94.md
> +You should use the `fetch()` method to make a `GET` request to `'https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json'`.
```suggestion
You should use the `fetch()` method to make a `GET` request to `"https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json"`.
```

2024-07-08 06:07 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da3c6b6fbd742bff6ee40.md
> +You should use the `fetch()` method to make a `GET` request to `'https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json'`.
```suggestion
You should use the `fetch()` method to make a `GET` request to `"https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json"`.
```

2024-07-08 06:07 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da51a9810e74411262fcc.md
> +You should use the `fetch()` method to make a `GET` request to `'https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json'`.
```suggestion
You should use the `fetch()` method to make a `GET` request to `"https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json"`.
```

2024-07-08 16:23 UTC, naomi-lgbt reviewed
Consistency nit.

2024-07-08 16:23 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-fetch-and-promises-by-building-an-fcc-authors-page/641da3c6b6fbd742bff6ee40.md
> +Make a `GET` request to this URL: `'https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json'`. Don't terminate your code with a semicolon yet.
```suggestion
Make a `GET` request to this URL: `"https://cdn.freecodecamp.org/curriculum/news-author-page/authors.json"`. Don't terminate your code with a semicolon yet.
```

2024-07-10 07:41 UTC, huyenltnguyen approved these changes

2024-07-16 04:41 UTC, naomi-lgbt approved these changes

2024-07-16 07:43 UTC, Sembauke approved these changes

2024-07-16 07:43 UTC, merged