fix(curriculum): assert closing form tag
freeCodeCamp/freeCodeCamp pull request #55449
Opened 2024-07-09 10:34 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55384

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/acb2a086-d766-4f3d-9a9f-34f79c3258e9)

2024-07-09 18:37 UTC, gikf approved these changes

2024-07-10 22:31 UTC, lasjorg requested changes

2024-07-10 22:31 UTC, lasjorg commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f5c3e399ff1a05629964e4.md
> +Your `form` element should have a closing tag. Closing tags have a `/` just after the `<` character.
```suggestion
Your `form` element should have a closing tag `</form>`.
```

I know I have seen this hint for closing tags elsewhere, but in my opinion, it is a bit ambiguous, and potentially confusing.

2024-07-10 22:31 UTC, lasjorg commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-forms-by-building-a-registration-form/60f5c3e399ff1a05629964e4.md
> +assert(code.match(/<\/form\>/));
```suggestion
assert.match(code, /<\/form\>/);
```

We should use the assert methods when possible.

2024-07-11 13:21 UTC, lasjorg approved these changes

2024-07-11 13:21 UTC, merged