fix(curriculum): update description regarding switch statement
freeCodeCamp/freeCodeCamp pull request #55450
Opened 2024-07-09 11:54 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55432

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/375bcf22-8dd7-4a24-bf62-04ab489bafe3)

2024-07-09 17:39 UTC, lasjorg requested changes

2024-07-09 17:39 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-modern-javascript-methods-by-building-football-team-cards/63c620161fc2b49ac340ffc4.md
> +In this project, you will build a set of football team cards and learn about nested objects, object destructuring, default parameters, and event listeners. All of the HTML and CSS for this project ha
```suggestion
In this project, you will build a set of football team cards and learn about nested objects, object destructuring, and default parameters. All of the HTML and CSS for this project has been provided for you.
```

Campers have already learned about event listeners. So to be consistent with what we are removing, I think that should go as well.

2024-07-10 16:18 UTC, lasjorg approved these changes

2024-07-10 18:17 UTC, raisedadead approved these changes

2024-07-10 18:17 UTC, merged