chore(curriculum): Statistics Calculator callback function not mandatory
freeCodeCamp/freeCodeCamp pull request #55466
Opened 2024-07-10 11:36 UTC by Supravisor

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54997

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/8ad005df-5fc2-4c71-8ad9-21d492f6482e)

![image](https://github.com/freeCodeCamp/freeCodeCamp/assets/153783117/962dcf56-7e49-47cf-a589-5b036b0e45cc)

2024-07-10 17:06 UTC, lasjorg requested changes
The hint text is wrong now. It should not require a `el` parameter, as that is only when using an anonymous callback function.

As such, we really should also not require a specific parameter name, but any valid identifier. I think we can just use `\w` and ignore that it will match on invalid identifier names, as that will cause a syntax error anyway.

2024-07-10 17:06 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-advanced-array-methods-by-building-a-statistics-calculator/63507c4b63731437227b0134.md
> +assert.match(calculate.toString(), /array\.map\(\s*(\(\s*el\s*\)|el)\s*=>|array\.map\(\s*function\s*\(\s*el\s*\)\s*\{|array\.map\(\s*Number\s*\)/)
```suggestion
assert.match(calculate.toString(), /array\.map\(\s*(\(\s*\w+\s*\)|\w+)\s*=>|array\.map\(\s*function\s*\(\s*\w+\s*\)\s*\{|array\.map\(\s*Number\s*\)/)
```

2024-07-10 17:06 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-advanced-array-methods-by-building-a-statistics-calculator/63507c4b63731437227b0134.md
> +assert.match(calculate.toString(), /Number\(\s*el\s*\)|Number/);
```suggestion
assert.match(calculate.toString(), /Number\(\s*\w+\s*\)|Number/);
```

2024-07-10 17:06 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-advanced-array-methods-by-building-a-statistics-calculator/63507c4b63731437227b0134.md
> +assert.match(calculate.toString(), /(array\.map\(\s*(\(\s*el\s*\)|el)\s*=>|array\.map\(\s*function\s*\(\s*el\s*\)\s*\{)\s*(return\s+)?Number\(\s*el\s*\)|array\.map\(\s*Number\s*\)/);
```suggestion
assert.match(calculate.toString(), /(array\.map\(\s*(\(\s*\w+\s*\)|\w+)\s*=>|array\.map\(\s*function\s*\(\s*\w+\s*\)\s*\{)\s*(return\s+)?Number\(\s*\w+\s*\)|array\.map\(\s*Number\s*\)/);
```

2024-07-11 13:33 UTC, lasjorg approved these changes

2024-07-11 23:41 UTC, jdwilkin4 approved these changes

2024-07-11 23:41 UTC, merged