combine steps
freeCodeCamp/freeCodeCamp pull request #55474
Opened 2024-07-10 21:18 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #55437

2024-07-22 19:26 UTC, moT01 requested changes
This removes two challenges, there should be changes in the meta.json file to go along with that I believe. We have some [helper scripts](https://contribute.freecodecamp.org/how-to-work-on-coding-challenges/#helper-scripts) that I think can help with that.

2024-07-22 21:28 UTC, gagan-bhullar-tech commented
@moT01  update meta.json file

2024-08-05 18:12 UTC, moT01 reviewed
This is looking good @gagan-bhullar-tech 👍 

I found a few more things we should fix up before getting this in.

2024-08-05 18:12 UTC, moT01 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-modern-javascript-methods-by-building-football-team-cards/63cf93472de77d01bf8474bf.md
> +  headCoach: {
The editable region should be moved to surround the `headCoach` object.

2024-08-05 18:12 UTC, moT01 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-modern-javascript-methods-by-building-football-team-cards/63cf90d4696d8f00851873a4.md
> +Your `headCoach` value should be an object.
Kind of minor, but can we add a test or add to this test to make sure the object is empty?

2024-08-06 17:36 UTC, gagan-bhullar-tech commented
@moT01 updated PR. Please review.

2024-08-27 21:14 UTC, moT01 approved these changes
LGTM 🎉

2024-08-29 11:17 UTC, Sembauke approved these changes

2024-08-29 11:17 UTC, merged