feat(api): add update-stripe-card endpoint
freeCodeCamp/freeCodeCamp pull request #55548
Opened 2024-07-17 17:46 UTC by ahmaxed

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-07-18 10:42 UTC, ojeytonwilliams requested changes

2024-07-18 10:42 UTC, ojeytonwilliams commented on api/src/routes/donate.ts
> +      }
```suggestion
    async req => {
      const donation = await fastify.prisma.donation.findFirst({
        where: { userId: req.user?.id }
      });
      if (!donation)
        throw Error(`Stripe donation record not found: ${req.user?.id}`);
      const { customerId, subscriptionId } = donation;
      const session = await stripe.checkout.sessions.create({
        payment_method_types: ['card'],
        mode: 'setup',
        customer: customerId,
        setup_intent_data: {
          metadata: {
            customer_id: customerId,
            subscription_id: subscriptionId
          }
        },
        success_url: `${HOME_LOCATION}/update-stripe-card?session_id={CHECKOUT_SESSION_ID}`,
        cancel_url: `${HOME_LOCATION}/update-stripe-card`
      });
      return { sessionId: session.id } as const;
```
Everything gets a bit simpler if we simply throw any errors. The handler will return `{ message: 'flash.generic-error', type: 'danger' }` and the client handles that the same as any other error response.

2024-07-18 10:42 UTC, ojeytonwilliams commented on api/src/schemas/donate/update-stripe-card.ts
> +  }
```suggestion
    default: genericError
```

2024-07-18 10:42 UTC, ojeytonwilliams commented on api/src/schemas/donate/update-stripe-card.ts
> +import { Type } from '@fastify/type-provider-typebox';
```suggestion
import { Type } from '@fastify/type-provider-typebox';
import { genericError } from '../types';
```

2024-07-18 10:42 UTC, ojeytonwilliams commented on api/src/routes/donate.ts
> +          where: { userId: req.user?.id }
Shouldn't this also check if the `provider` is `stripe`?

2024-07-18 10:53 UTC, ojeytonwilliams commented on api/src/routes/donate.test.ts
> +          message: 'Something went wrong.',
```suggestion
          message: 'flash.generic-error',
```
Sorry, missed this.

2024-07-19 08:48 UTC, ojeytonwilliams approved these changes
Looking good! Just the one nit:

2024-07-19 08:48 UTC, ojeytonwilliams commented on api/src/routes/donate.test.ts
> +        expect(true).toBe(true);
```suggestion
```
:thinking:

2024-08-02 11:27 UTC, ahmaxed commented
Added an empty object.

2024-08-05 23:52 UTC, moT01 approved these changes
LGTM 🎉

2024-08-05 23:52 UTC, merged