fix(curriculum): tests passing with seed code in Music player
freeCodeCamp/freeCodeCamp pull request #55586
Opened 2024-07-21 11:40 UTC by gikf

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

- - -
- Fixes test passing with seed code.

2024-08-08 15:45 UTC, moT01 approved these changes
LGTM 🎉 

Just a side note, spaces are allowed between `.`'s.

2024-08-11 18:09 UTC, gikf commented
> Just a side note, spaces are allowed between `.`'s.

Not sure how that's not coming up often on forums to be honest. Let me know if you'd want me to add them.

But surprise, between `?.` there cannot be space.

2024-08-12 16:59 UTC, moT01 commented
I think it's fine. If it's not coming up on the forum, it's probably not very common. Just thought I would mention it.

2024-08-26 07:44 UTC, Sembauke requested changes

2024-08-26 07:44 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/65a60aa3efd8fa079c2d1537.md
> +You should have second `if` statement inside your callback function.
```suggestion
You should have a second `if` statement inside your callback function.
```

2024-08-26 10:58 UTC, Sembauke approved these changes

2024-08-26 10:58 UTC, merged