fix(curriculum): tests passing with seed code in Role playing game
freeCodeCamp/freeCodeCamp pull request #55580
Opened 2024-07-20 09:14 UTC by gikf

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

- - -
Notes
- Step 1 - browser appears to fix many of the incorrectly defined `html`, `head`, `body`, including the lack of them.
- Step 18 & 29, wanna see _funny_ trick?
  1. Go to any page (not fCC limited, youtube), for example https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-18
  2. Open browser's console.
  3. Type either in browser's console, or in the editor: `console.log(button2)`
  4. See appear the `#button2` element in console.
  5. Try it with other ids with names that could be proper JS variables.
  6. Also see their elements printed in console.
  7. You can be as confused as I am.
- Steps with `pick` function and `if` statements. `pick.toString()` will added infinite loop protection to the loops. This uses `if`, which makes using `pick.toString()` to match `if` less convenient.

2024-08-08 14:57 UTC, moT01 requested changes
Looking good @gikf 👍 

I think you changed the tests on 18 and 29 cause of the funny trick you found. Here's what GPT says:

“In HTML, when you give an element an id, that id becomes a global variable accessible in the JavaScript environment. This is why you can reference button2 directly in your script without declaring a variable.”

But the first test on those steps checks for the variable declaration - e.g. `const button2` which overwrites the global. So I didn't see why they needed to be changed.

2024-08-11 17:34 UTC, gikf commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a7bf06d2ad9d1c5024e833.md
> +assert.match(goStore.toString(), /button1\.onclick/);
In current form this test is not really checking anything - it matches seed code.

What do you think about adding to the hint text something like: _in your `goStore` function_?

2024-08-11 17:42 UTC, gikf commented
> I think you changed the tests on 18 and 29 cause of the funny trick you found. Here's what GPT says:

That's the one!

> But the first test on those steps checks for the variable declaration - e.g. `const button2` which overwrites the global. So I didn't see why they needed to be changed.

It looks slightly like the best case scenario. The worst one is a bit nitpicking, but other test:
```js
assert.match(code, /const\s+button2/);
```
Would of course match `const button2something`. Only related test is changed, but it increases confidence for this one as well.

2024-10-08 14:49 UTC, moT01 approved these changes

2024-10-08 15:01 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-javascript-by-building-a-role-playing-game/62a1166ed9a56d439c0770e7.md
> +assert.equal(document.querySelectorAll('#stats > .stat')?.length, 3);
```suggestion
assert.lengthOf(document.querySelectorAll('#stats > .stat'), 3);
```

2024-10-28 08:36 UTC, ilenia-magoni approved these changes

2024-10-28 08:36 UTC, merged