feat(curriculum): add video compilation lab
freeCodeCamp/freeCodeCamp pull request #55639
Opened 2024-07-24 14:33 UTC by Dario-DC

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-07-29 19:25 UTC, zairahira requested changes

2024-07-29 19:25 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-video-compilation-page/669e81368e52b3a5c35a2dc5.md
> +Each `section` element should contain an `h2` element to give a title to that section as its first child.
This test is always passing.

2024-07-29 19:25 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-video-compilation-page/669e81368e52b3a5c35a2dc5.md
> +Each `section` element should contain a `p` element to introduce the video content as its second child.
Always passing.

2024-07-29 19:25 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-video-compilation-page/669e81368e52b3a5c35a2dc5.md
> +Each `section` element should contain an `iframe` element as its third child.
Always passing.

2024-07-30 07:25 UTC, Dario-DC commented
Those three tests should work properly now @zairahira

2024-08-02 12:42 UTC, zairahira approved these changes

2024-08-08 21:14 UTC, moT01 reviewed
LGTM after conflicts fixed and title adjusted 👍

2024-08-08 21:14 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +        "title": "Video Compilation Page",
```suggestion
        "title": "Build a Video Compilation Page",
```

2024-08-08 21:14 UTC, moT01 commented on curriculum/challenges/_meta/lab-video-compilation-page/meta.json
> +  "name": "Video Compilation Page",
```suggestion
  "name": "Build a Video Compilation Page",
```

2024-08-12 15:09 UTC, moT01 approved these changes

2024-08-12 15:09 UTC, merged