feat(curriculum): add travel agency page lab
freeCodeCamp/freeCodeCamp pull request #55633
Opened 2024-07-24 12:24 UTC by Dario-DC

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-07-31 08:12 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +Both your list items should contain an anchor element.
This test is passing without code.

2024-07-31 08:12 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +Each `figure` element should contain an anchor element as its first child.
Tests from here onwards are always passing.

2024-07-31 13:15 UTC, Dario-DC commented
Tests should work now @zairahira

2024-08-01 14:56 UTC, zairahira approved these changes
The tests are working as expected 👍️

2024-08-08 20:55 UTC, moT01 requested changes
This looks good @Dario-DC 👍 I left a few suggestions to adjust the block name. Other than that, I would be fine getting this in. I do think it could be a little better by having even more flexibility in what users can use for the content. Instead of forcing certain text, let them choose - but there's a numbers of things where they aren't forced to use specific text, so there's a decent amount of flexibility 👍

2024-08-08 20:55 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +        "title": "Travel Agency Page",
```suggestion
        "title": "Build a Travel Agency Page",
```

2024-08-08 20:55 UTC, moT01 commented on curriculum/challenges/_meta/lab-travel-agency-page/meta.json
> +  "name": "Travel Agency Page",
```suggestion
  "name": "Build a Travel Agency Page",
```

2024-08-09 14:16 UTC, Dario-DC commented
Title and merge conflicts are fixed. @moT01 If you think there's not enough flexibility I can change a couple of user stories.

2024-08-12 17:00 UTC, moT01 approved these changes
LGTM 🎉

2024-08-12 17:00 UTC, merged