Submit button text
freeCodeCamp/freeCodeCamp pull request #55631
Opened 2024-07-24 02:30 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55627

2024-07-24 16:00 UTC, a2937 commented
This does look pretty good, although I think a test should be added to ensure that the correct words are displaying depending on the browser type.

2024-07-25 00:22 UTC, gagan-bhullar-tech commented
@a2937 added test case

2024-07-25 15:21 UTC, lasjorg requested changes
I would prefer if your code used the same syntax as the other button code in the file. It is just less confusing to read if they are both written the same way.

2024-07-25 15:39 UTC, lasjorg reviewed
@gagan-bhullar-tech I forgot to mention it, but can you also move it up, so the code for the two buttons are one after the other.

So before

`const showSignInButton = !isSignedIn && challengeIsCompleted;`

2024-07-25 16:53 UTC, lasjorg requested changes

2024-07-25 16:53 UTC, lasjorg commented on client/src/templates/Challenges/classic/lower-jaw.tsx
> +    : t('buttons.submit-and-go-2');
```suggestion
      : t('buttons.submit-and-go-2')
    : t('buttons.submit-and-go');
```

Sorry, the properties are apparently switched for the submit button text.

I might open a PR after this is merged to give them better names and make sure the default is consistent.

2024-07-25 17:28 UTC, lasjorg approved these changes
LGTM.

I can't test it on Mac, but I see no reason why it wouldn't work.

2024-07-28 21:58 UTC, naomi-lgbt approved these changes

2024-07-28 21:58 UTC, merged