refactor(client): clean up gatsby-node
freeCodeCamp/freeCodeCamp pull request #55640
Opened 2024-07-24 15:06 UTC by ojeytonwilliams

- **refactor: remove unused fields from query**
- **refactor: use async await**

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

The graphql query in createPages was getting a bunch of things it didn't need.

2024-07-25 08:04 UTC, ShaunSHamilton requested changes
1) I suspect this will break the dolt stuff we have, but this is not a big deal for now.
2) Whilst in the neighbourhood, I would like to move the stuff that does not throw out of the `try`

2024-07-25 08:04 UTC, ShaunSHamilton commented on client/gatsby-node.js
> +    } catch (e) {
```suggestion
    if (nodeIdentity === 'blockIntroMarkdown') {
      if (!blocks.includes(frontmatter.block)) {
        return;
      }
    } else if (!superBlocks.includes(frontmatter.superBlock)) {
      return;
    }

    try {
      const pageBuilder = createByIdentityMap[nodeIdentity](createPage);
      pageBuilder(edge);
    } catch (e) {
```

2024-07-25 11:11 UTC, ShaunSHamilton approved these changes
LTM 👍

2024-08-02 08:29 UTC, Sembauke approved these changes

2024-08-02 08:29 UTC, merged