feat: explain multiple parameters, address hardcoding
freeCodeCamp/freeCodeCamp pull request #55665
Opened 2024-07-25 17:32 UTC by naomi-lgbt

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-07-25 18:56 UTC, gikf commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/66643c93e05093c728abdbe9.md
> +This function would return `"Hello"` regardless of the value passed to `arg`, so `"Hello"` is consered hard-coded.
```suggestion
This function would return `"Hello"` regardless of the value passed to `arg1`, or `arg2`, so `"Hello"` is considered hard-coded.
```

2024-07-25 23:58 UTC, lasjorg commented
For the hardcoded function return, I would suggest having a function call to show the unused arguments. It could also help reinforce the connection between parameters and arguments.

For example:

This function would return `"John Doe"` regardless of the arguments passed to the parameters `firstName`, and `lastName`, so `"John Doe"` is considered a hard-coded value.

```
function sayName(firstName, lastName) {
  return "John Doe"
}

sayName("Camper", "Cat");
```

2024-07-29 03:58 UTC, gikf approved these changes

2024-07-29 16:44 UTC, lasjorg requested changes

2024-07-29 16:44 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/66643c93e05093c728abdbe9.md
> +  return "John Doe"
```suggestion
  return "John Doe";
```

Sorry, that is my bad. Let's not skip semicolons in our example code.

2024-07-29 18:14 UTC, lasjorg approved these changes

2024-07-29 18:14 UTC, merged