fix(curriculum): new step for empty title bug
freeCodeCamp/freeCodeCamp pull request #55730
Opened 2024-08-02 18:27 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #54588

2024-08-05 17:06 UTC, naomi-lgbt requested changes

2024-08-05 17:06 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +If you try to add a new task, add space in title field and then click on the `Add New Task` button, you will notice a bug.
```suggestion
If you try to add a new task, add a single space in title field, and click on the `Add New Task` button, you will notice a bug.
```

2024-08-05 17:06 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +Empty task will be created even though title field is required. To fix this, you need add an `if` condition checking for empty title field value.
```suggestion
An empty task will be created even though title field is required. To fix this, you need add an `if` condition checking for a value that would appear empty.
```

2024-08-05 17:06 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +console.log(code)
```suggestion
```

2024-09-01 16:59 UTC, ilenia-magoni requested changes
Can you please adjust these sentences

2024-09-01 16:59 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +An empty task will be created even though title field is required. To fix this, you need add an `if` condition checking for a value that would appear empty.
```suggestion
An empty task will be created even though the title field is required. To fix this, you need to add an `if` condition checking for a value that would appear empty.
```

2024-09-01 16:59 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +If you try to add a new task, add a single space in title field, and click on the `Add New Task` button, you will notice a bug.
```suggestion
If you try to add a new task, write single space in title field, and click on the `Add New Task` button, you will notice a bug.
```

2024-09-01 20:56 UTC, gagan-bhullar-tech commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +An empty task will be created even though title field is required. To fix this, you need add an `if` condition checking for a value that would appear empty.
review comments

2024-09-04 08:10 UTC, ilenia-magoni approved these changes
LGTM 👍

2024-09-12 20:27 UTC, moT01 reviewed
I don't think the description explains enough for users to be able to complete this. The only way they will know what code to write is by looking at the hints. If the test is going to require using certain code or methods, we need to explain that in the description.

2024-09-13 02:50 UTC, gagan-bhullar-tech commented
@moT01 can you please let me know what should be the description in that case.

2024-09-26 16:47 UTC, moT01 requested changes
Sorry for the delay @gagan-bhullar-tech. I left a comment with a new description. Let me know if you have any suggestions for improvements on it. Also found a few minor things that weren't needed in the regex tests.

2024-09-26 16:47 UTC, moT01 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +An empty task will be created even though the title field is required. To fix this, you need to add an `if` condition checking for a value that would appear empty.
```suggestion
Finally, there's one bug to fix. If you create a task with only spaces for the title, an empty task will be created even though the title is required.

Fix that by adding a check at the beginning of the function for if `!titleInput.value.trim()`. If there's no title, show an alert with the text `Please provide a title` and `return` after that.
```

2024-09-26 16:47 UTC, moT01 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +assert.match(code, /if\s*\(\s*!titleInput\.value\.trim\(\s*\)\s*\)\s*\{\s*\s*alert\s*\(\s*('|"|`)Please provide a title\1\s*\)\s*/)
```suggestion
assert.match(code, /if\s*\(\s*!titleInput\.value\.trim\(\s*\)\s*\)\s*\{\s*alert\s*\(\s*('|"|`)Please provide a title\1\s*\)\s*/)
```

2024-09-26 16:47 UTC, moT01 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-localstorage-by-building-a-todo-app/66ad0f178ed5791ed898fe56.md
> +assert.match(code, /if\s*\(\s*!titleInput\.value\.trim\(\s*\)\s*\)\s*\{\s*\s*alert\s*\(\s*('|"|`)Please provide a title\1\s*\)\s*;?\s*return\s*;?\s*\}/);
```suggestion
assert.match(code, /if\s*\(\s*!titleInput\.value\.trim\(\s*\)\s*\)\s*\{\s*alert\s*\(\s*('|"|`)Please provide a title\1\s*\)\s*;?\s*return\s*;?\s*\}/);
```

2024-09-27 01:46 UTC, gagan-bhullar-tech commented
@moT01 thanks. Updated PR.

2024-10-08 14:55 UTC, moT01 approved these changes

2024-10-09 05:04 UTC, naomi-lgbt approved these changes
Apologies for leaving this blocked.

2024-10-09 05:04 UTC, merged