fix(curriculum): update calorie counter step 77 to not allow extra addition
freeCodeCamp/freeCodeCamp pull request #55842
Opened 2024-08-13 14:35 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #55840

The best way I thought of to resolve the issue is to simply make sure the line of code ends where it is supposed to with a semi-colon.

2024-08-13 19:16 UTC, lasjorg commented
You should be able to use `$` with the `m` flag.

---
````md
You should calculate the sum of `breakfastCalories`, `lunchCalories`, `dinnerCalories`, and `snacksCalories`, in order.

```js
assert.match(calculateCalories.toString(), /breakfastCalories\s*\+\s*lunchCalories\s*\+\s*dinnerCalories\s*\+\s*snacksCalories;?$/m);
```

You should assign the sum of `breakfastCalories`, `lunchCalories`, `dinnerCalories`, and `snacksCalories` to `consumedCalories`.

```js
assert.match(calculateCalories.toString(), /consumedCalories\s*=\s*breakfastCalories\s*\+\s*lunchCalories\s*\+\s*dinnerCalories\s*\+\s*snacksCalories;?$/m);
```
````

2024-08-13 21:10 UTC, lasjorg requested changes

2024-08-13 21:10 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9e4d2ff41811dd640504f.md
>  assert.match(calculateCalories.toString(), /consumedCalories\s*=\s*breakfastCalories\s*\+\s*lunchCalories\s*\+\s*dinnerCalories\s*\+\s*snacksCalories/);
```suggestion
assert.match(calculateCalories.toString(), /consumedCalories\s*=\s*breakfastCalories\s*\+\s*lunchCalories\s*\+\s*dinnerCalories\s*\+\s*snacksCalories;?$/m);
```

2024-08-13 21:10 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9e4d2ff41811dd640504f.md
>  assert.match(calculateCalories.toString(), /consumedCalories\s*=\s*breakfastCalories\s*\+\s*lunchCalories\s*\+\s*dinnerCalories\s*\+\s*snacksCalories/);
Might as well do the same here.

2024-08-13 21:10 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9e4d2ff41811dd640504f.md
> +
```suggestion
```

The semicolon is optional `;?`

So we shouldn't need this test.

2024-08-14 14:02 UTC, lasjorg approved these changes

2024-08-14 22:08 UTC, a2937 commented
Hey, regarding this https://github.com/freeCodeCamp/freeCodeCamp/issues/53694? 

Am I making this problem worse? I mean it's literally the only thing I could come up with at the time.

2024-08-15 14:58 UTC, lasjorg commented
Not sure I understand the question.

The tests in this PR do not require semicolons. But if it had, that would have been a questionable solution. Semicolons should be optional, unless specifically chosen not to be for some educational reason.

2024-08-15 15:36 UTC, a2937 commented
I think I just got confused about what the issue was about. You see for campers to pass these tests, they're going to need to insert semi-colons as that's how we can safely cut off content. 

I thought the issue meant that we should either enforce campers to consistently use semi-colons or not be strict about it.

2024-08-15 16:19 UTC, lasjorg commented
> You see for campers to pass these tests, they're going to need to insert semi-colons as that's how we can safely cut off content.

The tests in this PR do not rely on semicolons, they are optional.

---

The issue you linked to is about semicolons in general. How we teach them, when to require them, etc.

2024-08-15 17:28 UTC, gikf approved these changes

2024-08-15 17:40 UTC, merged

2024-08-15 18:11 UTC, lasjorg commented
@gikf I was going to add something like that, but then I seemed to remember having tested it so I tested it again and the regex already supported the optional spaces.

In any case, having it explicit in the regex is probably a good idea. I just wanted to mention it because it caught me by surprise as well.

2024-08-15 18:20 UTC, gikf commented
@lasjorg Do you mean with latest changes, or before?

2024-08-15 20:43 UTC, lasjorg commented
Before.

![spaces-oldregex](https://github.com/user-attachments/assets/2ac98290-471a-445f-8a47-a42bf3649ff2)

2024-08-16 08:29 UTC, gikf commented
@lasjorg Ah! It's the `calculateCalories.toString()` that's cleaning it up.