chore(curriculum): add newspaper article lab
freeCodeCamp/freeCodeCamp pull request #55844
Opened 2024-08-13 18:28 UTC by moT01

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-08-20 11:07 UTC, Dario-DC reviewed
I left a couple of comments. Other than that it looks good to me :+1:

2024-08-20 13:34 UTC, moT01 commented
Thanks for taking a look @Dario-DC - I added your suggestions 👍

2024-08-27 13:27 UTC, Sembauke requested changes

2024-08-27 13:27 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. Within your `.newspaper` element, you should have at least seven more elements: one for the newspaper name that has a class of `name`, one for the the date of the article with a class of `date`, o
```suggestion
1. Within your `.newspaper` element, you should have at least seven more elements: one for the newspaper name that has a class of `name`, one for the date of the article with a class of `date`, one for the headline with a class of `headline`, one for the sub-headline with a class of `sub-headline`, one for the author with a class of `author`, and two paragraphs each with a class of `text`. All of these elements should be filled with your article information.
```

2024-08-27 13:37 UTC, Sembauke requested changes

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. You should have an element with a class of `newspaper` that contains all your other elements.
```suggestion
1. You should have an element with a class of `.newspaper` that contains all your other elements.
```

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. Your `.name` element should have a `font-size` that's two times the size of the root elements `font-size` and a font of `Times New Roman` with a fallback font of `serif`.
```suggestion
1. Your `.name` element should have a `font-size` that is twice the root element's `font-size` and should use the `Times New Roman` font, with a fallback font of `serif`.
```

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. Your `.name` and `.author` elements should use CSS to make all its characters uppercase.
```suggestion
1. Your `.name` and `.author` elements should use CSS to make all their characters uppercase.
```

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. Your `.headline` element should `font-size` that's two times the size of its parent's `font-size` and use CSS to make it bold.
```suggestion
1. Your `.headline` element should have a `font-size` that is twice its parent element's `font-size` and should be bold.
```

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. Your `.sub-headline` element should have a `font-weight` of `100`, a `font-size` that's `1.5` times the size of its parent's `font-size`, and use CSS to make it italicized.
```suggestion
1. Your `.sub-headline` element should have a `font-weight` of `100`, a `font-size` that is `1.5` times its parent element's `font-size`, and should be italicized.
```

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. Your `.text` elements should be indented `20px`.
```suggestion
1. Your `.text` elements should have a `text-indent` of `20px`.
```

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. Your `.text` elements should have a `line-height` that's two times the size of its parent's `font-size`.
```suggestion
1. Your `.text` elements should have a `line-height` that is twice their parent element's `font-size`.
```

2024-08-27 13:37 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-newspaper-article/66ba762af611169359d9d369.md
> +1. The first letter of your `.text` elements should be bold and two times the size of its parent's `font-size`. Hint: use the `::first-letter` selector.
```suggestion
1. The first letter of your `.text` elements should be bold and twice the size of their parent element's `font-size`. Use the `::first-letter` selector for this.
```

2024-08-27 14:39 UTC, Sembauke approved these changes

2024-08-28 12:17 UTC, Dario-DC approved these changes
LGTM :+1:

2024-08-28 12:17 UTC, merged