feat(curriculum): adding teacher bot workshop
freeCodeCamp/freeCodeCamp pull request #55870
Opened 2024-08-15 05:53 UTC by jdwilkin4

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-08-20 07:14 UTC, Sembauke requested changes

2024-08-20 07:14 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-teacher-chatbot/66b59829dba144ff1351220f.md
> +Then using template literal syntax, assign a string that says `My name is` followed by the `botName` variable followed by a period (`.`).
```suggestion
Next, using template literal syntax, assign a string that says `My name is`, followed by the `botName` variable, and ending with a period (`.`).
```

2024-08-20 07:14 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-teacher-chatbot/66b59b12a745e10011158f7b.md
> +The next step is to create a few more variables that you will use in future bot messages.
```suggestion
The next step is to create a few more variables that will be used in future bot messages.
```

2024-08-20 07:14 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-teacher-chatbot/66b59be6ab830800c4df9146.md
> +Now it is time to use the variables you created in the previous step.
```suggestion
Now, it's time to use the variables you created in the previous step.
```

2024-08-20 07:14 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-teacher-chatbot/66b6e62423e8a031d6c1f03d.md
> +Remember to replace `[topic]` with the `topic` variable and use proper template literal syntax like you did in the previous steps.
```suggestion
Remember to replace `[topic]` with the `topic` variable, and use proper template literal syntax as you did in the previous steps.
```

2024-08-21 10:13 UTC, Ksound22 commented on curriculum/challenges/english/25-front-end-development/workshop-teacher-chatbot/66b6fdb76441c738719039fa.md
> +In the lecture videos you learned how to access the last character in a string like this:
```suggestion
In the lecture videos, you learned how to access the last character in a string like this:
```

2024-08-21 10:16 UTC, Ksound22 commented on curriculum/challenges/english/25-front-end-development/workshop-teacher-chatbot/66b70b8a611cbf3bcc5c6c5f.md
> +In the previous lecture videos you learned how to work with the `indexOf` method like this:
```suggestion
In the previous lecture videos, you learned how to work with the `indexOf` method like this:
```

2024-08-21 10:18 UTC, Ksound22 approved these changes
Things are good, other than a few nitpicks with commas.

2024-08-22 08:04 UTC, Sembauke approved these changes

2024-08-22 08:04 UTC, merged