feat: add favourite icon toggler lab
freeCodeCamp/freeCodeCamp pull request #55885
Opened 2024-08-17 08:09 UTC by zairahira

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-08-29 16:14 UTC, Dario-DC commented on curriculum/challenges/english/25-front-end-development/lab-favourite-icon-toggler/66bf6bacf178eac7b96d4f5e.md
> +const inputs = document.querySelectorAll('ul li span.favorite-icon');
```suggestion
const inputs = document.querySelectorAll('ul li span.favorite-icon');
assert(inputs.length)
```
When `inputs` is empty the for..of loop does not run. Therefore the test does not fail.

2024-09-13 13:31 UTC, jdwilkin4 reviewed
It also looks like some of the tests are failing too

2024-09-13 13:31 UTC, jdwilkin4 commented on curriculum/challenges/english/25-front-end-development/lab-favourite-icon-toggler/66bf6bacf178eac7b96d4f5e.md
> +In this lab you will use javascript click events to toggle the appearance of a favorite icon. When the heart icon is clicked, the appearance of the heart changes from empty to filled, and vice versa.
```suggestion
In this lab you will use JavaScript click events to toggle the appearance of a favorite icon. When the heart icon is clicked, the appearance of the heart changes from empty to filled, and vice versa.
```

2024-09-16 16:01 UTC, jdwilkin4 approved these changes

2024-09-16 18:03 UTC, moT01 requested changes
This is a fun one @zairahira 👍 

I left a few suggestions below. Additionally, I think you should change all the "favourite"'s, to "favorite"'s - including for the filenames.

Lastly, you could add one more user story and test for something like "Your `filled` class should change the `color` of the content with that class." Or "...should change it to red..."

2024-09-17 10:19 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-favourite-icon-toggler/66bf6bacf178eac7b96d4f5e.md
> +5. When the `span` element containing the heart is clicked, the class `filled` should be added to the `span` with class `favorite-icon` if it doesn't exist, and removed if it does.  `&#9825;` should
How about this:

5. When a `span` element containing a heart is clicked, you should add the `filled` class to the clicked `span` if it's not already present, and remove it if it is.

6. When a `span` element containing a heart is clicked, the heart symbol should toggle between `&#9825;` (empty heart) and `&#10084;` (filled heart), depending on its current state.

2024-09-17 10:26 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-favourite-icon-toggler/66bf6bacf178eac7b96d4f5e.md
> +3. The three list items should contain the item name followed by a `span` element with the class `favorite-icon` and an id of `favorite-icon-1`, `favorite-icon-2`, and `favorite-icon-3`, respectively
I would agree, those IDs aren't being used anywhere.
I have removed them from the instruction and the tests.

2024-09-18 12:53 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/lab-favourite-icon-toggler/66bf6bacf178eac7b96d4f5e.md
> +5. When the `span` element containing the heart is clicked, the class `filled` should be added to the `span` with class `favorite-icon` if it doesn't exist, and removed if it does.  `&#9825;` should
Yea, that would work better I think.

2024-09-20 10:33 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-favourite-icon-toggler/66bf6bacf178eac7b96d4f5e.md
> +5. When the `span` element containing the heart is clicked, the class `filled` should be added to the `span` with class `favorite-icon` if it doesn't exist, and removed if it does.  `&#9825;` should
@moT01 
I have updated these 2 stories.

Also, the `filled` class is just being used in script logic to identify whether the icon is filled or not. It's not adding a colour or any other style. The icon `&#10084` is already a filled black heart. So, it shouldn't need a separate user story.

2024-09-23 20:12 UTC, moT01 requested changes
noticed a couple more

Also, looks like there's some conflicts. And it looks like the order on the sheet changed to 190 - so we need to change that in the meta.json file and where the info is in the intro.json file if needed.

2024-09-23 20:12 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/lab-favorite-icon-toggler/66bf6bacf178eac7b96d4f5e.md
> +title: Build a Favourite Icon Toggler
```suggestion
title: Build a Favorite Icon Toggler
```

2024-09-23 20:12 UTC, moT01 commented on curriculum/challenges/_meta/lab-favorite-icon-toggler/meta.json
> +  "challengeOrder": [{ "id": "66bf6bacf178eac7b96d4f5e", "title": "Build a Favourite Icon Toggler" }],
```suggestion
  "challengeOrder": [{ "id": "66bf6bacf178eac7b96d4f5e", "title": "Build a Favorite Icon Toggler" }],
```

2024-09-23 20:12 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +        "title": "Build a Favourite Icon Toggler",
```suggestion
        "title": "Build a Favorite Icon Toggler",
```

2024-09-23 20:12 UTC, moT01 commented on client/src/pages/learn/front-end-development/lab-favorite-icon-toggler/index.md
> +title: Introduction to the Build a Favourite Icon Toggler
```suggestion
title: Introduction to the Build a Favorite Icon Toggler
```

2024-09-23 20:12 UTC, moT01 commented on curriculum/challenges/_meta/lab-favorite-icon-toggler/meta.json
> +  "name": "Build a Favourite Icon Toggler",
```suggestion
  "name": "Build a Favorite Icon Toggler",
```

2024-09-24 13:44 UTC, moT01 approved these changes
LGTM 🎉

2024-09-24 13:44 UTC, merged