fix(curriculum) : update head step 4
freeCodeCamp/freeCodeCamp pull request #55882
Opened 2024-08-16 17:45 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

As mentioned in https://github.com/freeCodeCamp/freeCodeCamp/pull/55871#issuecomment-2293607745, the tests needed updating so I updated them.

2024-08-16 18:19 UTC, lasjorg commented
Thanks for updating this.

Full disclosure, the reason why I never updated this challenge is because the regex I was using might have some issues (might be catastrophic backtracking). If you remove the closing `</head>` tag and run the tests it can lock up.

I was going to update the tests with something better but never got around to it. I'm still not sure what the best solution is but it might be that we have to match on the specific elements and not `(?:.|\s*)*?`


Example of code that causes issues with the regex
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>City Skyline</title>
    <link rel="stylesheet" href="styles.css">
  <body>
  </body>
</html>
```

2024-08-22 20:57 UTC, lasjorg requested changes
This should work and avoid the issue the old regex had.

2024-08-22 20:57 UTC, lasjorg commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98cc.md
> +const headContentRegex = /(?<=<head\s*>)(?:.|\s*)*?(?=<\/head\s*>)/;
```suggestion
const headContentRegex = /(?<=<head\s*>)[\S|\s]*(?=<\/head\s*>)/;
```

2024-08-22 20:57 UTC, lasjorg commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98cc.md
> +const headContentRegex = /(?<=<head\s*>)(?:.|\s*)*?(?=<\/head\s*>)/;
```suggestion
const headContentRegex = /(?<=<head\s*>)[\S|\s]*(?=<\/head\s*>)/;
```

2024-08-22 20:57 UTC, lasjorg commented on curriculum/challenges/english/14-responsive-web-design-22/learn-css-variables-by-building-a-city-skyline/5d822fd413a79914d39e98cc.md
> +const headContentRegex = /(?<=<head\s*>)(?:.|\s*)*?(?=<\/head\s*>)/;
```suggestion
const headContentRegex = /(?<=<head\s*>)[\S|\s]*(?=<\/head\s*>)/;
```

2024-08-23 12:27 UTC, lasjorg approved these changes
LGTM

2024-08-26 06:46 UTC, Sembauke approved these changes

2024-08-26 06:46 UTC, merged