fix closing editor panes
freeCodeCamp/freeCodeCamp pull request #55920
Opened 2024-08-22 11:49 UTC by Inventoris

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55864

Hi! I looked into the issue and noticed that when saving the code, createFiles is executed, in which visibleEditors is set to one main tab by default. I added code so that if state.visibleEditors contains current tabs at the time createFiles is launched, then visibleEditors will contain exactly them.

2024-08-22 18:20 UTC, gikf commented on client/src/templates/Challenges/redux/index.js
> +      };
```suggestion
      }
```
This semicolon is cause of the CI error.

2024-08-26 07:42 UTC, Sembauke approved these changes
Tested locally, works like a charm.

2024-09-02 08:46 UTC, ojeytonwilliams requested changes
Hi @Inventoris, thanks for taking the time to fix this. However, I think the root of the problem is that the `createFiles` action has too many jobs - it should put the challenge files in the redux store and nothing else.

If we do that, and update the ui via another action (`initVisibleEditors`, say), there's no need for any conditionals in the reducer and no chance of weird interactions.

2024-09-10 08:35 UTC, ojeytonwilliams approved these changes
Perfect. Thanks, @Inventoris

LGTM :+1:

2024-09-10 08:36 UTC, merged