feat(Curriculum) Add tasks B1 Block 3
freeCodeCamp/freeCodeCamp pull request #55932
Opened 2024-08-23 22:10 UTC by nieldakarla

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-11-27 13:41 UTC, anastasiiauk requested changes
Most of these changes are changing apostrophe, correcting the right answer, or changing the example structure.

2024-11-27 13:41 UTC, anastasiiauk commented on curriculum/challenges/_meta/learn-how-to-talk-about-past-activities/meta.json
> +      "title": "Dialogue 2 Post-Development Review"
```suggestion
      "title": "Dialogue 2: Post-Development Review"
```

2024-11-27 13:41 UTC, anastasiiauk commented on curriculum/challenges/english/24-b1-english-for-developers/learn-how-to-talk-about-past-activities/66df70abe410a681d7868729.md
> +`keep up`, `across`, `just`,  `since`, `yet`, `already`, `any`, and `roll out`.
```suggestion
`keep up`, `across`, `just`, `since`, `yet`, `already`, `any`, and `roll out`.
```

2024-11-27 13:41 UTC, anastasiiauk commented on curriculum/challenges/english/24-b1-english-for-developers/learn-how-to-talk-about-past-activities/66df70abe410a681d7868729.md
> +
```suggestion
```
There's no blank for `yet` in this part.

2024-11-27 13:41 UTC, anastasiiauk commented on curriculum/challenges/english/24-b1-english-for-developers/learn-how-to-talk-about-past-activities/66df70abe410a681d7868729.md
> +`Linda: I believe we can BLANK another update by next month. We've BLANK started working on the fixes.`
```suggestion
`Linda: I believe we can BLANK another update by next month. We've already started working on the fixes.`
```
The dialogue uses two blanks for `already`.

2024-11-27 13:41 UTC, anastasiiauk commented on curriculum/challenges/english/24-b1-english-for-developers/learn-how-to-talk-about-past-activities/66df70abe410a681d7868729.md
> +
```suggestion
```
There's no blank for `already` in this part.

2024-11-29 13:37 UTC, nieldakarla commented on curriculum/challenges/english/24-b1-english-for-developers/learn-how-to-talk-about-past-activities/673258f20e446069d7bc6c4e.md
> +- `Before this, I hadn't focused much on the user experience aspect of development` shows that his attention to user experience is new, meaning he did not focus on it in the past but has started doin
Agreed

2024-12-03 13:15 UTC, anastasiiauk approved these changes

2024-12-03 14:17 UTC, Sembauke approved these changes
I could not find any errors 👍

2024-12-03 14:24 UTC, merged