refactor(client/challenge views): extract items into sharable components
freeCodeCamp/freeCodeCamp pull request #55946
Opened 2024-08-26 19:31 UTC by moT01

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-08-29 10:16 UTC, Sembauke commented
I would love this.

2024-09-02 13:07 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/assignments.tsx
> +              }
False positive, we can ignore this.

2024-09-02 13:36 UTC, ojeytonwilliams requested changes

2024-09-03 13:46 UTC, moT01 commented on client/src/templates/Challenges/components/assignments.tsx
> +      <ChallengeHeading heading={t('learn.assignments')} />
This was pre-existing, so I think it's a little outside the scope of this PR - I would prefer to leave it here. I plan on some more refactoring of these, so I can potentially try to change it in another PR. Also, I don't know if I like either of those any better - what about `featureHeading` or `challengeTaskHeading` or something? To be clear, they are these headings in the challenges:

<details><summary>image</summary>

<img width="717" alt="Screenshot 2024-09-03 at 8 26 07 AM" src="https://github.com/user-attachments/assets/d86645ef-3dbc-4c39-95f3-4014bd925206">

</details>

2024-09-03 19:36 UTC, moT01 commented on client/src/templates/Challenges/fill-in-the-blank/show.tsx
> -    return `last-code-tag`;
✅

2024-09-03 19:36 UTC, moT01 commented on client/src/templates/Challenges/components/fill-in-the-blanks.tsx
> +                      size={blankAnswers[value as unknown as number].length}
✅

2024-09-03 19:36 UTC, moT01 commented on client/src/templates/Challenges/components/fill-in-the-blanks.tsx
> +                        value as unknown as number
✅

2024-09-03 19:36 UTC, moT01 commented on client/src/templates/Challenges/components/fill-in-the-blanks.tsx
> +                      }
✅

2024-09-04 09:32 UTC, ojeytonwilliams commented on client/src/templates/Challenges/components/assignments.tsx
> +      <ChallengeHeading heading={t('learn.assignments')} />
No worries, it's not urgent.

As for what to call them, it's just that they don't have anything to do with challenges beyond the fact they're used there. Not a big deal, obviously.

2024-09-04 09:33 UTC, ojeytonwilliams approved these changes
LGTM 👍

2024-09-06 10:16 UTC, Sembauke approved these changes

2024-09-06 10:16 UTC, merged