feat(curriculum): add functions calculator workshop
freeCodeCamp/freeCodeCamp pull request #55949
Opened 2024-08-27 17:01 UTC by jdwilkin4

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-08-29 06:48 UTC, Sembauke requested changes

2024-08-29 06:48 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-calculator-app/66cc0a9e06e00b75d6782be9.md
> +Add a `console.log` and inside that `console.log` call the `addTwoAndSeven` function.
```suggestion
Add a `console.log` statement, and inside it, call the `addTwoAndSeven` function.
```

2024-08-29 06:48 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-calculator-app/66cc0de2920bec775f610424.md
> +In the next step, you will review how to work with function parameters and arguments.
```suggestion
In the next step, you will review how to work with parameters and arguments in functions.
```

2024-08-29 06:48 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-calculator-app/66cc12fa504b0479dac479a0.md
> +The advantage of functions is that they can be called with different arguments. This allows you to reuse the same code with different values.
```suggestion
The advantage of functions is that they can be called with different arguments, allowing you to reuse the same code with various values.
```

2024-08-29 06:48 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-calculator-app/66cc14ca14e65e7a9ebecb80.md
> +Inside the function, return the difference of the two parameters.
```suggestion
Inside the function, return the difference between the two parameters.
```

2024-08-29 06:48 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-calculator-app/66cc14ca14e65e7a9ebecb80.md
> +Your `calculateDifference` function should return the difference of the two parameters.
```suggestion
Your `calculateDifference` function should return the difference between the two parameters.
```

2024-08-30 05:26 UTC, Sembauke approved these changes

2024-08-30 14:21 UTC, moT01 reviewed
Nicely done @jdwilkin4 🎉 

Only suggestion I have would be to remove "app" from the dashed names.

2024-08-30 16:09 UTC, moT01 approved these changes

2024-08-30 16:09 UTC, merged