fix(curriculum): Merge Sort algorithm step 10 requires spaces to pass
freeCodeCamp/freeCodeCamp pull request #55980
Opened 2024-08-31 11:54 UTC by subhadipjana866

This pull request fixes the issue number #55977 by adding /s* in the regular expressions.  The issue is fixed.

Fix #55977

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-09-02 19:15 UTC, lasjorg requested changes
I know you didn't write it, but I don't understand the negative look ahead. It makes the optional space required (as far as I can tell).

Considering identifiers without an assignment is valid syntax, but an assignment without a value isn't, wouldn't it make more sense to just have the first regex for each identifier only look for the identifier?

2024-09-02 19:15 UTC, lasjorg commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/656680b0fc79f2c38a34d90e.md
> +    assert.match(function_body, /left_array_index\s*(?!=)\s*/);
```suggestion
    assert.match(function_body, /left_array_index/);
```

2024-09-02 19:15 UTC, lasjorg commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/656680b0fc79f2c38a34d90e.md
> +    assert.match(function_body, /right_array_index\s*(?!=)\s*/);
```suggestion
    assert.match(function_body, /right_array_index/);
```

2024-09-02 19:15 UTC, lasjorg commented on curriculum/challenges/english/07-scientific-computing-with-python/learn-data-structures-by-building-the-merge-sort-algorithm/656680b0fc79f2c38a34d90e.md
> +    assert.match(function_body, /sorted_index\s*(?!=)\s*/);
```suggestion
    assert.match(function_body, /sorted_index/);
```

2024-09-03 14:23 UTC, lasjorg approved these changes
LGTM

2024-09-03 21:48 UTC, moT01 approved these changes
LGTM @subhadipjana866 🎉 Congratulations on your first contribution to the freeCodeCamp repo 🎉

2024-09-03 21:48 UTC, merged