feat(curriculum): add quicksort lab to frontend cert
freeCodeCamp/freeCodeCamp pull request #56009
Opened 2024-09-05 10:22 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-09-05 10:28 UTC, Sembauke requested changes

2024-09-05 10:28 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-quick-sort/66d97c3be4030e8f41a92083.md
> +This one has this implementation:
```suggestion
This one has the following implementation:
```

2024-09-05 10:28 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/lab-quick-sort/66d97c3be4030e8f41a92083.md
> +- Partition the input array into three subarrays made by elements greater than, lesser than, and equal to the pivot value.
```suggestion
- Partition the input array into three subarrays containing elements greater than, lesser than, and equal to the pivot value.
```

2024-09-05 12:39 UTC, Dario-DC commented on client/i18n/locales/english/intro.json
> +        "title": "Build a Quick Sort Algorithm",
```suggestion
      "lab-quick-sort-algorithm": {
        "title": "Build the Quick Sort Algorithm",
```
Not sure about this, but to me it makes more sense using "the".
Folders should be renamed `lab-quick-sort-algorithm`.

2024-09-05 12:39 UTC, Dario-DC commented on client/src/pages/learn/front-end-development/lab-quick-sort/index.md
> +title: Introduction to the Build a Quick Sort Algorithm
```suggestion
title: Introduction to the Build the Quick Sort Algorithm
```

2024-09-05 12:39 UTC, Dario-DC commented on client/src/pages/learn/front-end-development/lab-quick-sort/index.md
> +This is a test for the new project-based curriculum.
```suggestion
For this lab, you will implement the Quick Sort algorithm using JavaScript.
```

2024-09-05 12:39 UTC, Dario-DC commented on curriculum/challenges/_meta/lab-quick-sort/meta.json
> +  "name": "Build a Quick Sort Algorithm",
```suggestion
  "name": "Build the Quick Sort Algorithm",
```

2024-09-05 13:10 UTC, ojeytonwilliams requested changes
I forget how the titles/blocks and dirnames interact, but I suspect changing all `quick-sort`s will need to be `quicksort`.

2024-09-05 13:10 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +      "lab-quick-sort-algorithm": {
```suggestion
      "lab-quicksort-algorithm": {
```
It's one word. https://dl.acm.org/doi/10.1145/366622.366644

2024-09-05 13:10 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +        "title": "Build the Quick Sort Algorithm",
```suggestion
        "title": "Build the Quicksort Algorithm",
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +        "intro": ["For this lab, you will implement the Quick Sort algorithm using JavaScript."]
```suggestion
        "intro": ["For this lab, you will implement the Quicksort algorithm using JavaScript."]
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on client/src/pages/learn/front-end-development/lab-quick-sort/index.md
> +title: Introduction to the Build the Quick Sort Algorithm
```suggestion
title: Introduction to the Build the Quicksort Algorithm
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on client/src/pages/learn/front-end-development/lab-quick-sort/index.md
> +block: lab-quick-sort-algorithm
```suggestion
block: lab-quicksort-algorithm
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on client/src/pages/learn/front-end-development/lab-quick-sort/index.md
> +For this lab, you will implement the Quick Sort algorithm using JavaScript.
```suggestion
## Introduction to the Build the Quicksort Algorithm

For this lab, you will implement the Quicksort algorithm using JavaScript.
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on curriculum/challenges/_meta/lab-quick-sort-algorithm/meta.json
> +  "dashedName": "lab-quick-sort-algorithm",
```suggestion
  "dashedName": "lab-quicksort-algorithm",
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on curriculum/challenges/_meta/lab-quick-sort-algorithm/meta.json
> +  "name": "Build the Quick Sort Algorithm",
```suggestion
  "name": "Build the Quicksort Algorithm",
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on curriculum/challenges/_meta/lab-quick-sort-algorithm/meta.json
> +  "challengeOrder": [{ "id": "66d97c3be4030e8f41a92083", "title": "Build the Quick Sort Algorithm" }],
```suggestion
  "challengeOrder": [{ "id": "66d97c3be4030e8f41a92083", "title": "Build the Quicksort Algorithm" }],
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on curriculum/challenges/english/25-front-end-development/lab-quick-sort-algorithm/66d97c3be4030e8f41a92083.md
> +title: Build the Quick Sort Algorithm
```suggestion
title: Build the Quicksort Algorithm
```

2024-09-05 13:10 UTC, ojeytonwilliams commented on curriculum/challenges/english/25-front-end-development/lab-quick-sort-algorithm/66d97c3be4030e8f41a92083.md
> +dashedName: build-the-quick-sort-algorithm
```suggestion
dashedName: build-the-quicksort-algorithm
```

2024-09-05 13:29 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +      "lab-quick-sort-algorithm": {
No worries. I'm not sure it's worth the time for the old stuff since it sees so little use.

2024-09-05 15:18 UTC, ojeytonwilliams requested changes
Verbiage nits:

2024-09-05 15:18 UTC, ojeytonwilliams commented on curriculum/challenges/english/25-front-end-development/lab-quicksort-algorithm/66d97c3be4030e8f41a92083.md
> +The Quicksort algorithm is one of the various sorting algorithms that can be used.
```suggestion
Quicksort is an algorithm that uses the divide and conquer approach to sort arrays.
```
I think this is a little more informative.

2024-09-05 15:18 UTC, ojeytonwilliams commented on curriculum/challenges/english/25-front-end-development/lab-quicksort-algorithm/66d97c3be4030e8f41a92083.md
> +This one has the following implementation:
```suggestion
It can be implemented as follows:
```

2024-09-06 06:58 UTC, ojeytonwilliams approved these changes
Thanks, Ilenia. LGTM :+1:

2024-09-06 07:02 UTC, Sembauke approved these changes

2024-09-06 07:47 UTC, merged