chore(curriculum): add personal portfolio lab
freeCodeCamp/freeCodeCamp pull request #56012
Opened 2024-09-05 12:44 UTC by zairahira

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-09-06 19:19 UTC, moT01 commented
Blocking this while we figure out if we want to use the same or new challenge ID's

2024-09-10 20:49 UTC, moT01 commented
The tests here are failing. It might just need a rebase.

2024-09-10 22:27 UTC, huyenltnguyen reviewed
(I was just poking around. Don't count on me for review 😅 )

2024-09-12 10:06 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-personal-portfolio/66d98b777c5808d735c47295.md
> +        integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous" />
Thanks for taking a look @huyenltnguyen, your review is always welcome.
I tested and the updated logo doesn't have an underline now 👍️

2024-09-12 10:14 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-personal-portfolio/66d98b777c5808d735c47295.md
> +3. Your portfolio should have a projects section with an `id` of `projects`.
I have updated this in the seed code and tests.

2024-09-13 13:26 UTC, jdwilkin4 approved these changes

2024-09-16 18:13 UTC, moT01 requested changes
The filename should change to match the challenge id.

2024-09-18 13:37 UTC, moT01 approved these changes

2024-09-18 13:37 UTC, merged