chore(curriculum): add url shortener lab
freeCodeCamp/freeCodeCamp pull request #56050
Opened 2024-09-09 15:00 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/562

ALERT for merge conflicts in intro.json with the other 4 labs (373-377)

2024-09-11 17:57 UTC, jdwilkin4 approved these changes

2024-09-13 17:59 UTC, moT01 requested changes
Found one typo across many of the files. Also left one concern.

Other than that, LGTM 👍

2024-09-13 17:59 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/lab-url-shortener-microservice/bd7158d8c443edefaeb5bd0e.md
> +challengeType: 4
I noticed the forumTopicId was removed here. Do we not want that anymore? I feel like we should keep it.

2024-09-13 17:59 UTC, moT01 commented on curriculum/challenges/_meta/lab-url-shortener-microservice/meta.json
> +    "challengeOrder": [{ "id": "bd7158d8c443edefaeb5bd0e", "title": "Build an URL Shortener Microservice" }],
```suggestion
    "challengeOrder": [{ "id": "bd7158d8c443edefaeb5bd0e", "title": "Build a URL Shortener Microservice" }],
```

2024-09-13 17:59 UTC, moT01 commented on curriculum/challenges/_meta/lab-url-shortener-microservice/meta.json
> +    "name": "Build an URL Shortener Microservice",
```suggestion
    "name": "Build a URL Shortener Microservice",
```

2024-09-13 17:59 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +        "title": "Build an URL Shortener Microservice",
```suggestion
        "title": "Build a URL Shortener Microservice",
```

2024-09-13 17:59 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +        "intro": ["In this lab, you will build an URL Shortener Microservice"]
```suggestion
        "intro": ["In this lab, you will build a URL Shortener Microservice"]
```

2024-09-13 17:59 UTC, moT01 commented on client/src/pages/learn/front-end-development/lab-url-shortener-microservice/index.md
> +title: Introduction to the Build an URL Shortener Microservice
```suggestion
title: Introduction to the Build a URL Shortener Microservice
```

2024-09-13 17:59 UTC, moT01 commented on client/src/pages/learn/front-end-development/lab-url-shortener-microservice/index.md
> +In this lab you will build an URL Shortener Microservice
```suggestion
In this lab you will build a URL Shortener Microservice
```

2024-09-13 17:59 UTC, moT01 commented on client/src/pages/learn/front-end-development/lab-url-shortener-microservice/index.md
> +## Introduction to the Build an URL Shortener Microservice
```suggestion
## Introduction to the Build a URL Shortener Microservice
```

2024-09-13 18:31 UTC, ilenia-magoni commented on curriculum/challenges/_meta/lab-url-shortener-microservice/meta.json
> +    "name": "Build an URL Shortener Microservice",
English is weird

2024-09-13 19:07 UTC, moT01 approved these changes

2024-09-13 19:11 UTC, merged