feat(curriculum): add bookmark manager lab
freeCodeCamp/freeCodeCamp pull request #56068
Opened 2024-09-11 12:27 UTC by Dario-DC

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-09-20 11:10 UTC, zairahira requested changes

2024-09-20 11:10 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
> +const deleteBookmarkButtonTest = document.getElementById("delete-bookmark-button");
```suggestion
const deleteBookmarkButton = document.getElementById("delete-bookmark-button");
```

Not sure if this is the actual issue, but the last test was failing with the error: 

```js
// console output
[ReferenceError: deleteBookmarkButton is not defined]
```

2024-09-20 11:10 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
> +Each radio button should have a corresponding label containing an anchor element with the bookmark name and the `href` attribute set to the bookmark URL.
```suggestion
1. Each radio button should have a corresponding label containing an anchor element with the bookmark name and the `href` attribute set to the bookmark URL.
```

2024-09-23 10:10 UTC, zairahira commented on client/i18n/locales/english/intro.json
>        "qjws": { "title": "229", "intro": [] },
I noticed that now the order is `229` in the sheet.

2024-09-23 10:10 UTC, zairahira commented on curriculum/challenges/_meta/lab-bookmark-manager-app/meta.json
> +  "order": 230,
The order should be updated to `229`.

2024-09-23 14:51 UTC, zairahira approved these changes

2024-09-26 03:11 UTC, moT01 reviewed
This is looking good @Dario-DC 👍 Very challenging and really made me think. I left a few comments below to try and clarify some of the user stories. Additionally, I couldn't see the bookmark list very well:

<details><summary>image</summary>

<img width="300" alt="Screenshot 2024-09-25 at 9 55 51 PM" src="https://github.com/user-attachments/assets/5fea43d3-3895-4957-a746-b4eea4376a30">

</details>

I think we should change the CSS a little so you can see the text of those (visited) links - or maybe add a lighter background to the text or something.

Also, here's the JS code I used to pass it if you want to use it for the solution - still room for improvement, but it's a little more concise:

<details><summary>code</summary>

```
const mainSection = document.getElementById('main-section');
const formSection = document.getElementById('form-section');
const addBookmarkBtn = document.getElementById('add-bookmark-button');
const categoryName = document.querySelector('.category-name');
const categoryDropdown = document.getElementById('category-dropdown');
const closeFormBtn = document.getElementById('close-form-button');
const addBookmarkBtnForm = document.getElementById('add-bookmark-button-form');
const bookmarkName = document.getElementById("name");
const bookmarkURL = document.getElementById("url");
const bookmarkListSection = document.getElementById('bookmark-list-section');
const viewCategoryBtn = document.getElementById('view-category-button');
const categoryList = document.getElementById('category-list');
const closeListBtn = document.getElementById('close-list-button');
const deleteBookmarkBtn = document.getElementById('delete-bookmark-button');

const getBookmarks = () => JSON.parse(localStorage.getItem("bookmarks")) || [];

const displayOrCloseForm = () => {
  mainSection.classList.toggle("hidden");
  formSection.classList.toggle("hidden");
}

addBookmarkBtn.addEventListener('click', () => {
  categoryName.innerText = categoryDropdown.value;
  displayOrCloseForm();
});

closeFormBtn.addEventListener('click', displayOrCloseForm);

addBookmarkBtnForm.addEventListener('click', () => {
  const newBookmark = {
    name: bookmarkName.value,
    category: categoryDropdown.value,
    url: bookmarkURL.value
  };

  if (bookmarkName.value.length && bookmarkURL.value.length) {
    localStorage.setItem("bookmarks", JSON.stringify([...getBookmarks(), newBookmark]))
    bookmarkName.value = '';
    bookmarkURL.value = '';
    displayOrCloseForm();
  }
});

function displayOrHideCategory() {
  mainSection.classList.toggle("hidden");
  bookmarkListSection.classList.toggle("hidden");
}

viewCategoryBtn.addEventListener('click', () => {
  categoryName.innerText = categoryDropdown.value;
  const bookmarksToShow = getBookmarks().filter(bookmark => bookmark.category === categoryDropdown.value)
  fillBookmarkList(bookmarksToShow);
  displayOrHideCategory();
});

closeListBtn.addEventListener('click', displayOrHideCategory);

deleteBookmarkBtn.addEventListener('click', () => {
  const selectedBookmark = document.querySelector('input[type="radio"]:checked');
  const newBookmarks = getBookmarks().filter(bookmark =>
    bookmark.name !== selectedBookmark.value || bookmark.category !== categoryDropdown.value
  );
  localStorage.setItem("bookmarks", JSON.stringify(newBookmarks));
  const bookmarksToShow = getBookmarks().filter(bookmark => bookmark.category === categoryDropdown.value);
  fillBookmarkList(bookmarksToShow);
});

const fillBookmarkList = (bookmarksToShow) => {
  categoryList.innerHTML = '';
  if (bookmarksToShow.length === 0) {
    categoryList.innerHTML = '<p>No Bookmarks Found</p>'
  } else {
    bookmarksToShow.forEach(bookmark => {
      categoryList.innerHTML += `<div>
        <input type="radio" name="bookmarks" id="${bookmark.name}" value="${bookmark.name}">
        <label for="${bookmark.name}">
          <a href="${bookmark.url}">${bookmark.name}</a>
        </label>
      </div>`
    });
  }
}
```

</details>

2024-09-26 08:42 UTC, Dario-DC commented
Thanks for your feedback @moT01 Do you think this could work?
![image](https://github.com/user-attachments/assets/64784957-c4cc-4c3f-92a0-0e75d4ae1047)
![image](https://github.com/user-attachments/assets/69c05c38-a83b-4caf-befc-57dfcf68d9c5)

2024-09-26 13:46 UTC, moT01 approved these changes
🎉

2024-09-26 13:46 UTC, merged