feat(curriculum): adding boilerplate workshop to cert
freeCodeCamp/freeCodeCamp pull request #56083
Opened 2024-09-12 14:36 UTC by jdwilkin4

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/570

2024-09-13 19:19 UTC, moT01 approved these changes
LGTM 🎉 

After conflicts fixed.

2024-09-16 08:44 UTC, Dario-DC requested changes
It shouldn't appear like this, is that right?
![image](https://github.com/user-attachments/assets/d12bf853-13e7-40c1-bd06-af3a8764fc8b)

2024-09-16 13:56 UTC, jdwilkin4 commented
@Dario-DC 

If I reverse the UI changes made in this PR here it works as expected
https://github.com/freeCodeCamp/freeCodeCamp/pull/56090/files

<img width="910" alt="Screenshot 2024-09-16 at 6 55 27 AM" src="https://github.com/user-attachments/assets/2b71f7f4-0602-430e-9f1b-08f418263154">
<img width="910" alt="Screenshot 2024-09-16 at 6 55 27 AM" src="https://github.com/user-attachments/assets/2b71f7f4-0602-430e-9f1b-08f418263154">

so we should leave those fixes to the open PR here
https://github.com/freeCodeCamp/freeCodeCamp/pull/56101/files

2024-09-16 17:26 UTC, Dario-DC approved these changes

2024-09-16 17:27 UTC, merged