feat(curriculum): add event flyer lab
freeCodeCamp/freeCodeCamp pull request #56096
Opened 2024-09-13 17:01 UTC by moT01

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

images: https://github.com/freeCodeCamp/cdn/pull/278

Closes #XXXXX

2024-09-16 08:13 UTC, ilenia-magoni requested changes

2024-09-16 08:13 UTC, ilenia-magoni commented on client/i18n/locales/english/intro.json
> +          "In this lab, will use absolute and relative CSS units to create an event flyer page."
```suggestion
          "In this lab, you will use absolute and relative CSS units to create an event flyer page."
```

2024-09-16 08:13 UTC, ilenia-magoni commented on client/src/pages/learn/front-end-development/lab-event-flyer-page/index.md
> +In this lab, will use absolute and relative CSS units to create an event flyer page.
```suggestion
In this lab, you will use absolute and relative CSS units to create an event flyer page.
```

2024-09-16 08:13 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-event-flyer-page/66e45c8140f9fda5c105ae26.md
> +1. You should the `width` of all `hr` and `section` elements to a percent value relative to its parent.
```suggestion
1. You should set the `width` of all `hr` and `section` elements to a percent value relative to its parent.
```

I am not sure it is the right word, but a word is missing

2024-09-16 08:13 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-event-flyer-page/66e45c8140f9fda5c105ae26.md
> +You should have an `img` element as the first child in the header.
```suggestion
You should have an `img` element as the first child in the `header`.
```

2024-09-16 08:13 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-event-flyer-page/66e45c8140f9fda5c105ae26.md
> +You should have an `h1` element as the second child in the header.
```suggestion
You should have an `h1` element as the second child in the `header`.
```

2024-09-16 08:16 UTC, Dario-DC reviewed
I was able to pass all the tests with almost no content showing on the page. I think we should add some additional test, at least to verify that the image has a `src` set and the two sections are not completely empty.

2024-09-16 08:16 UTC, Dario-DC commented on curriculum/challenges/english/25-front-end-development/lab-event-flyer-page/66e45c8140f9fda5c105ae26.md
> +
```suggestion
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Build an Event Flyer Page</title>
</head>

<body>

</body>

</html>
```

2024-09-16 16:38 UTC, moT01 commented
Thanks for taking a look @ilenia-magoni & @Dario-DC 👍 I added the suggestions.

2024-09-16 17:42 UTC, Dario-DC approved these changes
LGTM :+1:

2024-09-16 18:53 UTC, jdwilkin4 approved these changes

2024-09-17 08:56 UTC, ilenia-magoni approved these changes

2024-09-17 08:56 UTC, merged