fix(curriculum): standardize quotations
freeCodeCamp/freeCodeCamp pull request #56118
Opened 2024-09-15 19:56 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56081

2024-09-15 20:12 UTC, ilenia-magoni requested changes
changes are needed also for the other selectors that have the same issue, and it should be added to the seed code as having the quotes is the preferred way

2024-09-15 20:17 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9c0d0857f0a10a57af936.md
>  You should call `document.querySelectorAll()` with `#exercise input[type=number]`.
Please continue finding all the places in which a change is needed

2024-09-15 20:18 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-form-validation-by-building-a-calorie-counter/63c9c0d0857f0a10a57af936.md
> +assert.match(calculateCalories.toString(), /snacksNumberInputs\s*=\s*document\.querySelectorAll\(\s*('|"|`)#snacks input\[\s*type\s*=\s*('|")?number('|")?\s*\]\s*\1\s*\)/);
```suggestion
assert.match(calculateCalories.toString(), /snacksNumberInputs\s*=\s*document\.querySelectorAll\(\s*('|"|`)#snacks input\[\s*type\s*=\s*('|")?number\2?\s*\]\s*\1\s*\)/);
```
use a capture group to match the same type of quote, this needs to be changed in all the tests

2024-09-15 20:37 UTC, gagan-bhullar-tech commented
@ilenia-magoni thanks. fixed all instances.

2024-09-16 08:22 UTC, ilenia-magoni approved these changes
looks good, thank you for the PR!

2024-09-16 10:19 UTC, Sembauke approved these changes

2024-09-16 10:19 UTC, merged