fix: inlining code examples in upper jaw
freeCodeCamp/freeCodeCamp pull request #56119
Opened 2024-09-16 08:49 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-09-16 09:06 UTC, ojeytonwilliams commented
Hey @Sembauke, Huyen's just added a PrismFormatted component to the ui components: https://github.com/freeCodeCamp/ui/pull/303. Could you port this fix in that repo instead?

2024-09-16 09:13 UTC, Sembauke commented
Alright, I'll take a look at it!

2024-09-16 09:22 UTC, Sembauke commented
I am not entirely sure if it has something to do with the Prism Component itself or with the details element applying it's max width to the child elements. Causing the Prism component to inline instead of using it's content width.

2024-09-16 09:44 UTC, ojeytonwilliams commented
I haven't looked into that deeply, but all of this going to be handled by the ui-components, so I assume this fix will need to be there too.

2024-09-16 09:47 UTC, Sembauke commented
@huyenltnguyen probably know if the detail element will be part of the component :)

2024-09-16 20:06 UTC, huyenltnguyen approved these changes
I can't reproduce the issue so I can't test the fix. Though I randomly checked some challenges and the challenge description seems to be displaying correctly still.

I can also confirm that the issue isn't in PrismFormatted as I can't reproduce it in fcc/ui (https://github.com/freeCodeCamp/ui/pull/319). I guess we could keep the changes here in /learn, then revisit when we get to a code example/code snippet component (I reckon we'd probably need to build one in fcc/ui in order to share it between /learn and CAP).

2024-09-17 10:44 UTC, ojeytonwilliams requested changes
It looks like the bug was introduced here: https://github.com/freeCodeCamp/freeCodeCamp/pull/55681, so it should be enough to provide a more specific selector to fix it:

2024-09-17 10:44 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/editor.css
> +
```suggestion
.editor-upper-jaw pre code {
  white-space: pre;
}

```
This css change should be enough.

2024-09-17 10:45 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/editor.css
> +
The rest of the changes can be reverted.

2024-09-17 12:32 UTC, ojeytonwilliams approved these changes

2024-09-17 13:55 UTC, merged