fix(curriculum): reset lesson text
freeCodeCamp/freeCodeCamp pull request #56130
Opened 2024-09-16 16:25 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55354

2024-09-17 10:05 UTC, ojeytonwilliams requested changes
This is looking much better, thanks @gagan-bhullar-tech! To fully close the issue, though, it would be better if the text in the modal became

> Are you sure you wish to revert this lesson? Your latest changes will be undone and the code reverted to the most saved version.

2024-09-18 04:52 UTC, gagan-bhullar-tech commented
@ojeytonwilliams updated PR.

2024-09-18 08:00 UTC, ojeytonwilliams approved these changes
LGTM :+1: 

Thanks, @gagan-bhullar-tech.

2024-10-08 18:18 UTC, moT01 requested changes
Couple minor grammar suggestions. Other than that, LGTM 👍

2024-10-08 18:18 UTC, moT01 commented on client/i18n/locales/english/translations.json
> +    "revert-to-saved-code": "Revert to saved code",
```suggestion
    "revert-to-saved-code": "Revert to Saved Code",
```

I think this matches the other button text.

2024-10-08 18:18 UTC, moT01 commented on client/i18n/locales/english/translations.json
> +    "revert-warn": "Are you sure you wish to revert this lesson? Your latest changes will be undone and the code reverted to the most saved version.",
```suggestion
    "revert-warn": "Are you sure you wish to revert this lesson? Your latest changes will be undone and the code reverted to the most recently saved version.",
```

2024-10-08 20:47 UTC, moT01 approved these changes

2024-10-08 20:47 UTC, merged