feat(curriculum): add hash table lab
freeCodeCamp/freeCodeCamp pull request #56301
Opened 2024-09-26 11:35 UTC by Dario-DC

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-09-27 18:17 UTC, moT01 requested changes
This is looking good @Dario-DC 👍 

It looks like this is just a partial copy of an existing challenge? I don't see the id of this challenge in any existing challenges - or a challenge that is the exact same. I do see [this one, which is similar](https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-hash-table) - so yea, I think we're fine to just create a new id here.

Only problem I noticed was the remove user stories/tests. I originally had this as my remove method:

```
  remove(key) {
    const hashedKey = this.hash(key);
    delete this.collection[hashedKey][key];
  }
```

So when it ran, I was left with an empty object if that was the only k/v in that hashed key - tests 12 and 13 are checking that the collection `isEmpty` - it wasn't, so they failed. We could change that user story to something like: "The `remove` method should take a key as a parameter and remove the corresponding key-value pair from the hash table. If that's the last key-value pair, it should remove the hash key as well." Not sure how to best word it. The tests could maybe be reworded and/or changed slightly as well.

Let me know if you want me to try and come up with something.

2024-09-27 18:17 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/lab-hash-table-class/66f1805aac05f00a7028fbcc.md
> +`hashTable.remove("fCC")` should remove the `fCC` key from the `collection` object.
```suggestion
`hashTable.remove("FCC")` should remove the `FCC` key from the `collection` object.
```

2024-09-30 08:34 UTC, Dario-DC commented
@moT01 I wouldn't say it is a partial copy because in the original challenge the `hash` function was already there ready to use. Here it becomes part of the `HashTable` class as a method. Anyway I think we should use a different ID for this lab.

I added your suggestion to clarify how `remove` should work. Let me know if that part still needs to be improved.

2024-09-30 10:53 UTC, zairahira reviewed
Went through the project, it's looking good 👍️

2024-09-30 19:50 UTC, moT01 approved these changes

2024-10-01 16:24 UTC, jdwilkin4 approved these changes

2024-10-01 16:24 UTC, merged