fix(curriculum): front end cert step 11-15
freeCodeCamp/freeCodeCamp pull request #56322
Opened 2024-09-27 05:39 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56311

2024-09-27 08:29 UTC, ilenia-magoni requested changes
the title of the workshop is cat photo app, please change to that so that it is understandable for what workshop this issue is for

2024-09-27 08:29 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698417821794837f14ca275.md
> +assert.isTrue(
please here use two asserts, one that checks if `anchor`has at least one element (assert.isNotEmpty), and then one that check the inner text of the first one (`assert.equal`)

2024-09-27 08:29 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698419d8f52cf3891f34853.md
> +assert.isTrue(
please replace this using optional chaining and `assert.equal`

2024-09-27 08:29 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698419d8f52cf3891f34853.md
> +assert.isTrue(document.querySelectorAll('a').length >= 2);
here use `assert.isAtLeast`

2024-09-27 08:29 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698419d8f52cf3891f34853.md
> +assert.equal(document.querySelectorAll('a').length, 2);
please use `assert.lengthOf`

2024-09-27 08:29 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698419d8f52cf3891f34853.md
> +assert.isTrue(code.match(/<\/a>/g).length >= 2);
please use `assert.isAtLeast`

2024-09-27 08:29 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698419d8f52cf3891f34853.md
> +assert.isTrue(code.match(/<\/a>/g).length === 2);
`assert.lengthOf`

2024-09-27 17:05 UTC, gagan-bhullar-tech commented
@ilenia-magoni updated PR.

2024-09-27 17:49 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698417821794837f14ca275.md
> +assert.isNotEmpty(anchor.length)
```suggestion
assert.isNotEmpty(anchor)
```

2024-09-27 17:50 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698419d8f52cf3891f34853.md
> +assert.lengthOf(document.querySelectorAll('a').length, 2);
```suggestion
assert.lengthOf(document.querySelectorAll('a'), 2);
```

2024-09-27 17:50 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698419d8f52cf3891f34853.md
> +assert.lengthOf(code.match(/<\/a>/g).length, 2);
```suggestion
assert.lengthOf(code.match(/<\/a>/g), 2);
```

2024-09-27 18:53 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698417821794837f14ca275.md
>  const anchor = $('p > a');
```suggestion
const anchor = document.querySelector('p > a');
```
Version without jQuery.

2024-09-27 18:53 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698417821794837f14ca275.md
> +    anchor[0].innerText.toLowerCase().replace(/\s+/g, ' '), 'cat photos'
```suggestion
assert.equal(
    anchor?.innerText?.toLowerCase().replace(/\s+/g, ' '), 'cat photos'
```

2024-09-27 18:53 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698410269ace0373ec812b6.md
>    pNextSibling.nodeName === '#text' && !/cat\s*photos/.test(pNextSibling.nodeValue) ||
```suggestion
  (pNextSibling.nodeName === '#text' && !/cat\s*photos/.test(pNextSibling.nodeValue)) ||
```
A bit explicit, but I think it makes it much clearer.

2024-09-27 23:08 UTC, gagan-bhullar-tech commented
@huyenltnguyen thanks for the tip. Will do that from now on.

2024-09-28 06:11 UTC, gikf approved these changes

2024-09-29 08:30 UTC, ilenia-magoni approved these changes
LGTM 👍

2024-09-29 08:30 UTC, merged