fix(curriculum): front end cert step 16-20
freeCodeCamp/freeCodeCamp pull request #56323
Opened 2024-09-27 05:52 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56312

2024-09-27 08:33 UTC, ilenia-magoni requested changes
the title of the workshop is cat photo app, please change to that so that it is understandable for what workshop this issue is for

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984218720e29393b1adad2.md
> +assert.equal(foundElements.length, 3);
`assert.lengthOf` is more appropriate

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698429ba5761b39f8aad814.md
> +assert.isTrue(document.querySelectorAll('section').length >= 2);
`assert.isAtLeast`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698429ba5761b39f8aad814.md
> +assert.equal(document.querySelectorAll('section').length, 2);
`assert.lengthOf`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698429ba5761b39f8aad814.md
> +assert.isTrue(code.match(/<\/section>/g).length >= 2);
`assert.isAtLeast`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698429ba5761b39f8aad814.md
> +assert.equal(code.match(/<\/section>/g).length, 2);
`assert.lengthOf`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698429ba5761b39f8aad814.md
> +assert.equal(foundElems.length, 0);
`assert.isEmpty`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698429ba5761b39f8aad814.md
> +assert.equal(foundElems.length, 2);
`assert.lengthOf`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/669842cee55b683aa13ee758.md
>  );
two asserts with `assert.lengthOf`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/669842cee55b683aa13ee758.md
> +assert.equal(document.querySelectorAll('h2').length, 2);
`assert.lengthOf`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/669842cee55b683aa13ee758.md
> +assert.isTrue(
`assert.equal`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/669842f261665d3b4a42df81.md
>  );
first `assert.exists`, then `assert.lengthOf`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/669842f261665d3b4a42df81.md
> +assert.isTrue(
`assert.equal`

2024-09-27 08:33 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/669842f261665d3b4a42df81.md
> +assert.isTrue(
`assert.equal`

2024-09-27 17:13 UTC, gagan-bhullar-tech commented
@ilenia-magoni updated PR

2024-09-27 17:52 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984218720e29393b1adad2.md
> +assert.lengthOf(foundElements.length, 3);
```suggestion
assert.lengthOf(foundElements, 3)
```
I'm not leaving anymore suggestions, if you use `assert.legnthOf`, don't use `.length`. Please fix the others

2024-09-27 17:53 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698429ba5761b39f8aad814.md
> +assert.isEmpty(foundElems.length);
```suggestion
assert.isEmpty(foundElems);
```

2024-09-27 18:07 UTC, gikf approved these changes

2024-09-28 03:28 UTC, jdwilkin4 approved these changes

2024-09-29 08:32 UTC, ilenia-magoni approved these changes
LGTM 👍

2024-09-29 08:32 UTC, merged