fix(curriculum): cat photo app step 21 to 25
freeCodeCamp/freeCodeCamp pull request #56337
Opened 2024-09-27 17:26 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56313

2024-09-27 17:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698444102ebd53d78cf66f8.md
> +assert.exists($('section')[1].lastElementChild.hasAttribute('alt'));
hasAttribute returns a boolean, `isTrue` is more appropriate

2024-09-27 17:56 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698440c54c8823cc60af8bc.md
> +assert.lengthOf($('li').length, 3);
can you also remove jQuery just you are here?
use `document.querySelectorAll` instead of `$`

Also, remove length if you use lengthOf

2024-09-27 17:57 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698444102ebd53d78cf66f8.md
> +assert.exists($('section')[1].lastElementChild.hasAttribute('src'));
```suggestion
assert.isTrue(document.querySelectorAll('section')[1].lastElementChild.hasAttribute('src'));
```

2024-09-27 17:57 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698444102ebd53d78cf66f8.md
>    $('section')[1]
```suggestion
  document.querySelectorAll('section')[1]
```

2024-09-27 17:58 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698444102ebd53d78cf66f8.md
> +  $('section')[1].lastElementChild.getAttribute('src'),
```suggestion
  document.querySelectorAll('section')[1].lastElementChild.getAttribute('src'),
```

2024-09-27 17:59 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698440c54c8823cc60af8bc.md
> +assert.lengthOf(
please check all cases in which you use `lengthOf`, then there don't use `length`

2024-09-27 22:27 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984535d474083eec6bb8da.md
> +  document.querySelector('figcaption').innerText, /Cats love lasagna.?$/i)
```suggestion
  document.querySelector('figcaption').innerText, /Cats love lasagna.?$/i
```

You have an extra parenthesis.

2024-09-27 23:07 UTC, gagan-bhullar-tech commented
@a2937 thanks. Updated PR.

2024-09-28 21:54 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698444102ebd53d78cf66f8.md
> +assert.equal($('section')[1].lastElementChild.nodeName, 'IMG');
Another jQuery call

2024-09-28 21:56 UTC, a2937 requested changes
You have some jQuery calls that need removed.

2024-09-28 21:56 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698444102ebd53d78cf66f8.md
> +assert.isTrue($('section')[1].lastElementChild.hasAttribute('alt'));
Don't forget about this jQuery call

2024-09-28 21:56 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984484deb84b3e21e5b3d7.md
> +assert.equal($('section')[1].lastElementChild.nodeName, 'FIGURE');
You have a jQuery call that needs removed

2024-09-29 08:50 UTC, ilenia-magoni approved these changes
LGTM 👍

2024-09-29 15:34 UTC, a2937 approved these changes
Looks good to me.

2024-09-29 15:34 UTC, merged