fix(curriculum): cat photo app step 31 to 35
freeCodeCamp/freeCodeCamp pull request #56339
Opened 2024-09-27 17:45 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56315

2024-09-27 18:01 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698491eff5f2e43c20c6503.md
> +assert.lengthOf(document.querySelectorAll('figcaption').length, 2);
same here, check all cases of `lengthOf`

2024-09-27 18:03 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984ec64a3652522e81c678.md
> +assert.isNotEmpty($('footer > p > a').length);
```suggestion
assert.isNotEmpty(document.querySelectorAll('footer > p > a'));
```

2024-09-28 21:47 UTC, a2937 approved these changes
All the tests pass and the assertions seem okay as far as I can tell.

2024-09-28 21:53 UTC, a2937 requested changes
I apologize for the early approval. Remove the jquery calls  please.

2024-09-28 21:53 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/6698491eff5f2e43c20c6503.md
> +assert.equal($('main > section')[1].lastElementChild.nodeName, 'FIGURE');
Oh. I should have seen that.

2024-09-28 21:53 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984e8ab54bee517207be42.md
>  const extraSpacesRemoved = $('footer > p')[0].innerText.replace(/\s+/g, ' ');
There's a jQuery call here

2024-09-28 21:53 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984ec64a3652522e81c678.md
>  const nestedAnchor = $('footer > p > a')[0];
Here as well

2024-09-28 21:53 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984ec64a3652522e81c678.md
>  const nestedAnchor = $('footer > p > a')[0];
Another jQuery call

2024-09-28 21:53 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/66984ec64a3652522e81c678.md
>  const pText = $('footer > p')[0].innerText.toLowerCase().replace(/\s+/g, ' ');
Here's another jQuery call.

2024-09-29 06:07 UTC, gagan-bhullar-tech commented
@a2937 updated PR.

2024-09-29 08:35 UTC, ilenia-magoni approved these changes
LGTM 👍

2024-09-29 15:36 UTC, a2937 approved these changes
Looks good to me.

2024-09-29 15:36 UTC, merged