feat(curriculum): create debugging quiz
freeCodeCamp/freeCodeCamp pull request #56429
Opened 2024-10-01 21:59 UTC by nayanmapara

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56208

2024-10-01 22:36 UTC, naomi-lgbt requested changes
This is a great start! Looks like there's a few things missing code tags.

Also you should never commit directly to your `main` branch when contributing to a repository.

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +try...catch
```suggestion
`try...catch`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.log()
```suggestion
`console.log()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +alert()
```suggestion
`alert()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +debugger
```suggestion
`debugger`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.log()
```suggestion
`console.log()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.warn()
```suggestion
`console.warn()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.error()
```suggestion
`console.error()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.table()
```suggestion
`console.table()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +try { ... } else { ... }
```suggestion
`try { ... } else { ... }`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +try { ... } catch { ... } finally { ... }
```suggestion
`try { ... } catch { ... } finally { ... }`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +try { ... } error { ... }
```suggestion
`try { ... } error { ... }`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +try { ... } catch(error) { ... }
```suggestion
`try { ... } catch(error) { ... }`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +inspect()
```suggestion
`inspect()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +trace()
```suggestion
`trace()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.error()
```suggestion
`console.error()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.log()
```suggestion
`console.log()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.log()
```suggestion
`console.log()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +alert()
```suggestion
`alert()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +throw statement
```suggestion
`throw` statement
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.log()
```suggestion
`console.log()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.table()
```suggestion
`console.table()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.warn()
```suggestion
`console.warn()`
```

2024-10-01 22:36 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +console.trace()
```suggestion
`console.trace()`
```

2024-10-01 22:57 UTC, nayanmapara commented
> This is a great start! Looks like there's a few things missing code tags.
> 
> Also you should never commit directly to your `main` branch when contributing to a repository.

Thank you for pointing that out! I’ll make sure to remember this moving forward and avoid committing directly to the main branch.

2024-10-03 20:00 UTC, naomi-lgbt requested changes
One tiny nit and then this will be ready to go.

2024-10-03 20:00 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-debugging-javascript/66edd10913f078e7669eca81.md
> +An uncaught exception error will occur
```suggestion
An uncaught exception error will occur

```

EOF new line.

2024-10-03 21:09 UTC, naomi-lgbt approved these changes
Great work! This looks good to go!

2024-10-04 16:27 UTC, gikf approved these changes

2024-10-04 16:29 UTC, merged

2024-10-04 16:29 UTC, gikf commented
Hi @nayanmapara. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

- - -

Note for future - it is recommended to make changes on a separate branch, rather than the `main` branch. See more about it in point 3 at https://contribute.freecodecamp.org/how-to-contribute-to-the-codebase/#contributing-to-the-codebase.

2024-10-04 16:57 UTC, nayanmapara commented
Thank you, looking forward to future contributions. 😄 
Will keep it in mind to make changes on a separate branch. 💯