feat(curriclum): Add questions, answers & distractors for nano quiz #56234
freeCodeCamp/freeCodeCamp pull request #56436
Opened 2024-10-02 03:52 UTC by CracktheDom

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56234

Added questions, answers and distractors for the quiz on usage of the text editor, nano.

2024-10-03 23:46 UTC, naomi-lgbt requested changes
A small nit to fix.

This looks great, though I'm not sure if we want to wrap keyboard shortcuts in code tags. For now, I'd say leave them as is.

2024-10-03 23:46 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-nano/66f1b03b922a53cb231e1c0d.md
> +Type `nano.exe [FILE] `, then press the **Enter** key
```suggestion
Type `nano.exe [FILE]`, then press the **Enter** key
```

2024-10-04 15:48 UTC, naomi-lgbt approved these changes

2024-10-07 19:01 UTC, gikf approved these changes

2024-10-07 19:01 UTC, merged