feat(curriculum): create javascript variables and data types quiz
freeCodeCamp/freeCodeCamp pull request #56448
Opened 2024-10-02 10:27 UTC by spartanns

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56196

2024-10-02 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +`const` can be updated but not re-declared.
imo, this is missing something about `let`

2024-10-02 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +`const` cannot be updated or re-declared.
same here, something about `let` is missing

2024-10-02 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
>  #### --distractors--
```suggestion

#### --distractors--
```

too many empty lines

2024-10-03 18:43 UTC, naomi-lgbt requested changes
Off to a great start! Couple of small fixes.

2024-10-03 18:43 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +`const` can be updated but not re-declared. `let` can be re-declared, but not updated.
```suggestion
`const` can be re-assigned but not re-declared. `let` can be re-declared, but not re-assigned.
```

2024-10-03 18:43 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +`const` cannot be updated or re-declared. `let` can be updated, but not re-declared.
```suggestion
`const` cannot be re-assigned or re-declared. `let` can be re-assigned, but not re-declared.
```

2024-10-03 18:43 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +Variables declared in global scope cannot be re-declared;
```suggestion
Variables declared in global scope cannot be re-declared.
```

2024-10-03 18:43 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +Which of the following prints out the type of the variable x in the console?
```suggestion
Which of the following prints out the type of the variable `x` in the console?
```

2024-10-03 20:45 UTC, naomi-lgbt approved these changes
This looks good to go! Nice work~!

2024-10-04 07:13 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +Reassigns ` world` to the variable `hello`, and prints it out in the console.
```suggestion
Reassigns `world` to the variable `hello`, and prints it out in the console.
```

2024-10-04 07:13 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-variables-and-data-types/66edc25ae5ea80bf6f785552.md
> +Adds the string ` world` to the variable `hello`, and prints it out in the console.
```suggestion
Adds the string `world` to the variable `hello`, and prints it out in the console.
```

2024-10-04 17:16 UTC, huyenltnguyen approved these changes
@spartanns Thank you for the PR, and congrats on your first contribution to the freeCodeCamp repo 🎉 

Happy contributing!

2024-10-04 18:58 UTC, merged