feat(curriculum): Added the quiz for Javascript Events
freeCodeCamp/freeCodeCamp pull request #56443
Opened 2024-10-02 08:48 UTC by userAdityaa

Checklist:
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56207

2024-10-02 11:15 UTC, ilenia-magoni commented
You are missing backticks around many code snippets, anything code needs to be wrapped in backticks

2024-10-02 14:05 UTC, userAdityaa commented
> You are missing backticks around many code snippets, anything code needs to be wrapped in backticks

Ok, Fixing this.

2024-10-02 14:39 UTC, userAdityaa commented
Hey @ilenia-magoni, Can you check the backtick issue now ?

2024-10-02 14:46 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +
```suggestion
`onfocus`
```

2024-10-02 14:46 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
```suggestion
`onfocus`

```

2024-10-02 14:47 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +DOMFinished
```suggestion
`DOMFinished`
```

2024-10-02 14:47 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +DocumentReady
here

2024-10-02 14:47 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +DOMContentLoaded
here

2024-10-03 19:47 UTC, naomi-lgbt requested changes
Nice work! We've got a few things to resolve before this is ready.

2024-10-03 19:47 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +In general, an event handler is nothing but ___________
```suggestion
In general, an event handler is nothing but a(n) ___________.
```

2024-10-03 19:47 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What is the purpose of the stopImmediatePropagation() method in JavaScript event handling?
```suggestion
What is the purpose of the `stopImmediatePropagation()` method in JavaScript event handling?
```

2024-10-03 19:47 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What is the purpose of the event.currentTarget property in JavaScript event handling?
```suggestion
What is the purpose of the `event.currentTarget` property in JavaScript event handling?
```

2024-10-03 19:47 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What is the purpose of the mouseenter event in JavaScript event handling?
```suggestion
What is the purpose of the `mouseenter` event in JavaScript event handling?
```

2024-10-03 19:51 UTC, userAdityaa commented
Hey @naomi-lgbt, Done with the changes.

2024-10-03 20:58 UTC, naomi-lgbt approved these changes
Nice work! Think we're all good!

2024-10-04 00:22 UTC, userAdityaa commented
Hey, Why is this one test failing can anyone help me ?

2024-10-04 02:48 UTC, naomi-lgbt commented
It's a Euler challenge timing out - not related to your PR. 💜

2024-10-05 07:34 UTC, userAdityaa commented
Any update on this @naomi-lgbt, @gikf, @ilenia-magoni

2024-10-05 17:47 UTC, a2937 commented
> Do NOT copy questions directly from other sources, even if paraphrased. Questions you submit should be your own creations. This includes using generative AI to create questions - please do NOT use AI (ChatGPT, Claude, etc) to create questions.

2024-10-05 17:47 UTC, closed without merging

2024-10-05 18:45 UTC, naomi-lgbt commented
That's disappointing.
I'll release the issue back to other contributors.