feat(curriculum) Added CSS Flexbox Quiz #56187
freeCodeCamp/freeCodeCamp pull request #56455
Opened 2024-10-02 13:13 UTC by COSMIC-ATOM97

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #56187

2024-10-02 13:32 UTC, ilenia-magoni commented
Please use backticks around anything code

2024-10-02 16:00 UTC, COSMIC-ATOM97 commented
I’ve made the required updates to the file. I would appreciate it if you could take a moment to review it.

2024-10-03 19:51 UTC, naomi-lgbt requested changes
One tiny nit, then this should be good to go!

2024-10-03 19:51 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-flexbox/66ed8fe7f45ce3ece4053eb2.md
> +`align-items`
```suggestion
`align-items`

```
We need the EOF new line.

2024-10-07 20:17 UTC, naomi-lgbt approved these changes

2024-10-18 13:25 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-flexbox/66ed8fe7f45ce3ece4053eb2.md
> +`space-evenly`
it is also an answer on line 80, this question is a duplicate and needs to be changed to something else

2024-10-18 13:25 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-flexbox/66ed8fe7f45ce3ece4053eb2.md
> +`nowrap`
duplicate question, it is an answer on line 36

2024-10-27 08:34 UTC, gikf commented
Hey @COSMIC-ATOM97,

did you have a chance too look at the latest feedback?

2024-11-01 14:25 UTC, closed without merging

2024-11-01 17:35 UTC, ilenia-magoni commented
@COSMIC-ATOM97 We would have really appreciated if you could see the PR to completion, deleting the repo closes the PR