feat: boilerplate for tooling and deployment quiz
freeCodeCamp/freeCodeCamp pull request #56463
Opened 2024-10-02 16:07 UTC by naomi-lgbt

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Unblocks #56238

Looks like this one never got created.

2024-10-02 16:09 UTC, ilenia-magoni commented on temp.txt
what about this file?

2024-10-02 16:13 UTC, majestic-owl448 approved these changes

2024-10-02 16:14 UTC, ilenia-magoni commented on curriculum/challenges/_meta/quiz-tooling-and-deployment/meta.json
> +  "hasEditableBoundaries": true,
does this create issues for quizzes?

2024-10-02 16:44 UTC, naomi-lgbt commented on curriculum/challenges/_meta/quiz-tooling-and-deployment/meta.json
> +  "hasEditableBoundaries": true,
Thanks!

2024-10-02 17:18 UTC, ilenia-magoni commented on client/src/pages/learn/front-end-development/quiz-tooling-and-deployment/index.md
> +title: Introduction to the quiz-tooling-and-deployment
dashed title here too

2024-10-02 17:18 UTC, ilenia-magoni commented on curriculum/challenges/_meta/quiz-tooling-and-deployment/meta.json
> +  "challengeOrder": [{ "id": "66fd6f0370213be90fed82ec", "title": "Step 1" }],
```suggestion
  "challengeOrder": [{ "id": "66fd6f0370213be90fed82ec", "title": ""Tooling and Deployment Quiz" }],
```

2024-10-02 17:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-tooling-and-deployment/66fd6f0370213be90fed82ec.md
> +dashedName: step-1
```suggestion
dashedName: quiz-tooling-and-deployment
```

2024-10-02 20:46 UTC, moT01 requested changes

2024-10-02 20:46 UTC, moT01 commented on client/src/pages/learn/front-end-development/quiz-tooling-and-deployment/index.md
> +title: Introduction to the quiz-tooling-and-deployment
```suggestion
title: Introduction to the Tooling and Deployment Quiz
```

2024-10-02 20:47 UTC, moT01 commented
I cannot commit suggestions 😢

2024-10-04 12:13 UTC, moT01 approved these changes

2024-10-04 12:13 UTC, merged