create CSS Colors Quiz
freeCodeCamp/freeCodeCamp pull request #56473
Opened 2024-10-02 22:32 UTC by pragyananda

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56184

2024-10-03 11:02 UTC, Sembauke requested changes

2024-10-03 20:39 UTC, naomi-lgbt requested changes
A few minor fixes.

2024-10-03 20:39 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-colors/66ed8fe1f45ce3ece4053eb1.md
> +How can you set the transparency of a color to 50%?
```suggestion
How can you set the transparency of an element to 50%?
```

Colour transparency is managed by the alpha channel, the `opacity` property affects the entire element(s) targeted by the selector.

2024-10-03 20:39 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-colors/66ed8fe1f45ce3ece4053eb1.md
> +`3`
These answers are not code and do not need to be in backticks.

2024-10-03 20:39 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-colors/66ed8fe1f45ce3ece4053eb1.md
> +Which keyword sets the text color to the default browser color?
Inherit does not set the value to the browser default. It sets the value to the computed value of the parent element. Which can sometimes be the default value, but not always.

2024-10-03 21:30 UTC, naomi-lgbt requested changes
Last one!

2024-10-03 21:30 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-colors/66ed8fe1f45ce3ece4053eb1.md
> +No direct way to set.
```suggestion
There is no direct way to do so.
```

2024-10-03 21:30 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-colors/66ed8fe1f45ce3ece4053eb1.md
> +Which of these functions allows specifying the saturation of a color?
```suggestion
Which of these functions allows specifying the transparency of a color?
```

Saturation is the second value of `hsl`.

2024-10-03 22:11 UTC, naomi-lgbt approved these changes
Great work!

2024-10-06 15:17 UTC, pragyananda commented
hello @Sembauke can you please review my PR?

2024-10-07 06:18 UTC, Sembauke approved these changes

2024-10-07 06:18 UTC, merged

2024-10-07 06:35 UTC, pragyananda commented
Thank you @Sembauke .