feat(curriculum): Create Security and Privacy Quiz
freeCodeCamp/freeCodeCamp pull request #56479
Opened 2024-10-03 08:10 UTC by royjohnlee

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #[56236](https://github.com/freeCodeCamp/freeCodeCamp/issues/56236)

2024-10-03 20:28 UTC, naomi-lgbt requested changes
Almost there! Just a few minor fixes.

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +What is the difference between Security and Privacy?
```suggestion
What is the difference between security and privacy?
```

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Access-Control-Expose-Headers
```suggestion
`Access-Control-Expose-Headers`
```

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Access-Control-Allow-Credentials
```suggestion
`Access-Control-Allow-Credentials`
```

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Access-Control-Allow-Headers
```suggestion
`Access-Control-Allow-Headers`
```

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Access-Control-Allow-Methods
```suggestion
`Access-Control-Allow-Methods`
```

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Cookies enhance page load speed by storing user data; however, this can prevent  your local machine from detecting abnormalities.
```suggestion
Cookies enhance page load speed by storing user data; however, this can prevent your local machine from detecting abnormalities.
```

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Name or Email
```suggestion
Name or Email
```

2024-10-03 20:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Using unencrypted storage systems for faster and easier data access.
```suggestion
Using unencrypted storage systems for faster and easier data access.

```

2024-10-03 21:18 UTC, royjohnlee commented
I'll do my best to not leave minor mistakes!

2024-10-03 21:33 UTC, naomi-lgbt requested changes
Last one!

2024-10-03 21:33 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Which of the following is a common web security issue, and what is the appropriate mitigation.
```suggestion
Which of the following is a common web security issue?
```

The answers do not mention mitigation.

2024-10-03 21:36 UTC, royjohnlee commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +Which of the following is a common web security issue, and what is the appropriate mitigation.
you got it boss

2024-10-03 21:59 UTC, naomi-lgbt approved these changes

2024-10-04 10:58 UTC, zairahira requested changes
Just one nit, the rest is good to go 👍️

2024-10-04 10:58 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/quiz-security-and-privacy/66f1b0a939e913ccd3d4fa18.md
> +To restrict all JavaScript and TypeScript execution within the user's brower.
```suggestion
To restrict all JavaScript and TypeScript execution within the user's browser.
```

2024-10-07 07:59 UTC, zairahira approved these changes

2024-10-07 07:59 UTC, merged