feat(curriculum): add css-typography quiz
freeCodeCamp/freeCodeCamp pull request #56477
Opened 2024-10-03 06:39 UTC by Dhairya-A-Mehra

Checklist:

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #56188 

I have added questions for the CSS Typography Quiz. I have not tested this application on my local machine because I am developing this on Windows. However, I consulted with @naomi-lgbt , and they informed me that I am allowed to submit the PR without local testing.
If any changes to the questions are needed, I am happy to make adjustments as required.

2024-10-03 07:17 UTC, ilenia-magoni commented
request: do not keep closing and opening PRs, it creates a lot of unnecessary noise

2024-10-03 08:01 UTC, Dhairya-A-Mehra commented
> request: do not keep closing and opening PRs, it creates a lot of unnecessary noise

do you want me to close this PR?

2024-10-03 08:29 UTC, ilenia-magoni commented
no, I just asked you to stop closing and reopening, keep this one and don't close and reopen again please

2024-10-03 08:35 UTC, Dhairya-A-Mehra commented
> no, I just asked you to stop closing and reopening, keep this one and don't close and reopen again please
okay sure
last one I closed because it was not in proper format given by you

2024-10-03 08:46 UTC, ilenia-magoni commented
you can edit the title instead of closing and reopening a PR

2024-10-03 08:49 UTC, ilenia-magoni commented
You also do not need to make a new PR if you are asked to change something in the code, there you will need to push a new commit

2024-10-03 20:29 UTC, naomi-lgbt requested changes
Before I can review this in-depth, all code needs to be between backticks so our parser renders it in code tags. I've left a couple of examples.

2024-10-03 20:29 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +Which of the following is the correct way to write a **@font-face** rule in CSS?
```suggestion
Which of the following is the correct way to write a `@font-face` rule in CSS?
```

2024-10-03 20:29 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +@font-face { font: 'MyFont'; size: 12px; }
```suggestion
`@font-face { font: 'MyFont'; size: 12px; }`
```

2024-10-06 07:26 UTC, Dhairya-A-Mehra commented
> Before I can review this in-depth, all code needs to be between backticks so our parser renders it in code tags. I've left a couple of examples.

Okay I'll do it

2024-10-07 21:13 UTC, naomi-lgbt requested changes

2024-10-07 21:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +What CSS property is used to set the **font family** for an element?
```suggestion
What CSS property is used to set the font family for an element?
```

2024-10-07 21:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +Why is **typographic hierarchy** important in design?
```suggestion
Why is typographic hierarchy important in design?
```

2024-10-09 09:49 UTC, ilenia-magoni commented
note, you can make a single commit if you go to the Edited files tab, which is preferred

2024-10-09 10:07 UTC, Dhairya-A-Mehra commented
> note, you can make a single commit if you go to the Edited files tab, which is preferred

I tried to commit this thing as a batch, but I was not able to do that, so made single commits.
Sorry for that

2024-10-09 10:48 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +It controls the amount of space between lines of text
```suggestion
It controls the amount of space between lines of text

```

you accidentally removed a line here, let's put it back

2024-10-09 17:03 UTC, naomi-lgbt approved these changes

2024-10-14 15:01 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +How many values does the `text-shadow` property usually have?
I don't quite like this question. Traditionally speaking, yes, developers probably want more than just the two required offset values but it feels unverifiable.

2024-10-14 15:25 UTC, a2937 requested changes

2024-10-14 15:25 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +What CSS property is used to set the font family for an element?
This is a give-me question. You said the answer in the question.  Please change it.

2024-10-14 15:25 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +What does the first value in the `text-shadow` property control?
Actually the first value, while optional, controls the color of the shadow. 

Source: https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow

2024-10-14 15:25 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/quiz-css-typography/66ed9010f45ce3ece4053eb8.md
> +For body text, what type of font is generally the easiest to read?
What exactly makes a serif font less readable than a sans-serif font? After all Times New Roman is pretty legible.

2024-10-16 20:48 UTC, Dhairya-A-Mehra commented
@a2937 I'll do the require changes

2024-10-22 17:07 UTC, gikf commented
Hey @Dhairya-A-Mehra,

Any progress on addressing requested changes?

2024-10-22 17:20 UTC, Dhairya-A-Mehra commented
> Hey @Dhairya-A-Mehra,
> 
> Any progress on addressing requested changes?

I will be committing the required changes in a few hours.

2024-10-23 17:21 UTC, a2937 requested changes
You still have yet to respond to Ilenia's suggestion.

2024-10-24 06:45 UTC, Dhairya-A-Mehra commented
> You still have yet to respond to Ilenia's suggestion.

Oh, I am extremely sorry.

2024-10-28 00:17 UTC, a2937 approved these changes
Everything seems okay to me.

2024-10-28 06:33 UTC, merged

2024-10-28 06:33 UTC, gikf commented
Hi @Dhairya-A-Mehra. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

2024-10-29 04:57 UTC, Dhairya-A-Mehra commented
> Hi @Dhairya-A-Mehra. Congrats on your first pull request (PR)! 🎉
> 
> Thank you for your contribution to the page! 👍 We are happy to accept these changes and look forward to future contributions. 📝

Thank You all for supporting me through this journey of contributing in your organization.