fix: regex checks for learn regex by spam filter
freeCodeCamp/freeCodeCamp pull request #56485
Opened 2024-10-03 12:29 UTC by bulutyerli

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56471

2024-10-03 22:35 UTC, naomi-lgbt requested changes
Also, the pattern test should probably come second, not first.

2024-10-03 22:35 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-regular-expressions-by-building-a-spam-filter/64233094a1293c079b5b0996.md
>  Your `freeRegex` should match `free money`.
```suggestion
Your `freeRegex` should match the entire phrase `free money`.
```

2024-10-03 22:35 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-regular-expressions-by-building-a-spam-filter/64233094a1293c079b5b0996.md
> +assert.match(freeRegex.source, /fr\[(e3|3e)\]\[(e3|3e)\] mon\[(e3|3e)\]/);
```suggestion
assert.match(freeRegex.source, /fr\[(?:e3|3e)\]\[(?:e3|3e)\] mon\[(?:e3|3e)\]/);
```

No need for these to actually capture.

2024-10-04 08:26 UTC, ilenia-magoni commented
You need to remove the 20 extra files from the PR

2024-10-04 09:20 UTC, ilenia-magoni commented
It looks like you are having issues, feel free to ask for help in the discord server

2024-10-04 09:22 UTC, closed without merging

2024-10-04 09:23 UTC, bulutyerli commented
> It looks like you are having issues, feel free to ask for help in the discord server

yes i will check that and also i guess its better to make a new pr

2024-10-04 09:26 UTC, ilenia-magoni commented
I suggested to ask for help to fix this PR, not to create a new one. There is always something you can do