feat(curriculum): add permutation generator lab
freeCodeCamp/freeCodeCamp pull request #56482
Opened 2024-10-03 10:30 UTC by zairahira

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Original prototype https://github.com/freeCodeCamp/CurriculumExpansion/pull/616/

I have modified the original code to remove redundant values from the final array.

2024-11-14 10:23 UTC, zairahira commented
Reopening this PR as recursion is now part of the curriculum we'll ship.

2024-11-15 16:55 UTC, moT01 requested changes
This is looking good @zairahira 👍 I left a comment about one of the tests and the solution below. Other than that, the only thing I saw was that you aren't actually required to use recursion to solve this. Wonder if you could add a test that checks if users are in fast using it?

2024-11-15 16:55 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/lab-permutation-generator/66fe4f33a2cc9b33f4d5cd9b.md
> +`permuteString('101')` should return `[ '101', '110', '011', '110', '101' ]`.
This test is asking for duplicates - `101` and `110` are in there twice. The function should not return duplicates, correct? It also means that the solution that is passing this test isn't removing duplicates properly.

2024-11-19 10:21 UTC, zairahira commented
@moT01 
I have added this test to check for recursion.

````md

You should use recursion in your `permuteString` function.

```js
assert.match(permuteString.toString(), /permuteString\s*\(/);
```

````

Let me know what you think.

2024-11-19 16:29 UTC, moT01 approved these changes
LGTM 🎉

2024-11-19 17:46 UTC, jdwilkin4 approved these changes

2024-11-19 17:47 UTC, merged