Added the Javascript Array Quiz
freeCodeCamp/freeCodeCamp pull request #56493
Opened 2024-10-03 18:47 UTC by Ritesh2351235

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56170

2024-10-03 19:54 UTC, jdwilkin4 commented
You are linking to the wrong issue.

Make sure to update your PR description to link to the issue you were assigned to

2024-10-03 20:00 UTC, ilenia-magoni commented
the correct issue to link is https://github.com/freeCodeCamp/freeCodeCamp/issues/56201

2024-10-03 20:03 UTC, Ritesh2351235 commented
@jdwilkin4 Sorry for the mistake

2024-10-03 20:06 UTC, ilenia-magoni reviewed
mostly empty lines suggestions

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What will be the result of the following array method `indexOf()`?

```js
const numbers = [10, 20, 30, 40];
const index = numbers.indexOf(20);
console.log(index);
```
````

I think 'javascript' is also accepted by the linter, but we usually use 'js'

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What will the following code output using the spread operator?

```js
const arr1 = [1, 2, 3];
const arr2 = [...arr1, 4, 5];
console.log(arr2);
```
````

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What will `splice()` do in the following example?

```js
const colors = ['red', 'blue', 'green', 'yellow'];
colors.splice(1, 2, 'purple');
console.log(colors);
```
````

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What will be the result of the following code using `slice()`?

```javascript
const arr = ['apple', 'banana', 'cherry', 'date'];
const slicedArr = arr.slice(1, 3);
console.log(slicedArr);
```
````

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What will be the output of this code ?

```js
const fruits = ['apple', 'banana', 'cherry', 'apple', 'orange'];
const index = fruits.indexOf('apple');
if (index !== -1) {
    fruits.splice(index, 1);
}
console.log(fruits);
```
````

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What is the final value of result in the following code ?

```js
const arr1 = [1, 2];
const arr2 = [3, 4, 5];
const combined = arr1.concat(arr2);
const result = combined.includes(3);
console.log(result);
```
````

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What does the following code output?

```ja
const nums = [1, 2, 3, 4];
const doubled = nums.map(n => n * 2);
console.log(doubled.includes(8));
```
````

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What is the output when using splice() to remove elements from a 2D array?

```js
let matrix = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
];
matrix.splice(1, 1);
console.log(matrix);
```
````

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +
```suggestion
It is used to add extra elements to the array.
```

2024-10-03 20:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
````suggestion
What will be the result of this code?

```js
const numbers = [10, 20, 30];
numbers.push(40);
numbers.pop();
const length = numbers.length;
console.log(length);
```
````

2024-10-03 20:46 UTC, Ritesh2351235 commented
@ilenia-magoni I have made the necessary changes can you please check it out once.

2024-10-03 21:27 UTC, naomi-lgbt requested changes
Some opportunities to address, but this is a good start!

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
```suggestion
What value will be assigned to the `index` variable?

```js
const numbers = [10, 20, 30, 40];
const index = numbers.indexOf(20);
```
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
```suggestion
What value will be assigned to the `arr2` variable?

```js
const arr1 = [1, 2, 3];
const arr2 = [...arr1, 4, 5];
```
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
```suggestion
What will this code print to the console?

```js
const colors = ['red', 'blue', 'green', 'yellow'];
colors.splice(1, 2, 'purple');
console.log(colors);
```
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +```
```suggestion
What value will be assigned to the `slicedArr` variable?

```js
const arr = ['apple', 'banana', 'cherry', 'date'];
const slicedArr = arr.slice(1, 3);
```
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +
```suggestion
The array gets truncated, removing elements beyond the new length.
```

Extra new line.

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +What is the final value of result in the following code ?
```suggestion
What is the final value of `result` in the following code ?
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +false
```suggestion
`false`
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +Error
```suggestion
`Error`
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +false
```suggestion
`false`
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +[1, 2, 3, 4, 5]
```suggestion
`[1, 2, 3, 4, 5]`
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +undefined
```suggestion
`undefined`
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +true
```suggestion
`true`
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +What is the output when using splice() to remove elements from a 2D array?
```suggestion
What is the output when using `splice()` to remove elements from a 2D array?
```

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +It counts the number of rows in a 2D array.
```suggestion
It counts the number of top-level elements in a 2D array.
```

Arrays don't really have rows.

2024-10-03 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
> +How does the rest parameter (`...rest`) work in array destructuring in JavaScript?
```suggestion
How does the rest parameter `...rest` work in array destructuring in JavaScript?
```

2024-10-04 02:53 UTC, Ritesh2351235 commented
@naomi-lgbt I have added the above-mentioned changes

2024-10-04 03:35 UTC, naomi-lgbt approved these changes

2024-10-04 19:00 UTC, gikf approved these changes

2024-10-04 19:00 UTC, merged