fix(curriculum):Changed the jquery files to vanilla js
freeCodeCamp/freeCodeCamp pull request #56499
Opened 2024-10-03 20:29 UTC by Ritesh2351235

Converted the previous JQuery elements to Vanilla JavaScript.

Checklist:
- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-10-03 22:42 UTC, naomi-lgbt requested changes
We should not need to switch to a `.forEach` loop for any of these tests. We should only be updating the query selector syntax.

2024-10-04 02:59 UTC, Ritesh2351235 commented
@naomi-lgbt Have made the above changes

2024-10-04 03:34 UTC, gikf approved these changes

2024-10-04 03:35 UTC, naomi-lgbt approved these changes

2024-10-04 04:41 UTC, merged