fix(curriculum):Shopping List Workshop
freeCodeCamp/freeCodeCamp pull request #56501
Opened 2024-10-03 21:01 UTC by Ritesh2351235

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56500

2024-10-03 21:11 UTC, ilenia-magoni requested changes

2024-10-03 21:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-arrays/66edcccbba6dacdb65a59067.md
this file should not be in this PR

2024-10-03 21:38 UTC, ilenia-magoni commented
now there is no files in the PR

2024-10-03 22:38 UTC, naomi-lgbt approved these changes

2024-10-09 13:46 UTC, zairahira approved these changes

2024-10-09 14:29 UTC, ilenia-magoni approved these changes

2024-10-09 14:29 UTC, merged