fix(curriculums): Update tests for HTML recipe page lab
freeCodeCamp/freeCodeCamp pull request #56507
Opened 2024-10-03 23:09 UTC by royjohnlee

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #[56489](https://github.com/freeCodeCamp/freeCodeCamp/issues/56489)
Removed all jQuery tests.
Used specific assert methods where applicable.
Corrected hint to match the text.

2024-10-03 23:28 UTC, naomi-lgbt requested changes

2024-10-03 23:28 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-recipe-page/668f08ea07b99b1f4a91acab.md
> +assert.isTrue(document.querySelector('p')?.previousElementSibling.tagName === 'H1');
```suggestion
assert.strictEqual(document.querySelector('p')?.previousElementSibling.tagName, 'H1');
```

Please update the others as well.

2024-10-03 23:34 UTC, royjohnlee commented on curriculum/challenges/english/25-front-end-development/lab-recipe-page/668f08ea07b99b1f4a91acab.md
> +assert.isTrue(document.querySelector('p')?.previousElementSibling.tagName === 'H1');
understood!

2024-10-04 08:03 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-recipe-page/668f08ea07b99b1f4a91acab.md
> +assert.isTrue(document.querySelector('ul')?.previousElementSibling.tagName === 'H2');
```suggestion
assert.strictEqual(document.querySelector('ul')?.previousElementSibling.tagName, 'H2');
```
These as well.

2024-10-04 08:03 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-recipe-page/668f08ea07b99b1f4a91acab.md
> +assert.isTrue(document.querySelector('ol')?.previousElementSibling.tagName === 'H2');
```suggestion
assert.strictEqual(document.querySelector('ol')?.previousElementSibling.tagName, 'H2');
```

2024-10-04 16:20 UTC, naomi-lgbt approved these changes

2024-10-04 17:19 UTC, gikf approved these changes

2024-10-04 17:19 UTC, merged