feat(curriculum): create CSS Grid quiz
freeCodeCamp/freeCodeCamp pull request #56529
Opened 2024-10-04 18:56 UTC by Sebastian-Wlo

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56194

2024-10-07 18:22 UTC, naomi-lgbt requested changes

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +What is the shorthand for `column_gap` and `row_gap` properties?
```suggestion
What is the shorthand for the `column-gap` and `row-gap` properties?
```

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +Which one of these options for `grid-template-columns` property will result in a middle column that is 80 characters wide, and two columns taking up the remaining space?
```suggestion
Which one of these options for `grid-template-columns` property will result in a middle column that is 80 relative units wide, and two columns taking up the remaining space?
```

`1rem` isn't necessarily the width of a single character.

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +What does `minmax()` function do?
```suggestion
What does the `minmax()` function do?
```

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +Which property sets a size for the rows in a grid container?
```suggestion
Which property automatically allocates rows based on a fixed size?
```

Technically more accurate - `grid-row` can also set the size.

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +What does `grid-auto-flow` property do?
```suggestion
What does the `grid-auto-flow` property do?
```

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +px
```suggestion
`px`
```

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +%
```suggestion
`%`
```

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +em
```suggestion
`em`
```

2024-10-07 18:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +fr
```suggestion
`fr`
```

2024-10-07 20:34 UTC, Sebastian-Wlo reviewed
Changes applied - I honestly expected more doubts about the quality of the questions.

2024-10-10 18:26 UTC, naomi-lgbt approved these changes

2024-10-11 11:10 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-grid/66ed8fedf45ce3ece4053eb3.md
> +Which one of these options for `grid-template-columns` property will result in a middle column that is 80 relative units wide, and two columns taking up the remaining space?
```suggestion
Which one of these options for the `grid-template-columns` property will result in a middle column that is 80 relative units wide, and two columns taking up the remaining space?
```

2024-10-11 11:47 UTC, ilenia-magoni approved these changes
Thank you for your PR

2024-10-11 12:11 UTC, merged