feat(curriculum): Add questions about react basics
freeCodeCamp/freeCodeCamp pull request #56540
Opened 2024-10-05 18:03 UTC by nikkivaddepelli

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-10-06 04:43 UTC, gikf reviewed
Hey @nikkivaddepelli,

Each question should have 3 distractors and one answer. Correct answer should not be included in the distractors.

Also please link PR to the issue its related to.

2024-10-06 09:53 UTC, nikkivaddepelli commented
@gikf  i have slove this problem

2024-10-07 21:27 UTC, naomi-lgbt requested changes

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +useState
```suggestion
`useState`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +useLayoutEffect
```suggestion
`useLayoutEffect`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +useContext
```suggestion
`useContext`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +useEffect
```suggestion
`useEffect`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +const count = 0;
```suggestion
`const count = 0;`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +const [count, setCount] = useEffect("");
```suggestion
`const [count, setCount] = useEffect("");`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +const state = 0;
```suggestion
`const state = 0;`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +const [count, setCount] = useState(0);
```suggestion
`const [count, setCount] = useState(0);`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +create-react-app
`create-react-app` is so outdated now that even the React docs no longer recommend it.

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +npm run
```suggestion
`npm run`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +npm update
```suggestion
`npm update`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +npm build
```suggestion
`npm build`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +npm install
```suggestion
`npm install`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +` <Home />`
```suggestion
`<Home />`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +Why should the key prop not be the array index?
```suggestion
Why should the `key` prop not be the array index?
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +style={{ color: blue }}
```suggestion
`style={{ color: blue }}`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +style="color: blue"
```suggestion
`style="color: blue"`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +style: { color: 'blue' }
```suggestion
`style: { color: 'blue' }`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +style={{ color: 'blue' }}
```suggestion
`style={{ color: 'blue' }}`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +const state = 0;
```suggestion
`const state = 0;`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +const count = 0;
```suggestion
`const count = 0;`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +let [count, setCount] = 0;
```suggestion
`let [count, setCount] = 0;`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +const [count, setCount] = useState(0);
```suggestion
`const [count, setCount] = useState(0);`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +Calling render() method.
```suggestion
Calling the `render()` method.
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +Changing the state using setState.
```suggestion
Changing the state using `setState`.
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +How would you specify a required name prop using PropTypes?
```suggestion
How would you specify a required `name` prop using `PropTypes`?
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +name: PropTypes.bool
```suggestion
`name: PropTypes.bool`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +name: PropTypes.array.isRequired
```suggestion
`name: PropTypes.array.isRequired`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +name: PropTypes.string
```suggestion
`name: PropTypes.string`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +name: PropTypes.string.isRequired
```suggestion
`name: PropTypes.string.isRequired`
```

2024-10-07 21:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +`<Route path="/home" component={Home} />`
```suggestion
`<Route path="/home" component={Home} />`

```

Restore the EOF new line.

2024-10-08 10:57 UTC, ahmedobaid23 reviewed
I noticed that this PR includes questions on states, hooks, and routing, which seem to overlap with the topics covered in the separate quiz (#56225). Since those topics are already addressed in the other quiz, should they be excluded from this one to avoid redundancy? I'd appreciate clarification on the intended scope of this PR.

2024-10-08 10:57 UTC, ahmedobaid23 commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +Which hook would you use to mimic `componentDidMount`?
Question related to hooks

2024-10-08 10:57 UTC, ahmedobaid23 commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +How do you initialize a state variable in a functional component?
Question related to states

2024-10-08 10:57 UTC, ahmedobaid23 commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +How do you initialize a state variable in a functional component?
Question related to states

2024-10-08 10:57 UTC, ahmedobaid23 commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +How would you create a route in React Router?
Question related to routing

2024-10-08 21:22 UTC, naomi-lgbt commented
Yes, you are correct.

2024-10-14 14:49 UTC, nikkivaddepelli commented
@naomi-lgbt i resolved this all comments

2024-10-14 18:13 UTC, naomi-lgbt requested changes

2024-10-14 18:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +setTimeout
```suggestion
`setTimeout`
```

2024-10-14 18:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +`Switch` statements
```suggestion
`switch` statements
```

2024-10-14 18:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +Using the React.Component only.
```suggestion
Using the `React.Component` only.
```

2024-10-14 18:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +Using the function keyword or arrow functions.
```suggestion
Using the `function` keyword or arrow functions.
```

2024-10-14 18:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +`<ChildComponent name={'John'} />`
This is technically valid syntax, no?

2024-10-14 18:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +It can cause unexpected bugs during state updates.
```suggestion
It can trigger unnecessary renders when modifying the array.
```

2024-10-14 18:13 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +`package.json`
```suggestion
`package.json`

```

Restore the EOF new line.

2024-10-15 07:45 UTC, nikkivaddepelli commented
@naomi-lgbt i resloved the comments

2024-10-15 15:10 UTC, naomi-lgbt requested changes

2024-10-15 15:10 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +It can trigger unnecessary renders when modifying the array..
```suggestion
It can trigger unnecessary renders when modifying the array.
```

2024-10-15 16:11 UTC, nikkivaddepelli commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +It can trigger unnecessary renders when modifying the array..
@naomi-lgbt i made changes

2024-10-16 11:42 UTC, nikkivaddepelli commented
@naomi-lgbt i made all changes

2024-10-16 12:38 UTC, nikkivaddepelli commented
@naomi-lgbt  please review

2024-10-16 12:45 UTC, ilenia-magoni commented
Do not keep pinging maintainers, when they are able they will come to review

2024-10-16 17:18 UTC, naomi-lgbt approved these changes

2024-10-16 17:51 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +`<div className='class'>`
Is this a valid element?

2024-10-17 12:15 UTC, nikkivaddepelli commented on curriculum/challenges/english/25-front-end-development/quiz-react-basics/66f1a2009e65c9a40a26d51e.md
> +`<div className='class'>`
@gikf i made correction

2024-10-18 11:24 UTC, gikf approved these changes

2024-10-18 12:28 UTC, merged

2024-10-18 12:30 UTC, gikf commented
Hi @nikkivaddepelli. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝