feat(curriculum): create basic css quiz #56179
freeCodeCamp/freeCodeCamp pull request #56545
Opened 2024-10-06 01:11 UTC by clydehenry3

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56179

2024-10-07 19:35 UTC, clydehenry3 commented
Hey @naomi-lgbt! My 7 day deadline is tomorrow from issue #56179. If the PR isn't accepted by then, will this kick me out of that issue and lose my credit?

Thanks!

2024-10-08 00:41 UTC, naomi-lgbt requested changes

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Which answer uses the correct strucutre of using a CSS rule?
```suggestion
Which answer uses the correct structure of using a CSS rule?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +What does the `<meta>` viewport do?
```suggestion
What does `<meta name="viewport">` do?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +When using internal CSS, where is the `<style>` placed within the HTML?
```suggestion
When using internal CSS, where is the `style` element placed within the HTML?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +`<meta>`
```suggestion
In the `meta` element
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +`<script>`
```suggestion
In the `script` element
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +`<body>`
```suggestion
In the `body` element
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +`<head>`
```suggestion
In the `head` element
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Which rule is correct to target `<h1>` inside of a `<div>`?
```suggestion
Which selector is correct to target `h1` elements inside of a `div`?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Which rule is correct to target direct children of a `<footer>`?
```suggestion
Which selector is correct to target direct children of a `footer`?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Which rule is correct to target the next sibling of an `<img>`?
```suggestion
Which selector is correct to target the next sibling of an `img`?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Which rule is correct to target all siblings of an `<img>`?
```suggestion
Which selector is correct to target all siblings of an `img`?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +What statement is TRUE when using the `inline-block` rule?
```suggestion
What statement is TRUE when using the `inline-block` value?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Given the following selectors, which has the highest priority?
```suggestion
Given the following selectors, which has the highest specificity?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Given the following selectors, which has the lowest priority?
```suggestion
Given the following selectors, which has the lowest specificity?
```

The answers also don't match. Type selectors have the same specificity - `div` is no more the correct answer than `h1` is.

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Targets all `<p>` elements on the page.
```suggestion
Targets all `p` elements on the page.
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Overrides any other styles that the property is used on.
```suggestion
Overrides any other values applied to the property for that selector.
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Determines styles of the element based on specificity and order of they appear from top to bottom.
```suggestion
Determines styles of the element based on specificity and order of declaration.
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Which rule applies 32px of margin to all sides?
```suggestion
Which rule applies `32px` of margin to all sides?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Which rule applies 24px padding to the top and bottom?
```suggestion
Which rule applies `24px` padding to the top and bottom?
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Controls how size of the font.
```suggestion
Controls the size of the font.
```

2024-10-08 00:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-basic-css/66ed8fa2f45ce3ece4053eab.md
> +Controls how much space is between the lines of text.
```suggestion
Controls how much space is between the lines of text.

```

Restore the EOF new line.

2024-10-08 01:22 UTC, clydehenry3 reviewed
Thank you so much for reviewing my code @naomi-lgbt!

2024-10-08 19:17 UTC, naomi-lgbt commented
![image](https://github.com/user-attachments/assets/e06025a1-04be-4384-8c62-4c6b83023076)

Looks like the ones that are "hidden" got missed.

2024-10-08 20:22 UTC, clydehenry3 commented
> ![image](https://private-user-images.githubusercontent.com/63889819/374695261-e06025a1-04be-4384-8c62-4c6b83023076.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTkyMTksIm5iZiI6MTcyODQxODkxOSwicGF0aCI6Ii82Mzg4OTgxOS8zNzQ2OTUyNjEtZTA2MDI1YTEtMDRiZS00Mzg0LThjNjItNGM2YjgzMDIzMDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIwMjE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZDVkMTdlM2UyNjY1NWJiYjc0N2I5ZTczNTI4OTFjM2E2YjFkMmM0N2RlNGFhZTkyZGFhYzVlMTAzNWI3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.791GDB7_CN89stwfFrpY4IrLROvayLtLvCTXRlI5L0U)
> 
> Looks like the ones that are "hidden" got missed.

My bad! Those were now resolved.

2024-10-09 15:43 UTC, naomi-lgbt approved these changes

2024-10-13 18:07 UTC, gikf approved these changes

2024-10-13 18:08 UTC, gikf approved these changes

2024-10-13 18:08 UTC, merged

2024-10-13 18:08 UTC, gikf commented
Hi @clydehenry3. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝