feat(curriculum): javascript regular expressions quiz
freeCodeCamp/freeCodeCamp pull request #56543
Opened 2024-10-05 21:43 UTC by EggSaled

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56209

2024-10-07 21:54 UTC, naomi-lgbt requested changes
Just looking at this, there's a lot of cases where you're using backticks around a type that you shouldn't be.

"X returns a `String`" - not really, `String` is the global constructor. "X returns a string".

2024-10-08 19:22 UTC, naomi-lgbt requested changes

2024-10-08 19:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-regular-expressions/66edd3011f18f4ee1bd9d28b.md
> +Which of the following character classes is equivalent to the regular expression `/[a-zA-Z0-9]/`?
```suggestion
Which of the following character classes is equivalent to the regular expression `/[a-zA-Z0-9_]/`?
```

`\w` includes the underscore.

2024-10-08 19:22 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-regular-expressions/66edd3011f18f4ee1bd9d28b.md
> +`/(?:Expense|Asset) \$\d+\.\d{2} \1 \$\d+\.\d{2}`
````suggestion
Which part of the following regular expression causes errors?

```js
/(?:Expense|Asset) \$\d+\.\d{2} \1 \$\d+\.\d{2}
```
````

2024-10-09 05:27 UTC, naomi-lgbt reviewed
Last nit.

2024-10-09 05:27 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-regular-expressions/66edd3011f18f4ee1bd9d28b.md
> +null, the method `test` only validates if the given regular expression is valid.
```suggestion
Null, the method `test` only validates if the given regular expression is valid.
```

Or wrap it in backticks as `` `null` `` if referring to the specific value.

2024-10-09 16:25 UTC, naomi-lgbt approved these changes

2024-10-09 17:39 UTC, gikf reviewed
Two nitpicks

2024-10-09 19:31 UTC, gikf approved these changes

2024-10-09 19:46 UTC, merged