feat(curriculam): added question on based form validation
freeCodeCamp/freeCodeCamp pull request #56558
Opened 2024-10-06 14:23 UTC by doosabhulaxmi

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #56210

2024-10-07 22:44 UTC, naomi-lgbt requested changes
Before I can review this in depth, you are missing backticks around all of the methods/property names/references to code.

You will need to fix that. The review comment is an example of such a fix.

2024-10-07 22:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +validateInput()
```suggestion
`validateInput()`
```

2024-10-09 04:46 UTC, naomi-lgbt requested changes

2024-10-09 04:46 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +Which actions will make `checkValidity()` run?
```suggestion
Which action will make `checkValidity()` run?
```

2024-10-09 04:46 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +When does the `checkValidity()` method stop form submission?
I don't believe `checkValidity()` does this. It does fire an invalid event on the input elements, but NOT on the form itself (and the input-level event has no default behaviour).

2024-10-09 04:46 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +To check if all required fields are filled and valid
```suggestion
To check if all inputs meet their specified constraints
```

2024-10-09 04:46 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +Which actions can be prevented using `e.preventDefault()`?
Hmm, this one's a little off. Technically `e.preventDefault()` doesn't prevent *submitting* a form, it prevents the default behaviour *caused* by submitting a form (re: the page refresh and POST call).

2024-10-09 04:46 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +Which method should you use to handle form data on the submit event in JavaScript?
Hmm. Technically, these are all the same method, with a different argument.

2024-10-11 14:12 UTC, doosabhulaxmi commented
@naomi-lgbt changes done on form validation.
please check now

2024-10-11 16:06 UTC, ilenia-magoni reviewed
some stylistic things

2024-10-11 16:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +input
```suggestion
`"input"`
```

2024-10-11 16:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +change
```suggestion
`"change"`
```

2024-10-11 16:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +focus
```suggestion
`"focus"`
```

2024-10-11 16:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +submit
```suggestion
`"submit"`
```

2024-10-11 16:06 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +Set the form's method to GET
```suggestion
Set the form's `method` to `"GET"`
```

2024-10-11 17:25 UTC, doosabhulaxmi commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +`setCustomValidity()`
method

2024-10-12 06:43 UTC, doosabhulaxmi commented
@ilenia-magoni  changes done.
please check now

2024-10-12 15:11 UTC, naomi-lgbt requested changes

2024-10-12 15:11 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +Which property is used to customize the message shown during validation failure?
```suggestion
Which method is used to customize the message shown during validation failure?
```

2024-10-12 15:11 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +`setErrorMessage`
```suggestion
`setErrorMessage()`
```

2024-10-12 15:11 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +`setValidationMessage`
```suggestion
`setValidationMessage()`
```

2024-10-12 15:11 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +`customMessage`
```suggestion
`customMessage()`
```

2024-10-12 15:11 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +`setCustomValidity()`
Then the question and distractors should reflect that.

2024-10-13 03:20 UTC, doosabhulaxmi commented
@naomi-lgbt changes done please check now.

2024-10-13 04:11 UTC, naomi-lgbt approved these changes

2024-10-13 04:20 UTC, doosabhulaxmi commented on curriculum/challenges/english/25-front-end-development/quiz-form-validation-with-javascript/66edd3403d7077eece6dc4b6.md
> +`customMessage`
changes done @naomi-lgbt

2024-10-16 06:47 UTC, doosabhulaxmi commented
@ilenia-magoni please check

2024-10-20 06:54 UTC, doosabhulaxmi commented
please review

2024-10-21 10:17 UTC, ilenia-magoni commented
@doosabhulaxmi please stop pinging maintainers

2024-10-21 11:17 UTC, Dario-DC approved these changes

2024-10-21 11:18 UTC, merged