feat(curriculum): added searching and sorting algorithm based questions
freeCodeCamp/freeCodeCamp pull request #56555
Opened 2024-10-06 10:15 UTC by harshitaadam

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #56215

2024-10-06 11:57 UTC, ilenia-magoni commented
the quiz should have exactly 20 questions not 30

2024-10-07 22:42 UTC, naomi-lgbt requested changes
Before I can review this in depth, you've added extra separators that should not be present at the end of each question set.

I've shown an example in the review suggestion.

2024-10-07 22:42 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-searching-and-sorting-algorithms/66edd476078cf3f3bc654271.md
> +---
```suggestion
O(log n)
```

2024-10-08 12:05 UTC, harshitaadam commented
Ok I will resolve this

On Tue, Oct 8, 2024, 4:12 AM Naomi ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Before I can review this in depth, you've added extra separators that
> should not be present at the end of each question set.
>
> I've shown an example in the review suggestion.
> ------------------------------
>
> In
> curriculum/challenges/english/25-front-end-development/quiz-searching-and-sorting-algorithms/66edd476078cf3f3bc654271.md
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/56555#discussion_r1790967343>
> :
>
> > +O(log n)
> +
> +---
>
> ⬇️ Suggested change
>
> -O(log n)
> -
> ----
> +O(log n)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/freeCodeCamp/freeCodeCamp/pull/56555#pullrequestreview-2353061272>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJHUB7ITY73VHXU6KDFVJVLZ2ME5FAVCNFSM6AAAAABPOF7PE2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJTGA3DCMRXGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-09 16:53 UTC, naomi-lgbt approved these changes

2024-10-09 17:11 UTC, gikf approved these changes

2024-10-09 17:22 UTC, merged