feat(curriculum): react state and hooks quiz
freeCodeCamp/freeCodeCamp pull request #56556
Opened 2024-10-06 10:38 UTC by mitchellabrouwer

Checklist:

- [ x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [ x] I have tested these changes either locally on my machine, or GitPod.

Closes #56225 

Thank you for considering this pull request. I look forward to your feedback.

2024-10-07 21:38 UTC, naomi-lgbt requested changes

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +Executing an apps most complex functionality.
```suggestion
Executing an app's most complex functionality.
```

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +SWR
Let's expand this into the full name.

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +MUI
This one too.

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +If I have a complex function inside a component, which hook can I use to memoize its result?
```suggestion
If you have a complex function inside a component, which hook can you use to memoize its result?
```

Second-person preferred.

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +The `useCallback` hook...
```suggestion
What is the `useCallback` hook?
```

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +Allows you to define a callback function.
```suggestion
A hook that allows you to define a callback function.
```

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +Is a custom hook not managed by React.
```suggestion
A custom hook not managed by React.
```

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +Checks an app's performance in development only.
```suggestion
A hook that checks an app's performance in development only.
```

2024-10-07 21:38 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +Ensures a function isn't re-created each time a component re-renders.
```suggestion
A hook that ensures a function isn't re-created each time a component re-renders.
```

2024-10-08 03:42 UTC, mitchellabrouwer commented
Thanks @naomi-lgbt, I've made the required updates.

2024-10-08 19:41 UTC, naomi-lgbt requested changes

2024-10-08 19:41 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +To abstracts repetitive logic.
```suggestion
To abstract repetitive logic.
```

2024-10-08 22:20 UTC, mitchellabrouwer commented
Thanks @naomi-lgbt, I've committed the update.

2024-10-09 16:23 UTC, naomi-lgbt approved these changes

2024-10-15 09:21 UTC, huyenltnguyen reviewed
I have some concerns regarding the following questions:
- "Which of the following is NOT a global React state library?"
- "Which of the following lists only includes built in React hooks?"
- "Which is NOT use for fetching data in React?"

There is nothing wrong with the questions themselves, but I'm not sure if we want them in our quiz, considering the target audience. 

The questions are probably more suitable for experienced developers who are already familiar with React's built-in features and React ecosystem.

I think it's better to have the questions cover React concepts and test how well campers understand them, rather than asking campers to identify libraries.

2024-10-16 10:48 UTC, mitchellabrouwer commented
Thanks for reviewing. I've taken your concerns into account and created replacement questions.

2024-10-16 10:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +setCertificates(previousItems => ...previousItems, 'Front End');
```suggestion
setCertificates(previousItems => ...previousItems, "Front End");
```

let's use double quotes for JSX to be uniform with the rest of the curriculum

2024-10-16 10:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +setCertificates('Front End');
```suggestion
setCertificates("Front End");
```

2024-10-16 10:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +setCertificates().append('Front End');
```suggestion
setCertificates().append("Front End");
```

2024-10-16 10:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +setCertificates(previousItems => [...previousItems, 'Front End']);
```suggestion
setCertificates(previousItems => [...previousItems, "Front End"]);
```

2024-10-16 10:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +    name: 'Discovery'
```suggestion
    name: "Discovery"
```

2024-10-16 10:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +  console.log('Nice work!!');
```suggestion
  console.log(| Nice work!!");
```

2024-10-16 10:55 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +The `react-router-dom` library is a popular choice to handle routing in React apps.
```suggestion
The `react-router-dom` library is a popular choice to handle routing in React apps.

```
let's not remove EOF empty lines

2024-10-18 08:48 UTC, huyenltnguyen approved these changes
LGTM 👍

@mitchellabrouwer Thank you for the PR and congratulations on your first contribution to this repo 🎉
We look forward to your next.

Happy contributing!

2024-10-18 09:00 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-react-state-and-hooks/66f1a417757b6ca4eecd89d6.md
> +  console.log(| Nice work!!");
```suggestion
  console.log("Nice work!!");
```

2024-10-18 09:47 UTC, merged