feat(curriculam):Add questions about CSS libraries and freamworks
freeCodeCamp/freeCodeCamp pull request #56554
Opened 2024-10-06 09:47 UTC by ReenaChidrala

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #56228

2024-10-07 21:44 UTC, naomi-lgbt requested changes

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +set of CSS rules
```suggestion
A set of CSS rules
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +coding language
```suggestion
A coding language
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +library for CSS styles
```suggestion
A library for CSS styles
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +What is the primary purpose of the .container class in Bootstrap?
```suggestion
What is the primary purpose of the `.container` class in Bootstrap?
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +m-4
```suggestion
`m-4`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +padding-4
```suggestion
`padding-4`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +margin-4
```suggestion
`margin-4`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +mt-4
```suggestion
`mt-4`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +.sass
```suggestion
`.sass`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +.scsss
```suggestion
`.scsss`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +.css
```suggestion
`.css`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +.scss
```suggestion
`.scss`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +text-red
```suggestion
`text-red`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +Which Tailwind class would you use to set text color to red?
```suggestion
Which Tailwind class would you use to set the text color to red?
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +red-text
```suggestion
`red-text`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +color-red
```suggestion
`color-red`
```

2024-10-07 21:44 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-libraries-and-frameworks/66f1aeb60b11aec5abe83c2e.md
> +text-red-500
```suggestion
`text-red-500`
```

2024-10-17 19:16 UTC, gikf commented
Hey @ReenaChidrala,

did you get a chance to take a look at the suggested changes?

2024-10-21 15:33 UTC, ReenaChidrala commented
@gikf "Hi ma'am, I have made the changes as per your suggestion. Please take a look."

2024-10-21 17:31 UTC, naomi-lgbt approved these changes

2024-10-22 11:34 UTC, ReenaChidrala commented
@gikf pls review my pr

2024-10-23 17:18 UTC, gikf approved these changes

2024-10-23 17:18 UTC, merged

2024-10-23 17:18 UTC, gikf commented
Hi @ReenaChidrala. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

2024-10-24 11:21 UTC, ReenaChidrala commented
@gikf 
Thank You so Much For Accepting My Pr And Form Such a Nice Comment