fix(curriculum): updated the falsy condition to null check
freeCodeCamp/freeCodeCamp pull request #56560
Opened 2024-10-06 15:23 UTC by kukutapunithish

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #56335

2024-10-06 17:40 UTC, gikf commented
Hi there,

Thanks for creating this pull request.

The linked issue has not been triaged yet, and a solution has not been agreed upon. Once the issue is open for contribution, you are welcome to update this pull request to reflect the issue consensus. Until the issue is open for contribution, we will not be able to review your pull request.

2024-10-09 17:38 UTC, lasjorg requested changes

2024-10-09 17:38 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/65422ba173a18b1bedef1bb6.md
> +  assert.match(code, /if\s*\(userData\?\.currentSong\s*===\s*null\s*\)\s*\{/);
```suggestion
  assert.match(code, /if\s*\(\s*userData\?\.currentSong\s*===\s*null\s*\)\s*\{/);
```
Allow for spaces on both sides of the conditional code.

2024-10-09 17:38 UTC, lasjorg commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/65422ba173a18b1bedef1bb6.md
> +assert.match(code, /if\s*\(userData\?\.currentSong\s*===\s*null\s*\)\s*\{\s*playSong\(\s*userData\?\.songs\s*\[\s*0\s*\]\s*\.id\s*\)\s*;?\s*\}/);
```suggestion
assert.match(code, /if\s*\(\s*userData\?\.currentSong\s*===\s*null\s*\)\s*\{\s*playSong\(\s*userData\?\.songs\s*\[\s*0\s*\]\s*\.id\s*\)\s*;?\s*\}/);
```

Same thing.

2024-10-14 19:44 UTC, closed without merging