feat(curriculum) : create javascript events quiz
freeCodeCamp/freeCodeCamp pull request #56575
Opened 2024-10-07 15:19 UTC by aakarsh-2004

Checklist:
- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #56207 

I have created the JavaScript Events Quiz which includes all the subtopics which were specified. I researched a lot in these hours and then after careful observations, I was able to create this quiz.

2024-10-07 16:59 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +
```suggestion
`.addEventListener()`
```

you have accidentally added an extra line here

2024-10-07 17:00 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +```
````suggestion
Following code is an example of?

```js
const parentList = document.getElementById('parent-list');

parentList.addEventListener('click', function(event) {
  if (event.target && event.target.nodeName === 'LI') {
    console.log('List item clicked:', event.target.textContent);
  }
});
```
````

code fences requires to be surrounded by empty lines

2024-10-07 17:00 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +
```suggestion
Callback function
```

2024-10-07 17:00 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +
```suggestion
The element that triggered the event
```

2024-10-07 17:03 UTC, aakarsh-2004 commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +
sure, working on these changes!

2024-10-07 17:17 UTC, aakarsh-2004 commented
I have added all the necessary changes which were requested, please review it! @ilenia-magoni

2024-10-08 00:21 UTC, naomi-lgbt requested changes

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +Following code is an example of?
```suggestion
What does this code demonstrate?
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What does the event.target property return?
```suggestion
What does the `event.target` property return?
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What is the best way to capture an input event across all types of input fields?
```suggestion
Which event type captures an input event across all types of input fields?
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +Using `keyup`
```suggestion
`keyup`
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +Using `keypress`
```suggestion
`keypress`
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +Using `keydown`
```suggestion
`keydown`
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +Using `input` event
```suggestion
`input`
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What is the main advantage of using addEventListener() over inline event handlers?
```suggestion
What is the main advantage of using `addEventListener()` over inline event handlers?
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What does the term "event propagation" mean?
```suggestion
What does the term "event propagation" refer to?
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +The way an event travels through the DOM in phases (capturing, target, and bubbling)
```suggestion
Events travel through the DOM in phases
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What is meant by "default action" of an event in JavaScript?
```suggestion
What is meant by the "default action" of an event in JavaScript?
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +Why is the once option in addEventListener() useful?
```suggestion
Why is the once option in `addEventListener()` useful?
```

2024-10-08 00:21 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +What does `DOMContentLoaded` event indicate?
```suggestion
What does the `DOMContentLoaded` event indicate?
```

2024-10-08 19:59 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +How do you correctly pass a parameter to an event handler function in JavaScript?
```suggestion
How do you correctly pass an argument to an event handler function in JavaScript?
```
Arguments are passed to function, parameters are in function definition.

2024-10-08 19:59 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +`addEventListener('click', myFunction.parameter)`
```suggestion
`addEventListener('click', myFunction.argument)`
```

2024-10-08 19:59 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +`addEventListener('click', parameter => myFunction(parameter))`
```suggestion
`addEventListener('click', argument => myFunction(argument))`
```

2024-10-08 19:59 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-events/66edd0ac31fea6e678eb925a.md
> +`addEventListener('click', () => myFunction(parameter))`
```suggestion
`addEventListener('click', () => myFunction(argument))`
```

2024-10-09 07:04 UTC, aakarsh-2004 commented
Changes done! @gikf

2024-10-22 23:04 UTC, naomi-lgbt approved these changes

2024-10-23 03:53 UTC, gikf approved these changes

2024-10-23 03:53 UTC, merged

2024-10-23 03:53 UTC, gikf commented
Hi @aakarsh-2004. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝