feat(curriculum): create bash and sql quiz
freeCodeCamp/freeCodeCamp pull request #56573
Opened 2024-10-07 14:14 UTC by prajwal3104

### Checklist

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes locally to ensure accuracy and functionality.

Closes #56233

2024-10-08 00:17 UTC, naomi-lgbt requested changes

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What makes SQL different from the other sort of programming languages, which include Python or Java?
```suggestion
What makes SQL different from other programming languages, such as Python or Java?
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +SQL is a procedural programming language designed specifically for building an interactive Web application but it relies heavily on database interaction to generate dynamic content.
```suggestion
SQL is a procedural programming language designed specifically for building an interactive web application but it relies heavily on database interaction to generate dynamic content.
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +SQL is a markup language that marks, format, and structures data for presentation on a web page such that they would be viewable through any web browser.
```suggestion
SQL is a markup language that marks, formats, and structures data for presentation on a web page such that they would be viewable through any web browser.
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +To hold customer reviews: The length of review may vary to a great extent.
```suggestion
To hold customer reviews, since the length of reviews may vary to a great extent.
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Title: `INTEGER`, PublicationYear: `DATE`, IsAvailable: `BOOLEAN`
```suggestion
`Title: INTEGER, PublicationYear: DATE, IsAvailable: BOOLEAN`
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Title: `VARCHAR`, PublicationYear: `INTEGER`, IsAvailable: `TEXT`
```suggestion
`Title: VARCHAR, PublicationYear: INTEGER, IsAvailable: TEXT`
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Title: `CHAR(100)`, PublicationYear: `INTEGER`, IsAvailable: `VARCHAR(3)`
```suggestion
`Title: CHAR(100), PublicationYear: INTEGER, IsAvailable: VARCHAR(3)`
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Title: `VARCHAR`, PublicationYear: `INTEGER`, IsAvailable: `BOOLEAN`
```suggestion
`Title: VARCHAR, PublicationYear: INTEGER, IsAvailable: BOOLEAN`
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What command would you use to redirect the errors of a command to a file named "errors.log"?
```suggestion
What command would you use to redirect the errors of a command to a file named `errors.log`?
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +3. Delete all files with the ".tmp" extension in the "/home/user" directory, asking for confirmation before deleting each file.
```suggestion
1. List all files and folders, including hidden ones, within the "/home/user" directory.
2. Copy all `.txt` files from the `/home/user` directory to a folder named `text_backup` within the current directory.
3. Delete all files with the `.tmp` extension in the `/home/user` directory, asking for confirmation before deleting each file.
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +```
````suggestion
```bash
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +```
````suggestion
```bash
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +```
````suggestion
```bash
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +```
````suggestion
```bash
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +| ReleaseYear  | INT        |             |
````suggestion
```md
| Column Name | Data Type  | Constraints |
|-------------|------------|-------------|
| AlbumID     | INT        | PRIMARY KEY |
| AlbumTitle   | VARCHAR(255) | NOT NULL   |
| ReleaseYear  | INT        |             |
```
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +| ArtistName  | VARCHAR(255) | NOT NULL   |
````suggestion
```md
| Column Name | Data Type  | Constraints |
|-------------|------------|-------------|
| ArtistID    | INT        | PRIMARY KEY |
| ArtistName  | VARCHAR(255) | NOT NULL   |
```
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +| Email       | VARCHAR(255) |             |
````suggestion
```md
| Column Name | Data Type    | Constraints |
| :---------- | :----------- | :---------- |
| CustomerID  | INT          | PRIMARY KEY |
| FirstName   | VARCHAR(255) | NOT NULL   |
| LastName    | VARCHAR(255) | NOT NULL   |
| Email       | VARCHAR(255) |             |
```
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +| ZipCode     | VARCHAR(10)  | NOT NULL   |
````suggestion
```md
| Column Name | Data Type    | Constraints |
| :---------- | :----------- | :---------- |
| AddressID   | INT          | PRIMARY KEY |
| CustomerID  | INT          |             |
| Street      | VARCHAR(255) | NOT NULL   |
| City        | VARCHAR(255) | NOT NULL   |
| State       | VARCHAR(255) | NOT NULL   |
| ZipCode     | VARCHAR(10)  | NOT NULL   |
```
````

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +You have a text file named "shopping_list.txt" located in your Documents directory. You would like to append "Milk" as a new entry to the end of your shopping list. What is the command to accomplish
```suggestion
You have a text file named `shopping_list.txt` located in your Documents directory. You would like to append `"Milk"` as a new entry to the end of your shopping list. What is the command to accomplish this?
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +You downloaded a compressed archive called "notes.tar.gz" from the internet. You need to unarchive this file in a directory called "study_materials" that you've already created in your home directory
```suggestion
You downloaded a compressed archive called `notes.tar.gz` from the internet. You need to extract this file in a directory called `study_materials` that you've already created in your home directory. Which command would you use?
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +You have a database table named `orders` with one column named `order_date`, showing the date each order was placed. Your task is to write a SQL query that retrieves all the orders taken in the year
```suggestion
You have a database table named `orders` with one column named `order_date`, showing the date each order was placed. Your task is to write a SQL query that retrieves all the orders taken in the year 2022. Which command would do so?
```

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +`All of the above options would work.`
```suggestion
All of these options would work.
```

Answers are shuffled.

2024-10-08 00:17 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Submitting common SQL commands, like 'SELECT' or 'UNION,' as part of user input
```suggestion
Submitting common SQL commands, like `SELECT` or `UNION`, as part of user input
```

2024-10-08 05:55 UTC, prajwal3104 commented
Hi @naomi-lgbt 

Thank you for reviewing the PR and suggesting the changes to be made, I have accepted the requested changes. And sorry I was unaware of the formats, I appreciate the time you took to look after and suggest the changes. 

I would be happy to contribute if anything is required to be done still!

Thank you

2024-10-08 08:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +
````suggestion
```
````
let's remove this extra empty line added accidentally

2024-10-08 08:37 UTC, prajwal3104 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +
okay on it

2024-10-08 19:50 UTC, naomi-lgbt requested changes

2024-10-08 19:50 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +1. List all files and folders, including hidden ones, within the "/home/user" directory.
```suggestion
1. List all files and folders, including hidden ones, within the `/home/user` directory.
```

2024-10-08 19:50 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +**Question:** What is the PRIMARY disadvantage of using a single table to store both movie and actor data in this scenario?
```suggestion
What is the PRIMARY disadvantage of using a single table to store both movie and actor data in this scenario?
```

2024-10-09 16:24 UTC, naomi-lgbt approved these changes

2024-10-11 06:34 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Which of the following is an example of why it is important to know when to use fixed-length and when to use variable-length data types in SQL?
I'm a bit confused by this question. All options look like example why that's important. Is the question trying to ask which one should have variable length?

2024-10-11 06:34 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Add a column named `CustomerID` to the Addresses table as a foreign key referencing the `CustomerID` in the Customers table.
There's already `CustomerID` column in `Addresses`.

2024-10-12 19:20 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
there is still written "Placeholder question" above this line, this should be the question

2024-10-12 19:20 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What makes SQL different from other programming languages, such as Python or Java?
```suggestion
Answer all of the questions below correctly to pass the quiz.
```

let's leave this line as is, and add the question below where it should go

2024-10-18 13:29 UTC, ilenia-magoni commented
hey @prajwal3104 did you have a chance to take a look at the feedback you received?

2024-10-28 17:25 UTC, closed without merging