feat(curriculum): create objects quiz
freeCodeCamp/freeCodeCamp pull request #56583
Opened 2024-10-07 21:44 UTC by IAMOTZ

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes [#56202](https://github.com/freeCodeCamp/freeCodeCamp/issues/56202)

2024-10-08 06:02 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-objects/66edcd0ecb4b25dc64a34804.md
> +`object -> name`
```suggestion
`obj -> key`
```

2024-10-08 06:02 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-objects/66edcd0ecb4b25dc64a34804.md
> +`object#name`
```suggestion
`obj#key`
```

2024-10-08 06:02 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-objects/66edcd0ecb4b25dc64a34804.md
> +`object[name]`
```suggestion
`obj[key]`
```

2024-10-08 06:02 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-objects/66edcd0ecb4b25dc64a34804.md
> +`object.name`
```suggestion
`obj.key`
```

2024-10-08 06:02 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-javascript-objects/66edcd0ecb4b25dc64a34804.md
> +`object.?key`
```suggestion
`object?.key`
```

2024-10-09 16:01 UTC, naomi-lgbt requested changes

2024-10-10 18:33 UTC, naomi-lgbt approved these changes

2024-10-11 14:04 UTC, gikf approved these changes

2024-10-11 14:04 UTC, merged

2024-10-11 14:05 UTC, gikf commented
Hi @IAMOTZ. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝