chore(e2e): create test to ensure `--fcc-expected--` does not show up in the hint text
freeCodeCamp/freeCodeCamp pull request #56581
Opened 2024-10-07 19:38 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This adds a simple test to ensure that `--fcc-expected--` never actually shows up as hint text for challenge. For our purposes, I'm using Step 4 of the CSS Penguin Project. 

Related to https://github.com/freeCodeCamp/freeCodeCamp/pull/56577

2024-10-07 20:25 UTC, ojeytonwilliams requested changes
Thanks @a2937 I think this will help. Could you make it check for a specific hint? It's a little more reliable to test for the presence of something than the absence. Reason being an empty string would pass, while not being what we want.

2024-10-07 22:50 UTC, a2937 commented
It's funny you should say that. Cause I'm getting something really weird happening here. In the automated tests, the element has no value. But in the browser it's completely fine.

2024-10-08 01:29 UTC, a2937 commented
My best bet is that `actual` is not being assigned a value. So either the error message is missing a value or the value of `actual` is reassigned to a none value.

2024-10-08 07:33 UTC, ojeytonwilliams requested changes
This should get it working in CI:

2024-10-08 07:33 UTC, ojeytonwilliams commented on e2e/lower-jaw.spec.ts
> +  await checkButton.click();
```suggestion
```
This needs to be done after the `fill`

2024-10-08 07:33 UTC, ojeytonwilliams commented on e2e/lower-jaw.spec.ts
> +
```suggestion
  await checkButton.click();
  
```

2024-10-08 14:44 UTC, ojeytonwilliams approved these changes
The code looks solid. Assuming no surprises in CI, LGTM :+1:

2024-10-08 21:25 UTC, naomi-lgbt approved these changes

2024-10-08 21:25 UTC, merged