Update 66ed9034f45ce3ece4053ebd.md
freeCodeCamp/freeCodeCamp pull request #56612
Opened 2024-10-09 07:21 UTC by uditbaliyan

Checklist:

- [ X ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ X ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ X ] My pull request targets the `main` branch of freeCodeCamp.
- [ X ] I have tested these changes either locally on my machine, or GitPod.

Closes #56192

2024-10-09 16:34 UTC, naomi-lgbt requested changes

2024-10-09 16:34 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-responsive-web-design/66ed9034f45ce3ece4053ebd.md
> +`max-width: 100%;`
```suggestion
`max-width: 100%;`

```

Restore the EOF new line.

2024-10-10 18:30 UTC, naomi-lgbt approved these changes

2024-10-18 11:40 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/quiz-responsive-web-design/66ed9034f45ce3ece4053ebd.md
> +`@media (min-resolution: 2dppx)`
Shouldn't this be `px`? `dppx` don't seem to be able to ensure what the actual resolution will be.

```suggestion
`@media (min-resolution: 2px)`
```

2024-10-18 12:04 UTC, gikf approved these changes

2024-10-18 13:19 UTC, merged

2024-10-18 13:24 UTC, gikf commented
Hi @uditbaliyan. Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝