Created quiz for CSS Pseudo Classes
freeCodeCamp/freeCodeCamp pull request #56659
Opened 2024-10-12 23:41 UTC by SahilWMI

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine or GitPod.

Closes #56183

2024-10-13 14:18 UTC, ilenia-magoni reviewed
please update the title of the PR to follow the title guidelines

2024-10-13 14:18 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +## --quiz--
you should not add new headers, please go through the file and remove this header. there is only one per file at the top

2024-10-13 14:18 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +:focus
```suggestion
`:focus`
```

use backticks around code things, please make this change in all the file

2024-10-13 14:18 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +::before
```suggestion
`::before`

```

let's not remove EOF lines

2024-10-13 14:52 UTC, SahilWMI reviewed
sorry for the mistakes, can you review and tell me if it needs any other correction?

corrections made so far:

- removeed quiz placeholdeer

- added backticks around lines of code.

2024-10-13 14:58 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
```suggestion
`:active`

```

let's not add extra empty lines

2024-10-13 14:58 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +_____ pseudo-class is used for the current active link.
```suggestion
Which pseudo-class is used for the current active link?
```

2024-10-13 14:58 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +
```suggestion
It selects elements that do not match a given selector.
```

an other extra line

2024-10-13 15:40 UTC, naomi-lgbt requested changes

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It is a CSS rule that creates additional content within an element when needed.
```suggestion
They are CSS rules that create additional content within an element when needed.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It is a property that adjusts an element's size or layout on the page.
```suggestion
They are properties that adjust an element's size or layout on the page.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +Which pseudo-class is used to select and style when an element is focused?
```suggestion
Which pseudo-class is used to select and style an element when it's focused?
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It makes your element float around the screen
```suggestion
It makes your element float around the screen.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It hides elements on click
```suggestion
It hides elements on click.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It styles an element when you hover over it
```suggestion
It styles an element when you hover over it.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It styles checked inputs
```suggestion
It styles checked inputs.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +Which one of these is not a Location pseudo-class?
```suggestion
Which one of these is not a location pseudo-class?
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +Which of the following selects the 3rd child in a row?
```suggestion
Which of the following selects the third list item?
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It selects the 4th child
```suggestion
It selects the fourth child.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It selects the last child
```suggestion
It selects the last child.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It selects all children
```suggestion
It selects all children.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It styles odd children
```suggestion
It styles odd children.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It selects the first child element
```suggestion
It selects the first child element.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It selects the middle element
```suggestion
It selects the middle element.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It selects every element in a group
```suggestion
It selects every element in a group.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +It selects the last child element
```suggestion
It selects the last sibling element.
```

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +Use ____ to select the second item in a list.
This one has not been addressed.

2024-10-13 15:40 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/quiz-css-pseudo-classes/66ed9002f45ce3ece4053eb6.md
> +`::before`
This one is not resolved either.

2024-10-13 15:50 UTC, SahilWMI reviewed
Fixed grammar, terminologies and updated questions.

2024-10-13 15:52 UTC, SahilWMI reviewed
fixed even more grammar and added EOF-lines.

2024-10-14 17:50 UTC, naomi-lgbt approved these changes

2024-10-15 08:58 UTC, ilenia-magoni approved these changes

2024-10-15 08:59 UTC, ilenia-magoni commented
Hi @SahilWMI . Congrats on your first pull request (PR)! 🎉

Thank you for your contribution to the page! 👍
We are happy to accept these changes and look forward to future contributions. 📝

2024-10-15 08:59 UTC, merged