fix(ui): use noto jp sans font
freeCodeCamp/freeCodeCamp pull request #56670
Opened 2024-10-14 02:01 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #44955

My hope is that the Japanese font files actually loaded.  I don't know how to dynamically change the navigator language and I was not aware of any existing tests in this repository that I can leverage for font testing. I will want to add one ideally before this gets merged.

2024-10-14 02:49 UTC, a2937 commented
Dang. Well of navigator doesn't exist , I guess there is another way to tell if the page is Japanese.

2024-10-14 18:00 UTC, naomi-lgbt requested changes
We should rarely, if ever, be using loose equality.

2024-10-14 18:00 UTC, naomi-lgbt commented on client/src/components/layouts/default.tsx
> +    clientLocale == 'japanese' ? jpSansLightURL : latoLightURL;
```suggestion
    clientLocale === 'japanese' ? jpSansLightURL : latoLightURL;
```

2024-10-14 18:00 UTC, naomi-lgbt commented on client/src/components/layouts/default.tsx
> +    clientLocale == 'japanese' ? jpSansRegularURL : latoRegularURL;
```suggestion
    clientLocale === 'japanese' ? jpSansRegularURL : latoRegularURL;
```

2024-10-14 18:00 UTC, naomi-lgbt commented on client/src/components/layouts/default.tsx
> +  const boldFontUrl = clientLocale == 'japanese' ? jpSansBoldURL : latoBoldURL;
```suggestion
  const boldFontUrl = clientLocale === 'japanese' ? jpSansBoldURL : latoBoldURL;
```

2024-10-14 18:43 UTC, naomi-lgbt approved these changes

2024-10-15 14:37 UTC, a2937 commented
I still need to write a test for this. But I'm a little stumped on how to write one that will work with what we're doing here; and is globalization friendly.

2024-10-15 14:59 UTC, ojeytonwilliams commented
For testing, I think it would make sense to create a unit test and mock env.json. That should let you create the default layout with and without the Japanese locale and confirm that it has the right font links each time.

2024-10-15 18:56 UTC, a2937 commented
I've hit a road block. The test I wrote doesn't work in the slightest. The font elements are just missing.

2024-10-16 04:28 UTC, sidemt requested changes

2024-10-16 08:46 UTC, ojeytonwilliams commented
>I've hit a road block. The test I wrote doesn't work in the slightest. The font elements are just missing.

Yeah, this is more involved than I thought. In principle we can setup Mock Service Worker, mock `window.matchMedia`, provide a user in response to the fetch request etc. etc.  It's a lot just to test if a font is used!

While I do think we should improve our client unit tests (and MSW would help with that), it's excessive for this particular feature. We should wait until we have time to improve the tests more generally.

2024-10-16 11:01 UTC, sidemt requested changes

2024-10-17 12:58 UTC, sidemt requested changes

2024-10-18 15:17 UTC, a2937 commented
I was afraid of something weird like that happening. I removed the fragment and that seemed to have gotten things working again.

2024-10-21 08:11 UTC, sidemt requested changes
Thanks, one last thing.

2024-10-21 12:56 UTC, sidemt approved these changes
LGTM 👍 Thank you so much for your work!

2024-10-21 12:56 UTC, merged