chore(curriculum): add colored markers to new cert
freeCodeCamp/freeCodeCamp pull request #56718
Opened 2024-10-17 09:14 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/592

2024-10-19 11:07 UTC, zairahira approved these changes

2024-10-25 16:21 UTC, Dario-DC commented on client/i18n/locales/english/intro.json
> +          "In this course, you'll build a set of colored markers. You'll practice different ways to set color values and how to pair colors with each other."
```suggestion
          "In this workshop, you'll build a set of colored markers. You'll practice different ways to set color values and how to pair colors with each other."
```

2024-10-25 16:21 UTC, Dario-DC commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/61696ef7ac756c829f9e4048.md
> +In this project you'll work with an external CSS file to style the page. We've already created a `styles.css` file for you. But before you can use it, you'll need to link it to the page.
```suggestion
In this project you'll work with an external CSS file to style the page. A `styles.css` file has been already created for you. But before you can use it, you'll need to link it to the page.
```

2024-10-25 16:21 UTC, Dario-DC commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/617bbb6b97a83f6d1f7d6e38.md
> +Now that you''ve practiced with secondary colors, you'll review how to create <dfn>tertiary colors</dfn>. Tertiary colors are created by combining a primary with a nearby secondary color.
```suggestion
Now that you've practiced with secondary colors, you'll review how to create <dfn>tertiary colors</dfn>. Tertiary colors are created by combining a primary with a nearby secondary color.
```

2024-10-25 16:21 UTC, Dario-DC commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/61b0936d9e7fc020b43b1bb8.md
> +It looks like your sleeve disappeared, but don't worry -- it's still there. What happened is that your new cap `div` is taking up the entire width of the marker, and is pushing the sleeve down to the
```suggestion
It looks like your sleeve disappeared, but don't worry — it's still there. What happened is that your new cap `div` is taking up the entire width of the marker, and is pushing the sleeve down to the next line.
```

2024-10-28 09:41 UTC, Dario-DC reviewed
I would stick to "build" but I don't have a strong opinion on this.

2024-10-28 09:41 UTC, Dario-DC commented on client/i18n/locales/english/intro.json
> +        "title": "Create a Set of Colored Markers",
```suggestion
        "title": "Build a Set of Colored Markers",
```

2024-10-28 09:41 UTC, Dario-DC commented on client/src/pages/learn/front-end-development/workshop-colored-markers/index.md
> +title: Introduction to the Create a Set of Colored Markers
```suggestion
title: Introduction to the Build a Set of Colored Markers
```

2024-10-28 09:41 UTC, Dario-DC commented on client/src/pages/learn/front-end-development/workshop-colored-markers/index.md
> +## Introduction to the Create a Set of Colored Markers
```suggestion
## Introduction to the Build a Set of Colored Markers
```

2024-10-28 09:41 UTC, Dario-DC commented on curriculum/challenges/_meta/workshop-colored-markers/meta.json
> +  "name": "Create a Set of Colored Markers",
```suggestion
  "name": "Build a Set of Colored Markers",
```

2024-10-28 11:42 UTC, Sembauke requested changes

2024-10-28 11:42 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/616d3a67ccf800ad94ec89ae.md
> +Now you'll add some elements that you'll eventually style into color markers.
```suggestion
Now, you'll add some elements that you'll eventually style as color markers.
```

2024-10-28 11:42 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/616d3a67ccf800ad94ec89ae.md
> +First, within the `body` element, add a `div` element and set its `class` attribute to `container`. Make sure the `div` element is below the `h1` element.
```suggestion
First, within the `body` element, add a `div` element with a `class` attribute set to `container`. Make sure the `div` element is placed below the `h1` element.
```

2024-10-28 11:42 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/616d525007b8c5d8b3308b1c.md
> +Your marker would look better if it was centered on the page. An easy way to do that is with the `margin` <dfn>shorthand property</dfn>.
```suggestion
Your marker would look better if it were centered on the page. An easy way to do this is by using the `margin` <dfn>shorthand property</dfn>.
```

2024-10-28 11:42 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/61764c602bee6974e7790f35.md
> +To give the markers different colors, you will need to add a unique class to each one. Multiple classes can be added to an element by listing them in the `class` attribute and separating them with a
```suggestion
To give the markers different colors, you’ll need to add a unique class to each one. You can add multiple classes to an element by listing them in the `class` attribute and separating them with a space. For example, the following code adds both the `animal` and `dog` classes to a `div` element:
```

2024-10-28 11:42 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/61764fdda535587e1fefb3aa.md
> +Add the class `two` to the second marker `div`, and add the class `three` to the third marker `div`.
```suggestion
Add the class `two` to the second marker `div` and the class `three` to the third marker `div`.
```

2024-10-28 11:42 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/617b65579ce424bf5f02ca73.md
> +As you have learned in the lectures, there are two main color models: the <dfn>additive</dfn> RGB (red, green, blue) model used in electronic devices, and the <dfn>subtractive</dfn> CMYK (cyan, magen
```suggestion
As you have learned in the lectures, there are two main color models: the <dfn>additive</dfn> RGB (red, green, blue) model, used in electronic devices, and the <dfn>subtractive</dfn> CMYK (cyan, magenta, yellow, black) model, used in print.
```

2024-10-28 11:42 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-colored-markers/617b65579ce424bf5f02ca73.md
> +In this project, you'll work with the RGB model. This means that colors begin as black, and change as different levels of red, green, and blue are introduced. An easy way to see this is with the CSS
```suggestion
In this project, you'll work with the RGB model. This means colors start as black and change as different levels of red, green, and blue are introduced. An easy way to see this is with the CSS `rgb` function.
```

2024-10-28 12:39 UTC, Sembauke requested changes

2024-10-28 17:42 UTC, Sembauke approved these changes

2024-10-28 17:42 UTC, merged