feat(curriculum): add registration form workshop to cert
freeCodeCamp/freeCodeCamp pull request #56724
Opened 2024-10-17 14:01 UTC by jdwilkin4

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/593

2024-10-19 10:59 UTC, zairahira approved these changes

2024-10-22 08:31 UTC, Sembauke requested changes

2024-10-22 08:31 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60f02e7361b68405e27b62a5.md
> +Within the `body`, provide a heading context for the content, by adding an `h1` with the text `Registration Form`.
```suggestion
Within the `body`, add a heading to give context to the form by using an `h1` element with the text `Registration Form`.
```

2024-10-22 08:31 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60f02e7361b68405e27b62a5.md
> +Within the `body`, provide a heading context for the content, by adding an `h1` with the text `Registration Form`.
It wasn't clear to me what I had to do here.

2024-10-22 08:31 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60f1922fcbd2410527b3bd89.md
> +Remember that the `vh` unit stands for viewport height, and is equal to 1% of the `height` of the viewport. This makes it relative to the viewport height.
```suggestion
Remember, the `vh` unit stands for viewport height and represents 1% of the viewport's total height. This makes it relative to the viewport's height.
```

2024-10-22 08:31 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60f5c3e399ff1a05629964e4.md
> +As suggested by the title, you are creating a form. So, after the `p` element, insert a `form` with an `action` attribute targeting `https://register-demo.freecodecamp.org`.
```suggestion
As the title suggests, you are creating a form. After the `p` element, insert a `form` element with an `action` attribute that targets `https://register-demo.freecodecamp.org`.
```

2024-10-22 08:31 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60f5d2776c854e069560fbe6.md
> +The first `fieldset` will hold name, email, and password fields. Start by adding four `label` elements to the first `fieldset`.
```suggestion
The first `fieldset` will contain the name, email, and password fields. Start by adding four `label` elements inside the first `fieldset`.
```

2024-10-22 08:31 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60f85a62fb30c80bcea0cedb.md
> +Users will be allowed to choose either a `Personal` or `Business`.
This doesn't make much sense. I think there is some text missing.

```suggestion
Users will be able to choose whether the workshop is for `Personal` or `Business` purposes.
```

2024-10-22 08:31 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60f8604682407e0d017bbf7f.md
> +Within each corresponding `label` element, and immediately after the `input` element, add a space and add the following text:
```suggestion
Within each corresponding `label` element, and immediately after the `input` element, add a space followed by the following text:
```

2024-10-22 09:09 UTC, Sembauke requested changes

2024-10-22 09:09 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/60ffe3936796ac04959285a9.md
> +Fix this, by setting the `color` to `#ffffff`, and setting their `min-height` to `2em`.
```suggestion
Fix this by setting the `color` to `#ffffff`, and setting their `min-height` to `2em`.
```

2024-10-22 09:09 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/workshop-registration-form/6537e0be715fcb57d31ba8c3.md
> +a new selector in the CSS.
```suggestion
Lastly, change the text color of the `terms and conditions` link element to `#dfdfe2` by adding a new selector in the CSS.
```

2024-10-25 09:01 UTC, Sembauke approved these changes

2024-10-25 09:01 UTC, merged