fix:show leave page confirmation if project code not saved
freeCodeCamp/freeCodeCamp pull request #56764
Opened 2024-10-21 08:19 UTC by kamalxdev

Checklist:

- [x ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x ] My pull request targets the `main` branch of freeCodeCamp.
- [x ] I have tested these changes either locally on my machine, or GitPod.

Closes #46810 

[Screencast from 2024-10-21 13-39-31.webm](https://github.com/user-attachments/assets/d15935a8-a738-45c5-814f-4dc505b8335b)

2024-10-29 07:42 UTC, Sembauke requested changes
Hey @kamalxdev,
Could we do something like this? It is a little bit cleaner.

```js
    const hasSaved = savedChallenges[0]?.challengeFiles;

    for (let index = 0; index < challengeFiles.length; index++) {
      if (!hasSaved) isFilesSaved = false;

      const hasChangedContentAfterSave =
        savedChallenges[0]?.challengeFiles?.[index]?.contents !=
        challengeFiles?.[index]?.contents;

      if (hasChangedContentAfterSave) isFilesSaved = false;
    }
```

2024-10-29 08:24 UTC, kamalxdev commented
> Hey @kamalxdev, Could we do something like this? It is a little bit cleaner.
> 
> ```js
>     const hasSaved = savedChallenges[0]?.challengeFiles;
> 
>     for (let index = 0; index < challengeFiles.length; index++) {
>       if (!hasSaved) isFilesSaved = false;
> 
>       const hasChangedContentAfterSave =
>         savedChallenges[0]?.challengeFiles?.[index]?.contents !=
>         challengeFiles?.[index]?.contents;
> 
>       if (hasChangedContentAfterSave) isFilesSaved = false;
>     }
> ```

You mean like this: 
`
  useEffect(() => {
    let isFilesSaved = true;

    const savedChallengeFiles=savedChallenges[0]?.challengeFiles;

    if (!challengeFiles) return;
    
    for (let index = 0; index < challengeFiles.length; index++) {
      let hasChangedContentAfterSave = savedChallengeFiles && savedChallengeFiles[index]?.contents !=challengeFiles[index]?.contents;

      if (!savedChallengeFiles || hasChangedContentAfterSave) {
        isFilesSaved = false;
      }
    }

    if (isFilesSaved) return;

    function onbeforeUnload(e: BeforeUnloadEvent) {
      e.preventDefault();
    }

    window.addEventListener('beforeunload', onbeforeUnload);

    return () => {
      window.removeEventListener('beforeunload', onbeforeUnload);
    };
  }, [challengeFiles, savedChallenges]);
`

2024-10-29 08:31 UTC, Sembauke commented
Sure, just make sure `hasChangedContentAfterSave` is a constant!

2024-10-29 08:33 UTC, kamalxdev commented
> Sure, just make sure `hasChangedContentAfterSave` is a constant!

okay

2024-10-29 08:37 UTC, kamalxdev commented
@Sembauke  changes updated

2024-11-05 09:19 UTC, ojeytonwilliams requested changes
The current project is only guaranteed to be first saved project if there's one saved challenge, so this can break if more than one project are saved.

To fix this, and DRY the codebase a little, you could create a `savedChallenge` selector, to get the current saved info for the current challenge. There are a few places in the codebase where we want the current saved challenge and they could all use it.

2024-11-05 09:19 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/show.tsx
> +
```suggestion
  // Show leave page confirmation if code is not saved
```
Nit

2024-11-05 09:19 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/show.tsx
> +      window.removeEventListener('beforeunload', onbeforeUnload);
```suggestion
    const savedChallengeFiles = savedChallenge?.challengeFiles;
    const savedContents = savedChallengeFiles?.map(file => file.contents);
    const currentContents = challengeFiles?.map(file => file.contents);

    const isSaved =
      savedChallengeFiles && isEqual(savedContents, currentContents);

    function handleBeforeUnload(e: BeforeUnloadEvent) {
      e.preventDefault();
    }

    if (!isSaved) window.addEventListener('beforeunload', handleBeforeUnload);

    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
```
This is a bit simpler and easier to read, I think. `isEqual` would need importing from `lodash-es`, though. `savedChallenge` would come from the selector I mentioned above.

2024-12-17 10:37 UTC, closed without merging