feat(client): display intro of FSD blocks in block header
freeCodeCamp/freeCodeCamp pull request #56808
Opened 2024-10-23 23:31 UTC by huyenltnguyen

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

There is an inconsistency in the FSD display in that some blocks have their intro immediately present on the screen, while others keep the intro in the accordion panel, which only show when the accordion is expanded.

I think we should have the intro displayed at all times because the block titles are now just "Build X", rather than "Learn X by building Y".

<details>
  <summary>Screenshots</summary>

  | Before | After |
  | --- | --- |
  | <img width="778" alt="Screenshot 2024-10-24 at 06 07 54" src="https://github.com/user-attachments/assets/a300e8d6-ffd3-48a8-aed0-5475730e7469"> | <img width="790" alt="Screenshot 2024-10-24 at 06 25 03" src="https://github.com/user-attachments/assets/ca14abbb-b883-4c2e-9560-2a896799a735"> |
</details>

2024-10-24 00:55 UTC, moT01 commented on client/src/templates/Introduction/components/block.tsx
> +                )}
I think I would vote to just clone the component again.

2024-10-24 00:59 UTC, moT01 reviewed
I would be fine going with this as-is, but I left a comment below that I would lean towards cloning the grid layout for the fsd stuff. Make the change if you want @huyenltnguyen - or just leave it and let me know.

Edit: another note - I like this for consistency for now, but we may come up with something in the future that moves the intros back to hidden. I think I might prefer that - but like I said, consistency for now.

2024-10-25 17:34 UTC, moT01 approved these changes
LGTM 🎉 

Only thing I notice is that the text isn't consistent in the blocks intros:

<img width="942" alt="Screenshot 2024-10-25 at 12 33 18 PM" src="https://github.com/user-attachments/assets/3f5204e9-0df4-4415-94e2-35186050cbfd">

^ notice the indentation and the padding at the bottom. I would be fine getting this in as-is and keep iterating on it - or feel free to make adjustments here.

2024-11-07 08:40 UTC, ojeytonwilliams requested changes
Now that the text appears in the block header the spacing is a little off and the border overlaps with the button
![image](https://github.com/user-attachments/assets/4f233006-77d8-4801-92a9-5892b8851523)

2024-11-07 08:40 UTC, ojeytonwilliams commented on client/src/templates/Introduction/components/block-header.tsx
> +        {blockIntroArr && blockIntroArr.length && (
```suggestion
        {!isEmpty(blockIntroArr) && (
```
Nitpicky, I know, but this is more declarative. (btw, we need to get `isEmpty` from `lodash-es` for reasons of tree shaking).

2024-11-07 08:40 UTC, ojeytonwilliams commented on client/src/templates/Introduction/components/block.tsx
> +        {' '}
```suggestion
```
It doesn't appear to do anything. I'll get rid of the rest in another PR.

2024-11-07 08:40 UTC, ojeytonwilliams commented on client/src/templates/Introduction/components/block.tsx
> +      </>
```suggestion
```
It'll need formatting as well :(

2024-11-07 08:40 UTC, ojeytonwilliams commented on client/src/templates/Introduction/components/block.tsx
>       * Example: https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app
The meta will need updating so that the old challenges aren't messed up when LegacyChallengeGridBlock and ChallengeGridBlock diverge.

2024-11-12 14:43 UTC, ojeytonwilliams commented on client/src/templates/Introduction/components/block.tsx
>       * Example: https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app
Sorry, Huyen, that's what confused me, I think.

How about this: I'll create another PR to add the blockLayout to all the old blocks and we can get rid of the `if(!blockLayout)...` stuff?

2024-11-12 17:53 UTC, ojeytonwilliams commented on client/src/templates/Introduction/components/block.tsx
>       * Example: https://www.freecodecamp.org/learn/2022/responsive-web-design/#learn-html-by-building-a-cat-photo-app
Here it is: https://github.com/freeCodeCamp/freeCodeCamp/pull/57138

2024-11-13 08:25 UTC, ojeytonwilliams approved these changes
LGTM 👍

2024-11-13 08:27 UTC, merged