feat: add a css linter
freeCodeCamp/freeCodeCamp pull request #56823
Opened 2024-10-24 15:29 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #52532

There are a lot of complaints here.

2024-10-25 12:38 UTC, ahmaxed commented
Thanks for the pr. I believe code-factor is using stylelint as well. 
Could you make sure our stylelint and code-factor's both share the same configuration.
Once the changes are implemented on the css files, the codefactor errors should go away.

2024-10-25 14:33 UTC, a2937 commented
So it was the additional stylelint config that made codefactor.io point out those tons of extra issues. Very neat. 

https://support.codefactor.io/i24-analysis-tools-open-source

2024-10-25 14:49 UTC, a2937 commented
I had to reset things to avoid a merge conflict with pnpm-lock of all things.

2024-12-23 12:03 UTC, ilenia-magoni commented
there are more merge conflicts

2024-12-23 15:11 UTC, a2937 commented
Okay that has been fixed.

2024-12-23 15:15 UTC, naomi-lgbt approved these changes

2025-01-03 11:00 UTC, ojeytonwilliams requested changes
Could we add this into the root lint script? Creating a new root script `lint:client-css` should do the trick. Otherwise it will not be checked in CI.

Also, while it's not strictly necessary, it would be nice if this was checked via .lintstagedrc.js, so that we get fewer PRs with lint failures.

2025-01-13 09:03 UTC, ojeytonwilliams requested changes

2025-01-13 09:03 UTC, ojeytonwilliams commented on .lintstagedrc.js
> +      return 'pnpm run lint:client-css';
```suggestion
      return 'pnpm run stylelint --fix .';
```
It's better to fix, if possible, so we get fewer formatting issues in PRs.

2025-01-13 09:03 UTC, ojeytonwilliams commented on .lintstagedrc.js
> +      return files.map(filename => `stylelint '${filename}'`);
```suggestion
      return files.map(filename => `stylelint --fix '${filename}'`);
```

2025-01-13 09:03 UTC, ojeytonwilliams commented on .lintstagedrc.js
line 28 needs to be

```js
  '*.!(js|ts|tsx|css)': files => {
  ```
  
since we're formatting the css in its own step.

2025-01-13 15:13 UTC, ojeytonwilliams approved these changes
Cheers, Anna. LGTM :+1:

2025-01-13 15:50 UTC, merged