fix(curriculum): update descriptions and tests for business card lab
freeCodeCamp/freeCodeCamp pull request #56884
Opened 2024-10-26 05:28 UTC by gagan-bhullar-tech

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56868

2024-10-26 07:41 UTC, ilenia-magoni requested changes
I can't leave a comment on line 67 and 81, but those can become `assert.isTrue()`

2024-10-26 07:41 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-business-card/6690e10ebe2181212abc9652.md
>  assert(document.querySelector('div')?.getAttribute('class') === 'business-card');
```suggestion
assert.strictEqual(document.querySelector('div')?.getAttribute('class'), 'business-card');
```

2024-10-26 07:41 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-business-card/6690e10ebe2181212abc9652.md
>  assert(new __helpers.CSSHelp(document).getStyle('.business-card')?.backgroundColor);
```suggestion
assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('.business-card')?.backgroundColor);
```

2024-10-26 17:58 UTC, gagan-bhullar-tech commented
@ilenia-magoni updated PR.

2024-10-26 18:04 UTC, ilenia-magoni approved these changes

2024-10-28 07:55 UTC, Sembauke approved these changes

2024-10-28 07:55 UTC, merged