Revise some of the tests in lab-travel-agency-page (#56861)
freeCodeCamp/freeCodeCamp pull request #56881
Opened 2024-10-25 23:01 UTC by CracktheDom

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56861

2024-10-26 07:35 UTC, ilenia-magoni requested changes
The issue requested breaking the hint/test into two, one for the order of the elements, one for the content of the `p` element.

Also please use [specific assert methods](https://www.chaijs.com/api/assert/), and [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

2024-10-26 07:35 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +assert(h1Element && pElement && h1Element.nextElementSibling === pElement)
```suggestion
assert.strictEqual(h1Element.nextElementSibling, pElement)
```

2024-10-26 07:35 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +assert(pElement && pElement.textContext.trim() !== "")
```suggestion
assert.isNotEmpty(pElement.textContext.trim())
```

2024-10-26 07:50 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
>  You should have a `p` element introducing the travel opportunities below the `h1` element.
```suggestion
You should have a `p` element below the `h1` element.
```

2024-10-26 07:50 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +assert(h1Element && pElement && h1Element.nextElementSibling === pElement)
````suggestion
assert.strictEqual(document.querySelector('h1')?.nextElementSibling, document.querySelector('p'))
```
````
Splitting into two tests.

2024-10-26 07:50 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +assert(pElement && pElement.textContext.trim() !== "")
````suggestion
Your first `p` element should introduce the travel opportunities.

```js
assert.isNotEmpty(document.querySelector('p')?.textContent?.trim());
````

2024-10-26 07:50 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
>  You should have a `p` element introducing briefly the various packages below your first `h2` element.
```suggestion
You should have a `p` element below your first `h2` element.
```

2024-10-26 07:50 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +assert(h2Element && pElement && h2Element.nextElementSibling === pElement)
````suggestion
assert.strictEqual(document.querySelector('h2')?.nextElementSibling, document.querySelectorAll('p')?.[1])
```
````
Splitting into two tests.

2024-10-26 07:50 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
> +assert(pElement && pElement.textContext.trim() !== "")
````suggestion
Your second `p` element should introduce briefly the various packages.

```js
assert.isNotEmpty(document.querySelectorAll('p')?.[1]?.textContent?.trim())
````

2024-10-26 19:50 UTC, CracktheDom reviewed
Add suggestions

2024-10-27 07:42 UTC, ilenia-magoni approved these changes

2024-10-27 08:19 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
>  You should have a `p` element introducing the travel opportunities below the `h1` element.
Looks like two of these were missed missed

2024-10-27 09:07 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-travel-agency-page/669e2f60e83c011754f711f9.md
>  You should have a `p` element introducing briefly the various packages below your first `h2` element.
You have missed this one @CracktheDom

2024-10-28 06:36 UTC, gikf approved these changes

2024-10-28 06:36 UTC, merged