fix(learn): improve description of method in JavaScript
freeCodeCamp/freeCodeCamp pull request #56972
Opened 2024-10-29 04:02 UTC by dejavuwl

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55651 

Here is my first PR.

2024-10-29 08:54 UTC, ilenia-magoni commented
This is not enough to solve the issue. It would need a big reordering of steps and topics

2024-10-29 08:56 UTC, Sembauke requested changes

2024-10-29 08:56 UTC, Sembauke commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660f0a55847d6cc485f29ba5.md
> +An <dfn>object</dfn> is like a container that contains some data and operations that can be used to perform certain tasks. A <dfn>method</dfn> in JavaScript is a operation that's associated with cert
```suggestion
A <dfn>function</dfn> is like a container that contains some data and operations that can be used to perform certain tasks. A <dfn>method</dfn> in JavaScript is a operation that's associated with certain values or objects. An example you've already encountered is the `.log()` method, which is part of the `console` object.
```

2024-11-01 04:24 UTC, dejavuwl commented
I will try to make some reordering  to fix it later.

2024-12-12 13:40 UTC, ilenia-magoni commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-introductory-javascript-by-building-a-pyramid-generator/660f0a55847d6cc485f29ba5.md
> +An <dfn>object</dfn> is like a container that contains some data and operations that can be used to perform certain tasks. A <dfn>method</dfn> in JavaScript is a operation that's associated with cert
you never fixed this @dejavuwl

2024-12-12 13:41 UTC, ilenia-magoni commented on curriculum/i18n-curriculum
this should not be in the PR

2024-12-12 13:41 UTC, ilenia-magoni commented
closing as stale

2024-12-12 13:41 UTC, closed without merging