feat(curriculum): Added Bash and SQL Quiz
freeCodeCamp/freeCodeCamp pull request #56974
Opened 2024-10-29 09:13 UTC by AbhinavTheDev

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #56233

2024-10-29 11:04 UTC, Sembauke requested changes

2024-10-29 11:04 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What does SQL stands for?
```suggestion
What does SQL stand for?
```

2024-10-29 11:04 UTC, Sembauke commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +They are ophaned.
```suggestion
They are orphaned.
```

2024-10-30 02:02 UTC, moT01 requested changes
All of the code (or fake code) should be placed in backticks @AbhinavTheDev. For example, `GENERATE DATABASE`, `CREATE DATABASE`, `SELECT []`, etc. should be `` `GENERATE DATABASE` ``, `` `CREATE DATABASE` ``, `` `SELECT []` ``. along with all the others.

2024-11-15 14:33 UTC, zairahira approved these changes

2024-11-15 17:40 UTC, moT01 requested changes
Pretty minor, but some more small improvements - or maybe just my preference in the case of adding the periods

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What does FOREIGN KEY establish?
```suggestion
What does `FOREIGN KEY` establish?
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +A unique identifier key
```suggestion
A unique identifier key.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +A primary key
```suggestion
A primary key.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +A null constraint
```suggestion
A null constraint.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Only foreign keys
```suggestion
Only foreign keys.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Only timestamps
```suggestion
Only timestamps.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Only primary keys
```suggestion
Only primary keys.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Foreign keys and additional data
```suggestion
Foreign keys and additional data.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Primary Key
```suggestion
Primary Key.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Unique Key
```suggestion
Unique Key.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Composite Key
```suggestion
Composite Key.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Foreign Key
```suggestion
Foreign Key.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Multi-Valued Dependencies
```suggestion
Multi-Valued Dependencies.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Partial Dependencies
```suggestion
Partial Dependencies.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +All Dependencies
```suggestion
All Dependencies.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +Transitive Dependencies
```suggestion
Transitive Dependencies.
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What happens to child records when implementing "ON DELETE CASCADE"?
```suggestion
What happens to child records when implementing `ON DELETE CASCADE`?
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What is the "COALESCE" function used for?
```suggestion
What is the `COALESCE` function used for?
```

2024-11-15 17:40 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/quiz-bash-and-sql/66f1affc0ef4fcca423d4688.md
> +What's the main risk of using "SELECT *" in production code?
```suggestion
What's the main risk of using `SELECT *` in production code?
```

2024-11-15 17:41 UTC, moT01 approved these changes

2024-11-15 18:57 UTC, Sembauke approved these changes

2024-11-15 18:57 UTC, merged