chore: update react-instancesearch to v7
freeCodeCamp/freeCodeCamp pull request #57020
Opened 2024-11-01 10:22 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-11-06 23:18 UTC, huyenltnguyen reviewed
I finally had the courage to click on this PR 😛 

Not sure what made you feel like picking this one, but that means less hair-pulling for me, so thank you 😄 

---
I added some small changes to the PR. I'll need to go through the PR again to digest the changes, though I tested the component locally and things seem to be working as intended.

2024-11-07 07:46 UTC, Sembauke commented on client/src/components/search/searchBar/search-bar.tsx
> -    updateSearchQuery(query);
Yes, this was fully intentional!

2024-11-07 20:23 UTC, huyenltnguyen reviewed
I just have a couple of questions left. But everything else looks good to me 👍

2024-11-07 20:51 UTC, huyenltnguyen approved these changes

2024-11-08 12:10 UTC, ojeytonwilliams requested changes
Other than the highlighting, this seems to work well. I don't think we need to force the types, though:

2024-11-08 12:45 UTC, Sembauke commented
@ojeytonwilliams I agree, could you open an issue for that? 

All changes have been applied.

2024-11-08 13:20 UTC, ojeytonwilliams approved these changes
LGTM :+1:, thanks @Sembauke

2024-11-08 13:20 UTC, merged