chore(curriculum): remove dsa blocks from JS modules
freeCodeCamp/freeCodeCamp pull request #57051
Opened 2024-11-05 09:34 UTC by Dario-DC

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/issues/633

2024-11-07 16:45 UTC, jdwilkin4 approved these changes

2024-11-07 17:43 UTC, jdwilkin4 requested changes
Actually, looking at the issues list, a few of these quiz PR's are still in review.
let's hold off of delete those in this PR. 
Any hacktoberfest issue that is still open should not be deleted 
https://github.com/freeCodeCamp/freeCodeCamp/issues/56170

At quick glance, that looks like the dynamic programming quiz and graphs and trees. I might be missing one, so I would double that open PR list to make sure.

Then in a separate PR once those hacktoberfest PR are merged in, we can remove them from the cert

2024-11-07 17:55 UTC, ilenia-magoni commented
Hacktoberfest has ended, if there was stalling to allow for people to get their hacktoberfest badges, that time has ended

2024-11-07 18:09 UTC, jdwilkin4 commented
I feel like we should get this one approved and merged in.
It looks like they worked really hard on it. I would feel bad if we just closed it since they are a first timer.
https://github.com/freeCodeCamp/freeCodeCamp/pull/56442

Then it can be removed in this PR along with the others

2024-11-13 16:25 UTC, jdwilkin4 approved these changes

2024-11-13 21:05 UTC, moT01 approved these changes

2024-11-13 21:05 UTC, merged