fix: separate footer from hits
freeCodeCamp/freeCodeCamp pull request #57130
Opened 2024-11-11 15:33 UTC by Sembauke

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #57100

2024-11-15 13:39 UTC, ojeytonwilliams requested changes

2024-11-15 13:39 UTC, ojeytonwilliams commented on client/src/components/search/searchBar/search-bar-footer.tsx
> +  const searchUrl = searchPageUrl;
```suggestion
```
Using `searchPageUrl` directly seems fine, tbh.

2024-11-15 13:39 UTC, ojeytonwilliams commented on client/src/components/search/searchBar/search-bar-footer.tsx
> +  if (hasHits && query) {
Since `!query` means we return `null`, you can just do that first and simplify the logic to `if (hasHits)`. That or `return hasHits ? ... : ...`

2024-11-15 13:39 UTC, ojeytonwilliams commented on client/src/components/search/searchBar/search-bar-footer.tsx
> +    );
I think this also needs to react to mouse enters and leaves. `onMouseEnter` and `onMouseLeave` should do the trick.

2024-11-21 20:21 UTC, moT01 approved these changes

2024-11-28 10:07 UTC, Sembauke commented
@ojeytonwilliams Could you give this another look?

2024-12-04 11:20 UTC, ojeytonwilliams approved these changes
Sorry for the delay, Sem. LGTM :+1:

2024-12-04 11:21 UTC, merged