chore(curriculum): update book inventory app tests
freeCodeCamp/freeCodeCamp pull request #57193
Opened 2024-11-16 21:39 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

This updates the assertions in the lab book inventory app to use proper assertion methods.

2024-11-18 09:54 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"] span[class="status"]')?.border);
```suggestion
assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"] span[class="status"]')?.border);
```

properties are all present, if they do not have a value it's an empty string

2024-11-18 10:08 UTC, ilenia-magoni requested changes
`exists` is not appropriate for testing a property from `getStyle`, all the properties are always strings, empty if there is no value. Please use `assert.isNotEmpty()`

2024-11-18 10:08 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="read"] span[class="status"]')?.border);
```suggestion
assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="read"] span[class="status"]')?.border);
```

2024-11-18 10:08 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="read"] span[class="status"]')?.backgroundImage);
```suggestion
assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="read"] span[class="status"]')?.backgroundImage);
```

and so on please every time there is a property being checked

2024-11-18 12:14 UTC, a2937 commented
I understand.

2024-11-18 17:31 UTC, majestic-owl448 requested changes

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="in-progress"] span[class="status"]')?.backgroundImage);
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(selector1?.height || selector2?.height);
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(selector1?.width || selector2?.width);
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(selector1?.padding || selector2?.padding);
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
>  ```
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('span[class^="rate"] > span')?.getPropVal('border-radius'));
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('span[class^="rate"] > span')?.getPropVal('margin'));
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('span[class^="rate"] > span')?.getPropVal('height'));
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('span[class^="rate"] > span')?.getPropVal('width'));
here

2024-11-18 17:43 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(new __helpers.CSSHelp(document).getStyle('span[class^="rate"] > span')?.getPropVal('background-color'));
here

2024-11-19 11:19 UTC, ilenia-magoni requested changes

2024-11-19 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(selector1 || selector2);
```suggestion
assert.exists(selector1 || selector2);
```

2024-11-19 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(selector1?.width || selector2?.width);
```suggestion
assert.exists(selector1?.width || selector2?.width);
```

2024-11-19 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('span[class^="rate"] > span'));
```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('span[class^="rate"] > span'));
```

2024-11-19 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(selector1 || selector2);
```suggestion
assert.exists(selector1 || selector2);
```

2024-11-19 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(selector1 || selector2 || selector3 || selector4);
```suggestion
assert.exists(selector1 || selector2 || selector3 || selector4);
```

2024-11-19 11:19 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('span[class~="three"] span'));
```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('span[class~="three"] span'));
```

2024-11-19 16:11 UTC, ilenia-magoni requested changes

2024-11-19 16:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="read"]'));
`getStyle` returns `null` if the selector is not there. `exists` or `isNotNull` are more appropriate

```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="read"]'));
```

2024-11-19 16:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"]'));
```suggestion
assert.exist(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"]'));
```

2024-11-19 16:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="in-progress"]'));
```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="in-progress"]'));
```

2024-11-19 16:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"] span[class="status"]'));
```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"] span[class="status"]'));
```

2024-11-19 16:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="read"] span[class="status"]'));
```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="read"] span[class="status"]'));
```

2024-11-19 16:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(new __helpers.CSSHelp(document).getStyle('tr[class="in-progress"] span[class="status"]'));
```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="in-progress"] span[class="status"]'));
```

2024-11-19 16:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exists(selector1?.width || selector2?.width);
```suggestion
assert.isNotEmpty(selector1?.width || selector2?.width);
```

2024-11-19 16:15 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.isNotEmpty(selector1?.width || selector2?.width);
yep, sorry, wrong suggestion here

2024-11-19 16:16 UTC, ilenia-magoni requested changes

2024-11-19 16:16 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-book-inventory-app/66a207974c806a19d6607073.md
> +assert.exist(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"]'));
```suggestion
assert.exists(new __helpers.CSSHelp(document).getStyle('tr[class="to-read"]'));
```

2024-11-19 18:25 UTC, majestic-owl448 approved these changes

2024-11-21 05:49 UTC, moT01 approved these changes

2024-11-21 05:49 UTC, merged