feat(curriculum): add voting system lab
freeCodeCamp/freeCodeCamp pull request #57208
Opened 2024-11-18 16:10 UTC by zairahira

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes https://github.com/freeCodeCamp/CurriculumExpansion/pull/662/

2024-11-20 12:59 UTC, zairahira commented on curriculum/challenges/english/25-front-end-development/lab-voting-system/673b567e3ba535dda140d278.md
> +Option A: N votes
Is this better:

````md
```js
Poll Results:
OptionA: N votes
OptionB: N votes
.
.

/* 
sample output

Poll Results:
Turkey: 2 votes
Morocco: 1 votes
*/
```

````

2024-11-22 13:04 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-voting-system/673b567e3ba535dda140d278.md
> +Option A: N votes
that would be more clear for sure

2024-11-22 16:16 UTC, moT01 requested changes
This is a lot of fun @zairahira 🎉 I left comments on a few minor typos below. One other issue I has was that the tests were interfering me testing and debugging my code:

<details></summary>image</summary>

<img width="316" alt="Screenshot 2024-11-22 at 10 06 17 AM" src="https://github.com/user-attachments/assets/35dcdb34-838d-4364-8567-b026abe9ac99">

</details>

They are overwriting the things I add. I think we need to try and fix this. Can we do some reassignment to not overwrite the users polls/votes?

One other thing you could add is some user stories and tests like I mentioned on the bank account lab to have users add to their poll and make votes. e.g.

"You should have at least three options in your poll."
"Your poll should have at least three votes."

Not necessary to add that, but I think it makes it better.

2024-11-22 16:16 UTC, moT01 commented on curriculum/challenges/english/25-front-end-development/lab-voting-system/673b567e3ba535dda140d278.md
> +   - If the `option` does not exist in the poll, the function should return the message `Option "<option>" does not exist.`;
```suggestion
   - If the `option` does not exist in the poll, the function should return the message `Option "<option>" does not exist.`.
```

2024-12-06 11:37 UTC, zairahira commented
@moT01,

I have modified the tests to not use `poll.clear()` every time. Maybe this was interfering/overriding your solutions.

I have also added the following tests/user stories:

- You should have at least three options in your `poll`.
- Your `poll` should have at least three votes.

Let me know if this is good to go.

2024-12-07 16:12 UTC, Dario-DC reviewed
I still see the outcome of the last test in the console. Ideally, you should save a copy of the map, make your changes to test things, and then restore the map to how it was before the test.

Something like this:

```js
const pollCopy = new Map(poll);
try {
  poll.clear();
  // modify poll as needed
  // assert things
} finally {
  // the finally block is required for when the assert fails
  // otherwise you won't restore the map
  poll.clear();
  pollCopy.forEach((val, key) => {
    poll.set(key, val);
  });
}
```

2024-12-09 14:39 UTC, Dario-DC reviewed
In my previous review I forgot to mention that the title should be shortened. I think `Build a Voting System` is enough

2024-12-09 14:39 UTC, Dario-DC commented on client/i18n/locales/english/intro.json
> +        "title": "Build a Voting System Using Maps and Sets",
```suggestion
        "title": "Build a Voting System",
```

2024-12-09 14:39 UTC, Dario-DC commented on client/src/pages/learn/full-stack-developer/lab-voting-system/index.md
> +title: Introduction to the Build a Voting System Using Maps and Sets
```suggestion
title: Introduction to the Build a Voting System
```

2024-12-09 14:39 UTC, Dario-DC commented on client/src/pages/learn/full-stack-developer/lab-voting-system/index.md
> +## Introduction to the Build a Voting System Using Maps and Sets
```suggestion
## Introduction to the Build a Voting System
```

2024-12-09 14:39 UTC, Dario-DC commented on curriculum/challenges/_meta/lab-voting-system/meta.json
> +  "name": "Build a Voting System Using Maps and Sets",
```suggestion
  "name": "Build a Voting System",
```

2024-12-09 14:39 UTC, Dario-DC commented on curriculum/challenges/_meta/lab-voting-system/meta.json
> +  "challengeOrder": [{ "id": "673b567e3ba535dda140d278", "title": "Build a Voting System Using Maps and Sets" }],
```suggestion
  "challengeOrder": [{ "id": "673b567e3ba535dda140d278", "title": "Build a Voting System" }],
```

2024-12-09 14:39 UTC, Dario-DC commented on curriculum/challenges/english/25-front-end-development/lab-voting-system/673b567e3ba535dda140d278.md
> +title: Build a Voting System Using Maps and Sets
```suggestion
title: Build a Voting System
```

2024-12-09 20:30 UTC, Dario-DC approved these changes

2024-12-10 00:50 UTC, moT01 approved these changes
LGTM 🎉

2024-12-10 00:50 UTC, merged

2024-12-11 21:34 UTC, mitaaios commented
I know u don’t care but it was a person from ca I’m just quit man Sent from my iPhoneOn Dec 9, 2024, at 7:00 PM, Tom ***@***.***> wrote:﻿
Merged #57208 into main.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-12-11 21:34 UTC, mitaaios commented
213 to now I was right Sent from my iPhoneOn Dec 9, 2024, at 7:00 PM, Tom ***@***.***> wrote:﻿
Merged #57208 into main.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-12-11 21:35 UTC, mitaaios commented
Was it anyone u know Sent from my iPhoneOn Dec 9, 2024, at 7:00 PM, Tom ***@***.***> wrote:﻿
Merged #57208 into main.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>