chore(curriculum): update tests lab product page
freeCodeCamp/freeCodeCamp pull request #57225
Opened 2024-11-19 01:07 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I've cleaned up the assertion methods in the lab product landing page.

2024-11-19 13:24 UTC, ilenia-magoni requested changes

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.isAbove(els.length,0);
```suggestion
assert.isNotEmpty(els);
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +  }
```suggestion
  assert.exists(document.getElementById(linkDestination));
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.isAbove(els.length,0);
```suggestion
assert.isNotEmpty(els); 
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.oneOf(el.tagNam, ['VIDEO','IFRAME']);
```suggestion
assert.oneOf(el.tagName, ['VIDEO','IFRAME']);
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.strictEqual(el.tagName,"FORM");
```suggestion
assert.strictEqual(el.tagName, "FORM"); 
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.strictEqual(el.tagName,"INPUT");
```suggestion
assert.strictEqual(el.tagName, "INPUT"); 
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.isAbove(els.length,0);
```suggestion
assert.isNotEmpty(els);
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.strictEqual(el.type,"email");
```suggestion
assert.strictEqual(el.type, "email");
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.strictEqual(el.tagName,"INPUT");
```suggestion
assert.strictEqual(el.tagName, "INPUT");
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.isAbove(els.length,0);
```suggestion
assert.isNotEmpty(els);
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.strictEqual(el.type,'submit');
```suggestion
assert.strictEqual(el.type, 'submit');
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.strictEqual(el.action,'https://www.freecodecamp.org/email-submit');
```suggestion
assert.strictEqual(el.action, 'https://www.freecodecamp.org/email-submit');
```

2024-11-19 13:24 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.strictEqual(el.name,'email');
```suggestion
assert.strictEqual(el.name, 'email');
```

2024-11-19 15:34 UTC, a2937 commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.notEmpty(el.getAttribute('src'));
I don't understand why the tests didn't fail. I mean yes, I did something wrong. But I have a tendency to count on tests to tell me when I make typos like that. 

![image](https://github.com/user-attachments/assets/b262962d-bc4c-46a0-96ec-254365720603)

2024-11-19 16:14 UTC, ilenia-magoni approved these changes

2024-11-19 16:28 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lab-product-landing-page/587d78af367417b2b2512b04.md
> +assert.isTrue(usesFlex || usesFlexMedia);
```suggestion
assert.exists(usesFlex || usesFlexMedia);
```

With `isTrue` it's failing as `find` returns the found element or `undefined`, so here something like `isDefined` or `exists` would work better than `isTrue`

2024-11-21 05:32 UTC, moT01 approved these changes

2024-11-21 05:32 UTC, merged