chore(ui): add bluesky button
freeCodeCamp/freeCodeCamp pull request #57297
Opened 2024-11-22 18:47 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #54572 

I had to update fontAwesome to support BlueSky. 

I'm not sure where `ShareTemplateWrapperTestID` is used and have only tested if the content loads. I will be double-checking both if the buttons display correctly and the new button can be used to share on BlueSky later today.

2024-11-22 23:32 UTC, a2937 commented
![Share cert](https://github.com/user-attachments/assets/41dee32e-2179-438c-9458-2c207203049e)


This looks pretty well. I haven't made a test message yet, but I believe it will work if I read the docs right.

https://docs.bsky.app/docs/advanced-guides/intent-links#compose-post

2024-11-23 09:36 UTC, ilenia-magoni commented
Will you also add Instagram and Linkedin?

2024-11-23 23:34 UTC, a2937 commented
Wait.  I don't actually know how to add LinkedIn buttons for clearing a challenge; nor how they're supposed to appear on the profile page.

2024-11-25 17:45 UTC, a2937 commented
I've made a Share on Instagram button for the lower jaw when a challenge is completed. Hopefully it works well.

2024-12-13 22:15 UTC, naomi-lgbt requested changes

2024-12-13 22:15 UTC, naomi-lgbt commented on client/i18n/locales/english/translations.json
> +    "share-on-insta": "Share on Threads"
```suggestion
    "share-on-threads": "Share on Threads"
```

This'll take more changes than just this line, but we shouldn't refer to Threads as Insta(gram) anywhere in the code, or that'll just make a mess when we get to the point where we *want* to include Instagram links.

2024-12-16 13:20 UTC, ilenia-magoni commented
there are merge conflicts

2024-12-18 23:09 UTC, naomi-lgbt approved these changes

2024-12-19 11:37 UTC, Sembauke approved these changes

2024-12-19 11:37 UTC, merged