feat: add donation animation ab test
freeCodeCamp/freeCodeCamp pull request #57345
Opened 2024-11-27 09:44 UTC by ahmaxed

This pr tests this version of the donation animation.

![Nov-26-2024 16-14-34](https://github.com/user-attachments/assets/ec165fb4-ead1-4ef3-ae42-d0b2c9a595ea)

I will be implementing the feedback from the initial review in an upcoming pr.

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-11-27 11:24 UTC, ahmaxed commented on client/src/components/Donation/donation-modal-body.tsx
> +                {t('donate.remove-distruptions')}
```suggestion
                {t('donate.remove-interruptions')}
```

2024-11-27 15:51 UTC, ojeytonwilliams requested changes

2024-11-27 15:51 UTC, ojeytonwilliams commented on client/src/components/Donation/donation-modal-body.tsx
> +  console.log(newBearAnimation);
```suggestion
```

2024-11-27 16:08 UTC, ojeytonwilliams approved these changes
I should have approved, the log doesn't matter. So... :+1:

2024-12-02 09:32 UTC, Sembauke approved these changes

2024-12-02 09:33 UTC, merged