chore(curriculum): update step 12 and 13 music player tests
freeCodeCamp/freeCodeCamp pull request #57361
Opened 2024-11-28 20:01 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #57359

This is a bit antithetical of my goal to removing the `before-user-code` but I can't think of a way around it using what's available in the challenge right now. 

See #57107 for more info about the `before-user-code`.

2024-12-02 10:29 UTC, ilenia-magoni commented
You don't need all that. The `console.log` is inside a function so you can in a single test:
```js
const temp = console.log
console.log = /* function that saves the output */
printGreeting();
console.log = temp
assert... /* check the saved output */
```

what you wrote may be needed if the console.log is in the global scope, it's not needed for these steps tho

2024-12-02 10:30 UTC, ilenia-magoni requested changes
please simplify

2024-12-02 13:33 UTC, a2937 commented
The goal of the two tests was to make sure that `printGreeting` was called in the global scope. I may need to reword the hint text but it was very much intended. 

My logic was that if the function is called in the global scope (that is outside and beloe the function) , it will output to the console and prove the camper did things correctly.

2024-12-02 15:19 UTC, ilenia-magoni commented
it is to check if the function is being called... there should be really a different way

2024-12-02 16:34 UTC, a2937 commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/660aea8782242e8f4bcc42d8.md
> +(function() { return logOutput || "console.log never called"; })();
The functions aren't doing anything. I'm removing them.

2024-12-02 17:07 UTC, ilenia-magoni commented
if you want to check if the function is being called you can replace the function itself instead of console.log and have it flip a variable from false to true but because is in the global scope you still need to do it in --before-user-code--
now I wonder, the code is available as a string in the `code` variable, could that be used to execute the code in a test?

2024-12-04 18:01 UTC, a2937 commented
> if you want to check if the function is being called you can replace the function itself

I actually can't do that. The variable used to hold the `printGreeting` function is a constant.

2024-12-04 18:25 UTC, ilenia-magoni commented
That's inconvienient... that remains using the `code` variable I guess

2024-12-04 18:40 UTC, a2937 commented
I'd rather double check that the index of the function call is greater than the index of the function itself than arbitrarily run code inside of a test case.

2024-12-05 14:25 UTC, ilenia-magoni approved these changes

2024-12-13 21:57 UTC, naomi-lgbt requested changes

2024-12-13 21:57 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-basic-string-and-array-methods-by-building-a-music-player/660ae8ad1475698da3c3c37d.md
> +var logOutput = "";
I get that this is "invisible" behind the scenes code, and that it gets passed through Babel, but why are we using `var`?

2024-12-18 22:45 UTC, naomi-lgbt approved these changes

2024-12-18 22:45 UTC, merged