now the pane remebers if they were opened in previous step and remain…
freeCodeCamp/freeCodeCamp pull request #57368
Opened 2024-11-30 10:16 UTC by X1Vi

…s open or closed as per the previous setting

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #55619

Now panes remain open or close when we shift to the next step as per our previous preferences

2024-11-30 15:35 UTC, X1Vi commented
> Hey there,
> 
> Thanks for your interest in contributing. We appreciate your efforts, but this PR doesn't follow [our guidelines](https://contribute.freecodecamp.org/how-to-open-a-pull-request).
> 
> Do not worry, you should join our [Discord](https://discord.gg/KVUmVXA) server and ask for help in the `#contributors` channel. That will help other contributors guide you to get your PR ready for a review.
> 
> Happy Contributing!

fixed

2024-12-17 11:55 UTC, Sembauke requested changes
We should use `store` not `sessionStorage` to keep it consistent.

Maybe change the key to `challenge-pane-layout` to conform with stored `challenge-layout` that remembers the size of the panes. 

Maybe even combine them.

2024-12-27 12:02 UTC, X1Vi commented
> We should use `store` not `sessionStorage` to keep it consistent.
> 
> Maybe change the key to `challenge-pane-layout` to conform with stored `challenge-layout` that remembers the size of the panes.
> 
> Maybe even combine them.

Which one should I put the functionality in ? 
```
export default combineReducers({
  [appNameSpace]: app,
  [challengeNameSpace]: challenge,
  [curriculumMapNameSpace]: curriculumMap,
  [flashNameSpace]: flash,
  [searchNameSpace]: search,
  [settingsNameSpace]: settings
});

```

2025-01-02 12:32 UTC, Sembauke commented
Sorry I don't understand what you are refering to.

2025-01-05 11:12 UTC, X1Vi commented
> Sorry I don't understand what you are refering to.

Where do I store the state of then panes in store ? There are bunch of reducers ?

2025-01-05 17:38 UTC, Sembauke commented
`store` is a package we use to get, set and remove variables from local storage. 

There is a pretty good example in `client/src/templates/Challenges/classic/show.tsx`

2025-01-06 09:01 UTC, X1Vi commented
> `store` is a package we use to get, set and remove variables from local storage.
> 
> There is a pretty good example in `client/src/templates/Challenges/classic/show.tsx`

I think it is done

2025-01-09 22:21 UTC, moT01 reviewed
Looking good @X1Vi 🎉 I left a few comments on some things I think could maybe be a little better. Let me know if you want to discuss any of it.

2025-01-09 22:21 UTC, moT01 commented on client/src/templates/Challenges/classic/desktop-layout.tsx
> +  /* eslint-disable react-hooks/exhaustive-deps */
These comments seem a little inconsistent. I don't think we need them on the effect above this one, but we do on the one below.

2025-01-09 22:21 UTC, moT01 commented on client/src/templates/Challenges/classic/desktop-layout.tsx
> +      const parsedState: Record<string, boolean> = JSON.parse(
Not sure what it wouldn't be JSON, but if JSON.parse fails here, I get a runtime error. We should probably handle that. Same with the json.parse below.

2025-01-09 22:21 UTC, moT01 commented on client/src/templates/Challenges/classic/desktop-layout.tsx
> +    const savedState: string = store.get('layoutPaneBooleans') as string;
Do we need to cast it and give it a type?

2025-01-10 09:37 UTC, X1Vi commented on client/src/templates/Challenges/classic/desktop-layout.tsx
> +    const savedState: string = store.get('layoutPaneBooleans') as string;
if you are talking bout `store.get('layoutPaneBooleans') as string` then yes I think

2025-01-10 09:37 UTC, X1Vi commented on client/src/templates/Challenges/classic/desktop-layout.tsx
> +  /* eslint-disable react-hooks/exhaustive-deps */
In the new commit I think I have remove all the unnecessary ones I think but I think you should review it once more if you want

2025-01-10 09:38 UTC, X1Vi commented on client/src/templates/Challenges/classic/desktop-layout.tsx
> +      const parsedState: Record<string, boolean> = JSON.parse(
I have added try catch blocks now if there is anything more you need me to do then do ping me

2025-01-10 09:38 UTC, X1Vi commented on client/src/templates/Challenges/classic/desktop-layout.tsx
> +    const savedState: string = store.get('layoutPaneBooleans') as string;
if you are talking about this `store.get('layoutPaneBooleans') as string` then probably yeah

2025-01-10 18:29 UTC, moT01 approved these changes
LGTM @X1Vi 🎉

2025-01-10 19:08 UTC, houssam-12bboo reviewed
Y

2025-01-10 20:48 UTC, houssam-12bboo reviewed
F

2025-01-11 09:39 UTC, ilenia-magoni commented
@houssam-12bboo it's great you want to help reviewing the PRs, but please be aware that your positive review has no effect on the PR and only cause noise. If you have constructive criticism instead you could point out what need to be bettered in a PR.

2025-01-14 07:42 UTC, Sembauke approved these changes

2025-01-14 07:42 UTC, merged