fix(api): only query for potentially valid tokens
freeCodeCamp/freeCodeCamp pull request #57383
Opened 2024-12-02 10:56 UTC by ojeytonwilliams

If the token id is not an objectID there cannot be a corresponding token.

Ref: https://freecodecamp.sentry.io/issues/6093481611/?project=4508182869508096&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=0

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

2024-12-02 13:54 UTC, ShaunSHamilton requested changes
I prefer this:

2024-12-02 13:54 UTC, ShaunSHamilton commented on api/src/exam-environment/routes/exam-environment.ts
> +    : null;
```suggestion
  if (!isObjectID(payload.examEnvironmentAuthorizationToken)) {
    void reply.code(418);
    return reply.send(
      ERRORS.FCC_EINVAL_EXAM_ENVIRONMENT_AUTHORIZATION_TOKEN(JSON.stringify(e))
    );
  }
```

2024-12-02 13:54 UTC, ShaunSHamilton commented on api/src/exam-environment/routes/exam-environment.ts
> +    : null;
```suggestion
  const token = await this.prisma.examEnvironmentAuthorizationToken.findUnique({
    where: {
      id: payload.examEnvironmentAuthorizationToken
    }
  });
```

2024-12-02 19:40 UTC, ShaunSHamilton approved these changes
LGTM

2024-12-06 19:06 UTC, moT01 approved these changes

2024-12-06 19:06 UTC, merged