Chore(curriculum)/add temp lab challenge type
freeCodeCamp/freeCodeCamp pull request #57441
Opened 2024-12-07 15:58 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Related to #57436

I think I chose the right template for the lab challenges like "Build an Availability Table". I think everything is working. I have multiple files in the editor and no save button.

2024-12-07 19:09 UTC, ilenia-magoni commented
There is a ValidationError from a test that needs to be adjusted for this to work

2024-12-08 02:31 UTC, a2937 commented
Thank you for pointing that out. Additionally I did not mean to request the mobile team but it just sort of happened.

2024-12-08 12:28 UTC, ilenia-magoni commented
the mobile team being requested depends on which files you change

2024-12-09 10:28 UTC, ojeytonwilliams requested changes
Thanks for jumping on this so quickly, Anna. The functionality is good, I just have some nitpicks:

2024-12-09 10:28 UTC, ojeytonwilliams commented on shared/config/challenge-types.ts
> +const frontEndCertLabWithSeed = 25;
```suggestion
const lab = 25;
```

2024-12-09 10:28 UTC, ojeytonwilliams commented on shared/config/challenge-types.ts
> +  frontEndCertLabWithSeed
```suggestion
  lab
```

2024-12-09 10:28 UTC, ojeytonwilliams commented on shared/config/challenge-types.ts
> +  [frontEndCertLabWithSeed]: 'classic'
```suggestion
  [lab]: 'classic'
```

2024-12-09 10:28 UTC, ojeytonwilliams commented on shared/config/challenge-types.ts
> +  [frontEndCertLabWithSeed]: 'tests'
```suggestion
  [lab]: 'tests'
```

2024-12-09 10:28 UTC, ojeytonwilliams commented on client/src/templates/Challenges/classic/desktop-layout.tsx
>    const isMultifileCertProject =
```suggestion
  const isMultifileProject =
```
Bit of a nitpick, but since labs are not certification projects, I think this should reflect that.

2024-12-09 14:06 UTC, ojeytonwilliams approved these changes
Thanks Anna :+1: I cleared up the lint issue and I think it's good to go.

2024-12-12 07:40 UTC, Sembauke approved these changes

2024-12-12 07:40 UTC, merged