fix(curriculum): test for values step 25 spreadsheet instructions
freeCodeCamp/freeCodeCamp pull request #57477
Opened 2024-12-10 19:39 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #55708

I decided to test the return values of step 25's spreadsheet rather than go off of how it was implemented. This provides cleaner tests and more allowed solutions.

2024-12-13 20:07 UTC, naomi-lgbt requested changes

2024-12-14 00:13 UTC, naomi-lgbt requested changes

2024-12-14 00:13 UTC, naomi-lgbt commented on curriculum/challenges/english/15-javascript-algorithms-and-data-structures-22/learn-functional-programming-by-building-a-spreadsheet/64496d80bc174a158c973080.md
> +You should use return a value from the function.
```suggestion
You should return a value from the `median` function. 
```

2024-12-14 00:16 UTC, naomi-lgbt approved these changes

2024-12-14 12:47 UTC, Sembauke approved these changes

2024-12-14 12:47 UTC, merged