fix: do not check for browser extension in mobile app
freeCodeCamp/freeCodeCamp pull request #57470
Opened 2024-12-10 08:23 UTC by Sembauke

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-12-10 10:57 UTC, ojeytonwilliams requested changes
There's also curriculum/challenges/english/25-front-end-development/workshop-cat-photo-app/5dc174fcf86c76b9248c6eb2.md, i.e. the FSD version of this file.

2024-12-10 10:57 UTC, ojeytonwilliams commented on curriculum/challenges/english/14-responsive-web-design-22/learn-html-by-building-a-cat-photo-app/5dc174fcf86c76b9248c6eb2.md
> +}
```suggestion
}
```
I don't think `assert(true)` does anything.

2024-12-10 11:38 UTC, Sembauke commented
Well in the mobile app we handle testing challenges differently so the number of script/style tags are different.

2024-12-10 12:08 UTC, a2937 commented
> Also, why does the mobile app have this issue? Thing is, this feels like it shouldn't be necessary, even though I can see how it can work.

My theory (that I can't prove yet) was that there was no inherited stylesheet in the mobile app. The mobile app is using a DOM parser and I don't see it inventing a new stylesheet.

2024-12-12 09:11 UTC, ojeytonwilliams approved these changes
Ideally, the mobile and Web apps should test the same way, but until we address that, I think this will do.

2024-12-12 09:12 UTC, ilenia-magoni approved these changes

2024-12-12 09:12 UTC, merged