chore: update css lectures intros
freeCodeCamp/freeCodeCamp pull request #57544
Opened 2024-12-16 14:06 UTC by Ksound22

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-12-16 14:43 UTC, Dario-DC commented
Hey @Ksound22 you have the changes from your previous PR in this one too.

2024-12-16 15:11 UTC, Ksound22 commented
> Hey @Ksound22 you have the changes from your previous PR in this one too.

Should be fine now

2024-12-17 13:46 UTC, ojeytonwilliams requested changes

2024-12-17 13:46 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +          "In these lecture videos, you will learn about best practices necessary in designing user-facing features like dark mode, breadcrumbs, modal dialogs, and much more. You will also learn how
```suggestion
          "In these lecture videos, you will learn about best practices for designing user-facing features like dark mode, breadcrumbs, modal dialogs, and much more. You will also learn how to conduct user research, user requirements and testing."
```
"necessary" implies you can't design without them, but you can. The design will likely be bad, but you can do that.

2024-12-17 13:46 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +          "In these lecture videos, you will learn how to use CSS positioning and floats. You will learn how to use <code>absolute</code>, <code>relative</code>, <code>fixed</code>, and <code>sticky<
```suggestion
          "In these lecture videos, you will learn how to use CSS positioning and floats. You will learn about <code>absolute</code>, <code>relative</code>, <code>fixed</code>, and <code>sticky</code> positioning. You will also use the <code>z-index</code> property."
```
Too much repetition made it feel clumsy.

2024-12-17 13:46 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +          "In these lecture videos, you will learn how to define and use custom properties, or CSS variables. You will also learn about the <code>@property</code> rule and how it works."
```suggestion
          "In these lecture videos, you will learn how to define and use custom properties (also known as CSS variables). You will also learn about the <code>@property</code> rule and how it works."
```
This makes it clear that CSS variables and custom properties are one and the same.

2024-12-18 18:48 UTC, naomi-lgbt requested changes

2024-12-18 21:48 UTC, ojeytonwilliams approved these changes
LGTM 👍

2024-12-19 21:24 UTC, naomi-lgbt approved these changes

2024-12-19 21:24 UTC, merged