chore: update lab intros
freeCodeCamp/freeCodeCamp pull request #57569
Opened 2024-12-17 15:41 UTC by zairahira

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

This PR updates the lab intros in `intro.json`.

Closes #XXXXX

2024-12-17 16:36 UTC, ojeytonwilliams requested changes
I saw a couple of minor things. 

Also, I think we should be consistent about contractions and commas in lists. For example, we use both "You'll" and "You will". Also, I _believe_ it's standard in US English to write lists like this "stuff, whatsits, and more", rather than "stuff, whatsits and more".

2024-12-17 16:36 UTC, ojeytonwilliams commented on client/i18n/locales/english/intro.json
> +          "In this lab, you will create a mood board using React props.",
```suggestion
          "In this lab, you will create a mood board using React.",
```
I think it's enough to mention props in the next step.

2024-12-18 08:27 UTC, naomi-lgbt commented
> Also, I believe it's standard in US English to write lists like this "stuff, whatsits, and more", rather than "stuff, whatsits and more".

This is called the Oxford Comma, and it's been a point of contention for many of our linguists for quite some time.

2024-12-18 08:37 UTC, zairahira commented
Thanks for sharing the feedback Oliver.
For consistency, I'll make the following changes in the next commit:

- Change You will -> You'll
- Use the Oxford comma("stuff, whatsits, and more").

2024-12-18 09:17 UTC, ojeytonwilliams commented
> > Also, I believe it's standard in US English to write lists like this "stuff, whatsits, and more", rather than "stuff, whatsits and more".
> 
> This is called the Oxford Comma, and it's been a point of contention for many of our linguists for quite some time.

Yeah, I was vaguely aware that there was some light controversy. A bit of googling suggests it's common in US English, though.

2024-12-18 16:02 UTC, ojeytonwilliams approved these changes
LGTM :+1: Thanks, Zaira!

2024-12-18 17:13 UTC, moT01 approved these changes
Lets go with it. 

I usually prefer the oxford comma - depends on the context though.
I also usually prefer not to use contractions - I think it sounds more professional.
But I'm fine with this for now 👍

2024-12-18 17:13 UTC, merged

2024-12-18 17:29 UTC, ojeytonwilliams commented
@moT01 sure, that makes sense.  Can we update the contribution site with a style guide? If the curriculum team broadly agrees, that is.