fix: trim whitespace from a string multiple choice question
freeCodeCamp/freeCodeCamp pull request #57560
Opened 2024-12-17 11:34 UTC by scissorsneedfoodtoo

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

This PR adjusts the spacing for one of the distractors and the correct answer for q3.

2024-12-17 13:54 UTC, Sembauke approved these changes

2024-12-17 14:06 UTC, ilenia-magoni requested changes
![image](https://github.com/user-attachments/assets/a707eb97-e237-459b-b262-8999309c9390)
You will need to use codeblocks, with the in-line code multiple spaces collapse to one

2024-12-17 14:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lecture-working-with-common-string-methods/67326c3c3ab931c644cea05b.md
> +`"   Code"`
````suggestion
```js
"   Code"
```
````

2024-12-17 14:11 UTC, ilenia-magoni commented on curriculum/challenges/english/25-front-end-development/lecture-working-with-common-string-methods/67326c3c3ab931c644cea05b.md
> +`"Code   "`
````suggestion
```js
"Code   "
```
````

2024-12-17 14:12 UTC, ilenia-magoni approved these changes

2024-12-17 14:35 UTC, merged

2024-12-21 06:37 UTC, scissorsneedfoodtoo commented
Sorry, just seeing this now. Thanks for catching that and for the fix, @ilenia-magoni!