fix: change Drum Machine based on @moT01review
freeCodeCamp/freeCodeCamp pull request #57627
Opened 2024-12-19 20:34 UTC by ilenia-magoni

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

hey @mot01 :eyes:

2024-12-19 23:28 UTC, moT01 approved these changes
LGTM 🎉

2024-12-20 00:54 UTC, naomi-lgbt requested changes

2024-12-20 00:54 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-drum-machine/6762ec275cef87635acc4fe3.md
> +3. In `id` the `#drum-machine` element you should have a `p` element with an `id` of `display`.
```suggestion
3. Inside the `#drum-machine` element you should have a `p` element with an `id` of `display`.
```

2024-12-20 00:54 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-drum-machine/6762ec275cef87635acc4fe3.md
> +Some audio samples you can use for your drum machine can be found at `https://cdn.freecodecamp.org/curriculum/drum/fileName`, where `fileName` is as follow:
```suggestion
Some audio samples you can use for your drum machine can be found at `https://cdn.freecodecamp.org/curriculum/drum/<fileName>`, where `<fileName>` is as follows:
```

2024-12-20 00:54 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-drum-machine/6762ec275cef87635acc4fe3.md
> +In `id` the `#drum-machine` element you should have another `div` with an `id` of `pad-bank`.
```suggestion
Inside the `#drum-machine` element you should have another `div` with an `id` of `pad-bank`.
```

2024-12-20 07:36 UTC, fhsinchy approved these changes

2024-12-20 19:08 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-drum-machine/6762ec275cef87635acc4fe3.md
> +1. You should have a `div` element with an  `id`  of `drum-machine` that contains all other elements.
```suggestion
1. You should have a `div` element with an `id` of `drum-machine` that contains all other elements.
```

2024-12-20 19:08 UTC, naomi-lgbt approved these changes

2024-12-20 19:35 UTC, merged