chore: auditing worshops, reviews, and quizzes intros
freeCodeCamp/freeCodeCamp pull request #57633
Opened 2024-12-20 09:53 UTC by Ksound22

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-12-22 18:41 UTC, moT01 requested changes

2024-12-22 18:41 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +          "In this quix, you will test what you've learned on how to style forms."
```suggestion
          "In this quiz, you will test what you've learned on how to style forms."
```

2024-12-22 18:41 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on CSS flexbox with this quiz of using."
```suggestion
          "Test what you've learned on CSS flexbox with this quiz."
```

2024-12-22 18:41 UTC, moT01 commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what you've learned on bash scripting in this quiz on."]
```suggestion
        "intro": ["Test what you've learned on bash scripting in this quiz."]
```

2024-12-23 07:04 UTC, zairahira reviewed
For consistency, wherever we are referring to plurals, `"about it"` should be replaced with `"about them."` 

For example:  
- **Correct:** `"Before you are quizzed on CSS Flexbox concepts, you first need to review what you've learned about it."`  
   *Reason:* The subject, "CSS Flexbox concepts," is treated as a singular idea here.  

- **Needs Correction:** `"Before you are quizzed on CSS and accessibility, you first need to review what you've learned on it."`  
   *Suggested Change:* `"Before you are quizzed on CSS and accessibility, you first need to review what you've learned about them."`  
   *Reason:* "CSS and accessibility" refers to two distinct items, so "about them" is grammatically accurate.

2024-12-23 09:47 UTC, zairahira approved these changes

2024-12-23 10:55 UTC, Ksound22 commented on client/i18n/locales/english/intro.json
>          ]
I can't understand why it's causing it, I have more like this.

What do I do to fix it?

2024-12-23 10:58 UTC, ilenia-magoni commented on client/i18n/locales/english/intro.json
>          ]
make it all in one line like in the code in Kris's post

2024-12-23 13:22 UTC, scissorsneedfoodtoo reviewed
Hey @Ksound22, thanks for going through this file and updating all of these strings.

Sorry about the wave of suggestions here, but I tried to simplify most of the intro sentences so we don't need to worry about singular or plural wording. I also tried to normalize the quiz intros as well.

Most of these aren't required, so feel free to disregard anything, or to update the wording.

Also, if you accept some suggestions, you may need to go into the `intro.json` file and run Prettier (or save the file if you've got Prettier as an extension) so that the linter won't complain about the spacing.

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on JavaScript Dates with this quiz."
```suggestion
          "Test what you've learned about JavaScript Dates with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on JavaScript Audio and Video learned with this quiz."
```suggestion
          "Test what you've learned about JavaScript audio and video with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "In this workshop, you will practice maps and sets by building a plant nursery catalog."
```suggestion
          "In this workshop, you will practice using Maps and Sets by building a plant nursery catalog."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on JavaScript Maps and Sets with this quiz."
```suggestion
          "Test what you've learned about JavaScript Maps and Sets with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on local storage and CRUD with this quiz."
```suggestion
          "Test what you've learned about local storage and CRUD with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Before you are quizzed on how to work with classes, you first need to review what you've learned about them.",
```suggestion
          "Before you're quizzed on how to work with classes, you should review what you've learned about them.",
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on JavaScript Classes with this quiz."
```suggestion
          "Test what you've learned about JavaScript Classes with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what your knowledge on Recursion with this quiz."]
```suggestion
        "intro": ["Test your knowledge of Recursion with this quiz."]
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on JavaScript functional programming with this quiz."
```suggestion
          "Test what you've learned about JavaScript functional programming with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on asynchronous JavaScript with this quiz."
```suggestion
          "Test what you've learned about asynchronous JavaScript with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test your knowledge on React basics with this quiz."]
```suggestion
        "intro": ["Test your knowledge of React basics with this quiz."]
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on React State and Hooks with this quiz."
```suggestion
          "Test what you've learned about React State and Hooks with this quiz."
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what you've learned on Advanced React with this quiz."]
```suggestion
        "intro": ["Test what you've learned about Advanced React with this quiz."]
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what you've learned on Web Performance with this quiz."]
```suggestion
        "intro": ["Test what you've learned about Web Performance with this quiz."]
```

2024-12-23 13:22 UTC, scissorsneedfoodtoo commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned on CSS Libraries and Frameworks with this quiz."
```suggestion
          "Test what you've learned about CSS Libraries and Frameworks with this quiz."
```

2024-12-23 14:11 UTC, Ksound22 commented
> Hey @Ksound22, thanks for going through this file and updating all of these strings.
> 
> Sorry about the wave of suggestions here, but I tried to simplify most of the intro sentences so we don't need to worry about singular or plural wording. I also tried to normalize the quiz intros as well.
> 
> Most of these aren't required, so feel free to disregard anything, or to update the wording.
> 
> Also, if you accept some suggestions, you may need to go into the `intro.json` file and run Prettier (or save the file if you've got Prettier as an extension) so that the linter won't complain about the spacing.

They're all appreciated, Kris. Thank you.

2024-12-23 15:28 UTC, naomi-lgbt requested changes

2024-12-23 15:28 UTC, naomi-lgbt commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test your knowledge of Recursion with this quiz."]
```suggestion
        "intro": ["Test your knowledge of recursion with this quiz."]
```

2024-12-23 15:28 UTC, naomi-lgbt commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what you've learned about Advanced React with this quiz."]
```suggestion
        "intro": ["Test what you've learned about advanced React with this quiz."]
```

2024-12-23 15:28 UTC, naomi-lgbt commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what you've learned about Web Performance with this quiz."]
```suggestion
        "intro": ["Test what you've learned about web performance with this quiz."]
```

2024-12-23 15:28 UTC, naomi-lgbt commented on client/i18n/locales/english/intro.json
> +          "Test what you've learned about CSS Libraries and Frameworks with this quiz."
```suggestion
          "Test what you've learned about CSS libraries and frameworks with this quiz."
```

2024-12-23 15:28 UTC, naomi-lgbt commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what you've learned on Typescript with this quiz."]
```suggestion
        "intro": ["Test what you've learned on TypeScript with this quiz."]
```

It *is* capitalised like this.

2024-12-23 15:28 UTC, naomi-lgbt commented on client/i18n/locales/english/intro.json
> +        "intro": ["Test what you've learned bash commands with this quiz."]
```suggestion
        "intro": ["Test what you've learned on bash commands with this quiz."]
```

2024-12-23 15:38 UTC, naomi-lgbt approved these changes

2024-12-23 15:43 UTC, moT01 approved these changes

2024-12-23 16:39 UTC, merged