fix(curriculum): improve Bookmark Manager tests
freeCodeCamp/freeCodeCamp pull request #57636
Opened 2024-12-20 14:22 UTC by gikf

Checklist:

- [x] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [x] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [x] My pull request targets the `main` branch of freeCodeCamp.
- [x] I have tested these changes either locally on my machine, or GitPod.

- - -
- Extends `getBookmarks()` tests with _invalid_ values in the local storage. This partially is to help with debugging. If camper, for whatever reason, will have at some point in the `'bookmarks'` key of local storage, something that cannot be parsed with `JSON.parse`, the error will be thrown and three tests will fail:
  > Your getBookmarks function should return an array.

  > When you click #add-bookmark-button-form, you should reset the value of #name and #url to an empty string.

  > When you click #add-bookmark-button-form, you should run displayOrCloseForm to hide the form section and show the main section.

  As they don't have the local storage setup, these tests could be modified to pass (they still can). However at the same time, in local tests, camper will get in every manual test that's using directly or indirectly the `getBookmarks`, `JSON.parse` error thrown. Which will not that obvious to pinpoint, as code setting `bookmarks` key with invalid value might not be anymore in the campers' code.

- Adds test for the `name` attribute of the radio inputs. Otherwise multiple inputs can be selected.
- Adds test for clearing of the previous category info, when opening another category. Currently relevant tests:
  > When you click #view-category-button, you should add a p element with the text No Bookmarks Found to #category-list's inner HTML if none of the bookmarks in local storage have the selected category.

  > When you click #view-category-button, you should modify #category-list's inner HTML by adding a radio button having the id and value attributes set to the bookmark name for each bookmark in the selected category.

  Are not checking such case. There was different test, that was failing as a side-effect, but new test more clearly directs to the problem.

- Adds test for bookmark deletion from the correct category, when bookmarks in different categories have the same name.
- Updates the solution for these tests.

2024-12-23 09:08 UTC, Dario-DC reviewed
Left a couple of suggestions. Other than that it looks good to me :+1:

2024-12-23 17:59 UTC, Dario-DC approved these changes
LGTM :tada:

2024-12-25 20:31 UTC, naomi-lgbt requested changes
Copy changes.

2024-12-25 20:31 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
> +1. When you click `#delete-bookmark-button`, you should delete the bookmark corresponding to the selected radio button and appropriate category from the local storage and update the displayed bookmar
```suggestion
1. When you click the `#delete-bookmark-button`, you should delete the bookmark corresponding to the selected radio button and appropriate category from the local storage and update the displayed bookmark list.
```

2024-12-25 20:31 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
> +When you click `#view-category-button`, you should modify `#category-list`'s inner HTML by adding a radio button having the `id` and `value` attributes set to the bookmark name for each bookmark in t
```suggestion
When you click the `#view-category-button`, you should modify the `#category-list` element's inner HTML by adding a radio button. The radio button should have the `id` and `value` attributes set to the bookmark name for each bookmark in the selected category. Additionally, each radio button should have the same `name` attribute.
```

2024-12-25 20:31 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
>  1. When you click `#close-list-button`, you should run your function to hide the `#bookmark-list-section` and display the main section.
```suggestion
 1. When you click the `#close-list-button`, you should run your function to hide the `#bookmark-list-section` and display the main section.
```

2024-12-25 20:31 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
> +When you click `#close-list-button` and then open again the same, or different category, the `#category-list` should contain only data relevant for selected category, without duplicating entries.
```suggestion
When you click the `#close-list-button` and then open any category, the `#category-list` should contain only data relevant for the selected category, without duplicating entries.
```

2024-12-25 20:31 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
> +When you click `#delete-bookmark-button`, you should delete the bookmark corresponding to the selected radio button and appropriate category from the local storage and update the displayed bookmark l
```suggestion
When you click the `#delete-bookmark-button`, you should delete the bookmark corresponding to the selected radio button and appropriate category from the local storage and update the displayed bookmark list.
```

2025-01-04 18:23 UTC, gikf commented on curriculum/challenges/english/25-front-end-development/lab-bookmark-manager-app/66def5467aee701733aaf8cc.md
>  1. When you click `#close-list-button`, you should run your function to hide the `#bookmark-list-section` and display the main section.
```suggestion
1. When you click the `#close-list-button`, you should run your function to hide the `#bookmark-list-section` and display the main section.
```

2025-01-07 03:24 UTC, naomi-lgbt approved these changes

2025-01-07 03:24 UTC, merged