fix tests
freeCodeCamp/freeCodeCamp pull request #57743
Opened 2024-12-24 15:39 UTC by ilenia-magoni

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-12-25 00:07 UTC, a2937 requested changes
This is pretty good but I think it can better. 

```html
 <img
          src=" "
          alt=" "
        />
```

This image element has an appropriate `src` attribute and an appropriate `alt` attribute according to the tests.

2024-12-25 20:05 UTC, naomi-lgbt approved these changes

2024-12-25 20:22 UTC, a2937 approved these changes

2024-12-25 20:22 UTC, merged

2025-01-04 10:40 UTC, ilenia-magoni commented
@a2937 can you open an issue for that? it was out of scope for this. or a PR? if you add `trim()` before checking if the values are not empty it would work

2025-01-04 16:52 UTC, a2937 commented
I made a PR for that last week.