fixed unreachable type error
freeCodeCamp/freeCodeCamp pull request #57762
Opened 2024-12-25 19:00 UTC by amrrashor

Checklist:

- [ ] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [ ] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [ ] My pull request targets the `main` branch of freeCodeCamp.
- [ ] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

2024-12-25 19:56 UTC, naomi-lgbt approved these changes
This shouldn't be producing any error at all, as it is definitely not unreachable code. 

Additionally, `ts-expect-error` is a last resort as it disables type checking entirely.

2024-12-25 20:34 UTC, jdwilkin4 commented
@amrrashor 

I linked the issue to this PR so it closes automatically when this is merged.

2024-12-25 20:34 UTC, jdwilkin4 approved these changes

2024-12-27 02:33 UTC, naomi-lgbt requested changes
Sorry, my approval on this was erroneous.

The code in question is not unreachable. Could you share how/where you saw that error message?

2025-01-03 10:15 UTC, ojeytonwilliams commented
Closing because there doesn't seem to be anything to fix.

2025-01-03 10:15 UTC, closed without merging