chore(curriculum): update asserts in legacy basic algorithm scripting
freeCodeCamp/freeCodeCamp pull request #57784
Opened 2024-12-27 00:35 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #XXXXX

I reorganized the tests in one of the files so that it detects if a value is a number before comparing it, and replaced the assertions with more specific ones.

2024-12-28 05:56 UTC, naomi-lgbt requested changes
One nit.

2024-12-28 05:56 UTC, naomi-lgbt commented on curriculum/challenges/english/02-javascript-algorithms-and-data-structures/basic-algorithm-scripting/convert-celsius-to-fahrenheit.md
> +  let fahrenheit = (celsius * 9) / 5 + 32;
I have never seen it written like this. It's either:

```suggestion
  let fahrenheit = celsius * (9 / 5) + 32;
```

or

```suggestion
  let fahrenheit = (celsius * 9 / 5) + 32;
```

2024-12-29 22:14 UTC, naomi-lgbt approved these changes

2025-01-04 12:09 UTC, ilenia-magoni approved these changes

2025-01-04 12:10 UTC, merged