fix(curriculum): allow variables in lab trivia bot
freeCodeCamp/freeCodeCamp pull request #57782
Opened 2024-12-26 16:20 UTC by a2937

Checklist:

- [X] I have read and followed the [contribution guidelines](https://contribute.freecodecamp.org).
- [X] I have read and followed the [how to open a pull request guide](https://contribute.freecodecamp.org/how-to-open-a-pull-request/).
- [X] My pull request targets the `main` branch of freeCodeCamp.
- [X] I have tested these changes either locally on my machine, or GitPod.

Closes #57755

I did my best to make this optional. I also added an `isNotEmpty` assertion to try to make sure valid JavaScript is involved. I can remove the added assertions if we want.

2024-12-28 06:11 UTC, naomi-lgbt requested changes

2024-12-28 06:11 UTC, naomi-lgbt commented on curriculum/challenges/english/25-front-end-development/lab-javascript-trivia-bot/66ed41f912d0bb1dc62da5dd.md
>  assert.exists(first);
```suggestion
assert.match(code, /let\s+codingFact/)
```

Really this test only needs to look at the declaration.

2024-12-29 22:21 UTC, naomi-lgbt approved these changes

2025-01-02 08:49 UTC, Sembauke approved these changes

2025-01-02 08:49 UTC, merged